{
  "abstract": [
    {
      "text": "The preferred initial scene session role for your app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationPreferredDefaultSceneSessionRole"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.UIApplicationPreferredDefaultSceneSessionRole",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIApplicationPreferredDefaultSceneSessionRole"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "UIApplicationPreferredDefaultSceneSessionRole"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "UIApplicationPreferredDefaultSceneSessionRole",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "string"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "kind": "possibleValues",
      "title": "Possible Values",
      "values": [
        {
          "content": [],
          "name": "UIWindowSceneSessionRoleApplication"
        },
        {
          "content": [],
          "name": "UIWindowSceneSessionRoleVolumetricApplication"
        },
        {
          "content": [],
          "name": "UISceneSessionRoleImmersiveSpaceApplication"
        },
        {
          "content": [],
          "name": "CPSceneSessionRoleImmersiveSpaceApplication"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system references this key to determine the preferred initial scene session role to create the first scene for your app. If you specify ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/UISceneSessionRoleImmersiveSpaceApplication",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPSceneSessionRoleImmersiveSpaceApplication",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", the system creates an immersive space scene which connects to your application at launch. To define the style that ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/UISceneSessionRoleImmersiveSpaceApplication",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " uses initially, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/UISceneSessionRoleImmersiveSpaceApplication/UISceneInitialImmersionStyle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSUIElement": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app is an agent app that runs in the background and doesn’t appear in the Dock.",
          "type": "text"
        }
      ],
      "ideTitle": "Application is agent (UIElement)",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSUIElement",
      "kind": "symbol",
      "name": "LSUIElement",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSUIElement"
        }
      ],
      "role": "symbol",
      "title": "LSUIElement",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsuielement"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSMainNibFile": {
      "abstract": [
        {
          "text": "The name of an app’s main user interface file.",
          "type": "text"
        }
      ],
      "ideTitle": "Main nib file base name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSMainNibFile",
      "kind": "symbol",
      "name": "NSMainNibFile",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMainNibFile"
        }
      ],
      "role": "symbol",
      "title": "NSMainNibFile",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsmainnibfile"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSMainStoryboardFile": {
      "abstract": [
        {
          "text": "The name of an app’s storyboard resource file.",
          "type": "text"
        }
      ],
      "ideTitle": "Main storyboard file base name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSMainStoryboardFile",
      "kind": "symbol",
      "name": "NSMainStoryboardFile",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMainStoryboardFile"
        }
      ],
      "role": "symbol",
      "title": "NSMainStoryboardFile",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsmainstoryboardfile"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationPreferredDefaultSceneSessionRole": {
      "abstract": [
        {
          "text": "The preferred initial scene session role for your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationPreferredDefaultSceneSessionRole",
      "kind": "symbol",
      "name": "UIApplicationPreferredDefaultSceneSessionRole",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationPreferredDefaultSceneSessionRole"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationPreferredDefaultSceneSessionRole",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationpreferreddefaultscenesessionrole"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest": {
      "abstract": [
        {
          "text": "The information about the app’s scene-based life-cycle support.",
          "type": "text"
        }
      ],
      "ideTitle": "Application Scene Manifest",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest",
      "kind": "symbol",
      "name": "UIApplicationSceneManifest",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationSceneManifest"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationSceneManifest",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationscenemanifest"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPSceneSessionRoleImmersiveSpaceApplication": {
      "abstract": [
        {
          "text": "Configurations for scenes you use to display Compositor Services content in an immersive space.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPSceneSessionRoleImmersiveSpaceApplication",
      "kind": "symbol",
      "name": "CPSceneSessionRoleImmersiveSpaceApplication",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPSceneSessionRoleImmersiveSpaceApplication"
        }
      ],
      "role": "symbol",
      "title": "CPSceneSessionRoleImmersiveSpaceApplication",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationscenemanifest/uisceneconfigurations/cpscenesessionroleimmersivespaceapplication"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/UISceneSessionRoleImmersiveSpaceApplication": {
      "abstract": [
        {
          "text": "Configurations for scenes you use to display SwiftUI content in an immersive space.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/UISceneSessionRoleImmersiveSpaceApplication",
      "kind": "symbol",
      "name": "UISceneSessionRoleImmersiveSpaceApplication",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISceneSessionRoleImmersiveSpaceApplication"
        }
      ],
      "role": "symbol",
      "title": "UISceneSessionRoleImmersiveSpaceApplication",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationscenemanifest/uisceneconfigurations/uiscenesessionroleimmersivespaceapplication"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/UISceneSessionRoleImmersiveSpaceApplication/UISceneInitialImmersionStyle": {
      "abstract": [
        {
          "text": "Provide a preferred initial scene style for an immersive space scene.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/UISceneSessionRoleImmersiveSpaceApplication/UISceneInitialImmersionStyle",
      "kind": "symbol",
      "name": "UISceneInitialImmersionStyle",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISceneInitialImmersionStyle"
        }
      ],
      "role": "symbol",
      "title": "UISceneInitialImmersionStyle",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationscenemanifest/uisceneconfigurations/uiscenesessionroleimmersivespaceapplication/uisceneinitialimmersionstyle"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIMainStoryboardFile": {
      "abstract": [
        {
          "text": "The name of the app’s main storyboard file.",
          "type": "text"
        }
      ],
      "ideTitle": "Main storyboard file base name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIMainStoryboardFile",
      "kind": "symbol",
      "name": "UIMainStoryboardFile",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMainStoryboardFile"
        }
      ],
      "role": "symbol",
      "title": "UIMainStoryboardFile",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uimainstoryboardfile"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportsTrueScreenSizeOnMac": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your iPad app supports arbitrary screen sizes and resolutions when running on a Mac.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportsTrueScreenSizeOnMac",
      "kind": "symbol",
      "name": "UISupportsTrueScreenSizeOnMac",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISupportsTrueScreenSizeOnMac"
        }
      ],
      "role": "symbol",
      "title": "UISupportsTrueScreenSizeOnMac",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uisupportstruescreensizeonmac"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Main-user-interface",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSMainStoryboardFile",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIMainStoryboardFile",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSMainNibFile",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSUIElement",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportsTrueScreenSizeOnMac"
      ],
      "title": "Main user interface"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIApplicationPreferredDefaultSceneSessionRole"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationPreferredDefaultSceneSessionRole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Main-user-interface",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSMainStoryboardFile",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIMainStoryboardFile",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSMainNibFile",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSUIElement",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportsTrueScreenSizeOnMac"
              ],
              "title": "Main user interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSMainStoryboardFile/title",
          "value": "NSMainStoryboardFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSMainStoryboardFile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMainStoryboardFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationPreferredDefaultSceneSessionRole/title",
          "value": "UIApplicationPreferredDefaultSceneSessionRole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationPreferredDefaultSceneSessionRole/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationPreferredDefaultSceneSessionRole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest/title",
          "value": "UIApplicationSceneManifest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationSceneManifest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSUIElement/title",
          "value": "LSUIElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSUIElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSUIElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations~1UISceneSessionRoleImmersiveSpaceApplication/title",
          "value": "UISceneSessionRoleImmersiveSpaceApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations~1UISceneSessionRoleImmersiveSpaceApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneSessionRoleImmersiveSpaceApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSMainNibFile/title",
          "value": "NSMainNibFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSMainNibFile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMainNibFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UISupportsTrueScreenSizeOnMac/title",
          "value": "UISupportsTrueScreenSizeOnMac"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UISupportsTrueScreenSizeOnMac/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISupportsTrueScreenSizeOnMac"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIMainStoryboardFile/title",
          "value": "UIMainStoryboardFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIMainStoryboardFile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMainStoryboardFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations~1UISceneSessionRoleImmersiveSpaceApplication~1UISceneInitialImmersionStyle/title",
          "value": "UISceneInitialImmersionStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations~1UISceneSessionRoleImmersiveSpaceApplication~1UISceneInitialImmersionStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneInitialImmersionStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations~1CPSceneSessionRoleImmersiveSpaceApplication/title",
          "value": "CPSceneSessionRoleImmersiveSpaceApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations~1CPSceneSessionRoleImmersiveSpaceApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPSceneSessionRoleImmersiveSpaceApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uiapplicationpreferreddefaultscenesessionrole"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uiapplicationpreferreddefaultscenesessionrole"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
