{
  "abstract": [
    {
      "text": "A Boolean value that indicates whether the app supports the Command-P keyboard shortcut.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSupportsPrintCommand"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.UIApplicationSupportsPrintCommand",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIApplicationSupportsPrintCommand"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "UIApplicationSupportsPrintCommand"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Supports Print Command",
        "name": "UIApplicationSupportsPrintCommand",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When the value for this key is ",
              "type": "text"
            },
            {
              "code": "YES",
              "type": "codeVoice"
            },
            {
              "text": ", the system adds the Command-P keyboard shortcut to the app. When someone enters Command-P while using the app, the system calls the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIResponderStandardEditActions/printContent(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method on the first responder that implements the method found in the responder chain.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "An iPad app running in iPadOS shows a Print command in the discoverability HUD when the value for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSupportsPrintCommand",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key is ",
              "type": "text"
            },
            {
              "code": "YES",
              "type": "codeVoice"
            },
            {
              "text": ". When the same app runs on a Mac with Apple silicon, the system adds Print and Export to PDF menu commands to the File menu.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When an app built with Mac Catalyst includes the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSupportsPrintCommand",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key with a value of ",
              "type": "text"
            },
            {
              "code": "YES",
              "type": "codeVoice"
            },
            {
              "text": ", the system adds the Print and Export to PDF commands to the File menu. However, the app must also include the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.print",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.files.user-selected.read-write",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " App Sandbox entitlements to make printing and exporting content available to the app when running in macOS.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.files.user-selected.read-write": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app may have read-write access to files the user has selected using an Open or Save dialog.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.files.user-selected.read-write",
      "kind": "symbol",
      "name": "com.apple.security.files.user-selected.read-write",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.security.files.user-selected.read-write"
        }
      ],
      "role": "symbol",
      "title": "com.apple.security.files.user-selected.read-write",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.security.files.user-selected.read-write"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.print": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether your app may print a document.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.print",
      "kind": "symbol",
      "name": "com.apple.security.print",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.security.print"
        }
      ],
      "role": "symbol",
      "title": "com.apple.security.print",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.security.print"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSupportsPrintCommand": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app supports the Command-P keyboard shortcut.",
          "type": "text"
        }
      ],
      "ideTitle": "Supports Print Command",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSupportsPrintCommand",
      "kind": "symbol",
      "name": "UIApplicationSupportsPrintCommand",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationSupportsPrintCommand"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationSupportsPrintCommand",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationsupportsprintcommand"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportedExternalAccessoryProtocols": {
      "abstract": [
        {
          "text": "The protocols that the app uses to communicate with external accessory hardware.",
          "type": "text"
        }
      ],
      "ideTitle": "Supported external accessory protocols",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportedExternalAccessoryProtocols",
      "kind": "symbol",
      "name": "UISupportedExternalAccessoryProtocols",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISupportedExternalAccessoryProtocols"
        }
      ],
      "role": "symbol",
      "title": "UISupportedExternalAccessoryProtocols",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uisupportedexternalaccessoryprotocols"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIResponderStandardEditActions/printContent(_:)": {
      "abstract": [
        {
          "text": "Tells your app to print available content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printContent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "sender"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIResponderStandardEditActions/printContent(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "printContent(_:)",
      "type": "topic",
      "url": "/documentation/UIKit/UIResponderStandardEditActions/printContent(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "External-accessories",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportedExternalAccessoryProtocols"
      ],
      "title": "External accessories"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIApplicationSupportsPrintCommand"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationSupportsPrintCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "External-accessories",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportedExternalAccessoryProtocols"
              ],
              "title": "External accessories"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSupportsPrintCommand/title",
          "value": "UIApplicationSupportsPrintCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSupportsPrintCommand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationSupportsPrintCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIResponderStandardEditActions~1printContent(_:)/title",
          "value": "print:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIResponderStandardEditActions~1printContent(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "print:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "keyword",
              "text": "id"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "sender"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.security.print/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.security.print"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UISupportedExternalAccessoryProtocols/title",
          "value": "UISupportedExternalAccessoryProtocols"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UISupportedExternalAccessoryProtocols/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISupportedExternalAccessoryProtocols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.security.files.user-selected.read-write/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.security.files.user-selected.read-write"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uiapplicationsupportsprintcommand"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uiapplicationsupportsprintcommand"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
