{
  "abstract": [
    {
      "text": "The launch storyboard to use to generate a launch image when your app opens from a supported scheme.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.UILaunchStoryboards",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UILaunchStoryboards"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "dictionary",
    "title": "UILaunchStoryboards"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "UILaunchStoryboards",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "object"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " when you want your app to show a different launch screen for different schemes. The schemes are the ones specified in your app’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleURLTypes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". You can also specify a default launch storyboard.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If your app has a single launch storyboard, use the simpler ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboardName",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleURLTypes": {
      "abstract": [
        {
          "text": "A list of URL schemes (http, ftp, and so on) supported by the app.",
          "type": "text"
        }
      ],
      "ideTitle": "URL types",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleURLTypes",
      "kind": "symbol",
      "name": "CFBundleURLTypes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleURLTypes"
        }
      ],
      "role": "symbol",
      "title": "CFBundleURLTypes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundleurltypes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSUIPresentationMode": {
      "abstract": [
        {
          "text": "The initial user-interface mode for the app.",
          "type": "text"
        }
      ],
      "ideTitle": "Application UI Presentation Mode",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSUIPresentationMode",
      "kind": "symbol",
      "name": "LSUIPresentationMode",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSUIPresentationMode"
        }
      ],
      "role": "symbol",
      "title": "LSUIPresentationMode",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsuipresentationmode"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreen": {
      "abstract": [
        {
          "text": "The user interface to show while an app launches.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreen",
      "kind": "symbol",
      "name": "UILaunchScreen",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchScreen"
        }
      ],
      "role": "symbol",
      "title": "UILaunchScreen",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreen"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens": {
      "abstract": [
        {
          "text": "The user interfaces to show while an app launches in response to different URL schemes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens",
      "kind": "symbol",
      "name": "UILaunchScreens",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchScreens"
        }
      ],
      "role": "symbol",
      "title": "UILaunchScreens",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreens"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboardName": {
      "abstract": [
        {
          "text": "The filename of the storyboard from which to generate the app’s launch image.",
          "type": "text"
        }
      ],
      "ideTitle": "Launch screen interface file base name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboardName",
      "kind": "symbol",
      "name": "UILaunchStoryboardName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchStoryboardName"
        }
      ],
      "role": "symbol",
      "title": "UILaunchStoryboardName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchstoryboardname"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards": {
      "abstract": [
        {
          "text": "The launch storyboard to use to generate a launch image when your app opens from a supported scheme.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards",
      "kind": "symbol",
      "name": "UILaunchStoryboards",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchStoryboards"
        }
      ],
      "role": "symbol",
      "title": "UILaunchStoryboards",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchstoryboards"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UIDefaultLaunchStoryboard": {
      "abstract": [
        {
          "text": "The identifier of the default launch storyboard to use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UIDefaultLaunchStoryboard",
      "kind": "symbol",
      "name": "UIDefaultLaunchStoryboard",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDefaultLaunchStoryboard"
        }
      ],
      "role": "symbol",
      "title": "UIDefaultLaunchStoryboard",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchstoryboards/uidefaultlaunchstoryboard"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UILaunchStoryboardDefinitions": {
      "abstract": [
        {
          "text": "An array of dictionaries mapping launch storyboard identifiers to storyboards.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UILaunchStoryboardDefinitions",
      "kind": "symbol",
      "name": "UILaunchStoryboardDefinitions",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchStoryboardDefinitions"
        }
      ],
      "role": "symbol",
      "title": "UILaunchStoryboardDefinitions",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchstoryboards/uilaunchstoryboarddefinitions"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UIURLToLaunchStoryboardAssociations": {
      "abstract": [
        {
          "text": "The user-defined storyboard identifiers that associate with supported schemes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UIURLToLaunchStoryboardAssociations",
      "kind": "symbol",
      "name": "UIURLToLaunchStoryboardAssociations",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIURLToLaunchStoryboardAssociations"
        }
      ],
      "role": "symbol",
      "title": "UIURLToLaunchStoryboardAssociations",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchstoryboards/uiurltolaunchstoryboardassociations"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchToFullScreenByDefaultOnMac": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to launch your iPad app in full-screen mode when running on a Mac.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchToFullScreenByDefaultOnMac",
      "kind": "symbol",
      "name": "UILaunchToFullScreenByDefaultOnMac",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchToFullScreenByDefaultOnMac"
        }
      ],
      "role": "symbol",
      "title": "UILaunchToFullScreenByDefaultOnMac",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchtofullscreenbydefaultonmac"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Launch-interface",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreen",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboardName",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSUIPresentationMode",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchToFullScreenByDefaultOnMac"
      ],
      "title": "Launch interface"
    }
  ],
  "topicSections": [
    {
      "anchor": "Specifying-Launch-Storyboards",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UILaunchStoryboardDefinitions",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UIDefaultLaunchStoryboard"
      ],
      "title": "Specifying Launch Storyboards"
    },
    {
      "anchor": "Associating-Storyboard-Identifiers-with-Schemes",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UIURLToLaunchStoryboardAssociations"
      ],
      "title": "Associating Storyboard Identifiers with Schemes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UILaunchStoryboards"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchStoryboards"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Specifying-Launch-Storyboards",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UILaunchStoryboardDefinitions",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UIDefaultLaunchStoryboard"
              ],
              "title": "Specifying Launch Storyboards"
            },
            {
              "anchor": "Associating-Storyboard-Identifiers-with-Schemes",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UIURLToLaunchStoryboardAssociations"
              ],
              "title": "Associating Storyboard Identifiers with Schemes"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Launch-interface",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreen",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboardName",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSUIPresentationMode",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchToFullScreenByDefaultOnMac"
              ],
              "title": "Launch interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchStoryboardName/title",
          "value": "UILaunchStoryboardName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchStoryboardName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchStoryboardName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSUIPresentationMode/title",
          "value": "LSUIPresentationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSUIPresentationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSUIPresentationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchStoryboards/title",
          "value": "UILaunchStoryboards"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchStoryboards/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchStoryboards"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchStoryboards~1UIDefaultLaunchStoryboard/title",
          "value": "UIDefaultLaunchStoryboard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchStoryboards~1UIDefaultLaunchStoryboard/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDefaultLaunchStoryboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchStoryboards~1UIURLToLaunchStoryboardAssociations/title",
          "value": "UIURLToLaunchStoryboardAssociations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchStoryboards~1UIURLToLaunchStoryboardAssociations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIURLToLaunchStoryboardAssociations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchStoryboards~1UILaunchStoryboardDefinitions/title",
          "value": "UILaunchStoryboardDefinitions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchStoryboards~1UILaunchStoryboardDefinitions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchStoryboardDefinitions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens/title",
          "value": "UILaunchScreens"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchScreens"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleURLTypes/title",
          "value": "CFBundleURLTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleURLTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleURLTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchToFullScreenByDefaultOnMac/title",
          "value": "UILaunchToFullScreenByDefaultOnMac"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchToFullScreenByDefaultOnMac/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchToFullScreenByDefaultOnMac"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreen/title",
          "value": "UILaunchScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreen/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uilaunchstoryboards"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uilaunchstoryboards"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
