{
  "abstract": [
    {
      "text": "The device-related features that your app requires to run.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIRequiredDeviceCapabilities"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.UIRequiredDeviceCapabilities",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIRequiredDeviceCapabilities"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "UIRequiredDeviceCapabilities"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Required device capabilities",
        "name": "UIRequiredDeviceCapabilities",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": true,
            "baseType": "string "
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "kind": "possibleValues",
      "title": "Possible Values",
      "values": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The presence of accelerometers. Use the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/CoreMotion",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " framework to receive accelerometer events. You don’t need to include this value if your app detects only device orientation changes. Available in iOS 3.0 and later. Unavailable in visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "accelerometer"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Support for ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/ARKit",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". Available in iOS 11.0 and later, and Full Space apps in visionOS. Unavailable for iPadOS and iOS apps running in visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "arkit"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Compilation for the ",
                  "type": "text"
                },
                {
                  "code": "armv7",
                  "type": "codeVoice"
                },
                {
                  "text": " instruction set, or as a 32- or 64-bit universal app. Available in iOS 3.1 and later, and visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "armv7"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Compilation for the ",
                  "type": "text"
                },
                {
                  "code": "arm64",
                  "type": "codeVoice"
                },
                {
                  "text": " instruction set. Include this key for all 64-bit apps and embedded bundles, like extensions and frameworks. Available in iOS 8.0 and later, and visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "arm64"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Autofocus capabilities in the device’s still camera. You might need to include this value if your app supports macro photography or requires sharper images to perform certain image-processing tasks. Available in iOS 3.0 and later. Unavailable in visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "auto-focus-camera"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Bluetooth low-energy hardware. Available in iOS 5.0 and later, and visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "bluetooth-le"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A camera flash. Use the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/UIKit/UIImagePickerController/cameraFlashMode-swift.property",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " property of a ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/UIKit/UIImagePickerController",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instance to control the camera’s flash. Available in iOS 3.0 and later. Unavailable in visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "camera-flash"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Support for ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/driverkit",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " on devices with M1 or later chips. Available on iPadOS 16.0 or later. Unavailable in visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "driverkit"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A forward-facing camera. Use the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/UIKit/UIImagePickerController/cameraDevice-swift.property",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " property of a ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/UIKit/UIImagePickerController",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instance to select the device’s camera. Available in iOS 3.0 and later, and iPadOS and iOS apps running in visionOS. Unavailable in apps built for visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "front-facing-camera"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Access to the Game Center service. Enable the Game Center capability in Xcode to add this value to your app. Available in iOS 4.1 and later, and visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "gamekit"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "GPS (or AGPS) hardware for tracking locations. If you include this value, you should also include the location-services value. Require GPS only if your app needs location data more accurate than the cellular or Wi-Fi radios provide. Available in iOS 3.0 and later. Unavailable in visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "gps"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A gyroscope. Use the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/CoreMotion",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " framework to retrieve information from gyroscope hardware. Available in iOS 3.0 and later. Unavailable in visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "gyroscope"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Support for ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/HealthKit",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". The system uses this value to limit apps to iPhone. In order to ship Universal apps, remove this key. Available in iOS 8.0 and later. Unavailable in visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "healthkit"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Requires the graphics performance and gaming features equivalent to the iPhone 15 Pro and iPhone 15 Pro Max. Available in iOS 17.0 and later. Unavailable in visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "iphone-performance-gaming-tier"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Performance and capabilities of the A12 Bionic and later chips. Available in iOS 12.0 and later, and iPadOS and iOS apps running in visionOS. Unavailable in apps built for visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "iphone-ipad-minimum-performance-a12"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Access to the device’s current location using the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/CoreLocation",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " framework. This value refers to the general location services feature. If you specifically need GPS-level accuracy, also include the ",
                  "type": "text"
                },
                {
                  "code": "gps",
                  "type": "codeVoice"
                },
                {
                  "text": " feature. Available in iOS 3.0 and later, and visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "location-services"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Magnetometer hardware. Apps use this hardware to receive heading-related events through the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/CoreLocation",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " framework. Available in iOS 3.0 and later. Unavailable in visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "magnetometer"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Support for graphics processing with ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Metal",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". Available in iOS 8.0 and later, and visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "metal"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The built-in microphone or accessories that provide a microphone. Available in iOS 3.0 and later, and visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "microphone"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Near Field Communication (NFC) tag detection and access to messages that contain NFC Data Exchange Format data. Use the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/CoreNFC",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " framework to detect and read NFC tags. Available in iOS 11.0 and later. Unavailable in visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "nfc"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The OpenGL ES 1.1 interface. Available in iOS 3.0 and later, and iPadOS and iOS apps running in visionOS. Unavailable in apps built for visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "opengles-1"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The OpenGL ES 2.0 interface. Available in iOS 3.0 and later, and iPadOS and iOS apps running in visionOS. Unavailable in apps built for visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "opengles-2"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The OpenGL ES 3.0 interface. Available in iOS 7.0 and later, and iPadOS and iOS apps running in visionOS. Unavailable in apps built for visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "opengles-3"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Peer-to-peer connectivity over a Bluetooth network. Available in iOS 3.1 and later, and visionOS. The App Store doesn’t prevent distributing an app to a device that doesn’t support this capability, but iOS prevents running the app.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "peer-peer"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The Messages app. You might require this feature if your app opens URLs with the ",
                  "type": "text"
                },
                {
                  "code": "sms",
                  "type": "codeVoice"
                },
                {
                  "text": " scheme. Available in iOS 3.0 and later. Unavailable in visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "sms"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A camera on the device. Use the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/UIKit/UIImagePickerController",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " interface to capture images from the device’s still camera. Available in iOS 3.0 and later. Unavailable in visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "still-camera"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The Phone app. You might require this feature if your app opens URLs with the ",
                  "type": "text"
                },
                {
                  "code": "tel",
                  "type": "codeVoice"
                },
                {
                  "text": " scheme. Available in iOS 3.0 and later. Unavailable in visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "telephony"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A camera with video capabilities on the device. Use the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/UIKit/UIImagePickerController",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " interface to capture video from the device’s camera. Available in iOS 3.0 and later, and visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "video-camera"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Networking features related to Wi-Fi access. Available in iOS 3.0 and later, and visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "wifi"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The App Store prevents customers from installing an app on a device that doesn’t support the required capabilities for that app. Use this key to declare the capabilities your app requires. For a list of the features that different devices support, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/support/required-device-capabilities/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You typically use an array for the key’s associated value. The presence in that array of any of the above possible values indicates that the app requires the corresponding feature. Omit a value to indicate that the app doesn’t require the feature, but it can be present.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Alternatively, you can use a dictionary as the associated value for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIRequiredDeviceCapabilities",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key. In that case, use the values above as the dictionary’s keys, each with an associated Boolean value. Set the value to ",
              "type": "text"
            },
            {
              "code": "true",
              "type": "codeVoice"
            },
            {
              "text": " to require the corresponding feature. Set the value to ",
              "type": "text"
            },
            {
              "code": "false",
              "type": "codeVoice"
            },
            {
              "text": " to indicate that the feature must not be present on the device. Omit the feature from the dictionary to indicate that your app neither requires nor disallows it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Specify only the features that your app absolutely requires. If your app can accommodate missing features by avoiding the code paths that use those features, don’t include the corresponding key.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Your app must include the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIRequiredDeviceCapabilities",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " key in the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " file that you submit with your binary. For app updates, you can only maintain or relax capability requirements. Submitting an update with added requirements would prevent some customers who previously downloaded your app from running the update.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CLKComplicationSupportedFamilies": {
      "abstract": [
        {
          "text": "The complication families for which the app can provide data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "ideTitle": "ClockKit Complication - Supported Families",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CLKComplicationSupportedFamilies",
      "kind": "symbol",
      "name": "CLKComplicationSupportedFamilies",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationSupportedFamilies"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationSupportedFamilies",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/clkcomplicationsupportedfamilies"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSArchitecturePriority": {
      "abstract": [
        {
          "text": "An array of the architectures that the app supports, arranged according to their preferred usage.",
          "type": "text"
        }
      ],
      "ideTitle": "Architecture priority",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSArchitecturePriority",
      "kind": "symbol",
      "name": "LSArchitecturePriority",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSArchitecturePriority"
        }
      ],
      "role": "symbol",
      "title": "LSArchitecturePriority",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsarchitecturepriority"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMultipleInstancesProhibited": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether more than one user can launch the app simultaneously.",
          "type": "text"
        }
      ],
      "ideTitle": "Application prohibits multiple instances",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMultipleInstancesProhibited",
      "kind": "symbol",
      "name": "LSMultipleInstancesProhibited",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMultipleInstancesProhibited"
        }
      ],
      "role": "symbol",
      "title": "LSMultipleInstancesProhibited",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsmultipleinstancesprohibited"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSRequiresNativeExecution": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to require the execution of the app’s native architecture when multiple architectures are available.",
          "type": "text"
        }
      ],
      "ideTitle": "Application requires native environment",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSRequiresNativeExecution",
      "kind": "symbol",
      "name": "LSRequiresNativeExecution",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSRequiresNativeExecution"
        }
      ],
      "role": "symbol",
      "title": "LSRequiresNativeExecution",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsrequiresnativeexecution"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/PUICAutoLaunchAudioOptOut": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether a watchOS app should opt out of automatically launching when its companion iOS app starts playing audio content.",
          "type": "text"
        }
      ],
      "ideTitle": "Opt out of Auto-launch Audio App (Watch)",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/PUICAutoLaunchAudioOptOut",
      "kind": "symbol",
      "name": "PUICAutoLaunchAudioOptOut",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PUICAutoLaunchAudioOptOut"
        }
      ],
      "role": "symbol",
      "title": "PUICAutoLaunchAudioOptOut",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/puicautolaunchaudiooptout"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIRequiredDeviceCapabilities": {
      "abstract": [
        {
          "text": "The device-related features that your app requires to run.",
          "type": "text"
        }
      ],
      "ideTitle": "Required device capabilities",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIRequiredDeviceCapabilities",
      "kind": "symbol",
      "name": "UIRequiredDeviceCapabilities",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIRequiredDeviceCapabilities"
        }
      ],
      "role": "symbol",
      "title": "UIRequiredDeviceCapabilities",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uirequireddevicecapabilities"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKPrefersNetworkUponForeground": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether an app requires network access on launch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKPrefersNetworkUponForeground",
      "kind": "symbol",
      "name": "WKPrefersNetworkUponForeground",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKPrefersNetworkUponForeground"
        }
      ],
      "role": "symbol",
      "title": "WKPrefersNetworkUponForeground",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/wkprefersnetworkuponforeground"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKRunsIndependentlyOfCompanionApp": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the user can install and run the watchOS app independently of its iOS companion app.",
          "type": "text"
        }
      ],
      "ideTitle": "App can run independently of companion iPhone app",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKRunsIndependentlyOfCompanionApp",
      "kind": "symbol",
      "name": "WKRunsIndependentlyOfCompanionApp",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKRunsIndependentlyOfCompanionApp"
        }
      ],
      "role": "symbol",
      "title": "WKRunsIndependentlyOfCompanionApp",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/wkrunsindependentlyofcompanionapp"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKWatchOnly": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app is a watch-only app.",
          "type": "text"
        }
      ],
      "ideTitle": "App is only available as a standalone watchOS app",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKWatchOnly",
      "kind": "symbol",
      "name": "WKWatchOnly",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWatchOnly"
        }
      ],
      "role": "symbol",
      "title": "WKWatchOnly",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/wkwatchonly"
    },
    "doc://com.apple.documentation/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/ARKit"
    },
    "doc://com.apple.documentation/documentation/CoreLocation": {
      "abstract": [
        {
          "text": "Obtain the geographic location and orientation of a device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreLocation",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Location",
      "type": "topic",
      "url": "/documentation/CoreLocation"
    },
    "doc://com.apple.documentation/documentation/CoreMotion": {
      "abstract": [
        {
          "text": "Process accelerometer, gyroscope, pedometer, and environment-related events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreMotion",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Motion",
      "type": "topic",
      "url": "/documentation/CoreMotion"
    },
    "doc://com.apple.documentation/documentation/CoreNFC": {
      "abstract": [
        {
          "text": "Detect NFC tags, read messages that contain NDEF data, and save data to writable tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreNFC",
      "kind": "symbol",
      "role": "collection",
      "title": "Core NFC",
      "type": "topic",
      "url": "/documentation/CoreNFC"
    },
    "doc://com.apple.documentation/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/HealthKit"
    },
    "doc://com.apple.documentation/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/Metal"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIImagePickerController": {
      "abstract": [
        {
          "text": "A view controller that manages the system interfaces for taking pictures, recording movies, and choosing items from the user’s media library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIImagePickerController"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIImagePickerController",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIImagePickerController",
      "type": "topic",
      "url": "/documentation/UIKit/UIImagePickerController"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIImagePickerController/cameraDevice-swift.property": {
      "abstract": [
        {
          "text": "The camera used by the image picker controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImagePickerController",
          "text": "UIImagePickerController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIImagePickerControllerCameraDevice",
          "text": "CameraDevice"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIImagePickerController/cameraDevice-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "cameraDevice",
      "type": "topic",
      "url": "/documentation/UIKit/UIImagePickerController/cameraDevice-swift.property"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIImagePickerController/cameraFlashMode-swift.property": {
      "abstract": [
        {
          "text": "The flash mode used by the active camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraFlashMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImagePickerController",
          "text": "UIImagePickerController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIImagePickerControllerCameraFlashMode",
          "text": "CameraFlashMode"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIImagePickerController/cameraFlashMode-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "cameraFlashMode",
      "type": "topic",
      "url": "/documentation/UIKit/UIImagePickerController/cameraFlashMode-swift.property"
    },
    "doc://com.apple.documentation/documentation/driverkit": {
      "abstract": [
        {
          "text": "Develop device drivers that run in user space.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/driverkit",
      "kind": "symbol",
      "role": "collection",
      "title": "DriverKit",
      "type": "topic",
      "url": "/documentation/driverkit"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/support/required-device-capabilities/": {
      "identifier": "https://developer.apple.com/support/required-device-capabilities/",
      "title": "Required Device Capabilities",
      "titleInlineContent": [
        {
          "text": "Required Device Capabilities",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/required-device-capabilities/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Launch-conditions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMultipleInstancesProhibited",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSArchitecturePriority",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSRequiresNativeExecution",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKPrefersNetworkUponForeground",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKRunsIndependentlyOfCompanionApp",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKWatchOnly",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/PUICAutoLaunchAudioOptOut",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CLKComplicationSupportedFamilies"
      ],
      "title": "Launch conditions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIRequiredDeviceCapabilities"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRequiredDeviceCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Launch-conditions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMultipleInstancesProhibited",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSArchitecturePriority",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSRequiresNativeExecution",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKPrefersNetworkUponForeground",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKRunsIndependentlyOfCompanionApp",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKWatchOnly",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/PUICAutoLaunchAudioOptOut",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CLKComplicationSupportedFamilies"
              ],
              "title": "Launch conditions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CLKComplicationSupportedFamilies/title",
          "value": "CLKComplicationSupportedFamilies"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CLKComplicationSupportedFamilies/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationSupportedFamilies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKPrefersNetworkUponForeground/title",
          "value": "WKPrefersNetworkUponForeground"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKPrefersNetworkUponForeground/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKPrefersNetworkUponForeground"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKWatchOnly/title",
          "value": "WKWatchOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKWatchOnly/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWatchOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIImagePickerController~1cameraFlashMode-swift.property/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UIImagePickerControllerCameraFlashMode",
              "text": "UIImagePickerControllerCameraFlashMode"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "cameraFlashMode"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIImagePickerController~1cameraDevice-swift.property/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UIImagePickerControllerCameraDevice",
              "text": "UIImagePickerControllerCameraDevice"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "cameraDevice"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIImagePickerController/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIImagePickerController"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UINavigationController",
              "text": "UINavigationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSMultipleInstancesProhibited/title",
          "value": "LSMultipleInstancesProhibited"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSMultipleInstancesProhibited/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMultipleInstancesProhibited"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSRequiresNativeExecution/title",
          "value": "LSRequiresNativeExecution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSRequiresNativeExecution/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSRequiresNativeExecution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIRequiredDeviceCapabilities/title",
          "value": "UIRequiredDeviceCapabilities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIRequiredDeviceCapabilities/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRequiredDeviceCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1PUICAutoLaunchAudioOptOut/title",
          "value": "PUICAutoLaunchAudioOptOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1PUICAutoLaunchAudioOptOut/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PUICAutoLaunchAudioOptOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSArchitecturePriority/title",
          "value": "LSArchitecturePriority"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSArchitecturePriority/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSArchitecturePriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKRunsIndependentlyOfCompanionApp/title",
          "value": "WKRunsIndependentlyOfCompanionApp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKRunsIndependentlyOfCompanionApp/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKRunsIndependentlyOfCompanionApp"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uirequireddevicecapabilities"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uirequireddevicecapabilities"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
