{
  "abstract": [
    {
      "text": "A Boolean value that indicates whether your iPad app supports arbitrary screen sizes and resolutions when running on a Mac.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportsTrueScreenSizeOnMac"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.UISupportsTrueScreenSizeOnMac",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UISupportsTrueScreenSizeOnMac"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.1",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "UISupportsTrueScreenSizeOnMac"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "UISupportsTrueScreenSizeOnMac",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To declare support for arbitrary screen sizes and resolutions when running your iPad app in macOS, add this key to your app’s ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file and set its value to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". This key has no effect when:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The app supports iPad multitasking and resizable windows. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIRequiresFullScreen",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The app is running on other Apple platforms.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The app is built with ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UIKit/mac-catalyst",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The use of this key implies that your app is capable of handling a variety of display configurations available on a Mac, including:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Small to large display resolutions; for example, 640 x 480 to 8K and beyond.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Retina and non-Retina displays.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "All conceivable aspect ratios, including portrait and 21:9 ultrawide.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Use of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportsTrueScreenSizeOnMac",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key also implies that your app is capable of handling portrait and landscape sizes even when they don’t align with the device orientation. For instance, if your app supports rotation in iPadOS, the device orientation is always landscape even though the display might have a portrait aspect ratio in reality.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "When running your iPad app on a Mac, macOS chooses the device orientation of your app from the set of app-supported orientations for iOS, regardless of the actual Mac display aspect ratio. This means that you don’t need to update the set of iOS-supported orientations (see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportedInterfaceOrientations",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": "), or alter your code to handle unsupported orientations when using the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportsTrueScreenSizeOnMac",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " key.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "When you include ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportsTrueScreenSizeOnMac",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in your app, your app is responsible for:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Handling memory management concerns that may occur when running at extreme resolutions.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Handling layout concerns for different aspect ratios, such as correct button placement.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Letterboxing and pillarboxing as needed if your app requires a specific aspect ratio.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "To provide a pixel-perfect, edge-to-edge, full-screen experience, use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportsTrueScreenSizeOnMac",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " along with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchToFullScreenByDefaultOnMac",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSUIElement": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app is an agent app that runs in the background and doesn’t appear in the Dock.",
          "type": "text"
        }
      ],
      "ideTitle": "Application is agent (UIElement)",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSUIElement",
      "kind": "symbol",
      "name": "LSUIElement",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSUIElement"
        }
      ],
      "role": "symbol",
      "title": "LSUIElement",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsuielement"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSMainNibFile": {
      "abstract": [
        {
          "text": "The name of an app’s main user interface file.",
          "type": "text"
        }
      ],
      "ideTitle": "Main nib file base name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSMainNibFile",
      "kind": "symbol",
      "name": "NSMainNibFile",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMainNibFile"
        }
      ],
      "role": "symbol",
      "title": "NSMainNibFile",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsmainnibfile"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSMainStoryboardFile": {
      "abstract": [
        {
          "text": "The name of an app’s storyboard resource file.",
          "type": "text"
        }
      ],
      "ideTitle": "Main storyboard file base name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSMainStoryboardFile",
      "kind": "symbol",
      "name": "NSMainStoryboardFile",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMainStoryboardFile"
        }
      ],
      "role": "symbol",
      "title": "NSMainStoryboardFile",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsmainstoryboardfile"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationPreferredDefaultSceneSessionRole": {
      "abstract": [
        {
          "text": "The preferred initial scene session role for your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationPreferredDefaultSceneSessionRole",
      "kind": "symbol",
      "name": "UIApplicationPreferredDefaultSceneSessionRole",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationPreferredDefaultSceneSessionRole"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationPreferredDefaultSceneSessionRole",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationpreferreddefaultscenesessionrole"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest": {
      "abstract": [
        {
          "text": "The information about the app’s scene-based life-cycle support.",
          "type": "text"
        }
      ],
      "ideTitle": "Application Scene Manifest",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest",
      "kind": "symbol",
      "name": "UIApplicationSceneManifest",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationSceneManifest"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationSceneManifest",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationscenemanifest"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchToFullScreenByDefaultOnMac": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to launch your iPad app in full-screen mode when running on a Mac.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchToFullScreenByDefaultOnMac",
      "kind": "symbol",
      "name": "UILaunchToFullScreenByDefaultOnMac",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchToFullScreenByDefaultOnMac"
        }
      ],
      "role": "symbol",
      "title": "UILaunchToFullScreenByDefaultOnMac",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchtofullscreenbydefaultonmac"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIMainStoryboardFile": {
      "abstract": [
        {
          "text": "The name of the app’s main storyboard file.",
          "type": "text"
        }
      ],
      "ideTitle": "Main storyboard file base name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIMainStoryboardFile",
      "kind": "symbol",
      "name": "UIMainStoryboardFile",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMainStoryboardFile"
        }
      ],
      "role": "symbol",
      "title": "UIMainStoryboardFile",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uimainstoryboardfile"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIRequiresFullScreen": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether an iPad app is capable of sharing the screen with other apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIRequiresFullScreen",
      "kind": "symbol",
      "name": "UIRequiresFullScreen",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIRequiresFullScreen"
        }
      ],
      "role": "symbol",
      "title": "UIRequiresFullScreen",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uirequiresfullscreen"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportedInterfaceOrientations": {
      "abstract": [
        {
          "text": "The interface orientations supported by your app.",
          "type": "text"
        }
      ],
      "ideTitle": "Supported interface orientations",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportedInterfaceOrientations",
      "kind": "symbol",
      "name": "UISupportedInterfaceOrientations",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISupportedInterfaceOrientations"
        }
      ],
      "role": "symbol",
      "title": "UISupportedInterfaceOrientations",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uisupportedinterfaceorientations"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportsTrueScreenSizeOnMac": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your iPad app supports arbitrary screen sizes and resolutions when running on a Mac.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportsTrueScreenSizeOnMac",
      "kind": "symbol",
      "name": "UISupportsTrueScreenSizeOnMac",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISupportsTrueScreenSizeOnMac"
        }
      ],
      "role": "symbol",
      "title": "UISupportsTrueScreenSizeOnMac",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uisupportstruescreensizeonmac"
    },
    "doc://com.apple.documentation/documentation/UIKit/mac-catalyst": {
      "abstract": [
        {
          "text": "Create a version of your iPad app that users can run on a Mac device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/mac-catalyst",
      "kind": "article",
      "role": "article",
      "title": "Mac Catalyst",
      "type": "topic",
      "url": "/documentation/UIKit/mac-catalyst"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Main-user-interface",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationPreferredDefaultSceneSessionRole",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSMainStoryboardFile",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIMainStoryboardFile",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSMainNibFile",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSUIElement"
      ],
      "title": "Main user interface"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.1",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UISupportsTrueScreenSizeOnMac"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISupportsTrueScreenSizeOnMac"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Main-user-interface",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationPreferredDefaultSceneSessionRole",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSMainStoryboardFile",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIMainStoryboardFile",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSMainNibFile",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSUIElement"
              ],
              "title": "Main user interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest/title",
          "value": "UIApplicationSceneManifest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationSceneManifest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIMainStoryboardFile/title",
          "value": "UIMainStoryboardFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIMainStoryboardFile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMainStoryboardFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSMainNibFile/title",
          "value": "NSMainNibFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSMainNibFile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMainNibFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationPreferredDefaultSceneSessionRole/title",
          "value": "UIApplicationPreferredDefaultSceneSessionRole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationPreferredDefaultSceneSessionRole/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationPreferredDefaultSceneSessionRole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchToFullScreenByDefaultOnMac/title",
          "value": "UILaunchToFullScreenByDefaultOnMac"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchToFullScreenByDefaultOnMac/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchToFullScreenByDefaultOnMac"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSMainStoryboardFile/title",
          "value": "NSMainStoryboardFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSMainStoryboardFile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMainStoryboardFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UISupportedInterfaceOrientations/title",
          "value": "UISupportedInterfaceOrientations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UISupportedInterfaceOrientations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISupportedInterfaceOrientations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UISupportsTrueScreenSizeOnMac/title",
          "value": "UISupportsTrueScreenSizeOnMac"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UISupportsTrueScreenSizeOnMac/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISupportsTrueScreenSizeOnMac"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSUIElement/title",
          "value": "LSUIElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSUIElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSUIElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIRequiresFullScreen/title",
          "value": "UIRequiresFullScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIRequiresFullScreen/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRequiresFullScreen"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uisupportstruescreensizeonmac"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uisupportstruescreensizeonmac"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
