{
  "abstract": [
    {
      "text": "The user interface style for the app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIUserInterfaceStyle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.UIUserInterfaceStyle",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIUserInterfaceStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "UIUserInterfaceStyle"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "User Interface Style",
        "name": "UIUserInterfaceStyle",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "string"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "kind": "possibleValues",
      "title": "Possible Values",
      "values": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Set this value to adopt the systemwide user interface style, and observe any changes to that style. This is the default value, and provides the same functionality as if the key weren’t explicitly set.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Automatic"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Set this value to force the light user interface style, even when the systemwide style is set to dark. Your app will ignore any changes to the systemwide style.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Light"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Set this value to force the dark user interface style, even when the systemwide style is set to light. Your app will ignore any changes to the systemwide style.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Dark"
        }
      ]
    },
    {
      "attributes": [
        {
          "kind": "default",
          "value": "Automatic"
        }
      ],
      "kind": "attributes",
      "title": "Attributes"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAccentColorName": {
      "abstract": [
        {
          "text": "The name of a color in an asset catalog to use for a target’s global accent color.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAccentColorName",
      "kind": "symbol",
      "name": "NSAccentColorName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccentColorName"
        }
      ],
      "role": "symbol",
      "title": "NSAccentColorName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsaccentcolorname"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSPrefersDisplaySafeAreaCompatibilityMode": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app prefers to run in compatibility mode when necessary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSPrefersDisplaySafeAreaCompatibilityMode",
      "kind": "symbol",
      "name": "NSPrefersDisplaySafeAreaCompatibilityMode",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrefersDisplaySafeAreaCompatibilityMode"
        }
      ],
      "role": "symbol",
      "title": "NSPrefersDisplaySafeAreaCompatibilityMode",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsprefersdisplaysafeareacompatibilitymode"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSWidgetBackgroundColorName": {
      "abstract": [
        {
          "text": "The name of a color in an asset catalog to use for a widget’s configuration interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSWidgetBackgroundColorName",
      "kind": "symbol",
      "name": "NSWidgetBackgroundColorName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWidgetBackgroundColorName"
        }
      ],
      "role": "symbol",
      "title": "NSWidgetBackgroundColorName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nswidgetbackgroundcolorname"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIRequiresFullScreen": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether an iPad app is capable of sharing the screen with other apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIRequiresFullScreen",
      "kind": "symbol",
      "name": "UIRequiresFullScreen",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIRequiresFullScreen"
        }
      ],
      "role": "symbol",
      "title": "UIRequiresFullScreen",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uirequiresfullscreen"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportsFullScreenInAssistiveAccess": {
      "abstract": [
        {
          "text": "A Boolean value that indicates if an iOS or iPadOS app appears as full screen in Assistive Access.",
          "type": "text"
        }
      ],
      "ideTitle": "Supports full screen in Assistive Access",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportsFullScreenInAssistiveAccess",
      "kind": "symbol",
      "name": "UISupportsFullScreenInAssistiveAccess",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISupportsFullScreenInAssistiveAccess"
        }
      ],
      "role": "symbol",
      "title": "UISupportsFullScreenInAssistiveAccess",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uisupportsfullscreeninassistiveaccess"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIUserInterfaceStyle": {
      "abstract": [
        {
          "text": "The user interface style for the app.",
          "type": "text"
        }
      ],
      "ideTitle": "User Interface Style",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIUserInterfaceStyle",
      "kind": "symbol",
      "name": "UIUserInterfaceStyle",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserInterfaceStyle"
        }
      ],
      "role": "symbol",
      "title": "UIUserInterfaceStyle",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiuserinterfacestyle"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIViewEdgeAntialiasing": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether Core Animation layers use antialiasing when drawing a layer that isn’t aligned to pixel boundaries.",
          "type": "text"
        }
      ],
      "ideTitle": "Renders with edge antialiasing",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIViewEdgeAntialiasing",
      "kind": "symbol",
      "name": "UIViewEdgeAntialiasing",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewEdgeAntialiasing"
        }
      ],
      "role": "symbol",
      "title": "UIViewEdgeAntialiasing",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiviewedgeantialiasing"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIViewGroupOpacity": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether Core Animation sublayers inherit the opacity of their superlayer.",
          "type": "text"
        }
      ],
      "ideTitle": "Renders with group opacity",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIViewGroupOpacity",
      "kind": "symbol",
      "name": "UIViewGroupOpacity",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewGroupOpacity"
        }
      ],
      "role": "symbol",
      "title": "UIViewGroupOpacity",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiviewgroupopacity"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIWhitePointAdaptivityStyle": {
      "abstract": [
        {
          "text": "The app’s white-point adaptivity style, enabled on devices with True Tone displays.",
          "type": "text"
        }
      ],
      "ideTitle": "White Point Adaptivity Style",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIWhitePointAdaptivityStyle",
      "kind": "symbol",
      "name": "UIWhitePointAdaptivityStyle",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWhitePointAdaptivityStyle"
        }
      ],
      "role": "symbol",
      "title": "UIWhitePointAdaptivityStyle",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiwhitepointadaptivitystyle"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Styling",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIViewEdgeAntialiasing",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIWhitePointAdaptivityStyle",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIViewGroupOpacity",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIRequiresFullScreen",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportsFullScreenInAssistiveAccess",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSPrefersDisplaySafeAreaCompatibilityMode",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAccentColorName",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSWidgetBackgroundColorName"
      ],
      "title": "Styling"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIUserInterfaceStyle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Styling",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIViewEdgeAntialiasing",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIWhitePointAdaptivityStyle",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIViewGroupOpacity",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIRequiresFullScreen",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportsFullScreenInAssistiveAccess",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSPrefersDisplaySafeAreaCompatibilityMode",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAccentColorName",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSWidgetBackgroundColorName"
              ],
              "title": "Styling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIUserInterfaceStyle/title",
          "value": "UIUserInterfaceStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIUserInterfaceStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UISupportsFullScreenInAssistiveAccess/title",
          "value": "UISupportsFullScreenInAssistiveAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UISupportsFullScreenInAssistiveAccess/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISupportsFullScreenInAssistiveAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSWidgetBackgroundColorName/title",
          "value": "NSWidgetBackgroundColorName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSWidgetBackgroundColorName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWidgetBackgroundColorName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSPrefersDisplaySafeAreaCompatibilityMode/title",
          "value": "NSPrefersDisplaySafeAreaCompatibilityMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSPrefersDisplaySafeAreaCompatibilityMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrefersDisplaySafeAreaCompatibilityMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIWhitePointAdaptivityStyle/title",
          "value": "UIWhitePointAdaptivityStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIWhitePointAdaptivityStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWhitePointAdaptivityStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIRequiresFullScreen/title",
          "value": "UIRequiresFullScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIRequiresFullScreen/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRequiresFullScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAccentColorName/title",
          "value": "NSAccentColorName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAccentColorName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccentColorName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIViewEdgeAntialiasing/title",
          "value": "UIViewEdgeAntialiasing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIViewEdgeAntialiasing/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewEdgeAntialiasing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIViewGroupOpacity/title",
          "value": "UIViewGroupOpacity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIViewGroupOpacity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewGroupOpacity"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uiuserinterfacestyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uiuserinterfacestyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
