{
  "abstract": [
    {
      "text": "A Boolean value that indicates whether an app requires network access on launch.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKPrefersNetworkUponForeground"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.WKPrefersNetworkUponForeground",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKPrefersNetworkUponForeground"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "WKPrefersNetworkUponForeground"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "WKPrefersNetworkUponForeground",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In low-power mode, the system turns off cellular data to preserve battery life. If this key is ",
              "type": "text"
            },
            {
              "code": "NO",
              "type": "codeVoice"
            },
            {
              "text": ", the system waits until an app requests a network connection before turning on cellular data. This can cause a few seconds of delay before your app can perform network requests.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If your app needs access to the network immediately upon launch, set this key to ",
              "type": "text"
            },
            {
              "code": "YES",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKPrefersNetworkUponForeground",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " defaults to ",
              "type": "text"
            },
            {
              "code": "NO",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CLKComplicationSupportedFamilies": {
      "abstract": [
        {
          "text": "The complication families for which the app can provide data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "ideTitle": "ClockKit Complication - Supported Families",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CLKComplicationSupportedFamilies",
      "kind": "symbol",
      "name": "CLKComplicationSupportedFamilies",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationSupportedFamilies"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationSupportedFamilies",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/clkcomplicationsupportedfamilies"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSArchitecturePriority": {
      "abstract": [
        {
          "text": "An array of the architectures that the app supports, arranged according to their preferred usage.",
          "type": "text"
        }
      ],
      "ideTitle": "Architecture priority",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSArchitecturePriority",
      "kind": "symbol",
      "name": "LSArchitecturePriority",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSArchitecturePriority"
        }
      ],
      "role": "symbol",
      "title": "LSArchitecturePriority",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsarchitecturepriority"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMultipleInstancesProhibited": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether more than one user can launch the app simultaneously.",
          "type": "text"
        }
      ],
      "ideTitle": "Application prohibits multiple instances",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMultipleInstancesProhibited",
      "kind": "symbol",
      "name": "LSMultipleInstancesProhibited",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMultipleInstancesProhibited"
        }
      ],
      "role": "symbol",
      "title": "LSMultipleInstancesProhibited",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsmultipleinstancesprohibited"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSRequiresNativeExecution": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to require the execution of the app’s native architecture when multiple architectures are available.",
          "type": "text"
        }
      ],
      "ideTitle": "Application requires native environment",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSRequiresNativeExecution",
      "kind": "symbol",
      "name": "LSRequiresNativeExecution",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSRequiresNativeExecution"
        }
      ],
      "role": "symbol",
      "title": "LSRequiresNativeExecution",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsrequiresnativeexecution"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/PUICAutoLaunchAudioOptOut": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether a watchOS app should opt out of automatically launching when its companion iOS app starts playing audio content.",
          "type": "text"
        }
      ],
      "ideTitle": "Opt out of Auto-launch Audio App (Watch)",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/PUICAutoLaunchAudioOptOut",
      "kind": "symbol",
      "name": "PUICAutoLaunchAudioOptOut",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PUICAutoLaunchAudioOptOut"
        }
      ],
      "role": "symbol",
      "title": "PUICAutoLaunchAudioOptOut",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/puicautolaunchaudiooptout"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIRequiredDeviceCapabilities": {
      "abstract": [
        {
          "text": "The device-related features that your app requires to run.",
          "type": "text"
        }
      ],
      "ideTitle": "Required device capabilities",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIRequiredDeviceCapabilities",
      "kind": "symbol",
      "name": "UIRequiredDeviceCapabilities",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIRequiredDeviceCapabilities"
        }
      ],
      "role": "symbol",
      "title": "UIRequiredDeviceCapabilities",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uirequireddevicecapabilities"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKPrefersNetworkUponForeground": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether an app requires network access on launch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKPrefersNetworkUponForeground",
      "kind": "symbol",
      "name": "WKPrefersNetworkUponForeground",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKPrefersNetworkUponForeground"
        }
      ],
      "role": "symbol",
      "title": "WKPrefersNetworkUponForeground",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/wkprefersnetworkuponforeground"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKRunsIndependentlyOfCompanionApp": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the user can install and run the watchOS app independently of its iOS companion app.",
          "type": "text"
        }
      ],
      "ideTitle": "App can run independently of companion iPhone app",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKRunsIndependentlyOfCompanionApp",
      "kind": "symbol",
      "name": "WKRunsIndependentlyOfCompanionApp",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKRunsIndependentlyOfCompanionApp"
        }
      ],
      "role": "symbol",
      "title": "WKRunsIndependentlyOfCompanionApp",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/wkrunsindependentlyofcompanionapp"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKWatchOnly": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app is a watch-only app.",
          "type": "text"
        }
      ],
      "ideTitle": "App is only available as a standalone watchOS app",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKWatchOnly",
      "kind": "symbol",
      "name": "WKWatchOnly",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWatchOnly"
        }
      ],
      "role": "symbol",
      "title": "WKWatchOnly",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/wkwatchonly"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Launch-conditions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIRequiredDeviceCapabilities",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMultipleInstancesProhibited",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSArchitecturePriority",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSRequiresNativeExecution",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKRunsIndependentlyOfCompanionApp",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKWatchOnly",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/PUICAutoLaunchAudioOptOut",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CLKComplicationSupportedFamilies"
      ],
      "title": "Launch conditions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKPrefersNetworkUponForeground"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKPrefersNetworkUponForeground"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Launch-conditions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIRequiredDeviceCapabilities",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMultipleInstancesProhibited",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSArchitecturePriority",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSRequiresNativeExecution",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKRunsIndependentlyOfCompanionApp",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKWatchOnly",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/PUICAutoLaunchAudioOptOut",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CLKComplicationSupportedFamilies"
              ],
              "title": "Launch conditions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIRequiredDeviceCapabilities/title",
          "value": "UIRequiredDeviceCapabilities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIRequiredDeviceCapabilities/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRequiredDeviceCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKWatchOnly/title",
          "value": "WKWatchOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKWatchOnly/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWatchOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSArchitecturePriority/title",
          "value": "LSArchitecturePriority"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSArchitecturePriority/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSArchitecturePriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKRunsIndependentlyOfCompanionApp/title",
          "value": "WKRunsIndependentlyOfCompanionApp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKRunsIndependentlyOfCompanionApp/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKRunsIndependentlyOfCompanionApp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1PUICAutoLaunchAudioOptOut/title",
          "value": "PUICAutoLaunchAudioOptOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1PUICAutoLaunchAudioOptOut/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PUICAutoLaunchAudioOptOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKPrefersNetworkUponForeground/title",
          "value": "WKPrefersNetworkUponForeground"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKPrefersNetworkUponForeground/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKPrefersNetworkUponForeground"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CLKComplicationSupportedFamilies/title",
          "value": "CLKComplicationSupportedFamilies"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CLKComplicationSupportedFamilies/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationSupportedFamilies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSRequiresNativeExecution/title",
          "value": "LSRequiresNativeExecution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSRequiresNativeExecution/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSRequiresNativeExecution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSMultipleInstancesProhibited/title",
          "value": "LSMultipleInstancesProhibited"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSMultipleInstancesProhibited/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMultipleInstancesProhibited"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/wkprefersnetworkuponforeground"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/wkprefersnetworkuponforeground"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
