{
  "abstract": [
    {
      "text": "A Boolean value that determines whether the system displays the app in the Always On state.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKSupportsAlwaysOnDisplay"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.WKSupportsAlwaysOnDisplay",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKSupportsAlwaysOnDisplay"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "WKSupportsAlwaysOnDisplay"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "WKSupportsAlwaysOnDisplay",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "attributes": [
        {
          "kind": "default",
          "value": "YES"
        }
      ],
      "kind": "attributes",
      "title": "Attributes"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", the system displays the app in the Always On state when the app is the frontmost app or running an active background session. Apps compiled for watchOS 8 and later have Always On enabled by default; however, users can disable Always On for the entire device or on a per-app basis by selecting Settings > Display & Brightness > Always On.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "code": "Designing Your App for the Always On State",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKSupportsAlwaysOnDisplay": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the system displays the app in the Always On state.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKSupportsAlwaysOnDisplay",
      "kind": "symbol",
      "name": "WKSupportsAlwaysOnDisplay",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKSupportsAlwaysOnDisplay"
        }
      ],
      "role": "symbol",
      "title": "WKSupportsAlwaysOnDisplay",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/wksupportsalwaysondisplay"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKSupportsAlwaysOnDisplay"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKSupportsAlwaysOnDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKSupportsAlwaysOnDisplay/title",
          "value": "WKSupportsAlwaysOnDisplay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKSupportsAlwaysOnDisplay/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKSupportsAlwaysOnDisplay"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/wksupportsalwaysondisplay"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/wksupportsalwaysondisplay"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
