{"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avkit/documentation/AVKit","doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView"]]},"relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/s:SY","doc://com.externally.resolved.symbol/s:s8SendableP"]}],"metadata":{"platforms":[{"deprecated":false,"name":"macOS","beta":false,"introducedAt":"10.15","unavailable":false}],"roleHeading":"Enumeration","modules":[{"name":"AVKit"}],"symbolKind":"enum","extendedModule":"AVKit","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ButtonState","kind":"identifier"}],"navigatorTitle":[{"text":"ButtonState","kind":"identifier"}],"title":"AVRoutePickerView.ButtonState","externalID":"c:@E@AVRoutePickerViewButtonState"},"kind":"symbol","topicSections":[{"title":"Button States","identifiers":["doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/normal","doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/normalHighlighted","doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/active","doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/activeHighlighted"],"anchor":"Button-States"},{"generated":true,"title":"Initializers","identifiers":["doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/init(rawValue:)"],"anchor":"Initializers"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ButtonState"}],"platforms":["macOS"]}]}],"seeAlsoSections":[{"title":"Configuring the route picker view","identifiers":["doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/activeTintColor","doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/isRoutePickerButtonBordered","doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/prioritizesVideoDevices","doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/routePickerButtonStyle","doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewButtonStyle","doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/routePickerButtonColor(for:)","doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/setRoutePickerButtonColor(_:for:)"],"generated":true,"anchor":"Configuring-the-route-picker-view"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/avkit/avroutepickerview/buttonstate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/avkit/avroutepickerview/buttonstate"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Constants that describe the available button states."}],"identifier":{"url":"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState","interfaceLanguage":"swift"},"references":{"doc://com.externally.resolved.symbol/s:SH":{"kind":"symbol","abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"type":"topic","url":"/documentation/Swift/Hashable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hashable","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SQ","text":"Equatable","kind":"typeIdentifier"}],"role":"symbol","title":"Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH"},"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP":{"type":"topic","title":"BitwiseCopyable","url":"/documentation/Swift/BitwiseCopyable","role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BitwiseCopyable"},{"kind":"text","text":" : ~Escapable"}],"abstract":[{"type":"text","text":""}]},"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/active":{"role":"symbol","kind":"symbol","title":"AVRoutePickerView.ButtonState.active","type":"topic","navigatorTitle":[{"text":"AVRoutePickerViewButtonStateActive","kind":"identifier"}],"abstract":[{"type":"text","text":"The button state when AirPlay is active."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"active","kind":"identifier"}],"identifier":"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/active","url":"/documentation/avkit/avroutepickerview/buttonstate/active"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","title":"Technologies","role":"overview"},"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/routePickerButtonStyle":{"abstract":[{"type":"text","text":"The button style for the route picker."}],"role":"symbol","title":"routePickerButtonStyle","url":"/documentation/avkit/avroutepickerview/routepickerbuttonstyle","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"routePickerButtonStyle","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVRoutePickerViewButtonStyle","preciseIdentifier":"c:@E@AVRoutePickerViewButtonStyle"}],"identifier":"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/routePickerButtonStyle","kind":"symbol","navigatorTitle":[{"text":"routePickerButtonStyle","kind":"identifier"}]},"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/setRoutePickerButtonColor(_:for:)":{"identifier":"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/setRoutePickerButtonColor(_:for:)","title":"setRoutePickerButtonColor(_:for:)","abstract":[{"text":"Sets the route picker button color for the specified state.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRoutePickerButtonColor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSColor","preciseIdentifier":"c:objc(cs)NSColor"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVRoutePickerView","preciseIdentifier":"c:objc(cs)AVRoutePickerView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ButtonState","preciseIdentifier":"c:@E@AVRoutePickerViewButtonState"},{"kind":"text","text":")"}],"url":"/documentation/avkit/avroutepickerview/setroutepickerbuttoncolor(_:for:)","navigatorTitle":[{"kind":"identifier","text":"setRoutePickerButtonColor:forState:"}],"type":"topic"},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"type":"topic","title":"NSInteger","url":"/documentation/objectivec/nsinteger","role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"NSInteger"}],"abstract":[{"type":"text","text":"Describes an integer."}]},"doc://com.externally.resolved.symbol/s:SQ":{"identifier":"doc://com.externally.resolved.symbol/s:SQ","title":"Equatable","abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Equatable"}],"url":"/documentation/Swift/Equatable","type":"topic"},"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView":{"identifier":"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView","title":"AVRoutePickerView","abstract":[{"type":"text","text":"A view that presents a list of nearby media receivers."}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVRoutePickerView","kind":"identifier"}],"url":"/documentation/avkit/avroutepickerview","navigatorTitle":[{"text":"AVRoutePickerView","kind":"identifier"}],"type":"topic"},"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/routePickerButtonColor(for:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"routePickerButtonColor"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVRoutePickerView","text":"AVRoutePickerView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AVRoutePickerViewButtonState","text":"ButtonState"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSColor","text":"NSColor"}],"role":"symbol","type":"topic","url":"/documentation/avkit/avroutepickerview/routepickerbuttoncolor(for:)","abstract":[{"text":"Returns the color of the picker button for the specified state.","type":"text"}],"identifier":"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/routePickerButtonColor(for:)","navigatorTitle":[{"kind":"identifier","text":"routePickerButtonColorForState:"}],"title":"routePickerButtonColor(for:)","kind":"symbol"},"doc://com.externally.resolved.symbol/s:s8SendableP":{"type":"topic","title":"Sendable","url":"/documentation/Swift/Sendable","role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Sendable"}],"abstract":[{"type":"text","text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races."}]},"doc://com.apple.avkit/documentation/AVKit":{"identifier":"doc://com.apple.avkit/documentation/AVKit","type":"topic","url":"/documentation/avkit","abstract":[{"type":"text","text":"Create user interfaces for media playback, complete with transport controls, chapter navigation, picture-in-picture support, and display of subtitles and closed captions."}],"kind":"symbol","title":"AVKit","role":"collection"},"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/activeHighlighted":{"abstract":[{"text":"The highlighted button state when AirPlay is active.","type":"text"}],"type":"topic","url":"/documentation/avkit/avroutepickerview/buttonstate/activehighlighted","title":"AVRoutePickerView.ButtonState.activeHighlighted","identifier":"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/activeHighlighted","kind":"symbol","navigatorTitle":[{"text":"AVRoutePickerViewButtonStateActiveHighlighted","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activeHighlighted","kind":"identifier"}],"role":"symbol"},"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/normalHighlighted":{"role":"symbol","kind":"symbol","title":"AVRoutePickerView.ButtonState.normalHighlighted","type":"topic","navigatorTitle":[{"text":"AVRoutePickerViewButtonStateNormalHighlighted","kind":"identifier"}],"abstract":[{"type":"text","text":"The highlighted button state when a mouse-down event occurs inside the button."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"normalHighlighted"}],"identifier":"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/normalHighlighted","url":"/documentation/avkit/avroutepickerview/buttonstate/normalhighlighted"},"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/init(rawValue:)":{"type":"topic","kind":"symbol","title":"init(rawValue:)","role":"symbol","url":"/documentation/avkit/avroutepickerview/buttonstate/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/init(rawValue:)","abstract":[]},"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/isRoutePickerButtonBordered":{"role":"symbol","identifier":"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/isRoutePickerButtonBordered","kind":"symbol","title":"isRoutePickerButtonBordered","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isRoutePickerButtonBordered","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"routePickerButtonBordered"}],"url":"/documentation/avkit/avroutepickerview/isroutepickerbuttonbordered","type":"topic","abstract":[{"type":"text","text":"A Boolean value that indicates whether the route picker button has a border."}]},"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/activeTintColor":{"url":"/documentation/avkit/avroutepickerview/activetintcolor","abstract":[{"type":"text","text":"The view’s tint color when AirPlay is active."}],"identifier":"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/activeTintColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activeTintColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"activeTintColor","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","title":"activeTintColor"},"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/normal":{"type":"topic","kind":"symbol","title":"AVRoutePickerView.ButtonState.normal","role":"symbol","url":"/documentation/avkit/avroutepickerview/buttonstate/normal","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"normal","kind":"identifier"}],"identifier":"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/normal","abstract":[{"type":"text","text":"The normal, or default, button state."}],"navigatorTitle":[{"text":"AVRoutePickerViewButtonStateNormal","kind":"identifier"}]},"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewButtonStyle":{"identifier":"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewButtonStyle","navigatorTitle":[{"kind":"identifier","text":"AVRoutePickerViewButtonStyle"}],"title":"AVRoutePickerViewButtonStyle","kind":"symbol","url":"/documentation/avkit/avroutepickerviewbuttonstyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVRoutePickerViewButtonStyle"}],"type":"topic","role":"symbol","abstract":[{"text":"Constants that define the button styles a route picker view supports.","type":"text"}]},"doc://com.externally.resolved.symbol/s:SY":{"type":"topic","title":"RawRepresentable","url":"/documentation/Swift/RawRepresentable","role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SY","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RawRepresentable"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:SY8RawValueQa","text":"RawValue"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"A type that can be converted to and from an associated raw value."}]},"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/prioritizesVideoDevices":{"title":"prioritizesVideoDevices","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prioritizesVideoDevices","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"A Boolean value that indicates whether the route picker sorts video output devices to the top of the list."}],"identifier":"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/prioritizesVideoDevices","role":"symbol","url":"/documentation/avkit/avroutepickerview/prioritizesvideodevices","kind":"symbol","type":"topic","navigatorTitle":[{"text":"prioritizesVideoDevices","kind":"identifier"}]},"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState":{"type":"topic","title":"AVRoutePickerView.ButtonState","url":"/documentation/avkit/avroutepickerview/buttonstate","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ButtonState"}],"identifier":"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ButtonState"}],"abstract":[{"type":"text","text":"Constants that describe the available button states."}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"introducedAt":"10.15","deprecated":false,"beta":false,"name":"macOS","unavailable":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Enumeration"},{"path":"/metadata/title","op":"replace","value":"AVRoutePickerViewButtonState"},{"path":"/metadata/symbolKind","op":"replace","value":"enum"},{"value":[{"text":"AVRoutePickerViewButtonState","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":[{"kind":"identifier","text":"AVRoutePickerViewButtonState"}],"op":"replace","path":"/metadata/navigatorTitle"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avkit/documentation/AVKit"]]},"op":"replace","path":"/hierarchy"},{"path":"/topicSections","value":[{"identifiers":["doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/normal","doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/normalHighlighted","doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/active","doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/activeHighlighted"],"title":"Button States","anchor":"Button-States"}],"op":"replace"},{"path":"/relationshipsSections","value":null,"op":"replace"},{"path":"/seeAlsoSections","value":[{"title":"Configuring the route picker view","generated":true,"anchor":"Configuring-the-route-picker-view","identifiers":["doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/activeTintColor","doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/isRoutePickerButtonBordered","doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/prioritizesVideoDevices","doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/routePickerButtonStyle","doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewButtonStyle","doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/routePickerButtonColor(for:)","doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/setRoutePickerButtonColor(_:for:)"]}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVRoutePickerViewButtonState"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}],"kind":"declarations"},"op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState~1active/title","value":"AVRoutePickerViewButtonStateActive","op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState~1active/fragments","value":[{"kind":"identifier","text":"AVRoutePickerViewButtonStateActive"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1routePickerButtonStyle/title","value":"routePickerButtonStyle","op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1routePickerButtonStyle/fragments","value":[{"text":"routePickerButtonStyle","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1setRoutePickerButtonColor(_:for:)/title","value":"setRoutePickerButtonColor:forState:","op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1setRoutePickerButtonColor(_:for:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setRoutePickerButtonColor:forState:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView/title","value":"AVRoutePickerView","op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView/fragments","value":[{"kind":"identifier","text":"AVRoutePickerView"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView/navigatorTitle","value":[{"text":"AVRoutePickerView","kind":"identifier"}],"op":"replace"},{"value":"routePickerButtonColorForState:","path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1routePickerButtonColor(for:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"routePickerButtonColorForState:"}],"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1routePickerButtonColor(for:)/fragments","op":"replace"},{"value":"AVRoutePickerViewButtonStateActiveHighlighted","path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState~1activeHighlighted/title","op":"replace"},{"value":[{"kind":"identifier","text":"AVRoutePickerViewButtonStateActiveHighlighted"}],"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState~1activeHighlighted/fragments","op":"replace"},{"value":"AVRoutePickerViewButtonStateNormalHighlighted","path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState~1normalHighlighted/title","op":"replace"},{"value":[{"text":"AVRoutePickerViewButtonStateNormalHighlighted","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState~1normalHighlighted/fragments","op":"replace"},{"value":"routePickerButtonBordered","path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1isRoutePickerButtonBordered/title","op":"replace"},{"value":[{"kind":"identifier","text":"routePickerButtonBordered"}],"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1isRoutePickerButtonBordered/fragments","op":"replace"},{"value":"activeTintColor","path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1activeTintColor/title","op":"replace"},{"value":[{"kind":"identifier","text":"activeTintColor"}],"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1activeTintColor/fragments","op":"replace"},{"value":"AVRoutePickerViewButtonStateNormal","path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState~1normal/title","op":"replace"},{"value":[{"text":"AVRoutePickerViewButtonStateNormal","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState~1normal/fragments","op":"replace"},{"value":"AVRoutePickerViewButtonStyle","path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerViewButtonStyle/title","op":"replace"},{"value":[{"text":"AVRoutePickerViewButtonStyle","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerViewButtonStyle/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AVRoutePickerViewButtonStyle"}],"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerViewButtonStyle/navigatorTitle","op":"replace"},{"value":"prioritizesVideoDevices","path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1prioritizesVideoDevices/title","op":"replace"},{"value":[{"kind":"identifier","text":"prioritizesVideoDevices"}],"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1prioritizesVideoDevices/fragments","op":"replace"},{"value":"AVRoutePickerViewButtonState","path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState/title","op":"replace"},{"value":[{"kind":"identifier","text":"AVRoutePickerViewButtonState"}],"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AVRoutePickerViewButtonState"}],"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}