{
  "abstract": [
    {
      "text": "A Boolean value that indicates whether the route picker button has a border.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avkit/documentation/AVKit",
        "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/isRoutePickerButtonBordered"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVRoutePickerView(py)routePickerButtonBordered",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "isRoutePickerButtonBordered"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "AVKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "routePickerButtonBordered"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "isRoutePickerButtonBordered"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "isRoutePickerButtonBordered"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The default value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avkit/documentation/AVKit": {
      "abstract": [
        {
          "text": "Create user interfaces for media playback, complete with transport controls, chapter navigation, picture-in-picture support, and display of subtitles and closed captions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AVKit",
      "type": "topic",
      "url": "/documentation/avkit"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView": {
      "abstract": [
        {
          "text": "A view that presents a list of nearby media receivers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVRoutePickerView"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVRoutePickerView"
        }
      ],
      "role": "symbol",
      "title": "AVRoutePickerView",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerview"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState": {
      "abstract": [
        {
          "text": "Constants that describe the available button states.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ButtonState"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ButtonState"
        }
      ],
      "role": "symbol",
      "title": "AVRoutePickerView.ButtonState",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerview/buttonstate"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/activeTintColor": {
      "abstract": [
        {
          "text": "The view’s tint color when AirPlay is active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activeTintColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/activeTintColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activeTintColor"
        }
      ],
      "role": "symbol",
      "title": "activeTintColor",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerview/activetintcolor"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/isRoutePickerButtonBordered": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the route picker button has a border.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isRoutePickerButtonBordered"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/isRoutePickerButtonBordered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "routePickerButtonBordered"
        }
      ],
      "role": "symbol",
      "title": "isRoutePickerButtonBordered",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerview/isroutepickerbuttonbordered"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/prioritizesVideoDevices": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the route picker sorts video output devices to the top of the list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prioritizesVideoDevices"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/prioritizesVideoDevices",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prioritizesVideoDevices"
        }
      ],
      "role": "symbol",
      "title": "prioritizesVideoDevices",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerview/prioritizesvideodevices"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/routePickerButtonColor(for:)": {
      "abstract": [
        {
          "text": "Returns the color of the picker button for the specified state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "routePickerButtonColor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVRoutePickerView",
          "text": "AVRoutePickerView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVRoutePickerViewButtonState",
          "text": "ButtonState"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/routePickerButtonColor(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "routePickerButtonColorForState:"
        }
      ],
      "role": "symbol",
      "title": "routePickerButtonColor(for:)",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerview/routepickerbuttoncolor(for:)"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/routePickerButtonStyle": {
      "abstract": [
        {
          "text": "The button style for the route picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "routePickerButtonStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVRoutePickerViewButtonStyle",
          "text": "AVRoutePickerViewButtonStyle"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/routePickerButtonStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "routePickerButtonStyle"
        }
      ],
      "role": "symbol",
      "title": "routePickerButtonStyle",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerview/routepickerbuttonstyle"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/setRoutePickerButtonColor(_:for:)": {
      "abstract": [
        {
          "text": "Sets the route picker button color for the specified state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setRoutePickerButtonColor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVRoutePickerView",
          "text": "AVRoutePickerView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVRoutePickerViewButtonState",
          "text": "ButtonState"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/setRoutePickerButtonColor(_:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setRoutePickerButtonColor:forState:"
        }
      ],
      "role": "symbol",
      "title": "setRoutePickerButtonColor(_:for:)",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerview/setroutepickerbuttoncolor(_:for:)"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewButtonStyle": {
      "abstract": [
        {
          "text": "Constants that define the button styles a route picker view supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVRoutePickerViewButtonStyle"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewButtonStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVRoutePickerViewButtonStyle"
        }
      ],
      "role": "symbol",
      "title": "AVRoutePickerViewButtonStyle",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerviewbuttonstyle"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-route-picker-view",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/activeTintColor",
        "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/prioritizesVideoDevices",
        "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/routePickerButtonStyle",
        "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewButtonStyle",
        "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/routePickerButtonColor(for:)",
        "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/setRoutePickerButtonColor(_:for:)",
        "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState"
      ],
      "title": "Configuring the route picker view"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "routePickerButtonBordered"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "routePickerButtonBordered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avkit/documentation/AVKit",
                "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-route-picker-view",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/activeTintColor",
                "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/prioritizesVideoDevices",
                "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/routePickerButtonStyle",
                "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewButtonStyle",
                "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/routePickerButtonColor(for:)",
                "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/setRoutePickerButtonColor(_:for:)",
                "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState"
              ],
              "title": "Configuring the route picker view"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "getter"
                  },
                  {
                    "kind": "text",
                    "text": "="
                  },
                  {
                    "kind": "identifier",
                    "text": "isRoutePickerButtonBordered"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "routePickerButtonBordered"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1routePickerButtonStyle/title",
          "value": "routePickerButtonStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1routePickerButtonStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "routePickerButtonStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState/title",
          "value": "AVRoutePickerViewButtonState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerViewButtonState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerViewButtonState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1routePickerButtonColor(for:)/title",
          "value": "routePickerButtonColorForState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1routePickerButtonColor(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "routePickerButtonColorForState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1isRoutePickerButtonBordered/title",
          "value": "routePickerButtonBordered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1isRoutePickerButtonBordered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "routePickerButtonBordered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView/title",
          "value": "AVRoutePickerView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1setRoutePickerButtonColor(_:for:)/title",
          "value": "setRoutePickerButtonColor:forState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1setRoutePickerButtonColor(_:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setRoutePickerButtonColor:forState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1activeTintColor/title",
          "value": "activeTintColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1activeTintColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activeTintColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1prioritizesVideoDevices/title",
          "value": "prioritizesVideoDevices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1prioritizesVideoDevices/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "prioritizesVideoDevices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerViewButtonStyle/title",
          "value": "AVRoutePickerViewButtonStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerViewButtonStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerViewButtonStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerViewButtonStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerViewButtonStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avkit/avroutepickerview/isroutepickerbuttonbordered"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avkit/avroutepickerview/isroutepickerbuttonbordered"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
