{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResults"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResults/results"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@BluetoothHCIInquiryResults@FI@results",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "results"
      },
      {
        "kind": "text",
        "text": ": ("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
        "text": "BluetoothHCIInquiryResult"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "results"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "results"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "results"
            },
            {
              "kind": "text",
              "text": ": ("
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
              "text": "BluetoothHCIInquiryResult"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothHCIInquiryResult"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothHCIInquiryResult"
        }
      ],
      "role": "symbol",
      "title": "BluetoothHCIInquiryResult",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhciinquiryresult"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResults": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothHCIInquiryResults"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResults",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothHCIInquiryResults"
        }
      ],
      "role": "symbol",
      "title": "BluetoothHCIInquiryResults",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhciinquiryresults"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResults/results": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "results"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
          "text": "BluetoothHCIInquiryResult"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResults/results",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "results"
        }
      ],
      "role": "symbol",
      "title": "results",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhciinquiryresults/results"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "results"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "results"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResults"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@BluetoothHCIInquiryResult",
                    "text": "BluetoothHCIInquiryResult"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "results"
                  },
                  {
                    "kind": "text",
                    "text": "["
                  },
                  {
                    "kind": "number",
                    "text": "50"
                  },
                  {
                    "kind": "text",
                    "text": "];"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIInquiryResults~1results/title",
          "value": "results"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIInquiryResults~1results/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "results"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIInquiryResults/title",
          "value": "BluetoothHCIInquiryResults"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIInquiryResults/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIInquiryResults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIInquiryResults/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIInquiryResults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIInquiryResult/title",
          "value": "BluetoothHCIInquiryResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIInquiryResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIInquiryResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIInquiryResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIInquiryResult"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/bluetoothhciinquiryresults/results"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/bluetoothhciinquiryresults/results"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
