{
  "abstract": [
    {
      "text": "A constant that accounts for all ruby positions during ruby annotation creation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText",
        "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition/count"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CTRubyPosition@kCTRubyPositionCount",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "count"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCTRubyPositionCount"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CTRubyPosition.count"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "count"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you create a ruby annotation using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyAnnotationCreate(_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", use this constant to allocate an array of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfstring",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " texts that contains a sufficient number of elements for each ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyAnnotationCreate(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates an immutable ruby annotation object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRubyAnnotationCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTRubyAlignment",
          "text": "CTRubyAlignment"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTRubyOverhang",
          "text": "CTRubyOverhang"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTRubyAnnotationRef",
          "text": "CTRubyAnnotation"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyAnnotationCreate(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRubyAnnotationCreate"
        }
      ],
      "role": "symbol",
      "title": "CTRubyAnnotationCreate(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyannotationcreate(_:_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition": {
      "abstract": [
        {
          "text": "Constants that specify the position of the ruby text relative to to the base text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRubyPosition"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRubyPosition"
        }
      ],
      "role": "symbol",
      "title": "CTRubyPosition",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyposition"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition/after": {
      "abstract": [
        {
          "text": "The ruby text is positioned after the base text, appearing below horizontal text and to the left of vertical text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "after"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition/after",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTRubyPositionAfter"
        }
      ],
      "role": "symbol",
      "title": "CTRubyPosition.after",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyposition/after"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition/before": {
      "abstract": [
        {
          "text": "The ruby text is positioned before the base text, appearing above horizontal text and to the right of vertical text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "before"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition/before",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTRubyPositionBefore"
        }
      ],
      "role": "symbol",
      "title": "CTRubyPosition.before",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyposition/before"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition/count": {
      "abstract": [
        {
          "text": "A constant that accounts for all ruby positions during ruby annotation creation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "count"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition/count",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTRubyPositionCount"
        }
      ],
      "role": "symbol",
      "title": "CTRubyPosition.count",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyposition/count"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition/inline": {
      "abstract": [
        {
          "text": "The ruby text follows the base text with no special styling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inline"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition/inline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTRubyPositionInline"
        }
      ],
      "role": "symbol",
      "title": "CTRubyPosition.inline",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyposition/inline"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition/interCharacter": {
      "abstract": [
        {
          "text": "The ruby text is positioned to the right of the base text, regardless of whether it’s horizontal or vertical.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interCharacter"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition/interCharacter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTRubyPositionInterCharacter"
        }
      ],
      "role": "symbol",
      "title": "CTRubyPosition.interCharacter",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyposition/intercharacter"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cfstring": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition/before",
        "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition/after",
        "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition/interCharacter",
        "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition/inline"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCTRubyPositionCount"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTRubyPositionCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText",
                "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition/before",
                "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition/after",
                "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition/interCharacter",
                "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition/inline"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCTRubyPositionCount"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~1cfstring/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyPosition~1before/title",
          "value": "kCTRubyPositionBefore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyPosition~1before/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTRubyPositionBefore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyPosition~1count/title",
          "value": "kCTRubyPositionCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyPosition~1count/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTRubyPositionCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyPosition~1interCharacter/title",
          "value": "kCTRubyPositionInterCharacter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyPosition~1interCharacter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTRubyPositionInterCharacter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyPosition~1inline/title",
          "value": "kCTRubyPositionInline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyPosition~1inline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTRubyPositionInline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyPosition~1after/title",
          "value": "kCTRubyPositionAfter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyPosition~1after/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTRubyPositionAfter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyPosition/title",
          "value": "CTRubyPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRubyPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyPosition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRubyPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAnnotationCreate(_:_:_:_:)/title",
          "value": "CTRubyAnnotationCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAnnotationCreate(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRubyAnnotationCreate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctrubyposition/count"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctrubyposition/count"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
