{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.modelio/documentation/ModelIO",
        "doc://com.apple.modelio/documentation/ModelIO/MDLIndexBitDepth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.modelio/documentation/ModelIO/MDLIndexBitDepth/uint8-swift.type.property"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MDLIndexBitDepth@MDLIndexBitDepthUint8",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "uint8"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MDLIndexBitDepth",
        "text": "MDLIndexBitDepth"
      }
    ],
    "modules": [
      {
        "name": "Model I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MDLIndexBitDepthUint8"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "uint8"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "uint8"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLIndexBitDepth",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MDLIndexBitDepth",
              "text": "MDLIndexBitDepth"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.modelio/documentation/ModelIO": {
      "abstract": [
        {
          "text": "Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Model I/O",
      "type": "topic",
      "url": "/documentation/modelio"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLIndexBitDepth": {
      "abstract": [
        {
          "text": "Options for the size of integer data in a submesh’s index buffer, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/indexType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLIndexBitDepth"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLIndexBitDepth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLIndexBitDepth"
        }
      ],
      "role": "symbol",
      "title": "MDLIndexBitDepth",
      "type": "topic",
      "url": "/documentation/modelio/mdlindexbitdepth"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLIndexBitDepth/uint8-swift.type.property": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uint8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLIndexBitDepth",
          "text": "MDLIndexBitDepth"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLIndexBitDepth/uint8-swift.type.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLIndexBitDepthUint8"
        }
      ],
      "role": "symbol",
      "title": "uint8",
      "type": "topic",
      "url": "/documentation/modelio/mdlindexbitdepth/uint8-swift.type.property"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/indexType": {
      "abstract": [
        {
          "text": "The data type for each element in the submesh’s index buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indexType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLIndexBitDepth",
          "text": "MDLIndexBitDepth"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/indexType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "indexType"
        }
      ],
      "role": "symbol",
      "title": "indexType",
      "type": "topic",
      "url": "/documentation/modelio/mdlsubmesh/indextype"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MDLIndexBitDepthUint8"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLIndexBitDepthUint8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.modelio/documentation/ModelIO",
                "doc://com.apple.modelio/documentation/ModelIO/MDLIndexBitDepth"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MDLIndexBitDepthUint8"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLIndexBitDepth/title",
          "value": "MDLIndexBitDepth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLIndexBitDepth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLIndexBitDepth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLIndexBitDepth/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLIndexBitDepth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh~1indexType/title",
          "value": "indexType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh~1indexType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "indexType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLIndexBitDepth~1uint8-swift.type.property/title",
          "value": "MDLIndexBitDepthUint8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLIndexBitDepth~1uint8-swift.type.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLIndexBitDepthUint8"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/modelio/mdlindexbitdepth/uint8-swift.type.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/modelio/mdlindexbitdepth/uint8-swift.type.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
