{
  "abstract": [
    {
      "text": "The value for Friday.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKWeekday/friday",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.eventkit/documentation/EventKit",
        "doc://com.apple.eventkit/documentation/EventKit/EKWeekday"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.eventkit/documentation/EventKit/EKWeekday/EKFriday"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@EKWeekday@EKFriday",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "EKFriday"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@EKWeekday",
        "text": "EKWeekday"
      }
    ],
    "modules": [
      {
        "name": "EventKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "EKFriday"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "4.0",
        "message": "Use EKWeekdayFriday instead",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "4.0",
        "message": "Use EKWeekdayFriday instead",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "Use EKWeekdayFriday instead",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.11",
        "introducedAt": "10.8",
        "message": "Use EKWeekdayFriday instead",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Use EKWeekdayFriday instead",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "2.0",
        "introducedAt": "2.0",
        "message": "Use EKWeekdayFriday instead",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "EKFriday"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "EKFriday"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKWeekday",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@EKWeekday",
              "text": "EKWeekday"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.eventkit/documentation/EventKit/creating-a-recurring-event"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.eventkit/documentation/EventKit": {
      "abstract": [
        {
          "text": "Create, view, and edit calendar and reminder events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit",
      "kind": "symbol",
      "role": "collection",
      "title": "EventKit",
      "type": "topic",
      "url": "/documentation/eventkit"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKWeekday": {
      "abstract": [
        {
          "text": "The day of the week.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKWeekday"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKWeekday",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKWeekday"
        }
      ],
      "role": "symbol",
      "title": "EKWeekday",
      "type": "topic",
      "url": "/documentation/eventkit/ekweekday"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKWeekday/EKFriday": {
      "abstract": [
        {
          "text": "The value for Friday.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKFriday"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKWeekday",
          "text": "EKWeekday"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKWeekday/EKFriday",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKFriday"
        }
      ],
      "role": "symbol",
      "title": "EKFriday",
      "type": "topic",
      "url": "/documentation/eventkit/ekweekday/ekfriday"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKWeekday/EKMonday": {
      "abstract": [
        {
          "text": "The value for Monday.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKMonday"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKWeekday",
          "text": "EKWeekday"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKWeekday/EKMonday",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKMonday"
        }
      ],
      "role": "symbol",
      "title": "EKMonday",
      "type": "topic",
      "url": "/documentation/eventkit/ekweekday/ekmonday"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKWeekday/EKSaturday": {
      "abstract": [
        {
          "text": "The value for Saturday.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKSaturday"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKWeekday",
          "text": "EKWeekday"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKWeekday/EKSaturday",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKSaturday"
        }
      ],
      "role": "symbol",
      "title": "EKSaturday",
      "type": "topic",
      "url": "/documentation/eventkit/ekweekday/eksaturday"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKWeekday/EKSunday": {
      "abstract": [
        {
          "text": "The value for Sunday.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKSunday"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKWeekday",
          "text": "EKWeekday"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKWeekday/EKSunday",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKSunday"
        }
      ],
      "role": "symbol",
      "title": "EKSunday",
      "type": "topic",
      "url": "/documentation/eventkit/ekweekday/eksunday"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKWeekday/EKThursday": {
      "abstract": [
        {
          "text": "The value for Thursday.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKThursday"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKWeekday",
          "text": "EKWeekday"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKWeekday/EKThursday",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKThursday"
        }
      ],
      "role": "symbol",
      "title": "EKThursday",
      "type": "topic",
      "url": "/documentation/eventkit/ekweekday/ekthursday"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKWeekday/EKTuesday": {
      "abstract": [
        {
          "text": "The value for Tuesday.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKTuesday"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKWeekday",
          "text": "EKWeekday"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKWeekday/EKTuesday",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKTuesday"
        }
      ],
      "role": "symbol",
      "title": "EKTuesday",
      "type": "topic",
      "url": "/documentation/eventkit/ekweekday/ektuesday"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKWeekday/EKWednesday": {
      "abstract": [
        {
          "text": "The value for Wednesday.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKWednesday"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKWeekday",
          "text": "EKWeekday"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKWeekday/EKWednesday",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKWednesday"
        }
      ],
      "role": "symbol",
      "title": "EKWednesday",
      "type": "topic",
      "url": "/documentation/eventkit/ekweekday/ekwednesday"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKWeekday/friday": {
      "abstract": [
        {
          "text": "The value for Friday.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "friday"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKWeekday/friday",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKWeekdayFriday"
        }
      ],
      "role": "symbol",
      "title": "EKWeekday.friday",
      "type": "topic",
      "url": "/documentation/eventkit/ekweekday/friday"
    },
    "doc://com.apple.eventkit/documentation/EventKit/creating-a-recurring-event": {
      "abstract": [
        {
          "text": "Set up an event or reminder that repeats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/creating-a-recurring-event",
      "kind": "article",
      "role": "article",
      "title": "Creating a recurring event",
      "type": "topic",
      "url": "/documentation/eventkit/creating-a-recurring-event"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated",
      "generated": true,
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKWeekday/EKSunday",
        "doc://com.apple.eventkit/documentation/EventKit/EKWeekday/EKMonday",
        "doc://com.apple.eventkit/documentation/EventKit/EKWeekday/EKTuesday",
        "doc://com.apple.eventkit/documentation/EventKit/EKWeekday/EKWednesday",
        "doc://com.apple.eventkit/documentation/EventKit/EKWeekday/EKThursday",
        "doc://com.apple.eventkit/documentation/EventKit/EKWeekday/EKSaturday"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.11",
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "2.0",
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "EKFriday"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKFriday"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.eventkit/documentation/EventKit",
                "doc://com.apple.eventkit/documentation/EventKit/EKWeekday"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated",
              "generated": true,
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/EKWeekday/EKSunday",
                "doc://com.apple.eventkit/documentation/EventKit/EKWeekday/EKMonday",
                "doc://com.apple.eventkit/documentation/EventKit/EKWeekday/EKTuesday",
                "doc://com.apple.eventkit/documentation/EventKit/EKWeekday/EKWednesday",
                "doc://com.apple.eventkit/documentation/EventKit/EKWeekday/EKThursday",
                "doc://com.apple.eventkit/documentation/EventKit/EKWeekday/EKSaturday"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "EKFriday"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKWeekday/friday",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKWeekday~1EKFriday/title",
          "value": "EKFriday"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKWeekday~1EKFriday/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKFriday"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKWeekday~1EKSaturday/title",
          "value": "EKSaturday"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKWeekday~1EKSaturday/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKSaturday"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKWeekday~1EKTuesday/title",
          "value": "EKTuesday"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKWeekday~1EKTuesday/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKTuesday"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKWeekday~1EKSunday/title",
          "value": "EKSunday"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKWeekday~1EKSunday/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKSunday"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKWeekday~1EKWednesday/title",
          "value": "EKWednesday"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKWeekday~1EKWednesday/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKWednesday"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKWeekday/title",
          "value": "EKWeekday"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKWeekday/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKWeekday"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKWeekday/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKWeekday"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKWeekday~1friday/title",
          "value": "EKWeekdayFriday"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKWeekday~1friday/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKWeekdayFriday"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKWeekday~1EKThursday/title",
          "value": "EKThursday"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKWeekday~1EKThursday/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKThursday"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKWeekday~1EKMonday/title",
          "value": "EKMonday"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKWeekday~1EKMonday/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKMonday"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/eventkit/ekweekday/ekfriday"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/eventkit/ekweekday/ekfriday"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
