{
  "abstract": [
    {
      "text": "The system displays the control’s options through a popover.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem",
        "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum/collapsed"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSPickerTouchBarItemControlRepresentation@NSPickerTouchBarItemControlRepresentationCollapsed",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "collapsed"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSPickerTouchBarItemControlRepresentationCollapsed"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSPickerTouchBarItem.ControlRepresentation.collapsed"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "collapsed"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem": {
      "abstract": [
        {
          "text": "A bar item that provides a picker control with multiple options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPickerTouchBarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPickerTouchBarItem"
        }
      ],
      "role": "symbol",
      "title": "NSPickerTouchBarItem",
      "type": "topic",
      "url": "/documentation/appkit/nspickertouchbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum": {
      "abstract": [
        {
          "text": "Constants that specify display styles for picker bar items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ControlRepresentation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ControlRepresentation"
        }
      ],
      "role": "symbol",
      "title": "NSPickerTouchBarItem.ControlRepresentation",
      "type": "topic",
      "url": "/documentation/appkit/nspickertouchbaritem/controlrepresentation-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum/automatic": {
      "abstract": [
        {
          "text": "The system dynamically changes the display mode based on the available space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPickerTouchBarItemControlRepresentationAutomatic"
        }
      ],
      "role": "symbol",
      "title": "NSPickerTouchBarItem.ControlRepresentation.automatic",
      "type": "topic",
      "url": "/documentation/appkit/nspickertouchbaritem/controlrepresentation-swift.enum/automatic"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum/collapsed": {
      "abstract": [
        {
          "text": "The system displays the control’s options through a popover.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collapsed"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum/collapsed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPickerTouchBarItemControlRepresentationCollapsed"
        }
      ],
      "role": "symbol",
      "title": "NSPickerTouchBarItem.ControlRepresentation.collapsed",
      "type": "topic",
      "url": "/documentation/appkit/nspickertouchbaritem/controlrepresentation-swift.enum/collapsed"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum/expanded": {
      "abstract": [
        {
          "text": "The system displays the control and all of its options directly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expanded"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum/expanded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPickerTouchBarItemControlRepresentationExpanded"
        }
      ],
      "role": "symbol",
      "title": "NSPickerTouchBarItem.ControlRepresentation.expanded",
      "type": "topic",
      "url": "/documentation/appkit/nspickertouchbaritem/controlrepresentation-swift.enum/expanded"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Display-styles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum/automatic",
        "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum/expanded"
      ],
      "title": "Display styles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSPickerTouchBarItemControlRepresentationCollapsed"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItemControlRepresentationCollapsed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Display-styles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum/automatic",
                "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum/expanded"
              ],
              "title": "Display styles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSPickerTouchBarItemControlRepresentationCollapsed"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1ControlRepresentation-swift.enum~1expanded/title",
          "value": "NSPickerTouchBarItemControlRepresentationExpanded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1ControlRepresentation-swift.enum~1expanded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItemControlRepresentationExpanded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem/title",
          "value": "NSPickerTouchBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1ControlRepresentation-swift.enum~1automatic/title",
          "value": "NSPickerTouchBarItemControlRepresentationAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1ControlRepresentation-swift.enum~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItemControlRepresentationAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1ControlRepresentation-swift.enum~1collapsed/title",
          "value": "NSPickerTouchBarItemControlRepresentationCollapsed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1ControlRepresentation-swift.enum~1collapsed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItemControlRepresentationCollapsed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1ControlRepresentation-swift.enum/title",
          "value": "NSPickerTouchBarItemControlRepresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1ControlRepresentation-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItemControlRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1ControlRepresentation-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItemControlRepresentation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nspickertouchbaritem/controlrepresentation-swift.enum/collapsed"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nspickertouchbaritem/controlrepresentation-swift.enum/collapsed"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
