{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/appkit/nsaccessibilitystatictext/accessibilityvalue()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsaccessibilitystatictext/accessibilityvalue()"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityAttributedString(for:)","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityVisibleCharacterRange()"],"title":"Supporting Accessibility","anchor":"Supporting-Accessibility"}],"sections":[],"abstract":[{"type":"text","text":"Returns the text that the accessibility element displays."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityValue","kind":"identifier"},{"text":"() -> ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:SS","preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}]},{"content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The text displayed by the element."}]}],"kind":"content"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"Discussion"},{"inlineContent":[{"text":"This method is the getter for the ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol","type":"reference","isActive":true},{"text":" protocol’s ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityValue"},{"text":" property.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","metadata":{"platforms":[{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS"}],"title":"accessibilityValue()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityValue"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"symbolKind":"method","externalID":"c:objc(pl)NSAccessibilityStaticText(im)accessibilityValue","roleHeading":"Instance Method","modules":[{"name":"AppKit"}],"navigatorTitle":[{"kind":"identifier","text":"accessibilityValue"}],"required":true},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityValue()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText"]]},"references":{"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText","navigatorTitle":[{"text":"NSAccessibilityStaticText","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSAccessibilityStaticText","kind":"identifier"}],"title":"NSAccessibilityStaticText","role":"symbol","abstract":[{"type":"text","text":"A role-based protocol that declares the minimum interface necessary for an accessibility element to act as static text."}],"kind":"symbol","type":"topic","url":"/documentation/appkit/nsaccessibilitystatictext"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityAttributedString(for:)":{"title":"accessibilityAttributedString(for:)","navigatorTitle":[{"text":"accessibilityAttributedStringForRange:","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityAttributedString(for:)","role":"symbol","url":"/documentation/appkit/nsaccessibilitystatictext/accessibilityattributedstring(for:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityAttributedString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRange","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"Returns the attributed substring for the specified range of characters.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityValue":{"role":"symbol","type":"topic","kind":"symbol","title":"accessibilityValue","abstract":[{"text":"The accessibility element’s value.","type":"text"}],"url":"/documentation/appkit/nsaccessibility-c.protocol/accessibilityvalue","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityValue","fragments":[{"text":"accessibilityValue","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityVisibleCharacterRange()":{"url":"/documentation/appkit/nsaccessibilitystatictext/accessibilityvisiblecharacterrange()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"accessibilityVisibleCharacterRange"}],"role":"symbol","type":"topic","title":"accessibilityVisibleCharacterRange()","abstract":[{"text":"Returns the range of visible characters in the document.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityVisibleCharacterRange"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NSRange"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityVisibleCharacterRange()"},"doc://com.externally.resolved.symbol/s:SS":{"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SS","url":"/documentation/Swift/String","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"String","kind":"identifier"}],"type":"topic","title":"String","role":"symbol","abstract":[{"text":"A Unicode string value that is a collection of characters.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityValue()":{"required":true,"title":"accessibilityValue()","url":"/documentation/appkit/nsaccessibilitystatictext/accessibilityvalue()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityValue"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityValue()","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Returns the text that the accessibility element displays."}],"navigatorTitle":[{"text":"accessibilityValue","kind":"identifier"}]},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","abstract":[{"text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"role":"symbol","fragments":[{"text":"class ","kind":"text"},{"text":"NSString","kind":"identifier"}],"title":"NSString","kind":"symbol","url":"/documentation/foundation/nsstring","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSAccessibilityProtocol","kind":"identifier"}],"url":"/documentation/appkit/nsaccessibilityprotocol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol","role":"symbol","title":"NSAccessibilityProtocol","kind":"symbol","abstract":[{"text":"The complete list of properties and methods for accessible elements.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityProtocol"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"deprecated":false,"beta":false,"name":"macOS","unavailable":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"accessibilityValue"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"accessibilityValue"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityValue"],"title":"Related Documentation","anchor":"Related-Documentation"},{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityAttributedString(for:)","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityVisibleCharacterRange()"],"title":"Supporting Accessibility","anchor":"Supporting-Accessibility"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityValue","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"}},{"path":"/primaryContentSections/1","value":{"kind":"content","content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The text displayed by the element."}]}]},"op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText/title","value":"NSAccessibilityStaticText"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText/fragments","value":[{"text":"NSAccessibilityStaticText","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText/navigatorTitle","value":[{"kind":"identifier","text":"NSAccessibilityStaticText"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText~1accessibilityAttributedString(for:)/title","value":"accessibilityAttributedStringForRange:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText~1accessibilityAttributedString(for:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"accessibilityAttributedStringForRange:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText~1accessibilityVisibleCharacterRange()/title","value":"accessibilityVisibleCharacterRange"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilityVisibleCharacterRange"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText~1accessibilityVisibleCharacterRange()/fragments"},{"value":"accessibilityValue","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText~1accessibilityValue()/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilityValue"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText~1accessibilityValue()/fragments"},{"value":[{"type":"text","text":"A static, plain-text Unicode string object."}],"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract"},{"value":"NSAccessibility","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/title"},{"value":[{"text":"NSAccessibility","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/fragments"},{"value":[{"text":"NSAccessibility","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}