{"seeAlsoSections":[{"title":"Supporting Accessibility","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityAttributedString(for:)","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityValue()"],"anchor":"Supporting-Accessibility","generated":true}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsaccessibilitystatictext/accessibilityvisiblecharacterrange()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsaccessibilitystatictext/accessibilityvisiblecharacterrange()"]}],"sections":[],"metadata":{"modules":[{"name":"AppKit"}],"roleHeading":"Instance Method","externalID":"c:objc(pl)NSAccessibilityStaticText(im)accessibilityVisibleCharacterRange","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityVisibleCharacterRange"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NSRange"}],"navigatorTitle":[{"text":"accessibilityVisibleCharacterRange","kind":"identifier"}],"role":"symbol","title":"accessibilityVisibleCharacterRange()","platforms":[{"deprecated":false,"beta":false,"unavailable":false,"name":"macOS"}],"symbolKind":"method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityVisibleCharacterRange"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NSRange"}],"platforms":["macOS"]}]},{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"The range of the visible characters in the document. This method should return the range for entire lines. Characters that are horizontally clipped are included in this range."}],"type":"paragraph"}],"kind":"content"},{"content":[{"anchor":"Discussion","text":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method is the getter for the "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol"},{"type":"text","text":" protocol’s "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityVisibleCharacterRange"},{"type":"text","text":" property."}]}],"kind":"content"}],"kind":"symbol","identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityVisibleCharacterRange()","interfaceLanguage":"swift"},"abstract":[{"text":"Returns the range of visible characters in the document.","type":"text"}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSAccessibilityProtocol","kind":"identifier"}],"url":"/documentation/appkit/nsaccessibilityprotocol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol","role":"symbol","title":"NSAccessibilityProtocol","kind":"symbol","abstract":[{"text":"The complete list of properties and methods for accessible elements.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityProtocol"}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityVisibleCharacterRange()":{"url":"/documentation/appkit/nsaccessibilitystatictext/accessibilityvisiblecharacterrange()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"accessibilityVisibleCharacterRange"}],"role":"symbol","type":"topic","title":"accessibilityVisibleCharacterRange()","abstract":[{"text":"Returns the range of visible characters in the document.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityVisibleCharacterRange"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NSRange"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityVisibleCharacterRange()"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityVisibleCharacterRange":{"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityVisibleCharacterRange","type":"topic","title":"accessibilityVisibleCharacterRange","abstract":[{"type":"text","text":"The range of visible characters in the document."}],"kind":"symbol","fragments":[{"text":"accessibilityVisibleCharacterRange","kind":"identifier"}],"url":"/documentation/appkit/nsaccessibility-c.protocol/accessibilityvisiblecharacterrange"},"doc://com.externally.resolved.symbol/c:@S@_NSRange":{"role":"symbol","type":"topic","abstract":[{"text":"A Swift-only concrete structure that backs the range type alias.","type":"text"}],"url":"/documentation/foundation/nsrange-jio","kind":"symbol","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"_NSRange"}],"identifier":"doc://com.externally.resolved.symbol/c:@S@_NSRange","title":"_NSRange"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityValue()":{"required":true,"title":"accessibilityValue()","url":"/documentation/appkit/nsaccessibilitystatictext/accessibilityvalue()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityValue"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityValue()","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Returns the text that the accessibility element displays."}],"navigatorTitle":[{"text":"accessibilityValue","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityAttributedString(for:)":{"title":"accessibilityAttributedString(for:)","navigatorTitle":[{"text":"accessibilityAttributedStringForRange:","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityAttributedString(for:)","role":"symbol","url":"/documentation/appkit/nsaccessibilitystatictext/accessibilityattributedstring(for:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityAttributedString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRange","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"Returns the attributed substring for the specified range of characters.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText","navigatorTitle":[{"text":"NSAccessibilityStaticText","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSAccessibilityStaticText","kind":"identifier"}],"title":"NSAccessibilityStaticText","role":"symbol","abstract":[{"type":"text","text":"A role-based protocol that declares the minimum interface necessary for an accessibility element to act as static text."}],"kind":"symbol","type":"topic","url":"/documentation/appkit/nsaccessibilitystatictext"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","op":"replace","value":[{"deprecated":false,"unavailable":false,"beta":false,"name":"macOS"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"accessibilityVisibleCharacterRange"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"accessibilityVisibleCharacterRange","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"title":"Related Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityVisibleCharacterRange"],"anchor":"Related-Documentation"},{"title":"Supporting Accessibility","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityAttributedString(for:)","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityValue()"],"anchor":"Supporting-Accessibility","generated":true}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSRange","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@S@_NSRange","preciseIdentifier":"c:@S@_NSRange"},{"text":") ","kind":"text"},{"text":"accessibilityVisibleCharacterRange","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"text","text":"The range of the visible characters in the document. This method should return the range for entire lines. Characters that are horizontally clipped are included in this range."}],"type":"paragraph"}],"kind":"content"},"path":"/primaryContentSections/1"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/title","op":"replace","value":"NSAccessibility"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/fragments","op":"replace","value":[{"kind":"identifier","text":"NSAccessibility"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSAccessibility"}]},{"value":"accessibilityVisibleCharacterRange","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText~1accessibilityVisibleCharacterRange()/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilityVisibleCharacterRange"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText~1accessibilityVisibleCharacterRange()/fragments","op":"replace"},{"value":"accessibilityValue","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText~1accessibilityValue()/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilityValue"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText~1accessibilityValue()/fragments","op":"replace"},{"value":"accessibilityAttributedStringForRange:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText~1accessibilityAttributedString(for:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"accessibilityAttributedStringForRange:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText~1accessibilityAttributedString(for:)/fragments","op":"replace"},{"value":"NSAccessibilityStaticText","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText/title"},{"value":[{"text":"NSAccessibilityStaticText","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText/fragments"},{"value":[{"kind":"identifier","text":"NSAccessibilityStaticText"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}