{"seeAlsoSections":[{"anchor":"Supporting-Accessibility","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityValue()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityVisibleCharacterRange()"],"title":"Supporting Accessibility"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityAttributedString"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"range"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NSAttributedString","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":"?"}],"platforms":["macOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"range","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The range of characters."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An attributed string representing the specified characters."}]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText"]]},"abstract":[{"text":"Returns the attributed substring for the specified range of characters.","type":"text"}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityAttributedString(for:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsaccessibilitystatictext/accessibilityattributedstring(for:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsaccessibilitystatictext/accessibilityattributedstring(for:)"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"accessibilityAttributedStringForRange:"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","externalID":"c:objc(pl)NSAccessibilityStaticText(im)accessibilityAttributedStringForRange:","platforms":[{"introducedAt":"10.0","name":"macOS","beta":false,"deprecated":false,"unavailable":false}],"modules":[{"name":"AppKit"}],"title":"accessibilityAttributedString(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityAttributedString"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":"?"}]},"references":{"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityVisibleCharacterRange()":{"url":"/documentation/appkit/nsaccessibilitystatictext/accessibilityvisiblecharacterrange()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"accessibilityVisibleCharacterRange"}],"role":"symbol","type":"topic","title":"accessibilityVisibleCharacterRange()","abstract":[{"text":"Returns the range of visible characters in the document.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityVisibleCharacterRange"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NSRange"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityVisibleCharacterRange()"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString":{"kind":"symbol","role":"symbol","fragments":[{"text":"class ","kind":"text"},{"text":"NSAttributedString","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString","abstract":[{"type":"text","text":"A string of text that manages data, layout, and stylistic information for ranges of characters to support rendering."}],"type":"topic","title":"NSAttributedString","url":"/documentation/foundation/nsattributedstring"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText","navigatorTitle":[{"text":"NSAccessibilityStaticText","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSAccessibilityStaticText","kind":"identifier"}],"title":"NSAccessibilityStaticText","role":"symbol","abstract":[{"type":"text","text":"A role-based protocol that declares the minimum interface necessary for an accessibility element to act as static text."}],"kind":"symbol","type":"topic","url":"/documentation/appkit/nsaccessibilitystatictext"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityValue()":{"required":true,"title":"accessibilityValue()","url":"/documentation/appkit/nsaccessibilitystatictext/accessibilityvalue()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityValue"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityValue()","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Returns the text that the accessibility element displays."}],"navigatorTitle":[{"text":"accessibilityValue","kind":"identifier"}]},"doc://com.externally.resolved.symbol/c:@S@_NSRange":{"role":"symbol","type":"topic","abstract":[{"text":"A Swift-only concrete structure that backs the range type alias.","type":"text"}],"url":"/documentation/foundation/nsrange-jio","kind":"symbol","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"_NSRange"}],"identifier":"doc://com.externally.resolved.symbol/c:@S@_NSRange","title":"_NSRange"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityAttributedString(for:)":{"title":"accessibilityAttributedString(for:)","navigatorTitle":[{"text":"accessibilityAttributedStringForRange:","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityAttributedString(for:)","role":"symbol","url":"/documentation/appkit/nsaccessibilitystatictext/accessibilityattributedstring(for:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityAttributedString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRange","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"Returns the attributed substring for the specified range of characters.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"deprecated":false,"unavailable":false,"name":"macOS","beta":false}],"op":"replace","path":"/metadata/platforms"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"accessibilityAttributedStringForRange:","op":"replace"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"accessibilityAttributedStringForRange:","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityValue()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityVisibleCharacterRange()"],"anchor":"Supporting-Accessibility","title":"Supporting Accessibility","generated":true}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)NSAttributedString","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString","text":"NSAttributedString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"accessibilityAttributedStringForRange:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@_NSRange","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@S@_NSRange","text":"NSRange"},{"kind":"text","text":") "},{"kind":"internalParam","text":"range"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The range of characters."}],"type":"paragraph"}],"name":"range"}],"kind":"parameters"},"path":"/primaryContentSections/1"},{"op":"replace","value":{"content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"An attributed string representing the specified characters."}],"type":"paragraph"}],"kind":"content"},"path":"/primaryContentSections/2"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText~1accessibilityVisibleCharacterRange()/title","op":"replace","value":"accessibilityVisibleCharacterRange"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText~1accessibilityVisibleCharacterRange()/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"accessibilityVisibleCharacterRange","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText/title","op":"replace","value":"NSAccessibilityStaticText"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText/fragments","op":"replace","value":[{"text":"NSAccessibilityStaticText","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSAccessibilityStaticText"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText~1accessibilityValue()/title","op":"replace","value":"accessibilityValue"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText~1accessibilityValue()/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"accessibilityValue","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText~1accessibilityAttributedString(for:)/title","op":"replace","value":"accessibilityAttributedStringForRange:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText~1accessibilityAttributedString(for:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilityAttributedStringForRange:"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}