{
  "abstract": [
    {
      "text": "Displays the user interface provided by the authorization plug-in view subclass.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.securityinterface/documentation/SecurityInterface",
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationPluginView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationPluginView/display()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "SecurityInterface",
    "externalID": "c:objc(cs)SFAuthorizationPluginView(im)displayView",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "display"
      },
      {
        "kind": "text",
        "text": "()"
      }
    ],
    "modules": [
      {
        "name": "Security Interface"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "displayView"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "display()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "display"
            },
            {
              "kind": "text",
              "text": "()"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "It’s not likely that you will want to override this method, but if you do, be sure to call ",
              "type": "text"
            },
            {
              "code": "[super displayView]",
              "type": "codeVoice"
            },
            {
              "text": ". If you don’t call ",
              "type": "text"
            },
            {
              "code": "[super displayView]",
              "type": "codeVoice"
            },
            {
              "text": ", your custom view will not get displayed.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This method will raise an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFDisplayViewException",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " exception if an error occurs while displaying the authorization dialog.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface": {
      "abstract": [
        {
          "text": "Provide user interface elements for security features such as authorization, access to digital certificates, and access to items in keychains.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface",
      "kind": "symbol",
      "role": "collection",
      "title": "Security Interface",
      "type": "topic",
      "url": "/documentation/securityinterface"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationPluginView": {
      "abstract": [
        {
          "text": "Allows authorization plug-in developers to create a custom view their plug-in can display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFAuthorizationPluginView"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationPluginView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFAuthorizationPluginView"
        }
      ],
      "role": "symbol",
      "title": "SFAuthorizationPluginView",
      "type": "topic",
      "url": "/documentation/securityinterface/sfauthorizationpluginview"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationPluginView/display()": {
      "abstract": [
        {
          "text": "Displays the user interface provided by the authorization plug-in view subclass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "display"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationPluginView/display()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayView"
        }
      ],
      "role": "symbol",
      "title": "display()",
      "type": "topic",
      "url": "/documentation/securityinterface/sfauthorizationpluginview/display()"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationPluginView/setButton(_:enabled:)": {
      "abstract": [
        {
          "text": "Enables or disables a button in the authorization plug-in’s user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setButton"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SFButtonType",
          "text": "SFButtonType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "enabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationPluginView/setButton(_:enabled:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setButton:enabled:"
        }
      ],
      "role": "symbol",
      "title": "setButton(_:enabled:)",
      "type": "topic",
      "url": "/documentation/securityinterface/sfauthorizationpluginview/setbutton(_:enabled:)"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationPluginView/update()": {
      "abstract": [
        {
          "text": "Tells the authorization plug-in to get and display the appropriate view in the authorization plug-in’s user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "update"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationPluginView/update()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateView"
        }
      ],
      "role": "symbol",
      "title": "update()",
      "type": "topic",
      "url": "/documentation/securityinterface/sfauthorizationpluginview/update()"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFDisplayViewException": {
      "abstract": [
        {
          "text": "Raised when an error occurs in displaying the authorization dialog.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFDisplayViewException"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFDisplayViewException",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFDisplayViewException"
        }
      ],
      "role": "symbol",
      "title": "SFDisplayViewException",
      "type": "topic",
      "url": "/documentation/securityinterface/sfdisplayviewexception"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Communicating-with-the-Authorization-Plug-in",
      "generated": true,
      "identifiers": [
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationPluginView/setButton(_:enabled:)",
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationPluginView/update()"
      ],
      "title": "Communicating with the Authorization Plug-in"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "displayView"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "displayView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.securityinterface/documentation/SecurityInterface",
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationPluginView"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Communicating-with-the-Authorization-Plug-in",
              "generated": true,
              "identifiers": [
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationPluginView/setButton(_:enabled:)",
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationPluginView/update()"
              ],
              "title": "Communicating with the Authorization Plug-in"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "displayView"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationPluginView/title",
          "value": "SFAuthorizationPluginView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationPluginView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAuthorizationPluginView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationPluginView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAuthorizationPluginView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationPluginView~1update()/title",
          "value": "updateView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationPluginView~1update()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFDisplayViewException/title",
          "value": "SFDisplayViewException"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFDisplayViewException/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFDisplayViewException"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationPluginView~1display()/title",
          "value": "displayView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationPluginView~1display()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "displayView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationPluginView~1setButton(_:enabled:)/title",
          "value": "setButton:enabled:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationPluginView~1setButton(_:enabled:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setButton:enabled:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/securityinterface/sfauthorizationpluginview/display()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/securityinterface/sfauthorizationpluginview/display()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
