{
  "abstract": [
    {
      "text": "The accessory is actively cooling.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueCurrentHeaterCoolerState"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueCurrentHeaterCoolerState/cooling"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HMCharacteristicValueCurrentHeaterCoolerState@HMCharacteristicValueCurrentHeaterCoolerStateCooling",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "cooling"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HMCharacteristicValueCurrentHeaterCoolerStateCooling"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.1",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.1.1",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HMCharacteristicValueCurrentHeaterCoolerState.cooling"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "cooling"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueCurrentHeaterCoolerState": {
      "abstract": [
        {
          "text": "Possible values for the current state of a device that heats or cools.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueCurrentHeaterCoolerState"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueCurrentHeaterCoolerState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueCurrentHeaterCoolerState"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueCurrentHeaterCoolerState",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluecurrentheatercoolerstate"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueCurrentHeaterCoolerState/cooling": {
      "abstract": [
        {
          "text": "The accessory is actively cooling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cooling"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueCurrentHeaterCoolerState/cooling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueCurrentHeaterCoolerStateCooling"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueCurrentHeaterCoolerState.cooling",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluecurrentheatercoolerstate/cooling"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueCurrentHeaterCoolerState/heating": {
      "abstract": [
        {
          "text": "The accessory is actively heating.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "heating"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueCurrentHeaterCoolerState/heating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueCurrentHeaterCoolerStateHeating"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueCurrentHeaterCoolerState.heating",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluecurrentheatercoolerstate/heating"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueCurrentHeaterCoolerState/idle": {
      "abstract": [
        {
          "text": "The accessory is idle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "idle"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueCurrentHeaterCoolerState/idle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueCurrentHeaterCoolerStateIdle"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueCurrentHeaterCoolerState.idle",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluecurrentheatercoolerstate/idle"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueCurrentHeaterCoolerState/inactive": {
      "abstract": [
        {
          "text": "The accessory is inactive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inactive"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueCurrentHeaterCoolerState/inactive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueCurrentHeaterCoolerStateInactive"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueCurrentHeaterCoolerState.inactive",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluecurrentheatercoolerstate/inactive"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Current-State",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueCurrentHeaterCoolerState/inactive",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueCurrentHeaterCoolerState/idle",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueCurrentHeaterCoolerState/heating"
      ],
      "title": "Current State"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.1.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HMCharacteristicValueCurrentHeaterCoolerStateCooling"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueCurrentHeaterCoolerStateCooling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.homekit/documentation/HomeKit",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueCurrentHeaterCoolerState"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Current-State",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueCurrentHeaterCoolerState/inactive",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueCurrentHeaterCoolerState/idle",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueCurrentHeaterCoolerState/heating"
              ],
              "title": "Current State"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HMCharacteristicValueCurrentHeaterCoolerStateCooling"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueCurrentHeaterCoolerState/title",
          "value": "HMCharacteristicValueCurrentHeaterCoolerState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueCurrentHeaterCoolerState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueCurrentHeaterCoolerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueCurrentHeaterCoolerState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueCurrentHeaterCoolerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueCurrentHeaterCoolerState~1heating/title",
          "value": "HMCharacteristicValueCurrentHeaterCoolerStateHeating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueCurrentHeaterCoolerState~1heating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueCurrentHeaterCoolerStateHeating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueCurrentHeaterCoolerState~1idle/title",
          "value": "HMCharacteristicValueCurrentHeaterCoolerStateIdle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueCurrentHeaterCoolerState~1idle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueCurrentHeaterCoolerStateIdle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueCurrentHeaterCoolerState~1inactive/title",
          "value": "HMCharacteristicValueCurrentHeaterCoolerStateInactive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueCurrentHeaterCoolerState~1inactive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueCurrentHeaterCoolerStateInactive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueCurrentHeaterCoolerState~1cooling/title",
          "value": "HMCharacteristicValueCurrentHeaterCoolerStateCooling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueCurrentHeaterCoolerState~1cooling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueCurrentHeaterCoolerStateCooling"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmcharacteristicvaluecurrentheatercoolerstate/cooling"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/hmcharacteristicvaluecurrentheatercoolerstate/cooling"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
