{
  "abstract": [
    {
      "text": "The app’s menu bar.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityMenuBar"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSAccessibility(py)accessibilityMenuBar",
    "fragments": [
      {
        "kind": "identifier",
        "text": "accessibilityMenuBar"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "accessibilityMenuBar"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "accessibilityMenuBar"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "weak"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "id"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "accessibilityMenuBar"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityExtrasMenuBar": {
      "abstract": [
        {
          "text": "The icon for the app’s menu bar extra.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityExtrasMenuBar"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityExtrasMenuBar",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityExtrasMenuBar",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilityextrasmenubar"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityFrontmost": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the app is the frontmost app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityFrontmost"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityFrontmost",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityFrontmost",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilityfrontmost"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityHidden": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the app is in a hidden state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityHidden"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityHidden",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityHidden",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilityhidden"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityMainWindow": {
      "abstract": [
        {
          "text": "The app’s main window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityMainWindow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityMainWindow",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityMainWindow",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilitymainwindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityMenuBar": {
      "abstract": [
        {
          "text": "The app’s menu bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityMenuBar"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityMenuBar",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityMenuBar",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilitymenubar"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityWindows": {
      "abstract": [
        {
          "text": "An array that contains all the app’s windows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityWindows"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityWindows",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityWindows",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilitywindows"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol": {
      "abstract": [
        {
          "text": "The complete list of properties and methods for accessible elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityProtocol",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Apps",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityExtrasMenuBar",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityFrontmost",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityHidden",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityMainWindow",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityWindows"
      ],
      "title": "Managing Apps"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/title",
          "value": "NSAccessibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsaccessibility-c.protocol/accessibilitymenubar"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
