{
  "abstract": [
    {
      "text": "The critical value for the level indicator.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityCriticalValue"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSAccessibility(py)accessibilityCriticalValue",
    "fragments": [
      {
        "kind": "identifier",
        "text": "accessibilityCriticalValue"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "accessibilityCriticalValue"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "accessibilityCriticalValue"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "strong"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "id"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "accessibilityCriticalValue"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this property for elements such as the battery level indicator. This property sets a boundary value. If the element’s value exceeds the boundary value, the element has reached a critical stage.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityContents": {
      "abstract": [
        {
          "text": "The contents of the current accessibility element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityContents"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityContents",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityContents",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilitycontents"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityCriticalValue": {
      "abstract": [
        {
          "text": "The critical value for the level indicator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityCriticalValue"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityCriticalValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityCriticalValue",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilitycriticalvalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityIdentifier": {
      "abstract": [
        {
          "text": "The accessibility element’s identity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityIdentifier"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityIdentifier",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilityidentifier"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityMaxValue": {
      "abstract": [
        {
          "text": "The maximum value for the accessibility element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityMaxValue"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityMaxValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityMaxValue",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilitymaxvalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityMinValue": {
      "abstract": [
        {
          "text": "The minimum value for the accessibility element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityMinValue"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityMinValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityMinValue",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilityminvalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityOrientation": {
      "abstract": [
        {
          "text": "The orientation of the accessibility element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityOrientation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityOrientation",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityOrientation",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilityorientation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityProtectedContent": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the accessibility element contains protected content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityProtectedContent"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityProtectedContent",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityProtectedContent",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilityprotectedcontent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilitySelected": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the accessibility element is currently in a selected state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilitySelected"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilitySelected",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilitySelected",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilityselected"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityURL": {
      "abstract": [
        {
          "text": "The URL for the accessibility element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityURL"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityURL",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityURL",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilityurl"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityValueDescription": {
      "abstract": [
        {
          "text": "A human-readable description of the accessibility element’s value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityValueDescription"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityValueDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityValueDescription",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilityvaluedescription"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityWarningValue": {
      "abstract": [
        {
          "text": "The warning value for the level indicator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityWarningValue"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityWarningValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityWarningValue",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilitywarningvalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityOrientation": {
      "abstract": [
        {
          "text": "Values that indicate the orientation of accessibility elements, such as scroll bars and split views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityOrientation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityOrientation"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityOrientation",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityorientation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol": {
      "abstract": [
        {
          "text": "The complete list of properties and methods for accessible elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityProtocol",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Setting-Content-and-Values",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityContents",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityIdentifier",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityMaxValue",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityMinValue",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityOrientation",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityProtectedContent",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilitySelected",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityURL",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityValueDescription",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityWarningValue",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityOrientation"
      ],
      "title": "Setting Content and Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/title",
          "value": "NSAccessibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityOrientation/title",
          "value": "NSAccessibilityOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityOrientation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityOrientation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsaccessibility-c.protocol/accessibilitycriticalvalue"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
