{
  "abstract": [
    {
      "text": "The column titles for the accessibility element.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityColumnTitles"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSAccessibility(py)accessibilityColumnTitles",
    "fragments": [
      {
        "kind": "identifier",
        "text": "accessibilityColumnTitles"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "accessibilityColumnTitles"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "accessibilityColumnTitles"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSArray",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSArray",
              "text": "NSArray"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "accessibilityColumnTitles"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityColumnHeaderUIElements": {
      "abstract": [
        {
          "text": "The column header accessibility elements for the table or outline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityColumnHeaderUIElements"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityColumnHeaderUIElements",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityColumnHeaderUIElements",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilitycolumnheaderuielements"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityColumnTitles": {
      "abstract": [
        {
          "text": "The column titles for the accessibility element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityColumnTitles"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityColumnTitles",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityColumnTitles",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilitycolumntitles"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityColumns": {
      "abstract": [
        {
          "text": "The column accessibility elements for the table or outline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityColumns"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityColumns",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityColumns",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilitycolumns"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityExpanded": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the accessibility element is in an expanded state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityExpanded"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityExpanded",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityExpanded",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilityexpanded"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityHeader": {
      "abstract": [
        {
          "text": "The header for the table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityHeader"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityHeader",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityHeader",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilityheader"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityIndex": {
      "abstract": [
        {
          "text": "The index of the row or column that the accessibility element represents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityIndex"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityIndex",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityIndex",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilityindex"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityRowHeaderUIElements": {
      "abstract": [
        {
          "text": "The row header accessibility elements for the table or outline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityRowHeaderUIElements"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityRowHeaderUIElements",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityRowHeaderUIElements",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilityrowheaderuielements"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityRows": {
      "abstract": [
        {
          "text": "The row accessibility elements for the table or outline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityRows"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityRows",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityRows",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilityrows"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilitySelectedColumns": {
      "abstract": [
        {
          "text": "The currently selected columns for the table or outline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilitySelectedColumns"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilitySelectedColumns",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilitySelectedColumns",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilityselectedcolumns"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilitySelectedRows": {
      "abstract": [
        {
          "text": "The currently selected rows for the table or outline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilitySelectedRows"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilitySelectedRows",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilitySelectedRows",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilityselectedrows"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilitySortDirection": {
      "abstract": [
        {
          "text": "The accessibility element’s sort direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilitySortDirection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilitySortDirection",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilitySortDirection",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilitysortdirection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityVisibleColumns": {
      "abstract": [
        {
          "text": "The visible columns for the table or outline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityVisibleColumns"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityVisibleColumns",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityVisibleColumns",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilityvisiblecolumns"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityVisibleRows": {
      "abstract": [
        {
          "text": "The visible rows for the table or outline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityVisibleRows"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityVisibleRows",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityVisibleRows",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilityvisiblerows"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol": {
      "abstract": [
        {
          "text": "The complete list of properties and methods for accessible elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityProtocol",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySortDirection": {
      "abstract": [
        {
          "text": "Values that indicate the sort direction of a column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilitySortDirection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySortDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilitySortDirection"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilitySortDirection",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitysortdirection"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSArray": {
      "abstract": [
        {
          "text": "An object representing a static ordered collection, for use instead of an  constant in cases that require reference semantics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSArray"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSArray",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSArray",
      "type": "topic",
      "url": "/documentation/foundation/nsarray"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Table-and-Outline-Views",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityColumnHeaderUIElements",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityColumns",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityExpanded",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityHeader",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityIndex",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityRowHeaderUIElements",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityRows",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilitySelectedColumns",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilitySelectedRows",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilitySortDirection",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityVisibleColumns",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityVisibleRows",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySortDirection"
      ],
      "title": "Configuring Table and Outline Views"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSArray/abstract",
          "value": [
            {
              "text": "A static ordered collection of objects.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/title",
          "value": "NSAccessibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilitySortDirection/title",
          "value": "NSAccessibilitySortDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilitySortDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilitySortDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilitySortDirection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilitySortDirection"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsaccessibility-c.protocol/accessibilitycolumntitles"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
