{
  "abstract": [
    {
      "text": "The units that the layout area uses for vertical values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityVerticalUnits"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSAccessibility(py)accessibilityVerticalUnits",
    "fragments": [
      {
        "kind": "identifier",
        "text": "accessibilityVerticalUnits"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "accessibilityVerticalUnits"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "accessibilityVerticalUnits"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityUnits",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSAccessibilityUnits",
              "text": "NSAccessibilityUnits"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "accessibilityVerticalUnits"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For a list of possible values, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityUnits",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityHandles": {
      "abstract": [
        {
          "text": "The drag handle accessibility elements for the layout item element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityHandles"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityHandles",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityHandles",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilityhandles"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityHorizontalUnitDescription": {
      "abstract": [
        {
          "text": "A description of the layout area’s horizontal units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityHorizontalUnitDescription"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityHorizontalUnitDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityHorizontalUnitDescription",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilityhorizontalunitdescription"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityHorizontalUnits": {
      "abstract": [
        {
          "text": "The units that the layout area uses for horizontal values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityHorizontalUnits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityHorizontalUnits",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityHorizontalUnits",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilityhorizontalunits"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityVerticalUnitDescription": {
      "abstract": [
        {
          "text": "A description of the layout area’s vertical units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityVerticalUnitDescription"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityVerticalUnitDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityVerticalUnitDescription",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilityverticalunitdescription"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityVerticalUnits": {
      "abstract": [
        {
          "text": "The units that the layout area uses for vertical values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityVerticalUnits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityVerticalUnits",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityVerticalUnits",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilityverticalunits"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol": {
      "abstract": [
        {
          "text": "The complete list of properties and methods for accessible elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityProtocol",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityLayoutPoint(forScreenPoint:)": {
      "abstract": [
        {
          "text": "Converts the provided point in screen coordinates to a point in the layout area’s coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityLayoutPoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forScreenPoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityLayoutPoint(forScreenPoint:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityLayoutPointForScreenPoint:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityLayoutPoint(forScreenPoint:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilitylayoutpoint(forscreenpoint:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityLayoutSize(forScreenSize:)": {
      "abstract": [
        {
          "text": "Converts the provided size in screen coordinates to a size in the layout area’s coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityLayoutSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forScreenSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityLayoutSize(forScreenSize:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityLayoutSizeForScreenSize:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityLayoutSize(forScreenSize:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilitylayoutsize(forscreensize:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityScreenPoint(forLayoutPoint:)": {
      "abstract": [
        {
          "text": "Converts the provided point in the layout area’s coordinates to a point in the screen’s coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityScreenPoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forLayoutPoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityScreenPoint(forLayoutPoint:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityScreenPointForLayoutPoint:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityScreenPoint(forLayoutPoint:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilityscreenpoint(forlayoutpoint:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityScreenSize(forLayoutSize:)": {
      "abstract": [
        {
          "text": "Converts the provided size in the layout area’s coordinates to a size in the screen’s coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityScreenSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forLayoutSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityScreenSize(forLayoutSize:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityScreenSizeForLayoutSize:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityScreenSize(forLayoutSize:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilityscreensize(forlayoutsize:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityUnits": {
      "abstract": [
        {
          "text": "Values that indicate the unit values of a ruler or layout area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityUnits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityUnits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityUnits"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityUnits",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityunits"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Layout",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityLayoutPoint(forScreenPoint:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityLayoutSize(forScreenSize:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityScreenPoint(forLayoutPoint:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityScreenSize(forLayoutSize:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityHandles",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityHorizontalUnits",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityHorizontalUnitDescription",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityVerticalUnitDescription"
      ],
      "title": "Configuring Layout"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol~1accessibilityLayoutSize(forScreenSize:)/title",
          "value": "accessibilityLayoutSizeForScreenSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol~1accessibilityLayoutSize(forScreenSize:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityLayoutSizeForScreenSize:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol~1accessibilityScreenSize(forLayoutSize:)/title",
          "value": "accessibilityScreenSizeForLayoutSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol~1accessibilityScreenSize(forLayoutSize:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityScreenSizeForLayoutSize:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol~1accessibilityScreenPoint(forLayoutPoint:)/title",
          "value": "accessibilityScreenPointForLayoutPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol~1accessibilityScreenPoint(forLayoutPoint:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityScreenPointForLayoutPoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol~1accessibilityLayoutPoint(forScreenPoint:)/title",
          "value": "accessibilityLayoutPointForScreenPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol~1accessibilityLayoutPoint(forScreenPoint:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityLayoutPointForScreenPoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityUnits/title",
          "value": "NSAccessibilityUnits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityUnits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityUnits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityUnits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityUnits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/title",
          "value": "NSAccessibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsaccessibility-c.protocol/accessibilityverticalunits"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
