{
  "abstract": [
    {
      "text": "The reasons for the app’s geotracking status.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "ARKit",
    "externalID": "c:@E@ARGeoTrackingStateReason",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "StateReason"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "StateReason"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "ARGeoTrackingStatus.StateReason"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "StateReason"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These possible values of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/stateReason-swift.property",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " provide more information about a geotracking session’s current ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/state-swift.property",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus": {
      "abstract": [
        {
          "text": "The state, accuracy, and reason that are possible for geo-tracking’s current condition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARGeoTrackingStatus"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeoTrackingStatus"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum": {
      "abstract": [
        {
          "text": "The reasons for the app’s geotracking status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "StateReason"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "StateReason"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus.StateReason",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/statereason-swift.enum"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/devicePointedTooLow": {
      "abstract": [
        {
          "text": "The position of the device is too low for geotracking.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "devicePointedTooLow"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/devicePointedTooLow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeoTrackingStateReasonDevicePointedTooLow"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus.StateReason.devicePointedTooLow",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/statereason-swift.enum/devicepointedtoolow"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/geoDataNotLoaded": {
      "abstract": [
        {
          "text": "A state in which the framework downloads localization imagery.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "geoDataNotLoaded"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/geoDataNotLoaded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeoTrackingStateReasonGeoDataNotLoaded"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus.StateReason.geoDataNotLoaded",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/statereason-swift.enum/geodatanotloaded"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/statereason-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/needLocationPermissions": {
      "abstract": [
        {
          "text": "The location requires user permission for geotracking.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "needLocationPermissions"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/needLocationPermissions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeoTrackingStateReasonNeedLocationPermissions"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus.StateReason.needLocationPermissions",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/statereason-swift.enum/needlocationpermissions"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/none": {
      "abstract": [
        {
          "text": "No issues reported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeoTrackingStateReasonNone"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus.StateReason.none",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/statereason-swift.enum/none"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/notAvailableAtLocation": {
      "abstract": [
        {
          "text": "The location doesn’t provide geotracking.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notAvailableAtLocation"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/notAvailableAtLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeoTrackingStateReasonNotAvailableAtLocation"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus.StateReason.notAvailableAtLocation",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/statereason-swift.enum/notavailableatlocation"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/visualLocalizationFailed": {
      "abstract": [
        {
          "text": "Localization imagery failed to match the view from the device’s camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visualLocalizationFailed"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/visualLocalizationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeoTrackingStateReasonVisualLocalizationFailed"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus.StateReason.visualLocalizationFailed",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/statereason-swift.enum/visuallocalizationfailed"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/waitingForAvailabilityCheck": {
      "abstract": [
        {
          "text": "A state in which the framework performs a check for geotracking availability at the user’s location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "waitingForAvailabilityCheck"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/waitingForAvailabilityCheck",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeoTrackingStateReasonWaitingForAvailabilityCheck"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus.StateReason.waitingForAvailabilityCheck",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/statereason-swift.enum/waitingforavailabilitycheck"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/waitingForLocation": {
      "abstract": [
        {
          "text": "A state in which the framework performs a check for the user’s GPS position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "waitingForLocation"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/waitingForLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeoTrackingStateReasonWaitingForLocation"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus.StateReason.waitingForLocation",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/statereason-swift.enum/waitingforlocation"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/worldTrackingUnstable": {
      "abstract": [
        {
          "text": "The position or motion of the device makes geotracking unstable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "worldTrackingUnstable"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/worldTrackingUnstable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeoTrackingStateReasonWorldTrackingUnstable"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus.StateReason.worldTrackingUnstable",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/statereason-swift.enum/worldtrackingunstable"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/state-swift.property": {
      "abstract": [
        {
          "text": "A value that describes the session’s current geo-tracking state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "state"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARGeoTrackingStatus",
          "text": "ARGeoTrackingStatus"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARGeoTrackingState",
          "text": "State"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/state-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "state"
        }
      ],
      "role": "symbol",
      "title": "state",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/state-swift.property"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/stateReason-swift.property": {
      "abstract": [
        {
          "text": "The reasons for the app’s geotracking status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stateReason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARGeoTrackingStatus",
          "text": "ARGeoTrackingStatus"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARGeoTrackingStateReason",
          "text": "StateReason"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/stateReason-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stateReason"
        }
      ],
      "role": "symbol",
      "title": "stateReason",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/statereason-swift.property"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Determining-the-Reason",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/stateReason-swift.property"
      ],
      "title": "Determining the Reason"
    }
  ],
  "topicSections": [
    {
      "anchor": "Status-Reasons",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/none",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/notAvailableAtLocation",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/needLocationPermissions",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/devicePointedTooLow",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/worldTrackingUnstable",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/waitingForLocation",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/waitingForAvailabilityCheck",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/geoDataNotLoaded",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/visualLocalizationFailed",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/none",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/notAvailableAtLocation",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/needLocationPermissions",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/devicePointedTooLow",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/worldTrackingUnstable",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/waitingForLocation",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/waitingForAvailabilityCheck",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/geoDataNotLoaded",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/visualLocalizationFailed"
      ],
      "title": "Status Reasons"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ARGeoTrackingStateReason"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStateReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStateReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.arkit/documentation/ARKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Status-Reasons",
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/none",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/notAvailableAtLocation",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/needLocationPermissions",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/devicePointedTooLow",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/worldTrackingUnstable",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/waitingForLocation",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/waitingForAvailabilityCheck",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/geoDataNotLoaded",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/visualLocalizationFailed",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/none",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/notAvailableAtLocation",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/needLocationPermissions",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/devicePointedTooLow",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/worldTrackingUnstable",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/waitingForLocation",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/waitingForAvailabilityCheck",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/geoDataNotLoaded",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum/visualLocalizationFailed"
              ],
              "title": "Status Reasons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Determining-the-Reason",
              "generated": true,
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/stateReason-swift.property"
              ],
              "title": "Determining the Reason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ARGeoTrackingStateReason"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum/title",
          "value": "ARGeoTrackingStateReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStateReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStateReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1visualLocalizationFailed/title",
          "value": "ARGeoTrackingStateReasonVisualLocalizationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1visualLocalizationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStateReasonVisualLocalizationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1waitingForLocation/title",
          "value": "ARGeoTrackingStateReasonWaitingForLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1waitingForLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStateReasonWaitingForLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1stateReason-swift.property/title",
          "value": "stateReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1stateReason-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "stateReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1none/title",
          "value": "ARGeoTrackingStateReasonNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStateReasonNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1notAvailableAtLocation/title",
          "value": "ARGeoTrackingStateReasonNotAvailableAtLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1notAvailableAtLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStateReasonNotAvailableAtLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1devicePointedTooLow/title",
          "value": "ARGeoTrackingStateReasonDevicePointedTooLow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1devicePointedTooLow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStateReasonDevicePointedTooLow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1state-swift.property/title",
          "value": "state"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1state-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "state"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1needLocationPermissions/title",
          "value": "ARGeoTrackingStateReasonNeedLocationPermissions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1needLocationPermissions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStateReasonNeedLocationPermissions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1waitingForAvailabilityCheck/title",
          "value": "ARGeoTrackingStateReasonWaitingForAvailabilityCheck"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1waitingForAvailabilityCheck/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStateReasonWaitingForAvailabilityCheck"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus/title",
          "value": "ARGeoTrackingStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1geoDataNotLoaded/title",
          "value": "ARGeoTrackingStateReasonGeoDataNotLoaded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1geoDataNotLoaded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStateReasonGeoDataNotLoaded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1worldTrackingUnstable/title",
          "value": "ARGeoTrackingStateReasonWorldTrackingUnstable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum~1worldTrackingUnstable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStateReasonWorldTrackingUnstable"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/argeotrackingstatus/statereason-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/arkit/argeotrackingstatus/statereason-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
