{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/offscreenTop"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSTextCursorAccessoryPlacement@NSTextCursorAccessoryPlacementOffscreenTop",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "offscreenTop"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextCursorAccessoryPlacementOffscreenTop"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSTextCursorAccessoryPlacement.offscreenTop"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "offscreenTop"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextCursorAccessoryPlacement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextCursorAccessoryPlacement"
        }
      ],
      "role": "symbol",
      "title": "NSTextCursorAccessoryPlacement",
      "type": "topic",
      "url": "/documentation/appkit/nstextcursoraccessoryplacement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/backward": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backward"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/backward",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextCursorAccessoryPlacementBackward"
        }
      ],
      "role": "symbol",
      "title": "NSTextCursorAccessoryPlacement.backward",
      "type": "topic",
      "url": "/documentation/appkit/nstextcursoraccessoryplacement/backward"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/center": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "center"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/center",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextCursorAccessoryPlacementCenter"
        }
      ],
      "role": "symbol",
      "title": "NSTextCursorAccessoryPlacement.center",
      "type": "topic",
      "url": "/documentation/appkit/nstextcursoraccessoryplacement/center"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/forward": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forward"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/forward",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextCursorAccessoryPlacementForward"
        }
      ],
      "role": "symbol",
      "title": "NSTextCursorAccessoryPlacement.forward",
      "type": "topic",
      "url": "/documentation/appkit/nstextcursoraccessoryplacement/forward"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/invisible": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invisible"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/invisible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextCursorAccessoryPlacementInvisible"
        }
      ],
      "role": "symbol",
      "title": "NSTextCursorAccessoryPlacement.invisible",
      "type": "topic",
      "url": "/documentation/appkit/nstextcursoraccessoryplacement/invisible"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/offscreenBottom": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offscreenBottom"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/offscreenBottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextCursorAccessoryPlacementOffscreenBottom"
        }
      ],
      "role": "symbol",
      "title": "NSTextCursorAccessoryPlacement.offscreenBottom",
      "type": "topic",
      "url": "/documentation/appkit/nstextcursoraccessoryplacement/offscreenbottom"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/offscreenLeft": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offscreenLeft"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/offscreenLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextCursorAccessoryPlacementOffscreenLeft"
        }
      ],
      "role": "symbol",
      "title": "NSTextCursorAccessoryPlacement.offscreenLeft",
      "type": "topic",
      "url": "/documentation/appkit/nstextcursoraccessoryplacement/offscreenleft"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/offscreenRight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offscreenRight"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/offscreenRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextCursorAccessoryPlacementOffscreenRight"
        }
      ],
      "role": "symbol",
      "title": "NSTextCursorAccessoryPlacement.offscreenRight",
      "type": "topic",
      "url": "/documentation/appkit/nstextcursoraccessoryplacement/offscreenright"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/offscreenTop": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offscreenTop"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/offscreenTop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextCursorAccessoryPlacementOffscreenTop"
        }
      ],
      "role": "symbol",
      "title": "NSTextCursorAccessoryPlacement.offscreenTop",
      "type": "topic",
      "url": "/documentation/appkit/nstextcursoraccessoryplacement/offscreentop"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/unspecified": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextCursorAccessoryPlacementUnspecified"
        }
      ],
      "role": "symbol",
      "title": "NSTextCursorAccessoryPlacement.unspecified",
      "type": "topic",
      "url": "/documentation/appkit/nstextcursoraccessoryplacement/unspecified"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/backward",
        "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/center",
        "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/forward",
        "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/invisible",
        "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/offscreenBottom",
        "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/offscreenLeft",
        "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/offscreenRight",
        "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/unspecified"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTextCursorAccessoryPlacementOffscreenTop"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextCursorAccessoryPlacementOffscreenTop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/backward",
                "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/center",
                "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/forward",
                "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/invisible",
                "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/offscreenBottom",
                "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/offscreenLeft",
                "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/offscreenRight",
                "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement/unspecified"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSTextCursorAccessoryPlacementOffscreenTop"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextCursorAccessoryPlacement~1offscreenRight/title",
          "value": "NSTextCursorAccessoryPlacementOffscreenRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextCursorAccessoryPlacement~1offscreenRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextCursorAccessoryPlacementOffscreenRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextCursorAccessoryPlacement/title",
          "value": "NSTextCursorAccessoryPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextCursorAccessoryPlacement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextCursorAccessoryPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextCursorAccessoryPlacement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextCursorAccessoryPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextCursorAccessoryPlacement~1offscreenTop/title",
          "value": "NSTextCursorAccessoryPlacementOffscreenTop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextCursorAccessoryPlacement~1offscreenTop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextCursorAccessoryPlacementOffscreenTop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextCursorAccessoryPlacement~1offscreenLeft/title",
          "value": "NSTextCursorAccessoryPlacementOffscreenLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextCursorAccessoryPlacement~1offscreenLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextCursorAccessoryPlacementOffscreenLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextCursorAccessoryPlacement~1center/title",
          "value": "NSTextCursorAccessoryPlacementCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextCursorAccessoryPlacement~1center/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextCursorAccessoryPlacementCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextCursorAccessoryPlacement~1unspecified/title",
          "value": "NSTextCursorAccessoryPlacementUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextCursorAccessoryPlacement~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextCursorAccessoryPlacementUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextCursorAccessoryPlacement~1invisible/title",
          "value": "NSTextCursorAccessoryPlacementInvisible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextCursorAccessoryPlacement~1invisible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextCursorAccessoryPlacementInvisible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextCursorAccessoryPlacement~1forward/title",
          "value": "NSTextCursorAccessoryPlacementForward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextCursorAccessoryPlacement~1forward/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextCursorAccessoryPlacementForward"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextCursorAccessoryPlacement~1offscreenBottom/title",
          "value": "NSTextCursorAccessoryPlacementOffscreenBottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextCursorAccessoryPlacement~1offscreenBottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextCursorAccessoryPlacementOffscreenBottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextCursorAccessoryPlacement~1backward/title",
          "value": "NSTextCursorAccessoryPlacementBackward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextCursorAccessoryPlacement~1backward/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextCursorAccessoryPlacementBackward"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstextcursoraccessoryplacement/offscreentop"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstextcursoraccessoryplacement/offscreentop"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
