{
  "abstract": [
    {
      "text": "Indicates the user inserted content by pasting.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/WebViewInsertAction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/WebViewInsertAction/pasted"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@WebViewInsertAction@WebViewInsertActionPasted",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "pasted"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WebViewInsertActionPasted"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "WebViewInsertAction.pasted"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "pasted"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebViewInsertAction": {
      "abstract": [
        {
          "text": "The type of user action that initiated a delegate message.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebViewInsertAction"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebViewInsertAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebViewInsertAction"
        }
      ],
      "role": "symbol",
      "title": "WebViewInsertAction",
      "type": "topic",
      "url": "/documentation/webkit/webviewinsertaction"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebViewInsertAction/dropped": {
      "abstract": [
        {
          "text": "Indicates the user inserted content by dropping.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dropped"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebViewInsertAction/dropped",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebViewInsertActionDropped"
        }
      ],
      "role": "symbol",
      "title": "WebViewInsertAction.dropped",
      "type": "topic",
      "url": "/documentation/webkit/webviewinsertaction/dropped"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebViewInsertAction/pasted": {
      "abstract": [
        {
          "text": "Indicates the user inserted content by pasting.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pasted"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebViewInsertAction/pasted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebViewInsertActionPasted"
        }
      ],
      "role": "symbol",
      "title": "WebViewInsertAction.pasted",
      "type": "topic",
      "url": "/documentation/webkit/webviewinsertaction/pasted"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebViewInsertAction/typed": {
      "abstract": [
        {
          "text": "Indicates the user inserted content by typing.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typed"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebViewInsertAction/typed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebViewInsertActionTyped"
        }
      ],
      "role": "symbol",
      "title": "WebViewInsertAction.typed",
      "type": "topic",
      "url": "/documentation/webkit/webviewinsertaction/typed"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebViewInsertAction/typed",
        "doc://com.apple.webkit/documentation/WebKit/WebViewInsertAction/dropped"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.14",
              "introducedAt": "10.3",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WebViewInsertActionPasted"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebViewInsertActionPasted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit",
                "doc://com.apple.webkit/documentation/WebKit/WebViewInsertAction"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WebViewInsertAction/typed",
                "doc://com.apple.webkit/documentation/WebKit/WebViewInsertAction/dropped"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "WebViewInsertActionPasted"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebViewInsertAction~1pasted/title",
          "value": "WebViewInsertActionPasted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebViewInsertAction~1pasted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebViewInsertActionPasted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebViewInsertAction~1typed/title",
          "value": "WebViewInsertActionTyped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebViewInsertAction~1typed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebViewInsertActionTyped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebViewInsertAction~1dropped/title",
          "value": "WebViewInsertActionDropped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebViewInsertAction~1dropped/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebViewInsertActionDropped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebViewInsertAction/title",
          "value": "WebViewInsertAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebViewInsertAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebViewInsertAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebViewInsertAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebViewInsertAction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/webviewinsertaction/pasted"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/webviewinsertaction/pasted"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
