{
  "abstract": [
    {
      "text": "Starts an asynchronous fetch for image data in all locations",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPerson"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/ABPerson/beginLoadingImageData(for:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AddressBook",
    "externalID": "c:objc(cs)ABPerson(im)beginLoadingImageDataForClient:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "beginLoadingImageData"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "for"
      },
      {
        "kind": "text",
        "text": ": (any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)ABImageClient",
        "text": "ABImageClient"
      },
      {
        "kind": "text",
        "text": ")!) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "beginLoadingImageDataForClient:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "beginLoadingImageData(for:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "beginLoadingImageData"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "client"
            },
            {
              "kind": "text",
              "text": ": (any "
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABImageClient",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)ABImageClient",
              "text": "ABImageClient"
            },
            {
              "kind": "text",
              "text": ")!) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The object to be notified when the image finishes loading.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "client"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A nonzero tag for tracking. This tag is used by the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPerson/cancelLoadingImageData(forTag:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to cancel a fetch operation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "client",
              "type": "codeVoice"
            },
            {
              "text": " object should conform to the ",
              "type": "text"
            },
            {
              "code": "ABImageClient",
              "type": "codeVoice"
            },
            {
              "text": " protocol. A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABImageClient/consumeImageData(_:forTag:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " message is sent to ",
              "type": "text"
            },
            {
              "code": "client",
              "type": "codeVoice"
            },
            {
              "text": " when the fetch is done. Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPerson/cancelLoadingImageData(forTag:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method if you need to cancel an asynchronous fetch.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABImageClient": {
      "abstract": [
        {
          "text": "Methods for responding to a request to load images associated with a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABImageClient"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABImageClient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABImageClient"
        }
      ],
      "role": "symbol",
      "title": "ABImageClient",
      "type": "topic",
      "url": "/documentation/addressbook/abimageclient"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABImageClient/consumeImageData(_:forTag:)": {
      "abstract": [
        {
          "text": "Gets the image data for the given tag that was initiated by an asynchronous fetch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "consumeImageData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "forTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABImageClient/consumeImageData(_:forTag:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "consumeImageData:forTag:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "consumeImageData(_:forTag:)",
      "type": "topic",
      "url": "/documentation/addressbook/abimageclient/consumeimagedata(_:fortag:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPerson": {
      "abstract": [
        {
          "text": "An object that encapsulates all information about a person in the Address Book database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPerson"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPerson",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPerson"
        }
      ],
      "role": "symbol",
      "title": "ABPerson",
      "type": "topic",
      "url": "/documentation/addressbook/abperson"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPerson/beginLoadingImageData(for:)": {
      "abstract": [
        {
          "text": "Starts an asynchronous fetch for image data in all locations",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginLoadingImageData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)ABImageClient",
          "text": "ABImageClient"
        },
        {
          "kind": "text",
          "text": ")!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPerson/beginLoadingImageData(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginLoadingImageDataForClient:"
        }
      ],
      "role": "symbol",
      "title": "beginLoadingImageData(for:)",
      "type": "topic",
      "url": "/documentation/addressbook/abperson/beginloadingimagedata(for:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPerson/cancelLoadingImageData(forTag:)": {
      "abstract": [
        {
          "text": "Cancels an asynchronous fetch of the images for a given tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelLoadingImageData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPerson/cancelLoadingImageData(forTag:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cancelLoadingImageDataForTag:"
        }
      ],
      "role": "symbol",
      "title": "cancelLoadingImageData(forTag:)",
      "type": "topic",
      "url": "/documentation/addressbook/abperson/cancelloadingimagedata(fortag:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPerson/imageData()": {
      "abstract": [
        {
          "text": "Returns data that contains a picture of this person.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageData"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPerson/imageData()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageData"
        }
      ],
      "role": "symbol",
      "title": "imageData()",
      "type": "topic",
      "url": "/documentation/addressbook/abperson/imagedata()"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPerson/setImageData(_:)": {
      "abstract": [
        {
          "text": "Sets the image for this person to the given data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setImageData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPerson/setImageData(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setImageData:"
        }
      ],
      "role": "symbol",
      "title": "setImageData(_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abperson/setimagedata(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Images",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABPerson/cancelLoadingImageData(forTag:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPerson/imageData()",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPerson/setImageData(_:)"
      ],
      "title": "Managing Images"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "beginLoadingImageDataForClient:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginLoadingImageDataForClient:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.addressbook/documentation/AddressBook",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPerson"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Images",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABPerson/cancelLoadingImageData(forTag:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPerson/imageData()",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPerson/setImageData(_:)"
              ],
              "title": "Managing Images"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "beginLoadingImageDataForClient:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)ABImageClient",
                    "text": "id<ABImageClient>"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "client"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The object to be notified when the image finishes loading.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "client"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A nonzero tag for tracking. This tag is used by the ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPerson/cancelLoadingImageData(forTag:)",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " method to cancel a fetch operation.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPerson~1setImageData(_:)/title",
          "value": "setImageData:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPerson~1setImageData(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setImageData:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPerson~1imageData()/title",
          "value": "imageData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPerson~1imageData()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "imageData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPerson~1beginLoadingImageData(for:)/title",
          "value": "beginLoadingImageDataForClient:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPerson~1beginLoadingImageData(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginLoadingImageDataForClient:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABImageClient/title",
          "value": "ABImageClient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABImageClient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABImageClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABImageClient/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABImageClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPerson~1cancelLoadingImageData(forTag:)/title",
          "value": "cancelLoadingImageDataForTag:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPerson~1cancelLoadingImageData(forTag:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "cancelLoadingImageDataForTag:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPerson/title",
          "value": "ABPerson"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPerson/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPerson"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPerson/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPerson"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABImageClient~1consumeImageData(_:forTag:)/title",
          "value": "consumeImageData:forTag:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABImageClient~1consumeImageData(_:forTag:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "consumeImageData:forTag:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/abperson/beginloadingimagedata(for:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/abperson/beginloadingimagedata(for:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
