{
  "abstract": [
    {
      "text": "An error indicating an incompatible home hub.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/noCompatibleHomeHub",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMErrorCode/HMErrorCodeIncompatibleHomeHub"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HMErrorCode@HMErrorCodeIncompatibleHomeHub",
    "fragments": [
      {
        "kind": "identifier",
        "text": "HMErrorCodeIncompatibleHomeHub"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HMErrorCodeIncompatibleHomeHub"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "4.0",
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "HMErrorCodeIncompatibleHomeHub"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeIncompatibleHomeHub"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code": {
      "abstract": [
        {
          "text": "Possible error values that can be returned from HomeKit APIs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/noCompatibleHomeHub": {
      "abstract": [
        {
          "text": "An error indicating no compatible home hub found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noCompatibleHomeHub"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/noCompatibleHomeHub",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeNoCompatibleHomeHub"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.noCompatibleHomeHub",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/nocompatiblehomehub"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMErrorCode/HMErrorCodeIncompatibleHomeHub": {
      "abstract": [
        {
          "text": "An error indicating an incompatible home hub.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeIncompatibleHomeHub"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMErrorCode/HMErrorCodeIncompatibleHomeHub",
      "kind": "symbol",
      "role": "symbol",
      "title": "HMErrorCodeIncompatibleHomeHub",
      "type": "topic",
      "url": "/documentation/homekit/hmerrorcode/hmerrorcodeincompatiblehomehub"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code/title",
          "value": "HMErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1noCompatibleHomeHub/title",
          "value": "HMErrorCodeNoCompatibleHomeHub"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1noCompatibleHomeHub/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeNoCompatibleHomeHub"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmerrorcode/hmerrorcodeincompatiblehomehub"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
