{"kind":"symbol","metadata":{"externalID":"c:objc(cs)ICCameraFile(py)duration","navigatorTitle":[{"kind":"identifier","text":"duration"}],"modules":[{"name":"ImageCaptureCore"}],"role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"title":"duration","platforms":[{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"13.0","name":"iOS"},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"13.0","name":"iPadOS"},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"13.1","name":"Mac Catalyst"},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"10.4","name":"macOS"},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"1.0","name":"visionOS"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile"]]},"seeAlsoSections":[{"anchor":"Inspecting-Video-Properties","identifiers":["doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/highFramerate","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/timeLapse"],"title":"Inspecting Video Properties","generated":true}],"abstract":[{"type":"text","text":"The duration, in seconds, of an audio or video file."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"duration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","identifier":"doc://com.externally.resolved.symbol/s:Sd","text":"Double","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/imagecapturecore/iccamerafile/duration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/imagecapturecore/iccamerafile/duration"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/duration","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore":{"title":"ImageCaptureCore","role":"collection","kind":"symbol","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore","abstract":[{"text":"Browse for media devices and control them programmatically from your app.","type":"text"}],"type":"topic","url":"/documentation/imagecapturecore"},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/timeLapse":{"kind":"symbol","title":"timeLapse","role":"symbol","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/timeLapse","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeLapse"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"timeLapse","kind":"identifier"}],"url":"/documentation/imagecapturecore/iccamerafile/timelapse","abstract":[{"type":"text","text":"A Boolean value that indicates whether the file is a time-lapse video file."}],"type":"topic"},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/duration":{"kind":"symbol","title":"duration","role":"symbol","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/duration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"duration","kind":"identifier"}],"url":"/documentation/imagecapturecore/iccamerafile/duration","abstract":[{"type":"text","text":"The duration, in seconds, of an audio or video file."}],"type":"topic"},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile":{"kind":"symbol","title":"ICCameraFile","type":"topic","role":"symbol","abstract":[{"type":"text","text":"An object that represents a file on a camera."}],"url":"/documentation/imagecapturecore/iccamerafile","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile","navigatorTitle":[{"text":"ICCameraFile","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ICCameraFile","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","kind":"technologies","role":"overview","title":"Technologies","abstract":[{"text":"","type":"text"}]},"doc://com.externally.resolved.symbol/s:Sd":{"kind":"symbol","role":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Double","kind":"identifier"}],"abstract":[{"type":"text","text":"A double-precision, floating-point value type."}],"type":"topic","title":"Double","identifier":"doc://com.externally.resolved.symbol/s:Sd","url":"/documentation/Swift/Double"},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/highFramerate":{"kind":"symbol","title":"highFramerate","role":"symbol","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/highFramerate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highFramerate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"highFramerate","kind":"identifier"}],"url":"/documentation/imagecapturecore/iccamerafile/highframerate","abstract":[{"type":"text","text":"A Boolean value that indicates whether the file is a slow motion or high-frame-rate video file."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"introducedAt":"13.0","unavailable":false,"beta":false,"deprecated":false,"name":"iOS"},{"introducedAt":"13.0","unavailable":false,"beta":false,"deprecated":false,"name":"iPadOS"},{"introducedAt":"13.1","name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"10.4","name":"macOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"1.0","name":"visionOS","deprecated":false,"unavailable":false,"beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"duration","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"duration"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"generated":true,"title":"Inspecting Video Properties","identifiers":["doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/highFramerate","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/timeLapse"],"anchor":"Inspecting-Video-Properties"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":"timeLapse","op":"replace","path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile~1timeLapse/title"},{"value":[{"kind":"identifier","text":"timeLapse"}],"op":"replace","path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile~1timeLapse/fragments"},{"value":"duration","op":"replace","path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile~1duration/title"},{"value":[{"kind":"identifier","text":"duration"}],"op":"replace","path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile~1duration/fragments"},{"value":"ICCameraFile","op":"replace","path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile/title"},{"value":[{"text":"ICCameraFile","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile/fragments"},{"value":[{"kind":"identifier","text":"ICCameraFile"}],"op":"replace","path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile/navigatorTitle"},{"value":"highFramerate","op":"replace","path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile~1highFramerate/title"},{"value":[{"kind":"identifier","text":"highFramerate"}],"op":"replace","path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile~1highFramerate/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}