{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fileSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"off_t","preciseIdentifier":"c:@T@off_t","identifier":"doc://com.externally.resolved.symbol/c:@T@off_t","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/imagecapturecore/iccamerafile/filesize"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/imagecapturecore/iccamerafile/filesize"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The size of the file, in bytes.","type":"text"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/fileSize"},"metadata":{"title":"fileSize","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fileSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@off_t","text":"off_t","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"fileSize","kind":"identifier"}],"symbolKind":"property","externalID":"c:objc(cs)ICCameraFile(py)fileSize","modules":[{"name":"ImageCaptureCore"}],"platforms":[{"unavailable":false,"deprecated":false,"beta":false,"name":"iOS","introducedAt":"13.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"iPadOS","introducedAt":"13.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"Mac Catalyst","introducedAt":"13.1"},{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS","introducedAt":"10.4"},{"unavailable":false,"deprecated":false,"beta":false,"name":"visionOS","introducedAt":"1.0"}],"roleHeading":"Instance Property"},"references":{"doc://com.apple.documentation/documentation/technologies":{"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","kind":"technologies","role":"overview","title":"Technologies","abstract":[{"text":"","type":"text"}]},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/fileSize":{"title":"fileSize","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"fileSize","kind":"identifier"}],"url":"/documentation/imagecapturecore/iccamerafile/filesize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileSize"},{"kind":"text","text":": "},{"text":"off_t","preciseIdentifier":"c:@T@off_t","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"The size of the file, in bytes.","type":"text"}],"identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/fileSize"},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore":{"title":"ImageCaptureCore","role":"collection","kind":"symbol","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore","abstract":[{"text":"Browse for media devices and control them programmatically from your app.","type":"text"}],"type":"topic","url":"/documentation/imagecapturecore"},"doc://com.externally.resolved.symbol/c:@T@off_t":{"url":"/documentation/kernel/off_t","type":"topic","abstract":[{"text":"","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@T@off_t","title":"off_t"},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile":{"kind":"symbol","title":"ICCameraFile","type":"topic","role":"symbol","abstract":[{"type":"text","text":"An object that represents a file on a camera."}],"url":"/documentation/imagecapturecore/iccamerafile","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile","navigatorTitle":[{"text":"ICCameraFile","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ICCameraFile","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"13.0"},{"name":"iPadOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"13.0"},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"13.1"},{"name":"macOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"10.4"},{"name":"visionOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"1.0"}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"op":"replace","value":"fileSize","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"fileSize","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"add","value":null,"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@off_t","text":"off_t","identifier":"doc://com.externally.resolved.symbol/c:@T@off_t"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileSize"},{"kind":"text","text":";"}]}]},"path":"/primaryContentSections/0"},{"op":"replace","value":"fileSize","path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile~1fileSize/title"},{"op":"replace","value":[{"text":"fileSize","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile~1fileSize/fragments"},{"op":"replace","value":"ICCameraFile","path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile/title"},{"op":"replace","value":[{"text":"ICCameraFile","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile/fragments"},{"op":"replace","value":[{"text":"ICCameraFile","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}