{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/imagecapturecore/iccamerafile/height"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/imagecapturecore/iccamerafile/height"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","identifier":"doc://com.externally.resolved.symbol/s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","abstract":[{"text":"The height of an image or movie frame.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/height"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"ImageCaptureCore"}],"platforms":[{"beta":false,"name":"iOS","deprecated":false,"introducedAt":"13.0","unavailable":false},{"beta":false,"name":"iPadOS","deprecated":false,"introducedAt":"13.0","unavailable":false},{"beta":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.1","unavailable":false},{"beta":false,"name":"macOS","deprecated":false,"introducedAt":"10.4","unavailable":false},{"deprecated":false,"beta":false,"name":"visionOS","unavailable":false,"introducedAt":"1.0"}],"title":"height","navigatorTitle":[{"text":"height","kind":"identifier"}],"externalID":"c:objc(cs)ICCameraFile(py)height","role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"roleHeading":"Instance Property"},"seeAlsoSections":[{"title":"Inspecting a File’s Dimensions","identifiers":["doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/width"],"generated":true,"anchor":"Inspecting-a-Files-Dimensions"}],"references":{"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile":{"kind":"symbol","title":"ICCameraFile","type":"topic","role":"symbol","abstract":[{"type":"text","text":"An object that represents a file on a camera."}],"url":"/documentation/imagecapturecore/iccamerafile","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile","navigatorTitle":[{"text":"ICCameraFile","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ICCameraFile","kind":"identifier"}]},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/height":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"title":"height","url":"/documentation/imagecapturecore/iccamerafile/height","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The height of an image or movie frame."}],"identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/height","navigatorTitle":[{"text":"height","kind":"identifier"}]},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore":{"title":"ImageCaptureCore","role":"collection","kind":"symbol","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore","abstract":[{"text":"Browse for media devices and control them programmatically from your app.","type":"text"}],"type":"topic","url":"/documentation/imagecapturecore"},"doc://com.externally.resolved.symbol/s:Si":{"identifier":"doc://com.externally.resolved.symbol/s:Si","kind":"symbol","type":"topic","url":"/documentation/Swift/Int","abstract":[{"text":"A signed integer value type.","type":"text"}],"fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}],"title":"Int","role":"symbol"},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/width":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"width","url":"/documentation/imagecapturecore/iccamerafile/width","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The width of an image or movie frame."}],"identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/width","navigatorTitle":[{"kind":"identifier","text":"width"}]},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","kind":"technologies","role":"overview","title":"Technologies","abstract":[{"text":"","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":[{"beta":false,"name":"iOS","deprecated":false,"introducedAt":"13.0","unavailable":false},{"beta":false,"name":"iPadOS","deprecated":false,"introducedAt":"13.0","unavailable":false},{"beta":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.1","unavailable":false},{"beta":false,"name":"macOS","deprecated":false,"introducedAt":"10.4","unavailable":false},{"deprecated":false,"beta":false,"name":"visionOS","unavailable":false,"introducedAt":"1.0"}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"height","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"height","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"title":"Inspecting a File’s Dimensions","generated":true,"identifiers":["doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/width"],"anchor":"Inspecting-a-Files-Dimensions"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"kind":"text","text":";"}]}]},"path":"/primaryContentSections/0"},{"op":"replace","value":"ICCameraFile","path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile/title"},{"op":"replace","value":[{"kind":"identifier","text":"ICCameraFile"}],"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile/fragments"},{"op":"replace","value":[{"text":"ICCameraFile","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile/navigatorTitle"},{"op":"replace","value":"height","path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile~1height/title"},{"op":"replace","value":[{"kind":"identifier","text":"height"}],"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile~1height/fragments"},{"op":"replace","value":"width","path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile~1width/title"},{"op":"replace","value":[{"kind":"identifier","text":"width"}],"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile~1width/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}