{"variants":[{"paths":["/documentation/imagecapturecore/iccamerafile/originatingassetid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/imagecapturecore/iccamerafile/originatingassetid"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"originatingAssetID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"platforms":[{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"13.0","name":"iOS"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"13.0","name":"iPadOS"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"13.1","name":"Mac Catalyst"},{"unavailable":false,"introducedAt":"10.4","deprecated":false,"name":"macOS","beta":false},{"unavailable":false,"introducedAt":"1.0","deprecated":false,"name":"visionOS","beta":false}],"symbolKind":"property","roleHeading":"Instance Property","title":"originatingAssetID","navigatorTitle":[{"kind":"identifier","text":"originatingAssetID"}],"modules":[{"name":"ImageCaptureCore"}],"externalID":"c:objc(cs)ICCameraFile(py)originatingAssetID"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"originatingAssetID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","identifier":"doc://com.externally.resolved.symbol/s:SS","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"The originating asset ID of an "},{"code":"HEIF","type":"codeVoice"},{"type":"text","text":" or "},{"code":"HVEC","type":"codeVoice"},{"text":" file.","type":"text"}],"kind":"symbol","sections":[],"identifier":{"url":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/originatingAssetID","interfaceLanguage":"swift"},"seeAlsoSections":[{"identifiers":["doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/groupUUID","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/relatedUUID"],"title":"Inspecting a File’s Identity","generated":true,"anchor":"Inspecting-a-Files-Identity"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile"]]},"references":{"doc://com.apple.documentation/documentation/technologies":{"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","kind":"technologies","role":"overview","title":"Technologies","abstract":[{"text":"","type":"text"}]},"doc://com.externally.resolved.symbol/s:SS":{"title":"String","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"String","kind":"identifier"}],"abstract":[{"type":"text","text":"A Unicode string value that is a collection of characters."}],"type":"topic","identifier":"doc://com.externally.resolved.symbol/s:SS","url":"/documentation/Swift/String","role":"symbol","kind":"symbol"},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/relatedUUID":{"navigatorTitle":[{"text":"relatedUUID","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/relatedUUID","abstract":[{"text":"A related UUID correlating several images from an Apple device.","type":"text"}],"kind":"symbol","type":"topic","title":"relatedUUID","url":"/documentation/imagecapturecore/iccamerafile/relateduuid","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"relatedUUID","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile":{"kind":"symbol","title":"ICCameraFile","type":"topic","role":"symbol","abstract":[{"type":"text","text":"An object that represents a file on a camera."}],"url":"/documentation/imagecapturecore/iccamerafile","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile","navigatorTitle":[{"text":"ICCameraFile","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ICCameraFile","kind":"identifier"}]},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/originatingAssetID":{"navigatorTitle":[{"text":"originatingAssetID","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/originatingAssetID","abstract":[{"text":"The originating asset ID of an ","type":"text"},{"type":"codeVoice","code":"HEIF"},{"type":"text","text":" or "},{"code":"HVEC","type":"codeVoice"},{"type":"text","text":" file."}],"kind":"symbol","type":"topic","title":"originatingAssetID","url":"/documentation/imagecapturecore/iccamerafile/originatingassetid","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"originatingAssetID","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/groupUUID":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"groupUUID","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The group "},{"code":"UUID","type":"codeVoice"},{"type":"text","text":" of the file."}],"title":"groupUUID","role":"symbol","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/groupUUID","url":"/documentation/imagecapturecore/iccamerafile/groupuuid","type":"topic","navigatorTitle":[{"text":"groupUUID","kind":"identifier"}]},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore":{"title":"ImageCaptureCore","role":"collection","kind":"symbol","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore","abstract":[{"text":"Browse for media devices and control them programmatically from your app.","type":"text"}],"type":"topic","url":"/documentation/imagecapturecore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"introducedAt":"13.0","name":"iOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"13.0","name":"iPadOS","unavailable":false,"beta":false},{"unavailable":false,"introducedAt":"13.1","deprecated":false,"name":"Mac Catalyst","beta":false},{"unavailable":false,"introducedAt":"10.4","deprecated":false,"name":"macOS","beta":false},{"unavailable":false,"introducedAt":"1.0","deprecated":false,"name":"visionOS","beta":false}],"path":"/metadata/platforms"},{"path":"/metadata/roleHeading","value":"Instance Property","op":"replace"},{"path":"/metadata/title","value":"originatingAssetID","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"originatingAssetID"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile"]]},"path":"/hierarchy"},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"identifiers":["doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/groupUUID","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/relatedUUID"],"anchor":"Inspecting-a-Files-Identity","title":"Inspecting a File’s Identity"}]},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"originatingAssetID"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile~1relatedUUID/title","value":"relatedUUID"},{"op":"replace","path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile~1relatedUUID/fragments","value":[{"kind":"identifier","text":"relatedUUID"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile/title","value":"ICCameraFile"},{"op":"replace","path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile/fragments","value":[{"kind":"identifier","text":"ICCameraFile"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile/navigatorTitle","value":[{"text":"ICCameraFile","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile~1originatingAssetID/title","value":"originatingAssetID"},{"op":"replace","path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile~1originatingAssetID/fragments","value":[{"kind":"identifier","text":"originatingAssetID"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile~1groupUUID/title","value":"groupUUID"},{"op":"replace","value":[{"kind":"identifier","text":"groupUUID"}],"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile~1groupUUID/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}