{"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestSecurityScopedURL"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" ("},{"identifier":"doc://com.externally.resolved.symbol/s:10Foundation3URLV","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"?, (any "},{"identifier":"doc://com.externally.resolved.symbol/s:s5ErrorP","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")?) -> "},{"identifier":"doc://com.externally.resolved.symbol/s:s4Voida","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}]},{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestSecurityScopedURL","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:10Foundation3URLV"}]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"ImageCaptureCore"}],"platforms":[{"deprecated":false,"name":"iOS","introducedAt":"17.0","beta":false,"unavailable":false},{"deprecated":false,"name":"iPadOS","introducedAt":"17.0","beta":false,"unavailable":false},{"deprecated":false,"name":"Mac Catalyst","introducedAt":"17.0","beta":false,"unavailable":false},{"deprecated":false,"name":"macOS","introducedAt":"14.0","beta":false,"unavailable":false},{"deprecated":false,"name":"visionOS","introducedAt":"1.0","beta":false,"unavailable":false}],"title":"requestSecurityScopedURL(completion:)","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ICCameraFile(im)requestSecurityScopedURLWithCompletion:","navigatorTitle":[{"kind":"identifier","text":"requestSecurityScopedURLWithCompletion:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestSecurityScopedURL"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"?, (any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"roleHeading":"Instance Method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"paths":["/documentation/imagecapturecore/iccamerafile/requestsecurityscopedurl(completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/imagecapturecore/iccamerafile/requestsecurityscopedurl(completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/requestSecurityScopedURL(completion:)"},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile"]]},"references":{"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/requestSecurityScopedURL(completion:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestSecurityScopedURL"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"?, (any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"requestSecurityScopedURLWithCompletion:","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/requestSecurityScopedURL(completion:)","url":"/documentation/imagecapturecore/iccamerafile/requestsecurityscopedurl(completion:)","kind":"symbol","title":"requestSecurityScopedURL(completion:)","abstract":[]},"doc://com.externally.resolved.symbol/s:10Foundation3URLV":{"kind":"symbol","url":"/documentation/foundation/url","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"URL"}],"title":"URL","abstract":[{"type":"text","text":"A value that identifies the location of a resource, such as an item on a remote server or the path to a local file."}],"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:10Foundation3URLV","type":"topic"},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile":{"kind":"symbol","title":"ICCameraFile","type":"topic","role":"symbol","abstract":[{"type":"text","text":"An object that represents a file on a camera."}],"url":"/documentation/imagecapturecore/iccamerafile","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile","navigatorTitle":[{"text":"ICCameraFile","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ICCameraFile","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:s5ErrorP":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:s8SendableP","kind":"typeIdentifier","text":"Sendable"}],"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s5ErrorP","url":"/documentation/Swift/Error","title":"Error","type":"topic","abstract":[{"type":"text","text":"A type representing an error value that can be thrown."}],"kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSURL":{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSURL","url":"/documentation/foundation/nsurl","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSURL"}],"role":"symbol","abstract":[{"text":"An object representing the location of a resource that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"kind":"symbol","title":"NSURL","type":"topic"},"doc://com.externally.resolved.symbol/s:s4Voida":{"kind":"symbol","url":"/documentation/Swift/Void","title":"Void","identifier":"doc://com.externally.resolved.symbol/s:s4Voida","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Void","kind":"identifier"},{"text":" = ()","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`."}],"role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","kind":"technologies","role":"overview","title":"Technologies","abstract":[{"text":"","type":"text"}]},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore":{"title":"ImageCaptureCore","role":"collection","kind":"symbol","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore","abstract":[{"text":"Browse for media devices and control them programmatically from your app.","type":"text"}],"type":"topic","url":"/documentation/imagecapturecore"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"introducedAt":"17.0","name":"iOS","beta":false,"deprecated":false,"unavailable":false},{"introducedAt":"17.0","name":"iPadOS","beta":false,"deprecated":false,"unavailable":false},{"introducedAt":"17.0","name":"Mac Catalyst","beta":false,"deprecated":false,"unavailable":false},{"introducedAt":"14.0","name":"macOS","beta":false,"deprecated":false,"unavailable":false},{"introducedAt":"1.0","name":"visionOS","beta":false,"deprecated":false,"unavailable":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"requestSecurityScopedURLWithCompletion:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"requestSecurityScopedURLWithCompletion:","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"add","value":null,"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"requestSecurityScopedURLWithCompletion:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" (^)("},{"preciseIdentifier":"c:objc(cs)NSURL","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSURL","kind":"typeIdentifier","text":"NSURL"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile~1requestSecurityScopedURL(completion:)/title","op":"replace","value":"requestSecurityScopedURLWithCompletion:"},{"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile~1requestSecurityScopedURL(completion:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"requestSecurityScopedURLWithCompletion:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile/title","op":"replace","value":"ICCameraFile"},{"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile/fragments","op":"replace","value":[{"text":"ICCameraFile","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ICCameraFile"}]},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSURL/abstract","op":"replace","value":[{"text":"An object that represents the location of a resource, such as an item on a remote server or the path to a local file. ","type":"text"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}