{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/width"},"variants":[{"paths":["/documentation/imagecapturecore/iccamerafile/width"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/imagecapturecore/iccamerafile/width"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","seeAlsoSections":[{"generated":true,"title":"Inspecting a File’s Dimensions","anchor":"Inspecting-a-Files-Dimensions","identifiers":["doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/height"]}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"ImageCaptureCore"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"width"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"externalID":"c:objc(cs)ICCameraFile(py)width","title":"width","platforms":[{"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"13.0","beta":false},{"unavailable":false,"name":"iPadOS","deprecated":false,"introducedAt":"13.0","beta":false},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.1","beta":false},{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"10.4","name":"macOS"},{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"1.0","name":"visionOS"}],"role":"symbol","roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"The width of an image or movie frame."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","identifier":"doc://com.externally.resolved.symbol/s:Si","text":"Int","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"]}],"kind":"declarations"}],"references":{"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/width":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"width","url":"/documentation/imagecapturecore/iccamerafile/width","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The width of an image or movie frame."}],"identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/width","navigatorTitle":[{"kind":"identifier","text":"width"}]},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile":{"kind":"symbol","title":"ICCameraFile","type":"topic","role":"symbol","abstract":[{"type":"text","text":"An object that represents a file on a camera."}],"url":"/documentation/imagecapturecore/iccamerafile","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile","navigatorTitle":[{"text":"ICCameraFile","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ICCameraFile","kind":"identifier"}]},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/height":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"title":"height","url":"/documentation/imagecapturecore/iccamerafile/height","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The height of an image or movie frame."}],"identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/height","navigatorTitle":[{"text":"height","kind":"identifier"}]},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore":{"title":"ImageCaptureCore","role":"collection","kind":"symbol","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore","abstract":[{"text":"Browse for media devices and control them programmatically from your app.","type":"text"}],"type":"topic","url":"/documentation/imagecapturecore"},"doc://com.externally.resolved.symbol/s:Si":{"identifier":"doc://com.externally.resolved.symbol/s:Si","kind":"symbol","type":"topic","url":"/documentation/Swift/Int","abstract":[{"text":"A signed integer value type.","type":"text"}],"fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}],"title":"Int","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","kind":"technologies","role":"overview","title":"Technologies","abstract":[{"text":"","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"13.0","beta":false},{"unavailable":false,"name":"iPadOS","deprecated":false,"introducedAt":"13.0","beta":false},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.1","beta":false},{"unavailable":false,"name":"macOS","deprecated":false,"introducedAt":"10.4","beta":false},{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"1.0","name":"visionOS"}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"width","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"width","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"title":"Inspecting a File’s Dimensions","identifiers":["doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/height"],"generated":true,"anchor":"Inspecting-a-Files-Dimensions"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"]}]},"path":"/primaryContentSections/0"},{"op":"replace","value":"width","path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile~1width/title"},{"op":"replace","value":[{"text":"width","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile~1width/fragments"},{"op":"replace","value":"ICCameraFile","path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile/title"},{"op":"replace","value":[{"kind":"identifier","text":"ICCameraFile"}],"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile/fragments"},{"op":"replace","value":[{"text":"ICCameraFile","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile/navigatorTitle"},{"op":"replace","value":"height","path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile~1height/title"},{"op":"replace","value":[{"text":"height","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile~1height/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}