{
  "abstract": [
    {
      "text": "Any bold text.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/boldText"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIAccessibilityCustomSystemRotorType@UIAccessibilityCustomSystemRotorTypeBoldText",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "boldText"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIAccessibilityCustomSystemRotorTypeBoldText"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIAccessibilityCustomRotor.SystemRotorType.boldText"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "boldText"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor": {
      "abstract": [
        {
          "text": "A context-sensitive function that helps VoiceOver users find the next instance of a related element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAccessibilityCustomRotor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityCustomRotor"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityCustomRotor",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomrotor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum": {
      "abstract": [
        {
          "text": "Constants that indicate the type of content that the rotor represents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SystemRotorType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SystemRotorType"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityCustomRotor.SystemRotorType",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomrotor/systemrotortype-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/boldText": {
      "abstract": [
        {
          "text": "Any bold text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "boldText"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/boldText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityCustomSystemRotorTypeBoldText"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityCustomRotor.SystemRotorType.boldText",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomrotor/systemrotortype-swift.enum/boldtext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/heading": {
      "abstract": [
        {
          "text": "Any heading-level text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "heading"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/heading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityCustomSystemRotorTypeHeading"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityCustomRotor.SystemRotorType.heading",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomrotor/systemrotortype-swift.enum/heading"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/headingLevel1": {
      "abstract": [
        {
          "text": "A first-level heading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headingLevel1"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/headingLevel1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityCustomSystemRotorTypeHeadingLevel1"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityCustomRotor.SystemRotorType.headingLevel1",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomrotor/systemrotortype-swift.enum/headinglevel1"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/headingLevel2": {
      "abstract": [
        {
          "text": "A second-level heading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headingLevel2"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/headingLevel2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityCustomSystemRotorTypeHeadingLevel2"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityCustomRotor.SystemRotorType.headingLevel2",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomrotor/systemrotortype-swift.enum/headinglevel2"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/headingLevel3": {
      "abstract": [
        {
          "text": "A third-level heading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headingLevel3"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/headingLevel3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityCustomSystemRotorTypeHeadingLevel3"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityCustomRotor.SystemRotorType.headingLevel3",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomrotor/systemrotortype-swift.enum/headinglevel3"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/headingLevel4": {
      "abstract": [
        {
          "text": "A fourth-level heading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headingLevel4"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/headingLevel4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityCustomSystemRotorTypeHeadingLevel4"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityCustomRotor.SystemRotorType.headingLevel4",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomrotor/systemrotortype-swift.enum/headinglevel4"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/headingLevel5": {
      "abstract": [
        {
          "text": "A fifth-level heading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headingLevel5"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/headingLevel5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityCustomSystemRotorTypeHeadingLevel5"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityCustomRotor.SystemRotorType.headingLevel5",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomrotor/systemrotortype-swift.enum/headinglevel5"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/headingLevel6": {
      "abstract": [
        {
          "text": "A sixth-level heading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headingLevel6"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/headingLevel6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityCustomSystemRotorTypeHeadingLevel6"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityCustomRotor.SystemRotorType.headingLevel6",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomrotor/systemrotortype-swift.enum/headinglevel6"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/image": {
      "abstract": [
        {
          "text": "An image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "image"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/image",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityCustomSystemRotorTypeImage"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityCustomRotor.SystemRotorType.image",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomrotor/systemrotortype-swift.enum/image"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/italicText": {
      "abstract": [
        {
          "text": "Any italicized text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "italicText"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/italicText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityCustomSystemRotorTypeItalicText"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityCustomRotor.SystemRotorType.italicText",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomrotor/systemrotortype-swift.enum/italictext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/link": {
      "abstract": [
        {
          "text": "A link.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "link"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/link",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityCustomSystemRotorTypeLink"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityCustomRotor.SystemRotorType.link",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomrotor/systemrotortype-swift.enum/link"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/misspelledWord": {
      "abstract": [
        {
          "text": "A misspelled word.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "misspelledWord"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/misspelledWord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityCustomSystemRotorTypeMisspelledWord"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityCustomRotor.SystemRotorType.misspelledWord",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomrotor/systemrotortype-swift.enum/misspelledword"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/none": {
      "abstract": [
        {
          "text": "No specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityCustomSystemRotorTypeNone"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityCustomRotor.SystemRotorType.none",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomrotor/systemrotortype-swift.enum/none"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/textField": {
      "abstract": [
        {
          "text": "A text field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textField"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/textField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityCustomSystemRotorTypeTextField"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityCustomRotor.SystemRotorType.textField",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomrotor/systemrotortype-swift.enum/textfield"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/underlineText": {
      "abstract": [
        {
          "text": "Any underlined text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "underlineText"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/underlineText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityCustomSystemRotorTypeUnderlineText"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityCustomRotor.SystemRotorType.underlineText",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomrotor/systemrotortype-swift.enum/underlinetext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/visitedLink": {
      "abstract": [
        {
          "text": "A visited link.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visitedLink"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/visitedLink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityCustomSystemRotorTypeVisitedLink"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityCustomRotor.SystemRotorType.visitedLink",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomrotor/systemrotortype-swift.enum/visitedlink"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/none",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/link",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/visitedLink",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/heading",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/headingLevel1",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/headingLevel2",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/headingLevel3",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/headingLevel4",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/headingLevel5",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/headingLevel6",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/italicText",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/underlineText",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/misspelledWord",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/image",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/textField"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIAccessibilityCustomSystemRotorTypeBoldText"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomSystemRotorTypeBoldText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/none",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/link",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/visitedLink",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/heading",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/headingLevel1",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/headingLevel2",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/headingLevel3",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/headingLevel4",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/headingLevel5",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/headingLevel6",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/italicText",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/underlineText",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/misspelledWord",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/image",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum/textField"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIAccessibilityCustomSystemRotorTypeBoldText"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor/title",
          "value": "UIAccessibilityCustomRotor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomRotor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomRotor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1headingLevel3/title",
          "value": "UIAccessibilityCustomSystemRotorTypeHeadingLevel3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1headingLevel3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomSystemRotorTypeHeadingLevel3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1none/title",
          "value": "UIAccessibilityCustomSystemRotorTypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomSystemRotorTypeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1heading/title",
          "value": "UIAccessibilityCustomSystemRotorTypeHeading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1heading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomSystemRotorTypeHeading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1textField/title",
          "value": "UIAccessibilityCustomSystemRotorTypeTextField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1textField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomSystemRotorTypeTextField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1underlineText/title",
          "value": "UIAccessibilityCustomSystemRotorTypeUnderlineText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1underlineText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomSystemRotorTypeUnderlineText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1headingLevel4/title",
          "value": "UIAccessibilityCustomSystemRotorTypeHeadingLevel4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1headingLevel4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomSystemRotorTypeHeadingLevel4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1headingLevel1/title",
          "value": "UIAccessibilityCustomSystemRotorTypeHeadingLevel1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1headingLevel1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomSystemRotorTypeHeadingLevel1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1headingLevel5/title",
          "value": "UIAccessibilityCustomSystemRotorTypeHeadingLevel5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1headingLevel5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomSystemRotorTypeHeadingLevel5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1link/title",
          "value": "UIAccessibilityCustomSystemRotorTypeLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1link/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomSystemRotorTypeLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1boldText/title",
          "value": "UIAccessibilityCustomSystemRotorTypeBoldText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1boldText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomSystemRotorTypeBoldText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1italicText/title",
          "value": "UIAccessibilityCustomSystemRotorTypeItalicText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1italicText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomSystemRotorTypeItalicText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1misspelledWord/title",
          "value": "UIAccessibilityCustomSystemRotorTypeMisspelledWord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1misspelledWord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomSystemRotorTypeMisspelledWord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1visitedLink/title",
          "value": "UIAccessibilityCustomSystemRotorTypeVisitedLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1visitedLink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomSystemRotorTypeVisitedLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1image/title",
          "value": "UIAccessibilityCustomSystemRotorTypeImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1image/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomSystemRotorTypeImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1headingLevel2/title",
          "value": "UIAccessibilityCustomSystemRotorTypeHeadingLevel2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1headingLevel2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomSystemRotorTypeHeadingLevel2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1headingLevel6/title",
          "value": "UIAccessibilityCustomSystemRotorTypeHeadingLevel6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum~1headingLevel6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomSystemRotorTypeHeadingLevel6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum/title",
          "value": "UIAccessibilityCustomSystemRotorType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomSystemRotorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomSystemRotorType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiaccessibilitycustomrotor/systemrotortype-swift.enum/boldtext"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiaccessibilitycustomrotor/systemrotortype-swift.enum/boldtext"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
