{
  "abstract": [
    {
      "text": "The frame rectangle to use for displaying a media playback button.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI",
        "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtension/mediaPlayPauseButtonFrame"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UNNotificationContentExtension(py)mediaPlayPauseButtonFrame",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "mediaPlayPauseButtonFrame"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@CGRect",
        "text": "CGRect"
      }
    ],
    "modules": [
      {
        "name": "User Notifications UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "mediaPlayPauseButtonFrame"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "mediaPlayPauseButtonFrame"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "mediaPlayPauseButtonFrame"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@CGRect",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CGRect",
              "text": "CGRect"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/customizing-the-appearance-of-notifications"
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you support the playback of media directly from your notification",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "interface, implement this property and use it to return a nonempty rectangle",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "specified in the coordinate system of your view controller’s view. The",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "system draws a button in the provided rectangle that lets the user play and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "pause your media content. The system handles the drawing of the button for",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "you and calls the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtension/mediaPlay()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtension/mediaPause()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " methods in response to user",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "interactions. You can place this button anywhere in your view controller’s",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you don’t implement this property, the system doesn’t draw a media",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "playback button.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI": {
      "abstract": [
        {
          "text": "Customize the interface that displays local and remote notifications.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI",
      "kind": "symbol",
      "role": "collection",
      "title": "User Notifications UI",
      "type": "topic",
      "url": "/documentation/usernotificationsui"
    },
    "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtension": {
      "abstract": [
        {
          "text": "An object that presents a custom interface for a delivered local or remote",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UNNotificationContentExtension"
        }
      ],
      "identifier": "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationContentExtension"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationContentExtension",
      "type": "topic",
      "url": "/documentation/usernotificationsui/unnotificationcontentextension"
    },
    "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtension/mediaPause()": {
      "abstract": [
        {
          "text": "Tells you to pause playback of your media content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaPause"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtension/mediaPause()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mediaPause"
        }
      ],
      "role": "symbol",
      "title": "mediaPause()",
      "type": "topic",
      "url": "/documentation/usernotificationsui/unnotificationcontentextension/mediapause()"
    },
    "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtension/mediaPlay()": {
      "abstract": [
        {
          "text": "Tells you to begin playback of your media content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaPlay"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtension/mediaPlay()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mediaPlay"
        }
      ],
      "role": "symbol",
      "title": "mediaPlay()",
      "type": "topic",
      "url": "/documentation/usernotificationsui/unnotificationcontentextension/mediaplay()"
    },
    "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtension/mediaPlayPauseButtonFrame": {
      "abstract": [
        {
          "text": "The frame rectangle to use for displaying a media playback button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaPlayPauseButtonFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtension/mediaPlayPauseButtonFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mediaPlayPauseButtonFrame"
        }
      ],
      "role": "symbol",
      "title": "mediaPlayPauseButtonFrame",
      "type": "topic",
      "url": "/documentation/usernotificationsui/unnotificationcontentextension/mediaplaypausebuttonframe"
    },
    "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtension/mediaPlayPauseButtonTintColor": {
      "abstract": [
        {
          "text": "The tint color for the media playback button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaPlayPauseButtonTintColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtension/mediaPlayPauseButtonTintColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mediaPlayPauseButtonTintColor"
        }
      ],
      "role": "symbol",
      "title": "mediaPlayPauseButtonTintColor",
      "type": "topic",
      "url": "/documentation/usernotificationsui/unnotificationcontentextension/mediaplaypausebuttontintcolor"
    },
    "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtension/mediaPlayPauseButtonType": {
      "abstract": [
        {
          "text": "The type of media button type to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaPlayPauseButtonType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UNNotificationContentExtensionMediaPlayPauseButtonType",
          "text": "UNNotificationContentExtensionMediaPlayPauseButtonType"
        }
      ],
      "identifier": "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtension/mediaPlayPauseButtonType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mediaPlayPauseButtonType"
        }
      ],
      "role": "symbol",
      "title": "mediaPlayPauseButtonType",
      "type": "topic",
      "url": "/documentation/usernotificationsui/unnotificationcontentextension/mediaplaypausebuttontype"
    },
    "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionMediaPlayPauseButtonType": {
      "abstract": [
        {
          "text": "Constants indicating the type of media button to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UNNotificationContentExtensionMediaPlayPauseButtonType"
        }
      ],
      "identifier": "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionMediaPlayPauseButtonType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationContentExtensionMediaPlayPauseButtonType"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationContentExtensionMediaPlayPauseButtonType",
      "type": "topic",
      "url": "/documentation/usernotificationsui/unnotificationcontentextensionmediaplaypausebuttontype"
    },
    "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/customizing-the-appearance-of-notifications": {
      "abstract": [
        {
          "text": "Customize the appearance of your iOS app’s notification alerts with a notification",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "content app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/customizing-the-appearance-of-notifications",
      "kind": "article",
      "role": "article",
      "title": "Customizing the Appearance of Notifications",
      "type": "topic",
      "url": "/documentation/usernotificationsui/customizing-the-appearance-of-notifications"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@S@CGRect": {
      "abstract": [
        {
          "text": "A structure that contains the location and dimensions of a rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@CGRect",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGRect",
      "type": "topic",
      "url": "/documentation/corefoundation/cgrect"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Supporting-Media-Playback",
      "generated": true,
      "identifiers": [
        "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtension/mediaPlayPauseButtonType",
        "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionMediaPlayPauseButtonType",
        "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtension/mediaPlayPauseButtonTintColor",
        "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtension/mediaPlay()",
        "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtension/mediaPause()"
      ],
      "title": "Supporting Media Playback"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "mediaPlayPauseButtonFrame"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mediaPlayPauseButtonFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI",
                "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtension"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Supporting-Media-Playback",
              "generated": true,
              "identifiers": [
                "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtension/mediaPlayPauseButtonType",
                "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionMediaPlayPauseButtonType",
                "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtension/mediaPlayPauseButtonTintColor",
                "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtension/mediaPlay()",
                "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtension/mediaPause()"
              ],
              "title": "Supporting Media Playback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@CGRect",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@CGRect",
                    "text": "CGRect"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "mediaPlayPauseButtonFrame"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtension~1mediaPlayPauseButtonFrame/title",
          "value": "mediaPlayPauseButtonFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtension~1mediaPlayPauseButtonFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mediaPlayPauseButtonFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtension~1mediaPause()/title",
          "value": "mediaPause"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtension~1mediaPause()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mediaPause"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtension~1mediaPlay()/title",
          "value": "mediaPlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtension~1mediaPlay()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mediaPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtensionMediaPlayPauseButtonType/title",
          "value": "UNNotificationContentExtensionMediaPlayPauseButtonType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtensionMediaPlayPauseButtonType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationContentExtensionMediaPlayPauseButtonType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtensionMediaPlayPauseButtonType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationContentExtensionMediaPlayPauseButtonType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtension/title",
          "value": "UNNotificationContentExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationContentExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationContentExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtension~1mediaPlayPauseButtonTintColor/title",
          "value": "mediaPlayPauseButtonTintColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtension~1mediaPlayPauseButtonTintColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mediaPlayPauseButtonTintColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtension~1mediaPlayPauseButtonType/title",
          "value": "mediaPlayPauseButtonType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtension~1mediaPlayPauseButtonType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mediaPlayPauseButtonType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/usernotificationsui/unnotificationcontentextension/mediaplaypausebuttonframe"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/usernotificationsui/unnotificationcontentextension/mediaplaypausebuttonframe"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
