{
  "abstract": [
    {
      "text": "20MHz channel width.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corewlan/documentation/CoreWLAN",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth/width20MHz"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CWChannelWidth@kCWChannelWidth20MHz",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "width20MHz"
      }
    ],
    "modules": [
      {
        "name": "Core WLAN"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCWChannelWidth20MHz"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CWChannelWidth.width20MHz"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "width20MHz"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corewlan/documentation/CoreWLAN": {
      "abstract": [
        {
          "text": "Query AirPort interfaces and choose wireless networks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN",
      "kind": "symbol",
      "role": "collection",
      "title": "Core WLAN",
      "type": "topic",
      "url": "/documentation/corewlan"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth": {
      "abstract": [
        {
          "text": "CoreWLAN channel widths.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWChannelWidth"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWChannelWidth"
        }
      ],
      "role": "symbol",
      "title": "CWChannelWidth",
      "type": "topic",
      "url": "/documentation/corewlan/cwchannelwidth"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth/width160MHz": {
      "abstract": [
        {
          "text": "160MHz channel width.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "width160MHz"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth/width160MHz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWChannelWidth160MHz"
        }
      ],
      "role": "symbol",
      "title": "CWChannelWidth.width160MHz",
      "type": "topic",
      "url": "/documentation/corewlan/cwchannelwidth/width160mhz"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth/width20MHz": {
      "abstract": [
        {
          "text": "20MHz channel width.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "width20MHz"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth/width20MHz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWChannelWidth20MHz"
        }
      ],
      "role": "symbol",
      "title": "CWChannelWidth.width20MHz",
      "type": "topic",
      "url": "/documentation/corewlan/cwchannelwidth/width20mhz"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth/width40MHz": {
      "abstract": [
        {
          "text": "40MHz channel width.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "width40MHz"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth/width40MHz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWChannelWidth40MHz"
        }
      ],
      "role": "symbol",
      "title": "CWChannelWidth.width40MHz",
      "type": "topic",
      "url": "/documentation/corewlan/cwchannelwidth/width40mhz"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth/width80MHz": {
      "abstract": [
        {
          "text": "80MHz channel width.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "width80MHz"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth/width80MHz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWChannelWidth80MHz"
        }
      ],
      "role": "symbol",
      "title": "CWChannelWidth.width80MHz",
      "type": "topic",
      "url": "/documentation/corewlan/cwchannelwidth/width80mhz"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth/widthUnknown": {
      "abstract": [
        {
          "text": "Unknown channel width.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widthUnknown"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth/widthUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWChannelWidthUnknown"
        }
      ],
      "role": "symbol",
      "title": "CWChannelWidth.widthUnknown",
      "type": "topic",
      "url": "/documentation/corewlan/cwchannelwidth/widthunknown"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth/widthUnknown",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth/width40MHz",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth/width80MHz",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth/width160MHz"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCWChannelWidth20MHz"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWChannelWidth20MHz"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corewlan/documentation/CoreWLAN",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth/widthUnknown",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth/width40MHz",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth/width80MHz",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth/width160MHz"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCWChannelWidth20MHz"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelWidth/title",
          "value": "CWChannelWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWChannelWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelWidth/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWChannelWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelWidth~1width40MHz/title",
          "value": "kCWChannelWidth40MHz"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelWidth~1width40MHz/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWChannelWidth40MHz"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelWidth~1width160MHz/title",
          "value": "kCWChannelWidth160MHz"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelWidth~1width160MHz/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWChannelWidth160MHz"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelWidth~1width80MHz/title",
          "value": "kCWChannelWidth80MHz"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelWidth~1width80MHz/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWChannelWidth80MHz"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelWidth~1widthUnknown/title",
          "value": "kCWChannelWidthUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelWidth~1widthUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWChannelWidthUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelWidth~1width20MHz/title",
          "value": "kCWChannelWidth20MHz"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelWidth~1width20MHz/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWChannelWidth20MHz"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corewlan/cwchannelwidth/width20mhz"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corewlan/cwchannelwidth/width20mhz"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
