{
  "abstract": [
    {
      "text": "The text marker range of the current selection.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityTextMarkerRangeForCurrentSelection()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)BEAccessibilityTextMarkerSupport(im)accessibilityTextMarkerRangeForCurrentSelection",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "accessibilityTextMarkerRangeForCurrentSelection"
      },
      {
        "kind": "text",
        "text": "() -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)BEAccessibilityTextMarker",
        "text": "BEAccessibilityTextMarker"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)BEAccessibilityTextMarkerRange",
        "text": "Range"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "BrowserEngineKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "accessibilityTextMarkerRangeForCurrentSelection"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.2",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "accessibilityTextMarkerRangeForCurrentSelection()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "accessibilityTextMarkerRangeForCurrentSelection"
            },
            {
              "kind": "text",
              "text": "() -> "
            },
            {
              "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarker",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)BEAccessibilityTextMarker",
              "text": "BEAccessibilityTextMarker"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarker/Range",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)BEAccessibilityTextMarkerRange",
              "text": "Range"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If there’s no text selected in the element, return ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit": {
      "abstract": [
        {
          "text": "Create a browser that renders content using an alternative browser engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit",
      "kind": "symbol",
      "role": "collection",
      "title": "BrowserEngineKit",
      "type": "topic",
      "url": "/documentation/browserenginekit"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarker": {
      "abstract": [
        {
          "text": "An abstract class that represents a location in an element’s accessibility text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BEAccessibilityTextMarker"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityTextMarker"
        }
      ],
      "role": "symbol",
      "title": "BEAccessibilityTextMarker",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitytextmarker"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarker/Range": {
      "abstract": [
        {
          "text": "A class that represents a range in an element’s accessibility text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Range"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarker/Range",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Range"
        }
      ],
      "role": "symbol",
      "title": "BEAccessibilityTextMarker.Range",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitytextmarker/range"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport": {
      "abstract": [
        {
          "text": "A set of methods that provide information about text offsets to support assistive features.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BEAccessibilityTextMarkerSupport"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityTextMarkerSupport"
        }
      ],
      "role": "symbol",
      "title": "BEAccessibilityTextMarkerSupport",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitytextmarkersupport"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityBounds(for:)": {
      "abstract": [
        {
          "text": "Calculates the bounding rectangle for a text range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityBounds"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)BEAccessibilityTextMarker",
          "text": "BEAccessibilityTextMarker"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)BEAccessibilityTextMarkerRange",
          "text": "Range"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityBounds(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityBoundsForTextMarkerRange:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityBounds(for:)",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitytextmarkersupport/accessibilitybounds(for:)"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityRange(for:)": {
      "abstract": [
        {
          "text": "Returns the range for the text in a given accessibility marker range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityRange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)BEAccessibilityTextMarker",
          "text": "BEAccessibilityTextMarker"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)BEAccessibilityTextMarkerRange",
          "text": "Range"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityRange(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityRangeForTextMarkerRange:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityRange(for:)",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitytextmarkersupport/accessibilityrange(for:)"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityTextMarkerRange()": {
      "abstract": [
        {
          "text": "The text marker range of the current element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityTextMarkerRange"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)BEAccessibilityTextMarker",
          "text": "BEAccessibilityTextMarker"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)BEAccessibilityTextMarkerRange",
          "text": "Range"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityTextMarkerRange()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityTextMarkerRange"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityTextMarkerRange()",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitytextmarkersupport/accessibilitytextmarkerrange()"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityTextMarkerRange(for:)": {
      "abstract": [
        {
          "text": "Returns the text marker range for the text in a given range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityTextMarkerRange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)BEAccessibilityTextMarker",
          "text": "BEAccessibilityTextMarker"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)BEAccessibilityTextMarkerRange",
          "text": "Range"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityTextMarkerRange(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityTextMarkerRangeForRange:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityTextMarkerRange(for:)",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitytextmarkersupport/accessibilitytextmarkerrange(for:)"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityTextMarkerRangeForCurrentSelection()": {
      "abstract": [
        {
          "text": "The text marker range of the current selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityTextMarkerRangeForCurrentSelection"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)BEAccessibilityTextMarker",
          "text": "BEAccessibilityTextMarker"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)BEAccessibilityTextMarkerRange",
          "text": "Range"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityTextMarkerRangeForCurrentSelection()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityTextMarkerRangeForCurrentSelection"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityTextMarkerRangeForCurrentSelection()",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitytextmarkersupport/accessibilitytextmarkerrangeforcurrentselection()"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Text-ranges",
      "generated": true,
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityBounds(for:)",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityTextMarkerRange()",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityTextMarkerRange(for:)",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityRange(for:)",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarker/Range"
      ],
      "title": "Text ranges"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.2",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "accessibilityTextMarkerRangeForCurrentSelection"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityTextMarkerRangeForCurrentSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Text-ranges",
              "generated": true,
              "identifiers": [
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityBounds(for:)",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityTextMarkerRange()",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityTextMarkerRange(for:)",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarkerSupport/accessibilityRange(for:)",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarker/Range"
              ],
              "title": "Text ranges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityTextMarker/Range",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)BEAccessibilityTextMarkerRange",
                    "text": "BEAccessibilityTextMarkerRange"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "accessibilityTextMarkerRangeForCurrentSelection"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarker~1Range/title",
          "value": "BEAccessibilityTextMarkerRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarker~1Range/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityTextMarkerRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarker~1Range/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityTextMarkerRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarkerSupport~1accessibilityTextMarkerRange()/title",
          "value": "accessibilityTextMarkerRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarkerSupport~1accessibilityTextMarkerRange()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityTextMarkerRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarkerSupport~1accessibilityRange(for:)/title",
          "value": "accessibilityRangeForTextMarkerRange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarkerSupport~1accessibilityRange(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityRangeForTextMarkerRange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarkerSupport~1accessibilityTextMarkerRange(for:)/title",
          "value": "accessibilityTextMarkerRangeForRange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarkerSupport~1accessibilityTextMarkerRange(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityTextMarkerRangeForRange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarkerSupport~1accessibilityBounds(for:)/title",
          "value": "accessibilityBoundsForTextMarkerRange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarkerSupport~1accessibilityBounds(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityBoundsForTextMarkerRange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarker/title",
          "value": "BEAccessibilityTextMarker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityTextMarker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityTextMarker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarkerSupport~1accessibilityTextMarkerRangeForCurrentSelection()/title",
          "value": "accessibilityTextMarkerRangeForCurrentSelection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarkerSupport~1accessibilityTextMarkerRangeForCurrentSelection()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityTextMarkerRangeForCurrentSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarkerSupport/title",
          "value": "BEAccessibilityTextMarkerSupport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarkerSupport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityTextMarkerSupport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityTextMarkerSupport/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityTextMarkerSupport"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/browserenginekit/beaccessibilitytextmarkersupport/accessibilitytextmarkerrangeforcurrentselection()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/browserenginekit/beaccessibilitytextmarkersupport/accessibilitytextmarkerrangeforcurrentselection()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
