{
  "abstract": [
    {
      "text": "A feature extractor that uses the standard, built-in word embeddings.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.CreateML/documentation/CreateML",
        "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier",
        "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/FeatureExtractorType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/FeatureExtractorType/staticEmbedding"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:8CreateML16MLTextClassifierV20FeatureExtractorTypeO15staticEmbeddingyA2EmF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "staticEmbedding"
      }
    ],
    "modules": [
      {
        "name": "Create ML"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MLTextClassifier.FeatureExtractorType.staticEmbedding"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "staticEmbedding"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The standard word embeddings are the same as those that",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/NaturalLanguage/NLEmbedding",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "provides with its",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/NaturalLanguage/NLEmbedding/wordEmbedding(for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.CreateML/documentation/CreateML": {
      "abstract": [
        {
          "text": "Create machine learning models for use in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML",
      "kind": "symbol",
      "role": "collection",
      "title": "Create ML",
      "type": "topic",
      "url": "/documentation/createml"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier": {
      "abstract": [
        {
          "text": "A model you train to classify natural language text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLTextClassifier"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLTextClassifier"
        }
      ],
      "role": "symbol",
      "title": "MLTextClassifier",
      "type": "topic",
      "url": "/documentation/createml/mltextclassifier"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/FeatureExtractorType": {
      "abstract": [
        {
          "text": "The text feature extractor type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FeatureExtractorType"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/FeatureExtractorType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FeatureExtractorType"
        }
      ],
      "role": "symbol",
      "title": "MLTextClassifier.FeatureExtractorType",
      "type": "topic",
      "url": "/documentation/createml/mltextclassifier/featureextractortype"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/FeatureExtractorType/bertEmbedding": {
      "abstract": [
        {
          "text": "A feature extractor that provides BERT contextual word embeddings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bertEmbedding"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/FeatureExtractorType/bertEmbedding",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLTextClassifier.FeatureExtractorType.bertEmbedding",
      "type": "topic",
      "url": "/documentation/createml/mltextclassifier/featureextractortype/bertembedding"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/FeatureExtractorType/customEmbedding(_:)": {
      "abstract": [
        {
          "text": "A feature extractor that uses a custom embedding contained in a CoreML model file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customEmbedding"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/FeatureExtractorType/customEmbedding(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLTextClassifier.FeatureExtractorType.customEmbedding(_:)",
      "type": "topic",
      "url": "/documentation/createml/mltextclassifier/featureextractortype/customembedding(_:)"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/FeatureExtractorType/dynamicEmbedding": {
      "abstract": [
        {
          "text": "A feature extractor that provides embeddings for words, based on their in-context use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dynamicEmbedding"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/FeatureExtractorType/dynamicEmbedding",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLTextClassifier.FeatureExtractorType.dynamicEmbedding",
      "type": "topic",
      "url": "/documentation/createml/mltextclassifier/featureextractortype/dynamicembedding"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/FeatureExtractorType/elmoEmbedding": {
      "abstract": [
        {
          "text": "A feature extractor that provides ELMo contextual word embeddings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "elmoEmbedding"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/FeatureExtractorType/elmoEmbedding",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLTextClassifier.FeatureExtractorType.elmoEmbedding",
      "type": "topic",
      "url": "/documentation/createml/mltextclassifier/featureextractortype/elmoembedding"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/FeatureExtractorType/staticEmbedding": {
      "abstract": [
        {
          "text": "A feature extractor that uses the standard, built-in word embeddings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "staticEmbedding"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/FeatureExtractorType/staticEmbedding",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLTextClassifier.FeatureExtractorType.staticEmbedding",
      "type": "topic",
      "url": "/documentation/createml/mltextclassifier/featureextractortype/staticembedding"
    },
    "doc://com.apple.documentation/documentation/NaturalLanguage/NLEmbedding": {
      "abstract": [
        {
          "text": "A map of strings to vectors, which locates neighboring, similar strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLEmbedding"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/NaturalLanguage/NLEmbedding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NLEmbedding",
      "type": "topic",
      "url": "/documentation/NaturalLanguage/NLEmbedding"
    },
    "doc://com.apple.documentation/documentation/NaturalLanguage/NLEmbedding/wordEmbedding(for:)": {
      "abstract": [
        {
          "text": "Retrieves a word embedding for a given language.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wordEmbedding"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "language"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLLanguage",
          "text": "NLLanguage"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NLEmbedding",
          "text": "NLEmbedding"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/NaturalLanguage/NLEmbedding/wordEmbedding(for:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "wordEmbedding(for:)",
      "type": "topic",
      "url": "/documentation/NaturalLanguage/NLEmbedding/wordEmbedding(for:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Selecting-a-feature-extractor-type",
      "generated": true,
      "identifiers": [
        "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/FeatureExtractorType/customEmbedding(_:)",
        "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/FeatureExtractorType/bertEmbedding",
        "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/FeatureExtractorType/elmoEmbedding",
        "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/FeatureExtractorType/dynamicEmbedding"
      ],
      "title": "Selecting a feature extractor type"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1NaturalLanguage~1NLEmbedding~1wordEmbedding(for:)/title",
          "value": "wordEmbeddingForLanguage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1NaturalLanguage~1NLEmbedding~1wordEmbedding(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NLEmbedding",
              "text": "NLEmbedding"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "identifier",
              "text": "wordEmbeddingForLanguage:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NLLanguage",
              "text": "NLLanguage"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "language"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1NaturalLanguage~1NLEmbedding/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NLEmbedding"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/createml/mltextclassifier/featureextractortype/staticembedding"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
