{
  "abstract": [
    {
      "text": "Creates a list parameter object with the initial value.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaextension/documentation/MediaExtension",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessingParameter/List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessingListParameter/initWithName:key:description:list:initialValue:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MERAWProcessingListParameter(im)initWithName:key:description:list:initialValue:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "initWithName:key:description:list:initialValue:"
      }
    ],
    "modules": [
      {
        "name": "MediaExtension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithName:key:description:list:initialValue:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "initWithName:key:description:list:initialValue:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "initWithName:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "name"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "key:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "key"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "description:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "description"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "list:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<MERAWProcessingListElementParameter *>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "listElements"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "initialValue:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "initialValue"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A localized human-readable name for the parameter, suitable for displaying in application UI.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "name"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A unique key string identifying this parameter.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "key"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A localized description of the parameter, suitable for displaying in a tool tip or similar explanatory UI.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "description"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ordered array of ",
                  "type": "text"
                },
                {
                  "code": "MERAWProcessingListElementParameter",
                  "type": "codeVoice"
                },
                {
                  "text": " objects which make up this list.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "listElements"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The initial value of this parameter as defined in the sequence metadata.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "initialValue"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessingParameter/List",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension": {
      "abstract": [
        {
          "text": "This framework provides a means for developers to create format readers, video decoders, and RAW processors for media that the system doesn’t natively support.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "MediaExtension",
      "type": "topic",
      "url": "/documentation/mediaextension"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessingListParameter/initWithName:key:description:list:initialValue:": {
      "abstract": [
        {
          "text": "Creates a list parameter object with the initial value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithName:key:description:list:initialValue:"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessingListParameter/initWithName:key:description:list:initialValue:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithName:key:description:list:initialValue:"
        }
      ],
      "role": "symbol",
      "title": "initWithName:key:description:list:initialValue:",
      "type": "topic",
      "url": "/documentation/mediaextension/merawprocessinglistparameter/initwithname:key:description:list:initialvalue:"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessingListParameter/initWithName:key:description:list:initialValue:cameraValue:": {
      "abstract": [
        {
          "text": "Creates a list parameter object with the initial and camera values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithName:key:description:list:initialValue:cameraValue:"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessingListParameter/initWithName:key:description:list:initialValue:cameraValue:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithName:key:description:list:initialValue:cameraValue:"
        }
      ],
      "role": "symbol",
      "title": "initWithName:key:description:list:initialValue:cameraValue:",
      "type": "topic",
      "url": "/documentation/mediaextension/merawprocessinglistparameter/initwithname:key:description:list:initialvalue:cameravalue:"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessingListParameter/initWithName:key:description:list:initialValue:neutralValue:": {
      "abstract": [
        {
          "text": "Creates a list parameter object with the initial and neutral values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithName:key:description:list:initialValue:neutralValue:"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessingListParameter/initWithName:key:description:list:initialValue:neutralValue:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithName:key:description:list:initialValue:neutralValue:"
        }
      ],
      "role": "symbol",
      "title": "initWithName:key:description:list:initialValue:neutralValue:",
      "type": "topic",
      "url": "/documentation/mediaextension/merawprocessinglistparameter/initwithname:key:description:list:initialvalue:neutralvalue:"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessingListParameter/initWithName:key:description:list:initialValue:neutralValue:cameraValue:": {
      "abstract": [
        {
          "text": "Creates a list parameter object with the initial, neutral, and camera values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithName:key:description:list:initialValue:neutralValue:cameraValue:"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessingListParameter/initWithName:key:description:list:initialValue:neutralValue:cameraValue:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithName:key:description:list:initialValue:neutralValue:cameraValue:"
        }
      ],
      "role": "symbol",
      "title": "initWithName:key:description:list:initialValue:neutralValue:cameraValue:",
      "type": "topic",
      "url": "/documentation/mediaextension/merawprocessinglistparameter/initwithname:key:description:list:initialvalue:neutralvalue:cameravalue:"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessingParameter/List": {
      "abstract": [
        {
          "text": "An object that describes a list parameter of a RAW processor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "List"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessingParameter/List",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "List"
        }
      ],
      "role": "symbol",
      "title": "MERAWProcessingParameter.List",
      "type": "topic",
      "url": "/documentation/mediaextension/merawprocessingparameter/list"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-list-parameter-object",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessingListParameter/initWithName:key:description:list:initialValue:cameraValue:",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessingListParameter/initWithName:key:description:list:initialValue:neutralValue:",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessingListParameter/initWithName:key:description:list:initialValue:neutralValue:cameraValue:"
      ],
      "title": "Creating a list parameter object"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MERAWProcessingParameter~1List/title",
          "value": "MERAWProcessingListParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MERAWProcessingParameter~1List/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MERAWProcessingListParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MERAWProcessingParameter~1List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MERAWProcessingListParameter"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaextension/merawprocessinglistparameter/initwithname:key:description:list:initialvalue:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
