{
  "abstract": [
    {
      "text": "No menstrual flow.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueMenstrualFlow"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueMenstrualFlow/none"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HKCategoryValueMenstrualFlow@HKCategoryValueMenstrualFlowNone",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "none"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKCategoryValueMenstrualFlowNone"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "12.0",
        "name": "iOS",
        "renamed": "HKCategoryValueVaginalBleeding",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "12.0",
        "name": "iPadOS",
        "renamed": "HKCategoryValueVaginalBleeding",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "renamed": "HKCategoryValueVaginalBleeding",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "13.0",
        "name": "macOS",
        "renamed": "HKCategoryValueVaginalBleeding",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "2.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "renamed": "HKCategoryValueVaginalBleeding",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "5.0",
        "name": "watchOS",
        "renamed": "HKCategoryValueVaginalBleeding",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HKCategoryValueMenstrualFlow.none"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "none"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueMenstrualFlow": {
      "abstract": [
        {
          "text": "Categories that indicate the amount of menstrual flow for a given sample.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValueMenstrualFlow"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueMenstrualFlow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueMenstrualFlow"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueMenstrualFlow",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluemenstrualflow"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueMenstrualFlow/heavy": {
      "abstract": [
        {
          "text": "Heavy menstrual flow.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "heavy"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueMenstrualFlow/heavy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueMenstrualFlowHeavy"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueMenstrualFlow.heavy",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluemenstrualflow/heavy"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueMenstrualFlow/light": {
      "abstract": [
        {
          "text": "Light menstrual flow.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "light"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueMenstrualFlow/light",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueMenstrualFlowLight"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueMenstrualFlow.light",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluemenstrualflow/light"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueMenstrualFlow/medium": {
      "abstract": [
        {
          "text": "Medium menstrual flow.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medium"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueMenstrualFlow/medium",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueMenstrualFlowMedium"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueMenstrualFlow.medium",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluemenstrualflow/medium"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueMenstrualFlow/none": {
      "abstract": [
        {
          "text": "No menstrual flow.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueMenstrualFlow/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueMenstrualFlowNone"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueMenstrualFlow.none",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluemenstrualflow/none"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueMenstrualFlow/unspecified": {
      "abstract": [
        {
          "text": "An unspecified amount of menstrual flow.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueMenstrualFlow/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueMenstrualFlowUnspecified"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueMenstrualFlow.unspecified",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluemenstrualflow/unspecified"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueMenstrualFlow/unspecified",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueMenstrualFlow/light",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueMenstrualFlow/medium",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueMenstrualFlow/heavy"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "2.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKCategoryValueMenstrualFlowNone"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueMenstrualFlowNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueMenstrualFlow"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueMenstrualFlow/unspecified",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueMenstrualFlow/light",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueMenstrualFlow/medium",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueMenstrualFlow/heavy"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HKCategoryValueMenstrualFlowNone"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueMenstrualFlow~1unspecified/title",
          "value": "HKCategoryValueMenstrualFlowUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueMenstrualFlow~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueMenstrualFlowUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueMenstrualFlow~1medium/title",
          "value": "HKCategoryValueMenstrualFlowMedium"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueMenstrualFlow~1medium/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueMenstrualFlowMedium"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueMenstrualFlow~1light/title",
          "value": "HKCategoryValueMenstrualFlowLight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueMenstrualFlow~1light/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueMenstrualFlowLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueMenstrualFlow~1heavy/title",
          "value": "HKCategoryValueMenstrualFlowHeavy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueMenstrualFlow~1heavy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueMenstrualFlowHeavy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueMenstrualFlow/title",
          "value": "HKCategoryValueMenstrualFlow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueMenstrualFlow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueMenstrualFlow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueMenstrualFlow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueMenstrualFlow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueMenstrualFlow~1none/title",
          "value": "HKCategoryValueMenstrualFlowNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueMenstrualFlow~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueMenstrualFlowNone"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkcategoryvaluemenstrualflow/none"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkcategoryvaluemenstrualflow/none"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
