{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"anchor":"Discussion","type":"heading","text":"Discussion"},{"inlineContent":[{"text":"Depending on the source of data for a mesh—that is, which file format it was loaded from in a ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAsset","type":"reference"},{"text":" object, or whether it was programmatically created—a vertex attribute’s name can be either one of the constants listed in ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.modelio/documentation/ModelIO/vertex-attributes","type":"reference"},{"text":" or an identifier specific to the file format.","type":"text"}],"type":"paragraph"}]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"symbolKind":"property","externalID":"c:objc(cs)MDLVertexAttribute(py)name","platforms":[{"deprecated":false,"name":"iOS","beta":false,"introducedAt":"9.0","unavailable":false},{"beta":false,"unavailable":false,"name":"iPadOS","introducedAt":"9.0","deprecated":false},{"beta":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"13.1","deprecated":false},{"beta":false,"unavailable":false,"name":"macOS","introducedAt":"10.11","deprecated":false},{"beta":false,"unavailable":false,"name":"tvOS","introducedAt":"9.0","deprecated":false},{"beta":false,"unavailable":false,"name":"visionOS","introducedAt":"1.0","deprecated":false}],"modules":[{"name":"Model I/O"}],"role":"symbol","title":"name","navigatorTitle":[{"text":"name","kind":"identifier"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.modelio/documentation/ModelIO","doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute"]]},"kind":"symbol","seeAlsoSections":[{"generated":true,"title":"Inspecting a Vertex Attribute","anchor":"Inspecting-a-Vertex-Attribute","identifiers":["doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/format","doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/offset","doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/bufferIndex","doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/initializationValue"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/modelio/mdlvertexattribute/name"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/modelio/mdlvertexattribute/name"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"An identifier for the semantic use of the vertex attribute.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/name"},"references":{"doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/name":{"title":"name","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/name","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"name"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[{"text":"An identifier for the semantic use of the vertex attribute.","type":"text"}],"role":"symbol","url":"/documentation/modelio/mdlvertexattribute/name","type":"topic"},"doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/offset":{"kind":"symbol","abstract":[{"text":"The offset, in bytes, of vertex data for the attribute in a vertex buffer, relative to the start of data for each vertex.","type":"text"}],"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/offset","navigatorTitle":[{"text":"offset","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offset","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"url":"/documentation/modelio/mdlvertexattribute/offset","type":"topic","title":"offset"},"doc://com.externally.resolved.symbol/s:SS":{"abstract":[{"type":"text","text":"A Unicode string value that is a collection of characters."}],"role":"symbol","type":"topic","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"String"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SS","title":"String","url":"/documentation/Swift/String"},"doc://com.apple.modelio/documentation/ModelIO/vertex-attributes":{"title":"Vertex Attributes","identifier":"doc://com.apple.modelio/documentation/ModelIO/vertex-attributes","kind":"article","abstract":[{"type":"text","text":"Names that identify semantic uses for vertex attribute data, used by the "},{"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/name","isActive":true,"type":"reference"},{"type":"text","text":" property."}],"role":"collectionGroup","url":"/documentation/modelio/vertex-attributes","type":"topic"},"doc://com.apple.modelio/documentation/ModelIO":{"identifier":"doc://com.apple.modelio/documentation/ModelIO","title":"Model I/O","role":"collection","kind":"symbol","abstract":[{"text":"Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.","type":"text"}],"type":"topic","url":"/documentation/modelio"},"doc://com.apple.modelio/documentation/ModelIO/MDLAsset":{"url":"/documentation/modelio/mdlasset","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAsset","kind":"symbol","abstract":[{"type":"text","text":"An indexed container for 3D objects and associated information, such as transform hierarchies, meshes, cameras, and lights."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MDLAsset","kind":"identifier"}],"navigatorTitle":[{"text":"MDLAsset","kind":"identifier"}],"title":"MDLAsset","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies","kind":"technologies","role":"overview","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.apple.modelio/documentation/ModelIO/MDLMesh/vertexBuffers":{"kind":"symbol","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMesh/vertexBuffers","navigatorTitle":[{"text":"vertexBuffers","kind":"identifier"}],"url":"/documentation/modelio/mdlmesh/vertexbuffers","title":"vertexBuffers","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vertexBuffers","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"MDLMeshBuffer","preciseIdentifier":"c:objc(pl)MDLMeshBuffer","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"abstract":[{"type":"text","text":"The array of buffers that provide vertex data for the mesh."}],"type":"topic","role":"symbol"},"doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/bufferIndex":{"type":"topic","abstract":[{"type":"text","text":"The index of the vertex buffer containing data for this attribute in a mesh’s "},{"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMesh/vertexBuffers","isActive":true,"type":"reference"},{"type":"text","text":" array."}],"title":"bufferIndex","navigatorTitle":[{"kind":"identifier","text":"bufferIndex"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bufferIndex"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"url":"/documentation/modelio/mdlvertexattribute/bufferindex","kind":"symbol","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/bufferIndex"},"doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/initializationValue":{"type":"topic","abstract":[{"type":"text","text":"The default value for vertex data for this attribute."}],"title":"initializationValue","navigatorTitle":[{"kind":"identifier","text":"initializationValue"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializationValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"vector_float4","preciseIdentifier":"c:@T@vector_float4"}],"url":"/documentation/modelio/mdlvertexattribute/initializationvalue","kind":"symbol","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/initializationValue"},"doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/format":{"abstract":[{"type":"text","text":"The format of per-vertex data for the attribute."}],"navigatorTitle":[{"kind":"identifier","text":"format"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"format"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MDLVertexFormat","preciseIdentifier":"c:@E@MDLVertexFormat"}],"kind":"symbol","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/format","title":"format","url":"/documentation/modelio/mdlvertexattribute/format"},"doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MDLVertexAttribute","kind":"identifier"}],"kind":"symbol","title":"MDLVertexAttribute","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute","url":"/documentation/modelio/mdlvertexattribute","abstract":[{"type":"text","text":"A description of the format of per-vertex data for a single vertex attribute in a mesh object."}],"role":"symbol","navigatorTitle":[{"text":"MDLVertexAttribute","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"introducedAt":"9.0","name":"iOS","unavailable":false,"deprecated":false,"beta":false},{"name":"iPadOS","introducedAt":"9.0","unavailable":false,"beta":false,"deprecated":false},{"name":"Mac Catalyst","introducedAt":"13.1","unavailable":false,"beta":false,"deprecated":false},{"name":"macOS","introducedAt":"10.11","unavailable":false,"beta":false,"deprecated":false},{"name":"tvOS","introducedAt":"9.0","unavailable":false,"beta":false,"deprecated":false},{"name":"visionOS","introducedAt":"1.0","unavailable":false,"beta":false,"deprecated":false}],"op":"replace","path":"/metadata/platforms"},{"path":"/metadata/roleHeading","value":"Instance Property","op":"replace"},{"path":"/metadata/title","value":"name","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"name","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.modelio/documentation/ModelIO","doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"title":"Inspecting a Vertex Attribute","generated":true,"anchor":"Inspecting-a-Vertex-Attribute","identifiers":["doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/format","doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/offset","doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/bufferIndex","doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/initializationValue"]}],"op":"replace"},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"name","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttribute~1name/title","value":"name","op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttribute~1name/fragments","value":[{"text":"name","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttribute~1offset/title","value":"offset","op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttribute~1offset/fragments","value":[{"kind":"identifier","text":"offset"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset/title","value":"MDLAsset","op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset/fragments","value":[{"kind":"identifier","text":"MDLAsset"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset/navigatorTitle","value":[{"text":"MDLAsset","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1vertexBuffers/title","value":"vertexBuffers","op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1vertexBuffers/fragments","value":[{"text":"vertexBuffers","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttribute~1bufferIndex/title","value":"bufferIndex","op":"replace"},{"value":[{"kind":"identifier","text":"bufferIndex"}],"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttribute~1bufferIndex/fragments"},{"value":"initializationValue","op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttribute~1initializationValue/title"},{"value":[{"kind":"identifier","text":"initializationValue"}],"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttribute~1initializationValue/fragments"},{"value":"format","op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttribute~1format/title"},{"value":[{"kind":"identifier","text":"format"}],"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttribute~1format/fragments"},{"value":"MDLVertexAttribute","op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttribute/title"},{"value":[{"text":"MDLVertexAttribute","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttribute/fragments"},{"value":[{"text":"MDLVertexAttribute","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttribute/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}