{
  "abstract": [
    {
      "text": "A collection of statistics, representing the results calculated over separate time intervals.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQueryDescriptor",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQueryDescriptor/Result"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQueryDescriptor/Result/statisticsCollection"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:9HealthKit37HKStatisticsCollectionQueryDescriptorV6ResultV010statisticsD0So0cD0Cvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "statisticsCollection"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)HKStatisticsCollection",
        "text": "HKStatisticsCollection"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.5",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "statisticsCollection"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "statisticsCollection"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollection",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)HKStatisticsCollection",
              "text": "HKStatisticsCollection"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollection": {
      "abstract": [
        {
          "text": "An object that manages a collection of statistics, representing the results calculated over separate time intervals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKStatisticsCollection"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStatisticsCollection"
        }
      ],
      "role": "symbol",
      "title": "HKStatisticsCollection",
      "type": "topic",
      "url": "/documentation/healthkit/hkstatisticscollection"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQueryDescriptor": {
      "abstract": [
        {
          "text": "A query descriptor that gathers a collection of statistics calculated over a series of fixed-length time intervals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKStatisticsCollectionQueryDescriptor"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQueryDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStatisticsCollectionQueryDescriptor"
        }
      ],
      "role": "symbol",
      "title": "HKStatisticsCollectionQueryDescriptor",
      "type": "topic",
      "url": "/documentation/healthkit/hkstatisticscollectionquerydescriptor"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQueryDescriptor/Result": {
      "abstract": [
        {
          "text": "A collection of results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Result"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQueryDescriptor/Result",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Result"
        }
      ],
      "role": "symbol",
      "title": "HKStatisticsCollectionQueryDescriptor.Result",
      "type": "topic",
      "url": "/documentation/healthkit/hkstatisticscollectionquerydescriptor/result"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQueryDescriptor/Result/statisticsCollection": {
      "abstract": [
        {
          "text": "A collection of statistics, representing the results calculated over separate time intervals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statisticsCollection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKStatisticsCollection",
          "text": "HKStatisticsCollection"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQueryDescriptor/Result/statisticsCollection",
      "kind": "symbol",
      "role": "symbol",
      "title": "statisticsCollection",
      "type": "topic",
      "url": "/documentation/healthkit/hkstatisticscollectionquerydescriptor/result/statisticscollection"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQueryDescriptor/Result/updatedStatistics": {
      "abstract": [
        {
          "text": "A collection of statistics that have changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updatedStatistics"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKStatistics",
          "text": "HKStatistics"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQueryDescriptor/Result/updatedStatistics",
      "kind": "symbol",
      "role": "symbol",
      "title": "updatedStatistics",
      "type": "topic",
      "url": "/documentation/healthkit/hkstatisticscollectionquerydescriptor/result/updatedstatistics"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Statistical-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQueryDescriptor/Result/updatedStatistics"
      ],
      "title": "Accessing Statistical Data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsCollection/title",
          "value": "HKStatisticsCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStatisticsCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsCollection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStatisticsCollection"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkstatisticscollectionquerydescriptor/result/statisticscollection"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
