{"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSEvent/cgEvent","interfaceLanguage":"swift"},"metadata":{"title":"cgEvent","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cgEvent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGEvent","preciseIdentifier":"c:@T@CGEventRef","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"CGEvent","kind":"identifier"}],"externalID":"c:objc(cs)NSEvent(py)CGEvent","role":"symbol","symbolKind":"property","modules":[{"name":"AppKit"}],"platforms":[{"beta":false,"name":"macOS","deprecated":false,"unavailable":false,"introducedAt":"10.5"}]},"abstract":[{"type":"text","text":"The Core Graphics event object corresponding to this event."}],"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSEvent/init(cgEvent:)"],"anchor":"Related-Documentation"},{"title":"Getting general event information","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSEvent/locationInWindow","doc://com.apple.appkit/documentation/AppKit/NSEvent/timestamp","doc://com.apple.appkit/documentation/AppKit/NSEvent/window","doc://com.apple.appkit/documentation/AppKit/NSEvent/windowNumber","doc://com.apple.appkit/documentation/AppKit/NSEvent/eventRef","doc://com.apple.appkit/documentation/AppKit/NSEvent/foreverDuration"],"generated":true,"anchor":"Getting-general-event-information"}],"variants":[{"paths":["/documentation/appkit/nsevent/cgevent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsevent/cgevent"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSEvent"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cgEvent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGEvent","identifier":"doc://com.externally.resolved.symbol/c:@T@CGEventRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGEventRef"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["macOS"]}]},{"kind":"content","content":[{"anchor":"Discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/coregraphics/cgevent","isActive":true},{"type":"text","text":" opaque type returned is autoreleased. If no "},{"type":"codeVoice","code":"CGEventRef"},{"text":" object corresponding to the ","type":"text"},{"type":"codeVoice","code":"NSEvent"},{"text":" object can be created, this method returns ","type":"text"},{"type":"codeVoice","code":"NULL"},{"text":".","type":"text"}]}]}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSEvent":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSEvent"}],"role":"symbol","type":"topic","title":"NSEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSEvent"}],"abstract":[{"type":"text","text":"An object that contains information about an input action, such as a mouse click or a key press."}],"url":"/documentation/appkit/nsevent"},"doc://com.apple.appkit/documentation/AppKit/NSEvent/eventRef":{"abstract":[{"type":"text","text":"An opaque Carbon type associated with this event."}],"type":"topic","title":"eventRef","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventRef"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeRawPointer","preciseIdentifier":"s:SV"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/eventRef","role":"symbol","url":"/documentation/appkit/nsevent/eventref","navigatorTitle":[{"kind":"identifier","text":"eventRef"}]},"doc://com.apple.appkit/documentation/AppKit/NSEvent/window":{"url":"/documentation/appkit/nsevent/window","role":"symbol","kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/window","navigatorTitle":[{"text":"window","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"window","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSWindow"},{"text":"?","kind":"text"}],"title":"window","abstract":[{"text":"The window object associated with the event.","type":"text"}]},"doc://com.apple.documentation/documentation/coregraphics/cgevent":{"role":"symbol","url":"/documentation/coregraphics/cgevent","identifier":"doc://com.apple.documentation/documentation/coregraphics/cgevent","abstract":[{"type":"text","text":"Defines an opaque type that represents a low-level hardware event."}],"fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"CGEvent"}],"type":"topic","title":"CGEvent","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSEvent/timestamp":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/timestamp","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"kind":"symbol","role":"symbol","url":"/documentation/appkit/nsevent/timestamp","navigatorTitle":[{"text":"timestamp","kind":"identifier"}],"abstract":[{"text":"The time when the event occurred in seconds since system startup.","type":"text"}],"title":"timestamp"},"doc://com.apple.appkit/documentation/AppKit/NSEvent/cgEvent":{"abstract":[{"text":"The Core Graphics event object corresponding to this event.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/cgEvent","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cgEvent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGEvent","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGEventRef"},{"text":"?","kind":"text"}],"title":"cgEvent","url":"/documentation/appkit/nsevent/cgevent","navigatorTitle":[{"text":"CGEvent","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSEvent/init(cgEvent:)":{"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/init(cgEvent:)","url":"/documentation/appkit/nsevent/init(cgevent:)","navigatorTitle":[{"text":"eventWithCGEvent:","kind":"identifier"}],"title":"init(cgEvent:)","abstract":[{"text":"Creates and returns an event object for a Core Graphics event.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"cgEvent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGEvent","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGEventRef"},{"text":")","kind":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSEvent/windowNumber":{"url":"/documentation/appkit/nsevent/windownumber","role":"symbol","kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/windowNumber","navigatorTitle":[{"text":"windowNumber","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"windowNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"windowNumber","abstract":[{"text":"The identifier for the window device associated with the event.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSEvent/foreverDuration":{"url":"/documentation/appkit/nsevent/foreverduration","type":"topic","title":"foreverDuration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSEventDurationForever"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"foreverDuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}],"abstract":[{"type":"text","text":"The longest time duration possible."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/foreverDuration","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSEvent/locationInWindow":{"url":"/documentation/appkit/nsevent/locationinwindow","role":"symbol","kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/locationInWindow","navigatorTitle":[{"kind":"identifier","text":"locationInWindow"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"locationInWindow","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSPoint","preciseIdentifier":"c:@T@NSPoint"}],"title":"locationInWindow","abstract":[{"text":"The event location in the base coordinate system of the associated window.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/c:@T@CGEventRef":{"role":"symbol","url":"/documentation/coregraphics/cgevent","identifier":"doc://com.externally.resolved.symbol/c:@T@CGEventRef","abstract":[{"type":"text","text":"Defines an opaque type that represents a low-level hardware event."}],"fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"CGEvent"}],"type":"topic","title":"CGEvent","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"beta":false,"name":"macOS","unavailable":false,"introducedAt":"10.5","deprecated":false}]},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"CGEvent","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"CGEvent"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSEvent"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"anchor":"Related-Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSEvent/init(cgEvent:)"],"title":"Related Documentation"},{"anchor":"Getting-general-event-information","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSEvent/locationInWindow","doc://com.apple.appkit/documentation/AppKit/NSEvent/timestamp","doc://com.apple.appkit/documentation/AppKit/NSEvent/window","doc://com.apple.appkit/documentation/AppKit/NSEvent/windowNumber","doc://com.apple.appkit/documentation/AppKit/NSEvent/eventRef","doc://com.apple.appkit/documentation/AppKit/NSEvent/foreverDuration"],"title":"Getting general event information"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@CGEventRef","text":"CGEventRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGEventRef"},{"text":" ","kind":"text"},{"text":"CGEvent","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"value":"NSEvent","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/title"},{"value":[{"text":"NSEvent","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/fragments"},{"value":[{"kind":"identifier","text":"NSEvent"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/navigatorTitle"},{"value":"eventRef","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1eventRef/title"},{"value":[{"text":"eventRef","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1eventRef/fragments"},{"value":"window","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1window/title"},{"value":[{"text":"window","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1window/fragments"},{"value":"CGEventRef","op":"replace","path":"/references/doc:~1~1com.apple.documentation~1documentation~1coregraphics~1cgevent/title"},{"value":"timestamp","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1timestamp/title"},{"value":[{"kind":"identifier","text":"timestamp"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1timestamp/fragments"},{"value":"CGEvent","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1cgEvent/title"},{"value":[{"kind":"identifier","text":"CGEvent"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1cgEvent/fragments"},{"value":"eventWithCGEvent:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1init(cgEvent:)/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"eventWithCGEvent:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1init(cgEvent:)/fragments"},{"value":"windowNumber","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1windowNumber/title"},{"value":[{"text":"windowNumber","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1windowNumber/fragments"},{"value":"NSEventDurationForever","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1foreverDuration/title"},{"value":[{"text":"NSEventDurationForever","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1foreverDuration/fragments"},{"value":"locationInWindow","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1locationInWindow/title"},{"value":[{"text":"locationInWindow","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1locationInWindow/fragments"},{"value":"CGEventRef","op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CGEventRef/title"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}