{"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSEvent/data1","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSEvent/subtype","doc://com.apple.appkit/documentation/AppKit/NSEvent/otherEvent(with:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:)"],"title":"Related Documentation","anchor":"Related-Documentation"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSEvent/data2"],"title":"Getting custom event information","anchor":"Getting-custom-event-information","generated":true}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsevent/data1"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsevent/data1"]}],"metadata":{"platforms":[{"name":"macOS","unavailable":false,"deprecated":false,"beta":false}],"title":"data1","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"data1"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"modules":[{"name":"AppKit"}],"externalID":"c:objc(cs)NSEvent(py)data1","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"data1"}],"roleHeading":"Instance Property","symbolKind":"property"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data1","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","identifier":"doc://com.externally.resolved.symbol/s:Si","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"The originator of the event defines the data in this property, and the data is dependent on the event type. If the type of this event isn’t  "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAppKitDefined","type":"reference","isActive":true},{"type":"text","text":", "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSystemDefined","type":"reference","isActive":true},{"type":"text","text":", "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplicationDefined","type":"reference","isActive":true},{"type":"text","text":", or "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSPeriodic","type":"reference","isActive":true},{"type":"text","text":", accessing this property raises "},{"identifier":"doc://com.apple.documentation/documentation/foundation/nsexceptionname/1416220-internalinconsistencyexception","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"paragraph"},{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPeriodic"},{"text":" events don’t use this property.","type":"text"}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSEvent"]]},"abstract":[{"text":"Additional data associated with this event.","type":"text"}],"sections":[],"references":{"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSEvent/data2":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/data2","kind":"symbol","navigatorTitle":[{"text":"data2","kind":"identifier"}],"url":"/documentation/appkit/nsevent/data2","type":"topic","abstract":[{"type":"text","text":"Additional data associated with this event."}],"role":"symbol","title":"data2","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"data2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"doc://com.apple.appkit/documentation/AppKit/NSEvent/data1":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/data1","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"data1"}],"url":"/documentation/appkit/nsevent/data1","type":"topic","abstract":[{"type":"text","text":"Additional data associated with this event."}],"role":"symbol","title":"data1","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"data1"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}]},"doc://com.externally.resolved.symbol/s:Si":{"abstract":[{"type":"text","text":"A signed integer value type."}],"url":"/documentation/Swift/Int","kind":"symbol","role":"symbol","title":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}]},"doc://com.apple.appkit/documentation/AppKit/NSAppKitDefined":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAppKitDefined","deprecated":true,"kind":"symbol","url":"/documentation/appkit/nsappkitdefined","type":"topic","abstract":[{"type":"text","text":"An AppKit-defined event."}],"role":"symbol","title":"NSAppKitDefined","fragments":[{"text":"NSAppKitDefined","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSPeriodic":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSPeriodic","deprecated":true,"kind":"symbol","url":"/documentation/appkit/nsperiodic","type":"topic","abstract":[{"type":"text","text":"A periodic event."}],"role":"symbol","title":"NSPeriodic","fragments":[{"text":"NSPeriodic","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSApplicationDefined":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplicationDefined","deprecated":true,"kind":"symbol","url":"/documentation/appkit/nsapplicationdefined","type":"topic","abstract":[{"type":"text","text":"An app-defined event."}],"role":"symbol","title":"NSApplicationDefined","fragments":[{"text":"NSApplicationDefined","kind":"identifier"}]},"doc://com.apple.documentation/documentation/foundation/nsexceptionname/1416220-internalinconsistencyexception":{"title":"internalInconsistencyException","fragments":[{"kind":"text","text":"static let "},{"kind":"identifier","text":"internalInconsistencyException"},{"kind":"text","text":": NSExceptionName"}],"kind":"symbol","abstract":[{"type":"text","text":"Name of an exception that occurs when an internal assertion fails and implies an unexpected condition within the called code."}],"type":"topic","role":"symbol","url":"/documentation/foundation/nsexceptionname/1416220-internalinconsistencyexception","identifier":"doc://com.apple.documentation/documentation/foundation/nsexceptionname/1416220-internalinconsistencyexception"},"doc://com.apple.appkit/documentation/AppKit/NSEvent/subtype":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/subtype","kind":"symbol","navigatorTitle":[{"text":"subtype","kind":"identifier"}],"url":"/documentation/appkit/nsevent/subtype","type":"topic","abstract":[{"type":"text","text":"The event’s subtype."}],"role":"symbol","title":"subtype","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtype"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSEvent","kind":"typeIdentifier","text":"NSEvent"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSEventSubtype","text":"EventSubtype","kind":"typeIdentifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSSystemDefined":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSystemDefined","deprecated":true,"kind":"symbol","url":"/documentation/appkit/nssystemdefined","type":"topic","abstract":[{"type":"text","text":"A system-defined event."}],"role":"symbol","title":"NSSystemDefined","fragments":[{"text":"NSSystemDefined","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSEvent/otherEvent(with:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/otherEvent(with:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"otherEventWithType:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:"}],"url":"/documentation/appkit/nsevent/otherevent(with:location:modifierflags:timestamp:windownumber:context:subtype:data1:data2:)","type":"topic","abstract":[{"type":"text","text":"Creates and returns a new event object that describes a custom event."}],"role":"symbol","title":"otherEvent(with:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"otherEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSEventType","text":"EventType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint","text":"NSPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"modifierFlags"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSEventModifierFlags","text":"ModifierFlags"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"windowNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSGraphicsContext","text":"NSGraphicsContext"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"subtype"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int16V","text":"Int16"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent"},{"kind":"text","text":"?"}]},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"NSInteger"}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes an integer."}],"title":"NSInteger"},"doc://com.apple.appkit/documentation/AppKit/NSEvent":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSEvent"}],"role":"symbol","type":"topic","title":"NSEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSEvent"}],"abstract":[{"type":"text","text":"An object that contains information about an input action, such as a mouse click or a key press."}],"url":"/documentation/appkit/nsevent"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"beta":false,"name":"macOS","unavailable":false,"deprecated":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Property"},{"path":"/metadata/title","value":"data1","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"data1"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSEvent"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"anchor":"Related-Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSEvent/subtype","doc://com.apple.appkit/documentation/AppKit/NSEvent/otherEvent(with:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:)"],"title":"Related Documentation"},{"anchor":"Getting-custom-event-information","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSEvent/data2"],"title":"Getting custom event information","generated":true}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"data1"},{"kind":"text","text":";"}]}]}},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1data2/title","value":"data2","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1data2/fragments","value":[{"text":"data2","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1data1/title","value":"data1","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1data1/fragments","value":[{"kind":"identifier","text":"data1"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsexceptionname~11416220-internalinconsistencyexception/title","value":"NSInternalInconsistencyException","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1subtype/title","value":"subtype","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1subtype/fragments","value":[{"kind":"identifier","text":"subtype"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1otherEvent(with:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:)/title","value":"otherEventWithType:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1otherEvent(with:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:)/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"otherEventWithType:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/title","value":"NSEvent","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/fragments","value":[{"text":"NSEvent","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/navigatorTitle","value":[{"text":"NSEvent","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}