{
  "abstract": [
    {
      "text": "Subtypes for various types of events.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@E@NSEventSubtype",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "EventSubtype"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "EventSubtype"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSEvent.EventSubtype"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "EventSubtype"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The event subtype contains one of these constants only when the event’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/type",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property contains ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitDefined",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSystemDefined",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplicationDefined",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or a mouse-related event type.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAWTEventType": {
      "abstract": [
        {
          "text": "An event type used to support Java applications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAWTEventType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAWTEventType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAWTEventType",
      "type": "topic",
      "url": "/documentation/appkit/nsawteventtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitDefined": {
      "abstract": [
        {
          "text": "An AppKit-defined event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAppKitDefined"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitDefined",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAppKitDefined",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitdefined"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplicationActivatedEventType": {
      "abstract": [
        {
          "text": "The application has been activated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSApplicationActivatedEventType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplicationActivatedEventType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSApplicationActivatedEventType",
      "type": "topic",
      "url": "/documentation/appkit/nsapplicationactivatedeventtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplicationDeactivatedEventType": {
      "abstract": [
        {
          "text": "The application has been deactivated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSApplicationDeactivatedEventType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplicationDeactivatedEventType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSApplicationDeactivatedEventType",
      "type": "topic",
      "url": "/documentation/appkit/nsapplicationdeactivatedeventtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplicationDefined": {
      "abstract": [
        {
          "text": "An app-defined event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSApplicationDefined"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplicationDefined",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSApplicationDefined",
      "type": "topic",
      "url": "/documentation/appkit/nsapplicationdefined"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent": {
      "abstract": [
        {
          "text": "An object that contains information about an input action, such as a mouse click or a key press.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEvent"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEvent"
        }
      ],
      "role": "symbol",
      "title": "NSEvent",
      "type": "topic",
      "url": "/documentation/appkit/nsevent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype": {
      "abstract": [
        {
          "text": "Subtypes for various types of events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EventSubtype"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EventSubtype"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventSubtype",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventsubtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/applicationActivated": {
      "abstract": [
        {
          "text": "An app-activation event occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationActivated"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/applicationActivated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventSubtypeApplicationActivated"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventSubtype.applicationActivated",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventsubtype/applicationactivated"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/applicationDeactivated": {
      "abstract": [
        {
          "text": "An app-deactivation event occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationDeactivated"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/applicationDeactivated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventSubtypeApplicationDeactivated"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventSubtype.applicationDeactivated",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventsubtype/applicationdeactivated"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventsubtype/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/mouseEvent": {
      "abstract": [
        {
          "text": "A mouse event occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mouseEvent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSEventSubtype",
          "text": "EventSubtype"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/mouseEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventSubtypeMouseEvent"
        }
      ],
      "role": "symbol",
      "title": "mouseEvent",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventsubtype/mouseevent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/powerOff": {
      "abstract": [
        {
          "text": "An event that indicates a system shutdown or restart operation is in progress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "powerOff"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSEventSubtype",
          "text": "EventSubtype"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/powerOff",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventSubtypePowerOff"
        }
      ],
      "role": "symbol",
      "title": "powerOff",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventsubtype/poweroff"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/screenChanged": {
      "abstract": [
        {
          "text": "An event that indicates a window changed screens.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screenChanged"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/screenChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventSubtypeScreenChanged"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventSubtype.screenChanged",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventsubtype/screenchanged"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/tabletPoint": {
      "abstract": [
        {
          "text": "A tablet-pointer event occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabletPoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSEventSubtype",
          "text": "EventSubtype"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/tabletPoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventSubtypeTabletPoint"
        }
      ],
      "role": "symbol",
      "title": "tabletPoint",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventsubtype/tabletpoint"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/tabletProximity": {
      "abstract": [
        {
          "text": "A tablet-proximity event occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabletProximity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSEventSubtype",
          "text": "EventSubtype"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/tabletProximity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventSubtypeTabletProximity"
        }
      ],
      "role": "symbol",
      "title": "tabletProximity",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventsubtype/tabletproximity"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/touch": {
      "abstract": [
        {
          "text": "A touch event occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touch"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/touch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventSubtypeTouch"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventSubtype.touch",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventsubtype/touch"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/windowExposed": {
      "abstract": [
        {
          "text": "An event that indicates a window’s contents are visible again.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "windowExposed"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/windowExposed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventSubtypeWindowExposed"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventSubtype.windowExposed",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventsubtype/windowexposed"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/windowMoved": {
      "abstract": [
        {
          "text": "An event that indicates a window moved.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "windowMoved"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/windowMoved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventSubtypeWindowMoved"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventSubtype.windowMoved",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventsubtype/windowmoved"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType": {
      "abstract": [
        {
          "text": "Constants for the types of events that responder objects can handle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EventType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EventType"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/appKitDefined": {
      "abstract": [
        {
          "text": "An AppKit-related event occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appKitDefined"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/appKitDefined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeAppKitDefined"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.appKitDefined",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/appkitdefined"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/systemDefined": {
      "abstract": [
        {
          "text": "A system-related event occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemDefined"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/systemDefined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeSystemDefined"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.systemDefined",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/systemdefined"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventTypeMask": {
      "abstract": [
        {
          "text": "Constants that you use to filter out specific event types from the stream of incoming events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EventTypeMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventTypeMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EventTypeMask"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventTypeMask",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtypemask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/subtype": {
      "abstract": [
        {
          "text": "The event’s subtype.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtype"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSEventSubtype",
          "text": "EventSubtype"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/subtype",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subtype"
        }
      ],
      "role": "symbol",
      "title": "subtype",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/subtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/type": {
      "abstract": [
        {
          "text": "The event’s type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSEventType",
          "text": "EventType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/type"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMouseEventSubtype": {
      "abstract": [
        {
          "text": "Indicates a purely mouse event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMouseEventSubtype"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMouseEventSubtype",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMouseEventSubtype",
      "type": "topic",
      "url": "/documentation/appkit/nsmouseeventsubtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPowerOffEventType": {
      "abstract": [
        {
          "text": "Specifies that the user is turning off the computer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPowerOffEventType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPowerOffEventType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPowerOffEventType",
      "type": "topic",
      "url": "/documentation/appkit/nspoweroffeventtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreenChangedEventType": {
      "abstract": [
        {
          "text": "An NSWindow has changed screens.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSScreenChangedEventType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreenChangedEventType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSScreenChangedEventType",
      "type": "topic",
      "url": "/documentation/appkit/nsscreenchangedeventtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSystemDefined": {
      "abstract": [
        {
          "text": "A system-defined event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSSystemDefined"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSystemDefined",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSystemDefined",
      "type": "topic",
      "url": "/documentation/appkit/nssystemdefined"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTabletPointEventSubtype": {
      "abstract": [
        {
          "text": "Indicates a tablet-pointer event; see description of ",
          "type": "text"
        },
        {
          "code": "NSTabletPoint",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTabletPointEventSubtype"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTabletPointEventSubtype",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTabletPointEventSubtype",
      "type": "topic",
      "url": "/documentation/appkit/nstabletpointeventsubtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTabletProximityEventSubtype": {
      "abstract": [
        {
          "text": "Indicates a tablet-proximity event; see description of ",
          "type": "text"
        },
        {
          "code": "NSTabletProximity",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTabletProximityEventSubtype"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTabletProximityEventSubtype",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTabletProximityEventSubtype",
      "type": "topic",
      "url": "/documentation/appkit/nstabletproximityeventsubtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTouchEventSubtype": {
      "abstract": [
        {
          "text": "Indicates a touch event subtype.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTouchEventSubtype"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouchEventSubtype",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTouchEventSubtype",
      "type": "topic",
      "url": "/documentation/appkit/nstoucheventsubtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindowExposedEventType": {
      "abstract": [
        {
          "text": "A non-retained NSWindow has been exposed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSWindowExposedEventType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindowExposedEventType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSWindowExposedEventType",
      "type": "topic",
      "url": "/documentation/appkit/nswindowexposedeventtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindowMovedEventType": {
      "abstract": [
        {
          "text": "An NSWindow has moved.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSWindowMovedEventType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindowMovedEventType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSWindowMovedEventType",
      "type": "topic",
      "url": "/documentation/appkit/nswindowmovedeventtype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-event-type",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/type",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventTypeMask",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/subtype"
      ],
      "title": "Getting the event type"
    }
  ],
  "topicSections": [
    {
      "abstract": [
        {
          "text": "These subtypes apply when the event type is ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/appKitDefined",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "anchor": "Getting-AppKit-Event-Subtypes",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/applicationActivated",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/applicationDeactivated",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/screenChanged",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/windowExposed",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/windowMoved"
      ],
      "title": "Getting AppKit Event Subtypes"
    },
    {
      "abstract": [
        {
          "text": "This subtype applies when the event type is ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/systemDefined",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "anchor": "Getting-System-Event-Subtypes",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/powerOff",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/powerOff"
      ],
      "title": "Getting System Event Subtypes"
    },
    {
      "anchor": "Getting-Other-Subtypes",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/mouseEvent",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/tabletPoint",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/tabletProximity",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/touch"
      ],
      "title": "Getting Other Subtypes"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSEventSubtype"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "abstract": [
                {
                  "text": "These subtypes apply when the event type is ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/appKitDefined",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "anchor": "Getting-AppKit-Event-Subtypes",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/applicationActivated",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/applicationDeactivated",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/screenChanged",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/windowExposed",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/windowMoved"
              ],
              "title": "Getting AppKit Event Subtypes"
            },
            {
              "abstract": [
                {
                  "text": "This subtype applies when the event type is ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/systemDefined",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "anchor": "Getting-System-Event-Subtypes",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/powerOff",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/powerOff"
              ],
              "title": "Getting System Event Subtypes"
            },
            {
              "anchor": "Getting-Other-Subtypes",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/mouseEvent",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/tabletPoint",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/tabletProximity",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/touch"
              ],
              "title": "Getting Other Subtypes"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAWTEventType",
                "doc://com.apple.appkit/documentation/AppKit/NSApplicationActivatedEventType",
                "doc://com.apple.appkit/documentation/AppKit/NSApplicationDeactivatedEventType",
                "doc://com.apple.appkit/documentation/AppKit/NSMouseEventSubtype",
                "doc://com.apple.appkit/documentation/AppKit/NSPowerOffEventType",
                "doc://com.apple.appkit/documentation/AppKit/NSScreenChangedEventType",
                "doc://com.apple.appkit/documentation/AppKit/NSTabletPointEventSubtype",
                "doc://com.apple.appkit/documentation/AppKit/NSTabletProximityEventSubtype",
                "doc://com.apple.appkit/documentation/AppKit/NSTouchEventSubtype",
                "doc://com.apple.appkit/documentation/AppKit/NSWindowExposedEventType",
                "doc://com.apple.appkit/documentation/AppKit/NSWindowMovedEventType"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-event-type",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/type",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventTypeMask",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/subtype"
              ],
              "title": "Getting the event type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSEventSubtype"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:S",
                    "text": "short"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype~1tabletProximity/title",
          "value": "NSEventSubtypeTabletProximity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype~1tabletProximity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventSubtypeTabletProximity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype~1applicationDeactivated/title",
          "value": "NSEventSubtypeApplicationDeactivated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype~1applicationDeactivated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventSubtypeApplicationDeactivated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype~1touch/title",
          "value": "NSEventSubtypeTouch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype~1touch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventSubtypeTouch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype/title",
          "value": "NSEventSubtype"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1appKitDefined/title",
          "value": "NSEventTypeAppKitDefined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1appKitDefined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeAppKitDefined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventTypeMask/title",
          "value": "NSEventMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventTypeMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventTypeMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType/title",
          "value": "NSEventType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1subtype/title",
          "value": "subtype"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1subtype/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype~1powerOff/title",
          "value": "NSEventSubtypePowerOff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype~1powerOff/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventSubtypePowerOff"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype~1tabletPoint/title",
          "value": "NSEventSubtypeTabletPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype~1tabletPoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventSubtypeTabletPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype~1windowMoved/title",
          "value": "NSEventSubtypeWindowMoved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype~1windowMoved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventSubtypeWindowMoved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype~1mouseEvent/title",
          "value": "NSEventSubtypeMouseEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype~1mouseEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventSubtypeMouseEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype~1applicationActivated/title",
          "value": "NSEventSubtypeApplicationActivated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype~1applicationActivated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventSubtypeApplicationActivated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype~1screenChanged/title",
          "value": "NSEventSubtypeScreenChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype~1screenChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventSubtypeScreenChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype~1windowExposed/title",
          "value": "NSEventSubtypeWindowExposed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype~1windowExposed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventSubtypeWindowExposed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1systemDefined/title",
          "value": "NSEventTypeSystemDefined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1systemDefined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeSystemDefined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/title",
          "value": "NSEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEvent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsevent/eventsubtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsevent/eventsubtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
