{"metadata":{"navigatorTitle":[{"text":"eventNumber","kind":"identifier"}],"modules":[{"name":"AppKit"}],"roleHeading":"Instance Property","title":"eventNumber","externalID":"c:objc(cs)NSEvent(py)eventNumber","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eventNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"platforms":[{"name":"macOS","deprecated":false,"unavailable":false,"beta":false}],"role":"symbol","symbolKind":"property"},"seeAlsoSections":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSEvent/enterExitEvent(with:location:modifierFlags:timestamp:windowNumber:context:eventNumber:trackingNumber:userData:)","doc://com.apple.appkit/documentation/AppKit/NSEvent/mouseEvent(with:location:modifierFlags:timestamp:windowNumber:context:eventNumber:clickCount:pressure:)"]},{"anchor":"Getting-tracking-area-information","generated":true,"title":"Getting tracking area information","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSEvent/trackingNumber","doc://com.apple.appkit/documentation/AppKit/NSEvent/trackingArea","doc://com.apple.appkit/documentation/AppKit/NSEvent/userData"]}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSEvent/eventNumber","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eventNumber","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Every system-generated mouse and tracking-rectangle event increments this counter. If you access this property on an event of an unsupported type, AppKit raises ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/foundation/nsexceptionname/1416220-internalinconsistencyexception","isActive":true,"type":"reference"},{"text":".","type":"text"}]}],"kind":"content"}],"variants":[{"paths":["/documentation/appkit/nsevent/eventnumber"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsevent/eventnumber"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The counter value of the latest mouse or tracking-rectangle event object.","type":"text"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSEvent"]]},"kind":"symbol","references":{"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"NSInteger"}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes an integer."}],"title":"NSInteger"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.documentation/documentation/foundation/nsexceptionname/1416220-internalinconsistencyexception":{"title":"internalInconsistencyException","fragments":[{"kind":"text","text":"static let "},{"kind":"identifier","text":"internalInconsistencyException"},{"kind":"text","text":": NSExceptionName"}],"kind":"symbol","abstract":[{"type":"text","text":"Name of an exception that occurs when an internal assertion fails and implies an unexpected condition within the called code."}],"type":"topic","role":"symbol","url":"/documentation/foundation/nsexceptionname/1416220-internalinconsistencyexception","identifier":"doc://com.apple.documentation/documentation/foundation/nsexceptionname/1416220-internalinconsistencyexception"},"doc://com.apple.appkit/documentation/AppKit/NSEvent/trackingArea":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"trackingArea","kind":"identifier"}],"url":"/documentation/appkit/nsevent/trackingarea","title":"trackingArea","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/trackingArea","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackingArea","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSTrackingArea","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTrackingArea"},{"text":"?","kind":"text"}],"abstract":[{"text":"The tracking area for the event.","type":"text"}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:Si":{"abstract":[{"type":"text","text":"A signed integer value type."}],"url":"/documentation/Swift/Int","kind":"symbol","role":"symbol","title":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}]},"doc://com.apple.appkit/documentation/AppKit/NSEvent/mouseEvent(with:location:modifierFlags:timestamp:windowNumber:context:eventNumber:clickCount:pressure:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/mouseEvent(with:location:modifierFlags:timestamp:windowNumber:context:eventNumber:clickCount:pressure:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouseEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent"},{"text":".","kind":"text"},{"text":"EventType","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSEventType"},{"text":", ","kind":"text"},{"text":"location","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPoint","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint"},{"text":", ","kind":"text"},{"text":"modifierFlags","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent"},{"text":".","kind":"text"},{"text":"ModifierFlags","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSEventModifierFlags"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"text":"windowNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"text":"NSGraphicsContext","preciseIdentifier":"c:objc(cs)NSGraphicsContext","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"eventNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"clickCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pressure"},{"kind":"text","text":": "},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":") -> ","kind":"text"},{"text":"NSEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Creates and returns a new event object that describes a mouse-down, -up, -moved, or -dragged event."}],"url":"/documentation/appkit/nsevent/mouseevent(with:location:modifierflags:timestamp:windownumber:context:eventnumber:clickcount:pressure:)","title":"mouseEvent(with:location:modifierFlags:timestamp:windowNumber:context:eventNumber:clickCount:pressure:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"mouseEventWithType:location:modifierFlags:timestamp:windowNumber:context:eventNumber:clickCount:pressure:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSEvent":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSEvent"}],"role":"symbol","type":"topic","title":"NSEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSEvent"}],"abstract":[{"type":"text","text":"An object that contains information about an input action, such as a mouse click or a key press."}],"url":"/documentation/appkit/nsevent"},"doc://com.apple.appkit/documentation/AppKit/NSEvent/enterExitEvent(with:location:modifierFlags:timestamp:windowNumber:context:eventNumber:trackingNumber:userData:)":{"kind":"symbol","url":"/documentation/appkit/nsevent/enterexitevent(with:location:modifierflags:timestamp:windownumber:context:eventnumber:trackingnumber:userdata:)","title":"enterExitEvent(with:location:modifierFlags:timestamp:windowNumber:context:eventNumber:trackingNumber:userData:)","navigatorTitle":[{"text":"enterExitEventWithType:location:modifierFlags:timestamp:windowNumber:context:eventNumber:trackingNumber:userData:","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enterExitEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent"},{"text":".","kind":"text"},{"text":"EventType","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSEventType"},{"text":", ","kind":"text"},{"text":"location","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPoint","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint"},{"text":", ","kind":"text"},{"text":"modifierFlags","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent"},{"text":".","kind":"text"},{"text":"ModifierFlags","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSEventModifierFlags"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"windowNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSGraphicsContext","text":"NSGraphicsContext"},{"kind":"text","text":"?, "},{"text":"eventNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"text":"trackingNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userData"},{"kind":"text","text":": "},{"text":"UnsafeMutableRawPointer","kind":"typeIdentifier","preciseIdentifier":"s:Sv"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Creates and returns a new event object that describes a tracking-rectangle or cursor-update event."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/enterExitEvent(with:location:modifierFlags:timestamp:windowNumber:context:eventNumber:trackingNumber:userData:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSEvent/userData":{"title":"userData","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/userData","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userData","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UnsafeMutableRawPointer","kind":"typeIdentifier","preciseIdentifier":"s:Sv"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The data associated with a mouse-tracking event."}],"kind":"symbol","navigatorTitle":[{"text":"userData","kind":"identifier"}],"url":"/documentation/appkit/nsevent/userdata"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSEvent/trackingNumber":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackingNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"url":"/documentation/appkit/nsevent/trackingnumber","title":"trackingNumber","abstract":[{"type":"text","text":"The identifier of a mouse-tracking event."}],"navigatorTitle":[{"kind":"identifier","text":"trackingNumber"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/trackingNumber","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSEvent/eventNumber":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"eventNumber"}],"url":"/documentation/appkit/nsevent/eventnumber","title":"eventNumber","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/eventNumber","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"text":"The counter value of the latest mouse or tracking-rectangle event object.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"beta":false,"unavailable":false,"name":"macOS"}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"eventNumber","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"eventNumber","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSEvent"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"title":"Related Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSEvent/enterExitEvent(with:location:modifierFlags:timestamp:windowNumber:context:eventNumber:trackingNumber:userData:)","doc://com.apple.appkit/documentation/AppKit/NSEvent/mouseEvent(with:location:modifierFlags:timestamp:windowNumber:context:eventNumber:clickCount:pressure:)"],"anchor":"Related-Documentation"},{"title":"Getting tracking area information","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSEvent/trackingNumber","doc://com.apple.appkit/documentation/AppKit/NSEvent/trackingArea","doc://com.apple.appkit/documentation/AppKit/NSEvent/userData"],"anchor":"Getting-tracking-area-information","generated":true}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"eventNumber","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"/primaryContentSections/0"},{"op":"replace","path":"/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsexceptionname~11416220-internalinconsistencyexception/title","value":"NSInternalInconsistencyException"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1trackingArea/title","value":"trackingArea"},{"value":[{"kind":"identifier","text":"trackingArea"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1trackingArea/fragments","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1mouseEvent(with:location:modifierFlags:timestamp:windowNumber:context:eventNumber:clickCount:pressure:)/title","value":"mouseEventWithType:location:modifierFlags:timestamp:windowNumber:context:eventNumber:clickCount:pressure:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1mouseEvent(with:location:modifierFlags:timestamp:windowNumber:context:eventNumber:clickCount:pressure:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"mouseEventWithType:location:modifierFlags:timestamp:windowNumber:context:eventNumber:clickCount:pressure:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/title","value":"NSEvent","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/fragments","value":[{"text":"NSEvent","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/navigatorTitle","value":[{"kind":"identifier","text":"NSEvent"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1enterExitEvent(with:location:modifierFlags:timestamp:windowNumber:context:eventNumber:trackingNumber:userData:)/title","value":"enterExitEventWithType:location:modifierFlags:timestamp:windowNumber:context:eventNumber:trackingNumber:userData:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"enterExitEventWithType:location:modifierFlags:timestamp:windowNumber:context:eventNumber:trackingNumber:userData:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1enterExitEvent(with:location:modifierFlags:timestamp:windowNumber:context:eventNumber:trackingNumber:userData:)/fragments","op":"replace"},{"value":"userData","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1userData/title","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1userData/fragments","value":[{"text":"userData","kind":"identifier"}]},{"value":"trackingNumber","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1trackingNumber/title","op":"replace"},{"value":[{"kind":"identifier","text":"trackingNumber"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1trackingNumber/fragments","op":"replace"},{"value":"eventNumber","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1eventNumber/title","op":"replace"},{"value":[{"text":"eventNumber","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1eventNumber/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}