{
  "abstract": [
    {
      "text": "Constants for the types of events that responder objects can handle.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@E@NSEventType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "EventType"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "EventType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSEvent.EventType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "EventType"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These constants appear in the event’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/type",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property. You also use them when you construct new events.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitDefined": {
      "abstract": [
        {
          "text": "An AppKit-defined event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAppKitDefined"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitDefined",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAppKitDefined",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitdefined"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplicationDefined": {
      "abstract": [
        {
          "text": "An app-defined event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSApplicationDefined"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplicationDefined",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSApplicationDefined",
      "type": "topic",
      "url": "/documentation/appkit/nsapplicationdefined"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursorUpdate": {
      "abstract": [
        {
          "text": "A cursor-update event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCursorUpdate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursorUpdate",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCursorUpdate",
      "type": "topic",
      "url": "/documentation/appkit/nscursorupdate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent": {
      "abstract": [
        {
          "text": "An object that contains information about an input action, such as a mouse click or a key press.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEvent"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEvent"
        }
      ],
      "role": "symbol",
      "title": "NSEvent",
      "type": "topic",
      "url": "/documentation/appkit/nsevent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype": {
      "abstract": [
        {
          "text": "Subtypes for various types of events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EventSubtype"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EventSubtype"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventSubtype",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventsubtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType": {
      "abstract": [
        {
          "text": "Constants for the types of events that responder objects can handle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EventType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EventType"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/appKitDefined": {
      "abstract": [
        {
          "text": "An AppKit-related event occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appKitDefined"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/appKitDefined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeAppKitDefined"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.appKitDefined",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/appkitdefined"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/applicationDefined": {
      "abstract": [
        {
          "text": "An app-defined event occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationDefined"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/applicationDefined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeApplicationDefined"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.applicationDefined",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/applicationdefined"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/beginGesture": {
      "abstract": [
        {
          "text": "An event marking the beginning of a gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginGesture"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/beginGesture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeBeginGesture"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.beginGesture",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/begingesture"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/changeMode": {
      "abstract": [
        {
          "text": "The user changed the mode of a connected device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/changeMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeChangeMode"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.changeMode",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/changemode"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/cursorUpdate": {
      "abstract": [
        {
          "text": "An event that updates the cursor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cursorUpdate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/cursorUpdate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeCursorUpdate"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.cursorUpdate",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/cursorupdate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/directTouch": {
      "abstract": [
        {
          "text": "The user touched a portion of the touch bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "directTouch"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/directTouch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeDirectTouch"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.directTouch",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/directtouch"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/endGesture": {
      "abstract": [
        {
          "text": "An event that marks the end of a gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endGesture"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/endGesture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeEndGesture"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.endGesture",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/endgesture"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/flagsChanged": {
      "abstract": [
        {
          "text": "The event flags changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flagsChanged"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/flagsChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeFlagsChanged"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.flagsChanged",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/flagschanged"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/gesture": {
      "abstract": [
        {
          "text": "The user performed a nonspecific type of gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gesture"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/gesture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeGesture"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.gesture",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/gesture"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/keyDown": {
      "abstract": [
        {
          "text": "The user pressed a key on the keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyDown"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/keyDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeKeyDown"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.keyDown",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/keydown"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/keyUp": {
      "abstract": [
        {
          "text": "The user released a key on the keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyUp"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/keyUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeKeyUp"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.keyUp",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/keyup"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/leftMouseDown": {
      "abstract": [
        {
          "text": "The user pressed the left mouse button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftMouseDown"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/leftMouseDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeLeftMouseDown"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.leftMouseDown",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/leftmousedown"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/leftMouseDragged": {
      "abstract": [
        {
          "text": "The user moved the mouse while holding down the left mouse button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftMouseDragged"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/leftMouseDragged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeLeftMouseDragged"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.leftMouseDragged",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/leftmousedragged"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/leftMouseUp": {
      "abstract": [
        {
          "text": "The user released the left mouse button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftMouseUp"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/leftMouseUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeLeftMouseUp"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.leftMouseUp",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/leftmouseup"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/magnify": {
      "abstract": [
        {
          "text": "The user performed a pinch-open or pinch-close gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "magnify"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/magnify",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeMagnify"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.magnify",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/magnify"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/mouseEntered": {
      "abstract": [
        {
          "text": "The cursor entered a well-defined area, such as a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mouseEntered"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/mouseEntered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeMouseEntered"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.mouseEntered",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/mouseentered"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/mouseExited": {
      "abstract": [
        {
          "text": "The cursor exited a well-defined area, such as a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mouseExited"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/mouseExited",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeMouseExited"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.mouseExited",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/mouseexited"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/mouseMoved": {
      "abstract": [
        {
          "text": "The user moved the mouse in a way that caused the cursor to move onscreen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mouseMoved"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/mouseMoved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeMouseMoved"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.mouseMoved",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/mousemoved"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/otherMouseDown": {
      "abstract": [
        {
          "text": "The user pressed a tertiary mouse button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "otherMouseDown"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/otherMouseDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeOtherMouseDown"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.otherMouseDown",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/othermousedown"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/otherMouseDragged": {
      "abstract": [
        {
          "text": "The user moved the mouse while holding down a tertiary mouse button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "otherMouseDragged"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/otherMouseDragged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeOtherMouseDragged"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.otherMouseDragged",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/othermousedragged"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/otherMouseUp": {
      "abstract": [
        {
          "text": "The user released a tertiary mouse button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "otherMouseUp"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/otherMouseUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeOtherMouseUp"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.otherMouseUp",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/othermouseup"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/periodic": {
      "abstract": [
        {
          "text": "An event that provides execution time to periodic tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "periodic"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/periodic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypePeriodic"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.periodic",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/periodic"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/pressure": {
      "abstract": [
        {
          "text": "An event that reports a change in pressure on a pressure-sensitive device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pressure"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/pressure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypePressure"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.pressure",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/pressure"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/quickLook": {
      "abstract": [
        {
          "text": "An event that initiates a Quick Look request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickLook"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/quickLook",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeQuickLook"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.quickLook",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/quicklook"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rightMouseDown": {
      "abstract": [
        {
          "text": "The user pressed the right mouse button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightMouseDown"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rightMouseDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeRightMouseDown"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.rightMouseDown",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/rightmousedown"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rightMouseDragged": {
      "abstract": [
        {
          "text": "The user moved the mouse while holding down the right mouse button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightMouseDragged"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rightMouseDragged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeRightMouseDragged"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.rightMouseDragged",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/rightmousedragged"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rightMouseUp": {
      "abstract": [
        {
          "text": "The user released the right mouse button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightMouseUp"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rightMouseUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeRightMouseUp"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.rightMouseUp",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/rightmouseup"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rotate": {
      "abstract": [
        {
          "text": "The user performed a rotate gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rotate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rotate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeRotate"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.rotate",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/rotate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/scrollWheel": {
      "abstract": [
        {
          "text": "The scroll wheel position changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollWheel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/scrollWheel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeScrollWheel"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.scrollWheel",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/scrollwheel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/smartMagnify": {
      "abstract": [
        {
          "text": "The user performed a smart-zoom gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartMagnify"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/smartMagnify",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeSmartMagnify"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.smartMagnify",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/smartmagnify"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/swipe": {
      "abstract": [
        {
          "text": "The user performed a swipe gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "swipe"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/swipe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeSwipe"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.swipe",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/swipe"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/systemDefined": {
      "abstract": [
        {
          "text": "A system-related event occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemDefined"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/systemDefined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeSystemDefined"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.systemDefined",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/systemdefined"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/tabletPoint": {
      "abstract": [
        {
          "text": "The user touched a point on a tablet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabletPoint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/tabletPoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeTabletPoint"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.tabletPoint",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/tabletpoint"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/tabletProximity": {
      "abstract": [
        {
          "text": "A pointing device is near, but not touching, the associated tablet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabletProximity"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/tabletProximity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeTabletProximity"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.tabletProximity",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/tabletproximity"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventTypeMask": {
      "abstract": [
        {
          "text": "Constants that you use to filter out specific event types from the stream of incoming events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EventTypeMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventTypeMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EventTypeMask"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventTypeMask",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtypemask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/subtype": {
      "abstract": [
        {
          "text": "The event’s subtype.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtype"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSEventSubtype",
          "text": "EventSubtype"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/subtype",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subtype"
        }
      ],
      "role": "symbol",
      "title": "subtype",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/subtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/type": {
      "abstract": [
        {
          "text": "The event’s type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSEventType",
          "text": "EventType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/type"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFlagsChanged": {
      "abstract": [
        {
          "text": "A flags-changed event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFlagsChanged"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFlagsChanged",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFlagsChanged",
      "type": "topic",
      "url": "/documentation/appkit/nsflagschanged"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSKeyDown": {
      "abstract": [
        {
          "text": "A key-down event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSKeyDown"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSKeyDown",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSKeyDown",
      "type": "topic",
      "url": "/documentation/appkit/nskeydown"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSKeyUp": {
      "abstract": [
        {
          "text": "A key-up event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSKeyUp"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSKeyUp",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSKeyUp",
      "type": "topic",
      "url": "/documentation/appkit/nskeyup"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLeftMouseDown": {
      "abstract": [
        {
          "text": "A left mouse-down event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLeftMouseDown"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLeftMouseDown",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLeftMouseDown",
      "type": "topic",
      "url": "/documentation/appkit/nsleftmousedown"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLeftMouseDragged": {
      "abstract": [
        {
          "text": "A left mouse-dragged event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLeftMouseDragged"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLeftMouseDragged",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLeftMouseDragged",
      "type": "topic",
      "url": "/documentation/appkit/nsleftmousedragged"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLeftMouseUp": {
      "abstract": [
        {
          "text": "A left mouse-up event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLeftMouseUp"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLeftMouseUp",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLeftMouseUp",
      "type": "topic",
      "url": "/documentation/appkit/nsleftmouseup"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMouseEntered": {
      "abstract": [
        {
          "text": "A mouse-entered event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMouseEntered"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMouseEntered",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMouseEntered",
      "type": "topic",
      "url": "/documentation/appkit/nsmouseentered"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMouseExited": {
      "abstract": [
        {
          "text": "A mouse-exited event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMouseExited"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMouseExited",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMouseExited",
      "type": "topic",
      "url": "/documentation/appkit/nsmouseexited"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMouseMoved": {
      "abstract": [
        {
          "text": "A mouse-moved event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMouseMoved"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMouseMoved",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMouseMoved",
      "type": "topic",
      "url": "/documentation/appkit/nsmousemoved"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOtherMouseDown": {
      "abstract": [
        {
          "text": "An other mouse-down event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOtherMouseDown"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOtherMouseDown",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOtherMouseDown",
      "type": "topic",
      "url": "/documentation/appkit/nsothermousedown"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOtherMouseDragged": {
      "abstract": [
        {
          "text": "An other mouse-dragged event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOtherMouseDragged"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOtherMouseDragged",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOtherMouseDragged",
      "type": "topic",
      "url": "/documentation/appkit/nsothermousedragged"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOtherMouseUp": {
      "abstract": [
        {
          "text": "An other mouse-up event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOtherMouseUp"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOtherMouseUp",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOtherMouseUp",
      "type": "topic",
      "url": "/documentation/appkit/nsothermouseup"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPeriodic": {
      "abstract": [
        {
          "text": "A periodic event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPeriodic"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPeriodic",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPeriodic",
      "type": "topic",
      "url": "/documentation/appkit/nsperiodic"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRightMouseDown": {
      "abstract": [
        {
          "text": "A right mouse-down event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRightMouseDown"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRightMouseDown",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRightMouseDown",
      "type": "topic",
      "url": "/documentation/appkit/nsrightmousedown"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRightMouseDragged": {
      "abstract": [
        {
          "text": "A right mouse-dragged event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRightMouseDragged"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRightMouseDragged",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRightMouseDragged",
      "type": "topic",
      "url": "/documentation/appkit/nsrightmousedragged"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRightMouseUp": {
      "abstract": [
        {
          "text": "A right mouse-up event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRightMouseUp"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRightMouseUp",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRightMouseUp",
      "type": "topic",
      "url": "/documentation/appkit/nsrightmouseup"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrollWheel": {
      "abstract": [
        {
          "text": "A scroll-wheel event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSScrollWheel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrollWheel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSScrollWheel",
      "type": "topic",
      "url": "/documentation/appkit/nsscrollwheel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSystemDefined": {
      "abstract": [
        {
          "text": "A system-defined event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSSystemDefined"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSystemDefined",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSystemDefined",
      "type": "topic",
      "url": "/documentation/appkit/nssystemdefined"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTabletPoint": {
      "abstract": [
        {
          "text": "An event representing the current state of a tablet pointing device, including its location, pressure, and tilt.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTabletPoint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTabletPoint",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTabletPoint",
      "type": "topic",
      "url": "/documentation/appkit/nstabletpoint"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTabletProximity": {
      "abstract": [
        {
          "text": "An event representing the proximity of a pointing device to its tablet.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTabletProximity"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTabletProximity",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTabletProximity",
      "type": "topic",
      "url": "/documentation/appkit/nstabletproximity"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-event-type",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/type",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventTypeMask",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/subtype",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype"
      ],
      "title": "Getting the event type"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-Mouse-Related-Event-Types",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/leftMouseDown",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/leftMouseDragged",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/leftMouseUp",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rightMouseDown",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rightMouseUp",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rightMouseDragged",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/otherMouseDown",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/otherMouseDragged",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/otherMouseUp",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/mouseMoved",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/mouseEntered",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/mouseExited"
      ],
      "title": "Getting Mouse-Related Event Types"
    },
    {
      "anchor": "Getting-Keyboard-Event-Types",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/keyDown",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/keyUp"
      ],
      "title": "Getting Keyboard Event Types"
    },
    {
      "anchor": "Getting-Touch-Based-Events",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/beginGesture",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/endGesture",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/magnify",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/smartMagnify",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/swipe",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rotate",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/gesture",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/directTouch",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/tabletPoint",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/tabletProximity",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/pressure"
      ],
      "title": "Getting Touch-Based Events"
    },
    {
      "anchor": "Getting-Other-Input-Types",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/scrollWheel",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/changeMode"
      ],
      "title": "Getting Other Input Types"
    },
    {
      "anchor": "Getting-System-Event-Types",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/appKitDefined",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/applicationDefined",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/cursorUpdate",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/flagsChanged",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/periodic",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/quickLook",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/systemDefined"
      ],
      "title": "Getting System Event Types"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSEventType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-Mouse-Related-Event-Types",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/leftMouseDown",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/leftMouseDragged",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/leftMouseUp",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rightMouseDown",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rightMouseUp",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rightMouseDragged",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/otherMouseDown",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/otherMouseDragged",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/otherMouseUp",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/mouseMoved",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/mouseEntered",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/mouseExited"
              ],
              "title": "Getting Mouse-Related Event Types"
            },
            {
              "anchor": "Getting-Keyboard-Event-Types",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/keyDown",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/keyUp"
              ],
              "title": "Getting Keyboard Event Types"
            },
            {
              "anchor": "Getting-Touch-Based-Events",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/beginGesture",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/endGesture",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/magnify",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/smartMagnify",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/swipe",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rotate",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/gesture",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/directTouch",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/tabletPoint",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/tabletProximity",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/pressure"
              ],
              "title": "Getting Touch-Based Events"
            },
            {
              "anchor": "Getting-Other-Input-Types",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/scrollWheel",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/changeMode"
              ],
              "title": "Getting Other Input Types"
            },
            {
              "anchor": "Getting-System-Event-Types",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/appKitDefined",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/applicationDefined",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/cursorUpdate",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/flagsChanged",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/periodic",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/quickLook",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/systemDefined"
              ],
              "title": "Getting System Event Types"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSLeftMouseDown",
                "doc://com.apple.appkit/documentation/AppKit/NSLeftMouseUp",
                "doc://com.apple.appkit/documentation/AppKit/NSRightMouseDown",
                "doc://com.apple.appkit/documentation/AppKit/NSRightMouseUp",
                "doc://com.apple.appkit/documentation/AppKit/NSOtherMouseDown",
                "doc://com.apple.appkit/documentation/AppKit/NSOtherMouseUp",
                "doc://com.apple.appkit/documentation/AppKit/NSMouseMoved",
                "doc://com.apple.appkit/documentation/AppKit/NSLeftMouseDragged",
                "doc://com.apple.appkit/documentation/AppKit/NSRightMouseDragged",
                "doc://com.apple.appkit/documentation/AppKit/NSOtherMouseDragged",
                "doc://com.apple.appkit/documentation/AppKit/NSMouseEntered",
                "doc://com.apple.appkit/documentation/AppKit/NSMouseExited",
                "doc://com.apple.appkit/documentation/AppKit/NSCursorUpdate",
                "doc://com.apple.appkit/documentation/AppKit/NSKeyDown",
                "doc://com.apple.appkit/documentation/AppKit/NSKeyUp",
                "doc://com.apple.appkit/documentation/AppKit/NSFlagsChanged",
                "doc://com.apple.appkit/documentation/AppKit/NSAppKitDefined",
                "doc://com.apple.appkit/documentation/AppKit/NSSystemDefined",
                "doc://com.apple.appkit/documentation/AppKit/NSApplicationDefined",
                "doc://com.apple.appkit/documentation/AppKit/NSPeriodic",
                "doc://com.apple.appkit/documentation/AppKit/NSScrollWheel",
                "doc://com.apple.appkit/documentation/AppKit/NSTabletPoint",
                "doc://com.apple.appkit/documentation/AppKit/NSTabletProximity"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-event-type",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/type",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventTypeMask",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/subtype",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype"
              ],
              "title": "Getting the event type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSEventType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1mouseMoved/title",
          "value": "NSEventTypeMouseMoved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1mouseMoved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeMouseMoved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1leftMouseUp/title",
          "value": "NSEventTypeLeftMouseUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1leftMouseUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeLeftMouseUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1magnify/title",
          "value": "NSEventTypeMagnify"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1magnify/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeMagnify"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/title",
          "value": "NSEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1applicationDefined/title",
          "value": "NSEventTypeApplicationDefined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1applicationDefined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeApplicationDefined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1rightMouseDragged/title",
          "value": "NSEventTypeRightMouseDragged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1rightMouseDragged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeRightMouseDragged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1keyUp/title",
          "value": "NSEventTypeKeyUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1keyUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeKeyUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1smartMagnify/title",
          "value": "NSEventTypeSmartMagnify"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1smartMagnify/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeSmartMagnify"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1mouseExited/title",
          "value": "NSEventTypeMouseExited"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1mouseExited/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeMouseExited"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1directTouch/title",
          "value": "NSEventTypeDirectTouch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1directTouch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeDirectTouch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1changeMode/title",
          "value": "NSEventTypeChangeMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1changeMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeChangeMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1rotate/title",
          "value": "NSEventTypeRotate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1rotate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeRotate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1subtype/title",
          "value": "subtype"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1subtype/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1systemDefined/title",
          "value": "NSEventTypeSystemDefined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1systemDefined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeSystemDefined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1keyDown/title",
          "value": "NSEventTypeKeyDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1keyDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeKeyDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventTypeMask/title",
          "value": "NSEventMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventTypeMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventTypeMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1leftMouseDown/title",
          "value": "NSEventTypeLeftMouseDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1leftMouseDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeLeftMouseDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1swipe/title",
          "value": "NSEventTypeSwipe"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1swipe/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeSwipe"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType/title",
          "value": "NSEventType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1pressure/title",
          "value": "NSEventTypePressure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1pressure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypePressure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1rightMouseDown/title",
          "value": "NSEventTypeRightMouseDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1rightMouseDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeRightMouseDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1flagsChanged/title",
          "value": "NSEventTypeFlagsChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1flagsChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeFlagsChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1otherMouseDown/title",
          "value": "NSEventTypeOtherMouseDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1otherMouseDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeOtherMouseDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1quickLook/title",
          "value": "NSEventTypeQuickLook"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1quickLook/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeQuickLook"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1periodic/title",
          "value": "NSEventTypePeriodic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1periodic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypePeriodic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1endGesture/title",
          "value": "NSEventTypeEndGesture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1endGesture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeEndGesture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1otherMouseUp/title",
          "value": "NSEventTypeOtherMouseUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1otherMouseUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeOtherMouseUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1tabletProximity/title",
          "value": "NSEventTypeTabletProximity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1tabletProximity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeTabletProximity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1appKitDefined/title",
          "value": "NSEventTypeAppKitDefined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1appKitDefined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeAppKitDefined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1otherMouseDragged/title",
          "value": "NSEventTypeOtherMouseDragged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1otherMouseDragged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeOtherMouseDragged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1rightMouseUp/title",
          "value": "NSEventTypeRightMouseUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1rightMouseUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeRightMouseUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype/title",
          "value": "NSEventSubtype"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1mouseEntered/title",
          "value": "NSEventTypeMouseEntered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1mouseEntered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeMouseEntered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1scrollWheel/title",
          "value": "NSEventTypeScrollWheel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1scrollWheel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeScrollWheel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1cursorUpdate/title",
          "value": "NSEventTypeCursorUpdate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1cursorUpdate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeCursorUpdate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1gesture/title",
          "value": "NSEventTypeGesture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1gesture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeGesture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1beginGesture/title",
          "value": "NSEventTypeBeginGesture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1beginGesture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeBeginGesture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1leftMouseDragged/title",
          "value": "NSEventTypeLeftMouseDragged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1leftMouseDragged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeLeftMouseDragged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1tabletPoint/title",
          "value": "NSEventTypeTabletPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1tabletPoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeTabletPoint"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsevent/eventtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsevent/eventtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
