{"metadata":{"modules":[{"name":"AppKit"}],"externalID":"c:@NSEventDurationForever","role":"symbol","title":"foreverDuration","platforms":[{"unavailable":false,"deprecated":false,"name":"macOS","beta":false}],"symbolKind":"property","roleHeading":"Type Property","extendedModule":"AppKit","navigatorTitle":[{"kind":"identifier","text":"NSEventDurationForever"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"foreverDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"foreverDuration"},{"kind":"text","text":": "},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSTimeInterval"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSEvent"]]},"seeAlsoSections":[{"title":"Getting general event information","generated":true,"anchor":"Getting-general-event-information","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSEvent/locationInWindow","doc://com.apple.appkit/documentation/AppKit/NSEvent/timestamp","doc://com.apple.appkit/documentation/AppKit/NSEvent/window","doc://com.apple.appkit/documentation/AppKit/NSEvent/windowNumber","doc://com.apple.appkit/documentation/AppKit/NSEvent/eventRef","doc://com.apple.appkit/documentation/AppKit/NSEvent/cgEvent"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsevent/foreverduration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsevent/foreverduration"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSEvent/foreverDuration"},"sections":[],"abstract":[{"text":"The longest time duration possible.","type":"text"}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSEvent/cgEvent":{"abstract":[{"text":"The Core Graphics event object corresponding to this event.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/cgEvent","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cgEvent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGEvent","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGEventRef"},{"text":"?","kind":"text"}],"title":"cgEvent","url":"/documentation/appkit/nsevent/cgevent","navigatorTitle":[{"text":"CGEvent","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSEvent/window":{"url":"/documentation/appkit/nsevent/window","role":"symbol","kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/window","navigatorTitle":[{"text":"window","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"window","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSWindow"},{"text":"?","kind":"text"}],"title":"window","abstract":[{"text":"The window object associated with the event.","type":"text"}]},"doc://com.externally.resolved.symbol/c:@T@NSTimeInterval":{"role":"symbol","fragments":[{"text":"typealias ","kind":"text"},{"text":"TimeInterval","kind":"identifier"}],"url":"/documentation/foundation/timeinterval","type":"topic","kind":"symbol","title":"TimeInterval","abstract":[{"text":"A number of seconds.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@NSTimeInterval"},"doc://com.apple.appkit/documentation/AppKit/NSEvent/windowNumber":{"url":"/documentation/appkit/nsevent/windownumber","role":"symbol","kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/windowNumber","navigatorTitle":[{"text":"windowNumber","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"windowNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"windowNumber","abstract":[{"text":"The identifier for the window device associated with the event.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSEvent/foreverDuration":{"url":"/documentation/appkit/nsevent/foreverduration","type":"topic","title":"foreverDuration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSEventDurationForever"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"foreverDuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}],"abstract":[{"type":"text","text":"The longest time duration possible."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/foreverDuration","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSEvent/eventRef":{"abstract":[{"type":"text","text":"An opaque Carbon type associated with this event."}],"type":"topic","title":"eventRef","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventRef"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeRawPointer","preciseIdentifier":"s:SV"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/eventRef","role":"symbol","url":"/documentation/appkit/nsevent/eventref","navigatorTitle":[{"kind":"identifier","text":"eventRef"}]},"doc://com.apple.appkit/documentation/AppKit/NSEvent":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSEvent"}],"role":"symbol","type":"topic","title":"NSEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSEvent"}],"abstract":[{"type":"text","text":"An object that contains information about an input action, such as a mouse click or a key press."}],"url":"/documentation/appkit/nsevent"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSEvent/timestamp":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/timestamp","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"kind":"symbol","role":"symbol","url":"/documentation/appkit/nsevent/timestamp","navigatorTitle":[{"text":"timestamp","kind":"identifier"}],"abstract":[{"text":"The time when the event occurred in seconds since system startup.","type":"text"}],"title":"timestamp"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSEvent/locationInWindow":{"url":"/documentation/appkit/nsevent/locationinwindow","role":"symbol","kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/locationInWindow","navigatorTitle":[{"kind":"identifier","text":"locationInWindow"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"locationInWindow","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSPoint","preciseIdentifier":"c:@T@NSPoint"}],"title":"locationInWindow","abstract":[{"text":"The event location in the base coordinate system of the associated window.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"path":"/metadata/platforms","value":[{"deprecated":false,"name":"macOS","beta":false,"unavailable":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Global Variable","op":"replace"},{"path":"/metadata/title","value":"NSEventDurationForever","op":"replace"},{"path":"/metadata/symbolKind","value":"var","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"NSEventDurationForever"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSEvent/locationInWindow","doc://com.apple.appkit/documentation/AppKit/NSEvent/timestamp","doc://com.apple.appkit/documentation/AppKit/NSEvent/window","doc://com.apple.appkit/documentation/AppKit/NSEvent/windowNumber","doc://com.apple.appkit/documentation/AppKit/NSEvent/eventRef","doc://com.apple.appkit/documentation/AppKit/NSEvent/cgEvent"],"title":"Getting general event information","anchor":"Getting-general-event-information"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval","identifier":"doc://com.externally.resolved.symbol/c:@T@NSTimeInterval"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSEventDurationForever"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1cgEvent/title","value":"CGEvent","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1cgEvent/fragments","value":[{"kind":"identifier","text":"CGEvent"}],"op":"replace"},{"value":"window","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1window/title"},{"value":[{"text":"window","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1window/fragments"},{"value":"NSTimeInterval","op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSTimeInterval/title"},{"value":"windowNumber","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1windowNumber/title"},{"value":[{"kind":"identifier","text":"windowNumber"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1windowNumber/fragments"},{"value":"NSEventDurationForever","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1foreverDuration/title"},{"value":[{"text":"NSEventDurationForever","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1foreverDuration/fragments"},{"value":"eventRef","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1eventRef/title"},{"value":[{"kind":"identifier","text":"eventRef"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1eventRef/fragments"},{"value":"NSEvent","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/title"},{"value":[{"text":"NSEvent","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/fragments"},{"value":[{"kind":"identifier","text":"NSEvent"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/navigatorTitle"},{"value":"timestamp","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1timestamp/title"},{"value":[{"kind":"identifier","text":"timestamp"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1timestamp/fragments"},{"value":"locationInWindow","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1locationInWindow/title"},{"value":[{"kind":"identifier","text":"locationInWindow"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1locationInWindow/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}