{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsevent/mouseevent(with:location:modifierflags:timestamp:windownumber:context:eventnumber:clickcount:pressure:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsevent/mouseevent(with:location:modifierflags:timestamp:windownumber:context:eventnumber:clickcount:pressure:)"]}],"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSEvent/clickCount","doc://com.apple.appkit/documentation/AppKit/NSEvent/eventNumber","doc://com.apple.documentation/documentation/foundation/processinfo/1414553-systemuptime","doc://com.apple.appkit/documentation/AppKit/NSEvent/pressure"],"title":"Related Documentation","anchor":"Related-Documentation"},{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSEvent/keyEvent(with:location:modifierFlags:timestamp:windowNumber:context:characters:charactersIgnoringModifiers:isARepeat:keyCode:)","doc://com.apple.appkit/documentation/AppKit/NSEvent/enterExitEvent(with:location:modifierFlags:timestamp:windowNumber:context:eventNumber:trackingNumber:userData:)","doc://com.apple.appkit/documentation/AppKit/NSEvent/otherEvent(with:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:)","doc://com.apple.appkit/documentation/AppKit/NSEvent/init(eventRef:)","doc://com.apple.appkit/documentation/AppKit/NSEvent/init(cgEvent:)"],"title":"Creating an event object","anchor":"Creating-an-event-object"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSEvent"]]},"sections":[],"abstract":[{"type":"text","text":"Creates and returns a new event object that describes a mouse-down, -up, -moved, or -dragged event."}],"kind":"symbol","metadata":{"externalID":"c:objc(cs)NSEvent(cm)mouseEventWithType:location:modifierFlags:timestamp:windowNumber:context:eventNumber:clickCount:pressure:","symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"mouseEventWithType:location:modifierFlags:timestamp:windowNumber:context:eventNumber:clickCount:pressure:"}],"title":"mouseEvent(with:location:modifierFlags:timestamp:windowNumber:context:eventNumber:clickCount:pressure:)","platforms":[{"beta":false,"deprecated":false,"unavailable":false,"name":"macOS"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouseEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSEventType","text":"EventType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"location","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSPoint","text":"NSPoint","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"modifierFlags","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSEventModifierFlags","text":"ModifierFlags","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"windowNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"context","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSGraphicsContext","text":"NSGraphicsContext","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"eventNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"clickCount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pressure","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"AppKit"}],"roleHeading":"Type Method"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouseEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSEvent","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent","text":"NSEvent","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSEventType","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType","text":"EventType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"location","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSPoint","identifier":"doc://com.externally.resolved.symbol/c:@T@NSPoint","text":"NSPoint","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"modifierFlags","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"flags","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSEvent","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent","text":"NSEvent","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSEventModifierFlags","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/ModifierFlags-swift.struct","text":"ModifierFlags","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"time","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","identifier":"doc://com.externally.resolved.symbol/c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"windowNumber","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"wNum","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","identifier":"doc://com.externally.resolved.symbol/s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"context","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"unusedPassNil","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSGraphicsContext","identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext","text":"NSGraphicsContext","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"eventNumber","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"eNum","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","identifier":"doc://com.externally.resolved.symbol/s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"clickCount","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"cNum","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","identifier":"doc://com.externally.resolved.symbol/s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pressure","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","identifier":"doc://com.externally.resolved.symbol/s:Sf","text":"Float","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSEvent","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent","text":"NSEvent","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"One of the modifier key masks described in "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType"},{"type":"text","text":", or an "},{"type":"codeVoice","code":"NSInternalInconsistencyException"},{"type":"text","text":" is raised."}]}],"name":"type"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The cursor location in the base coordinate system of the window specified by ","type":"text"},{"code":"windowNum","type":"codeVoice"},{"text":".","type":"text"}]}],"name":"location"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An integer bit field containing any of the modifier key masks described in "},{"type":"codeVoice","code":"Getting Unicode Values"},{"type":"text","text":", combined using the C bitwise OR operator."}]}],"name":"flags"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The time the event occurred in seconds since system startup.","type":"text"}]}],"name":"time"},{"content":[{"inlineContent":[{"text":"An integer that identifies the window device associated with the event, which is associated with the ","type":"text"},{"code":"NSWindow","type":"codeVoice"},{"text":" that will receive the event.","type":"text"}],"type":"paragraph"}],"name":"wNum"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The display graphics context of the event. Pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" for this parameter."}]}],"name":"unusedPassNil"},{"content":[{"type":"paragraph","inlineContent":[{"text":"An identifier for the new event. It’s normally taken from a counter for mouse events, which continually increases as the application runs.","type":"text"}]}],"name":"eNum"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The number of mouse clicks associated with the mouse event.","type":"text"}]}],"name":"cNum"},{"content":[{"type":"paragraph","inlineContent":[{"text":"A value from ","type":"text"},{"code":"0.0","type":"codeVoice"},{"text":" to ","type":"text"},{"code":"1.0","type":"codeVoice"},{"text":" indicating the pressure applied to the input device on a mouse event, used for an appropriate device such as a graphics tablet. For devices that aren’t pressure-sensitive, the value should be either ","type":"text"},{"code":"0.0","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"1.0","type":"codeVoice"},{"text":".","type":"text"}]}],"name":"pressure"}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"The created "},{"type":"codeVoice","code":"NSEvent"},{"type":"text","text":" instance or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the instance could not be created."}],"type":"paragraph"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSEvent/mouseEvent(with:location:modifierFlags:timestamp:windowNumber:context:eventNumber:clickCount:pressure:)"},"references":{"doc://com.apple.appkit/documentation/AppKit/NSEvent/init(cgEvent:)":{"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/init(cgEvent:)","url":"/documentation/appkit/nsevent/init(cgevent:)","navigatorTitle":[{"text":"eventWithCGEvent:","kind":"identifier"}],"title":"init(cgEvent:)","abstract":[{"text":"Creates and returns an event object for a Core Graphics event.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"cgEvent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGEvent","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGEventRef"},{"text":")","kind":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSEvent/keyEvent(with:location:modifierFlags:timestamp:windowNumber:context:characters:charactersIgnoringModifiers:isARepeat:keyCode:)":{"role":"symbol","abstract":[{"text":"Creates and returns a new event object that describes a key event.","type":"text"}],"url":"/documentation/appkit/nsevent/keyevent(with:location:modifierflags:timestamp:windownumber:context:characters:charactersignoringmodifiers:isarepeat:keycode:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyEvent"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSEventType","text":"EventType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"location","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSPoint","text":"NSPoint","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"modifierFlags","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent"},{"text":".","kind":"text"},{"text":"ModifierFlags","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSEventModifierFlags"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"text":"windowNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"context","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSGraphicsContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSGraphicsContext"},{"text":"?, ","kind":"text"},{"text":"characters","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"charactersIgnoringModifiers","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"isARepeat","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"keyCode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt16","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt16V"},{"text":") -> ","kind":"text"},{"text":"NSEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"keyEventWithType:location:modifierFlags:timestamp:windowNumber:context:characters:charactersIgnoringModifiers:isARepeat:keyCode:","kind":"identifier"}],"type":"topic","title":"keyEvent(with:location:modifierFlags:timestamp:windowNumber:context:characters:charactersIgnoringModifiers:isARepeat:keyCode:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/keyEvent(with:location:modifierFlags:timestamp:windowNumber:context:characters:charactersIgnoringModifiers:isARepeat:keyCode:)"},"doc://com.apple.appkit/documentation/AppKit/NSEvent":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSEvent"}],"role":"symbol","type":"topic","title":"NSEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSEvent"}],"abstract":[{"type":"text","text":"An object that contains information about an input action, such as a mouse click or a key press."}],"url":"/documentation/appkit/nsevent"},"doc://com.apple.appkit/documentation/AppKit/NSEvent/otherEvent(with:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/otherEvent(with:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"otherEventWithType:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:"}],"url":"/documentation/appkit/nsevent/otherevent(with:location:modifierflags:timestamp:windownumber:context:subtype:data1:data2:)","type":"topic","abstract":[{"type":"text","text":"Creates and returns a new event object that describes a custom event."}],"role":"symbol","title":"otherEvent(with:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"otherEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSEventType","text":"EventType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint","text":"NSPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"modifierFlags"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSEventModifierFlags","text":"ModifierFlags"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"windowNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSGraphicsContext","text":"NSGraphicsContext"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"subtype"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int16V","text":"Int16"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent"},{"kind":"text","text":"?"}]},"doc://com.apple.appkit/documentation/AppKit/NSEvent/init(eventRef:)":{"title":"init(eventRef:)","type":"topic","abstract":[{"type":"text","text":"Creates and returns a new event object for a Carbon event."}],"url":"/documentation/appkit/nsevent/init(eventref:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"eventRef"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SV","kind":"typeIdentifier","text":"UnsafeRawPointer"},{"kind":"text","text":")"}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/init(eventRef:)","navigatorTitle":[{"kind":"identifier","text":"eventWithEventRef:"}],"kind":"symbol"},"doc://com.externally.resolved.symbol/s:Sf":{"fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Float","kind":"identifier"}],"url":"/documentation/Swift/Float","abstract":[{"text":"A single-precision, floating-point value type.","type":"text"}],"type":"topic","identifier":"doc://com.externally.resolved.symbol/s:Sf","kind":"symbol","role":"symbol","title":"Float"},"doc://com.apple.appkit/documentation/AppKit/NSEvent/mouseEvent(with:location:modifierFlags:timestamp:windowNumber:context:eventNumber:clickCount:pressure:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/mouseEvent(with:location:modifierFlags:timestamp:windowNumber:context:eventNumber:clickCount:pressure:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouseEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent"},{"text":".","kind":"text"},{"text":"EventType","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSEventType"},{"text":", ","kind":"text"},{"text":"location","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPoint","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint"},{"text":", ","kind":"text"},{"text":"modifierFlags","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent"},{"text":".","kind":"text"},{"text":"ModifierFlags","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSEventModifierFlags"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"text":"windowNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"text":"NSGraphicsContext","preciseIdentifier":"c:objc(cs)NSGraphicsContext","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"eventNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"clickCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pressure"},{"kind":"text","text":": "},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":") -> ","kind":"text"},{"text":"NSEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Creates and returns a new event object that describes a mouse-down, -up, -moved, or -dragged event."}],"url":"/documentation/appkit/nsevent/mouseevent(with:location:modifierflags:timestamp:windownumber:context:eventnumber:clickcount:pressure:)","title":"mouseEvent(with:location:modifierFlags:timestamp:windowNumber:context:eventNumber:clickCount:pressure:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"mouseEventWithType:location:modifierFlags:timestamp:windowNumber:context:eventNumber:clickCount:pressure:","kind":"identifier"}]},"doc://com.externally.resolved.symbol/c:@T@NSTimeInterval":{"role":"symbol","fragments":[{"text":"typealias ","kind":"text"},{"text":"TimeInterval","kind":"identifier"}],"url":"/documentation/foundation/timeinterval","type":"topic","kind":"symbol","title":"TimeInterval","abstract":[{"text":"A number of seconds.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@NSTimeInterval"},"doc://com.apple.appkit/documentation/AppKit/NSEvent/ModifierFlags-swift.struct":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModifierFlags","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/ModifierFlags-swift.struct","abstract":[{"text":"Flags that represent key states in an event object.","type":"text"}],"type":"topic","title":"NSEvent.ModifierFlags","kind":"symbol","navigatorTitle":[{"text":"ModifierFlags","kind":"identifier"}],"url":"/documentation/appkit/nsevent/modifierflags-swift.struct","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSEvent/pressure":{"url":"/documentation/appkit/nsevent/pressure","role":"symbol","kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/pressure","navigatorTitle":[{"text":"pressure","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pressure","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"title":"pressure","abstract":[{"type":"text","text":"A normalized value that indicates the degree of pressure applied to an appropriate input device."}]},"doc://com.apple.appkit/documentation/AppKit/NSEvent/enterExitEvent(with:location:modifierFlags:timestamp:windowNumber:context:eventNumber:trackingNumber:userData:)":{"kind":"symbol","url":"/documentation/appkit/nsevent/enterexitevent(with:location:modifierflags:timestamp:windownumber:context:eventnumber:trackingnumber:userdata:)","title":"enterExitEvent(with:location:modifierFlags:timestamp:windowNumber:context:eventNumber:trackingNumber:userData:)","navigatorTitle":[{"text":"enterExitEventWithType:location:modifierFlags:timestamp:windowNumber:context:eventNumber:trackingNumber:userData:","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enterExitEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent"},{"text":".","kind":"text"},{"text":"EventType","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSEventType"},{"text":", ","kind":"text"},{"text":"location","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPoint","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint"},{"text":", ","kind":"text"},{"text":"modifierFlags","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent"},{"text":".","kind":"text"},{"text":"ModifierFlags","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSEventModifierFlags"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"windowNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSGraphicsContext","text":"NSGraphicsContext"},{"kind":"text","text":"?, "},{"text":"eventNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"text":"trackingNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userData"},{"kind":"text","text":": "},{"text":"UnsafeMutableRawPointer","kind":"typeIdentifier","preciseIdentifier":"s:Sv"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Creates and returns a new event object that describes a tracking-rectangle or cursor-update event."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/enterExitEvent(with:location:modifierFlags:timestamp:windowNumber:context:eventNumber:trackingNumber:userData:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType":{"url":"/documentation/appkit/nsevent/eventtype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EventType","kind":"identifier"}],"title":"NSEvent.EventType","kind":"symbol","abstract":[{"text":"Constants for the types of events that responder objects can handle.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType","role":"symbol","type":"topic","navigatorTitle":[{"text":"EventType","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSEvent/clickCount":{"role":"symbol","navigatorTitle":[{"text":"clickCount","kind":"identifier"}],"title":"clickCount","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/clickCount","abstract":[{"type":"text","text":"The number of mouse clicks associated with a mouse-down or mouse-up event."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"clickCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"url":"/documentation/appkit/nsevent/clickcount","type":"topic"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.externally.resolved.symbol/s:Si":{"abstract":[{"type":"text","text":"A signed integer value type."}],"url":"/documentation/Swift/Int","kind":"symbol","role":"symbol","title":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}]},"doc://com.apple.documentation/documentation/foundation/processinfo/1414553-systemuptime":{"type":"topic","abstract":[{"text":"The amount of time the system has been awake since the last time it was restarted.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"var ","kind":"text"},{"kind":"identifier","text":"systemUptime"},{"kind":"text","text":": TimeInterval"}],"url":"/documentation/foundation/processinfo/1414553-systemuptime","identifier":"doc://com.apple.documentation/documentation/foundation/processinfo/1414553-systemuptime","title":"systemUptime"},"doc://com.externally.resolved.symbol/c:@T@NSPoint":{"abstract":[{"text":"A point in a Cartesian coordinate system.","type":"text"}],"url":"/documentation/foundation/nspoint","kind":"symbol","role":"symbol","title":"NSPoint","identifier":"doc://com.externally.resolved.symbol/c:@T@NSPoint","type":"topic","fragments":[{"text":"typealias ","kind":"text"},{"text":"NSPoint","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext","role":"symbol","type":"topic","url":"/documentation/appkit/nsgraphicscontext","navigatorTitle":[{"text":"NSGraphicsContext","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that represents a graphics context."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSGraphicsContext","kind":"identifier"}],"title":"NSGraphicsContext","kind":"symbol"},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"NSInteger"}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes an integer."}],"title":"NSInteger"},"doc://com.apple.appkit/documentation/AppKit/NSEvent/eventNumber":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"eventNumber"}],"url":"/documentation/appkit/nsevent/eventnumber","title":"eventNumber","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/eventNumber","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"text":"The counter value of the latest mouse or tracking-rectangle event object.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"deprecated":false,"name":"macOS","unavailable":false,"beta":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Type Method","op":"replace"},{"path":"/metadata/title","value":"mouseEventWithType:location:modifierFlags:timestamp:windowNumber:context:eventNumber:clickCount:pressure:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"+ ","kind":"text"},{"text":"mouseEventWithType:location:modifierFlags:timestamp:windowNumber:context:eventNumber:clickCount:pressure:","kind":"identifier"}],"op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSEvent"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSEvent/clickCount","doc://com.apple.appkit/documentation/AppKit/NSEvent/eventNumber","doc://com.apple.documentation/documentation/foundation/processinfo/1414553-systemuptime","doc://com.apple.appkit/documentation/AppKit/NSEvent/pressure"],"anchor":"Related-Documentation","title":"Related Documentation"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSEvent/keyEvent(with:location:modifierFlags:timestamp:windowNumber:context:characters:charactersIgnoringModifiers:isARepeat:keyCode:)","doc://com.apple.appkit/documentation/AppKit/NSEvent/enterExitEvent(with:location:modifierFlags:timestamp:windowNumber:context:eventNumber:trackingNumber:userData:)","doc://com.apple.appkit/documentation/AppKit/NSEvent/otherEvent(with:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:)","doc://com.apple.appkit/documentation/AppKit/NSEvent/init(eventRef:)","doc://com.apple.appkit/documentation/AppKit/NSEvent/init(cgEvent:)"],"generated":true,"anchor":"Creating-an-event-object","title":"Creating an event object"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent","text":"NSEvent","preciseIdentifier":"c:objc(cs)NSEvent"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"mouseEventWithType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSEventType","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType","text":"NSEventType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"kind":"text","text":" "},{"kind":"identifier","text":"location:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint","identifier":"doc://com.externally.resolved.symbol/c:@T@NSPoint","text":"NSPoint"},{"kind":"text","text":") "},{"kind":"internalParam","text":"location"},{"kind":"text","text":" "},{"kind":"identifier","text":"modifierFlags:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSEventModifierFlags","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/ModifierFlags-swift.struct","text":"NSEventModifierFlags"},{"kind":"text","text":") "},{"kind":"internalParam","text":"flags"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","identifier":"doc://com.externally.resolved.symbol/c:@T@NSTimeInterval","text":"NSTimeInterval"},{"kind":"text","text":") "},{"kind":"internalParam","text":"time"},{"kind":"text","text":" "},{"kind":"identifier","text":"windowNumber:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"wNum"},{"kind":"text","text":" "},{"kind":"identifier","text":"context:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSGraphicsContext","identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext","kind":"typeIdentifier","text":"NSGraphicsContext"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"unusedPassNil"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventNumber:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"eNum"},{"kind":"text","text":" "},{"kind":"identifier","text":"clickCount:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cNum"},{"kind":"text","text":" "},{"kind":"identifier","text":"pressure:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:f","kind":"typeIdentifier","text":"float"},{"kind":"text","text":") "},{"kind":"internalParam","text":"pressure"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"]}]},"path":"/primaryContentSections/0","op":"replace"},{"value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"One of the modifier key masks described in "},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType","isActive":true},{"type":"text","text":", or an "},{"type":"codeVoice","code":"NSInternalInconsistencyException"},{"type":"text","text":" is raised."}],"type":"paragraph"}],"name":"type"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The cursor location in the base coordinate system of the window specified by "},{"type":"codeVoice","code":"windowNum"},{"type":"text","text":"."}]}],"name":"location"},{"content":[{"inlineContent":[{"text":"An integer bit field containing any of the modifier key masks described in ","type":"text"},{"code":"Getting Unicode Values","type":"codeVoice"},{"text":", combined using the C bitwise OR operator.","type":"text"}],"type":"paragraph"}],"name":"flags"},{"content":[{"inlineContent":[{"text":"The time the event occurred in seconds since system startup.","type":"text"}],"type":"paragraph"}],"name":"time"},{"content":[{"inlineContent":[{"type":"text","text":"An integer that identifies the window device associated with the event, which is associated with the "},{"code":"NSWindow","type":"codeVoice"},{"type":"text","text":" that will receive the event."}],"type":"paragraph"}],"name":"wNum"},{"content":[{"inlineContent":[{"text":"The display graphics context of the event. Pass ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" for this parameter.","type":"text"}],"type":"paragraph"}],"name":"unusedPassNil"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An identifier for the new event. It’s normally taken from a counter for mouse events, which continually increases as the application runs."}]}],"name":"eNum"},{"content":[{"inlineContent":[{"text":"The number of mouse clicks associated with the mouse event.","type":"text"}],"type":"paragraph"}],"name":"cNum"},{"content":[{"type":"paragraph","inlineContent":[{"text":"A value from ","type":"text"},{"code":"0.0","type":"codeVoice"},{"text":" to ","type":"text"},{"code":"1.0","type":"codeVoice"},{"text":" indicating the pressure applied to the input device on a mouse event, used for an appropriate device such as a graphics tablet. For devices that aren’t pressure-sensitive, the value should be either ","type":"text"},{"code":"0.0","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"1.0","type":"codeVoice"},{"text":".","type":"text"}]}],"name":"pressure"}],"kind":"parameters"},"path":"/primaryContentSections/1","op":"replace"},{"value":{"content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"The created "},{"type":"codeVoice","code":"NSEvent"},{"type":"text","text":" instance or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the instance could not be created."}],"type":"paragraph"}],"kind":"content"},"path":"/primaryContentSections/2","op":"replace"},{"value":"eventWithCGEvent:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1init(cgEvent:)/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"eventWithCGEvent:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1init(cgEvent:)/fragments","op":"replace"},{"value":"keyEventWithType:location:modifierFlags:timestamp:windowNumber:context:characters:charactersIgnoringModifiers:isARepeat:keyCode:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1keyEvent(with:location:modifierFlags:timestamp:windowNumber:context:characters:charactersIgnoringModifiers:isARepeat:keyCode:)/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"keyEventWithType:location:modifierFlags:timestamp:windowNumber:context:characters:charactersIgnoringModifiers:isARepeat:keyCode:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1keyEvent(with:location:modifierFlags:timestamp:windowNumber:context:characters:charactersIgnoringModifiers:isARepeat:keyCode:)/fragments","op":"replace"},{"value":"NSEvent","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/title","op":"replace"},{"value":[{"text":"NSEvent","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSEvent"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/navigatorTitle","op":"replace"},{"value":"otherEventWithType:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1otherEvent(with:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:)/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"otherEventWithType:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1otherEvent(with:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:)/fragments","op":"replace"},{"value":"eventWithEventRef:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1init(eventRef:)/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"eventWithEventRef:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1init(eventRef:)/fragments","op":"replace"},{"value":"mouseEventWithType:location:modifierFlags:timestamp:windowNumber:context:eventNumber:clickCount:pressure:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1mouseEvent(with:location:modifierFlags:timestamp:windowNumber:context:eventNumber:clickCount:pressure:)/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"mouseEventWithType:location:modifierFlags:timestamp:windowNumber:context:eventNumber:clickCount:pressure:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1mouseEvent(with:location:modifierFlags:timestamp:windowNumber:context:eventNumber:clickCount:pressure:)/fragments","op":"replace"},{"value":"NSTimeInterval","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSTimeInterval/title","op":"replace"},{"value":"NSEventModifierFlags","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1ModifierFlags-swift.struct/title","op":"replace"},{"value":[{"text":"NSEventModifierFlags","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1ModifierFlags-swift.struct/fragments","op":"replace"},{"value":[{"text":"NSEventModifierFlags","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1ModifierFlags-swift.struct/navigatorTitle","op":"replace"},{"value":"pressure","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1pressure/title","op":"replace"},{"value":[{"kind":"identifier","text":"pressure"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1pressure/fragments","op":"replace"},{"value":"enterExitEventWithType:location:modifierFlags:timestamp:windowNumber:context:eventNumber:trackingNumber:userData:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1enterExitEvent(with:location:modifierFlags:timestamp:windowNumber:context:eventNumber:trackingNumber:userData:)/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"enterExitEventWithType:location:modifierFlags:timestamp:windowNumber:context:eventNumber:trackingNumber:userData:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1enterExitEvent(with:location:modifierFlags:timestamp:windowNumber:context:eventNumber:trackingNumber:userData:)/fragments","op":"replace"},{"value":"NSEventType","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType/title","op":"replace"},{"value":[{"text":"NSEventType","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSEventType"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType/navigatorTitle","op":"replace"},{"value":"clickCount","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1clickCount/title","op":"replace"},{"value":[{"text":"clickCount","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1clickCount/fragments","op":"replace"},{"value":"NSGraphicsContext","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext/title","op":"replace"},{"value":[{"text":"NSGraphicsContext","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSGraphicsContext"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext/navigatorTitle","op":"replace"},{"value":"eventNumber","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1eventNumber/title","op":"replace"},{"value":[{"text":"eventNumber","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1eventNumber/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}