{
  "abstract": [
    {
      "text": "Reports the current mouse position in screen coordinates.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSEvent/mouseLocation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSEvent(cpy)mouseLocation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "mouseLocation"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSPoint",
        "text": "NSPoint"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "mouseLocation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "mouseLocation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "mouseLocation"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSPoint",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSPoint",
              "text": "NSPoint"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The current mouse location in screen coordinates.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method is similar to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/mouseLocationOutsideOfEventStream",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". It returns the location regardless of the current event or pending events. The difference between these methods is that ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/mouseLocationOutsideOfEventStream",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " returns a point in the receiving window’s coordinates, and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/mouseLocation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " returns the same information in screen coordinates.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent": {
      "abstract": [
        {
          "text": "An object that contains information about an input action, such as a mouse click or a key press.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEvent"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEvent"
        }
      ],
      "role": "symbol",
      "title": "NSEvent",
      "type": "topic",
      "url": "/documentation/appkit/nsevent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/associatedEventsMask": {
      "abstract": [
        {
          "text": "The associated events mask of a mouse event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "associatedEventsMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSEventMask",
          "text": "EventTypeMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/associatedEventsMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "associatedEventsMask"
        }
      ],
      "role": "symbol",
      "title": "associatedEventsMask",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/associatedeventsmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/buttonNumber": {
      "abstract": [
        {
          "text": "The button number for a mouse event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buttonNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/buttonNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "buttonNumber"
        }
      ],
      "role": "symbol",
      "title": "buttonNumber",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/buttonnumber"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/clickCount": {
      "abstract": [
        {
          "text": "The number of mouse clicks associated with a mouse-down or mouse-up event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clickCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/clickCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clickCount"
        }
      ],
      "role": "symbol",
      "title": "clickCount",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/clickcount"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/doubleClickInterval": {
      "abstract": [
        {
          "text": "The maximum number of seconds in which a second mouse click must occur for an event to be a double-click event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "doubleClickInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/doubleClickInterval",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "doubleClickInterval"
        }
      ],
      "role": "symbol",
      "title": "doubleClickInterval",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/doubleclickinterval"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/mouseLocation": {
      "abstract": [
        {
          "text": "Reports the current mouse position in screen coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mouseLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/mouseLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mouseLocation"
        }
      ],
      "role": "symbol",
      "title": "mouseLocation",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/mouselocation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/pressedMouseButtons": {
      "abstract": [
        {
          "text": "The indices of the currently pressed mouse buttons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pressedMouseButtons"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/pressedMouseButtons",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pressedMouseButtons"
        }
      ],
      "role": "symbol",
      "title": "pressedMouseButtons",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/pressedmousebuttons"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow": {
      "abstract": [
        {
          "text": "A window that an app displays on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWindow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindow"
        }
      ],
      "role": "symbol",
      "title": "NSWindow",
      "type": "topic",
      "url": "/documentation/appkit/nswindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/mouseLocationOutsideOfEventStream": {
      "abstract": [
        {
          "text": "The current location of the pointer reckoned in the window’s base coordinate system, regardless of the current event being handled or of any events pending.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mouseLocationOutsideOfEventStream"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/mouseLocationOutsideOfEventStream",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mouseLocationOutsideOfEventStream"
        }
      ],
      "role": "symbol",
      "title": "mouseLocationOutsideOfEventStream",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/mouselocationoutsideofeventstream"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSPoint": {
      "abstract": [
        {
          "text": "A point in a Cartesian coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSPoint"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSPoint",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPoint",
      "type": "topic",
      "url": "/documentation/foundation/nspoint"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-mouse-event-information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/pressedMouseButtons",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/doubleClickInterval",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/buttonNumber",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/clickCount",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/associatedEventsMask"
      ],
      "title": "Getting mouse event information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "mouseLocation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mouseLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-mouse-event-information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/pressedMouseButtons",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/doubleClickInterval",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/buttonNumber",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/clickCount",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/associatedEventsMask"
              ],
              "title": "Getting mouse event information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "class"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSPoint",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSPoint",
                    "text": "NSPoint"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "mouseLocation"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title",
          "value": "NSWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1mouseLocationOutsideOfEventStream/title",
          "value": "mouseLocationOutsideOfEventStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1mouseLocationOutsideOfEventStream/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mouseLocationOutsideOfEventStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/title",
          "value": "NSEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1mouseLocation/title",
          "value": "mouseLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1mouseLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mouseLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1associatedEventsMask/title",
          "value": "associatedEventsMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1associatedEventsMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "associatedEventsMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1doubleClickInterval/title",
          "value": "doubleClickInterval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1doubleClickInterval/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "doubleClickInterval"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1pressedMouseButtons/title",
          "value": "pressedMouseButtons"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1pressedMouseButtons/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pressedMouseButtons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1buttonNumber/title",
          "value": "buttonNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1buttonNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "buttonNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1clickCount/title",
          "value": "clickCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1clickCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "clickCount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsevent/mouselocation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsevent/mouselocation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
