{
  "abstract": [
    {
      "text": "The phase of a gesture event, such as a magnify, scroll, or pressure change.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSEvent/phase-swift.property"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSEvent(py)phase",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "phase"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSEvent",
        "text": "NSEvent"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSEventPhase",
        "text": "Phase"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "phase"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "phase"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "phase"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSEvent",
              "text": "NSEvent"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/Phase-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSEventPhase",
              "text": "Phase"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A gesture phase corresponds to a fluid gesture event. As a gesture event occurs, its phase begins with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/Phase-swift.struct/began",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ends with either ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/Phase-swift.struct/ended",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/Phase-swift.struct/cancelled",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". All the gesture events are sent to the view under the cursor when the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/Phase-swift.struct/began",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " occurred.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Technically, a gesture scroll event starts with a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/Phase-swift.struct/began",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " phase and ends with a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/Phase-swift.struct/ended",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". However, when the user puts two fingers down on a trackpad, the trackpad issues ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/Phase-swift.struct/mayBegin",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", followed by ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/Phase-swift.struct/began",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/Phase-swift.struct/cancelled",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/Phase-swift.struct/ended",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/Phase-swift.struct/mayBegin",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " event phase signals that scrolling is about to begin before the gesture has technically started. A Magic Mouse does not issue ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/Phase-swift.struct/mayBegin",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " scroll wheel events.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A pressure event (type ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/pressure",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ") is a fluid gesture. Like the other fluid gesture events, it has a phase that describes the sequence of the pressure gesture stream.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Legacy scroll wheel events (say from a Mighty Mouse) and momentum scroll wheel events both have a phase of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEventPhase/NSEventPhaseNone",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". (Legacy scroll wheel events also have a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/momentumPhase",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEventPhase/NSEventPhaseNone",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".) To learn more about scroll wheel events, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/EventOverview/HandlingTouchEvents/HandlingTouchEvents.html#//apple_ref/doc/uid/10000060i-CH13",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/Phase-swift.struct",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for possible values.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent": {
      "abstract": [
        {
          "text": "An object that contains information about an input action, such as a mouse click or a key press.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEvent"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEvent"
        }
      ],
      "role": "symbol",
      "title": "NSEvent",
      "type": "topic",
      "url": "/documentation/appkit/nsevent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/pressure": {
      "abstract": [
        {
          "text": "An event that reports a change in pressure on a pressure-sensitive device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pressure"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/pressure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypePressure"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.pressure",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/pressure"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/GestureAxis": {
      "abstract": [
        {
          "text": "Constants that specify the direction of travel for a gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GestureAxis"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/GestureAxis",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GestureAxis"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.GestureAxis",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/gestureaxis"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/Phase-swift.struct": {
      "abstract": [
        {
          "text": "Constants that represent the possible phases during an event phase.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Phase"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/Phase-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Phase"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.Phase",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/phase-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/Phase-swift.struct/began": {
      "abstract": [
        {
          "text": "An event phase has begun.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "began"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSEventPhase",
          "text": "Phase"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/Phase-swift.struct/began",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventPhaseBegan"
        }
      ],
      "role": "symbol",
      "title": "began",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/phase-swift.struct/began"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/Phase-swift.struct/cancelled": {
      "abstract": [
        {
          "text": "The system canceled the event phase.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSEventPhase",
          "text": "Phase"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/Phase-swift.struct/cancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventPhaseCancelled"
        }
      ],
      "role": "symbol",
      "title": "cancelled",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/phase-swift.struct/cancelled"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/Phase-swift.struct/ended": {
      "abstract": [
        {
          "text": "The event phase ended.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ended"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSEventPhase",
          "text": "Phase"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/Phase-swift.struct/ended",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventPhaseEnded"
        }
      ],
      "role": "symbol",
      "title": "ended",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/phase-swift.struct/ended"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/Phase-swift.struct/mayBegin": {
      "abstract": [
        {
          "text": "The system event phase may begin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mayBegin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSEventPhase",
          "text": "Phase"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/Phase-swift.struct/mayBegin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventPhaseMayBegin"
        }
      ],
      "role": "symbol",
      "title": "mayBegin",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/phase-swift.struct/maybegin"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/allTouches()": {
      "abstract": [
        {
          "text": "Returns all touch objects associated with the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allTouches"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTouch",
          "text": "NSTouch"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/allTouches()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allTouches"
        }
      ],
      "role": "symbol",
      "title": "allTouches()",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/alltouches()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/coalescedTouches(for:)": {
      "abstract": [
        {
          "text": "Returns all of the touch objects associated with the specified main touch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coalescedTouches"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTouch",
          "text": "NSTouch"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTouch",
          "text": "NSTouch"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/coalescedTouches(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "coalescedTouchesForTouch:"
        }
      ],
      "role": "symbol",
      "title": "coalescedTouches(for:)",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/coalescedtouches(for:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/isMouseCoalescingEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the system coalesces mouse movement events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isMouseCoalescingEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/isMouseCoalescingEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mouseCoalescingEnabled"
        }
      ],
      "role": "symbol",
      "title": "isMouseCoalescingEnabled",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/ismousecoalescingenabled"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/magnification": {
      "abstract": [
        {
          "text": "The amount of change to add to a magnification gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "magnification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/magnification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "magnification"
        }
      ],
      "role": "symbol",
      "title": "magnification",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/magnification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/momentumPhase": {
      "abstract": [
        {
          "text": "The momentum phase for a scroll or flick gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "momentumPhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSEventPhase",
          "text": "Phase"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/momentumPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "momentumPhase"
        }
      ],
      "role": "symbol",
      "title": "momentumPhase",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/momentumphase"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/phase-swift.property": {
      "abstract": [
        {
          "text": "The phase of a gesture event, such as a magnify, scroll, or pressure change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "phase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSEventPhase",
          "text": "Phase"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/phase-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "phase"
        }
      ],
      "role": "symbol",
      "title": "phase",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/phase-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/touches(for:)": {
      "abstract": [
        {
          "text": "Returns the touch objects from the event that belong to the specified view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touches"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTouch",
          "text": "NSTouch"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/touches(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "touchesForView:"
        }
      ],
      "role": "symbol",
      "title": "touches(for:)",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/touches(for:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/touches(matching:in:)": {
      "abstract": [
        {
          "text": "Returns the touch objects associated with the specified phase.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touches"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "matching"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTouch",
          "text": "NSTouch"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTouchPhase",
          "text": "Phase"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTouch",
          "text": "NSTouch"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/touches(matching:in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "touchesMatchingPhase:inView:"
        }
      ],
      "role": "symbol",
      "title": "touches(matching:in:)",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/touches(matching:in:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEventPhase/NSEventPhaseNone": {
      "abstract": [
        {
          "text": "The event is not associated with a phase.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSEventPhaseNone"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEventPhase/NSEventPhaseNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSEventPhaseNone",
      "type": "topic",
      "url": "/documentation/appkit/nseventphase/nseventphasenone"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/EventOverview/HandlingTouchEvents/HandlingTouchEvents.html#//apple_ref/doc/uid/10000060i-CH13": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/EventOverview/HandlingTouchEvents/HandlingTouchEvents.html#//apple_ref/doc/uid/10000060i-CH13",
      "title": "Handling Trackpad Events",
      "titleInlineContent": [
        {
          "text": "Handling Trackpad Events",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/EventOverview/HandlingTouchEvents/HandlingTouchEvents.html#//apple_ref/doc/uid/10000060i-CH13"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-gesture-and-touch-information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/Phase-swift.struct",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/magnification",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/touches(matching:in:)",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/allTouches()",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/touches(for:)",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/coalescedTouches(for:)",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/isMouseCoalescingEnabled",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/GestureAxis"
      ],
      "title": "Getting gesture and touch information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "phase"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "phase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-gesture-and-touch-information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/Phase-swift.struct",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/magnification",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/touches(matching:in:)",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/allTouches()",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/touches(for:)",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/coalescedTouches(for:)",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/isMouseCoalescingEnabled",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/GestureAxis"
              ],
              "title": "Getting gesture and touch information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/Phase-swift.struct",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@NSEventPhase",
                    "text": "NSEventPhase"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "phase"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1touches(for:)/title",
          "value": "touchesForView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1touches(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "touchesForView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1pressure/title",
          "value": "NSEventTypePressure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1pressure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypePressure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1momentumPhase/title",
          "value": "momentumPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1momentumPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "momentumPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1Phase-swift.struct/title",
          "value": "NSEventPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1Phase-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1Phase-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/title",
          "value": "NSEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1Phase-swift.struct~1cancelled/title",
          "value": "NSEventPhaseCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1Phase-swift.struct~1cancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventPhaseCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1Phase-swift.struct~1ended/title",
          "value": "NSEventPhaseEnded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1Phase-swift.struct~1ended/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventPhaseEnded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1Phase-swift.struct~1began/title",
          "value": "NSEventPhaseBegan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1Phase-swift.struct~1began/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventPhaseBegan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1allTouches()/title",
          "value": "allTouches"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1allTouches()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "allTouches"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1isMouseCoalescingEnabled/title",
          "value": "mouseCoalescingEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1isMouseCoalescingEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mouseCoalescingEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1GestureAxis/title",
          "value": "NSEventGestureAxis"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1GestureAxis/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventGestureAxis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1GestureAxis/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventGestureAxis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1touches(matching:in:)/title",
          "value": "touchesMatchingPhase:inView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1touches(matching:in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "touchesMatchingPhase:inView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1Phase-swift.struct~1mayBegin/title",
          "value": "NSEventPhaseMayBegin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1Phase-swift.struct~1mayBegin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventPhaseMayBegin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1magnification/title",
          "value": "magnification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1magnification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "magnification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1phase-swift.property/title",
          "value": "phase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1phase-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "phase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1coalescedTouches(for:)/title",
          "value": "coalescedTouchesForTouch:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1coalescedTouches(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "coalescedTouchesForTouch:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsevent/phase-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsevent/phase-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
