{
  "abstract": [
    {
      "text": "The vendor-assigned serial number of a pointing device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSEvent/pointingDeviceSerialNumber"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSEvent(py)pointingDeviceSerialNumber",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "pointingDeviceSerialNumber"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "pointingDeviceSerialNumber"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "pointingDeviceSerialNumber"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "pointingDeviceSerialNumber"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Devices of different types, such as a puck and a pen, may have the same serial number. This property is valid for mouse events with subtype ",
              "type": "text"
            },
            {
              "code": "NSTabletProximityEventSubtype",
              "type": "codeVoice"
            },
            {
              "text": " or an event of type ",
              "type": "text"
            },
            {
              "code": "NSTabletProximity",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent": {
      "abstract": [
        {
          "text": "An object that contains information about an input action, such as a mouse click or a key press.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEvent"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEvent"
        }
      ],
      "role": "symbol",
      "title": "NSEvent",
      "type": "topic",
      "url": "/documentation/appkit/nsevent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum": {
      "abstract": [
        {
          "text": "The pointing-device types for tablet-proximity events or mouse events with a proximity event subtype.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PointingDeviceType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PointingDeviceType"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.PointingDeviceType",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/pointingdevicetype-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/capabilityMask": {
      "abstract": [
        {
          "text": "A mask that indicates the capabilities of the tablet device that generated this event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "capabilityMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/capabilityMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "capabilityMask"
        }
      ],
      "role": "symbol",
      "title": "capabilityMask",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/capabilitymask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/deviceID": {
      "abstract": [
        {
          "text": "A special identifier the system matches against tablet-pointer and tablet-proximity events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/deviceID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceID"
        }
      ],
      "role": "symbol",
      "title": "deviceID",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/deviceid"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/isEnteringProximity": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether a pointing device is entering or leaving the proximity of its tablet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEnteringProximity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/isEnteringProximity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enteringProximity"
        }
      ],
      "role": "symbol",
      "title": "isEnteringProximity",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/isenteringproximity"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/pointingDeviceID": {
      "abstract": [
        {
          "text": "The index of the pointing device currently in proximity with the tablet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pointingDeviceID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/pointingDeviceID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pointingDeviceID"
        }
      ],
      "role": "symbol",
      "title": "pointingDeviceID",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/pointingdeviceid"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/pointingDeviceSerialNumber": {
      "abstract": [
        {
          "text": "The vendor-assigned serial number of a pointing device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pointingDeviceSerialNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/pointingDeviceSerialNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pointingDeviceSerialNumber"
        }
      ],
      "role": "symbol",
      "title": "pointingDeviceSerialNumber",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/pointingdeviceserialnumber"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/pointingDeviceType-swift.property": {
      "abstract": [
        {
          "text": "The kind of pointing device associated with this event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pointingDeviceType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPointingDeviceType",
          "text": "PointingDeviceType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/pointingDeviceType-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pointingDeviceType"
        }
      ],
      "role": "symbol",
      "title": "pointingDeviceType",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/pointingdevicetype-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/systemTabletID": {
      "abstract": [
        {
          "text": "The index of the tablet device connected to the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemTabletID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/systemTabletID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "systemTabletID"
        }
      ],
      "role": "symbol",
      "title": "systemTabletID",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/systemtabletid"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/tabletID": {
      "abstract": [
        {
          "text": "The USB model identifier of the tablet device associated with this event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabletID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/tabletID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabletID"
        }
      ],
      "role": "symbol",
      "title": "tabletID",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/tabletid"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/uniqueID": {
      "abstract": [
        {
          "text": "The unique identifier of the pointing device that generated this event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uniqueID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/uniqueID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "uniqueID"
        }
      ],
      "role": "symbol",
      "title": "uniqueID",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/uniqueid"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/vendorID": {
      "abstract": [
        {
          "text": "The vendor identifier of the tablet associated with the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vendorID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/vendorID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vendorID"
        }
      ],
      "role": "symbol",
      "title": "vendorID",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/vendorid"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/vendorPointingDeviceType": {
      "abstract": [
        {
          "text": "A coded bit field whose set bits indicate the type of pointing device (within a vendor selection) associated with the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vendorPointingDeviceType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/vendorPointingDeviceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vendorPointingDeviceType"
        }
      ],
      "role": "symbol",
      "title": "vendorPointingDeviceType",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/vendorpointingdevicetype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-tablet-proximity-information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/capabilityMask",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/deviceID",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/isEnteringProximity",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/pointingDeviceID",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/pointingDeviceType-swift.property",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/systemTabletID",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/tabletID",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/uniqueID",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/vendorID",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/vendorPointingDeviceType"
      ],
      "title": "Getting tablet proximity information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "pointingDeviceSerialNumber"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pointingDeviceSerialNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-tablet-proximity-information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/capabilityMask",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/deviceID",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/isEnteringProximity",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/pointingDeviceID",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/pointingDeviceType-swift.property",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/systemTabletID",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/tabletID",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/uniqueID",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/vendorID",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/vendorPointingDeviceType"
              ],
              "title": "Getting tablet proximity information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "pointingDeviceSerialNumber"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1pointingDeviceID/title",
          "value": "pointingDeviceID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1pointingDeviceID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pointingDeviceID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1capabilityMask/title",
          "value": "capabilityMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1capabilityMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "capabilityMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1vendorID/title",
          "value": "vendorID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1vendorID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vendorID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1vendorPointingDeviceType/title",
          "value": "vendorPointingDeviceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1vendorPointingDeviceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vendorPointingDeviceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1tabletID/title",
          "value": "tabletID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1tabletID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tabletID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1pointingDeviceType-swift.property/title",
          "value": "pointingDeviceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1pointingDeviceType-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pointingDeviceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1systemTabletID/title",
          "value": "systemTabletID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1systemTabletID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "systemTabletID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/title",
          "value": "NSEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1isEnteringProximity/title",
          "value": "enteringProximity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1isEnteringProximity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "enteringProximity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1pointingDeviceSerialNumber/title",
          "value": "pointingDeviceSerialNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1pointingDeviceSerialNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pointingDeviceSerialNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1deviceID/title",
          "value": "deviceID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1deviceID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deviceID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PointingDeviceType-swift.enum/title",
          "value": "NSPointingDeviceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PointingDeviceType-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPointingDeviceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PointingDeviceType-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPointingDeviceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1uniqueID/title",
          "value": "uniqueID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1uniqueID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "uniqueID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsevent/pointingdeviceserialnumber"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsevent/pointingdeviceserialnumber"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
