{
  "abstract": [
    {
      "text": "The pointing-device types for tablet-proximity events or mouse events with a proximity event subtype.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@E@NSPointingDeviceType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PointingDeviceType"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PointingDeviceType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSEvent.PointingDeviceType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PointingDeviceType"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/pointingDeviceType-swift.property",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property returns one of these constants.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursorPointingDevice": {
      "abstract": [
        {
          "text": "Represents a cursor (or puck-like) pointing device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCursorPointingDevice"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursorPointingDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCursorPointingDevice",
      "type": "topic",
      "url": "/documentation/appkit/nscursorpointingdevice"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEraserPointingDevice": {
      "abstract": [
        {
          "text": "Represents the eraser end of a stylus-like pointing device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSEraserPointingDevice"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEraserPointingDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSEraserPointingDevice",
      "type": "topic",
      "url": "/documentation/appkit/nseraserpointingdevice"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent": {
      "abstract": [
        {
          "text": "An object that contains information about an input action, such as a mouse click or a key press.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEvent"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEvent"
        }
      ],
      "role": "symbol",
      "title": "NSEvent",
      "type": "topic",
      "url": "/documentation/appkit/nsevent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum": {
      "abstract": [
        {
          "text": "The pointing-device types for tablet-proximity events or mouse events with a proximity event subtype.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PointingDeviceType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PointingDeviceType"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.PointingDeviceType",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/pointingdevicetype-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/cursor": {
      "abstract": [
        {
          "text": "Represents a cursor pointing device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cursor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/cursor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPointingDeviceTypeCursor"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.PointingDeviceType.cursor",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/pointingdevicetype-swift.enum/cursor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/eraser": {
      "abstract": [
        {
          "text": "Represents the eraser end of a stylus-like pointing device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eraser"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/eraser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPointingDeviceTypeEraser"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.PointingDeviceType.eraser",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/pointingdevicetype-swift.enum/eraser"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/pointingdevicetype-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/pen": {
      "abstract": [
        {
          "text": "Represents the tip end of a stylus-like pointing device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pen"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/pen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPointingDeviceTypePen"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.PointingDeviceType.pen",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/pointingdevicetype-swift.enum/pen"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/unknown": {
      "abstract": [
        {
          "text": "Represents an unknown type of pointing device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPointingDeviceTypeUnknown"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.PointingDeviceType.unknown",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/pointingdevicetype-swift.enum/unknown"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/capabilityMask": {
      "abstract": [
        {
          "text": "A mask that indicates the capabilities of the tablet device that generated this event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "capabilityMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/capabilityMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "capabilityMask"
        }
      ],
      "role": "symbol",
      "title": "capabilityMask",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/capabilitymask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/deviceID": {
      "abstract": [
        {
          "text": "A special identifier the system matches against tablet-pointer and tablet-proximity events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/deviceID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceID"
        }
      ],
      "role": "symbol",
      "title": "deviceID",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/deviceid"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/isEnteringProximity": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether a pointing device is entering or leaving the proximity of its tablet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEnteringProximity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/isEnteringProximity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enteringProximity"
        }
      ],
      "role": "symbol",
      "title": "isEnteringProximity",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/isenteringproximity"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/pointingDeviceID": {
      "abstract": [
        {
          "text": "The index of the pointing device currently in proximity with the tablet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pointingDeviceID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/pointingDeviceID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pointingDeviceID"
        }
      ],
      "role": "symbol",
      "title": "pointingDeviceID",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/pointingdeviceid"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/pointingDeviceSerialNumber": {
      "abstract": [
        {
          "text": "The vendor-assigned serial number of a pointing device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pointingDeviceSerialNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/pointingDeviceSerialNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pointingDeviceSerialNumber"
        }
      ],
      "role": "symbol",
      "title": "pointingDeviceSerialNumber",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/pointingdeviceserialnumber"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/pointingDeviceType-swift.property": {
      "abstract": [
        {
          "text": "The kind of pointing device associated with this event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pointingDeviceType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPointingDeviceType",
          "text": "PointingDeviceType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/pointingDeviceType-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pointingDeviceType"
        }
      ],
      "role": "symbol",
      "title": "pointingDeviceType",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/pointingdevicetype-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/systemTabletID": {
      "abstract": [
        {
          "text": "The index of the tablet device connected to the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemTabletID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/systemTabletID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "systemTabletID"
        }
      ],
      "role": "symbol",
      "title": "systemTabletID",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/systemtabletid"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/tabletID": {
      "abstract": [
        {
          "text": "The USB model identifier of the tablet device associated with this event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabletID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/tabletID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabletID"
        }
      ],
      "role": "symbol",
      "title": "tabletID",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/tabletid"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/uniqueID": {
      "abstract": [
        {
          "text": "The unique identifier of the pointing device that generated this event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uniqueID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/uniqueID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "uniqueID"
        }
      ],
      "role": "symbol",
      "title": "uniqueID",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/uniqueid"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/vendorID": {
      "abstract": [
        {
          "text": "The vendor identifier of the tablet associated with the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vendorID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/vendorID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vendorID"
        }
      ],
      "role": "symbol",
      "title": "vendorID",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/vendorid"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/vendorPointingDeviceType": {
      "abstract": [
        {
          "text": "A coded bit field whose set bits indicate the type of pointing device (within a vendor selection) associated with the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vendorPointingDeviceType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/vendorPointingDeviceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vendorPointingDeviceType"
        }
      ],
      "role": "symbol",
      "title": "vendorPointingDeviceType",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/vendorpointingdevicetype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPenPointingDevice": {
      "abstract": [
        {
          "text": "Represents the tip end of a stylus-like pointing device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPenPointingDevice"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPenPointingDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPenPointingDevice",
      "type": "topic",
      "url": "/documentation/appkit/nspenpointingdevice"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnknownPointingDevice": {
      "abstract": [
        {
          "text": "Represents an unknown type of pointing device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnknownPointingDevice"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnknownPointingDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnknownPointingDevice",
      "type": "topic",
      "url": "/documentation/appkit/nsunknownpointingdevice"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-tablet-proximity-information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/capabilityMask",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/deviceID",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/isEnteringProximity",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/pointingDeviceID",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/pointingDeviceSerialNumber",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/pointingDeviceType-swift.property",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/systemTabletID",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/tabletID",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/uniqueID",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/vendorID",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/vendorPointingDeviceType"
      ],
      "title": "Getting tablet proximity information"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/cursor",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/eraser",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/pen",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/unknown"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSPointingDeviceType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPointingDeviceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPointingDeviceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/cursor",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/eraser",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/pen",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/unknown"
              ],
              "title": "Enumeration Cases"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSCursorPointingDevice",
                "doc://com.apple.appkit/documentation/AppKit/NSEraserPointingDevice",
                "doc://com.apple.appkit/documentation/AppKit/NSPenPointingDevice",
                "doc://com.apple.appkit/documentation/AppKit/NSUnknownPointingDevice"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-tablet-proximity-information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/capabilityMask",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/deviceID",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/isEnteringProximity",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/pointingDeviceID",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/pointingDeviceSerialNumber",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/pointingDeviceType-swift.property",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/systemTabletID",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/tabletID",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/uniqueID",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/vendorID",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/vendorPointingDeviceType"
              ],
              "title": "Getting tablet proximity information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSPointingDeviceType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1pointingDeviceID/title",
          "value": "pointingDeviceID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1pointingDeviceID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pointingDeviceID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1capabilityMask/title",
          "value": "capabilityMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1capabilityMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "capabilityMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PointingDeviceType-swift.enum/title",
          "value": "NSPointingDeviceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PointingDeviceType-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPointingDeviceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PointingDeviceType-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPointingDeviceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PointingDeviceType-swift.enum~1cursor/title",
          "value": "NSPointingDeviceTypeCursor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PointingDeviceType-swift.enum~1cursor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPointingDeviceTypeCursor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PointingDeviceType-swift.enum~1eraser/title",
          "value": "NSPointingDeviceTypeEraser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PointingDeviceType-swift.enum~1eraser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPointingDeviceTypeEraser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1vendorPointingDeviceType/title",
          "value": "vendorPointingDeviceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1vendorPointingDeviceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vendorPointingDeviceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1uniqueID/title",
          "value": "uniqueID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1uniqueID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "uniqueID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PointingDeviceType-swift.enum~1pen/title",
          "value": "NSPointingDeviceTypePen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PointingDeviceType-swift.enum~1pen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPointingDeviceTypePen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1isEnteringProximity/title",
          "value": "enteringProximity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1isEnteringProximity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "enteringProximity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PointingDeviceType-swift.enum~1unknown/title",
          "value": "NSPointingDeviceTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PointingDeviceType-swift.enum~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPointingDeviceTypeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1pointingDeviceType-swift.property/title",
          "value": "pointingDeviceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1pointingDeviceType-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pointingDeviceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1systemTabletID/title",
          "value": "systemTabletID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1systemTabletID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "systemTabletID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1vendorID/title",
          "value": "vendorID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1vendorID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vendorID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1deviceID/title",
          "value": "deviceID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1deviceID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deviceID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1tabletID/title",
          "value": "tabletID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1tabletID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tabletID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/title",
          "value": "NSEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1pointingDeviceSerialNumber/title",
          "value": "pointingDeviceSerialNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1pointingDeviceSerialNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pointingDeviceSerialNumber"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsevent/pointingdevicetype-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsevent/pointingdevicetype-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
