{
  "abstract": [
    {
      "text": "These constants describe the behavior and progression of a pressure gesture.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@E@NSPressureBehavior",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PressureBehavior"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PressureBehavior"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSEvent.PressureBehavior"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PressureBehavior"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These constants describe the behavior and progression of a pressure gesture. They allow you to configure how pressure from a pressure-sensitive device, such as the Force Touch trackpad, is interpreted by the system. For example, a drawing or painting app may adjust the behavior of pressure events to focus on variable pressure and prevent force clicks from occurring.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In most cases, a pressure gesture’s behavior goes into effect when the gesture event’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/stage",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property reaches a value of ",
              "type": "text"
            },
            {
              "code": "1",
              "type": "codeVoice"
            },
            {
              "text": " and remains in effect until the gesture event’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/stage",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property reaches a value of ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": ". This behavior corresponds to the behavior of simultaneously generated mouse-up and mouse-down events.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAcceleratorButton": {
      "abstract": [
        {
          "text": "A button that sends an action when the user first clicks the button and continues sending actions until the user releases pressure entirely.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAcceleratorButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAcceleratorButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAcceleratorButton",
      "type": "topic",
      "url": "/documentation/appkit/nsacceleratorbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent": {
      "abstract": [
        {
          "text": "An object that contains information about an input action, such as a mouse click or a key press.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEvent"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEvent"
        }
      ],
      "role": "symbol",
      "title": "NSEvent",
      "type": "topic",
      "url": "/documentation/appkit/nsevent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum": {
      "abstract": [
        {
          "text": "These constants describe the behavior and progression of a pressure gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PressureBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PressureBehavior"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.PressureBehavior",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/pressurebehavior-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/pressurebehavior-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum/primaryAccelerator": {
      "abstract": [
        {
          "text": "A pressure gesture’s behavior begins on left mouse-down events. A maximum of one stage is supported, and a stage transition animation occurs when moving from stage 1 to stage 0. Actuations occur during the mouse-down and mouse-up events when this behavior is configured. This configuration uses specific pressure mappings that are ideal for controlling speed as variable pressure occurs between the mouse-down and mouse-up events. The ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAcceleratorButton",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " class uses this behavior. Note that the pressure gesture operates on a separate event stream from the mouse events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primaryAccelerator"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum/primaryAccelerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPressureBehaviorPrimaryAccelerator"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.PressureBehavior.primaryAccelerator",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/pressurebehavior-swift.enum/primaryaccelerator"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum/primaryClick": {
      "abstract": [
        {
          "text": "A pressure gesture’s behavior begins on left mouse-down events. A maximum of one stage is supported, and a stage transition animation occurs when moving from stage 1 to stage 0. Actuations (haptic feedback the user feels) occur during mouse-down and mouse-up events when this behavior is configured. Note that the pressure gesture operates on a separate event stream from the mouse events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primaryClick"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum/primaryClick",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPressureBehaviorPrimaryClick"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.PressureBehavior.primaryClick",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/pressurebehavior-swift.enum/primaryclick"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum/primaryDeepClick": {
      "abstract": [
        {
          "text": "A pressure gesture’s behavior begins on left mouse-down events. Two stages are supported, and a stage transition animation may occur when moving between stages—from stage 1 to stage 0, stage 1 to stage 2, stage 2 to stage 1, and stage 2 to stage 0. With this behavior type, stage 2 becomes disabled once dragging occurs. When this behavior is configured, actuations occur during the mouse-down and mouse-up events, as well as when force click is activated and released when entering or exiting stage 2. This configuration is ideal for responding to force clicks. Note that the pressure gesture operates on a separate event stream from the mouse events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primaryDeepClick"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum/primaryDeepClick",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPressureBehaviorPrimaryDeepClick"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.PressureBehavior.primaryDeepClick",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/pressurebehavior-swift.enum/primarydeepclick"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum/primaryDeepDrag": {
      "abstract": [
        {
          "text": "A pressure gesture’s behavior begins on left mouse-down events. Two stages are supported, and a stage transition animation may occur when moving between stages—from stage 1 to stage 0, stage 1 to stage 2, stage 2 to stage 1, or stage 2 to stage 0. Actuations occur during the mouse-down and mouse-up events, as well as during the transitions up and down between stage 1 and stage 2, when this behavior is configured. This configuration is ideal for responding to force clicks during drag operations. Note that the pressure gesture operates on a separate event stream from the mouse events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primaryDeepDrag"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum/primaryDeepDrag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPressureBehaviorPrimaryDeepDrag"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.PressureBehavior.primaryDeepDrag",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/pressurebehavior-swift.enum/primarydeepdrag"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum/primaryDefault": {
      "abstract": [
        {
          "text": "This is the default behavior when a pressure gesture’s behavior has not been explicitly configured. In OS X 10.10.3, this behavior defaults to the behavior of ",
          "type": "text"
        },
        {
          "code": "NSPressureBehaviorPrimaryDeepClick",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primaryDefault"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum/primaryDefault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPressureBehaviorPrimaryDefault"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.PressureBehavior.primaryDefault",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/pressurebehavior-swift.enum/primarydefault"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum/primaryGeneric": {
      "abstract": [
        {
          "text": "A pressure gesture’s behavior begins on left mouse-down events. A maximum of one stage is supported, and a stage transition animation occurs when moving from stage 1 to stage 0. Actuations occur during the mouse-down and mouse-up events when this behavior is configured. This configuration is ideal for drawing, painting, and general use. Variable pressure occurs throughout the course of the gesture. Note that the pressure gesture operates on a separate event stream from the mouse events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primaryGeneric"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum/primaryGeneric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPressureBehaviorPrimaryGeneric"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.PressureBehavior.primaryGeneric",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/pressurebehavior-swift.enum/primarygeneric"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum/unknown": {
      "abstract": [
        {
          "text": "A pressure gesture’s behavior is not known, perhaps because the input device does not support pressure gestures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPressureBehaviorUnknown"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.PressureBehavior.unknown",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/pressurebehavior-swift.enum/unknown"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/pressure": {
      "abstract": [
        {
          "text": "A normalized value that indicates the degree of pressure applied to an appropriate input device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pressure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/pressure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pressure"
        }
      ],
      "role": "symbol",
      "title": "pressure",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/pressure"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/pressureBehavior-swift.property": {
      "abstract": [
        {
          "text": "The behavior and progression for a pressure event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pressureBehavior"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPressureBehavior",
          "text": "PressureBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/pressureBehavior-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pressureBehavior"
        }
      ],
      "role": "symbol",
      "title": "pressureBehavior",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/pressurebehavior-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/stage": {
      "abstract": [
        {
          "text": "A value that indicates the stage of a pressure gesture event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/stage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stage"
        }
      ],
      "role": "symbol",
      "title": "stage",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/stage"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/stageTransition": {
      "abstract": [
        {
          "text": "The transition value for the stage of a pressure gesture event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stageTransition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/stageTransition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stageTransition"
        }
      ],
      "role": "symbol",
      "title": "stageTransition",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/stagetransition"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-pressure-information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/pressure",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/stage",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/stageTransition",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/pressureBehavior-swift.property"
      ],
      "title": "Getting pressure information"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum/unknown",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum/primaryDefault",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum/primaryClick",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum/primaryGeneric",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum/primaryAccelerator",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum/primaryDeepClick",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum/primaryDeepDrag"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10.3",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSPressureBehavior"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPressureBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPressureBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum/unknown",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum/primaryDefault",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum/primaryClick",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum/primaryGeneric",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum/primaryAccelerator",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum/primaryDeepClick",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/PressureBehavior-swift.enum/primaryDeepDrag"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-pressure-information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/pressure",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/stage",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/stageTransition",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/pressureBehavior-swift.property"
              ],
              "title": "Getting pressure information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSPressureBehavior"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1stage/title",
          "value": "stage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1stage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "stage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PressureBehavior-swift.enum~1primaryGeneric/title",
          "value": "NSPressureBehaviorPrimaryGeneric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PressureBehavior-swift.enum~1primaryGeneric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPressureBehaviorPrimaryGeneric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1stageTransition/title",
          "value": "stageTransition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1stageTransition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "stageTransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PressureBehavior-swift.enum~1unknown/title",
          "value": "NSPressureBehaviorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PressureBehavior-swift.enum~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPressureBehaviorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PressureBehavior-swift.enum~1primaryDeepClick/title",
          "value": "NSPressureBehaviorPrimaryDeepClick"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PressureBehavior-swift.enum~1primaryDeepClick/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPressureBehaviorPrimaryDeepClick"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PressureBehavior-swift.enum~1primaryClick/title",
          "value": "NSPressureBehaviorPrimaryClick"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PressureBehavior-swift.enum~1primaryClick/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPressureBehaviorPrimaryClick"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1pressureBehavior-swift.property/title",
          "value": "pressureBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1pressureBehavior-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pressureBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PressureBehavior-swift.enum~1primaryDefault/title",
          "value": "NSPressureBehaviorPrimaryDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PressureBehavior-swift.enum~1primaryDefault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPressureBehaviorPrimaryDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/title",
          "value": "NSEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PressureBehavior-swift.enum~1primaryAccelerator/title",
          "value": "NSPressureBehaviorPrimaryAccelerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PressureBehavior-swift.enum~1primaryAccelerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPressureBehaviorPrimaryAccelerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1pressure/title",
          "value": "pressure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1pressure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pressure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PressureBehavior-swift.enum~1primaryDeepDrag/title",
          "value": "NSPressureBehaviorPrimaryDeepDrag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PressureBehavior-swift.enum~1primaryDeepDrag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPressureBehaviorPrimaryDeepDrag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PressureBehavior-swift.enum/title",
          "value": "NSPressureBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PressureBehavior-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPressureBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PressureBehavior-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPressureBehavior"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsevent/pressurebehavior-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsevent/pressurebehavior-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
