{"abstract":[{"type":"text","text":"The event’s subtype."}],"seeAlsoSections":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSEvent/data1","doc://com.apple.appkit/documentation/AppKit/NSEvent/data2","doc://com.apple.appkit/documentation/AppKit/NSEvent/otherEvent(with:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:)"]},{"title":"Getting the event type","anchor":"Getting-the-event-type","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSEvent/type","doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType","doc://com.apple.appkit/documentation/AppKit/NSEvent/EventTypeMask","doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype"],"generated":true}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSEvent"]]},"variants":[{"paths":["/documentation/appkit/nsevent/subtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsevent/subtype"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subtype","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSEvent","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent"},{"text":".","kind":"text"},{"text":"EventSubtype","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSEventSubtype"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["macOS"]}],"kind":"declarations"},{"content":[{"anchor":"Discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Access this property only if the event is a mouse event or if the ","type":"text"},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/type","isActive":true},{"text":" property contains ","type":"text"},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAppKitDefined","isActive":true},{"text":", ","type":"text"},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSystemDefined","isActive":true},{"text":", ","type":"text"},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplicationDefined","isActive":true},{"text":", or ","type":"text"},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPeriodic","isActive":true},{"text":". If you access this property for other types, AppKit raises ","type":"text"},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/foundation/nsexceptionname/1416220-internalinconsistencyexception","isActive":true},{"text":". For information about predefined mouse and tablet subtypes, see ","type":"text"},{"type":"codeVoice","code":"Getting Unicode Values"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPeriodic","isActive":true},{"type":"text","text":" events don’t use this property."}]}],"kind":"content"}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSEvent/subtype","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtype"},{"kind":"text","text":": "},{"text":"NSEvent","preciseIdentifier":"c:objc(cs)NSEvent","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"EventSubtype","preciseIdentifier":"c:@E@NSEventSubtype","kind":"typeIdentifier"}],"platforms":[{"unavailable":false,"deprecated":false,"name":"macOS","beta":false}],"title":"subtype","roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"subtype","kind":"identifier"}],"symbolKind":"property","externalID":"c:objc(cs)NSEvent(py)subtype","modules":[{"name":"AppKit"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.appkit/documentation/AppKit/NSEvent/data2":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/data2","kind":"symbol","navigatorTitle":[{"text":"data2","kind":"identifier"}],"url":"/documentation/appkit/nsevent/data2","type":"topic","abstract":[{"type":"text","text":"Additional data associated with this event."}],"role":"symbol","title":"data2","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"data2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"doc://com.apple.appkit/documentation/AppKit/NSSystemDefined":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSystemDefined","deprecated":true,"kind":"symbol","url":"/documentation/appkit/nssystemdefined","type":"topic","abstract":[{"type":"text","text":"A system-defined event."}],"role":"symbol","title":"NSSystemDefined","fragments":[{"text":"NSSystemDefined","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSEvent/data1":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/data1","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"data1"}],"url":"/documentation/appkit/nsevent/data1","type":"topic","abstract":[{"type":"text","text":"Additional data associated with this event."}],"role":"symbol","title":"data1","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"data1"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType":{"url":"/documentation/appkit/nsevent/eventtype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EventType","kind":"identifier"}],"title":"NSEvent.EventType","kind":"symbol","abstract":[{"text":"Constants for the types of events that responder objects can handle.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType","role":"symbol","type":"topic","navigatorTitle":[{"text":"EventType","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSEvent":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSEvent"}],"role":"symbol","type":"topic","title":"NSEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSEvent"}],"abstract":[{"type":"text","text":"An object that contains information about an input action, such as a mouse click or a key press."}],"url":"/documentation/appkit/nsevent"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSAppKitDefined":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAppKitDefined","deprecated":true,"kind":"symbol","url":"/documentation/appkit/nsappkitdefined","type":"topic","abstract":[{"type":"text","text":"An AppKit-defined event."}],"role":"symbol","title":"NSAppKitDefined","fragments":[{"text":"NSAppKitDefined","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSEvent/otherEvent(with:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/otherEvent(with:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"otherEventWithType:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:"}],"url":"/documentation/appkit/nsevent/otherevent(with:location:modifierflags:timestamp:windownumber:context:subtype:data1:data2:)","type":"topic","abstract":[{"type":"text","text":"Creates and returns a new event object that describes a custom event."}],"role":"symbol","title":"otherEvent(with:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"otherEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSEventType","text":"EventType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint","text":"NSPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"modifierFlags"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSEventModifierFlags","text":"ModifierFlags"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"windowNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSGraphicsContext","text":"NSGraphicsContext"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"subtype"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int16V","text":"Int16"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent"},{"kind":"text","text":"?"}]},"doc://com.apple.appkit/documentation/AppKit/NSEvent/EventTypeMask":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"EventTypeMask","kind":"identifier"}],"url":"/documentation/appkit/nsevent/eventtypemask","title":"NSEvent.EventTypeMask","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/EventTypeMask","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EventTypeMask","kind":"identifier"}],"abstract":[{"type":"text","text":"Constants that you use to filter out specific event types from the stream of incoming events."}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSApplicationDefined":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplicationDefined","deprecated":true,"kind":"symbol","url":"/documentation/appkit/nsapplicationdefined","type":"topic","abstract":[{"type":"text","text":"An app-defined event."}],"role":"symbol","title":"NSApplicationDefined","fragments":[{"text":"NSApplicationDefined","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSEvent/subtype":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/subtype","kind":"symbol","navigatorTitle":[{"text":"subtype","kind":"identifier"}],"url":"/documentation/appkit/nsevent/subtype","type":"topic","abstract":[{"type":"text","text":"The event’s subtype."}],"role":"symbol","title":"subtype","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtype"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSEvent","kind":"typeIdentifier","text":"NSEvent"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSEventSubtype","text":"EventSubtype","kind":"typeIdentifier"}]},"doc://com.apple.documentation/documentation/foundation/nsexceptionname/1416220-internalinconsistencyexception":{"title":"internalInconsistencyException","fragments":[{"kind":"text","text":"static let "},{"kind":"identifier","text":"internalInconsistencyException"},{"kind":"text","text":": NSExceptionName"}],"kind":"symbol","abstract":[{"type":"text","text":"Name of an exception that occurs when an internal assertion fails and implies an unexpected condition within the called code."}],"type":"topic","role":"symbol","url":"/documentation/foundation/nsexceptionname/1416220-internalinconsistencyexception","identifier":"doc://com.apple.documentation/documentation/foundation/nsexceptionname/1416220-internalinconsistencyexception"},"doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype":{"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype","title":"NSEvent.EventSubtype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EventSubtype"}],"abstract":[{"type":"text","text":"Subtypes for various types of events."}],"navigatorTitle":[{"kind":"identifier","text":"EventSubtype"}],"kind":"symbol","url":"/documentation/appkit/nsevent/eventsubtype","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSPeriodic":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSPeriodic","deprecated":true,"kind":"symbol","url":"/documentation/appkit/nsperiodic","type":"topic","abstract":[{"type":"text","text":"A periodic event."}],"role":"symbol","title":"NSPeriodic","fragments":[{"text":"NSPeriodic","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSEvent/type":{"title":"type","role":"symbol","type":"topic","url":"/documentation/appkit/nsevent/type","abstract":[{"text":"The event’s type.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"type","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSEvent","preciseIdentifier":"c:objc(cs)NSEvent","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"EventType","preciseIdentifier":"c:@E@NSEventType","kind":"typeIdentifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/type"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"unavailable":false,"deprecated":false,"name":"macOS","beta":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"subtype"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"subtype","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSEvent"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSEvent/data1","doc://com.apple.appkit/documentation/AppKit/NSEvent/data2","doc://com.apple.appkit/documentation/AppKit/NSEvent/otherEvent(with:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:)"],"title":"Related Documentation","anchor":"Related-Documentation"},{"anchor":"Getting-the-event-type","title":"Getting the event type","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSEvent/type","doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType","doc://com.apple.appkit/documentation/AppKit/NSEvent/EventTypeMask","doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype"],"generated":true}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype","text":"NSEventSubtype","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSEventSubtype"},{"text":" ","kind":"text"},{"text":"subtype","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1data2/title","value":"data2","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1data2/fragments","value":[{"kind":"identifier","text":"data2"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1data1/title","value":"data1","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1data1/fragments","value":[{"kind":"identifier","text":"data1"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType/title","value":"NSEventType","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType/fragments","value":[{"text":"NSEventType","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType/navigatorTitle","value":[{"text":"NSEventType","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/title","value":"NSEvent","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/fragments","value":[{"kind":"identifier","text":"NSEvent"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/navigatorTitle","value":[{"text":"NSEvent","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1otherEvent(with:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:)/title","value":"otherEventWithType:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1otherEvent(with:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"otherEventWithType:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventTypeMask/title","value":"NSEventMask","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventTypeMask/fragments","value":[{"kind":"identifier","text":"NSEventMask"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventTypeMask/navigatorTitle","value":[{"text":"NSEventMask","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1subtype/title","value":"subtype","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1subtype/fragments","value":[{"text":"subtype","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsexceptionname~11416220-internalinconsistencyexception/title","value":"NSInternalInconsistencyException","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype/title","value":"NSEventSubtype","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype/fragments","value":[{"text":"NSEventSubtype","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype/navigatorTitle","value":[{"kind":"identifier","text":"NSEventSubtype"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1type/title","value":"type","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1type/fragments","value":[{"text":"type","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}