{
  "abstract": [
    {
      "text": "Color formats that can be specified under the ",
      "type": "text"
    },
    {
      "code": "kEAGLDrawablePropertyColorFormat",
      "type": "codeVoice"
    },
    {
      "text": " key.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.opengles/documentation/OpenGLES",
        "doc://com.apple.opengles/documentation/OpenGLES/EAGLDrawable"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.opengles/documentation/OpenGLES/color-formats"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "OpenGL ES"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Color Formats"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.opengles/documentation/OpenGLES": {
      "abstract": [
        {
          "text": "Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opengles/documentation/OpenGLES",
      "kind": "symbol",
      "role": "collection",
      "title": "OpenGL ES",
      "type": "topic",
      "url": "/documentation/opengles"
    },
    "doc://com.apple.opengles/documentation/OpenGLES/EAGLDrawable": {
      "abstract": [
        {
          "text": "iOS objects that implement the ",
          "type": "text"
        },
        {
          "code": "EAGLDrawable",
          "type": "codeVoice"
        },
        {
          "text": " protocol can be used as a rendering surface and displayed to the screen by an ",
          "type": "text"
        },
        {
          "code": "EAGLContext",
          "type": "codeVoice"
        },
        {
          "text": " object. In iOS 2.0, this protocol is implemented only by the ",
          "type": "text"
        },
        {
          "code": "CAEAGLLayer",
          "type": "codeVoice"
        },
        {
          "text": " class, but in the future other classes may choose to implement the protocol. The ",
          "type": "text"
        },
        {
          "code": "EAGLDrawable",
          "type": "codeVoice"
        },
        {
          "text": " protocol is not intended to be implemented by objects outside of the iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EAGLDrawable"
        }
      ],
      "identifier": "doc://com.apple.opengles/documentation/OpenGLES/EAGLDrawable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EAGLDrawable"
        }
      ],
      "role": "symbol",
      "title": "EAGLDrawable",
      "type": "topic",
      "url": "/documentation/opengles/eagldrawable"
    },
    "doc://com.apple.opengles/documentation/OpenGLES/kEAGLColorFormatRGB565": {
      "abstract": [
        {
          "text": "Specifies a 16-bit RGB format that corresponds to the OpenGL ES ",
          "type": "text"
        },
        {
          "code": "GL_RGB565",
          "type": "codeVoice"
        },
        {
          "text": " format.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kEAGLColorFormatRGB565"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.opengles/documentation/OpenGLES/kEAGLColorFormatRGB565",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kEAGLColorFormatRGB565"
        }
      ],
      "role": "symbol",
      "title": "kEAGLColorFormatRGB565",
      "type": "topic",
      "url": "/documentation/opengles/keaglcolorformatrgb565"
    },
    "doc://com.apple.opengles/documentation/OpenGLES/kEAGLColorFormatRGBA8": {
      "abstract": [
        {
          "text": "Specifies a 32-bit RGBA format that corresponds to the OpenGL ES ",
          "type": "text"
        },
        {
          "code": "GL_RGBA8888",
          "type": "codeVoice"
        },
        {
          "text": " format.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kEAGLColorFormatRGBA8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.opengles/documentation/OpenGLES/kEAGLColorFormatRGBA8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kEAGLColorFormatRGBA8"
        }
      ],
      "role": "symbol",
      "title": "kEAGLColorFormatRGBA8",
      "type": "topic",
      "url": "/documentation/opengles/keaglcolorformatrgba8"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.opengles/documentation/OpenGLES/kEAGLColorFormatRGB565",
        "doc://com.apple.opengles/documentation/OpenGLES/kEAGLColorFormatRGBA8"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.opengles/documentation/OpenGLES/kEAGLColorFormatRGB565",
                "doc://com.apple.opengles/documentation/OpenGLES/kEAGLColorFormatRGBA8"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1kEAGLColorFormatRGBA8/title",
          "value": "kEAGLColorFormatRGBA8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1kEAGLColorFormatRGBA8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kEAGLColorFormatRGBA8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1kEAGLColorFormatRGB565/title",
          "value": "kEAGLColorFormatRGB565"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1kEAGLColorFormatRGB565/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kEAGLColorFormatRGB565"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1EAGLDrawable/title",
          "value": "EAGLDrawable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1EAGLDrawable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EAGLDrawable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1EAGLDrawable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EAGLDrawable"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/opengles/color-formats"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/opengles/color-formats"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
