{
  "abstract": [
    {
      "text": "Keys to specify in the ",
      "type": "text"
    },
    {
      "code": "drawableProperties",
      "type": "codeVoice"
    },
    {
      "text": " dictionary.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.opengles/documentation/OpenGLES",
        "doc://com.apple.opengles/documentation/OpenGLES/EAGLDrawable"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.opengles/documentation/OpenGLES/drawable-property-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "OpenGL ES"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Drawable Property Keys"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.opengles/documentation/OpenGLES": {
      "abstract": [
        {
          "text": "Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opengles/documentation/OpenGLES",
      "kind": "symbol",
      "role": "collection",
      "title": "OpenGL ES",
      "type": "topic",
      "url": "/documentation/opengles"
    },
    "doc://com.apple.opengles/documentation/OpenGLES/EAGLDrawable": {
      "abstract": [
        {
          "text": "iOS objects that implement the ",
          "type": "text"
        },
        {
          "code": "EAGLDrawable",
          "type": "codeVoice"
        },
        {
          "text": " protocol can be used as a rendering surface and displayed to the screen by an ",
          "type": "text"
        },
        {
          "code": "EAGLContext",
          "type": "codeVoice"
        },
        {
          "text": " object. In iOS 2.0, this protocol is implemented only by the ",
          "type": "text"
        },
        {
          "code": "CAEAGLLayer",
          "type": "codeVoice"
        },
        {
          "text": " class, but in the future other classes may choose to implement the protocol. The ",
          "type": "text"
        },
        {
          "code": "EAGLDrawable",
          "type": "codeVoice"
        },
        {
          "text": " protocol is not intended to be implemented by objects outside of the iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EAGLDrawable"
        }
      ],
      "identifier": "doc://com.apple.opengles/documentation/OpenGLES/EAGLDrawable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EAGLDrawable"
        }
      ],
      "role": "symbol",
      "title": "EAGLDrawable",
      "type": "topic",
      "url": "/documentation/opengles/eagldrawable"
    },
    "doc://com.apple.opengles/documentation/OpenGLES/kEAGLDrawablePropertyColorFormat": {
      "abstract": [
        {
          "text": "The key specifying the internal color buffer format for the drawable surface. The value for this key is an ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": " object that specifies a specific color buffer format. This color buffer format is used by the ",
          "type": "text"
        },
        {
          "code": "EAGLContext",
          "type": "codeVoice"
        },
        {
          "text": " object to create the storage for a renderbuffer. The default value is ",
          "type": "text"
        },
        {
          "code": "kEAGLColorFormatRGBA8",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kEAGLDrawablePropertyColorFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.opengles/documentation/OpenGLES/kEAGLDrawablePropertyColorFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kEAGLDrawablePropertyColorFormat"
        }
      ],
      "role": "symbol",
      "title": "kEAGLDrawablePropertyColorFormat",
      "type": "topic",
      "url": "/documentation/opengles/keagldrawablepropertycolorformat"
    },
    "doc://com.apple.opengles/documentation/OpenGLES/kEAGLDrawablePropertyRetainedBacking": {
      "abstract": [
        {
          "text": "The key specifying whether the drawable surface retains its contents after displaying them.  The value for this key is an ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a ",
          "type": "text"
        },
        {
          "code": "BOOL",
          "type": "codeVoice"
        },
        {
          "text": " data type. If ",
          "type": "text"
        },
        {
          "code": "false",
          "type": "codeVoice"
        },
        {
          "text": ", you may not rely on the contents being the same after the contents are displayed.  If ",
          "type": "text"
        },
        {
          "code": "true",
          "type": "codeVoice"
        },
        {
          "text": ", then the contents will not change after being displayed. Setting the value to ",
          "type": "text"
        },
        {
          "code": "true",
          "type": "codeVoice"
        },
        {
          "text": " is recommended only when you need the content to remain unchanged, as using it can result in both reduced performance and additional memory usage. The default value is ",
          "type": "text"
        },
        {
          "code": "false",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kEAGLDrawablePropertyRetainedBacking"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.opengles/documentation/OpenGLES/kEAGLDrawablePropertyRetainedBacking",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kEAGLDrawablePropertyRetainedBacking"
        }
      ],
      "role": "symbol",
      "title": "kEAGLDrawablePropertyRetainedBacking",
      "type": "topic",
      "url": "/documentation/opengles/keagldrawablepropertyretainedbacking"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.opengles/documentation/OpenGLES/kEAGLDrawablePropertyColorFormat",
        "doc://com.apple.opengles/documentation/OpenGLES/kEAGLDrawablePropertyRetainedBacking"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.opengles/documentation/OpenGLES/kEAGLDrawablePropertyColorFormat",
                "doc://com.apple.opengles/documentation/OpenGLES/kEAGLDrawablePropertyRetainedBacking"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1kEAGLDrawablePropertyColorFormat/title",
          "value": "kEAGLDrawablePropertyColorFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1kEAGLDrawablePropertyColorFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kEAGLDrawablePropertyColorFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1kEAGLDrawablePropertyRetainedBacking/title",
          "value": "kEAGLDrawablePropertyRetainedBacking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1kEAGLDrawablePropertyRetainedBacking/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kEAGLDrawablePropertyRetainedBacking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1EAGLDrawable/title",
          "value": "EAGLDrawable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1EAGLDrawable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EAGLDrawable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1EAGLDrawable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EAGLDrawable"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/opengles/drawable-property-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/opengles/drawable-property-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
