{
  "abstract": [
    {
      "text": "iOS objects that implement the ",
      "type": "text"
    },
    {
      "code": "EAGLDrawable",
      "type": "codeVoice"
    },
    {
      "text": " protocol can be used as a rendering surface and displayed to the screen by an ",
      "type": "text"
    },
    {
      "code": "EAGLContext",
      "type": "codeVoice"
    },
    {
      "text": " object. In iOS 2.0, this protocol is implemented only by the ",
      "type": "text"
    },
    {
      "code": "CAEAGLLayer",
      "type": "codeVoice"
    },
    {
      "text": " class, but in the future other classes may choose to implement the protocol. The ",
      "type": "text"
    },
    {
      "code": "EAGLDrawable",
      "type": "codeVoice"
    },
    {
      "text": " protocol is not intended to be implemented by objects outside of the iOS.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "OpenGLES API deprecated. (Define GLES_SILENCE_DEPRECATION to silence these warnings)",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.opengles/documentation/OpenGLES"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.opengles/documentation/OpenGLES/EAGLDrawable"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)EAGLDrawable",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "EAGLDrawable"
      }
    ],
    "modules": [
      {
        "name": "OpenGL ES"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "EAGLDrawable"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "2.0",
        "message": "OpenGLES API deprecated. (Define GLES_SILENCE_DEPRECATION to silence these warnings)",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "2.0",
        "message": "OpenGLES API deprecated. (Define GLES_SILENCE_DEPRECATION to silence these warnings)",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "2.0",
        "message": "OpenGLES API deprecated. (Define GLES_SILENCE_DEPRECATION to silence these warnings)",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "9.0",
        "message": "OpenGLES API deprecated. (Define GLES_SILENCE_DEPRECATION to silence these warnings)",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "EAGLDrawable"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "EAGLDrawable"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.opengles/documentation/OpenGLES": {
      "abstract": [
        {
          "text": "Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opengles/documentation/OpenGLES",
      "kind": "symbol",
      "role": "collection",
      "title": "OpenGL ES",
      "type": "topic",
      "url": "/documentation/opengles"
    },
    "doc://com.apple.opengles/documentation/OpenGLES/EAGLDrawable": {
      "abstract": [
        {
          "text": "iOS objects that implement the ",
          "type": "text"
        },
        {
          "code": "EAGLDrawable",
          "type": "codeVoice"
        },
        {
          "text": " protocol can be used as a rendering surface and displayed to the screen by an ",
          "type": "text"
        },
        {
          "code": "EAGLContext",
          "type": "codeVoice"
        },
        {
          "text": " object. In iOS 2.0, this protocol is implemented only by the ",
          "type": "text"
        },
        {
          "code": "CAEAGLLayer",
          "type": "codeVoice"
        },
        {
          "text": " class, but in the future other classes may choose to implement the protocol. The ",
          "type": "text"
        },
        {
          "code": "EAGLDrawable",
          "type": "codeVoice"
        },
        {
          "text": " protocol is not intended to be implemented by objects outside of the iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EAGLDrawable"
        }
      ],
      "identifier": "doc://com.apple.opengles/documentation/OpenGLES/EAGLDrawable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EAGLDrawable"
        }
      ],
      "role": "symbol",
      "title": "EAGLDrawable",
      "type": "topic",
      "url": "/documentation/opengles/eagldrawable"
    },
    "doc://com.apple.opengles/documentation/OpenGLES/EAGLDrawable/drawableProperties": {
      "abstract": [
        {
          "text": "A dictionary of values that specify the desired characteristics of the drawable surface.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawableProperties"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.opengles/documentation/OpenGLES/EAGLDrawable/drawableProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawableProperties"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "drawableProperties",
      "type": "topic",
      "url": "/documentation/opengles/eagldrawable/drawableproperties"
    },
    "doc://com.apple.opengles/documentation/OpenGLES/color-formats": {
      "abstract": [
        {
          "text": "Color formats that can be specified under the ",
          "type": "text"
        },
        {
          "code": "kEAGLDrawablePropertyColorFormat",
          "type": "codeVoice"
        },
        {
          "text": " key.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opengles/documentation/OpenGLES/color-formats",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Color Formats",
      "type": "topic",
      "url": "/documentation/opengles/color-formats"
    },
    "doc://com.apple.opengles/documentation/OpenGLES/drawable-property-keys": {
      "abstract": [
        {
          "text": "Keys to specify in the ",
          "type": "text"
        },
        {
          "code": "drawableProperties",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opengles/documentation/OpenGLES/drawable-property-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Drawable Property Keys",
      "type": "topic",
      "url": "/documentation/opengles/drawable-property-keys"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Drawable-Properties",
      "identifiers": [
        "doc://com.apple.opengles/documentation/OpenGLES/EAGLDrawable/drawableProperties"
      ],
      "title": "Drawable Properties"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.opengles/documentation/OpenGLES/drawable-property-keys",
        "doc://com.apple.opengles/documentation/OpenGLES/color-formats"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "12.0",
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "12.0",
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "12.0",
              "introducedAt": "2.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "12.0",
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "EAGLDrawable"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EAGLDrawable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EAGLDrawable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.opengles/documentation/OpenGLES"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Drawable-Properties",
              "identifiers": [
                "doc://com.apple.opengles/documentation/OpenGLES/EAGLDrawable/drawableProperties"
              ],
              "title": "Drawable Properties"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.opengles/documentation/OpenGLES/drawable-property-keys",
                "doc://com.apple.opengles/documentation/OpenGLES/color-formats"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "EAGLDrawable"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "OpenGLES API deprecated. (Define GLES_SILENCE_DEPRECATION to silence these warnings)",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1EAGLDrawable/title",
          "value": "EAGLDrawable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1EAGLDrawable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EAGLDrawable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1EAGLDrawable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EAGLDrawable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1EAGLDrawable~1drawableProperties/title",
          "value": "drawableProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1EAGLDrawable~1drawableProperties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "drawableProperties"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/opengles/eagldrawable"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/opengles/eagldrawable"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
