{"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"GL_ACTIVE_ATTRIBUTE_MAX_LENGTH","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"}],"title":"GL_ACTIVE_ATTRIBUTE_MAX_LENGTH","modules":[{"name":"OpenGL ES"}],"symbolKind":"var","navigatorTitle":[{"text":"GL_ACTIVE_ATTRIBUTE_MAX_LENGTH","kind":"identifier"}],"platforms":[{"deprecated":false,"name":"iOS","introducedAt":"2.0","beta":false,"unavailable":false},{"deprecated":false,"name":"iPadOS","introducedAt":"2.0","beta":false,"unavailable":false},{"deprecated":false,"name":"Mac Catalyst","introducedAt":"2.0","beta":false,"unavailable":false},{"deprecated":false,"name":"tvOS","introducedAt":"9.0","beta":false,"unavailable":false},{"introducedAt":"1.0","name":"visionOS","deprecated":false,"unavailable":false,"beta":false}],"externalID":"c:@macro@GL_ACTIVE_ATTRIBUTE_MAX_LENGTH","roleHeading":"Global Variable","role":"symbol"},"identifier":{"url":"doc://com.apple.opengles/documentation/OpenGLES/GL_ACTIVE_ATTRIBUTE_MAX_LENGTH","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_ACTIVE_ATTRIBUTE_MAX_LENGTH","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","preciseIdentifier":"s:s5Int32V"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/opengles/gl_active_attribute_max_length"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/opengles/gl_active_attribute_max_length"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.opengles/documentation/OpenGLES":{"type":"topic","kind":"symbol","url":"/documentation/opengles","identifier":"doc://com.apple.opengles/documentation/OpenGLES","title":"OpenGL ES","abstract":[{"type":"text","text":"Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL."}],"role":"collection"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"role":"symbol","url":"/documentation/Swift/Int32","abstract":[{"type":"text","text":"A 32-bit signed integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"title":"Int32","type":"topic"},"doc://com.apple.opengles/documentation/OpenGLES/GL_ACTIVE_ATTRIBUTE_MAX_LENGTH":{"kind":"symbol","title":"GL_ACTIVE_ATTRIBUTE_MAX_LENGTH","type":"topic","url":"/documentation/opengles/gl_active_attribute_max_length","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_ACTIVE_ATTRIBUTE_MAX_LENGTH","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"navigatorTitle":[{"kind":"identifier","text":"GL_ACTIVE_ATTRIBUTE_MAX_LENGTH"}],"identifier":"doc://com.apple.opengles/documentation/OpenGLES/GL_ACTIVE_ATTRIBUTE_MAX_LENGTH","role":"symbol","abstract":[]},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"deprecated":false,"name":"iOS","introducedAt":"2.0","unavailable":false,"beta":false},{"introducedAt":"2.0","beta":false,"deprecated":false,"name":"iPadOS","unavailable":false},{"introducedAt":"2.0","beta":false,"deprecated":false,"name":"Mac Catalyst","unavailable":false},{"introducedAt":"9.0","beta":false,"deprecated":false,"name":"tvOS","unavailable":false},{"introducedAt":"1.0","name":"visionOS","unavailable":false,"deprecated":false,"beta":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Macro","path":"/metadata/roleHeading","op":"replace"},{"value":"GL_ACTIVE_ATTRIBUTE_MAX_LENGTH","path":"/metadata/title","op":"replace"},{"path":"/metadata/symbolKind","value":"macro","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"GL_ACTIVE_ATTRIBUTE_MAX_LENGTH","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":null,"op":"add"},{"path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"#define"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_ACTIVE_ATTRIBUTE_MAX_LENGTH"}],"languages":["occ"],"platforms":["iOS","iPadOS","tvOS","visionOS"]}],"kind":"declarations"},"op":"replace"},{"path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_ACTIVE_ATTRIBUTE_MAX_LENGTH/title","op":"replace","value":"GL_ACTIVE_ATTRIBUTE_MAX_LENGTH"},{"path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_ACTIVE_ATTRIBUTE_MAX_LENGTH/fragments","op":"replace","value":[{"kind":"identifier","text":"GL_ACTIVE_ATTRIBUTE_MAX_LENGTH"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}