{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_ALIASED_POINT_SIZE_RANGE"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS","iPadOS","tvOS","visionOS"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"variants":[{"paths":["/documentation/opengles/gl_aliased_point_size_range"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/opengles/gl_aliased_point_size_range"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_ALIASED_POINT_SIZE_RANGE"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"modules":[{"name":"OpenGL ES"}],"platforms":[{"deprecated":false,"name":"iOS","unavailable":false,"beta":false,"introducedAt":"2.0"},{"deprecated":false,"name":"iPadOS","unavailable":false,"beta":false,"introducedAt":"2.0"},{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false,"introducedAt":"2.0"},{"introducedAt":"9.0","name":"tvOS","unavailable":false,"deprecated":false,"beta":false},{"introducedAt":"1.0","name":"visionOS","unavailable":false,"deprecated":false,"beta":false}],"title":"GL_ALIASED_POINT_SIZE_RANGE","externalID":"c:@macro@GL_ALIASED_POINT_SIZE_RANGE","role":"symbol","symbolKind":"var","navigatorTitle":[{"text":"GL_ALIASED_POINT_SIZE_RANGE","kind":"identifier"}],"roleHeading":"Global Variable"},"identifier":{"url":"doc://com.apple.opengles/documentation/OpenGLES/GL_ALIASED_POINT_SIZE_RANGE","interfaceLanguage":"swift"},"references":{"doc://com.externally.resolved.symbol/s:s5Int32V":{"role":"symbol","url":"/documentation/Swift/Int32","abstract":[{"type":"text","text":"A 32-bit signed integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"title":"Int32","type":"topic"},"doc://com.apple.opengles/documentation/OpenGLES/GL_ALIASED_POINT_SIZE_RANGE":{"kind":"symbol","role":"symbol","title":"GL_ALIASED_POINT_SIZE_RANGE","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_ALIASED_POINT_SIZE_RANGE","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"navigatorTitle":[{"text":"GL_ALIASED_POINT_SIZE_RANGE","kind":"identifier"}],"url":"/documentation/opengles/gl_aliased_point_size_range","abstract":[],"identifier":"doc://com.apple.opengles/documentation/OpenGLES/GL_ALIASED_POINT_SIZE_RANGE","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview"},"doc://com.apple.opengles/documentation/OpenGLES":{"type":"topic","kind":"symbol","url":"/documentation/opengles","identifier":"doc://com.apple.opengles/documentation/OpenGLES","title":"OpenGL ES","abstract":[{"type":"text","text":"Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL."}],"role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"deprecated":false,"name":"iOS","unavailable":false,"beta":false,"introducedAt":"2.0"},{"deprecated":false,"name":"iPadOS","unavailable":false,"beta":false,"introducedAt":"2.0"},{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false,"introducedAt":"2.0"},{"deprecated":false,"name":"tvOS","unavailable":false,"beta":false,"introducedAt":"9.0"},{"introducedAt":"1.0","name":"visionOS","unavailable":false,"deprecated":false,"beta":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Macro"},{"op":"replace","path":"/metadata/title","value":"GL_ALIASED_POINT_SIZE_RANGE"},{"op":"replace","path":"/metadata/symbolKind","value":"macro"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"GL_ALIASED_POINT_SIZE_RANGE"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"add","path":"/seeAlsoSections","value":null},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"#define","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_ALIASED_POINT_SIZE_RANGE","kind":"identifier"}],"platforms":["iOS","iPadOS","tvOS","visionOS"],"languages":["occ"]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_ALIASED_POINT_SIZE_RANGE/title","value":"GL_ALIASED_POINT_SIZE_RANGE"},{"op":"replace","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_ALIASED_POINT_SIZE_RANGE/fragments","value":[{"text":"GL_ALIASED_POINT_SIZE_RANGE","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}