{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.opengles/documentation/OpenGLES/GL_BOOL"},"metadata":{"role":"symbol","roleHeading":"Global Variable","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_BOOL","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"modules":[{"name":"OpenGL ES"}],"platforms":[{"beta":false,"name":"iOS","introducedAt":"2.0","deprecated":false,"unavailable":false},{"beta":false,"name":"iPadOS","introducedAt":"2.0","deprecated":false,"unavailable":false},{"beta":false,"name":"Mac Catalyst","introducedAt":"2.0","deprecated":false,"unavailable":false},{"beta":false,"name":"tvOS","introducedAt":"9.0","deprecated":false,"unavailable":false},{"beta":false,"name":"visionOS","introducedAt":"1.0","deprecated":false,"unavailable":false}],"symbolKind":"var","title":"GL_BOOL","navigatorTitle":[{"text":"GL_BOOL","kind":"identifier"}],"externalID":"c:@macro@GL_BOOL"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","tvOS","visionOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_BOOL","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"sections":[],"variants":[{"paths":["/documentation/opengles/gl_bool"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/opengles/gl_bool"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"kind":"symbol","references":{"doc://com.apple.opengles/documentation/OpenGLES/GL_BOOL":{"navigatorTitle":[{"text":"GL_BOOL","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_BOOL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"type":"topic","role":"symbol","identifier":"doc://com.apple.opengles/documentation/OpenGLES/GL_BOOL","title":"GL_BOOL","abstract":[],"url":"/documentation/opengles/gl_bool","kind":"symbol"},"doc://com.apple.opengles/documentation/OpenGLES":{"type":"topic","kind":"symbol","url":"/documentation/opengles","identifier":"doc://com.apple.opengles/documentation/OpenGLES","title":"OpenGL ES","abstract":[{"type":"text","text":"Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL."}],"role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"role":"symbol","url":"/documentation/Swift/Int32","abstract":[{"type":"text","text":"A 32-bit signed integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"title":"Int32","type":"topic"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"beta":false,"unavailable":false,"introducedAt":"2.0","name":"iOS","deprecated":false},{"beta":false,"name":"iPadOS","introducedAt":"2.0","deprecated":false,"unavailable":false},{"beta":false,"name":"Mac Catalyst","introducedAt":"2.0","deprecated":false,"unavailable":false},{"beta":false,"name":"tvOS","introducedAt":"9.0","deprecated":false,"unavailable":false},{"beta":false,"name":"visionOS","introducedAt":"1.0","deprecated":false,"unavailable":false}],"op":"replace"},{"op":"replace","value":"Macro","path":"/metadata/roleHeading"},{"op":"replace","value":"GL_BOOL","path":"/metadata/title"},{"op":"replace","value":"macro","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"GL_BOOL"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"path":"/seeAlsoSections","op":"add","value":null},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","tvOS","visionOS"],"tokens":[{"text":"#define","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_BOOL","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","value":"GL_BOOL","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_BOOL/title"},{"op":"replace","value":[{"kind":"identifier","text":"GL_BOOL"}],"path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_BOOL/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}