{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Global Variable","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"symbolKind":"var","role":"symbol","externalID":"c:@macro@GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR","modules":[{"name":"OpenGL ES"}],"navigatorTitle":[{"kind":"identifier","text":"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR"}],"platforms":[{"unavailable":false,"deprecated":false,"introducedAt":"2.0","beta":false,"name":"iOS"},{"unavailable":false,"deprecated":false,"introducedAt":"2.0","beta":false,"name":"iPadOS"},{"unavailable":false,"deprecated":false,"introducedAt":"2.0","beta":false,"name":"Mac Catalyst"},{"unavailable":false,"deprecated":false,"introducedAt":"9.0","beta":false,"name":"tvOS"},{"unavailable":false,"deprecated":false,"introducedAt":"1.0","beta":false,"name":"visionOS"}],"title":"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS","iPadOS","tvOS","visionOS"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.opengles/documentation/OpenGLES/GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR"},"variants":[{"paths":["/documentation/opengles/gl_compressed_srgb8_alpha8_astc_12x12_khr"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/opengles/gl_compressed_srgb8_alpha8_astc_12x12_khr"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.opengles/documentation/OpenGLES/GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"}],"url":"/documentation/opengles/gl_compressed_srgb8_alpha8_astc_12x12_khr","kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR"}],"type":"topic","title":"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR","identifier":"doc://com.apple.opengles/documentation/OpenGLES/GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR"},"doc://com.apple.opengles/documentation/OpenGLES":{"type":"topic","kind":"symbol","url":"/documentation/opengles","identifier":"doc://com.apple.opengles/documentation/OpenGLES","title":"OpenGL ES","abstract":[{"type":"text","text":"Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL."}],"role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"role":"symbol","url":"/documentation/Swift/Int32","abstract":[{"type":"text","text":"A 32-bit signed integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"title":"Int32","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"unavailable":false,"name":"iOS","deprecated":false,"beta":false,"introducedAt":"2.0"},{"unavailable":false,"name":"iPadOS","deprecated":false,"beta":false,"introducedAt":"2.0"},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false,"introducedAt":"2.0"},{"unavailable":false,"name":"tvOS","deprecated":false,"beta":false,"introducedAt":"9.0"},{"deprecated":false,"name":"visionOS","unavailable":false,"introducedAt":"1.0","beta":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Macro"},{"path":"/metadata/title","op":"replace","value":"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR"},{"path":"/metadata/symbolKind","op":"replace","value":"macro"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"add","value":null},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"#define"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR"}],"languages":["occ"]}]}},{"value":"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR","op":"replace","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR/title"},{"value":[{"kind":"identifier","text":"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR"}],"op":"replace","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}