{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","tvOS","visionOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_COLOR_ARRAY_SIZE","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"sections":[],"metadata":{"title":"GL_COLOR_ARRAY_SIZE","externalID":"c:@macro@GL_COLOR_ARRAY_SIZE","roleHeading":"Global Variable","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_COLOR_ARRAY_SIZE","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"modules":[{"name":"OpenGL ES"}],"navigatorTitle":[{"text":"GL_COLOR_ARRAY_SIZE","kind":"identifier"}],"platforms":[{"deprecated":false,"introducedAt":"2.0","name":"iOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"2.0","name":"iPadOS","unavailable":false,"beta":false},{"name":"Mac Catalyst","deprecated":false,"introducedAt":"2.0","unavailable":false,"beta":false},{"name":"tvOS","deprecated":false,"introducedAt":"9.0","unavailable":false,"beta":false},{"name":"visionOS","deprecated":false,"introducedAt":"1.0","unavailable":false,"beta":false}],"symbolKind":"var"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/opengles/gl_color_array_size"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/opengles/gl_color_array_size"]}],"identifier":{"url":"doc://com.apple.opengles/documentation/OpenGLES/GL_COLOR_ARRAY_SIZE","interfaceLanguage":"swift"},"references":{"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"role":"symbol","url":"/documentation/Swift/Int32","abstract":[{"type":"text","text":"A 32-bit signed integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"title":"Int32","type":"topic"},"doc://com.apple.opengles/documentation/OpenGLES":{"type":"topic","kind":"symbol","url":"/documentation/opengles","identifier":"doc://com.apple.opengles/documentation/OpenGLES","title":"OpenGL ES","abstract":[{"type":"text","text":"Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL."}],"role":"collection"},"doc://com.apple.opengles/documentation/OpenGLES/GL_COLOR_ARRAY_SIZE":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_COLOR_ARRAY_SIZE","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"navigatorTitle":[{"kind":"identifier","text":"GL_COLOR_ARRAY_SIZE"}],"role":"symbol","kind":"symbol","url":"/documentation/opengles/gl_color_array_size","abstract":[],"title":"GL_COLOR_ARRAY_SIZE","identifier":"doc://com.apple.opengles/documentation/OpenGLES/GL_COLOR_ARRAY_SIZE"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"deprecated":false,"introducedAt":"2.0","name":"iOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"2.0","name":"iPadOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"2.0","name":"Mac Catalyst","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"9.0","name":"tvOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"1.0","name":"visionOS","unavailable":false,"beta":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Macro","op":"replace"},{"path":"/metadata/title","value":"GL_COLOR_ARRAY_SIZE","op":"replace"},{"path":"/metadata/symbolKind","value":"macro","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"GL_COLOR_ARRAY_SIZE","kind":"identifier"}],"op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"op":"add","path":"/seeAlsoSections","value":null},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"#define","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_COLOR_ARRAY_SIZE","kind":"identifier"}],"platforms":["iOS","iPadOS","tvOS","visionOS"],"languages":["occ"]}]}},{"value":"GL_COLOR_ARRAY_SIZE","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_COLOR_ARRAY_SIZE/title","op":"replace"},{"value":[{"kind":"identifier","text":"GL_COLOR_ARRAY_SIZE"}],"path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_COLOR_ARRAY_SIZE/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}