{"metadata":{"roleHeading":"Global Variable","navigatorTitle":[{"kind":"identifier","text":"GL_COLOR_ATTACHMENT10"}],"externalID":"c:@macro@GL_COLOR_ATTACHMENT10","role":"symbol","symbolKind":"var","title":"GL_COLOR_ATTACHMENT10","platforms":[{"beta":false,"introducedAt":"2.0","deprecated":false,"unavailable":false,"name":"iOS"},{"beta":false,"introducedAt":"2.0","deprecated":false,"unavailable":false,"name":"iPadOS"},{"introducedAt":"2.0","deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false},{"introducedAt":"9.0","deprecated":false,"name":"tvOS","unavailable":false,"beta":false},{"introducedAt":"1.0","deprecated":false,"name":"visionOS","unavailable":false,"beta":false}],"modules":[{"name":"OpenGL ES"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_COLOR_ATTACHMENT10"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}]},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","tvOS","visionOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_COLOR_ATTACHMENT10","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/opengles/gl_color_attachment10"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/opengles/gl_color_attachment10"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.opengles/documentation/OpenGLES/GL_COLOR_ATTACHMENT10"},"references":{"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"role":"symbol","url":"/documentation/Swift/Int32","abstract":[{"type":"text","text":"A 32-bit signed integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"title":"Int32","type":"topic"},"doc://com.apple.opengles/documentation/OpenGLES":{"type":"topic","kind":"symbol","url":"/documentation/opengles","identifier":"doc://com.apple.opengles/documentation/OpenGLES","title":"OpenGL ES","abstract":[{"type":"text","text":"Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL."}],"role":"collection"},"doc://com.apple.opengles/documentation/OpenGLES/GL_COLOR_ATTACHMENT10":{"kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GL_COLOR_ATTACHMENT10"}],"type":"topic","title":"GL_COLOR_ATTACHMENT10","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_COLOR_ATTACHMENT10"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"}],"url":"/documentation/opengles/gl_color_attachment10","identifier":"doc://com.apple.opengles/documentation/OpenGLES/GL_COLOR_ATTACHMENT10","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"deprecated":false,"beta":false,"name":"iOS","introducedAt":"2.0"},{"name":"iPadOS","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"2.0"},{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"2.0"},{"name":"tvOS","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"9.0"},{"name":"visionOS","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"1.0"}],"op":"replace","path":"/metadata/platforms"},{"value":"Macro","op":"replace","path":"/metadata/roleHeading"},{"value":"GL_COLOR_ATTACHMENT10","op":"replace","path":"/metadata/title"},{"value":"macro","op":"replace","path":"/metadata/symbolKind"},{"path":"/metadata/fragments","value":[{"text":"GL_COLOR_ATTACHMENT10","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":null,"op":"add"},{"path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"#define","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_COLOR_ATTACHMENT10","kind":"identifier"}],"platforms":["iOS","iPadOS","tvOS","visionOS"]}],"kind":"declarations"},"op":"replace"},{"path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_COLOR_ATTACHMENT10/title","value":"GL_COLOR_ATTACHMENT10","op":"replace"},{"path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_COLOR_ATTACHMENT10/fragments","value":[{"text":"GL_COLOR_ATTACHMENT10","kind":"identifier"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}