{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_DEPTH_BUFFER_BIT","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS","iPadOS","tvOS","visionOS"]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.opengles/documentation/OpenGLES/GL_DEPTH_BUFFER_BIT"},"sections":[],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_DEPTH_BUFFER_BIT","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"navigatorTitle":[{"text":"GL_DEPTH_BUFFER_BIT","kind":"identifier"}],"modules":[{"name":"OpenGL ES"}],"platforms":[{"deprecated":false,"introducedAt":"2.0","name":"iOS","beta":false,"unavailable":false},{"introducedAt":"2.0","beta":false,"unavailable":false,"name":"iPadOS","deprecated":false},{"introducedAt":"2.0","beta":false,"unavailable":false,"name":"Mac Catalyst","deprecated":false},{"introducedAt":"9.0","beta":false,"unavailable":false,"name":"tvOS","deprecated":false},{"introducedAt":"1.0","beta":false,"unavailable":false,"name":"visionOS","deprecated":false}],"externalID":"c:@macro@GL_DEPTH_BUFFER_BIT","symbolKind":"var","roleHeading":"Global Variable","role":"symbol","title":"GL_DEPTH_BUFFER_BIT"},"kind":"symbol","variants":[{"paths":["/documentation/opengles/gl_depth_buffer_bit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/opengles/gl_depth_buffer_bit"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.opengles/documentation/OpenGLES/GL_DEPTH_BUFFER_BIT":{"type":"topic","url":"/documentation/opengles/gl_depth_buffer_bit","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_DEPTH_BUFFER_BIT"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"}],"navigatorTitle":[{"kind":"identifier","text":"GL_DEPTH_BUFFER_BIT"}],"identifier":"doc://com.apple.opengles/documentation/OpenGLES/GL_DEPTH_BUFFER_BIT","role":"symbol","title":"GL_DEPTH_BUFFER_BIT","kind":"symbol"},"doc://com.apple.opengles/documentation/OpenGLES":{"type":"topic","kind":"symbol","url":"/documentation/opengles","identifier":"doc://com.apple.opengles/documentation/OpenGLES","title":"OpenGL ES","abstract":[{"type":"text","text":"Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL."}],"role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"role":"symbol","url":"/documentation/Swift/Int32","abstract":[{"type":"text","text":"A 32-bit signed integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"title":"Int32","type":"topic"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"beta":false,"name":"iOS","introducedAt":"2.0","deprecated":false,"unavailable":false},{"beta":false,"name":"iPadOS","introducedAt":"2.0","deprecated":false,"unavailable":false},{"beta":false,"name":"Mac Catalyst","introducedAt":"2.0","deprecated":false,"unavailable":false},{"beta":false,"name":"tvOS","introducedAt":"9.0","deprecated":false,"unavailable":false},{"introducedAt":"1.0","beta":false,"unavailable":false,"name":"visionOS","deprecated":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Macro","op":"replace"},{"path":"/metadata/title","value":"GL_DEPTH_BUFFER_BIT","op":"replace"},{"path":"/metadata/symbolKind","value":"macro","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"GL_DEPTH_BUFFER_BIT","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":null,"op":"add"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"#define"},{"kind":"text","text":" "},{"text":"GL_DEPTH_BUFFER_BIT","kind":"identifier"}],"platforms":["iOS","iPadOS","tvOS","visionOS"],"languages":["occ"]}]},"op":"replace"},{"path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_DEPTH_BUFFER_BIT/title","value":"GL_DEPTH_BUFFER_BIT","op":"replace"},{"path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_DEPTH_BUFFER_BIT/fragments","value":[{"text":"GL_DEPTH_BUFFER_BIT","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}