{"metadata":{"role":"symbol","modules":[{"name":"OpenGL ES"}],"platforms":[{"deprecated":false,"name":"iOS","unavailable":false,"beta":false,"introducedAt":"2.0"},{"deprecated":false,"name":"iPadOS","unavailable":false,"beta":false,"introducedAt":"2.0"},{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false,"introducedAt":"2.0"},{"deprecated":false,"name":"tvOS","unavailable":false,"beta":false,"introducedAt":"9.0"},{"deprecated":false,"name":"visionOS","unavailable":false,"beta":false,"introducedAt":"1.0"}],"roleHeading":"Global Variable","externalID":"c:@macro@GL_EXT_debug_marker","title":"GL_EXT_debug_marker","symbolKind":"var","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_EXT_debug_marker","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"navigatorTitle":[{"text":"GL_EXT_debug_marker","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_EXT_debug_marker","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS","iPadOS","tvOS","visionOS"]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.opengles/documentation/OpenGLES/GL_EXT_debug_marker"},"sections":[],"variants":[{"paths":["/documentation/opengles/gl_ext_debug_marker"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/opengles/gl_ext_debug_marker"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.opengles/documentation/OpenGLES":{"type":"topic","kind":"symbol","url":"/documentation/opengles","identifier":"doc://com.apple.opengles/documentation/OpenGLES","title":"OpenGL ES","abstract":[{"type":"text","text":"Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL."}],"role":"collection"},"doc://com.apple.opengles/documentation/OpenGLES/GL_EXT_debug_marker":{"title":"GL_EXT_debug_marker","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_EXT_debug_marker","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"GL_EXT_debug_marker","kind":"identifier"}],"kind":"symbol","url":"/documentation/opengles/gl_ext_debug_marker","identifier":"doc://com.apple.opengles/documentation/OpenGLES/GL_EXT_debug_marker","abstract":[],"role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"role":"symbol","url":"/documentation/Swift/Int32","abstract":[{"type":"text","text":"A 32-bit signed integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"title":"Int32","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"beta":false,"deprecated":false,"name":"iOS","unavailable":false,"introducedAt":"2.0"},{"beta":false,"deprecated":false,"name":"iPadOS","unavailable":false,"introducedAt":"2.0"},{"beta":false,"deprecated":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"2.0"},{"beta":false,"deprecated":false,"name":"tvOS","unavailable":false,"introducedAt":"9.0"},{"beta":false,"deprecated":false,"name":"visionOS","unavailable":false,"introducedAt":"1.0"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Macro"},{"op":"replace","path":"/metadata/title","value":"GL_EXT_debug_marker"},{"op":"replace","path":"/metadata/symbolKind","value":"macro"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"GL_EXT_debug_marker","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"add","path":"/seeAlsoSections","value":null},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","tvOS","visionOS"],"tokens":[{"text":"#define","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_EXT_debug_marker","kind":"identifier"}]}]}},{"path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_EXT_debug_marker/title","value":"GL_EXT_debug_marker","op":"replace"},{"path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_EXT_debug_marker/fragments","value":[{"text":"GL_EXT_debug_marker","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}