{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_FLOAT_MAT3x2"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS","iPadOS","tvOS","visionOS"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","metadata":{"externalID":"c:@macro@GL_FLOAT_MAT3x2","symbolKind":"var","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_FLOAT_MAT3x2"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"}],"roleHeading":"Global Variable","modules":[{"name":"OpenGL ES"}],"platforms":[{"beta":false,"name":"iOS","introducedAt":"2.0","unavailable":false,"deprecated":false},{"unavailable":false,"beta":false,"introducedAt":"2.0","deprecated":false,"name":"iPadOS"},{"unavailable":false,"beta":false,"introducedAt":"2.0","deprecated":false,"name":"Mac Catalyst"},{"unavailable":false,"deprecated":false,"introducedAt":"9.0","beta":false,"name":"tvOS"},{"unavailable":false,"deprecated":false,"introducedAt":"1.0","beta":false,"name":"visionOS"}],"role":"symbol","title":"GL_FLOAT_MAT3x2","navigatorTitle":[{"kind":"identifier","text":"GL_FLOAT_MAT3x2"}]},"variants":[{"paths":["/documentation/opengles/gl_float_mat3x2"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/opengles/gl_float_mat3x2"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.opengles/documentation/OpenGLES/GL_FLOAT_MAT3x2"},"references":{"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview"},"doc://com.apple.opengles/documentation/OpenGLES/GL_FLOAT_MAT3x2":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GL_FLOAT_MAT3x2"}],"url":"/documentation/opengles/gl_float_mat3x2","kind":"symbol","title":"GL_FLOAT_MAT3x2","identifier":"doc://com.apple.opengles/documentation/OpenGLES/GL_FLOAT_MAT3x2","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_FLOAT_MAT3x2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"type":"topic"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"role":"symbol","url":"/documentation/Swift/Int32","abstract":[{"type":"text","text":"A 32-bit signed integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"title":"Int32","type":"topic"},"doc://com.apple.opengles/documentation/OpenGLES":{"type":"topic","kind":"symbol","url":"/documentation/opengles","identifier":"doc://com.apple.opengles/documentation/OpenGLES","title":"OpenGL ES","abstract":[{"type":"text","text":"Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL."}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"beta":false,"introducedAt":"2.0","name":"iOS","deprecated":false,"unavailable":false},{"beta":false,"introducedAt":"2.0","name":"iPadOS","deprecated":false,"unavailable":false},{"deprecated":false,"introducedAt":"2.0","unavailable":false,"beta":false,"name":"Mac Catalyst"},{"deprecated":false,"introducedAt":"9.0","unavailable":false,"beta":false,"name":"tvOS"},{"deprecated":false,"name":"visionOS","introducedAt":"1.0","beta":false,"unavailable":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Macro","path":"/metadata/roleHeading"},{"value":"GL_FLOAT_MAT3x2","op":"replace","path":"/metadata/title"},{"value":"macro","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"GL_FLOAT_MAT3x2","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"op":"replace","path":"/hierarchy"},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"add","value":null},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"#define","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_FLOAT_MAT3x2","kind":"identifier"}],"platforms":["iOS","iPadOS","tvOS","visionOS"]}]}},{"path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_FLOAT_MAT3x2/title","op":"replace","value":"GL_FLOAT_MAT3x2"},{"path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_FLOAT_MAT3x2/fragments","op":"replace","value":[{"kind":"identifier","text":"GL_FLOAT_MAT3x2"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}