{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"metadata":{"symbolKind":"var","modules":[{"name":"OpenGL ES"}],"role":"symbol","platforms":[{"name":"iOS","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"2.0"},{"name":"iPadOS","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"2.0"},{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"2.0"},{"name":"tvOS","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"9.0"},{"name":"visionOS","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"1.0"}],"title":"GL_HALF_FLOAT_OES","externalID":"c:@macro@GL_HALF_FLOAT_OES","navigatorTitle":[{"kind":"identifier","text":"GL_HALF_FLOAT_OES"}],"roleHeading":"Global Variable","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_HALF_FLOAT_OES"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/opengles/gl_half_float_oes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/opengles/gl_half_float_oes"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.opengles/documentation/OpenGLES/GL_HALF_FLOAT_OES"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_HALF_FLOAT_OES"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","tvOS","visionOS"],"languages":["swift"]}]}],"references":{"doc://com.apple.opengles/documentation/OpenGLES/GL_HALF_FLOAT_OES":{"type":"topic","abstract":[],"kind":"symbol","url":"/documentation/opengles/gl_half_float_oes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_HALF_FLOAT_OES"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"title":"GL_HALF_FLOAT_OES","navigatorTitle":[{"kind":"identifier","text":"GL_HALF_FLOAT_OES"}],"identifier":"doc://com.apple.opengles/documentation/OpenGLES/GL_HALF_FLOAT_OES","role":"symbol"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"role":"symbol","url":"/documentation/Swift/Int32","abstract":[{"type":"text","text":"A 32-bit signed integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"title":"Int32","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview"},"doc://com.apple.opengles/documentation/OpenGLES":{"type":"topic","kind":"symbol","url":"/documentation/opengles","identifier":"doc://com.apple.opengles/documentation/OpenGLES","title":"OpenGL ES","abstract":[{"type":"text","text":"Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL."}],"role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"introducedAt":"2.0","beta":false,"name":"iOS","unavailable":false,"deprecated":false},{"introducedAt":"2.0","beta":false,"name":"iPadOS","unavailable":false,"deprecated":false},{"introducedAt":"2.0","beta":false,"name":"Mac Catalyst","unavailable":false,"deprecated":false},{"introducedAt":"9.0","beta":false,"name":"tvOS","unavailable":false,"deprecated":false},{"introducedAt":"1.0","beta":false,"name":"visionOS","unavailable":false,"deprecated":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Macro","path":"/metadata/roleHeading"},{"op":"replace","value":"GL_HALF_FLOAT_OES","path":"/metadata/title"},{"op":"replace","value":"macro","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"GL_HALF_FLOAT_OES","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"add","value":null,"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"#define"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_HALF_FLOAT_OES"}],"platforms":["iOS","iPadOS","tvOS","visionOS"],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"value":"GL_HALF_FLOAT_OES","op":"replace","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_HALF_FLOAT_OES/title"},{"value":[{"kind":"identifier","text":"GL_HALF_FLOAT_OES"}],"op":"replace","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_HALF_FLOAT_OES/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}