{"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","tvOS","visionOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_LOGIC_OP_MODE","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"GL_LOGIC_OP_MODE","role":"symbol","platforms":[{"name":"iOS","unavailable":false,"introducedAt":"2.0","deprecated":false,"beta":false},{"name":"iPadOS","unavailable":false,"introducedAt":"2.0","deprecated":false,"beta":false},{"name":"Mac Catalyst","unavailable":false,"introducedAt":"2.0","deprecated":false,"beta":false},{"name":"tvOS","unavailable":false,"introducedAt":"9.0","deprecated":false,"beta":false},{"beta":false,"unavailable":false,"name":"visionOS","introducedAt":"1.0","deprecated":false}],"roleHeading":"Global Variable","externalID":"c:@macro@GL_LOGIC_OP_MODE","modules":[{"name":"OpenGL ES"}],"navigatorTitle":[{"kind":"identifier","text":"GL_LOGIC_OP_MODE"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_LOGIC_OP_MODE"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"symbolKind":"var"},"identifier":{"url":"doc://com.apple.opengles/documentation/OpenGLES/GL_LOGIC_OP_MODE","interfaceLanguage":"swift"},"variants":[{"paths":["/documentation/opengles/gl_logic_op_mode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/opengles/gl_logic_op_mode"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"references":{"doc://com.apple.opengles/documentation/OpenGLES/GL_LOGIC_OP_MODE":{"kind":"symbol","type":"topic","identifier":"doc://com.apple.opengles/documentation/OpenGLES/GL_LOGIC_OP_MODE","navigatorTitle":[{"text":"GL_LOGIC_OP_MODE","kind":"identifier"}],"abstract":[],"role":"symbol","title":"GL_LOGIC_OP_MODE","url":"/documentation/opengles/gl_logic_op_mode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"GL_LOGIC_OP_MODE","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"}]},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview"},"doc://com.apple.opengles/documentation/OpenGLES":{"type":"topic","kind":"symbol","url":"/documentation/opengles","identifier":"doc://com.apple.opengles/documentation/OpenGLES","title":"OpenGL ES","abstract":[{"type":"text","text":"Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL."}],"role":"collection"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"role":"symbol","url":"/documentation/Swift/Int32","abstract":[{"type":"text","text":"A 32-bit signed integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"title":"Int32","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"beta":false,"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"2.0"},{"name":"iPadOS","unavailable":false,"introducedAt":"2.0","deprecated":false,"beta":false},{"name":"Mac Catalyst","unavailable":false,"introducedAt":"2.0","deprecated":false,"beta":false},{"name":"tvOS","unavailable":false,"introducedAt":"9.0","deprecated":false,"beta":false},{"name":"visionOS","unavailable":false,"introducedAt":"1.0","deprecated":false,"beta":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Macro","op":"replace"},{"path":"/metadata/title","value":"GL_LOGIC_OP_MODE","op":"replace"},{"path":"/metadata/symbolKind","value":"macro","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"GL_LOGIC_OP_MODE"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":null,"op":"add"},{"path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["iOS","iPadOS","tvOS","visionOS"],"languages":["occ"],"tokens":[{"text":"#define","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_LOGIC_OP_MODE","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"value":"GL_LOGIC_OP_MODE","op":"replace","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_LOGIC_OP_MODE/title"},{"op":"replace","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_LOGIC_OP_MODE/fragments","value":[{"text":"GL_LOGIC_OP_MODE","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}