{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_MAX_TEXTURE_IMAGE_UNITS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/opengles/gl_max_texture_image_units"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/opengles/gl_max_texture_image_units"]}],"metadata":{"title":"GL_MAX_TEXTURE_IMAGE_UNITS","navigatorTitle":[{"kind":"identifier","text":"GL_MAX_TEXTURE_IMAGE_UNITS"}],"platforms":[{"deprecated":false,"introducedAt":"2.0","beta":false,"unavailable":false,"name":"iOS"},{"deprecated":false,"introducedAt":"2.0","beta":false,"unavailable":false,"name":"iPadOS"},{"deprecated":false,"introducedAt":"2.0","beta":false,"unavailable":false,"name":"Mac Catalyst"},{"deprecated":false,"introducedAt":"9.0","beta":false,"unavailable":false,"name":"tvOS"},{"deprecated":false,"introducedAt":"1.0","beta":false,"unavailable":false,"name":"visionOS"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_MAX_TEXTURE_IMAGE_UNITS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"symbolKind":"var","externalID":"c:@macro@GL_MAX_TEXTURE_IMAGE_UNITS","role":"symbol","modules":[{"name":"OpenGL ES"}],"roleHeading":"Global Variable"},"identifier":{"url":"doc://com.apple.opengles/documentation/OpenGLES/GL_MAX_TEXTURE_IMAGE_UNITS","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.externally.resolved.symbol/s:s5Int32V":{"role":"symbol","url":"/documentation/Swift/Int32","abstract":[{"type":"text","text":"A 32-bit signed integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"title":"Int32","type":"topic"},"doc://com.apple.opengles/documentation/OpenGLES":{"type":"topic","kind":"symbol","url":"/documentation/opengles","identifier":"doc://com.apple.opengles/documentation/OpenGLES","title":"OpenGL ES","abstract":[{"type":"text","text":"Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL."}],"role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview"},"doc://com.apple.opengles/documentation/OpenGLES/GL_MAX_TEXTURE_IMAGE_UNITS":{"url":"/documentation/opengles/gl_max_texture_image_units","title":"GL_MAX_TEXTURE_IMAGE_UNITS","identifier":"doc://com.apple.opengles/documentation/OpenGLES/GL_MAX_TEXTURE_IMAGE_UNITS","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GL_MAX_TEXTURE_IMAGE_UNITS"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_MAX_TEXTURE_IMAGE_UNITS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"abstract":[],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"beta":false,"deprecated":false,"name":"iOS","introducedAt":"2.0"},{"unavailable":false,"beta":false,"deprecated":false,"name":"iPadOS","introducedAt":"2.0"},{"unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"2.0"},{"unavailable":false,"beta":false,"deprecated":false,"name":"tvOS","introducedAt":"9.0"},{"unavailable":false,"beta":false,"deprecated":false,"name":"visionOS","introducedAt":"1.0"}],"path":"/metadata/platforms"},{"op":"replace","value":"Macro","path":"/metadata/roleHeading"},{"op":"replace","value":"GL_MAX_TEXTURE_IMAGE_UNITS","path":"/metadata/title"},{"op":"replace","value":"macro","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"GL_MAX_TEXTURE_IMAGE_UNITS"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"add","value":null,"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","tvOS","visionOS"],"tokens":[{"text":"#define","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_MAX_TEXTURE_IMAGE_UNITS","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"op":"replace","value":"GL_MAX_TEXTURE_IMAGE_UNITS","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_MAX_TEXTURE_IMAGE_UNITS/title"},{"value":[{"kind":"identifier","text":"GL_MAX_TEXTURE_IMAGE_UNITS"}],"path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_MAX_TEXTURE_IMAGE_UNITS/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}