{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.opengles/documentation/OpenGLES/GL_MODELVIEW"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","tvOS","visionOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_MODELVIEW"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"metadata":{"title":"GL_MODELVIEW","platforms":[{"name":"iOS","deprecated":false,"introducedAt":"2.0","unavailable":false,"beta":false},{"name":"iPadOS","deprecated":false,"introducedAt":"2.0","unavailable":false,"beta":false},{"introducedAt":"2.0","deprecated":false,"name":"Mac Catalyst","beta":false,"unavailable":false},{"introducedAt":"9.0","deprecated":false,"name":"tvOS","beta":false,"unavailable":false},{"introducedAt":"1.0","deprecated":false,"name":"visionOS","beta":false,"unavailable":false}],"navigatorTitle":[{"text":"GL_MODELVIEW","kind":"identifier"}],"modules":[{"name":"OpenGL ES"}],"roleHeading":"Global Variable","externalID":"c:@macro@GL_MODELVIEW","symbolKind":"var","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_MODELVIEW"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/opengles/gl_modelview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/opengles/gl_modelview"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"kind":"symbol","references":{"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview"},"doc://com.apple.opengles/documentation/OpenGLES":{"type":"topic","kind":"symbol","url":"/documentation/opengles","identifier":"doc://com.apple.opengles/documentation/OpenGLES","title":"OpenGL ES","abstract":[{"type":"text","text":"Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL."}],"role":"collection"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"role":"symbol","url":"/documentation/Swift/Int32","abstract":[{"type":"text","text":"A 32-bit signed integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"title":"Int32","type":"topic"},"doc://com.apple.opengles/documentation/OpenGLES/GL_MODELVIEW":{"role":"symbol","identifier":"doc://com.apple.opengles/documentation/OpenGLES/GL_MODELVIEW","title":"GL_MODELVIEW","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GL_MODELVIEW"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_MODELVIEW"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"type":"topic","url":"/documentation/opengles/gl_modelview","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"name":"iOS","deprecated":false,"beta":false,"introducedAt":"2.0","unavailable":false},{"name":"iPadOS","deprecated":false,"beta":false,"introducedAt":"2.0","unavailable":false},{"introducedAt":"2.0","deprecated":false,"name":"Mac Catalyst","beta":false,"unavailable":false},{"introducedAt":"9.0","deprecated":false,"name":"tvOS","beta":false,"unavailable":false},{"introducedAt":"1.0","deprecated":false,"name":"visionOS","beta":false,"unavailable":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Macro","path":"/metadata/roleHeading","op":"replace"},{"value":"GL_MODELVIEW","path":"/metadata/title","op":"replace"},{"value":"macro","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"GL_MODELVIEW"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":null,"op":"add"},{"path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"#define","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_MODELVIEW","kind":"identifier"}],"platforms":["iOS","iPadOS","tvOS","visionOS"]}],"kind":"declarations"},"op":"replace"},{"path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_MODELVIEW/title","value":"GL_MODELVIEW","op":"replace"},{"path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_MODELVIEW/fragments","value":[{"text":"GL_MODELVIEW","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}