{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.opengles/documentation/OpenGLES/GL_MAP_WRITE_BIT"},"sections":[],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"GL_MAP_WRITE_BIT"}],"roleHeading":"Global Variable","externalID":"c:@macro@GL_MAP_WRITE_BIT","role":"symbol","symbolKind":"var","modules":[{"name":"OpenGL ES"}],"platforms":[{"unavailable":false,"beta":false,"name":"iOS","introducedAt":"2.0","deprecated":false},{"unavailable":false,"name":"iPadOS","deprecated":false,"beta":false,"introducedAt":"2.0"},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false,"introducedAt":"2.0"},{"unavailable":false,"name":"tvOS","deprecated":false,"beta":false,"introducedAt":"9.0"},{"unavailable":false,"name":"visionOS","deprecated":false,"beta":false,"introducedAt":"1.0"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_MAP_WRITE_BIT"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"}],"title":"GL_MAP_WRITE_BIT"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_MAP_WRITE_BIT"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/opengles/gl_map_write_bit"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/opengles/gl_map_write_bit"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.externally.resolved.symbol/s:s5Int32V":{"role":"symbol","url":"/documentation/Swift/Int32","abstract":[{"type":"text","text":"A 32-bit signed integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"title":"Int32","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview"},"doc://com.apple.opengles/documentation/OpenGLES/GL_MAP_WRITE_BIT":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_MAP_WRITE_BIT"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"}],"identifier":"doc://com.apple.opengles/documentation/OpenGLES/GL_MAP_WRITE_BIT","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GL_MAP_WRITE_BIT"}],"url":"/documentation/opengles/gl_map_write_bit","title":"GL_MAP_WRITE_BIT","type":"topic"},"doc://com.apple.opengles/documentation/OpenGLES":{"type":"topic","kind":"symbol","url":"/documentation/opengles","identifier":"doc://com.apple.opengles/documentation/OpenGLES","title":"OpenGL ES","abstract":[{"type":"text","text":"Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL."}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"name":"iOS","beta":false,"unavailable":false,"introducedAt":"2.0","deprecated":false},{"name":"iPadOS","beta":false,"unavailable":false,"introducedAt":"2.0","deprecated":false},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false,"introducedAt":"2.0"},{"unavailable":false,"name":"tvOS","deprecated":false,"beta":false,"introducedAt":"9.0"},{"deprecated":false,"beta":false,"name":"visionOS","unavailable":false,"introducedAt":"1.0"}],"path":"/metadata/platforms"},{"op":"replace","value":"Macro","path":"/metadata/roleHeading"},{"op":"replace","value":"GL_MAP_WRITE_BIT","path":"/metadata/title"},{"op":"replace","value":"macro","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"GL_MAP_WRITE_BIT","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"add","value":null,"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"#define"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_MAP_WRITE_BIT"}]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"value":"GL_MAP_WRITE_BIT","op":"replace","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_MAP_WRITE_BIT/title"},{"value":[{"kind":"identifier","text":"GL_MAP_WRITE_BIT"}],"op":"replace","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_MAP_WRITE_BIT/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}