{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/opengles/gl_oes_element_index_uint"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/opengles/gl_oes_element_index_uint"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.opengles/documentation/OpenGLES/GL_OES_element_index_uint"},"kind":"symbol","sections":[],"metadata":{"platforms":[{"unavailable":false,"name":"iOS","deprecated":false,"beta":false,"introducedAt":"2.0"},{"unavailable":false,"name":"iPadOS","deprecated":false,"beta":false,"introducedAt":"2.0"},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false,"introducedAt":"2.0"},{"unavailable":false,"name":"tvOS","deprecated":false,"beta":false,"introducedAt":"9.0"},{"beta":false,"name":"visionOS","unavailable":false,"deprecated":false,"introducedAt":"1.0"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_OES_element_index_uint","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"roleHeading":"Global Variable","navigatorTitle":[{"text":"GL_OES_element_index_uint","kind":"identifier"}],"role":"symbol","symbolKind":"var","externalID":"c:@macro@GL_OES_element_index_uint","title":"GL_OES_element_index_uint","modules":[{"name":"OpenGL ES"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_OES_element_index_uint"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.externally.resolved.symbol/s:s5Int32V":{"role":"symbol","url":"/documentation/Swift/Int32","abstract":[{"type":"text","text":"A 32-bit signed integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"title":"Int32","type":"topic"},"doc://com.apple.opengles/documentation/OpenGLES/GL_OES_element_index_uint":{"type":"topic","url":"/documentation/opengles/gl_oes_element_index_uint","identifier":"doc://com.apple.opengles/documentation/OpenGLES/GL_OES_element_index_uint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_OES_element_index_uint"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"GL_OES_element_index_uint","kind":"identifier"}],"title":"GL_OES_element_index_uint","kind":"symbol","role":"symbol","abstract":[]},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview"},"doc://com.apple.opengles/documentation/OpenGLES":{"type":"topic","kind":"symbol","url":"/documentation/opengles","identifier":"doc://com.apple.opengles/documentation/OpenGLES","title":"OpenGL ES","abstract":[{"type":"text","text":"Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL."}],"role":"collection"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"beta":false,"introducedAt":"2.0","deprecated":false,"unavailable":false,"name":"iOS"},{"beta":false,"name":"iPadOS","unavailable":false,"deprecated":false,"introducedAt":"2.0"},{"beta":false,"name":"Mac Catalyst","unavailable":false,"deprecated":false,"introducedAt":"2.0"},{"beta":false,"name":"tvOS","unavailable":false,"deprecated":false,"introducedAt":"9.0"},{"beta":false,"name":"visionOS","unavailable":false,"deprecated":false,"introducedAt":"1.0"}],"op":"replace"},{"op":"replace","path":"/metadata/roleHeading","value":"Macro"},{"op":"replace","path":"/metadata/title","value":"GL_OES_element_index_uint"},{"op":"replace","path":"/metadata/symbolKind","value":"macro"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"GL_OES_element_index_uint"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"add","path":"/seeAlsoSections","value":null},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","tvOS","visionOS"],"tokens":[{"text":"#define","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_OES_element_index_uint","kind":"identifier"}]}]}},{"op":"replace","value":"GL_OES_element_index_uint","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_OES_element_index_uint/title"},{"op":"replace","value":[{"text":"GL_OES_element_index_uint","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_OES_element_index_uint/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}