{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/opengles/gl_program_pipeline_binding_ext"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/opengles/gl_program_pipeline_binding_ext"]}],"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_PROGRAM_PIPELINE_BINDING_EXT"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.opengles/documentation/OpenGLES/GL_PROGRAM_PIPELINE_BINDING_EXT"},"metadata":{"symbolKind":"var","platforms":[{"introducedAt":"2.0","unavailable":false,"deprecated":false,"beta":false,"name":"iOS"},{"introducedAt":"2.0","unavailable":false,"deprecated":false,"beta":false,"name":"iPadOS"},{"introducedAt":"2.0","unavailable":false,"deprecated":false,"beta":false,"name":"Mac Catalyst"},{"introducedAt":"9.0","unavailable":false,"deprecated":false,"beta":false,"name":"tvOS"},{"introducedAt":"1.0","unavailable":false,"deprecated":false,"beta":false,"name":"visionOS"}],"roleHeading":"Global Variable","title":"GL_PROGRAM_PIPELINE_BINDING_EXT","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_PROGRAM_PIPELINE_BINDING_EXT"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"externalID":"c:@macro@GL_PROGRAM_PIPELINE_BINDING_EXT","navigatorTitle":[{"kind":"identifier","text":"GL_PROGRAM_PIPELINE_BINDING_EXT"}],"modules":[{"name":"OpenGL ES"}],"role":"symbol"},"references":{"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"role":"symbol","url":"/documentation/Swift/Int32","abstract":[{"type":"text","text":"A 32-bit signed integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"title":"Int32","type":"topic"},"doc://com.apple.opengles/documentation/OpenGLES":{"type":"topic","kind":"symbol","url":"/documentation/opengles","identifier":"doc://com.apple.opengles/documentation/OpenGLES","title":"OpenGL ES","abstract":[{"type":"text","text":"Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL."}],"role":"collection"},"doc://com.apple.opengles/documentation/OpenGLES/GL_PROGRAM_PIPELINE_BINDING_EXT":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_PROGRAM_PIPELINE_BINDING_EXT","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"role":"symbol","abstract":[],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GL_PROGRAM_PIPELINE_BINDING_EXT"}],"title":"GL_PROGRAM_PIPELINE_BINDING_EXT","url":"/documentation/opengles/gl_program_pipeline_binding_ext","identifier":"doc://com.apple.opengles/documentation/OpenGLES/GL_PROGRAM_PIPELINE_BINDING_EXT"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"introducedAt":"2.0","unavailable":false,"deprecated":false,"beta":false,"name":"iOS"},{"introducedAt":"2.0","unavailable":false,"deprecated":false,"beta":false,"name":"iPadOS"},{"introducedAt":"2.0","unavailable":false,"deprecated":false,"beta":false,"name":"Mac Catalyst"},{"introducedAt":"9.0","unavailable":false,"deprecated":false,"beta":false,"name":"tvOS"},{"introducedAt":"1.0","unavailable":false,"deprecated":false,"beta":false,"name":"visionOS"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Macro","op":"replace"},{"path":"/metadata/title","value":"GL_PROGRAM_PIPELINE_BINDING_EXT","op":"replace"},{"value":"macro","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"GL_PROGRAM_PIPELINE_BINDING_EXT","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":null,"path":"/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"#define"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_PROGRAM_PIPELINE_BINDING_EXT"}],"platforms":["iOS","iPadOS","tvOS","visionOS"],"languages":["occ"]}]},"path":"/primaryContentSections/0","op":"replace"},{"value":"GL_PROGRAM_PIPELINE_BINDING_EXT","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_PROGRAM_PIPELINE_BINDING_EXT/title","op":"replace"},{"value":[{"text":"GL_PROGRAM_PIPELINE_BINDING_EXT","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_PROGRAM_PIPELINE_BINDING_EXT/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}