{"variants":[{"paths":["/documentation/opengles/gl_rgb10_a2"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/opengles/gl_rgb10_a2"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"identifier":{"url":"doc://com.apple.opengles/documentation/OpenGLES/GL_RGB10_A2","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"GL_RGB10_A2","kind":"identifier"}],"title":"GL_RGB10_A2","modules":[{"name":"OpenGL ES"}],"externalID":"c:@macro@GL_RGB10_A2","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_RGB10_A2"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"roleHeading":"Global Variable","symbolKind":"var","role":"symbol","platforms":[{"name":"iOS","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"2.0"},{"name":"iPadOS","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"2.0"},{"name":"Mac Catalyst","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"2.0"},{"name":"tvOS","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"9.0"},{"name":"visionOS","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"1.0"}]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_RGB10_A2","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","tvOS","visionOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview"},"doc://com.apple.opengles/documentation/OpenGLES/GL_RGB10_A2":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_RGB10_A2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"kind":"symbol","abstract":[],"type":"topic","title":"GL_RGB10_A2","identifier":"doc://com.apple.opengles/documentation/OpenGLES/GL_RGB10_A2","url":"/documentation/opengles/gl_rgb10_a2","navigatorTitle":[{"text":"GL_RGB10_A2","kind":"identifier"}]},"doc://com.apple.opengles/documentation/OpenGLES":{"type":"topic","kind":"symbol","url":"/documentation/opengles","identifier":"doc://com.apple.opengles/documentation/OpenGLES","title":"OpenGL ES","abstract":[{"type":"text","text":"Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL."}],"role":"collection"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"role":"symbol","url":"/documentation/Swift/Int32","abstract":[{"type":"text","text":"A 32-bit signed integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"title":"Int32","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"value":[{"name":"iOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"2.0"},{"name":"iPadOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"2.0"},{"name":"Mac Catalyst","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"2.0"},{"name":"tvOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"9.0"},{"name":"visionOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"1.0"}],"path":"/metadata/platforms","op":"replace"},{"path":"/metadata/roleHeading","op":"replace","value":"Macro"},{"path":"/metadata/title","op":"replace","value":"GL_RGB10_A2"},{"path":"/metadata/symbolKind","op":"replace","value":"macro"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"GL_RGB10_A2","kind":"identifier"}]},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":null,"op":"add"},{"path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"text":"#define","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_RGB10_A2","kind":"identifier"}],"platforms":["iOS","iPadOS","tvOS","visionOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_RGB10_A2/title","value":"GL_RGB10_A2","op":"replace"},{"path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_RGB10_A2/fragments","value":[{"kind":"identifier","text":"GL_RGB10_A2"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}