{"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"metadata":{"role":"symbol","modules":[{"name":"OpenGL ES"}],"roleHeading":"Global Variable","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GL_RENDERER"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"platforms":[{"unavailable":false,"deprecated":false,"beta":false,"name":"iOS","introducedAt":"2.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"iPadOS","introducedAt":"2.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"Mac Catalyst","introducedAt":"2.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"tvOS","introducedAt":"9.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"visionOS","introducedAt":"1.0"}],"navigatorTitle":[{"kind":"identifier","text":"GL_RENDERER"}],"externalID":"c:@macro@GL_RENDERER","symbolKind":"var","title":"GL_RENDERER"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.opengles/documentation/OpenGLES/GL_RENDERER","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/opengles/gl_renderer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/opengles/gl_renderer"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","tvOS","visionOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_RENDERER","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"references":{"doc://com.apple.opengles/documentation/OpenGLES":{"type":"topic","kind":"symbol","url":"/documentation/opengles","identifier":"doc://com.apple.opengles/documentation/OpenGLES","title":"OpenGL ES","abstract":[{"type":"text","text":"Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL."}],"role":"collection"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"role":"symbol","url":"/documentation/Swift/Int32","abstract":[{"type":"text","text":"A 32-bit signed integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"title":"Int32","type":"topic"},"doc://com.apple.opengles/documentation/OpenGLES/GL_RENDERER":{"navigatorTitle":[{"text":"GL_RENDERER","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_RENDERER","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"role":"symbol","abstract":[],"identifier":"doc://com.apple.opengles/documentation/OpenGLES/GL_RENDERER","title":"GL_RENDERER","type":"topic","url":"/documentation/opengles/gl_renderer","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"name":"iOS","beta":false,"deprecated":false,"introducedAt":"2.0","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"2.0","name":"iPadOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"2.0","name":"Mac Catalyst","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"9.0","name":"tvOS","unavailable":false},{"unavailable":false,"deprecated":false,"name":"visionOS","introducedAt":"1.0","beta":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Macro","path":"/metadata/roleHeading","op":"replace"},{"value":"GL_RENDERER","path":"/metadata/title","op":"replace"},{"value":"macro","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"GL_RENDERER","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":null,"path":"/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS","iPadOS","tvOS","visionOS"],"languages":["occ"],"tokens":[{"text":"#define","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_RENDERER","kind":"identifier"}]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"value":"GL_RENDERER","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_RENDERER/title","op":"replace"},{"value":[{"kind":"identifier","text":"GL_RENDERER"}],"path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_RENDERER/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}