{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.opengles/documentation/OpenGLES/GL_RED_INTEGER","interfaceLanguage":"swift"},"metadata":{"role":"symbol","externalID":"c:@macro@GL_RED_INTEGER","symbolKind":"var","roleHeading":"Global Variable","modules":[{"name":"OpenGL ES"}],"navigatorTitle":[{"kind":"identifier","text":"GL_RED_INTEGER"}],"title":"GL_RED_INTEGER","platforms":[{"beta":false,"name":"iOS","unavailable":false,"introducedAt":"2.0","deprecated":false},{"beta":false,"name":"iPadOS","unavailable":false,"introducedAt":"2.0","deprecated":false},{"beta":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"2.0","deprecated":false},{"beta":false,"name":"tvOS","unavailable":false,"introducedAt":"9.0","deprecated":false},{"beta":false,"name":"visionOS","unavailable":false,"introducedAt":"1.0","deprecated":false}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_RED_INTEGER"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}]},"sections":[],"variants":[{"paths":["/documentation/opengles/gl_red_integer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/opengles/gl_red_integer"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_RED_INTEGER"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","text":"Int32"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","tvOS","visionOS"],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://com.apple.opengles/documentation/OpenGLES/GL_RED_INTEGER":{"navigatorTitle":[{"kind":"identifier","text":"GL_RED_INTEGER"}],"role":"symbol","identifier":"doc://com.apple.opengles/documentation/OpenGLES/GL_RED_INTEGER","kind":"symbol","title":"GL_RED_INTEGER","url":"/documentation/opengles/gl_red_integer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_RED_INTEGER"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"abstract":[],"type":"topic"},"doc://com.apple.opengles/documentation/OpenGLES":{"type":"topic","kind":"symbol","url":"/documentation/opengles","identifier":"doc://com.apple.opengles/documentation/OpenGLES","title":"OpenGL ES","abstract":[{"type":"text","text":"Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL."}],"role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"role":"symbol","url":"/documentation/Swift/Int32","abstract":[{"type":"text","text":"A 32-bit signed integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"title":"Int32","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"introducedAt":"2.0","unavailable":false,"deprecated":false,"name":"iOS","beta":false},{"introducedAt":"2.0","unavailable":false,"deprecated":false,"name":"iPadOS","beta":false},{"introducedAt":"2.0","unavailable":false,"deprecated":false,"name":"Mac Catalyst","beta":false},{"introducedAt":"9.0","unavailable":false,"deprecated":false,"name":"tvOS","beta":false},{"introducedAt":"1.0","unavailable":false,"deprecated":false,"name":"visionOS","beta":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Macro","path":"/metadata/roleHeading"},{"op":"replace","value":"GL_RED_INTEGER","path":"/metadata/title"},{"op":"replace","value":"macro","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"GL_RED_INTEGER"}],"path":"/metadata/fragments"},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"add","value":null},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"#define"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_RED_INTEGER"}],"languages":["occ"],"platforms":["iOS","iPadOS","tvOS","visionOS"]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_RED_INTEGER/title","value":"GL_RED_INTEGER"},{"op":"replace","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_RED_INTEGER/fragments","value":[{"text":"GL_RED_INTEGER","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}