{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_STENCIL_BACK_FAIL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"metadata":{"symbolKind":"var","externalID":"c:@macro@GL_STENCIL_BACK_FAIL","title":"GL_STENCIL_BACK_FAIL","platforms":[{"name":"iOS","unavailable":false,"deprecated":false,"introducedAt":"2.0","beta":false},{"name":"iPadOS","unavailable":false,"deprecated":false,"introducedAt":"2.0","beta":false},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"introducedAt":"2.0","beta":false},{"name":"tvOS","unavailable":false,"deprecated":false,"introducedAt":"9.0","beta":false},{"name":"visionOS","unavailable":false,"deprecated":false,"introducedAt":"1.0","beta":false}],"modules":[{"name":"OpenGL ES"}],"roleHeading":"Global Variable","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GL_STENCIL_BACK_FAIL"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_STENCIL_BACK_FAIL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc://com.apple.opengles/documentation/OpenGLES/GL_STENCIL_BACK_FAIL","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/opengles/gl_stencil_back_fail"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/opengles/gl_stencil_back_fail"]}],"references":{"doc://com.apple.opengles/documentation/OpenGLES":{"type":"topic","kind":"symbol","url":"/documentation/opengles","identifier":"doc://com.apple.opengles/documentation/OpenGLES","title":"OpenGL ES","abstract":[{"type":"text","text":"Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL."}],"role":"collection"},"doc://com.apple.opengles/documentation/OpenGLES/GL_STENCIL_BACK_FAIL":{"navigatorTitle":[{"kind":"identifier","text":"GL_STENCIL_BACK_FAIL"}],"title":"GL_STENCIL_BACK_FAIL","identifier":"doc://com.apple.opengles/documentation/OpenGLES/GL_STENCIL_BACK_FAIL","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"GL_STENCIL_BACK_FAIL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"}],"role":"symbol","url":"/documentation/opengles/gl_stencil_back_fail","abstract":[],"type":"topic","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"role":"symbol","url":"/documentation/Swift/Int32","abstract":[{"type":"text","text":"A 32-bit signed integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"title":"Int32","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"introducedAt":"2.0","beta":false,"unavailable":false,"deprecated":false,"name":"iOS"},{"introducedAt":"2.0","beta":false,"unavailable":false,"deprecated":false,"name":"iPadOS"},{"introducedAt":"2.0","beta":false,"unavailable":false,"deprecated":false,"name":"Mac Catalyst"},{"deprecated":false,"beta":false,"unavailable":false,"name":"tvOS","introducedAt":"9.0"},{"deprecated":false,"beta":false,"unavailable":false,"name":"visionOS","introducedAt":"1.0"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Macro"},{"path":"/metadata/title","op":"replace","value":"GL_STENCIL_BACK_FAIL"},{"path":"/metadata/symbolKind","op":"replace","value":"macro"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"GL_STENCIL_BACK_FAIL","kind":"identifier"}]},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":null,"op":"add","path":"/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS","iPadOS","tvOS","visionOS"],"languages":["occ"],"tokens":[{"text":"#define","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_STENCIL_BACK_FAIL","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":"GL_STENCIL_BACK_FAIL","op":"replace","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_STENCIL_BACK_FAIL/title"},{"value":[{"text":"GL_STENCIL_BACK_FAIL","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_STENCIL_BACK_FAIL/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}