{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/opengles/gl_srgb8_alpha8"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/opengles/gl_srgb8_alpha8"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.opengles/documentation/OpenGLES/GL_SRGB8_ALPHA8","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_SRGB8_ALPHA8","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","tvOS","visionOS"]}],"kind":"declarations"}],"metadata":{"symbolKind":"var","modules":[{"name":"OpenGL ES"}],"externalID":"c:@macro@GL_SRGB8_ALPHA8","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_SRGB8_ALPHA8","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"role":"symbol","title":"GL_SRGB8_ALPHA8","platforms":[{"unavailable":false,"name":"iOS","introducedAt":"2.0","beta":false,"deprecated":false},{"unavailable":false,"name":"iPadOS","introducedAt":"2.0","beta":false,"deprecated":false},{"unavailable":false,"name":"Mac Catalyst","introducedAt":"2.0","beta":false,"deprecated":false},{"unavailable":false,"name":"tvOS","introducedAt":"9.0","beta":false,"deprecated":false},{"unavailable":false,"name":"visionOS","introducedAt":"1.0","beta":false,"deprecated":false}],"navigatorTitle":[{"text":"GL_SRGB8_ALPHA8","kind":"identifier"}],"roleHeading":"Global Variable"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"references":{"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview"},"doc://com.apple.opengles/documentation/OpenGLES":{"type":"topic","kind":"symbol","url":"/documentation/opengles","identifier":"doc://com.apple.opengles/documentation/OpenGLES","title":"OpenGL ES","abstract":[{"type":"text","text":"Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL."}],"role":"collection"},"doc://com.apple.opengles/documentation/OpenGLES/GL_SRGB8_ALPHA8":{"url":"/documentation/opengles/gl_srgb8_alpha8","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_SRGB8_ALPHA8"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"identifier":"doc://com.apple.opengles/documentation/OpenGLES/GL_SRGB8_ALPHA8","title":"GL_SRGB8_ALPHA8","abstract":[],"navigatorTitle":[{"text":"GL_SRGB8_ALPHA8","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"role":"symbol","url":"/documentation/Swift/Int32","abstract":[{"type":"text","text":"A 32-bit signed integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"title":"Int32","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"introducedAt":"2.0","beta":false,"unavailable":false,"deprecated":false,"name":"iOS"},{"introducedAt":"2.0","beta":false,"unavailable":false,"deprecated":false,"name":"iPadOS"},{"introducedAt":"2.0","beta":false,"unavailable":false,"deprecated":false,"name":"Mac Catalyst"},{"introducedAt":"9.0","beta":false,"unavailable":false,"deprecated":false,"name":"tvOS"},{"introducedAt":"1.0","beta":false,"unavailable":false,"deprecated":false,"name":"visionOS"}],"path":"/metadata/platforms"},{"op":"replace","value":"Macro","path":"/metadata/roleHeading"},{"op":"replace","value":"GL_SRGB8_ALPHA8","path":"/metadata/title"},{"op":"replace","value":"macro","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"GL_SRGB8_ALPHA8","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"add","value":null,"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"#define"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_SRGB8_ALPHA8"}],"platforms":["iOS","iPadOS","tvOS","visionOS"]}]},"path":"/primaryContentSections/0"},{"value":"GL_SRGB8_ALPHA8","op":"replace","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_SRGB8_ALPHA8/title"},{"value":[{"text":"GL_SRGB8_ALPHA8","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_SRGB8_ALPHA8/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}