{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.opengles/documentation/OpenGLES/GL_SPOT_EXPONENT"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/opengles/gl_spot_exponent"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/opengles/gl_spot_exponent"]}],"kind":"symbol","metadata":{"platforms":[{"deprecated":false,"unavailable":false,"introducedAt":"2.0","beta":false,"name":"iOS"},{"deprecated":false,"unavailable":false,"introducedAt":"2.0","beta":false,"name":"iPadOS"},{"deprecated":false,"unavailable":false,"introducedAt":"2.0","beta":false,"name":"Mac Catalyst"},{"deprecated":false,"unavailable":false,"introducedAt":"9.0","beta":false,"name":"tvOS"},{"deprecated":false,"unavailable":false,"introducedAt":"1.0","beta":false,"name":"visionOS"}],"externalID":"c:@macro@GL_SPOT_EXPONENT","title":"GL_SPOT_EXPONENT","role":"symbol","roleHeading":"Global Variable","navigatorTitle":[{"kind":"identifier","text":"GL_SPOT_EXPONENT"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_SPOT_EXPONENT"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"}],"modules":[{"name":"OpenGL ES"}],"symbolKind":"var"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_SPOT_EXPONENT"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","tvOS","visionOS"],"languages":["swift"]}]}],"sections":[],"references":{"doc://com.apple.opengles/documentation/OpenGLES/GL_SPOT_EXPONENT":{"identifier":"doc://com.apple.opengles/documentation/OpenGLES/GL_SPOT_EXPONENT","title":"GL_SPOT_EXPONENT","url":"/documentation/opengles/gl_spot_exponent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_SPOT_EXPONENT"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GL_SPOT_EXPONENT"}],"role":"symbol","type":"topic","abstract":[]},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"role":"symbol","url":"/documentation/Swift/Int32","abstract":[{"type":"text","text":"A 32-bit signed integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"title":"Int32","type":"topic"},"doc://com.apple.opengles/documentation/OpenGLES":{"type":"topic","kind":"symbol","url":"/documentation/opengles","identifier":"doc://com.apple.opengles/documentation/OpenGLES","title":"OpenGL ES","abstract":[{"type":"text","text":"Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL."}],"role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"introducedAt":"2.0","deprecated":false,"unavailable":false,"beta":false,"name":"iOS"},{"introducedAt":"2.0","deprecated":false,"unavailable":false,"beta":false,"name":"iPadOS"},{"introducedAt":"2.0","deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst"},{"introducedAt":"9.0","deprecated":false,"unavailable":false,"beta":false,"name":"tvOS"},{"name":"visionOS","introducedAt":"1.0","beta":false,"deprecated":false,"unavailable":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Macro"},{"op":"replace","path":"/metadata/title","value":"GL_SPOT_EXPONENT"},{"op":"replace","path":"/metadata/symbolKind","value":"macro"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"GL_SPOT_EXPONENT"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"add","path":"/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"#define"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_SPOT_EXPONENT"}]}]},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_SPOT_EXPONENT/title","value":"GL_SPOT_EXPONENT"},{"op":"replace","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_SPOT_EXPONENT/fragments","value":[{"text":"GL_SPOT_EXPONENT","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}