{"identifier":{"url":"doc://com.apple.opengles/documentation/OpenGLES/GL_STENCIL_BACK_PASS_DEPTH_PASS","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"OpenGL ES"}],"title":"GL_STENCIL_BACK_PASS_DEPTH_PASS","platforms":[{"name":"iOS","beta":false,"deprecated":false,"introducedAt":"2.0","unavailable":false},{"name":"iPadOS","deprecated":false,"beta":false,"unavailable":false,"introducedAt":"2.0"},{"name":"Mac Catalyst","deprecated":false,"beta":false,"unavailable":false,"introducedAt":"2.0"},{"name":"tvOS","deprecated":false,"beta":false,"unavailable":false,"introducedAt":"9.0"},{"name":"visionOS","deprecated":false,"beta":false,"unavailable":false,"introducedAt":"1.0"}],"navigatorTitle":[{"text":"GL_STENCIL_BACK_PASS_DEPTH_PASS","kind":"identifier"}],"role":"symbol","roleHeading":"Global Variable","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_STENCIL_BACK_PASS_DEPTH_PASS"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"}],"externalID":"c:@macro@GL_STENCIL_BACK_PASS_DEPTH_PASS","symbolKind":"var"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/opengles/gl_stencil_back_pass_depth_pass"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/opengles/gl_stencil_back_pass_depth_pass"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","tvOS","visionOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_STENCIL_BACK_PASS_DEPTH_PASS"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"sections":[],"references":{"doc://com.apple.opengles/documentation/OpenGLES":{"type":"topic","kind":"symbol","url":"/documentation/opengles","identifier":"doc://com.apple.opengles/documentation/OpenGLES","title":"OpenGL ES","abstract":[{"type":"text","text":"Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL."}],"role":"collection"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"role":"symbol","url":"/documentation/Swift/Int32","abstract":[{"type":"text","text":"A 32-bit signed integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"title":"Int32","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview"},"doc://com.apple.opengles/documentation/OpenGLES/GL_STENCIL_BACK_PASS_DEPTH_PASS":{"type":"topic","identifier":"doc://com.apple.opengles/documentation/OpenGLES/GL_STENCIL_BACK_PASS_DEPTH_PASS","title":"GL_STENCIL_BACK_PASS_DEPTH_PASS","url":"/documentation/opengles/gl_stencil_back_pass_depth_pass","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GL_STENCIL_BACK_PASS_DEPTH_PASS"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_STENCIL_BACK_PASS_DEPTH_PASS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"name":"iOS","beta":false,"deprecated":false,"introducedAt":"2.0","unavailable":false},{"name":"iPadOS","beta":false,"deprecated":false,"introducedAt":"2.0","unavailable":false},{"name":"Mac Catalyst","deprecated":false,"beta":false,"unavailable":false,"introducedAt":"2.0"},{"name":"tvOS","deprecated":false,"beta":false,"unavailable":false,"introducedAt":"9.0"},{"name":"visionOS","deprecated":false,"beta":false,"unavailable":false,"introducedAt":"1.0"}],"path":"/metadata/platforms","op":"replace"},{"value":"Macro","path":"/metadata/roleHeading","op":"replace"},{"value":"GL_STENCIL_BACK_PASS_DEPTH_PASS","path":"/metadata/title","op":"replace"},{"value":"macro","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"GL_STENCIL_BACK_PASS_DEPTH_PASS","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"op":"add","path":"/relationshipsSections","value":null},{"op":"add","path":"/seeAlsoSections","value":null},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"#define","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_STENCIL_BACK_PASS_DEPTH_PASS","kind":"identifier"}],"platforms":["iOS","iPadOS","tvOS","visionOS"]}],"kind":"declarations"}},{"op":"replace","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_STENCIL_BACK_PASS_DEPTH_PASS/title","value":"GL_STENCIL_BACK_PASS_DEPTH_PASS"},{"op":"replace","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_STENCIL_BACK_PASS_DEPTH_PASS/fragments","value":[{"text":"GL_STENCIL_BACK_PASS_DEPTH_PASS","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}