{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_TEXTURE_BINDING_3D"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["/documentation/opengles/gl_texture_binding_3d"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/opengles/gl_texture_binding_3d"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.opengles/documentation/OpenGLES/GL_TEXTURE_BINDING_3D"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"GL_TEXTURE_BINDING_3D"}],"role":"symbol","symbolKind":"var","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_TEXTURE_BINDING_3D"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"}],"platforms":[{"unavailable":false,"name":"iOS","introducedAt":"2.0","deprecated":false,"beta":false},{"unavailable":false,"name":"iPadOS","introducedAt":"2.0","deprecated":false,"beta":false},{"unavailable":false,"deprecated":false,"introducedAt":"2.0","beta":false,"name":"Mac Catalyst"},{"unavailable":false,"deprecated":false,"introducedAt":"9.0","beta":false,"name":"tvOS"},{"unavailable":false,"deprecated":false,"introducedAt":"1.0","beta":false,"name":"visionOS"}],"roleHeading":"Global Variable","modules":[{"name":"OpenGL ES"}],"externalID":"c:@macro@GL_TEXTURE_BINDING_3D","title":"GL_TEXTURE_BINDING_3D"},"kind":"symbol","references":{"doc://com.externally.resolved.symbol/s:s5Int32V":{"role":"symbol","url":"/documentation/Swift/Int32","abstract":[{"type":"text","text":"A 32-bit signed integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"title":"Int32","type":"topic"},"doc://com.apple.opengles/documentation/OpenGLES":{"type":"topic","kind":"symbol","url":"/documentation/opengles","identifier":"doc://com.apple.opengles/documentation/OpenGLES","title":"OpenGL ES","abstract":[{"type":"text","text":"Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL."}],"role":"collection"},"doc://com.apple.opengles/documentation/OpenGLES/GL_TEXTURE_BINDING_3D":{"url":"/documentation/opengles/gl_texture_binding_3d","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_TEXTURE_BINDING_3D","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"role":"symbol","type":"topic","title":"GL_TEXTURE_BINDING_3D","identifier":"doc://com.apple.opengles/documentation/OpenGLES/GL_TEXTURE_BINDING_3D","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"GL_TEXTURE_BINDING_3D","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"op":"replace","value":[{"unavailable":false,"name":"iOS","introducedAt":"2.0","deprecated":false,"beta":false},{"unavailable":false,"name":"iPadOS","introducedAt":"2.0","deprecated":false,"beta":false},{"unavailable":false,"name":"Mac Catalyst","introducedAt":"2.0","deprecated":false,"beta":false},{"introducedAt":"9.0","name":"tvOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"1.0","name":"visionOS","deprecated":false,"unavailable":false,"beta":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Macro","path":"/metadata/roleHeading"},{"op":"replace","value":"GL_TEXTURE_BINDING_3D","path":"/metadata/title"},{"value":"macro","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"GL_TEXTURE_BINDING_3D","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":null,"op":"add","path":"/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"#define","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_TEXTURE_BINDING_3D","kind":"identifier"}],"languages":["occ"],"platforms":["iOS","iPadOS","tvOS","visionOS"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":"GL_TEXTURE_BINDING_3D","op":"replace","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_TEXTURE_BINDING_3D/title"},{"value":[{"text":"GL_TEXTURE_BINDING_3D","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_TEXTURE_BINDING_3D/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}