{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_UNSIGNED_SHORT_5_5_5_1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","text":"Int32"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc://com.apple.opengles/documentation/OpenGLES/GL_UNSIGNED_SHORT_5_5_5_1","interfaceLanguage":"swift"},"variants":[{"paths":["/documentation/opengles/gl_unsigned_short_5_5_5_1"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/opengles/gl_unsigned_short_5_5_5_1"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"platforms":[{"deprecated":false,"beta":false,"introducedAt":"2.0","name":"iOS","unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"2.0","name":"iPadOS","unavailable":false},{"beta":false,"deprecated":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"2.0"},{"beta":false,"deprecated":false,"name":"tvOS","unavailable":false,"introducedAt":"9.0"},{"beta":false,"deprecated":false,"name":"visionOS","unavailable":false,"introducedAt":"1.0"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"GL_UNSIGNED_SHORT_5_5_5_1","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"title":"GL_UNSIGNED_SHORT_5_5_5_1","roleHeading":"Global Variable","navigatorTitle":[{"text":"GL_UNSIGNED_SHORT_5_5_5_1","kind":"identifier"}],"externalID":"c:@macro@GL_UNSIGNED_SHORT_5_5_5_1","modules":[{"name":"OpenGL ES"}],"role":"symbol","symbolKind":"var"},"kind":"symbol","sections":[],"references":{"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview"},"doc://com.apple.opengles/documentation/OpenGLES":{"type":"topic","kind":"symbol","url":"/documentation/opengles","identifier":"doc://com.apple.opengles/documentation/OpenGLES","title":"OpenGL ES","abstract":[{"type":"text","text":"Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL."}],"role":"collection"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"role":"symbol","url":"/documentation/Swift/Int32","abstract":[{"type":"text","text":"A 32-bit signed integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"title":"Int32","type":"topic"},"doc://com.apple.opengles/documentation/OpenGLES/GL_UNSIGNED_SHORT_5_5_5_1":{"abstract":[],"type":"topic","identifier":"doc://com.apple.opengles/documentation/OpenGLES/GL_UNSIGNED_SHORT_5_5_5_1","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_UNSIGNED_SHORT_5_5_5_1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"title":"GL_UNSIGNED_SHORT_5_5_5_1","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GL_UNSIGNED_SHORT_5_5_5_1"}],"url":"/documentation/opengles/gl_unsigned_short_5_5_5_1","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","value":[{"introducedAt":"2.0","deprecated":false,"name":"iOS","beta":false,"unavailable":false},{"introducedAt":"2.0","deprecated":false,"name":"iPadOS","beta":false,"unavailable":false},{"introducedAt":"2.0","deprecated":false,"name":"Mac Catalyst","beta":false,"unavailable":false},{"introducedAt":"9.0","beta":false,"unavailable":false,"name":"tvOS","deprecated":false},{"introducedAt":"1.0","beta":false,"unavailable":false,"name":"visionOS","deprecated":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Macro","op":"replace"},{"path":"/metadata/title","value":"GL_UNSIGNED_SHORT_5_5_5_1","op":"replace"},{"op":"replace","value":"macro","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"GL_UNSIGNED_SHORT_5_5_5_1","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":null,"op":"add","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"#define"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_UNSIGNED_SHORT_5_5_5_1"}],"platforms":["iOS","iPadOS","tvOS","visionOS"]}]},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","value":"GL_UNSIGNED_SHORT_5_5_5_1","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_UNSIGNED_SHORT_5_5_5_1/title"},{"op":"replace","value":[{"text":"GL_UNSIGNED_SHORT_5_5_5_1","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_UNSIGNED_SHORT_5_5_5_1/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}