{"metadata":{"symbolKind":"var","platforms":[{"deprecated":false,"unavailable":false,"introducedAt":"2.0","name":"iOS","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"2.0","name":"iPadOS","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"2.0","name":"Mac Catalyst","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"9.0","name":"tvOS","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"1.0","name":"visionOS","beta":false}],"externalID":"c:@macro@GL_UNSIGNED_SHORT_8_8_APPLE","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_UNSIGNED_SHORT_8_8_APPLE","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"GL_UNSIGNED_SHORT_8_8_APPLE","kind":"identifier"}],"role":"symbol","title":"GL_UNSIGNED_SHORT_8_8_APPLE","roleHeading":"Global Variable","modules":[{"name":"OpenGL ES"}]},"variants":[{"paths":["/documentation/opengles/gl_unsigned_short_8_8_apple"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/opengles/gl_unsigned_short_8_8_apple"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc://com.apple.opengles/documentation/OpenGLES/GL_UNSIGNED_SHORT_8_8_APPLE","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","tvOS","visionOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_UNSIGNED_SHORT_8_8_APPLE"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"references":{"doc://com.apple.opengles/documentation/OpenGLES":{"type":"topic","kind":"symbol","url":"/documentation/opengles","identifier":"doc://com.apple.opengles/documentation/OpenGLES","title":"OpenGL ES","abstract":[{"type":"text","text":"Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL."}],"role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"role":"symbol","url":"/documentation/Swift/Int32","abstract":[{"type":"text","text":"A 32-bit signed integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"title":"Int32","type":"topic"},"doc://com.apple.opengles/documentation/OpenGLES/GL_UNSIGNED_SHORT_8_8_APPLE":{"abstract":[],"title":"GL_UNSIGNED_SHORT_8_8_APPLE","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_UNSIGNED_SHORT_8_8_APPLE","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"type":"topic","identifier":"doc://com.apple.opengles/documentation/OpenGLES/GL_UNSIGNED_SHORT_8_8_APPLE","role":"symbol","navigatorTitle":[{"text":"GL_UNSIGNED_SHORT_8_8_APPLE","kind":"identifier"}],"url":"/documentation/opengles/gl_unsigned_short_8_8_apple","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"deprecated":false,"introducedAt":"2.0","beta":false,"name":"iOS"},{"unavailable":false,"deprecated":false,"introducedAt":"2.0","beta":false,"name":"iPadOS"},{"unavailable":false,"deprecated":false,"introducedAt":"2.0","beta":false,"name":"Mac Catalyst"},{"deprecated":false,"name":"tvOS","introducedAt":"9.0","beta":false,"unavailable":false},{"deprecated":false,"name":"visionOS","introducedAt":"1.0","beta":false,"unavailable":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Macro","path":"/metadata/roleHeading"},{"op":"replace","value":"GL_UNSIGNED_SHORT_8_8_APPLE","path":"/metadata/title"},{"op":"replace","value":"macro","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"GL_UNSIGNED_SHORT_8_8_APPLE"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"add","value":null,"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","tvOS","visionOS"],"tokens":[{"text":"#define","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_UNSIGNED_SHORT_8_8_APPLE","kind":"identifier"}],"languages":["occ"]}]},"path":"/primaryContentSections/0"},{"op":"replace","value":"GL_UNSIGNED_SHORT_8_8_APPLE","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_UNSIGNED_SHORT_8_8_APPLE/title"},{"op":"replace","value":[{"kind":"identifier","text":"GL_UNSIGNED_SHORT_8_8_APPLE"}],"path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_UNSIGNED_SHORT_8_8_APPLE/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}