{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/opengles/gl_uniform_block_index"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/opengles/gl_uniform_block_index"]}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"metadata":{"roleHeading":"Global Variable","role":"symbol","modules":[{"name":"OpenGL ES"}],"title":"GL_UNIFORM_BLOCK_INDEX","externalID":"c:@macro@GL_UNIFORM_BLOCK_INDEX","symbolKind":"var","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_UNIFORM_BLOCK_INDEX"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"navigatorTitle":[{"kind":"identifier","text":"GL_UNIFORM_BLOCK_INDEX"}],"platforms":[{"deprecated":false,"unavailable":false,"name":"iOS","introducedAt":"2.0","beta":false},{"beta":false,"deprecated":false,"introducedAt":"2.0","name":"iPadOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"2.0","name":"Mac Catalyst","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"9.0","name":"tvOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"1.0","name":"visionOS","unavailable":false}]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.opengles/documentation/OpenGLES/GL_UNIFORM_BLOCK_INDEX"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_UNIFORM_BLOCK_INDEX","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","tvOS","visionOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.opengles/documentation/OpenGLES/GL_UNIFORM_BLOCK_INDEX":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_UNIFORM_BLOCK_INDEX"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"kind":"symbol","abstract":[],"type":"topic","title":"GL_UNIFORM_BLOCK_INDEX","identifier":"doc://com.apple.opengles/documentation/OpenGLES/GL_UNIFORM_BLOCK_INDEX","url":"/documentation/opengles/gl_uniform_block_index","navigatorTitle":[{"kind":"identifier","text":"GL_UNIFORM_BLOCK_INDEX"}]},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview"},"doc://com.apple.opengles/documentation/OpenGLES":{"type":"topic","kind":"symbol","url":"/documentation/opengles","identifier":"doc://com.apple.opengles/documentation/OpenGLES","title":"OpenGL ES","abstract":[{"type":"text","text":"Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL."}],"role":"collection"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"role":"symbol","url":"/documentation/Swift/Int32","abstract":[{"type":"text","text":"A 32-bit signed integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"title":"Int32","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"value":[{"deprecated":false,"unavailable":false,"name":"iOS","introducedAt":"2.0","beta":false},{"deprecated":false,"unavailable":false,"name":"iPadOS","introducedAt":"2.0","beta":false},{"name":"Mac Catalyst","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"2.0"},{"name":"tvOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"9.0"},{"name":"visionOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"1.0"}],"op":"replace","path":"/metadata/platforms"},{"value":"Macro","path":"/metadata/roleHeading","op":"replace"},{"value":"GL_UNIFORM_BLOCK_INDEX","path":"/metadata/title","op":"replace"},{"value":"macro","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"GL_UNIFORM_BLOCK_INDEX"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":null,"path":"/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS","iPadOS","tvOS","visionOS"],"languages":["occ"],"tokens":[{"text":"#define","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_UNIFORM_BLOCK_INDEX","kind":"identifier"}]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"value":"GL_UNIFORM_BLOCK_INDEX","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_UNIFORM_BLOCK_INDEX/title","op":"replace"},{"value":[{"text":"GL_UNIFORM_BLOCK_INDEX","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_UNIFORM_BLOCK_INDEX/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}