{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","tvOS","visionOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_VERTEX_ATTRIB_ARRAY_NORMALIZED","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/opengles/gl_vertex_attrib_array_normalized"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/opengles/gl_vertex_attrib_array_normalized"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"role":"symbol","navigatorTitle":[{"text":"GL_VERTEX_ATTRIB_ARRAY_NORMALIZED","kind":"identifier"}],"modules":[{"name":"OpenGL ES"}],"title":"GL_VERTEX_ATTRIB_ARRAY_NORMALIZED","externalID":"c:@macro@GL_VERTEX_ATTRIB_ARRAY_NORMALIZED","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GL_VERTEX_ATTRIB_ARRAY_NORMALIZED","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"roleHeading":"Global Variable","symbolKind":"var","platforms":[{"introducedAt":"2.0","deprecated":false,"unavailable":false,"name":"iOS","beta":false},{"introducedAt":"2.0","deprecated":false,"unavailable":false,"name":"iPadOS","beta":false},{"introducedAt":"2.0","deprecated":false,"unavailable":false,"name":"Mac Catalyst","beta":false},{"introducedAt":"9.0","deprecated":false,"unavailable":false,"name":"tvOS","beta":false},{"name":"visionOS","beta":false,"deprecated":false,"introducedAt":"1.0","unavailable":false}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.opengles/documentation/OpenGLES/GL_VERTEX_ATTRIB_ARRAY_NORMALIZED"},"references":{"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview"},"doc://com.apple.opengles/documentation/OpenGLES":{"type":"topic","kind":"symbol","url":"/documentation/opengles","identifier":"doc://com.apple.opengles/documentation/OpenGLES","title":"OpenGL ES","abstract":[{"type":"text","text":"Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL."}],"role":"collection"},"doc://com.apple.opengles/documentation/OpenGLES/GL_VERTEX_ATTRIB_ARRAY_NORMALIZED":{"role":"symbol","identifier":"doc://com.apple.opengles/documentation/OpenGLES/GL_VERTEX_ATTRIB_ARRAY_NORMALIZED","title":"GL_VERTEX_ATTRIB_ARRAY_NORMALIZED","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GL_VERTEX_ATTRIB_ARRAY_NORMALIZED"}],"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_VERTEX_ATTRIB_ARRAY_NORMALIZED"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"url":"/documentation/opengles/gl_vertex_attrib_array_normalized","type":"topic"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"role":"symbol","url":"/documentation/Swift/Int32","abstract":[{"type":"text","text":"A 32-bit signed integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"title":"Int32","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"2.0","beta":false},{"introducedAt":"2.0","deprecated":false,"unavailable":false,"name":"iPadOS","beta":false},{"introducedAt":"2.0","deprecated":false,"unavailable":false,"name":"Mac Catalyst","beta":false},{"introducedAt":"9.0","deprecated":false,"unavailable":false,"name":"tvOS","beta":false},{"introducedAt":"1.0","deprecated":false,"unavailable":false,"name":"visionOS","beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Macro","op":"replace","path":"/metadata/roleHeading"},{"value":"GL_VERTEX_ATTRIB_ARRAY_NORMALIZED","op":"replace","path":"/metadata/title"},{"value":"macro","op":"replace","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"GL_VERTEX_ATTRIB_ARRAY_NORMALIZED","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"add","value":null,"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"#define"},{"kind":"text","text":" "},{"kind":"identifier","text":"GL_VERTEX_ATTRIB_ARRAY_NORMALIZED"}],"platforms":["iOS","iPadOS","tvOS","visionOS"],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"op":"replace","value":"GL_VERTEX_ATTRIB_ARRAY_NORMALIZED","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_VERTEX_ATTRIB_ARRAY_NORMALIZED/title"},{"op":"replace","value":[{"text":"GL_VERTEX_ATTRIB_ARRAY_NORMALIZED","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_VERTEX_ATTRIB_ARRAY_NORMALIZED/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}