{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"GLsizeiptr"},{"kind":"text","text":" = "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","identifier":"doc://com.externally.resolved.symbol/s:Si","text":"Int"}],"platforms":["iOS","iPadOS","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]},"metadata":{"modules":[{"name":"OpenGL ES"}],"externalID":"c:@T@GLsizeiptr","roleHeading":"Type Alias","platforms":[{"beta":false,"unavailable":false,"deprecated":false,"name":"iOS","introducedAt":"2.0"},{"beta":false,"unavailable":false,"deprecated":false,"name":"iPadOS","introducedAt":"2.0"},{"beta":false,"unavailable":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"2.0"},{"beta":false,"unavailable":false,"deprecated":false,"name":"tvOS","introducedAt":"9.0"},{"beta":false,"unavailable":false,"deprecated":false,"name":"visionOS","introducedAt":"1.0"}],"title":"GLsizeiptr","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"GLsizeiptr"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GLsizeiptr"}],"symbolKind":"typealias"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/opengles/glsizeiptr"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/opengles/glsizeiptr"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.opengles/documentation/OpenGLES/GLsizeiptr","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.apple.opengles/documentation/OpenGLES":{"type":"topic","kind":"symbol","url":"/documentation/opengles","identifier":"doc://com.apple.opengles/documentation/OpenGLES","title":"OpenGL ES","abstract":[{"type":"text","text":"Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL."}],"role":"collection"},"doc://com.externally.resolved.symbol/s:Si":{"kind":"symbol","url":"/documentation/Swift/Int","type":"topic","title":"Int","role":"symbol","abstract":[{"type":"text","text":"A signed integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:Si","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}]},"doc://com.apple.opengles/documentation/OpenGLES/GLsizeiptr":{"navigatorTitle":[{"kind":"identifier","text":"GLsizeiptr"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GLsizeiptr"}],"abstract":[],"type":"topic","title":"GLsizeiptr","identifier":"doc://com.apple.opengles/documentation/OpenGLES/GLsizeiptr","url":"/documentation/opengles/glsizeiptr","role":"symbol","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"2.0","name":"iOS"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"2.0","name":"iPadOS"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"2.0","name":"Mac Catalyst"},{"unavailable":false,"name":"tvOS","deprecated":false,"beta":false,"introducedAt":"9.0"},{"unavailable":false,"name":"visionOS","deprecated":false,"beta":false,"introducedAt":"1.0"}],"op":"replace","path":"/metadata/platforms"},{"value":"Type Alias","op":"replace","path":"/metadata/roleHeading"},{"value":"GLsizeiptr","op":"replace","path":"/metadata/title"},{"value":"typealias","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"GLsizeiptr"}],"op":"replace","path":"/metadata/fragments"},{"value":[{"text":"GLsizeiptr","kind":"identifier"}],"op":"replace","path":"/metadata/navigatorTitle"},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opengles/documentation/OpenGLES"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"add","path":"/seeAlsoSections","value":null},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"intptr_t","preciseIdentifier":"c:@T@intptr_t"},{"kind":"text","text":" "},{"kind":"identifier","text":"GLsizeiptr"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","tvOS","visionOS"]}],"kind":"declarations"}},{"op":"replace","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GLsizeiptr/title","value":"GLsizeiptr"},{"op":"replace","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GLsizeiptr/fragments","value":[{"text":"GLsizeiptr","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GLsizeiptr/navigatorTitle","value":[{"kind":"identifier","text":"GLsizeiptr"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}