{
  "abstract": [
    {
      "text": "The last call to request content authorization couldn’t be completed because another asset is currently attempting authorization.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/busy"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVContentAuthorizationStatus@AVContentAuthorizationBusy",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "busy"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVContentAuthorizationBusy"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AVContentAuthorizationStatus.busy"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "busy"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus": {
      "abstract": [
        {
          "text": "A value representing the status of a content authorization request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContentAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentAuthorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "AVContentAuthorizationStatus",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentauthorizationstatus"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/busy": {
      "abstract": [
        {
          "text": "The last call to request content authorization couldn’t be completed because another asset is currently attempting authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "busy"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/busy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentAuthorizationBusy"
        }
      ],
      "role": "symbol",
      "title": "AVContentAuthorizationStatus.busy",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentauthorizationstatus/busy"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/cancelled": {
      "abstract": [
        {
          "text": "The last call to request content authorization was cancelled by the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelled"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/cancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentAuthorizationCancelled"
        }
      ],
      "role": "symbol",
      "title": "AVContentAuthorizationStatus.cancelled",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentauthorizationstatus/cancelled"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/completed": {
      "abstract": [
        {
          "text": "The last completed call to request content authorization completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "completed"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/completed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentAuthorizationCompleted"
        }
      ],
      "role": "symbol",
      "title": "AVContentAuthorizationStatus.completed",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentauthorizationstatus/completed"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/notAvailable": {
      "abstract": [
        {
          "text": "The last call to request content authorization couldn’t be completed because there was no known mechanism by which to attempt authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notAvailable"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/notAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentAuthorizationNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "AVContentAuthorizationStatus.notAvailable",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentauthorizationstatus/notavailable"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/notPossible": {
      "abstract": [
        {
          "text": "The last call to request content authorization couldn’t be completed in a non-recoverable way.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notPossible"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/notPossible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentAuthorizationNotPossible"
        }
      ],
      "role": "symbol",
      "title": "AVContentAuthorizationStatus.notPossible",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentauthorizationstatus/notpossible"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/timedOut": {
      "abstract": [
        {
          "text": "The last call to request content authorization was cancelled because the timeout interval was reached.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timedOut"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/timedOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentAuthorizationTimedOut"
        }
      ],
      "role": "symbol",
      "title": "AVContentAuthorizationStatus.timedOut",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentauthorizationstatus/timedout"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/unknown": {
      "abstract": [
        {
          "text": "The content authorization content request hasn’t completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentAuthorizationUnknown"
        }
      ],
      "role": "symbol",
      "title": "AVContentAuthorizationStatus.unknown",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentauthorizationstatus/unknown"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Content-Authorization-Statuses",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/unknown",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/completed",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/cancelled",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/timedOut",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/notAvailable",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/notPossible"
      ],
      "title": "Content Authorization Statuses"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVContentAuthorizationBusy"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentAuthorizationBusy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Content-Authorization-Statuses",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/unknown",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/completed",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/cancelled",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/timedOut",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/notAvailable",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/notPossible"
              ],
              "title": "Content Authorization Statuses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "AVContentAuthorizationBusy"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus~1busy/title",
          "value": "AVContentAuthorizationBusy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus~1busy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentAuthorizationBusy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus/title",
          "value": "AVContentAuthorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus~1unknown/title",
          "value": "AVContentAuthorizationUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentAuthorizationUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus~1completed/title",
          "value": "AVContentAuthorizationCompleted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus~1completed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentAuthorizationCompleted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus~1timedOut/title",
          "value": "AVContentAuthorizationTimedOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus~1timedOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentAuthorizationTimedOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus~1cancelled/title",
          "value": "AVContentAuthorizationCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus~1cancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentAuthorizationCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus~1notPossible/title",
          "value": "AVContentAuthorizationNotPossible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus~1notPossible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentAuthorizationNotPossible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus~1notAvailable/title",
          "value": "AVContentAuthorizationNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus~1notAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentAuthorizationNotAvailable"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcontentauthorizationstatus/busy"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avcontentauthorizationstatus/busy"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
