{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/cssm_appledl_open_parameters-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/cssm_appledl_open_parameters-swift.struct/init(length:version:autoCommit:mask:mode:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So28cssm_appledl_open_parametersV6length7version10autoCommit4mask4modeABs6UInt32V_AIs5Int32VAIs6UInt16Vtcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "length"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@uint32",
        "text": "uint32"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "version"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@uint32",
        "text": "uint32"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "autoCommit"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CSSM_BOOL",
        "text": "CSSM_BOOL"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "mask"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@uint32",
        "text": "uint32"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "mode"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@mode_t",
        "text": "mode_t"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(length:version:autoCommit:mask:mode:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "length"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/uint32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint32",
              "text": "uint32"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "version"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/uint32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint32",
              "text": "uint32"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "autoCommit"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_BOOL",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_BOOL",
              "text": "CSSM_BOOL"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "mask"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/uint32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint32",
              "text": "uint32"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "mode"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@mode_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@mode_t",
              "text": "mode_t"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/CSSM_BOOL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_BOOL"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_BOOL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_BOOL"
        }
      ],
      "role": "symbol",
      "title": "CSSM_BOOL",
      "type": "topic",
      "url": "/documentation/security/cssm_bool"
    },
    "doc://com.apple.security/documentation/Security/cssm_appledl_open_parameters-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cssm_appledl_open_parameters"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_appledl_open_parameters-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cssm_appledl_open_parameters"
        }
      ],
      "role": "symbol",
      "title": "cssm_appledl_open_parameters",
      "type": "topic",
      "url": "/documentation/security/cssm_appledl_open_parameters-swift.struct"
    },
    "doc://com.apple.security/documentation/Security/cssm_appledl_open_parameters-swift.struct/init(length:version:autoCommit:mask:mode:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "length"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "autoCommit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CSSM_BOOL",
          "text": "CSSM_BOOL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@mode_t",
          "text": "mode_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_appledl_open_parameters-swift.struct/init(length:version:autoCommit:mask:mode:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(length:version:autoCommit:mask:mode:)",
      "type": "topic",
      "url": "/documentation/security/cssm_appledl_open_parameters-swift.struct/init(length:version:autocommit:mask:mode:)"
    },
    "doc://com.apple.security/documentation/Security/uint32": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uint32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/uint32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "uint32"
        }
      ],
      "role": "symbol",
      "title": "uint32",
      "type": "topic",
      "url": "/documentation/security/uint32"
    },
    "doc://com.externally.resolved.symbol/c:@T@mode_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@mode_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "mode_t",
      "type": "topic",
      "url": "/documentation/kernel/mode_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1uint32/title",
          "value": "uint32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1uint32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "uint32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1uint32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "uint32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_appledl_open_parameters-swift.struct/title",
          "value": "cssm_appledl_open_parameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_appledl_open_parameters-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_appledl_open_parameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_appledl_open_parameters-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_appledl_open_parameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_BOOL/title",
          "value": "CSSM_BOOL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_BOOL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_BOOL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_BOOL/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_BOOL"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/cssm_appledl_open_parameters-swift.struct/init(length:version:autocommit:mask:mode:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
