{
  "abstract": [
    {
      "text": "The persistent history changes since the requested date, token, or transaction.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResultType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResultType/changesOnly"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSPersistentHistoryResultType@NSPersistentHistoryResultTypeChangesOnly",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "changesOnly"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSPersistentHistoryResultTypeChangesOnly"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSPersistentHistoryResultType.changesOnly"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "changesOnly"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResultType": {
      "abstract": [
        {
          "text": "The types of results from a persistent history change request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentHistoryResultType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResultType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentHistoryResultType"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentHistoryResultType",
      "type": "topic",
      "url": "/documentation/coredata/nspersistenthistoryresulttype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResultType/changesOnly": {
      "abstract": [
        {
          "text": "The persistent history changes since the requested date, token, or transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changesOnly"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResultType/changesOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentHistoryResultTypeChangesOnly"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentHistoryResultType.changesOnly",
      "type": "topic",
      "url": "/documentation/coredata/nspersistenthistoryresulttype/changesonly"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResultType/count": {
      "abstract": [
        {
          "text": "The number of persistent history changes since the requested date, token, or transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "count"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResultType/count",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentHistoryResultTypeCount"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentHistoryResultType.count",
      "type": "topic",
      "url": "/documentation/coredata/nspersistenthistoryresulttype/count"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResultType/objectIDs": {
      "abstract": [
        {
          "text": "The identifiers of managed objects changed since the requested date, token, or transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "objectIDs"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResultType/objectIDs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentHistoryResultTypeObjectIDs"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentHistoryResultType.objectIDs",
      "type": "topic",
      "url": "/documentation/coredata/nspersistenthistoryresulttype/objectids"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResultType/statusOnly": {
      "abstract": [
        {
          "text": "The status of the persistent history change request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusOnly"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResultType/statusOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentHistoryResultTypeStatusOnly"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentHistoryResultType.statusOnly",
      "type": "topic",
      "url": "/documentation/coredata/nspersistenthistoryresulttype/statusonly"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResultType/transactionsAndChanges": {
      "abstract": [
        {
          "text": "The persistent history transactions and changes since the requested date, token, or transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transactionsAndChanges"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResultType/transactionsAndChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentHistoryResultTypeTransactionsAndChanges"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentHistoryResultType.transactionsAndChanges",
      "type": "topic",
      "url": "/documentation/coredata/nspersistenthistoryresulttype/transactionsandchanges"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResultType/transactionsOnly": {
      "abstract": [
        {
          "text": "The persistent history transactions since the requested date, token, or transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transactionsOnly"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResultType/transactionsOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentHistoryResultTypeTransactionsOnly"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentHistoryResultType.transactionsOnly",
      "type": "topic",
      "url": "/documentation/coredata/nspersistenthistoryresulttype/transactionsonly"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Result-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResultType/statusOnly",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResultType/count",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResultType/objectIDs",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResultType/transactionsAndChanges",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResultType/transactionsOnly"
      ],
      "title": "Result Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSPersistentHistoryResultTypeChangesOnly"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentHistoryResultTypeChangesOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coredata/documentation/CoreData",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResultType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Result-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResultType/statusOnly",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResultType/count",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResultType/objectIDs",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResultType/transactionsAndChanges",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResultType/transactionsOnly"
              ],
              "title": "Result Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSPersistentHistoryResultTypeChangesOnly"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryResultType~1count/title",
          "value": "NSPersistentHistoryResultTypeCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryResultType~1count/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentHistoryResultTypeCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryResultType~1objectIDs/title",
          "value": "NSPersistentHistoryResultTypeObjectIDs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryResultType~1objectIDs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentHistoryResultTypeObjectIDs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryResultType/title",
          "value": "NSPersistentHistoryResultType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryResultType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentHistoryResultType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryResultType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentHistoryResultType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryResultType~1changesOnly/title",
          "value": "NSPersistentHistoryResultTypeChangesOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryResultType~1changesOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentHistoryResultTypeChangesOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryResultType~1statusOnly/title",
          "value": "NSPersistentHistoryResultTypeStatusOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryResultType~1statusOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentHistoryResultTypeStatusOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryResultType~1transactionsAndChanges/title",
          "value": "NSPersistentHistoryResultTypeTransactionsAndChanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryResultType~1transactionsAndChanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentHistoryResultTypeTransactionsAndChanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryResultType~1transactionsOnly/title",
          "value": "NSPersistentHistoryResultTypeTransactionsOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryResultType~1transactionsOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentHistoryResultTypeTransactionsOnly"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nspersistenthistoryresulttype/changesonly"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/nspersistenthistoryresulttype/changesonly"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
