{
  "abstract": [
    {
      "text": "Creates and returns a dragging image component with the specified key.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingImageComponent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSDraggingImageComponent/draggingImageComponentWithKey:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSDraggingImageComponent(cm)draggingImageComponentWithKey:",
    "fragments": [
      {
        "kind": "text",
        "text": "+ "
      },
      {
        "kind": "identifier",
        "text": "draggingImageComponentWithKey:"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "draggingImageComponentWithKey:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "draggingImageComponentWithKey:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingImageComponent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSDraggingImageComponent",
              "text": "NSDraggingImageComponent"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "identifier",
              "text": "draggingImageComponentWithKey:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingItem/ImageComponentKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSDraggingImageComponentKey",
              "text": "NSDraggingImageComponentKey"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "key"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The key.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "key"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A dragging image component with the specified key.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingImageComponent": {
      "abstract": [
        {
          "text": "A single object in a dragging item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDraggingImageComponent"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingImageComponent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDraggingImageComponent"
        }
      ],
      "role": "symbol",
      "title": "NSDraggingImageComponent",
      "type": "topic",
      "url": "/documentation/appkit/nsdraggingimagecomponent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingImageComponent/draggingImageComponentWithKey:": {
      "abstract": [
        {
          "text": "Creates and returns a dragging image component with the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "draggingImageComponentWithKey:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingImageComponent/draggingImageComponentWithKey:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "draggingImageComponentWithKey:"
        }
      ],
      "role": "symbol",
      "title": "draggingImageComponentWithKey:",
      "type": "topic",
      "url": "/documentation/appkit/nsdraggingimagecomponent/draggingimagecomponentwithkey:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingImageComponent/init(key:)": {
      "abstract": [
        {
          "text": "Initializes and returns a dragging image component with the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "key"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDraggingItem",
          "text": "NSDraggingItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSDraggingImageComponentKey",
          "text": "ImageComponentKey"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingImageComponent/init(key:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithKey:"
        }
      ],
      "role": "symbol",
      "title": "init(key:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdraggingimagecomponent/init(key:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingItem/ImageComponentKey": {
      "abstract": [
        {
          "text": "Keys that identify components of a dragging image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ImageComponentKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingItem/ImageComponentKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ImageComponentKey"
        }
      ],
      "role": "symbol",
      "title": "NSDraggingItem.ImageComponentKey",
      "type": "topic",
      "url": "/documentation/appkit/nsdraggingitem/imagecomponentkey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Dragging-Image-Component",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingImageComponent/init(key:)"
      ],
      "title": "Creating a Dragging Image Component"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingImageComponent/title",
          "value": "NSDraggingImageComponent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingImageComponent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingImageComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingImageComponent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingImageComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingImageComponent~1init(key:)/title",
          "value": "initWithKey:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingImageComponent~1init(key:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithKey:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingItem~1ImageComponentKey/title",
          "value": "NSDraggingImageComponentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingItem~1ImageComponentKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingImageComponentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingItem~1ImageComponentKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingImageComponentKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsdraggingimagecomponent/draggingimagecomponentwithkey:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
