{
  "abstract": [
    {
      "text": "Converts device-independent temperature and tint values to device-specific white balance RGB gain values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/deviceWhiteBalanceGains(for:)-3wtsa"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "c:objc(cs)AVCaptureDevice(im)deviceWhiteBalanceGainsForTemperatureAndTintValues:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "deviceWhiteBalanceGains"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "for"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
        "text": "AVCaptureDevice"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@AVCaptureWhiteBalanceTemperatureAndTintValues",
        "text": "WhiteBalanceTemperatureAndTintValues"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
        "text": "AVCaptureDevice"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@AVCaptureWhiteBalanceGains",
        "text": "WhiteBalanceGains"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "deviceWhiteBalanceGainsForTemperatureAndTintValues:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "deviceWhiteBalanceGains(for:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "deviceWhiteBalanceGains"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "tempAndTintValues"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
              "text": "AVCaptureDevice"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/WhiteBalanceTemperatureAndTintValues",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@AVCaptureWhiteBalanceTemperatureAndTintValues",
              "text": "WhiteBalanceTemperatureAndTintValues"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
              "text": "AVCaptureDevice"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/WhiteBalanceGains",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@AVCaptureWhiteBalanceGains",
              "text": "WhiteBalanceGains"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/WhiteBalanceTemperatureAndTintValues",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " structure containing the temperature and tint values.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "tempAndTintValues"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A fully populated ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/WhiteBalanceGains",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " structure containing device-specific RGB gain values.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Call this method to convert device-independent temperature and tint values to device-specific RGB white balance gain values.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You may pass any temperature and tint values and corresponding white balance gains will be produced. Note, though, that some temperature and tint combinations yield out-of-range device RGB values that will cause an exception to be thrown if passed directly to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/setWhiteBalanceModeLocked(with:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".  Be sure to verify that the red, green, and blue gain values are within the range of [",
              "type": "text"
            },
            {
              "code": "1.0",
              "type": "codeVoice"
            },
            {
              "text": " - ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/maxWhiteBalanceGain",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "].",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice": {
      "abstract": [
        {
          "text": "An object that represents a hardware or virtual capture device like a camera or microphone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureDevice"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureDevice"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDevice",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/WhiteBalanceChromaticityValues": {
      "abstract": [
        {
          "text": "A structure that defines CIE 1931 xy chromaticity values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WhiteBalanceChromaticityValues"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/WhiteBalanceChromaticityValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WhiteBalanceChromaticityValues"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDevice.WhiteBalanceChromaticityValues",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/whitebalancechromaticityvalues"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/WhiteBalanceGains": {
      "abstract": [
        {
          "text": "A structure that defines RGB white balance gain values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WhiteBalanceGains"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/WhiteBalanceGains",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WhiteBalanceGains"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDevice.WhiteBalanceGains",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/whitebalancegains"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/WhiteBalanceTemperatureAndTintValues": {
      "abstract": [
        {
          "text": "A structure that defines temperature and tint values correlated to a white-balance color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WhiteBalanceTemperatureAndTintValues"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/WhiteBalanceTemperatureAndTintValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WhiteBalanceTemperatureAndTintValues"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDevice.WhiteBalanceTemperatureAndTintValues",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/whitebalancetemperatureandtintvalues"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/chromaticityValues(for:)": {
      "abstract": [
        {
          "text": "Converts device-specific white balance RGB gain values to device-independent chromaticity values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "chromaticityValues"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@AVCaptureWhiteBalanceGains",
          "text": "WhiteBalanceGains"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@AVCaptureWhiteBalanceChromaticityValues",
          "text": "WhiteBalanceChromaticityValues"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/chromaticityValues(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "chromaticityValuesForDeviceWhiteBalanceGains:"
        }
      ],
      "role": "symbol",
      "title": "chromaticityValues(for:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/chromaticityvalues(for:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/deviceWhiteBalanceGains(for:)-3wtsa": {
      "abstract": [
        {
          "text": "Converts device-independent temperature and tint values to device-specific white balance RGB gain values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceWhiteBalanceGains"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@AVCaptureWhiteBalanceTemperatureAndTintValues",
          "text": "WhiteBalanceTemperatureAndTintValues"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@AVCaptureWhiteBalanceGains",
          "text": "WhiteBalanceGains"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/deviceWhiteBalanceGains(for:)-3wtsa",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceWhiteBalanceGainsForTemperatureAndTintValues:"
        }
      ],
      "role": "symbol",
      "title": "deviceWhiteBalanceGains(for:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/devicewhitebalancegains(for:)-3wtsa"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/deviceWhiteBalanceGains(for:)-9gdtw": {
      "abstract": [
        {
          "text": "Converts device-independent chromaticity values to device-specific white balance RGB gain values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceWhiteBalanceGains"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@AVCaptureWhiteBalanceChromaticityValues",
          "text": "WhiteBalanceChromaticityValues"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@AVCaptureWhiteBalanceGains",
          "text": "WhiteBalanceGains"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/deviceWhiteBalanceGains(for:)-9gdtw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceWhiteBalanceGainsForChromaticityValues:"
        }
      ],
      "role": "symbol",
      "title": "deviceWhiteBalanceGains(for:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/devicewhitebalancegains(for:)-9gdtw"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/maxWhiteBalanceGain": {
      "abstract": [
        {
          "text": "The maximum supported value to which you can set a color channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxWhiteBalanceGain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/maxWhiteBalanceGain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxWhiteBalanceGain"
        }
      ],
      "role": "symbol",
      "title": "maxWhiteBalanceGain",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/maxwhitebalancegain"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/setWhiteBalanceModeLocked(with:completionHandler:)": {
      "abstract": [
        {
          "text": "Sets the white balance to locked mode with the specified white balance gains.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setWhiteBalanceModeLocked"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@AVCaptureWhiteBalanceGains",
          "text": "WhiteBalanceGains"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/setWhiteBalanceModeLocked(with:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setWhiteBalanceModeLockedWithDeviceWhiteBalanceGains:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "setWhiteBalanceModeLocked(with:completionHandler:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/setwhitebalancemodelocked(with:completionhandler:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/temperatureAndTintValues(for:)": {
      "abstract": [
        {
          "text": "Converts device-specific white balance RGB gain values to device-independent temperature and tint values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "temperatureAndTintValues"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@AVCaptureWhiteBalanceGains",
          "text": "WhiteBalanceGains"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@AVCaptureWhiteBalanceTemperatureAndTintValues",
          "text": "WhiteBalanceTemperatureAndTintValues"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/temperatureAndTintValues(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "temperatureAndTintValuesForDeviceWhiteBalanceGains:"
        }
      ],
      "role": "symbol",
      "title": "temperatureAndTintValues(for:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/temperatureandtintvalues(for:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Performing-Conversions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/chromaticityValues(for:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/temperatureAndTintValues(for:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/deviceWhiteBalanceGains(for:)-9gdtw",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/WhiteBalanceGains",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/WhiteBalanceChromaticityValues",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/WhiteBalanceTemperatureAndTintValues"
      ],
      "title": "Performing Conversions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "deviceWhiteBalanceGainsForTemperatureAndTintValues:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deviceWhiteBalanceGainsForTemperatureAndTintValues:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Performing-Conversions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/chromaticityValues(for:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/temperatureAndTintValues(for:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/deviceWhiteBalanceGains(for:)-9gdtw",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/WhiteBalanceGains",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/WhiteBalanceChromaticityValues",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/WhiteBalanceTemperatureAndTintValues"
              ],
              "title": "Performing Conversions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/WhiteBalanceGains",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@AVCaptureWhiteBalanceGains",
                    "text": "AVCaptureWhiteBalanceGains"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "deviceWhiteBalanceGainsForTemperatureAndTintValues:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/WhiteBalanceTemperatureAndTintValues",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@AVCaptureWhiteBalanceTemperatureAndTintValues",
                    "text": "AVCaptureWhiteBalanceTemperatureAndTintValues"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "tempAndTintValues"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/WhiteBalanceTemperatureAndTintValues",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " structure containing the temperature and tint values.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "tempAndTintValues"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A fully populated ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/WhiteBalanceGains",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " structure containing device-specific RGB gain values.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/title",
          "value": "AVCaptureDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1deviceWhiteBalanceGains(for:)-9gdtw/title",
          "value": "deviceWhiteBalanceGainsForChromaticityValues:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1deviceWhiteBalanceGains(for:)-9gdtw/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deviceWhiteBalanceGainsForChromaticityValues:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1chromaticityValues(for:)/title",
          "value": "chromaticityValuesForDeviceWhiteBalanceGains:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1chromaticityValues(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "chromaticityValuesForDeviceWhiteBalanceGains:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1setWhiteBalanceModeLocked(with:completionHandler:)/title",
          "value": "setWhiteBalanceModeLockedWithDeviceWhiteBalanceGains:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1setWhiteBalanceModeLocked(with:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setWhiteBalanceModeLockedWithDeviceWhiteBalanceGains:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1temperatureAndTintValues(for:)/title",
          "value": "temperatureAndTintValuesForDeviceWhiteBalanceGains:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1temperatureAndTintValues(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "temperatureAndTintValuesForDeviceWhiteBalanceGains:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1WhiteBalanceChromaticityValues/title",
          "value": "AVCaptureWhiteBalanceChromaticityValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1WhiteBalanceChromaticityValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureWhiteBalanceChromaticityValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1WhiteBalanceChromaticityValues/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureWhiteBalanceChromaticityValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1WhiteBalanceTemperatureAndTintValues/title",
          "value": "AVCaptureWhiteBalanceTemperatureAndTintValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1WhiteBalanceTemperatureAndTintValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureWhiteBalanceTemperatureAndTintValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1WhiteBalanceTemperatureAndTintValues/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureWhiteBalanceTemperatureAndTintValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1WhiteBalanceGains/title",
          "value": "AVCaptureWhiteBalanceGains"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1WhiteBalanceGains/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureWhiteBalanceGains"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1WhiteBalanceGains/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureWhiteBalanceGains"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1deviceWhiteBalanceGains(for:)-3wtsa/title",
          "value": "deviceWhiteBalanceGainsForTemperatureAndTintValues:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1deviceWhiteBalanceGains(for:)-3wtsa/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deviceWhiteBalanceGainsForTemperatureAndTintValues:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1maxWhiteBalanceGain/title",
          "value": "maxWhiteBalanceGain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1maxWhiteBalanceGain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxWhiteBalanceGain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcapturedevice/devicewhitebalancegains(for:)-3wtsa"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avcapturedevice/devicewhitebalancegains(for:)-3wtsa"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
