{
  "abstract": [
    {
      "text": "Returns a Boolean value that indicates whether the device supports the specified focus mode.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isFocusModeSupported(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "c:objc(cs)AVCaptureDevice(im)isFocusModeSupported:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "isFocusModeSupported"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
        "text": "AVCaptureDevice"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AVCaptureFocusMode",
        "text": "FocusMode"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "isFocusModeSupported:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "isFocusModeSupported(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "isFocusModeSupported"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "focusMode"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
              "text": "AVCaptureDevice"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/FocusMode-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AVCaptureFocusMode",
              "text": "FocusMode"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A focus mode to query.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "focusMode"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " if the device supports the focus mode; otherwise, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice": {
      "abstract": [
        {
          "text": "An object that represents a hardware or virtual capture device like a camera or microphone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureDevice"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureDevice"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDevice",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/AutoFocusRangeRestriction-swift.enum": {
      "abstract": [
        {
          "text": "Constants to specify the autofocus range of a capture device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AutoFocusRangeRestriction"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/AutoFocusRangeRestriction-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AutoFocusRangeRestriction"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDevice.AutoFocusRangeRestriction",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/autofocusrangerestriction-swift.enum"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/FocusMode-swift.enum": {
      "abstract": [
        {
          "text": "Constants to specify the focus mode of a capture device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FocusMode"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/FocusMode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FocusMode"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDevice.FocusMode",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/focusmode-swift.enum"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/autoFocusRangeRestriction-swift.property": {
      "abstract": [
        {
          "text": "A value that controls the allowable range for automatic focusing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autoFocusRangeRestriction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVCaptureAutoFocusRangeRestriction",
          "text": "AutoFocusRangeRestriction"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/autoFocusRangeRestriction-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "autoFocusRangeRestriction"
        }
      ],
      "role": "symbol",
      "title": "autoFocusRangeRestriction",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/autofocusrangerestriction-swift.property"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/automaticallyAdjustsFaceDrivenAutoFocusEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the device automatically adjusts face-driven autofocus.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automaticallyAdjustsFaceDrivenAutoFocusEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/automaticallyAdjustsFaceDrivenAutoFocusEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticallyAdjustsFaceDrivenAutoFocusEnabled"
        }
      ],
      "role": "symbol",
      "title": "automaticallyAdjustsFaceDrivenAutoFocusEnabled",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/automaticallyadjustsfacedrivenautofocusenabled"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/focusMode-swift.property": {
      "abstract": [
        {
          "text": "The capture device’s focus mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "focusMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVCaptureFocusMode",
          "text": "FocusMode"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/focusMode-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "focusMode"
        }
      ],
      "role": "symbol",
      "title": "focusMode",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/focusmode-swift.property"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isAutoFocusRangeRestrictionSupported": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the device supports focus range restrictions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAutoFocusRangeRestrictionSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isAutoFocusRangeRestrictionSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "autoFocusRangeRestrictionSupported"
        }
      ],
      "role": "symbol",
      "title": "isAutoFocusRangeRestrictionSupported",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/isautofocusrangerestrictionsupported"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isFaceDrivenAutoFocusEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the device has face-driven autofocus enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isFaceDrivenAutoFocusEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isFaceDrivenAutoFocusEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "faceDrivenAutoFocusEnabled"
        }
      ],
      "role": "symbol",
      "title": "isFaceDrivenAutoFocusEnabled",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/isfacedrivenautofocusenabled"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isFocusModeSupported(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the device supports the specified focus mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isFocusModeSupported"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVCaptureFocusMode",
          "text": "FocusMode"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isFocusModeSupported(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isFocusModeSupported:"
        }
      ],
      "role": "symbol",
      "title": "isFocusModeSupported(_:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/isfocusmodesupported(_:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isSmoothAutoFocusEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether smooth autofocus is in an enabled state on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSmoothAutoFocusEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isSmoothAutoFocusEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "smoothAutoFocusEnabled"
        }
      ],
      "role": "symbol",
      "title": "isSmoothAutoFocusEnabled",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/issmoothautofocusenabled"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isSmoothAutoFocusSupported": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the device supports smooth autofocus.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSmoothAutoFocusSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isSmoothAutoFocusSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "smoothAutoFocusSupported"
        }
      ],
      "role": "symbol",
      "title": "isSmoothAutoFocusSupported",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/issmoothautofocussupported"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Automatic-Focus",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/focusMode-swift.property",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/FocusMode-swift.enum",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isSmoothAutoFocusSupported",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isSmoothAutoFocusEnabled",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isFaceDrivenAutoFocusEnabled",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/automaticallyAdjustsFaceDrivenAutoFocusEnabled",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isAutoFocusRangeRestrictionSupported",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/autoFocusRangeRestriction-swift.property",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/AutoFocusRangeRestriction-swift.enum"
      ],
      "title": "Configuring Automatic Focus"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "isFocusModeSupported:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "isFocusModeSupported:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Automatic-Focus",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/focusMode-swift.property",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/FocusMode-swift.enum",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isSmoothAutoFocusSupported",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isSmoothAutoFocusEnabled",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isFaceDrivenAutoFocusEnabled",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/automaticallyAdjustsFaceDrivenAutoFocusEnabled",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isAutoFocusRangeRestrictionSupported",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/autoFocusRangeRestriction-swift.property",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/AutoFocusRangeRestriction-swift.enum"
              ],
              "title": "Configuring Automatic Focus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "isFocusModeSupported:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/FocusMode-swift.enum",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@AVCaptureFocusMode",
                    "text": "AVCaptureFocusMode"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "focusMode"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A focus mode to query.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "focusMode"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/swift/true",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " if the device supports the focus mode; otherwise, ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/swift/false",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isFaceDrivenAutoFocusEnabled/title",
          "value": "faceDrivenAutoFocusEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isFaceDrivenAutoFocusEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "faceDrivenAutoFocusEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isSmoothAutoFocusEnabled/title",
          "value": "smoothAutoFocusEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isSmoothAutoFocusEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "smoothAutoFocusEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1focusMode-swift.property/title",
          "value": "focusMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1focusMode-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "focusMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1automaticallyAdjustsFaceDrivenAutoFocusEnabled/title",
          "value": "automaticallyAdjustsFaceDrivenAutoFocusEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1automaticallyAdjustsFaceDrivenAutoFocusEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticallyAdjustsFaceDrivenAutoFocusEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1autoFocusRangeRestriction-swift.property/title",
          "value": "autoFocusRangeRestriction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1autoFocusRangeRestriction-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "autoFocusRangeRestriction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1AutoFocusRangeRestriction-swift.enum/title",
          "value": "AVCaptureAutoFocusRangeRestriction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1AutoFocusRangeRestriction-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureAutoFocusRangeRestriction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1AutoFocusRangeRestriction-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureAutoFocusRangeRestriction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1FocusMode-swift.enum/title",
          "value": "AVCaptureFocusMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1FocusMode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureFocusMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1FocusMode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureFocusMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isSmoothAutoFocusSupported/title",
          "value": "smoothAutoFocusSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isSmoothAutoFocusSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "smoothAutoFocusSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isFocusModeSupported(_:)/title",
          "value": "isFocusModeSupported:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isFocusModeSupported(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "isFocusModeSupported:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/title",
          "value": "AVCaptureDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isAutoFocusRangeRestrictionSupported/title",
          "value": "autoFocusRangeRestrictionSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isAutoFocusRangeRestrictionSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "autoFocusRangeRestrictionSupported"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcapturedevice/isfocusmodesupported(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avcapturedevice/isfocusmodesupported(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
