{"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"inUseByAnotherApplication"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInUseByAnotherApplication"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isInUseByAnotherApplication","externalID":"c:objc(cs)AVCaptureDevice(py)inUseByAnotherApplication","roleHeading":"Instance Property","platforms":[{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"14.0","name":"Mac Catalyst"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"10.7","name":"macOS"}],"modules":[{"name":"AVFoundation"}],"role":"symbol","symbolKind":"property"},"variants":[{"paths":["/documentation/avfoundation/avcapturedevice/isinusebyanotherapplication"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/avfoundation/avcapturedevice/isinusebyanotherapplication"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"A Boolean value that indicates whether another app is using the device.","type":"text"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isInUseByAnotherApplication","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Sb","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["Mac Catalyst","macOS"]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This property is key-value observable."}]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isInUseByAnotherApplication"},"seeAlsoSections":[{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isConnected","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isSuspended"],"title":"Accessing Device State","generated":true,"anchor":"Accessing-Device-State"}],"references":{"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/s:Sb":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"type":"topic","title":"Bool","url":"/documentation/Swift/Bool","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isSuspended":{"navigatorTitle":[{"kind":"identifier","text":"suspended"}],"url":"/documentation/avfoundation/avcapturedevice/issuspended","abstract":[{"type":"text","text":"A Boolean value that indicates whether the device is in a suspended state."}],"kind":"symbol","title":"isSuspended","role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isSuspended","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSuspended"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","title":"BOOL","url":"/documentation/objectivec/bool","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice":{"url":"/documentation/avfoundation/avcapturedevice","title":"AVCaptureDevice","abstract":[{"text":"An object that represents a hardware or virtual capture device like a camera or microphone.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVCaptureDevice","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVCaptureDevice","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isConnected":{"navigatorTitle":[{"kind":"identifier","text":"connected"}],"url":"/documentation/avfoundation/avcapturedevice/isconnected","abstract":[{"type":"text","text":"A Boolean value that indicates whether a device is currently connected to the system and available for use."}],"kind":"symbol","title":"isConnected","role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isConnected","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isConnected"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isInUseByAnotherApplication":{"navigatorTitle":[{"kind":"identifier","text":"inUseByAnotherApplication"}],"url":"/documentation/avfoundation/avcapturedevice/isinusebyanotherapplication","abstract":[{"type":"text","text":"A Boolean value that indicates whether another app is using the device."}],"kind":"symbol","title":"isInUseByAnotherApplication","role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isInUseByAnotherApplication","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInUseByAnotherApplication"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"unavailable":false,"introducedAt":"14.0","deprecated":false,"beta":false,"name":"Mac Catalyst"},{"unavailable":false,"introducedAt":"10.7","deprecated":false,"beta":false,"name":"macOS"}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Property","path":"/metadata/roleHeading","op":"replace"},{"value":"inUseByAnotherApplication","path":"/metadata/title","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"inUseByAnotherApplication"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"generated":true,"anchor":"Accessing-Device-State","title":"Accessing Device State","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isConnected","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isSuspended"]}],"op":"replace"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":", "},{"kind":"keyword","text":"getter"},{"kind":"text","text":"="},{"kind":"identifier","text":"isInUseByAnotherApplication"},{"kind":"text","text":") "},{"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"inUseByAnotherApplication"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}]},"path":"/primaryContentSections/0","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isSuspended/title","value":"suspended","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isSuspended/fragments","value":[{"text":"suspended","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/title","value":"AVCaptureDevice","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/fragments","value":[{"kind":"identifier","text":"AVCaptureDevice"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/navigatorTitle","value":[{"text":"AVCaptureDevice","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isConnected/title","value":"connected","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isConnected/fragments","value":[{"kind":"identifier","text":"connected"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isInUseByAnotherApplication/title","value":"inUseByAnotherApplication","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isInUseByAnotherApplication/fragments","value":[{"kind":"identifier","text":"inUseByAnotherApplication"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}