{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","identifier":"doc://com.externally.resolved.symbol/s:SS","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice"]]},"abstract":[{"text":"A localized device name for display in the user interface.","type":"text"}],"seeAlsoSections":[{"anchor":"Identifying-a-Device","title":"Identifying a Device","generated":true,"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/uniqueID","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/modelID","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/manufacturer","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/deviceType-swift.property","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/DeviceType-swift.struct","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/position-swift.property","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Position-swift.enum"]}],"variants":[{"paths":["/documentation/avfoundation/avcapturedevice/localizedname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/avfoundation/avcapturedevice/localizedname"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:objc(cs)AVCaptureDevice(py)localizedName","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"localizedName"}],"modules":[{"name":"AVFoundation"}],"platforms":[{"introducedAt":"4.0","name":"iOS","beta":false,"deprecated":false,"unavailable":false},{"introducedAt":"4.0","name":"iPadOS","beta":false,"deprecated":false,"unavailable":false},{"introducedAt":"14.0","name":"Mac Catalyst","beta":false,"deprecated":false,"unavailable":false},{"introducedAt":"10.7","name":"macOS","beta":false,"deprecated":false,"unavailable":false},{"introducedAt":"17.0","name":"tvOS","beta":false,"deprecated":false,"unavailable":false},{"name":"visionOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"1.0"}],"title":"localizedName","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedName","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"symbolKind":"property","role":"symbol"},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/localizedName"},"references":{"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/deviceType-swift.property":{"title":"deviceType","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/deviceType-swift.property","type":"topic","abstract":[{"text":"The type of device, such as a built-in microphone or wide-angle camera.","type":"text"}],"navigatorTitle":[{"text":"deviceType","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deviceType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVCaptureDevice","preciseIdentifier":"c:objc(cs)AVCaptureDevice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"DeviceType","preciseIdentifier":"c:@T@AVCaptureDeviceType","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","url":"/documentation/avfoundation/avcapturedevice/devicetype-swift.property"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/uniqueID":{"abstract":[{"type":"text","text":"An identifier that uniquely identifies the device."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"uniqueID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/uniqueID","role":"symbol","url":"/documentation/avfoundation/avcapturedevice/uniqueid","navigatorTitle":[{"kind":"identifier","text":"uniqueID"}],"type":"topic","title":"uniqueID","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/localizedName":{"title":"localizedName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/localizedName","type":"topic","navigatorTitle":[{"kind":"identifier","text":"localizedName"}],"role":"symbol","url":"/documentation/avfoundation/avcapturedevice/localizedname","abstract":[{"type":"text","text":"A localized device name for display in the user interface."}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/DeviceType-swift.struct":{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/DeviceType-swift.struct","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceType"}],"type":"topic","role":"symbol","title":"AVCaptureDevice.DeviceType","navigatorTitle":[{"kind":"identifier","text":"DeviceType"}],"url":"/documentation/avfoundation/avcapturedevice/devicetype-swift.struct","abstract":[{"type":"text","text":"A structure that defines the device types the framework supports."}]},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSString"}],"abstract":[{"text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"type":"topic","title":"NSString","url":"/documentation/foundation/nsstring","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Position-swift.enum":{"title":"AVCaptureDevice.Position","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Position","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Position-swift.enum","type":"topic","navigatorTitle":[{"text":"Position","kind":"identifier"}],"role":"symbol","url":"/documentation/avfoundation/avcapturedevice/position-swift.enum","abstract":[{"text":"Constants that indicate the physical position of a capture device.","type":"text"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/manufacturer":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"manufacturer","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","role":"symbol","title":"manufacturer","kind":"symbol","navigatorTitle":[{"text":"manufacturer","kind":"identifier"}],"abstract":[{"type":"text","text":"A human-readable string for the manufacturer of the device."}],"url":"/documentation/avfoundation/avcapturedevice/manufacturer","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/manufacturer"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/position-swift.property":{"abstract":[{"text":"The physical position of the capture device hardware.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"position"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVCaptureDevice","kind":"typeIdentifier","text":"AVCaptureDevice"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@AVCaptureDevicePosition","kind":"typeIdentifier","text":"Position"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/position-swift.property","role":"symbol","url":"/documentation/avfoundation/avcapturedevice/position-swift.property","navigatorTitle":[{"kind":"identifier","text":"position"}],"type":"topic","title":"position","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice":{"url":"/documentation/avfoundation/avcapturedevice","title":"AVCaptureDevice","abstract":[{"text":"An object that represents a hardware or virtual capture device like a camera or microphone.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVCaptureDevice","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVCaptureDevice","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/s:SS":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SS","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"String","kind":"identifier"}],"abstract":[{"type":"text","text":"A Unicode string value that is a collection of characters."}],"type":"topic","title":"String","url":"/documentation/Swift/String","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/modelID":{"title":"modelID","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"modelID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/modelID","type":"topic","navigatorTitle":[{"kind":"identifier","text":"modelID"}],"role":"symbol","url":"/documentation/avfoundation/avcapturedevice/modelid","abstract":[{"type":"text","text":"A model identifier for the device."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"deprecated":false,"unavailable":false,"name":"iOS","beta":false,"introducedAt":"4.0"},{"deprecated":false,"unavailable":false,"name":"iPadOS","beta":false,"introducedAt":"4.0"},{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"introducedAt":"14.0","beta":false},{"name":"macOS","deprecated":false,"unavailable":false,"introducedAt":"10.7","beta":false},{"name":"tvOS","deprecated":false,"unavailable":false,"introducedAt":"17.0","beta":false},{"name":"visionOS","deprecated":false,"unavailable":false,"introducedAt":"1.0","beta":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Property"},{"path":"/metadata/title","op":"replace","value":"localizedName"},{"path":"/metadata/symbolKind","op":"replace","value":"property"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"identifier","text":"localizedName"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"anchor":"Identifying-a-Device","generated":true,"title":"Identifying a Device","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/uniqueID","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/modelID","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/manufacturer","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/deviceType-swift.property","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/DeviceType-swift.struct","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/position-swift.property","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Position-swift.enum"]}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"localizedName"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1deviceType-swift.property/title","value":"deviceType","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1deviceType-swift.property/fragments","value":[{"kind":"identifier","text":"deviceType"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1uniqueID/title","value":"uniqueID","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1uniqueID/fragments","value":[{"text":"uniqueID","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1localizedName/title","value":"localizedName","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1localizedName/fragments","value":[{"kind":"identifier","text":"localizedName"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1DeviceType-swift.struct/title","value":"AVCaptureDeviceType","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1DeviceType-swift.struct/fragments","value":[{"kind":"identifier","text":"AVCaptureDeviceType"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1DeviceType-swift.struct/navigatorTitle","value":[{"text":"AVCaptureDeviceType","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract","value":[{"type":"text","text":"A static, plain-text Unicode string object."}],"op":"replace"},{"value":"AVCaptureDevicePosition","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1Position-swift.enum/title"},{"value":[{"text":"AVCaptureDevicePosition","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1Position-swift.enum/fragments"},{"value":[{"text":"AVCaptureDevicePosition","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1Position-swift.enum/navigatorTitle"},{"value":"manufacturer","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1manufacturer/title"},{"value":[{"kind":"identifier","text":"manufacturer"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1manufacturer/fragments","op":"replace"},{"value":"position","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1position-swift.property/title","op":"replace"},{"value":[{"kind":"identifier","text":"position"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1position-swift.property/fragments","op":"replace"},{"value":"AVCaptureDevice","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/title","op":"replace"},{"value":[{"kind":"identifier","text":"AVCaptureDevice"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/fragments","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/navigatorTitle","value":[{"kind":"identifier","text":"AVCaptureDevice"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1modelID/title","value":"modelID"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1modelID/fragments","value":[{"kind":"identifier","text":"modelID"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}