{
  "abstract": [
    {
      "text": "Sets the switching behavior of the primary constituent device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/setPrimaryConstituentDeviceSwitchingBehavior(_:restrictedSwitchingBehaviorConditions:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "c:objc(cs)AVCaptureDevice(im)setPrimaryConstituentDeviceSwitchingBehavior:restrictedSwitchingBehaviorConditions:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "setPrimaryConstituentDeviceSwitchingBehavior"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
        "text": "AVCaptureDevice"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AVCapturePrimaryConstituentDeviceSwitchingBehavior",
        "text": "PrimaryConstituentDeviceSwitchingBehavior"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "restrictedSwitchingBehaviorConditions"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
        "text": "AVCaptureDevice"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AVCapturePrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions",
        "text": "PrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setPrimaryConstituentDeviceSwitchingBehavior:restrictedSwitchingBehaviorConditions:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setPrimaryConstituentDeviceSwitchingBehavior(_:restrictedSwitchingBehaviorConditions:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "setPrimaryConstituentDeviceSwitchingBehavior"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "switchingBehavior"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
              "text": "AVCaptureDevice"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/PrimaryConstituentDeviceSwitchingBehavior-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AVCapturePrimaryConstituentDeviceSwitchingBehavior",
              "text": "PrimaryConstituentDeviceSwitchingBehavior"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "restrictedSwitchingBehaviorConditions"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
              "text": "AVCaptureDevice"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/PrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AVCapturePrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions",
              "text": "PrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The switching behavior to set on the device.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "switchingBehavior"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Sets the conditions during which the system restricts switching cameras.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Setting the switching behavior to a value other than ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/PrimaryConstituentDeviceSwitchingBehavior-swift.enum/restricted",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " requires that you set this argument to an empty option set.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "restrictedSwitchingBehaviorConditions"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this method to configure the camera switching behavior of a capture device. Before calling it, determine if a device supports configuring its device switching behavior by querying the device’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/activePrimaryConstituentDeviceSwitchingBehavior",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property. If the value equals ",
              "type": "text"
            },
            {
              "code": ".unsupported",
              "type": "codeVoice"
            },
            {
              "text": ", attempting to configure its switching behavior results in an error.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Exit early if the device doesn't support configuring switching behavior.",
            "guard captureDevice.activePrimaryConstituentDeviceSwitchingBehavior != .unsupported else { return }",
            "captureDevice.setPrimaryConstituentDeviceSwitchingBehavior(.auto, restrictedSwitchingBehaviorConditions: [])"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "When recording using an instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMovieFileOutput",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", you may override the switching behavior by calling the movie file output’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMovieFileOutput/setPrimaryConstituentDeviceSwitchingBehaviorForRecording(_:restrictedSwitchingBehaviorConditions:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice": {
      "abstract": [
        {
          "text": "An object that represents a hardware or virtual capture device like a camera or microphone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureDevice"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureDevice"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDevice",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/PrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions-swift.struct": {
      "abstract": [
        {
          "text": "A structure that defines the conditions in which to restrict camera switching.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/PrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDevice.PrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/primaryconstituentdevicerestrictedswitchingbehaviorconditions-swift.struct"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/PrimaryConstituentDeviceSwitchingBehavior-swift.enum": {
      "abstract": [
        {
          "text": "Constants that control when to allow a virtual device to switch its active primary constituent device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PrimaryConstituentDeviceSwitchingBehavior"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/PrimaryConstituentDeviceSwitchingBehavior-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PrimaryConstituentDeviceSwitchingBehavior"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDevice.PrimaryConstituentDeviceSwitchingBehavior",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/primaryconstituentdeviceswitchingbehavior-swift.enum"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/PrimaryConstituentDeviceSwitchingBehavior-swift.enum/restricted": {
      "abstract": [
        {
          "text": "The device restricts fallback camera selection to certain conditions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restricted"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/PrimaryConstituentDeviceSwitchingBehavior-swift.enum/restricted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCapturePrimaryConstituentDeviceSwitchingBehaviorRestricted"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDevice.PrimaryConstituentDeviceSwitchingBehavior.restricted",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/primaryconstituentdeviceswitchingbehavior-swift.enum/restricted"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/activePrimaryConstituent": {
      "abstract": [
        {
          "text": "A virtual device’s active primary constituent device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activePrimaryConstituent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/activePrimaryConstituent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activePrimaryConstituentDevice"
        }
      ],
      "role": "symbol",
      "title": "activePrimaryConstituent",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/activeprimaryconstituent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/activePrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions": {
      "abstract": [
        {
          "text": "The conditions that restrict camera switching behavior for the active primary constituent device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activePrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVCapturePrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions",
          "text": "PrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/activePrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activePrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions"
        }
      ],
      "role": "symbol",
      "title": "activePrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/activeprimaryconstituentdevicerestrictedswitchingbehaviorconditions"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/activePrimaryConstituentDeviceSwitchingBehavior": {
      "abstract": [
        {
          "text": "The switching behavior of the active constituent device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activePrimaryConstituentDeviceSwitchingBehavior"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVCapturePrimaryConstituentDeviceSwitchingBehavior",
          "text": "PrimaryConstituentDeviceSwitchingBehavior"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/activePrimaryConstituentDeviceSwitchingBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activePrimaryConstituentDeviceSwitchingBehavior"
        }
      ],
      "role": "symbol",
      "title": "activePrimaryConstituentDeviceSwitchingBehavior",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/activeprimaryconstituentdeviceswitchingbehavior"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/fallbackPrimaryConstituentDevices": {
      "abstract": [
        {
          "text": "The fallback devices to use when a constituent device with a longer focal length becomes limited by its light sensitivity or minimum focus distance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fallbackPrimaryConstituentDevices"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/fallbackPrimaryConstituentDevices",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fallbackPrimaryConstituentDevices"
        }
      ],
      "role": "symbol",
      "title": "fallbackPrimaryConstituentDevices",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/fallbackprimaryconstituentdevices"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/primaryConstituentDeviceRestrictedSwitchingBehaviorConditions-swift.property": {
      "abstract": [
        {
          "text": "The conditions that restrict the primary constituent device’s switching behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primaryConstituentDeviceRestrictedSwitchingBehaviorConditions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVCapturePrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions",
          "text": "PrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/primaryConstituentDeviceRestrictedSwitchingBehaviorConditions-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "primaryConstituentDeviceRestrictedSwitchingBehaviorConditions"
        }
      ],
      "role": "symbol",
      "title": "primaryConstituentDeviceRestrictedSwitchingBehaviorConditions",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/primaryconstituentdevicerestrictedswitchingbehaviorconditions-swift.property"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/primaryConstituentDeviceSwitchingBehavior-swift.property": {
      "abstract": [
        {
          "text": "The switching behavior for the primary constituent device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primaryConstituentDeviceSwitchingBehavior"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVCapturePrimaryConstituentDeviceSwitchingBehavior",
          "text": "PrimaryConstituentDeviceSwitchingBehavior"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/primaryConstituentDeviceSwitchingBehavior-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "primaryConstituentDeviceSwitchingBehavior"
        }
      ],
      "role": "symbol",
      "title": "primaryConstituentDeviceSwitchingBehavior",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/primaryconstituentdeviceswitchingbehavior-swift.property"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/setPrimaryConstituentDeviceSwitchingBehavior(_:restrictedSwitchingBehaviorConditions:)": {
      "abstract": [
        {
          "text": "Sets the switching behavior of the primary constituent device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setPrimaryConstituentDeviceSwitchingBehavior"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVCapturePrimaryConstituentDeviceSwitchingBehavior",
          "text": "PrimaryConstituentDeviceSwitchingBehavior"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "restrictedSwitchingBehaviorConditions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVCapturePrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions",
          "text": "PrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/setPrimaryConstituentDeviceSwitchingBehavior(_:restrictedSwitchingBehaviorConditions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setPrimaryConstituentDeviceSwitchingBehavior:restrictedSwitchingBehaviorConditions:"
        }
      ],
      "role": "symbol",
      "title": "setPrimaryConstituentDeviceSwitchingBehavior(_:restrictedSwitchingBehaviorConditions:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/setprimaryconstituentdeviceswitchingbehavior(_:restrictedswitchingbehaviorconditions:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/supportedFallbackPrimaryConstituentDevices": {
      "abstract": [
        {
          "text": "The constituent devices available to select as a fallback for a longer focal length primary constituent device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedFallbackPrimaryConstituentDevices"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/supportedFallbackPrimaryConstituentDevices",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportedFallbackPrimaryConstituentDevices"
        }
      ],
      "role": "symbol",
      "title": "supportedFallbackPrimaryConstituentDevices",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/supportedfallbackprimaryconstituentdevices"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMovieFileOutput": {
      "abstract": [
        {
          "text": "A capture output that records video and audio to a QuickTime movie file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureMovieFileOutput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMovieFileOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureMovieFileOutput"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureMovieFileOutput",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturemoviefileoutput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMovieFileOutput/setPrimaryConstituentDeviceSwitchingBehaviorForRecording(_:restrictedSwitchingBehaviorConditions:)": {
      "abstract": [
        {
          "text": "Sets the camera switching behavior to use during recording.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setPrimaryConstituentDeviceSwitchingBehaviorForRecording"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVCapturePrimaryConstituentDeviceSwitchingBehavior",
          "text": "PrimaryConstituentDeviceSwitchingBehavior"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "restrictedSwitchingBehaviorConditions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVCapturePrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions",
          "text": "PrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMovieFileOutput/setPrimaryConstituentDeviceSwitchingBehaviorForRecording(_:restrictedSwitchingBehaviorConditions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setPrimaryConstituentDeviceSwitchingBehaviorForRecording:restrictedSwitchingBehaviorConditions:"
        }
      ],
      "role": "symbol",
      "title": "setPrimaryConstituentDeviceSwitchingBehaviorForRecording(_:restrictedSwitchingBehaviorConditions:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturemoviefileoutput/setprimaryconstituentdeviceswitchingbehaviorforrecording(_:restrictedswitchingbehaviorconditions:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Restricting-Camera-Switching",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/primaryConstituentDeviceSwitchingBehavior-swift.property",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/primaryConstituentDeviceRestrictedSwitchingBehaviorConditions-swift.property",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/activePrimaryConstituentDeviceSwitchingBehavior",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/activePrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/activePrimaryConstituent",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/PrimaryConstituentDeviceSwitchingBehavior-swift.enum",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/PrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions-swift.struct",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/supportedFallbackPrimaryConstituentDevices",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/fallbackPrimaryConstituentDevices"
      ],
      "title": "Restricting Camera Switching"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "setPrimaryConstituentDeviceSwitchingBehavior:restrictedSwitchingBehaviorConditions:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setPrimaryConstituentDeviceSwitchingBehavior:restrictedSwitchingBehaviorConditions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Restricting-Camera-Switching",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/primaryConstituentDeviceSwitchingBehavior-swift.property",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/primaryConstituentDeviceRestrictedSwitchingBehaviorConditions-swift.property",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/activePrimaryConstituentDeviceSwitchingBehavior",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/activePrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/activePrimaryConstituent",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/PrimaryConstituentDeviceSwitchingBehavior-swift.enum",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/PrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions-swift.struct",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/supportedFallbackPrimaryConstituentDevices",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/fallbackPrimaryConstituentDevices"
              ],
              "title": "Restricting Camera Switching"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "setPrimaryConstituentDeviceSwitchingBehavior:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/PrimaryConstituentDeviceSwitchingBehavior-swift.enum",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@AVCapturePrimaryConstituentDeviceSwitchingBehavior",
                    "text": "AVCapturePrimaryConstituentDeviceSwitchingBehavior"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "switchingBehavior"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "restrictedSwitchingBehaviorConditions:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/PrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions-swift.struct",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@AVCapturePrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions",
                    "text": "AVCapturePrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "restrictedSwitchingBehaviorConditions"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The switching behavior to set on the device.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "switchingBehavior"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Sets the conditions during which the system restricts switching cameras.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "Setting the switching behavior to a value other than ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/PrimaryConstituentDeviceSwitchingBehavior-swift.enum/restricted",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " requires that you set this argument to an empty option set.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "restrictedSwitchingBehaviorConditions"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1PrimaryConstituentDeviceSwitchingBehavior-swift.enum/title",
          "value": "AVCapturePrimaryConstituentDeviceSwitchingBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1PrimaryConstituentDeviceSwitchingBehavior-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePrimaryConstituentDeviceSwitchingBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1PrimaryConstituentDeviceSwitchingBehavior-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePrimaryConstituentDeviceSwitchingBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1activePrimaryConstituent/title",
          "value": "activePrimaryConstituentDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1activePrimaryConstituent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activePrimaryConstituentDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1supportedFallbackPrimaryConstituentDevices/title",
          "value": "supportedFallbackPrimaryConstituentDevices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1supportedFallbackPrimaryConstituentDevices/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportedFallbackPrimaryConstituentDevices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1setPrimaryConstituentDeviceSwitchingBehavior(_:restrictedSwitchingBehaviorConditions:)/title",
          "value": "setPrimaryConstituentDeviceSwitchingBehavior:restrictedSwitchingBehaviorConditions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1setPrimaryConstituentDeviceSwitchingBehavior(_:restrictedSwitchingBehaviorConditions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setPrimaryConstituentDeviceSwitchingBehavior:restrictedSwitchingBehaviorConditions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureMovieFileOutput/title",
          "value": "AVCaptureMovieFileOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureMovieFileOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureMovieFileOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureMovieFileOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureMovieFileOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1PrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions-swift.struct/title",
          "value": "AVCapturePrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1PrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1PrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/title",
          "value": "AVCaptureDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1fallbackPrimaryConstituentDevices/title",
          "value": "fallbackPrimaryConstituentDevices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1fallbackPrimaryConstituentDevices/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fallbackPrimaryConstituentDevices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureMovieFileOutput~1setPrimaryConstituentDeviceSwitchingBehaviorForRecording(_:restrictedSwitchingBehaviorConditions:)/title",
          "value": "setPrimaryConstituentDeviceSwitchingBehaviorForRecording:restrictedSwitchingBehaviorConditions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureMovieFileOutput~1setPrimaryConstituentDeviceSwitchingBehaviorForRecording(_:restrictedSwitchingBehaviorConditions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setPrimaryConstituentDeviceSwitchingBehaviorForRecording:restrictedSwitchingBehaviorConditions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1PrimaryConstituentDeviceSwitchingBehavior-swift.enum~1restricted/title",
          "value": "AVCapturePrimaryConstituentDeviceSwitchingBehaviorRestricted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1PrimaryConstituentDeviceSwitchingBehavior-swift.enum~1restricted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePrimaryConstituentDeviceSwitchingBehaviorRestricted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1primaryConstituentDeviceSwitchingBehavior-swift.property/title",
          "value": "primaryConstituentDeviceSwitchingBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1primaryConstituentDeviceSwitchingBehavior-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "primaryConstituentDeviceSwitchingBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1activePrimaryConstituentDeviceSwitchingBehavior/title",
          "value": "activePrimaryConstituentDeviceSwitchingBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1activePrimaryConstituentDeviceSwitchingBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activePrimaryConstituentDeviceSwitchingBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1primaryConstituentDeviceRestrictedSwitchingBehaviorConditions-swift.property/title",
          "value": "primaryConstituentDeviceRestrictedSwitchingBehaviorConditions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1primaryConstituentDeviceRestrictedSwitchingBehaviorConditions-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "primaryConstituentDeviceRestrictedSwitchingBehaviorConditions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1activePrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions/title",
          "value": "activePrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1activePrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activePrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcapturedevice/setprimaryconstituentdeviceswitchingbehavior(_:restrictedswitchingbehaviorconditions:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avcapturedevice/setprimaryconstituentdeviceswitchingbehavior(_:restrictedswitchingbehaviorconditions:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
