{
  "abstract": [
    {
      "text": "Sets the illumination level when in torch mode.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/setTorchModeOn(level:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "c:objc(cs)AVCaptureDevice(im)setTorchModeOnWithLevel:error:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "setTorchModeOn"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "level"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sf",
        "text": "Float"
      },
      {
        "kind": "text",
        "text": ") "
      },
      {
        "kind": "keyword",
        "text": "throws"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setTorchModeOnWithLevel:error:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setTorchModeOn(level:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "setTorchModeOn"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "level"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "torchLevel"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sf",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sf",
              "text": "Float"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "throws"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The new torch mode level. This value must be a floating-point number between ",
                  "type": "text"
                },
                {
                  "code": "0.0",
                  "type": "codeVoice"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "code": "1.0",
                  "type": "codeVoice"
                },
                {
                  "text": ". To set the torch mode level to the currently available maximum, specify the constant ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/maxAvailableTorchLevel",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for this parameter.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "torchLevel"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method sets the torch mode to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/TorchMode-swift.enum/on",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and sets the level to the specified value. If the device doesn’t support this mode or if you specify a value for ",
              "type": "text"
            },
            {
              "code": "torchLevel",
              "type": "codeVoice"
            },
            {
              "text": " that’s outside the accepted range, this method raises an exception. If the torch value is within the accepted range but greater than the currently supported maximum—perhaps because the device is overheating—this method returns ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Before changing the value of this property, you must call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/lockForConfiguration()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to acquire exclusive access to the device’s configuration properties. Otherwise, calling this method raises an exception. When you finish configuring the device, call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/unlockForConfiguration()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to release the lock and allow other devices to configure the settings.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice": {
      "abstract": [
        {
          "text": "An object that represents a hardware or virtual capture device like a camera or microphone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureDevice"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureDevice"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDevice",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/TorchMode-swift.enum": {
      "abstract": [
        {
          "text": "Constants to specify the capture device’s torch mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TorchMode"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/TorchMode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TorchMode"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDevice.TorchMode",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/torchmode-swift.enum"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/TorchMode-swift.enum/on": {
      "abstract": [
        {
          "text": "The capture device torch is always on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "on"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/TorchMode-swift.enum/on",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureTorchModeOn"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDevice.TorchMode.on",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/torchmode-swift.enum/on"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/hasTorch": {
      "abstract": [
        {
          "text": "A Boolean value that specifies whether the capture device has a torch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasTorch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/hasTorch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasTorch"
        }
      ],
      "role": "symbol",
      "title": "hasTorch",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/hastorch"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isTorchActive": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the device’s torch is currently active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isTorchActive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isTorchActive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "torchActive"
        }
      ],
      "role": "symbol",
      "title": "isTorchActive",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/istorchactive"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isTorchAvailable": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the torch is currently available for use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isTorchAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isTorchAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "torchAvailable"
        }
      ],
      "role": "symbol",
      "title": "isTorchAvailable",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/istorchavailable"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isTorchModeSupported(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the device supports the specified torch mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isTorchModeSupported"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVCaptureTorchMode",
          "text": "TorchMode"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isTorchModeSupported(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isTorchModeSupported:"
        }
      ],
      "role": "symbol",
      "title": "isTorchModeSupported(_:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/istorchmodesupported(_:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/lockForConfiguration()": {
      "abstract": [
        {
          "text": "Requests exclusive access to configure device hardware properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lockForConfiguration"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/lockForConfiguration()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lockForConfiguration:"
        }
      ],
      "role": "symbol",
      "title": "lockForConfiguration()",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/lockforconfiguration()"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/maxAvailableTorchLevel": {
      "abstract": [
        {
          "text": "A constant that indicates to set the torch to its maximum level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxAvailableTorchLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/maxAvailableTorchLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureMaxAvailableTorchLevel"
        }
      ],
      "role": "symbol",
      "title": "maxAvailableTorchLevel",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/maxavailabletorchlevel"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/setTorchModeOn(level:)": {
      "abstract": [
        {
          "text": "Sets the illumination level when in torch mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTorchModeOn"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "level"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/setTorchModeOn(level:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTorchModeOnWithLevel:error:"
        }
      ],
      "role": "symbol",
      "title": "setTorchModeOn(level:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/settorchmodeon(level:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/torchLevel": {
      "abstract": [
        {
          "text": "The current torch brightness level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "torchLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/torchLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "torchLevel"
        }
      ],
      "role": "symbol",
      "title": "torchLevel",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/torchlevel"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/torchMode-swift.property": {
      "abstract": [
        {
          "text": "The current torch mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "torchMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVCaptureTorchMode",
          "text": "TorchMode"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/torchMode-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "torchMode"
        }
      ],
      "role": "symbol",
      "title": "torchMode",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/torchmode-swift.property"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/unlockForConfiguration()": {
      "abstract": [
        {
          "text": "Releases exclusive control over device hardware properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unlockForConfiguration"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/unlockForConfiguration()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unlockForConfiguration"
        }
      ],
      "role": "symbol",
      "title": "unlockForConfiguration()",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/unlockforconfiguration()"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSError": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.externally.resolved.symbol/s:Sf": {
      "abstract": [
        {
          "text": "A single-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sf",
      "kind": "symbol",
      "role": "symbol",
      "title": "Float",
      "type": "topic",
      "url": "/documentation/Swift/Float"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Torch-Settings",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/hasTorch",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isTorchAvailable",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isTorchActive",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/torchLevel",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/torchMode-swift.property",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/TorchMode-swift.enum",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isTorchModeSupported(_:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/maxAvailableTorchLevel"
      ],
      "title": "Configuring Torch Settings"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "setTorchModeOnWithLevel:error:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setTorchModeOnWithLevel:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Torch-Settings",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/hasTorch",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isTorchAvailable",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isTorchActive",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/torchLevel",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/torchMode-swift.property",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/TorchMode-swift.enum",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isTorchModeSupported(_:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/maxAvailableTorchLevel"
              ],
              "title": "Configuring Torch Settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "setTorchModeOnWithLevel:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:f",
                    "text": "float"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "torchLevel"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "error:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " * *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "outError"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The new torch mode level. This value must be a floating-point number between ",
                        "type": "text"
                      },
                      {
                        "code": "0.0",
                        "type": "codeVoice"
                      },
                      {
                        "text": " and ",
                        "type": "text"
                      },
                      {
                        "code": "1.0",
                        "type": "codeVoice"
                      },
                      {
                        "text": ". To set the torch mode level to the currently available maximum, specify the constant ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/maxAvailableTorchLevel",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " for this parameter.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "torchLevel"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "On input, a pointer to an error object. If an error occurs, this method assigns an error object to the pointer with information about what happened.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "outError"
              }
            ]
          }
        },
        {
          "op": "add",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/swift/true",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " if the torch mode level was set or ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/swift/false",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " if it was not.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1unlockForConfiguration()/title",
          "value": "unlockForConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1unlockForConfiguration()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "unlockForConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/title",
          "value": "AVCaptureDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1lockForConfiguration()/title",
          "value": "lockForConfiguration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1lockForConfiguration()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "lockForConfiguration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1torchLevel/title",
          "value": "torchLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1torchLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "torchLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1TorchMode-swift.enum/title",
          "value": "AVCaptureTorchMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1TorchMode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureTorchMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1TorchMode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureTorchMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isTorchAvailable/title",
          "value": "torchAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isTorchAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "torchAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1maxAvailableTorchLevel/title",
          "value": "AVCaptureMaxAvailableTorchLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1maxAvailableTorchLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureMaxAvailableTorchLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1TorchMode-swift.enum~1on/title",
          "value": "AVCaptureTorchModeOn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1TorchMode-swift.enum~1on/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureTorchModeOn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1torchMode-swift.property/title",
          "value": "torchMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1torchMode-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "torchMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1setTorchModeOn(level:)/title",
          "value": "setTorchModeOnWithLevel:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1setTorchModeOn(level:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setTorchModeOnWithLevel:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isTorchActive/title",
          "value": "torchActive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isTorchActive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "torchActive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1hasTorch/title",
          "value": "hasTorch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1hasTorch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hasTorch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isTorchModeSupported(_:)/title",
          "value": "isTorchModeSupported:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isTorchModeSupported(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "isTorchModeSupported:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcapturedevice/settorchmodeon(level:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avcapturedevice/settorchmodeon(level:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
