{"sections":[],"relationshipsSections":[{"kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSObject"],"type":"conformsTo","title":"Conforms To"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice"]]},"topicSections":[{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/SystemPressureState-swift.class/level-swift.property","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/SystemPressureState-swift.class/Level-swift.struct"],"anchor":"Overall-Level","title":"Overall Level"},{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/SystemPressureState-swift.class/factors-swift.property","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/SystemPressureState-swift.class/Factors-swift.struct"],"anchor":"Contributing-Factors","title":"Contributing Factors"}],"kind":"symbol","variants":[{"paths":["/documentation/avfoundation/avcapturedevice/systempressurestate-swift.class"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/avfoundation/avcapturedevice/systempressurestate-swift.class"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SystemPressureState","kind":"identifier"}]}]},{"kind":"content","content":[{"level":2,"anchor":"overview","text":"Overview","type":"heading"},{"inlineContent":[{"text":"The performance and availability of the camera capture system on an iOS device is subject to several external factors, such as power usage and device temperature. If during a capture session the total system pressure reaches excessive levels, the capture system automatically shuts down, causing a session interruption (see ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSession/wasInterruptedNotification"},{"text":"). Under less heavy pressure, the system may automatically reduce capture quality.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Key-value observe the capture device’s ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/systemPressureState-swift.property","type":"reference"},{"text":" property to monitor its state, and take action to reduce the performance impact of your capture session when system pressure increases—for example, by reducing the capture frame rate.","type":"text"}],"type":"paragraph"}]}],"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/systemPressureState-swift.property","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSessionInterruptionSystemPressureStateKey"],"anchor":"Monitoring-System-Pressure","title":"Monitoring System Pressure"}],"identifier":{"url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/SystemPressureState-swift.class","interfaceLanguage":"swift"},"abstract":[{"text":"An object that provides information about OS and hardware status affecting capture system performance and availability.","type":"text"}],"metadata":{"externalID":"c:objc(cs)AVCaptureSystemPressureState","extendedModule":"AVFoundation","roleHeading":"Class","modules":[{"name":"AVFoundation"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SystemPressureState"}],"title":"AVCaptureDevice.SystemPressureState","platforms":[{"beta":false,"name":"iOS","deprecated":false,"introducedAt":"11.1","unavailable":false},{"beta":false,"name":"iPadOS","deprecated":false,"introducedAt":"11.1","unavailable":false},{"beta":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"14.0","unavailable":false},{"beta":false,"name":"tvOS","deprecated":false,"introducedAt":"17.0","unavailable":false},{"beta":false,"name":"visionOS","deprecated":false,"introducedAt":"1.0","unavailable":false}],"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"SystemPressureState"}],"role":"symbol"},"references":{"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice":{"url":"/documentation/avfoundation/avcapturedevice","title":"AVCaptureDevice","abstract":[{"text":"An object that represents a hardware or virtual capture device like a camera or microphone.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVCaptureDevice","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVCaptureDevice","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/systemPressureState-swift.property":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/systemPressureState-swift.property","type":"topic","title":"systemPressureState","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"systemPressureState","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVCaptureDevice","text":"AVCaptureDevice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVCaptureSystemPressureState","text":"SystemPressureState","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"A value that indicates the capture device’s current system pressure state."}],"navigatorTitle":[{"text":"systemPressureState","kind":"identifier"}],"url":"/documentation/avfoundation/avcapturedevice/systempressurestate-swift.property"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/SystemPressureState-swift.class":{"title":"AVCaptureDevice.SystemPressureState","type":"topic","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/SystemPressureState-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SystemPressureState","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SystemPressureState","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"An object that provides information about OS and hardware status affecting capture system performance and availability."}],"url":"/documentation/avfoundation/avcapturedevice/systempressurestate-swift.class"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/SystemPressureState-swift.class/Level-swift.struct":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Level","kind":"identifier"}],"abstract":[{"text":"A structure that defines system pressure state levels.","type":"text"}],"navigatorTitle":[{"text":"Level","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/SystemPressureState-swift.class/Level-swift.struct","url":"/documentation/avfoundation/avcapturedevice/systempressurestate-swift.class/level-swift.struct","kind":"symbol","type":"topic","role":"symbol","title":"AVCaptureDevice.SystemPressureState.Level"},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomStringConvertible"}],"abstract":[{"type":"text","text":"A type with a customized textual representation."}],"type":"topic","title":"CustomStringConvertible","url":"/documentation/Swift/CustomStringConvertible","kind":"symbol"},"doc://com.externally.resolved.symbol/s:SQ":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SQ","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"type":"topic","title":"Equatable","url":"/documentation/Swift/Equatable","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/SystemPressureState-swift.class/Factors-swift.struct":{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/SystemPressureState-swift.class/Factors-swift.struct","role":"symbol","navigatorTitle":[{"text":"Factors","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Factors","kind":"identifier"}],"kind":"symbol","type":"topic","url":"/documentation/avfoundation/avcapturedevice/systempressurestate-swift.class/factors-swift.struct","title":"AVCaptureDevice.SystemPressureState.Factors","abstract":[{"text":"A structure that defines the factors affecting capture system performance.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSession/wasInterruptedNotification":{"abstract":[{"text":"A notification the system posts when it interrupts a capture session.","type":"text"}],"title":"wasInterruptedNotification","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wasInterruptedNotification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Name","preciseIdentifier":"c:@T@NSNotificationName","kind":"typeIdentifier"}],"url":"/documentation/avfoundation/avcapturesession/wasinterruptednotification","kind":"symbol","navigatorTitle":[{"text":"AVCaptureSessionWasInterruptedNotification","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSession/wasInterruptedNotification","role":"symbol"},"doc://com.externally.resolved.symbol/s:SH":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SH","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hashable","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"Equatable","kind":"typeIdentifier","preciseIdentifier":"s:SQ"}],"abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"type":"topic","title":"Hashable","url":"/documentation/Swift/Hashable","kind":"symbol"},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"url":"/documentation/Swift/CustomDebugStringConvertible","title":"CustomDebugStringConvertible","abstract":[{"text":"A type with a customized textual representation suitable for debugging purposes.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomDebugStringConvertible","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP"},"doc://com.externally.resolved.symbol/c:objc(cs)NSObject":{"abstract":[{"text":"The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.","type":"text"}],"role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject","title":"NSObject","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSObject"}],"url":"/documentation/objectivec/nsobject","type":"topic","kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"url":"/documentation/objectivec/nsobjectprotocol","title":"NSObjectProtocol","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject"},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVarArg"}],"abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"type":"topic","title":"CVarArg","url":"/documentation/Swift/CVarArg","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSessionInterruptionSystemPressureStateKey":{"abstract":[{"type":"text","text":"A key to retrieve a state value that indicates the system pressure level and contributing factors that caused the interruption."}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSessionInterruptionSystemPressureStateKey","url":"/documentation/avfoundation/avcapturesessioninterruptionsystempressurestatekey","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AVCaptureSessionInterruptionSystemPressureStateKey"}],"type":"topic","title":"AVCaptureSessionInterruptionSystemPressureStateKey","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AVCaptureSessionInterruptionSystemPressureStateKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/SystemPressureState-swift.class/level-swift.property":{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/SystemPressureState-swift.class/level-swift.property","title":"level","abstract":[{"text":"The overall level of performance constraints on the capture system.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"level","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVCaptureDevice","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVCaptureDevice"},{"text":".","kind":"text"},{"text":"SystemPressureState","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVCaptureSystemPressureState"},{"text":".","kind":"text"},{"text":"Level","kind":"typeIdentifier","preciseIdentifier":"c:@T@AVCaptureSystemPressureLevel"}],"role":"symbol","kind":"symbol","url":"/documentation/avfoundation/avcapturedevice/systempressurestate-swift.class/level-swift.property","navigatorTitle":[{"text":"level","kind":"identifier"}],"type":"topic"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/SystemPressureState-swift.class/factors-swift.property":{"abstract":[{"text":"The set of underlying causes for the system pressure level.","type":"text"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/SystemPressureState-swift.class/factors-swift.property","title":"factors","navigatorTitle":[{"text":"factors","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"factors","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVCaptureDevice","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVCaptureDevice"},{"text":".","kind":"text"},{"text":"SystemPressureState","preciseIdentifier":"c:objc(cs)AVCaptureSystemPressureState","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Factors","preciseIdentifier":"c:@E@AVCaptureSystemPressureFactors","kind":"typeIdentifier"}],"role":"symbol","url":"/documentation/avfoundation/avcapturedevice/systempressurestate-swift.class/factors-swift.property"},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"beta":false,"name":"iOS","deprecated":false,"introducedAt":"11.1","unavailable":false},{"beta":false,"name":"iPadOS","deprecated":false,"introducedAt":"11.1","unavailable":false},{"beta":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"14.0","unavailable":false},{"beta":false,"name":"tvOS","deprecated":false,"introducedAt":"17.0","unavailable":false},{"beta":false,"name":"visionOS","deprecated":false,"introducedAt":"1.0","unavailable":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Class"},{"op":"replace","path":"/metadata/title","value":"AVCaptureSystemPressureState"},{"op":"replace","path":"/metadata/symbolKind","value":"class"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"AVCaptureSystemPressureState"}]},{"op":"replace","path":"/metadata/navigatorTitle","value":[{"kind":"identifier","text":"AVCaptureSystemPressureState"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation"]]}},{"op":"replace","path":"/topicSections","value":[{"anchor":"Overall-Level","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/SystemPressureState-swift.class/level-swift.property","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/SystemPressureState-swift.class/Level-swift.struct"],"title":"Overall Level"},{"anchor":"Contributing-Factors","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/SystemPressureState-swift.class/factors-swift.property","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/SystemPressureState-swift.class/Factors-swift.struct"],"title":"Contributing Factors"}]},{"path":"/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"],"kind":"relationships"}],"op":"replace"},{"path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/systemPressureState-swift.property","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSessionInterruptionSystemPressureStateKey"],"anchor":"Monitoring-System-Pressure","generated":true,"title":"Monitoring System Pressure"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVCaptureSystemPressureState"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/title","value":"AVCaptureDevice"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/fragments","value":[{"kind":"identifier","text":"AVCaptureDevice"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/navigatorTitle","value":[{"text":"AVCaptureDevice","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1systemPressureState-swift.property/title","value":"systemPressureState"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1systemPressureState-swift.property/fragments","value":[{"text":"systemPressureState","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1SystemPressureState-swift.class/title","value":"AVCaptureSystemPressureState"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1SystemPressureState-swift.class/fragments","value":[{"text":"AVCaptureSystemPressureState","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1SystemPressureState-swift.class/navigatorTitle","value":[{"text":"AVCaptureSystemPressureState","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1SystemPressureState-swift.class~1Level-swift.struct/title","value":"AVCaptureSystemPressureLevel"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1SystemPressureState-swift.class~1Level-swift.struct/fragments","value":[{"kind":"identifier","text":"AVCaptureSystemPressureLevel"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1SystemPressureState-swift.class~1Level-swift.struct/navigatorTitle","value":[{"kind":"identifier","text":"AVCaptureSystemPressureLevel"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1SystemPressureState-swift.class~1Factors-swift.struct/title","value":"AVCaptureSystemPressureFactors"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1SystemPressureState-swift.class~1Factors-swift.struct/fragments","value":[{"text":"AVCaptureSystemPressureFactors","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1SystemPressureState-swift.class~1Factors-swift.struct/navigatorTitle","value":[{"text":"AVCaptureSystemPressureFactors","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSession~1wasInterruptedNotification/title","value":"AVCaptureSessionWasInterruptedNotification"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSession~1wasInterruptedNotification/fragments","value":[{"kind":"identifier","text":"AVCaptureSessionWasInterruptedNotification"}]},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","value":"NSObject"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSessionInterruptionSystemPressureStateKey/title","value":"AVCaptureSessionInterruptionSystemPressureStateKey"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSessionInterruptionSystemPressureStateKey/fragments","value":[{"text":"AVCaptureSessionInterruptionSystemPressureStateKey","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1SystemPressureState-swift.class~1level-swift.property/title","value":"level"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1SystemPressureState-swift.class~1level-swift.property/fragments","value":[{"text":"level","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1SystemPressureState-swift.class~1factors-swift.property/title","value":"factors"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1SystemPressureState-swift.class~1factors-swift.property/fragments","value":[{"kind":"identifier","text":"factors"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}