{"metadata":{"title":"uniqueID","role":"symbol","modules":[{"name":"AVFoundation"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"uniqueID","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"externalID":"c:objc(cs)AVCaptureDevice(py)uniqueID","symbolKind":"property","platforms":[{"name":"iOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"4.0"},{"name":"iPadOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"4.0"},{"name":"Mac Catalyst","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"14.0"},{"name":"macOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"10.7"},{"name":"tvOS","deprecated":false,"beta":false,"unavailable":false,"introducedAt":"17.0"},{"name":"visionOS","deprecated":false,"beta":false,"unavailable":false,"introducedAt":"1.0"}],"navigatorTitle":[{"text":"uniqueID","kind":"identifier"}],"roleHeading":"Instance Property"},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/uniqueID"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice"]]},"abstract":[{"type":"text","text":"An identifier that uniquely identifies the device."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uniqueID","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","identifier":"doc://com.externally.resolved.symbol/s:SS","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]},{"kind":"content","content":[{"anchor":"Discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Capture devices have a unique identifier that persists on one system across device connections and disconnections, application restarts, and reboots of the system itself. You can store the value returned by this property to recall or track the status of a specific device in the future."}]}]}],"seeAlsoSections":[{"anchor":"Identifying-a-Device","title":"Identifying a Device","generated":true,"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/modelID","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/localizedName","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/manufacturer","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/deviceType-swift.property","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/DeviceType-swift.struct","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/position-swift.property","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Position-swift.enum"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/avfoundation/avcapturedevice/uniqueid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/avfoundation/avcapturedevice/uniqueid"]}],"kind":"symbol","references":{"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/DeviceType-swift.struct":{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/DeviceType-swift.struct","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceType"}],"type":"topic","role":"symbol","title":"AVCaptureDevice.DeviceType","navigatorTitle":[{"kind":"identifier","text":"DeviceType"}],"url":"/documentation/avfoundation/avcapturedevice/devicetype-swift.struct","abstract":[{"type":"text","text":"A structure that defines the device types the framework supports."}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/deviceType-swift.property":{"title":"deviceType","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/deviceType-swift.property","type":"topic","abstract":[{"text":"The type of device, such as a built-in microphone or wide-angle camera.","type":"text"}],"navigatorTitle":[{"text":"deviceType","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deviceType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVCaptureDevice","preciseIdentifier":"c:objc(cs)AVCaptureDevice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"DeviceType","preciseIdentifier":"c:@T@AVCaptureDeviceType","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","url":"/documentation/avfoundation/avcapturedevice/devicetype-swift.property"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/manufacturer":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"manufacturer","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","role":"symbol","title":"manufacturer","kind":"symbol","navigatorTitle":[{"text":"manufacturer","kind":"identifier"}],"abstract":[{"type":"text","text":"A human-readable string for the manufacturer of the device."}],"url":"/documentation/avfoundation/avcapturedevice/manufacturer","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/manufacturer"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/uniqueID":{"abstract":[{"type":"text","text":"An identifier that uniquely identifies the device."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"uniqueID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/uniqueID","role":"symbol","url":"/documentation/avfoundation/avcapturedevice/uniqueid","navigatorTitle":[{"kind":"identifier","text":"uniqueID"}],"type":"topic","title":"uniqueID","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice":{"url":"/documentation/avfoundation/avcapturedevice","title":"AVCaptureDevice","abstract":[{"text":"An object that represents a hardware or virtual capture device like a camera or microphone.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVCaptureDevice","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVCaptureDevice","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/modelID":{"title":"modelID","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"modelID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/modelID","type":"topic","navigatorTitle":[{"kind":"identifier","text":"modelID"}],"role":"symbol","url":"/documentation/avfoundation/avcapturedevice/modelid","abstract":[{"type":"text","text":"A model identifier for the device."}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Position-swift.enum":{"title":"AVCaptureDevice.Position","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Position","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Position-swift.enum","type":"topic","navigatorTitle":[{"text":"Position","kind":"identifier"}],"role":"symbol","url":"/documentation/avfoundation/avcapturedevice/position-swift.enum","abstract":[{"text":"Constants that indicate the physical position of a capture device.","type":"text"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/position-swift.property":{"abstract":[{"text":"The physical position of the capture device hardware.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"position"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVCaptureDevice","kind":"typeIdentifier","text":"AVCaptureDevice"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@AVCaptureDevicePosition","kind":"typeIdentifier","text":"Position"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/position-swift.property","role":"symbol","url":"/documentation/avfoundation/avcapturedevice/position-swift.property","navigatorTitle":[{"kind":"identifier","text":"position"}],"type":"topic","title":"position","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/localizedName":{"title":"localizedName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/localizedName","type":"topic","navigatorTitle":[{"kind":"identifier","text":"localizedName"}],"role":"symbol","url":"/documentation/avfoundation/avcapturedevice/localizedname","abstract":[{"type":"text","text":"A localized device name for display in the user interface."}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSString"}],"abstract":[{"text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"type":"topic","title":"NSString","url":"/documentation/foundation/nsstring","kind":"symbol"},"doc://com.externally.resolved.symbol/s:SS":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SS","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"String","kind":"identifier"}],"abstract":[{"type":"text","text":"A Unicode string value that is a collection of characters."}],"type":"topic","title":"String","url":"/documentation/Swift/String","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"introducedAt":"4.0","unavailable":false,"deprecated":false,"beta":false,"name":"iOS"},{"introducedAt":"4.0","unavailable":false,"deprecated":false,"beta":false,"name":"iPadOS"},{"unavailable":false,"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false,"beta":false},{"unavailable":false,"name":"macOS","introducedAt":"10.7","deprecated":false,"beta":false},{"unavailable":false,"name":"tvOS","introducedAt":"17.0","deprecated":false,"beta":false},{"unavailable":false,"name":"visionOS","introducedAt":"1.0","deprecated":false,"beta":false}]},{"value":"Instance Property","path":"/metadata/roleHeading","op":"replace"},{"value":"uniqueID","path":"/metadata/title","op":"replace"},{"value":"property","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"uniqueID","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"anchor":"Identifying-a-Device","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/modelID","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/localizedName","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/manufacturer","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/deviceType-swift.property","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/DeviceType-swift.struct","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/position-swift.property","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Position-swift.enum"],"title":"Identifying a Device","generated":true}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"uniqueID","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","value":"AVCaptureDeviceType","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1DeviceType-swift.struct/title"},{"op":"replace","value":[{"text":"AVCaptureDeviceType","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1DeviceType-swift.struct/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AVCaptureDeviceType"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1DeviceType-swift.struct/navigatorTitle"},{"op":"replace","value":"deviceType","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1deviceType-swift.property/title"},{"op":"replace","value":[{"text":"deviceType","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1deviceType-swift.property/fragments"},{"op":"replace","value":"manufacturer","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1manufacturer/title"},{"op":"replace","value":[{"kind":"identifier","text":"manufacturer"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1manufacturer/fragments"},{"op":"replace","value":"uniqueID","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1uniqueID/title"},{"op":"replace","value":[{"kind":"identifier","text":"uniqueID"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1uniqueID/fragments"},{"op":"replace","value":"AVCaptureDevice","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/title"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/fragments","value":[{"kind":"identifier","text":"AVCaptureDevice"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/navigatorTitle","value":[{"text":"AVCaptureDevice","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1modelID/title","value":"modelID"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1modelID/fragments","value":[{"kind":"identifier","text":"modelID"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1Position-swift.enum/title","value":"AVCaptureDevicePosition"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1Position-swift.enum/fragments","value":[{"kind":"identifier","text":"AVCaptureDevicePosition"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1Position-swift.enum/navigatorTitle","value":[{"kind":"identifier","text":"AVCaptureDevicePosition"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1position-swift.property/title","value":"position"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1position-swift.property/fragments","value":[{"kind":"identifier","text":"position"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1localizedName/title","value":"localizedName"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1localizedName/fragments","value":[{"text":"localizedName","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract","value":[{"text":"A static, plain-text Unicode string object.","type":"text"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}