{
  "abstract": [
    {
      "text": "An object that contains information you want the system to use when activating a new window scene.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationRequestOptions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:objc(cs)UIWindowSceneActivationRequestOptions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ActivationRequestOptions"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ActivationRequestOptions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UIWindowScene.ActivationRequestOptions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ActivationRequestOptions"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Create a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationRequestOptions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object before you activate a scene using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/activateSceneSession(for:errorHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " (Swift) or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/activateSceneSessionForRequest:errorHandler:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " (Objective-C) method of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Use this object to specify the preferred presentation style of the new scene.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication": {
      "abstract": [
        {
          "text": "The centralized point of control and coordination for apps running in iOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIApplication"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplication"
        }
      ],
      "role": "symbol",
      "title": "UIApplication",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/activateSceneSession(for:errorHandler:)": {
      "abstract": [
        {
          "text": "Asks the system to activate an existing scene or create a new scene and associate it with your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activateSceneSession"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit31UISceneSessionActivationRequestV",
          "text": "UISceneSessionActivationRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "errorHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/activateSceneSession(for:errorHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "activateSceneSession(for:errorHandler:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/activatescenesession(for:errorhandler:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/activateSceneSessionForRequest:errorHandler:": {
      "abstract": [
        {
          "text": "Asks the system to activate an existing scene or create a new scene and associate it with your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "activateSceneSessionForRequest:errorHandler:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/activateSceneSessionForRequest:errorHandler:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activateSceneSessionForRequest:errorHandler:"
        }
      ],
      "role": "symbol",
      "title": "activateSceneSessionForRequest:errorHandler:",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/activatescenesessionforrequest:errorhandler:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationRequestOptions": {
      "abstract": [
        {
          "text": "An object that contains information you want the system to use when activating the session associated with a scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ActivationRequestOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationRequestOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ActivationRequestOptions"
        }
      ],
      "role": "symbol",
      "title": "UIScene.ActivationRequestOptions",
      "type": "topic",
      "url": "/documentation/uikit/uiscene/activationrequestoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene": {
      "abstract": [
        {
          "text": "A scene that manages one or more windows for your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIWindowScene"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWindowScene"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationAction": {
      "abstract": [
        {
          "text": "A menu element that requests a window scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ActivationAction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ActivationAction"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.ActivationAction",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/activationaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationConfiguration": {
      "abstract": [
        {
          "text": "An object that provides configuration options for a window scene request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ActivationConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ActivationConfiguration"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.ActivationConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/activationconfiguration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationInteraction": {
      "abstract": [
        {
          "text": "An interaction that facilitates activating a window scene when a user pinches out on the interaction’s view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ActivationInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ActivationInteraction"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.ActivationInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/activationinteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationRequestOptions": {
      "abstract": [
        {
          "text": "An object that contains information you want the system to use when activating a new window scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ActivationRequestOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationRequestOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ActivationRequestOptions"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.ActivationRequestOptions",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/activationrequestoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationRequestOptions/placement": {
      "abstract": [
        {
          "text": "The placement you prefer when the system activates the window scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "placement"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit22UIWindowScenePlacementP",
          "text": "UIWindowScenePlacement"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationRequestOptions/placement",
      "kind": "symbol",
      "role": "symbol",
      "title": "placement",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/activationrequestoptions/placement"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationRequestOptions/preferredPresentationStyle": {
      "abstract": [
        {
          "text": "The presentation style of the window scene.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredPresentationStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWindowScene",
          "text": "UIWindowScene"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIWindowScenePresentationStyle",
          "text": "PresentationStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationRequestOptions/preferredPresentationStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredPresentationStyle"
        }
      ],
      "role": "symbol",
      "title": "preferredPresentationStyle",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/activationrequestoptions/preferredpresentationstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/DismissalAnimation": {
      "abstract": [
        {
          "text": "Constants that indicate the types of animations available for dismissing a scene’s windows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DismissalAnimation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/DismissalAnimation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DismissalAnimation"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.DismissalAnimation",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/dismissalanimation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/PresentationStyle": {
      "abstract": [
        {
          "text": "The placement of a window scene relative to other scenes in the workspace.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PresentationStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/PresentationStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PresentationStyle"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.PresentationStyle",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/presentationstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ResizingRestrictions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ResizingRestrictions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ResizingRestrictions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ResizingRestrictions"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.ResizingRestrictions",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/resizingrestrictions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneActivationRequestOptions/placement": {
      "abstract": [
        {
          "text": "The placement you prefer when the system activates the window scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "placement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneActivationRequestOptions/placement",
      "kind": "symbol",
      "role": "symbol",
      "title": "placement",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowsceneactivationrequestoptions/placement"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneDestructionRequestOptions": {
      "abstract": [
        {
          "text": "An object that contains information to use when removing a window scene from your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIWindowSceneDestructionRequestOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneDestructionRequestOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWindowSceneDestructionRequestOptions"
        }
      ],
      "role": "symbol",
      "title": "UIWindowSceneDestructionRequestOptions",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscenedestructionrequestoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneDragInteraction": {
      "abstract": [
        {
          "text": "An interaction you add to a view that enables pan gestures to change the containing window scene’s position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIWindowSceneDragInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneDragInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWindowSceneDragInteraction"
        }
      ],
      "role": "symbol",
      "title": "UIWindowSceneDragInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscenedraginteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScenePlacement-c.class": {
      "abstract": [
        {
          "text": "The placement of a window scene in the workspace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIWindowScenePlacement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScenePlacement-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIWindowScenePlacement",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowsceneplacement-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScenePlacement-swift.protocol": {
      "abstract": [
        {
          "text": "The placement of a window scene in the workspace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIWindowScenePlacement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScenePlacement-swift.protocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWindowScenePlacement"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScenePlacement",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowsceneplacement-swift.protocol"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneProminentPlacement-c.class": {
      "abstract": [
        {
          "text": "A placement that indicates the system should present the window more prominently than others in the space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIWindowSceneProminentPlacement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneProminentPlacement-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIWindowSceneProminentPlacement",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowsceneprominentplacement-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneProminentPlacement-swift.struct": {
      "abstract": [
        {
          "text": "A placement that indicates the system should present the window more prominently than others in the space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIWindowSceneProminentPlacement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneProminentPlacement-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWindowSceneProminentPlacement"
        }
      ],
      "role": "symbol",
      "title": "UIWindowSceneProminentPlacement",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowsceneprominentplacement-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScenePushPlacement-c.class": {
      "abstract": [
        {
          "text": "A placement that indicates the system needs to present the window by pushing it onto another window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIWindowScenePushPlacement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScenePushPlacement-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIWindowScenePushPlacement",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscenepushplacement-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScenePushPlacement-swift.struct": {
      "abstract": [
        {
          "text": "A placement that indicates the system needs to present the window by pushing it onto another window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIWindowScenePushPlacement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScenePushPlacement-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWindowScenePushPlacement"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScenePushPlacement",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscenepushplacement-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneReplacePlacement-c.class": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIWindowSceneReplacePlacement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneReplacePlacement-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIWindowSceneReplacePlacement",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscenereplaceplacement-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneReplacePlacement-swift.struct": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIWindowSceneReplacePlacement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneReplacePlacement-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWindowSceneReplacePlacement"
        }
      ],
      "role": "symbol",
      "title": "UIWindowSceneReplacePlacement",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscenereplaceplacement-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneResizingRestrictions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIWindowSceneResizingRestrictions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneResizingRestrictions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWindowSceneResizingRestrictions"
        }
      ],
      "role": "symbol",
      "title": "UIWindowSceneResizingRestrictions",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowsceneresizingrestrictions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneStandardPlacement-c.class": {
      "abstract": [
        {
          "text": "A placement that indicates the system should present the window using the default style of the system in the space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIWindowSceneStandardPlacement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneStandardPlacement-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIWindowSceneStandardPlacement",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscenestandardplacement-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneStandardPlacement-swift.struct": {
      "abstract": [
        {
          "text": "A placement that indicates the system should present the window using the default style of the system in the space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIWindowSceneStandardPlacement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneStandardPlacement-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWindowSceneStandardPlacement"
        }
      ],
      "role": "symbol",
      "title": "UIWindowSceneStandardPlacement",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscenestandardplacement-swift.struct"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationRequestOptions"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Supporting-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationAction",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationConfiguration",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationInteraction",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneDestructionRequestOptions",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/DismissalAnimation",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneDragInteraction",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ResizingRestrictions",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneResizingRestrictions",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/PresentationStyle"
      ],
      "title": "Supporting types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Positioning-windows",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationRequestOptions/placement",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScenePlacement-swift.protocol",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneProminentPlacement-swift.struct",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneStandardPlacement-swift.struct",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScenePushPlacement-swift.struct"
      ],
      "title": "Positioning windows"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationRequestOptions/preferredPresentationStyle",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneReplacePlacement-swift.struct"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIWindowSceneActivationRequestOptions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Positioning-windows",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneActivationRequestOptions/placement",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScenePlacement-c.class",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneProminentPlacement-c.class",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneStandardPlacement-c.class",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScenePushPlacement-c.class"
              ],
              "title": "Positioning windows"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationRequestOptions/preferredPresentationStyle",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneReplacePlacement-c.class"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationRequestOptions"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Supporting-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationAction",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationConfiguration",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationInteraction",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneDestructionRequestOptions",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/DismissalAnimation",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneDragInteraction",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneResizingRestrictions",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/PresentationStyle"
              ],
              "title": "Supporting types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIWindowSceneActivationRequestOptions"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationRequestOptions",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UISceneActivationRequestOptions",
                    "text": "UISceneActivationRequestOptions"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowSceneResizingRestrictions/title",
          "value": "UIWindowSceneResizingRestrictions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowSceneResizingRestrictions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneResizingRestrictions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowSceneResizingRestrictions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneResizingRestrictions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/title",
          "value": "UIApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene/title",
          "value": "UIWindowScene"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowSceneDestructionRequestOptions/title",
          "value": "UIWindowSceneDestructionRequestOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowSceneDestructionRequestOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneDestructionRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowSceneDestructionRequestOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneDestructionRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationConfiguration/title",
          "value": "UIWindowSceneActivationConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationAction/title",
          "value": "UIWindowSceneActivationAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationRequestOptions~1preferredPresentationStyle/title",
          "value": "preferredPresentationStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationRequestOptions~1preferredPresentationStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredPresentationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1DismissalAnimation/title",
          "value": "UIWindowSceneDismissalAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1DismissalAnimation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneDismissalAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1DismissalAnimation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneDismissalAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationRequestOptions/title",
          "value": "UIWindowSceneActivationRequestOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationRequestOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationRequestOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene~1ActivationRequestOptions/title",
          "value": "UISceneActivationRequestOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene~1ActivationRequestOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneActivationRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene~1ActivationRequestOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneActivationRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationInteraction/title",
          "value": "UIWindowSceneActivationInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowSceneDragInteraction/title",
          "value": "UIWindowSceneDragInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowSceneDragInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneDragInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowSceneDragInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneDragInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1PresentationStyle/title",
          "value": "UIWindowScenePresentationStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1PresentationStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowScenePresentationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1PresentationStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowScenePresentationStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiwindowscene/activationrequestoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiwindowscene/activationrequestoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
