{
  "abstract": [
    {
      "text": "An object that provides configuration options for a window scene request.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationConfiguration"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:objc(cs)UIWindowSceneActivationConfiguration",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ActivationConfiguration"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ActivationConfiguration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UIWindowScene.ActivationConfiguration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ActivationConfiguration"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to request a new window scene from the system. An activation configuration requires a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsuseractivity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object that represents the scene’s content. You can specify a preferred presentation style for the new scene by including an optional ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationRequestOptions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. The system automatically animates the transition to the new scene, but you can customize the transition by providing an optional targeted preview.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To request scene activation from a view interaction, use an instance of this class with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationInteraction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". To request scene activation from a context menu, use an instance of this class with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationAction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nsuseractivity": {
      "abstract": [
        {
          "text": "A representation of the state of your app at a moment in time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSUserActivity"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsuseractivity",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUserActivity",
      "type": "topic",
      "url": "/documentation/foundation/nsuseractivity"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene": {
      "abstract": [
        {
          "text": "A scene that manages one or more windows for your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIWindowScene"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWindowScene"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationAction": {
      "abstract": [
        {
          "text": "A menu element that requests a window scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ActivationAction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ActivationAction"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.ActivationAction",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/activationaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationConfiguration": {
      "abstract": [
        {
          "text": "An object that provides configuration options for a window scene request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ActivationConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ActivationConfiguration"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.ActivationConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/activationconfiguration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationConfiguration/init(userActivity:options:preview:)": {
      "abstract": [
        {
          "text": "Creates an activation configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "userActivity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUserActivity",
          "text": "NSUserActivity"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWindowScene",
          "text": "UIWindowScene"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWindowSceneActivationRequestOptions",
          "text": "ActivationRequestOptions"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "preview"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITargetedPreview",
          "text": "UITargetedPreview"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationConfiguration/init(userActivity:options:preview:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(userActivity:options:preview:)",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/activationconfiguration/init(useractivity:options:preview:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationConfiguration/options": {
      "abstract": [
        {
          "text": "Options for customizing the scene request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWindowScene",
          "text": "UIWindowScene"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWindowSceneActivationRequestOptions",
          "text": "ActivationRequestOptions"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationConfiguration/options",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "options"
        }
      ],
      "role": "symbol",
      "title": "options",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/activationconfiguration/options"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationConfiguration/preview": {
      "abstract": [
        {
          "text": "An optional targeted preview that the system uses to animate the transition to the new scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preview"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITargetedPreview",
          "text": "UITargetedPreview"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationConfiguration/preview",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preview"
        }
      ],
      "role": "symbol",
      "title": "preview",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/activationconfiguration/preview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationConfiguration/userActivity": {
      "abstract": [
        {
          "text": "The user activity used to request a scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userActivity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUserActivity",
          "text": "NSUserActivity"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationConfiguration/userActivity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userActivity"
        }
      ],
      "role": "symbol",
      "title": "userActivity",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/activationconfiguration/useractivity"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationInteraction": {
      "abstract": [
        {
          "text": "An interaction that facilitates activating a window scene when a user pinches out on the interaction’s view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ActivationInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ActivationInteraction"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.ActivationInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/activationinteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationRequestOptions": {
      "abstract": [
        {
          "text": "An object that contains information you want the system to use when activating a new window scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ActivationRequestOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationRequestOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ActivationRequestOptions"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.ActivationRequestOptions",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/activationrequestoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/DismissalAnimation": {
      "abstract": [
        {
          "text": "Constants that indicate the types of animations available for dismissing a scene’s windows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DismissalAnimation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/DismissalAnimation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DismissalAnimation"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.DismissalAnimation",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/dismissalanimation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/PresentationStyle": {
      "abstract": [
        {
          "text": "The placement of a window scene relative to other scenes in the workspace.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PresentationStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/PresentationStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PresentationStyle"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.PresentationStyle",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/presentationstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ResizingRestrictions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ResizingRestrictions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ResizingRestrictions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ResizingRestrictions"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.ResizingRestrictions",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/resizingrestrictions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneActivationConfiguration/initWithUserActivity:": {
      "abstract": [
        {
          "text": "Creates an activation configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithUserActivity:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneActivationConfiguration/initWithUserActivity:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithUserActivity:"
        }
      ],
      "role": "symbol",
      "title": "initWithUserActivity:",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowsceneactivationconfiguration/initwithuseractivity:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneDestructionRequestOptions": {
      "abstract": [
        {
          "text": "An object that contains information to use when removing a window scene from your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIWindowSceneDestructionRequestOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneDestructionRequestOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWindowSceneDestructionRequestOptions"
        }
      ],
      "role": "symbol",
      "title": "UIWindowSceneDestructionRequestOptions",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscenedestructionrequestoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneDragInteraction": {
      "abstract": [
        {
          "text": "An interaction you add to a view that enables pan gestures to change the containing window scene’s position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIWindowSceneDragInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneDragInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWindowSceneDragInteraction"
        }
      ],
      "role": "symbol",
      "title": "UIWindowSceneDragInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscenedraginteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneResizingRestrictions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIWindowSceneResizingRestrictions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneResizingRestrictions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWindowSceneResizingRestrictions"
        }
      ],
      "role": "symbol",
      "title": "UIWindowSceneResizingRestrictions",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowsceneresizingrestrictions"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Supporting-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationAction",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationInteraction",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationRequestOptions",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneDestructionRequestOptions",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/DismissalAnimation",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneDragInteraction",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ResizingRestrictions",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneResizingRestrictions",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/PresentationStyle"
      ],
      "title": "Supporting types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-an-activation-configuration",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationConfiguration/init(userActivity:options:preview:)"
      ],
      "title": "Creating an activation configuration"
    },
    {
      "anchor": "Getting-information-about-the-activation-configuration",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationConfiguration/userActivity",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationConfiguration/options",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationRequestOptions",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationConfiguration/preview"
      ],
      "title": "Getting information about the activation configuration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIWindowSceneActivationConfiguration"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-an-activation-configuration",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneActivationConfiguration/initWithUserActivity:"
              ],
              "title": "Creating an activation configuration"
            },
            {
              "anchor": "Getting-information-about-the-activation-configuration",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationConfiguration/userActivity",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationConfiguration/options",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationRequestOptions",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationConfiguration/preview"
              ],
              "title": "Getting information about the activation configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Supporting-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationAction",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationInteraction",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationRequestOptions",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneDestructionRequestOptions",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/DismissalAnimation",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneDragInteraction",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneResizingRestrictions",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/PresentationStyle"
              ],
              "title": "Supporting types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIWindowSceneActivationConfiguration"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1DismissalAnimation/title",
          "value": "UIWindowSceneDismissalAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1DismissalAnimation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneDismissalAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1DismissalAnimation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneDismissalAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationConfiguration/title",
          "value": "UIWindowSceneActivationConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowSceneDragInteraction/title",
          "value": "UIWindowSceneDragInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowSceneDragInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneDragInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowSceneDragInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneDragInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene/title",
          "value": "UIWindowScene"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationConfiguration~1preview/title",
          "value": "preview"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationConfiguration~1preview/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preview"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowSceneDestructionRequestOptions/title",
          "value": "UIWindowSceneDestructionRequestOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowSceneDestructionRequestOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneDestructionRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowSceneDestructionRequestOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneDestructionRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationRequestOptions/title",
          "value": "UIWindowSceneActivationRequestOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationRequestOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationRequestOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationConfiguration~1userActivity/title",
          "value": "userActivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationConfiguration~1userActivity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationInteraction/title",
          "value": "UIWindowSceneActivationInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowSceneResizingRestrictions/title",
          "value": "UIWindowSceneResizingRestrictions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowSceneResizingRestrictions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneResizingRestrictions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowSceneResizingRestrictions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneResizingRestrictions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationConfiguration~1options/title",
          "value": "options"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationConfiguration~1options/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1PresentationStyle/title",
          "value": "UIWindowScenePresentationStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1PresentationStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowScenePresentationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1PresentationStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowScenePresentationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationAction/title",
          "value": "UIWindowSceneActivationAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationAction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiwindowscene/activationconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiwindowscene/activationconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
