{"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIWindowScene/screen","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"abstract":[{"text":"The screen that displays the contents of the scene.","type":"text"}],"seeAlsoSections":[{"anchor":"Getting-the-active-windows","title":"Getting the active windows","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIWindowScene/windows","doc://com.apple.uikit/documentation/UIKit/UIWindowScene/keyWindow"],"generated":true}],"variants":[{"paths":["/documentation/uikit/uiwindowscene/screen"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uiwindowscene/screen"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIWindowScene"]]},"metadata":{"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"screen","kind":"identifier"}],"modules":[{"name":"UIKit"}],"externalID":"c:objc(cs)UIWindowScene(py)screen","platforms":[{"introducedAt":"13.0","deprecated":false,"name":"iOS","beta":false,"unavailable":false},{"introducedAt":"13.0","deprecated":false,"name":"iPadOS","beta":false,"unavailable":false},{"introducedAt":"13.1","deprecated":false,"name":"Mac Catalyst","beta":false,"unavailable":false},{"introducedAt":"13.0","deprecated":false,"name":"tvOS","beta":false,"unavailable":false}],"title":"screen","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"screen","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIScreen","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScreen"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"screen","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIScreen","preciseIdentifier":"c:objc(cs)UIScreen","text":"UIScreen","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS"]}],"kind":"declarations"},{"kind":"mentions","mentions":["doc://com.apple.uikit/documentation/UIKit/presenting-content-on-a-connected-display"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.uikit/documentation/UIKit/UIWindowScene/windows":{"navigatorTitle":[{"text":"windows","kind":"identifier"}],"role":"symbol","type":"topic","title":"windows","identifier":"doc://com.apple.uikit/documentation/UIKit/UIWindowScene/windows","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"windows"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":"]"}],"abstract":[{"text":"The windows associated with the scene.","type":"text"}],"kind":"symbol","url":"/documentation/uikit/uiwindowscene/windows"},"doc://com.apple.uikit/documentation/UIKit/UIWindowScene/screen":{"navigatorTitle":[{"kind":"identifier","text":"screen"}],"role":"symbol","type":"topic","title":"screen","identifier":"doc://com.apple.uikit/documentation/UIKit/UIWindowScene/screen","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"screen"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScreen","preciseIdentifier":"c:objc(cs)UIScreen"}],"abstract":[{"text":"The screen that displays the contents of the scene.","type":"text"}],"kind":"symbol","url":"/documentation/uikit/uiwindowscene/screen"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIScreen":{"kind":"symbol","title":"UIScreen","abstract":[{"type":"text","text":"An object that defines the properties associated with a hardware-based display."}],"url":"/documentation/uikit/uiscreen","identifier":"doc://com.apple.uikit/documentation/UIKit/UIScreen","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UIScreen"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UIScreen"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/presenting-content-on-a-connected-display":{"url":"/documentation/uikit/presenting-content-on-a-connected-display","abstract":[{"type":"text","text":"Fill connected displays with additional content from your app."}],"type":"topic","kind":"article","title":"Presenting content on a connected display","identifier":"doc://com.apple.uikit/documentation/UIKit/presenting-content-on-a-connected-display","role":"article"},"doc://com.apple.uikit/documentation/UIKit/UIWindowScene/keyWindow":{"navigatorTitle":[{"kind":"identifier","text":"keyWindow"}],"role":"symbol","type":"topic","title":"keyWindow","identifier":"doc://com.apple.uikit/documentation/UIKit/UIWindowScene/keyWindow","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyWindow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":"?"}],"abstract":[{"text":"The key window associated with the scene.","type":"text"}],"kind":"symbol","url":"/documentation/uikit/uiwindowscene/keywindow"},"doc://com.apple.uikit/documentation/UIKit/UIWindowScene":{"role":"symbol","abstract":[{"type":"text","text":"A scene that manages one or more windows for your app."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIWindowScene","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIWindowScene","title":"UIWindowScene","navigatorTitle":[{"text":"UIWindowScene","kind":"identifier"}],"type":"topic","kind":"symbol","url":"/documentation/uikit/uiwindowscene"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"introducedAt":"13.0","deprecated":false,"name":"iOS","beta":false,"unavailable":false},{"introducedAt":"13.0","deprecated":false,"name":"iPadOS","beta":false,"unavailable":false},{"introducedAt":"13.1","deprecated":false,"name":"Mac Catalyst","beta":false,"unavailable":false},{"introducedAt":"13.0","deprecated":false,"name":"tvOS","beta":false,"unavailable":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"screen","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"screen","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIWindowScene"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"anchor":"Getting-the-active-windows","title":"Getting the active windows","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIWindowScene/windows","doc://com.apple.uikit/documentation/UIKit/UIWindowScene/keyWindow"]}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIScreen","identifier":"doc://com.apple.uikit/documentation/UIKit/UIScreen","text":"UIScreen","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"screen","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"value":"windows","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1windows/title"},{"value":[{"text":"windows","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1windows/fragments"},{"value":"screen","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1screen/title"},{"value":[{"kind":"identifier","text":"screen"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1screen/fragments"},{"value":"UIScreen","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen/title"},{"value":[{"text":"UIScreen","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen/fragments"},{"value":[{"kind":"identifier","text":"UIScreen"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen/navigatorTitle"},{"value":"keyWindow","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1keyWindow/title"},{"value":[{"kind":"identifier","text":"keyWindow"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1keyWindow/fragments"},{"value":"UIWindowScene","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene/title"},{"value":[{"kind":"identifier","text":"UIWindowScene"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"UIWindowScene"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}