{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIWindowScene"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uiwindowscene/traitoverrides-1klo1"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"attribute","text":"@preconcurrency"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"traitOverrides","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UITraitOverrides","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UITraitOverrides-swift.struct","preciseIdentifier":"s:5UIKit16UITraitOverridesV"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"seeAlsoSections":[{"title":"Overriding trait values","anchor":"Overriding-trait-values","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITraitOverrides-swift.struct"]}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIWindowScene/traitOverrides-1klo1","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"UIKit"}],"platforms":[{"name":"iOS","introducedAt":"17.0","beta":false,"deprecated":false,"unavailable":false},{"beta":false,"name":"iPadOS","unavailable":false,"introducedAt":"17.0","deprecated":false},{"beta":false,"name":"Mac Catalyst","unavailable":false,"deprecated":false},{"beta":false,"name":"tvOS","unavailable":false,"introducedAt":"17.0","deprecated":false},{"beta":false,"name":"visionOS","unavailable":false,"deprecated":false}],"title":"traitOverrides","role":"symbol","extendedModule":"UIKit","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"traitOverrides"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:5UIKit16UITraitOverridesV","text":"UITraitOverrides"}],"symbolKind":"property","externalID":"s:So13UIWindowSceneC5UIKitE14traitOverridesAC07UITraitE0Vvp"},"references":{"doc://com.apple.uikit/documentation/UIKit/UIWindowScene":{"role":"symbol","abstract":[{"type":"text","text":"A scene that manages one or more windows for your app."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIWindowScene","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIWindowScene","title":"UIWindowScene","navigatorTitle":[{"text":"UIWindowScene","kind":"identifier"}],"type":"topic","kind":"symbol","url":"/documentation/uikit/uiwindowscene"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITraitOverrides-swift.struct":{"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITraitOverrides","kind":"identifier"}],"abstract":[],"title":"UITraitOverrides","navigatorTitle":[{"text":"UITraitOverrides","kind":"identifier"}],"url":"/documentation/uikit/uitraitoverrides-swift.struct","role":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITraitOverrides-swift.struct"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIWindowScene/traitOverrides-1klo1":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"traitOverrides","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UITraitOverrides","preciseIdentifier":"s:5UIKit16UITraitOverridesV","kind":"typeIdentifier"}],"abstract":[],"title":"traitOverrides","url":"/documentation/uikit/uiwindowscene/traitoverrides-1klo1","role":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIWindowScene/traitOverrides-1klo1"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"UIWindowScene","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene/title","op":"replace"},{"value":[{"text":"UIWindowScene","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene/fragments","op":"replace"},{"value":[{"text":"UIWindowScene","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene/navigatorTitle","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}