{
  "abstract": [
    {
      "text": "Speech recognition (potentially including audio recording) is in progress.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.speech/documentation/Speech",
        "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskState"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskState/running"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SFSpeechRecognitionTaskState@SFSpeechRecognitionTaskStateRunning",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "running"
      }
    ],
    "modules": [
      {
        "name": "Speech"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SFSpeechRecognitionTaskStateRunning"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SFSpeechRecognitionTaskState.running"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "running"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.speech/documentation/Speech": {
      "abstract": [
        {
          "text": "Perform speech recognition on live or prerecorded audio, and receive transcriptions, alternative interpretations, and confidence levels of the results.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech",
      "kind": "symbol",
      "role": "collection",
      "title": "Speech",
      "type": "topic",
      "url": "/documentation/speech"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskState": {
      "abstract": [
        {
          "text": "The state of the task associated with the recognition request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSpeechRecognitionTaskState"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechRecognitionTaskState"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechRecognitionTaskState",
      "type": "topic",
      "url": "/documentation/speech/sfspeechrecognitiontaskstate"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskState/canceling": {
      "abstract": [
        {
          "text": "Delivery of recognition results has finished, but audio recording may be ongoing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canceling"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskState/canceling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechRecognitionTaskStateCanceling"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechRecognitionTaskState.canceling",
      "type": "topic",
      "url": "/documentation/speech/sfspeechrecognitiontaskstate/canceling"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskState/completed": {
      "abstract": [
        {
          "text": "Delivery of recognition requests has finished and audio recording has stopped.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "completed"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskState/completed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechRecognitionTaskStateCompleted"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechRecognitionTaskState.completed",
      "type": "topic",
      "url": "/documentation/speech/sfspeechrecognitiontaskstate/completed"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskState/finishing": {
      "abstract": [
        {
          "text": "Audio recording has stopped, but delivery of recognition results may continue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "finishing"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskState/finishing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechRecognitionTaskStateFinishing"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechRecognitionTaskState.finishing",
      "type": "topic",
      "url": "/documentation/speech/sfspeechrecognitiontaskstate/finishing"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskState/running": {
      "abstract": [
        {
          "text": "Speech recognition (potentially including audio recording) is in progress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "running"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskState/running",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechRecognitionTaskStateRunning"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechRecognitionTaskState.running",
      "type": "topic",
      "url": "/documentation/speech/sfspeechrecognitiontaskstate/running"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskState/starting": {
      "abstract": [
        {
          "text": "Speech recognition (potentially including audio recording) has not yet started.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "starting"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskState/starting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechRecognitionTaskStateStarting"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechRecognitionTaskState.starting",
      "type": "topic",
      "url": "/documentation/speech/sfspeechrecognitiontaskstate/starting"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskState/canceling",
        "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskState/completed",
        "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskState/finishing",
        "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskState/starting"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SFSpeechRecognitionTaskStateRunning"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognitionTaskStateRunning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.speech/documentation/Speech",
                "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskState"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskState/canceling",
                "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskState/completed",
                "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskState/finishing",
                "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskState/starting"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SFSpeechRecognitionTaskStateRunning"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskState~1completed/title",
          "value": "SFSpeechRecognitionTaskStateCompleted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskState~1completed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognitionTaskStateCompleted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskState~1running/title",
          "value": "SFSpeechRecognitionTaskStateRunning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskState~1running/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognitionTaskStateRunning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskState~1canceling/title",
          "value": "SFSpeechRecognitionTaskStateCanceling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskState~1canceling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognitionTaskStateCanceling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskState~1starting/title",
          "value": "SFSpeechRecognitionTaskStateStarting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskState~1starting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognitionTaskStateStarting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskState~1finishing/title",
          "value": "SFSpeechRecognitionTaskStateFinishing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskState~1finishing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognitionTaskStateFinishing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskState/title",
          "value": "SFSpeechRecognitionTaskState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognitionTaskState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognitionTaskState"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/speech/sfspeechrecognitiontaskstate/running"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/speech/sfspeechrecognitiontaskstate/running"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
