{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CRL_OPTIONS"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CRL_OPTIONS/init(Version:CrlFlags:crlStore:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So25CSSM_APPLE_TP_CRL_OPTIONSa7Version8CrlFlags8crlStoreABs6UInt32V_AGSpySo17cssm_dl_db_handleVGSgtcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "Version"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@uint32",
        "text": "uint32"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "CrlFlags"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CSSM_APPLE_TP_CRL_OPT_FLAGS",
        "text": "CSSM_APPLE_TP_CRL_OPT_FLAGS"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "crlStore"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@cssm_dl_db_handle",
        "text": "cssm_dl_db_handle"
      },
      {
        "kind": "text",
        "text": ">!)"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(Version:CrlFlags:crlStore:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "Version"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/uint32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint32",
              "text": "uint32"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "CrlFlags"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CRL_OPT_FLAGS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_APPLE_TP_CRL_OPT_FLAGS",
              "text": "CSSM_APPLE_TP_CRL_OPT_FLAGS"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "crlStore"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/cssm_dl_db_handle-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@cssm_dl_db_handle",
              "text": "cssm_dl_db_handle"
            },
            {
              "kind": "text",
              "text": ">!)"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CRL_OPTIONS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_TP_CRL_OPTIONS"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CRL_OPTIONS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_TP_CRL_OPTIONS"
        }
      ],
      "role": "symbol",
      "title": "CSSM_APPLE_TP_CRL_OPTIONS",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_crl_options"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CRL_OPTIONS/init(Version:CrlFlags:crlStore:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "Version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "CrlFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CSSM_APPLE_TP_CRL_OPT_FLAGS",
          "text": "CSSM_APPLE_TP_CRL_OPT_FLAGS"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "crlStore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@cssm_dl_db_handle",
          "text": "cssm_dl_db_handle"
        },
        {
          "kind": "text",
          "text": ">!)"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CRL_OPTIONS/init(Version:CrlFlags:crlStore:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(Version:CrlFlags:crlStore:)",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_crl_options/init(version:crlflags:crlstore:)"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CRL_OPT_FLAGS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_TP_CRL_OPT_FLAGS"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CRL_OPT_FLAGS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_TP_CRL_OPT_FLAGS"
        }
      ],
      "role": "symbol",
      "title": "CSSM_APPLE_TP_CRL_OPT_FLAGS",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_crl_opt_flags"
    },
    "doc://com.apple.security/documentation/Security/cssm_dl_db_handle-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cssm_dl_db_handle"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_dl_db_handle-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cssm_dl_db_handle"
        }
      ],
      "role": "symbol",
      "title": "cssm_dl_db_handle",
      "type": "topic",
      "url": "/documentation/security/cssm_dl_db_handle-swift.struct"
    },
    "doc://com.apple.security/documentation/Security/uint32": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uint32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/uint32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "uint32"
        }
      ],
      "role": "symbol",
      "title": "uint32",
      "type": "topic",
      "url": "/documentation/security/uint32"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1uint32/title",
          "value": "uint32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1uint32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "uint32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1uint32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "uint32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CRL_OPTIONS/title",
          "value": "CSSM_APPLE_TP_CRL_OPTIONS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CRL_OPTIONS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_TP_CRL_OPTIONS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CRL_OPTIONS/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_TP_CRL_OPTIONS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CRL_OPT_FLAGS/title",
          "value": "CSSM_APPLE_TP_CRL_OPT_FLAGS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CRL_OPT_FLAGS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_TP_CRL_OPT_FLAGS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CRL_OPT_FLAGS/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_TP_CRL_OPT_FLAGS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_dl_db_handle-swift.struct/title",
          "value": "cssm_dl_db_handle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_dl_db_handle-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_dl_db_handle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_dl_db_handle-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_dl_db_handle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/cssm_apple_tp_crl_options/init(version:crlflags:crlstore:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
