{
  "abstract": [
    {
      "text": "The user or the issuer has suspended the pass and it isn’t available to use.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass",
        "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/PassActivationState-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/PassActivationState-swift.enum/suspended"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PKSecureElementPassActivationState@PKSecureElementPassActivationStateSuspended",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "suspended"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKSecureElementPassActivationStateSuspended"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PKSecureElementPass.PassActivationState.suspended"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "suspended"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass": {
      "abstract": [
        {
          "text": "A pass with a credential that the device stores in a certified payment information chip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKSecureElementPass"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKSecureElementPass"
        }
      ],
      "role": "symbol",
      "title": "PKSecureElementPass",
      "type": "topic",
      "url": "/documentation/passkit/pksecureelementpass"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/PassActivationState-swift.enum": {
      "abstract": [
        {
          "text": "The activation states of a Secure Element pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PassActivationState"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/PassActivationState-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PassActivationState"
        }
      ],
      "role": "symbol",
      "title": "PKSecureElementPass.PassActivationState",
      "type": "topic",
      "url": "/documentation/passkit/pksecureelementpass/passactivationstate-swift.enum"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/PassActivationState-swift.enum/activated": {
      "abstract": [
        {
          "text": "The pass is active and ready to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activated"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/PassActivationState-swift.enum/activated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKSecureElementPassActivationStateActivated"
        }
      ],
      "role": "symbol",
      "title": "PKSecureElementPass.PassActivationState.activated",
      "type": "topic",
      "url": "/documentation/passkit/pksecureelementpass/passactivationstate-swift.enum/activated"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/PassActivationState-swift.enum/activating": {
      "abstract": [
        {
          "text": "The pass isn’t ready to use, but activation is in progress",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activating"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/PassActivationState-swift.enum/activating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKSecureElementPassActivationStateActivating"
        }
      ],
      "role": "symbol",
      "title": "PKSecureElementPass.PassActivationState.activating",
      "type": "topic",
      "url": "/documentation/passkit/pksecureelementpass/passactivationstate-swift.enum/activating"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/PassActivationState-swift.enum/deactivated": {
      "abstract": [
        {
          "text": "The issuer has deactivated the pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deactivated"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/PassActivationState-swift.enum/deactivated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKSecureElementPassActivationStateDeactivated"
        }
      ],
      "role": "symbol",
      "title": "PKSecureElementPass.PassActivationState.deactivated",
      "type": "topic",
      "url": "/documentation/passkit/pksecureelementpass/passactivationstate-swift.enum/deactivated"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/PassActivationState-swift.enum/requiresActivation": {
      "abstract": [
        {
          "text": "The pass requires activation by the issuer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requiresActivation"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/PassActivationState-swift.enum/requiresActivation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKSecureElementPassActivationStateRequiresActivation"
        }
      ],
      "role": "symbol",
      "title": "PKSecureElementPass.PassActivationState.requiresActivation",
      "type": "topic",
      "url": "/documentation/passkit/pksecureelementpass/passactivationstate-swift.enum/requiresactivation"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/PassActivationState-swift.enum/suspended": {
      "abstract": [
        {
          "text": "The user or the issuer has suspended the pass and it isn’t available to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "suspended"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/PassActivationState-swift.enum/suspended",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKSecureElementPassActivationStateSuspended"
        }
      ],
      "role": "symbol",
      "title": "PKSecureElementPass.PassActivationState.suspended",
      "type": "topic",
      "url": "/documentation/passkit/pksecureelementpass/passactivationstate-swift.enum/suspended"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Activation-states",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/PassActivationState-swift.enum/requiresActivation",
        "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/PassActivationState-swift.enum/activating",
        "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/PassActivationState-swift.enum/activated",
        "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/PassActivationState-swift.enum/deactivated"
      ],
      "title": "Activation states"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKSecureElementPassActivationStateSuspended"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSecureElementPassActivationStateSuspended"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit",
                "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/PassActivationState-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Activation-states",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/PassActivationState-swift.enum/requiresActivation",
                "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/PassActivationState-swift.enum/activating",
                "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/PassActivationState-swift.enum/activated",
                "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass/PassActivationState-swift.enum/deactivated"
              ],
              "title": "Activation states"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PKSecureElementPassActivationStateSuspended"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1PassActivationState-swift.enum~1suspended/title",
          "value": "PKSecureElementPassActivationStateSuspended"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1PassActivationState-swift.enum~1suspended/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSecureElementPassActivationStateSuspended"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1PassActivationState-swift.enum~1activating/title",
          "value": "PKSecureElementPassActivationStateActivating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1PassActivationState-swift.enum~1activating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSecureElementPassActivationStateActivating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass/title",
          "value": "PKSecureElementPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSecureElementPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSecureElementPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1PassActivationState-swift.enum~1activated/title",
          "value": "PKSecureElementPassActivationStateActivated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1PassActivationState-swift.enum~1activated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSecureElementPassActivationStateActivated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1PassActivationState-swift.enum~1requiresActivation/title",
          "value": "PKSecureElementPassActivationStateRequiresActivation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1PassActivationState-swift.enum~1requiresActivation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSecureElementPassActivationStateRequiresActivation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1PassActivationState-swift.enum~1deactivated/title",
          "value": "PKSecureElementPassActivationStateDeactivated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1PassActivationState-swift.enum~1deactivated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSecureElementPassActivationStateDeactivated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1PassActivationState-swift.enum/title",
          "value": "PKSecureElementPassActivationState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1PassActivationState-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSecureElementPassActivationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass~1PassActivationState-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSecureElementPassActivationState"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pksecureelementpass/passactivationstate-swift.enum/suspended"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pksecureelementpass/passactivationstate-swift.enum/suspended"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
