{
  "abstract": [
    {
      "text": "An enumeration that lists policies for how a web view that’s not in a window handles tasks.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/WKPreferences"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "WebKit",
    "externalID": "c:@E@WKInactiveSchedulingPolicy",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "InactiveSchedulingPolicy"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "InactiveSchedulingPolicy"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "WKPreferences.InactiveSchedulingPolicy"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "InactiveSchedulingPolicy"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKPreferences": {
      "abstract": [
        {
          "text": "An object that encapsulates the standard behaviors to apply to websites.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKPreferences"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKPreferences",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKPreferences"
        }
      ],
      "role": "symbol",
      "title": "WKPreferences",
      "type": "topic",
      "url": "/documentation/webkit/wkpreferences"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum": {
      "abstract": [
        {
          "text": "An enumeration that lists policies for how a web view that’s not in a window handles tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "InactiveSchedulingPolicy"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "InactiveSchedulingPolicy"
        }
      ],
      "role": "symbol",
      "title": "WKPreferences.InactiveSchedulingPolicy",
      "type": "topic",
      "url": "/documentation/webkit/wkpreferences/inactiveschedulingpolicy-swift.enum"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/webkit/wkpreferences/inactiveschedulingpolicy-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum/none": {
      "abstract": [
        {
          "text": "A policy where a web view that’s not in a window runs tasks normally.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInactiveSchedulingPolicyNone"
        }
      ],
      "role": "symbol",
      "title": "WKPreferences.InactiveSchedulingPolicy.none",
      "type": "topic",
      "url": "/documentation/webkit/wkpreferences/inactiveschedulingpolicy-swift.enum/none"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum/suspend": {
      "abstract": [
        {
          "text": "A policy where a web view that’s not in a window fully suspends tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "suspend"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum/suspend",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInactiveSchedulingPolicySuspend"
        }
      ],
      "role": "symbol",
      "title": "WKPreferences.InactiveSchedulingPolicy.suspend",
      "type": "topic",
      "url": "/documentation/webkit/wkpreferences/inactiveschedulingpolicy-swift.enum/suspend"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum/throttle": {
      "abstract": [
        {
          "text": "A policy where a web view that’s not in a window limits processing, but does not fully suspend tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "throttle"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum/throttle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInactiveSchedulingPolicyThrottle"
        }
      ],
      "role": "symbol",
      "title": "WKPreferences.InactiveSchedulingPolicy.throttle",
      "type": "topic",
      "url": "/documentation/webkit/wkpreferences/inactiveschedulingpolicy-swift.enum/throttle"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKPreferences/inactiveSchedulingPolicy-swift.property": {
      "abstract": [
        {
          "text": "A policy you set to specify how a web view that’s not in a window handles tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inactiveSchedulingPolicy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKPreferences",
          "text": "WKPreferences"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKInactiveSchedulingPolicy",
          "text": "InactiveSchedulingPolicy"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKPreferences/inactiveSchedulingPolicy-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inactiveSchedulingPolicy"
        }
      ],
      "role": "symbol",
      "title": "inactiveSchedulingPolicy",
      "type": "topic",
      "url": "/documentation/webkit/wkpreferences/inactiveschedulingpolicy-swift.property"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKPreferences/isElementFullscreenEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether a web view can display content full screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isElementFullscreenEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKPreferences/isElementFullscreenEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "elementFullscreenEnabled"
        }
      ],
      "role": "symbol",
      "title": "isElementFullscreenEnabled",
      "type": "topic",
      "url": "/documentation/webkit/wkpreferences/iselementfullscreenenabled"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKPreferences/isTextInteractionEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to allow people to select or otherwise interact with text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isTextInteractionEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKPreferences/isTextInteractionEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textInteractionEnabled"
        }
      ],
      "role": "symbol",
      "title": "isTextInteractionEnabled",
      "type": "topic",
      "url": "/documentation/webkit/wkpreferences/istextinteractionenabled"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKPreferences/tabFocusesLinks": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether pressing the tab key changes the focus to links and form controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabFocusesLinks"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKPreferences/tabFocusesLinks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabFocusesLinks"
        }
      ],
      "role": "symbol",
      "title": "tabFocusesLinks",
      "type": "topic",
      "url": "/documentation/webkit/wkpreferences/tabfocuseslinks"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Setting-Behavior-Preferences",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKPreferences/tabFocusesLinks",
        "doc://com.apple.webkit/documentation/WebKit/WKPreferences/isTextInteractionEnabled",
        "doc://com.apple.webkit/documentation/WebKit/WKPreferences/isElementFullscreenEnabled",
        "doc://com.apple.webkit/documentation/WebKit/WKPreferences/inactiveSchedulingPolicy-swift.property"
      ],
      "title": "Setting Behavior Preferences"
    }
  ],
  "topicSections": [
    {
      "anchor": "Scheduling-policies",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum/none",
        "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum/suspend",
        "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum/throttle"
      ],
      "title": "Scheduling policies"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKInactiveSchedulingPolicy"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInactiveSchedulingPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInactiveSchedulingPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Scheduling-policies",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum/none",
                "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum/suspend",
                "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum/throttle"
              ],
              "title": "Scheduling policies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Setting-Behavior-Preferences",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKPreferences/tabFocusesLinks",
                "doc://com.apple.webkit/documentation/WebKit/WKPreferences/isTextInteractionEnabled",
                "doc://com.apple.webkit/documentation/WebKit/WKPreferences/isElementFullscreenEnabled",
                "doc://com.apple.webkit/documentation/WebKit/WKPreferences/inactiveSchedulingPolicy-swift.property"
              ],
              "title": "Setting Behavior Preferences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "WKInactiveSchedulingPolicy"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences~1InactiveSchedulingPolicy-swift.enum/title",
          "value": "WKInactiveSchedulingPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences~1InactiveSchedulingPolicy-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInactiveSchedulingPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences~1InactiveSchedulingPolicy-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInactiveSchedulingPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences/title",
          "value": "WKPreferences"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKPreferences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKPreferences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences~1tabFocusesLinks/title",
          "value": "tabFocusesLinks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences~1tabFocusesLinks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tabFocusesLinks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences~1InactiveSchedulingPolicy-swift.enum~1suspend/title",
          "value": "WKInactiveSchedulingPolicySuspend"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences~1InactiveSchedulingPolicy-swift.enum~1suspend/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInactiveSchedulingPolicySuspend"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences~1isElementFullscreenEnabled/title",
          "value": "elementFullscreenEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences~1isElementFullscreenEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "elementFullscreenEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences~1isTextInteractionEnabled/title",
          "value": "textInteractionEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences~1isTextInteractionEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "textInteractionEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences~1inactiveSchedulingPolicy-swift.property/title",
          "value": "inactiveSchedulingPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences~1inactiveSchedulingPolicy-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inactiveSchedulingPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences~1InactiveSchedulingPolicy-swift.enum~1throttle/title",
          "value": "WKInactiveSchedulingPolicyThrottle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences~1InactiveSchedulingPolicy-swift.enum~1throttle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInactiveSchedulingPolicyThrottle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences~1InactiveSchedulingPolicy-swift.enum~1none/title",
          "value": "WKInactiveSchedulingPolicyNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences~1InactiveSchedulingPolicy-swift.enum~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInactiveSchedulingPolicyNone"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/wkpreferences/inactiveschedulingpolicy-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/wkpreferences/inactiveschedulingpolicy-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
