{
  "abstract": [
    {
      "text": "Creates a verdict to drop the current chunk of network data and all subsequent data for the current flow, and provides a remediation URL.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict/remediateVerdict(withRemediationURLMapKey:remediationButtonTextMapKey:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NEFilterDataVerdict(cm)remediateVerdictWithRemediationURLMapKey:remediationButtonTextMapKey:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "remediateVerdict"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "withRemediationURLMapKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "remediationButtonTextMapKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": "?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NEFilterDataVerdict",
        "text": "NEFilterDataVerdict"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "remediateVerdictWithRemediationURLMapKey:remediationButtonTextMapKey:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "remediateVerdict(withRemediationURLMapKey:remediationButtonTextMapKey:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "remediateVerdict"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "withRemediationURLMapKey"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "remediationURLMapKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "remediationButtonTextMapKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": "?) -> "
            },
            {
              "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NEFilterDataVerdict",
              "text": "NEFilterDataVerdict"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The key in the Filter Control Provider’s ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterControlProvider/remediationMap",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " dictionary corresponding to the URL of the remediation link to give to the user.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "remediationURLMapKey"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The key in the Filter Control Provider’s ",
                  "type": "text"
                },
                {
                  "code": "remediationMap",
                  "type": "codeVoice"
                },
                {
                  "text": " dictionary that corresponds to the text of the remediation link text to give to the user.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "remediationButtonTextMapKey"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "code": "NEFilterDataVerdict",
              "type": "codeVoice"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When the Filter Data Provider returns this verdict from one of its data filtering methods, the system resolves the verdict as follows:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The system uses the verdict’s ",
                      "type": "text"
                    },
                    {
                      "code": "remediationURLMapKey",
                      "type": "codeVoice"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "code": "remediationButtonTextMapKey",
                      "type": "codeVoice"
                    },
                    {
                      "text": " to look up the remediation URL parameters in the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterControlProvider/remediationMap",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " dictionary set by the Filter Control Provider.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The system then inserts the remediation URL parameters into the block page and presents it to the user.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The user can tap the URL to appeal the decision to drop the flow. This starts the remediation process, if your app provides one.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterControlProvider/remediationMap": {
      "abstract": [
        {
          "text": "A dictionary containing sets of strings used to customize the remediation portion of the block page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remediationMap"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSObject",
          "text": "NSObject"
        },
        {
          "kind": "text",
          "text": "]]?"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterControlProvider/remediationMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "remediationMap"
        }
      ],
      "role": "symbol",
      "title": "remediationMap",
      "type": "topic",
      "url": "/documentation/networkextension/nefiltercontrolprovider/remediationmap"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict": {
      "abstract": [
        {
          "text": "The result from a filter data provder for subsequent chunks of data on a flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEFilterDataVerdict"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterDataVerdict"
        }
      ],
      "role": "symbol",
      "title": "NEFilterDataVerdict",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterdataverdict"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict/allow()": {
      "abstract": [
        {
          "text": "Creates a verdict that tells the system to pass the current chunk of network data and all subsequent data for the current flow to its final destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allow"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NEFilterDataVerdict",
          "text": "NEFilterDataVerdict"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict/allow()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowVerdict"
        }
      ],
      "role": "symbol",
      "title": "allow()",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterdataverdict/allow()"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict/drop()": {
      "abstract": [
        {
          "text": "Creates a verdict that tells the system to drop the current chunk of network data and all subsequent data for the current flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drop"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NEFilterDataVerdict",
          "text": "NEFilterDataVerdict"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict/drop()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dropVerdict"
        }
      ],
      "role": "symbol",
      "title": "drop()",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterdataverdict/drop()"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict/init(passBytes:peekBytes:)": {
      "abstract": [
        {
          "text": "Creates a verdict that tells the system to pass a chunk of network data to its final destination, and specifies the next chunk of data to provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "passBytes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "peekBytes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict/init(passBytes:peekBytes:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dataVerdictWithPassBytes:peekBytes:"
        }
      ],
      "role": "symbol",
      "title": "init(passBytes:peekBytes:)",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterdataverdict/init(passbytes:peekbytes:)"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict/needRules()": {
      "abstract": [
        {
          "text": "Creates a verdict that tells the system that the Filter Control Provider needs to update the rules before making a decision about the flow’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "needRules"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NEFilterDataVerdict",
          "text": "NEFilterDataVerdict"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict/needRules()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "needRulesVerdict"
        }
      ],
      "role": "symbol",
      "title": "needRules()",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterdataverdict/needrules()"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict/pause()": {
      "abstract": [
        {
          "text": "Creates a verdict that tells the system to pause the flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pause"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NEFilterDataVerdict",
          "text": "NEFilterDataVerdict"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict/pause()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pauseVerdict"
        }
      ],
      "role": "symbol",
      "title": "pause()",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterdataverdict/pause()"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict/remediateVerdict(withRemediationURLMapKey:remediationButtonTextMapKey:)": {
      "abstract": [
        {
          "text": "Creates a verdict to drop the current chunk of network data and all subsequent data for the current flow, and provides a remediation URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remediateVerdict"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withRemediationURLMapKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "remediationButtonTextMapKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NEFilterDataVerdict",
          "text": "NEFilterDataVerdict"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict/remediateVerdict(withRemediationURLMapKey:remediationButtonTextMapKey:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "remediateVerdictWithRemediationURLMapKey:remediationButtonTextMapKey:"
        }
      ],
      "role": "symbol",
      "title": "remediateVerdict(withRemediationURLMapKey:remediationButtonTextMapKey:)",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterdataverdict/remediateverdict(withremediationurlmapkey:remediationbuttontextmapkey:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-data-verdicts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict/allow()",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict/drop()",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict/pause()",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict/needRules()",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict/init(passBytes:peekBytes:)"
      ],
      "title": "Creating data verdicts"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "remediateVerdictWithRemediationURLMapKey:remediationButtonTextMapKey:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "remediateVerdictWithRemediationURLMapKey:remediationButtonTextMapKey:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-data-verdicts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict/allow()",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict/drop()",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict/pause()",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict/needRules()",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict/init(passBytes:peekBytes:)"
              ],
              "title": "Creating data verdicts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NEFilterDataVerdict",
                    "text": "NEFilterDataVerdict"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "remediateVerdictWithRemediationURLMapKey:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "remediationURLMapKey"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "remediationButtonTextMapKey:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "remediationButtonTextMapKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The key in the Filter Control Provider’s ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterControlProvider/remediationMap",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " dictionary corresponding to the URL of the remediation link to give to the user.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "remediationURLMapKey"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The key in the Filter Control Provider’s ",
                        "type": "text"
                      },
                      {
                        "code": "remediationMap",
                        "type": "codeVoice"
                      },
                      {
                        "text": " dictionary that corresponds to the text of the remediation link text to give to the user.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "remediationButtonTextMapKey"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A ",
                    "type": "text"
                  },
                  {
                    "code": "NEFilterDataVerdict",
                    "type": "codeVoice"
                  },
                  {
                    "text": " object.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterDataVerdict~1drop()/title",
          "value": "dropVerdict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterDataVerdict~1drop()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "dropVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterDataVerdict~1needRules()/title",
          "value": "needRulesVerdict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterDataVerdict~1needRules()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "needRulesVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterDataVerdict~1pause()/title",
          "value": "pauseVerdict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterDataVerdict~1pause()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "pauseVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterDataVerdict/title",
          "value": "NEFilterDataVerdict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterDataVerdict/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterDataVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterDataVerdict/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterDataVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterDataVerdict~1init(passBytes:peekBytes:)/title",
          "value": "dataVerdictWithPassBytes:peekBytes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterDataVerdict~1init(passBytes:peekBytes:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "dataVerdictWithPassBytes:peekBytes:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterControlProvider~1remediationMap/title",
          "value": "remediationMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterControlProvider~1remediationMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "remediationMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterDataVerdict~1remediateVerdict(withRemediationURLMapKey:remediationButtonTextMapKey:)/title",
          "value": "remediateVerdictWithRemediationURLMapKey:remediationButtonTextMapKey:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterDataVerdict~1remediateVerdict(withRemediationURLMapKey:remediationButtonTextMapKey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "remediateVerdictWithRemediationURLMapKey:remediationButtonTextMapKey:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterDataVerdict~1allow()/title",
          "value": "allowVerdict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterDataVerdict~1allow()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "allowVerdict"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nefilterdataverdict/remediateverdict(withremediationurlmapkey:remediationbuttontextmapkey:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nefilterdataverdict/remediateverdict(withremediationurlmapkey:remediationbuttontextmapkey:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
