{
  "abstract": [
    {
      "text": "Returns a sample predicate that matches audiogram samples.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/audiogram(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:9HealthKit17HKSamplePredicateV9audiogramyACySo17HKAudiogramSampleCGSo11NSPredicateCSgFZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "audiogram"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSPredicate",
        "text": "NSPredicate"
      },
      {
        "kind": "text",
        "text": "?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:9HealthKit17HKSamplePredicateV",
        "text": "HKSamplePredicate"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)HKAudiogramSample",
        "text": "HKAudiogramSample"
      },
      {
        "kind": "text",
        "text": ">"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.5",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "audiogram(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "audiogram"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "predicate"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSPredicate",
              "text": "NSPredicate"
            },
            {
              "kind": "text",
              "text": "? = nil) -> "
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:9HealthKit17HKSamplePredicateV",
              "text": "HKSamplePredicate"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramSample",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)HKAudiogramSample",
              "text": "HKAudiogramSample"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An optional predicate that further restricts the results that the query returns.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "predicate"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this method to create an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance that you can use to query for ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramSample",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramSample": {
      "abstract": [
        {
          "text": "A sample that stores an audiogram.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKAudiogramSample"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramSample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKAudiogramSample"
        }
      ],
      "role": "symbol",
      "title": "HKAudiogramSample",
      "type": "topic",
      "url": "/documentation/healthkit/hkaudiogramsample"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate": {
      "abstract": [
        {
          "text": "A predicate for queries that return a collection of matching sample objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKSamplePredicate"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSamplePredicate"
        }
      ],
      "role": "symbol",
      "title": "HKSamplePredicate",
      "type": "topic",
      "url": "/documentation/healthkit/hksamplepredicate"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/audiogram(_:)": {
      "abstract": [
        {
          "text": "Returns a sample predicate that matches audiogram samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audiogram"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9HealthKit17HKSamplePredicateV",
          "text": "HKSamplePredicate"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKAudiogramSample",
          "text": "HKAudiogramSample"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/audiogram(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "audiogram(_:)",
      "type": "topic",
      "url": "/documentation/healthkit/hksamplepredicate/audiogram(_:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/categorySample(type:predicate:)": {
      "abstract": [
        {
          "text": "Returns a sample predicate that matches category samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "categorySample"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKCategoryType",
          "text": "HKCategoryType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "predicate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9HealthKit17HKSamplePredicateV",
          "text": "HKSamplePredicate"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKCategorySample",
          "text": "HKCategorySample"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/categorySample(type:predicate:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "categorySample(type:predicate:)",
      "type": "topic",
      "url": "/documentation/healthkit/hksamplepredicate/categorysample(type:predicate:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/clinicalRecord(type:predicate:)": {
      "abstract": [
        {
          "text": "Returns a sample predicate that matches clinical record samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clinicalRecord"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKClinicalType",
          "text": "HKClinicalType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "predicate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9HealthKit17HKSamplePredicateV",
          "text": "HKSamplePredicate"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKClinicalRecord",
          "text": "HKClinicalRecord"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/clinicalRecord(type:predicate:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "clinicalRecord(type:predicate:)",
      "type": "topic",
      "url": "/documentation/healthkit/hksamplepredicate/clinicalrecord(type:predicate:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/correlation(type:predicate:)": {
      "abstract": [
        {
          "text": "Returns a sample predicate that matches samples that contain correlated data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "correlation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKCorrelationType",
          "text": "HKCorrelationType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "predicate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9HealthKit17HKSamplePredicateV",
          "text": "HKSamplePredicate"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKCorrelation",
          "text": "HKCorrelation"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/correlation(type:predicate:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "correlation(type:predicate:)",
      "type": "topic",
      "url": "/documentation/healthkit/hksamplepredicate/correlation(type:predicate:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/electrocardiogram(_:)": {
      "abstract": [
        {
          "text": "Returns a sample predicate that matches electrocardiogram samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "electrocardiogram"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9HealthKit17HKSamplePredicateV",
          "text": "HKSamplePredicate"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKElectrocardiogram",
          "text": "HKElectrocardiogram"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/electrocardiogram(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "electrocardiogram(_:)",
      "type": "topic",
      "url": "/documentation/healthkit/hksamplepredicate/electrocardiogram(_:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/heartbeatSeries(_:)": {
      "abstract": [
        {
          "text": "Returns a sample predicate that matches heartbeat series samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "heartbeatSeries"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9HealthKit17HKSamplePredicateV",
          "text": "HKSamplePredicate"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKHeartbeatSeriesSample",
          "text": "HKHeartbeatSeriesSample"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/heartbeatSeries(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "heartbeatSeries(_:)",
      "type": "topic",
      "url": "/documentation/healthkit/hksamplepredicate/heartbeatseries(_:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/quantitySample(type:predicate:)": {
      "abstract": [
        {
          "text": "Returns a sample predicate that matches quantity samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quantitySample"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKQuantityType",
          "text": "HKQuantityType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "predicate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9HealthKit17HKSamplePredicateV",
          "text": "HKSamplePredicate"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKQuantitySample",
          "text": "HKQuantitySample"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/quantitySample(type:predicate:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "quantitySample(type:predicate:)",
      "type": "topic",
      "url": "/documentation/healthkit/hksamplepredicate/quantitysample(type:predicate:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/sample(type:predicate:)": {
      "abstract": [
        {
          "text": "Returns a sample predicate that matches samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sample"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKSampleType",
          "text": "HKSampleType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "predicate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9HealthKit17HKSamplePredicateV",
          "text": "HKSamplePredicate"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKSample",
          "text": "HKSample"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/sample(type:predicate:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "sample(type:predicate:)",
      "type": "topic",
      "url": "/documentation/healthkit/hksamplepredicate/sample(type:predicate:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/visionPrescription(_:)": {
      "abstract": [
        {
          "text": "Returns a predicate that matches prescription samples.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Sample",
            "type": "codeVoice"
          },
          {
            "text": " inherits ",
            "type": "text"
          },
          {
            "code": "HKSample",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visionPrescription"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9HealthKit17HKSamplePredicateV",
          "text": "HKSamplePredicate"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKVisionPrescription",
          "text": "HKVisionPrescription"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/visionPrescription(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "visionPrescription(_:)",
      "type": "topic",
      "url": "/documentation/healthkit/hksamplepredicate/visionprescription(_:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/workout(_:)": {
      "abstract": [
        {
          "text": "Returns a sample predicate that matches workout samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workout"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9HealthKit17HKSamplePredicateV",
          "text": "HKSamplePredicate"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKWorkout",
          "text": "HKWorkout"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/workout(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "workout(_:)",
      "type": "topic",
      "url": "/documentation/healthkit/hksamplepredicate/workout(_:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/workoutRoute(_:)": {
      "abstract": [
        {
          "text": "Returns a sample predicate that matches samples containing workout route data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workoutRoute"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9HealthKit17HKSamplePredicateV",
          "text": "HKSamplePredicate"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKWorkoutRoute",
          "text": "HKWorkoutRoute"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/workoutRoute(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "workoutRoute(_:)",
      "type": "topic",
      "url": "/documentation/healthkit/hksamplepredicate/workoutroute(_:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate": {
      "abstract": [
        {
          "text": "A definition of logical conditions for constraining a search for a fetch or for in-memory filtering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSPredicate"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPredicate",
      "type": "topic",
      "url": "/documentation/foundation/nspredicate"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-Sample-Predicates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/categorySample(type:predicate:)",
        "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/clinicalRecord(type:predicate:)",
        "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/correlation(type:predicate:)",
        "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/electrocardiogram(_:)",
        "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/heartbeatSeries(_:)",
        "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/quantitySample(type:predicate:)",
        "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/sample(type:predicate:)",
        "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/visionPrescription(_:)",
        "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/workout(_:)",
        "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/workoutRoute(_:)"
      ],
      "title": "Creating Sample Predicates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAudiogramSample/title",
          "value": "HKAudiogramSample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAudiogramSample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAudiogramSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAudiogramSample/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAudiogramSample"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hksamplepredicate/audiogram(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
