{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/stateOfMind(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "conformance": {
      "availabilityPrefix": [
        {
          "text": "Available when",
          "type": "text"
        }
      ],
      "conformancePrefix": [
        {
          "text": "Conforms when",
          "type": "text"
        }
      ],
      "constraints": [
        {
          "code": "Sample",
          "type": "codeVoice"
        },
        {
          "text": " inherits ",
          "type": "text"
        },
        {
          "code": "HKSample",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ]
    },
    "extendedModule": "HealthKit",
    "externalID": "s:9HealthKit17HKSamplePredicateV11stateOfMindyACySo07HKStatefG0CGSo11NSPredicateCSgFZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "stateOfMind"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSPredicate",
        "text": "NSPredicate"
      },
      {
        "kind": "text",
        "text": "?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:9HealthKit17HKSamplePredicateV",
        "text": "HKSamplePredicate"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)HKStateOfMind",
        "text": "HKStateOfMind"
      },
      {
        "kind": "text",
        "text": ">"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "stateOfMind(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "stateOfMind"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "predicate"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSPredicate",
              "text": "NSPredicate"
            },
            {
              "kind": "text",
              "text": "? = nil) -> "
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:9HealthKit17HKSamplePredicateV",
              "text": "HKSamplePredicate"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)HKStateOfMind",
              "text": "HKStateOfMind"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate": {
      "abstract": [
        {
          "text": "A predicate for queries that return a collection of matching sample objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKSamplePredicate"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSamplePredicate"
        }
      ],
      "role": "symbol",
      "title": "HKSamplePredicate",
      "type": "topic",
      "url": "/documentation/healthkit/hksamplepredicate"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/stateOfMind(_:)": {
      "abstract": [],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Sample",
            "type": "codeVoice"
          },
          {
            "text": " inherits ",
            "type": "text"
          },
          {
            "code": "HKSample",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stateOfMind"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9HealthKit17HKSamplePredicateV",
          "text": "HKSamplePredicate"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKStateOfMind",
          "text": "HKStateOfMind"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate/stateOfMind(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "stateOfMind(_:)",
      "type": "topic",
      "url": "/documentation/healthkit/hksamplepredicate/stateofmind(_:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKStateOfMind"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStateOfMind"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMind",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmind"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate": {
      "abstract": [
        {
          "text": "A definition of logical conditions for constraining a search for a fetch or for in-memory filtering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSPredicate"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPredicate",
      "type": "topic",
      "url": "/documentation/foundation/nspredicate"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind/title",
          "value": "HKStateOfMind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMind"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hksamplepredicate/stateofmind(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
