{
  "abstract": [
    {
      "text": "Use the Legacy OpenGL API for SceneKit rendering in macOS.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderingAPI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderingAPI/openGLLegacy"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SCNRenderingAPI@SCNRenderingAPIOpenGLLegacy",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "openGLLegacy"
      }
    ],
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SCNRenderingAPIOpenGLLegacy"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SCNRenderingAPI.openGLLegacy"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "openGLLegacy"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This option is available on all macOS systems supporting SceneKit. If you request the Metal rendering API for an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object on a system that does not support Metal, SceneKit falls back to the Legacy OpenGL API.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderingAPI": {
      "abstract": [
        {
          "text": "Options for choosing the graphics technology for an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object (or other SceneKit renderer) to use for drawing its contents. Used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/renderingAPI",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property and the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNView/Option/preferredRenderingAPI",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " option when initializing an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNRenderingAPI"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderingAPI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNRenderingAPI"
        }
      ],
      "role": "symbol",
      "title": "SCNRenderingAPI",
      "type": "topic",
      "url": "/documentation/scenekit/scnrenderingapi"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderingAPI/metal": {
      "abstract": [
        {
          "text": "Use the Metal framework for SceneKit rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metal"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderingAPI/metal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNRenderingAPIMetal"
        }
      ],
      "role": "symbol",
      "title": "SCNRenderingAPI.metal",
      "type": "topic",
      "url": "/documentation/scenekit/scnrenderingapi/metal"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderingAPI/openGLCore32": {
      "abstract": [
        {
          "text": "Use the OpenGL 3.2 Core Profile API for SceneKit rendering in macOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openGLCore32"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderingAPI/openGLCore32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNRenderingAPIOpenGLCore32"
        }
      ],
      "role": "symbol",
      "title": "SCNRenderingAPI.openGLCore32",
      "type": "topic",
      "url": "/documentation/scenekit/scnrenderingapi/openglcore32"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderingAPI/openGLCore41": {
      "abstract": [
        {
          "text": "Use the OpenGL 4.1 Core Profile API for SceneKit rendering in macOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openGLCore41"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderingAPI/openGLCore41",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNRenderingAPIOpenGLCore41"
        }
      ],
      "role": "symbol",
      "title": "SCNRenderingAPI.openGLCore41",
      "type": "topic",
      "url": "/documentation/scenekit/scnrenderingapi/openglcore41"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderingAPI/openGLES2": {
      "abstract": [
        {
          "text": "Use the OpenGL ES 2.0 API for SceneKit rendering in iOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openGLES2"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderingAPI/openGLES2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNRenderingAPIOpenGLES2"
        }
      ],
      "role": "symbol",
      "title": "SCNRenderingAPI.openGLES2",
      "type": "topic",
      "url": "/documentation/scenekit/scnrenderingapi/opengles2"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderingAPI/openGLLegacy": {
      "abstract": [
        {
          "text": "Use the Legacy OpenGL API for SceneKit rendering in macOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openGLLegacy"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderingAPI/openGLLegacy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNRenderingAPIOpenGLLegacy"
        }
      ],
      "role": "symbol",
      "title": "SCNRenderingAPI.openGLLegacy",
      "type": "topic",
      "url": "/documentation/scenekit/scnrenderingapi/opengllegacy"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/renderingAPI": {
      "abstract": [
        {
          "text": "The graphics technology SceneKit uses to render the scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "renderingAPI"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNRenderingAPI",
          "text": "SCNRenderingAPI"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/renderingAPI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "renderingAPI"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "renderingAPI",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenerenderer/renderingapi"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNView": {
      "abstract": [
        {
          "text": "A view for displaying 3D SceneKit content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNView"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNView"
        }
      ],
      "role": "symbol",
      "title": "SCNView",
      "type": "topic",
      "url": "/documentation/scenekit/scnview"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNView/Option/preferredRenderingAPI": {
      "abstract": [
        {
          "text": "The rendering API to use for rendering the view (for example, Metal or OpenGL).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredRenderingAPI"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNView",
          "text": "SCNView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNViewOption",
          "text": "Option"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNView/Option/preferredRenderingAPI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNPreferredRenderingAPIKey"
        }
      ],
      "role": "symbol",
      "title": "preferredRenderingAPI",
      "type": "topic",
      "url": "/documentation/scenekit/scnview/option/preferredrenderingapi"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderingAPI/metal",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderingAPI/openGLES2",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderingAPI/openGLCore32",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderingAPI/openGLCore41"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SCNRenderingAPIOpenGLLegacy"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNRenderingAPIOpenGLLegacy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.scenekit/documentation/SceneKit",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderingAPI"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderingAPI/metal",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderingAPI/openGLES2",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderingAPI/openGLCore32",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderingAPI/openGLCore41"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SCNRenderingAPIOpenGLLegacy"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView~1Option~1preferredRenderingAPI/title",
          "value": "SCNPreferredRenderingAPIKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView~1Option~1preferredRenderingAPI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPreferredRenderingAPIKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView/title",
          "value": "SCNView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNRenderingAPI~1openGLLegacy/title",
          "value": "SCNRenderingAPIOpenGLLegacy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNRenderingAPI~1openGLLegacy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNRenderingAPIOpenGLLegacy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNRenderingAPI~1openGLCore41/title",
          "value": "SCNRenderingAPIOpenGLCore41"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNRenderingAPI~1openGLCore41/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNRenderingAPIOpenGLCore41"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNRenderingAPI~1openGLCore32/title",
          "value": "SCNRenderingAPIOpenGLCore32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNRenderingAPI~1openGLCore32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNRenderingAPIOpenGLCore32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNRenderingAPI~1openGLES2/title",
          "value": "SCNRenderingAPIOpenGLES2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNRenderingAPI~1openGLES2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNRenderingAPIOpenGLES2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1renderingAPI/title",
          "value": "renderingAPI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1renderingAPI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "renderingAPI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNRenderingAPI/title",
          "value": "SCNRenderingAPI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNRenderingAPI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNRenderingAPI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNRenderingAPI/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNRenderingAPI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNRenderingAPI~1metal/title",
          "value": "SCNRenderingAPIMetal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNRenderingAPI~1metal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNRenderingAPIMetal"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/scnrenderingapi/opengllegacy"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/scnrenderingapi/opengllegacy"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
