{
  "abstract": [
    {
      "text": "The currency code string for this disbursement.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/currencyCode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PKDisbursementRequest(py)currencyCode",
    "fragments": [
      {
        "kind": "identifier",
        "text": "currencyCode"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "currencyCode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "currencyCode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "currencyCode"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Apple Pay interprets the amounts that this request’s summary items provide as amounts in this currency. For more information on currency codes, see ",
              "type": "text"
            },
            {
              "identifier": "https://www.iso.org/iso-4217-currency-codes.html",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest": {
      "abstract": [
        {
          "text": "An object that represents a request to disburse funds from a merchant to an individual.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKDisbursementRequest"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKDisbursementRequest"
        }
      ],
      "role": "symbol",
      "title": "PKDisbursementRequest",
      "type": "topic",
      "url": "/documentation/passkit/pkdisbursementrequest"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/currencyCode": {
      "abstract": [
        {
          "text": "The currency code string for this disbursement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "currencyCode"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/currencyCode",
      "kind": "symbol",
      "role": "symbol",
      "title": "currencyCode",
      "type": "topic",
      "url": "/documentation/passkit/pkdisbursementrequest/currencycode"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/regionCode": {
      "abstract": [
        {
          "text": "The merchant’s country code string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "regionCode"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/regionCode",
      "kind": "symbol",
      "role": "symbol",
      "title": "regionCode",
      "type": "topic",
      "url": "/documentation/passkit/pkdisbursementrequest/regioncode"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/supportedRegions-j9ug": {
      "abstract": [
        {
          "text": "An array of two-letter region codes that describes the regions to support.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "supportedRegions"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/supportedRegions-j9ug",
      "kind": "symbol",
      "role": "symbol",
      "title": "supportedRegions",
      "type": "topic",
      "url": "/documentation/passkit/pkdisbursementrequest/supportedregions-j9ug"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "https://www.iso.org/iso-4217-currency-codes.html": {
      "identifier": "https://www.iso.org/iso-4217-currency-codes.html",
      "title": "ISO 4127 Currency Codes",
      "titleInlineContent": [
        {
          "text": "ISO 4127 Currency Codes",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://www.iso.org/iso-4217-currency-codes.html"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Setting-currency-and-region-information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/regionCode",
        "doc://com.apple.passkit/documentation/PassKit/PKDisbursementRequest/supportedRegions-j9ug"
      ],
      "title": "Setting currency and region information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementRequest/title",
          "value": "PKDisbursementRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKDisbursementRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKDisbursementRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKDisbursementRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkdisbursementrequest/currencycode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
