{
  "abstract": [
    {
      "text": "Initialize a sports mode for display on the CarPlay now playing screen.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay",
        "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingModeSports"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingModeSports/init(leftTeam:rightTeam:eventStatus:backgroundArtwork:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CPNowPlayingModeSports(im)initWithLeftTeam:rightTeam:eventStatus:backgroundArtwork:",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "leftTeam"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CPNowPlayingSportsTeam",
        "text": "CPNowPlayingSportsTeam"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "rightTeam"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CPNowPlayingSportsTeam",
        "text": "CPNowPlayingSportsTeam"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "eventStatus"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CPNowPlayingSportsEventStatus",
        "text": "CPNowPlayingSportsEventStatus"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "backgroundArtwork"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIImage",
        "text": "UIImage"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithLeftTeam:rightTeam:eventStatus:backgroundArtwork:"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(leftTeam:rightTeam:eventStatus:backgroundArtwork:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "leftTeam"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingSportsTeam",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CPNowPlayingSportsTeam",
              "text": "CPNowPlayingSportsTeam"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "rightTeam"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingSportsTeam",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CPNowPlayingSportsTeam",
              "text": "CPNowPlayingSportsTeam"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "eventStatus"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingSportsEventStatus",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CPNowPlayingSportsEventStatus",
              "text": "CPNowPlayingSportsEventStatus"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "backgroundArtwork"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UIImage",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIImage",
              "text": "UIImage"
            },
            {
              "kind": "text",
              "text": "?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The sports team that should appear on the left side of the",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "now playing screen. This is commonly (but not always) the AWAY or VISITING team.",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "This team will be on the left in all layouts; it does not flip to the right",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "side when in a right-to-left language or a right-hand-drive vehicle.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "leftTeam"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The sports team that should appear on the right side of the",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "now playing screen. This is commonly (but not always) the HOME team.",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "This team will be on the right in all layouts; it does not flip to the left",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "side when in a right-to-left language or a right-hand-drive vehicle.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "rightTeam"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A representation of the current event status. See",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "eventStatus"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A large colorful image for the background of the",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "now playing screen. A gradient or crossfade image works best, especially",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "when it includes the primary colors of each team. Provide an image no larger",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "than 500x500.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "backgroundArtwork"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingModeSports": {
      "abstract": [
        {
          "text": "The sports mode represents a layout for now playing suited to live-streaming or",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "recorded playback of a sporting event that features exactly two teams.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPNowPlayingModeSports"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingModeSports",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPNowPlayingModeSports"
        }
      ],
      "role": "symbol",
      "title": "CPNowPlayingModeSports",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingmodesports"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingModeSports/init(leftTeam:rightTeam:eventStatus:backgroundArtwork:)": {
      "abstract": [
        {
          "text": "Initialize a sports mode for display on the CarPlay now playing screen.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "leftTeam"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPNowPlayingSportsTeam",
          "text": "CPNowPlayingSportsTeam"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rightTeam"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPNowPlayingSportsTeam",
          "text": "CPNowPlayingSportsTeam"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "eventStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPNowPlayingSportsEventStatus",
          "text": "CPNowPlayingSportsEventStatus"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "backgroundArtwork"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingModeSports/init(leftTeam:rightTeam:eventStatus:backgroundArtwork:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithLeftTeam:rightTeam:eventStatus:backgroundArtwork:"
        }
      ],
      "role": "symbol",
      "title": "init(leftTeam:rightTeam:eventStatus:backgroundArtwork:)",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingmodesports/init(leftteam:rightteam:eventstatus:backgroundartwork:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingSportsEventStatus": {
      "abstract": [
        {
          "text": "A representation of the status of a sporting event.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPNowPlayingSportsEventStatus"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingSportsEventStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPNowPlayingSportsEventStatus"
        }
      ],
      "role": "symbol",
      "title": "CPNowPlayingSportsEventStatus",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingsportseventstatus"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingSportsTeam": {
      "abstract": [
        {
          "text": "A representation of a sports team for the now playing screen,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "in sports that have exactly two teams.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPNowPlayingSportsTeam"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingSportsTeam",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPNowPlayingSportsTeam"
        }
      ],
      "role": "symbol",
      "title": "CPNowPlayingSportsTeam",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingsportsteam"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)UIImage": {
      "abstract": [
        {
          "text": "An object that manages image data in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIImage"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UIImage",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIImage",
      "type": "topic",
      "url": "/documentation/UIKit/UIImage"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithLeftTeam:rightTeam:eventStatus:backgroundArtwork:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithLeftTeam:rightTeam:eventStatus:backgroundArtwork:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.carplay/documentation/CarPlay",
                "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingModeSports"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithLeftTeam:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingSportsTeam",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CPNowPlayingSportsTeam",
                    "text": "CPNowPlayingSportsTeam"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "leftTeam"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "rightTeam:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingSportsTeam",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CPNowPlayingSportsTeam",
                    "text": "CPNowPlayingSportsTeam"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "rightTeam"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "eventStatus:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingSportsEventStatus",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CPNowPlayingSportsEventStatus",
                    "text": "CPNowPlayingSportsEventStatus"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "eventStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "backgroundArtwork:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UIImage",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIImage",
                    "text": "UIImage"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "backgroundArtwork"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The sports team that should appear on the left side of the",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "now playing screen. This is commonly (but not always) the AWAY or VISITING team.",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "This team will be on the left in all layouts; it does not flip to the right",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "side when in a right-to-left language or a right-hand-drive vehicle.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "leftTeam"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The sports team that should appear on the right side of the",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "now playing screen. This is commonly (but not always) the HOME team.",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "This team will be on the right in all layouts; it does not flip to the left",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "side when in a right-to-left language or a right-hand-drive vehicle.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "rightTeam"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A representation of the current event status. See",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "eventStatus"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A large colorful image for the background of the",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "now playing screen. A gradient or crossfade image works best, especially",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "when it includes the primary colors of each team. Provide an image no larger",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "than 500x500.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "backgroundArtwork"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)UIImage/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIImage"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingModeSports/title",
          "value": "CPNowPlayingModeSports"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingModeSports/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingModeSports"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingModeSports/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingModeSports"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingSportsTeam/title",
          "value": "CPNowPlayingSportsTeam"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingSportsTeam/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingSportsTeam"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingSportsTeam/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingSportsTeam"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingModeSports~1init(leftTeam:rightTeam:eventStatus:backgroundArtwork:)/title",
          "value": "initWithLeftTeam:rightTeam:eventStatus:backgroundArtwork:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingModeSports~1init(leftTeam:rightTeam:eventStatus:backgroundArtwork:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithLeftTeam:rightTeam:eventStatus:backgroundArtwork:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingSportsEventStatus/title",
          "value": "CPNowPlayingSportsEventStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingSportsEventStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingSportsEventStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingSportsEventStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingSportsEventStatus"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cpnowplayingmodesports/init(leftteam:rightteam:eventstatus:backgroundartwork:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/cpnowplayingmodesports/init(leftteam:rightteam:eventstatus:backgroundartwork:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
