{
  "abstract": [
    {
      "text": "A key that identifies the beginning of a parameter curve definition.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corehaptics/documentation/CoreHaptics",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/parameterCurve"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CoreHaptics",
    "externalID": "c:@CHHapticPatternKeyParameterCurve",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "parameterCurve"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CHHapticPattern",
        "text": "CHHapticPattern"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CHHapticPatternKey",
        "text": "Key"
      }
    ],
    "modules": [
      {
        "name": "Core Haptics"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CHHapticPatternKeyParameterCurve"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "parameterCurve"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "parameterCurve"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CHHapticPattern",
              "text": "CHHapticPattern"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CHHapticPatternKey",
              "text": "Key"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corehaptics/documentation/CoreHaptics": {
      "abstract": [
        {
          "text": "Compose and play haptic patterns to customize your iOS app’s haptic feedback.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Haptics",
      "type": "topic",
      "url": "/documentation/corehaptics"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern": {
      "abstract": [
        {
          "text": "An object representing a haptic waveform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CHHapticPattern"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticPattern"
        }
      ],
      "role": "symbol",
      "title": "CHHapticPattern",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticpattern"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key": {
      "abstract": [
        {
          "text": "Constants that define the keys you use to create a haptic pattern dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Key"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Key"
        }
      ],
      "role": "symbol",
      "title": "CHHapticPattern.Key",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticpattern/key"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/event": {
      "abstract": [
        {
          "text": "A key that identifies the beginning of a haptic event definition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "event"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticPattern",
          "text": "CHHapticPattern"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CHHapticPatternKey",
          "text": "Key"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/event",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticPatternKeyEvent"
        }
      ],
      "role": "symbol",
      "title": "event",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticpattern/key/event"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/eventDuration": {
      "abstract": [
        {
          "text": "A key that identifies the duration of an event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eventDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticPattern",
          "text": "CHHapticPattern"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CHHapticPatternKey",
          "text": "Key"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/eventDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticPatternKeyEventDuration"
        }
      ],
      "role": "symbol",
      "title": "eventDuration",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticpattern/key/eventduration"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/eventParameters": {
      "abstract": [
        {
          "text": "A key that identifies the beginning of an array of fixed parameter definitions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eventParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticPattern",
          "text": "CHHapticPattern"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CHHapticPatternKey",
          "text": "Key"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/eventParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticPatternKeyEventParameters"
        }
      ],
      "role": "symbol",
      "title": "eventParameters",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticpattern/key/eventparameters"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/eventType": {
      "abstract": [
        {
          "text": "A key that identifies the type of event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eventType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticPattern",
          "text": "CHHapticPattern"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CHHapticPatternKey",
          "text": "Key"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/eventType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticPatternKeyEventType"
        }
      ],
      "role": "symbol",
      "title": "eventType",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticpattern/key/eventtype"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/eventWaveformLoopEnabled": {
      "abstract": [
        {
          "text": "A key for a Boolean value that indicates whether to loop custom audio events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eventWaveformLoopEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticPattern",
          "text": "CHHapticPattern"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CHHapticPatternKey",
          "text": "Key"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/eventWaveformLoopEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticPatternKeyEventWaveformLoopEnabled"
        }
      ],
      "role": "symbol",
      "title": "eventWaveformLoopEnabled",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticpattern/key/eventwaveformloopenabled"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/eventWaveformPath": {
      "abstract": [
        {
          "text": "A key that identifies the path to the local file that contains the audio waveform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eventWaveformPath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticPattern",
          "text": "CHHapticPattern"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CHHapticPatternKey",
          "text": "Key"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/eventWaveformPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticPatternKeyEventWaveformPath"
        }
      ],
      "role": "symbol",
      "title": "eventWaveformPath",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticpattern/key/eventwaveformpath"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/eventWaveformUseVolumeEnvelope": {
      "abstract": [
        {
          "text": "A key that identifies whether audio file playback fades in and out using an envelope.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eventWaveformUseVolumeEnvelope"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticPattern",
          "text": "CHHapticPattern"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CHHapticPatternKey",
          "text": "Key"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/eventWaveformUseVolumeEnvelope",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticPatternKeyEventWaveformUseVolumeEnvelope"
        }
      ],
      "role": "symbol",
      "title": "eventWaveformUseVolumeEnvelope",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticpattern/key/eventwaveformusevolumeenvelope"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/parameter": {
      "abstract": [
        {
          "text": "A key that identifies the beginning of a parameter definition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticPattern",
          "text": "CHHapticPattern"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CHHapticPatternKey",
          "text": "Key"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/parameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticPatternKeyParameter"
        }
      ],
      "role": "symbol",
      "title": "parameter",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticpattern/key/parameter"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/parameterCurve": {
      "abstract": [
        {
          "text": "A key that identifies the beginning of a parameter curve definition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parameterCurve"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticPattern",
          "text": "CHHapticPattern"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CHHapticPatternKey",
          "text": "Key"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/parameterCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticPatternKeyParameterCurve"
        }
      ],
      "role": "symbol",
      "title": "parameterCurve",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticpattern/key/parametercurve"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/parameterCurveControlPoints": {
      "abstract": [
        {
          "text": "A key that identifies the control points of a parameter curve.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parameterCurveControlPoints"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticPattern",
          "text": "CHHapticPattern"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CHHapticPatternKey",
          "text": "Key"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/parameterCurveControlPoints",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticPatternKeyParameterCurveControlPoints"
        }
      ],
      "role": "symbol",
      "title": "parameterCurveControlPoints",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticpattern/key/parametercurvecontrolpoints"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/parameterID": {
      "abstract": [
        {
          "text": "A key that identifies the parameter ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parameterID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticPattern",
          "text": "CHHapticPattern"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CHHapticPatternKey",
          "text": "Key"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/parameterID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticPatternKeyParameterID"
        }
      ],
      "role": "symbol",
      "title": "parameterID",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticpattern/key/parameterid"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/parameterValue": {
      "abstract": [
        {
          "text": "A key that identifies the value of a parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parameterValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticPattern",
          "text": "CHHapticPattern"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CHHapticPatternKey",
          "text": "Key"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/parameterValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticPatternKeyParameterValue"
        }
      ],
      "role": "symbol",
      "title": "parameterValue",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticpattern/key/parametervalue"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/pattern": {
      "abstract": [
        {
          "text": "A key that identifies the beginning of a haptic pattern definition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pattern"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticPattern",
          "text": "CHHapticPattern"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CHHapticPatternKey",
          "text": "Key"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/pattern",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticPatternKeyPattern"
        }
      ],
      "role": "symbol",
      "title": "pattern",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticpattern/key/pattern"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/time": {
      "abstract": [
        {
          "text": "A key that identifies the relative time for an event or parameter, in seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "time"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticPattern",
          "text": "CHHapticPattern"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CHHapticPatternKey",
          "text": "Key"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/time",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticPatternKeyTime"
        }
      ],
      "role": "symbol",
      "title": "time",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticpattern/key/time"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/version": {
      "abstract": [
        {
          "text": "A key that identifies rhe version number of a haptic pattern dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticPattern",
          "text": "CHHapticPattern"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CHHapticPatternKey",
          "text": "Key"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/version",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticPatternKeyVersion"
        }
      ],
      "role": "symbol",
      "title": "version",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticpattern/key/version"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Haptic-Pattern-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/event",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/eventDuration",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/eventParameters",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/eventType",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/eventWaveformLoopEnabled",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/eventWaveformPath",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/eventWaveformUseVolumeEnvelope",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/parameter",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/parameterCurveControlPoints",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/parameterID",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/parameterValue",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/pattern",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/time",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/version"
      ],
      "title": "Haptic Pattern Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CHHapticPatternKeyParameterCurve"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticPatternKeyParameterCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corehaptics/documentation/CoreHaptics"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Haptic-Pattern-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/event",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/eventDuration",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/eventParameters",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/eventType",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/eventWaveformLoopEnabled",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/eventWaveformPath",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/eventWaveformUseVolumeEnvelope",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/parameter",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/parameterCurveControlPoints",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/parameterID",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/parameterValue",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/pattern",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/time",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key/version"
              ],
              "title": "Haptic Pattern Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern/Key",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CHHapticPatternKey",
                    "text": "CHHapticPatternKey"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CHHapticPatternKeyParameterCurve"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key~1parameterValue/title",
          "value": "CHHapticPatternKeyParameterValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key~1parameterValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticPatternKeyParameterValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key~1parameterID/title",
          "value": "CHHapticPatternKeyParameterID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key~1parameterID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticPatternKeyParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key~1eventWaveformPath/title",
          "value": "CHHapticPatternKeyEventWaveformPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key~1eventWaveformPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticPatternKeyEventWaveformPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key~1event/title",
          "value": "CHHapticPatternKeyEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key~1event/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticPatternKeyEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key~1parameterCurveControlPoints/title",
          "value": "CHHapticPatternKeyParameterCurveControlPoints"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key~1parameterCurveControlPoints/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticPatternKeyParameterCurveControlPoints"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key~1eventWaveformLoopEnabled/title",
          "value": "CHHapticPatternKeyEventWaveformLoopEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key~1eventWaveformLoopEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticPatternKeyEventWaveformLoopEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key~1eventParameters/title",
          "value": "CHHapticPatternKeyEventParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key~1eventParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticPatternKeyEventParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key~1version/title",
          "value": "CHHapticPatternKeyVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key~1version/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticPatternKeyVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key~1eventType/title",
          "value": "CHHapticPatternKeyEventType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key~1eventType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticPatternKeyEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key~1parameter/title",
          "value": "CHHapticPatternKeyParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key~1parameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticPatternKeyParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key~1eventDuration/title",
          "value": "CHHapticPatternKeyEventDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key~1eventDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticPatternKeyEventDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key~1eventWaveformUseVolumeEnvelope/title",
          "value": "CHHapticPatternKeyEventWaveformUseVolumeEnvelope"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key~1eventWaveformUseVolumeEnvelope/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticPatternKeyEventWaveformUseVolumeEnvelope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key~1parameterCurve/title",
          "value": "CHHapticPatternKeyParameterCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key~1parameterCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticPatternKeyParameterCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key~1pattern/title",
          "value": "CHHapticPatternKeyPattern"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key~1pattern/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticPatternKeyPattern"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key/title",
          "value": "CHHapticPatternKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticPatternKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticPatternKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern/title",
          "value": "CHHapticPattern"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticPattern"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticPattern"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key~1time/title",
          "value": "CHHapticPatternKeyTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern~1Key~1time/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticPatternKeyTime"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corehaptics/chhapticpattern/key/parametercurve"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corehaptics/chhapticpattern/key/parametercurve"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
