{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox",
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTap"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTap/Equatable-Implementations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Media Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Equatable Implementations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox": {
      "abstract": [
        {
          "text": "Enable support for media format readers; tap and process audio from an audio mix.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Toolbox",
      "type": "topic",
      "url": "/documentation/mediatoolbox"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTap": {
      "abstract": [
        {
          "text": "An audio processing tap object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTAudioProcessingTap"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTAudioProcessingTap"
        }
      ],
      "role": "symbol",
      "title": "MTAudioProcessingTap",
      "type": "topic",
      "url": "/documentation/mediatoolbox/mtaudioprocessingtap"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTap/!=(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether two values are not equal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "!="
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTap/!=(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "!=(_:_:)",
      "type": "topic",
      "url": "/documentation/mediatoolbox/mtaudioprocessingtap/!=(_:_:)"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTap/==(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether two values are equal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "=="
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTap/==(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "==(_:_:)",
      "type": "topic",
      "url": "/documentation/mediatoolbox/mtaudioprocessingtap/==(_:_:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Operators",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTap/!=(_:_:)",
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTap/==(_:_:)"
      ],
      "title": "Operators"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTap/title",
          "value": "MTAudioProcessingTapRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTAudioProcessingTapRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTAudioProcessingTapRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediatoolbox/mtaudioprocessingtap/equatable-implementations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
