{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox",
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTap"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTap/Hashable-Implementations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Media Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Hashable Implementations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox": {
      "abstract": [
        {
          "text": "Enable support for media format readers; tap and process audio from an audio mix.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Toolbox",
      "type": "topic",
      "url": "/documentation/mediatoolbox"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTap": {
      "abstract": [
        {
          "text": "An audio processing tap object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTAudioProcessingTap"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTAudioProcessingTap"
        }
      ],
      "role": "symbol",
      "title": "MTAudioProcessingTap",
      "type": "topic",
      "url": "/documentation/mediatoolbox/mtaudioprocessingtap"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTap/hash(into:)": {
      "abstract": [
        {
          "text": "Hashes the essential components of this value by feeding them into the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "given hasher.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hash"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "into"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6HasherV",
          "text": "Hasher"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTap/hash(into:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "hash(into:)",
      "type": "topic",
      "url": "/documentation/mediatoolbox/mtaudioprocessingtap/hash(into:)"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTap/hashValue": {
      "abstract": [
        {
          "text": "The hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hashValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTap/hashValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "hashValue",
      "type": "topic",
      "url": "/documentation/mediatoolbox/mtaudioprocessingtap/hashvalue"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTap/hashValue"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTap/hash(into:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTap/title",
          "value": "MTAudioProcessingTapRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTAudioProcessingTapRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTAudioProcessingTapRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediatoolbox/mtaudioprocessingtap/hashable-implementations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
