{
  "abstract": [
    {
      "text": "Creates an audio channel layout object from an existing one.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioChannelLayout"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioChannelLayout/layoutWithLayout:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVAudioChannelLayout(cm)layoutWithLayout:",
    "fragments": [
      {
        "kind": "text",
        "text": "+ "
      },
      {
        "kind": "identifier",
        "text": "layoutWithLayout:"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "layoutWithLayout:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "layoutWithLayout:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "layoutWithLayout:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@AudioChannelLayout",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@AudioChannelLayout",
              "text": "AudioChannelLayout"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "layout"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The existing audio channel layout object.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "layout"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A new ",
              "type": "text"
            },
            {
              "code": "AVAudioChannelLayout",
              "type": "codeVoice"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the layout’s tag is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreAudioTypes/kAudioChannelLayoutTag_UseChannelDescriptions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", the method attempts to convert it to a more specific tag.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioChannelLayout": {
      "abstract": [
        {
          "text": "An object that describes the roles of a set of audio channels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioChannelLayout"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioChannelLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioChannelLayout"
        }
      ],
      "role": "symbol",
      "title": "AVAudioChannelLayout",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiochannellayout"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioChannelLayout/init(layout:)": {
      "abstract": [
        {
          "text": "Creates an audio channel layout object from an existing one.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "layout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioChannelLayout",
          "text": "AudioChannelLayout"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioChannelLayout/init(layout:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithLayout:"
        }
      ],
      "role": "symbol",
      "title": "init(layout:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiochannellayout/init(layout:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioChannelLayout/init(layoutTag:)": {
      "abstract": [
        {
          "text": "Creates an audio channel layout object from a layout tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "layoutTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioChannelLayout/init(layoutTag:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithLayoutTag:"
        }
      ],
      "role": "symbol",
      "title": "init(layoutTag:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiochannellayout/init(layouttag:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioChannelLayout/layoutWithLayout:": {
      "abstract": [
        {
          "text": "Creates an audio channel layout object from an existing one.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "layoutWithLayout:"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioChannelLayout/layoutWithLayout:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layoutWithLayout:"
        }
      ],
      "role": "symbol",
      "title": "layoutWithLayout:",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiochannellayout/layoutwithlayout:"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioChannelLayout/layoutWithLayoutTag:": {
      "abstract": [
        {
          "text": "Creates an audio channel layout object from an audio channel layout tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "layoutWithLayoutTag:"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioChannelLayout/layoutWithLayoutTag:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layoutWithLayoutTag:"
        }
      ],
      "role": "symbol",
      "title": "layoutWithLayoutTag:",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiochannellayout/layoutwithlayouttag:"
    },
    "doc://com.apple.documentation/documentation/CoreAudioTypes/kAudioChannelLayoutTag_UseChannelDescriptions": {
      "abstract": [
        {
          "text": "An array of audio channel description structures that defines the layout mapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_UseChannelDescriptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreAudioTypes/kAudioChannelLayoutTag_UseChannelDescriptions",
      "kind": "symbol",
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_UseChannelDescriptions",
      "type": "topic",
      "url": "/documentation/CoreAudioTypes/kAudioChannelLayoutTag_UseChannelDescriptions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@S@AudioChannelLayout": {
      "abstract": [
        {
          "text": "A structure that specifies a channel layout in a file or in hardware.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioChannelLayout"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@AudioChannelLayout",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioChannelLayout",
      "type": "topic",
      "url": "/documentation/CoreAudioTypes/AudioChannelLayout"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-an-Audio-Channel-Layout",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioChannelLayout/init(layout:)",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioChannelLayout/init(layoutTag:)",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioChannelLayout/layoutWithLayoutTag:"
      ],
      "title": "Creating an Audio Channel Layout"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioChannelLayout~1init(layoutTag:)/title",
          "value": "initWithLayoutTag:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioChannelLayout~1init(layoutTag:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithLayoutTag:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@S@AudioChannelLayout/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioChannelLayout"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioChannelLayout~1init(layout:)/title",
          "value": "initWithLayout:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioChannelLayout~1init(layout:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithLayout:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioChannelLayout/title",
          "value": "AVAudioChannelLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioChannelLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioChannelLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioChannelLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioChannelLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_UseChannelDescriptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_UseChannelDescriptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudiochannellayout/layoutwithlayout:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
