{
  "abstract": [
    {
      "text": "A recording input device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputDeviceType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputDeviceType/recording"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HMCharacteristicValueInputDeviceType@HMCharacteristicValueInputDeviceTypeRecording",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "recording"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HMCharacteristicValueInputDeviceTypeRecording"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HMCharacteristicValueInputDeviceType.recording"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "recording"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputDeviceType": {
      "abstract": [
        {
          "text": "Categories of input devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueInputDeviceType"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputDeviceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueInputDeviceType"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueInputDeviceType",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueinputdevicetype"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputDeviceType/audioSystem": {
      "abstract": [
        {
          "text": "An audio system input device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioSystem"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputDeviceType/audioSystem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueInputDeviceTypeAudioSystem"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueInputDeviceType.audioSystem",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueinputdevicetype/audiosystem"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputDeviceType/none": {
      "abstract": [
        {
          "text": "No input device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputDeviceType/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueInputDeviceTypeNone"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueInputDeviceType.none",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueinputdevicetype/none"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputDeviceType/other": {
      "abstract": [
        {
          "text": "An input device that doesn’t fit classifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "other"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputDeviceType/other",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueInputDeviceTypeOther"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueInputDeviceType.other",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueinputdevicetype/other"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputDeviceType/playback": {
      "abstract": [
        {
          "text": "A playback control input device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playback"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputDeviceType/playback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueInputDeviceTypePlayback"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueInputDeviceType.playback",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueinputdevicetype/playback"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputDeviceType/recording": {
      "abstract": [
        {
          "text": "A recording input device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recording"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputDeviceType/recording",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueInputDeviceTypeRecording"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueInputDeviceType.recording",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueinputdevicetype/recording"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputDeviceType/tuner": {
      "abstract": [
        {
          "text": "A tuner input device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tuner"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputDeviceType/tuner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueInputDeviceTypeTuner"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueInputDeviceType.tuner",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueinputdevicetype/tuner"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputDeviceType/tv": {
      "abstract": [
        {
          "text": "A television input device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tv"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputDeviceType/tv",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueInputDeviceTypeTV"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueInputDeviceType.tv",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueinputdevicetype/tv"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Input-devices",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputDeviceType/audioSystem",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputDeviceType/none",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputDeviceType/other",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputDeviceType/playback",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputDeviceType/tuner",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputDeviceType/tv"
      ],
      "title": "Input devices"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HMCharacteristicValueInputDeviceTypeRecording"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueInputDeviceTypeRecording"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.homekit/documentation/HomeKit",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputDeviceType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Input-devices",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputDeviceType/audioSystem",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputDeviceType/none",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputDeviceType/other",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputDeviceType/playback",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputDeviceType/tuner",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputDeviceType/tv"
              ],
              "title": "Input devices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HMCharacteristicValueInputDeviceTypeRecording"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputDeviceType~1audioSystem/title",
          "value": "HMCharacteristicValueInputDeviceTypeAudioSystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputDeviceType~1audioSystem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueInputDeviceTypeAudioSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputDeviceType~1playback/title",
          "value": "HMCharacteristicValueInputDeviceTypePlayback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputDeviceType~1playback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueInputDeviceTypePlayback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputDeviceType~1recording/title",
          "value": "HMCharacteristicValueInputDeviceTypeRecording"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputDeviceType~1recording/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueInputDeviceTypeRecording"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputDeviceType/title",
          "value": "HMCharacteristicValueInputDeviceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputDeviceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueInputDeviceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputDeviceType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueInputDeviceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputDeviceType~1other/title",
          "value": "HMCharacteristicValueInputDeviceTypeOther"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputDeviceType~1other/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueInputDeviceTypeOther"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputDeviceType~1tuner/title",
          "value": "HMCharacteristicValueInputDeviceTypeTuner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputDeviceType~1tuner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueInputDeviceTypeTuner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputDeviceType~1tv/title",
          "value": "HMCharacteristicValueInputDeviceTypeTV"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputDeviceType~1tv/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueInputDeviceTypeTV"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputDeviceType~1none/title",
          "value": "HMCharacteristicValueInputDeviceTypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputDeviceType~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueInputDeviceTypeNone"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmcharacteristicvalueinputdevicetype/recording"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/hmcharacteristicvalueinputdevicetype/recording"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
