{
  "abstract": [
    {
      "text": "The token that identifies the starting point for retrieving changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation/ZoneOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation/ZoneOptions/previousServerChangeToken"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CKFetchRecordZoneChangesOptions(py)previousServerChangeToken",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "previousServerChangeToken"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CKServerChangeToken",
        "text": "CKServerChangeToken"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "previousServerChangeToken"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "10.0",
        "name": "iOS",
        "renamed": "CKFetchRecordZoneChangesOperation.ZoneConfiguration",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "10.0",
        "name": "iPadOS",
        "renamed": "CKFetchRecordZoneChangesOperation.ZoneConfiguration",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "renamed": "CKFetchRecordZoneChangesOperation.ZoneConfiguration",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.12",
        "name": "macOS",
        "renamed": "CKFetchRecordZoneChangesOperation.ZoneConfiguration",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "10.0",
        "name": "tvOS",
        "renamed": "CKFetchRecordZoneChangesOperation.ZoneConfiguration",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "renamed": "CKFetchRecordZoneChangesOperation.ZoneConfiguration",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "5.0",
        "introducedAt": "3.0",
        "name": "watchOS",
        "renamed": "CKFetchRecordZoneChangesOperation.ZoneConfiguration",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "previousServerChangeToken"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@NSCopying"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "previousServerChangeToken"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKServerChangeToken",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CKServerChangeToken",
              "text": "CKServerChangeToken"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Each fetch request returns a unique token in addition to any changes. CloudKit passes the token to your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordChangesOperation/fetchRecordChangesCompletionBlock",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " handler. During a subsequent fetch request, providing the previous token causes the server to return only the changes since the previous fetch request. Tokens are opaque values that you can write to disk safely and reuse later.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordChangesOperation/fetchRecordChangesCompletionBlock": {
      "abstract": [
        {
          "text": "The block to execute when the system finishes processing all changes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchRecordChangesCompletionBlock"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKServerChangeToken",
          "text": "CKServerChangeToken"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordChangesOperation/fetchRecordChangesCompletionBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fetchRecordChangesCompletionBlock"
        }
      ],
      "role": "symbol",
      "title": "fetchRecordChangesCompletionBlock",
      "type": "topic",
      "url": "/documentation/cloudkit/ckfetchrecordchangesoperation/fetchrecordchangescompletionblock"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation": {
      "abstract": [
        {
          "text": "An operation that fetches record zone changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKFetchRecordZoneChangesOperation"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKFetchRecordZoneChangesOperation"
        }
      ],
      "role": "symbol",
      "title": "CKFetchRecordZoneChangesOperation",
      "type": "topic",
      "url": "/documentation/cloudkit/ckfetchrecordzonechangesoperation"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation/ZoneOptions": {
      "abstract": [
        {
          "text": "A configuration object that describes the information to fetch from a record zone.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ZoneOptions"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation/ZoneOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ZoneOptions"
        }
      ],
      "role": "symbol",
      "title": "CKFetchRecordZoneChangesOperation.ZoneOptions",
      "type": "topic",
      "url": "/documentation/cloudkit/ckfetchrecordzonechangesoperation/zoneoptions"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation/ZoneOptions/desiredKeys": {
      "abstract": [
        {
          "text": "The fields to fetch for the requested records.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "desiredKeys"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation/ZoneOptions/desiredKeys",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "desiredKeys"
        }
      ],
      "role": "symbol",
      "title": "desiredKeys",
      "type": "topic",
      "url": "/documentation/cloudkit/ckfetchrecordzonechangesoperation/zoneoptions/desiredkeys"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation/ZoneOptions/previousServerChangeToken": {
      "abstract": [
        {
          "text": "The token that identifies the starting point for retrieving changes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previousServerChangeToken"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKServerChangeToken",
          "text": "CKServerChangeToken"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation/ZoneOptions/previousServerChangeToken",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "previousServerChangeToken"
        }
      ],
      "role": "symbol",
      "title": "previousServerChangeToken",
      "type": "topic",
      "url": "/documentation/cloudkit/ckfetchrecordzonechangesoperation/zoneoptions/previousserverchangetoken"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation/ZoneOptions/resultsLimit": {
      "abstract": [
        {
          "text": "The maximum number of records to fetch from the record zone.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resultsLimit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation/ZoneOptions/resultsLimit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resultsLimit"
        }
      ],
      "role": "symbol",
      "title": "resultsLimit",
      "type": "topic",
      "url": "/documentation/cloudkit/ckfetchrecordzonechangesoperation/zoneoptions/resultslimit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKServerChangeToken": {
      "abstract": [
        {
          "text": "An opaque token that represents a specific point in a database’s history.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKServerChangeToken"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKServerChangeToken",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKServerChangeToken"
        }
      ],
      "role": "symbol",
      "title": "CKServerChangeToken",
      "type": "topic",
      "url": "/documentation/cloudkit/ckserverchangetoken"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Zone-Change-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation/ZoneOptions/desiredKeys",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation/ZoneOptions/resultsLimit"
      ],
      "title": "Zone Change Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "12.0",
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "12.0",
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.14",
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "12.0",
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "5.0",
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "previousServerChangeToken"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "previousServerChangeToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cloudkit/documentation/CloudKit",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation/ZoneOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Zone-Change-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation/ZoneOptions/desiredKeys",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation/ZoneOptions/resultsLimit"
              ],
              "title": "Zone Change Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKServerChangeToken",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CKServerChangeToken",
                    "text": "CKServerChangeToken"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "previousServerChangeToken"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchRecordChangesOperation~1fetchRecordChangesCompletionBlock/title",
          "value": "fetchRecordChangesCompletionBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchRecordChangesOperation~1fetchRecordChangesCompletionBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fetchRecordChangesCompletionBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchRecordZoneChangesOperation/title",
          "value": "CKFetchRecordZoneChangesOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchRecordZoneChangesOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKFetchRecordZoneChangesOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchRecordZoneChangesOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKFetchRecordZoneChangesOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchRecordZoneChangesOperation~1ZoneOptions~1desiredKeys/title",
          "value": "desiredKeys"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchRecordZoneChangesOperation~1ZoneOptions~1desiredKeys/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "desiredKeys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKServerChangeToken/title",
          "value": "CKServerChangeToken"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKServerChangeToken/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKServerChangeToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKServerChangeToken/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKServerChangeToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchRecordZoneChangesOperation~1ZoneOptions~1previousServerChangeToken/title",
          "value": "previousServerChangeToken"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchRecordZoneChangesOperation~1ZoneOptions~1previousServerChangeToken/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "previousServerChangeToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchRecordZoneChangesOperation~1ZoneOptions~1resultsLimit/title",
          "value": "resultsLimit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchRecordZoneChangesOperation~1ZoneOptions~1resultsLimit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "resultsLimit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchRecordZoneChangesOperation~1ZoneOptions/title",
          "value": "CKFetchRecordZoneChangesOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchRecordZoneChangesOperation~1ZoneOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKFetchRecordZoneChangesOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchRecordZoneChangesOperation~1ZoneOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKFetchRecordZoneChangesOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/ckfetchrecordzonechangesoperation/zoneoptions/previousserverchangetoken"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cloudkit/ckfetchrecordzonechangesoperation/zoneoptions/previousserverchangetoken"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
