{"sections":[],"seeAlsoSections":[{"anchor":"Tracking-the-drag-movements","title":"Tracking the drag movements","identifiers":["doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidEnter:)","doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidExit:)","doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidEnd:)"],"generated":true}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dropSessionDidUpdate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIDropSession","text":"UIDropSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withDestinationIndexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewDropProposal","text":"UICollectionViewDropProposal"}],"title":"collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)","role":"symbol","symbolKind":"method","externalID":"c:objc(pl)UICollectionViewDropDelegate(im)collectionView:dropSessionDidUpdate:withDestinationIndexPath:","navigatorTitle":[{"kind":"identifier","text":"collectionView:dropSessionDidUpdate:withDestinationIndexPath:"}],"platforms":[{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"11.0","name":"iOS"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"11.0","name":"iPadOS"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"13.1","name":"Mac Catalyst"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"1.0","name":"visionOS"}],"modules":[{"name":"UIKit"}],"roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate"]]},"variants":[{"paths":["/documentation/uikit/uicollectionviewdropdelegate/collectionview(_:dropsessiondidupdate:withdestinationindexpath:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uicollectionviewdropdelegate/collectionview(_:dropsessiondidupdate:withdestinationindexpath:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Tells your delegate that the position of the dragged data over the collection view changed."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UICollectionView","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dropSessionDidUpdate","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":": any ","kind":"text"},{"text":"UIDropSession","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropSession","preciseIdentifier":"c:objc(pl)UIDropSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"withDestinationIndexPath","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"destinationIndexPath","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","identifier":"doc://com.externally.resolved.symbol/s:10Foundation9IndexPathV","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"UICollectionViewDropProposal","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal","preciseIdentifier":"c:objc(cs)UICollectionViewDropProposal","kind":"typeIdentifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"collectionView","content":[{"inlineContent":[{"type":"text","text":"The collection view that’s tracking the dragged content."}],"type":"paragraph"}]},{"name":"session","content":[{"inlineContent":[{"text":"The drop session object containing information about the type of data being dragged.","type":"text"}],"type":"paragraph"}]},{"name":"destinationIndexPath","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The index path at which the content would be dropped."}]}]}]},{"content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"text":"Your proposal for how to handle the content if it is dropped at the specified location.","type":"text"}]}],"kind":"content"},{"kind":"mentions","mentions":["doc://com.apple.uikit/documentation/UIKit/supporting-drag-and-drop-in-collection-views"]},{"content":[{"anchor":"Discussion","level":2,"type":"heading","text":"Discussion"},{"inlineContent":[{"type":"text","text":"While the user is dragging content, the collection view calls this method repeatedly to determine how you would handle the drop if it occurred at the specified location. The collection view provides visual feedback to the user based on your proposal."}],"type":"paragraph"},{"inlineContent":[{"text":"In your implementation of this method, create a ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal","isActive":true,"type":"reference"},{"text":" object and use it to convey your intentions. Because this method is called repeatedly while the user drags over the table view, your implementation should return as quickly as possible.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidExit:)":{"navigatorTitle":[{"kind":"identifier","text":"collectionView:dropSessionDidExit:"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dropSessionDidExit","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"UIDropSession","preciseIdentifier":"c:objc(pl)UIDropSession","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Notifies you when dragged content exits the collection view’s bounds rectangle."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidExit:)","url":"/documentation/uikit/uicollectionviewdropdelegate/collectionview(_:dropsessiondidexit:)","role":"symbol","type":"topic","title":"collectionView(_:dropSessionDidExit:)"},"doc://com.apple.uikit/documentation/UIKit/supporting-drag-and-drop-in-collection-views":{"abstract":[{"text":"Initiate drags and handle drops from a collection view.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/supporting-drag-and-drop-in-collection-views","url":"/documentation/uikit/supporting-drag-and-drop-in-collection-views","kind":"article","role":"article","title":"Supporting Drag and Drop in Collection Views","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidEnd:)":{"navigatorTitle":[{"kind":"identifier","text":"collectionView:dropSessionDidEnd:"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dropSessionDidEnd","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"UIDropSession","preciseIdentifier":"c:objc(pl)UIDropSession","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Notifies you when the drag operation ends."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidEnd:)","url":"/documentation/uikit/uicollectionviewdropdelegate/collectionview(_:dropsessiondidend:)","role":"symbol","type":"topic","title":"collectionView(_:dropSessionDidEnd:)"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)":{"type":"topic","url":"/documentation/uikit/uicollectionviewdropdelegate/collectionview(_:dropsessiondidupdate:withdestinationindexpath:)","kind":"symbol","role":"symbol","abstract":[{"text":"Tells your delegate that the position of the dragged data over the collection view changed.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"collectionView:dropSessionDidUpdate:withDestinationIndexPath:"}],"title":"collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"text":", ","kind":"text"},{"text":"dropSessionDidUpdate","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"UIDropSession","preciseIdentifier":"c:objc(pl)UIDropSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"withDestinationIndexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionViewDropProposal","kind":"typeIdentifier","text":"UICollectionViewDropProposal"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)"},"doc://com.apple.uikit/documentation/UIKit/UIDropSession":{"abstract":[{"type":"text","text":"The interface for querying a drop session about its state and associated drag items."}],"url":"/documentation/uikit/uidropsession","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropSession","title":"UIDropSession","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"UIDropSession","kind":"identifier"}],"navigatorTitle":[{"text":"UIDropSession","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidEnter:)":{"navigatorTitle":[{"kind":"identifier","text":"collectionView:dropSessionDidEnter:"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dropSessionDidEnter","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"UIDropSession","preciseIdentifier":"c:objc(pl)UIDropSession","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Notifies you when dragged content enters the collection view’s bounds rectangle."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidEnter:)","url":"/documentation/uikit/uicollectionviewdropdelegate/collectionview(_:dropsessiondidenter:)","role":"symbol","type":"topic","title":"collectionView(_:dropSessionDidEnter:)"},"doc://com.externally.resolved.symbol/s:10Foundation9IndexPathV":{"role":"symbol","url":"/documentation/foundation/indexpath","abstract":[{"type":"text","text":"A list of indexes that together represent the path to a specific location in a tree of nested arrays. "}],"type":"topic","title":"IndexPath","fragments":[{"text":"struct ","kind":"text"},{"text":"IndexPath","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:10Foundation9IndexPathV","kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSIndexPath":{"abstract":[{"type":"text","text":"An object containing a list of indexes that bridges to ; use  when you need reference semantics or other Foundation-specific behavior."}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSIndexPath","url":"/documentation/foundation/nsindexpath","kind":"symbol","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSIndexPath"}],"role":"symbol","title":"NSIndexPath","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UICollectionView":{"navigatorTitle":[{"text":"UICollectionView","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UICollectionView","kind":"identifier"}],"kind":"symbol","url":"/documentation/uikit/uicollectionview","title":"UICollectionView","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionView","type":"topic","role":"symbol","abstract":[{"type":"text","text":"An object that manages an ordered collection of data items and presents them using customizable layouts."}]},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate":{"abstract":[{"text":"The interface for handling drops in a collection view.","type":"text"}],"title":"UICollectionViewDropDelegate","url":"/documentation/uikit/uicollectionviewdropdelegate","navigatorTitle":[{"kind":"identifier","text":"UICollectionViewDropDelegate"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"UICollectionViewDropDelegate","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"UICollectionViewDropProposal","kind":"identifier"}],"title":"UICollectionViewDropProposal","url":"/documentation/uikit/uicollectionviewdropproposal","abstract":[{"text":"Your proposed solution for handling a drop in a collection view.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UICollectionViewDropProposal","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"unavailable":false,"name":"iOS","beta":false,"introducedAt":"11.0","deprecated":false},{"unavailable":false,"name":"iPadOS","beta":false,"introducedAt":"11.0","deprecated":false},{"unavailable":false,"name":"Mac Catalyst","beta":false,"introducedAt":"13.1","deprecated":false},{"unavailable":false,"name":"visionOS","beta":false,"introducedAt":"1.0","deprecated":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"collectionView:dropSessionDidUpdate:withDestinationIndexPath:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:dropSessionDidUpdate:withDestinationIndexPath:"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"anchor":"Tracking-the-drag-movements","identifiers":["doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidEnter:)","doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidExit:)","doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidEnd:)"],"generated":true,"title":"Tracking the drag movements"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal","preciseIdentifier":"c:objc(cs)UICollectionViewDropProposal","text":"UICollectionViewDropProposal"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"collectionView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"collectionView"},{"kind":"text","text":" "},{"kind":"identifier","text":"dropSessionDidUpdate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)UIDropSession","text":"id<UIDropSession>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"session"},{"kind":"text","text":" "},{"kind":"identifier","text":"withDestinationIndexPath:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath","text":"NSIndexPath"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"destinationIndexPath"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]}},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"collectionView","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The collection view that’s tracking the dragged content."}]}]},{"name":"session","content":[{"type":"paragraph","inlineContent":[{"text":"The drop session object containing information about the type of data being dragged.","type":"text"}]}]},{"name":"destinationIndexPath","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The index path at which the content would be dropped."}]}]}]},"path":"/primaryContentSections/1"},{"path":"/primaryContentSections/2","op":"replace","value":{"kind":"content","content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"Your proposal for how to handle the content if it is dropped at the specified location."}],"type":"paragraph"}]}},{"op":"replace","value":"collectionView:dropSessionDidExit:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:dropSessionDidExit:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:dropSessionDidExit:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:dropSessionDidExit:)/fragments"},{"op":"replace","value":"collectionView:dropSessionDidEnd:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:dropSessionDidEnd:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:dropSessionDidEnd:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:dropSessionDidEnd:)/fragments"},{"op":"replace","value":"collectionView:dropSessionDidUpdate:withDestinationIndexPath:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"collectionView:dropSessionDidUpdate:withDestinationIndexPath:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)/fragments"},{"op":"replace","value":"UIDropSession","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession/title"},{"op":"replace","value":[{"text":"UIDropSession","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UIDropSession"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession/navigatorTitle"},{"op":"replace","value":"collectionView:dropSessionDidEnter:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:dropSessionDidEnter:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"collectionView:dropSessionDidEnter:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:dropSessionDidEnter:)/fragments"},{"op":"replace","value":[{"text":"A list of indexes that together represent the path to a specific location in a tree of nested arrays.","type":"text"}],"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSIndexPath/abstract"},{"op":"replace","value":"UICollectionView","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView/title"},{"op":"replace","value":[{"kind":"identifier","text":"UICollectionView"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UICollectionView"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView/navigatorTitle"},{"op":"replace","value":"UICollectionViewDropDelegate","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate/title"},{"op":"replace","value":[{"text":"UICollectionViewDropDelegate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UICollectionViewDropDelegate"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate/navigatorTitle"},{"op":"replace","value":"UICollectionViewDropProposal","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropProposal/title"},{"op":"replace","value":[{"kind":"identifier","text":"UICollectionViewDropProposal"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropProposal/fragments"},{"op":"replace","value":[{"text":"UICollectionViewDropProposal","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropProposal/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}