{"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uicollectionviewdropdelegate/collectionview(_:dropsessiondidenter:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uicollectionviewdropdelegate/collectionview(_:dropsessiondidenter:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidEnter:)"},"seeAlsoSections":[{"generated":true,"title":"Tracking the drag movements","identifiers":["doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)","doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidExit:)","doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidEnd:)"],"anchor":"Tracking-the-drag-movements"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionView"},{"text":", ","kind":"text"},{"text":"dropSessionDidEnter","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIDropSession","text":"UIDropSession","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropSession"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"collectionView","content":[{"inlineContent":[{"type":"text","text":"The collection view that’s tracking the dragged content."}],"type":"paragraph"}]},{"name":"session","content":[{"type":"paragraph","inlineContent":[{"text":"The drop session object containing information about the type of data being dragged.","type":"text"}]}]}]},{"content":[{"type":"heading","anchor":"Discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The collection view calls this method when dragged content enters its bounds rectangle. The method isn’t called again until the dragged content exits the collection view’s bounds (triggering a call to the "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidExit:)","isActive":true},{"type":"text","text":" method) and enters again."}]},{"type":"paragraph","inlineContent":[{"text":"Use this method to perform any one-time setup associated with tracking dragged content over the collection view.","type":"text"}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Notifies you when dragged content enters the collection view’s bounds rectangle.","type":"text"}],"metadata":{"role":"symbol","platforms":[{"introducedAt":"11.0","name":"iOS","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"11.0","name":"iPadOS","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"13.1","name":"Mac Catalyst","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"1.0","name":"visionOS","unavailable":false,"beta":false,"deprecated":false}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dropSessionDidEnter"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"UIDropSession","preciseIdentifier":"c:objc(pl)UIDropSession"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"collectionView:dropSessionDidEnter:"}],"title":"collectionView(_:dropSessionDidEnter:)","roleHeading":"Instance Method","modules":[{"name":"UIKit"}],"externalID":"c:objc(pl)UICollectionViewDropDelegate(im)collectionView:dropSessionDidEnter:"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate"]]},"references":{"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIDropSession":{"abstract":[{"type":"text","text":"The interface for querying a drop session about its state and associated drag items."}],"url":"/documentation/uikit/uidropsession","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropSession","title":"UIDropSession","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"UIDropSession","kind":"identifier"}],"navigatorTitle":[{"text":"UIDropSession","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidEnter:)":{"navigatorTitle":[{"kind":"identifier","text":"collectionView:dropSessionDidEnter:"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dropSessionDidEnter","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"UIDropSession","preciseIdentifier":"c:objc(pl)UIDropSession","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Notifies you when dragged content enters the collection view’s bounds rectangle."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidEnter:)","url":"/documentation/uikit/uicollectionviewdropdelegate/collectionview(_:dropsessiondidenter:)","role":"symbol","type":"topic","title":"collectionView(_:dropSessionDidEnter:)"},"doc://com.apple.uikit/documentation/UIKit/UICollectionView":{"navigatorTitle":[{"text":"UICollectionView","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UICollectionView","kind":"identifier"}],"kind":"symbol","url":"/documentation/uikit/uicollectionview","title":"UICollectionView","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionView","type":"topic","role":"symbol","abstract":[{"type":"text","text":"An object that manages an ordered collection of data items and presents them using customizable layouts."}]},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate":{"abstract":[{"text":"The interface for handling drops in a collection view.","type":"text"}],"title":"UICollectionViewDropDelegate","url":"/documentation/uikit/uicollectionviewdropdelegate","navigatorTitle":[{"kind":"identifier","text":"UICollectionViewDropDelegate"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"UICollectionViewDropDelegate","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)":{"type":"topic","url":"/documentation/uikit/uicollectionviewdropdelegate/collectionview(_:dropsessiondidupdate:withdestinationindexpath:)","kind":"symbol","role":"symbol","abstract":[{"text":"Tells your delegate that the position of the dragged data over the collection view changed.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"collectionView:dropSessionDidUpdate:withDestinationIndexPath:"}],"title":"collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"text":", ","kind":"text"},{"text":"dropSessionDidUpdate","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"UIDropSession","preciseIdentifier":"c:objc(pl)UIDropSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"withDestinationIndexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionViewDropProposal","kind":"typeIdentifier","text":"UICollectionViewDropProposal"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidEnd:)":{"navigatorTitle":[{"kind":"identifier","text":"collectionView:dropSessionDidEnd:"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dropSessionDidEnd","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"UIDropSession","preciseIdentifier":"c:objc(pl)UIDropSession","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Notifies you when the drag operation ends."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidEnd:)","url":"/documentation/uikit/uicollectionviewdropdelegate/collectionview(_:dropsessiondidend:)","role":"symbol","type":"topic","title":"collectionView(_:dropSessionDidEnd:)"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidExit:)":{"navigatorTitle":[{"kind":"identifier","text":"collectionView:dropSessionDidExit:"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dropSessionDidExit","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"UIDropSession","preciseIdentifier":"c:objc(pl)UIDropSession","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Notifies you when dragged content exits the collection view’s bounds rectangle."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidExit:)","url":"/documentation/uikit/uicollectionviewdropdelegate/collectionview(_:dropsessiondidexit:)","role":"symbol","type":"topic","title":"collectionView(_:dropSessionDidExit:)"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"unavailable":false,"name":"iOS","introducedAt":"11.0","beta":false,"deprecated":false},{"unavailable":false,"name":"iPadOS","introducedAt":"11.0","beta":false,"deprecated":false},{"unavailable":false,"name":"Mac Catalyst","introducedAt":"13.1","beta":false,"deprecated":false},{"unavailable":false,"name":"visionOS","introducedAt":"1.0","beta":false,"deprecated":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"collectionView:dropSessionDidEnter:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:dropSessionDidEnter:"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"anchor":"Tracking-the-drag-movements","identifiers":["doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)","doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidExit:)","doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidEnd:)"],"generated":true,"title":"Tracking the drag movements"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"collectionView:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UICollectionView","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"text":" *) ","kind":"text"},{"text":"collectionView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"dropSessionDidEnter:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<UIDropSession>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)UIDropSession"},{"text":") ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"}},{"path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The collection view that’s tracking the dragged content."}],"type":"paragraph"}],"name":"collectionView"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The drop session object containing information about the type of data being dragged.","type":"text"}]}],"name":"session"}]},"op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession/title","value":"UIDropSession"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession/fragments","value":[{"text":"UIDropSession","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession/navigatorTitle","value":[{"text":"UIDropSession","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:dropSessionDidEnter:)/title","value":"collectionView:dropSessionDidEnter:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:dropSessionDidEnter:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"collectionView:dropSessionDidEnter:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView/title","value":"UICollectionView"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView/fragments","value":[{"kind":"identifier","text":"UICollectionView"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView/navigatorTitle","value":[{"text":"UICollectionView","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate/title","value":"UICollectionViewDropDelegate"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate/fragments","value":[{"kind":"identifier","text":"UICollectionViewDropDelegate"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate/navigatorTitle","value":[{"text":"UICollectionViewDropDelegate","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)/title","value":"collectionView:dropSessionDidUpdate:withDestinationIndexPath:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"collectionView:dropSessionDidUpdate:withDestinationIndexPath:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:dropSessionDidEnd:)/title","value":"collectionView:dropSessionDidEnd:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:dropSessionDidEnd:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:dropSessionDidEnd:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:dropSessionDidExit:)/title","value":"collectionView:dropSessionDidExit:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:dropSessionDidExit:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:dropSessionDidExit:"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}