{
  "abstract": [
    {
      "text": "The tag specification dictionary of the type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers",
        "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeReference"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeReference/tags"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UniformTypeIdentifiers",
    "externalID": "c:objc(cs)UTType(py)tags",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "tags"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": " : ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": "]]"
      }
    ],
    "modules": [
      {
        "name": "Uniform Type Identifiers"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "tags"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "tags"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "tags"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": " : ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": "]] { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Uniform Type Identifiers don’t store tag information for nonstandard tag classes. Identifiers normalize string values into arrays that contain those strings. For example, a tag specification dictionary with values of:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "{",
            "    \"public.mime-type\": \"x/y\",",
            "    \"nonstandard-tag-class\": \"abc\",",
            "}"
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Normalizes to:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "{",
            "    \"public.mime-type\": [\"x/y\"]",
            "}"
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Use the tag class ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTagClass/mimeType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTagClass/filenameExtension",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to retrieve the list of supporting MIME types or filename extensions for your type. For example, the following example retrieves a list of the filename extensions for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTType-swift.struct/mpeg",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " type:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let MPEGextensions = UTType.mpeg.tags[.filenameExtension]"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Types that have no tags for the requested tag class return a nil, not an empty array.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To get the preferred filename extension or MIME type, use the tag class ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTType-swift.struct/preferredFilenameExtension",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTType-swift.struct/preferredMIMEType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", respectively.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers": {
      "abstract": [
        {
          "text": "Provide uniform type identifiers that describe file types for storage or transfer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers",
      "kind": "symbol",
      "role": "collection",
      "title": "Uniform Type Identifiers",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTagClass/filenameExtension": {
      "abstract": [
        {
          "text": "A type property that returns the tag class used to map a type to a filename extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "filenameExtension"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22UniformTypeIdentifiers10UTTagClassV",
          "text": "UTTagClass"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTagClass/filenameExtension",
      "kind": "symbol",
      "role": "symbol",
      "title": "filenameExtension",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/uttagclass/filenameextension"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTagClass/mimeType": {
      "abstract": [
        {
          "text": "A type property that returns the tag class used to map a type to a MIME type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mimeType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22UniformTypeIdentifiers10UTTagClassV",
          "text": "UTTagClass"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTagClass/mimeType",
      "kind": "symbol",
      "role": "symbol",
      "title": "mimeType",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/uttagclass/mimetype"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTType-swift.struct/mpeg": {
      "abstract": [
        {
          "text": "A type that represents an MPEG-1 or MPEG-2 movie.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mpeg"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22UniformTypeIdentifiers6UTTypeV",
          "text": "UTType"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTType-swift.struct/mpeg",
      "kind": "symbol",
      "role": "symbol",
      "title": "mpeg",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/uttype-swift.struct/mpeg"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTType-swift.struct/preferredFilenameExtension": {
      "abstract": [
        {
          "text": "The preferred filename extension for the type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredFilenameExtension"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTType-swift.struct/preferredFilenameExtension",
      "kind": "symbol",
      "role": "symbol",
      "title": "preferredFilenameExtension",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/uttype-swift.struct/preferredfilenameextension"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTType-swift.struct/preferredMIMEType": {
      "abstract": [
        {
          "text": "The preferred MIME type for the type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredMIMEType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTType-swift.struct/preferredMIMEType",
      "kind": "symbol",
      "role": "symbol",
      "title": "preferredMIMEType",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/uttype-swift.struct/preferredmimetype"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeReference": {
      "abstract": [
        {
          "text": "An object that represents a type of data to load, send, or receive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UTTypeReference"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UTTypeReference"
        }
      ],
      "role": "symbol",
      "title": "UTTypeReference",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/uttypereference"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeReference/preferredFilenameExtension": {
      "abstract": [
        {
          "text": "The preferred filename extension for the type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredFilenameExtension"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeReference/preferredFilenameExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredFilenameExtension"
        }
      ],
      "role": "symbol",
      "title": "preferredFilenameExtension",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/uttypereference/preferredfilenameextension"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeReference/preferredMIMEType": {
      "abstract": [
        {
          "text": "The preferred MIME type for the type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredMIMEType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeReference/preferredMIMEType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredMIMEType"
        }
      ],
      "role": "symbol",
      "title": "preferredMIMEType",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/uttypereference/preferredmimetype"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeReference/tags": {
      "abstract": [
        {
          "text": "The tag specification dictionary of the type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tags"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]]"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeReference/tags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tags"
        }
      ],
      "role": "symbol",
      "title": "tags",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/uttypereference/tags"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "tags"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers",
                "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeReference"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Obtaining-tags",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeReference/preferredFilenameExtension",
                "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeReference/preferredMIMEType"
              ],
              "title": "Obtaining tags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSDictionary",
                    "text": "NSDictionary<NSString *,NSArray<NSString *> *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "tags"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uniformtypeidentifiers~1documentation~1UniformTypeIdentifiers~1UTTypeReference/title",
          "value": "UTType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uniformtypeidentifiers~1documentation~1UniformTypeIdentifiers~1UTTypeReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UTType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uniformtypeidentifiers~1documentation~1UniformTypeIdentifiers~1UTTypeReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UTType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uniformtypeidentifiers~1documentation~1UniformTypeIdentifiers~1UTTypeReference~1preferredMIMEType/title",
          "value": "preferredMIMEType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uniformtypeidentifiers~1documentation~1UniformTypeIdentifiers~1UTTypeReference~1preferredMIMEType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredMIMEType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uniformtypeidentifiers~1documentation~1UniformTypeIdentifiers~1UTTypeReference~1tags/title",
          "value": "tags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uniformtypeidentifiers~1documentation~1UniformTypeIdentifiers~1UTTypeReference~1tags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uniformtypeidentifiers~1documentation~1UniformTypeIdentifiers~1UTTypeReference~1preferredFilenameExtension/title",
          "value": "preferredFilenameExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uniformtypeidentifiers~1documentation~1UniformTypeIdentifiers~1UTTypeReference~1preferredFilenameExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredFilenameExtension"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uniformtypeidentifiers/uttypereference/tags"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uniformtypeidentifiers/uttypereference/tags"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
