{
  "abstract": [
    {
      "text": "Returns an array of types from the provided tag and tag class.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers",
        "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeReference"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeReference/types(tag:tagClass:conformingTo:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UniformTypeIdentifiers",
    "externalID": "c:objc(cs)UTType(cm)typesWithTag:tagClass:conformingToType:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "types"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "tag"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "tagClass"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "conformingTo"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:22UniformTypeIdentifiers6UTTypeV",
        "text": "UTType"
      },
      {
        "kind": "text",
        "text": "?) -> ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:22UniformTypeIdentifiers6UTTypeV",
        "text": "UTType"
      },
      {
        "kind": "text",
        "text": "]"
      }
    ],
    "modules": [
      {
        "name": "Uniform Type Identifiers"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "typesWithTag:tagClass:conformingToType:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "types(tag:tagClass:conformingTo:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "types"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "tag"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "tagClass"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "conformingTo"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "supertype"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTType-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:22UniformTypeIdentifiers6UTTypeV",
              "text": "UTType"
            },
            {
              "kind": "text",
              "text": "?) -> ["
            },
            {
              "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTType-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:22UniformTypeIdentifiers6UTTypeV",
              "text": "UTType"
            },
            {
              "kind": "text",
              "text": "]"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The desired tag, such as a filename extension.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "tag"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The tag class, such as ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTagClassFilenameExtension",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "tagClass"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Another type that the resulting type must conform to; for example, ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeData",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "supertype"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers": {
      "abstract": [
        {
          "text": "Provide uniform type identifiers that describe file types for storage or transfer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers",
      "kind": "symbol",
      "role": "collection",
      "title": "Uniform Type Identifiers",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTagClassFilenameExtension": {
      "abstract": [
        {
          "text": "The string identifier for the tag that maps to filename extensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UTTagClassFilenameExtension"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTagClassFilenameExtension",
      "kind": "symbol",
      "role": "symbol",
      "title": "UTTagClassFilenameExtension",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/uttagclassfilenameextension"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTType-swift.struct": {
      "abstract": [
        {
          "text": "A structure that represents a type of data to load, send, or receive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UTType"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTType-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UTType"
        }
      ],
      "role": "symbol",
      "title": "UTType",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/uttype-swift.struct"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeData": {
      "abstract": [
        {
          "text": "A base type that represents any sort of byte stream, including files and in-memory data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UTTypeData"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeData",
      "kind": "symbol",
      "role": "symbol",
      "title": "UTTypeData",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/uttypedata"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeReference": {
      "abstract": [
        {
          "text": "An object that represents a type of data to load, send, or receive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UTTypeReference"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UTTypeReference"
        }
      ],
      "role": "symbol",
      "title": "UTTypeReference",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/uttypereference"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeReference/types(tag:tagClass:conformingTo:)": {
      "abstract": [
        {
          "text": "Returns an array of types from the provided tag and tag class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "types"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "tag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "tagClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "conformingTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22UniformTypeIdentifiers6UTTypeV",
          "text": "UTType"
        },
        {
          "kind": "text",
          "text": "?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22UniformTypeIdentifiers6UTTypeV",
          "text": "UTType"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeReference/types(tag:tagClass:conformingTo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "typesWithTag:tagClass:conformingToType:"
        }
      ],
      "role": "symbol",
      "title": "types(tag:tagClass:conformingTo:)",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/uttypereference/types(tag:tagclass:conformingto:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "typesWithTag:tagClass:conformingToType:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "typesWithTag:tagClass:conformingToType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers",
                "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeReference"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<UTType *>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "typesWithTag:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "tag"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "tagClass:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "tagClass"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "conformingToType:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeReference",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UTType",
                    "text": "UTType"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "supertype"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The desired tag, such as a filename extension.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "tag"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The tag class, such as ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTagClassFilenameExtension",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "tagClass"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Another type that the resulting type must conform to; for example, ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeData",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "supertype"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uniformtypeidentifiers~1documentation~1UniformTypeIdentifiers~1UTTypeReference/title",
          "value": "UTType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uniformtypeidentifiers~1documentation~1UniformTypeIdentifiers~1UTTypeReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UTType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uniformtypeidentifiers~1documentation~1UniformTypeIdentifiers~1UTTypeReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UTType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uniformtypeidentifiers~1documentation~1UniformTypeIdentifiers~1UTTypeReference~1types(tag:tagClass:conformingTo:)/title",
          "value": "typesWithTag:tagClass:conformingToType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uniformtypeidentifiers~1documentation~1UniformTypeIdentifiers~1UTTypeReference~1types(tag:tagClass:conformingTo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "typesWithTag:tagClass:conformingToType:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uniformtypeidentifiers/uttypereference/types(tag:tagclass:conformingto:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uniformtypeidentifiers/uttypereference/types(tag:tagclass:conformingto:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
