{
  "abstract": [
    {
      "text": "Assemble a hierarchy of contexts and declare your app’s assignable content.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.classkit/documentation/ClassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.classkit/documentation/ClassKit/advertising-your-app-s-assignable-content"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "ClassKit"
      }
    ],
    "role": "collectionGroup",
    "title": "Advertising your app’s assignable content"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A context, stored as a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance, represents an area within your app, such as a book chapter or a game level, that teachers can assign to students as tasks. You create a hierarchy of contexts to enable teachers to browse and assign your app’s content. You provide deep links to the content that the contexts represent to help teachers guide students to your content. You then activate and deactivate contexts as users move through your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Identify-Your-Apps-Assignable-Tasks",
          "level": 3,
          "text": "Identify Your App’s Assignable Tasks",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Before you write any new code, decide which parts of your existing app correspond to tasks that a teacher might want to assign to students. For example, a textbook reader app might divide textbooks into chapters and sections, while offering tests and quizzes to measure the reader’s retention of the material. So the app’s assignable tasks fall into a hierarchical structure with the app at the top and tests and quizzes at the bottom.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2969445",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Every app that adopts ClassKit has a single, predefined top-level context called the main app context. To this, you add one or more child contexts representing assignable tasks, each potentially with descendants of its own representing subtasks.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Organize the hierarchy so that it makes sense to teachers creating assignments. For example, the lowest level contexts should represent indivisible units of work, like a quiz. Don’t define a different context for each question of a quiz when you expect teachers to assign the entire quiz as a single task. Instead, use a single context to represent the whole quiz.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Do use contexts to group other contexts in a way that allows teachers to extract useful metrics. A teacher might be interested in a student’s progress not only through a particular section of a textbook, but also through the entire chapter in which that section appears, as well as through the book as a whole. You can design a context hierarchy up to eight levels deep, including the main app context.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Tell-ClassKit-About-Your-Content",
          "level": 3,
          "text": "Tell ClassKit About Your Content",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For teachers to be able to assign your app’s content, they have to be able to see it in the Schoolwork app. Schoolwork becomes aware of your content after you tell ClassKit about it. So your next task is to declare the existence of all your contexts to ClassKit. This results in a navigable table of contents in the Schoolwork app that teachers can browse when creating assignments.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You declare a context by requesting it from the data store—the shared ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance—using an identifier that you assign. The act of asking for a context tells ClassKit that it exists, and where it lives in the context hierarchy. For details, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/declaring-your-app-s-context-hierarchy",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-New-Contexts-When-Needed",
          "level": 3,
          "text": "Create New Contexts When Needed",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you ask the data store for a context, whether to declare its existence or to activate and use it, the data store looks to see if that context already exists in its database. If so, the data store returns the stored context. If not, the data store asks its delegate to build the context. You adopt the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSDataStoreDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol to build contexts when they don’t already exist, as described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/building-missing-contexts",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Help-Teachers-Guide-Students-to-Your-Content",
          "level": 3,
          "text": "Help Teachers Guide Students to Your Content",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Tapping in the Schoolwork app on an assignment associated with your ClassKit enabled app generates a deep link to your app. The link arrives in the form of either a user activity or a universal link, depending on how you’ve configured the context corresponding to the assignment. By properly handling this link, as described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/linking-directly-to-assignments",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", you help teachers to guide students to the content that’s important to them.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Activate-Contexts-When-Users-Begin-a-Task",
          "level": 3,
          "text": "Activate Contexts When Users Begin a Task",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When the user begins a task that corresponds to one of your app’s contexts, you activate the context. Later, when the user completes the task, you deactivate the context. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/informing-classkit-that-a-task-is-about-to-begin",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for details.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Ignore-the-Users-Role",
          "level": 3,
          "text": "Ignore the User’s Role",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Certain aspects of context management only pertain to particular users. For example, students never see a complete table of contents of your app’s content in Schoolwork, so they don’t need to declare or build all contexts. They really only need to build the contexts associated with specific assignments that they receive. However, for privacy reasons, ClassKit doesn’t tell you the current user’s role. So your app must perform all operations for all users and let ClassKit figure out what data it actually needs. For more details, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/about-classkit-and-user-roles",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.classkit/documentation/ClassKit": {
      "abstract": [
        {
          "text": "Enable teachers to assign activities from your app’s content and to view student progress.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClassKit",
      "type": "topic",
      "url": "/documentation/classkit"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext": {
      "abstract": [
        {
          "text": "An area of your app that represents an assignable task, like a quiz or a chapter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSContext"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContext"
        }
      ],
      "role": "symbol",
      "title": "CLSContext",
      "type": "topic",
      "url": "/documentation/classkit/clscontext"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextProvider": {
      "abstract": [
        {
          "text": "An interface used to tell your ClassKit context provider app extension to update contexts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSContextProvider"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextProvider"
        }
      ],
      "role": "symbol",
      "title": "CLSContextProvider",
      "type": "topic",
      "url": "/documentation/classkit/clscontextprovider"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore": {
      "abstract": [
        {
          "text": "A container for all the ClassKit data in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSDataStore"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSDataStore"
        }
      ],
      "role": "symbol",
      "title": "CLSDataStore",
      "type": "topic",
      "url": "/documentation/classkit/clsdatastore"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSDataStoreDelegate": {
      "abstract": [
        {
          "text": "An interface the data store uses to request new contexts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSDataStoreDelegate"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSDataStoreDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSDataStoreDelegate"
        }
      ],
      "role": "symbol",
      "title": "CLSDataStoreDelegate",
      "type": "topic",
      "url": "/documentation/classkit/clsdatastoredelegate"
    },
    "doc://com.apple.classkit/documentation/ClassKit/about-classkit-and-user-roles": {
      "abstract": [
        {
          "text": "Understand how ClassKit interacts with different kinds of users.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/about-classkit-and-user-roles",
      "kind": "article",
      "role": "article",
      "title": "About ClassKit and user roles",
      "type": "topic",
      "url": "/documentation/classkit/about-classkit-and-user-roles"
    },
    "doc://com.apple.classkit/documentation/ClassKit/building-missing-contexts": {
      "abstract": [
        {
          "text": "Create and initialize missing contexts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/building-missing-contexts",
      "kind": "article",
      "role": "article",
      "title": "Building missing contexts",
      "type": "topic",
      "url": "/documentation/classkit/building-missing-contexts"
    },
    "doc://com.apple.classkit/documentation/ClassKit/creating-bookmarks-and-assignments-from-your-app": {
      "abstract": [
        {
          "text": "Make it easier for teachers to find and assign your content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/creating-bookmarks-and-assignments-from-your-app",
      "kind": "article",
      "role": "article",
      "title": "Creating bookmarks and assignments from your app",
      "type": "topic",
      "url": "/documentation/classkit/creating-bookmarks-and-assignments-from-your-app"
    },
    "doc://com.apple.classkit/documentation/ClassKit/declaring-your-app-s-context-hierarchy": {
      "abstract": [
        {
          "text": "Tell ClassKit about your context hierarchy so teachers can see your assignable content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/declaring-your-app-s-context-hierarchy",
      "kind": "article",
      "role": "article",
      "title": "Declaring your app’s context hierarchy",
      "type": "topic",
      "url": "/documentation/classkit/declaring-your-app-s-context-hierarchy"
    },
    "doc://com.apple.classkit/documentation/ClassKit/informing-classkit-that-a-task-is-about-to-begin": {
      "abstract": [
        {
          "text": "Activate and deactivate contexts according to user interaction.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/informing-classkit-that-a-task-is-about-to-begin",
      "kind": "article",
      "role": "article",
      "title": "Informing ClassKit that a task is about to begin",
      "type": "topic",
      "url": "/documentation/classkit/informing-classkit-that-a-task-is-about-to-begin"
    },
    "doc://com.apple.classkit/documentation/ClassKit/linking-directly-to-assignments": {
      "abstract": [
        {
          "text": "Make it easy for teachers to guide students to specific content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/linking-directly-to-assignments",
      "kind": "article",
      "role": "article",
      "title": "Linking directly to assignments",
      "type": "topic",
      "url": "/documentation/classkit/linking-directly-to-assignments"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "media-2969445": {
      "alt": "Diagram showing a context hierarchy corresponding to a textbook reader.",
      "identifier": "media-2969445",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/b23ff2cd38ab0d1f9483d46e67c9eea5/media-2969445@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/b23ff2cd38ab0d1f9483d46e67c9eea5/media-2969445~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Contexts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextProvider"
      ],
      "title": "Contexts"
    }
  ],
  "topicSections": [
    {
      "anchor": "Context-management",
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/declaring-your-app-s-context-hierarchy",
        "doc://com.apple.classkit/documentation/ClassKit/building-missing-contexts",
        "doc://com.apple.classkit/documentation/ClassKit/informing-classkit-that-a-task-is-about-to-begin"
      ],
      "title": "Context management"
    },
    {
      "anchor": "Deep-links",
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/linking-directly-to-assignments"
      ],
      "title": "Deep links"
    },
    {
      "anchor": "Bookmarks",
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/creating-bookmarks-and-assignments-from-your-app"
      ],
      "title": "Bookmarks"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Context-management",
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/declaring-your-app-s-context-hierarchy",
                "doc://com.apple.classkit/documentation/ClassKit/building-missing-contexts",
                "doc://com.apple.classkit/documentation/ClassKit/informing-classkit-that-a-task-is-about-to-begin"
              ],
              "title": "Context management"
            },
            {
              "anchor": "Deep-links",
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/linking-directly-to-assignments"
              ],
              "title": "Deep links"
            },
            {
              "anchor": "Bookmarks",
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/creating-bookmarks-and-assignments-from-your-app"
              ],
              "title": "Bookmarks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Contexts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextProvider"
              ],
              "title": "Contexts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSDataStore/title",
          "value": "CLSDataStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSDataStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSDataStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSDataStore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSDataStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextProvider/title",
          "value": "CLSContextProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSDataStoreDelegate/title",
          "value": "CLSDataStoreDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSDataStoreDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSDataStoreDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSDataStoreDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSDataStoreDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext/title",
          "value": "CLSContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContext"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/classkit/advertising-your-app-s-assignable-content"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/classkit/advertising-your-app-s-assignable-content"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
