{
  "abstract": [
    {
      "text": "The areas of study to which contexts may relate.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.classkit/documentation/ClassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@CLSContextTopic",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CLSContextTopic"
      }
    ],
    "modules": [
      {
        "name": "ClassKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CLSContextTopic"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CLSContextTopic"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CLSContextTopic"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.classkit/documentation/ClassKit/building-missing-contexts"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After you initialize a context, you can assign it a topic by setting its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/topic",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property. Doing so helps teachers browsing your app’s content to understand what your app offers.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.classkit/documentation/ClassKit": {
      "abstract": [
        {
          "text": "Enable teachers to assign activities from your app’s content and to view student progress.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClassKit",
      "type": "topic",
      "url": "/documentation/classkit"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/displayOrder": {
      "abstract": [
        {
          "text": "The position of a context relative to its siblings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayOrder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/displayOrder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayOrder"
        }
      ],
      "role": "symbol",
      "title": "displayOrder",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/displayorder"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/topic": {
      "abstract": [
        {
          "text": "The area of study to which a context relates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLSContextTopic",
          "text": "CLSContextTopic"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/topic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "topic"
        }
      ],
      "role": "symbol",
      "title": "topic",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/topic"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic": {
      "abstract": [
        {
          "text": "The areas of study to which contexts may relate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSContextTopic"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTopic"
        }
      ],
      "role": "symbol",
      "title": "CLSContextTopic",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttopic"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/artsAndMusic": {
      "abstract": [
        {
          "text": "Arts and music.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "artsAndMusic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLSContextTopic",
          "text": "CLSContextTopic"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/artsAndMusic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTopicArtsAndMusic"
        }
      ],
      "role": "symbol",
      "title": "artsAndMusic",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttopic/artsandmusic"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/computerScienceAndEngineering": {
      "abstract": [
        {
          "text": "Computer science and engineering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "computerScienceAndEngineering"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLSContextTopic",
          "text": "CLSContextTopic"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/computerScienceAndEngineering",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTopicComputerScienceAndEngineering"
        }
      ],
      "role": "symbol",
      "title": "computerScienceAndEngineering",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttopic/computerscienceandengineering"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/healthAndFitness": {
      "abstract": [
        {
          "text": "Health and fitness.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "healthAndFitness"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLSContextTopic",
          "text": "CLSContextTopic"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/healthAndFitness",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTopicHealthAndFitness"
        }
      ],
      "role": "symbol",
      "title": "healthAndFitness",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttopic/healthandfitness"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/init(rawValue:)": {
      "abstract": [
        {
          "text": "Initializes a context topic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttopic/init(rawvalue:)"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/literacyAndWriting": {
      "abstract": [
        {
          "text": "Literacy and writing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "literacyAndWriting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLSContextTopic",
          "text": "CLSContextTopic"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/literacyAndWriting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTopicLiteracyAndWriting"
        }
      ],
      "role": "symbol",
      "title": "literacyAndWriting",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttopic/literacyandwriting"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/math": {
      "abstract": [
        {
          "text": "Mathematics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "math"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLSContextTopic",
          "text": "CLSContextTopic"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/math",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTopicMath"
        }
      ],
      "role": "symbol",
      "title": "math",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttopic/math"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/science": {
      "abstract": [
        {
          "text": "Science.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "science"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLSContextTopic",
          "text": "CLSContextTopic"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/science",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTopicScience"
        }
      ],
      "role": "symbol",
      "title": "science",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttopic/science"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/socialScience": {
      "abstract": [
        {
          "text": "Social science.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "socialScience"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLSContextTopic",
          "text": "CLSContextTopic"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/socialScience",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTopicSocialScience"
        }
      ],
      "role": "symbol",
      "title": "socialScience",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttopic/socialscience"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/worldLanguage": {
      "abstract": [
        {
          "text": "Language acquisition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "worldLanguage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLSContextTopic",
          "text": "CLSContextTopic"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/worldLanguage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTopicWorldLanguage"
        }
      ],
      "role": "symbol",
      "title": "worldLanguage",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttopic/worldlanguage"
    },
    "doc://com.apple.classkit/documentation/ClassKit/building-missing-contexts": {
      "abstract": [
        {
          "text": "Create and initialize missing contexts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/building-missing-contexts",
      "kind": "article",
      "role": "article",
      "title": "Building missing contexts",
      "type": "topic",
      "url": "/documentation/classkit/building-missing-contexts"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-context-presentation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/displayOrder",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/topic"
      ],
      "title": "Managing context presentation"
    }
  ],
  "topicSections": [
    {
      "anchor": "Context-Topics",
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/artsAndMusic",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/computerScienceAndEngineering",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/healthAndFitness",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/literacyAndWriting",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/math",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/science",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/socialScience",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/worldLanguage"
      ],
      "title": "Context Topics"
    },
    {
      "anchor": "Initializing-a-Topic",
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/init(rawValue:)"
      ],
      "title": "Initializing a Topic"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CLSContextTopic"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTopic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTopic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.classkit/documentation/ClassKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Context-Topics",
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/artsAndMusic",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/computerScienceAndEngineering",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/healthAndFitness",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/literacyAndWriting",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/math",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/science",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/socialScience",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/worldLanguage"
              ],
              "title": "Context Topics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-context-presentation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/displayOrder",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/topic"
              ],
              "title": "Managing context presentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "CLSContextTopic"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1worldLanguage/title",
          "value": "CLSContextTopicWorldLanguage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1worldLanguage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTopicWorldLanguage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1socialScience/title",
          "value": "CLSContextTopicSocialScience"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1socialScience/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTopicSocialScience"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1topic/title",
          "value": "topic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1topic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "topic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic/title",
          "value": "CLSContextTopic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTopic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTopic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1displayOrder/title",
          "value": "displayOrder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1displayOrder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displayOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1artsAndMusic/title",
          "value": "CLSContextTopicArtsAndMusic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1artsAndMusic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTopicArtsAndMusic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1literacyAndWriting/title",
          "value": "CLSContextTopicLiteracyAndWriting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1literacyAndWriting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTopicLiteracyAndWriting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1math/title",
          "value": "CLSContextTopicMath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1math/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTopicMath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1computerScienceAndEngineering/title",
          "value": "CLSContextTopicComputerScienceAndEngineering"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1computerScienceAndEngineering/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTopicComputerScienceAndEngineering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1healthAndFitness/title",
          "value": "CLSContextTopicHealthAndFitness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1healthAndFitness/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTopicHealthAndFitness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1science/title",
          "value": "CLSContextTopicScience"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1science/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTopicScience"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/classkit/clscontexttopic"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/classkit/clscontexttopic"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
