{
  "abstract": [
    {
      "text": "The kinds of assignable content a context can contain.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.classkit/documentation/ClassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.classkit/documentation/ClassKit/CLSContextType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CLSContextType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CLSContextType"
      }
    ],
    "modules": [
      {
        "name": "ClassKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CLSContextType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CLSContextType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CLSContextType"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you initialize a new context with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/init(type:identifier:title:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", you specify its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/type",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to provide an indication of how your content is structured. The type doesn’t affect the context’s behavior, but it does provide an important indicator to teachers trying to understand your app’s content.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.classkit/documentation/ClassKit": {
      "abstract": [
        {
          "text": "Enable teachers to assign activities from your app’s content and to view student progress.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClassKit",
      "type": "topic",
      "url": "/documentation/classkit"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/customTypeName": {
      "abstract": [
        {
          "text": "An optional name that the system presents to the user if you choose the custom context type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customTypeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/customTypeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "customTypeName"
        }
      ],
      "role": "symbol",
      "title": "customTypeName",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/customtypename"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/init(type:identifier:title:)": {
      "abstract": [
        {
          "text": "Initializes a new context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLSContextType",
          "text": "CLSContextType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/init(type:identifier:title:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithType:identifier:title:"
        }
      ],
      "role": "symbol",
      "title": "init(type:identifier:title:)",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/init(type:identifier:title:)"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/setType(_:)": {
      "abstract": [
        {
          "text": "Updates the kind of content that a context represents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLSContextType",
          "text": "CLSContextType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/setType(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setType:"
        }
      ],
      "role": "symbol",
      "title": "setType(_:)",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/settype(_:)"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/type": {
      "abstract": [
        {
          "text": "The kind of content a context represents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLSContextType",
          "text": "CLSContextType"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/type"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextType": {
      "abstract": [
        {
          "text": "The kinds of assignable content a context can contain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSContextType"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextType"
        }
      ],
      "role": "symbol",
      "title": "CLSContextType",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttype"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/app": {
      "abstract": [
        {
          "text": "An app context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "app"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/app",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTypeApp"
        }
      ],
      "role": "symbol",
      "title": "CLSContextType.app",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttype/app"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/audio": {
      "abstract": [
        {
          "text": "An audio context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audio"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/audio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTypeAudio"
        }
      ],
      "role": "symbol",
      "title": "CLSContextType.audio",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttype/audio"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/book": {
      "abstract": [
        {
          "text": "A book context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "book"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/book",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTypeBook"
        }
      ],
      "role": "symbol",
      "title": "CLSContextType.book",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttype/book"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/challenge": {
      "abstract": [
        {
          "text": "A challenge context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "challenge"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/challenge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTypeChallenge"
        }
      ],
      "role": "symbol",
      "title": "CLSContextType.challenge",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttype/challenge"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/chapter": {
      "abstract": [
        {
          "text": "A chapter context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "chapter"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/chapter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTypeChapter"
        }
      ],
      "role": "symbol",
      "title": "CLSContextType.chapter",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttype/chapter"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/course": {
      "abstract": [
        {
          "text": "A context that represents an entire course.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "course"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/course",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTypeCourse"
        }
      ],
      "role": "symbol",
      "title": "CLSContextType.course",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttype/course"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/custom": {
      "abstract": [
        {
          "text": "A context for assignable content that isn’t represented by one of the built-in context types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "custom"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/custom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTypeCustom"
        }
      ],
      "role": "symbol",
      "title": "CLSContextType.custom",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttype/custom"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/document": {
      "abstract": [
        {
          "text": "A document context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "document"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/document",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTypeDocument"
        }
      ],
      "role": "symbol",
      "title": "CLSContextType.document",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttype/document"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/exercise": {
      "abstract": [
        {
          "text": "An exercise context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exercise"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/exercise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTypeExercise"
        }
      ],
      "role": "symbol",
      "title": "CLSContextType.exercise",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttype/exercise"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/game": {
      "abstract": [
        {
          "text": "A game context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "game"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/game",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTypeGame"
        }
      ],
      "role": "symbol",
      "title": "CLSContextType.game",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttype/game"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttype/init(rawvalue:)"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/lesson": {
      "abstract": [
        {
          "text": "A lesson context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lesson"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/lesson",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTypeLesson"
        }
      ],
      "role": "symbol",
      "title": "CLSContextType.lesson",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttype/lesson"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/level": {
      "abstract": [
        {
          "text": "A level context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "level"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/level",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTypeLevel"
        }
      ],
      "role": "symbol",
      "title": "CLSContextType.level",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttype/level"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/none": {
      "abstract": [
        {
          "text": "No type is assigned.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTypeNone"
        }
      ],
      "role": "symbol",
      "title": "CLSContextType.none",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttype/none"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/page": {
      "abstract": [
        {
          "text": "A page context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "page"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/page",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTypePage"
        }
      ],
      "role": "symbol",
      "title": "CLSContextType.page",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttype/page"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/quiz": {
      "abstract": [
        {
          "text": "A quiz context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quiz"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/quiz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTypeQuiz"
        }
      ],
      "role": "symbol",
      "title": "CLSContextType.quiz",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttype/quiz"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/section": {
      "abstract": [
        {
          "text": "A section context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "section"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/section",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTypeSection"
        }
      ],
      "role": "symbol",
      "title": "CLSContextType.section",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttype/section"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/task": {
      "abstract": [
        {
          "text": "A task context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "task"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/task",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTypeTask"
        }
      ],
      "role": "symbol",
      "title": "CLSContextType.task",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttype/task"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/video": {
      "abstract": [
        {
          "text": "A video context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "video"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/video",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTypeVideo"
        }
      ],
      "role": "symbol",
      "title": "CLSContextType.video",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttype/video"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-the-context-type",
      "generated": true,
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/type",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/setType(_:)",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/customTypeName"
      ],
      "title": "Managing the context type"
    }
  ],
  "topicSections": [
    {
      "anchor": "Context-Types",
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/app",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/audio",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/book",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/challenge",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/chapter",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/course",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/custom",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/document",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/exercise",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/game",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/lesson",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/level",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/none",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/page",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/quiz",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/section",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/task",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/video"
      ],
      "title": "Context Types"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CLSContextType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.classkit/documentation/ClassKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Context-Types",
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/app",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/audio",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/book",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/challenge",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/chapter",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/course",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/custom",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/document",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/exercise",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/game",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/lesson",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/level",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/none",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/page",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/quiz",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/section",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/task",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextType/video"
              ],
              "title": "Context Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-the-context-type",
              "generated": true,
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/type",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/setType(_:)",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/customTypeName"
              ],
              "title": "Managing the context type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CLSContextType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1section/title",
          "value": "CLSContextTypeSection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1section/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTypeSection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1challenge/title",
          "value": "CLSContextTypeChallenge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1challenge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTypeChallenge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1custom/title",
          "value": "CLSContextTypeCustom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1custom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTypeCustom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1init(type:identifier:title:)/title",
          "value": "initWithType:identifier:title:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1init(type:identifier:title:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithType:identifier:title:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1page/title",
          "value": "CLSContextTypePage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1page/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTypePage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1app/title",
          "value": "CLSContextTypeApp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1app/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTypeApp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1chapter/title",
          "value": "CLSContextTypeChapter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1chapter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTypeChapter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1course/title",
          "value": "CLSContextTypeCourse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1course/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTypeCourse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType/title",
          "value": "CLSContextType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1game/title",
          "value": "CLSContextTypeGame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1game/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTypeGame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1setType(_:)/title",
          "value": "setType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1setType(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1level/title",
          "value": "CLSContextTypeLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1level/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTypeLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1none/title",
          "value": "CLSContextTypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTypeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1document/title",
          "value": "CLSContextTypeDocument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1document/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTypeDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1video/title",
          "value": "CLSContextTypeVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1video/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTypeVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1customTypeName/title",
          "value": "customTypeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1customTypeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "customTypeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1quiz/title",
          "value": "CLSContextTypeQuiz"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1quiz/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTypeQuiz"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1exercise/title",
          "value": "CLSContextTypeExercise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1exercise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTypeExercise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1task/title",
          "value": "CLSContextTypeTask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1task/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTypeTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1lesson/title",
          "value": "CLSContextTypeLesson"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1lesson/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTypeLesson"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1audio/title",
          "value": "CLSContextTypeAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1audio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTypeAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1book/title",
          "value": "CLSContextTypeBook"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType~1book/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTypeBook"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/classkit/clscontexttype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/classkit/clscontexttype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
