{
  "abstract": [
    {
      "text": "An area of your app that represents an assignable task, like a quiz or a chapter.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.classkit/documentation/ClassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.classkit/documentation/ClassKit/CLSContext"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CLSContext",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CLSContext"
      }
    ],
    "modules": [
      {
        "name": "ClassKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CLSContext"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CLSContext"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CLSContext"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.classkit/documentation/ClassKit/creating-bookmarks-and-assignments-from-your-app",
        "doc://com.apple.classkit/documentation/ClassKit/building-missing-contexts"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Make it easy for teachers to understand the app content a context represents by configuring it with information like a clear, concise title localized for the regions that your app supports.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A context can contain groups of other contexts, like a book that contains chapters or a chapter that contains sections. You can assemble contexts into a hierarchy of up to eight levels that acts as a table of contents for teachers who want to assign your app content. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/advertising-your-app-s-assignable-content",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for more details.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.classkit/documentation/ClassKit": {
      "abstract": [
        {
          "text": "Enable teachers to assign activities from your app’s content and to view student progress.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClassKit",
      "type": "topic",
      "url": "/documentation/classkit"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext": {
      "abstract": [
        {
          "text": "An area of your app that represents an assignable task, like a quiz or a chapter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSContext"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContext"
        }
      ],
      "role": "symbol",
      "title": "CLSContext",
      "type": "topic",
      "url": "/documentation/classkit/clscontext"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/addChildContext(_:)": {
      "abstract": [
        {
          "text": "Adds the specifed context as a child of the context receiving the method call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addChildContext"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLSContext",
          "text": "CLSContext"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/addChildContext(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addChildContext:"
        }
      ],
      "role": "symbol",
      "title": "addChildContext(_:)",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/addchildcontext(_:)"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/addNavigationChildContext(_:)": {
      "abstract": [
        {
          "text": "Adds a child context that users can navigate to from this context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addNavigationChildContext"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLSContext",
          "text": "CLSContext"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/addNavigationChildContext(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addNavigationChildContext:"
        }
      ],
      "role": "symbol",
      "title": "addNavigationChildContext(_:)",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/addnavigationchildcontext(_:)"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/addProgressReportingCapabilities(_:)": {
      "abstract": [
        {
          "text": "Adds a progress reporting capability to the set of capabilities for the context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addProgressReportingCapabilities"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLSProgressReportingCapability",
          "text": "CLSProgressReportingCapability"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/addProgressReportingCapabilities(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addProgressReportingCapabilities:"
        }
      ],
      "role": "symbol",
      "title": "addProgressReportingCapabilities(_:)",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/addprogressreportingcapabilities(_:)"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/becomeActive()": {
      "abstract": [
        {
          "text": "Tells a context to become the active context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "becomeActive"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/becomeActive()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "becomeActive"
        }
      ],
      "role": "symbol",
      "title": "becomeActive()",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/becomeactive()"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/createNewActivity()": {
      "abstract": [
        {
          "text": "Creates and returns a new activity instance for the context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "createNewActivity"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLSActivity",
          "text": "CLSActivity"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/createNewActivity()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "createNewActivity"
        }
      ],
      "role": "symbol",
      "title": "createNewActivity()",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/createnewactivity()"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/currentActivity": {
      "abstract": [
        {
          "text": "The activity available for recording progress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentActivity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLSActivity",
          "text": "CLSActivity"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/currentActivity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentActivity"
        }
      ],
      "role": "symbol",
      "title": "currentActivity",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/currentactivity"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/customTypeName": {
      "abstract": [
        {
          "text": "An optional name that the system presents to the user if you choose the custom context type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customTypeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/customTypeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "customTypeName"
        }
      ],
      "role": "symbol",
      "title": "customTypeName",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/customtypename"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/descendant(matchingIdentifierPath:completion:)": {
      "abstract": [
        {
          "text": "Finds the context with the given identifier path relative to this context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "descendant"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "matchingIdentifierPath"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLSContext",
          "text": "CLSContext"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/descendant(matchingIdentifierPath:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descendantMatchingIdentifierPath:completion:"
        }
      ],
      "role": "symbol",
      "title": "descendant(matchingIdentifierPath:completion:)",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/descendant(matchingidentifierpath:completion:)"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/displayOrder": {
      "abstract": [
        {
          "text": "The position of a context relative to its siblings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayOrder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/displayOrder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayOrder"
        }
      ],
      "role": "symbol",
      "title": "displayOrder",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/displayorder"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/identifier": {
      "abstract": [
        {
          "text": "A string that uniquely identifies a context among its siblings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/identifier"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/identifierPath": {
      "abstract": [
        {
          "text": "The identifier path that locates the context within the data store’s context hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifierPath"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/identifierPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifierPath"
        }
      ],
      "role": "symbol",
      "title": "identifierPath",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/identifierpath"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/init(type:identifier:title:)": {
      "abstract": [
        {
          "text": "Initializes a new context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLSContextType",
          "text": "CLSContextType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/init(type:identifier:title:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithType:identifier:title:"
        }
      ],
      "role": "symbol",
      "title": "init(type:identifier:title:)",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/init(type:identifier:title:)"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/isActive": {
      "abstract": [
        {
          "text": "A Boolean indicating whether the context is active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isActive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/isActive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "active"
        }
      ],
      "role": "symbol",
      "title": "isActive",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/isactive"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/isAssignable": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether teachers can assign the context as a task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAssignable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/isAssignable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "assignable"
        }
      ],
      "role": "symbol",
      "title": "isAssignable",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/isassignable"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/navigationChildContexts": {
      "abstract": [
        {
          "text": "The child contexts that a user can navigate to from this context in the Schoolwork app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "navigationChildContexts"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLSContext",
          "text": "CLSContext"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/navigationChildContexts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "navigationChildContexts"
        }
      ],
      "role": "symbol",
      "title": "navigationChildContexts",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/navigationchildcontexts"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/parent": {
      "abstract": [
        {
          "text": "The direct ancestor of this context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLSContext",
          "text": "CLSContext"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/parent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "parent"
        }
      ],
      "role": "symbol",
      "title": "parent",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/parent"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/progressReportingCapabilities": {
      "abstract": [
        {
          "text": "The kinds of progress reporting that the context can perform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "progressReportingCapabilities"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLSProgressReportingCapability",
          "text": "CLSProgressReportingCapability"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/progressReportingCapabilities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "progressReportingCapabilities"
        }
      ],
      "role": "symbol",
      "title": "progressReportingCapabilities",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/progressreportingcapabilities"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/removeFromParent()": {
      "abstract": [
        {
          "text": "Removes the context from its parent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeFromParent"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/removeFromParent()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeFromParent"
        }
      ],
      "role": "symbol",
      "title": "removeFromParent()",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/removefromparent()"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/removeNavigationChildContext(_:)": {
      "abstract": [
        {
          "text": "Removes the specified context as a presentable child of this context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeNavigationChildContext"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLSContext",
          "text": "CLSContext"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/removeNavigationChildContext(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeNavigationChildContext:"
        }
      ],
      "role": "symbol",
      "title": "removeNavigationChildContext(_:)",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/removenavigationchildcontext(_:)"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/resetProgressReportingCapabilities()": {
      "abstract": [
        {
          "text": "Resets the set of capabilities for the context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resetProgressReportingCapabilities"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/resetProgressReportingCapabilities()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resetProgressReportingCapabilities"
        }
      ],
      "role": "symbol",
      "title": "resetProgressReportingCapabilities()",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/resetprogressreportingcapabilities()"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/resignActive()": {
      "abstract": [
        {
          "text": "Tells a context to stop being the active context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resignActive"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/resignActive()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resignActive"
        }
      ],
      "role": "symbol",
      "title": "resignActive()",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/resignactive()"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/setType(_:)": {
      "abstract": [
        {
          "text": "Updates the kind of content that a context represents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLSContextType",
          "text": "CLSContextType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/setType(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setType:"
        }
      ],
      "role": "symbol",
      "title": "setType(_:)",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/settype(_:)"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/suggestedAge": {
      "abstract": [
        {
          "text": "The range of ages, measured in years, for which you deem a context’s content suitable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "suggestedAge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/suggestedAge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "suggestedAge"
        }
      ],
      "role": "symbol",
      "title": "suggestedAge",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/suggestedage"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/suggestedCompletionTime": {
      "abstract": [
        {
          "text": "A suggested time range to complete a task, measured in minutes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "suggestedCompletionTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/suggestedCompletionTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "suggestedCompletionTime"
        }
      ],
      "role": "symbol",
      "title": "suggestedCompletionTime",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/suggestedcompletiontime"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/summary": {
      "abstract": [
        {
          "text": "An optional, user-visible description of the context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "summary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/summary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "summary"
        }
      ],
      "role": "symbol",
      "title": "summary",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/summary"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/thumbnail": {
      "abstract": [
        {
          "text": "An optional thumbnail image associated with the context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thumbnail"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageRef",
          "text": "CGImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/thumbnail",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "thumbnail"
        }
      ],
      "role": "symbol",
      "title": "thumbnail",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/thumbnail"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/title": {
      "abstract": [
        {
          "text": "The name of the context as it appears to users.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/title"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/topic": {
      "abstract": [
        {
          "text": "The area of study to which a context relates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLSContextTopic",
          "text": "CLSContextTopic"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/topic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "topic"
        }
      ],
      "role": "symbol",
      "title": "topic",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/topic"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/type": {
      "abstract": [
        {
          "text": "The kind of content a context represents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLSContextType",
          "text": "CLSContextType"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/type"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/universalLinkURL": {
      "abstract": [
        {
          "text": "A URL that leads to the content in your app associated with the current context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "universalLinkURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/universalLinkURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "universalLinkURL"
        }
      ],
      "role": "symbol",
      "title": "universalLinkURL",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/universallinkurl"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextProvider": {
      "abstract": [
        {
          "text": "An interface used to tell your ClassKit context provider app extension to update contexts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSContextProvider"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextProvider"
        }
      ],
      "role": "symbol",
      "title": "CLSContextProvider",
      "type": "topic",
      "url": "/documentation/classkit/clscontextprovider"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic": {
      "abstract": [
        {
          "text": "The areas of study to which contexts may relate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSContextTopic"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTopic"
        }
      ],
      "role": "symbol",
      "title": "CLSContextTopic",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttopic"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextType": {
      "abstract": [
        {
          "text": "The kinds of assignable content a context can contain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSContextType"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextType"
        }
      ],
      "role": "symbol",
      "title": "CLSContextType",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttype"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSObject": {
      "abstract": [
        {
          "text": "The abstract base class for objects managed by ClassKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSObject"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSObject"
        }
      ],
      "role": "symbol",
      "title": "CLSObject",
      "type": "topic",
      "url": "/documentation/classkit/clsobject"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSProgressReportingCapability": {
      "abstract": [
        {
          "text": "A progress reporting capability supported by a context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSProgressReportingCapability"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSProgressReportingCapability",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSProgressReportingCapability"
        }
      ],
      "role": "symbol",
      "title": "CLSProgressReportingCapability",
      "type": "topic",
      "url": "/documentation/classkit/clsprogressreportingcapability"
    },
    "doc://com.apple.classkit/documentation/ClassKit/advertising-your-app-s-assignable-content": {
      "abstract": [
        {
          "text": "Assemble a hierarchy of contexts and declare your app’s assignable content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/advertising-your-app-s-assignable-content",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Advertising your app’s assignable content",
      "type": "topic",
      "url": "/documentation/classkit/advertising-your-app-s-assignable-content"
    },
    "doc://com.apple.classkit/documentation/ClassKit/building-missing-contexts": {
      "abstract": [
        {
          "text": "Create and initialize missing contexts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/building-missing-contexts",
      "kind": "article",
      "role": "article",
      "title": "Building missing contexts",
      "type": "topic",
      "url": "/documentation/classkit/building-missing-contexts"
    },
    "doc://com.apple.classkit/documentation/ClassKit/creating-bookmarks-and-assignments-from-your-app": {
      "abstract": [
        {
          "text": "Make it easier for teachers to find and assign your content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/creating-bookmarks-and-assignments-from-your-app",
      "kind": "article",
      "role": "article",
      "title": "Creating bookmarks and assignments from your app",
      "type": "topic",
      "url": "/documentation/classkit/creating-bookmarks-and-assignments-from-your-app"
    },
    "doc://com.apple.classkit/documentation/ClassKit/informing-classkit-that-a-task-is-about-to-begin": {
      "abstract": [
        {
          "text": "Activate and deactivate contexts according to user interaction.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/informing-classkit-that-a-task-is-about-to-begin",
      "kind": "article",
      "role": "article",
      "title": "Informing ClassKit that a task is about to begin",
      "type": "topic",
      "url": "/documentation/classkit/informing-classkit-that-a-task-is-about-to-begin"
    },
    "doc://com.apple.classkit/documentation/ClassKit/linking-directly-to-assignments": {
      "abstract": [
        {
          "text": "Make it easy for teachers to guide students to specific content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/linking-directly-to-assignments",
      "kind": "article",
      "role": "article",
      "title": "Linking directly to assignments",
      "type": "topic",
      "url": "/documentation/classkit/linking-directly-to-assignments"
    },
    "doc://com.apple.documentation/documentation/foundation/nsuseractivity/2866826-contextidentifierpath": {
      "abstract": [
        {
          "text": "The identifier path associated with a user activity generated by an app that adopts ClassKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "contextIdentifierPath"
        },
        {
          "kind": "text",
          "text": ": [String]?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsuseractivity/2866826-contextidentifierpath",
      "kind": "symbol",
      "role": "symbol",
      "title": "contextIdentifierPath",
      "type": "topic",
      "url": "/documentation/foundation/nsuseractivity/2866826-contextidentifierpath"
    },
    "doc://com.apple.documentation/documentation/foundation/nsuseractivity/2953056-isclasskitdeeplink": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether a user activity represents a ClassKit context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "isClassKitDeepLink"
        },
        {
          "kind": "text",
          "text": ": Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsuseractivity/2953056-isclasskitdeeplink",
      "kind": "symbol",
      "role": "symbol",
      "title": "isClassKitDeepLink",
      "type": "topic",
      "url": "/documentation/foundation/nsuseractivity/2953056-isclasskitdeeplink"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/CLSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Contexts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/advertising-your-app-s-assignable-content",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextProvider"
      ],
      "title": "Contexts"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-contexts",
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/init(type:identifier:title:)",
        "doc://com.apple.classkit/documentation/ClassKit/CLSObject"
      ],
      "title": "Creating contexts"
    },
    {
      "anchor": "Identifying-the-context",
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/identifier",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/title",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/summary",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/thumbnail"
      ],
      "title": "Identifying the context"
    },
    {
      "anchor": "Managing-the-context-type",
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/type",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/setType(_:)",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextType",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/customTypeName"
      ],
      "title": "Managing the context type"
    },
    {
      "anchor": "Characterizing-the-context",
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/suggestedAge",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/suggestedCompletionTime",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/isAssignable"
      ],
      "title": "Characterizing the context"
    },
    {
      "anchor": "Managing-context-presentation",
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/displayOrder",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/topic",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic"
      ],
      "title": "Managing context presentation"
    },
    {
      "anchor": "Indicating-progress-reporting-capabilities",
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/progressReportingCapabilities",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/addProgressReportingCapabilities(_:)",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/resetProgressReportingCapabilities()",
        "doc://com.apple.classkit/documentation/ClassKit/CLSProgressReportingCapability"
      ],
      "title": "Indicating progress reporting capabilities"
    },
    {
      "anchor": "Activating-and-deactivating-a-context",
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/informing-classkit-that-a-task-is-about-to-begin",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/becomeActive()",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/resignActive()",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/isActive"
      ],
      "title": "Activating and deactivating a context"
    },
    {
      "anchor": "Creating-activities",
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/currentActivity",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/createNewActivity()"
      ],
      "title": "Creating activities"
    },
    {
      "anchor": "Managing-context-hierarchy",
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/identifierPath",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/parent",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/removeFromParent()",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/addChildContext(_:)",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/descendant(matchingIdentifierPath:completion:)"
      ],
      "title": "Managing context hierarchy"
    },
    {
      "anchor": "Creating-a-context-presentation-hierarchy",
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/navigationChildContexts",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/addNavigationChildContext(_:)",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/removeNavigationChildContext(_:)"
      ],
      "title": "Creating a context presentation hierarchy"
    },
    {
      "anchor": "Configuring-deep-links",
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/linking-directly-to-assignments",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext/universalLinkURL",
        "doc://com.apple.documentation/documentation/foundation/nsuseractivity/2953056-isclasskitdeeplink",
        "doc://com.apple.documentation/documentation/foundation/nsuseractivity/2866826-contextidentifierpath"
      ],
      "title": "Configuring deep links"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CLSContext"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.classkit/documentation/ClassKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-contexts",
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/init(type:identifier:title:)",
                "doc://com.apple.classkit/documentation/ClassKit/CLSObject"
              ],
              "title": "Creating contexts"
            },
            {
              "anchor": "Identifying-the-context",
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/identifier",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/title",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/summary",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/thumbnail"
              ],
              "title": "Identifying the context"
            },
            {
              "anchor": "Managing-the-context-type",
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/type",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/setType(_:)",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextType",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/customTypeName"
              ],
              "title": "Managing the context type"
            },
            {
              "anchor": "Characterizing-the-context",
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/suggestedAge",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/suggestedCompletionTime",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/isAssignable"
              ],
              "title": "Characterizing the context"
            },
            {
              "anchor": "Managing-context-presentation",
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/displayOrder",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/topic",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic"
              ],
              "title": "Managing context presentation"
            },
            {
              "anchor": "Indicating-progress-reporting-capabilities",
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/progressReportingCapabilities",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/addProgressReportingCapabilities(_:)",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/resetProgressReportingCapabilities()",
                "doc://com.apple.classkit/documentation/ClassKit/CLSProgressReportingCapability"
              ],
              "title": "Indicating progress reporting capabilities"
            },
            {
              "anchor": "Activating-and-deactivating-a-context",
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/informing-classkit-that-a-task-is-about-to-begin",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/becomeActive()",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/resignActive()",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/isActive"
              ],
              "title": "Activating and deactivating a context"
            },
            {
              "anchor": "Creating-activities",
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/currentActivity",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/createNewActivity()"
              ],
              "title": "Creating activities"
            },
            {
              "anchor": "Managing-context-hierarchy",
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/identifierPath",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/parent",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/removeFromParent()",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/addChildContext(_:)",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/descendant(matchingIdentifierPath:completion:)"
              ],
              "title": "Managing context hierarchy"
            },
            {
              "anchor": "Creating-a-context-presentation-hierarchy",
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/navigationChildContexts",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/addNavigationChildContext(_:)",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/removeNavigationChildContext(_:)"
              ],
              "title": "Creating a context presentation hierarchy"
            },
            {
              "anchor": "Configuring-deep-links",
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/linking-directly-to-assignments",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext/universalLinkURL",
                "doc://com.apple.documentation/documentation/foundation/nsuseractivity/2953056-isclasskitdeeplink",
                "doc://com.apple.documentation/documentation/foundation/nsuseractivity/2866826-contextidentifierpath"
              ],
              "title": "Configuring deep links"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/CLSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Contexts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/advertising-your-app-s-assignable-content",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextProvider"
              ],
              "title": "Contexts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CLSContext"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CLSObject",
                    "text": "CLSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1addChildContext(_:)/title",
          "value": "addChildContext:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1addChildContext(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addChildContext:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1currentActivity/title",
          "value": "currentActivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1currentActivity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1removeNavigationChildContext(_:)/title",
          "value": "removeNavigationChildContext:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1removeNavigationChildContext(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeNavigationChildContext:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1removeFromParent()/title",
          "value": "removeFromParent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1removeFromParent()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeFromParent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1displayOrder/title",
          "value": "displayOrder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1displayOrder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displayOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1suggestedAge/title",
          "value": "suggestedAge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1suggestedAge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "suggestedAge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1navigationChildContexts/title",
          "value": "navigationChildContexts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1navigationChildContexts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "navigationChildContexts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSObject/title",
          "value": "CLSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1setType(_:)/title",
          "value": "setType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1setType(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1isAssignable/title",
          "value": "assignable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1isAssignable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "assignable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1title/title",
          "value": "title"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "title"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1becomeActive()/title",
          "value": "becomeActive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1becomeActive()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "becomeActive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext/title",
          "value": "CLSContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1progressReportingCapabilities/title",
          "value": "progressReportingCapabilities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1progressReportingCapabilities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "progressReportingCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1universalLinkURL/title",
          "value": "universalLinkURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1universalLinkURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "universalLinkURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1resignActive()/title",
          "value": "resignActive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1resignActive()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resignActive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1descendant(matchingIdentifierPath:completion:)/title",
          "value": "descendantMatchingIdentifierPath:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1descendant(matchingIdentifierPath:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "descendantMatchingIdentifierPath:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1addProgressReportingCapabilities(_:)/title",
          "value": "addProgressReportingCapabilities:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1addProgressReportingCapabilities(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addProgressReportingCapabilities:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1isActive/title",
          "value": "active"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1isActive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "active"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1addNavigationChildContext(_:)/title",
          "value": "addNavigationChildContext:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1addNavigationChildContext(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addNavigationChildContext:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1identifierPath/title",
          "value": "identifierPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1identifierPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifierPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic/title",
          "value": "CLSContextTopic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTopic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTopic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSProgressReportingCapability/title",
          "value": "CLSProgressReportingCapability"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSProgressReportingCapability/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSProgressReportingCapability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSProgressReportingCapability/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSProgressReportingCapability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1resetProgressReportingCapabilities()/title",
          "value": "resetProgressReportingCapabilities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1resetProgressReportingCapabilities()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resetProgressReportingCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1summary/title",
          "value": "summary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1summary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "summary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1identifier/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1createNewActivity()/title",
          "value": "createNewActivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1createNewActivity()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "createNewActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1suggestedCompletionTime/title",
          "value": "suggestedCompletionTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1suggestedCompletionTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "suggestedCompletionTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1thumbnail/title",
          "value": "thumbnail"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1thumbnail/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "thumbnail"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1init(type:identifier:title:)/title",
          "value": "initWithType:identifier:title:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1init(type:identifier:title:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithType:identifier:title:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextProvider/title",
          "value": "CLSContextProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType/title",
          "value": "CLSContextType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1parent/title",
          "value": "parent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1parent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "parent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1topic/title",
          "value": "topic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1topic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "topic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1customTypeName/title",
          "value": "customTypeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1customTypeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "customTypeName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/classkit/clscontext"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/classkit/clscontext"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
