{
  "abstract": [
    {
      "text": "Errors issued by ClassKit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.classkit/documentation/ClassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.classkit/documentation/ClassKit/CLSError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC12CLSErrorCodeLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CLSError"
      }
    ],
    "modules": [
      {
        "name": "ClassKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CLSError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CLSError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CLSError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.classkit/documentation/ClassKit": {
      "abstract": [
        {
          "text": "Enable teachers to assign activities from your app’s content and to view student progress.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClassKit",
      "type": "topic",
      "url": "/documentation/classkit"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSError": {
      "abstract": [
        {
          "text": "Errors issued by ClassKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSError"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSError"
        }
      ],
      "role": "symbol",
      "title": "CLSError",
      "type": "topic",
      "url": "/documentation/classkit/clserror"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code": {
      "abstract": [
        {
          "text": "Error codes that ClassKit issues.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CLSError.Code",
      "type": "topic",
      "url": "/documentation/classkit/clserror/code"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSError/authorizationDenied": {
      "abstract": [
        {
          "text": "The app isn’t authorized to perform the requested operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorizationDenied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12CLSErrorCodeLeV",
          "text": "CLSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSError/authorizationDenied",
      "kind": "symbol",
      "role": "symbol",
      "title": "authorizationDenied",
      "type": "topic",
      "url": "/documentation/classkit/clserror/authorizationdenied"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSError/classKitUnavailable": {
      "abstract": [
        {
          "text": "ClassKit isn’t available on this device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classKitUnavailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12CLSErrorCodeLeV",
          "text": "CLSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSError/classKitUnavailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "classKitUnavailable",
      "type": "topic",
      "url": "/documentation/classkit/clserror/classkitunavailable"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSError/databaseInaccessible": {
      "abstract": [
        {
          "text": "ClassKit isn’t accessible because the device is locked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "databaseInaccessible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12CLSErrorCodeLeV",
          "text": "CLSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSError/databaseInaccessible",
      "kind": "symbol",
      "role": "symbol",
      "title": "databaseInaccessible",
      "type": "topic",
      "url": "/documentation/classkit/clserror/databaseinaccessible"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSError/errorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSError/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/classkit/clserror/errordomain"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSError/invalidAccountCredentials": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidAccountCredentials"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12CLSErrorCodeLeV",
          "text": "CLSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSError/invalidAccountCredentials",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidAccountCredentials",
      "type": "topic",
      "url": "/documentation/classkit/clserror/invalidaccountcredentials"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSError/invalidArgument": {
      "abstract": [
        {
          "text": "An invalid argument was provided to the API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidArgument"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12CLSErrorCodeLeV",
          "text": "CLSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSError/invalidArgument",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidArgument",
      "type": "topic",
      "url": "/documentation/classkit/clserror/invalidargument"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSError/invalidCreate": {
      "abstract": [
        {
          "text": "An attempt to save a new object that already exists in the data store failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidCreate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12CLSErrorCodeLeV",
          "text": "CLSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSError/invalidCreate",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidCreate",
      "type": "topic",
      "url": "/documentation/classkit/clserror/invalidcreate"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSError/invalidModification": {
      "abstract": [
        {
          "text": "An attempt to modify a read-only object failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidModification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12CLSErrorCodeLeV",
          "text": "CLSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSError/invalidModification",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidModification",
      "type": "topic",
      "url": "/documentation/classkit/clserror/invalidmodification"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSError/invalidUpdate": {
      "abstract": [
        {
          "text": "ClassKit failed to save an updated object in the data store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidUpdate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12CLSErrorCodeLeV",
          "text": "CLSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSError/invalidUpdate",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidUpdate",
      "type": "topic",
      "url": "/documentation/classkit/clserror/invalidupdate"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSError/limits": {
      "abstract": [
        {
          "text": "A limit has been exceeded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "limits"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12CLSErrorCodeLeV",
          "text": "CLSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSError/limits",
      "kind": "symbol",
      "role": "symbol",
      "title": "limits",
      "type": "topic",
      "url": "/documentation/classkit/clserror/limits"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSError/none": {
      "abstract": [
        {
          "text": "No error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12CLSErrorCodeLeV",
          "text": "CLSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSError/none",
      "kind": "symbol",
      "role": "symbol",
      "title": "none",
      "type": "topic",
      "url": "/documentation/classkit/clserror/none"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSError/partialFailure": {
      "abstract": [
        {
          "text": "ClassKit encountered more than one error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "partialFailure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12CLSErrorCodeLeV",
          "text": "CLSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSError/partialFailure",
      "kind": "symbol",
      "role": "symbol",
      "title": "partialFailure",
      "type": "topic",
      "url": "/documentation/classkit/clserror/partialfailure"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSErrorCodeDomain": {
      "abstract": [
        {
          "text": "The error domain that ClassKit uses when issuing errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSErrorCodeDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSErrorCodeDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSErrorCodeDomain"
        }
      ],
      "role": "symbol",
      "title": "CLSErrorCodeDomain",
      "type": "topic",
      "url": "/documentation/classkit/clserrorcodedomain"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSErrorUserInfoKey": {
      "abstract": [
        {
          "text": "Keys that appear in the user info dictionary in errors that ClassKit creates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSErrorUserInfoKey"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSErrorUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSErrorUserInfoKey"
        }
      ],
      "role": "symbol",
      "title": "CLSErrorUserInfoKey",
      "type": "topic",
      "url": "/documentation/classkit/clserroruserinfokey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/CLSErrorCodeDomain",
        "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code",
        "doc://com.apple.classkit/documentation/ClassKit/CLSErrorUserInfoKey"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-Domain",
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/CLSErrorCodeDomain"
      ],
      "title": "Error Domain"
    },
    {
      "anchor": "Error-Codes",
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/CLSError/none",
        "doc://com.apple.classkit/documentation/ClassKit/CLSError/authorizationDenied",
        "doc://com.apple.classkit/documentation/ClassKit/CLSError/classKitUnavailable",
        "doc://com.apple.classkit/documentation/ClassKit/CLSError/databaseInaccessible",
        "doc://com.apple.classkit/documentation/ClassKit/CLSError/invalidAccountCredentials",
        "doc://com.apple.classkit/documentation/ClassKit/CLSError/invalidArgument",
        "doc://com.apple.classkit/documentation/ClassKit/CLSError/invalidCreate",
        "doc://com.apple.classkit/documentation/ClassKit/CLSError/invalidModification",
        "doc://com.apple.classkit/documentation/ClassKit/CLSError/invalidUpdate",
        "doc://com.apple.classkit/documentation/ClassKit/CLSError/limits",
        "doc://com.apple.classkit/documentation/ClassKit/CLSError/partialFailure",
        "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code"
      ],
      "title": "Error Codes"
    },
    {
      "anchor": "User-info",
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/CLSErrorUserInfoKey"
      ],
      "title": "User info"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/CLSError/errorDomain"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSErrorCodeDomain/title",
          "value": "CLSErrorCodeDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSErrorCodeDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSErrorCodeDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSError~1Code/title",
          "value": "CLSErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSErrorUserInfoKey/title",
          "value": "CLSErrorUserInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSErrorUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSErrorUserInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSErrorUserInfoKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSErrorUserInfoKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/classkit/clserror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
