{
  "abstract": [
    {
      "text": "Prepare your app and your development environment to adopt ClassKit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.classkit/documentation/ClassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.classkit/documentation/ClassKit/enabling-classkit-in-your-app"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "ClassKit"
      }
    ],
    "role": "collectionGroup",
    "title": "Enabling ClassKit in your app"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Adopting ClassKit allows your app to participate in a virtual classroom that spans many devices communicating through iCloud. To participate in this educational ecosystem, first enable the ClassKit capability. Then, to test your app’s interaction with this ecosystem, install Apple’s Schoolwork app on your development devices and simulate iCloud interaction by running in development mode.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Enable-the-ClassKit-Capability",
          "level": 3,
          "text": "Enable the ClassKit Capability",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To gain access to the virtual classroom environment, enable the ClassKit capability for your app in Xcode.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2977078",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When you enable the ClassKit capability, Xcode automatically adds the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.ClassKit-environment",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to your entitlements file. It also adds the corresponding feature to your App ID. See ",
              "type": "text"
            },
            {
              "identifier": "https://help.apple.com/xcode/mac/current/#/dev88ff319e7",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in Xcode help for more information about enabling capabilities.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Install-the-Schoolwork-app-on-your-devices",
          "level": 3,
          "text": "Install the Schoolwork app on your devices",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Schoolwork app provides the interface that teachers use to see what content your app offers, create assignments based on that content, and monitor student progress through those assignments. Students use the same app to receive assignments, and link directly to content in your app. Schoolwork provides both of these experiences by changing its behavior according to the role of the logged in user. For more information about user roles, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/about-classkit-and-user-roles",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To test your app’s ClassKit adoption, you install Schoolwork on your own development devices. This lets you validate the data your app sends to ClassKit. It also lets you experience what teachers and students see when they use your app in an educational environment.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To get Schoolwork, download it from the ",
              "type": "text"
            },
            {
              "identifier": "https://itunes.apple.com/us/app/schoolwork/id1355112526?ls=1&mt=8",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "You can’t test ClassKit behavior in Simulator because Schoolwork isn’t available in that environment.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Use-development-mode-to-test-locally",
          "level": 3,
          "text": "Use development mode to test locally",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you distribute your ClassKit enabled app through the App Store, it runs in ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "production mode",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ". In this mode, assigments made by teachers propagate to students’ devices, and progress returns to the teacher’s device through iCloud. But during development, you might not have access to a classroom full of managed devices. So you test in ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "development mode",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ", storing all data locally on a single device, switching between teacher and student roles as needed. Xcode automatically handles the mode selection for you, but you control the role (student or teacher) in development mode, as described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/testing-your-classkit-app-during-development",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.classkit/documentation/ClassKit": {
      "abstract": [
        {
          "text": "Enable teachers to assign activities from your app’s content and to view student progress.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClassKit",
      "type": "topic",
      "url": "/documentation/classkit"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore": {
      "abstract": [
        {
          "text": "A container for all the ClassKit data in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSDataStore"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSDataStore"
        }
      ],
      "role": "symbol",
      "title": "CLSDataStore",
      "type": "topic",
      "url": "/documentation/classkit/clsdatastore"
    },
    "doc://com.apple.classkit/documentation/ClassKit/about-classkit-and-user-roles": {
      "abstract": [
        {
          "text": "Understand how ClassKit interacts with different kinds of users.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/about-classkit-and-user-roles",
      "kind": "article",
      "role": "article",
      "title": "About ClassKit and user roles",
      "type": "topic",
      "url": "/documentation/classkit/about-classkit-and-user-roles"
    },
    "doc://com.apple.classkit/documentation/ClassKit/incorporating-classkit-into-an-educational-app": {
      "abstract": [
        {
          "text": "Walk through the process of setting up assignments and recording student progress.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/incorporating-classkit-into-an-educational-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Incorporating ClassKit into an Educational App",
      "type": "topic",
      "url": "/documentation/classkit/incorporating-classkit-into-an-educational-app"
    },
    "doc://com.apple.classkit/documentation/ClassKit/testing-your-classkit-app-during-development": {
      "abstract": [
        {
          "text": "Use development mode to test your app without a Managed Apple ID.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/testing-your-classkit-app-during-development",
      "kind": "article",
      "role": "article",
      "title": "Testing your ClassKit app during development",
      "type": "topic",
      "url": "/documentation/classkit/testing-your-classkit-app-during-development"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.ClassKit-environment": {
      "abstract": [
        {
          "text": "The ClassKit development or production environment for an education app that works with the Schoolwork app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.ClassKit-environment",
      "kind": "symbol",
      "role": "symbol",
      "title": "ClassKit Environment Entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.ClassKit-environment"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://help.apple.com/xcode/mac/current/#/dev88ff319e7": {
      "identifier": "https://help.apple.com/xcode/mac/current/#/dev88ff319e7",
      "title": "Add a Capability",
      "titleInlineContent": [
        {
          "text": "Add a Capability",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://help.apple.com/xcode/mac/current/#/dev88ff319e7"
    },
    "https://itunes.apple.com/us/app/schoolwork/id1355112526?ls=1&mt=8": {
      "identifier": "https://itunes.apple.com/us/app/schoolwork/id1355112526?ls=1&mt=8",
      "title": "App Store",
      "titleInlineContent": [
        {
          "text": "App Store",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://itunes.apple.com/us/app/schoolwork/id1355112526?ls=1&mt=8"
    },
    "media-2977078": {
      "alt": "Screenshot showing the ClassKit capability enabled in Xcode.",
      "identifier": "media-2977078",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/885993173db889f00c58ec1d7a60f602/media-2977078@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/8bee657f0c6718e9dd7520ec6c4cf8e1/media-2977078~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.ClassKit-environment",
        "doc://com.apple.classkit/documentation/ClassKit/incorporating-classkit-into-an-educational-app",
        "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore"
      ],
      "title": "Essentials"
    }
  ],
  "topicSections": [
    {
      "anchor": "Development-mode",
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/testing-your-classkit-app-during-development"
      ],
      "title": "Development mode"
    },
    {
      "anchor": "User-roles",
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/about-classkit-and-user-roles"
      ],
      "title": "User roles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Development-mode",
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/testing-your-classkit-app-during-development"
              ],
              "title": "Development mode"
            },
            {
              "anchor": "User-roles",
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/about-classkit-and-user-roles"
              ],
              "title": "User roles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.ClassKit-environment",
                "doc://com.apple.classkit/documentation/ClassKit/incorporating-classkit-into-an-educational-app",
                "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore"
              ],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSDataStore/title",
          "value": "CLSDataStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSDataStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSDataStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSDataStore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSDataStore"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/classkit/enabling-classkit-in-your-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/classkit/enabling-classkit-in-your-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
