{
  "abstract": [
    {
      "text": "Walk through the process of setting up assignments and recording student progress.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.classkit/documentation/ClassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.classkit/documentation/ClassKit/incorporating-classkit-into-an-educational-app"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "ClassKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "11.3",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "11.3",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "10.2",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Incorporating ClassKit into an Educational App"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You adopt ClassKit in an existing educational app to enable teachers to create assignments and monitor students’ progress through those assignments. This sample code project demonstrates ClassKit adoption in an app that lets users read plays.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Before starting, be sure to read ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/ClassKit/enabling-classkit-in-your-app",
              "isActive": true,
              "overridingTitle": "Enabling ClassKit in Your App",
              "overridingTitleInlineContent": [
                {
                  "text": "Enabling ClassKit in Your App",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": " to learn how to configure your environment to work with ClassKit, and ",
              "type": "text"
            },
            {
              "text": "Testing Your App During Development",
              "type": "text"
            },
            {
              "text": " to prepare to debug your ClassKit adoption.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Start-with-an-Existing-Educational-App",
          "level": 3,
          "text": "Start with an Existing Educational App",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The GreatPlays app provides a navigable hierarchy of plays, acts, and scenes, along with quizzes that test the reader’s comprehension. The app uses a simple data model that represents a collection of plays—the shared ",
              "type": "text"
            },
            {
              "code": "PlayLibrary",
              "type": "codeVoice"
            },
            {
              "text": " instance holds ",
              "type": "text"
            },
            {
              "code": "Play",
              "type": "codeVoice"
            },
            {
              "text": " instances, each of which contain an array of ",
              "type": "text"
            },
            {
              "code": "Act",
              "type": "codeVoice"
            },
            {
              "text": " instances, and so on. These all exist independent of ClassKit.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "ModelHierarchy.png",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For this example, the structure of a single play—Shakespeare’s ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "Hamlet",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": "—is added to the library at launch, from inside the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:didFinishLaunchingWithOptions:)",
              "isActive": true,
              "overridingTitle": "application(_:didFinishLaunchingWithOptions:)",
              "overridingTitleInlineContent": [
                {
                  "code": "application(_:didFinishLaunchingWithOptions:)",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "When writing an app for the educational market, consider supporting shared iPad, as described in ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/education/shared-ipad/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". This sample app does that by not using any persistent local storage and by setting the ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW45",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " key to ",
                  "type": "text"
                },
                {
                  "code": "YES",
                  "type": "codeVoice"
                },
                {
                  "text": " in its ",
                  "type": "text"
                },
                {
                  "code": "Info.plist",
                  "type": "codeVoice"
                },
                {
                  "text": " file.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "In a real app, in addition to the structure, you would also add the play’s text, along with quiz questions tailored to each scene. You might also support other plays, either distributed with the app, or downloaded later.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Define-Assignable-Content",
          "level": 3,
          "text": "Define Assignable Content",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Your first task in adopting ClassKit is to define your app’s assignable content. You represent a unit of assignable content to ClassKit as a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContext",
              "isActive": true,
              "overridingTitle": "CLSContext",
              "overridingTitleInlineContent": [
                {
                  "code": "CLSContext",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " instance, and then establish relationships between contexts by grouping them together into a hierarchy. For the play reader, teachers might want to assign a quiz, an individual scene, an act (with all its scenes), or even the whole play. So the existing model hierarchy provides a good template for a context hierarchy.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Because ClassKit layers on top of what your app already does, it’s often best to isolate ClassKit support into class extensions. This scheme avoids disrupting the app’s normal flow. The sample app therefore declares a ",
              "type": "text"
            },
            {
              "code": "Node",
              "type": "codeVoice"
            },
            {
              "text": " protocol that model objects can adopt in an extension to readily associate with a related context:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "protocol Node {",
            "    var parent: Node? { get }",
            "    var children: [Node]? { get }",
            "    var identifier: String { get }",
            "    var contextType: CLSContextType { get }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "In adopting this protocol, a model object discloses its immediate ancestor and descendants, a unique identifier, and a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContextType",
              "isActive": true,
              "overridingTitle": "CLSContextType",
              "overridingTitleInlineContent": [
                {
                  "code": "CLSContextType",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " value that indicates what kind of content it contains. For example, the ",
              "type": "text"
            },
            {
              "code": "Node",
              "type": "codeVoice"
            },
            {
              "text": " extension to ",
              "type": "text"
            },
            {
              "code": "Act",
              "type": "codeVoice"
            },
            {
              "text": ", shown below, defines its ",
              "type": "text"
            },
            {
              "code": "parent",
              "type": "codeVoice"
            },
            {
              "text": " as the ",
              "type": "text"
            },
            {
              "code": "play",
              "type": "codeVoice"
            },
            {
              "text": " that contains it, and its ",
              "type": "text"
            },
            {
              "code": "children",
              "type": "codeVoice"
            },
            {
              "text": " as the ",
              "type": "text"
            },
            {
              "code": "scenes",
              "type": "codeVoice"
            },
            {
              "text": " it contains. It provides an identifier that is unique to the act, and a context type of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContextType/chapter",
              "isActive": true,
              "overridingTitle": "chapter",
              "overridingTitleInlineContent": [
                {
                  "text": "chapter",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": ", which is a reasonable approximation of the role of an act within a play.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "extension Act: Node {",
            "    var parent: Node? {",
            "        return play",
            "    }",
            "    ",
            "    var children: [Node]? {",
            "        return scenes",
            "    }",
            "    ",
            "    var identifier: String {",
            "        return \"Act \\(number)\"",
            "    }",
            "    ",
            "    var contextType: CLSContextType {",
            "        return .chapter",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Further, an extension to the ",
              "type": "text"
            },
            {
              "code": "Node",
              "type": "codeVoice"
            },
            {
              "text": " protocol provides default behavior to all model objects for handling identifiers. In particular, a model object that adopts the protocol gains the ability to report its own identifier path (a collection of ",
              "type": "text"
            },
            {
              "code": "identifier",
              "type": "codeVoice"
            },
            {
              "text": " strings that trace through the hierarchy from one node to another), and to find a descendant node from an identifier path:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "extension Node {",
            "    var identifierPath: [String] {",
            "        var pathComponents: [String] = [identifier]",
            "        ",
            "        if let parent = self.parent {",
            "            pathComponents = parent.identifierPath + pathComponents",
            "        }",
            "        ",
            "        return pathComponents",
            "    }",
            "    ",
            "    /// Finds a node in the play list hierarchy by its identifier path.",
            "    func descendant(matching identifierPath: [String]) -> Node? {",
            "        if let identifier = identifierPath.first {",
            "            if let child = children?.first(where: { $0.identifier == identifier }) {",
            "                return child.descendant(matching: Array(identifierPath.suffix(identifierPath.count - 1)))",
            "            } else {",
            "                return nil",
            "            }",
            "        } else {",
            "            return self",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Advertise-Your-Content-to-Teachers",
          "level": 3,
          "text": "Advertise Your Content to Teachers",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Contexts are the mechanism by which your app advertises its assignable content to teachers. Contexts you tell ClassKit about appear as tasks in Apple’s Schoolwork app, where teachers go to create assignments based on your content. So it’s important to declare contexts as soon (and as atomically) as possible. Otherwise teachers won’t see your app’s content in Schoolwork, or might only see a partial list of tasks.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You deal with this by declaring the context hierarchy for static content at application launch, or immediately after you download dynamic content. In the play reader app, you do this by making context declaration an integral step of building a new play instance in the ",
              "type": "text"
            },
            {
              "code": "addPlay",
              "type": "codeVoice"
            },
            {
              "text": " method:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func addPlay(_ play: Play, creatingContexts: Bool = true) {",
            "    if !plays.contains(where: { $0.title == play.title }) {",
            "        plays.append(play)",
            "",
            "        // Give ClassKit a chance to set up its contexts.",
            "        if creatingContexts {",
            "            setupContext(play: play)",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "You declare an entire play context hierarchy by asking the data store for all the leaf nodes, which implicitly also declares all of the contexts that are ancestors of the leaf nodes:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func setupContext(play: Play) {",
            "    for act in play.acts {",
            "        for scene in act.scenes {",
            "            ",
            "            // Get the deepest path: the quiz if there is one, or the scene if not.",
            "            let path = scene.quiz?.identifierPath ?? scene.identifierPath",
            "            ",
            "            // Asking for a context causes it (and its ancestors) to be built, as needed.",
            "            CLSDataStore.shared.mainAppContext.descendant(matchingIdentifierPath: path) { _, _ in }",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Because you’re only declaring the contexts at this point, you don’t need to do anything with the returned values.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Build-Contexts-on-Demand",
          "level": 3,
          "text": "Build Contexts on Demand",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Any time you ask the data store (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSDataStore",
              "isActive": true,
              "overridingTitle": "CLSDataStore",
              "overridingTitleInlineContent": [
                {
                  "code": "CLSDataStore",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": ") for a context, whether during declaration or because you want to activate the context, the data store first looks in its database of stored contexts. If the context is available there, perhaps from a previous launch of your app, the data store returns that. But if it’s not available, the data store asks its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSDataStore/delegate",
              "isActive": true,
              "overridingTitle": "delegate",
              "overridingTitleInlineContent": [
                {
                  "code": "delegate",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " to build the context.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "By defining contexts that parallel your model hierarchy, you facilitate the building of new contexts. In your implementation of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSDataStoreDelegate",
              "isActive": true,
              "overridingTitle": "CLSDataStoreDelegate",
              "overridingTitleInlineContent": [
                {
                  "code": "CLSDataStoreDelegate",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " protocol’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSDataStoreDelegate/createContext(forIdentifier:parentContext:parentIdentifierPath:)",
              "isActive": true,
              "overridingTitle": "createContext(forIdentifier:parentContext:parentIdentifierPath:)",
              "overridingTitleInlineContent": [
                {
                  "code": "createContext(forIdentifier:parentContext:parentIdentifierPath:)",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " method, you can use characteristics of your model objects to inform context creation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In the play reader, the shared instance of the ",
              "type": "text"
            },
            {
              "code": "PlayLibrary",
              "type": "codeVoice"
            },
            {
              "text": " class takes the role of delegate, again using an extension. Its ",
              "type": "text"
            },
            {
              "code": "ClassKit",
              "type": "codeVoice"
            },
            {
              "text": " extension includes the ",
              "type": "text"
            },
            {
              "code": "setupClassKit()",
              "type": "codeVoice"
            },
            {
              "text": " method that assigns itself as the delegate:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func setupClassKit() {",
            "    CLSDataStore.shared.delegate = self",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The extension also implements the delegate callback, relying on each model object’s ",
              "type": "text"
            },
            {
              "code": "Node",
              "type": "codeVoice"
            },
            {
              "text": " extension to provide data needed for context creation:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func createContext(forIdentifier identifier: String, parentContext: CLSContext, parentIdentifierPath: [String]) -> CLSContext? {",
            "    ",
            "    // Find a node in the model hierarchy based on the identifier path.",
            "    let identifierPath = parentIdentifierPath + [identifier]",
            "",
            "    guard let playIdentifier = identifierPath.first,",
            "        let play = PlayLibrary.shared.plays.first(where: { $0.identifier == playIdentifier }),",
            "        let node = play.descendant(matching: Array(identifierPath.suffix(identifierPath.count - 1))) else {",
            "        return nil",
            "    }",
            "    ",
            "    // Use the node to create and customize a context.",
            "    let context = CLSContext(type: node.contextType, identifier: identifier, title: node.identifier)",
            "    context.topic = .literacyAndWriting",
            "",
            "    // Users of 11.3 rely on a user activity instead.",
            "    if #available(iOS 11.4, *),",
            "        let path = identifierPath.joined(separator: \"/\").addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) {",
            "",
            "        // Use custom URLs to locate activities.",
            "        //  Comment this assignment to rely on a user activity for all users.",
            "        context.universalLinkURL = URL(string: \"greatplays://\" + path)",
            "    }",
            "",
            "    // No need to save: the framework handles that automatically.",
            "    os_log(\"%s Built\", node.identifierPath.description)",
            "    return context",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Build-Contexts-from-an-App-Extension",
          "level": 3,
          "text": "Build Contexts from an App Extension",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The app includes a ClassKit context provider app extension by defining a target called ",
              "type": "text"
            },
            {
              "code": "ClassKitContextProvider",
              "type": "codeVoice"
            },
            {
              "text": ". A ClassKit extension’s primary class conforms to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContextProvider",
              "isActive": true,
              "overridingTitle": "CLSContextProvider",
              "overridingTitleInlineContent": [
                {
                  "code": "CLSContextProvider",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " protocol. Schoolwork calls this protocol’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContextProvider/updateDescendants(of:completion:)",
              "isActive": true,
              "overridingTitle": "updateDescendants",
              "overridingTitleInlineContent": [
                {
                  "code": "updateDescendants",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " method to create or update the children of a given context as the teacher browses assignable content. This enables Schoolwork to advertise the most up-to-date version of an app’s assignable content, even before the teacher runs the main app for the first time.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Using the identifier path of the passed-in context, the update method finds the corresponding node in the data model, and then finds the children of that node:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Start with plays as child nodes. Then look for a descendant.",
            "var childNodes: [Node] = PlayLibrary.shared.plays",
            "",
            "if let identifier = identifierPath.first,",
            "    let play = PlayLibrary.shared.plays.first(where: { $0.identifier == identifier }),",
            "    let node = play.descendant(matching: Array(identifierPath.suffix(identifierPath.count - 1))) {",
            "",
            "    childNodes = node.children ?? []",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The update method then finds existing child contexts at the same hierarchical level as the node, and creates any that are missing:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let predicate = NSPredicate(format: \"%K = %@\",",
            "                            CLSPredicateKeyPath.parent as CVarArg,",
            "                            context)",
            "CLSDataStore.shared.contexts(matching: predicate) { childContexts, _ in",
            "    for childNode in childNodes {",
            "        if !childContexts.contains(where: { $0.identifier == childNode.identifier }),",
            "            let childContext = PlayLibrary.shared.createContext(forIdentifier: childNode.identifier,",
            "                                                                parentContext: context,",
            "                                                                parentIdentifierPath: identifierPath) {",
            "            context.addChildContext(childContext)",
            "        }",
            "    }"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "In this app, contexts never change, so the loop moves to the next iteration without taking any action when it finds an existing context. If your app has contexts that can change, use this opportunity to reconfigure the context. Either way, after finishing the loop, save the updates and call the completion handler:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "    CLSDataStore.shared.save { error in",
            "        if let error = error {",
            "            os_log(\"Save error: %s\", error.localizedDescription)",
            "        } else {",
            "            os_log(\"Saved\")",
            "        }",
            "        completion(error)",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Record-Progress-with-Activities",
          "level": 3,
          "text": "Record Progress with Activities",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "While contexts declare the structure of your app, you use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSActivity",
              "isActive": true,
              "overridingTitle": "CLSActivity",
              "overridingTitleInlineContent": [
                {
                  "code": "CLSActivity",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " instances to report progress through those contexts. For example, for a context representing a scene, the corresponding activity reports how much of the scene the student has read and how long they took to read it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In addition to the identifier extension, the sample app includes another extension to ",
              "type": "text"
            },
            {
              "code": "Node",
              "type": "codeVoice"
            },
            {
              "text": " that provides default behavior for working with ClassKit activities. Model objects use their own identifier path to locate the matching context, and then use the context to manage activities. For example, the ",
              "type": "text"
            },
            {
              "code": "startActivity()",
              "type": "codeVoice"
            },
            {
              "text": " method defined in the extension begins an activity:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func startActivity(asNew: Bool = false) {",
            "    os_log(\"%s Start\", identifierPath.description)",
            "",
            "    CLSDataStore.shared.mainAppContext.descendant(matchingIdentifierPath: identifierPath) { context, _ in",
            "",
            "        // Activate the context.",
            "        context?.becomeActive()",
            "",
            "        if asNew == false,",
            "            let activity = context?.currentActivity {",
            "            ",
            "            // Re-start the existing activity",
            "            activity.start()",
            "            ",
            "        } else {",
            "            // Create and start an activity.",
            "            context?.createNewActivity().start()",
            "        }",
            "        ",
            "        CLSDataStore.shared.save { error in",
            "            guard error == nil else {",
            "                os_log(\"%s Start save error: %s\", self.identifierPath.description, error!.localizedDescription)",
            "                return",
            "            }",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "code": "Node",
              "type": "codeVoice"
            },
            {
              "text": " also defines methods for reporting progress as a fraction of task completion and ending an activity. Notice that all these methods retrieve the context every time, rather than storing a reference to it. It’s important to do this, because the underlying instance could change between calls as a result of network synchronization.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Start-Recording-When-the-User-Begins-an-Activity",
          "level": 3,
          "text": "Start Recording When the User Begins an Activity",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You typically call methods to record activity from your view controllers. Consider an assignment to read a particular scene. The scene’s view controller knows when the scene appears on screen and has a handle on the scene instance. So the controller is in the best position to tell the scene to begin recording an activity from its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIViewController/viewDidAppear(_:)",
              "isActive": true,
              "overridingTitle": "viewDidAppear(_:)",
              "overridingTitleInlineContent": [
                {
                  "code": "viewDidAppear(_:)",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " method:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "override func viewDidAppear(_ animated: Bool) {",
            "    super.viewDidAppear(animated)",
            "",
            "    scene?.startActivity()",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Notice that when the student starts to read a scene, the controller doesn’t set the ",
              "type": "text"
            },
            {
              "code": "startActivity()",
              "type": "codeVoice"
            },
            {
              "text": " method’s ",
              "type": "text"
            },
            {
              "code": "asNew",
              "type": "codeVoice"
            },
            {
              "text": " parameter, leaving it to have the default value of ",
              "type": "text"
            },
            {
              "code": "false",
              "type": "codeVoice"
            },
            {
              "text": ". As a result, a previously stopped activity, if available, is resumed. This allows the user to begin reading a scene, then navigate elsewhere in the app (for example to review an earlier scene) without finalizing the current attempt. When the user returns, progress and duration pick up from where the user left off.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In contrast, the ",
              "type": "text"
            },
            {
              "code": "startQuiz()",
              "type": "codeVoice"
            },
            {
              "text": " method does set the ",
              "type": "text"
            },
            {
              "code": "startActivity()",
              "type": "codeVoice"
            },
            {
              "text": " method’s ",
              "type": "text"
            },
            {
              "code": "asNew",
              "type": "codeVoice"
            },
            {
              "text": " parameter to ",
              "type": "text"
            },
            {
              "code": "true",
              "type": "codeVoice"
            },
            {
              "text": ". Quizzes, once started, must be finished before the user can move to another task. So the app treats each new attempt as a new activity.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func start() {",
            "    startActivity(asNew: true)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "How you handle this for a particular activity depends on the characteristics of the tasks you define.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Add-Progress-When-the-User-Scrolls",
          "level": 3,
          "text": "Add Progress When the User Scrolls",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "While the scene view controller (which manages a scroll view) is visible, it uses its knowledge of the content offset as an indication of how far through the scene the student has read. For each scroll view delegate update, the controller reports a new progress value to the scene by measuring scroll position as a proxy for how much the student has read:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func scrollViewDidScroll(_ scrollView: UIScrollView) {",
            "    let position = sceneText.contentOffset.y + sceneText.frame.size.height",
            "    let total = sceneText.contentSize.height",
            "    ",
            "    // The scroll view can bounce, so use care to bound the progress.",
            "    let progress = Double(max(0, min(1, position / total)))",
            "    ",
            "    scene?.update(progress: progress)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Stop-Recording-When-the-User-Stops-an-Activity",
          "level": 3,
          "text": "Stop Recording When the User Stops an Activity",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The controller informs the scene when the activity is over in its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIViewController/viewWillDisappear(_:)",
              "isActive": true,
              "overridingTitle": "viewWillDisappear(_:)",
              "overridingTitleInlineContent": [
                {
                  "code": "viewWillDisappear(_:)",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " method:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "override func viewWillDisappear(_ animated: Bool) {",
            "    super.viewWillDisappear(animated)",
            "",
            "    scene?.stopActivity()",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Report-Additional-Metrics-with-Activity-Items",
          "level": 3,
          "text": "Report Additional Metrics with Activity Items",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Activities report duration and progress automatically. But sometimes you want to provide additional metrics about an activity. For example, you might want to report a quiz score, or record how many times a hint was used in solving a problem. For this, you use activity items.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In GreatPlays, the ",
              "type": "text"
            },
            {
              "code": "Node",
              "type": "codeVoice"
            },
            {
              "text": " protocol extension provides the ",
              "type": "text"
            },
            {
              "code": "addScore()",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "addQuantity()",
              "type": "codeVoice"
            },
            {
              "text": " methods for this purpose. These are called when the user completes the quiz, but before ending the activity, to report the quiz results:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func record() {",
            "    // The score is the primary metric for a quiz.",
            "    addScore(score, title: \"Score\", primary: true)",
            "    addQuantity(Double(hints), title: \"Hints\")",
            "    markAsDone()",
            "    stopActivity()",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Mark-an-Activity-as-Done",
          "level": 3,
          "text": "Mark an Activity as Done",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "While recording the quiz score, the app also calls the ",
              "type": "text"
            },
            {
              "code": "markAsDone()",
              "type": "codeVoice"
            },
            {
              "text": " method, as shown in the previous section, which in turn calls the data store’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSDataStore/completeAllAssignedActivities(matching:)",
              "isActive": true,
              "overridingTitle": "completeAllAssignedActivities(matching:)",
              "overridingTitleInlineContent": [
                {
                  "code": "completeAllAssignedActivities(matching:)",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " method to indicate that the student has finalized the attempt.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func markAsDone() {",
            "    if #available(iOS 12.2, *) {",
            "        os_log(\"%s Done\", identifierPath.description)",
            "        CLSDataStore.shared.completeAllAssignedActivities(matching: identifierPath)",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The student can’t go back and change anything after reaching the end of the quiz, so the app can safely mark the activity as done. In contrast, reading a scene has no easily detected end point, and so the app doesn’t make a call to the completion method in that case. Instead, the student decides when to mark the activity complete in Schoolwork.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Designate-a-Primary-Activity-Item",
          "level": 3,
          "text": "Designate a Primary Activity Item",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you add activity items, you can choose to make one of them the primary item. The primary gets a more prominent role in summarized results that teachers see. In the play reader example, for a quiz, the score is considered the primary item, as shown above. Alternatively, you can choose not to set any activity item as the primary, in which case progress becomes the most prominent result displayed to teachers. The ",
              "type": "text"
            },
            {
              "code": "addScore()",
              "type": "codeVoice"
            },
            {
              "text": " method demonstrates the two ways in which you can register an activity item, either as primary or not:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "if primary {",
            "    activity.primaryActivityItem = item",
            "} else {",
            "    activity.addAdditionalActivityItem(item)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "If you do decide to set a primary item, make sure you always set the same kind of primary item for a given activity. For example, once you register the score item as the primary for a quiz activity, you must always use score this way. Making the hint quantity the primary at a later time generates an error.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "ModelHierarchy.png": {
      "alt": "Diagram showing how model objects appear in a tree structure.",
      "identifier": "ModelHierarchy.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/af312c8ad42197179f5754d8578924d8/ModelHierarchy@2x.png"
        }
      ]
    },
    "doc://com.apple.classkit/documentation/ClassKit": {
      "abstract": [
        {
          "text": "Enable teachers to assign activities from your app’s content and to view student progress.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClassKit",
      "type": "topic",
      "url": "/documentation/classkit"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore": {
      "abstract": [
        {
          "text": "A container for all the ClassKit data in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSDataStore"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSDataStore"
        }
      ],
      "role": "symbol",
      "title": "CLSDataStore",
      "type": "topic",
      "url": "/documentation/classkit/clsdatastore"
    },
    "doc://com.apple.classkit/documentation/ClassKit/enabling-classkit-in-your-app": {
      "abstract": [
        {
          "text": "Prepare your app and your development environment to adopt ClassKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/enabling-classkit-in-your-app",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Enabling ClassKit in your app",
      "type": "topic",
      "url": "/documentation/classkit/enabling-classkit-in-your-app"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.ClassKit-environment": {
      "abstract": [
        {
          "text": "The ClassKit development or production environment for an education app that works with the Schoolwork app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.ClassKit-environment",
      "kind": "symbol",
      "role": "symbol",
      "title": "ClassKit Environment Entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.ClassKit-environment"
    },
    "doc://com.apple.documentation/documentation/ClassKit/CLSActivity": {
      "abstract": [
        {
          "text": "A representation of user interaction with a context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSActivity"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSActivity",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLSActivity",
      "type": "topic",
      "url": "/documentation/ClassKit/CLSActivity"
    },
    "doc://com.apple.documentation/documentation/ClassKit/CLSContext": {
      "abstract": [
        {
          "text": "An area of your app that represents an assignable task, like a quiz or a chapter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSContext"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContext",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLSContext",
      "type": "topic",
      "url": "/documentation/ClassKit/CLSContext"
    },
    "doc://com.apple.documentation/documentation/ClassKit/CLSContextProvider": {
      "abstract": [
        {
          "text": "An interface used to tell your ClassKit context provider app extension to update contexts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSContextProvider"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContextProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLSContextProvider",
      "type": "topic",
      "url": "/documentation/ClassKit/CLSContextProvider"
    },
    "doc://com.apple.documentation/documentation/ClassKit/CLSContextProvider/updateDescendants(of:completion:)": {
      "abstract": [
        {
          "text": "Updates the descendants of the given context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateDescendants"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "context"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLSContext",
          "text": "CLSContext"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "@escaping"
        },
        {
          "kind": "text",
          "text": " ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContextProvider/updateDescendants(of:completion:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "updateDescendants(of:completion:)",
      "type": "topic",
      "url": "/documentation/ClassKit/CLSContextProvider/updateDescendants(of:completion:)"
    },
    "doc://com.apple.documentation/documentation/ClassKit/CLSContextType": {
      "abstract": [
        {
          "text": "The kinds of assignable content a context can contain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSContextType"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContextType",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLSContextType",
      "type": "topic",
      "url": "/documentation/ClassKit/CLSContextType"
    },
    "doc://com.apple.documentation/documentation/ClassKit/CLSContextType/chapter": {
      "abstract": [
        {
          "text": "A chapter context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "chapter"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContextType/chapter",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLSContextType.chapter",
      "type": "topic",
      "url": "/documentation/ClassKit/CLSContextType/chapter"
    },
    "doc://com.apple.documentation/documentation/ClassKit/CLSDataStore": {
      "abstract": [
        {
          "text": "A container for all the ClassKit data in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSDataStore"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSDataStore",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLSDataStore",
      "type": "topic",
      "url": "/documentation/ClassKit/CLSDataStore"
    },
    "doc://com.apple.documentation/documentation/ClassKit/CLSDataStore/completeAllAssignedActivities(matching:)": {
      "abstract": [
        {
          "text": "Marks all of the assigned and active activities for the given context path as complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "completeAllAssignedActivities"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "matching"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "contextPath"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSDataStore/completeAllAssignedActivities(matching:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "completeAllAssignedActivities(matching:)",
      "type": "topic",
      "url": "/documentation/ClassKit/CLSDataStore/completeAllAssignedActivities(matching:)"
    },
    "doc://com.apple.documentation/documentation/ClassKit/CLSDataStore/delegate": {
      "abstract": [
        {
          "text": "The data store delegate instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "weak"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)CLSDataStoreDelegate",
          "text": "CLSDataStoreDelegate"
        },
        {
          "kind": "text",
          "text": ")? { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSDataStore/delegate",
      "kind": "symbol",
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/ClassKit/CLSDataStore/delegate"
    },
    "doc://com.apple.documentation/documentation/ClassKit/CLSDataStoreDelegate": {
      "abstract": [
        {
          "text": "An interface the data store uses to request new contexts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSDataStoreDelegate"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSDataStoreDelegate",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLSDataStoreDelegate",
      "type": "topic",
      "url": "/documentation/ClassKit/CLSDataStoreDelegate"
    },
    "doc://com.apple.documentation/documentation/ClassKit/CLSDataStoreDelegate/createContext(forIdentifier:parentContext:parentIdentifierPath:)": {
      "abstract": [
        {
          "text": "Asks the delegate for a new context with the given identifier for the given parent context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "createContext"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forIdentifier"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "parentContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLSContext",
          "text": "CLSContext"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "parentIdentifierPath"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLSContext",
          "text": "CLSContext"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSDataStoreDelegate/createContext(forIdentifier:parentContext:parentIdentifierPath:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "createContext(forIdentifier:parentContext:parentIdentifierPath:)",
      "type": "topic",
      "url": "/documentation/ClassKit/CLSDataStoreDelegate/createContext(forIdentifier:parentContext:parentIdentifierPath:)"
    },
    "doc://com.apple.documentation/documentation/ClassKit/enabling-classkit-in-your-app": {
      "abstract": [
        {
          "text": "Prepare your app and your development environment to adopt ClassKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ClassKit/enabling-classkit-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Enabling ClassKit in your app",
      "type": "topic",
      "url": "/documentation/ClassKit/enabling-classkit-in-your-app"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:didFinishLaunchingWithOptions:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the launch process is almost done and the app is almost ready to run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "application"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "application"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFinishLaunchingWithOptions"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "launchOptions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIApplicationLaunchOptionsKey",
          "text": "LaunchOptionsKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]? = nil) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:didFinishLaunchingWithOptions:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "application(_:didFinishLaunchingWithOptions:)",
      "type": "topic",
      "url": "/documentation/UIKit/UIApplicationDelegate/application(_:didFinishLaunchingWithOptions:)"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIViewController/viewDidAppear(_:)": {
      "abstract": [
        {
          "text": "Notifies the view controller that its view was added to a view hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewDidAppear"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIViewController/viewDidAppear(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "viewDidAppear(_:)",
      "type": "topic",
      "url": "/documentation/UIKit/UIViewController/viewDidAppear(_:)"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIViewController/viewWillDisappear(_:)": {
      "abstract": [
        {
          "text": "Notifies the view controller that its view is about to be removed from a view hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewWillDisappear"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIViewController/viewWillDisappear(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "viewWillDisappear(_:)",
      "type": "topic",
      "url": "/documentation/UIKit/UIViewController/viewWillDisappear(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "e9fc53147345/IncorporatingClassKitIntoAnEducationalApp.zip": {
      "checksum": "e9fc5314734562df2c4c81b349e47ee8c93599b96b4ebd8dd4810f400917f412e68c3c64db562994bb18e28ac82a4b2f30e5a175bc40116b5b0a65603163663f",
      "identifier": "e9fc53147345/IncorporatingClassKitIntoAnEducationalApp.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/e9fc53147345/IncorporatingClassKitIntoAnEducationalApp.zip"
    },
    "https://developer.apple.com/education/shared-ipad/": {
      "identifier": "https://developer.apple.com/education/shared-ipad/",
      "title": "Optimizing Apps for Shared iPad",
      "titleInlineContent": [
        {
          "text": "Optimizing Apps for Shared iPad",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/education/shared-ipad/"
    },
    "https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW45": {
      "identifier": "https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW45",
      "title": "NSSupportsPurgeableLocalStorage",
      "titleInlineContent": [
        {
          "code": "NSSupportsPurgeableLocalStorage",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW45"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "e9fc53147345/IncorporatingClassKitIntoAnEducationalApp.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/enabling-classkit-in-your-app",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.ClassKit-environment",
        "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore"
      ],
      "title": "Essentials"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/enabling-classkit-in-your-app",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.ClassKit-environment",
                "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore"
              ],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ClassKit~1CLSContext/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CLSContext"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CLSObject",
              "text": "CLSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ClassKit~1CLSContextProvider/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CLSContextProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ClassKit~1CLSContextType~1chapter/title",
          "value": "CLSContextTypeChapter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ClassKit~1CLSContextType~1chapter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTypeChapter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ClassKit~1CLSDataStore/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CLSDataStore"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ClassKit~1CLSContextType/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CLSContextType"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ClassKit~1CLSDataStore~1completeAllAssignedActivities(matching:)/title",
          "value": "completeAllAssignedActivitiesMatching:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ClassKit~1CLSDataStore~1completeAllAssignedActivities(matching:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "completeAllAssignedActivitiesMatching:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<NSString *>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "contextPath"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIViewController~1viewDidAppear(_:)/title",
          "value": "viewDidAppear:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIViewController~1viewDidAppear(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "viewDidAppear:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "animated"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIViewController~1viewWillDisappear(_:)/title",
          "value": "viewWillDisappear:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIViewController~1viewWillDisappear(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "viewWillDisappear:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "animated"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didFinishLaunchingWithOptions:)/title",
          "value": "application:didFinishLaunchingWithOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didFinishLaunchingWithOptions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "application:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIApplication",
              "text": "UIApplication"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "application"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "didFinishLaunchingWithOptions:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSDictionary",
              "text": "NSDictionary<NSString *,id>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "launchOptions"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ClassKit~1CLSActivity/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CLSActivity"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CLSObject",
              "text": "CLSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ClassKit~1CLSDataStoreDelegate~1createContext(forIdentifier:parentContext:parentIdentifierPath:)/title",
          "value": "createContextForIdentifier:parentContext:parentIdentifierPath:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ClassKit~1CLSDataStoreDelegate~1createContext(forIdentifier:parentContext:parentIdentifierPath:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CLSContext",
              "text": "CLSContext"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "identifier",
              "text": "createContextForIdentifier:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "identifier"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "parentContext:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CLSContext",
              "text": "CLSContext"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "parentContext"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "parentIdentifierPath:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<NSString *>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "parentIdentifierPath"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSDataStore/title",
          "value": "CLSDataStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSDataStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSDataStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSDataStore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSDataStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ClassKit~1CLSContextProvider~1updateDescendants(of:completion:)/title",
          "value": "updateDescendantsOfContext:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ClassKit~1CLSContextProvider~1updateDescendants(of:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "updateDescendantsOfContext:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CLSContext",
              "text": "CLSContext"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "context"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "completion:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " (^)("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSError",
              "text": "NSError"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "error"
            },
            {
              "kind": "text",
              "text": ")) "
            },
            {
              "kind": "internalParam",
              "text": "completion"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ClassKit~1CLSDataStoreDelegate/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CLSDataStoreDelegate"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ClassKit~1CLSDataStore~1delegate/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "weak"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Qoobjc(pl)CLSDataStoreDelegate",
              "text": "id<CLSDataStoreDelegate>"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "delegate"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/classkit/incorporating-classkit-into-an-educational-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/classkit/incorporating-classkit-into-an-educational-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
