{
  "abstract": [
    {
      "text": "Add an activity item to an activity to record additional information about a student’s attempt to complete a task.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.classkit/documentation/ClassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.classkit/documentation/ClassKit/recording-additional-metrics-about-a-completed-task"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "ClassKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Recording additional metrics about a completed task"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You use an activity to measure how long a task takes and record progress through the task. To supply additional metrics about the task, you attach one or more activity items to the activity. You typically add these items to the activity after the user finishes the corresponding task, just before calling the activity’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSActivity/stop()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. These items record supplemental information, like a test score, a measured quantity, or a binary condition (like pass or fail).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-and-add-items",
          "level": 3,
          "text": "Create and add items",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Activity items have an identifier that distinguishes them from other items attached to the same activity, and a title that the teacher sees when reviewing results in the Schoolwork app. After creating and configuring the item, you add it to the activity using a call to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSActivity/addAdditionalActivityItem(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For example, for a quiz, you could create an activity item to record the number of times a hint was used, and report it as a quantity item:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "CLSDataStore.shared.mainAppContext.descendant(matchingIdentifierPath: identifierPath) { context, _ in",
            "    guard let activity = context?.currentActivity,",
            "        activity.isStarted else { return }",
            "",
            "    let item = CLSQuantityItem(identifier: \"hints\", title: \"Hints Used\")",
            "    item.quantity = <# The number of times a hint was used #>",
            "",
            "    activity.addAdditionalActivityItem(item)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Add-a-primary-activity-item",
          "level": 3,
          "text": "Add a primary activity item",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In some cases, the most important information about a task isn’t the student’s progress through it, but another metric that you define. For example, for a quiz, teachers are typically interested in the score. In this case, you provide an optional primary activity item that takes a prominent position in the reported results.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To add a primary activity item to an activity, you construct the item exactly as described in the preceding section. But rather than adding it with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSActivity/addAdditionalActivityItem(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", assign it to the activity’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSActivity/primaryActivityItem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property instead. For a quiz, you can assign a score item as the primary:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "CLSDataStore.shared.mainAppContext.descendant(matchingIdentifierPath: identifierPath) { context, _ in",
            "    guard let activity = context?.currentActivity,",
            "        activity.isStarted else { return }",
            "",
            "    activity.primaryActivityItem = CLSScoreItem(identifier: \"score\",",
            "                                                title: \"Score\",",
            "                                                score: correctAnswerCount / totalAnswerCount,",
            "                                                maxScore: 1)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Always use the same type of primary activity item for a given kind of activity. For example, activities generated for a particular quiz context should always have a primary activity item type of either a score or a pass/fail. Don’t use one value in some places and another in other places. Inconsistent assignment of primary activity items can confuse teachers when they try to interpret reported results.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Dont-overwhelm-teachers-with-data",
          "level": 3,
          "text": "Don’t overwhelm teachers with data",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use activity items to provide insights into a student’s interaction with your app. A quiz score, for example, demonstrates clearly and quantitatively how well a student understands the corresponding material.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "On the other hand, don’t collect data just for the sake of collecting data. Report only information that’s meaningful and actionable for teachers. The Schoolwork app is designed to give teachers insight into student performance, not to report every action a student takes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.classkit/documentation/ClassKit": {
      "abstract": [
        {
          "text": "Enable teachers to assign activities from your app’s content and to view student progress.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClassKit",
      "type": "topic",
      "url": "/documentation/classkit"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSActivity/addAdditionalActivityItem(_:)": {
      "abstract": [
        {
          "text": "Adds an activity item to an activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addAdditionalActivityItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLSActivityItem",
          "text": "CLSActivityItem"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSActivity/addAdditionalActivityItem(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addAdditionalActivityItem:"
        }
      ],
      "role": "symbol",
      "title": "addAdditionalActivityItem(_:)",
      "type": "topic",
      "url": "/documentation/classkit/clsactivity/addadditionalactivityitem(_:)"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSActivity/primaryActivityItem": {
      "abstract": [
        {
          "text": "Adds an activity item to an activity and sets it as the primary activity item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primaryActivityItem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLSActivityItem",
          "text": "CLSActivityItem"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSActivity/primaryActivityItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "primaryActivityItem"
        }
      ],
      "role": "symbol",
      "title": "primaryActivityItem",
      "type": "topic",
      "url": "/documentation/classkit/clsactivity/primaryactivityitem"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSActivity/stop()": {
      "abstract": [
        {
          "text": "Tells an activity to stop or pause recording duration and progress for a task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stop"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSActivity/stop()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stop"
        }
      ],
      "role": "symbol",
      "title": "stop()",
      "type": "topic",
      "url": "/documentation/classkit/clsactivity/stop()"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSActivityItem": {
      "abstract": [
        {
          "text": "An abstract base class for gathering information about an activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSActivityItem"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSActivityItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSActivityItem"
        }
      ],
      "role": "symbol",
      "title": "CLSActivityItem",
      "type": "topic",
      "url": "/documentation/classkit/clsactivityitem"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSBinaryItem": {
      "abstract": [
        {
          "text": "Activity information that is true or false, pass or fail, yes or no.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSBinaryItem"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSBinaryItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSBinaryItem"
        }
      ],
      "role": "symbol",
      "title": "CLSBinaryItem",
      "type": "topic",
      "url": "/documentation/classkit/clsbinaryitem"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSQuantityItem": {
      "abstract": [
        {
          "text": "Activity information that signifies a quantity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSQuantityItem"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSQuantityItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSQuantityItem"
        }
      ],
      "role": "symbol",
      "title": "CLSQuantityItem",
      "type": "topic",
      "url": "/documentation/classkit/clsquantityitem"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSScoreItem": {
      "abstract": [
        {
          "text": "Activity information that signifies a score out of a possible maximum.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSScoreItem"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSScoreItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSScoreItem"
        }
      ],
      "role": "symbol",
      "title": "CLSScoreItem",
      "type": "topic",
      "url": "/documentation/classkit/clsscoreitem"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Activity-items",
      "generated": true,
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/CLSScoreItem",
        "doc://com.apple.classkit/documentation/ClassKit/CLSBinaryItem",
        "doc://com.apple.classkit/documentation/ClassKit/CLSQuantityItem",
        "doc://com.apple.classkit/documentation/ClassKit/CLSActivityItem"
      ],
      "title": "Activity items"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Activity-items",
              "generated": true,
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/CLSScoreItem",
                "doc://com.apple.classkit/documentation/ClassKit/CLSBinaryItem",
                "doc://com.apple.classkit/documentation/ClassKit/CLSQuantityItem",
                "doc://com.apple.classkit/documentation/ClassKit/CLSActivityItem"
              ],
              "title": "Activity items"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSActivityItem/title",
          "value": "CLSActivityItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSActivityItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSActivityItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSActivityItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSActivityItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSActivity~1addAdditionalActivityItem(_:)/title",
          "value": "addAdditionalActivityItem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSActivity~1addAdditionalActivityItem(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addAdditionalActivityItem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSActivity~1primaryActivityItem/title",
          "value": "primaryActivityItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSActivity~1primaryActivityItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "primaryActivityItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSBinaryItem/title",
          "value": "CLSBinaryItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSBinaryItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSBinaryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSBinaryItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSBinaryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSQuantityItem/title",
          "value": "CLSQuantityItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSQuantityItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSQuantityItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSQuantityItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSQuantityItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSScoreItem/title",
          "value": "CLSScoreItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSScoreItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSScoreItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSScoreItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSScoreItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSActivity~1stop()/title",
          "value": "stop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSActivity~1stop()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stop"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/classkit/recording-additional-metrics-about-a-completed-task"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/classkit/recording-additional-metrics-about-a-completed-task"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
