{
  "abstract": [
    {
      "text": "Create an activity to record student progress through an assignment.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.classkit/documentation/ClassKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.classkit/documentation/ClassKit/recording-student-progress"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "ClassKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Recording student progress"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "While contexts describe what tasks a teacher can assign in your app, such as reading a chapter in a book, activities report on student progress as they work through those tasks. An activity measures duration—the length of time a user spends on a task—based on when you tell the activity to start and stop. It also records how far a user has progressed through the task as a percentage of completion, based on updates you supply. It’s up to you to define progress depending on the particulars of your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Retrieve-the-context",
          "level": 3,
          "text": "Retrieve the context",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An activity is always tied to a particular context. In fact, you create a new ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSActivity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance by asking the context whose task you are measuring to do so on your behalf. The newly created activity becomes the context’s current activity, which you access later through the context’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/currentActivity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Begin by retrieving the relevant context with a call to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/descendant(matchingIdentifierPath:completion:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. You’ll operate on the context from within the completion handler.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let identifierPath = <# The path to some context #>",
            "",
            "CLSDataStore.shared.mainAppContext.descendant(matchingIdentifierPath: identifierPath) { context, _ in",
            "    // Operate on the context here...",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Look up a context like this every time you need it, rather than storing a reference to it. The underlying instance may change from time to time as a result of network synchronization. If you always look up the context, you can be sure that you’re working with the right instance.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-and-start-an-activity",
          "level": 3,
          "text": "Create and start an activity",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "From within the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/descendant(matchingIdentifierPath:completion:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method’s completion handler, activate the context, and then create the activity. Typically, you’ll also start the activity right after creating it:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// You typically activate the context when you start an activity.",
            "context?.becomeActive()",
            "    ",
            "// Create and start a new activity.",
            "context?.createNewActivity().start()"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Then, while still inside the completion handler, save the changes to record them in the framework’s database and share them with the teacher:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "CLSDataStore.shared.save { error in",
            "    // Handle the error",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "For privacy reasons, only users logged in with managed student accounts who have received an assignment for a given context can save activities in that context to the database. This operation silently fails for other users (including both teachers and unmanaged users, and even students who have not yet received an assignment).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When you create and start an activity as shown above, you indicate that the user has begun an attempt at the task represented by the given context. This code runs each time a student attempts a task. For example, within the context of a book chapter, the app may create a reading activity that measures progress through the material. If the user abandons the task, then the next time they attempt it, create a new activity to record the new attempt as a new task. What it means to abandon a task (as opposed to pausing it) depends on your app’s usage model.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "In some cases, the user might only pause the task—for example, to review something that appears in an earlier chapter. In that case, when the user resumes the current task, don’t create a new activity. Instead, restart the existing one. See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.classkit/documentation/ClassKit/recording-student-progress#Pause-an-activity-when-the-user-interrupts-a-task-briefly",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for more details.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Update-progress-periodically",
          "level": 3,
          "text": "Update progress periodically",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An activity measures duration as the time interval between when you call its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSActivity/start()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSActivity/stop()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " methods. But the concept of progress depends entirely on what your app does, so you supply additional information in the form of progress updates.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To provide updates, you periodically call the activity’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSActivity/addProgressRange(fromStart:toEnd:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method at intervals that make sense for your app. For a book reader, you might define progress in terms of how many pages the user has read, calling for an update every time the user turns a page:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Progress defined as the current page as a fraction of the total pages.",
            "let progress = Double(max(0, min(1, currentPage / totalPages)))",
            "",
            "CLSDataStore.shared.mainAppContext.descendant(matchingIdentifierPath: identifierPath) { context, _ in",
            "",
            "    // Ensure we have a started activity.",
            "    guard let activity = context?.currentActivity,",
            "        activity.isStarted else { return }",
            "",
            "    activity.addProgressRange(fromStart: 0, toEnd: progress)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Another app that presents content in a scroll view might define progress as the current position relative to the bottom of the view, to be updated in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIScrollViewDelegate/scrollViewDidScroll(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " callback of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIScrollViewDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let position = scrollView.contentOffset.y + scrollView.frame.size.height",
            "let total = scrollView.contentSize.height",
            "let progress = Double(max(0, min(1, position / total)))"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "You can call the data store’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore/save(completion:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method every time you add a progress update to ensure your changes are reported to the teacher. And for certain long-running activities with infrequent updates, this might make sense. But for performance reasons, in most cases it’s best to wait until the activity ends, after which you save all the updates in one shot. This is particularly true if you generate frequent progress updates, as you might from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIScrollViewDelegate/scrollViewDidScroll(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Stop-an-activity-when-the-user-ends-the-attempt",
          "level": 3,
          "text": "Stop an activity when the user ends the attempt",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When the user aborts or completes a task, for example by navigating away from the chapter they’ve been reading, or by answering all the questions on a quiz, mark the activity as stopped:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "CLSDataStore.shared.mainAppContext.descendant(matchingIdentifierPath: identifierPath) { context, _ in",
            "    guard let activity = context?.currentActivity else { return }",
            "",
            "    activity.stop()",
            "",
            "    // Typically, you deactive the context at this point as well.",
            "    context?.resignActive()",
            "",
            "    CLSDataStore.shared.save { error in",
            "        // Handle the error",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Call the data store’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore/save(completion:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method at this point to ensure your accumulated progress updates and state changes synchronize to the network.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Because data must be synchronized across the network, expect some delay in a production environment between when you record results in your app, and when the teacher actually sees the results in Schoolwork.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Pause-an-activity-when-the-user-interrupts-a-task-briefly",
          "level": 3,
          "text": "Pause an activity when the user interrupts a task briefly",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can also use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSActivity/stop()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to pause an activity. For example, if you’re measuring progress through a game and the user taps the pause button, you may want to tell the corresponding activity to stop. Resume a paused activity with another call to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSActivity/start()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. You can stop and start repeatedly, but once you create a new activity in a given context using a call to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/createNewActivity()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, the previous activity becomes final, and can no longer be accessed from your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Whether pausing makes sense depends on the particulars of your app. Typically, you pause when the user interrupts a task with the expectation of continuing after a brief delay, but create a new activity when the user makes a fresh attempt at a task.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The framework automatically pauses a running activity if your app enters the background, and resumes the same activity when your app returns to the foreground.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Optionally-mark-an-assignment-as-done",
          "level": 3,
          "text": "Optionally, mark an assignment as done",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For each assignment, the Schoolwork app displays a per-student Done indicator to teachers. Students self-report this status by tapping a button in their own instance of Schoolwork. To do the same thing programmatically from your app, call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore/completeAllAssignedActivities(matching:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "CLSDataStore.shared.completeAllAssignedActivities(matching: [\"chapter-1\", \"quiz-1\"])"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "You can do this automatically for tasks that have a well-defined end point, like a timed quiz. After time runs out, the student isn’t allowed to make any further changes, so your app marks the task as done. For a task without a strict time limit, but that ends with a submission of an artifact, like a drawing or a poem, you can call the completion method as part of the submission flow. If you already have a done button of some kind in your interface, you can call the method from that button’s handler.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "A task’s progress isn’t connected to its Done indicator. For example, setting the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSActivity/progress",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " property to 1 doesn’t automatically force the Done indicator to true. Use progress to give teachers an idea of which parts of a task the student has attempted. Use the Done indicator to indicate that the student plans no further action for the activity.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Record-progress-at-multiple-levels-of-hierarchy",
          "level": 3,
          "text": "Record progress at multiple levels of hierarchy",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you group contexts into a hierarchy, you might want to record progress at multiple levels of the hierarchy concurrently. This lets you measure progress through a small, indivisible task, like reading a chapter in a book, while simultaneously recording progress through the larger, enclosing task, like reading the whole book in which that chapter appears. Do this by running more than one activity at a time.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For example, when the user begins reading Chapter 1 of a book, you start an activity in the Chapter 1 context and another in the book context. You set progress independently for each, while each maintains its own duration measurement. When the user begins reading Chapter 2, you stop the Chapter 1 activity and then create and start a new activity in Chapter 2. The book activity continues running through the chapter change.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "So the duration of time spent working on the book automatically becomes the cumulative duration of reading all the chapters. On the other hand, it’s up to you to report progress in the book context in a way that’s meaningful. For instance, if the chapters are all about the same length, you might set book progress simply as the fraction of the number of chapters read. But if they aren’t, you might need to account for the relative size of each chapter in setting book progress.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can nest activities like this to the full depth of your context hierarchy. For example, the chapters might each contain multiple sections, in which case you run the book, a chapter, and a particular section activity all at the same time.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When you do run more than one activity at a time, the data store’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore/runningActivity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property reports only the most recently started activity.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Recording at multiple levels of hierarchy is available in iOS 11.4 or later. In iOS 11.3, you can only run one activity at a time, so starting an activity when one is already running implicitly forces the running one to stop.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.classkit/documentation/ClassKit": {
      "abstract": [
        {
          "text": "Enable teachers to assign activities from your app’s content and to view student progress.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClassKit",
      "type": "topic",
      "url": "/documentation/classkit"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSActivity": {
      "abstract": [
        {
          "text": "A representation of user interaction with a context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSActivity"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSActivity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSActivity"
        }
      ],
      "role": "symbol",
      "title": "CLSActivity",
      "type": "topic",
      "url": "/documentation/classkit/clsactivity"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSActivity/addProgressRange(fromStart:toEnd:)": {
      "abstract": [
        {
          "text": "Adds a progress range to a given activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addProgressRange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "fromStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSActivity/addProgressRange(fromStart:toEnd:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addProgressRangeFromStart:toEnd:"
        }
      ],
      "role": "symbol",
      "title": "addProgressRange(fromStart:toEnd:)",
      "type": "topic",
      "url": "/documentation/classkit/clsactivity/addprogressrange(fromstart:toend:)"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSActivity/progress": {
      "abstract": [
        {
          "text": "A measure of progress through the task, given as a fraction in the range [0, 1].",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "progress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSActivity/progress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "progress"
        }
      ],
      "role": "symbol",
      "title": "progress",
      "type": "topic",
      "url": "/documentation/classkit/clsactivity/progress"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSActivity/start()": {
      "abstract": [
        {
          "text": "Tells an activity to start recording duration and progress for a task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "start"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSActivity/start()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "start"
        }
      ],
      "role": "symbol",
      "title": "start()",
      "type": "topic",
      "url": "/documentation/classkit/clsactivity/start()"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSActivity/stop()": {
      "abstract": [
        {
          "text": "Tells an activity to stop or pause recording duration and progress for a task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stop"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSActivity/stop()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stop"
        }
      ],
      "role": "symbol",
      "title": "stop()",
      "type": "topic",
      "url": "/documentation/classkit/clsactivity/stop()"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/createNewActivity()": {
      "abstract": [
        {
          "text": "Creates and returns a new activity instance for the context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "createNewActivity"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLSActivity",
          "text": "CLSActivity"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/createNewActivity()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "createNewActivity"
        }
      ],
      "role": "symbol",
      "title": "createNewActivity()",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/createnewactivity()"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/currentActivity": {
      "abstract": [
        {
          "text": "The activity available for recording progress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentActivity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLSActivity",
          "text": "CLSActivity"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/currentActivity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentActivity"
        }
      ],
      "role": "symbol",
      "title": "currentActivity",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/currentactivity"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext/descendant(matchingIdentifierPath:completion:)": {
      "abstract": [
        {
          "text": "Finds the context with the given identifier path relative to this context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "descendant"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "matchingIdentifierPath"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLSContext",
          "text": "CLSContext"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext/descendant(matchingIdentifierPath:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descendantMatchingIdentifierPath:completion:"
        }
      ],
      "role": "symbol",
      "title": "descendant(matchingIdentifierPath:completion:)",
      "type": "topic",
      "url": "/documentation/classkit/clscontext/descendant(matchingidentifierpath:completion:)"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore/completeAllAssignedActivities(matching:)": {
      "abstract": [
        {
          "text": "Marks all of the assigned and active activities for the given context path as complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "completeAllAssignedActivities"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "matching"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore/completeAllAssignedActivities(matching:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "completeAllAssignedActivitiesMatching:"
        }
      ],
      "role": "symbol",
      "title": "completeAllAssignedActivities(matching:)",
      "type": "topic",
      "url": "/documentation/classkit/clsdatastore/completeallassignedactivities(matching:)"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore/runningActivity": {
      "abstract": [
        {
          "text": "The currently running activity within the currently active context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "runningActivity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLSActivity",
          "text": "CLSActivity"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore/runningActivity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runningActivity"
        }
      ],
      "role": "symbol",
      "title": "runningActivity",
      "type": "topic",
      "url": "/documentation/classkit/clsdatastore/runningactivity"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore/save(completion:)": {
      "abstract": [
        {
          "text": "Saves any changes you’ve made in the data store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "save"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore/save(completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "saveWithCompletion:"
        }
      ],
      "role": "symbol",
      "title": "save(completion:)",
      "type": "topic",
      "url": "/documentation/classkit/clsdatastore/save(completion:)"
    },
    "doc://com.apple.classkit/documentation/ClassKit/recording-student-progress#Pause-an-activity-when-the-user-interrupts-a-task-briefly": {
      "abstract": [],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/recording-student-progress#Pause-an-activity-when-the-user-interrupts-a-task-briefly",
      "kind": "section",
      "title": "Pause an activity when the user interrupts a task briefly",
      "type": "topic",
      "url": "/documentation/classkit/recording-student-progress#Pause-an-activity-when-the-user-interrupts-a-task-briefly"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIScrollViewDelegate": {
      "abstract": [
        {
          "text": "The interface for the delegate of a scroll view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIScrollViewDelegate"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIScrollViewDelegate",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIScrollViewDelegate",
      "type": "topic",
      "url": "/documentation/UIKit/UIScrollViewDelegate"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIScrollViewDelegate/scrollViewDidScroll(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate when the user scrolls the content view within the scroll view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollViewDidScroll"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "scrollView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScrollView",
          "text": "UIScrollView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIScrollViewDelegate/scrollViewDidScroll(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "scrollViewDidScroll(_:)",
      "type": "topic",
      "url": "/documentation/UIKit/UIScrollViewDelegate/scrollViewDidScroll(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Activities",
      "generated": true,
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/CLSActivity"
      ],
      "title": "Activities"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Activities",
              "generated": true,
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/CLSActivity"
              ],
              "title": "Activities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1currentActivity/title",
          "value": "currentActivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1currentActivity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1descendant(matchingIdentifierPath:completion:)/title",
          "value": "descendantMatchingIdentifierPath:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1descendant(matchingIdentifierPath:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "descendantMatchingIdentifierPath:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSActivity~1stop()/title",
          "value": "stop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSActivity~1stop()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSDataStore~1runningActivity/title",
          "value": "runningActivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSDataStore~1runningActivity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "runningActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIScrollViewDelegate~1scrollViewDidScroll(_:)/title",
          "value": "scrollViewDidScroll:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIScrollViewDelegate~1scrollViewDidScroll(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "scrollViewDidScroll:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIScrollView",
              "text": "UIScrollView"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "scrollView"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSActivity/title",
          "value": "CLSActivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSActivity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSActivity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSDataStore~1completeAllAssignedActivities(matching:)/title",
          "value": "completeAllAssignedActivitiesMatching:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSDataStore~1completeAllAssignedActivities(matching:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "completeAllAssignedActivitiesMatching:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSDataStore~1save(completion:)/title",
          "value": "saveWithCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSDataStore~1save(completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "saveWithCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1createNewActivity()/title",
          "value": "createNewActivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext~1createNewActivity()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "createNewActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSActivity~1progress/title",
          "value": "progress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSActivity~1progress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "progress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSActivity~1start()/title",
          "value": "start"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSActivity~1start()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "start"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIScrollViewDelegate/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIScrollViewDelegate"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSActivity~1addProgressRange(fromStart:toEnd:)/title",
          "value": "addProgressRangeFromStart:toEnd:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSActivity~1addProgressRange(fromStart:toEnd:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addProgressRangeFromStart:toEnd:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/classkit/recording-student-progress"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/classkit/recording-student-progress"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
