{"seeAlsoSections":[{"title":"Constants","identifiers":["doc://com.apple.coremedia/documentation/CoreMedia/CMTime/zero","doc://com.apple.coremedia/documentation/CoreMedia/CMTime/invalid","doc://com.apple.coremedia/documentation/CoreMedia/CMTime/indefinite","doc://com.apple.coremedia/documentation/CoreMedia/CMTime/negativeInfinity"],"anchor":"Constants","generated":true}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coremedia/documentation/CoreMedia","doc://com.apple.coremedia/documentation/CoreMedia/CMTime"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"positiveInfinity"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.coremedia/documentation/CoreMedia/CMTime","preciseIdentifier":"c:@SA@CMTime","kind":"typeIdentifier","text":"CMTime"}]}]},{"content":[{"anchor":"Discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Don’t test a time against this constant using (time == "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.coremedia/documentation/CoreMedia/CMTime/positiveInfinity"},{"type":"text","text":") because there are many times that are also positive infinity. Use "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_POSITIVEINFINITY(_:)"},{"type":"text","text":" instead."}]}],"kind":"content"}],"abstract":[{"text":"A value that represents positive infinity.","type":"text"}],"variants":[{"paths":["/documentation/coremedia/cmtime/positiveinfinity"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/coremedia/cmtime/positiveinfinity"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.coremedia/documentation/CoreMedia/CMTime/positiveInfinity"},"metadata":{"modules":[{"name":"Core Media"}],"role":"symbol","extendedModule":"CoreMedia","symbolKind":"property","title":"positiveInfinity","navigatorTitle":[{"kind":"identifier","text":"kCMTimePositiveInfinity"}],"roleHeading":"Type Property","platforms":[{"deprecated":false,"unavailable":false,"name":"iOS","introducedAt":"4.0","beta":false},{"deprecated":false,"unavailable":false,"name":"iPadOS","introducedAt":"4.0","beta":false},{"deprecated":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"13.1","beta":false},{"deprecated":false,"unavailable":false,"name":"macOS","introducedAt":"10.7","beta":false},{"deprecated":false,"unavailable":false,"name":"tvOS","introducedAt":"9.0","beta":false},{"deprecated":false,"unavailable":false,"name":"visionOS","introducedAt":"1.0","beta":false},{"unavailable":false,"beta":false,"introducedAt":"6.0","name":"watchOS","deprecated":false}],"externalID":"c:@kCMTimePositiveInfinity","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"positiveInfinity"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@SA@CMTime","kind":"typeIdentifier","text":"CMTime"}]},"kind":"symbol","sections":[],"references":{"doc://com.apple.coremedia/documentation/CoreMedia/CMTime":{"navigatorTitle":[{"text":"CMTime","kind":"identifier"}],"role":"symbol","title":"CMTime","type":"topic","identifier":"doc://com.apple.coremedia/documentation/CoreMedia/CMTime","url":"/documentation/coremedia/cmtime","abstract":[{"type":"text","text":"A structure that represents time."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"CMTime","kind":"identifier"}],"kind":"symbol"},"doc://com.apple.coremedia/documentation/CoreMedia/CMTime/positiveInfinity":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"positiveInfinity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CMTime","kind":"typeIdentifier","preciseIdentifier":"c:@SA@CMTime"}],"kind":"symbol","navigatorTitle":[{"text":"kCMTimePositiveInfinity","kind":"identifier"}],"title":"positiveInfinity","url":"/documentation/coremedia/cmtime/positiveinfinity","type":"topic","identifier":"doc://com.apple.coremedia/documentation/CoreMedia/CMTime/positiveInfinity","abstract":[{"text":"A value that represents positive infinity.","type":"text"}]},"doc://com.apple.coremedia/documentation/CoreMedia/CMTime/indefinite":{"url":"/documentation/coremedia/cmtime/indefinite","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"indefinite"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@SA@CMTime","text":"CMTime","kind":"typeIdentifier"}],"identifier":"doc://com.apple.coremedia/documentation/CoreMedia/CMTime/indefinite","title":"indefinite","navigatorTitle":[{"text":"kCMTimeIndefinite","kind":"identifier"}],"abstract":[{"type":"text","text":"A value that represents an indefinite time."}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"text":"","type":"text"}],"type":"topic","role":"overview","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies"},"doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_POSITIVEINFINITY(_:)":{"title":"CMTIME_IS_POSITIVEINFINITY(_:)","url":"/documentation/coremedia/cmtime_is_positiveinfinity(_:)","abstract":[{"text":"Returns a Boolean value that indicates whether a given time is positive infinity.","type":"text"}],"type":"topic","identifier":"doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_POSITIVEINFINITY(_:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CMTIME_IS_POSITIVEINFINITY","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@SA@CMTime","text":"CMTime","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.apple.coremedia/documentation/CoreMedia/CMTime/negativeInfinity":{"title":"negativeInfinity","navigatorTitle":[{"kind":"identifier","text":"kCMTimeNegativeInfinity"}],"url":"/documentation/coremedia/cmtime/negativeinfinity","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"negativeInfinity"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@SA@CMTime","kind":"typeIdentifier","text":"CMTime"}],"abstract":[{"text":"A value that represents negative infinity.","type":"text"}],"identifier":"doc://com.apple.coremedia/documentation/CoreMedia/CMTime/negativeInfinity","role":"symbol","kind":"symbol","type":"topic"},"doc://com.apple.coremedia/documentation/CoreMedia/CMTime/invalid":{"navigatorTitle":[{"kind":"identifier","text":"kCMTimeInvalid"}],"abstract":[{"type":"text","text":"A value that represents an invalid time."}],"identifier":"doc://com.apple.coremedia/documentation/CoreMedia/CMTime/invalid","kind":"symbol","type":"topic","title":"invalid","role":"symbol","url":"/documentation/coremedia/cmtime/invalid","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@CMTime","text":"CMTime"}]},"doc://com.apple.coremedia/documentation/CoreMedia/CMTime/zero":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"zero","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CMTime","kind":"typeIdentifier","preciseIdentifier":"c:@SA@CMTime"}],"kind":"symbol","navigatorTitle":[{"text":"kCMTimeZero","kind":"identifier"}],"title":"zero","url":"/documentation/coremedia/cmtime/zero","type":"topic","identifier":"doc://com.apple.coremedia/documentation/CoreMedia/CMTime/zero","abstract":[{"text":"A value that represents time zero.","type":"text"}]},"doc://com.apple.coremedia/documentation/CoreMedia":{"url":"/documentation/coremedia","abstract":[{"type":"text","text":"Represent time-based audio-visual assets with essential data types."}],"identifier":"doc://com.apple.coremedia/documentation/CoreMedia","title":"Core Media","role":"collection","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"beta":false,"introducedAt":"4.0","name":"iOS","deprecated":false,"unavailable":false},{"beta":false,"introducedAt":"4.0","name":"iPadOS","deprecated":false,"unavailable":false},{"beta":false,"introducedAt":"13.1","name":"Mac Catalyst","deprecated":false,"unavailable":false},{"beta":false,"introducedAt":"10.7","name":"macOS","deprecated":false,"unavailable":false},{"beta":false,"introducedAt":"9.0","name":"tvOS","deprecated":false,"unavailable":false},{"introducedAt":"1.0","name":"visionOS","unavailable":false,"deprecated":false,"beta":false},{"introducedAt":"6.0","name":"watchOS","unavailable":false,"deprecated":false,"beta":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Global Variable","op":"replace"},{"path":"/metadata/title","value":"kCMTimePositiveInfinity","op":"replace"},{"path":"/metadata/symbolKind","value":"var","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"kCMTimePositiveInfinity"}],"op":"replace"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coremedia/documentation/CoreMedia"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc://com.apple.coremedia/documentation/CoreMedia/CMTime/zero","doc://com.apple.coremedia/documentation/CoreMedia/CMTime/invalid","doc://com.apple.coremedia/documentation/CoreMedia/CMTime/indefinite","doc://com.apple.coremedia/documentation/CoreMedia/CMTime/negativeInfinity"],"anchor":"Constants","title":"Constants","generated":true}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc://com.apple.coremedia/documentation/CoreMedia/CMTime","text":"CMTime","preciseIdentifier":"c:@SA@CMTime","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"kCMTimePositiveInfinity","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"op":"replace","value":"CMTime","path":"/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime/title"},{"op":"replace","path":"/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime/fragments","value":[{"kind":"identifier","text":"CMTime"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime/navigatorTitle","value":[{"kind":"identifier","text":"CMTime"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime~1positiveInfinity/title","value":"kCMTimePositiveInfinity"},{"op":"replace","path":"/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime~1positiveInfinity/fragments","value":[{"text":"kCMTimePositiveInfinity","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime~1indefinite/title","value":"kCMTimeIndefinite"},{"op":"replace","path":"/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime~1indefinite/fragments","value":[{"text":"kCMTimeIndefinite","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime~1negativeInfinity/title","value":"kCMTimeNegativeInfinity"},{"op":"replace","path":"/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime~1negativeInfinity/fragments","value":[{"text":"kCMTimeNegativeInfinity","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime~1invalid/title","value":"kCMTimeInvalid"},{"op":"replace","path":"/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime~1invalid/fragments","value":[{"kind":"identifier","text":"kCMTimeInvalid"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime~1zero/title","value":"kCMTimeZero"},{"op":"replace","path":"/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime~1zero/fragments","value":[{"text":"kCMTimeZero","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}