{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"panel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelect"},{"kind":"text","text":" "},{"kind":"internalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:22UniformTypeIdentifiers6UTTypeV","preciseIdentifier":"s:22UniformTypeIdentifiers6UTTypeV","text":"UTType"},{"kind":"text","text":"?)"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["/documentation/appkit/nsopensavepaneldelegate/panel(_:didselect:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsopensavepaneldelegate/panel(_:didselect:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"codeVoice","code":"NSSavePanel"},{"type":"text","text":": Optional — Sent when the user changes the current type."},{"type":"text","text":" "},{"type":"codeVoice","code":"NSOpenPanel"},{"type":"text","text":": Not sent."}],"metadata":{"platforms":[{"name":"macOS","introducedAt":"15.0","deprecated":false,"beta":false,"unavailable":false}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"panel"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UTType","preciseIdentifier":"s:22UniformTypeIdentifiers6UTTypeV"},{"kind":"text","text":"?)"}],"symbolKind":"method","title":"panel(_:didSelect:)","externalID":"c:objc(pl)NSOpenSavePanelDelegate(im)panel:didSelectType:","modules":[{"name":"AppKit"}],"role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"panel:didSelectType:"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panel(_:didSelect:)"},"references":{"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panel(_:didSelect:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panel(_:didSelect:)","title":"panel(_:didSelect:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"panel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didSelect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:22UniformTypeIdentifiers6UTTypeV","text":"UTType"},{"kind":"text","text":"?)"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"panel:didSelectType:"}],"type":"topic","role":"symbol","url":"/documentation/appkit/nsopensavepaneldelegate/panel(_:didselect:)","abstract":[{"type":"codeVoice","code":"NSSavePanel"},{"type":"text","text":": Optional — Sent when the user changes the current type."},{"type":"text","text":" "},{"type":"codeVoice","code":"NSOpenPanel"},{"type":"text","text":": Not sent."}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.externally.resolved.symbol/s:22UniformTypeIdentifiers6UTTypeV":{"identifier":"doc://com.externally.resolved.symbol/s:22UniformTypeIdentifiers6UTTypeV","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UTType","kind":"identifier"}],"title":"UTType","abstract":[{"type":"text","text":"A structure that represents a type of data to load, send, or receive."}],"role":"symbol","url":"/documentation/UniformTypeIdentifiers/UTType-swift.struct","kind":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate":{"role":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NSOpenSavePanelDelegate"}],"abstract":[{"text":"A set of methods for managing interactions with an open or save panel.","type":"text"}],"url":"/documentation/appkit/nsopensavepaneldelegate","title":"NSOpenSavePanelDelegate","navigatorTitle":[{"kind":"identifier","text":"NSOpenSavePanelDelegate"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"name":"macOS","introducedAt":"15.0","deprecated":false,"beta":false,"unavailable":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"panel:didSelectType:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"panel:didSelectType:","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"add","value":null},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"panel:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSelectType:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UTType","kind":"typeIdentifier","text":"UTType"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"type"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenSavePanelDelegate~1panel(_:didSelect:)/title","value":"panel:didSelectType:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenSavePanelDelegate~1panel(_:didSelect:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"panel:didSelectType:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenSavePanelDelegate/title","value":"NSOpenSavePanelDelegate"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenSavePanelDelegate/fragments","value":[{"kind":"identifier","text":"NSOpenSavePanelDelegate"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenSavePanelDelegate/navigatorTitle","value":[{"kind":"identifier","text":"NSOpenSavePanelDelegate"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}