{
  "abstract": [
    {
      "text": "A count of changes to the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/serverAddress",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " property over the last uninterrupted period of playback.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use AVPlayerViewController in AVKit",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfServerAddressChanges"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MPMovieAccessLogEvent(py)numberOfServerAddressChanges",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "numberOfServerAddressChanges"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "numberOfServerAddressChanges"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "3.2",
        "message": "Use AVPlayerViewController in AVKit",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "3.2",
        "message": "Use AVPlayerViewController in AVKit",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "Use AVPlayerViewController in AVKit",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "numberOfServerAddressChanges"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "numberOfServerAddressChanges"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent": {
      "abstract": [
        {
          "text": "A single piece of information for a movie access log.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMovieAccessLogEvent"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMovieAccessLogEvent"
        }
      ],
      "role": "symbol",
      "title": "MPMovieAccessLogEvent",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslogevent"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/durationWatched": {
      "abstract": [
        {
          "text": "The accumulated duration of the media played, in seconds.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "durationWatched"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/durationWatched",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "durationWatched"
        }
      ],
      "role": "symbol",
      "title": "durationWatched",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslogevent/durationwatched"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/indicatedBitrate": {
      "abstract": [
        {
          "text": "The throughput required to play the stream, as advertised by the web server, in bits per second.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indicatedBitrate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/indicatedBitrate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "indicatedBitrate"
        }
      ],
      "role": "symbol",
      "title": "indicatedBitrate",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslogevent/indicatedbitrate"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfBytesTransferred": {
      "abstract": [
        {
          "text": "The accumulated number of bytes transferred.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfBytesTransferred"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfBytesTransferred",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfBytesTransferred"
        }
      ],
      "role": "symbol",
      "title": "numberOfBytesTransferred",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslogevent/numberofbytestransferred"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfDroppedVideoFrames": {
      "abstract": [
        {
          "text": "The total number of dropped video frames.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfDroppedVideoFrames"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfDroppedVideoFrames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfDroppedVideoFrames"
        }
      ],
      "role": "symbol",
      "title": "numberOfDroppedVideoFrames",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslogevent/numberofdroppedvideoframes"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfSegmentsDownloaded": {
      "abstract": [
        {
          "text": "A count of media segments downloaded from the web server to your app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfSegmentsDownloaded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfSegmentsDownloaded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfSegmentsDownloaded"
        }
      ],
      "role": "symbol",
      "title": "numberOfSegmentsDownloaded",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslogevent/numberofsegmentsdownloaded"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfServerAddressChanges": {
      "abstract": [
        {
          "text": "A count of changes to the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/serverAddress",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property over the last uninterrupted period of playback.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfServerAddressChanges"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfServerAddressChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfServerAddressChanges"
        }
      ],
      "role": "symbol",
      "title": "numberOfServerAddressChanges",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslogevent/numberofserveraddresschanges"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfStalls": {
      "abstract": [
        {
          "text": "The total number of playback stalls encountered.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfStalls"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfStalls",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfStalls"
        }
      ],
      "role": "symbol",
      "title": "numberOfStalls",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslogevent/numberofstalls"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/observedBitrate": {
      "abstract": [
        {
          "text": "The empirical throughput across all media downloaded for the movie player, in bits per second.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "observedBitrate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/observedBitrate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "observedBitrate"
        }
      ],
      "role": "symbol",
      "title": "observedBitrate",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslogevent/observedbitrate"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/playbackSessionID": {
      "abstract": [
        {
          "text": "A GUID that identifies the playback session to use in HTTP requests.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playbackSessionID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/playbackSessionID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playbackSessionID"
        }
      ],
      "role": "symbol",
      "title": "playbackSessionID",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslogevent/playbacksessionid"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/playbackStartDate": {
      "abstract": [
        {
          "text": "The timestamp for when playback began for the movie log access event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playbackStartDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/playbackStartDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playbackStartDate"
        }
      ],
      "role": "symbol",
      "title": "playbackStartDate",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslogevent/playbackstartdate"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/playbackStartOffset": {
      "abstract": [
        {
          "text": "An offset into the playlist where the last uninterrupted period of playback began, in seconds.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playbackStartOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/playbackStartOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playbackStartOffset"
        }
      ],
      "role": "symbol",
      "title": "playbackStartOffset",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslogevent/playbackstartoffset"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/segmentsDownloadedDuration": {
      "abstract": [
        {
          "text": "The accumulated duration of the media downloaded, in seconds.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "segmentsDownloadedDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/segmentsDownloadedDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "segmentsDownloadedDuration"
        }
      ],
      "role": "symbol",
      "title": "segmentsDownloadedDuration",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslogevent/segmentsdownloadedduration"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/serverAddress": {
      "abstract": [
        {
          "text": "The IPv4 or IPv6 address of the web server that was the source of the last delivered media segment.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serverAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/serverAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "serverAddress"
        }
      ],
      "role": "symbol",
      "title": "serverAddress",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslogevent/serveraddress"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/uri": {
      "abstract": [
        {
          "text": "The URI of the playback item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uri"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/uri",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "URI"
        }
      ],
      "role": "symbol",
      "title": "uri",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslogevent/uri"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Movie-access-log-event-properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfSegmentsDownloaded",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/playbackStartDate",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/uri",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/serverAddress",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/playbackSessionID",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/playbackStartOffset",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/segmentsDownloadedDuration",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/durationWatched",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfStalls",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfBytesTransferred",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/observedBitrate",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/indicatedBitrate",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfDroppedVideoFrames"
      ],
      "title": "Movie access log event properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "4.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "4.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "numberOfServerAddressChanges"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfServerAddressChanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Movie-access-log-event-properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfSegmentsDownloaded",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/playbackStartDate",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/uri",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/serverAddress",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/playbackSessionID",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/playbackStartOffset",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/segmentsDownloadedDuration",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/durationWatched",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfStalls",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfBytesTransferred",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/observedBitrate",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/indicatedBitrate",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfDroppedVideoFrames"
              ],
              "title": "Movie access log event properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "numberOfServerAddressChanges"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use AVPlayerViewController in AVKit",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1uri/title",
          "value": "URI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1uri/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "URI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1numberOfStalls/title",
          "value": "numberOfStalls"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1numberOfStalls/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfStalls"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent/title",
          "value": "MPMovieAccessLogEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieAccessLogEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieAccessLogEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1observedBitrate/title",
          "value": "observedBitrate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1observedBitrate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "observedBitrate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1numberOfDroppedVideoFrames/title",
          "value": "numberOfDroppedVideoFrames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1numberOfDroppedVideoFrames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfDroppedVideoFrames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1playbackStartOffset/title",
          "value": "playbackStartOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1playbackStartOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "playbackStartOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1durationWatched/title",
          "value": "durationWatched"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1durationWatched/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "durationWatched"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1numberOfSegmentsDownloaded/title",
          "value": "numberOfSegmentsDownloaded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1numberOfSegmentsDownloaded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfSegmentsDownloaded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1segmentsDownloadedDuration/title",
          "value": "segmentsDownloadedDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1segmentsDownloadedDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "segmentsDownloadedDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1playbackSessionID/title",
          "value": "playbackSessionID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1playbackSessionID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "playbackSessionID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1serverAddress/title",
          "value": "serverAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1serverAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "serverAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1indicatedBitrate/title",
          "value": "indicatedBitrate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1indicatedBitrate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "indicatedBitrate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1numberOfBytesTransferred/title",
          "value": "numberOfBytesTransferred"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1numberOfBytesTransferred/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfBytesTransferred"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1playbackStartDate/title",
          "value": "playbackStartDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1playbackStartDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "playbackStartDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1numberOfServerAddressChanges/title",
          "value": "numberOfServerAddressChanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1numberOfServerAddressChanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfServerAddressChanges"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/mpmovieaccesslogevent/numberofserveraddresschanges"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/mpmovieaccesslogevent/numberofserveraddresschanges"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
