{
  "abstract": [
    {
      "text": "A group key identifying the landmarks of the right arm.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyRightArm"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Vision",
    "externalID": "c:@VNBodyLandmarkRegionKeyRightArm",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "bodyLandmarkRegionKeyRightArm"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@VNRecognizedPointGroupKey",
        "text": "VNRecognizedPointGroupKey"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VNBodyLandmarkRegionKeyRightArm"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "14.0",
        "name": "iOS",
        "renamed": "VNHumanBodyPoseObservation.JointsGroupName.rightArm",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "renamed": "VNHumanBodyPoseObservation.JointsGroupName.rightArm",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "renamed": "VNHumanBodyPoseObservation.JointsGroupName.rightArm",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "11.0",
        "name": "macOS",
        "renamed": "VNHumanBodyPoseObservation.JointsGroupName.rightArm",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "14.0",
        "name": "tvOS",
        "renamed": "VNHumanBodyPoseObservation.JointsGroupName.rightArm",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "renamed": "VNHumanBodyPoseObservation.JointsGroupName.rightArm",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "bodyLandmarkRegionKeyRightArm"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "bodyLandmarkRegionKeyRightArm"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@VNRecognizedPointGroupKey",
              "text": "VNRecognizedPointGroupKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey": {
      "abstract": [
        {
          "text": "The data type for all recognized-point group keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNRecognizedPointGroupKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRecognizedPointGroupKey"
        }
      ],
      "role": "symbol",
      "title": "VNRecognizedPointGroupKey",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointgroupkey"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyFace": {
      "abstract": [
        {
          "text": "A group key identifying the face, which includes the eyes, ears, and nose.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkRegionKeyFace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointGroupKey",
          "text": "VNRecognizedPointGroupKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyFace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkRegionKeyFace"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkRegionKeyFace",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointgroupkey/bodylandmarkregionkeyface"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyLeftArm": {
      "abstract": [
        {
          "text": "A group key identifying the landmarks of the left arm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkRegionKeyLeftArm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointGroupKey",
          "text": "VNRecognizedPointGroupKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyLeftArm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkRegionKeyLeftArm"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkRegionKeyLeftArm",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointgroupkey/bodylandmarkregionkeyleftarm"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyLeftLeg": {
      "abstract": [
        {
          "text": "A group key identifying the landmarks of the left leg.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkRegionKeyLeftLeg"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointGroupKey",
          "text": "VNRecognizedPointGroupKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyLeftLeg",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkRegionKeyLeftLeg"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkRegionKeyLeftLeg",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointgroupkey/bodylandmarkregionkeyleftleg"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyRightArm": {
      "abstract": [
        {
          "text": "A group key identifying the landmarks of the right arm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkRegionKeyRightArm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointGroupKey",
          "text": "VNRecognizedPointGroupKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyRightArm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkRegionKeyRightArm"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkRegionKeyRightArm",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointgroupkey/bodylandmarkregionkeyrightarm"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyRightLeg": {
      "abstract": [
        {
          "text": "A group key identifying the landmarks of the right leg.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkRegionKeyRightLeg"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointGroupKey",
          "text": "VNRecognizedPointGroupKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyRightLeg",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkRegionKeyRightLeg"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkRegionKeyRightLeg",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointgroupkey/bodylandmarkregionkeyrightleg"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyTorso": {
      "abstract": [
        {
          "text": "A group key identifying the torso, which includes the neck, shoulders, hips, and root.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkRegionKeyTorso"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointGroupKey",
          "text": "VNRecognizedPointGroupKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyTorso",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkRegionKeyTorso"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkRegionKeyTorso",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointgroupkey/bodylandmarkregionkeytorso"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Body-Regions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyFace",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyTorso",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyLeftArm",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyRightLeg",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyLeftLeg"
      ],
      "title": "Body Regions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNBodyLandmarkRegionKeyRightArm"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkRegionKeyRightArm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Body-Regions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyFace",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyTorso",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyLeftArm",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyRightLeg",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyLeftLeg"
              ],
              "title": "Body Regions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@VNRecognizedPointGroupKey",
                    "text": "VNRecognizedPointGroupKey"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VNBodyLandmarkRegionKeyRightArm"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1bodyLandmarkRegionKeyLeftLeg/title",
          "value": "VNBodyLandmarkRegionKeyLeftLeg"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1bodyLandmarkRegionKeyLeftLeg/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkRegionKeyLeftLeg"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1bodyLandmarkRegionKeyFace/title",
          "value": "VNBodyLandmarkRegionKeyFace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1bodyLandmarkRegionKeyFace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkRegionKeyFace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1bodyLandmarkRegionKeyLeftArm/title",
          "value": "VNBodyLandmarkRegionKeyLeftArm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1bodyLandmarkRegionKeyLeftArm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkRegionKeyLeftArm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1bodyLandmarkRegionKeyRightArm/title",
          "value": "VNBodyLandmarkRegionKeyRightArm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1bodyLandmarkRegionKeyRightArm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkRegionKeyRightArm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1bodyLandmarkRegionKeyTorso/title",
          "value": "VNBodyLandmarkRegionKeyTorso"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1bodyLandmarkRegionKeyTorso/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkRegionKeyTorso"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey/title",
          "value": "VNRecognizedPointGroupKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRecognizedPointGroupKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRecognizedPointGroupKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1bodyLandmarkRegionKeyRightLeg/title",
          "value": "VNBodyLandmarkRegionKeyRightLeg"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1bodyLandmarkRegionKeyRightLeg/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkRegionKeyRightLeg"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vnrecognizedpointgroupkey/bodylandmarkregionkeyrightarm"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vnrecognizedpointgroupkey/bodylandmarkregionkeyrightarm"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
