{
  "abstract": [
    {
      "text": "The print order for the pages of the operation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintOperation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSPrintOperation/pageOrder-swift.property"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSPrintOperation(py)pageOrder",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "pageOrder"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSPrintOperation",
        "text": "NSPrintOperation"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSPrintingPageOrder",
        "text": "PageOrder"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "pageOrder"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "pageOrder"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "pageOrder"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintOperation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSPrintOperation",
              "text": "NSPrintOperation"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintOperation/PageOrder-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSPrintingPageOrder",
              "text": "PageOrder"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The print order. For a list of possible values, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintOperation/PageOrder-swift.enum",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "order"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintOperation": {
      "abstract": [
        {
          "text": "An object that controls operations that generate Encapsulated PostScript (EPS) code, Portable Document Format (PDF) code, or print jobs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPrintOperation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintOperation"
        }
      ],
      "role": "symbol",
      "title": "NSPrintOperation",
      "type": "topic",
      "url": "/documentation/appkit/nsprintoperation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintOperation/PageOrder-swift.enum": {
      "abstract": [
        {
          "text": "Constants that specify the page order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PageOrder"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintOperation/PageOrder-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PageOrder"
        }
      ],
      "role": "symbol",
      "title": "NSPrintOperation.PageOrder",
      "type": "topic",
      "url": "/documentation/appkit/nsprintoperation/pageorder-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintOperation/currentPage": {
      "abstract": [
        {
          "text": "The current page number being printed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentPage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintOperation/currentPage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentPage"
        }
      ],
      "role": "symbol",
      "title": "currentPage",
      "type": "topic",
      "url": "/documentation/appkit/nsprintoperation/currentpage"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintOperation/pageOrder-swift.property": {
      "abstract": [
        {
          "text": "The print order for the pages of the operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageOrder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintOperation",
          "text": "NSPrintOperation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPrintingPageOrder",
          "text": "PageOrder"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintOperation/pageOrder-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pageOrder"
        }
      ],
      "role": "symbol",
      "title": "pageOrder",
      "type": "topic",
      "url": "/documentation/appkit/nsprintoperation/pageorder-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintOperation/pageRange": {
      "abstract": [
        {
          "text": "The range of pages associated with the print operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintOperation/pageRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pageRange"
        }
      ],
      "role": "symbol",
      "title": "pageRange",
      "type": "topic",
      "url": "/documentation/appkit/nsprintoperation/pagerange"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Page-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPrintOperation/currentPage",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintOperation/pageRange",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintOperation/PageOrder-swift.enum"
      ],
      "title": "Managing Page Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "pageOrder"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pageOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintOperation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Page-Information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPrintOperation/currentPage",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintOperation/pageRange",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintOperation/PageOrder-swift.enum"
              ],
              "title": "Managing Page Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintOperation/PageOrder-swift.enum",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@NSPrintingPageOrder",
                    "text": "NSPrintingPageOrder"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "pageOrder"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintOperation~1pageRange/title",
          "value": "pageRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintOperation~1pageRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pageRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintOperation~1pageOrder-swift.property/title",
          "value": "pageOrder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintOperation~1pageOrder-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pageOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintOperation~1currentPage/title",
          "value": "currentPage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintOperation~1currentPage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentPage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintOperation~1PageOrder-swift.enum/title",
          "value": "NSPrintingPageOrder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintOperation~1PageOrder-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintingPageOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintOperation~1PageOrder-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintingPageOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintOperation/title",
          "value": "NSPrintOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintOperation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsprintoperation/pageorder-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsprintoperation/pageorder-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
