{
  "abstract": [
    {
      "text": "Asks the delegate to provide an array of row actions to be attached to the specified edge of a table row and displayed when the user swipes horizontally across the row.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:rowActionsForRow:edge:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSTableViewDelegate(im)tableView:rowActionsForRow:edge:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "tableView"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSTableView",
        "text": "NSTableView"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "rowActionsForRow"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "edge"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSTableView",
        "text": "NSTableView"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSTableRowActionEdge",
        "text": "RowActionEdge"
      },
      {
        "kind": "text",
        "text": ") -> ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSTableViewRowAction",
        "text": "NSTableViewRowAction"
      },
      {
        "kind": "text",
        "text": "]"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "tableView:rowActionsForRow:edge:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "tableView(_:rowActionsForRow:edge:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "tableView"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "tableView"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSTableView",
              "text": "NSTableView"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "rowActionsForRow"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "row"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "edge"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSTableView",
              "text": "NSTableView"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowActionEdge",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSTableRowActionEdge",
              "text": "RowActionEdge"
            },
            {
              "kind": "text",
              "text": ") -> ["
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSTableViewRowAction",
              "text": "NSTableViewRowAction"
            },
            {
              "kind": "text",
              "text": "]"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The table view that sent the message.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "tableView"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The index of the target row.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "row"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The edge (of class ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowActionEdge",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ") for which row actions are requested. This is based on the direction in which the user swiped on the row. Swiping to the right results in an edge value of ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowActionEdge/leading",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". Swiping to the left results in an edge value of ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowActionEdge/trailing",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "edge"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An array of row actions (of class ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ") to be enabled on the specified edge of the table row.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Implement this method if your table row supports actions that are displayed when the user swipes horizontally across the row. For example, your table view could use this method to implement a swipe left to delete function in your table rows. When called, this method receives the table view, the index of the row the user swiped, and an edge of type ",
              "type": "text"
            },
            {
              "code": "NSTableRowActionEdge",
              "type": "codeVoice"
            },
            {
              "text": ". The method should return an array of any row actions of class ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that are supported for the specified edge. If no row actions are available, an empty array should be returned.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If this method isn’t implemented, then the table row displays no actions when the user swipes horizontally away from the specified edge.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView": {
      "abstract": [
        {
          "text": "A set of related records, displayed in rows that represent individual records and columns that represent the attributes of those records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableView"
        }
      ],
      "role": "symbol",
      "title": "NSTableView",
      "type": "topic",
      "url": "/documentation/appkit/nstableview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowActionEdge": {
      "abstract": [
        {
          "text": "These constants define table row edges on which row actions are attached. They are used by the ",
          "type": "text"
        },
        {
          "code": "tableView:rowActionsForRow:edge:",
          "type": "codeVoice"
        },
        {
          "text": " delegate method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RowActionEdge"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowActionEdge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RowActionEdge"
        }
      ],
      "role": "symbol",
      "title": "NSTableView.RowActionEdge",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/rowactionedge"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowActionEdge/leading": {
      "abstract": [
        {
          "text": "Denotes the leading, or left, edge of a table row view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leading"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowActionEdge/leading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableRowActionEdgeLeading"
        }
      ],
      "role": "symbol",
      "title": "NSTableView.RowActionEdge.leading",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/rowactionedge/leading"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowActionEdge/trailing": {
      "abstract": [
        {
          "text": "Denotes the trailing, or right, edge of a table row view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trailing"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowActionEdge/trailing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableRowActionEdgeTrailing"
        }
      ],
      "role": "symbol",
      "title": "NSTableView.RowActionEdge.trailing",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/rowactionedge/trailing"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate": {
      "abstract": [
        {
          "text": "A set of optional methods you implement in a table view delegate to customize the behavior of the table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSTableViewDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nstableviewdelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:rowActionsForRow:edge:)": {
      "abstract": [
        {
          "text": "Asks the delegate to provide an array of row actions to be attached to the specified edge of a table row and displayed when the user swipes horizontally across the row.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tableView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableView",
          "text": "NSTableView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rowActionsForRow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "edge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableView",
          "text": "NSTableView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTableRowActionEdge",
          "text": "RowActionEdge"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableViewRowAction",
          "text": "NSTableViewRowAction"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:rowActionsForRow:edge:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tableView:rowActionsForRow:edge:"
        }
      ],
      "role": "symbol",
      "title": "tableView(_:rowActionsForRow:edge:)",
      "type": "topic",
      "url": "/documentation/appkit/nstableviewdelegate/tableview(_:rowactionsforrow:edge:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction": {
      "abstract": [
        {
          "text": "A single action to present when the user swipes horizontally on a table row.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableViewRowAction"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableViewRowAction"
        }
      ],
      "role": "symbol",
      "title": "NSTableViewRowAction",
      "type": "topic",
      "url": "/documentation/appkit/nstableviewrowaction"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowActionEdge"
      ],
      "title": "Related Documentation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "tableView:rowActionsForRow:edge:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tableView:rowActionsForRow:edge:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction",
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowActionEdge"
              ],
              "title": "Related Documentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<NSTableViewRowAction *>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "tableView:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSTableView",
                    "text": "NSTableView"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "tableView"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "rowActionsForRow:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "row"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "edge:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowActionEdge",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@NSTableRowActionEdge",
                    "text": "NSTableRowActionEdge"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "edge"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The table view that sent the message.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "tableView"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The index of the target row.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "row"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The edge (of class ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowActionEdge",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ") for which row actions are requested. This is based on the direction in which the user swiped on the row. Swiping to the right results in an edge value of ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowActionEdge/leading",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ". Swiping to the left results in an edge value of ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowActionEdge/trailing",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "edge"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "An array of row actions (of class ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ") to be enabled on the specified edge of the table row.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1RowActionEdge~1trailing/title",
          "value": "NSTableRowActionEdgeTrailing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1RowActionEdge~1trailing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableRowActionEdgeTrailing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1RowActionEdge~1leading/title",
          "value": "NSTableRowActionEdgeLeading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1RowActionEdge~1leading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableRowActionEdgeLeading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:rowActionsForRow:edge:)/title",
          "value": "tableView:rowActionsForRow:edge:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:rowActionsForRow:edge:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tableView:rowActionsForRow:edge:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/title",
          "value": "NSTableView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate/title",
          "value": "NSTableViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1RowActionEdge/title",
          "value": "NSTableRowActionEdge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1RowActionEdge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableRowActionEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1RowActionEdge/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableRowActionEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewRowAction/title",
          "value": "NSTableViewRowAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewRowAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewRowAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewRowAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewRowAction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstableviewdelegate/tableview(_:rowactionsforrow:edge:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstableviewdelegate/tableview(_:rowactionsforrow:edge:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
