{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/Extensions-swift.struct",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/Extensions-swift.struct/Value",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/Extensions-swift.struct/Value/FontFace"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/Extensions-swift.struct/Value/FontFace/italic"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV5ValueV8FontFaceV6italicAIvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "italic"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
        "text": "CMFormatDescription"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV",
        "text": "Extensions"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV5ValueV",
        "text": "Value"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV5ValueV8FontFaceV",
        "text": "FontFace"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "italic"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "italic"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
              "text": "CMFormatDescription"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/Extensions-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV",
              "text": "Extensions"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/Extensions-swift.struct/Value",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV5ValueV",
              "text": "Value"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/Extensions-swift.struct/Value/FontFace",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV5ValueV8FontFaceV",
              "text": "FontFace"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription": {
      "abstract": [
        {
          "text": "An object that describes a media format descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMFormatDescription"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMFormatDescription"
        }
      ],
      "role": "symbol",
      "title": "CMFormatDescription",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/Extensions-swift.struct": {
      "abstract": [
        {
          "text": "A type that describes format description extensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Extensions"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/Extensions-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Extensions"
        }
      ],
      "role": "symbol",
      "title": "CMFormatDescription.Extensions",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/extensions-swift.struct"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/Extensions-swift.struct/Value": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Value"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/Extensions-swift.struct/Value",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Value"
        }
      ],
      "role": "symbol",
      "title": "CMFormatDescription.Extensions.Value",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/extensions-swift.struct/value"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/Extensions-swift.struct/Value/FontFace": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FontFace"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/Extensions-swift.struct/Value/FontFace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FontFace"
        }
      ],
      "role": "symbol",
      "title": "CMFormatDescription.Extensions.Value.FontFace",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/extensions-swift.struct/value/fontface"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/Extensions-swift.struct/Value/FontFace/all": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "all"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV",
          "text": "Extensions"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV5ValueV",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV5ValueV8FontFaceV",
          "text": "FontFace"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/Extensions-swift.struct/Value/FontFace/all",
      "kind": "symbol",
      "role": "symbol",
      "title": "all",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/extensions-swift.struct/value/fontface/all"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/Extensions-swift.struct/Value/FontFace/bold": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV",
          "text": "Extensions"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV5ValueV",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV5ValueV8FontFaceV",
          "text": "FontFace"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/Extensions-swift.struct/Value/FontFace/bold",
      "kind": "symbol",
      "role": "symbol",
      "title": "bold",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/extensions-swift.struct/value/fontface/bold"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/Extensions-swift.struct/Value/FontFace/italic": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "italic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV",
          "text": "Extensions"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV5ValueV",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV5ValueV8FontFaceV",
          "text": "FontFace"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/Extensions-swift.struct/Value/FontFace/italic",
      "kind": "symbol",
      "role": "symbol",
      "title": "italic",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/extensions-swift.struct/value/fontface/italic"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/Extensions-swift.struct/Value/FontFace/underline": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "underline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV",
          "text": "Extensions"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV5ValueV",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV5ValueV8FontFaceV",
          "text": "FontFace"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/Extensions-swift.struct/Value/FontFace/underline",
      "kind": "symbol",
      "role": "symbol",
      "title": "underline",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/extensions-swift.struct/value/fontface/underline"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Font-Faces",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/Extensions-swift.struct/Value/FontFace/all",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/Extensions-swift.struct/Value/FontFace/bold",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/Extensions-swift.struct/Value/FontFace/underline"
      ],
      "title": "Font Faces"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMFormatDescription/title",
          "value": "CMFormatDescriptionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMFormatDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMFormatDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMFormatDescriptionRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmformatdescription/extensions-swift.struct/value/fontface/italic"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
