{
  "abstract": [
    {
      "text": "The format descriptions of the media samples that a track references.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/formatDescriptions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "c:objc(cs)AVCompositionTrack(py)formatDescriptions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "formatDescriptions"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "]"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "formatDescriptions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "formatDescriptions"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "] { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The array contains ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMFormatDescription",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects that indicate the format of media samples the track references.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Asset tracks typically present uniform media (for example, media that uses the same encoding settings) and contain a single format description. However, in some cases, an asset track may contain multiple format descriptions. For example, an H.264-encoded video track may have some segments that use the Main profile and others that use the High profile. Also, an individual ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", which subclasses ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrack",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", may contain audio or video segments using different codecs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMFormatDescription",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to access low-level details about the media the track references. For example, you can retrieve the details of track’s media type and subtype as the code below shows:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "extension AVAssetTrack {",
            "    var mediaFormat: String {",
            "        get async throws {",
            "            var format = \"\"",
            "            let descriptions = try await load(.formatDescriptions)",
            "            for (index, formatDesc) in descriptions.enumerated() {",
            "                // Get a string representation of the media type.",
            "                let type =",
            "                    CMFormatDescriptionGetMediaType(formatDesc).toString()",
            "                // Get a string representation of the media subtype.",
            "                let subType =",
            "                    CMFormatDescriptionGetMediaSubType(formatDesc).toString()",
            "                // Format the string as type/subType, such as vide/avc1 or soun/aac.",
            "                format += \"\\(type)/\\(subType)\"",
            "                // Comma-separate if there's more than one format description.",
            "                if index < descriptions.count - 1 {",
            "                    format += \",\"",
            "                }",
            "            }",
            "            return format",
            "        }",
            "    }",
            "}",
            " ",
            "extension FourCharCode {",
            "    // Create a string representation of a FourCC.",
            "    func toString() -> String {",
            "        let bytes: [CChar] = [",
            "            CChar((self >> 24) & 0xff),",
            "            CChar((self >> 16) & 0xff),",
            "            CChar((self >> 8) & 0xff),",
            "            CChar(self & 0xff),",
            "            0",
            "        ]",
            "        let result = String(cString: bytes)",
            "        let characterSet = CharacterSet.whitespaces",
            "        return result.trimmingCharacters(in: characterSet)",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrack": {
      "abstract": [
        {
          "text": "An object that models a track of media that an asset contains.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetTrack"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetTrack"
        }
      ],
      "role": "symbol",
      "title": "AVAssetTrack",
      "type": "topic",
      "url": "/documentation/avfoundation/avassettrack"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack": {
      "abstract": [
        {
          "text": "A track in a composition that presents media of a uniform type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCompositionTrack"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCompositionTrack"
        }
      ],
      "role": "symbol",
      "title": "AVCompositionTrack",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/formatDescriptionReplacements": {
      "abstract": [
        {
          "text": "The replacement format descriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formatDescriptionReplacements"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCompositionTrackFormatDescriptionReplacement",
          "text": "AVCompositionTrackFormatDescriptionReplacement"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/formatDescriptionReplacements",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "formatDescriptionReplacements"
        }
      ],
      "role": "symbol",
      "title": "formatDescriptionReplacements",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/formatdescriptionreplacements"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/formatDescriptions": {
      "abstract": [
        {
          "text": "The format descriptions of the media samples that a track references.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formatDescriptions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/formatDescriptions",
      "kind": "symbol",
      "role": "symbol",
      "title": "formatDescriptions",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/formatdescriptions"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrackFormatDescriptionReplacement": {
      "abstract": [
        {
          "text": "An object that represents a format description and its replacement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCompositionTrackFormatDescriptionReplacement"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrackFormatDescriptionReplacement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCompositionTrackFormatDescriptionReplacement"
        }
      ],
      "role": "symbol",
      "title": "AVCompositionTrackFormatDescriptionReplacement",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrackformatdescriptionreplacement"
    },
    "doc://com.apple.documentation/documentation/CoreMedia/CMFormatDescription": {
      "abstract": [
        {
          "text": "An object that describes a media format descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMFormatDescription"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMFormatDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMFormatDescription",
      "type": "topic",
      "url": "/documentation/CoreMedia/CMFormatDescription"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Format-Descriptions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/formatDescriptionReplacements",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrackFormatDescriptionReplacement"
      ],
      "title": "Managing Format Descriptions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrack/title",
          "value": "AVCompositionTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCompositionTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCompositionTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrackFormatDescriptionReplacement/title",
          "value": "AVCompositionTrackFormatDescriptionReplacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrackFormatDescriptionReplacement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCompositionTrackFormatDescriptionReplacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrackFormatDescriptionReplacement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCompositionTrackFormatDescriptionReplacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreMedia~1CMFormatDescription/title",
          "value": "CMFormatDescriptionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreMedia~1CMFormatDescription/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@opaqueCMFormatDescription",
              "text": "opaqueCMFormatDescription"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "CMFormatDescriptionRef"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrack/title",
          "value": "AVAssetTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrack~1formatDescriptionReplacements/title",
          "value": "formatDescriptionReplacements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrack~1formatDescriptionReplacements/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "formatDescriptionReplacements"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcompositiontrack/formatdescriptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
