{
  "abstract": [
    {
      "text": "The track’s transform preference to apply to its visual content during presentation or processing.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/preferredTransform"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "c:objc(cs)AVCompositionTrack(py)preferredTransform",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "preferredTransform"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@CGAffineTransform",
        "text": "CGAffineTransform"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "preferredTransform"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "preferredTransform"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@CGAffineTransform",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CGAffineTransform",
              "text": "CGAffineTransform"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The value of this property is typically, but not always, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgaffinetransformidentity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack": {
      "abstract": [
        {
          "text": "A track in a composition that presents media of a uniform type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCompositionTrack"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCompositionTrack"
        }
      ],
      "role": "symbol",
      "title": "AVCompositionTrack",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/naturalSize": {
      "abstract": [
        {
          "text": "The natural dimensions of the media data that the track references.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "naturalSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/naturalSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "naturalSize",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/naturalsize"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/preferredTransform": {
      "abstract": [
        {
          "text": "The track’s transform preference to apply to its visual content during presentation or processing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredTransform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGAffineTransform",
          "text": "CGAffineTransform"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/preferredTransform",
      "kind": "symbol",
      "role": "symbol",
      "title": "preferredTransform",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/preferredtransform"
    },
    "doc://com.apple.documentation/documentation/coregraphics/cgaffinetransformidentity": {
      "abstract": [
        {
          "text": "The identity transform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static var "
        },
        {
          "kind": "identifier",
          "text": "identity"
        },
        {
          "kind": "text",
          "text": ": CGAffineTransform"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgaffinetransformidentity",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGAffineTransformIdentity",
      "type": "topic",
      "url": "/documentation/coregraphics/cgaffinetransformidentity"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@S@CGAffineTransform": {
      "abstract": [
        {
          "text": "An affine transformation matrix for use in drawing 2D graphics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGAffineTransform"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@CGAffineTransform",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGAffineTransform",
      "type": "topic",
      "url": "/documentation/corefoundation/cgaffinetransform"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Visual-Characteristics",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/naturalSize"
      ],
      "title": "Accessing Visual Characteristics"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrack/title",
          "value": "AVCompositionTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCompositionTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCompositionTrack"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcompositiontrack/preferredtransform"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
