{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSGridCell",
        "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/inherited"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSGridCellPlacement@NSGridCellPlacementInherited",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "inherited"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSGridCellPlacementInherited"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSGridCell.Placement.inherited"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "inherited"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell": {
      "abstract": [
        {
          "text": "An individual content area within a grid view, typically at the intersection of a row and a column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSGridCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGridCell"
        }
      ],
      "role": "symbol",
      "title": "NSGridCell",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Placement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Placement"
        }
      ],
      "role": "symbol",
      "title": "NSGridCell.Placement",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell/placement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/bottom": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSGridCell",
          "text": "NSGridCell"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSGridCellPlacement",
          "text": "Placement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/bottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGridCellPlacementBottom"
        }
      ],
      "role": "symbol",
      "title": "bottom",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell/placement/bottom"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/center": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "center"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/center",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGridCellPlacementCenter"
        }
      ],
      "role": "symbol",
      "title": "NSGridCell.Placement.center",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell/placement/center"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/fill": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fill"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/fill",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGridCellPlacementFill"
        }
      ],
      "role": "symbol",
      "title": "NSGridCell.Placement.fill",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell/placement/fill"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/inherited": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inherited"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/inherited",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGridCellPlacementInherited"
        }
      ],
      "role": "symbol",
      "title": "NSGridCell.Placement.inherited",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell/placement/inherited"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/leading": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leading"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/leading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGridCellPlacementLeading"
        }
      ],
      "role": "symbol",
      "title": "NSGridCell.Placement.leading",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell/placement/leading"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/none": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGridCellPlacementNone"
        }
      ],
      "role": "symbol",
      "title": "NSGridCell.Placement.none",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell/placement/none"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/top": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "top"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSGridCell",
          "text": "NSGridCell"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSGridCellPlacement",
          "text": "Placement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/top",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGridCellPlacementTop"
        }
      ],
      "role": "symbol",
      "title": "top",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell/placement/top"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/trailing": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trailing"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/trailing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGridCellPlacementTrailing"
        }
      ],
      "role": "symbol",
      "title": "NSGridCell.Placement.trailing",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell/placement/trailing"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Placement-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/top",
        "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/bottom",
        "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/center",
        "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/fill",
        "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/leading",
        "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/none",
        "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/trailing"
      ],
      "title": "Placement Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSGridCellPlacementInherited"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCellPlacementInherited"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Placement-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/top",
                "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/bottom",
                "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/center",
                "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/fill",
                "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/leading",
                "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/none",
                "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/trailing"
              ],
              "title": "Placement Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSGridCellPlacementInherited"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1none/title",
          "value": "NSGridCellPlacementNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCellPlacementNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell/title",
          "value": "NSGridCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1fill/title",
          "value": "NSGridCellPlacementFill"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1fill/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCellPlacementFill"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1trailing/title",
          "value": "NSGridCellPlacementTrailing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1trailing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCellPlacementTrailing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1top/title",
          "value": "NSGridCellPlacementTop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1top/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCellPlacementTop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1bottom/title",
          "value": "NSGridCellPlacementBottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1bottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCellPlacementBottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1inherited/title",
          "value": "NSGridCellPlacementInherited"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1inherited/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCellPlacementInherited"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement/title",
          "value": "NSGridCellPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCellPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCellPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1center/title",
          "value": "NSGridCellPlacementCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1center/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCellPlacementCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1leading/title",
          "value": "NSGridCellPlacementLeading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1leading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCellPlacementLeading"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsgridcell/placement/inherited"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsgridcell/placement/inherited"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
