{
  "abstract": [
    {
      "text": "A semantic group contains the element.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/semanticGroup"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@BEAccessibilityContainerType@BEAccessibilityContainerTypeSemanticGroup",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "semanticGroup"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@BEAccessibilityContainerType",
        "text": "BEAccessibilityContainerType"
      }
    ],
    "modules": [
      {
        "name": "BrowserEngineKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BEAccessibilityContainerTypeSemanticGroup"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "semanticGroup"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "semanticGroup"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@BEAccessibilityContainerType",
              "text": "BEAccessibilityContainerType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit": {
      "abstract": [
        {
          "text": "Create a browser that renders content using an alternative browser engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit",
      "kind": "symbol",
      "role": "collection",
      "title": "BrowserEngineKit",
      "type": "topic",
      "url": "/documentation/browserenginekit"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType": {
      "abstract": [
        {
          "text": "An enumeration that indicates the type of container in which an element is located.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerType"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerType"
        }
      ],
      "role": "symbol",
      "title": "BEAccessibilityContainerType",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/BEAccessibilityContainerTypeNone": {
      "abstract": [
        {
          "text": "The element isn’t in a container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerTypeNone"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/BEAccessibilityContainerTypeNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "BEAccessibilityContainerTypeNone",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/beaccessibilitycontainertypenone"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/alert": {
      "abstract": [
        {
          "text": "An alert contains the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alert"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BEAccessibilityContainerType",
          "text": "BEAccessibilityContainerType"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/alert",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerTypeAlert"
        }
      ],
      "role": "symbol",
      "title": "alert",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/alert"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/article": {
      "abstract": [
        {
          "text": "An HTML article element contains the alert.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "article"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BEAccessibilityContainerType",
          "text": "BEAccessibilityContainerType"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/article",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerTypeArticle"
        }
      ],
      "role": "symbol",
      "title": "article",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/article"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/descriptionList": {
      "abstract": [
        {
          "text": "A description list contains the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "descriptionList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BEAccessibilityContainerType",
          "text": "BEAccessibilityContainerType"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/descriptionList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerTypeDescriptionList"
        }
      ],
      "role": "symbol",
      "title": "descriptionList",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/descriptionlist"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/dialog": {
      "abstract": [
        {
          "text": "A dialog contains the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dialog"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BEAccessibilityContainerType",
          "text": "BEAccessibilityContainerType"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/dialog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerTypeDialog"
        }
      ],
      "role": "symbol",
      "title": "dialog",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/dialog"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/fieldset": {
      "abstract": [
        {
          "text": "An HTML fieldset element contains the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fieldset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BEAccessibilityContainerType",
          "text": "BEAccessibilityContainerType"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/fieldset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerTypeFieldset"
        }
      ],
      "role": "symbol",
      "title": "fieldset",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/fieldset"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/frame": {
      "abstract": [
        {
          "text": "A frame contains the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BEAccessibilityContainerType",
          "text": "BEAccessibilityContainerType"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/frame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerTypeFrame"
        }
      ],
      "role": "symbol",
      "title": "frame",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/frame"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/landmark": {
      "abstract": [
        {
          "text": "A website accessibility landmark contains the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "landmark"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BEAccessibilityContainerType",
          "text": "BEAccessibilityContainerType"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/landmark",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerTypeLandmark"
        }
      ],
      "role": "symbol",
      "title": "landmark",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/landmark"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/list": {
      "abstract": [
        {
          "text": "A list contains the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "list"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BEAccessibilityContainerType",
          "text": "BEAccessibilityContainerType"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/list",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerTypeList"
        }
      ],
      "role": "symbol",
      "title": "list",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/list"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/scrollArea": {
      "abstract": [
        {
          "text": "A scroll area contains the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BEAccessibilityContainerType",
          "text": "BEAccessibilityContainerType"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/scrollArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerTypeScrollArea"
        }
      ],
      "role": "symbol",
      "title": "scrollArea",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/scrollarea"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/semanticGroup": {
      "abstract": [
        {
          "text": "A semantic group contains the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "semanticGroup"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BEAccessibilityContainerType",
          "text": "BEAccessibilityContainerType"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/semanticGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerTypeSemanticGroup"
        }
      ],
      "role": "symbol",
      "title": "semanticGroup",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/semanticgroup"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/table": {
      "abstract": [
        {
          "text": "A table contains the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "table"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BEAccessibilityContainerType",
          "text": "BEAccessibilityContainerType"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/table",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerTypeTable"
        }
      ],
      "role": "symbol",
      "title": "table",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/table"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/tree": {
      "abstract": [
        {
          "text": "A tree contains the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tree"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BEAccessibilityContainerType",
          "text": "BEAccessibilityContainerType"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/tree",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerTypeTree"
        }
      ],
      "role": "symbol",
      "title": "tree",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/tree"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Container-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/landmark",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/table",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/list",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/fieldset",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/dialog",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/tree",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/frame",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/article",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/scrollArea",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/alert",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/descriptionList"
      ],
      "title": "Container types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BEAccessibilityContainerTypeSemanticGroup"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerTypeSemanticGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Container-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/BEAccessibilityContainerTypeNone",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/landmark",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/table",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/list",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/fieldset",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/dialog",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/tree",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/frame",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/article",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/scrollArea",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/alert",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/descriptionList"
              ],
              "title": "Container types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "BEAccessibilityContainerTypeSemanticGroup"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1fieldset/title",
          "value": "BEAccessibilityContainerTypeFieldset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1fieldset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerTypeFieldset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1frame/title",
          "value": "BEAccessibilityContainerTypeFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1frame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerTypeFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1dialog/title",
          "value": "BEAccessibilityContainerTypeDialog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1dialog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerTypeDialog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1semanticGroup/title",
          "value": "BEAccessibilityContainerTypeSemanticGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1semanticGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerTypeSemanticGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType/title",
          "value": "BEAccessibilityContainerType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1alert/title",
          "value": "BEAccessibilityContainerTypeAlert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1alert/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerTypeAlert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1landmark/title",
          "value": "BEAccessibilityContainerTypeLandmark"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1landmark/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerTypeLandmark"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1tree/title",
          "value": "BEAccessibilityContainerTypeTree"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1tree/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerTypeTree"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1article/title",
          "value": "BEAccessibilityContainerTypeArticle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1article/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerTypeArticle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1list/title",
          "value": "BEAccessibilityContainerTypeList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1list/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerTypeList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1table/title",
          "value": "BEAccessibilityContainerTypeTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1table/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerTypeTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1scrollArea/title",
          "value": "BEAccessibilityContainerTypeScrollArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1scrollArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerTypeScrollArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1descriptionList/title",
          "value": "BEAccessibilityContainerTypeDescriptionList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType~1descriptionList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerTypeDescriptionList"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/browserenginekit/beaccessibilitycontainertype/semanticgroup"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/browserenginekit/beaccessibilitycontainertype/semanticgroup"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
