{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/SetAlgebra-Implementations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "BrowserEngineKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "SetAlgebra Implementations"
  },
  "references": {
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit": {
      "abstract": [
        {
          "text": "Create a browser that renders content using an alternative browser engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit",
      "kind": "symbol",
      "role": "collection",
      "title": "BrowserEngineKit",
      "type": "topic",
      "url": "/documentation/browserenginekit"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType": {
      "abstract": [
        {
          "text": "An enumeration that indicates the type of container in which an element is located.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerType"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEAccessibilityContainerType"
        }
      ],
      "role": "symbol",
      "title": "BEAccessibilityContainerType",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/init(_:)": {
      "abstract": [
        {
          "text": "Creates a new set from a finite sequence of items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "S"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "text": "S"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/init(_:)"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/init(arrayLiteral:)": {
      "abstract": [
        {
          "text": "Creates a set containing the elements of the given array literal.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "ArrayLiteralElement",
            "type": "codeVoice"
          },
          {
            "text": " is ",
            "type": "text"
          },
          {
            "code": "Self.Element",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "arrayLiteral"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "...)"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/init(arrayLiteral:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(arrayLiteral:)",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/init(arrayliteral:)"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/isDisjoint(with:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the set has no members in",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "common with the given set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isDisjoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/isDisjoint(with:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "isDisjoint(with:)",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/isdisjoint(with:)"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/isEmpty": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the set has no elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEmpty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/isEmpty",
      "kind": "symbol",
      "role": "symbol",
      "title": "isEmpty",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/isempty"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/isStrictSubset(of:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether this set is a strict",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "subset of the given set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isStrictSubset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/isStrictSubset(of:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "isStrictSubset(of:)",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/isstrictsubset(of:)"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/isStrictSuperset(of:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether this set is a strict",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "superset of the given set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isStrictSuperset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/isStrictSuperset(of:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "isStrictSuperset(of:)",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/isstrictsuperset(of:)"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/isSubset(of:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the set is a subset of",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "another set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSubset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/isSubset(of:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "isSubset(of:)",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/issubset(of:)"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/isSuperset(of:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the set is a superset of",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "the given set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSuperset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/isSuperset(of:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "isSuperset(of:)",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/issuperset(of:)"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/subtract(_:)": {
      "abstract": [
        {
          "text": "Removes the elements of the given set from this set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtract"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/subtract(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "subtract(_:)",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/subtract(_:)"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/subtracting(_:)": {
      "abstract": [
        {
          "text": "Returns a new set containing the elements of this set that do not occur",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "in the given set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtracting"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/subtracting(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "subtracting(_:)",
      "type": "topic",
      "url": "/documentation/browserenginekit/beaccessibilitycontainertype/subtracting(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/init(_:)",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/init(arrayLiteral:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/isEmpty"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/isDisjoint(with:)",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/isStrictSubset(of:)",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/isStrictSuperset(of:)",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/isSubset(of:)",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/isSuperset(of:)",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/subtract(_:)",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEAccessibilityContainerType/subtracting(_:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType/title",
          "value": "BEAccessibilityContainerType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEAccessibilityContainerType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BEAccessibilityContainerType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/browserenginekit/beaccessibilitycontainertype/setalgebra-implementations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
