{
  "abstract": [
    {
      "text": "Creates a vibrancy effect suitable for indicating the secondary importance or relevance of supporting text and template images within a widget.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect/init(forBlurEffect:style:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect/widgetSecondary()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:objc(cs)UIVibrancyEffect(cm)widgetSecondaryVibrancyEffect",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "widgetSecondary"
      },
      {
        "kind": "text",
        "text": "() -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIVibrancyEffect",
        "text": "UIVibrancyEffect"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "widgetSecondaryVibrancyEffect"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "widgetSecondary()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "widgetSecondary"
            },
            {
              "kind": "text",
              "text": "() -> "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIVibrancyEffect",
              "text": "UIVibrancyEffect"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect": {
      "abstract": [
        {
          "text": "An object that amplifies and adjusts the color of the content layered behind a visual effect view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIVibrancyEffect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIVibrancyEffect"
        }
      ],
      "role": "symbol",
      "title": "UIVibrancyEffect",
      "type": "topic",
      "url": "/documentation/uikit/uivibrancyeffect"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect/init(forBlurEffect:style:)": {
      "abstract": [
        {
          "text": "Creates a vibrancy effect with the specified blur and style values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forBlurEffect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIBlurEffect",
          "text": "UIBlurEffect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "style"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIVibrancyEffectStyle",
          "text": "UIVibrancyEffectStyle"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect/init(forBlurEffect:style:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "effectForBlurEffect:style:"
        }
      ],
      "role": "symbol",
      "title": "init(forBlurEffect:style:)",
      "type": "topic",
      "url": "/documentation/uikit/uivibrancyeffect/init(forblureffect:style:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect/notificationCenter()": {
      "abstract": [
        {
          "text": "Creates a vibrancy effect for use in Notification Center.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notificationCenter"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIVibrancyEffect",
          "text": "UIVibrancyEffect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect/notificationCenter()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "notificationCenterVibrancyEffect"
        }
      ],
      "role": "symbol",
      "title": "notificationCenter()",
      "type": "topic",
      "url": "/documentation/uikit/uivibrancyeffect/notificationcenter()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect/widgetEffect(forVibrancyStyle:)": {
      "abstract": [
        {
          "text": "Creates a vibrancy effect for the specified style.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widgetEffect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forVibrancyStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIVibrancyEffectStyle",
          "text": "UIVibrancyEffectStyle"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIVibrancyEffect",
          "text": "UIVibrancyEffect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect/widgetEffect(forVibrancyStyle:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "widgetEffectForVibrancyStyle:"
        }
      ],
      "role": "symbol",
      "title": "widgetEffect(forVibrancyStyle:)",
      "type": "topic",
      "url": "/documentation/uikit/uivibrancyeffect/widgeteffect(forvibrancystyle:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect/widgetPrimary()": {
      "abstract": [
        {
          "text": "Creates a vibrancy effect suitable for use with certain supporting text and template images within a widget.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widgetPrimary"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIVibrancyEffect",
          "text": "UIVibrancyEffect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect/widgetPrimary()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "widgetPrimaryVibrancyEffect"
        }
      ],
      "role": "symbol",
      "title": "widgetPrimary()",
      "type": "topic",
      "url": "/documentation/uikit/uivibrancyeffect/widgetprimary()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect/widgetSecondary()": {
      "abstract": [
        {
          "text": "Creates a vibrancy effect suitable for indicating the secondary importance or relevance of supporting text and template images within a widget.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widgetSecondary"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIVibrancyEffect",
          "text": "UIVibrancyEffect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect/widgetSecondary()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "widgetSecondaryVibrancyEffect"
        }
      ],
      "role": "symbol",
      "title": "widgetSecondary()",
      "type": "topic",
      "url": "/documentation/uikit/uivibrancyeffect/widgetsecondary()"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect/widgetPrimary()",
        "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect/widgetEffect(forVibrancyStyle:)",
        "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect/notificationCenter()"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "widgetSecondaryVibrancyEffect"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "widgetSecondaryVibrancyEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect/widgetPrimary()",
                "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect/widgetEffect(forVibrancyStyle:)",
                "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect/notificationCenter()"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIVibrancyEffect",
                    "text": "UIVibrancyEffect"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "widgetSecondaryVibrancyEffect"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect/init(forBlurEffect:style:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffect~1widgetPrimary()/title",
          "value": "widgetPrimaryVibrancyEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffect~1widgetPrimary()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "widgetPrimaryVibrancyEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffect~1notificationCenter()/title",
          "value": "notificationCenterVibrancyEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffect~1notificationCenter()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "notificationCenterVibrancyEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffect~1widgetSecondary()/title",
          "value": "widgetSecondaryVibrancyEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffect~1widgetSecondary()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "widgetSecondaryVibrancyEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffect~1widgetEffect(forVibrancyStyle:)/title",
          "value": "widgetEffectForVibrancyStyle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffect~1widgetEffect(forVibrancyStyle:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "widgetEffectForVibrancyStyle:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffect/title",
          "value": "UIVibrancyEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIVibrancyEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffect/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIVibrancyEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffect~1init(forBlurEffect:style:)/title",
          "value": "effectForBlurEffect:style:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffect~1init(forBlurEffect:style:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "effectForBlurEffect:style:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uivibrancyeffect/widgetsecondary()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uivibrancyeffect/widgetsecondary()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
