{
  "abstract": [
    {
      "text": "Indicates that the user included digits after a hard pause in their dial string. A hard pause is indicated by a semicolon (",
      "type": "text"
    },
    {
      "code": ";",
      "type": "codeVoice"
    },
    {
      "text": ") and waits for further user interaction before dialing the additional digits.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.callkit/documentation/CallKit",
        "doc://com.apple.callkit/documentation/CallKit/CXPlayDTMFCallAction",
        "doc://com.apple.callkit/documentation/CallKit/CXPlayDTMFCallAction/ActionType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.callkit/documentation/CallKit/CXPlayDTMFCallAction/ActionType/hardPause"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CXPlayDTMFCallActionType@CXPlayDTMFCallActionTypeHardPause",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "hardPause"
      }
    ],
    "modules": [
      {
        "name": "CallKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CXPlayDTMFCallActionTypeHardPause"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CXPlayDTMFCallAction.ActionType.hardPause"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "hardPause"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.callkit/documentation/CallKit": {
      "abstract": [
        {
          "text": "Display the system-calling UI for your app’s VoIP services, and coordinate your calling services with other apps and the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CallKit",
      "type": "topic",
      "url": "/documentation/callkit"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXPlayDTMFCallAction": {
      "abstract": [
        {
          "text": "An encapsulation of the act of playing a dual tone multifrequency (DTMF) sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXPlayDTMFCallAction"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXPlayDTMFCallAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXPlayDTMFCallAction"
        }
      ],
      "role": "symbol",
      "title": "CXPlayDTMFCallAction",
      "type": "topic",
      "url": "/documentation/callkit/cxplaydtmfcallaction"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXPlayDTMFCallAction/ActionType": {
      "abstract": [
        {
          "text": "The types of events that generate dial tones.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ActionType"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXPlayDTMFCallAction/ActionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ActionType"
        }
      ],
      "role": "symbol",
      "title": "CXPlayDTMFCallAction.ActionType",
      "type": "topic",
      "url": "/documentation/callkit/cxplaydtmfcallaction/actiontype"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXPlayDTMFCallAction/ActionType/hardPause": {
      "abstract": [
        {
          "text": "Indicates that the user included digits after a hard pause in their dial string. A hard pause is indicated by a semicolon (",
          "type": "text"
        },
        {
          "code": ";",
          "type": "codeVoice"
        },
        {
          "text": ") and waits for further user interaction before dialing the additional digits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hardPause"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXPlayDTMFCallAction/ActionType/hardPause",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXPlayDTMFCallActionTypeHardPause"
        }
      ],
      "role": "symbol",
      "title": "CXPlayDTMFCallAction.ActionType.hardPause",
      "type": "topic",
      "url": "/documentation/callkit/cxplaydtmfcallaction/actiontype/hardpause"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXPlayDTMFCallAction/ActionType/singleTone": {
      "abstract": [
        {
          "text": "Indicates that the user tapped a digit on the in-call keypad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "singleTone"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXPlayDTMFCallAction/ActionType/singleTone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXPlayDTMFCallActionTypeSingleTone"
        }
      ],
      "role": "symbol",
      "title": "CXPlayDTMFCallAction.ActionType.singleTone",
      "type": "topic",
      "url": "/documentation/callkit/cxplaydtmfcallaction/actiontype/singletone"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXPlayDTMFCallAction/ActionType/softPause": {
      "abstract": [
        {
          "text": "Indicates that the user included digits after a soft pause in their dial string. A soft pause is indicated by a comma (",
          "type": "text"
        },
        {
          "code": ",",
          "type": "codeVoice"
        },
        {
          "text": ") and waits a few seconds before dialing the additional digits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "softPause"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXPlayDTMFCallAction/ActionType/softPause",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXPlayDTMFCallActionTypeSoftPause"
        }
      ],
      "role": "symbol",
      "title": "CXPlayDTMFCallAction.ActionType.softPause",
      "type": "topic",
      "url": "/documentation/callkit/cxplaydtmfcallaction/actiontype/softpause"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXPlayDTMFCallAction/ActionType/singleTone",
        "doc://com.apple.callkit/documentation/CallKit/CXPlayDTMFCallAction/ActionType/softPause"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CXPlayDTMFCallActionTypeHardPause"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXPlayDTMFCallActionTypeHardPause"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.callkit/documentation/CallKit",
                "doc://com.apple.callkit/documentation/CallKit/CXPlayDTMFCallAction/ActionType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/CXPlayDTMFCallAction/ActionType/singleTone",
                "doc://com.apple.callkit/documentation/CallKit/CXPlayDTMFCallAction/ActionType/softPause"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CXPlayDTMFCallActionTypeHardPause"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXPlayDTMFCallAction/title",
          "value": "CXPlayDTMFCallAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXPlayDTMFCallAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXPlayDTMFCallAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXPlayDTMFCallAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXPlayDTMFCallAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXPlayDTMFCallAction~1ActionType~1singleTone/title",
          "value": "CXPlayDTMFCallActionTypeSingleTone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXPlayDTMFCallAction~1ActionType~1singleTone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXPlayDTMFCallActionTypeSingleTone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXPlayDTMFCallAction~1ActionType~1softPause/title",
          "value": "CXPlayDTMFCallActionTypeSoftPause"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXPlayDTMFCallAction~1ActionType~1softPause/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXPlayDTMFCallActionTypeSoftPause"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXPlayDTMFCallAction~1ActionType~1hardPause/title",
          "value": "CXPlayDTMFCallActionTypeHardPause"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXPlayDTMFCallAction~1ActionType~1hardPause/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXPlayDTMFCallActionTypeHardPause"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXPlayDTMFCallAction~1ActionType/title",
          "value": "CXPlayDTMFCallActionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXPlayDTMFCallAction~1ActionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXPlayDTMFCallActionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXPlayDTMFCallAction~1ActionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXPlayDTMFCallActionType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/callkit/cxplaydtmfcallaction/actiontype/hardpause"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/callkit/cxplaydtmfcallaction/actiontype/hardpause"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
