{
  "abstract": [
    {
      "text": "The nominal frame rate of the variant’s renditions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariantVideoAttributes/nominalFrameRate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVAssetVariantVideoAttributes(py)nominalFrameRate",
    "fragments": [
      {
        "kind": "identifier",
        "text": "nominalFrameRate"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nominalFrameRate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "nominalFrameRate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:d",
              "text": "double"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nominalFrameRate"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class": {
      "abstract": [
        {
          "text": "An object that defines the video attributes for an asset variant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VideoAttributes"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VideoAttributes"
        }
      ],
      "role": "symbol",
      "title": "AVAssetVariant.VideoAttributes",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetvariant/videoattributes-swift.class"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/LayoutAttributes": {
      "abstract": [
        {
          "text": "Attributes that describe the layout of video content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LayoutAttributes"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/LayoutAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LayoutAttributes"
        }
      ],
      "role": "symbol",
      "title": "AVAssetVariant.VideoAttributes.LayoutAttributes",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetvariant/videoattributes-swift.class/layoutattributes"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/presentationSize": {
      "abstract": [
        {
          "text": "The presentation size of the variant’s renditions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentationSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/presentationSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentationSize"
        }
      ],
      "role": "symbol",
      "title": "presentationSize",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetvariant/videoattributes-swift.class/presentationsize"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/videoLayoutAttributes": {
      "abstract": [
        {
          "text": "Attributes that describe the layout of the video content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoLayoutAttributes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetVariant",
          "text": "AVAssetVariant"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetVariantVideoAttributes",
          "text": "VideoAttributes"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetVariantVideoLayoutAttributes",
          "text": "LayoutAttributes"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/videoLayoutAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "videoLayoutAttributes"
        }
      ],
      "role": "symbol",
      "title": "videoLayoutAttributes",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetvariant/videoattributes-swift.class/videolayoutattributes"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/videoRange": {
      "abstract": [
        {
          "text": "The video range of the variant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVVideoRange",
          "text": "AVVideoRange"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/videoRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "videoRange"
        }
      ],
      "role": "symbol",
      "title": "videoRange",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetvariant/videoattributes-swift.class/videorange"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariantVideoAttributes/codecTypes": {
      "abstract": [
        {
          "text": "The video sample codec types present in the variant’s renditions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "codecTypes"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariantVideoAttributes/codecTypes",
      "kind": "symbol",
      "role": "symbol",
      "title": "codecTypes",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetvariantvideoattributes/codectypes"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariantVideoAttributes/nominalFrameRate": {
      "abstract": [
        {
          "text": "The nominal frame rate of the variant’s renditions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "nominalFrameRate"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariantVideoAttributes/nominalFrameRate",
      "kind": "symbol",
      "role": "symbol",
      "title": "nominalFrameRate",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetvariantvideoattributes/nominalframerate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoRange": {
      "abstract": [
        {
          "text": "Constants that describe a video variant’s dynamic range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoRange"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoRange"
        }
      ],
      "role": "symbol",
      "title": "AVVideoRange",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideorange"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-the-Attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariantVideoAttributes/codecTypes",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/presentationSize",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/videoRange",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoRange",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/videoLayoutAttributes",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/LayoutAttributes"
      ],
      "title": "Inspecting the Attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant~1VideoAttributes-swift.class~1videoRange/title",
          "value": "videoRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant~1VideoAttributes-swift.class~1videoRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "videoRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant~1VideoAttributes-swift.class/title",
          "value": "AVAssetVariantVideoAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant~1VideoAttributes-swift.class/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetVariantVideoAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant~1VideoAttributes-swift.class/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetVariantVideoAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoRange/title",
          "value": "AVVideoRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant~1VideoAttributes-swift.class~1videoLayoutAttributes/title",
          "value": "videoLayoutAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant~1VideoAttributes-swift.class~1videoLayoutAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "videoLayoutAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant~1VideoAttributes-swift.class~1presentationSize/title",
          "value": "presentationSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant~1VideoAttributes-swift.class~1presentationSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "presentationSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant~1VideoAttributes-swift.class~1LayoutAttributes/title",
          "value": "AVAssetVariantVideoLayoutAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant~1VideoAttributes-swift.class~1LayoutAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetVariantVideoLayoutAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant~1VideoAttributes-swift.class~1LayoutAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetVariantVideoLayoutAttributes"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avassetvariantvideoattributes/nominalframerate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
