{
  "abstract": [
    {
      "text": "An action that inserts a horizontal tab.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/ControlCharacterAction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/ControlCharacterAction/horizontalTab"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSControlCharacterAction@NSControlCharacterActionHorizontalTab",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "horizontalTab"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSLayoutManager",
        "text": "NSLayoutManager"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSControlCharacterAction",
        "text": "ControlCharacterAction"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSControlCharacterActionHorizontalTab"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "horizontalTab"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "horizontalTab"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSLayoutManager",
              "text": "NSLayoutManager"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/ControlCharacterAction",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSControlCharacterAction",
              "text": "ControlCharacterAction"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager": {
      "abstract": [
        {
          "text": "An object that coordinates the layout and display of text characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLayoutManager"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutManager"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutManager",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutmanager"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/ControlCharacterAction": {
      "abstract": [
        {
          "text": "Constants that describe actions for control characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ControlCharacterAction"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/ControlCharacterAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ControlCharacterAction"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutManager.ControlCharacterAction",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutmanager/controlcharacteraction"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/ControlCharacterAction/containerBreak": {
      "abstract": [
        {
          "text": "An action that triggers a break in layout for the current container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containerBreak"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutManager",
          "text": "NSLayoutManager"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSControlCharacterAction",
          "text": "ControlCharacterAction"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/ControlCharacterAction/containerBreak",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSControlCharacterActionContainerBreak"
        }
      ],
      "role": "symbol",
      "title": "containerBreak",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutmanager/controlcharacteraction/containerbreak"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/ControlCharacterAction/horizontalTab": {
      "abstract": [
        {
          "text": "An action that inserts a horizontal tab.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "horizontalTab"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutManager",
          "text": "NSLayoutManager"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSControlCharacterAction",
          "text": "ControlCharacterAction"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/ControlCharacterAction/horizontalTab",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSControlCharacterActionHorizontalTab"
        }
      ],
      "role": "symbol",
      "title": "horizontalTab",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutmanager/controlcharacteraction/horizontaltab"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/ControlCharacterAction/lineBreak": {
      "abstract": [
        {
          "text": "An action that causes a line break.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineBreak"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutManager",
          "text": "NSLayoutManager"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSControlCharacterAction",
          "text": "ControlCharacterAction"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/ControlCharacterAction/lineBreak",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSControlCharacterActionLineBreak"
        }
      ],
      "role": "symbol",
      "title": "lineBreak",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutmanager/controlcharacteraction/linebreak"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/ControlCharacterAction/paragraphBreak": {
      "abstract": [
        {
          "text": "An action that causes a paragraph break.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paragraphBreak"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutManager",
          "text": "NSLayoutManager"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSControlCharacterAction",
          "text": "ControlCharacterAction"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/ControlCharacterAction/paragraphBreak",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSControlCharacterActionParagraphBreak"
        }
      ],
      "role": "symbol",
      "title": "paragraphBreak",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutmanager/controlcharacteraction/paragraphbreak"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/ControlCharacterAction/whitespace": {
      "abstract": [
        {
          "text": "An action that adds whitespace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "whitespace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutManager",
          "text": "NSLayoutManager"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSControlCharacterAction",
          "text": "ControlCharacterAction"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/ControlCharacterAction/whitespace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSControlCharacterActionWhitespace"
        }
      ],
      "role": "symbol",
      "title": "whitespace",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutmanager/controlcharacteraction/whitespace"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/ControlCharacterAction/zeroAdvancement": {
      "abstract": [
        {
          "text": "An action that removes the glyph from layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zeroAdvancement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutManager",
          "text": "NSLayoutManager"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSControlCharacterAction",
          "text": "ControlCharacterAction"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/ControlCharacterAction/zeroAdvancement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSControlCharacterActionZeroAdvancement"
        }
      ],
      "role": "symbol",
      "title": "zeroAdvancement",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutmanager/controlcharacteraction/zeroadvancement"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Actions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/ControlCharacterAction/containerBreak",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/ControlCharacterAction/lineBreak",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/ControlCharacterAction/paragraphBreak",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/ControlCharacterAction/whitespace",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/ControlCharacterAction/zeroAdvancement"
      ],
      "title": "Actions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSControlCharacterActionHorizontalTab"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlCharacterActionHorizontalTab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/ControlCharacterAction"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Actions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/ControlCharacterAction/containerBreak",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/ControlCharacterAction/lineBreak",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/ControlCharacterAction/paragraphBreak",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/ControlCharacterAction/whitespace",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/ControlCharacterAction/zeroAdvancement"
              ],
              "title": "Actions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSControlCharacterActionHorizontalTab"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager/title",
          "value": "NSLayoutManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1ControlCharacterAction~1zeroAdvancement/title",
          "value": "NSControlCharacterActionZeroAdvancement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1ControlCharacterAction~1zeroAdvancement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlCharacterActionZeroAdvancement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1ControlCharacterAction/title",
          "value": "NSControlCharacterAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1ControlCharacterAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlCharacterAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1ControlCharacterAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlCharacterAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1ControlCharacterAction~1containerBreak/title",
          "value": "NSControlCharacterActionContainerBreak"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1ControlCharacterAction~1containerBreak/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlCharacterActionContainerBreak"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1ControlCharacterAction~1whitespace/title",
          "value": "NSControlCharacterActionWhitespace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1ControlCharacterAction~1whitespace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlCharacterActionWhitespace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1ControlCharacterAction~1lineBreak/title",
          "value": "NSControlCharacterActionLineBreak"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1ControlCharacterAction~1lineBreak/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlCharacterActionLineBreak"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1ControlCharacterAction~1paragraphBreak/title",
          "value": "NSControlCharacterActionParagraphBreak"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1ControlCharacterAction~1paragraphBreak/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlCharacterActionParagraphBreak"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1ControlCharacterAction~1horizontalTab/title",
          "value": "NSControlCharacterActionHorizontalTab"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1ControlCharacterAction~1horizontalTab/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlCharacterActionHorizontalTab"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nslayoutmanager/controlcharacteraction/horizontaltab"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nslayoutmanager/controlcharacteraction/horizontaltab"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
