{
  "abstract": [
    {
      "text": "A parameter in an event is missing a required field.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corehaptics/documentation/CoreHaptics",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/badParameterEntry"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CHHapticErrorCode@CHHapticErrorCodeBadParameterEntry",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "badParameterEntry"
      }
    ],
    "modules": [
      {
        "name": "Core Haptics"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CHHapticErrorCodeBadParameterEntry"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CHHapticError.Code.badParameterEntry"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "badParameterEntry"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corehaptics/documentation/CoreHaptics": {
      "abstract": [
        {
          "text": "Compose and play haptic patterns to customize your iOS app’s haptic feedback.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Haptics",
      "type": "topic",
      "url": "/documentation/corehaptics"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError": {
      "abstract": [
        {
          "text": "A structure that represents a framework error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CHHapticError"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticError"
        }
      ],
      "role": "symbol",
      "title": "CHHapticError",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code": {
      "abstract": [
        {
          "text": "Error codes for framework operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CHHapticError.Code",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/code"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/badEventEntry": {
      "abstract": [
        {
          "text": "An event is missing a required field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "badEventEntry"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/badEventEntry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticErrorCodeBadEventEntry"
        }
      ],
      "role": "symbol",
      "title": "CHHapticError.Code.badEventEntry",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/code/badevententry"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/badParameterEntry": {
      "abstract": [
        {
          "text": "A parameter in an event is missing a required field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "badParameterEntry"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/badParameterEntry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticErrorCodeBadParameterEntry"
        }
      ],
      "role": "symbol",
      "title": "CHHapticError.Code.badParameterEntry",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/code/badparameterentry"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/engineNotRunning": {
      "abstract": [
        {
          "text": "Your app requested haptic playback when the engine wasn’t running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "engineNotRunning"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/engineNotRunning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticErrorCodeEngineNotRunning"
        }
      ],
      "role": "symbol",
      "title": "CHHapticError.Code.engineNotRunning",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/code/enginenotrunning"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/engineStartTimeout": {
      "abstract": [
        {
          "text": "The haptic engine timed out while starting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "engineStartTimeout"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/engineStartTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticErrorCodeEngineStartTimeout"
        }
      ],
      "role": "symbol",
      "title": "CHHapticError.Code.engineStartTimeout",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/code/enginestarttimeout"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/fileNotFound": {
      "abstract": [
        {
          "text": "The system couldn’t find an audio file or haptic asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileNotFound"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/fileNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticErrorCodeFileNotFound"
        }
      ],
      "role": "symbol",
      "title": "CHHapticError.Code.fileNotFound",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/code/filenotfound"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/insufficientPower": {
      "abstract": [
        {
          "text": "The operation failed due to power restrictions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insufficientPower"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/insufficientPower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticErrorCodeInsufficientPower"
        }
      ],
      "role": "symbol",
      "title": "CHHapticError.Code.insufficientPower",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/code/insufficientpower"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidAudioResource": {
      "abstract": [
        {
          "text": "A pattern dictionary or an event array contain a reference to an invalid audio resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidAudioResource"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidAudioResource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticErrorCodeInvalidAudioResource"
        }
      ],
      "role": "symbol",
      "title": "CHHapticError.Code.invalidAudioResource",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/code/invalidaudioresource"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidAudioSession": {
      "abstract": [
        {
          "text": "The system invalidated the audio session associated with the haptic engine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidAudioSession"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidAudioSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticErrorCodeInvalidAudioSession"
        }
      ],
      "role": "symbol",
      "title": "CHHapticError.Code.invalidAudioSession",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/code/invalidaudiosession"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidEngineParameter": {
      "abstract": [
        {
          "text": "Your app attempted to initialize the haptic engine with an invalid configuration parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidEngineParameter"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidEngineParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticErrorCodeInvalidEngineParameter"
        }
      ],
      "role": "symbol",
      "title": "CHHapticError.Code.invalidEngineParameter",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/code/invalidengineparameter"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidEventDuration": {
      "abstract": [
        {
          "text": "An event in the dictionary has an invalid duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidEventDuration"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidEventDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticErrorCodeInvalidEventDuration"
        }
      ],
      "role": "symbol",
      "title": "CHHapticError.Code.invalidEventDuration",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/code/invalideventduration"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidEventTime": {
      "abstract": [
        {
          "text": "The time of an event in the dictionary is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidEventTime"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidEventTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticErrorCodeInvalidEventTime"
        }
      ],
      "role": "symbol",
      "title": "CHHapticError.Code.invalidEventTime",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/code/invalideventtime"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidEventType": {
      "abstract": [
        {
          "text": "The type of an event in the dictionary is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidEventType"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidEventType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticErrorCodeInvalidEventType"
        }
      ],
      "role": "symbol",
      "title": "CHHapticError.Code.invalidEventType",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/code/invalideventtype"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidParameterType": {
      "abstract": [
        {
          "text": "A pattern dictionary or parameter array contains an unknown or invalid parameter type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidParameterType"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidParameterType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticErrorCodeInvalidParameterType"
        }
      ],
      "role": "symbol",
      "title": "CHHapticError.Code.invalidParameterType",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/code/invalidparametertype"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidPatternData": {
      "abstract": [
        {
          "text": "Your app passed an invalid pattern to the haptic engine or player.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidPatternData"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidPatternData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticErrorCodeInvalidPatternData"
        }
      ],
      "role": "symbol",
      "title": "CHHapticError.Code.invalidPatternData",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/code/invalidpatterndata"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidPatternDictionary": {
      "abstract": [
        {
          "text": "A pattern in the dictionary is missing a required field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidPatternDictionary"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidPatternDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticErrorCodeInvalidPatternDictionary"
        }
      ],
      "role": "symbol",
      "title": "CHHapticError.Code.invalidPatternDictionary",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/code/invalidpatterndictionary"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidPatternPlayer": {
      "abstract": [
        {
          "text": "The current pattern player is no longer valid due to a server error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidPatternPlayer"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidPatternPlayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticErrorCodeInvalidPatternPlayer"
        }
      ],
      "role": "symbol",
      "title": "CHHapticError.Code.invalidPatternPlayer",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/code/invalidpatternplayer"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/badEventEntry",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/engineNotRunning",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/engineStartTimeout",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/fileNotFound",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/insufficientPower",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidAudioResource",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidAudioSession",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidEngineParameter",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidEventDuration",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidEventTime",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidEventType",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidParameterType",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidPatternData",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidPatternDictionary",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidPatternPlayer"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CHHapticErrorCodeBadParameterEntry"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticErrorCodeBadParameterEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corehaptics/documentation/CoreHaptics",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/badEventEntry",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/engineNotRunning",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/engineStartTimeout",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/fileNotFound",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/insufficientPower",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidAudioResource",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidAudioSession",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidEngineParameter",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidEventDuration",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidEventTime",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidEventType",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidParameterType",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidPatternData",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidPatternDictionary",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code/invalidPatternPlayer"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CHHapticErrorCodeBadParameterEntry"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code/title",
          "value": "CHHapticErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1invalidPatternPlayer/title",
          "value": "CHHapticErrorCodeInvalidPatternPlayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1invalidPatternPlayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticErrorCodeInvalidPatternPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1invalidAudioResource/title",
          "value": "CHHapticErrorCodeInvalidAudioResource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1invalidAudioResource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticErrorCodeInvalidAudioResource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1invalidParameterType/title",
          "value": "CHHapticErrorCodeInvalidParameterType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1invalidParameterType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticErrorCodeInvalidParameterType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1insufficientPower/title",
          "value": "CHHapticErrorCodeInsufficientPower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1insufficientPower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticErrorCodeInsufficientPower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1badParameterEntry/title",
          "value": "CHHapticErrorCodeBadParameterEntry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1badParameterEntry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticErrorCodeBadParameterEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1engineStartTimeout/title",
          "value": "CHHapticErrorCodeEngineStartTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1engineStartTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticErrorCodeEngineStartTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1invalidPatternDictionary/title",
          "value": "CHHapticErrorCodeInvalidPatternDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1invalidPatternDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticErrorCodeInvalidPatternDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1fileNotFound/title",
          "value": "CHHapticErrorCodeFileNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1fileNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticErrorCodeFileNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1invalidEngineParameter/title",
          "value": "CHHapticErrorCodeInvalidEngineParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1invalidEngineParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticErrorCodeInvalidEngineParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1invalidEventTime/title",
          "value": "CHHapticErrorCodeInvalidEventTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1invalidEventTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticErrorCodeInvalidEventTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1badEventEntry/title",
          "value": "CHHapticErrorCodeBadEventEntry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1badEventEntry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticErrorCodeBadEventEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1engineNotRunning/title",
          "value": "CHHapticErrorCodeEngineNotRunning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1engineNotRunning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticErrorCodeEngineNotRunning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1invalidEventType/title",
          "value": "CHHapticErrorCodeInvalidEventType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1invalidEventType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticErrorCodeInvalidEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1invalidPatternData/title",
          "value": "CHHapticErrorCodeInvalidPatternData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1invalidPatternData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticErrorCodeInvalidPatternData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1invalidEventDuration/title",
          "value": "CHHapticErrorCodeInvalidEventDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1invalidEventDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticErrorCodeInvalidEventDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1invalidAudioSession/title",
          "value": "CHHapticErrorCodeInvalidAudioSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code~1invalidAudioSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticErrorCodeInvalidAudioSession"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corehaptics/chhapticerror/code/badparameterentry"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corehaptics/chhapticerror/code/badparameterentry"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
