{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKQueryOptions"]]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"tokens":[{"text":"HKQueryOptionNone","kind":"identifier"}]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"Discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"The sample’s end time must be equal to or later than the target’s start time, and the sample’s start time must be earlier than the target’s end time."}],"type":"paragraph"}],"kind":"content"}],"sections":[],"abstract":[{"text":"The sample’s time period must overlap part of the target time period.","type":"text"}],"kind":"symbol","metadata":{"title":"HKQueryOptionNone","fragments":[{"kind":"identifier","text":"HKQueryOptionNone"}],"modules":[{"name":"HealthKit"}],"externalID":"c:@E@HKQueryOptions@HKQueryOptionNone","role":"symbol","platforms":[{"deprecated":false,"introducedAt":"8.0","beta":false,"name":"iOS","unavailable":false},{"name":"iPadOS","unavailable":false,"introducedAt":"8.0","beta":false,"deprecated":false},{"name":"Mac Catalyst","unavailable":false,"introducedAt":"13.0","beta":false,"deprecated":false},{"name":"macOS","unavailable":false,"introducedAt":"13.0","beta":false,"deprecated":false},{"name":"visionOS","unavailable":false,"introducedAt":"1.0","beta":false,"deprecated":false},{"name":"watchOS","unavailable":false,"introducedAt":"2.0","beta":false,"deprecated":false}],"navigatorTitle":[{"kind":"identifier","text":"HKQueryOptionNone"}],"roleHeading":"Enumeration Case","symbolKind":"case"},"seeAlsoSections":[{"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKQueryOptions/strictStartDate","doc://com.apple.healthkit/documentation/HealthKit/HKQueryOptions/strictEndDate"],"title":"Constants","generated":true,"anchor":"Constants"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/healthkit/hkqueryoptions/hkqueryoptionnone"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.healthkit/documentation/HealthKit/HKQueryOptions/HKQueryOptionNone","interfaceLanguage":"occ"},"references":{"doc://com.apple.healthkit/documentation/HealthKit/HKQueryOptions/HKQueryOptionNone":{"fragments":[{"kind":"identifier","text":"HKQueryOptionNone"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The sample’s time period must overlap part of the target time period."}],"kind":"symbol","title":"HKQueryOptionNone","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQueryOptions/HKQueryOptionNone","url":"/documentation/healthkit/hkqueryoptions/hkqueryoptionnone"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"},"doc://com.apple.healthkit/documentation/HealthKit/HKQueryOptions/strictStartDate":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"strictStartDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@HKQueryOptions","text":"HKQueryOptions"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The sample’s start time must fall within the target time period."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKQueryOptionStrictStartDate"}],"title":"strictStartDate","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQueryOptions/strictStartDate","url":"/documentation/healthkit/hkqueryoptions/strictstartdate"},"doc://com.apple.healthkit/documentation/HealthKit/HKQueryOptions":{"url":"/documentation/healthkit/hkqueryoptions","role":"symbol","kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQueryOptions","abstract":[{"text":"Constants that describe how a sample’s time period overlaps with the target time period.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKQueryOptions"}],"navigatorTitle":[{"kind":"identifier","text":"HKQueryOptions"}],"title":"HKQueryOptions"},"doc://com.apple.healthkit/documentation/HealthKit/HKQueryOptions/strictEndDate":{"url":"/documentation/healthkit/hkqueryoptions/strictenddate","role":"symbol","kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQueryOptions/strictEndDate","abstract":[{"text":"The sample’s end time must fall within the target time period.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"strictEndDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@HKQueryOptions","text":"HKQueryOptions"}],"navigatorTitle":[{"kind":"identifier","text":"HKQueryOptionStrictEndDate"}],"title":"strictEndDate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"HKQueryOptionStrictStartDate","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQueryOptions~1strictStartDate/title"},{"value":[{"text":"HKQueryOptionStrictStartDate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQueryOptions~1strictStartDate/fragments","op":"replace"},{"value":"HKQueryOptions","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQueryOptions/title","op":"replace"},{"value":[{"text":"HKQueryOptions","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQueryOptions/fragments","op":"replace"},{"value":[{"text":"HKQueryOptions","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQueryOptions/navigatorTitle","op":"replace"},{"value":"HKQueryOptionStrictEndDate","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQueryOptions~1strictEndDate/title","op":"replace"},{"value":[{"text":"HKQueryOptionStrictEndDate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQueryOptions~1strictEndDate/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}