{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","identifier":"doc://com.externally.resolved.symbol/s:Su","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"]}]}],"metadata":{"externalID":"s:So14HKQueryOptionsV8rawValueABSu_tcfc","role":"symbol","symbolKind":"init","modules":[{"name":"HealthKit"}],"platforms":[{"introducedAt":"8.0","beta":false,"name":"iOS","unavailable":false,"deprecated":false},{"introducedAt":"8.0","beta":false,"name":"iPadOS","unavailable":false,"deprecated":false},{"introducedAt":"13.0","beta":false,"name":"Mac Catalyst","unavailable":false,"deprecated":false},{"introducedAt":"13.0","beta":false,"name":"macOS","unavailable":false,"deprecated":false},{"introducedAt":"1.0","beta":false,"name":"visionOS","unavailable":false,"deprecated":false},{"introducedAt":"2.0","beta":false,"name":"watchOS","unavailable":false,"deprecated":false}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)","roleHeading":"Initializer"},"variants":[{"paths":["/documentation/healthkit/hkqueryoptions/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKQueryOptions"]]},"abstract":[{"text":"Returns a newly initialized query option using the provided integer.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.healthkit/documentation/HealthKit/HKQueryOptions/init(rawValue:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"},"doc://com.apple.healthkit/documentation/HealthKit/HKQueryOptions":{"url":"/documentation/healthkit/hkqueryoptions","role":"symbol","kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQueryOptions","abstract":[{"text":"Constants that describe how a sample’s time period overlaps with the target time period.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKQueryOptions"}],"navigatorTitle":[{"kind":"identifier","text":"HKQueryOptions"}],"title":"HKQueryOptions"},"doc://com.apple.healthkit/documentation/HealthKit/HKQueryOptions/init(rawValue:)":{"type":"topic","title":"init(rawValue:)","url":"/documentation/healthkit/hkqueryoptions/init(rawvalue:)","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQueryOptions/init(rawValue:)","abstract":[{"type":"text","text":"Returns a newly initialized query option using the provided integer."}],"kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.externally.resolved.symbol/s:Su":{"kind":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UInt"}],"role":"symbol","title":"UInt","abstract":[{"type":"text","text":"An unsigned integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:Su","type":"topic","url":"/documentation/Swift/UInt"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"}},"variantOverrides":[{"patch":[{"op":"replace","value":"HKQueryOptions","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQueryOptions/title"},{"op":"replace","value":[{"text":"HKQueryOptions","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQueryOptions/fragments"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQueryOptions/navigatorTitle","value":[{"text":"HKQueryOptions","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}