{
  "abstract": [
    {
      "text": "Values that describe the different granularities available to make a selection.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelection"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:@E@NSTextSelectionGranularity",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Granularity"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Granularity"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSTextSelection.Granularity"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Granularity"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLocation": {
      "abstract": [
        {
          "text": "An interface you implement that represents an abstract location inside your document’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextLocation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLocation"
        }
      ],
      "role": "symbol",
      "title": "NSTextLocation",
      "type": "topic",
      "url": "/documentation/uikit/nstextlocation"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelection": {
      "abstract": [
        {
          "text": "A class that represents a single logical selection context that corresponds to an insertion point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextSelection"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelection"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelection",
      "type": "topic",
      "url": "/documentation/uikit/nstextselection"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Affinity-swift.enum": {
      "abstract": [
        {
          "text": "Values that describe the visual location of the text cursor, or the direction of the non-anchored edge of the selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Affinity"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Affinity-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Affinity"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelection.Affinity",
      "type": "topic",
      "url": "/documentation/uikit/nstextselection/affinity-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum": {
      "abstract": [
        {
          "text": "Values that describe the different granularities available to make a selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Granularity"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Granularity"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelection.Granularity",
      "type": "topic",
      "url": "/documentation/uikit/nstextselection/granularity-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/character": {
      "abstract": [
        {
          "text": "A value that represents selection by character.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "character"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/character",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionGranularityCharacter"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelection.Granularity.character",
      "type": "topic",
      "url": "/documentation/uikit/nstextselection/granularity-swift.enum/character"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextselection/granularity-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/line": {
      "abstract": [
        {
          "text": "A value that represents selection by line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "line"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/line",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionGranularityLine"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelection.Granularity.line",
      "type": "topic",
      "url": "/documentation/uikit/nstextselection/granularity-swift.enum/line"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/paragraph": {
      "abstract": [
        {
          "text": "A value that represents selection by paragraph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paragraph"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/paragraph",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionGranularityParagraph"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelection.Granularity.paragraph",
      "type": "topic",
      "url": "/documentation/uikit/nstextselection/granularity-swift.enum/paragraph"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/sentence": {
      "abstract": [
        {
          "text": "A value that represents selection by sentence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sentence"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/sentence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionGranularitySentence"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelection.Granularity.sentence",
      "type": "topic",
      "url": "/documentation/uikit/nstextselection/granularity-swift.enum/sentence"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/word": {
      "abstract": [
        {
          "text": "A value that represents selection by word.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "word"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/word",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionGranularityWord"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelection.Granularity.word",
      "type": "topic",
      "url": "/documentation/uikit/nstextselection/granularity-swift.enum/word"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/affinity-swift.property": {
      "abstract": [
        {
          "text": "Returns the selection affinity of the text selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "affinity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextSelection",
          "text": "NSTextSelection"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextSelectionAffinity",
          "text": "Affinity"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/affinity-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "affinity"
        }
      ],
      "role": "symbol",
      "title": "affinity",
      "type": "topic",
      "url": "/documentation/uikit/nstextselection/affinity-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/anchorPositionOffset": {
      "abstract": [
        {
          "text": "Represents the anchor position offset from the beginning of a line fragment in the visual order for the initial tap or click location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "anchorPositionOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/anchorPositionOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "anchorPositionOffset"
        }
      ],
      "role": "symbol",
      "title": "anchorPositionOffset",
      "type": "topic",
      "url": "/documentation/uikit/nstextselection/anchorpositionoffset"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/granularity-swift.property": {
      "abstract": [
        {
          "text": "The granularity of the selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "granularity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextSelection",
          "text": "NSTextSelection"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextSelectionGranularity",
          "text": "Granularity"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/granularity-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "granularity"
        }
      ],
      "role": "symbol",
      "title": "granularity",
      "type": "topic",
      "url": "/documentation/uikit/nstextselection/granularity-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/isLogical": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the framework interprets the selection as logical or visual.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isLogical"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/isLogical",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "logical"
        }
      ],
      "role": "symbol",
      "title": "isLogical",
      "type": "topic",
      "url": "/documentation/uikit/nstextselection/islogical"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/isTransient": {
      "abstract": [
        {
          "text": "A Boolean value that indicates transient text selection during drag handling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isTransient"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/isTransient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "transient"
        }
      ],
      "role": "symbol",
      "title": "isTransient",
      "type": "topic",
      "url": "/documentation/uikit/nstextselection/istransient"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/secondarySelectionLocation": {
      "abstract": [
        {
          "text": "Specifies the secondary character location when user taps or clicks at a directional boundary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secondarySelectionLocation"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSTextLocation",
          "text": "NSTextLocation"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/secondarySelectionLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "secondarySelectionLocation"
        }
      ],
      "role": "symbol",
      "title": "secondarySelectionLocation",
      "type": "topic",
      "url": "/documentation/uikit/nstextselection/secondaryselectionlocation"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/textRanges": {
      "abstract": [
        {
          "text": "Represents an array of noncontiguous logical ranges in the selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textRanges"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextRange",
          "text": "NSTextRange"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/textRanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textRanges"
        }
      ],
      "role": "symbol",
      "title": "textRanges",
      "type": "topic",
      "url": "/documentation/uikit/nstextselection/textranges"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/typingAttributes": {
      "abstract": [
        {
          "text": "The template attributes the framework uses for characters that replace the contents of this selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typingAttributes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringKey",
          "text": "Key"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/typingAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "typingAttributes"
        }
      ],
      "role": "symbol",
      "title": "typingAttributes",
      "type": "topic",
      "url": "/documentation/uikit/nstextselection/typingattributes"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Characteristics-of-a-selection",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/affinity-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Affinity-swift.enum",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/anchorPositionOffset",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/granularity-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/isLogical",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/isTransient",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/secondarySelectionLocation",
        "doc://com.apple.uikit/documentation/UIKit/NSTextLocation",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/textRanges",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/typingAttributes"
      ],
      "title": "Characteristics of a selection"
    }
  ],
  "topicSections": [
    {
      "anchor": "Degrees-of-granularity",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/character",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/word",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/paragraph",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/line",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/sentence"
      ],
      "title": "Degrees of granularity"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTextSelectionGranularity"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionGranularity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionGranularity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Degrees-of-granularity",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/character",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/word",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/paragraph",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/line",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/sentence"
              ],
              "title": "Degrees of granularity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Characteristics-of-a-selection",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/affinity-swift.property",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Affinity-swift.enum",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/anchorPositionOffset",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/granularity-swift.property",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/isLogical",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/isTransient",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/secondarySelectionLocation",
                "doc://com.apple.uikit/documentation/UIKit/NSTextLocation",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/textRanges",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/typingAttributes"
              ],
              "title": "Characteristics of a selection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSTextSelectionGranularity"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1typingAttributes/title",
          "value": "typingAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1typingAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "typingAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLocation/title",
          "value": "NSTextLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1Granularity-swift.enum~1sentence/title",
          "value": "NSTextSelectionGranularitySentence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1Granularity-swift.enum~1sentence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionGranularitySentence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1isTransient/title",
          "value": "transient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1isTransient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "transient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1isLogical/title",
          "value": "logical"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1isLogical/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "logical"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1secondarySelectionLocation/title",
          "value": "secondarySelectionLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1secondarySelectionLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "secondarySelectionLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1Granularity-swift.enum~1character/title",
          "value": "NSTextSelectionGranularityCharacter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1Granularity-swift.enum~1character/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionGranularityCharacter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1Granularity-swift.enum~1line/title",
          "value": "NSTextSelectionGranularityLine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1Granularity-swift.enum~1line/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionGranularityLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1affinity-swift.property/title",
          "value": "affinity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1affinity-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "affinity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1Granularity-swift.enum/title",
          "value": "NSTextSelectionGranularity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1Granularity-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionGranularity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1Granularity-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionGranularity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1Affinity-swift.enum/title",
          "value": "NSTextSelectionAffinity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1Affinity-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionAffinity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1Affinity-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionAffinity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection/title",
          "value": "NSTextSelection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1Granularity-swift.enum~1paragraph/title",
          "value": "NSTextSelectionGranularityParagraph"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1Granularity-swift.enum~1paragraph/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionGranularityParagraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1Granularity-swift.enum~1word/title",
          "value": "NSTextSelectionGranularityWord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1Granularity-swift.enum~1word/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionGranularityWord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1anchorPositionOffset/title",
          "value": "anchorPositionOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1anchorPositionOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "anchorPositionOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1granularity-swift.property/title",
          "value": "granularity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1granularity-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "granularity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1textRanges/title",
          "value": "textRanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1textRanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "textRanges"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/nstextselection/granularity-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/nstextselection/granularity-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
