{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAEnvironment"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAEnvironment/MechanismBiometry"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "LocalAuthentication",
    "externalID": "c:objc(cs)LAEnvironmentMechanismBiometry",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MechanismBiometry"
      }
    ],
    "modules": [
      {
        "name": "Local Authentication"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MechanismBiometry"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "LAEnvironment.MechanismBiometry"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MechanismBiometry"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication": {
      "abstract": [
        {
          "text": "Authenticate users biometrically or with a passphrase they already know.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication",
      "kind": "symbol",
      "role": "collection",
      "title": "Local Authentication",
      "type": "topic",
      "url": "/documentation/localauthentication"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAEnvironment": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LAEnvironment"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAEnvironment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAEnvironment"
        }
      ],
      "role": "symbol",
      "title": "LAEnvironment",
      "type": "topic",
      "url": "/documentation/localauthentication/laenvironment"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAEnvironment/Mechanism": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Mechanism"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAEnvironment/Mechanism",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Mechanism"
        }
      ],
      "role": "symbol",
      "title": "LAEnvironment.Mechanism",
      "type": "topic",
      "url": "/documentation/localauthentication/laenvironment/mechanism"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAEnvironment/MechanismBiometry": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MechanismBiometry"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAEnvironment/MechanismBiometry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MechanismBiometry"
        }
      ],
      "role": "symbol",
      "title": "LAEnvironment.MechanismBiometry",
      "type": "topic",
      "url": "/documentation/localauthentication/laenvironment/mechanismbiometry"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAEnvironment/MechanismBiometry/biometryType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "biometryType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LABiometryType",
          "text": "LABiometryType"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAEnvironment/MechanismBiometry/biometryType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "biometryType"
        }
      ],
      "role": "symbol",
      "title": "biometryType",
      "type": "topic",
      "url": "/documentation/localauthentication/laenvironment/mechanismbiometry/biometrytype"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAEnvironment/MechanismBiometry/builtInSensorInaccessible": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "builtInSensorInaccessible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAEnvironment/MechanismBiometry/builtInSensorInaccessible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "builtInSensorInaccessible"
        }
      ],
      "role": "symbol",
      "title": "builtInSensorInaccessible",
      "type": "topic",
      "url": "/documentation/localauthentication/laenvironment/mechanismbiometry/builtinsensorinaccessible"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAEnvironment/MechanismBiometry/isEnrolled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEnrolled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAEnvironment/MechanismBiometry/isEnrolled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isEnrolled"
        }
      ],
      "role": "symbol",
      "title": "isEnrolled",
      "type": "topic",
      "url": "/documentation/localauthentication/laenvironment/mechanismbiometry/isenrolled"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAEnvironment/MechanismBiometry/isLockedOut": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isLockedOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAEnvironment/MechanismBiometry/isLockedOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isLockedOut"
        }
      ],
      "role": "symbol",
      "title": "isLockedOut",
      "type": "topic",
      "url": "/documentation/localauthentication/laenvironment/mechanismbiometry/islockedout"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAEnvironment/MechanismBiometry/stateHash": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stateHash"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAEnvironment/MechanismBiometry/stateHash",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stateHash"
        }
      ],
      "role": "symbol",
      "title": "stateHash",
      "type": "topic",
      "url": "/documentation/localauthentication/laenvironment/mechanismbiometry/statehash"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAEnvironment/Mechanism"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAEnvironment/MechanismBiometry/biometryType",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAEnvironment/MechanismBiometry/builtInSensorInaccessible",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAEnvironment/MechanismBiometry/isEnrolled",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAEnvironment/MechanismBiometry/isLockedOut",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAEnvironment/MechanismBiometry/stateHash"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "LAEnvironmentMechanismBiometry"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAEnvironmentMechanismBiometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LAEnvironmentMechanismBiometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAEnvironment/MechanismBiometry/biometryType",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAEnvironment/MechanismBiometry/builtInSensorInaccessible",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAEnvironment/MechanismBiometry/isEnrolled",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAEnvironment/MechanismBiometry/isLockedOut",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAEnvironment/MechanismBiometry/stateHash"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAEnvironment/Mechanism"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "LAEnvironmentMechanismBiometry"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAEnvironment/Mechanism",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)LAEnvironmentMechanism",
                    "text": "LAEnvironmentMechanism"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAEnvironment~1MechanismBiometry~1stateHash/title",
          "value": "stateHash"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAEnvironment~1MechanismBiometry~1stateHash/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "stateHash"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAEnvironment~1MechanismBiometry~1isLockedOut/title",
          "value": "isLockedOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAEnvironment~1MechanismBiometry~1isLockedOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isLockedOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAEnvironment/title",
          "value": "LAEnvironment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAEnvironment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAEnvironment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LAEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAEnvironment~1MechanismBiometry~1isEnrolled/title",
          "value": "isEnrolled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAEnvironment~1MechanismBiometry~1isEnrolled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isEnrolled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAEnvironment~1Mechanism/title",
          "value": "LAEnvironmentMechanism"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAEnvironment~1Mechanism/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAEnvironmentMechanism"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAEnvironment~1Mechanism/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LAEnvironmentMechanism"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAEnvironment~1MechanismBiometry/title",
          "value": "LAEnvironmentMechanismBiometry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAEnvironment~1MechanismBiometry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAEnvironmentMechanismBiometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAEnvironment~1MechanismBiometry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LAEnvironmentMechanismBiometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAEnvironment~1MechanismBiometry~1biometryType/title",
          "value": "biometryType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAEnvironment~1MechanismBiometry~1biometryType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "biometryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAEnvironment~1MechanismBiometry~1builtInSensorInaccessible/title",
          "value": "builtInSensorInaccessible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAEnvironment~1MechanismBiometry~1builtInSensorInaccessible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "builtInSensorInaccessible"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/localauthentication/laenvironment/mechanismbiometry"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/localauthentication/laenvironment/mechanismbiometry"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
