{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.glkit/documentation/GLKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.glkit/documentation/GLKit/glkit-structures"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "GLKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "GLKit Structures"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.glkit/documentation/GLKit": {
      "abstract": [
        {
          "text": "Speed up OpenGL ES or OpenGL app development. Use math libraries, background texture loading, pre-created shader effects, and a standard view and view controller to implement your rendering loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GLKit",
      "type": "topic",
      "url": "/documentation/glkit"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderError"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderError"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderError",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadererror-swift.struct"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVertexAttributeParameters": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVertexAttributeParameters"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVertexAttributeParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVertexAttributeParameters"
        }
      ],
      "role": "symbol",
      "title": "GLKVertexAttributeParameters",
      "type": "topic",
      "url": "/documentation/glkit/glkvertexattributeparameters"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkit-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkit-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKit Constants",
      "type": "topic",
      "url": "/documentation/glkit/glkit-constants"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkit-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkit-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKit Data Types",
      "type": "topic",
      "url": "/documentation/glkit/glkit-data-types"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkit-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkit-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKit Enumerations",
      "type": "topic",
      "url": "/documentation/glkit/glkit-enumerations"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkit-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkit-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKit Functions",
      "type": "topic",
      "url": "/documentation/glkit/glkit-functions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/glkit-enumerations",
        "doc://com.apple.glkit/documentation/GLKit/glkit-constants",
        "doc://com.apple.glkit/documentation/GLKit/glkit-functions",
        "doc://com.apple.glkit/documentation/GLKit/glkit-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Structures",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct"
      ],
      "title": "Structures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Structures",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKVertexAttributeParameters"
              ],
              "title": "Structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/glkit-enumerations",
                "doc://com.apple.glkit/documentation/GLKit/glkit-constants",
                "doc://com.apple.glkit/documentation/GLKit/glkit-functions",
                "doc://com.apple.glkit/documentation/GLKit/glkit-data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVertexAttributeParameters/title",
          "value": "GLKVertexAttributeParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVertexAttributeParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVertexAttributeParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVertexAttributeParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVertexAttributeParameters"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/glkit/glkit-structures"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/glkit/glkit-structures"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
