{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.glkit/documentation/GLKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.glkit/documentation/GLKit/glkit-enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "GLKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "GLKit Enumerations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.glkit/documentation/GLKit": {
      "abstract": [
        {
          "text": "Speed up OpenGL ES or OpenGL app development. Use math libraries, background texture loading, pre-created shader effects, and a standard view and view controller to implement your rendering loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GLKit",
      "type": "topic",
      "url": "/documentation/glkit"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKFogMode": {
      "abstract": [
        {
          "text": "A mode that describes how the fog component is calculated for the fragment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKFogMode"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKFogMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKFogMode"
        }
      ],
      "role": "symbol",
      "title": "GLKFogMode",
      "type": "topic",
      "url": "/documentation/glkit/glkfogmode"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKLightingType": {
      "abstract": [
        {
          "text": "A constant that describes how lighting is calculated by an effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKLightingType"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKLightingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKLightingType"
        }
      ],
      "role": "symbol",
      "title": "GLKLightingType",
      "type": "topic",
      "url": "/documentation/glkit/glklightingtype"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureEnvMode": {
      "abstract": [
        {
          "text": "The mode used to combine the texture with other color components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureEnvMode"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureEnvMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureEnvMode"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureEnvMode",
      "type": "topic",
      "url": "/documentation/glkit/glktextureenvmode"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfoAlphaState": {
      "abstract": [
        {
          "text": "Values that describe the alpha information stored in a source image’s pixel data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureInfoAlphaState"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfoAlphaState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureInfoAlphaState"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureInfoAlphaState",
      "type": "topic",
      "url": "/documentation/glkit/glktextureinfoalphastate"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfoOrigin": {
      "abstract": [
        {
          "text": "The location of the origin in the original source image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureInfoOrigin"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfoOrigin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureInfoOrigin"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureInfoOrigin",
      "type": "topic",
      "url": "/documentation/glkit/glktextureinfoorigin"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Values to be returned when a texture loader encounters an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderError.Code",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadererror-swift.struct/code"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureTarget": {
      "abstract": [
        {
          "text": "The kind of texture pointed to by the property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureTarget"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureTarget",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureTarget"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureTarget",
      "type": "topic",
      "url": "/documentation/glkit/glktexturetarget"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKViewDrawableColorFormat": {
      "abstract": [
        {
          "text": "The format of the color renderbuffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKViewDrawableColorFormat"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKViewDrawableColorFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKViewDrawableColorFormat"
        }
      ],
      "role": "symbol",
      "title": "GLKViewDrawableColorFormat",
      "type": "topic",
      "url": "/documentation/glkit/glkviewdrawablecolorformat"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKViewDrawableDepthFormat": {
      "abstract": [
        {
          "text": "The format of the depth renderbuffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKViewDrawableDepthFormat"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKViewDrawableDepthFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKViewDrawableDepthFormat"
        }
      ],
      "role": "symbol",
      "title": "GLKViewDrawableDepthFormat",
      "type": "topic",
      "url": "/documentation/glkit/glkviewdrawabledepthformat"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKViewDrawableMultisample": {
      "abstract": [
        {
          "text": "The format of the multisampling buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKViewDrawableMultisample"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKViewDrawableMultisample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKViewDrawableMultisample"
        }
      ],
      "role": "symbol",
      "title": "GLKViewDrawableMultisample",
      "type": "topic",
      "url": "/documentation/glkit/glkviewdrawablemultisample"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKViewDrawableStencilFormat": {
      "abstract": [
        {
          "text": "The format of the stencil renderbuffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKViewDrawableStencilFormat"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKViewDrawableStencilFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKViewDrawableStencilFormat"
        }
      ],
      "role": "symbol",
      "title": "GLKViewDrawableStencilFormat",
      "type": "topic",
      "url": "/documentation/glkit/glkviewdrawablestencilformat"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkit-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkit-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKit Constants",
      "type": "topic",
      "url": "/documentation/glkit/glkit-constants"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkit-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkit-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKit Data Types",
      "type": "topic",
      "url": "/documentation/glkit/glkit-data-types"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkit-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkit-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKit Functions",
      "type": "topic",
      "url": "/documentation/glkit/glkit-functions"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkit-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkit-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKit Structures",
      "type": "topic",
      "url": "/documentation/glkit/glkit-structures"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/glkit-structures",
        "doc://com.apple.glkit/documentation/GLKit/glkit-constants",
        "doc://com.apple.glkit/documentation/GLKit/glkit-functions",
        "doc://com.apple.glkit/documentation/GLKit/glkit-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKFogMode",
        "doc://com.apple.glkit/documentation/GLKit/GLKLightingType",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureEnvMode",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfoAlphaState",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfoOrigin",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureTarget",
        "doc://com.apple.glkit/documentation/GLKit/GLKViewDrawableColorFormat",
        "doc://com.apple.glkit/documentation/GLKit/GLKViewDrawableDepthFormat",
        "doc://com.apple.glkit/documentation/GLKit/GLKViewDrawableMultisample",
        "doc://com.apple.glkit/documentation/GLKit/GLKViewDrawableStencilFormat"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKFogMode",
                "doc://com.apple.glkit/documentation/GLKit/GLKLightingType",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureEnvMode",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfoAlphaState",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfoOrigin",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureTarget",
                "doc://com.apple.glkit/documentation/GLKit/GLKViewDrawableColorFormat",
                "doc://com.apple.glkit/documentation/GLKit/GLKViewDrawableDepthFormat",
                "doc://com.apple.glkit/documentation/GLKit/GLKViewDrawableMultisample",
                "doc://com.apple.glkit/documentation/GLKit/GLKViewDrawableStencilFormat"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/glkit-structures",
                "doc://com.apple.glkit/documentation/GLKit/glkit-constants",
                "doc://com.apple.glkit/documentation/GLKit/glkit-functions",
                "doc://com.apple.glkit/documentation/GLKit/glkit-data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKViewDrawableMultisample/title",
          "value": "GLKViewDrawableMultisample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKViewDrawableMultisample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKViewDrawableMultisample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKViewDrawableMultisample/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKViewDrawableMultisample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfoOrigin/title",
          "value": "GLKTextureInfoOrigin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfoOrigin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureInfoOrigin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfoOrigin/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureInfoOrigin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfoAlphaState/title",
          "value": "GLKTextureInfoAlphaState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfoAlphaState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureInfoAlphaState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfoAlphaState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureInfoAlphaState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKFogMode/title",
          "value": "GLKFogMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKFogMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKFogMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKFogMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKFogMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureTarget/title",
          "value": "GLKTextureTarget"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureTarget/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureTarget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureTarget/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureTarget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKViewDrawableDepthFormat/title",
          "value": "GLKViewDrawableDepthFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKViewDrawableDepthFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKViewDrawableDepthFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKViewDrawableDepthFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKViewDrawableDepthFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKViewDrawableStencilFormat/title",
          "value": "GLKViewDrawableStencilFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKViewDrawableStencilFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKViewDrawableStencilFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKViewDrawableStencilFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKViewDrawableStencilFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureEnvMode/title",
          "value": "GLKTextureEnvMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureEnvMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureEnvMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureEnvMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureEnvMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code/title",
          "value": "GLKTextureLoaderError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKViewDrawableColorFormat/title",
          "value": "GLKViewDrawableColorFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKViewDrawableColorFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKViewDrawableColorFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKViewDrawableColorFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKViewDrawableColorFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKLightingType/title",
          "value": "GLKLightingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKLightingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKLightingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKLightingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKLightingType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/glkit/glkit-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/glkit/glkit-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
