{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.glkit/documentation/GLKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.glkit/documentation/GLKit/glkit-math-utilities"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "GLKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "GLKit Math Utilities"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Math routines without a specific type associated with them.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.glkit/documentation/GLKit": {
      "abstract": [
        {
          "text": "Speed up OpenGL ES or OpenGL app development. Use math libraries, background texture loading, pre-created shader effects, and a standard view and view controller to implement your rendering loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GLKit",
      "type": "topic",
      "url": "/documentation/glkit"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMathDegreesToRadians(_:)": {
      "abstract": [
        {
          "text": "Converts an angle measured in degrees to radians.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMathDegreesToRadians"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMathDegreesToRadians(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMathDegreesToRadians"
        }
      ],
      "role": "symbol",
      "title": "GLKMathDegreesToRadians(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmathdegreestoradians(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMathProject(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Projects a point in object space into the window coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMathProject"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMathProject(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMathProject"
        }
      ],
      "role": "symbol",
      "title": "GLKMathProject(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmathproject(_:_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMathRadiansToDegrees(_:)": {
      "abstract": [
        {
          "text": "Converts an angle measured in radians to degrees.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMathRadiansToDegrees"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMathRadiansToDegrees(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMathRadiansToDegrees"
        }
      ],
      "role": "symbol",
      "title": "GLKMathRadiansToDegrees(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmathradianstodegrees(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMathUnproject(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Projects a point in view space into object space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMathUnproject"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMathUnproject(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMathUnproject"
        }
      ],
      "role": "symbol",
      "title": "GLKMathUnproject(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmathunproject(_:_:_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStack": {
      "abstract": [
        {
          "text": "An opaque type that represents a stack of 4 x 4 matrices, providing support for hierarchical transform modeling and similar tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrixStack"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrixStack"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrixStack",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrixstack"
    },
    "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKMatrix2(_:)": {
      "abstract": [
        {
          "text": "Returns a string that represents the contents of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStringFromGLKMatrix2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKMatrix2(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStringFromGLKMatrix2"
        }
      ],
      "role": "symbol",
      "title": "NSStringFromGLKMatrix2(_:)",
      "type": "topic",
      "url": "/documentation/glkit/nsstringfromglkmatrix2(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKMatrix3(_:)": {
      "abstract": [
        {
          "text": "Returns a string that represents the contents of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStringFromGLKMatrix3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKMatrix3(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStringFromGLKMatrix3"
        }
      ],
      "role": "symbol",
      "title": "NSStringFromGLKMatrix3(_:)",
      "type": "topic",
      "url": "/documentation/glkit/nsstringfromglkmatrix3(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKMatrix4(_:)": {
      "abstract": [
        {
          "text": "Returns a string that represents the contents of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStringFromGLKMatrix4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKMatrix4(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStringFromGLKMatrix4"
        }
      ],
      "role": "symbol",
      "title": "NSStringFromGLKMatrix4(_:)",
      "type": "topic",
      "url": "/documentation/glkit/nsstringfromglkmatrix4(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKQuaternion(_:)": {
      "abstract": [
        {
          "text": "Returns a string that represents the contents of a quaternion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStringFromGLKQuaternion"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKQuaternion(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStringFromGLKQuaternion"
        }
      ],
      "role": "symbol",
      "title": "NSStringFromGLKQuaternion(_:)",
      "type": "topic",
      "url": "/documentation/glkit/nsstringfromglkquaternion(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKVector2(_:)": {
      "abstract": [
        {
          "text": "Returns a string that represents the contents of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStringFromGLKVector2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKVector2(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStringFromGLKVector2"
        }
      ],
      "role": "symbol",
      "title": "NSStringFromGLKVector2(_:)",
      "type": "topic",
      "url": "/documentation/glkit/nsstringfromglkvector2(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKVector3(_:)": {
      "abstract": [
        {
          "text": "Returns a string that represents the contents of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStringFromGLKVector3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKVector3(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStringFromGLKVector3"
        }
      ],
      "role": "symbol",
      "title": "NSStringFromGLKVector3(_:)",
      "type": "topic",
      "url": "/documentation/glkit/nsstringfromglkvector3(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKVector4(_:)": {
      "abstract": [
        {
          "text": "Returns a string that represents the contents of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStringFromGLKVector4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKVector4(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStringFromGLKVector4"
        }
      ],
      "role": "symbol",
      "title": "NSStringFromGLKVector4(_:)",
      "type": "topic",
      "url": "/documentation/glkit/nsstringfromglkvector4(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkmatrix3-pcl": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkmatrix3-pcl",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKMatrix3",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3-pcl"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkmatrix4-pce": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkmatrix4-pce",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKMatrix4",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4-pce"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkquaternion-pc6": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkquaternion-pc6",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKQuaternion",
      "type": "topic",
      "url": "/documentation/glkit/glkquaternion-pc6"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkvector2-pbj": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkvector2-pbj",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKVector2",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2-pbj"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkvector3-pbt": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkvector3-pbt",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKVector3",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3-pbt"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkvector4-pbk": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkvector4-pbk",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKVector4",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4-pbk"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Math-Utilties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStack",
        "doc://com.apple.glkit/documentation/GLKit/glkmatrix3-pcl",
        "doc://com.apple.glkit/documentation/GLKit/glkmatrix4-pce",
        "doc://com.apple.glkit/documentation/GLKit/glkvector2-pbj",
        "doc://com.apple.glkit/documentation/GLKit/glkvector3-pbt",
        "doc://com.apple.glkit/documentation/GLKit/glkvector4-pbk",
        "doc://com.apple.glkit/documentation/GLKit/glkquaternion-pc6"
      ],
      "title": "Math Utilties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Converting-Angles",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKMathDegreesToRadians(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMathRadiansToDegrees(_:)"
      ],
      "title": "Converting Angles"
    },
    {
      "anchor": "Projecting-Vectors",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKMathProject(_:_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMathUnproject(_:_:_:_:_:)"
      ],
      "title": "Projecting Vectors"
    },
    {
      "anchor": "Obtaining-String-Descriptions",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKMatrix2(_:)",
        "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKMatrix3(_:)",
        "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKMatrix4(_:)",
        "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKVector2(_:)",
        "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKVector3(_:)",
        "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKVector4(_:)",
        "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKQuaternion(_:)"
      ],
      "title": "Obtaining String Descriptions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Converting-Angles",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKMathDegreesToRadians(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMathRadiansToDegrees(_:)"
              ],
              "title": "Converting Angles"
            },
            {
              "anchor": "Projecting-Vectors",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKMathProject(_:_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMathUnproject(_:_:_:_:_:)"
              ],
              "title": "Projecting Vectors"
            },
            {
              "anchor": "Obtaining-String-Descriptions",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKMatrix2(_:)",
                "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKMatrix3(_:)",
                "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKMatrix4(_:)",
                "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKVector2(_:)",
                "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKVector3(_:)",
                "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKVector4(_:)",
                "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKQuaternion(_:)"
              ],
              "title": "Obtaining String Descriptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Math-Utilties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStack",
                "doc://com.apple.glkit/documentation/GLKit/glkmatrix3-pcl",
                "doc://com.apple.glkit/documentation/GLKit/glkmatrix4-pce",
                "doc://com.apple.glkit/documentation/GLKit/glkvector2-pbj",
                "doc://com.apple.glkit/documentation/GLKit/glkvector3-pbt",
                "doc://com.apple.glkit/documentation/GLKit/glkvector4-pbk",
                "doc://com.apple.glkit/documentation/GLKit/glkquaternion-pc6"
              ],
              "title": "Math Utilties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMathUnproject(_:_:_:_:_:)/title",
          "value": "GLKMathUnproject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMathUnproject(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMathUnproject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMathProject(_:_:_:_:)/title",
          "value": "GLKMathProject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMathProject(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMathProject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1NSStringFromGLKMatrix4(_:)/title",
          "value": "NSStringFromGLKMatrix4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1NSStringFromGLKMatrix4(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringFromGLKMatrix4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMathRadiansToDegrees(_:)/title",
          "value": "GLKMathRadiansToDegrees"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMathRadiansToDegrees(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMathRadiansToDegrees"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMathDegreesToRadians(_:)/title",
          "value": "GLKMathDegreesToRadians"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMathDegreesToRadians(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMathDegreesToRadians"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStack/title",
          "value": "GLKMatrixStackRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrixStackRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrixStackRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1NSStringFromGLKMatrix3(_:)/title",
          "value": "NSStringFromGLKMatrix3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1NSStringFromGLKMatrix3(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringFromGLKMatrix3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1NSStringFromGLKVector3(_:)/title",
          "value": "NSStringFromGLKVector3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1NSStringFromGLKVector3(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringFromGLKVector3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1NSStringFromGLKVector4(_:)/title",
          "value": "NSStringFromGLKVector4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1NSStringFromGLKVector4(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringFromGLKVector4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1NSStringFromGLKQuaternion(_:)/title",
          "value": "NSStringFromGLKQuaternion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1NSStringFromGLKQuaternion(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringFromGLKQuaternion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1NSStringFromGLKVector2(_:)/title",
          "value": "NSStringFromGLKVector2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1NSStringFromGLKVector2(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringFromGLKVector2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1NSStringFromGLKMatrix2(_:)/title",
          "value": "NSStringFromGLKMatrix2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1NSStringFromGLKMatrix2(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringFromGLKMatrix2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/glkit/glkit-math-utilities"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/glkit/glkit-math-utilities"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
