{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.glkit/documentation/GLKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.glkit/documentation/GLKit/glkit-effects-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "GLKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "GLKit Effects Constants"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "GLKit effects implement shaders to perform their calculations. These shaders require vertex data to be provided by your application. All of the effects provided by GLKit use a consistent set of indices to reference vertex data provided by your application. When your application enables a vertex attribute array by calling the ",
              "type": "text"
            },
            {
              "code": "glEnableVertexAttribArray",
              "type": "codeVoice"
            },
            {
              "text": " function, or specifies the vertex attribute pointer by calling the ",
              "type": "text"
            },
            {
              "code": "glVertexAttribPointer",
              "type": "codeVoice"
            },
            {
              "text": " function, it uses one of these constants to specify the ",
              "type": "text"
            },
            {
              "code": "index",
              "type": "codeVoice"
            },
            {
              "text": " parameter.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.glkit/documentation/GLKit": {
      "abstract": [
        {
          "text": "Speed up OpenGL ES or OpenGL app development. Use math libraries, background texture loading, pre-created shader effects, and a standard view and view controller to implement your rendering loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GLKit",
      "type": "topic",
      "url": "/documentation/glkit"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKEffectProperty": {
      "abstract": [
        {
          "text": "The abstract superclass for configuration information used in GLKit rendering effects.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKEffectProperty"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKEffectProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKEffectProperty"
        }
      ],
      "role": "symbol",
      "title": "GLKEffectProperty",
      "type": "topic",
      "url": "/documentation/glkit/glkeffectproperty"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKEffectPropertyFog": {
      "abstract": [
        {
          "text": "Fog drawing information for use in GLKit rendering effects.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKEffectPropertyFog"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKEffectPropertyFog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKEffectPropertyFog"
        }
      ],
      "role": "symbol",
      "title": "GLKEffectPropertyFog",
      "type": "topic",
      "url": "/documentation/glkit/glkeffectpropertyfog"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKEffectPropertyLight": {
      "abstract": [
        {
          "text": "Lighting information for use in GLKit rendering effects.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKEffectPropertyLight"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKEffectPropertyLight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKEffectPropertyLight"
        }
      ],
      "role": "symbol",
      "title": "GLKEffectPropertyLight",
      "type": "topic",
      "url": "/documentation/glkit/glkeffectpropertylight"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKEffectPropertyMaterial": {
      "abstract": [
        {
          "text": "Surface appearance properties for use in GLKit rendering effects.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKEffectPropertyMaterial"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKEffectPropertyMaterial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKEffectPropertyMaterial"
        }
      ],
      "role": "symbol",
      "title": "GLKEffectPropertyMaterial",
      "type": "topic",
      "url": "/documentation/glkit/glkeffectpropertymaterial"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKEffectPropertyTexture": {
      "abstract": [
        {
          "text": "Texture drawing parameters for use in GLKit rendering effects.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKEffectPropertyTexture"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKEffectPropertyTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKEffectPropertyTexture"
        }
      ],
      "role": "symbol",
      "title": "GLKEffectPropertyTexture",
      "type": "topic",
      "url": "/documentation/glkit/glkeffectpropertytexture"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKEffectPropertyTransform": {
      "abstract": [
        {
          "text": "Coordinate transform information for use in GLKit rendering effects.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKEffectPropertyTransform"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKEffectPropertyTransform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKEffectPropertyTransform"
        }
      ],
      "role": "symbol",
      "title": "GLKEffectPropertyTransform",
      "type": "topic",
      "url": "/documentation/glkit/glkeffectpropertytransform"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVertexAttrib": {
      "abstract": [
        {
          "text": "Values used as indices in OpenGL code to associate vertex data with an attribute in a named shader effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVertexAttrib"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVertexAttrib",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVertexAttrib"
        }
      ],
      "role": "symbol",
      "title": "GLKVertexAttrib",
      "type": "topic",
      "url": "/documentation/glkit/glkvertexattrib"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Rendering-Effect-Parameters",
      "generated": true,
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKEffectProperty",
        "doc://com.apple.glkit/documentation/GLKit/GLKEffectPropertyFog",
        "doc://com.apple.glkit/documentation/GLKit/GLKEffectPropertyLight",
        "doc://com.apple.glkit/documentation/GLKit/GLKEffectPropertyTexture",
        "doc://com.apple.glkit/documentation/GLKit/GLKEffectPropertyMaterial",
        "doc://com.apple.glkit/documentation/GLKit/GLKEffectPropertyTransform"
      ],
      "title": "Rendering Effect Parameters"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKVertexAttrib"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKVertexAttrib"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Rendering-Effect-Parameters",
              "generated": true,
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKEffectProperty",
                "doc://com.apple.glkit/documentation/GLKit/GLKEffectPropertyFog",
                "doc://com.apple.glkit/documentation/GLKit/GLKEffectPropertyLight",
                "doc://com.apple.glkit/documentation/GLKit/GLKEffectPropertyTexture",
                "doc://com.apple.glkit/documentation/GLKit/GLKEffectPropertyMaterial",
                "doc://com.apple.glkit/documentation/GLKit/GLKEffectPropertyTransform"
              ],
              "title": "Rendering Effect Parameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKEffectProperty/title",
          "value": "GLKEffectProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKEffectProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKEffectProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKEffectProperty/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKEffectProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKEffectPropertyTransform/title",
          "value": "GLKEffectPropertyTransform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKEffectPropertyTransform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKEffectPropertyTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKEffectPropertyTransform/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKEffectPropertyTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKEffectPropertyLight/title",
          "value": "GLKEffectPropertyLight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKEffectPropertyLight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKEffectPropertyLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKEffectPropertyLight/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKEffectPropertyLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKEffectPropertyFog/title",
          "value": "GLKEffectPropertyFog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKEffectPropertyFog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKEffectPropertyFog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKEffectPropertyFog/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKEffectPropertyFog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKEffectPropertyTexture/title",
          "value": "GLKEffectPropertyTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKEffectPropertyTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKEffectPropertyTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKEffectPropertyTexture/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKEffectPropertyTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVertexAttrib/title",
          "value": "GLKVertexAttrib"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVertexAttrib/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVertexAttrib"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVertexAttrib/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVertexAttrib"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKEffectPropertyMaterial/title",
          "value": "GLKEffectPropertyMaterial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKEffectPropertyMaterial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKEffectPropertyMaterial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKEffectPropertyMaterial/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKEffectPropertyMaterial"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/glkit/glkit-effects-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/glkit/glkit-effects-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
