{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.glkit/documentation/GLKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.glkit/documentation/GLKit/glkit-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "GLKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "GLKit Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.glkit/documentation/GLKit": {
      "abstract": [
        {
          "text": "Speed up OpenGL ES or OpenGL app development. Use math libraries, background texture loading, pre-created shader effects, and a standard view and view controller to implement your rendering loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GLKit",
      "type": "topic",
      "url": "/documentation/glkit"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderApplyPremultiplication": {
      "abstract": [
        {
          "text": "Whether image data should be premultiplied before being loaded into the sharegroup.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderApplyPremultiplication"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderApplyPremultiplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderApplyPremultiplication"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderApplyPremultiplication",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloaderapplypremultiplication"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderErrorDomain": {
      "abstract": [
        {
          "text": "The error domain used by GLKit when returning texture loading errors.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderErrorDomain",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadererrordomain"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderErrorKey": {
      "abstract": [
        {
          "text": "A key used to retrieve an error string from an error object userinfo dictionary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderErrorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderErrorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderErrorKey"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderErrorKey",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadererrorkey"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderGLErrorKey": {
      "abstract": [
        {
          "text": "A key used to retrieve additional information from an error object’s userinfo dictionary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderGLErrorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderGLErrorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderGLErrorKey"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderGLErrorKey",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloaderglerrorkey"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderGenerateMipmaps": {
      "abstract": [
        {
          "text": "Whether or not to create mipmaps for a texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderGenerateMipmaps"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderGenerateMipmaps",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderGenerateMipmaps"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderGenerateMipmaps",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadergeneratemipmaps"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderGrayscaleAsAlpha": {
      "abstract": [
        {
          "text": "Whether or not to treat greyscale image data as alpha information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderGrayscaleAsAlpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderGrayscaleAsAlpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderGrayscaleAsAlpha"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderGrayscaleAsAlpha",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadergrayscaleasalpha"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderOriginBottomLeft": {
      "abstract": [
        {
          "text": "Whether or not to vertically flip image data to match OpenGL’s coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderOriginBottomLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderOriginBottomLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderOriginBottomLeft"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderOriginBottomLeft",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloaderoriginbottomleft"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderSRGB": {
      "abstract": [
        {
          "text": "Whether or not to treat texture image data as sRGB data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderSRGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderSRGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderSRGB"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderSRGB",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadersrgb"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLK_SSE3_INTRINSICS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLK_SSE3_INTRINSICS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLK_SSE3_INTRINSICS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLK_SSE3_INTRINSICS"
        }
      ],
      "role": "symbol",
      "title": "GLK_SSE3_INTRINSICS",
      "type": "topic",
      "url": "/documentation/glkit/glk_sse3_intrinsics"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkit-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkit-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKit Data Types",
      "type": "topic",
      "url": "/documentation/glkit/glkit-data-types"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkit-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkit-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKit Enumerations",
      "type": "topic",
      "url": "/documentation/glkit/glkit-enumerations"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkit-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkit-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKit Functions",
      "type": "topic",
      "url": "/documentation/glkit/glkit-functions"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkit-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkit-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKit Structures",
      "type": "topic",
      "url": "/documentation/glkit/glkit-structures"
    },
    "doc://com.apple.glkit/documentation/GLKit/kGLKModelErrorDomain": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kGLKModelErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/kGLKModelErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kGLKModelErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "kGLKModelErrorDomain",
      "type": "topic",
      "url": "/documentation/glkit/kglkmodelerrordomain"
    },
    "doc://com.apple.glkit/documentation/GLKit/kGLKModelErrorKey": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kGLKModelErrorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/kGLKModelErrorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kGLKModelErrorKey"
        }
      ],
      "role": "symbol",
      "title": "kGLKModelErrorKey",
      "type": "topic",
      "url": "/documentation/glkit/kglkmodelerrorkey"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/glkit-structures",
        "doc://com.apple.glkit/documentation/GLKit/glkit-enumerations",
        "doc://com.apple.glkit/documentation/GLKit/glkit-functions",
        "doc://com.apple.glkit/documentation/GLKit/glkit-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderApplyPremultiplication",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderErrorDomain",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderErrorKey",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderGLErrorKey",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderGenerateMipmaps",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderGrayscaleAsAlpha",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderOriginBottomLeft",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderSRGB",
        "doc://com.apple.glkit/documentation/GLKit/GLK_SSE3_INTRINSICS",
        "doc://com.apple.glkit/documentation/GLKit/kGLKModelErrorDomain",
        "doc://com.apple.glkit/documentation/GLKit/kGLKModelErrorKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderApplyPremultiplication",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderErrorDomain",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderErrorKey",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderGLErrorKey",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderGenerateMipmaps",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderGrayscaleAsAlpha",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderOriginBottomLeft",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderSRGB",
                "doc://com.apple.glkit/documentation/GLKit/GLK_SSE3_INTRINSICS",
                "doc://com.apple.glkit/documentation/GLKit/kGLKModelErrorDomain",
                "doc://com.apple.glkit/documentation/GLKit/kGLKModelErrorKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/glkit-structures",
                "doc://com.apple.glkit/documentation/GLKit/glkit-enumerations",
                "doc://com.apple.glkit/documentation/GLKit/glkit-functions",
                "doc://com.apple.glkit/documentation/GLKit/glkit-data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderGenerateMipmaps/title",
          "value": "GLKTextureLoaderGenerateMipmaps"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderGenerateMipmaps/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderGenerateMipmaps"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1kGLKModelErrorDomain/title",
          "value": "kGLKModelErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1kGLKModelErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kGLKModelErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLK_SSE3_INTRINSICS/title",
          "value": "GLK_SSE3_INTRINSICS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLK_SSE3_INTRINSICS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLK_SSE3_INTRINSICS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderSRGB/title",
          "value": "GLKTextureLoaderSRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderSRGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderSRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderOriginBottomLeft/title",
          "value": "GLKTextureLoaderOriginBottomLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderOriginBottomLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderOriginBottomLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderErrorKey/title",
          "value": "GLKTextureLoaderErrorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderErrorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderErrorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderGLErrorKey/title",
          "value": "GLKTextureLoaderGLErrorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderGLErrorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderGLErrorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderGrayscaleAsAlpha/title",
          "value": "GLKTextureLoaderGrayscaleAsAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderGrayscaleAsAlpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderGrayscaleAsAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1kGLKModelErrorKey/title",
          "value": "kGLKModelErrorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1kGLKModelErrorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kGLKModelErrorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderErrorDomain/title",
          "value": "GLKTextureLoaderErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderApplyPremultiplication/title",
          "value": "GLKTextureLoaderApplyPremultiplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderApplyPremultiplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderApplyPremultiplication"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/glkit/glkit-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/glkit/glkit-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
