{
  "abstract": [
    {
      "text": "Multiplies a ",
      "type": "text"
    },
    {
      "code": "4x4",
      "type": "codeVoice"
    },
    {
      "text": " matrix by a ",
      "type": "text"
    },
    {
      "code": "3",
      "type": "codeVoice"
    },
    {
      "text": "-component vector.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.glkit/documentation/GLKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4MultiplyVector3(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@GLKMatrix4MultiplyVector3",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GLKMatrix4MultiplyVector3"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "text": "GLKMatrix4"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "text": "GLKVector3"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "text": "GLKVector3"
      }
    ],
    "modules": [
      {
        "name": "GLKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GLKMatrix4MultiplyVector3"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "GLKMatrix4MultiplyVector3(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GLKMatrix4MultiplyVector3"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "matrixLeft"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "GLKMatrix4"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "vectorRight"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "GLKVector3"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "kind": "typeIdentifier",
              "text": "GLKVector3"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The matrix multiplicand.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "matrixLeft"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The vector multiplier.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "vectorRight"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A new vector created by multiplying the matrix by the vector.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The input vector is treated as it were a 4-component vector with a ",
              "type": "text"
            },
            {
              "code": "w",
              "type": "codeVoice"
            },
            {
              "text": "-component of ",
              "type": "text"
            },
            {
              "code": "0.0",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.glkit/documentation/GLKit": {
      "abstract": [
        {
          "text": "Speed up OpenGL ES or OpenGL app development. Use math libraries, background texture loading, pre-created shader effects, and a standard view and view controller to implement your rendering loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GLKit",
      "type": "topic",
      "url": "/documentation/glkit"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4MultiplyAndProjectVector3(_:_:)": {
      "abstract": [
        {
          "text": "Multiplies a ",
          "type": "text"
        },
        {
          "code": "4x4",
          "type": "codeVoice"
        },
        {
          "text": " matrix by a position vector to create a vector in homogenous coordinates, then projects the result to a ",
          "type": "text"
        },
        {
          "code": "3",
          "type": "codeVoice"
        },
        {
          "text": "-component vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix4MultiplyAndProjectVector3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4MultiplyAndProjectVector3(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4MultiplyAndProjectVector3"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix4MultiplyAndProjectVector3(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4multiplyandprojectvector3(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4MultiplyAndProjectVector3Array(_:_:_:)": {
      "abstract": [
        {
          "text": "Multiplies a ",
          "type": "text"
        },
        {
          "code": "4x4",
          "type": "codeVoice"
        },
        {
          "text": " matrix by an array of ",
          "type": "text"
        },
        {
          "code": "3",
          "type": "codeVoice"
        },
        {
          "text": "-component vectors. Each result is projected back to ",
          "type": "text"
        },
        {
          "code": "3",
          "type": "codeVoice"
        },
        {
          "text": "-component vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix4MultiplyAndProjectVector3Array"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4MultiplyAndProjectVector3Array(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4MultiplyAndProjectVector3Array"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix4MultiplyAndProjectVector3Array(_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4multiplyandprojectvector3array(_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4MultiplyVector3(_:_:)": {
      "abstract": [
        {
          "text": "Multiplies a ",
          "type": "text"
        },
        {
          "code": "4x4",
          "type": "codeVoice"
        },
        {
          "text": " matrix by a ",
          "type": "text"
        },
        {
          "code": "3",
          "type": "codeVoice"
        },
        {
          "text": "-component vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix4MultiplyVector3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4MultiplyVector3(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4MultiplyVector3"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix4MultiplyVector3(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4multiplyvector3(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4MultiplyVector3Array(_:_:_:)": {
      "abstract": [
        {
          "text": "Multiplies a ",
          "type": "text"
        },
        {
          "code": "4x4",
          "type": "codeVoice"
        },
        {
          "text": " matrix by an array of ",
          "type": "text"
        },
        {
          "code": "3",
          "type": "codeVoice"
        },
        {
          "text": "-component vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix4MultiplyVector3Array"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4MultiplyVector3Array(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4MultiplyVector3Array"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix4MultiplyVector3Array(_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4multiplyvector3array(_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4MultiplyVector3ArrayWithTranslation(_:_:_:)": {
      "abstract": [
        {
          "text": "Multiplies a ",
          "type": "text"
        },
        {
          "code": "4x4",
          "type": "codeVoice"
        },
        {
          "text": " matrix by an array of ",
          "type": "text"
        },
        {
          "code": "3",
          "type": "codeVoice"
        },
        {
          "text": "-component vectors, applying translation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix4MultiplyVector3ArrayWithTranslation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4MultiplyVector3ArrayWithTranslation(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4MultiplyVector3ArrayWithTranslation"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix4MultiplyVector3ArrayWithTranslation(_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4multiplyvector3arraywithtranslation(_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4MultiplyVector3WithTranslation(_:_:)": {
      "abstract": [
        {
          "text": "Multiplies a ",
          "type": "text"
        },
        {
          "code": "4x4",
          "type": "codeVoice"
        },
        {
          "text": " matrix by a ",
          "type": "text"
        },
        {
          "code": "3",
          "type": "codeVoice"
        },
        {
          "text": "-component vector, applying translation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix4MultiplyVector3WithTranslation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4MultiplyVector3WithTranslation(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4MultiplyVector3WithTranslation"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix4MultiplyVector3WithTranslation(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4multiplyvector3withtranslation(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4MultiplyVector4(_:_:)": {
      "abstract": [
        {
          "text": "Multiplies a ",
          "type": "text"
        },
        {
          "code": "4x4",
          "type": "codeVoice"
        },
        {
          "text": " matrix by a ",
          "type": "text"
        },
        {
          "code": "4",
          "type": "codeVoice"
        },
        {
          "text": "-component vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix4MultiplyVector4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4MultiplyVector4(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4MultiplyVector4"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix4MultiplyVector4(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4multiplyvector4(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4MultiplyVector4Array(_:_:_:)": {
      "abstract": [
        {
          "text": "Multiplies a ",
          "type": "text"
        },
        {
          "code": "4x4",
          "type": "codeVoice"
        },
        {
          "text": " matrix by an array of ",
          "type": "text"
        },
        {
          "code": "4",
          "type": "codeVoice"
        },
        {
          "text": "-component vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix4MultiplyVector4Array"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4MultiplyVector4Array(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4MultiplyVector4Array"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix4MultiplyVector4Array(_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4multiplyvector4array(_:_:_:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Performing-Mathematical-Operations-on-Vectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4MultiplyVector3Array(_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4MultiplyVector3WithTranslation(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4MultiplyVector3ArrayWithTranslation(_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4MultiplyVector4(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4MultiplyVector4Array(_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4MultiplyAndProjectVector3(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4MultiplyAndProjectVector3Array(_:_:_:)"
      ],
      "title": "Performing Mathematical Operations on Vectors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GLKMatrix4MultiplyVector3"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4MultiplyVector3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.glkit/documentation/GLKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Performing-Mathematical-Operations-on-Vectors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4MultiplyVector3Array(_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4MultiplyVector3WithTranslation(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4MultiplyVector3ArrayWithTranslation(_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4MultiplyVector4(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4MultiplyVector4Array(_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4MultiplyAndProjectVector3(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4MultiplyAndProjectVector3Array(_:_:_:)"
              ],
              "title": "Performing Mathematical Operations on Vectors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@U@_GLKVector3",
                    "text": "GLKVector3"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GLKMatrix4MultiplyVector3"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@U@_GLKMatrix4",
                    "text": "GLKMatrix4"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "matrixLeft"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@U@_GLKVector3",
                    "text": "GLKVector3"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "vectorRight"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The matrix multiplicand.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "matrixLeft"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The vector multiplier.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "vectorRight"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A new vector created by multiplying the matrix by the vector.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4MultiplyAndProjectVector3Array(_:_:_:)/title",
          "value": "GLKMatrix4MultiplyAndProjectVector3Array"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4MultiplyAndProjectVector3Array(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4MultiplyAndProjectVector3Array"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4MultiplyAndProjectVector3(_:_:)/title",
          "value": "GLKMatrix4MultiplyAndProjectVector3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4MultiplyAndProjectVector3(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4MultiplyAndProjectVector3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4MultiplyVector3(_:_:)/title",
          "value": "GLKMatrix4MultiplyVector3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4MultiplyVector3(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4MultiplyVector3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4MultiplyVector4Array(_:_:_:)/title",
          "value": "GLKMatrix4MultiplyVector4Array"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4MultiplyVector4Array(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4MultiplyVector4Array"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4MultiplyVector3ArrayWithTranslation(_:_:_:)/title",
          "value": "GLKMatrix4MultiplyVector3ArrayWithTranslation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4MultiplyVector3ArrayWithTranslation(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4MultiplyVector3ArrayWithTranslation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4MultiplyVector3Array(_:_:_:)/title",
          "value": "GLKMatrix4MultiplyVector3Array"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4MultiplyVector3Array(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4MultiplyVector3Array"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4MultiplyVector4(_:_:)/title",
          "value": "GLKMatrix4MultiplyVector4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4MultiplyVector4(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4MultiplyVector4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4MultiplyVector3WithTranslation(_:_:)/title",
          "value": "GLKMatrix4MultiplyVector3WithTranslation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4MultiplyVector3WithTranslation(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4MultiplyVector3WithTranslation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/glkit/glkmatrix4multiplyvector3(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/glkit/glkmatrix4multiplyvector3(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
