{
  "abstract": [
    {
      "text": "Returns a new ",
      "type": "text"
    },
    {
      "code": "3x3",
      "type": "codeVoice"
    },
    {
      "text": " matrix created by concatenating a matrix with a rotation around a vector.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.glkit/documentation/GLKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateWithVector4(_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@GLKMatrix3RotateWithVector4",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GLKMatrix3RotateWithVector4"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "text": "GLKMatrix3"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sf",
        "text": "Float"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "text": "GLKVector4"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "text": "GLKMatrix3"
      }
    ],
    "modules": [
      {
        "name": "GLKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GLKMatrix3RotateWithVector4"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "GLKMatrix3RotateWithVector4(_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GLKMatrix3RotateWithVector4"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "matrix"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "GLKMatrix3"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "radians"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sf",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sf",
              "text": "Float"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "axisVector"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "GLKVector4"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "kind": "typeIdentifier",
              "text": "GLKMatrix3"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The source matrix.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "matrix"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The angle of the rotation (a positive angle is counterclockwise).",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "radians"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The axis to perform the rotation around.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "axisVector"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A new matrix.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The w-component of the ",
              "type": "text"
            },
            {
              "code": "axisVector",
              "type": "codeVoice"
            },
            {
              "text": " parameter is ignored.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.glkit/documentation/GLKit": {
      "abstract": [
        {
          "text": "Speed up OpenGL ES or OpenGL app development. Use math libraries, background texture loading, pre-created shader effects, and a standard view and view controller to implement your rendering loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GLKit",
      "type": "topic",
      "url": "/documentation/glkit"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Add(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by performing a component-wise addition of two matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3Add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Add(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3Add"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3Add(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3add(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Invert(_:_:)": {
      "abstract": [
        {
          "text": "Returns the inverse of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3Invert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Invert(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3Invert"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3Invert(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3invert(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3InvertAndTranspose(_:_:)": {
      "abstract": [
        {
          "text": "Returns the inverse transpose of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3InvertAndTranspose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3InvertAndTranspose(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3InvertAndTranspose"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3InvertAndTranspose(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3invertandtranspose(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Multiply(_:_:)": {
      "abstract": [
        {
          "text": "Returns the product of two matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3Multiply"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Multiply(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3Multiply"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3Multiply(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3multiply(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Rotate(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by concatenating a matrix with a rotation around a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3Rotate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Rotate(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3Rotate"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3Rotate(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3rotate(_:_:_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateWithVector3(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by concatenating a matrix with a rotation around a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3RotateWithVector3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateWithVector3(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3RotateWithVector3"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3RotateWithVector3(_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3rotatewithvector3(_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateWithVector4(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by concatenating a matrix with a rotation around a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3RotateWithVector4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateWithVector4(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3RotateWithVector4"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3RotateWithVector4(_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3rotatewithvector4(_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateX(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by concatenating a matrix with a rotation around the x-axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3RotateX"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateX(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3RotateX"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3RotateX(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3rotatex(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateY(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by concatenating a matrix with a rotation around the y-axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3RotateY"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateY(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3RotateY"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3RotateY(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3rotatey(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateZ(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by concatenating a matrix with a rotation around the z-axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3RotateZ"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateZ(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3RotateZ"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3RotateZ(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3rotatez(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Scale(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by concatenating a matrix with a scaling transform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3Scale"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Scale(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3Scale"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3Scale(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3scale(_:_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3ScaleWithVector3(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by concatenating a matrix with a scaling transform defined by a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3ScaleWithVector3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3ScaleWithVector3(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3ScaleWithVector3"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3ScaleWithVector3(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3scalewithvector3(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3ScaleWithVector4(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by concatenating a matrix with a scaling transform defined by a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3ScaleWithVector4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3ScaleWithVector4(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3ScaleWithVector4"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3ScaleWithVector4(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3scalewithvector4(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Subtract(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by performing a component-wise subtraction of two matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3Subtract"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Subtract(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3Subtract"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3Subtract(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3subtract(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Transpose(_:)": {
      "abstract": [
        {
          "text": "Returns the transpose of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3Transpose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Transpose(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3Transpose"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3Transpose(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3transpose(_:)"
    },
    "doc://com.externally.resolved.symbol/s:Sf": {
      "abstract": [
        {
          "text": "A single-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sf",
      "kind": "symbol",
      "role": "symbol",
      "title": "Float",
      "type": "topic",
      "url": "/documentation/Swift/Float"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Performing-Mathematical-Operations-on-Matrices",
      "generated": true,
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Invert(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Transpose(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3InvertAndTranspose(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Multiply(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Rotate(_:_:_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateWithVector3(_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateX(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateY(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateZ(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Scale(_:_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3ScaleWithVector3(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3ScaleWithVector4(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Add(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Subtract(_:_:)"
      ],
      "title": "Performing Mathematical Operations on Matrices"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GLKMatrix3RotateWithVector4"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3RotateWithVector4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.glkit/documentation/GLKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Performing-Mathematical-Operations-on-Matrices",
              "generated": true,
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Invert(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Transpose(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3InvertAndTranspose(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Multiply(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Rotate(_:_:_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateWithVector3(_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateX(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateY(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateZ(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Scale(_:_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3ScaleWithVector3(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3ScaleWithVector4(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Add(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Subtract(_:_:)"
              ],
              "title": "Performing Mathematical Operations on Matrices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@U@_GLKMatrix3",
                    "text": "GLKMatrix3"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GLKMatrix3RotateWithVector4"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@U@_GLKMatrix3",
                    "text": "GLKMatrix3"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "matrix"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:f",
                    "text": "float"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "radians"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@U@_GLKVector4",
                    "text": "GLKVector4"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "axisVector"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The source matrix.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "matrix"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The angle of the rotation (a positive angle is counterclockwise).",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "radians"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The axis to perform the rotation around.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "axisVector"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A new matrix.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3ScaleWithVector3(_:_:)/title",
          "value": "GLKMatrix3ScaleWithVector3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3ScaleWithVector3(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3ScaleWithVector3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3RotateZ(_:_:)/title",
          "value": "GLKMatrix3RotateZ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3RotateZ(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3RotateZ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3RotateX(_:_:)/title",
          "value": "GLKMatrix3RotateX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3RotateX(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3RotateX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3RotateWithVector3(_:_:_:)/title",
          "value": "GLKMatrix3RotateWithVector3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3RotateWithVector3(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3RotateWithVector3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3RotateY(_:_:)/title",
          "value": "GLKMatrix3RotateY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3RotateY(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3RotateY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Invert(_:_:)/title",
          "value": "GLKMatrix3Invert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Invert(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3Invert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Add(_:_:)/title",
          "value": "GLKMatrix3Add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Add(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3Add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Rotate(_:_:_:_:_:)/title",
          "value": "GLKMatrix3Rotate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Rotate(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3Rotate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Scale(_:_:_:_:)/title",
          "value": "GLKMatrix3Scale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Scale(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3Scale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Multiply(_:_:)/title",
          "value": "GLKMatrix3Multiply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Multiply(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3Multiply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Transpose(_:)/title",
          "value": "GLKMatrix3Transpose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Transpose(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3Transpose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Subtract(_:_:)/title",
          "value": "GLKMatrix3Subtract"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Subtract(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3Subtract"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3InvertAndTranspose(_:_:)/title",
          "value": "GLKMatrix3InvertAndTranspose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3InvertAndTranspose(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3InvertAndTranspose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3RotateWithVector4(_:_:_:)/title",
          "value": "GLKMatrix3RotateWithVector4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3RotateWithVector4(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3RotateWithVector4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3ScaleWithVector4(_:_:)/title",
          "value": "GLKMatrix3ScaleWithVector4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3ScaleWithVector4(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3ScaleWithVector4"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/glkit/glkmatrix3rotatewithvector4(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/glkit/glkmatrix3rotatewithvector4(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
