{
  "abstract": [
    {
      "text": "Returns a new ",
      "type": "text"
    },
    {
      "code": "3x3",
      "type": "codeVoice"
    },
    {
      "text": " matrix with one column replaced by a new vector.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.glkit/documentation/GLKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3SetColumn(_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@GLKMatrix3SetColumn",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GLKMatrix3SetColumn"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "text": "GLKMatrix3"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "text": "GLKVector3"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "text": "GLKMatrix3"
      }
    ],
    "modules": [
      {
        "name": "GLKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GLKMatrix3SetColumn"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "GLKMatrix3SetColumn(_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GLKMatrix3SetColumn"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "matrix"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "GLKMatrix3"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "column"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "vector"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "GLKVector3"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "kind": "typeIdentifier",
              "text": "GLKMatrix3"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The source matrix.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "matrix"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The index of the column to replace, which must be a number between ",
                  "type": "text"
                },
                {
                  "code": "0",
                  "type": "codeVoice"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "code": "2",
                  "type": "codeVoice"
                },
                {
                  "text": ", inclusive.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "column"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A vector holding the replacement component values.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "vector"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A new matrix.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.glkit/documentation/GLKit": {
      "abstract": [
        {
          "text": "Speed up OpenGL ES or OpenGL app development. Use math libraries, background texture loading, pre-created shader effects, and a standard view and view controller to implement your rendering loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GLKit",
      "type": "topic",
      "url": "/documentation/glkit"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3GetColumn(_:_:)": {
      "abstract": [
        {
          "text": "Retrieves a column from a ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3GetColumn"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3GetColumn(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3GetColumn"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3GetColumn(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3getcolumn(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3GetMatrix2(_:)": {
      "abstract": [
        {
          "text": "Returns the upper-left ",
          "type": "text"
        },
        {
          "code": "2x2",
          "type": "codeVoice"
        },
        {
          "text": " section of a ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3GetMatrix2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3GetMatrix2(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3GetMatrix2"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3GetMatrix2(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3getmatrix2(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3GetRow(_:_:)": {
      "abstract": [
        {
          "text": "Retrieves a row from a ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3GetRow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3GetRow(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3GetRow"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3GetRow(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3getrow(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3SetColumn(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix with one column replaced by a new vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3SetColumn"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3SetColumn(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3SetColumn"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3SetColumn(_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3setcolumn(_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3SetRow(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix with one row replaced by a new vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3SetRow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3SetRow(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3SetRow"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3SetRow(_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3setrow(_:_:_:)"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-With-Parts-of-a-Matrix",
      "generated": true,
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3GetMatrix2(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3GetColumn(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3GetRow(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3SetRow(_:_:_:)"
      ],
      "title": "Working With Parts of a Matrix"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GLKMatrix3SetColumn"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3SetColumn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.glkit/documentation/GLKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-With-Parts-of-a-Matrix",
              "generated": true,
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3GetMatrix2(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3GetColumn(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3GetRow(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3SetRow(_:_:_:)"
              ],
              "title": "Working With Parts of a Matrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@U@_GLKMatrix3",
                    "text": "GLKMatrix3"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GLKMatrix3SetColumn"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@U@_GLKMatrix3",
                    "text": "GLKMatrix3"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "matrix"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:I",
                    "text": "int"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "column"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@U@_GLKVector3",
                    "text": "GLKVector3"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "vector"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The source matrix.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "matrix"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The index of the column to replace, which must be a number between ",
                        "type": "text"
                      },
                      {
                        "code": "0",
                        "type": "codeVoice"
                      },
                      {
                        "text": " and ",
                        "type": "text"
                      },
                      {
                        "code": "2",
                        "type": "codeVoice"
                      },
                      {
                        "text": ", inclusive.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "column"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A vector holding the replacement component values.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "vector"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A new matrix.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3SetRow(_:_:_:)/title",
          "value": "GLKMatrix3SetRow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3SetRow(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3SetRow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3GetMatrix2(_:)/title",
          "value": "GLKMatrix3GetMatrix2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3GetMatrix2(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3GetMatrix2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3GetRow(_:_:)/title",
          "value": "GLKMatrix3GetRow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3GetRow(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3GetRow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3GetColumn(_:_:)/title",
          "value": "GLKMatrix3GetColumn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3GetColumn(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3GetColumn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3SetColumn(_:_:_:)/title",
          "value": "GLKMatrix3SetColumn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3SetColumn(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3SetColumn"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/glkit/glkmatrix3setcolumn(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/glkit/glkmatrix3setcolumn(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
