{
  "abstract": [
    {
      "text": "Returns the upper-left ",
      "type": "text"
    },
    {
      "code": "2x2",
      "type": "codeVoice"
    },
    {
      "text": " section of a ",
      "type": "text"
    },
    {
      "code": "4x4",
      "type": "codeVoice"
    },
    {
      "text": " matrix.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.glkit/documentation/GLKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4GetMatrix2(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@GLKMatrix4GetMatrix2",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GLKMatrix4GetMatrix2"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "text": "GLKMatrix4"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "text": "GLKMatrix2"
      }
    ],
    "modules": [
      {
        "name": "GLKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GLKMatrix4GetMatrix2"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "GLKMatrix4GetMatrix2(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GLKMatrix4GetMatrix2"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "matrix"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "GLKMatrix4"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "kind": "typeIdentifier",
              "text": "GLKMatrix2"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A ",
                  "type": "text"
                },
                {
                  "code": "4x4",
                  "type": "codeVoice"
                },
                {
                  "text": " matrix.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "matrix"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A new ",
              "type": "text"
            },
            {
              "code": "2x2",
              "type": "codeVoice"
            },
            {
              "text": " matrix.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.glkit/documentation/GLKit": {
      "abstract": [
        {
          "text": "Speed up OpenGL ES or OpenGL app development. Use math libraries, background texture loading, pre-created shader effects, and a standard view and view controller to implement your rendering loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GLKit",
      "type": "topic",
      "url": "/documentation/glkit"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4GetColumn(_:_:)": {
      "abstract": [
        {
          "text": "Retrieves a column from a ",
          "type": "text"
        },
        {
          "code": "4x4",
          "type": "codeVoice"
        },
        {
          "text": " matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix4GetColumn"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4GetColumn(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4GetColumn"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix4GetColumn(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4getcolumn(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4GetMatrix2(_:)": {
      "abstract": [
        {
          "text": "Returns the upper-left ",
          "type": "text"
        },
        {
          "code": "2x2",
          "type": "codeVoice"
        },
        {
          "text": " section of a ",
          "type": "text"
        },
        {
          "code": "4x4",
          "type": "codeVoice"
        },
        {
          "text": " matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix4GetMatrix2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4GetMatrix2(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4GetMatrix2"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix4GetMatrix2(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4getmatrix2(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4GetMatrix3(_:)": {
      "abstract": [
        {
          "text": "Returns the upper-left ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " section of a ",
          "type": "text"
        },
        {
          "code": "4x4",
          "type": "codeVoice"
        },
        {
          "text": " matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix4GetMatrix3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4GetMatrix3(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4GetMatrix3"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix4GetMatrix3(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4getmatrix3(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4GetRow(_:_:)": {
      "abstract": [
        {
          "text": "Retrieves a row from a ",
          "type": "text"
        },
        {
          "code": "4x4",
          "type": "codeVoice"
        },
        {
          "text": " matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix4GetRow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4GetRow(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4GetRow"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix4GetRow(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4getrow(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4SetColumn(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "4x4",
          "type": "codeVoice"
        },
        {
          "text": " matrix with one column replaced by a new vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix4SetColumn"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4SetColumn(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4SetColumn"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix4SetColumn(_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4setcolumn(_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4SetRow(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "4x4",
          "type": "codeVoice"
        },
        {
          "text": " matrix with one row replaced by a new vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix4SetRow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4SetRow(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4SetRow"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix4SetRow(_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4setrow(_:_:_:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-With-Parts-of-a-Matrix",
      "generated": true,
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4GetMatrix3(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4GetColumn(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4GetRow(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4SetColumn(_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4SetRow(_:_:_:)"
      ],
      "title": "Working With Parts of a Matrix"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GLKMatrix4GetMatrix2"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4GetMatrix2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.glkit/documentation/GLKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-With-Parts-of-a-Matrix",
              "generated": true,
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4GetMatrix3(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4GetColumn(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4GetRow(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4SetColumn(_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4SetRow(_:_:_:)"
              ],
              "title": "Working With Parts of a Matrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@U@_GLKMatrix2",
                    "text": "GLKMatrix2"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GLKMatrix4GetMatrix2"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@U@_GLKMatrix4",
                    "text": "GLKMatrix4"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "matrix"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A ",
                        "type": "text"
                      },
                      {
                        "code": "4x4",
                        "type": "codeVoice"
                      },
                      {
                        "text": " matrix.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "matrix"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A new ",
                    "type": "text"
                  },
                  {
                    "code": "2x2",
                    "type": "codeVoice"
                  },
                  {
                    "text": " matrix.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4SetColumn(_:_:_:)/title",
          "value": "GLKMatrix4SetColumn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4SetColumn(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4SetColumn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4SetRow(_:_:_:)/title",
          "value": "GLKMatrix4SetRow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4SetRow(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4SetRow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4GetColumn(_:_:)/title",
          "value": "GLKMatrix4GetColumn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4GetColumn(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4GetColumn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4GetRow(_:_:)/title",
          "value": "GLKMatrix4GetRow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4GetRow(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4GetRow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4GetMatrix2(_:)/title",
          "value": "GLKMatrix4GetMatrix2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4GetMatrix2(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4GetMatrix2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4GetMatrix3(_:)/title",
          "value": "GLKMatrix4GetMatrix3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4GetMatrix3(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4GetMatrix3"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/glkit/glkmatrix4getmatrix2(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/glkit/glkmatrix4getmatrix2(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
