{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.glkit/documentation/GLKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.glkit/documentation/GLKit/glkmatrix3-pcl"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "GLKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "GLKMatrix3"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "GLKMatrix3",
              "type": "codeVoice"
            },
            {
              "text": " type defines a ",
              "type": "text"
            },
            {
              "code": "3x3",
              "type": "codeVoice"
            },
            {
              "text": " floating-point matrix as well as many mathematical operations commonly used to manipulate matrices. A ",
              "type": "text"
            },
            {
              "code": "3x3",
              "type": "codeVoice"
            },
            {
              "text": " matrix is commonly used in graphics programming to represent scaling or rotation transformations to convert from one coordinate system to another.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The functions that manipulate ",
              "type": "text"
            },
            {
              "code": "GLKMatrix3",
              "type": "codeVoice"
            },
            {
              "text": " structures treat the inputs as immutable, instead returning a new matrix that represent the results of the operation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.glkit/documentation/GLKit": {
      "abstract": [
        {
          "text": "Speed up OpenGL ES or OpenGL app development. Use math libraries, background texture loading, pre-created shader effects, and a standard view and view controller to implement your rendering loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GLKit",
      "type": "topic",
      "url": "/documentation/glkit"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix2": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "2x2",
          "type": "codeVoice"
        },
        {
          "text": " matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix2"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix2",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix2"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix stored in column-major order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Add(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by performing a component-wise addition of two matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3Add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Add(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3Add"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3Add(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3add(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3GetColumn(_:_:)": {
      "abstract": [
        {
          "text": "Retrieves a column from a ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3GetColumn"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3GetColumn(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3GetColumn"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3GetColumn(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3getcolumn(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3GetMatrix2(_:)": {
      "abstract": [
        {
          "text": "Returns the upper-left ",
          "type": "text"
        },
        {
          "code": "2x2",
          "type": "codeVoice"
        },
        {
          "text": " section of a ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3GetMatrix2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3GetMatrix2(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3GetMatrix2"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3GetMatrix2(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3getmatrix2(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3GetRow(_:_:)": {
      "abstract": [
        {
          "text": "Retrieves a row from a ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3GetRow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3GetRow(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3GetRow"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3GetRow(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3getrow(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Identity": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " identity matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3Identity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Identity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3Identity"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3Identity",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3identity"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Invert(_:_:)": {
      "abstract": [
        {
          "text": "Returns the inverse of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3Invert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Invert(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3Invert"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3Invert(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3invert(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3InvertAndTranspose(_:_:)": {
      "abstract": [
        {
          "text": "Returns the inverse transpose of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3InvertAndTranspose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3InvertAndTranspose(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3InvertAndTranspose"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3InvertAndTranspose(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3invertandtranspose(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Make(_:_:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix created from individual component values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3Make"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Make(_:_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3Make"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3Make(_:_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3make(_:_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeAndTranspose(_:_:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " transposed matrix created from individual component values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3MakeAndTranspose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeAndTranspose(_:_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3MakeAndTranspose"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3MakeAndTranspose(_:_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3makeandtranspose(_:_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeRotation(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix that performs a rotation around an arbitrary vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3MakeRotation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeRotation(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3MakeRotation"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3MakeRotation(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3makerotation(_:_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeScale(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix that performs a scaling transformation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3MakeScale"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeScale(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3MakeScale"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3MakeScale(_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3makescale(_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeWithArray(_:)": {
      "abstract": [
        {
          "text": "Returns a ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix created from an array of component values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3MakeWithArray"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeWithArray(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3MakeWithArray"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3MakeWithArray(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3makewitharray(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeWithArrayAndTranspose(_:)": {
      "abstract": [
        {
          "text": "Returns a ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " transposed matrix created from an array of component values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3MakeWithArrayAndTranspose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeWithArrayAndTranspose(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3MakeWithArrayAndTranspose"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3MakeWithArrayAndTranspose(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3makewitharrayandtranspose(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeWithColumns(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix created from three column vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3MakeWithColumns"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeWithColumns(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3MakeWithColumns"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3MakeWithColumns(_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3makewithcolumns(_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeWithQuaternion(_:)": {
      "abstract": [
        {
          "text": "Returns a ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix that performs a rotation based on a quaternion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3MakeWithQuaternion"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeWithQuaternion(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3MakeWithQuaternion"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3MakeWithQuaternion(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3makewithquaternion(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeWithRows(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix created from three row vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3MakeWithRows"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeWithRows(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3MakeWithRows"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3MakeWithRows(_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3makewithrows(_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeXRotation(_:)": {
      "abstract": [
        {
          "text": "Returns a ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix that performs a rotation around the positive x-axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3MakeXRotation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeXRotation(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3MakeXRotation"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3MakeXRotation(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3makexrotation(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeYRotation(_:)": {
      "abstract": [
        {
          "text": "Returns a ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix that performs a rotation around the positive y-axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3MakeYRotation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeYRotation(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3MakeYRotation"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3MakeYRotation(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3makeyrotation(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeZRotation(_:)": {
      "abstract": [
        {
          "text": "Returns a ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix that performs a rotation around the positive z-axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3MakeZRotation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeZRotation(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3MakeZRotation"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3MakeZRotation(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3makezrotation(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Multiply(_:_:)": {
      "abstract": [
        {
          "text": "Returns the product of two matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3Multiply"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Multiply(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3Multiply"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3Multiply(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3multiply(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MultiplyVector3(_:_:)": {
      "abstract": [
        {
          "text": "Multiplies a ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix by a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3MultiplyVector3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MultiplyVector3(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3MultiplyVector3"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3MultiplyVector3(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3multiplyvector3(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MultiplyVector3Array(_:_:_:)": {
      "abstract": [
        {
          "text": "Multiplies a ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix by an array of vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3MultiplyVector3Array"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MultiplyVector3Array(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3MultiplyVector3Array"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3MultiplyVector3Array(_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3multiplyvector3array(_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Rotate(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by concatenating a matrix with a rotation around a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3Rotate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Rotate(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3Rotate"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3Rotate(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3rotate(_:_:_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateWithVector3(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by concatenating a matrix with a rotation around a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3RotateWithVector3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateWithVector3(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3RotateWithVector3"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3RotateWithVector3(_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3rotatewithvector3(_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateWithVector4(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by concatenating a matrix with a rotation around a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3RotateWithVector4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateWithVector4(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3RotateWithVector4"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3RotateWithVector4(_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3rotatewithvector4(_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateX(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by concatenating a matrix with a rotation around the x-axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3RotateX"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateX(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3RotateX"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3RotateX(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3rotatex(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateY(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by concatenating a matrix with a rotation around the y-axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3RotateY"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateY(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3RotateY"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3RotateY(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3rotatey(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateZ(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by concatenating a matrix with a rotation around the z-axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3RotateZ"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateZ(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3RotateZ"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3RotateZ(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3rotatez(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Scale(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by concatenating a matrix with a scaling transform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3Scale"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Scale(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3Scale"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3Scale(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3scale(_:_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3ScaleWithVector3(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by concatenating a matrix with a scaling transform defined by a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3ScaleWithVector3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3ScaleWithVector3(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3ScaleWithVector3"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3ScaleWithVector3(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3scalewithvector3(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3ScaleWithVector4(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by concatenating a matrix with a scaling transform defined by a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3ScaleWithVector4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3ScaleWithVector4(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3ScaleWithVector4"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3ScaleWithVector4(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3scalewithvector4(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3SetColumn(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix with one column replaced by a new vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3SetColumn"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3SetColumn(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3SetColumn"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3SetColumn(_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3setcolumn(_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3SetRow(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix with one row replaced by a new vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3SetRow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3SetRow(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3SetRow"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3SetRow(_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3setrow(_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Subtract(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by performing a component-wise subtraction of two matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3Subtract"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Subtract(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3Subtract"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3Subtract(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3subtract(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Transpose(_:)": {
      "abstract": [
        {
          "text": "Returns the transpose of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix3Transpose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Transpose(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix3Transpose"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix3Transpose(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3transpose(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStack": {
      "abstract": [
        {
          "text": "An opaque type that represents a stack of 4 x 4 matrices, providing support for hierarchical transform modeling and similar tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrixStack"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrixStack"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrixStack",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrixstack"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkit-math-utilities": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkit-math-utilities",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKit Math Utilities",
      "type": "topic",
      "url": "/documentation/glkit/glkit-math-utilities"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkmatrix4-pce": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkmatrix4-pce",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKMatrix4",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4-pce"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkquaternion-pc6": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkquaternion-pc6",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKQuaternion",
      "type": "topic",
      "url": "/documentation/glkit/glkquaternion-pc6"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkvector2-pbj": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkvector2-pbj",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKVector2",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2-pbj"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkvector3-pbt": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkvector3-pbt",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKVector3",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3-pbt"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkvector4-pbk": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkvector4-pbk",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKVector4",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4-pbk"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Math-Utilties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStack",
        "doc://com.apple.glkit/documentation/GLKit/glkmatrix4-pce",
        "doc://com.apple.glkit/documentation/GLKit/glkvector2-pbj",
        "doc://com.apple.glkit/documentation/GLKit/glkvector3-pbt",
        "doc://com.apple.glkit/documentation/GLKit/glkvector4-pbk",
        "doc://com.apple.glkit/documentation/GLKit/glkquaternion-pc6",
        "doc://com.apple.glkit/documentation/GLKit/glkit-math-utilities"
      ],
      "title": "Math Utilties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Matrices",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Make(_:_:_:_:_:_:_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeAndTranspose(_:_:_:_:_:_:_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeWithArray(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeWithArrayAndTranspose(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeWithColumns(_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeWithRows(_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeRotation(_:_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeXRotation(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeYRotation(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeZRotation(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeWithQuaternion(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeScale(_:_:_:)"
      ],
      "title": "Creating Matrices"
    },
    {
      "anchor": "Working-With-Parts-of-a-Matrix",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3GetMatrix2(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3GetColumn(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3GetRow(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3SetColumn(_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3SetRow(_:_:_:)"
      ],
      "title": "Working With Parts of a Matrix"
    },
    {
      "anchor": "Performing-Mathematical-Operations-on-Matrices",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Invert(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Transpose(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3InvertAndTranspose(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Multiply(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Rotate(_:_:_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateWithVector3(_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateWithVector4(_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateX(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateY(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateZ(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Scale(_:_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3ScaleWithVector3(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3ScaleWithVector4(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Add(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Subtract(_:_:)"
      ],
      "title": "Performing Mathematical Operations on Matrices"
    },
    {
      "anchor": "Performing-Mathematical-Operations-on-Vectors",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MultiplyVector3(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MultiplyVector3Array(_:_:_:)"
      ],
      "title": "Performing Mathematical Operations on Vectors"
    },
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix2",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3"
      ],
      "title": "Data Types"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Identity"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Matrices",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Make(_:_:_:_:_:_:_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeAndTranspose(_:_:_:_:_:_:_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeWithArray(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeWithArrayAndTranspose(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeWithColumns(_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeWithRows(_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeRotation(_:_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeXRotation(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeYRotation(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeZRotation(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeWithQuaternion(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MakeScale(_:_:_:)"
              ],
              "title": "Creating Matrices"
            },
            {
              "anchor": "Working-With-Parts-of-a-Matrix",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3GetMatrix2(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3GetColumn(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3GetRow(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3SetColumn(_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3SetRow(_:_:_:)"
              ],
              "title": "Working With Parts of a Matrix"
            },
            {
              "anchor": "Performing-Mathematical-Operations-on-Matrices",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Invert(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Transpose(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3InvertAndTranspose(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Multiply(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Rotate(_:_:_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateWithVector3(_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateWithVector4(_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateX(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateY(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3RotateZ(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Scale(_:_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3ScaleWithVector3(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3ScaleWithVector4(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Add(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Subtract(_:_:)"
              ],
              "title": "Performing Mathematical Operations on Matrices"
            },
            {
              "anchor": "Performing-Mathematical-Operations-on-Vectors",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MultiplyVector3(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3MultiplyVector3Array(_:_:_:)"
              ],
              "title": "Performing Mathematical Operations on Vectors"
            },
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix2",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3"
              ],
              "title": "Data Types"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix3Identity"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Math-Utilties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStack",
                "doc://com.apple.glkit/documentation/GLKit/glkmatrix4-pce",
                "doc://com.apple.glkit/documentation/GLKit/glkvector2-pbj",
                "doc://com.apple.glkit/documentation/GLKit/glkvector3-pbt",
                "doc://com.apple.glkit/documentation/GLKit/glkvector4-pbk",
                "doc://com.apple.glkit/documentation/GLKit/glkquaternion-pc6",
                "doc://com.apple.glkit/documentation/GLKit/glkit-math-utilities"
              ],
              "title": "Math Utilties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3MakeWithColumns(_:_:_:)/title",
          "value": "GLKMatrix3MakeWithColumns"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3MakeWithColumns(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3MakeWithColumns"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3MakeAndTranspose(_:_:_:_:_:_:_:_:_:)/title",
          "value": "GLKMatrix3MakeAndTranspose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3MakeAndTranspose(_:_:_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3MakeAndTranspose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStack/title",
          "value": "GLKMatrixStackRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrixStackRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrixStackRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3ScaleWithVector4(_:_:)/title",
          "value": "GLKMatrix3ScaleWithVector4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3ScaleWithVector4(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3ScaleWithVector4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3MakeXRotation(_:)/title",
          "value": "GLKMatrix3MakeXRotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3MakeXRotation(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3MakeXRotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Subtract(_:_:)/title",
          "value": "GLKMatrix3Subtract"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Subtract(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3Subtract"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3SetColumn(_:_:_:)/title",
          "value": "GLKMatrix3SetColumn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3SetColumn(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3SetColumn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3MultiplyVector3Array(_:_:_:)/title",
          "value": "GLKMatrix3MultiplyVector3Array"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3MultiplyVector3Array(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3MultiplyVector3Array"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3/title",
          "value": "GLKMatrix3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Scale(_:_:_:_:)/title",
          "value": "GLKMatrix3Scale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Scale(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3Scale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3MakeScale(_:_:_:)/title",
          "value": "GLKMatrix3MakeScale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3MakeScale(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3MakeScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3MakeWithArray(_:)/title",
          "value": "GLKMatrix3MakeWithArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3MakeWithArray(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3MakeWithArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3ScaleWithVector3(_:_:)/title",
          "value": "GLKMatrix3ScaleWithVector3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3ScaleWithVector3(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3ScaleWithVector3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3MakeWithQuaternion(_:)/title",
          "value": "GLKMatrix3MakeWithQuaternion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3MakeWithQuaternion(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3MakeWithQuaternion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3GetRow(_:_:)/title",
          "value": "GLKMatrix3GetRow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3GetRow(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3GetRow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3RotateZ(_:_:)/title",
          "value": "GLKMatrix3RotateZ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3RotateZ(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3RotateZ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Rotate(_:_:_:_:_:)/title",
          "value": "GLKMatrix3Rotate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Rotate(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3Rotate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3GetColumn(_:_:)/title",
          "value": "GLKMatrix3GetColumn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3GetColumn(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3GetColumn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3RotateWithVector4(_:_:_:)/title",
          "value": "GLKMatrix3RotateWithVector4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3RotateWithVector4(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3RotateWithVector4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3GetMatrix2(_:)/title",
          "value": "GLKMatrix3GetMatrix2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3GetMatrix2(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3GetMatrix2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3InvertAndTranspose(_:_:)/title",
          "value": "GLKMatrix3InvertAndTranspose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3InvertAndTranspose(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3InvertAndTranspose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix2/title",
          "value": "GLKMatrix2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3MakeZRotation(_:)/title",
          "value": "GLKMatrix3MakeZRotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3MakeZRotation(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3MakeZRotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3RotateY(_:_:)/title",
          "value": "GLKMatrix3RotateY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3RotateY(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3RotateY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Add(_:_:)/title",
          "value": "GLKMatrix3Add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Add(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3Add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3MakeYRotation(_:)/title",
          "value": "GLKMatrix3MakeYRotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3MakeYRotation(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3MakeYRotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3MakeWithRows(_:_:_:)/title",
          "value": "GLKMatrix3MakeWithRows"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3MakeWithRows(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3MakeWithRows"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Transpose(_:)/title",
          "value": "GLKMatrix3Transpose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Transpose(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3Transpose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3SetRow(_:_:_:)/title",
          "value": "GLKMatrix3SetRow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3SetRow(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3SetRow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3MultiplyVector3(_:_:)/title",
          "value": "GLKMatrix3MultiplyVector3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3MultiplyVector3(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3MultiplyVector3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3MakeRotation(_:_:_:_:)/title",
          "value": "GLKMatrix3MakeRotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3MakeRotation(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3MakeRotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Invert(_:_:)/title",
          "value": "GLKMatrix3Invert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Invert(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3Invert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3RotateX(_:_:)/title",
          "value": "GLKMatrix3RotateX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3RotateX(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3RotateX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3RotateWithVector3(_:_:_:)/title",
          "value": "GLKMatrix3RotateWithVector3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3RotateWithVector3(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3RotateWithVector3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Identity/title",
          "value": "GLKMatrix3Identity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Identity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3Identity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3MakeWithArrayAndTranspose(_:)/title",
          "value": "GLKMatrix3MakeWithArrayAndTranspose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3MakeWithArrayAndTranspose(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3MakeWithArrayAndTranspose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Make(_:_:_:_:_:_:_:_:_:)/title",
          "value": "GLKMatrix3Make"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Make(_:_:_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3Make"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Multiply(_:_:)/title",
          "value": "GLKMatrix3Multiply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix3Multiply(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix3Multiply"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/glkit/glkmatrix3-pcl"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/glkit/glkmatrix3-pcl"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
