{
  "abstract": [
    {
      "text": "An opaque type that represents a stack of 4 x 4 matrices, providing support for hierarchical transform modeling and similar tasks.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.glkit/documentation/GLKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStack"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@GLKMatrixStackRef",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GLKMatrixStack"
      }
    ],
    "modules": [
      {
        "name": "GLKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GLKMatrixStack"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "GLKMatrixStack"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GLKMatrixStack"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.glkit/documentation/GLKit": {
      "abstract": [
        {
          "text": "Speed up OpenGL ES or OpenGL app development. Use math libraries, background texture loading, pre-created shader effects, and a standard view and view controller to implement your rendering loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GLKit",
      "type": "topic",
      "url": "/documentation/glkit"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStack": {
      "abstract": [
        {
          "text": "An opaque type that represents a stack of 4 x 4 matrices, providing support for hierarchical transform modeling and similar tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrixStack"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrixStack"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrixStack",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrixstack"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkit-math-utilities": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkit-math-utilities",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKit Math Utilities",
      "type": "topic",
      "url": "/documentation/glkit/glkit-math-utilities"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkmatrix3-pcl": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkmatrix3-pcl",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKMatrix3",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3-pcl"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkmatrix4-pce": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkmatrix4-pce",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKMatrix4",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4-pce"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkquaternion-pc6": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkquaternion-pc6",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKQuaternion",
      "type": "topic",
      "url": "/documentation/glkit/glkquaternion-pc6"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkvector2-pbj": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkvector2-pbj",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKVector2",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2-pbj"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkvector3-pbt": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkvector3-pbt",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKVector3",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3-pbt"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkvector4-pbk": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkvector4-pbk",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKVector4",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4-pbk"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Math-Utilties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/glkmatrix3-pcl",
        "doc://com.apple.glkit/documentation/GLKit/glkmatrix4-pce",
        "doc://com.apple.glkit/documentation/GLKit/glkvector2-pbj",
        "doc://com.apple.glkit/documentation/GLKit/glkvector3-pbt",
        "doc://com.apple.glkit/documentation/GLKit/glkvector4-pbk",
        "doc://com.apple.glkit/documentation/GLKit/glkquaternion-pc6",
        "doc://com.apple.glkit/documentation/GLKit/glkit-math-utilities"
      ],
      "title": "Math Utilties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GLKMatrixStackRef"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrixStackRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrixStackRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.glkit/documentation/GLKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Math-Utilties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/glkmatrix3-pcl",
                "doc://com.apple.glkit/documentation/GLKit/glkmatrix4-pce",
                "doc://com.apple.glkit/documentation/GLKit/glkvector2-pbj",
                "doc://com.apple.glkit/documentation/GLKit/glkvector3-pbt",
                "doc://com.apple.glkit/documentation/GLKit/glkvector4-pbk",
                "doc://com.apple.glkit/documentation/GLKit/glkquaternion-pc6",
                "doc://com.apple.glkit/documentation/GLKit/glkit-math-utilities"
              ],
              "title": "Math Utilties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@_GLKMatrixStack",
                    "text": "_GLKMatrixStack"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "GLKMatrixStackRef"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStack/title",
          "value": "GLKMatrixStackRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrixStackRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrixStackRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/glkit/glkmatrixstack"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/glkit/glkmatrixstack"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
