{
  "abstract": [
    {
      "text": "Returns the transpose of a matrix.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.glkit/documentation/GLKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4Transpose(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@GLKMatrix4Transpose",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GLKMatrix4Transpose"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "text": "GLKMatrix4"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "text": "GLKMatrix4"
      }
    ],
    "modules": [
      {
        "name": "GLKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GLKMatrix4Transpose"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "GLKMatrix4Transpose(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GLKMatrix4Transpose"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "matrix"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "GLKMatrix4"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "kind": "typeIdentifier",
              "text": "GLKMatrix4"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A ",
                  "type": "text"
                },
                {
                  "code": "4x4",
                  "type": "codeVoice"
                },
                {
                  "text": " matrix.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "matrix"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A new matrix that is the transpose of the original matrix.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.glkit/documentation/GLKit": {
      "abstract": [
        {
          "text": "Speed up OpenGL ES or OpenGL app development. Use math libraries, background texture loading, pre-created shader effects, and a standard view and view controller to implement your rendering loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GLKit",
      "type": "topic",
      "url": "/documentation/glkit"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4Invert(_:_:)": {
      "abstract": [
        {
          "text": "Returns the inverse of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix4Invert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4Invert(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4Invert"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix4Invert(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4invert(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4InvertAndTranspose(_:_:)": {
      "abstract": [
        {
          "text": "Returns the inverse transpose of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix4InvertAndTranspose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4InvertAndTranspose(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4InvertAndTranspose"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix4InvertAndTranspose(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4invertandtranspose(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4Multiply(_:_:)": {
      "abstract": [
        {
          "text": "Returns the product of two matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix4Multiply"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4Multiply(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4Multiply"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix4Multiply(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4multiply(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4Rotate(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "4x4",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by concatenating a matrix with a rotation around a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix4Rotate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4Rotate(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4Rotate"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix4Rotate(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4rotate(_:_:_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4RotateWithVector3(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "4x4",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by concatenating a matrix with a rotation around a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix4RotateWithVector3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4RotateWithVector3(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4RotateWithVector3"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix4RotateWithVector3(_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4rotatewithvector3(_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4RotateWithVector4(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "4x4",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by concatenating a matrix with a rotation around a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix4RotateWithVector4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4RotateWithVector4(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4RotateWithVector4"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix4RotateWithVector4(_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4rotatewithvector4(_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4RotateX(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "4x4",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by concatenating a matrix with a rotation around the x-axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix4RotateX"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4RotateX(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4RotateX"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix4RotateX(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4rotatex(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4RotateY(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "4x4",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by concatenating a matrix with a rotation around the y-axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix4RotateY"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4RotateY(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4RotateY"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix4RotateY(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4rotatey(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4RotateZ(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "4x4",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by concatenating a matrix with a rotation around the z-axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix4RotateZ"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4RotateZ(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4RotateZ"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix4RotateZ(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4rotatez(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4Scale(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "4x4",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by concatenating a matrix with a scaling transform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix4Scale"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4Scale(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4Scale"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix4Scale(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4scale(_:_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4ScaleWithVector3(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "4x4",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by concatenating a matrix with a scaling transform defined by a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix4ScaleWithVector3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4ScaleWithVector3(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4ScaleWithVector3"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix4ScaleWithVector3(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4scalewithvector3(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4ScaleWithVector4(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "4x4",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by concatenating a matrix with a scaling transform defined by a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix4ScaleWithVector4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4ScaleWithVector4(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4ScaleWithVector4"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix4ScaleWithVector4(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4scalewithvector4(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4Translate(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "4x4",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by concatenating a matrix with a translation transform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix4Translate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4Translate(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4Translate"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix4Translate(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4translate(_:_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4TranslateWithVector3(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "4x4",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by concatenating a matrix with a translation transform defined by a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix4TranslateWithVector3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4TranslateWithVector3(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4TranslateWithVector3"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix4TranslateWithVector3(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4translatewithvector3(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4TranslateWithVector4(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new ",
          "type": "text"
        },
        {
          "code": "4x4",
          "type": "codeVoice"
        },
        {
          "text": " matrix created by concatenating a matrix with a translation transform defined by a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix4TranslateWithVector4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4TranslateWithVector4(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4TranslateWithVector4"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix4TranslateWithVector4(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4translatewithvector4(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4Transpose(_:)": {
      "abstract": [
        {
          "text": "Returns the transpose of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrix4Transpose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4Transpose(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4Transpose"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrix4Transpose(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4transpose(_:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Performing-Mathematical-Operations-on-Matrices",
      "generated": true,
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4Invert(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4InvertAndTranspose(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4Multiply(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4Rotate(_:_:_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4RotateWithVector3(_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4RotateWithVector4(_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4RotateX(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4RotateY(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4RotateZ(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4Scale(_:_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4ScaleWithVector3(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4ScaleWithVector4(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4Translate(_:_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4TranslateWithVector3(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4TranslateWithVector4(_:_:)"
      ],
      "title": "Performing Mathematical Operations on Matrices"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GLKMatrix4Transpose"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4Transpose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.glkit/documentation/GLKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Performing-Mathematical-Operations-on-Matrices",
              "generated": true,
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4Invert(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4InvertAndTranspose(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4Multiply(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4Rotate(_:_:_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4RotateWithVector3(_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4RotateWithVector4(_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4RotateX(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4RotateY(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4RotateZ(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4Scale(_:_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4ScaleWithVector3(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4ScaleWithVector4(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4Translate(_:_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4TranslateWithVector3(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrix4TranslateWithVector4(_:_:)"
              ],
              "title": "Performing Mathematical Operations on Matrices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@U@_GLKMatrix4",
                    "text": "GLKMatrix4"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GLKMatrix4Transpose"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@U@_GLKMatrix4",
                    "text": "GLKMatrix4"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "matrix"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A ",
                        "type": "text"
                      },
                      {
                        "code": "4x4",
                        "type": "codeVoice"
                      },
                      {
                        "text": " matrix.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "matrix"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A new matrix that is the transpose of the original matrix.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4RotateZ(_:_:)/title",
          "value": "GLKMatrix4RotateZ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4RotateZ(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4RotateZ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4RotateWithVector3(_:_:_:)/title",
          "value": "GLKMatrix4RotateWithVector3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4RotateWithVector3(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4RotateWithVector3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4ScaleWithVector3(_:_:)/title",
          "value": "GLKMatrix4ScaleWithVector3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4ScaleWithVector3(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4ScaleWithVector3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4RotateY(_:_:)/title",
          "value": "GLKMatrix4RotateY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4RotateY(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4RotateY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4RotateWithVector4(_:_:_:)/title",
          "value": "GLKMatrix4RotateWithVector4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4RotateWithVector4(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4RotateWithVector4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4Translate(_:_:_:_:)/title",
          "value": "GLKMatrix4Translate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4Translate(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4Translate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4TranslateWithVector4(_:_:)/title",
          "value": "GLKMatrix4TranslateWithVector4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4TranslateWithVector4(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4TranslateWithVector4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4ScaleWithVector4(_:_:)/title",
          "value": "GLKMatrix4ScaleWithVector4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4ScaleWithVector4(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4ScaleWithVector4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4Rotate(_:_:_:_:_:)/title",
          "value": "GLKMatrix4Rotate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4Rotate(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4Rotate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4InvertAndTranspose(_:_:)/title",
          "value": "GLKMatrix4InvertAndTranspose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4InvertAndTranspose(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4InvertAndTranspose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4RotateX(_:_:)/title",
          "value": "GLKMatrix4RotateX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4RotateX(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4RotateX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4Multiply(_:_:)/title",
          "value": "GLKMatrix4Multiply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4Multiply(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4Multiply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4Transpose(_:)/title",
          "value": "GLKMatrix4Transpose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4Transpose(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4Transpose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4Scale(_:_:_:_:)/title",
          "value": "GLKMatrix4Scale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4Scale(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4Scale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4TranslateWithVector3(_:_:)/title",
          "value": "GLKMatrix4TranslateWithVector3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4TranslateWithVector3(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4TranslateWithVector3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4Invert(_:_:)/title",
          "value": "GLKMatrix4Invert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrix4Invert(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrix4Invert"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/glkit/glkmatrix4transpose(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/glkit/glkmatrix4transpose(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
