{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.glkit/documentation/GLKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.glkit/documentation/GLKit/glkquaternion-pc6"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "GLKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "GLKQuaternion"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "GLKQuaternion",
              "type": "codeVoice"
            },
            {
              "text": " type defines a structure that represents a quaternion. A quaternion is defined by a scalar component ",
              "type": "text"
            },
            {
              "code": "s",
              "type": "codeVoice"
            },
            {
              "text": " and an XYZ vector ",
              "type": "text"
            },
            {
              "code": "v",
              "type": "codeVoice"
            },
            {
              "text": ". Quaternions are often used in graphics programming as a compact representation of a rotation of an object in three dimensions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The functions that manipulate ",
              "type": "text"
            },
            {
              "code": "GLKQuaternion",
              "type": "codeVoice"
            },
            {
              "text": " structures treat the inputs as immutable, instead returning a new quaternion that represent the results of the operation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.glkit/documentation/GLKit": {
      "abstract": [
        {
          "text": "Speed up OpenGL ES or OpenGL app development. Use math libraries, background texture loading, pre-created shader effects, and a standard view and view controller to implement your rendering loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GLKit",
      "type": "topic",
      "url": "/documentation/glkit"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStack": {
      "abstract": [
        {
          "text": "An opaque type that represents a stack of 4 x 4 matrices, providing support for hierarchical transform modeling and similar tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrixStack"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrixStack"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrixStack",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrixstack"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKQuaternion": {
      "abstract": [
        {
          "text": "A representation of a quaternion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKQuaternion"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKQuaternion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKQuaternion"
        }
      ],
      "role": "symbol",
      "title": "GLKQuaternion",
      "type": "topic",
      "url": "/documentation/glkit/glkquaternion"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionAdd(_:_:)": {
      "abstract": [
        {
          "text": "Returns the sum of two quaternions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKQuaternionAdd"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionAdd(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKQuaternionAdd"
        }
      ],
      "role": "symbol",
      "title": "GLKQuaternionAdd(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkquaternionadd(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionAngle(_:)": {
      "abstract": [
        {
          "text": "Returns the rotation angle of a quaternion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKQuaternionAngle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionAngle(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKQuaternionAngle"
        }
      ],
      "role": "symbol",
      "title": "GLKQuaternionAngle(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkquaternionangle(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionAxis(_:)": {
      "abstract": [
        {
          "text": "Returns the axis of rotation of a quaternion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKQuaternionAxis"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionAxis(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKQuaternionAxis"
        }
      ],
      "role": "symbol",
      "title": "GLKQuaternionAxis(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkquaternionaxis(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionConjugate(_:)": {
      "abstract": [
        {
          "text": "Returns the conjugate of a quaternion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKQuaternionConjugate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionConjugate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKQuaternionConjugate"
        }
      ],
      "role": "symbol",
      "title": "GLKQuaternionConjugate(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkquaternionconjugate(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionIdentity": {
      "abstract": [
        {
          "text": "An identity quaternion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKQuaternionIdentity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionIdentity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKQuaternionIdentity"
        }
      ],
      "role": "symbol",
      "title": "GLKQuaternionIdentity",
      "type": "topic",
      "url": "/documentation/glkit/glkquaternionidentity"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionInvert(_:)": {
      "abstract": [
        {
          "text": "Returns an inverse of a quaternion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKQuaternionInvert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionInvert(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKQuaternionInvert"
        }
      ],
      "role": "symbol",
      "title": "GLKQuaternionInvert(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkquaternioninvert(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionLength(_:)": {
      "abstract": [
        {
          "text": "Returns the length of a quaternion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKQuaternionLength"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionLength(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKQuaternionLength"
        }
      ],
      "role": "symbol",
      "title": "GLKQuaternionLength(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkquaternionlength(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMake(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a quaternion created from its separate components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKQuaternionMake"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMake(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKQuaternionMake"
        }
      ],
      "role": "symbol",
      "title": "GLKQuaternionMake(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkquaternionmake(_:_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMakeWithAngleAndAxis(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a quaternion that represents a rotation around an axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKQuaternionMakeWithAngleAndAxis"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMakeWithAngleAndAxis(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKQuaternionMakeWithAngleAndAxis"
        }
      ],
      "role": "symbol",
      "title": "GLKQuaternionMakeWithAngleAndAxis(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkquaternionmakewithangleandaxis(_:_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMakeWithAngleAndVector3Axis(_:_:)": {
      "abstract": [
        {
          "text": "Creates a quaternion that represents a rotation around an axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKQuaternionMakeWithAngleAndVector3Axis"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMakeWithAngleAndVector3Axis(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKQuaternionMakeWithAngleAndVector3Axis"
        }
      ],
      "role": "symbol",
      "title": "GLKQuaternionMakeWithAngleAndVector3Axis(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkquaternionmakewithangleandvector3axis(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMakeWithArray(_:)": {
      "abstract": [
        {
          "text": "Returns a quaternion created from an array of components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKQuaternionMakeWithArray"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMakeWithArray(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKQuaternionMakeWithArray"
        }
      ],
      "role": "symbol",
      "title": "GLKQuaternionMakeWithArray(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkquaternionmakewitharray(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMakeWithMatrix3(_:)": {
      "abstract": [
        {
          "text": "Creates a quaternion from a rotation matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKQuaternionMakeWithMatrix3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMakeWithMatrix3(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKQuaternionMakeWithMatrix3"
        }
      ],
      "role": "symbol",
      "title": "GLKQuaternionMakeWithMatrix3(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkquaternionmakewithmatrix3(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMakeWithMatrix4(_:)": {
      "abstract": [
        {
          "text": "Creates a quaternion from a rotation matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKQuaternionMakeWithMatrix4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMakeWithMatrix4(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKQuaternionMakeWithMatrix4"
        }
      ],
      "role": "symbol",
      "title": "GLKQuaternionMakeWithMatrix4(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkquaternionmakewithmatrix4(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMakeWithVector3(_:_:)": {
      "abstract": [
        {
          "text": "Returns a quaternion created from a vector and a scalar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKQuaternionMakeWithVector3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMakeWithVector3(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKQuaternionMakeWithVector3"
        }
      ],
      "role": "symbol",
      "title": "GLKQuaternionMakeWithVector3(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkquaternionmakewithvector3(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMultiply(_:_:)": {
      "abstract": [
        {
          "text": "Returns the product of two quaternions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKQuaternionMultiply"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMultiply(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKQuaternionMultiply"
        }
      ],
      "role": "symbol",
      "title": "GLKQuaternionMultiply(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkquaternionmultiply(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionNormalize(_:)": {
      "abstract": [
        {
          "text": "Returns a normalized version of a quaternion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKQuaternionNormalize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionNormalize(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKQuaternionNormalize"
        }
      ],
      "role": "symbol",
      "title": "GLKQuaternionNormalize(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkquaternionnormalize(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionRotateVector3(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector that is calculated by applying a quaternion rotation to a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKQuaternionRotateVector3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionRotateVector3(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKQuaternionRotateVector3"
        }
      ],
      "role": "symbol",
      "title": "GLKQuaternionRotateVector3(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkquaternionrotatevector3(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionRotateVector3Array(_:_:_:)": {
      "abstract": [
        {
          "text": "Applies a quaternion rotation to an array of vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKQuaternionRotateVector3Array"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionRotateVector3Array(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKQuaternionRotateVector3Array"
        }
      ],
      "role": "symbol",
      "title": "GLKQuaternionRotateVector3Array(_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkquaternionrotatevector3array(_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionRotateVector4(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector calculated by applying a quaternion rotation to a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKQuaternionRotateVector4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionRotateVector4(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKQuaternionRotateVector4"
        }
      ],
      "role": "symbol",
      "title": "GLKQuaternionRotateVector4(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkquaternionrotatevector4(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionRotateVector4Array(_:_:_:)": {
      "abstract": [
        {
          "text": "Applies a quaternion rotation to an array of vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKQuaternionRotateVector4Array"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionRotateVector4Array(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKQuaternionRotateVector4Array"
        }
      ],
      "role": "symbol",
      "title": "GLKQuaternionRotateVector4Array(_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkquaternionrotatevector4array(_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionSlerp(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the spherical linear interpolation of two quaternions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKQuaternionSlerp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionSlerp(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKQuaternionSlerp"
        }
      ],
      "role": "symbol",
      "title": "GLKQuaternionSlerp(_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkquaternionslerp(_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionSubtract(_:_:)": {
      "abstract": [
        {
          "text": "Returns the difference between two quaternions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKQuaternionSubtract"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionSubtract(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKQuaternionSubtract"
        }
      ],
      "role": "symbol",
      "title": "GLKQuaternionSubtract(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkquaternionsubtract(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkit-math-utilities": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkit-math-utilities",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKit Math Utilities",
      "type": "topic",
      "url": "/documentation/glkit/glkit-math-utilities"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkmatrix3-pcl": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkmatrix3-pcl",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKMatrix3",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3-pcl"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkmatrix4-pce": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkmatrix4-pce",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKMatrix4",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4-pce"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkvector2-pbj": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkvector2-pbj",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKVector2",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2-pbj"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkvector3-pbt": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkvector3-pbt",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKVector3",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3-pbt"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkvector4-pbk": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkvector4-pbk",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKVector4",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4-pbk"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Math-Utilties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStack",
        "doc://com.apple.glkit/documentation/GLKit/glkmatrix3-pcl",
        "doc://com.apple.glkit/documentation/GLKit/glkmatrix4-pce",
        "doc://com.apple.glkit/documentation/GLKit/glkvector2-pbj",
        "doc://com.apple.glkit/documentation/GLKit/glkvector3-pbt",
        "doc://com.apple.glkit/documentation/GLKit/glkvector4-pbk",
        "doc://com.apple.glkit/documentation/GLKit/glkit-math-utilities"
      ],
      "title": "Math Utilties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Quaternions",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMake(_:_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMakeWithArray(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMakeWithVector3(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMakeWithAngleAndAxis(_:_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMakeWithAngleAndVector3Axis(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMakeWithMatrix3(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMakeWithMatrix4(_:)"
      ],
      "title": "Creating Quaternions"
    },
    {
      "anchor": "Retrieving-Information-About-a-Quaternion",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionLength(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionAxis(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionAngle(_:)"
      ],
      "title": "Retrieving Information About a Quaternion"
    },
    {
      "anchor": "Performing-Mathematical-Operations-on-Quaternions",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionNormalize(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionInvert(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionConjugate(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionAdd(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionSubtract(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMultiply(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionSlerp(_:_:_:)"
      ],
      "title": "Performing Mathematical Operations on Quaternions"
    },
    {
      "anchor": "Applying-Quaternions-to-Vectors",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionRotateVector3(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionRotateVector3Array(_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionRotateVector4(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionRotateVector4Array(_:_:_:)"
      ],
      "title": "Applying Quaternions to Vectors"
    },
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKQuaternion"
      ],
      "title": "Data Types"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionIdentity"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Quaternions",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMake(_:_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMakeWithArray(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMakeWithVector3(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMakeWithAngleAndAxis(_:_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMakeWithAngleAndVector3Axis(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMakeWithMatrix3(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMakeWithMatrix4(_:)"
              ],
              "title": "Creating Quaternions"
            },
            {
              "anchor": "Retrieving-Information-About-a-Quaternion",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionLength(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionAxis(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionAngle(_:)"
              ],
              "title": "Retrieving Information About a Quaternion"
            },
            {
              "anchor": "Performing-Mathematical-Operations-on-Quaternions",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionNormalize(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionInvert(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionConjugate(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionAdd(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionSubtract(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionMultiply(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionSlerp(_:_:_:)"
              ],
              "title": "Performing Mathematical Operations on Quaternions"
            },
            {
              "anchor": "Applying-Quaternions-to-Vectors",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionRotateVector3(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionRotateVector3Array(_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionRotateVector4(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionRotateVector4Array(_:_:_:)"
              ],
              "title": "Applying Quaternions to Vectors"
            },
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKQuaternion"
              ],
              "title": "Data Types"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKQuaternionIdentity"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Math-Utilties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStack",
                "doc://com.apple.glkit/documentation/GLKit/glkmatrix3-pcl",
                "doc://com.apple.glkit/documentation/GLKit/glkmatrix4-pce",
                "doc://com.apple.glkit/documentation/GLKit/glkvector2-pbj",
                "doc://com.apple.glkit/documentation/GLKit/glkvector3-pbt",
                "doc://com.apple.glkit/documentation/GLKit/glkvector4-pbk",
                "doc://com.apple.glkit/documentation/GLKit/glkit-math-utilities"
              ],
              "title": "Math Utilties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternion/title",
          "value": "GLKQuaternion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKQuaternion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKQuaternion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionMake(_:_:_:_:)/title",
          "value": "GLKQuaternionMake"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionMake(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKQuaternionMake"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionMakeWithMatrix4(_:)/title",
          "value": "GLKQuaternionMakeWithMatrix4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionMakeWithMatrix4(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKQuaternionMakeWithMatrix4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionIdentity/title",
          "value": "GLKQuaternionIdentity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionIdentity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKQuaternionIdentity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionConjugate(_:)/title",
          "value": "GLKQuaternionConjugate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionConjugate(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKQuaternionConjugate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionAngle(_:)/title",
          "value": "GLKQuaternionAngle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionAngle(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKQuaternionAngle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionLength(_:)/title",
          "value": "GLKQuaternionLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionLength(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKQuaternionLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionAxis(_:)/title",
          "value": "GLKQuaternionAxis"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionAxis(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKQuaternionAxis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionMakeWithArray(_:)/title",
          "value": "GLKQuaternionMakeWithArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionMakeWithArray(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKQuaternionMakeWithArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionRotateVector4(_:_:)/title",
          "value": "GLKQuaternionRotateVector4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionRotateVector4(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKQuaternionRotateVector4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionNormalize(_:)/title",
          "value": "GLKQuaternionNormalize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionNormalize(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKQuaternionNormalize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionInvert(_:)/title",
          "value": "GLKQuaternionInvert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionInvert(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKQuaternionInvert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionMakeWithAngleAndAxis(_:_:_:_:)/title",
          "value": "GLKQuaternionMakeWithAngleAndAxis"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionMakeWithAngleAndAxis(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKQuaternionMakeWithAngleAndAxis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionRotateVector4Array(_:_:_:)/title",
          "value": "GLKQuaternionRotateVector4Array"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionRotateVector4Array(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKQuaternionRotateVector4Array"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionMakeWithMatrix3(_:)/title",
          "value": "GLKQuaternionMakeWithMatrix3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionMakeWithMatrix3(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKQuaternionMakeWithMatrix3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionRotateVector3(_:_:)/title",
          "value": "GLKQuaternionRotateVector3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionRotateVector3(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKQuaternionRotateVector3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStack/title",
          "value": "GLKMatrixStackRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrixStackRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrixStackRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionMakeWithVector3(_:_:)/title",
          "value": "GLKQuaternionMakeWithVector3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionMakeWithVector3(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKQuaternionMakeWithVector3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionRotateVector3Array(_:_:_:)/title",
          "value": "GLKQuaternionRotateVector3Array"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionRotateVector3Array(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKQuaternionRotateVector3Array"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionAdd(_:_:)/title",
          "value": "GLKQuaternionAdd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionAdd(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKQuaternionAdd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionSlerp(_:_:_:)/title",
          "value": "GLKQuaternionSlerp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionSlerp(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKQuaternionSlerp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionMakeWithAngleAndVector3Axis(_:_:)/title",
          "value": "GLKQuaternionMakeWithAngleAndVector3Axis"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionMakeWithAngleAndVector3Axis(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKQuaternionMakeWithAngleAndVector3Axis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionSubtract(_:_:)/title",
          "value": "GLKQuaternionSubtract"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionSubtract(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKQuaternionSubtract"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionMultiply(_:_:)/title",
          "value": "GLKQuaternionMultiply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKQuaternionMultiply(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKQuaternionMultiply"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/glkit/glkquaternion-pc6"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/glkit/glkquaternion-pc6"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
