{
  "abstract": [
    {
      "text": "Information about OpenGL textures created by the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoader",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " class.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "OpenGLES API deprecated. (Define GLES_SILENCE_DEPRECATION to silence these warnings)",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.glkit/documentation/GLKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)GLKTextureInfo",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GLKTextureInfo"
      }
    ],
    "modules": [
      {
        "name": "GLKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GLKTextureInfo"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "5.0",
        "message": "OpenGLES API deprecated. (Define GLES_SILENCE_DEPRECATION to silence these warnings)",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "5.0",
        "message": "OpenGLES API deprecated. (Define GLES_SILENCE_DEPRECATION to silence these warnings)",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.8",
        "message": "OpenGL API deprecated. (Define GL_SILENCE_DEPRECATION to silence these warnings)",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "9.0",
        "message": "OpenGLES API deprecated. (Define GLES_SILENCE_DEPRECATION to silence these warnings)",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "GLKTextureInfo"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GLKTextureInfo"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When your app loads textures using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoader",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class, the texture loader returns information about the textures using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects. Your app never creates ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects directly.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.glkit/documentation/GLKit": {
      "abstract": [
        {
          "text": "Speed up OpenGL ES or OpenGL app development. Use math libraries, background texture loading, pre-created shader effects, and a standard view and view controller to implement your rendering loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GLKit",
      "type": "topic",
      "url": "/documentation/glkit"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo": {
      "abstract": [
        {
          "text": "Information about OpenGL textures created by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoader",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " class.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureInfo"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureInfo"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureInfo",
      "type": "topic",
      "url": "/documentation/glkit/glktextureinfo"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/alphaState-c.ivar": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "alphaState"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/alphaState-c.ivar",
      "kind": "symbol",
      "role": "symbol",
      "title": "alphaState",
      "type": "topic",
      "url": "/documentation/glkit/glktextureinfo/alphastate-c.ivar"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/alphaState-swift.property": {
      "abstract": [
        {
          "text": "The state of the alpha component in the loaded texture.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alphaState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GLKTextureInfoAlphaState",
          "text": "GLKTextureInfoAlphaState"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/alphaState-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "alphaState"
        }
      ],
      "role": "symbol",
      "title": "alphaState",
      "type": "topic",
      "url": "/documentation/glkit/glktextureinfo/alphastate-swift.property"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/arrayLength-c.ivar": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "arrayLength"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/arrayLength-c.ivar",
      "kind": "symbol",
      "role": "symbol",
      "title": "arrayLength",
      "type": "topic",
      "url": "/documentation/glkit/glktextureinfo/arraylength-c.ivar"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/arrayLength-swift.property": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "arrayLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLuint",
          "text": "GLuint"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/arrayLength-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "arrayLength"
        }
      ],
      "role": "symbol",
      "title": "arrayLength",
      "type": "topic",
      "url": "/documentation/glkit/glktextureinfo/arraylength-swift.property"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/containsMipmaps-c.ivar": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "containsMipmaps"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/containsMipmaps-c.ivar",
      "kind": "symbol",
      "role": "symbol",
      "title": "containsMipmaps",
      "type": "topic",
      "url": "/documentation/glkit/glktextureinfo/containsmipmaps-c.ivar"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/containsMipmaps-swift.property": {
      "abstract": [
        {
          "text": "A Boolean value that states whether the loaded texture contains mip maps.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containsMipmaps"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/containsMipmaps-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "containsMipmaps"
        }
      ],
      "role": "symbol",
      "title": "containsMipmaps",
      "type": "topic",
      "url": "/documentation/glkit/glktextureinfo/containsmipmaps-swift.property"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/depth-c.ivar": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "depth"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/depth-c.ivar",
      "kind": "symbol",
      "role": "symbol",
      "title": "depth",
      "type": "topic",
      "url": "/documentation/glkit/glktextureinfo/depth-c.ivar"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/depth-swift.property": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "depth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLuint",
          "text": "GLuint"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/depth-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "depth"
        }
      ],
      "role": "symbol",
      "title": "depth",
      "type": "topic",
      "url": "/documentation/glkit/glktextureinfo/depth-swift.property"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/height-c.ivar": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "height"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/height-c.ivar",
      "kind": "symbol",
      "role": "symbol",
      "title": "height",
      "type": "topic",
      "url": "/documentation/glkit/glktextureinfo/height-c.ivar"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/height-swift.property": {
      "abstract": [
        {
          "text": "The height of the loaded texture.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "height"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLuint",
          "text": "GLuint"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/height-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "height"
        }
      ],
      "role": "symbol",
      "title": "height",
      "type": "topic",
      "url": "/documentation/glkit/glktextureinfo/height-swift.property"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/mimapLevelCount-c.ivar": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mimapLevelCount"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/mimapLevelCount-c.ivar",
      "kind": "symbol",
      "role": "symbol",
      "title": "mimapLevelCount",
      "type": "topic",
      "url": "/documentation/glkit/glktextureinfo/mimaplevelcount-c.ivar"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/mimapLevelCount-swift.property": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mimapLevelCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLuint",
          "text": "GLuint"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/mimapLevelCount-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mimapLevelCount"
        }
      ],
      "role": "symbol",
      "title": "mimapLevelCount",
      "type": "topic",
      "url": "/documentation/glkit/glktextureinfo/mimaplevelcount-swift.property"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/name-c.ivar": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/name-c.ivar",
      "kind": "symbol",
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/glkit/glktextureinfo/name-c.ivar"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/name-swift.property": {
      "abstract": [
        {
          "text": "The OpenGL context’s name for the texture.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLuint",
          "text": "GLuint"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/name-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/glkit/glktextureinfo/name-swift.property"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/target-c.ivar": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "target"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/target-c.ivar",
      "kind": "symbol",
      "role": "symbol",
      "title": "target",
      "type": "topic",
      "url": "/documentation/glkit/glktextureinfo/target-c.ivar"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/target-swift.property": {
      "abstract": [
        {
          "text": "The OpenGL binding target for the texture.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "target"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLenum",
          "text": "GLenum"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/target-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "target"
        }
      ],
      "role": "symbol",
      "title": "target",
      "type": "topic",
      "url": "/documentation/glkit/glktextureinfo/target-swift.property"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/textureOrigin-c.ivar": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "textureOrigin"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/textureOrigin-c.ivar",
      "kind": "symbol",
      "role": "symbol",
      "title": "textureOrigin",
      "type": "topic",
      "url": "/documentation/glkit/glktextureinfo/textureorigin-c.ivar"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/textureOrigin-swift.property": {
      "abstract": [
        {
          "text": "The location of the origin in the loaded texture.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textureOrigin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GLKTextureInfoOrigin",
          "text": "GLKTextureInfoOrigin"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/textureOrigin-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textureOrigin"
        }
      ],
      "role": "symbol",
      "title": "textureOrigin",
      "type": "topic",
      "url": "/documentation/glkit/glktextureinfo/textureorigin-swift.property"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/width-c.ivar": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "width"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/width-c.ivar",
      "kind": "symbol",
      "role": "symbol",
      "title": "width",
      "type": "topic",
      "url": "/documentation/glkit/glktextureinfo/width-c.ivar"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/width-swift.property": {
      "abstract": [
        {
          "text": "The width of the loaded texture.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "width"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLuint",
          "text": "GLuint"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/width-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "width"
        }
      ],
      "role": "symbol",
      "title": "width",
      "type": "topic",
      "url": "/documentation/glkit/glktextureinfo/width-swift.property"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfoAlphaState": {
      "abstract": [
        {
          "text": "Values that describe the alpha information stored in a source image’s pixel data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureInfoAlphaState"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfoAlphaState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureInfoAlphaState"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureInfoAlphaState",
      "type": "topic",
      "url": "/documentation/glkit/glktextureinfoalphastate"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfoOrigin": {
      "abstract": [
        {
          "text": "The location of the origin in the original source image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureInfoOrigin"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfoOrigin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureInfoOrigin"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureInfoOrigin",
      "type": "topic",
      "url": "/documentation/glkit/glktextureinfoorigin"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoader": {
      "abstract": [
        {
          "text": "A utility class that simplifies loading OpenGL or OpenGL ES texture datas from a variety of image file formats.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureLoader"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoader"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoader",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloader"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Texture-Loading",
      "generated": true,
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoader"
      ],
      "title": "Texture Loading"
    }
  ],
  "topicSections": [
    {
      "anchor": "Reading-Texture-Information",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/name-swift.property",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/target-swift.property",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/height-swift.property",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/width-swift.property",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/textureOrigin-swift.property",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/alphaState-swift.property",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/containsMipmaps-swift.property"
      ],
      "title": "Reading Texture Information"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfoAlphaState",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfoOrigin"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/arrayLength-swift.property",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/depth-swift.property",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/mimapLevelCount-swift.property"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "12.0",
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "12.0",
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.14",
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "12.0",
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GLKTextureInfo"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.glkit/documentation/GLKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Reading-Texture-Information",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/name-swift.property",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/target-swift.property",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/height-swift.property",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/width-swift.property",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/textureOrigin-swift.property",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/alphaState-swift.property",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/containsMipmaps-swift.property"
              ],
              "title": "Reading Texture Information"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfoAlphaState",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfoOrigin"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/arrayLength-swift.property",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/depth-swift.property",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/mimapLevelCount-swift.property"
              ],
              "title": "Instance Properties"
            },
            {
              "anchor": "Instance-Variables",
              "generated": true,
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/alphaState-c.ivar",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/arrayLength-c.ivar",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/containsMipmaps-c.ivar",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/depth-c.ivar",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/height-c.ivar",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/mimapLevelCount-c.ivar",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/name-c.ivar",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/target-c.ivar",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/textureOrigin-c.ivar",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfo/width-c.ivar"
              ],
              "title": "Instance Variables"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Texture-Loading",
              "generated": true,
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoader"
              ],
              "title": "Texture Loading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GLKTextureInfo"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "OpenGLES API deprecated. (Define GLES_SILENCE_DEPRECATION to silence these warnings)",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfo~1textureOrigin-swift.property/title",
          "value": "textureOrigin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfo~1textureOrigin-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "textureOrigin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfo~1target-swift.property/title",
          "value": "target"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfo~1target-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "target"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfo~1depth-swift.property/title",
          "value": "depth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfo~1depth-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "depth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfo~1alphaState-swift.property/title",
          "value": "alphaState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfo~1alphaState-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "alphaState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfo/title",
          "value": "GLKTextureInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfo~1arrayLength-swift.property/title",
          "value": "arrayLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfo~1arrayLength-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "arrayLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfo~1height-swift.property/title",
          "value": "height"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfo~1height-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "height"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfo~1mimapLevelCount-swift.property/title",
          "value": "mimapLevelCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfo~1mimapLevelCount-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mimapLevelCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfoOrigin/title",
          "value": "GLKTextureInfoOrigin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfoOrigin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureInfoOrigin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfoOrigin/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureInfoOrigin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfo~1name-swift.property/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfo~1name-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoader/title",
          "value": "GLKTextureLoader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoader/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfo~1width-swift.property/title",
          "value": "width"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfo~1width-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "width"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfoAlphaState/title",
          "value": "GLKTextureInfoAlphaState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfoAlphaState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureInfoAlphaState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfoAlphaState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureInfoAlphaState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfo~1containsMipmaps-swift.property/title",
          "value": "containsMipmaps"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfo~1containsMipmaps-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "containsMipmaps"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/glkit/glktextureinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/glkit/glktextureinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
