{
  "abstract": [
    {
      "text": "Whether or not to create mipmaps for a texture.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.glkit/documentation/GLKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderGenerateMipmaps"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@GLKTextureLoaderGenerateMipmaps",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GLKTextureLoaderGenerateMipmaps"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "GLKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GLKTextureLoaderGenerateMipmaps"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "9.0",
        "message": "OpenGLES API deprecated. (Define GLES_SILENCE_DEPRECATION to silence these warnings)",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "GLKTextureLoaderGenerateMipmaps"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderGenerateMipmaps"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The value for this key is an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object that specifies a boolean value. If ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", only the texture is loaded. If ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", a full set of mipmap levels are generated for the texture when the texture is created. The ",
              "type": "text"
            },
            {
              "code": "GL_TEXTURE_MIN_FILTER",
              "type": "codeVoice"
            },
            {
              "text": " parameter for the texture is changed to ",
              "type": "text"
            },
            {
              "code": "GL_LINEAR_MIPMAP_LINEAR",
              "type": "codeVoice"
            },
            {
              "text": " when mipmaps are generated. If the key is not specified, the default value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nsnumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.glkit/documentation/GLKit": {
      "abstract": [
        {
          "text": "Speed up OpenGL ES or OpenGL app development. Use math libraries, background texture loading, pre-created shader effects, and a standard view and view controller to implement your rendering loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GLKit",
      "type": "topic",
      "url": "/documentation/glkit"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderApplyPremultiplication": {
      "abstract": [
        {
          "text": "Whether image data should be premultiplied before being loaded into the sharegroup.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderApplyPremultiplication"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderApplyPremultiplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderApplyPremultiplication"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderApplyPremultiplication",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloaderapplypremultiplication"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderErrorDomain": {
      "abstract": [
        {
          "text": "The error domain used by GLKit when returning texture loading errors.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderErrorDomain",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadererrordomain"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderErrorKey": {
      "abstract": [
        {
          "text": "A key used to retrieve an error string from an error object userinfo dictionary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderErrorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderErrorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderErrorKey"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderErrorKey",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadererrorkey"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderGLErrorKey": {
      "abstract": [
        {
          "text": "A key used to retrieve additional information from an error object’s userinfo dictionary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderGLErrorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderGLErrorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderGLErrorKey"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderGLErrorKey",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloaderglerrorkey"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderGenerateMipmaps": {
      "abstract": [
        {
          "text": "Whether or not to create mipmaps for a texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderGenerateMipmaps"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderGenerateMipmaps",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderGenerateMipmaps"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderGenerateMipmaps",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadergeneratemipmaps"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderGrayscaleAsAlpha": {
      "abstract": [
        {
          "text": "Whether or not to treat greyscale image data as alpha information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderGrayscaleAsAlpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderGrayscaleAsAlpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderGrayscaleAsAlpha"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderGrayscaleAsAlpha",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadergrayscaleasalpha"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderOriginBottomLeft": {
      "abstract": [
        {
          "text": "Whether or not to vertically flip image data to match OpenGL’s coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderOriginBottomLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderOriginBottomLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderOriginBottomLeft"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderOriginBottomLeft",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloaderoriginbottomleft"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderSRGB": {
      "abstract": [
        {
          "text": "Whether or not to treat texture image data as sRGB data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderSRGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderSRGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderSRGB"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderSRGB",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadersrgb"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLK_SSE3_INTRINSICS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLK_SSE3_INTRINSICS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLK_SSE3_INTRINSICS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLK_SSE3_INTRINSICS"
        }
      ],
      "role": "symbol",
      "title": "GLK_SSE3_INTRINSICS",
      "type": "topic",
      "url": "/documentation/glkit/glk_sse3_intrinsics"
    },
    "doc://com.apple.glkit/documentation/GLKit/kGLKModelErrorDomain": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kGLKModelErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/kGLKModelErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kGLKModelErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "kGLKModelErrorDomain",
      "type": "topic",
      "url": "/documentation/glkit/kglkmodelerrordomain"
    },
    "doc://com.apple.glkit/documentation/GLKit/kGLKModelErrorKey": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kGLKModelErrorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/kGLKModelErrorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kGLKModelErrorKey"
        }
      ],
      "role": "symbol",
      "title": "kGLKModelErrorKey",
      "type": "topic",
      "url": "/documentation/glkit/kglkmodelerrorkey"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderApplyPremultiplication",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderErrorDomain",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderErrorKey",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderGLErrorKey",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderGrayscaleAsAlpha",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderOriginBottomLeft",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderSRGB",
        "doc://com.apple.glkit/documentation/GLKit/GLK_SSE3_INTRINSICS",
        "doc://com.apple.glkit/documentation/GLKit/kGLKModelErrorDomain",
        "doc://com.apple.glkit/documentation/GLKit/kGLKModelErrorKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "12.0",
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GLKTextureLoaderGenerateMipmaps"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderGenerateMipmaps"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.glkit/documentation/GLKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderApplyPremultiplication",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderErrorDomain",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderErrorKey",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderGLErrorKey",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderGrayscaleAsAlpha",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderOriginBottomLeft",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderSRGB",
                "doc://com.apple.glkit/documentation/GLKit/GLK_SSE3_INTRINSICS",
                "doc://com.apple.glkit/documentation/GLKit/kGLKModelErrorDomain",
                "doc://com.apple.glkit/documentation/GLKit/kGLKModelErrorKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GLKTextureLoaderGenerateMipmaps"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderGLErrorKey/title",
          "value": "GLKTextureLoaderGLErrorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderGLErrorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderGLErrorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderGrayscaleAsAlpha/title",
          "value": "GLKTextureLoaderGrayscaleAsAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderGrayscaleAsAlpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderGrayscaleAsAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1kGLKModelErrorDomain/title",
          "value": "kGLKModelErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1kGLKModelErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kGLKModelErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderErrorDomain/title",
          "value": "GLKTextureLoaderErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1kGLKModelErrorKey/title",
          "value": "kGLKModelErrorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1kGLKModelErrorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kGLKModelErrorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderGenerateMipmaps/title",
          "value": "GLKTextureLoaderGenerateMipmaps"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderGenerateMipmaps/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderGenerateMipmaps"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderErrorKey/title",
          "value": "GLKTextureLoaderErrorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderErrorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderErrorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLK_SSE3_INTRINSICS/title",
          "value": "GLK_SSE3_INTRINSICS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLK_SSE3_INTRINSICS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLK_SSE3_INTRINSICS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderSRGB/title",
          "value": "GLKTextureLoaderSRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderSRGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderSRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderApplyPremultiplication/title",
          "value": "GLKTextureLoaderApplyPremultiplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderApplyPremultiplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderApplyPremultiplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderOriginBottomLeft/title",
          "value": "GLKTextureLoaderOriginBottomLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderOriginBottomLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderOriginBottomLeft"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/glkit/glktextureloadergeneratemipmaps"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/glkit/glktextureloadergeneratemipmaps"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
