{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.glkit/documentation/GLKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.glkit/documentation/GLKit/glkvector2-pbj"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "GLKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "GLKVector2"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "GLKVector2",
              "type": "codeVoice"
            },
            {
              "text": " type defines a ",
              "type": "text"
            },
            {
              "code": "2",
              "type": "codeVoice"
            },
            {
              "text": "-component floating-point vector as well as many mathematical operations commonly used to manipulate vectors. Graphics programming uses vectors extensively to represent positions, colors and other data structures.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The functions that manipulate ",
              "type": "text"
            },
            {
              "code": "GLKVector2",
              "type": "codeVoice"
            },
            {
              "text": " structures treat the inputs as immutable, instead returning a new vector that represent the results of the operation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.glkit/documentation/GLKit": {
      "abstract": [
        {
          "text": "Speed up OpenGL ES or OpenGL app development. Use math libraries, background texture loading, pre-created shader effects, and a standard view and view controller to implement your rendering loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GLKit",
      "type": "topic",
      "url": "/documentation/glkit"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStack": {
      "abstract": [
        {
          "text": "An opaque type that represents a stack of 4 x 4 matrices, providing support for hierarchical transform modeling and similar tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrixStack"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrixStack"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrixStack",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrixstack"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2": {
      "abstract": [
        {
          "text": "A representation of a 2-component vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2Add(_:_:)": {
      "abstract": [
        {
          "text": "Returns the sum of two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2Add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2Add(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2Add"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2Add(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2add(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2AddScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by adding a scalar value to each component of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2AddScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2AddScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2AddScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2AddScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2addscalar(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2AllEqualToScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that states whether all the components of the source vector are equal to a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2AllEqualToScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2AllEqualToScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2AllEqualToScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2AllEqualToScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2allequaltoscalar(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2AllEqualToVector2(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether each component of the first vector is equal to the corresponding component of a second vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2AllEqualToVector2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2AllEqualToVector2(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2AllEqualToVector2"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2AllEqualToVector2(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2allequaltovector2(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2AllGreaterThanOrEqualToScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that states whether all the components of the source vector are greater than or equal to a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2AllGreaterThanOrEqualToScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2AllGreaterThanOrEqualToScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2AllGreaterThanOrEqualToScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2AllGreaterThanOrEqualToScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2allgreaterthanorequaltoscalar(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2AllGreaterThanOrEqualToVector2(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether each component of the first vector is greater than or equal to the corresponding component of a second vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2AllGreaterThanOrEqualToVector2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2AllGreaterThanOrEqualToVector2(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2AllGreaterThanOrEqualToVector2"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2AllGreaterThanOrEqualToVector2(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2allgreaterthanorequaltovector2(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2AllGreaterThanScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that states whether all the components of the source vector are greater than a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2AllGreaterThanScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2AllGreaterThanScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2AllGreaterThanScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2AllGreaterThanScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2allgreaterthanscalar(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2AllGreaterThanVector2(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether each component of the first vector is greater than the corresponding component of a second vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2AllGreaterThanVector2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2AllGreaterThanVector2(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2AllGreaterThanVector2"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2AllGreaterThanVector2(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2allgreaterthanvector2(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2Distance(_:_:)": {
      "abstract": [
        {
          "text": "Returns the distance between two points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2Distance"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2Distance(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2Distance"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2Distance(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2distance(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2Divide(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by dividing one vector by another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2Divide"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2Divide(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2Divide"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2Divide(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2divide(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2DivideScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by dividing each component of a vector by a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2DivideScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2DivideScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2DivideScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2DivideScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2dividescalar(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2DotProduct(_:_:)": {
      "abstract": [
        {
          "text": "Returns the dot product of two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2DotProduct"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2DotProduct(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2DotProduct"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2DotProduct(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2dotproduct(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2Length(_:)": {
      "abstract": [
        {
          "text": "Returns the length of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2Length"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2Length(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2Length"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2Length(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2length(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2Lerp(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by linearly interpreting between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2Lerp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2Lerp(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2Lerp"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2Lerp(_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2lerp(_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2Make(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new two-component vector created from individual component values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2Make"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2Make(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2Make"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2Make(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2make(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2MakeWithArray(_:)": {
      "abstract": [
        {
          "text": "Returns a new two-component vector created from an array of components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2MakeWithArray"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2MakeWithArray(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2MakeWithArray"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2MakeWithArray(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2makewitharray(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2Maximum(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector whose component value at each position is the largest component value at the same position of the two source vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2Maximum"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2Maximum(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2Maximum"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2Maximum(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2maximum(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2Minimum(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector whose component value at each position is the smallest component value at the same position of the two source vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2Minimum"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2Minimum(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2Minimum"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2Minimum(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2minimum(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2Multiply(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by multiplying one vector by another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2Multiply"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2Multiply(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2Multiply"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2Multiply(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2multiply(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2MultiplyScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by multiplying each component of a vector by a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2MultiplyScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2MultiplyScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2MultiplyScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2MultiplyScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2multiplyscalar(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2Negate(_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by negating the component values of another vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2Negate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2Negate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2Negate"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2Negate(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2negate(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2Normalize(_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by normalizing an input vector to a length of ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2Normalize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2Normalize(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2Normalize"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2Normalize(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2normalize(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2Project(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by projecting a vector onto another vector",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2Project"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2Project(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2Project"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2Project(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2project(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2Subtract(_:_:)": {
      "abstract": [
        {
          "text": "Returns the difference between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2Subtract"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2Subtract(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2Subtract"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2Subtract(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2subtract(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2SubtractScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by subtracting a scalar value from each component of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2SubtractScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2SubtractScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2SubtractScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2SubtractScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2subtractscalar(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkit-math-utilities": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkit-math-utilities",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKit Math Utilities",
      "type": "topic",
      "url": "/documentation/glkit/glkit-math-utilities"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkmatrix3-pcl": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkmatrix3-pcl",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKMatrix3",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3-pcl"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkmatrix4-pce": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkmatrix4-pce",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKMatrix4",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4-pce"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkquaternion-pc6": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkquaternion-pc6",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKQuaternion",
      "type": "topic",
      "url": "/documentation/glkit/glkquaternion-pc6"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkvector3-pbt": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkvector3-pbt",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKVector3",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3-pbt"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkvector4-pbk": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkvector4-pbk",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKVector4",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4-pbk"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Math-Utilties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStack",
        "doc://com.apple.glkit/documentation/GLKit/glkmatrix3-pcl",
        "doc://com.apple.glkit/documentation/GLKit/glkmatrix4-pce",
        "doc://com.apple.glkit/documentation/GLKit/glkvector3-pbt",
        "doc://com.apple.glkit/documentation/GLKit/glkvector4-pbk",
        "doc://com.apple.glkit/documentation/GLKit/glkquaternion-pc6",
        "doc://com.apple.glkit/documentation/GLKit/glkit-math-utilities"
      ],
      "title": "Math Utilties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Vectors",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2Make(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2MakeWithArray(_:)"
      ],
      "title": "Creating Vectors"
    },
    {
      "anchor": "Retrieving-Information-About-a-Vector",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2Length(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2Distance(_:_:)"
      ],
      "title": "Retrieving Information About a Vector"
    },
    {
      "anchor": "Mathematical-Operations-Performed-on-Vectors",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2Negate(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2Normalize(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2AddScalar(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2SubtractScalar(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2MultiplyScalar(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2DivideScalar(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2Add(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2Subtract(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2Multiply(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2Divide(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2DotProduct(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2Lerp(_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2Project(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2Maximum(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2Minimum(_:_:)"
      ],
      "title": "Mathematical Operations Performed on Vectors"
    },
    {
      "anchor": "Comparison-Operations",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2AllEqualToScalar(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2AllEqualToVector2(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2AllGreaterThanOrEqualToScalar(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2AllGreaterThanOrEqualToVector2(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2AllGreaterThanScalar(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2AllGreaterThanVector2(_:_:)"
      ],
      "title": "Comparison Operations"
    },
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Vectors",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2Make(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2MakeWithArray(_:)"
              ],
              "title": "Creating Vectors"
            },
            {
              "anchor": "Retrieving-Information-About-a-Vector",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2Length(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2Distance(_:_:)"
              ],
              "title": "Retrieving Information About a Vector"
            },
            {
              "anchor": "Mathematical-Operations-Performed-on-Vectors",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2Negate(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2Normalize(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2AddScalar(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2SubtractScalar(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2MultiplyScalar(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2DivideScalar(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2Add(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2Subtract(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2Multiply(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2Divide(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2DotProduct(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2Lerp(_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2Project(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2Maximum(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2Minimum(_:_:)"
              ],
              "title": "Mathematical Operations Performed on Vectors"
            },
            {
              "anchor": "Comparison-Operations",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2AllEqualToScalar(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2AllEqualToVector2(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2AllGreaterThanOrEqualToScalar(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2AllGreaterThanOrEqualToVector2(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2AllGreaterThanScalar(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2AllGreaterThanVector2(_:_:)"
              ],
              "title": "Comparison Operations"
            },
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Math-Utilties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStack",
                "doc://com.apple.glkit/documentation/GLKit/glkmatrix3-pcl",
                "doc://com.apple.glkit/documentation/GLKit/glkmatrix4-pce",
                "doc://com.apple.glkit/documentation/GLKit/glkvector3-pbt",
                "doc://com.apple.glkit/documentation/GLKit/glkvector4-pbk",
                "doc://com.apple.glkit/documentation/GLKit/glkquaternion-pc6",
                "doc://com.apple.glkit/documentation/GLKit/glkit-math-utilities"
              ],
              "title": "Math Utilties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2SubtractScalar(_:_:)/title",
          "value": "GLKVector2SubtractScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2SubtractScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2SubtractScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Length(_:)/title",
          "value": "GLKVector2Length"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Length(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2Length"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2AllEqualToVector2(_:_:)/title",
          "value": "GLKVector2AllEqualToVector2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2AllEqualToVector2(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2AllEqualToVector2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Add(_:_:)/title",
          "value": "GLKVector2Add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Add(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2Add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2DotProduct(_:_:)/title",
          "value": "GLKVector2DotProduct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2DotProduct(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2DotProduct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Multiply(_:_:)/title",
          "value": "GLKVector2Multiply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Multiply(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2Multiply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2MultiplyScalar(_:_:)/title",
          "value": "GLKVector2MultiplyScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2MultiplyScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2MultiplyScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2AllGreaterThanOrEqualToScalar(_:_:)/title",
          "value": "GLKVector2AllGreaterThanOrEqualToScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2AllGreaterThanOrEqualToScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2AllGreaterThanOrEqualToScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Divide(_:_:)/title",
          "value": "GLKVector2Divide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Divide(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2Divide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Distance(_:_:)/title",
          "value": "GLKVector2Distance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Distance(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2Distance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2AllGreaterThanVector2(_:_:)/title",
          "value": "GLKVector2AllGreaterThanVector2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2AllGreaterThanVector2(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2AllGreaterThanVector2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Project(_:_:)/title",
          "value": "GLKVector2Project"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Project(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2Project"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2AllGreaterThanScalar(_:_:)/title",
          "value": "GLKVector2AllGreaterThanScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2AllGreaterThanScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2AllGreaterThanScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2/title",
          "value": "GLKVector2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Maximum(_:_:)/title",
          "value": "GLKVector2Maximum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Maximum(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2Maximum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Minimum(_:_:)/title",
          "value": "GLKVector2Minimum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Minimum(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2Minimum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2DivideScalar(_:_:)/title",
          "value": "GLKVector2DivideScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2DivideScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2DivideScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Make(_:_:)/title",
          "value": "GLKVector2Make"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Make(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2Make"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2MakeWithArray(_:)/title",
          "value": "GLKVector2MakeWithArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2MakeWithArray(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2MakeWithArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStack/title",
          "value": "GLKMatrixStackRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrixStackRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrixStackRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Subtract(_:_:)/title",
          "value": "GLKVector2Subtract"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Subtract(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2Subtract"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2AllEqualToScalar(_:_:)/title",
          "value": "GLKVector2AllEqualToScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2AllEqualToScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2AllEqualToScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Negate(_:)/title",
          "value": "GLKVector2Negate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Negate(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2Negate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2AllGreaterThanOrEqualToVector2(_:_:)/title",
          "value": "GLKVector2AllGreaterThanOrEqualToVector2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2AllGreaterThanOrEqualToVector2(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2AllGreaterThanOrEqualToVector2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Normalize(_:)/title",
          "value": "GLKVector2Normalize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Normalize(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2Normalize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Lerp(_:_:_:)/title",
          "value": "GLKVector2Lerp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Lerp(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2Lerp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2AddScalar(_:_:)/title",
          "value": "GLKVector2AddScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2AddScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2AddScalar"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/glkit/glkvector2-pbj"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/glkit/glkvector2-pbj"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
