{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.glkit/documentation/GLKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.glkit/documentation/GLKit/GLKVertexAttributeParametersFromModelIO(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@GLKVertexAttributeParametersFromModelIO",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GLKVertexAttributeParametersFromModelIO"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MDLVertexFormat",
        "text": "MDLVertexFormat"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "text": "GLKVertexAttributeParameters"
      }
    ],
    "modules": [
      {
        "name": "GLKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GLKVertexAttributeParametersFromModelIO"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "GLKVertexAttributeParametersFromModelIO(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GLKVertexAttributeParametersFromModelIO"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "vertexFormat"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@E@MDLVertexFormat",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MDLVertexFormat",
              "text": "MDLVertexFormat"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "kind": "typeIdentifier",
              "text": "GLKVertexAttributeParameters"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.glkit/documentation/GLKit": {
      "abstract": [
        {
          "text": "Speed up OpenGL ES or OpenGL app development. Use math libraries, background texture loading, pre-created shader effects, and a standard view and view controller to implement your rendering loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GLKit",
      "type": "topic",
      "url": "/documentation/glkit"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackCreate(_:)": {
      "abstract": [
        {
          "text": "Allocates and returns a new matrix stack.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrixStackCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLKMatrixStackRef",
          "text": "GLKMatrixStack"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackCreate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrixStackCreate"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrixStackCreate(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrixstackcreate(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetMatrix2(_:)": {
      "abstract": [
        {
          "text": "Returns the top-left ",
          "type": "text"
        },
        {
          "code": "2x2",
          "type": "codeVoice"
        },
        {
          "text": " corner of the top matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrixStackGetMatrix2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLKMatrixStackRef",
          "text": "GLKMatrixStack"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetMatrix2(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrixStackGetMatrix2"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrixStackGetMatrix2(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrixstackgetmatrix2(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetMatrix3(_:)": {
      "abstract": [
        {
          "text": "Returns the top-left ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " corner of the top matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrixStackGetMatrix3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLKMatrixStackRef",
          "text": "GLKMatrixStack"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetMatrix3(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrixStackGetMatrix3"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrixStackGetMatrix3(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrixstackgetmatrix3(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetMatrix3Inverse(_:)": {
      "abstract": [
        {
          "text": "Fetches the top-left ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " corner of the top matrix and returns its inverse.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrixStackGetMatrix3Inverse"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLKMatrixStackRef",
          "text": "GLKMatrixStack"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetMatrix3Inverse(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrixStackGetMatrix3Inverse"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrixStackGetMatrix3Inverse(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrixstackgetmatrix3inverse(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetMatrix3InverseTranspose(_:)": {
      "abstract": [
        {
          "text": "Fetches the top-left ",
          "type": "text"
        },
        {
          "code": "3x3",
          "type": "codeVoice"
        },
        {
          "text": " corner of the top matrix and returns its inverse transpose.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrixStackGetMatrix3InverseTranspose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLKMatrixStackRef",
          "text": "GLKMatrixStack"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetMatrix3InverseTranspose(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrixStackGetMatrix3InverseTranspose"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrixStackGetMatrix3InverseTranspose(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrixstackgetmatrix3inversetranspose(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetMatrix4(_:)": {
      "abstract": [
        {
          "text": "Returns a copy of the top matrix on the stack.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrixStackGetMatrix4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLKMatrixStackRef",
          "text": "GLKMatrixStack"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetMatrix4(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrixStackGetMatrix4"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrixStackGetMatrix4(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrixstackgetmatrix4(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetMatrix4Inverse(_:)": {
      "abstract": [
        {
          "text": "Returns the inverse of the top matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrixStackGetMatrix4Inverse"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLKMatrixStackRef",
          "text": "GLKMatrixStack"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetMatrix4Inverse(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrixStackGetMatrix4Inverse"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrixStackGetMatrix4Inverse(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrixstackgetmatrix4inverse(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetMatrix4InverseTranspose(_:)": {
      "abstract": [
        {
          "text": "Returns the inverse transpose of the top matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrixStackGetMatrix4InverseTranspose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLKMatrixStackRef",
          "text": "GLKMatrixStack"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetMatrix4InverseTranspose(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrixStackGetMatrix4InverseTranspose"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrixStackGetMatrix4InverseTranspose(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrixstackgetmatrix4inversetranspose(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetTypeID()": {
      "abstract": [
        {
          "text": "Returns the Core Foundation type for a matrix stack.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrixStackGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrixStackGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrixStackGetTypeID()",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrixstackgettypeid()"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackLoadMatrix4(_:_:)": {
      "abstract": [
        {
          "text": "Replaces the contents of the top matrix with a new matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrixStackLoadMatrix4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLKMatrixStackRef",
          "text": "GLKMatrixStack"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackLoadMatrix4(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrixStackLoadMatrix4"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrixStackLoadMatrix4(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrixstackloadmatrix4(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackMultiplyMatrix4(_:_:)": {
      "abstract": [
        {
          "text": "Replaces the contents of the top matrix with a matrix calculated by multiplying the contents of the top matrix by another matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrixStackMultiplyMatrix4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLKMatrixStackRef",
          "text": "GLKMatrixStack"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackMultiplyMatrix4(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrixStackMultiplyMatrix4"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrixStackMultiplyMatrix4(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrixstackmultiplymatrix4(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackMultiplyMatrixStack(_:_:)": {
      "abstract": [
        {
          "text": "Replaces the contents of the top matrix with a matrix calculated by multiplying the contents of the top matrix by the top matrix of another matrix stack.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrixStackMultiplyMatrixStack"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLKMatrixStackRef",
          "text": "GLKMatrixStack"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLKMatrixStackRef",
          "text": "GLKMatrixStack"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackMultiplyMatrixStack(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrixStackMultiplyMatrixStack"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrixStackMultiplyMatrixStack(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrixstackmultiplymatrixstack(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackPop(_:)": {
      "abstract": [
        {
          "text": "Removes the topmost entry from the stack.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrixStackPop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLKMatrixStackRef",
          "text": "GLKMatrixStack"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackPop(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrixStackPop"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrixStackPop(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrixstackpop(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackPush(_:)": {
      "abstract": [
        {
          "text": "Push a copy of the topmost matrix onto the top of the stack.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrixStackPush"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLKMatrixStackRef",
          "text": "GLKMatrixStack"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackPush(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrixStackPush"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrixStackPush(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrixstackpush(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackRotate(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Replaces the contents of the top matrix with a matrix calculated by composing the top matrix with a rotation around an arbitrary axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrixStackRotate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLKMatrixStackRef",
          "text": "GLKMatrixStack"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackRotate(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrixStackRotate"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrixStackRotate(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrixstackrotate(_:_:_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVertexAttributeParametersFromModelIO(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVertexAttributeParametersFromModelIO"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLVertexFormat",
          "text": "MDLVertexFormat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVertexAttributeParameters"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVertexAttributeParametersFromModelIO(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVertexAttributeParametersFromModelIO"
        }
      ],
      "role": "symbol",
      "title": "GLKVertexAttributeParametersFromModelIO(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvertexattributeparametersfrommodelio(_:)"
    },
    "doc://com.externally.resolved.symbol/c:@E@MDLVertexFormat": {
      "abstract": [
        {
          "text": "Descriptions of the data size and layout for a vertex attribute, used by the [`format`](doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/format) property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexFormat"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@E@MDLVertexFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "MDLVertexFormat",
      "type": "topic",
      "url": "/documentation/ModelIO/MDLVertexFormat"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackCreate(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetMatrix2(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetMatrix3(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetMatrix3Inverse(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetMatrix3InverseTranspose(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetMatrix4(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetMatrix4Inverse(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetMatrix4InverseTranspose(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetTypeID()",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackLoadMatrix4(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackMultiplyMatrix4(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackMultiplyMatrixStack(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackPop(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackPush(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackRotate(_:_:_:_:_:)"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GLKVertexAttributeParametersFromModelIO"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVertexAttributeParametersFromModelIO"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.glkit/documentation/GLKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackCreate(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetMatrix2(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetMatrix3(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetMatrix3Inverse(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetMatrix3InverseTranspose(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetMatrix4(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetMatrix4Inverse(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetMatrix4InverseTranspose(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackGetTypeID()",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackLoadMatrix4(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackMultiplyMatrix4(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackMultiplyMatrixStack(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackPop(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackPush(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStackRotate(_:_:_:_:_:)"
              ],
              "title": "Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@_GLKVertexAttributeParameters",
                    "text": "GLKVertexAttributeParameters"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GLKVertexAttributeParametersFromModelIO"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@E@MDLVertexFormat",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@MDLVertexFormat",
                    "text": "MDLVertexFormat"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "vertexFormat"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@E@MDLVertexFormat/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MDLVertexFormat"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStackGetMatrix3(_:)/title",
          "value": "GLKMatrixStackGetMatrix3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStackGetMatrix3(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrixStackGetMatrix3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStackGetMatrix3InverseTranspose(_:)/title",
          "value": "GLKMatrixStackGetMatrix3InverseTranspose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStackGetMatrix3InverseTranspose(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrixStackGetMatrix3InverseTranspose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStackMultiplyMatrixStack(_:_:)/title",
          "value": "GLKMatrixStackMultiplyMatrixStack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStackMultiplyMatrixStack(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrixStackMultiplyMatrixStack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStackGetTypeID()/title",
          "value": "GLKMatrixStackGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStackGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrixStackGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStackGetMatrix4Inverse(_:)/title",
          "value": "GLKMatrixStackGetMatrix4Inverse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStackGetMatrix4Inverse(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrixStackGetMatrix4Inverse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStackGetMatrix4InverseTranspose(_:)/title",
          "value": "GLKMatrixStackGetMatrix4InverseTranspose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStackGetMatrix4InverseTranspose(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrixStackGetMatrix4InverseTranspose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStackMultiplyMatrix4(_:_:)/title",
          "value": "GLKMatrixStackMultiplyMatrix4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStackMultiplyMatrix4(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrixStackMultiplyMatrix4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStackLoadMatrix4(_:_:)/title",
          "value": "GLKMatrixStackLoadMatrix4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStackLoadMatrix4(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrixStackLoadMatrix4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStackGetMatrix4(_:)/title",
          "value": "GLKMatrixStackGetMatrix4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStackGetMatrix4(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrixStackGetMatrix4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStackPush(_:)/title",
          "value": "GLKMatrixStackPush"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStackPush(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrixStackPush"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStackGetMatrix2(_:)/title",
          "value": "GLKMatrixStackGetMatrix2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStackGetMatrix2(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrixStackGetMatrix2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStackPop(_:)/title",
          "value": "GLKMatrixStackPop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStackPop(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrixStackPop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStackGetMatrix3Inverse(_:)/title",
          "value": "GLKMatrixStackGetMatrix3Inverse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStackGetMatrix3Inverse(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrixStackGetMatrix3Inverse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStackCreate(_:)/title",
          "value": "GLKMatrixStackCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStackCreate(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrixStackCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStackRotate(_:_:_:_:_:)/title",
          "value": "GLKMatrixStackRotate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStackRotate(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrixStackRotate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVertexAttributeParametersFromModelIO(_:)/title",
          "value": "GLKVertexAttributeParametersFromModelIO"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVertexAttributeParametersFromModelIO(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVertexAttributeParametersFromModelIO"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/glkit/glkvertexattributeparametersfrommodelio(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/glkit/glkvertexattributeparametersfrommodelio(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
