{
  "abstract": [
    {
      "text": "Returns a new vector created by subtracting a scalar value from each component of a vector.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.glkit/documentation/GLKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.glkit/documentation/GLKit/GLKVector2SubtractScalar(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@GLKVector2SubtractScalar",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GLKVector2SubtractScalar"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "text": "GLKVector2"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sf",
        "text": "Float"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "text": "GLKVector2"
      }
    ],
    "modules": [
      {
        "name": "GLKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GLKVector2SubtractScalar"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "GLKVector2SubtractScalar(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GLKVector2SubtractScalar"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "vector"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "GLKVector2"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "value"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sf",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sf",
              "text": "Float"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "kind": "typeIdentifier",
              "text": "GLKVector2"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A vector.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "vector"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A scalar value.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "value"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A new vector.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.glkit/documentation/GLKit": {
      "abstract": [
        {
          "text": "Speed up OpenGL ES or OpenGL app development. Use math libraries, background texture loading, pre-created shader effects, and a standard view and view controller to implement your rendering loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GLKit",
      "type": "topic",
      "url": "/documentation/glkit"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2Add(_:_:)": {
      "abstract": [
        {
          "text": "Returns the sum of two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2Add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2Add(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2Add"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2Add(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2add(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2AddScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by adding a scalar value to each component of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2AddScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2AddScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2AddScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2AddScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2addscalar(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2Divide(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by dividing one vector by another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2Divide"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2Divide(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2Divide"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2Divide(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2divide(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2DivideScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by dividing each component of a vector by a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2DivideScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2DivideScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2DivideScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2DivideScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2dividescalar(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2DotProduct(_:_:)": {
      "abstract": [
        {
          "text": "Returns the dot product of two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2DotProduct"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2DotProduct(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2DotProduct"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2DotProduct(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2dotproduct(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2Lerp(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by linearly interpreting between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2Lerp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2Lerp(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2Lerp"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2Lerp(_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2lerp(_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2Maximum(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector whose component value at each position is the largest component value at the same position of the two source vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2Maximum"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2Maximum(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2Maximum"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2Maximum(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2maximum(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2Minimum(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector whose component value at each position is the smallest component value at the same position of the two source vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2Minimum"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2Minimum(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2Minimum"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2Minimum(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2minimum(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2Multiply(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by multiplying one vector by another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2Multiply"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2Multiply(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2Multiply"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2Multiply(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2multiply(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2MultiplyScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by multiplying each component of a vector by a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2MultiplyScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2MultiplyScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2MultiplyScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2MultiplyScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2multiplyscalar(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2Negate(_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by negating the component values of another vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2Negate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2Negate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2Negate"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2Negate(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2negate(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2Normalize(_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by normalizing an input vector to a length of ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2Normalize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2Normalize(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2Normalize"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2Normalize(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2normalize(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2Project(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by projecting a vector onto another vector",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2Project"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2Project(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2Project"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2Project(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2project(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2Subtract(_:_:)": {
      "abstract": [
        {
          "text": "Returns the difference between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2Subtract"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2Subtract(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2Subtract"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2Subtract(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2subtract(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector2SubtractScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by subtracting a scalar value from each component of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector2SubtractScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector2SubtractScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector2SubtractScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector2SubtractScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2subtractscalar(_:_:)"
    },
    "doc://com.externally.resolved.symbol/s:Sf": {
      "abstract": [
        {
          "text": "A single-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sf",
      "kind": "symbol",
      "role": "symbol",
      "title": "Float",
      "type": "topic",
      "url": "/documentation/Swift/Float"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Mathematical-Operations-Performed-on-Vectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2Negate(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2Normalize(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2AddScalar(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2MultiplyScalar(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2DivideScalar(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2Add(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2Subtract(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2Multiply(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2Divide(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2DotProduct(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2Lerp(_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2Project(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2Maximum(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector2Minimum(_:_:)"
      ],
      "title": "Mathematical Operations Performed on Vectors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GLKVector2SubtractScalar"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2SubtractScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.glkit/documentation/GLKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Mathematical-Operations-Performed-on-Vectors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2Negate(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2Normalize(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2AddScalar(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2MultiplyScalar(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2DivideScalar(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2Add(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2Subtract(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2Multiply(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2Divide(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2DotProduct(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2Lerp(_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2Project(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2Maximum(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector2Minimum(_:_:)"
              ],
              "title": "Mathematical Operations Performed on Vectors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@U@_GLKVector2",
                    "text": "GLKVector2"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GLKVector2SubtractScalar"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@U@_GLKVector2",
                    "text": "GLKVector2"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "vector"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:f",
                    "text": "float"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "value"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A vector.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "vector"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A scalar value.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "value"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A new vector.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2DotProduct(_:_:)/title",
          "value": "GLKVector2DotProduct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2DotProduct(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2DotProduct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Divide(_:_:)/title",
          "value": "GLKVector2Divide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Divide(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2Divide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2DivideScalar(_:_:)/title",
          "value": "GLKVector2DivideScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2DivideScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2DivideScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2MultiplyScalar(_:_:)/title",
          "value": "GLKVector2MultiplyScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2MultiplyScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2MultiplyScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Multiply(_:_:)/title",
          "value": "GLKVector2Multiply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Multiply(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2Multiply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Negate(_:)/title",
          "value": "GLKVector2Negate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Negate(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2Negate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Subtract(_:_:)/title",
          "value": "GLKVector2Subtract"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Subtract(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2Subtract"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Maximum(_:_:)/title",
          "value": "GLKVector2Maximum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Maximum(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2Maximum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2SubtractScalar(_:_:)/title",
          "value": "GLKVector2SubtractScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2SubtractScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2SubtractScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2AddScalar(_:_:)/title",
          "value": "GLKVector2AddScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2AddScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2AddScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Lerp(_:_:_:)/title",
          "value": "GLKVector2Lerp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Lerp(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2Lerp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Normalize(_:)/title",
          "value": "GLKVector2Normalize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Normalize(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2Normalize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Add(_:_:)/title",
          "value": "GLKVector2Add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Add(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2Add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Minimum(_:_:)/title",
          "value": "GLKVector2Minimum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Minimum(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2Minimum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Project(_:_:)/title",
          "value": "GLKVector2Project"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector2Project(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector2Project"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/glkit/glkvector2subtractscalar(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/glkit/glkvector2subtractscalar(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
