{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.glkit/documentation/GLKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.glkit/documentation/GLKit/glkvector3-pbt"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "GLKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "GLKVector3"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "GLKVector3",
              "type": "codeVoice"
            },
            {
              "text": " type defines a ",
              "type": "text"
            },
            {
              "code": "3",
              "type": "codeVoice"
            },
            {
              "text": "-component floating-point vector as well as many mathematical operations commonly used to manipulate vectors. Graphics programming uses vectors extensively to represent positions, normals, colors and other data structures.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The functions that manipulate ",
              "type": "text"
            },
            {
              "code": "GLKVector3",
              "type": "codeVoice"
            },
            {
              "text": " structures treat the inputs as immutable, instead returning a new vector that represent the results of the operation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.glkit/documentation/GLKit": {
      "abstract": [
        {
          "text": "Speed up OpenGL ES or OpenGL app development. Use math libraries, background texture loading, pre-created shader effects, and a standard view and view controller to implement your rendering loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GLKit",
      "type": "topic",
      "url": "/documentation/glkit"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStack": {
      "abstract": [
        {
          "text": "An opaque type that represents a stack of 4 x 4 matrices, providing support for hierarchical transform modeling and similar tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrixStack"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrixStack"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrixStack",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrixstack"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3": {
      "abstract": [
        {
          "text": "A representation of a 3-component vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3Add(_:_:)": {
      "abstract": [
        {
          "text": "Returns the sum of two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3Add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3Add(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3Add"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3Add(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3add(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3AddScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by adding a scalar value to each component of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3AddScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3AddScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3AddScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3AddScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3addscalar(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3AllEqualToScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that states whether all the components of the source vector are equal to a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3AllEqualToScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3AllEqualToScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3AllEqualToScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3AllEqualToScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3allequaltoscalar(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3AllEqualToVector3(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether each component of the first vector is equal to the corresponding component of a second vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3AllEqualToVector3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3AllEqualToVector3(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3AllEqualToVector3"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3AllEqualToVector3(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3allequaltovector3(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3AllGreaterThanOrEqualToScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that states whether all the components of the source vector are greater than or equal to a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3AllGreaterThanOrEqualToScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3AllGreaterThanOrEqualToScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3AllGreaterThanOrEqualToScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3AllGreaterThanOrEqualToScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3allgreaterthanorequaltoscalar(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3AllGreaterThanOrEqualToVector3(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether each component of the first vector is greater than or equal to the corresponding component of a second vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3AllGreaterThanOrEqualToVector3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3AllGreaterThanOrEqualToVector3(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3AllGreaterThanOrEqualToVector3"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3AllGreaterThanOrEqualToVector3(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3allgreaterthanorequaltovector3(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3AllGreaterThanScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that states whether all the components of the source vector are greater than a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3AllGreaterThanScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3AllGreaterThanScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3AllGreaterThanScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3AllGreaterThanScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3allgreaterthanscalar(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3AllGreaterThanVector3(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether each component of the first vector is greater than the corresponding component of a second vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3AllGreaterThanVector3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3AllGreaterThanVector3(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3AllGreaterThanVector3"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3AllGreaterThanVector3(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3allgreaterthanvector3(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3CrossProduct(_:_:)": {
      "abstract": [
        {
          "text": "Returns the cross product of two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3CrossProduct"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3CrossProduct(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3CrossProduct"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3CrossProduct(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3crossproduct(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3Distance(_:_:)": {
      "abstract": [
        {
          "text": "Returns the distance between two points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3Distance"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3Distance(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3Distance"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3Distance(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3distance(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3Divide(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by dividing one vector by another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3Divide"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3Divide(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3Divide"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3Divide(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3divide(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3DivideScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by dividing each component of a vector by a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3DivideScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3DivideScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3DivideScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3DivideScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3dividescalar(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3DotProduct(_:_:)": {
      "abstract": [
        {
          "text": "Returns the dot product of two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3DotProduct"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3DotProduct(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3DotProduct"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3DotProduct(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3dotproduct(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3Length(_:)": {
      "abstract": [
        {
          "text": "Returns the length of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3Length"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3Length(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3Length"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3Length(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3length(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3Lerp(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by linearly interpreting between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3Lerp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3Lerp(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3Lerp"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3Lerp(_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3lerp(_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3Make(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new three-component vector created from individual component values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3Make"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3Make(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3Make"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3Make(_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3make(_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3MakeWithArray(_:)": {
      "abstract": [
        {
          "text": "Returns a new three-component vector created from an array of components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3MakeWithArray"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3MakeWithArray(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3MakeWithArray"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3MakeWithArray(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3makewitharray(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3Maximum(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector whose component value at each position is the largest component value at the same position in the source vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3Maximum"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3Maximum(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3Maximum"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3Maximum(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3maximum(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3Minimum(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector whose component value at each position is the smallest component value at the same position in the source vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3Minimum"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3Minimum(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3Minimum"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3Minimum(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3minimum(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3Multiply(_:_:)": {
      "abstract": [
        {
          "text": "Returns the product of two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3Multiply"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3Multiply(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3Multiply"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3Multiply(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3multiply(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3MultiplyScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by multiplying each component of a vector by a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3MultiplyScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3MultiplyScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3MultiplyScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3MultiplyScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3multiplyscalar(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3Negate(_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by negating the component values of another vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3Negate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3Negate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3Negate"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3Negate(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3negate(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3Normalize(_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by normalizing the input vector to a length of ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3Normalize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3Normalize(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3Normalize"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3Normalize(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3normalize(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3Project(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by projecting a vector onto another vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3Project"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3Project(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3Project"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3Project(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3project(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3Subtract(_:_:)": {
      "abstract": [
        {
          "text": "Returns the difference between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3Subtract"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3Subtract(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3Subtract"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3Subtract(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3subtract(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3SubtractScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by subtracting a scalar value from each component of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3SubtractScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3SubtractScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3SubtractScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3SubtractScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3subtractscalar(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkit-math-utilities": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkit-math-utilities",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKit Math Utilities",
      "type": "topic",
      "url": "/documentation/glkit/glkit-math-utilities"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkmatrix3-pcl": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkmatrix3-pcl",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKMatrix3",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3-pcl"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkmatrix4-pce": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkmatrix4-pce",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKMatrix4",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4-pce"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkquaternion-pc6": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkquaternion-pc6",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKQuaternion",
      "type": "topic",
      "url": "/documentation/glkit/glkquaternion-pc6"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkvector2-pbj": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkvector2-pbj",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKVector2",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2-pbj"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkvector4-pbk": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkvector4-pbk",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKVector4",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4-pbk"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Math-Utilties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStack",
        "doc://com.apple.glkit/documentation/GLKit/glkmatrix3-pcl",
        "doc://com.apple.glkit/documentation/GLKit/glkmatrix4-pce",
        "doc://com.apple.glkit/documentation/GLKit/glkvector2-pbj",
        "doc://com.apple.glkit/documentation/GLKit/glkvector4-pbk",
        "doc://com.apple.glkit/documentation/GLKit/glkquaternion-pc6",
        "doc://com.apple.glkit/documentation/GLKit/glkit-math-utilities"
      ],
      "title": "Math Utilties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Vectors",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3Make(_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3MakeWithArray(_:)"
      ],
      "title": "Creating Vectors"
    },
    {
      "anchor": "Retrieving-Information-About-a-Vector",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3Length(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3Distance(_:_:)"
      ],
      "title": "Retrieving Information About a Vector"
    },
    {
      "anchor": "Mathematical-Operations-Performed-on-Vectors",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3Negate(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3Normalize(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3AddScalar(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3SubtractScalar(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3MultiplyScalar(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3DivideScalar(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3Add(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3Subtract(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3Multiply(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3Divide(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3DotProduct(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3CrossProduct(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3Lerp(_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3Project(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3Maximum(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3Minimum(_:_:)"
      ],
      "title": "Mathematical Operations Performed on Vectors"
    },
    {
      "anchor": "Comparison-Operations",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3AllEqualToScalar(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3AllEqualToVector3(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3AllGreaterThanOrEqualToScalar(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3AllGreaterThanOrEqualToVector3(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3AllGreaterThanScalar(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3AllGreaterThanVector3(_:_:)"
      ],
      "title": "Comparison Operations"
    },
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Vectors",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3Make(_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3MakeWithArray(_:)"
              ],
              "title": "Creating Vectors"
            },
            {
              "anchor": "Retrieving-Information-About-a-Vector",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3Length(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3Distance(_:_:)"
              ],
              "title": "Retrieving Information About a Vector"
            },
            {
              "anchor": "Mathematical-Operations-Performed-on-Vectors",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3Negate(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3Normalize(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3AddScalar(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3SubtractScalar(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3MultiplyScalar(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3DivideScalar(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3Add(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3Subtract(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3Multiply(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3Divide(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3DotProduct(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3CrossProduct(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3Lerp(_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3Project(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3Maximum(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3Minimum(_:_:)"
              ],
              "title": "Mathematical Operations Performed on Vectors"
            },
            {
              "anchor": "Comparison-Operations",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3AllEqualToScalar(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3AllEqualToVector3(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3AllGreaterThanOrEqualToScalar(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3AllGreaterThanOrEqualToVector3(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3AllGreaterThanScalar(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3AllGreaterThanVector3(_:_:)"
              ],
              "title": "Comparison Operations"
            },
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Math-Utilties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStack",
                "doc://com.apple.glkit/documentation/GLKit/glkmatrix3-pcl",
                "doc://com.apple.glkit/documentation/GLKit/glkmatrix4-pce",
                "doc://com.apple.glkit/documentation/GLKit/glkvector2-pbj",
                "doc://com.apple.glkit/documentation/GLKit/glkvector4-pbk",
                "doc://com.apple.glkit/documentation/GLKit/glkquaternion-pc6",
                "doc://com.apple.glkit/documentation/GLKit/glkit-math-utilities"
              ],
              "title": "Math Utilties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Distance(_:_:)/title",
          "value": "GLKVector3Distance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Distance(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3Distance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3CrossProduct(_:_:)/title",
          "value": "GLKVector3CrossProduct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3CrossProduct(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3CrossProduct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3AllEqualToVector3(_:_:)/title",
          "value": "GLKVector3AllEqualToVector3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3AllEqualToVector3(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3AllEqualToVector3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Add(_:_:)/title",
          "value": "GLKVector3Add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Add(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3Add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3AllGreaterThanScalar(_:_:)/title",
          "value": "GLKVector3AllGreaterThanScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3AllGreaterThanScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3AllGreaterThanScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Subtract(_:_:)/title",
          "value": "GLKVector3Subtract"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Subtract(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3Subtract"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3AllGreaterThanOrEqualToScalar(_:_:)/title",
          "value": "GLKVector3AllGreaterThanOrEqualToScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3AllGreaterThanOrEqualToScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3AllGreaterThanOrEqualToScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3SubtractScalar(_:_:)/title",
          "value": "GLKVector3SubtractScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3SubtractScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3SubtractScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3AddScalar(_:_:)/title",
          "value": "GLKVector3AddScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3AddScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3AddScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3DivideScalar(_:_:)/title",
          "value": "GLKVector3DivideScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3DivideScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3DivideScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Make(_:_:_:)/title",
          "value": "GLKVector3Make"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Make(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3Make"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Project(_:_:)/title",
          "value": "GLKVector3Project"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Project(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3Project"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3AllGreaterThanVector3(_:_:)/title",
          "value": "GLKVector3AllGreaterThanVector3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3AllGreaterThanVector3(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3AllGreaterThanVector3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Maximum(_:_:)/title",
          "value": "GLKVector3Maximum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Maximum(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3Maximum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Normalize(_:)/title",
          "value": "GLKVector3Normalize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Normalize(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3Normalize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Minimum(_:_:)/title",
          "value": "GLKVector3Minimum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Minimum(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3Minimum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3/title",
          "value": "GLKVector3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3MakeWithArray(_:)/title",
          "value": "GLKVector3MakeWithArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3MakeWithArray(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3MakeWithArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStack/title",
          "value": "GLKMatrixStackRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrixStackRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrixStackRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Length(_:)/title",
          "value": "GLKVector3Length"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Length(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3Length"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3AllEqualToScalar(_:_:)/title",
          "value": "GLKVector3AllEqualToScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3AllEqualToScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3AllEqualToScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Multiply(_:_:)/title",
          "value": "GLKVector3Multiply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Multiply(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3Multiply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Negate(_:)/title",
          "value": "GLKVector3Negate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Negate(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3Negate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3DotProduct(_:_:)/title",
          "value": "GLKVector3DotProduct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3DotProduct(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3DotProduct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Lerp(_:_:_:)/title",
          "value": "GLKVector3Lerp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Lerp(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3Lerp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3MultiplyScalar(_:_:)/title",
          "value": "GLKVector3MultiplyScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3MultiplyScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3MultiplyScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Divide(_:_:)/title",
          "value": "GLKVector3Divide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Divide(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3Divide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3AllGreaterThanOrEqualToVector3(_:_:)/title",
          "value": "GLKVector3AllGreaterThanOrEqualToVector3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3AllGreaterThanOrEqualToVector3(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3AllGreaterThanOrEqualToVector3"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/glkit/glkvector3-pbt"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/glkit/glkvector3-pbt"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
