{
  "abstract": [
    {
      "text": "Returns the difference between two vectors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.glkit/documentation/GLKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.glkit/documentation/GLKit/GLKVector4Subtract(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@GLKVector4Subtract",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GLKVector4Subtract"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "text": "GLKVector4"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "text": "GLKVector4"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "text": "GLKVector4"
      }
    ],
    "modules": [
      {
        "name": "GLKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GLKVector4Subtract"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "GLKVector4Subtract(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GLKVector4Subtract"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "vectorLeft"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "GLKVector4"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "vectorRight"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "GLKVector4"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "kind": "typeIdentifier",
              "text": "GLKVector4"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The starting vector.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "vectorLeft"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The vector to subtract.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "vectorRight"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A new vector whose components each represent the difference between the components found in the same positions of the two source vectors.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.glkit/documentation/GLKit": {
      "abstract": [
        {
          "text": "Speed up OpenGL ES or OpenGL app development. Use math libraries, background texture loading, pre-created shader effects, and a standard view and view controller to implement your rendering loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GLKit",
      "type": "topic",
      "url": "/documentation/glkit"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4Add(_:_:)": {
      "abstract": [
        {
          "text": "Returns the sum of two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4Add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4Add(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4Add"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4Add(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4add(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4AddScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by adding a scalar value to each component of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4AddScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4AddScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4AddScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4AddScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4addscalar(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4CrossProduct(_:_:)": {
      "abstract": [
        {
          "text": "Returns the cross product of two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4CrossProduct"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4CrossProduct(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4CrossProduct"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4CrossProduct(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4crossproduct(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4Divide(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by dividing one vector by another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4Divide"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4Divide(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4Divide"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4Divide(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4divide(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4DivideScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by dividing each component of a vector by a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4DivideScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4DivideScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4DivideScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4DivideScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4dividescalar(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4DotProduct(_:_:)": {
      "abstract": [
        {
          "text": "Returns the dot product of two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4DotProduct"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4DotProduct(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4DotProduct"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4DotProduct(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4dotproduct(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4Lerp(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by linearly interpreting between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4Lerp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4Lerp(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4Lerp"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4Lerp(_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4lerp(_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4Maximum(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector whose component value at each position is the largest component value at the same position in the source vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4Maximum"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4Maximum(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4Maximum"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4Maximum(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4maximum(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4Minimum(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector whose component value at each position is the smallest component value at the same position in the source vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4Minimum"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4Minimum(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4Minimum"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4Minimum(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4minimum(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4Multiply(_:_:)": {
      "abstract": [
        {
          "text": "Returns the product of two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4Multiply"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4Multiply(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4Multiply"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4Multiply(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4multiply(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4MultiplyScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by multiplying each component of a vector by a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4MultiplyScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4MultiplyScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4MultiplyScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4MultiplyScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4multiplyscalar(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4Negate(_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by negating the component values of another vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4Negate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4Negate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4Negate"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4Negate(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4negate(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4Normalize(_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by normalizing an input vector to a length of ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4Normalize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4Normalize(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4Normalize"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4Normalize(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4normalize(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4Project(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by projecting a vector onto another vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4Project"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4Project(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4Project"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4Project(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4project(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4Subtract(_:_:)": {
      "abstract": [
        {
          "text": "Returns the difference between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4Subtract"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4Subtract(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4Subtract"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4Subtract(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4subtract(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4SubtractScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by subtracting a scalar value from each component of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4SubtractScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4SubtractScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4SubtractScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4SubtractScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4subtractscalar(_:_:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Mathematical-Operations-Performed-on-Vectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4Negate(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4Normalize(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4AddScalar(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4SubtractScalar(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4MultiplyScalar(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4DivideScalar(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4Add(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4Multiply(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4Divide(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4DotProduct(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4CrossProduct(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4Lerp(_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4Project(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4Maximum(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4Minimum(_:_:)"
      ],
      "title": "Mathematical Operations Performed on Vectors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GLKVector4Subtract"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4Subtract"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.glkit/documentation/GLKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Mathematical-Operations-Performed-on-Vectors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4Negate(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4Normalize(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4AddScalar(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4SubtractScalar(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4MultiplyScalar(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4DivideScalar(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4Add(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4Multiply(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4Divide(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4DotProduct(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4CrossProduct(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4Lerp(_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4Project(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4Maximum(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4Minimum(_:_:)"
              ],
              "title": "Mathematical Operations Performed on Vectors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@U@_GLKVector4",
                    "text": "GLKVector4"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GLKVector4Subtract"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@U@_GLKVector4",
                    "text": "GLKVector4"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "vectorLeft"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@U@_GLKVector4",
                    "text": "GLKVector4"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "vectorRight"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The starting vector.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "vectorLeft"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The vector to subtract.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "vectorRight"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A new vector whose components each represent the difference between the components found in the same positions of the two source vectors.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4DotProduct(_:_:)/title",
          "value": "GLKVector4DotProduct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4DotProduct(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4DotProduct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Subtract(_:_:)/title",
          "value": "GLKVector4Subtract"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Subtract(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4Subtract"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Maximum(_:_:)/title",
          "value": "GLKVector4Maximum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Maximum(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4Maximum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4DivideScalar(_:_:)/title",
          "value": "GLKVector4DivideScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4DivideScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4DivideScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4SubtractScalar(_:_:)/title",
          "value": "GLKVector4SubtractScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4SubtractScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4SubtractScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Add(_:_:)/title",
          "value": "GLKVector4Add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Add(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4Add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Lerp(_:_:_:)/title",
          "value": "GLKVector4Lerp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Lerp(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4Lerp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4MultiplyScalar(_:_:)/title",
          "value": "GLKVector4MultiplyScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4MultiplyScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4MultiplyScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4AddScalar(_:_:)/title",
          "value": "GLKVector4AddScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4AddScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4AddScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Multiply(_:_:)/title",
          "value": "GLKVector4Multiply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Multiply(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4Multiply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Project(_:_:)/title",
          "value": "GLKVector4Project"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Project(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4Project"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Divide(_:_:)/title",
          "value": "GLKVector4Divide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Divide(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4Divide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Negate(_:)/title",
          "value": "GLKVector4Negate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Negate(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4Negate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4CrossProduct(_:_:)/title",
          "value": "GLKVector4CrossProduct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4CrossProduct(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4CrossProduct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Minimum(_:_:)/title",
          "value": "GLKVector4Minimum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Minimum(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4Minimum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Normalize(_:)/title",
          "value": "GLKVector4Normalize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Normalize(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4Normalize"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/glkit/glkvector4subtract(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/glkit/glkvector4subtract(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
