{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.glkit/documentation/GLKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.glkit/documentation/GLKit/glkvector4-pbk"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "GLKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "GLKVector4"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "GLKVector4",
              "type": "codeVoice"
            },
            {
              "text": " type defines a ",
              "type": "text"
            },
            {
              "code": "4",
              "type": "codeVoice"
            },
            {
              "text": "-component floating-point vector as well as many mathematical operations commonly used to manipulate vectors. Graphics programming uses vectors extensively to represent positions, normals, colors and other data structures.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The functions that manipulate ",
              "type": "text"
            },
            {
              "code": "GLKVector4",
              "type": "codeVoice"
            },
            {
              "text": " structures treat the inputs as immutable, instead returning a new vector that represent the results of the operation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.glkit/documentation/GLKit": {
      "abstract": [
        {
          "text": "Speed up OpenGL ES or OpenGL app development. Use math libraries, background texture loading, pre-created shader effects, and a standard view and view controller to implement your rendering loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GLKit",
      "type": "topic",
      "url": "/documentation/glkit"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStack": {
      "abstract": [
        {
          "text": "An opaque type that represents a stack of 4 x 4 matrices, providing support for hierarchical transform modeling and similar tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKMatrixStack"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKMatrixStack"
        }
      ],
      "role": "symbol",
      "title": "GLKMatrixStack",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrixstack"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4": {
      "abstract": [
        {
          "text": "A representation of a 4-component vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4Add(_:_:)": {
      "abstract": [
        {
          "text": "Returns the sum of two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4Add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4Add(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4Add"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4Add(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4add(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4AddScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by adding a scalar value to each component of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4AddScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4AddScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4AddScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4AddScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4addscalar(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4AllEqualToScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that states whether all the components of the source vector are equal to a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4AllEqualToScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4AllEqualToScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4AllEqualToScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4AllEqualToScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4allequaltoscalar(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4AllEqualToVector4(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether each component of the first vector is equal to the corresponding component of a second vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4AllEqualToVector4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4AllEqualToVector4(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4AllEqualToVector4"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4AllEqualToVector4(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4allequaltovector4(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4AllGreaterThanOrEqualToScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that states whether all the components of the source vector are greater than or equal to a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4AllGreaterThanOrEqualToScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4AllGreaterThanOrEqualToScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4AllGreaterThanOrEqualToScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4AllGreaterThanOrEqualToScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4allgreaterthanorequaltoscalar(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4AllGreaterThanOrEqualToVector4(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether each component of the first vector is greater than or equal to the corresponding component of a second vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4AllGreaterThanOrEqualToVector4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4AllGreaterThanOrEqualToVector4(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4AllGreaterThanOrEqualToVector4"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4AllGreaterThanOrEqualToVector4(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4allgreaterthanorequaltovector4(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4AllGreaterThanScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that states whether all the components of the source vector are greater than a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4AllGreaterThanScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4AllGreaterThanScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4AllGreaterThanScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4AllGreaterThanScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4allgreaterthanscalar(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4AllGreaterThanVector4(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether each component of the first vector is greater than the corresponding component of a second vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4AllGreaterThanVector4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4AllGreaterThanVector4(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4AllGreaterThanVector4"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4AllGreaterThanVector4(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4allgreaterthanvector4(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4CrossProduct(_:_:)": {
      "abstract": [
        {
          "text": "Returns the cross product of two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4CrossProduct"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4CrossProduct(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4CrossProduct"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4CrossProduct(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4crossproduct(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4Distance(_:_:)": {
      "abstract": [
        {
          "text": "Returns the distance between two points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4Distance"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4Distance(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4Distance"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4Distance(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4distance(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4Divide(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by dividing one vector by another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4Divide"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4Divide(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4Divide"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4Divide(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4divide(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4DivideScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by dividing each component of a vector by a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4DivideScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4DivideScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4DivideScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4DivideScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4dividescalar(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4DotProduct(_:_:)": {
      "abstract": [
        {
          "text": "Returns the dot product of two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4DotProduct"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4DotProduct(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4DotProduct"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4DotProduct(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4dotproduct(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4Length(_:)": {
      "abstract": [
        {
          "text": "Returns the length of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4Length"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4Length(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4Length"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4Length(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4length(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4Lerp(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by linearly interpreting between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4Lerp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4Lerp(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4Lerp"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4Lerp(_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4lerp(_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4Make(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new four-component vector created from individual component values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4Make"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4Make(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4Make"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4Make(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4make(_:_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4MakeWithArray(_:)": {
      "abstract": [
        {
          "text": "Returns a new four-component vector created from an array of components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4MakeWithArray"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4MakeWithArray(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4MakeWithArray"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4MakeWithArray(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4makewitharray(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4MakeWithVector3(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new four-component vector created by combining a three-component vector with a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4MakeWithVector3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4MakeWithVector3(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4MakeWithVector3"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4MakeWithVector3(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4makewithvector3(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4Maximum(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector whose component value at each position is the largest component value at the same position in the source vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4Maximum"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4Maximum(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4Maximum"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4Maximum(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4maximum(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4Minimum(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector whose component value at each position is the smallest component value at the same position in the source vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4Minimum"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4Minimum(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4Minimum"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4Minimum(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4minimum(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4Multiply(_:_:)": {
      "abstract": [
        {
          "text": "Returns the product of two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4Multiply"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4Multiply(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4Multiply"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4Multiply(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4multiply(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4MultiplyScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by multiplying each component of a vector by a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4MultiplyScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4MultiplyScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4MultiplyScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4MultiplyScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4multiplyscalar(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4Negate(_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by negating the component values of another vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4Negate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4Negate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4Negate"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4Negate(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4negate(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4Normalize(_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by normalizing an input vector to a length of ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4Normalize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4Normalize(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4Normalize"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4Normalize(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4normalize(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4Project(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by projecting a vector onto another vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4Project"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4Project(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4Project"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4Project(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4project(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4Subtract(_:_:)": {
      "abstract": [
        {
          "text": "Returns the difference between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4Subtract"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4Subtract(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4Subtract"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4Subtract(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4subtract(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector4SubtractScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by subtracting a scalar value from each component of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector4SubtractScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector4SubtractScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector4SubtractScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector4SubtractScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector4subtractscalar(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkit-math-utilities": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkit-math-utilities",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKit Math Utilities",
      "type": "topic",
      "url": "/documentation/glkit/glkit-math-utilities"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkmatrix3-pcl": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkmatrix3-pcl",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKMatrix3",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix3-pcl"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkmatrix4-pce": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkmatrix4-pce",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKMatrix4",
      "type": "topic",
      "url": "/documentation/glkit/glkmatrix4-pce"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkquaternion-pc6": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkquaternion-pc6",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKQuaternion",
      "type": "topic",
      "url": "/documentation/glkit/glkquaternion-pc6"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkvector2-pbj": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkvector2-pbj",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKVector2",
      "type": "topic",
      "url": "/documentation/glkit/glkvector2-pbj"
    },
    "doc://com.apple.glkit/documentation/GLKit/glkvector3-pbt": {
      "abstract": [],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/glkvector3-pbt",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GLKVector3",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3-pbt"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Math-Utilties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStack",
        "doc://com.apple.glkit/documentation/GLKit/glkmatrix3-pcl",
        "doc://com.apple.glkit/documentation/GLKit/glkmatrix4-pce",
        "doc://com.apple.glkit/documentation/GLKit/glkvector2-pbj",
        "doc://com.apple.glkit/documentation/GLKit/glkvector3-pbt",
        "doc://com.apple.glkit/documentation/GLKit/glkquaternion-pc6",
        "doc://com.apple.glkit/documentation/GLKit/glkit-math-utilities"
      ],
      "title": "Math Utilties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Vectors",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4Make(_:_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4MakeWithArray(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4MakeWithVector3(_:_:)"
      ],
      "title": "Creating Vectors"
    },
    {
      "anchor": "Retrieving-Information-About-a-Vector",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4Length(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4Distance(_:_:)"
      ],
      "title": "Retrieving Information About a Vector"
    },
    {
      "anchor": "Mathematical-Operations-Performed-on-Vectors",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4Negate(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4Normalize(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4AddScalar(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4SubtractScalar(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4MultiplyScalar(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4DivideScalar(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4Add(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4Subtract(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4Multiply(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4Divide(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4DotProduct(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4CrossProduct(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4Lerp(_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4Project(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4Maximum(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4Minimum(_:_:)"
      ],
      "title": "Mathematical Operations Performed on Vectors"
    },
    {
      "anchor": "Comparison-Operations",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4AllEqualToScalar(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4AllEqualToVector4(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4AllGreaterThanOrEqualToScalar(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4AllGreaterThanOrEqualToVector4(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4AllGreaterThanScalar(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4AllGreaterThanVector4(_:_:)"
      ],
      "title": "Comparison Operations"
    },
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKVector4"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Vectors",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4Make(_:_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4MakeWithArray(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4MakeWithVector3(_:_:)"
              ],
              "title": "Creating Vectors"
            },
            {
              "anchor": "Retrieving-Information-About-a-Vector",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4Length(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4Distance(_:_:)"
              ],
              "title": "Retrieving Information About a Vector"
            },
            {
              "anchor": "Mathematical-Operations-Performed-on-Vectors",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4Negate(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4Normalize(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4AddScalar(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4SubtractScalar(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4MultiplyScalar(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4DivideScalar(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4Add(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4Subtract(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4Multiply(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4Divide(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4DotProduct(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4CrossProduct(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4Lerp(_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4Project(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4Maximum(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4Minimum(_:_:)"
              ],
              "title": "Mathematical Operations Performed on Vectors"
            },
            {
              "anchor": "Comparison-Operations",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4AllEqualToScalar(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4AllEqualToVector4(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4AllGreaterThanOrEqualToScalar(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4AllGreaterThanOrEqualToVector4(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4AllGreaterThanScalar(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4AllGreaterThanVector4(_:_:)"
              ],
              "title": "Comparison Operations"
            },
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKVector4"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Math-Utilties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKMatrixStack",
                "doc://com.apple.glkit/documentation/GLKit/glkmatrix3-pcl",
                "doc://com.apple.glkit/documentation/GLKit/glkmatrix4-pce",
                "doc://com.apple.glkit/documentation/GLKit/glkvector2-pbj",
                "doc://com.apple.glkit/documentation/GLKit/glkvector3-pbt",
                "doc://com.apple.glkit/documentation/GLKit/glkquaternion-pc6",
                "doc://com.apple.glkit/documentation/GLKit/glkit-math-utilities"
              ],
              "title": "Math Utilties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Project(_:_:)/title",
          "value": "GLKVector4Project"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Project(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4Project"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4AddScalar(_:_:)/title",
          "value": "GLKVector4AddScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4AddScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4AddScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4SubtractScalar(_:_:)/title",
          "value": "GLKVector4SubtractScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4SubtractScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4SubtractScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4AllEqualToVector4(_:_:)/title",
          "value": "GLKVector4AllEqualToVector4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4AllEqualToVector4(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4AllEqualToVector4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Distance(_:_:)/title",
          "value": "GLKVector4Distance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Distance(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4Distance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Add(_:_:)/title",
          "value": "GLKVector4Add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Add(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4Add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Make(_:_:_:_:)/title",
          "value": "GLKVector4Make"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Make(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4Make"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4DivideScalar(_:_:)/title",
          "value": "GLKVector4DivideScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4DivideScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4DivideScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Multiply(_:_:)/title",
          "value": "GLKVector4Multiply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Multiply(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4Multiply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4AllEqualToScalar(_:_:)/title",
          "value": "GLKVector4AllEqualToScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4AllEqualToScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4AllEqualToScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Minimum(_:_:)/title",
          "value": "GLKVector4Minimum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Minimum(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4Minimum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Negate(_:)/title",
          "value": "GLKVector4Negate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Negate(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4Negate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4/title",
          "value": "GLKVector4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4MakeWithVector3(_:_:)/title",
          "value": "GLKVector4MakeWithVector3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4MakeWithVector3(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4MakeWithVector3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4CrossProduct(_:_:)/title",
          "value": "GLKVector4CrossProduct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4CrossProduct(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4CrossProduct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4MakeWithArray(_:)/title",
          "value": "GLKVector4MakeWithArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4MakeWithArray(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4MakeWithArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4MultiplyScalar(_:_:)/title",
          "value": "GLKVector4MultiplyScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4MultiplyScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4MultiplyScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Normalize(_:)/title",
          "value": "GLKVector4Normalize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Normalize(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4Normalize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4AllGreaterThanOrEqualToScalar(_:_:)/title",
          "value": "GLKVector4AllGreaterThanOrEqualToScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4AllGreaterThanOrEqualToScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4AllGreaterThanOrEqualToScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4AllGreaterThanVector4(_:_:)/title",
          "value": "GLKVector4AllGreaterThanVector4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4AllGreaterThanVector4(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4AllGreaterThanVector4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Maximum(_:_:)/title",
          "value": "GLKVector4Maximum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Maximum(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4Maximum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4AllGreaterThanScalar(_:_:)/title",
          "value": "GLKVector4AllGreaterThanScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4AllGreaterThanScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4AllGreaterThanScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Subtract(_:_:)/title",
          "value": "GLKVector4Subtract"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Subtract(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4Subtract"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4AllGreaterThanOrEqualToVector4(_:_:)/title",
          "value": "GLKVector4AllGreaterThanOrEqualToVector4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4AllGreaterThanOrEqualToVector4(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4AllGreaterThanOrEqualToVector4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Lerp(_:_:_:)/title",
          "value": "GLKVector4Lerp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Lerp(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4Lerp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Length(_:)/title",
          "value": "GLKVector4Length"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Length(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4Length"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Divide(_:_:)/title",
          "value": "GLKVector4Divide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4Divide(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4Divide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4DotProduct(_:_:)/title",
          "value": "GLKVector4DotProduct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector4DotProduct(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector4DotProduct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStack/title",
          "value": "GLKMatrixStackRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrixStackRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKMatrixStack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKMatrixStackRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/glkit/glkvector4-pbk"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/glkit/glkvector4-pbk"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
