{
  "abstract": [
    {
      "text": "Returns a new vector created by dividing each component of a vector by a scalar value.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.glkit/documentation/GLKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.glkit/documentation/GLKit/GLKVector3DivideScalar(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@GLKVector3DivideScalar",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GLKVector3DivideScalar"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "text": "GLKVector3"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sf",
        "text": "Float"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "text": "GLKVector3"
      }
    ],
    "modules": [
      {
        "name": "GLKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GLKVector3DivideScalar"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "GLKVector3DivideScalar(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GLKVector3DivideScalar"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "vector"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "GLKVector3"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "value"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sf",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sf",
              "text": "Float"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "kind": "typeIdentifier",
              "text": "GLKVector3"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A vector.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "vector"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A scalar value.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "value"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A new vector.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.glkit/documentation/GLKit": {
      "abstract": [
        {
          "text": "Speed up OpenGL ES or OpenGL app development. Use math libraries, background texture loading, pre-created shader effects, and a standard view and view controller to implement your rendering loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GLKit",
      "type": "topic",
      "url": "/documentation/glkit"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3Add(_:_:)": {
      "abstract": [
        {
          "text": "Returns the sum of two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3Add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3Add(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3Add"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3Add(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3add(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3AddScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by adding a scalar value to each component of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3AddScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3AddScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3AddScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3AddScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3addscalar(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3CrossProduct(_:_:)": {
      "abstract": [
        {
          "text": "Returns the cross product of two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3CrossProduct"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3CrossProduct(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3CrossProduct"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3CrossProduct(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3crossproduct(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3Divide(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by dividing one vector by another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3Divide"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3Divide(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3Divide"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3Divide(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3divide(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3DivideScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by dividing each component of a vector by a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3DivideScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3DivideScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3DivideScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3DivideScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3dividescalar(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3DotProduct(_:_:)": {
      "abstract": [
        {
          "text": "Returns the dot product of two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3DotProduct"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3DotProduct(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3DotProduct"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3DotProduct(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3dotproduct(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3Lerp(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by linearly interpreting between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3Lerp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3Lerp(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3Lerp"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3Lerp(_:_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3lerp(_:_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3Maximum(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector whose component value at each position is the largest component value at the same position in the source vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3Maximum"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3Maximum(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3Maximum"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3Maximum(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3maximum(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3Minimum(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector whose component value at each position is the smallest component value at the same position in the source vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3Minimum"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3Minimum(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3Minimum"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3Minimum(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3minimum(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3Multiply(_:_:)": {
      "abstract": [
        {
          "text": "Returns the product of two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3Multiply"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3Multiply(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3Multiply"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3Multiply(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3multiply(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3MultiplyScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by multiplying each component of a vector by a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3MultiplyScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3MultiplyScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3MultiplyScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3MultiplyScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3multiplyscalar(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3Negate(_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by negating the component values of another vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3Negate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3Negate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3Negate"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3Negate(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3negate(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3Normalize(_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by normalizing the input vector to a length of ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3Normalize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3Normalize(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3Normalize"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3Normalize(_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3normalize(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3Project(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by projecting a vector onto another vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3Project"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3Project(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3Project"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3Project(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3project(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3Subtract(_:_:)": {
      "abstract": [
        {
          "text": "Returns the difference between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3Subtract"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3Subtract(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3Subtract"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3Subtract(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3subtract(_:_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKVector3SubtractScalar(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector created by subtracting a scalar value from each component of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKVector3SubtractScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKVector3SubtractScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKVector3SubtractScalar"
        }
      ],
      "role": "symbol",
      "title": "GLKVector3SubtractScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/glkit/glkvector3subtractscalar(_:_:)"
    },
    "doc://com.externally.resolved.symbol/s:Sf": {
      "abstract": [
        {
          "text": "A single-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sf",
      "kind": "symbol",
      "role": "symbol",
      "title": "Float",
      "type": "topic",
      "url": "/documentation/Swift/Float"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Mathematical-Operations-Performed-on-Vectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3Negate(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3Normalize(_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3AddScalar(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3SubtractScalar(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3MultiplyScalar(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3Add(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3Subtract(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3Multiply(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3Divide(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3DotProduct(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3CrossProduct(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3Lerp(_:_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3Project(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3Maximum(_:_:)",
        "doc://com.apple.glkit/documentation/GLKit/GLKVector3Minimum(_:_:)"
      ],
      "title": "Mathematical Operations Performed on Vectors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GLKVector3DivideScalar"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3DivideScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.glkit/documentation/GLKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Mathematical-Operations-Performed-on-Vectors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3Negate(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3Normalize(_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3AddScalar(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3SubtractScalar(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3MultiplyScalar(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3Add(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3Subtract(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3Multiply(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3Divide(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3DotProduct(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3CrossProduct(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3Lerp(_:_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3Project(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3Maximum(_:_:)",
                "doc://com.apple.glkit/documentation/GLKit/GLKVector3Minimum(_:_:)"
              ],
              "title": "Mathematical Operations Performed on Vectors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@U@_GLKVector3",
                    "text": "GLKVector3"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GLKVector3DivideScalar"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@U@_GLKVector3",
                    "text": "GLKVector3"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "vector"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:f",
                    "text": "float"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "value"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A vector.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "vector"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A scalar value.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "value"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A new vector.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Project(_:_:)/title",
          "value": "GLKVector3Project"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Project(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3Project"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Maximum(_:_:)/title",
          "value": "GLKVector3Maximum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Maximum(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3Maximum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Add(_:_:)/title",
          "value": "GLKVector3Add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Add(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3Add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3MultiplyScalar(_:_:)/title",
          "value": "GLKVector3MultiplyScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3MultiplyScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3MultiplyScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3CrossProduct(_:_:)/title",
          "value": "GLKVector3CrossProduct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3CrossProduct(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3CrossProduct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3AddScalar(_:_:)/title",
          "value": "GLKVector3AddScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3AddScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3AddScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3DivideScalar(_:_:)/title",
          "value": "GLKVector3DivideScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3DivideScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3DivideScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Divide(_:_:)/title",
          "value": "GLKVector3Divide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Divide(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3Divide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3DotProduct(_:_:)/title",
          "value": "GLKVector3DotProduct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3DotProduct(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3DotProduct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3SubtractScalar(_:_:)/title",
          "value": "GLKVector3SubtractScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3SubtractScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3SubtractScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Lerp(_:_:_:)/title",
          "value": "GLKVector3Lerp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Lerp(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3Lerp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Multiply(_:_:)/title",
          "value": "GLKVector3Multiply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Multiply(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3Multiply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Negate(_:)/title",
          "value": "GLKVector3Negate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Negate(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3Negate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Normalize(_:)/title",
          "value": "GLKVector3Normalize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Normalize(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3Normalize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Subtract(_:_:)/title",
          "value": "GLKVector3Subtract"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Subtract(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3Subtract"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Minimum(_:_:)/title",
          "value": "GLKVector3Minimum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKVector3Minimum(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKVector3Minimum"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/glkit/glkvector3dividescalar(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/glkit/glkvector3dividescalar(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
