{
  "abstract": [
    {
      "text": "Returns a string that represents the contents of a matrix.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.glkit/documentation/GLKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKMatrix4(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@NSStringFromGLKMatrix4",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSStringFromGLKMatrix4"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "text": "GLKMatrix4"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "GLKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSStringFromGLKMatrix4"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "NSStringFromGLKMatrix4(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSStringFromGLKMatrix4"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "matrix"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "GLKMatrix4"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A ",
                  "type": "text"
                },
                {
                  "code": "4x4",
                  "type": "codeVoice"
                },
                {
                  "text": " matrix.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "matrix"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.glkit/documentation/GLKit": {
      "abstract": [
        {
          "text": "Speed up OpenGL ES or OpenGL app development. Use math libraries, background texture loading, pre-created shader effects, and a standard view and view controller to implement your rendering loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GLKit",
      "type": "topic",
      "url": "/documentation/glkit"
    },
    "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKMatrix2(_:)": {
      "abstract": [
        {
          "text": "Returns a string that represents the contents of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStringFromGLKMatrix2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKMatrix2(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStringFromGLKMatrix2"
        }
      ],
      "role": "symbol",
      "title": "NSStringFromGLKMatrix2(_:)",
      "type": "topic",
      "url": "/documentation/glkit/nsstringfromglkmatrix2(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKMatrix3(_:)": {
      "abstract": [
        {
          "text": "Returns a string that represents the contents of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStringFromGLKMatrix3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKMatrix3(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStringFromGLKMatrix3"
        }
      ],
      "role": "symbol",
      "title": "NSStringFromGLKMatrix3(_:)",
      "type": "topic",
      "url": "/documentation/glkit/nsstringfromglkmatrix3(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKMatrix4(_:)": {
      "abstract": [
        {
          "text": "Returns a string that represents the contents of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStringFromGLKMatrix4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKMatrix4(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStringFromGLKMatrix4"
        }
      ],
      "role": "symbol",
      "title": "NSStringFromGLKMatrix4(_:)",
      "type": "topic",
      "url": "/documentation/glkit/nsstringfromglkmatrix4(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKQuaternion(_:)": {
      "abstract": [
        {
          "text": "Returns a string that represents the contents of a quaternion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStringFromGLKQuaternion"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKQuaternion"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKQuaternion(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStringFromGLKQuaternion"
        }
      ],
      "role": "symbol",
      "title": "NSStringFromGLKQuaternion(_:)",
      "type": "topic",
      "url": "/documentation/glkit/nsstringfromglkquaternion(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKVector2(_:)": {
      "abstract": [
        {
          "text": "Returns a string that represents the contents of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStringFromGLKVector2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKVector2(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStringFromGLKVector2"
        }
      ],
      "role": "symbol",
      "title": "NSStringFromGLKVector2(_:)",
      "type": "topic",
      "url": "/documentation/glkit/nsstringfromglkvector2(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKVector3(_:)": {
      "abstract": [
        {
          "text": "Returns a string that represents the contents of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStringFromGLKVector3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKVector3(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStringFromGLKVector3"
        }
      ],
      "role": "symbol",
      "title": "NSStringFromGLKVector3(_:)",
      "type": "topic",
      "url": "/documentation/glkit/nsstringfromglkvector3(_:)"
    },
    "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKVector4(_:)": {
      "abstract": [
        {
          "text": "Returns a string that represents the contents of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStringFromGLKVector4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKVector4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKVector4(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStringFromGLKVector4"
        }
      ],
      "role": "symbol",
      "title": "NSStringFromGLKVector4(_:)",
      "type": "topic",
      "url": "/documentation/glkit/nsstringfromglkvector4(_:)"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Obtaining-String-Descriptions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKMatrix2(_:)",
        "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKMatrix3(_:)",
        "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKVector2(_:)",
        "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKVector3(_:)",
        "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKVector4(_:)",
        "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKQuaternion(_:)"
      ],
      "title": "Obtaining String Descriptions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSStringFromGLKMatrix4"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringFromGLKMatrix4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.glkit/documentation/GLKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Obtaining-String-Descriptions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKMatrix2(_:)",
                "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKMatrix3(_:)",
                "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKVector2(_:)",
                "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKVector3(_:)",
                "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKVector4(_:)",
                "doc://com.apple.glkit/documentation/GLKit/NSStringFromGLKQuaternion(_:)"
              ],
              "title": "Obtaining String Descriptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSStringFromGLKMatrix4"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@U@_GLKMatrix4",
                    "text": "GLKMatrix4"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "matrix"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A ",
                        "type": "text"
                      },
                      {
                        "code": "4x4",
                        "type": "codeVoice"
                      },
                      {
                        "text": " matrix.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "matrix"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1NSStringFromGLKMatrix3(_:)/title",
          "value": "NSStringFromGLKMatrix3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1NSStringFromGLKMatrix3(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringFromGLKMatrix3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1NSStringFromGLKMatrix4(_:)/title",
          "value": "NSStringFromGLKMatrix4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1NSStringFromGLKMatrix4(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringFromGLKMatrix4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1NSStringFromGLKVector2(_:)/title",
          "value": "NSStringFromGLKVector2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1NSStringFromGLKVector2(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringFromGLKVector2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1NSStringFromGLKVector4(_:)/title",
          "value": "NSStringFromGLKVector4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1NSStringFromGLKVector4(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringFromGLKVector4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1NSStringFromGLKMatrix2(_:)/title",
          "value": "NSStringFromGLKMatrix2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1NSStringFromGLKMatrix2(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringFromGLKMatrix2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1NSStringFromGLKVector3(_:)/title",
          "value": "NSStringFromGLKVector3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1NSStringFromGLKVector3(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringFromGLKVector3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1NSStringFromGLKQuaternion(_:)/title",
          "value": "NSStringFromGLKQuaternion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1NSStringFromGLKQuaternion(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringFromGLKQuaternion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/glkit/nsstringfromglkmatrix4(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/glkit/nsstringfromglkmatrix4(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
