{
  "abstract": [
    {
      "text": "Strings used when handling error messages returned from a texture loading method.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.glkit/documentation/GLKit",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoader"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.glkit/documentation/GLKit/texture-error-handling"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "GLKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Texture Error Handling"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.glkit/documentation/GLKit": {
      "abstract": [
        {
          "text": "Speed up OpenGL ES or OpenGL app development. Use math libraries, background texture loading, pre-created shader effects, and a standard view and view controller to implement your rendering loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GLKit",
      "type": "topic",
      "url": "/documentation/glkit"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoader": {
      "abstract": [
        {
          "text": "A utility class that simplifies loading OpenGL or OpenGL ES texture datas from a variety of image file formats.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureLoader"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoader"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoader",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloader"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderCallback": {
      "abstract": [
        {
          "text": "Signature for the block executed after an asynchronous texture loading operation completes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderCallback"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderCallback"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderCallback",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadercallback"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Values to be returned when a texture loader encounters an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderError.Code",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadererror-swift.struct/code"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderErrorDomain": {
      "abstract": [
        {
          "text": "The error domain used by GLKit when returning texture loading errors.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderErrorDomain",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadererrordomain"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderErrorKey": {
      "abstract": [
        {
          "text": "A key used to retrieve an error string from an error object userinfo dictionary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderErrorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderErrorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderErrorKey"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderErrorKey",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadererrorkey"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderGLErrorKey": {
      "abstract": [
        {
          "text": "A key used to retrieve additional information from an error object’s userinfo dictionary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderGLErrorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderGLErrorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderGLErrorKey"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderGLErrorKey",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloaderglerrorkey"
    },
    "doc://com.apple.glkit/documentation/GLKit/texture-loading-options": {
      "abstract": [
        {
          "text": "Keys to specify in a ",
          "type": "text"
        },
        {
          "code": "textureOperations",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/texture-loading-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Texture Loading Options",
      "type": "topic",
      "url": "/documentation/glkit/texture-loading-options"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderCallback",
        "doc://com.apple.glkit/documentation/GLKit/texture-loading-options",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderErrorDomain",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderErrorKey",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderGLErrorKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderErrorDomain",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderErrorKey",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderGLErrorKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderCallback",
                "doc://com.apple.glkit/documentation/GLKit/texture-loading-options",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderGLErrorKey/title",
          "value": "GLKTextureLoaderGLErrorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderGLErrorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderGLErrorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderErrorDomain/title",
          "value": "GLKTextureLoaderErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code/title",
          "value": "GLKTextureLoaderError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderErrorKey/title",
          "value": "GLKTextureLoaderErrorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderErrorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderErrorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoader/title",
          "value": "GLKTextureLoader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoader/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderCallback/title",
          "value": "GLKTextureLoaderCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderCallback"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/glkit/texture-error-handling"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/glkit/texture-error-handling"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
