{
  "abstract": [
    {
      "text": "Parameters for the Highpass unit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389948-auhipass_parameters"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "AUHipass Parameters"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389745-aunbandeq-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389745-aunbandeq-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNBandEQ Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389745-aunbandeq-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389965-aunbandeq_filter_types": {
      "abstract": [
        {
          "text": "Values for the filter type parameter of the Multitype EQ (NBandEQ) unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389965-aunbandeq_filter_types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNBandEQ Filter Types",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389965-aunbandeq_filter_types"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389967-auhighshelffilter_parameters": {
      "abstract": [
        {
          "text": "Parameters for the High Shelf Filter unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389967-auhighshelffilter_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUHighShelfFilter Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389967-auhighshelffilter_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389995-aulowshelf_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Low Shelf Filter unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389995-aulowshelf_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AULowShelf Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389995-aulowshelf_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389999-aulowpass_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Lowpass unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389999-aulowpass_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AULowpass Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389999-aulowpass_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390144-bandpass_unit_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Bandpass unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390144-bandpass_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Bandpass Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390144-bandpass_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534022-aunbandeq-property-ids": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534022-aunbandeq-property-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNBandEQ Property IDs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534022-aunbandeq-property-ids"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584153-audio-unit-filter-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584153-audio-unit-filter-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Filter Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584153-audio-unit-filter-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties": {
      "abstract": [
        {
          "text": "Obtain information about the built-in mixers, equalizers, filters, effects, and other Audio Unit app extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kHipassParam_CutoffFrequency": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kHipassParam_CutoffFrequency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kHipassParam_CutoffFrequency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kHipassParam_CutoffFrequency"
        }
      ],
      "role": "symbol",
      "title": "kHipassParam_CutoffFrequency",
      "type": "topic",
      "url": "/documentation/audiotoolbox/khipassparam_cutofffrequency"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kHipassParam_Resonance": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kHipassParam_Resonance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kHipassParam_Resonance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kHipassParam_Resonance"
        }
      ],
      "role": "symbol",
      "title": "kHipassParam_Resonance",
      "type": "topic",
      "url": "/documentation/audiotoolbox/khipassparam_resonance"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Filters",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584153-audio-unit-filter-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390144-bandpass_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389999-aulowpass_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389995-aulowshelf_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389967-auhighshelffilter_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389965-aunbandeq_filter_types",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534022-aunbandeq-property-ids",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389745-aunbandeq-parameters"
      ],
      "title": "Filters"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kHipassParam_CutoffFrequency",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kHipassParam_Resonance"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kHipassParam_CutoffFrequency",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kHipassParam_Resonance"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Filters",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584153-audio-unit-filter-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390144-bandpass_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389999-aulowpass_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389995-aulowshelf_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389967-auhighshelffilter_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389965-aunbandeq_filter_types",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534022-aunbandeq-property-ids",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389745-aunbandeq-parameters"
              ],
              "title": "Filters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kHipassParam_Resonance/title",
          "value": "kHipassParam_Resonance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kHipassParam_Resonance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kHipassParam_Resonance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kHipassParam_CutoffFrequency/title",
          "value": "kHipassParam_CutoffFrequency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kHipassParam_CutoffFrequency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kHipassParam_CutoffFrequency"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1389948-auhipass_parameters"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1389948-auhipass_parameters"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
