{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389745-aunbandeq-parameters"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "AUNBandEQ Parameters"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389948-auhipass_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Highpass unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389948-auhipass_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUHipass Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389948-auhipass_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389965-aunbandeq_filter_types": {
      "abstract": [
        {
          "text": "Values for the filter type parameter of the Multitype EQ (NBandEQ) unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389965-aunbandeq_filter_types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNBandEQ Filter Types",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389965-aunbandeq_filter_types"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389967-auhighshelffilter_parameters": {
      "abstract": [
        {
          "text": "Parameters for the High Shelf Filter unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389967-auhighshelffilter_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUHighShelfFilter Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389967-auhighshelffilter_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389995-aulowshelf_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Low Shelf Filter unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389995-aulowshelf_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AULowShelf Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389995-aulowshelf_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389999-aulowpass_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Lowpass unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389999-aulowpass_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AULowpass Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389999-aulowpass_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390144-bandpass_unit_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Bandpass unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390144-bandpass_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Bandpass Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390144-bandpass_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534022-aunbandeq-property-ids": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534022-aunbandeq-property-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNBandEQ Property IDs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534022-aunbandeq-property-ids"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584153-audio-unit-filter-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584153-audio-unit-filter-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Filter Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584153-audio-unit-filter-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties": {
      "abstract": [
        {
          "text": "Obtain information about the built-in mixers, equalizers, filters, effects, and other Audio Unit app extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQParam_Bandwidth": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNBandEQParam_Bandwidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQParam_Bandwidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNBandEQParam_Bandwidth"
        }
      ],
      "role": "symbol",
      "title": "kAUNBandEQParam_Bandwidth",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunbandeqparam_bandwidth"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQParam_BypassBand": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNBandEQParam_BypassBand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQParam_BypassBand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNBandEQParam_BypassBand"
        }
      ],
      "role": "symbol",
      "title": "kAUNBandEQParam_BypassBand",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunbandeqparam_bypassband"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQParam_FilterType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNBandEQParam_FilterType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQParam_FilterType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNBandEQParam_FilterType"
        }
      ],
      "role": "symbol",
      "title": "kAUNBandEQParam_FilterType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunbandeqparam_filtertype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQParam_Frequency": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNBandEQParam_Frequency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQParam_Frequency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNBandEQParam_Frequency"
        }
      ],
      "role": "symbol",
      "title": "kAUNBandEQParam_Frequency",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunbandeqparam_frequency"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQParam_Gain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNBandEQParam_Gain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQParam_Gain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNBandEQParam_Gain"
        }
      ],
      "role": "symbol",
      "title": "kAUNBandEQParam_Gain",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunbandeqparam_gain"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQParam_GlobalGain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNBandEQParam_GlobalGain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQParam_GlobalGain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNBandEQParam_GlobalGain"
        }
      ],
      "role": "symbol",
      "title": "kAUNBandEQParam_GlobalGain",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunbandeqparam_globalgain"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Filters",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584153-audio-unit-filter-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390144-bandpass_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389948-auhipass_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389999-aulowpass_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389995-aulowshelf_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389967-auhighshelffilter_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389965-aunbandeq_filter_types",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534022-aunbandeq-property-ids"
      ],
      "title": "Filters"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQParam_Bandwidth",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQParam_BypassBand",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQParam_FilterType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQParam_Frequency",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQParam_Gain",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQParam_GlobalGain"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQParam_Bandwidth",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQParam_BypassBand",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQParam_FilterType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQParam_Frequency",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQParam_Gain",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQParam_GlobalGain"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Filters",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584153-audio-unit-filter-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390144-bandpass_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389948-auhipass_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389999-aulowpass_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389995-aulowshelf_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389967-auhighshelffilter_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389965-aunbandeq_filter_types",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534022-aunbandeq-property-ids"
              ],
              "title": "Filters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQParam_BypassBand/title",
          "value": "kAUNBandEQParam_BypassBand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQParam_BypassBand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNBandEQParam_BypassBand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQParam_GlobalGain/title",
          "value": "kAUNBandEQParam_GlobalGain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQParam_GlobalGain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNBandEQParam_GlobalGain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQParam_FilterType/title",
          "value": "kAUNBandEQParam_FilterType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQParam_FilterType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNBandEQParam_FilterType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQParam_Bandwidth/title",
          "value": "kAUNBandEQParam_Bandwidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQParam_Bandwidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNBandEQParam_Bandwidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQParam_Frequency/title",
          "value": "kAUNBandEQParam_Frequency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQParam_Frequency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNBandEQParam_Frequency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQParam_Gain/title",
          "value": "kAUNBandEQParam_Gain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQParam_Gain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNBandEQParam_Gain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1389745-aunbandeq-parameters"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1389745-aunbandeq-parameters"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
