{
  "abstract": [
    {
      "text": "Parameters for the Dynamics Processor unit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389787-dynamics_processor_unit_paramete"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Dynamics Processor Unit Parameters"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389597-peak_limiter_unit_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Peak Limiter unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389597-peak_limiter_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Peak Limiter Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389597-peak_limiter_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389932-audio-unit-graphic-eq-parameter": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389932-audio-unit-graphic-eq-parameter",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Graphic EQ Parameter ID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389932-audio-unit-graphic-eq-parameter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389950-parametric_eq_unit_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Parametric EQ unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389950-parametric_eq_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Parametric EQ Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389950-parametric_eq_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534092-frequency_response_constants": {
      "abstract": [
        {
          "text": "The maximum number of frequency response bin structures for the ",
          "type": "text"
        },
        {
          "code": "AudioUnitProperty_FrequencyResponse",
          "type": "codeVoice"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534092-frequency_response_constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Frequency Response Constants",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534092-frequency_response_constants"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatializationAlgorithm"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatializationAlgorithm"
        }
      ],
      "role": "symbol",
      "title": "AUSpatializationAlgorithm",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatializationalgorithm"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties": {
      "abstract": [
        {
          "text": "Obtain information about the built-in mixers, equalizers, filters, effects, and other Audio Unit app extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_AttackTime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_AttackTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_AttackTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_AttackTime"
        }
      ],
      "role": "symbol",
      "title": "kDynamicsProcessorParam_AttackTime",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdynamicsprocessorparam_attacktime"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_CompressionAmount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_CompressionAmount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_CompressionAmount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_CompressionAmount"
        }
      ],
      "role": "symbol",
      "title": "kDynamicsProcessorParam_CompressionAmount",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdynamicsprocessorparam_compressionamount"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_ExpansionRatio": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_ExpansionRatio"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_ExpansionRatio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_ExpansionRatio"
        }
      ],
      "role": "symbol",
      "title": "kDynamicsProcessorParam_ExpansionRatio",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdynamicsprocessorparam_expansionratio"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_ExpansionThreshold": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_ExpansionThreshold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_ExpansionThreshold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_ExpansionThreshold"
        }
      ],
      "role": "symbol",
      "title": "kDynamicsProcessorParam_ExpansionThreshold",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdynamicsprocessorparam_expansionthreshold"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_HeadRoom": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_HeadRoom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_HeadRoom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_HeadRoom"
        }
      ],
      "role": "symbol",
      "title": "kDynamicsProcessorParam_HeadRoom",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdynamicsprocessorparam_headroom"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_InputAmplitude": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_InputAmplitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_InputAmplitude",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_InputAmplitude"
        }
      ],
      "role": "symbol",
      "title": "kDynamicsProcessorParam_InputAmplitude",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdynamicsprocessorparam_inputamplitude"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_MasterGain": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_MasterGain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_MasterGain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_MasterGain"
        }
      ],
      "role": "symbol",
      "title": "kDynamicsProcessorParam_MasterGain",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdynamicsprocessorparam_mastergain"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_OutputAmplitude": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_OutputAmplitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_OutputAmplitude",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_OutputAmplitude"
        }
      ],
      "role": "symbol",
      "title": "kDynamicsProcessorParam_OutputAmplitude",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdynamicsprocessorparam_outputamplitude"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_OverallGain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_OverallGain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_OverallGain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_OverallGain"
        }
      ],
      "role": "symbol",
      "title": "kDynamicsProcessorParam_OverallGain",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdynamicsprocessorparam_overallgain"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_ReleaseTime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_ReleaseTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_ReleaseTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_ReleaseTime"
        }
      ],
      "role": "symbol",
      "title": "kDynamicsProcessorParam_ReleaseTime",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdynamicsprocessorparam_releasetime"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_Threshold": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_Threshold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_Threshold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_Threshold"
        }
      ],
      "role": "symbol",
      "title": "kDynamicsProcessorParam_Threshold",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdynamicsprocessorparam_threshold"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Equalizers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389950-parametric_eq_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389932-audio-unit-graphic-eq-parameter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389597-peak_limiter_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534092-frequency_response_constants",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm"
      ],
      "title": "Equalizers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_AttackTime",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_CompressionAmount",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_ExpansionRatio",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_ExpansionThreshold",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_HeadRoom",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_InputAmplitude",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_MasterGain",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_OutputAmplitude",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_ReleaseTime",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_Threshold",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_OverallGain"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_AttackTime",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_CompressionAmount",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_ExpansionRatio",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_ExpansionThreshold",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_HeadRoom",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_InputAmplitude",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_MasterGain",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_OutputAmplitude",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_ReleaseTime",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_Threshold",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_OverallGain"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Equalizers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389950-parametric_eq_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389932-audio-unit-graphic-eq-parameter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389597-peak_limiter_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534092-frequency_response_constants",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm"
              ],
              "title": "Equalizers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_AttackTime/title",
          "value": "kDynamicsProcessorParam_AttackTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_AttackTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDynamicsProcessorParam_AttackTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_OverallGain/title",
          "value": "kDynamicsProcessorParam_OverallGain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_OverallGain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDynamicsProcessorParam_OverallGain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_InputAmplitude/title",
          "value": "kDynamicsProcessorParam_InputAmplitude"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_InputAmplitude/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDynamicsProcessorParam_InputAmplitude"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm/title",
          "value": "AUSpatializationAlgorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatializationAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatializationAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_ExpansionRatio/title",
          "value": "kDynamicsProcessorParam_ExpansionRatio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_ExpansionRatio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDynamicsProcessorParam_ExpansionRatio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_CompressionAmount/title",
          "value": "kDynamicsProcessorParam_CompressionAmount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_CompressionAmount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDynamicsProcessorParam_CompressionAmount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_HeadRoom/title",
          "value": "kDynamicsProcessorParam_HeadRoom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_HeadRoom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDynamicsProcessorParam_HeadRoom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_Threshold/title",
          "value": "kDynamicsProcessorParam_Threshold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_Threshold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDynamicsProcessorParam_Threshold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_ExpansionThreshold/title",
          "value": "kDynamicsProcessorParam_ExpansionThreshold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_ExpansionThreshold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDynamicsProcessorParam_ExpansionThreshold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_ReleaseTime/title",
          "value": "kDynamicsProcessorParam_ReleaseTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_ReleaseTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDynamicsProcessorParam_ReleaseTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_OutputAmplitude/title",
          "value": "kDynamicsProcessorParam_OutputAmplitude"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_OutputAmplitude/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDynamicsProcessorParam_OutputAmplitude"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_MasterGain/title",
          "value": "kDynamicsProcessorParam_MasterGain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_MasterGain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDynamicsProcessorParam_MasterGain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1389787-dynamics_processor_unit_paramete"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1389787-dynamics_processor_unit_paramete"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
