{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389727-aurogerbeep-parameters"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "AURogerBeep Parameters"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389639-aurandom-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389639-aurandom-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AURandom Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389639-aurandom-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389769-ausampler-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389769-ausampler-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUSampler Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389769-ausampler-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389808-auroundtripaacparam-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389808-auroundtripaacparam-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AURoundTripAACParam Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389808-auroundtripaacparam-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533959-ausampler-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533959-ausampler-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUSampler Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1533959-ausampler-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534086-ausampler-property-ids": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534086-ausampler-property-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUSampler Property IDs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534086-ausampler-property-ids"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534190-aumidisynth-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534190-aumidisynth-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUMIDISynth Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534190-aumidisynth-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties": {
      "abstract": [
        {
          "text": "Obtain information about the built-in mixers, equalizers, filters, effects, and other Audio Unit app extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_InGateThreshold": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRogerBeepParam_InGateThreshold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_InGateThreshold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRogerBeepParam_InGateThreshold"
        }
      ],
      "role": "symbol",
      "title": "kRogerBeepParam_InGateThreshold",
      "type": "topic",
      "url": "/documentation/audiotoolbox/krogerbeepparam_ingatethreshold"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_InGateThresholdTime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRogerBeepParam_InGateThresholdTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_InGateThresholdTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRogerBeepParam_InGateThresholdTime"
        }
      ],
      "role": "symbol",
      "title": "kRogerBeepParam_InGateThresholdTime",
      "type": "topic",
      "url": "/documentation/audiotoolbox/krogerbeepparam_ingatethresholdtime"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_OutGateThreshold": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRogerBeepParam_OutGateThreshold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_OutGateThreshold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRogerBeepParam_OutGateThreshold"
        }
      ],
      "role": "symbol",
      "title": "kRogerBeepParam_OutGateThreshold",
      "type": "topic",
      "url": "/documentation/audiotoolbox/krogerbeepparam_outgatethreshold"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_OutGateThresholdTime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRogerBeepParam_OutGateThresholdTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_OutGateThresholdTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRogerBeepParam_OutGateThresholdTime"
        }
      ],
      "role": "symbol",
      "title": "kRogerBeepParam_OutGateThresholdTime",
      "type": "topic",
      "url": "/documentation/audiotoolbox/krogerbeepparam_outgatethresholdtime"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_RogerGain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRogerBeepParam_RogerGain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_RogerGain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRogerBeepParam_RogerGain"
        }
      ],
      "role": "symbol",
      "title": "kRogerBeepParam_RogerGain",
      "type": "topic",
      "url": "/documentation/audiotoolbox/krogerbeepparam_rogergain"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_RogerType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRogerBeepParam_RogerType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_RogerType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRogerBeepParam_RogerType"
        }
      ],
      "role": "symbol",
      "title": "kRogerBeepParam_RogerType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/krogerbeepparam_rogertype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_Sensitivity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRogerBeepParam_Sensitivity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_Sensitivity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRogerBeepParam_Sensitivity"
        }
      ],
      "role": "symbol",
      "title": "kRogerBeepParam_Sensitivity",
      "type": "topic",
      "url": "/documentation/audiotoolbox/krogerbeepparam_sensitivity"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Generators",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389639-aurandom-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389769-ausampler-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534086-ausampler-property-ids",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533959-ausampler-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534190-aumidisynth-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389808-auroundtripaacparam-parameters"
      ],
      "title": "Generators"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_InGateThreshold",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_InGateThresholdTime",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_OutGateThreshold",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_OutGateThresholdTime",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_RogerGain",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_RogerType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_Sensitivity"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_InGateThreshold",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_InGateThresholdTime",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_OutGateThreshold",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_OutGateThresholdTime",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_RogerGain",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_RogerType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_Sensitivity"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Generators",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389639-aurandom-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389769-ausampler-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534086-ausampler-property-ids",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533959-ausampler-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534190-aumidisynth-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389808-auroundtripaacparam-parameters"
              ],
              "title": "Generators"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRogerBeepParam_InGateThresholdTime/title",
          "value": "kRogerBeepParam_InGateThresholdTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRogerBeepParam_InGateThresholdTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRogerBeepParam_InGateThresholdTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRogerBeepParam_InGateThreshold/title",
          "value": "kRogerBeepParam_InGateThreshold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRogerBeepParam_InGateThreshold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRogerBeepParam_InGateThreshold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRogerBeepParam_OutGateThreshold/title",
          "value": "kRogerBeepParam_OutGateThreshold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRogerBeepParam_OutGateThreshold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRogerBeepParam_OutGateThreshold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRogerBeepParam_Sensitivity/title",
          "value": "kRogerBeepParam_Sensitivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRogerBeepParam_Sensitivity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRogerBeepParam_Sensitivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRogerBeepParam_RogerType/title",
          "value": "kRogerBeepParam_RogerType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRogerBeepParam_RogerType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRogerBeepParam_RogerType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRogerBeepParam_OutGateThresholdTime/title",
          "value": "kRogerBeepParam_OutGateThresholdTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRogerBeepParam_OutGateThresholdTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRogerBeepParam_OutGateThresholdTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRogerBeepParam_RogerGain/title",
          "value": "kRogerBeepParam_RogerGain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRogerBeepParam_RogerGain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRogerBeepParam_RogerGain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1389727-aurogerbeep-parameters"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1389727-aurogerbeep-parameters"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
