{
  "abstract": [
    {
      "text": "Parameters for instrument units.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389613-midi_audio_unit_parameters"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "MIDI Audio Unit Parameters"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi": {
      "abstract": [
        {
          "text": "Reserved for system use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Reserved Audio Unit Clump Identifier",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1533986-reserved_audio_unit_clump_identi"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534054-offline_audio_unit_properties": {
      "abstract": [
        {
          "text": "Properties for audio units that perform offline processing—that is, processing in a nonplayback, nonrealtime mode.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534054-offline_audio_unit_properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Offline Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534054-offline_audio_unit_properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes": {
      "abstract": [
        {
          "text": "Input/output audio unit subtypes for audio units provided by Apple.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Input/Output Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584139-input_output_audio_unit_subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele": {
      "abstract": [
        {
          "text": "General audio unit component selectors that correspond to functions in the audio unit API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele",
      "kind": "article",
      "role": "collectionGroup",
      "title": "General Audio Unit Function Selectors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584140-general_audio_unit_function_sele"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584142-audio_unit_types": {
      "abstract": [
        {
          "text": "The defined types of audio processing plug-ins known as audio units.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584142-audio_unit_types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Types",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584142-audio_unit_types"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi": {
      "abstract": [
        {
          "text": "The Apple audio unit manufacturer code.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Manufacturer Identifier",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584143-audio_unit_manufacturer_identifi"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes": {
      "abstract": [
        {
          "text": "Audio data format converter audio unit subtypes for audio units provided by Apple.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Converter Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584145-converter_audio_unit_subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584148-audio-unit-output-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584148-audio-unit-output-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Output Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584148-audio-unit-output-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Panner Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584151-audio-unit-panner-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Pitch Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584152-audio-unit-pitch-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Player Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584155-audio-unit-player-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "I/O Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1619485-i-o-audio-unit-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes": {
      "abstract": [
        {
          "text": "Audio units that serve as sound sources.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Generator Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1619493-generator_audio_unit_subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Inter-App Audio Unit Types",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1619501-inter-app-audio-unit-types"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitEventType"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitEventType"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitEventType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiouniteventtype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api": {
      "abstract": [
        {
          "text": "Configure an Audio Unit and prepare it to render audio.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit v2 (C) API",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-v2-c-api"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllNotesOff": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_AllNotesOff"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllNotesOff",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_AllNotesOff"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_AllNotesOff",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_allnotesoff"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllSoundOff": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_AllSoundOff"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllSoundOff",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_AllSoundOff"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_AllSoundOff",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_allsoundoff"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ChannelPressure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_ChannelPressure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ChannelPressure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_ChannelPressure"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_ChannelPressure",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_channelpressure"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_DataEntry"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_DataEntry"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_DataEntry",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_dataentry"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry_LSB": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_DataEntry_LSB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry_LSB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_DataEntry_LSB"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_DataEntry_LSB",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_dataentry_lsb"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Expression"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Expression"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_Expression",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_expression"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression_LSB": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Expression_LSB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression_LSB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Expression_LSB"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_Expression_LSB",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_expression_lsb"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Foot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Foot"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_Foot",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_foot"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot_LSB": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Foot_LSB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot_LSB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Foot_LSB"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_Foot_LSB",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_foot_lsb"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_KeyPressure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_KeyPressure"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_KeyPressure",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_keypressure"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_FirstKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_KeyPressure_FirstKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_FirstKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_KeyPressure_FirstKey"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_KeyPressure_FirstKey",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_keypressure_firstkey"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_LastKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_KeyPressure_LastKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_LastKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_KeyPressure_LastKey"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_KeyPressure_LastKey",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_keypressure_lastkey"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_ModWheel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_ModWheel"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_ModWheel",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_modwheel"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel_LSB": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_ModWheel_LSB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel_LSB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_ModWheel_LSB"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_ModWheel_LSB",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_modwheel_lsb"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Pan": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Pan"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Pan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Pan"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_Pan",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_pan"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Pan_LSB": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Pan_LSB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Pan_LSB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Pan_LSB"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_Pan_LSB",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_pan_lsb"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_PitchBend": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_PitchBend"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_PitchBend",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_PitchBend"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_PitchBend",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_pitchbend"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ResetAllControllers": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_ResetAllControllers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ResetAllControllers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_ResetAllControllers"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_ResetAllControllers",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_resetallcontrollers"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Sostenuto": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Sostenuto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Sostenuto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Sostenuto"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_Sostenuto",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_sostenuto"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Sustain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Sustain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Sustain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Sustain"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_Sustain",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_sustain"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Volume": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Volume"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Volume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Volume"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_Volume",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_volume"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Volume_LSB": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Volume_LSB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Volume_LSB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Volume_LSB"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_Volume_LSB",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_volume_lsb"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584142-audio_unit_types",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584148-audio-unit-output-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534054-offline_audio_unit_properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllNotesOff",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllSoundOff",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ChannelPressure",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry_LSB",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression_LSB",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot_LSB",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_FirstKey",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_LastKey",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel_LSB",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Pan",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Pan_LSB",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_PitchBend",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ResetAllControllers",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Sostenuto",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Sustain",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Volume",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Volume_LSB"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllNotesOff",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllSoundOff",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ChannelPressure",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry_LSB",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression_LSB",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot_LSB",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_FirstKey",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_LastKey",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel_LSB",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Pan",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Pan_LSB",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_PitchBend",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ResetAllControllers",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Sostenuto",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Sustain",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Volume",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Volume_LSB"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584142-audio_unit_types",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584148-audio-unit-output-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534054-offline_audio_unit_properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_KeyPressure/title",
          "value": "kAUGroupParameterID_KeyPressure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_KeyPressure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_KeyPressure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEventType/title",
          "value": "AudioUnitEventType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEventType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEventType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_AllSoundOff/title",
          "value": "kAUGroupParameterID_AllSoundOff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_AllSoundOff/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_AllSoundOff"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Sostenuto/title",
          "value": "kAUGroupParameterID_Sostenuto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Sostenuto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_Sostenuto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Expression/title",
          "value": "kAUGroupParameterID_Expression"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Expression/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_Expression"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Sustain/title",
          "value": "kAUGroupParameterID_Sustain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Sustain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_Sustain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Foot_LSB/title",
          "value": "kAUGroupParameterID_Foot_LSB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Foot_LSB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_Foot_LSB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Pan/title",
          "value": "kAUGroupParameterID_Pan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Pan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_Pan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Expression_LSB/title",
          "value": "kAUGroupParameterID_Expression_LSB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Expression_LSB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_Expression_LSB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_ModWheel_LSB/title",
          "value": "kAUGroupParameterID_ModWheel_LSB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_ModWheel_LSB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_ModWheel_LSB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_KeyPressure_FirstKey/title",
          "value": "kAUGroupParameterID_KeyPressure_FirstKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_KeyPressure_FirstKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_KeyPressure_FirstKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_PitchBend/title",
          "value": "kAUGroupParameterID_PitchBend"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_PitchBend/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_PitchBend"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_KeyPressure_LastKey/title",
          "value": "kAUGroupParameterID_KeyPressure_LastKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_KeyPressure_LastKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_KeyPressure_LastKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Volume/title",
          "value": "kAUGroupParameterID_Volume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Volume/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_Volume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_ResetAllControllers/title",
          "value": "kAUGroupParameterID_ResetAllControllers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_ResetAllControllers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_ResetAllControllers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_DataEntry/title",
          "value": "kAUGroupParameterID_DataEntry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_DataEntry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_DataEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_ChannelPressure/title",
          "value": "kAUGroupParameterID_ChannelPressure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_ChannelPressure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_ChannelPressure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_AllNotesOff/title",
          "value": "kAUGroupParameterID_AllNotesOff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_AllNotesOff/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_AllNotesOff"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Foot/title",
          "value": "kAUGroupParameterID_Foot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Foot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_Foot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_DataEntry_LSB/title",
          "value": "kAUGroupParameterID_DataEntry_LSB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_DataEntry_LSB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_DataEntry_LSB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Volume_LSB/title",
          "value": "kAUGroupParameterID_Volume_LSB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Volume_LSB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_Volume_LSB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_ModWheel/title",
          "value": "kAUGroupParameterID_ModWheel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_ModWheel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_ModWheel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Pan_LSB/title",
          "value": "kAUGroupParameterID_Pan_LSB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Pan_LSB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_Pan_LSB"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1389613-midi_audio_unit_parameters"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1389613-midi_audio_unit_parameters"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
