{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389781-aumultibandcompressor-parameters"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "AUMultibandCompressor Parameters"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389643-aunewtimepitch-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389643-aunewtimepitch-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNewTimePitch Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389643-aunewtimepitch-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389801-aumatrixreverb-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389801-aumatrixreverb-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUMatrixReverb Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389801-aumatrixreverb-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389946-autimepitch_autimepitch_offline": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389946-autimepitch_autimepitch_offline",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUTimePitch, AUTimePitch (offline), and AUPitch Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389946-autimepitch_autimepitch_offline"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390010-audelay-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390010-audelay-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUDelay Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390010-audelay-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390014-varispeed_unit_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Varispeed unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390014-varispeed_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Varispeed Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390014-varispeed_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390086-audistortion-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390086-audistortion-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUDistortion Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390086-audistortion-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390119-reverb_parameters": {
      "abstract": [
        {
          "text": "Additional reverb parameters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390119-reverb_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Reverb Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390119-reverb_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534061-audeferredrenderer-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534061-audeferredrenderer-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUDeferredRenderer Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534061-audeferredrenderer-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584154-effect_audio_unit_subtypes": {
      "abstract": [
        {
          "text": "Effect (digital signal processing) audio unit subtypes for audio units provided by Apple.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584154-effect_audio_unit_subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Effect Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584154-effect_audio_unit_subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1615024-reverb_unit_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Reverb unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1615024-reverb_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Reverb Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1615024-reverb_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3547050-ausampledelay-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3547050-ausampledelay-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUSampleDelay Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/3547050-ausampledelay-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUReverbRoomType"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUReverbRoomType"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties": {
      "abstract": [
        {
          "text": "Obtain information about the built-in mixers, equalizers, filters, effects, and other Audio Unit app extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_AttackTime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_AttackTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_AttackTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_AttackTime"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_AttackTime",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_attacktime"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_CompressionAmount1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_CompressionAmount1"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_CompressionAmount1",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_compressionamount1"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_CompressionAmount2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_CompressionAmount2"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_CompressionAmount2",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_compressionamount2"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_CompressionAmount3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_CompressionAmount3"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_CompressionAmount3",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_compressionamount3"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_CompressionAmount4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_CompressionAmount4"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_CompressionAmount4",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_compressionamount4"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Crossover1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Crossover1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Crossover1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Crossover1"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_Crossover1",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_crossover1"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Crossover2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Crossover2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Crossover2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Crossover2"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_Crossover2",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_crossover2"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Crossover3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Crossover3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Crossover3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Crossover3"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_Crossover3",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_crossover3"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_EQ1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_EQ1"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_EQ1",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_eq1"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_EQ2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_EQ2"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_EQ2",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_eq2"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_EQ3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_EQ3"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_EQ3",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_eq3"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_EQ4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_EQ4"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_EQ4",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_eq4"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Headroom1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Headroom1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Headroom1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Headroom1"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_Headroom1",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_headroom1"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Headroom2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Headroom2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Headroom2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Headroom2"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_Headroom2",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_headroom2"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Headroom3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Headroom3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Headroom3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Headroom3"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_Headroom3",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_headroom3"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Headroom4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Headroom4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Headroom4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Headroom4"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_Headroom4",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_headroom4"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_InputAmplitude1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_InputAmplitude1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_InputAmplitude1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_InputAmplitude1"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_InputAmplitude1",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_inputamplitude1"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_InputAmplitude2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_InputAmplitude2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_InputAmplitude2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_InputAmplitude2"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_InputAmplitude2",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_inputamplitude2"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_InputAmplitude3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_InputAmplitude3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_InputAmplitude3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_InputAmplitude3"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_InputAmplitude3",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_inputamplitude3"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_InputAmplitude4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_InputAmplitude4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_InputAmplitude4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_InputAmplitude4"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_InputAmplitude4",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_inputamplitude4"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_OutputAmplitude1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_OutputAmplitude1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_OutputAmplitude1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_OutputAmplitude1"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_OutputAmplitude1",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_outputamplitude1"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_OutputAmplitude2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_OutputAmplitude2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_OutputAmplitude2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_OutputAmplitude2"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_OutputAmplitude2",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_outputamplitude2"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_OutputAmplitude3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_OutputAmplitude3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_OutputAmplitude3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_OutputAmplitude3"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_OutputAmplitude3",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_outputamplitude3"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_OutputAmplitude4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_OutputAmplitude4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_OutputAmplitude4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_OutputAmplitude4"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_OutputAmplitude4",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_outputamplitude4"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Postgain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Postgain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Postgain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Postgain"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_Postgain",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_postgain"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Pregain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Pregain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Pregain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Pregain"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_Pregain",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_pregain"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_ReleaseTime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_ReleaseTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_ReleaseTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_ReleaseTime"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_ReleaseTime",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_releasetime"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Threshold1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Threshold1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Threshold1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Threshold1"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_Threshold1",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_threshold1"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Threshold2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Threshold2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Threshold2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Threshold2"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_Threshold2",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_threshold2"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Threshold3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Threshold3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Threshold3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Threshold3"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_Threshold3",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_threshold3"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Threshold4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Threshold4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Threshold4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Threshold4"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_Threshold4",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_threshold4"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Effects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584154-effect_audio_unit_subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389801-aumatrixreverb-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390086-audistortion-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390119-reverb_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1615024-reverb_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390014-varispeed_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390010-audelay-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534061-audeferredrenderer-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3547050-ausampledelay-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389643-aunewtimepitch-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389946-autimepitch_autimepitch_offline"
      ],
      "title": "Effects"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_AttackTime",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount1",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount2",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount3",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount4",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Crossover1",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Crossover2",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Crossover3",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ1",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ2",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ3",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ4",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Headroom1",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Headroom2",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Headroom3",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Headroom4",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_InputAmplitude1",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_InputAmplitude2",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_InputAmplitude3",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_InputAmplitude4",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_OutputAmplitude1",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_OutputAmplitude2",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_OutputAmplitude3",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_OutputAmplitude4",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Postgain",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Pregain",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_ReleaseTime",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Threshold1",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Threshold2",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Threshold3",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Threshold4"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_AttackTime",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount1",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount2",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount3",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount4",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Crossover1",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Crossover2",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Crossover3",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ1",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ2",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ3",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ4",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Headroom1",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Headroom2",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Headroom3",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Headroom4",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_InputAmplitude1",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_InputAmplitude2",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_InputAmplitude3",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_InputAmplitude4",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_OutputAmplitude1",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_OutputAmplitude2",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_OutputAmplitude3",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_OutputAmplitude4",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Postgain",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Pregain",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_ReleaseTime",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Threshold1",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Threshold2",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Threshold3",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Threshold4"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Effects",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584154-effect_audio_unit_subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389801-aumatrixreverb-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390086-audistortion-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390119-reverb_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1615024-reverb_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390014-varispeed_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390010-audelay-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534061-audeferredrenderer-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3547050-ausampledelay-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389643-aunewtimepitch-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389946-autimepitch_autimepitch_offline"
              ],
              "title": "Effects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Threshold1/title",
          "value": "kMultibandCompressorParam_Threshold1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Threshold1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_Threshold1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Threshold2/title",
          "value": "kMultibandCompressorParam_Threshold2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Threshold2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_Threshold2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Headroom1/title",
          "value": "kMultibandCompressorParam_Headroom1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Headroom1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_Headroom1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_InputAmplitude3/title",
          "value": "kMultibandCompressorParam_InputAmplitude3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_InputAmplitude3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_InputAmplitude3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_OutputAmplitude3/title",
          "value": "kMultibandCompressorParam_OutputAmplitude3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_OutputAmplitude3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_OutputAmplitude3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType/title",
          "value": "AUReverbRoomType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUReverbRoomType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUReverbRoomType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_InputAmplitude1/title",
          "value": "kMultibandCompressorParam_InputAmplitude1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_InputAmplitude1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_InputAmplitude1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Headroom4/title",
          "value": "kMultibandCompressorParam_Headroom4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Headroom4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_Headroom4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Threshold4/title",
          "value": "kMultibandCompressorParam_Threshold4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Threshold4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_Threshold4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_CompressionAmount1/title",
          "value": "kMultibandCompressorParam_CompressionAmount1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_CompressionAmount1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_CompressionAmount1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Headroom3/title",
          "value": "kMultibandCompressorParam_Headroom3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Headroom3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_Headroom3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_EQ1/title",
          "value": "kMultibandCompressorParam_EQ1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_EQ1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_EQ1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_EQ2/title",
          "value": "kMultibandCompressorParam_EQ2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_EQ2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_EQ2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_InputAmplitude2/title",
          "value": "kMultibandCompressorParam_InputAmplitude2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_InputAmplitude2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_InputAmplitude2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_EQ3/title",
          "value": "kMultibandCompressorParam_EQ3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_EQ3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_EQ3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Crossover2/title",
          "value": "kMultibandCompressorParam_Crossover2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Crossover2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_Crossover2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Crossover3/title",
          "value": "kMultibandCompressorParam_Crossover3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Crossover3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_Crossover3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Headroom2/title",
          "value": "kMultibandCompressorParam_Headroom2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Headroom2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_Headroom2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_CompressionAmount2/title",
          "value": "kMultibandCompressorParam_CompressionAmount2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_CompressionAmount2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_CompressionAmount2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_InputAmplitude4/title",
          "value": "kMultibandCompressorParam_InputAmplitude4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_InputAmplitude4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_InputAmplitude4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Threshold3/title",
          "value": "kMultibandCompressorParam_Threshold3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Threshold3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_Threshold3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_OutputAmplitude2/title",
          "value": "kMultibandCompressorParam_OutputAmplitude2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_OutputAmplitude2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_OutputAmplitude2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_ReleaseTime/title",
          "value": "kMultibandCompressorParam_ReleaseTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_ReleaseTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_ReleaseTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_AttackTime/title",
          "value": "kMultibandCompressorParam_AttackTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_AttackTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_AttackTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_OutputAmplitude1/title",
          "value": "kMultibandCompressorParam_OutputAmplitude1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_OutputAmplitude1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_OutputAmplitude1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_CompressionAmount3/title",
          "value": "kMultibandCompressorParam_CompressionAmount3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_CompressionAmount3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_CompressionAmount3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Pregain/title",
          "value": "kMultibandCompressorParam_Pregain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Pregain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_Pregain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Crossover1/title",
          "value": "kMultibandCompressorParam_Crossover1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Crossover1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_Crossover1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_EQ4/title",
          "value": "kMultibandCompressorParam_EQ4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_EQ4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_EQ4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_CompressionAmount4/title",
          "value": "kMultibandCompressorParam_CompressionAmount4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_CompressionAmount4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_CompressionAmount4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Postgain/title",
          "value": "kMultibandCompressorParam_Postgain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Postgain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_Postgain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_OutputAmplitude4/title",
          "value": "kMultibandCompressorParam_OutputAmplitude4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_OutputAmplitude4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_OutputAmplitude4"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1389781-aumultibandcompressor-parameters"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1389781-aumultibandcompressor-parameters"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
