{
  "abstract": [
    {
      "text": "Parameters for the Parametric EQ unit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389950-parametric_eq_unit_parameters"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Parametric EQ Unit Parameters"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389597-peak_limiter_unit_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Peak Limiter unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389597-peak_limiter_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Peak Limiter Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389597-peak_limiter_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389787-dynamics_processor_unit_paramete": {
      "abstract": [
        {
          "text": "Parameters for the Dynamics Processor unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389787-dynamics_processor_unit_paramete",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dynamics Processor Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389787-dynamics_processor_unit_paramete"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389932-audio-unit-graphic-eq-parameter": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389932-audio-unit-graphic-eq-parameter",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Graphic EQ Parameter ID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389932-audio-unit-graphic-eq-parameter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534092-frequency_response_constants": {
      "abstract": [
        {
          "text": "The maximum number of frequency response bin structures for the ",
          "type": "text"
        },
        {
          "code": "AudioUnitProperty_FrequencyResponse",
          "type": "codeVoice"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534092-frequency_response_constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Frequency Response Constants",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534092-frequency_response_constants"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatializationAlgorithm"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatializationAlgorithm"
        }
      ],
      "role": "symbol",
      "title": "AUSpatializationAlgorithm",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatializationalgorithm"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties": {
      "abstract": [
        {
          "text": "Obtain information about the built-in mixers, equalizers, filters, effects, and other Audio Unit app extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kParametricEQParam_CenterFreq": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kParametricEQParam_CenterFreq"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kParametricEQParam_CenterFreq",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kParametricEQParam_CenterFreq"
        }
      ],
      "role": "symbol",
      "title": "kParametricEQParam_CenterFreq",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kparametriceqparam_centerfreq"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kParametricEQParam_Gain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kParametricEQParam_Gain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kParametricEQParam_Gain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kParametricEQParam_Gain"
        }
      ],
      "role": "symbol",
      "title": "kParametricEQParam_Gain",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kparametriceqparam_gain"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kParametricEQParam_Q": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kParametricEQParam_Q"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kParametricEQParam_Q",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kParametricEQParam_Q"
        }
      ],
      "role": "symbol",
      "title": "kParametricEQParam_Q",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kparametriceqparam_q"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Equalizers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389932-audio-unit-graphic-eq-parameter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389597-peak_limiter_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389787-dynamics_processor_unit_paramete",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534092-frequency_response_constants",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm"
      ],
      "title": "Equalizers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kParametricEQParam_CenterFreq",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kParametricEQParam_Gain",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kParametricEQParam_Q"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kParametricEQParam_CenterFreq",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kParametricEQParam_Gain",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kParametricEQParam_Q"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Equalizers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389932-audio-unit-graphic-eq-parameter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389597-peak_limiter_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389787-dynamics_processor_unit_paramete",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534092-frequency_response_constants",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm"
              ],
              "title": "Equalizers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kParametricEQParam_Q/title",
          "value": "kParametricEQParam_Q"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kParametricEQParam_Q/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kParametricEQParam_Q"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kParametricEQParam_Gain/title",
          "value": "kParametricEQParam_Gain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kParametricEQParam_Gain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kParametricEQParam_Gain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm/title",
          "value": "AUSpatializationAlgorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatializationAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatializationAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kParametricEQParam_CenterFreq/title",
          "value": "kParametricEQParam_CenterFreq"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kParametricEQParam_CenterFreq/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kParametricEQParam_CenterFreq"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1389950-parametric_eq_unit_parameters"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1389950-parametric_eq_unit_parameters"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
