{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389808-auroundtripaacparam-parameters"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "AURoundTripAACParam Parameters"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389639-aurandom-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389639-aurandom-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AURandom Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389639-aurandom-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389727-aurogerbeep-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389727-aurogerbeep-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AURogerBeep Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389727-aurogerbeep-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389769-ausampler-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389769-ausampler-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUSampler Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389769-ausampler-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533959-ausampler-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533959-ausampler-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUSampler Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1533959-ausampler-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534086-ausampler-property-ids": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534086-ausampler-property-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUSampler Property IDs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534086-ausampler-property-ids"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534190-aumidisynth-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534190-aumidisynth-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUMIDISynth Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534190-aumidisynth-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties": {
      "abstract": [
        {
          "text": "Obtain information about the built-in mixers, equalizers, filters, effects, and other Audio Unit app extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_BitRate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRoundTripAACParam_BitRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_BitRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRoundTripAACParam_BitRate"
        }
      ],
      "role": "symbol",
      "title": "kRoundTripAACParam_BitRate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kroundtripaacparam_bitrate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_CompressedFormatSampleRate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRoundTripAACParam_CompressedFormatSampleRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_CompressedFormatSampleRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRoundTripAACParam_CompressedFormatSampleRate"
        }
      ],
      "role": "symbol",
      "title": "kRoundTripAACParam_CompressedFormatSampleRate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kroundtripaacparam_compressedformatsamplerate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_EncodingStrategy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRoundTripAACParam_EncodingStrategy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_EncodingStrategy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRoundTripAACParam_EncodingStrategy"
        }
      ],
      "role": "symbol",
      "title": "kRoundTripAACParam_EncodingStrategy",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kroundtripaacparam_encodingstrategy"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_Format": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRoundTripAACParam_Format"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_Format",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRoundTripAACParam_Format"
        }
      ],
      "role": "symbol",
      "title": "kRoundTripAACParam_Format",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kroundtripaacparam_format"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_Quality": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRoundTripAACParam_Quality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_Quality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRoundTripAACParam_Quality"
        }
      ],
      "role": "symbol",
      "title": "kRoundTripAACParam_Quality",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kroundtripaacparam_quality"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_RateOrQuality": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRoundTripAACParam_RateOrQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_RateOrQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRoundTripAACParam_RateOrQuality"
        }
      ],
      "role": "symbol",
      "title": "kRoundTripAACParam_RateOrQuality",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kroundtripaacparam_rateorquality"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Generators",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389639-aurandom-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389769-ausampler-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534086-ausampler-property-ids",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533959-ausampler-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389727-aurogerbeep-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534190-aumidisynth-properties"
      ],
      "title": "Generators"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_BitRate",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_CompressedFormatSampleRate",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_EncodingStrategy",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_Format",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_Quality",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_RateOrQuality"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_BitRate",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_CompressedFormatSampleRate",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_EncodingStrategy",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_Format",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_Quality",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_RateOrQuality"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Generators",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389639-aurandom-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389769-ausampler-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534086-ausampler-property-ids",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533959-ausampler-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389727-aurogerbeep-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534190-aumidisynth-properties"
              ],
              "title": "Generators"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRoundTripAACParam_RateOrQuality/title",
          "value": "kRoundTripAACParam_RateOrQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRoundTripAACParam_RateOrQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRoundTripAACParam_RateOrQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRoundTripAACParam_Format/title",
          "value": "kRoundTripAACParam_Format"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRoundTripAACParam_Format/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRoundTripAACParam_Format"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRoundTripAACParam_Quality/title",
          "value": "kRoundTripAACParam_Quality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRoundTripAACParam_Quality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRoundTripAACParam_Quality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRoundTripAACParam_BitRate/title",
          "value": "kRoundTripAACParam_BitRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRoundTripAACParam_BitRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRoundTripAACParam_BitRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRoundTripAACParam_CompressedFormatSampleRate/title",
          "value": "kRoundTripAACParam_CompressedFormatSampleRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRoundTripAACParam_CompressedFormatSampleRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRoundTripAACParam_CompressedFormatSampleRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRoundTripAACParam_EncodingStrategy/title",
          "value": "kRoundTripAACParam_EncodingStrategy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRoundTripAACParam_EncodingStrategy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRoundTripAACParam_EncodingStrategy"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1389808-auroundtripaacparam-parameters"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1389808-auroundtripaacparam-parameters"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
