{
  "abstract": [
    {
      "text": "Values for the filter type parameter of the Multitype EQ (NBandEQ) unit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389965-aunbandeq_filter_types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "AUNBandEQ Filter Types"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these constants with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQParam_FilterType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " parameter.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389745-aunbandeq-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389745-aunbandeq-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNBandEQ Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389745-aunbandeq-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389948-auhipass_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Highpass unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389948-auhipass_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUHipass Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389948-auhipass_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389967-auhighshelffilter_parameters": {
      "abstract": [
        {
          "text": "Parameters for the High Shelf Filter unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389967-auhighshelffilter_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUHighShelfFilter Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389967-auhighshelffilter_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389995-aulowshelf_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Low Shelf Filter unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389995-aulowshelf_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AULowShelf Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389995-aulowshelf_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389999-aulowpass_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Lowpass unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389999-aulowpass_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AULowpass Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389999-aulowpass_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390144-bandpass_unit_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Bandpass unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390144-bandpass_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Bandpass Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390144-bandpass_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534022-aunbandeq-property-ids": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534022-aunbandeq-property-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNBandEQ Property IDs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534022-aunbandeq-property-ids"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584153-audio-unit-filter-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584153-audio-unit-filter-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Filter Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584153-audio-unit-filter-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties": {
      "abstract": [
        {
          "text": "Obtain information about the built-in mixers, equalizers, filters, effects, and other Audio Unit app extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_2ndOrderButterworthHighPass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_2ndOrderButterworthHighPass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_2ndOrderButterworthHighPass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_2ndOrderButterworthHighPass"
        }
      ],
      "role": "symbol",
      "title": "kAUNBandEQFilterType_2ndOrderButterworthHighPass",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunbandeqfiltertype_2ndorderbutterworthhighpass"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_2ndOrderButterworthLowPass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_2ndOrderButterworthLowPass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_2ndOrderButterworthLowPass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_2ndOrderButterworthLowPass"
        }
      ],
      "role": "symbol",
      "title": "kAUNBandEQFilterType_2ndOrderButterworthLowPass",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunbandeqfiltertype_2ndorderbutterworthlowpass"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_BandPass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_BandPass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_BandPass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_BandPass"
        }
      ],
      "role": "symbol",
      "title": "kAUNBandEQFilterType_BandPass",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunbandeqfiltertype_bandpass"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_BandStop": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_BandStop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_BandStop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_BandStop"
        }
      ],
      "role": "symbol",
      "title": "kAUNBandEQFilterType_BandStop",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunbandeqfiltertype_bandstop"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_HighShelf": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_HighShelf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_HighShelf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_HighShelf"
        }
      ],
      "role": "symbol",
      "title": "kAUNBandEQFilterType_HighShelf",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunbandeqfiltertype_highshelf"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_LowShelf": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_LowShelf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_LowShelf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_LowShelf"
        }
      ],
      "role": "symbol",
      "title": "kAUNBandEQFilterType_LowShelf",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunbandeqfiltertype_lowshelf"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_Parametric": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_Parametric"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_Parametric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_Parametric"
        }
      ],
      "role": "symbol",
      "title": "kAUNBandEQFilterType_Parametric",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunbandeqfiltertype_parametric"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantHighPass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_ResonantHighPass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantHighPass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_ResonantHighPass"
        }
      ],
      "role": "symbol",
      "title": "kAUNBandEQFilterType_ResonantHighPass",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunbandeqfiltertype_resonanthighpass"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantHighShelf": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_ResonantHighShelf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantHighShelf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_ResonantHighShelf"
        }
      ],
      "role": "symbol",
      "title": "kAUNBandEQFilterType_ResonantHighShelf",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunbandeqfiltertype_resonanthighshelf"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantLowPass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_ResonantLowPass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantLowPass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_ResonantLowPass"
        }
      ],
      "role": "symbol",
      "title": "kAUNBandEQFilterType_ResonantLowPass",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunbandeqfiltertype_resonantlowpass"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantLowShelf": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_ResonantLowShelf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantLowShelf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_ResonantLowShelf"
        }
      ],
      "role": "symbol",
      "title": "kAUNBandEQFilterType_ResonantLowShelf",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunbandeqfiltertype_resonantlowshelf"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQParam_FilterType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNBandEQParam_FilterType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQParam_FilterType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNBandEQParam_FilterType"
        }
      ],
      "role": "symbol",
      "title": "kAUNBandEQParam_FilterType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunbandeqparam_filtertype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNumAUNBandEQFilterTypes": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kNumAUNBandEQFilterTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNumAUNBandEQFilterTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kNumAUNBandEQFilterTypes"
        }
      ],
      "role": "symbol",
      "title": "kNumAUNBandEQFilterTypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/knumaunbandeqfiltertypes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Filters",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584153-audio-unit-filter-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390144-bandpass_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389948-auhipass_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389999-aulowpass_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389995-aulowshelf_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389967-auhighshelffilter_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534022-aunbandeq-property-ids",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389745-aunbandeq-parameters"
      ],
      "title": "Filters"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_2ndOrderButterworthHighPass",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_2ndOrderButterworthLowPass",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_BandPass",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_BandStop",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_HighShelf",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_LowShelf",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_Parametric",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantHighPass",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantHighShelf",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantLowPass",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantLowShelf",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNumAUNBandEQFilterTypes"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_2ndOrderButterworthHighPass",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_2ndOrderButterworthLowPass",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_BandPass",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_BandStop",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_HighShelf",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_LowShelf",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_Parametric",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantHighPass",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantHighShelf",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantLowPass",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantLowShelf",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNumAUNBandEQFilterTypes"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Filters",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584153-audio-unit-filter-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390144-bandpass_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389948-auhipass_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389999-aulowpass_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389995-aulowshelf_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389967-auhighshelffilter_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534022-aunbandeq-property-ids",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389745-aunbandeq-parameters"
              ],
              "title": "Filters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_HighShelf/title",
          "value": "kAUNBandEQFilterType_HighShelf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_HighShelf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNBandEQFilterType_HighShelf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_2ndOrderButterworthHighPass/title",
          "value": "kAUNBandEQFilterType_2ndOrderButterworthHighPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_2ndOrderButterworthHighPass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNBandEQFilterType_2ndOrderButterworthHighPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_BandPass/title",
          "value": "kAUNBandEQFilterType_BandPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_BandPass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNBandEQFilterType_BandPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kNumAUNBandEQFilterTypes/title",
          "value": "kNumAUNBandEQFilterTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kNumAUNBandEQFilterTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kNumAUNBandEQFilterTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_ResonantLowShelf/title",
          "value": "kAUNBandEQFilterType_ResonantLowShelf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_ResonantLowShelf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNBandEQFilterType_ResonantLowShelf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_2ndOrderButterworthLowPass/title",
          "value": "kAUNBandEQFilterType_2ndOrderButterworthLowPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_2ndOrderButterworthLowPass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNBandEQFilterType_2ndOrderButterworthLowPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_Parametric/title",
          "value": "kAUNBandEQFilterType_Parametric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_Parametric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNBandEQFilterType_Parametric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_ResonantHighPass/title",
          "value": "kAUNBandEQFilterType_ResonantHighPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_ResonantHighPass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNBandEQFilterType_ResonantHighPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_ResonantHighShelf/title",
          "value": "kAUNBandEQFilterType_ResonantHighShelf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_ResonantHighShelf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNBandEQFilterType_ResonantHighShelf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_LowShelf/title",
          "value": "kAUNBandEQFilterType_LowShelf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_LowShelf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNBandEQFilterType_LowShelf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_BandStop/title",
          "value": "kAUNBandEQFilterType_BandStop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_BandStop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNBandEQFilterType_BandStop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQParam_FilterType/title",
          "value": "kAUNBandEQParam_FilterType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQParam_FilterType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNBandEQParam_FilterType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_ResonantLowPass/title",
          "value": "kAUNBandEQFilterType_ResonantLowPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_ResonantLowPass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNBandEQFilterType_ResonantLowPass"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1389965-aunbandeq_filter_types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1389965-aunbandeq_filter_types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
