{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389643-aunewtimepitch-parameters"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "AUNewTimePitch Parameters"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389781-aumultibandcompressor-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389781-aumultibandcompressor-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUMultibandCompressor Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389781-aumultibandcompressor-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389801-aumatrixreverb-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389801-aumatrixreverb-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUMatrixReverb Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389801-aumatrixreverb-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389946-autimepitch_autimepitch_offline": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389946-autimepitch_autimepitch_offline",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUTimePitch, AUTimePitch (offline), and AUPitch Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389946-autimepitch_autimepitch_offline"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390010-audelay-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390010-audelay-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUDelay Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390010-audelay-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390014-varispeed_unit_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Varispeed unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390014-varispeed_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Varispeed Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390014-varispeed_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390086-audistortion-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390086-audistortion-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUDistortion Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390086-audistortion-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390119-reverb_parameters": {
      "abstract": [
        {
          "text": "Additional reverb parameters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390119-reverb_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Reverb Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390119-reverb_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534061-audeferredrenderer-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534061-audeferredrenderer-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUDeferredRenderer Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534061-audeferredrenderer-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584154-effect_audio_unit_subtypes": {
      "abstract": [
        {
          "text": "Effect (digital signal processing) audio unit subtypes for audio units provided by Apple.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584154-effect_audio_unit_subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Effect Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584154-effect_audio_unit_subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1615024-reverb_unit_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Reverb unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1615024-reverb_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Reverb Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1615024-reverb_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3547050-ausampledelay-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3547050-ausampledelay-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUSampleDelay Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/3547050-ausampledelay-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUReverbRoomType"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUReverbRoomType"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties": {
      "abstract": [
        {
          "text": "Obtain information about the built-in mixers, equalizers, filters, effects, and other Audio Unit app extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNewTimePitchParam_EnablePeakLocking": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kNewTimePitchParam_EnablePeakLocking"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNewTimePitchParam_EnablePeakLocking",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kNewTimePitchParam_EnablePeakLocking"
        }
      ],
      "role": "symbol",
      "title": "kNewTimePitchParam_EnablePeakLocking",
      "type": "topic",
      "url": "/documentation/audiotoolbox/knewtimepitchparam_enablepeaklocking"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNewTimePitchParam_EnableSpectralCoherence": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kNewTimePitchParam_EnableSpectralCoherence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNewTimePitchParam_EnableSpectralCoherence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kNewTimePitchParam_EnableSpectralCoherence"
        }
      ],
      "role": "symbol",
      "title": "kNewTimePitchParam_EnableSpectralCoherence",
      "type": "topic",
      "url": "/documentation/audiotoolbox/knewtimepitchparam_enablespectralcoherence"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNewTimePitchParam_EnableTransientPreservation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kNewTimePitchParam_EnableTransientPreservation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNewTimePitchParam_EnableTransientPreservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kNewTimePitchParam_EnableTransientPreservation"
        }
      ],
      "role": "symbol",
      "title": "kNewTimePitchParam_EnableTransientPreservation",
      "type": "topic",
      "url": "/documentation/audiotoolbox/knewtimepitchparam_enabletransientpreservation"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNewTimePitchParam_Overlap": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kNewTimePitchParam_Overlap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNewTimePitchParam_Overlap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kNewTimePitchParam_Overlap"
        }
      ],
      "role": "symbol",
      "title": "kNewTimePitchParam_Overlap",
      "type": "topic",
      "url": "/documentation/audiotoolbox/knewtimepitchparam_overlap"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNewTimePitchParam_Pitch": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kNewTimePitchParam_Pitch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNewTimePitchParam_Pitch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kNewTimePitchParam_Pitch"
        }
      ],
      "role": "symbol",
      "title": "kNewTimePitchParam_Pitch",
      "type": "topic",
      "url": "/documentation/audiotoolbox/knewtimepitchparam_pitch"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNewTimePitchParam_Rate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kNewTimePitchParam_Rate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNewTimePitchParam_Rate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kNewTimePitchParam_Rate"
        }
      ],
      "role": "symbol",
      "title": "kNewTimePitchParam_Rate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/knewtimepitchparam_rate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNewTimePitchParam_Smoothness": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kNewTimePitchParam_Smoothness"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNewTimePitchParam_Smoothness",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kNewTimePitchParam_Smoothness"
        }
      ],
      "role": "symbol",
      "title": "kNewTimePitchParam_Smoothness",
      "type": "topic",
      "url": "/documentation/audiotoolbox/knewtimepitchparam_smoothness"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Effects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584154-effect_audio_unit_subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389801-aumatrixreverb-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390086-audistortion-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390119-reverb_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1615024-reverb_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390014-varispeed_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390010-audelay-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389781-aumultibandcompressor-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534061-audeferredrenderer-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3547050-ausampledelay-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389946-autimepitch_autimepitch_offline"
      ],
      "title": "Effects"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNewTimePitchParam_EnablePeakLocking",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNewTimePitchParam_Overlap",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNewTimePitchParam_Pitch",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNewTimePitchParam_Rate",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNewTimePitchParam_EnableSpectralCoherence",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNewTimePitchParam_EnableTransientPreservation",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNewTimePitchParam_Smoothness"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNewTimePitchParam_EnablePeakLocking",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNewTimePitchParam_Overlap",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNewTimePitchParam_Pitch",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNewTimePitchParam_Rate",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNewTimePitchParam_EnableSpectralCoherence",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNewTimePitchParam_EnableTransientPreservation",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNewTimePitchParam_Smoothness"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Effects",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584154-effect_audio_unit_subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389801-aumatrixreverb-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390086-audistortion-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390119-reverb_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1615024-reverb_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390014-varispeed_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390010-audelay-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389781-aumultibandcompressor-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534061-audeferredrenderer-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3547050-ausampledelay-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389946-autimepitch_autimepitch_offline"
              ],
              "title": "Effects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kNewTimePitchParam_Rate/title",
          "value": "kNewTimePitchParam_Rate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kNewTimePitchParam_Rate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kNewTimePitchParam_Rate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kNewTimePitchParam_Overlap/title",
          "value": "kNewTimePitchParam_Overlap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kNewTimePitchParam_Overlap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kNewTimePitchParam_Overlap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kNewTimePitchParam_EnableSpectralCoherence/title",
          "value": "kNewTimePitchParam_EnableSpectralCoherence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kNewTimePitchParam_EnableSpectralCoherence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kNewTimePitchParam_EnableSpectralCoherence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kNewTimePitchParam_Pitch/title",
          "value": "kNewTimePitchParam_Pitch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kNewTimePitchParam_Pitch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kNewTimePitchParam_Pitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType/title",
          "value": "AUReverbRoomType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUReverbRoomType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUReverbRoomType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kNewTimePitchParam_EnableTransientPreservation/title",
          "value": "kNewTimePitchParam_EnableTransientPreservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kNewTimePitchParam_EnableTransientPreservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kNewTimePitchParam_EnableTransientPreservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kNewTimePitchParam_Smoothness/title",
          "value": "kNewTimePitchParam_Smoothness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kNewTimePitchParam_Smoothness/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kNewTimePitchParam_Smoothness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kNewTimePitchParam_EnablePeakLocking/title",
          "value": "kNewTimePitchParam_EnablePeakLocking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kNewTimePitchParam_EnablePeakLocking/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kNewTimePitchParam_EnablePeakLocking"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1389643-aunewtimepitch-parameters"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1389643-aunewtimepitch-parameters"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
