{
  "abstract": [
    {
      "text": "Parameters for the 3D Mixer unit.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389763-3d_mixer_unit_parameters"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "3D Mixer Unit Parameters"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389739-aumultichannelmixer_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Multichannel Mixer unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389739-aumultichannelmixer_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUMultiChannelMixer Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389739-aumultichannelmixer_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389928-stereo-mixer-unit-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389928-stereo-mixer-unit-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Stereo Mixer Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389928-stereo-mixer-unit-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389991-panner-audio-unit-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389991-panner-audio-unit-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Panner Audio Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389991-panner-audio-unit-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390003-aumatrixmixer-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390003-aumatrixmixer-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUMatrixMixer Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390003-aumatrixmixer-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390073-auspatialmixer-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390073-auspatialmixer-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUSpatialMixer Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390073-auspatialmixer-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534041-mixer_audio_unit_properties": {
      "abstract": [
        {
          "text": "Properties for Apple mixer audio units.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534041-mixer_audio_unit_properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mixer Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534041-mixer_audio_unit_properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534150-spatial-mixer-property-ids": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534150-spatial-mixer-property-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Spatial Mixer Property IDs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534150-spatial-mixer-property-ids"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584146-audio-unit-mixer-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584146-audio-unit-mixer-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Mixer Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584146-audio-unit-mixer-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584150-mixer_audio_unit_subtypes": {
      "abstract": [
        {
          "text": "Audio mixing audio unit subtypes for audio units provided by Apple.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584150-mixer_audio_unit_subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mixer Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584150-mixer_audio_unit_subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AU3DMixerAttenuationCurve"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AU3DMixerAttenuationCurve"
        }
      ],
      "role": "symbol",
      "title": "AU3DMixerAttenuationCurve",
      "type": "topic",
      "url": "/documentation/audiotoolbox/au3dmixerattenuationcurve"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerAttenuationCurve": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatialMixerAttenuationCurve"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerAttenuationCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatialMixerAttenuationCurve"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerAttenuationCurve",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixerattenuationcurve"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerOutputType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatialMixerOutputType"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerOutputType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatialMixerOutputType"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerOutputType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixeroutputtype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerPointSourceInHeadMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatialMixerPointSourceInHeadMode"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerPointSourceInHeadMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatialMixerPointSourceInHeadMode"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerPointSourceInHeadMode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixerpointsourceinheadmode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerRenderingFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatialMixerRenderingFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerRenderingFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatialMixerRenderingFlags"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerRenderingFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixerrenderingflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatialMixerSourceMode"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatialMixerSourceMode"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerSourceMode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixersourcemode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties": {
      "abstract": [
        {
          "text": "Obtain information about the built-in mixers, equalizers, filters, effects, and other Audio Unit app extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Azimuth": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_Azimuth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Azimuth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_Azimuth"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_Azimuth",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_azimuth"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_BusEnable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_BusEnable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_BusEnable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_BusEnable"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_BusEnable",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_busenable"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Distance": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_Distance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Distance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_Distance"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_Distance",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_distance"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_DryWetReverbBlend": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_DryWetReverbBlend"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_DryWetReverbBlend",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_DryWetReverbBlend"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_DryWetReverbBlend",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_drywetreverbblend"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Elevation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_Elevation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Elevation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_Elevation"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_Elevation",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_elevation"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Enable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_Enable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Enable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_Enable"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_Enable",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_enable"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Gain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_Gain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Gain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_Gain"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_Gain",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_gain"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_GlobalReverbGain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_GlobalReverbGain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_GlobalReverbGain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_GlobalReverbGain"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_GlobalReverbGain",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_globalreverbgain"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_GlobalReverbGainInDecibels": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_GlobalReverbGainInDecibels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_GlobalReverbGainInDecibels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_GlobalReverbGainInDecibels"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_GlobalReverbGainInDecibels",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_globalreverbgainindecibels"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_MaxGain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_MaxGain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_MaxGain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_MaxGain"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_MaxGain",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_maxgain"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_MaxGainInDecibels": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_MaxGainInDecibels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_MaxGainInDecibels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_MaxGainInDecibels"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_MaxGainInDecibels",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_maxgainindecibels"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_MinGain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_MinGain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_MinGain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_MinGain"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_MinGain",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_mingain"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_MinGainInDecibels": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_MinGainInDecibels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_MinGainInDecibels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_MinGainInDecibels"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_MinGainInDecibels",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_mingainindecibels"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_ObstructionAttenuation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_ObstructionAttenuation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_ObstructionAttenuation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_ObstructionAttenuation"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_ObstructionAttenuation",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_obstructionattenuation"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_ObstructionAttenuationInDecibels": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_ObstructionAttenuationInDecibels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_ObstructionAttenuationInDecibels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_ObstructionAttenuationInDecibels"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_ObstructionAttenuationInDecibels",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_obstructionattenuationindecibels"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_OcclusionAttenuation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_OcclusionAttenuation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_OcclusionAttenuation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_OcclusionAttenuation"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_OcclusionAttenuation",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_occlusionattenuation"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_OcclusionAttenuationInDecibels": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_OcclusionAttenuationInDecibels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_OcclusionAttenuationInDecibels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_OcclusionAttenuationInDecibels"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_OcclusionAttenuationInDecibels",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_occlusionattenuationindecibels"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PlaybackRate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_PlaybackRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PlaybackRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_PlaybackRate"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_PlaybackRate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_playbackrate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PostAveragePower": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_PostAveragePower"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PostAveragePower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_PostAveragePower"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_PostAveragePower",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_postaveragepower"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PostPeakHoldLevel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_PostPeakHoldLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PostPeakHoldLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_PostPeakHoldLevel"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_PostPeakHoldLevel",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_postpeakholdlevel"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PreAveragePower": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_PreAveragePower"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PreAveragePower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_PreAveragePower"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_PreAveragePower",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_preaveragepower"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PrePeakHoldLevel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_PrePeakHoldLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PrePeakHoldLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_PrePeakHoldLevel"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_PrePeakHoldLevel",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_prepeakholdlevel"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_ReverbBlend": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_ReverbBlend"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_ReverbBlend",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_ReverbBlend"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_ReverbBlend",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_reverbblend"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Mixers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584146-audio-unit-mixer-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerAttenuationCurve",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerRenderingFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390073-auspatialmixer-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389991-panner-audio-unit-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390003-aumatrixmixer-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389739-aumultichannelmixer_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534150-spatial-mixer-property-ids",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389928-stereo-mixer-unit-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534041-mixer_audio_unit_properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584150-mixer_audio_unit_subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerOutputType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerPointSourceInHeadMode",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve"
      ],
      "title": "Mixers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Azimuth",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Distance",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Elevation",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Enable",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Gain",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_GlobalReverbGain",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_MaxGain",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_MinGain",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_ObstructionAttenuation",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_OcclusionAttenuation",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PlaybackRate",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PostAveragePower",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PostPeakHoldLevel",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PreAveragePower",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PrePeakHoldLevel",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_ReverbBlend",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_BusEnable",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_DryWetReverbBlend",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_GlobalReverbGainInDecibels",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_MaxGainInDecibels",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_MinGainInDecibels",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_ObstructionAttenuationInDecibels",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_OcclusionAttenuationInDecibels"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Azimuth",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Distance",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Elevation",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Enable",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Gain",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_GlobalReverbGain",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_MaxGain",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_MinGain",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_ObstructionAttenuation",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_OcclusionAttenuation",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PlaybackRate",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PostAveragePower",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PostPeakHoldLevel",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PreAveragePower",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PrePeakHoldLevel",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_ReverbBlend",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_BusEnable",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_DryWetReverbBlend",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_GlobalReverbGainInDecibels",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_MaxGainInDecibels",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_MinGainInDecibels",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_ObstructionAttenuationInDecibels",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_OcclusionAttenuationInDecibels"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Mixers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584146-audio-unit-mixer-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerAttenuationCurve",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerRenderingFlags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390073-auspatialmixer-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389991-panner-audio-unit-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390003-aumatrixmixer-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389739-aumultichannelmixer_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534150-spatial-mixer-property-ids",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389928-stereo-mixer-unit-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534041-mixer_audio_unit_properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584150-mixer_audio_unit_subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerOutputType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerPointSourceInHeadMode",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve"
              ],
              "title": "Mixers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_OcclusionAttenuation/title",
          "value": "k3DMixerParam_OcclusionAttenuation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_OcclusionAttenuation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_OcclusionAttenuation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_MinGainInDecibels/title",
          "value": "k3DMixerParam_MinGainInDecibels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_MinGainInDecibels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_MinGainInDecibels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_MaxGain/title",
          "value": "k3DMixerParam_MaxGain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_MaxGain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_MaxGain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_GlobalReverbGainInDecibels/title",
          "value": "k3DMixerParam_GlobalReverbGainInDecibels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_GlobalReverbGainInDecibels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_GlobalReverbGainInDecibels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_OcclusionAttenuationInDecibels/title",
          "value": "k3DMixerParam_OcclusionAttenuationInDecibels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_OcclusionAttenuationInDecibels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_OcclusionAttenuationInDecibels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_GlobalReverbGain/title",
          "value": "k3DMixerParam_GlobalReverbGain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_GlobalReverbGain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_GlobalReverbGain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerAttenuationCurve/title",
          "value": "AUSpatialMixerAttenuationCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerAttenuationCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerAttenuationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerAttenuationCurve/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerAttenuationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerRenderingFlags/title",
          "value": "AUSpatialMixerRenderingFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerRenderingFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerRenderingFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerRenderingFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerRenderingFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_Distance/title",
          "value": "k3DMixerParam_Distance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_Distance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_Distance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_DryWetReverbBlend/title",
          "value": "k3DMixerParam_DryWetReverbBlend"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_DryWetReverbBlend/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_DryWetReverbBlend"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_MaxGainInDecibels/title",
          "value": "k3DMixerParam_MaxGainInDecibels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_MaxGainInDecibels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_MaxGainInDecibels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_Elevation/title",
          "value": "k3DMixerParam_Elevation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_Elevation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_Elevation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_PreAveragePower/title",
          "value": "k3DMixerParam_PreAveragePower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_PreAveragePower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_PreAveragePower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_ObstructionAttenuationInDecibels/title",
          "value": "k3DMixerParam_ObstructionAttenuationInDecibels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_ObstructionAttenuationInDecibels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_ObstructionAttenuationInDecibels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_PostAveragePower/title",
          "value": "k3DMixerParam_PostAveragePower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_PostAveragePower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_PostAveragePower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerAttenuationCurve/title",
          "value": "AU3DMixerAttenuationCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerAttenuationCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AU3DMixerAttenuationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerAttenuationCurve/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AU3DMixerAttenuationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_BusEnable/title",
          "value": "k3DMixerParam_BusEnable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_BusEnable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_BusEnable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_PrePeakHoldLevel/title",
          "value": "k3DMixerParam_PrePeakHoldLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_PrePeakHoldLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_PrePeakHoldLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_ReverbBlend/title",
          "value": "k3DMixerParam_ReverbBlend"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_ReverbBlend/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_ReverbBlend"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerSourceMode/title",
          "value": "AUSpatialMixerSourceMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerSourceMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerSourceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerSourceMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerSourceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_MinGain/title",
          "value": "k3DMixerParam_MinGain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_MinGain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_MinGain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerPointSourceInHeadMode/title",
          "value": "AUSpatialMixerPointSourceInHeadMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerPointSourceInHeadMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerPointSourceInHeadMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerPointSourceInHeadMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerPointSourceInHeadMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_ObstructionAttenuation/title",
          "value": "k3DMixerParam_ObstructionAttenuation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_ObstructionAttenuation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_ObstructionAttenuation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_Azimuth/title",
          "value": "k3DMixerParam_Azimuth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_Azimuth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_Azimuth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_PlaybackRate/title",
          "value": "k3DMixerParam_PlaybackRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_PlaybackRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_PlaybackRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerOutputType/title",
          "value": "AUSpatialMixerOutputType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerOutputType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerOutputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerOutputType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerOutputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_PostPeakHoldLevel/title",
          "value": "k3DMixerParam_PostPeakHoldLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_PostPeakHoldLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_PostPeakHoldLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_Enable/title",
          "value": "k3DMixerParam_Enable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_Enable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_Enable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_Gain/title",
          "value": "k3DMixerParam_Gain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_Gain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_Gain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1389763-3d_mixer_unit_parameters"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1389763-3d_mixer_unit_parameters"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
