{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390003-aumatrixmixer-parameters"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "AUMatrixMixer Parameters"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389739-aumultichannelmixer_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Multichannel Mixer unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389739-aumultichannelmixer_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUMultiChannelMixer Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389739-aumultichannelmixer_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389763-3d_mixer_unit_parameters": {
      "abstract": [
        {
          "text": "Parameters for the 3D Mixer unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389763-3d_mixer_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "3D Mixer Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389763-3d_mixer_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389928-stereo-mixer-unit-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389928-stereo-mixer-unit-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Stereo Mixer Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389928-stereo-mixer-unit-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389991-panner-audio-unit-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389991-panner-audio-unit-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Panner Audio Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389991-panner-audio-unit-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390073-auspatialmixer-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390073-auspatialmixer-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUSpatialMixer Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390073-auspatialmixer-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534041-mixer_audio_unit_properties": {
      "abstract": [
        {
          "text": "Properties for Apple mixer audio units.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534041-mixer_audio_unit_properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mixer Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534041-mixer_audio_unit_properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534150-spatial-mixer-property-ids": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534150-spatial-mixer-property-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Spatial Mixer Property IDs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534150-spatial-mixer-property-ids"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584146-audio-unit-mixer-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584146-audio-unit-mixer-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Mixer Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584146-audio-unit-mixer-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584150-mixer_audio_unit_subtypes": {
      "abstract": [
        {
          "text": "Audio mixing audio unit subtypes for audio units provided by Apple.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584150-mixer_audio_unit_subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mixer Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584150-mixer_audio_unit_subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AU3DMixerAttenuationCurve"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AU3DMixerAttenuationCurve"
        }
      ],
      "role": "symbol",
      "title": "AU3DMixerAttenuationCurve",
      "type": "topic",
      "url": "/documentation/audiotoolbox/au3dmixerattenuationcurve"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerAttenuationCurve": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatialMixerAttenuationCurve"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerAttenuationCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatialMixerAttenuationCurve"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerAttenuationCurve",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixerattenuationcurve"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerOutputType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatialMixerOutputType"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerOutputType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatialMixerOutputType"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerOutputType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixeroutputtype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerPointSourceInHeadMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatialMixerPointSourceInHeadMode"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerPointSourceInHeadMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatialMixerPointSourceInHeadMode"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerPointSourceInHeadMode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixerpointsourceinheadmode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerRenderingFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatialMixerRenderingFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerRenderingFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatialMixerRenderingFlags"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerRenderingFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixerrenderingflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatialMixerSourceMode"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatialMixerSourceMode"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerSourceMode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixersourcemode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties": {
      "abstract": [
        {
          "text": "Obtain information about the built-in mixers, equalizers, filters, effects, and other Audio Unit app extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_Enable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_Enable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_Enable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_Enable"
        }
      ],
      "role": "symbol",
      "title": "kMatrixMixerParam_Enable",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmatrixmixerparam_enable"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostAveragePower": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PostAveragePower"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostAveragePower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PostAveragePower"
        }
      ],
      "role": "symbol",
      "title": "kMatrixMixerParam_PostAveragePower",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmatrixmixerparam_postaveragepower"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostAveragePowerLinear": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PostAveragePowerLinear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostAveragePowerLinear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PostAveragePowerLinear"
        }
      ],
      "role": "symbol",
      "title": "kMatrixMixerParam_PostAveragePowerLinear",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmatrixmixerparam_postaveragepowerlinear"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostPeakHoldLevel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PostPeakHoldLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostPeakHoldLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PostPeakHoldLevel"
        }
      ],
      "role": "symbol",
      "title": "kMatrixMixerParam_PostPeakHoldLevel",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmatrixmixerparam_postpeakholdlevel"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostPeakHoldLevelLinear": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PostPeakHoldLevelLinear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostPeakHoldLevelLinear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PostPeakHoldLevelLinear"
        }
      ],
      "role": "symbol",
      "title": "kMatrixMixerParam_PostPeakHoldLevelLinear",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmatrixmixerparam_postpeakholdlevellinear"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PreAveragePower": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PreAveragePower"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PreAveragePower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PreAveragePower"
        }
      ],
      "role": "symbol",
      "title": "kMatrixMixerParam_PreAveragePower",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmatrixmixerparam_preaveragepower"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PreAveragePowerLinear": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PreAveragePowerLinear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PreAveragePowerLinear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PreAveragePowerLinear"
        }
      ],
      "role": "symbol",
      "title": "kMatrixMixerParam_PreAveragePowerLinear",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmatrixmixerparam_preaveragepowerlinear"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PrePeakHoldLevel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PrePeakHoldLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PrePeakHoldLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PrePeakHoldLevel"
        }
      ],
      "role": "symbol",
      "title": "kMatrixMixerParam_PrePeakHoldLevel",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmatrixmixerparam_prepeakholdlevel"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PrePeakHoldLevelLinear": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PrePeakHoldLevelLinear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PrePeakHoldLevelLinear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PrePeakHoldLevelLinear"
        }
      ],
      "role": "symbol",
      "title": "kMatrixMixerParam_PrePeakHoldLevelLinear",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmatrixmixerparam_prepeakholdlevellinear"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_Volume": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_Volume"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_Volume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_Volume"
        }
      ],
      "role": "symbol",
      "title": "kMatrixMixerParam_Volume",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmatrixmixerparam_volume"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Mixers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584146-audio-unit-mixer-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerAttenuationCurve",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerRenderingFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390073-auspatialmixer-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389991-panner-audio-unit-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389739-aumultichannelmixer_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534150-spatial-mixer-property-ids",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389928-stereo-mixer-unit-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534041-mixer_audio_unit_properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584150-mixer_audio_unit_subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerOutputType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerPointSourceInHeadMode",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389763-3d_mixer_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve"
      ],
      "title": "Mixers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_Enable",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostAveragePower",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostAveragePowerLinear",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostPeakHoldLevel",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostPeakHoldLevelLinear",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PreAveragePower",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PreAveragePowerLinear",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PrePeakHoldLevel",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PrePeakHoldLevelLinear",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_Volume"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_Enable",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostAveragePower",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostAveragePowerLinear",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostPeakHoldLevel",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostPeakHoldLevelLinear",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PreAveragePower",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PreAveragePowerLinear",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PrePeakHoldLevel",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PrePeakHoldLevelLinear",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_Volume"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Mixers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584146-audio-unit-mixer-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerAttenuationCurve",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerRenderingFlags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390073-auspatialmixer-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389991-panner-audio-unit-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389739-aumultichannelmixer_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534150-spatial-mixer-property-ids",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389928-stereo-mixer-unit-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534041-mixer_audio_unit_properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584150-mixer_audio_unit_subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerOutputType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerPointSourceInHeadMode",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389763-3d_mixer_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve"
              ],
              "title": "Mixers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_Volume/title",
          "value": "kMatrixMixerParam_Volume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_Volume/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMatrixMixerParam_Volume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerOutputType/title",
          "value": "AUSpatialMixerOutputType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerOutputType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerOutputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerOutputType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerOutputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerRenderingFlags/title",
          "value": "AUSpatialMixerRenderingFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerRenderingFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerRenderingFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerRenderingFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerRenderingFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PostAveragePower/title",
          "value": "kMatrixMixerParam_PostAveragePower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PostAveragePower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMatrixMixerParam_PostAveragePower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerAttenuationCurve/title",
          "value": "AUSpatialMixerAttenuationCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerAttenuationCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerAttenuationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerAttenuationCurve/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerAttenuationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerAttenuationCurve/title",
          "value": "AU3DMixerAttenuationCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerAttenuationCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AU3DMixerAttenuationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerAttenuationCurve/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AU3DMixerAttenuationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PostPeakHoldLevel/title",
          "value": "kMatrixMixerParam_PostPeakHoldLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PostPeakHoldLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMatrixMixerParam_PostPeakHoldLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PostAveragePowerLinear/title",
          "value": "kMatrixMixerParam_PostAveragePowerLinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PostAveragePowerLinear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMatrixMixerParam_PostAveragePowerLinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PreAveragePower/title",
          "value": "kMatrixMixerParam_PreAveragePower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PreAveragePower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMatrixMixerParam_PreAveragePower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerSourceMode/title",
          "value": "AUSpatialMixerSourceMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerSourceMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerSourceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerSourceMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerSourceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PreAveragePowerLinear/title",
          "value": "kMatrixMixerParam_PreAveragePowerLinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PreAveragePowerLinear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMatrixMixerParam_PreAveragePowerLinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PostPeakHoldLevelLinear/title",
          "value": "kMatrixMixerParam_PostPeakHoldLevelLinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PostPeakHoldLevelLinear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMatrixMixerParam_PostPeakHoldLevelLinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PrePeakHoldLevelLinear/title",
          "value": "kMatrixMixerParam_PrePeakHoldLevelLinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PrePeakHoldLevelLinear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMatrixMixerParam_PrePeakHoldLevelLinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PrePeakHoldLevel/title",
          "value": "kMatrixMixerParam_PrePeakHoldLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PrePeakHoldLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMatrixMixerParam_PrePeakHoldLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerPointSourceInHeadMode/title",
          "value": "AUSpatialMixerPointSourceInHeadMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerPointSourceInHeadMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerPointSourceInHeadMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerPointSourceInHeadMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerPointSourceInHeadMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_Enable/title",
          "value": "kMatrixMixerParam_Enable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_Enable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMatrixMixerParam_Enable"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1390003-aumatrixmixer-parameters"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1390003-aumatrixmixer-parameters"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
