{
  "abstract": [
    {
      "text": "Audio file stream properties contain information that you can use to help interpret the audio data in a stream.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-stream-services"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1391506-audio-file-stream-properties"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio File Stream Properties"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these property IDs when calling the ",
              "type": "text"
            },
            {
              "code": "AudioFileStreamGetProperty",
              "type": "codeVoice"
            },
            {
              "text": " function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamParseBytes(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Passes audio file stream data to the parser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileStreamParseBytes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamID",
          "text": "AudioFileStreamID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioFileStreamParseFlags",
          "text": "AudioFileStreamParseFlags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamParseBytes(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileStreamParseBytes"
        }
      ],
      "role": "symbol",
      "title": "AudioFileStreamParseBytes(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilestreamparsebytes(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileWriteBytes(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Writes bytes of audio data to an audio file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileWriteBytes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileID",
          "text": "AudioFileID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileWriteBytes(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileWriteBytes"
        }
      ],
      "role": "symbol",
      "title": "AudioFileWriteBytes(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilewritebytes(_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileWritePackets(_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Writes packets of audio data to an audio data file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileWritePackets"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileID",
          "text": "AudioFileID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioStreamPacketDescription",
          "text": "AudioStreamPacketDescription"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileWritePackets(_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileWritePackets"
        }
      ],
      "role": "symbol",
      "title": "AudioFileWritePackets(_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilewritepackets(_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-stream-flags": {
      "abstract": [
        {
          "text": "Flags set by the property listener callback and the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamParseBytes(_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-stream-flags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio File Stream Flags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-file-stream-flags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-stream-services": {
      "abstract": [
        {
          "text": "Parse streamed audio files as the data arrives on the user’s computer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-stream-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio File Stream Services",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-file-stream-services"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_AudioDataByteCount": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "UInt64",
          "type": "codeVoice"
        },
        {
          "text": " value indicating the number of bytes of audio data in the streamed file. This property is valid only if the number of bytes for the entire stream is known from the data parsed in the header. For some kinds of streams this property may have no value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_AudioDataByteCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_AudioDataByteCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_AudioDataByteCount"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_AudioDataByteCount",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_audiodatabytecount"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_AudioDataPacketCount": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "UInt64",
          "type": "codeVoice"
        },
        {
          "text": " value indicating the number of packets of audio data in the streamed file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_AudioDataPacketCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_AudioDataPacketCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_AudioDataPacketCount"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_AudioDataPacketCount",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_audiodatapacketcount"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_AverageBytesPerPacket": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "Float64",
          "type": "codeVoice"
        },
        {
          "text": " value indicating the average bytes per packet. For CBR and files with packet tables, this number will be exact. Otherwise, it is a running average of packets parsed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_AverageBytesPerPacket"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_AverageBytesPerPacket",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_AverageBytesPerPacket"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_AverageBytesPerPacket",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_averagebytesperpacket"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_BitRate": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value indicating the bit rate of a stream in bits per second.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_BitRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_BitRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_BitRate"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_BitRate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_bitrate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_ByteToPacket": {
      "abstract": [
        {
          "text": "Obtains the packet number corresponding to a byte number. Pass an ",
          "type": "text"
        },
        {
          "code": "AudioBytePacketTranslation",
          "type": "codeVoice"
        },
        {
          "text": " structure with the ",
          "type": "text"
        },
        {
          "code": "mByte",
          "type": "codeVoice"
        },
        {
          "text": " field filled in, and values are returned in the ",
          "type": "text"
        },
        {
          "code": "mPacket",
          "type": "codeVoice"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "code": "mByteOffsetInPacket",
          "type": "codeVoice"
        },
        {
          "text": " fields. If the ",
          "type": "text"
        },
        {
          "code": "mPacket",
          "type": "codeVoice"
        },
        {
          "text": " value is an estimate, then the ",
          "type": "text"
        },
        {
          "code": "kBytePacketTranslationFlag_IsEstimate",
          "type": "codeVoice"
        },
        {
          "text": " value will be set in the ",
          "type": "text"
        },
        {
          "code": "mFlags",
          "type": "codeVoice"
        },
        {
          "text": " field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_ByteToPacket"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_ByteToPacket",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_ByteToPacket"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_ByteToPacket",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_bytetopacket"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_ChannelLayout": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "AudioChannelLayout",
          "type": "codeVoice"
        },
        {
          "text": " structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_ChannelLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_ChannelLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_ChannelLayout"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_ChannelLayout",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_channellayout"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_DataFormat": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "AudioStreamBasicDescription",
          "type": "codeVoice"
        },
        {
          "text": " structure describing the format of the audio data in the stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_DataFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_DataFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_DataFormat"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_DataFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_dataformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_DataOffset": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "SInt64",
          "type": "codeVoice"
        },
        {
          "text": " value indicating the byte offset in the streamed file at which the audio data starts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_DataOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_DataOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_DataOffset"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_DataOffset",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_dataoffset"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_FileFormat": {
      "abstract": [
        {
          "text": "A four-character code that identifies the audio data format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_FileFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_FileFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_FileFormat"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_FileFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_fileformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_FormatList": {
      "abstract": [
        {
          "text": "To support formats such as AAC with SBR where an encoded data stream can be decoded to multiple destination formats, this property returns an array of ",
          "type": "text"
        },
        {
          "code": "AudioFormatListItem",
          "type": "codeVoice"
        },
        {
          "text": " structures (declared in ",
          "type": "text"
        },
        {
          "code": "AudioFormat.h",
          "type": "codeVoice"
        },
        {
          "text": ")—one for each of the destination formats. The default behavior is to return an ",
          "type": "text"
        },
        {
          "code": "AudioFormatListItem",
          "type": "codeVoice"
        },
        {
          "text": " structure that has the same ",
          "type": "text"
        },
        {
          "code": "AudioStreamBasicDescription",
          "type": "codeVoice"
        },
        {
          "text": " structure as that returned by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_DataFormat",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_FormatList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_FormatList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_FormatList"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_FormatList",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_formatlist"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_FrameToPacket": {
      "abstract": [
        {
          "text": "Obtains the packet number corresponding to a frame number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_FrameToPacket"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_FrameToPacket",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_FrameToPacket"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_FrameToPacket",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_frametopacket"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_InfoDictionary": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_InfoDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_InfoDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_InfoDictionary"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_InfoDictionary",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_infodictionary"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_MagicCookieData": {
      "abstract": [
        {
          "text": "A pointer (",
          "type": "text"
        },
        {
          "code": "void *",
          "type": "codeVoice"
        },
        {
          "text": ") to a magic cookie. For audio file types that require a magic cookie before packets can be written to a file, you should get this property value before calling the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileWriteBytes(_:_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileWritePackets(_:_:_:_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_MagicCookieData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_MagicCookieData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_MagicCookieData"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_MagicCookieData",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_magiccookiedata"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_MaximumPacketSize": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value indicating the maximum packet size of the data in the streamed file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_MaximumPacketSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_MaximumPacketSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_MaximumPacketSize"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_MaximumPacketSize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_maximumpacketsize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_NextIndependentPacket": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_NextIndependentPacket"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_NextIndependentPacket",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_NextIndependentPacket"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_NextIndependentPacket",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_nextindependentpacket"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketSizeUpperBound": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value indicating the theoretical maximum packet size in the streamed file. This value is useful for determining minimum buffer sizes, for example.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_PacketSizeUpperBound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketSizeUpperBound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_PacketSizeUpperBound"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_PacketSizeUpperBound",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_packetsizeupperbound"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketTableInfo": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "AudioFilePacketTableInfo",
          "type": "codeVoice"
        },
        {
          "text": " structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_PacketTableInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketTableInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_PacketTableInfo"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_PacketTableInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_packettableinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketToByte": {
      "abstract": [
        {
          "text": "Obtains the byte number corresponding to a packet number. Pass an ",
          "type": "text"
        },
        {
          "code": "AudioBytePacketTranslation",
          "type": "codeVoice"
        },
        {
          "text": " structure with the ",
          "type": "text"
        },
        {
          "code": "mPacket",
          "type": "codeVoice"
        },
        {
          "text": " field filled in, and a value is returned in the ",
          "type": "text"
        },
        {
          "code": "mByte",
          "type": "codeVoice"
        },
        {
          "text": " field. The ",
          "type": "text"
        },
        {
          "code": "mByteOffsetInPacket",
          "type": "codeVoice"
        },
        {
          "text": " field of the ",
          "type": "text"
        },
        {
          "code": "AudioBytePacketTranslation",
          "type": "codeVoice"
        },
        {
          "text": " structure is ignored. If the ",
          "type": "text"
        },
        {
          "code": "mByte",
          "type": "codeVoice"
        },
        {
          "text": " value is an estimate, then the ",
          "type": "text"
        },
        {
          "code": "kBytePacketTranslationFlag_IsEstimate",
          "type": "codeVoice"
        },
        {
          "text": " value will be set in the ",
          "type": "text"
        },
        {
          "code": "mFlags",
          "type": "codeVoice"
        },
        {
          "text": " field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_PacketToByte"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketToByte",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_PacketToByte"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_PacketToByte",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_packettobyte"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketToDependencyInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_PacketToDependencyInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketToDependencyInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_PacketToDependencyInfo"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_PacketToDependencyInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_packettodependencyinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketToFrame": {
      "abstract": [
        {
          "text": "Obtains the frame number corresponding to a packet number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_PacketToFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketToFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_PacketToFrame"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_PacketToFrame",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_packettoframe"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketToRollDistance": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_PacketToRollDistance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketToRollDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_PacketToRollDistance"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_PacketToRollDistance",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_packettorolldistance"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PreviousIndependentPacket": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_PreviousIndependentPacket"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PreviousIndependentPacket",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_PreviousIndependentPacket"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_PreviousIndependentPacket",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_previousindependentpacket"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_ReadyToProducePackets": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_ReadyToProducePackets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_ReadyToProducePackets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_ReadyToProducePackets"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_ReadyToProducePackets",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_readytoproducepackets"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_RestrictsRandomAccess": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_RestrictsRandomAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_RestrictsRandomAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_RestrictsRandomAccess"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_RestrictsRandomAccess",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_restrictsrandomaccess"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-stream-flags"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_ReadyToProducePackets",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_FileFormat",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_DataFormat",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_FormatList",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_MagicCookieData",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_AudioDataByteCount",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_AudioDataPacketCount",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_MaximumPacketSize",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_DataOffset",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_ChannelLayout",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketToFrame",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_FrameToPacket",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketToByte",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_ByteToPacket",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketTableInfo",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketSizeUpperBound",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_AverageBytesPerPacket",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_BitRate",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_InfoDictionary",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_NextIndependentPacket",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketToDependencyInfo",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketToRollDistance",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PreviousIndependentPacket",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_RestrictsRandomAccess"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_ReadyToProducePackets",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_FileFormat",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_DataFormat",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_FormatList",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_MagicCookieData",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_AudioDataByteCount",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_AudioDataPacketCount",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_MaximumPacketSize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_DataOffset",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_ChannelLayout",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketToFrame",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_FrameToPacket",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketToByte",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_ByteToPacket",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketTableInfo",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketSizeUpperBound",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_AverageBytesPerPacket",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_BitRate",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_InfoDictionary",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_NextIndependentPacket",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketToDependencyInfo",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketToRollDistance",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PreviousIndependentPacket",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_RestrictsRandomAccess"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-stream-flags"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_PacketToByte/title",
          "value": "kAudioFileStreamProperty_PacketToByte"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_PacketToByte/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_PacketToByte"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileWritePackets(_:_:_:_:_:_:_:)/title",
          "value": "AudioFileWritePackets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileWritePackets(_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileWritePackets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_NextIndependentPacket/title",
          "value": "kAudioFileStreamProperty_NextIndependentPacket"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_NextIndependentPacket/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_NextIndependentPacket"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_DataOffset/title",
          "value": "kAudioFileStreamProperty_DataOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_DataOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_DataOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_PacketToRollDistance/title",
          "value": "kAudioFileStreamProperty_PacketToRollDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_PacketToRollDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_PacketToRollDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_MagicCookieData/title",
          "value": "kAudioFileStreamProperty_MagicCookieData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_MagicCookieData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_MagicCookieData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_MaximumPacketSize/title",
          "value": "kAudioFileStreamProperty_MaximumPacketSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_MaximumPacketSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_MaximumPacketSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_AverageBytesPerPacket/title",
          "value": "kAudioFileStreamProperty_AverageBytesPerPacket"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_AverageBytesPerPacket/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_AverageBytesPerPacket"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_PacketToFrame/title",
          "value": "kAudioFileStreamProperty_PacketToFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_PacketToFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_PacketToFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_ChannelLayout/title",
          "value": "kAudioFileStreamProperty_ChannelLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_ChannelLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_ChannelLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_PacketTableInfo/title",
          "value": "kAudioFileStreamProperty_PacketTableInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_PacketTableInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_PacketTableInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_AudioDataByteCount/title",
          "value": "kAudioFileStreamProperty_AudioDataByteCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_AudioDataByteCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_AudioDataByteCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_FileFormat/title",
          "value": "kAudioFileStreamProperty_FileFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_FileFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_FileFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileWriteBytes(_:_:_:_:_:)/title",
          "value": "AudioFileWriteBytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileWriteBytes(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileWriteBytes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_FormatList/title",
          "value": "kAudioFileStreamProperty_FormatList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_FormatList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_FormatList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_ByteToPacket/title",
          "value": "kAudioFileStreamProperty_ByteToPacket"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_ByteToPacket/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_ByteToPacket"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_BitRate/title",
          "value": "kAudioFileStreamProperty_BitRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_BitRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_BitRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_PreviousIndependentPacket/title",
          "value": "kAudioFileStreamProperty_PreviousIndependentPacket"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_PreviousIndependentPacket/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_PreviousIndependentPacket"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_PacketSizeUpperBound/title",
          "value": "kAudioFileStreamProperty_PacketSizeUpperBound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_PacketSizeUpperBound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_PacketSizeUpperBound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_AudioDataPacketCount/title",
          "value": "kAudioFileStreamProperty_AudioDataPacketCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_AudioDataPacketCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_AudioDataPacketCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_ReadyToProducePackets/title",
          "value": "kAudioFileStreamProperty_ReadyToProducePackets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_ReadyToProducePackets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_ReadyToProducePackets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_RestrictsRandomAccess/title",
          "value": "kAudioFileStreamProperty_RestrictsRandomAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_RestrictsRandomAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_RestrictsRandomAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_FrameToPacket/title",
          "value": "kAudioFileStreamProperty_FrameToPacket"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_FrameToPacket/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_FrameToPacket"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileStreamParseBytes(_:_:_:_:)/title",
          "value": "AudioFileStreamParseBytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileStreamParseBytes(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileStreamParseBytes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_InfoDictionary/title",
          "value": "kAudioFileStreamProperty_InfoDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_InfoDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_InfoDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_PacketToDependencyInfo/title",
          "value": "kAudioFileStreamProperty_PacketToDependencyInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_PacketToDependencyInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_PacketToDependencyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_DataFormat/title",
          "value": "kAudioFileStreamProperty_DataFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_DataFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_DataFormat"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1391506-audio-file-stream-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1391506-audio-file-stream-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
