{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-components"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1404186-audio-file-component-specific-pr"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio File Component Specific Properties"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentGetProperty(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileComponentGetProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileComponent",
          "text": "AudioFileComponent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileComponentPropertyID",
          "text": "AudioFileComponentPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentGetProperty(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileComponentGetProperty"
        }
      ],
      "role": "symbol",
      "title": "AudioFileComponentGetProperty(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilecomponentgetproperty(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentGetPropertyInfo(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileComponentGetPropertyInfo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileComponent",
          "text": "AudioFileComponent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileComponentPropertyID",
          "text": "AudioFileComponentPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentGetPropertyInfo(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileComponentGetPropertyInfo"
        }
      ],
      "role": "symbol",
      "title": "AudioFileComponentGetPropertyInfo(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilecomponentgetpropertyinfo(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentGetPropertyInfoProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileComponentGetPropertyInfoProc"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentGetPropertyInfoProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileComponentGetPropertyInfoProc"
        }
      ],
      "role": "symbol",
      "title": "AudioFileComponentGetPropertyInfoProc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilecomponentgetpropertyinfoproc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentGetPropertyProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileComponentGetPropertyProc"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentGetPropertyProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileComponentGetPropertyProc"
        }
      ],
      "role": "symbol",
      "title": "AudioFileComponentGetPropertyProc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilecomponentgetpropertyproc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentSetProperty(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileComponentSetProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileComponent",
          "text": "AudioFileComponent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileComponentPropertyID",
          "text": "AudioFileComponentPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentSetProperty(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileComponentSetProperty"
        }
      ],
      "role": "symbol",
      "title": "AudioFileComponentSetProperty(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilecomponentsetproperty(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentSetPropertyProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileComponentSetPropertyProc"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentSetPropertyProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileComponentSetPropertyProc"
        }
      ],
      "role": "symbol",
      "title": "AudioFileComponentSetPropertyProc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilecomponentsetpropertyproc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-components": {
      "abstract": [
        {
          "text": "Get information about audio file formats, and about files containing audio data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-components",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio File Components",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-file-components"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_AvailableFormatIDs": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_AvailableFormatIDs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_AvailableFormatIDs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_AvailableFormatIDs"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileComponent_AvailableFormatIDs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilecomponent_availableformatids"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_AvailableStreamDescriptionsForFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_AvailableStreamDescriptionsForFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_AvailableStreamDescriptionsForFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_AvailableStreamDescriptionsForFormat"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileComponent_AvailableStreamDescriptionsForFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilecomponent_availablestreamdescriptionsforformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_CanRead": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_CanRead"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_CanRead",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_CanRead"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileComponent_CanRead",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilecomponent_canread"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_CanWrite": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_CanWrite"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_CanWrite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_CanWrite"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileComponent_CanWrite",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilecomponent_canwrite"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_ExtensionsForType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_ExtensionsForType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_ExtensionsForType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_ExtensionsForType"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileComponent_ExtensionsForType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilecomponent_extensionsfortype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_FastDispatchTable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_FastDispatchTable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_FastDispatchTable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_FastDispatchTable"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileComponent_FastDispatchTable",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilecomponent_fastdispatchtable"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_FileTypeName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_FileTypeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_FileTypeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_FileTypeName"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileComponent_FileTypeName",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilecomponent_filetypename"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_HFSTypeCodesForType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_HFSTypeCodesForType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_HFSTypeCodesForType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_HFSTypeCodesForType"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileComponent_HFSTypeCodesForType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilecomponent_hfstypecodesfortype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_MIMETypesForType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_MIMETypesForType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_MIMETypesForType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_MIMETypesForType"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileComponent_MIMETypesForType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilecomponent_mimetypesfortype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_UTIsForType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_UTIsForType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_UTIsForType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_UTIsForType"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileComponent_UTIsForType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilecomponent_utisfortype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentGetProperty(_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentGetPropertyInfo(_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentSetProperty(_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentGetPropertyInfoProc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentGetPropertyProc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentSetPropertyProc"
      ],
      "title": "Accessing Properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_AvailableFormatIDs",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_AvailableStreamDescriptionsForFormat",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_CanRead",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_CanWrite",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_ExtensionsForType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_FastDispatchTable",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_FileTypeName",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_HFSTypeCodesForType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_MIMETypesForType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_UTIsForType"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_AvailableFormatIDs",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_AvailableStreamDescriptionsForFormat",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_CanRead",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_CanWrite",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_ExtensionsForType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_FastDispatchTable",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_FileTypeName",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_HFSTypeCodesForType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_MIMETypesForType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_UTIsForType"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentGetProperty(_:_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentGetPropertyInfo(_:_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentSetProperty(_:_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentGetPropertyInfoProc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentGetPropertyProc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentSetPropertyProc"
              ],
              "title": "Accessing Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileComponentGetPropertyProc/title",
          "value": "AudioFileComponentGetPropertyProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileComponentGetPropertyProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileComponentGetPropertyProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileComponentGetPropertyProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileComponentGetPropertyProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_MIMETypesForType/title",
          "value": "kAudioFileComponent_MIMETypesForType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_MIMETypesForType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileComponent_MIMETypesForType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_FileTypeName/title",
          "value": "kAudioFileComponent_FileTypeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_FileTypeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileComponent_FileTypeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileComponentSetPropertyProc/title",
          "value": "AudioFileComponentSetPropertyProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileComponentSetPropertyProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileComponentSetPropertyProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileComponentSetPropertyProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileComponentSetPropertyProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_UTIsForType/title",
          "value": "kAudioFileComponent_UTIsForType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_UTIsForType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileComponent_UTIsForType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileComponentSetProperty(_:_:_:_:)/title",
          "value": "AudioFileComponentSetProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileComponentSetProperty(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileComponentSetProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileComponentGetPropertyInfo(_:_:_:_:)/title",
          "value": "AudioFileComponentGetPropertyInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileComponentGetPropertyInfo(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileComponentGetPropertyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileComponentGetPropertyInfoProc/title",
          "value": "AudioFileComponentGetPropertyInfoProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileComponentGetPropertyInfoProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileComponentGetPropertyInfoProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileComponentGetPropertyInfoProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileComponentGetPropertyInfoProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_CanRead/title",
          "value": "kAudioFileComponent_CanRead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_CanRead/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileComponent_CanRead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_ExtensionsForType/title",
          "value": "kAudioFileComponent_ExtensionsForType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_ExtensionsForType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileComponent_ExtensionsForType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_HFSTypeCodesForType/title",
          "value": "kAudioFileComponent_HFSTypeCodesForType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_HFSTypeCodesForType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileComponent_HFSTypeCodesForType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_AvailableFormatIDs/title",
          "value": "kAudioFileComponent_AvailableFormatIDs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_AvailableFormatIDs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileComponent_AvailableFormatIDs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_FastDispatchTable/title",
          "value": "kAudioFileComponent_FastDispatchTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_FastDispatchTable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileComponent_FastDispatchTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileComponentGetProperty(_:_:_:_:)/title",
          "value": "AudioFileComponentGetProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileComponentGetProperty(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileComponentGetProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_CanWrite/title",
          "value": "kAudioFileComponent_CanWrite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_CanWrite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileComponent_CanWrite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_AvailableStreamDescriptionsForFormat/title",
          "value": "kAudioFileComponent_AvailableStreamDescriptionsForFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_AvailableStreamDescriptionsForFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileComponent_AvailableStreamDescriptionsForFormat"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1404186-audio-file-component-specific-pr"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1404186-audio-file-component-specific-pr"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
