{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-components"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1404047-audio-file-component-selectors"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio File Component Selectors"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentInitializeWithCallbacks(_:_:_:_:_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileComponentInitializeWithCallbacks"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileComponent",
          "text": "AudioFileComponent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFile_ReadProc",
          "text": "AudioFile_ReadProc"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFile_WriteProc",
          "text": "AudioFile_WriteProc"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFile_GetSizeProc",
          "text": "AudioFile_GetSizeProc"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFile_SetSizeProc",
          "text": "AudioFile_SetSizeProc"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioStreamBasicDescription",
          "text": "AudioStreamBasicDescription"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentInitializeWithCallbacks(_:_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileComponentInitializeWithCallbacks"
        }
      ],
      "role": "symbol",
      "title": "AudioFileComponentInitializeWithCallbacks(_:_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilecomponentinitializewithcallbacks(_:_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentInitializeWithCallbacksProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileComponentInitializeWithCallbacksProc"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentInitializeWithCallbacksProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileComponentInitializeWithCallbacksProc"
        }
      ],
      "role": "symbol",
      "title": "AudioFileComponentInitializeWithCallbacksProc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilecomponentinitializewithcallbacksproc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-components": {
      "abstract": [
        {
          "text": "Get information about audio file formats, and about files containing audio data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-components",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio File Components",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-file-components"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCloseSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileCloseSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCloseSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileCloseSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileCloseSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilecloseselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCountUserDataSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileCountUserDataSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCountUserDataSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileCountUserDataSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileCountUserDataSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilecountuserdataselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCreateSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileCreateSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCreateSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileCreateSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileCreateSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilecreateselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCreateURLSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileCreateURLSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCreateURLSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileCreateURLSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileCreateURLSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilecreateurlselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileDataIsThisFormatSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileDataIsThisFormatSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileDataIsThisFormatSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileDataIsThisFormatSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileDataIsThisFormatSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofiledataisthisformatselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileExtensionIsThisFormatSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileExtensionIsThisFormatSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileExtensionIsThisFormatSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileExtensionIsThisFormatSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileExtensionIsThisFormatSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileextensionisthisformatselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileFileDataIsThisFormatSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileFileDataIsThisFormatSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileFileDataIsThisFormatSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileFileDataIsThisFormatSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileFileDataIsThisFormatSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilefiledataisthisformatselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileFileIsThisFormatSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileFileIsThisFormatSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileFileIsThisFormatSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileFileIsThisFormatSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileFileIsThisFormatSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilefileisthisformatselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetGlobalInfoSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGetGlobalInfoSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetGlobalInfoSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGetGlobalInfoSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGetGlobalInfoSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilegetglobalinfoselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetGlobalInfoSizeSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGetGlobalInfoSizeSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetGlobalInfoSizeSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGetGlobalInfoSizeSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGetGlobalInfoSizeSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilegetglobalinfosizeselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetPropertyInfoSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGetPropertyInfoSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetPropertyInfoSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGetPropertyInfoSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGetPropertyInfoSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilegetpropertyinfoselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetPropertySelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGetPropertySelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetPropertySelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGetPropertySelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGetPropertySelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilegetpropertyselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataAtOffsetSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGetUserDataAtOffsetSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataAtOffsetSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGetUserDataAtOffsetSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGetUserDataAtOffsetSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilegetuserdataatoffsetselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGetUserDataSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGetUserDataSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGetUserDataSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilegetuserdataselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataSize64Select": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGetUserDataSize64Select"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataSize64Select",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGetUserDataSize64Select"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGetUserDataSize64Select",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilegetuserdatasize64select"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataSizeSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGetUserDataSizeSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataSizeSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGetUserDataSizeSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGetUserDataSizeSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilegetuserdatasizeselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInitializeSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileInitializeSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInitializeSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileInitializeSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileInitializeSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileinitializeselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInitializeWithCallbacksSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileInitializeWithCallbacksSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInitializeWithCallbacksSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileInitializeWithCallbacksSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileInitializeWithCallbacksSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileinitializewithcallbacksselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileOpenSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileOpenSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileOpenSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileOpenSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileOpenSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileopenselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileOpenURLSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileOpenURLSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileOpenURLSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileOpenURLSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileOpenURLSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileopenurlselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileOpenWithCallbacksSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileOpenWithCallbacksSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileOpenWithCallbacksSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileOpenWithCallbacksSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileOpenWithCallbacksSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileopenwithcallbacksselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileOptimizeSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileOptimizeSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileOptimizeSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileOptimizeSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileOptimizeSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileoptimizeselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileReadBytesSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileReadBytesSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileReadBytesSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileReadBytesSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileReadBytesSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilereadbytesselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileReadPacketDataSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileReadPacketDataSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileReadPacketDataSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileReadPacketDataSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileReadPacketDataSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilereadpacketdataselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileReadPacketsSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileReadPacketsSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileReadPacketsSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileReadPacketsSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileReadPacketsSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilereadpacketsselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileRemoveUserDataSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileRemoveUserDataSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileRemoveUserDataSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileRemoveUserDataSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileRemoveUserDataSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileremoveuserdataselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileSetPropertySelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileSetPropertySelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileSetPropertySelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileSetPropertySelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileSetPropertySelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilesetpropertyselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileSetUserDataSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileSetUserDataSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileSetUserDataSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileSetUserDataSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileSetUserDataSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilesetuserdataselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileWriteBytesSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileWriteBytesSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileWriteBytesSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileWriteBytesSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileWriteBytesSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilewritebytesselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileWritePacketsSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileWritePacketsSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileWritePacketsSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileWritePacketsSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileWritePacketsSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilewritepacketsselect"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-Callbacks",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentInitializeWithCallbacks(_:_:_:_:_:_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentInitializeWithCallbacksProc"
      ],
      "title": "Configuring the Callbacks"
    }
  ],
  "topicSections": [
    {
      "anchor": "Selectors",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCloseSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCountUserDataSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCreateSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCreateURLSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileDataIsThisFormatSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileExtensionIsThisFormatSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileFileDataIsThisFormatSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileFileIsThisFormatSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetGlobalInfoSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetGlobalInfoSizeSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetPropertyInfoSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataAtOffsetSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataSize64Select",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetPropertySelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataSizeSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInitializeSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInitializeWithCallbacksSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileOpenSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileOpenURLSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileOpenWithCallbacksSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileOptimizeSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileReadBytesSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileReadPacketDataSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileReadPacketsSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileRemoveUserDataSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileSetPropertySelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileSetUserDataSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileWriteBytesSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileWritePacketsSelect"
      ],
      "title": "Selectors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Selectors",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCloseSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCountUserDataSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCreateSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCreateURLSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileDataIsThisFormatSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileExtensionIsThisFormatSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileFileDataIsThisFormatSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileFileIsThisFormatSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetGlobalInfoSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetGlobalInfoSizeSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetPropertyInfoSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataAtOffsetSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataSize64Select",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetPropertySelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataSizeSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInitializeSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInitializeWithCallbacksSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileOpenSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileOpenURLSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileOpenWithCallbacksSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileOptimizeSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileReadBytesSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileReadPacketDataSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileReadPacketsSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileRemoveUserDataSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileSetPropertySelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileSetUserDataSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileWriteBytesSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileWritePacketsSelect"
              ],
              "title": "Selectors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-Callbacks",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentInitializeWithCallbacks(_:_:_:_:_:_:_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentInitializeWithCallbacksProc"
              ],
              "title": "Configuring the Callbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileOptimizeSelect/title",
          "value": "kAudioFileOptimizeSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileOptimizeSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileOptimizeSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileComponentInitializeWithCallbacks(_:_:_:_:_:_:_:_:_:)/title",
          "value": "AudioFileComponentInitializeWithCallbacks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileComponentInitializeWithCallbacks(_:_:_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileComponentInitializeWithCallbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileReadBytesSelect/title",
          "value": "kAudioFileReadBytesSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileReadBytesSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileReadBytesSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileInitializeSelect/title",
          "value": "kAudioFileInitializeSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileInitializeSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileInitializeSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileReadPacketsSelect/title",
          "value": "kAudioFileReadPacketsSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileReadPacketsSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileReadPacketsSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileWriteBytesSelect/title",
          "value": "kAudioFileWriteBytesSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileWriteBytesSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileWriteBytesSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetPropertyInfoSelect/title",
          "value": "kAudioFileGetPropertyInfoSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetPropertyInfoSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGetPropertyInfoSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileSetPropertySelect/title",
          "value": "kAudioFileSetPropertySelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileSetPropertySelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileSetPropertySelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileCloseSelect/title",
          "value": "kAudioFileCloseSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileCloseSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileCloseSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetUserDataAtOffsetSelect/title",
          "value": "kAudioFileGetUserDataAtOffsetSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetUserDataAtOffsetSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGetUserDataAtOffsetSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileCreateURLSelect/title",
          "value": "kAudioFileCreateURLSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileCreateURLSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileCreateURLSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileReadPacketDataSelect/title",
          "value": "kAudioFileReadPacketDataSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileReadPacketDataSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileReadPacketDataSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileFileDataIsThisFormatSelect/title",
          "value": "kAudioFileFileDataIsThisFormatSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileFileDataIsThisFormatSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileFileDataIsThisFormatSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileCountUserDataSelect/title",
          "value": "kAudioFileCountUserDataSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileCountUserDataSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileCountUserDataSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileExtensionIsThisFormatSelect/title",
          "value": "kAudioFileExtensionIsThisFormatSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileExtensionIsThisFormatSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileExtensionIsThisFormatSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileInitializeWithCallbacksSelect/title",
          "value": "kAudioFileInitializeWithCallbacksSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileInitializeWithCallbacksSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileInitializeWithCallbacksSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileComponentInitializeWithCallbacksProc/title",
          "value": "AudioFileComponentInitializeWithCallbacksProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileComponentInitializeWithCallbacksProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileComponentInitializeWithCallbacksProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileComponentInitializeWithCallbacksProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileComponentInitializeWithCallbacksProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetUserDataSize64Select/title",
          "value": "kAudioFileGetUserDataSize64Select"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetUserDataSize64Select/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGetUserDataSize64Select"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileOpenSelect/title",
          "value": "kAudioFileOpenSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileOpenSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileOpenSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetUserDataSelect/title",
          "value": "kAudioFileGetUserDataSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetUserDataSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGetUserDataSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetPropertySelect/title",
          "value": "kAudioFileGetPropertySelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetPropertySelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGetPropertySelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileDataIsThisFormatSelect/title",
          "value": "kAudioFileDataIsThisFormatSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileDataIsThisFormatSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileDataIsThisFormatSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileOpenWithCallbacksSelect/title",
          "value": "kAudioFileOpenWithCallbacksSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileOpenWithCallbacksSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileOpenWithCallbacksSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetUserDataSizeSelect/title",
          "value": "kAudioFileGetUserDataSizeSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetUserDataSizeSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGetUserDataSizeSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileRemoveUserDataSelect/title",
          "value": "kAudioFileRemoveUserDataSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileRemoveUserDataSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileRemoveUserDataSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetGlobalInfoSelect/title",
          "value": "kAudioFileGetGlobalInfoSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetGlobalInfoSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGetGlobalInfoSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileWritePacketsSelect/title",
          "value": "kAudioFileWritePacketsSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileWritePacketsSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileWritePacketsSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetGlobalInfoSizeSelect/title",
          "value": "kAudioFileGetGlobalInfoSizeSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetGlobalInfoSizeSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGetGlobalInfoSizeSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileCreateSelect/title",
          "value": "kAudioFileCreateSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileCreateSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileCreateSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileFileIsThisFormatSelect/title",
          "value": "kAudioFileFileIsThisFormatSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileFileIsThisFormatSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileFileIsThisFormatSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileOpenURLSelect/title",
          "value": "kAudioFileOpenURLSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileOpenURLSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileOpenURLSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileSetUserDataSelect/title",
          "value": "kAudioFileSetUserDataSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileSetUserDataSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileSetUserDataSelect"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1404047-audio-file-component-selectors"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1404047-audio-file-component-selectors"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
