{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-services"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1405232-audio-services-errors"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio Services Errors"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-services": {
      "abstract": [
        {
          "text": "Play short sounds or trigger a vibration effect on iOS devices with the appropriate hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Services",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-services"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesBadPropertySizeError": {
      "abstract": [
        {
          "text": "The size of the property data was not correct.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioServicesBadPropertySizeError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesBadPropertySizeError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioServicesBadPropertySizeError"
        }
      ],
      "role": "symbol",
      "title": "kAudioServicesBadPropertySizeError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioservicesbadpropertysizeerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesBadSpecifierSizeError": {
      "abstract": [
        {
          "text": "The size of the specifier data was not correct.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioServicesBadSpecifierSizeError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesBadSpecifierSizeError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioServicesBadSpecifierSizeError"
        }
      ],
      "role": "symbol",
      "title": "kAudioServicesBadSpecifierSizeError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioservicesbadspecifiersizeerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesNoError": {
      "abstract": [
        {
          "text": "No error has occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioServicesNoError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesNoError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioServicesNoError"
        }
      ],
      "role": "symbol",
      "title": "kAudioServicesNoError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioservicesnoerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesSystemSoundClientTimedOutError": {
      "abstract": [
        {
          "text": "System sound client message timed out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioServicesSystemSoundClientTimedOutError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesSystemSoundClientTimedOutError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioServicesSystemSoundClientTimedOutError"
        }
      ],
      "role": "symbol",
      "title": "kAudioServicesSystemSoundClientTimedOutError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioservicessystemsoundclienttimedouterror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesSystemSoundExceededMaximumDurationError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioServicesSystemSoundExceededMaximumDurationError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesSystemSoundExceededMaximumDurationError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioServicesSystemSoundExceededMaximumDurationError"
        }
      ],
      "role": "symbol",
      "title": "kAudioServicesSystemSoundExceededMaximumDurationError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioservicessystemsoundexceededmaximumdurationerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesSystemSoundUnspecifiedError": {
      "abstract": [
        {
          "text": "An unspecified error has occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioServicesSystemSoundUnspecifiedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesSystemSoundUnspecifiedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioServicesSystemSoundUnspecifiedError"
        }
      ],
      "role": "symbol",
      "title": "kAudioServicesSystemSoundUnspecifiedError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioservicessystemsoundunspecifiederror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesUnsupportedPropertyError": {
      "abstract": [
        {
          "text": "The property is not supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioServicesUnsupportedPropertyError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesUnsupportedPropertyError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioServicesUnsupportedPropertyError"
        }
      ],
      "role": "symbol",
      "title": "kAudioServicesUnsupportedPropertyError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioservicesunsupportedpropertyerror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesNoError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesUnsupportedPropertyError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesBadPropertySizeError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesBadSpecifierSizeError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesSystemSoundUnspecifiedError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesSystemSoundClientTimedOutError"
      ],
      "title": "Getting Error Codes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesBadPropertySizeError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesBadSpecifierSizeError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesNoError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesSystemSoundClientTimedOutError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesSystemSoundUnspecifiedError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesUnsupportedPropertyError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesSystemSoundExceededMaximumDurationError"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesBadPropertySizeError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesBadSpecifierSizeError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesNoError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesSystemSoundClientTimedOutError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesSystemSoundUnspecifiedError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesUnsupportedPropertyError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesSystemSoundExceededMaximumDurationError"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Error-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesNoError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesUnsupportedPropertyError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesBadPropertySizeError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesBadSpecifierSizeError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesSystemSoundUnspecifiedError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesSystemSoundClientTimedOutError"
              ],
              "title": "Getting Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioServicesBadPropertySizeError/title",
          "value": "kAudioServicesBadPropertySizeError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioServicesBadPropertySizeError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioServicesBadPropertySizeError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioServicesUnsupportedPropertyError/title",
          "value": "kAudioServicesUnsupportedPropertyError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioServicesUnsupportedPropertyError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioServicesUnsupportedPropertyError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioServicesNoError/title",
          "value": "kAudioServicesNoError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioServicesNoError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioServicesNoError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioServicesSystemSoundExceededMaximumDurationError/title",
          "value": "kAudioServicesSystemSoundExceededMaximumDurationError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioServicesSystemSoundExceededMaximumDurationError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioServicesSystemSoundExceededMaximumDurationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioServicesSystemSoundUnspecifiedError/title",
          "value": "kAudioServicesSystemSoundUnspecifiedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioServicesSystemSoundUnspecifiedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioServicesSystemSoundUnspecifiedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioServicesBadSpecifierSizeError/title",
          "value": "kAudioServicesBadSpecifierSizeError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioServicesBadSpecifierSizeError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioServicesBadSpecifierSizeError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioServicesSystemSoundClientTimedOutError/title",
          "value": "kAudioServicesSystemSoundClientTimedOutError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioServicesSystemSoundClientTimedOutError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioServicesSystemSoundClientTimedOutError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1405232-audio-services-errors"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1405232-audio-services-errors"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
