{
  "abstract": [
    {
      "text": "Property identifiers that apply to HAL audio objects only when accessed via the Audio Hardware Services.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-services"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1405208-audio-hardware-services-properti"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio Hardware Services Properties"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1405268-system-sound-services-property-i": {
      "abstract": [
        {
          "text": "Property identifiers used when playing alerts with System Sound Services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1405268-system-sound-services-property-i",
      "kind": "article",
      "role": "collectionGroup",
      "title": "System Sound Services Property Identifiers",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1405268-system-sound-services-property-i"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesGetProperty(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Gets a specified System Sound Services property value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioServicesGetProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioServicesPropertyID",
          "text": "AudioServicesPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesGetProperty(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioServicesGetProperty"
        }
      ],
      "role": "symbol",
      "title": "AudioServicesGetProperty(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioservicesgetproperty(_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesGetPropertyInfo(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Gets information about a System Sound Services property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioServicesGetPropertyInfo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioServicesPropertyID",
          "text": "AudioServicesPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Darwin0A7BooleanV",
          "text": "DarwinBoolean"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesGetPropertyInfo(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioServicesGetPropertyInfo"
        }
      ],
      "role": "symbol",
      "title": "AudioServicesGetPropertyInfo(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioservicesgetpropertyinfo(_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesPropertyID": {
      "abstract": [
        {
          "text": "The data type for a system sound property identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioServicesPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesPropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioServicesPropertyID"
        }
      ],
      "role": "symbol",
      "title": "AudioServicesPropertyID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioservicespropertyid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesSetProperty(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Sets the value for a specified System Sound Services property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioServicesSetProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioServicesPropertyID",
          "text": "AudioServicesPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesSetProperty(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioServicesSetProperty"
        }
      ],
      "role": "symbol",
      "title": "AudioServicesSetProperty(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioservicessetproperty(_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-services": {
      "abstract": [
        {
          "text": "Play short sounds or trigger a vibration effect on iOS devices with the appropriate hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Services",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-services"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMainBalance": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwareServiceDeviceProperty_VirtualMainBalance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMainBalance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwareServiceDeviceProperty_VirtualMainBalance"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwareServiceDeviceProperty_VirtualMainBalance",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiohardwareservicedeviceproperty_virtualmainbalance"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMainVolume": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwareServiceDeviceProperty_VirtualMainVolume"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMainVolume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwareServiceDeviceProperty_VirtualMainVolume"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwareServiceDeviceProperty_VirtualMainVolume",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiohardwareservicedeviceproperty_virtualmainvolume"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMasterBalance": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "Float32",
          "type": "codeVoice"
        },
        {
          "text": " value that represents the value of a hardware device’s stereo balance control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kAudioHardwareServiceDeviceProperty_VirtualMasterBalance"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMasterBalance",
      "kind": "symbol",
      "role": "symbol",
      "title": "kAudioHardwareServiceDeviceProperty_VirtualMasterBalance",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiohardwareservicedeviceproperty_virtualmasterbalance"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMasterVolume": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "Float32",
          "type": "codeVoice"
        },
        {
          "text": " value that represents the value of the volume control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kAudioHardwareServiceDeviceProperty_VirtualMasterVolume"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMasterVolume",
      "kind": "symbol",
      "role": "symbol",
      "title": "kAudioHardwareServiceDeviceProperty_VirtualMasterVolume",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiohardwareservicedeviceproperty_virtualmastervolume"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceProperty_ServiceRestarted": {
      "abstract": [
        {
          "text": "Used, with a HAL audio object property listener callback, as a flag that indicates a hardware service restart. The property’s ",
          "type": "text"
        },
        {
          "code": "Float32",
          "type": "codeVoice"
        },
        {
          "text": " value has no meaning. When the hardware service restarts, any associated application state, such as cached data or property listener callbacks, must be re-established.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwareServiceProperty_ServiceRestarted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceProperty_ServiceRestarted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwareServiceProperty_ServiceRestarted"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwareServiceProperty_ServiceRestarted",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiohardwareserviceproperty_servicerestarted"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-System-Sound-Services-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesGetPropertyInfo(_:_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesGetProperty(_:_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesSetProperty(_:_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesPropertyID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1405268-system-sound-services-property-i"
      ],
      "title": "Managing System Sound Services Properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceProperty_ServiceRestarted",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMainBalance",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMainVolume"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceProperty_ServiceRestarted",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMasterVolume",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMasterBalance",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMainBalance",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMainVolume"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-System-Sound-Services-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesGetPropertyInfo(_:_:_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesGetProperty(_:_:_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesSetProperty(_:_:_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesPropertyID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1405268-system-sound-services-property-i"
              ],
              "title": "Managing System Sound Services Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioServicesGetPropertyInfo(_:_:_:_:_:)/title",
          "value": "AudioServicesGetPropertyInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioServicesGetPropertyInfo(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioServicesGetPropertyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioHardwareServiceDeviceProperty_VirtualMainVolume/title",
          "value": "kAudioHardwareServiceDeviceProperty_VirtualMainVolume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioHardwareServiceDeviceProperty_VirtualMainVolume/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwareServiceDeviceProperty_VirtualMainVolume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioServicesSetProperty(_:_:_:_:_:)/title",
          "value": "AudioServicesSetProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioServicesSetProperty(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioServicesSetProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioServicesPropertyID/title",
          "value": "AudioServicesPropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioServicesPropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioServicesPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioServicesPropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioServicesPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioHardwareServiceDeviceProperty_VirtualMainBalance/title",
          "value": "kAudioHardwareServiceDeviceProperty_VirtualMainBalance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioHardwareServiceDeviceProperty_VirtualMainBalance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwareServiceDeviceProperty_VirtualMainBalance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioServicesGetProperty(_:_:_:_:_:)/title",
          "value": "AudioServicesGetProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioServicesGetProperty(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioServicesGetProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioHardwareServiceProperty_ServiceRestarted/title",
          "value": "kAudioHardwareServiceProperty_ServiceRestarted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioHardwareServiceProperty_ServiceRestarted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwareServiceProperty_ServiceRestarted"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1405208-audio-hardware-services-properti"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1405208-audio-hardware-services-properti"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
