{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/extended-audio-file-services"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1486883-extended-audio-file-errors"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Extended Audio FIle Errors"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1486859-property-identifiers-for-extende": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1486859-property-identifiers-for-extende",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Property Identifiers for Extended Audio File Objects",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1486859-property-identifiers-for-extende"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1623673-codec-unavailable-errors": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1623673-codec-unavailable-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Codec Unavailable Errors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1623673-codec-unavailable-errors"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3547074-extended-audio-file-packet-overr": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3547074-extended-audio-file-packet-overr",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Extended Audio File Packet Overrides",
      "type": "topic",
      "url": "/documentation/audiotoolbox/3547074-extended-audio-file-packet-overr"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/extended-audio-file-services": {
      "abstract": [
        {
          "text": "Read and write compressed files and linear PCM audio files using a simplified interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/extended-audio-file-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Extended Audio File Services",
      "type": "topic",
      "url": "/documentation/audiotoolbox/extended-audio-file-services"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_AsyncWriteBufferOverflow": {
      "abstract": [
        {
          "text": "An asynchronous write operation could not be completed in time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_AsyncWriteBufferOverflow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_AsyncWriteBufferOverflow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_AsyncWriteBufferOverflow"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileError_AsyncWriteBufferOverflow",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileerror_asyncwritebufferoverflow"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_AsyncWriteTooLarge": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_AsyncWriteTooLarge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_AsyncWriteTooLarge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_AsyncWriteTooLarge"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileError_AsyncWriteTooLarge",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileerror_asyncwritetoolarge"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidChannelMap": {
      "abstract": [
        {
          "text": "The number of channels does not match the specified format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_InvalidChannelMap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidChannelMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_InvalidChannelMap"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileError_InvalidChannelMap",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileerror_invalidchannelmap"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidDataFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_InvalidDataFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidDataFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_InvalidDataFormat"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileError_InvalidDataFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileerror_invaliddataformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidOperationOrder": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_InvalidOperationOrder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidOperationOrder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_InvalidOperationOrder"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileError_InvalidOperationOrder",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileerror_invalidoperationorder"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidProperty": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_InvalidProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_InvalidProperty"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileError_InvalidProperty",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileerror_invalidproperty"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidPropertySize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_InvalidPropertySize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidPropertySize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_InvalidPropertySize"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileError_InvalidPropertySize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileerror_invalidpropertysize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidSeek": {
      "abstract": [
        {
          "text": "An attempt to write, or an offset, is out of bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_InvalidSeek"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidSeek",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_InvalidSeek"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileError_InvalidSeek",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileerror_invalidseek"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_MaxPacketSizeUnknown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_MaxPacketSizeUnknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_MaxPacketSizeUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_MaxPacketSizeUnknown"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileError_MaxPacketSizeUnknown",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileerror_maxpacketsizeunknown"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_NonPCMClientFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_NonPCMClientFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_NonPCMClientFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_NonPCMClientFormat"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileError_NonPCMClientFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileerror_nonpcmclientformat"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1623673-codec-unavailable-errors",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1486859-property-identifiers-for-extende",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3547074-extended-audio-file-packet-overr"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_AsyncWriteBufferOverflow",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_AsyncWriteTooLarge",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidChannelMap",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidDataFormat",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidOperationOrder",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidProperty",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidPropertySize",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidSeek",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_MaxPacketSizeUnknown",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_NonPCMClientFormat"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_AsyncWriteBufferOverflow",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_AsyncWriteTooLarge",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidChannelMap",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidDataFormat",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidOperationOrder",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidProperty",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidPropertySize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidSeek",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_MaxPacketSizeUnknown",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_NonPCMClientFormat"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1623673-codec-unavailable-errors",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1486859-property-identifiers-for-extende",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3547074-extended-audio-file-packet-overr"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_MaxPacketSizeUnknown/title",
          "value": "kExtAudioFileError_MaxPacketSizeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_MaxPacketSizeUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileError_MaxPacketSizeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_InvalidProperty/title",
          "value": "kExtAudioFileError_InvalidProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_InvalidProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileError_InvalidProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_AsyncWriteTooLarge/title",
          "value": "kExtAudioFileError_AsyncWriteTooLarge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_AsyncWriteTooLarge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileError_AsyncWriteTooLarge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_InvalidOperationOrder/title",
          "value": "kExtAudioFileError_InvalidOperationOrder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_InvalidOperationOrder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileError_InvalidOperationOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_InvalidDataFormat/title",
          "value": "kExtAudioFileError_InvalidDataFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_InvalidDataFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileError_InvalidDataFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_InvalidChannelMap/title",
          "value": "kExtAudioFileError_InvalidChannelMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_InvalidChannelMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileError_InvalidChannelMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_AsyncWriteBufferOverflow/title",
          "value": "kExtAudioFileError_AsyncWriteBufferOverflow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_AsyncWriteBufferOverflow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileError_AsyncWriteBufferOverflow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_InvalidSeek/title",
          "value": "kExtAudioFileError_InvalidSeek"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_InvalidSeek/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileError_InvalidSeek"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_InvalidPropertySize/title",
          "value": "kExtAudioFileError_InvalidPropertySize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_InvalidPropertySize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileError_InvalidPropertySize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_NonPCMClientFormat/title",
          "value": "kExtAudioFileError_NonPCMClientFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_NonPCMClientFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileError_NonPCMClientFormat"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1486883-extended-audio-file-errors"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1486883-extended-audio-file-errors"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
