{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/deprecated-symbols"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494070-deprecated-constants-used-with-k"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Deprecated Constants Used With kAudioCodecOutputPrecedence"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533960-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533960-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1533960-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534019-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534019-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534019-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534063-3d_mixer_audio_unit_properties": {
      "abstract": [
        {
          "text": "Properties for the Apple 3D Mixer audio unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534063-3d_mixer_audio_unit_properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "3D Mixer Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534063-3d_mixer_audio_unit_properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534074-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534074-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534074-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534089-music-device-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534089-music-device-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Music Device Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534089-music-device-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534112-audio-unit-attenuation-propertie": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534112-audio-unit-attenuation-propertie",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Attenuation Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534112-audio-unit-attenuation-propertie"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534225-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534225-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534225-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1537630-audio-graph-errors": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1537630-audio-graph-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Graph Errors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1537630-audio-graph-errors"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584141-audio-unit-instrument-errors": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584141-audio-unit-instrument-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Instrument Errors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584141-audio-unit-instrument-errors"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618426-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618426-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1618426-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618742-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618742-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1618742-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619479-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619479-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1619479-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619504-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619504-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1619504-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621044-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621044-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1621044-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1624333-audio-converter-property-id": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1624333-audio-converter-property-id",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Converter Property ID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1624333-audio-converter-property-id"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/deprecated-symbols": {
      "abstract": [
        {
          "text": "Review unsupported symbols and their replacements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/audiotoolbox/deprecated-symbols"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecOutputPrecedenceBitRate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecOutputPrecedenceBitRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecOutputPrecedenceBitRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecOutputPrecedenceBitRate"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecOutputPrecedenceBitRate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecoutputprecedencebitrate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecOutputPrecedenceNone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecOutputPrecedenceNone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecOutputPrecedenceNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecOutputPrecedenceNone"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecOutputPrecedenceNone",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecoutputprecedencenone"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecOutputPrecedenceSampleRate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecOutputPrecedenceSampleRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecOutputPrecedenceSampleRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecOutputPrecedenceSampleRate"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecOutputPrecedenceSampleRate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecoutputprecedencesamplerate"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534112-audio-unit-attenuation-propertie",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584141-audio-unit-instrument-errors",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534019-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534074-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1537630-audio-graph-errors",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1624333-audio-converter-property-id",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621044-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618426-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618742-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619479-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619504-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533960-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534225-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534089-music-device-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534063-3d_mixer_audio_unit_properties"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecOutputPrecedenceBitRate",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecOutputPrecedenceNone",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecOutputPrecedenceSampleRate"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecOutputPrecedenceBitRate",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecOutputPrecedenceNone",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecOutputPrecedenceSampleRate"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534112-audio-unit-attenuation-propertie",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584141-audio-unit-instrument-errors",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534019-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534074-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1537630-audio-graph-errors",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1624333-audio-converter-property-id",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621044-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618426-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618742-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619479-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619504-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533960-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534225-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534089-music-device-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534063-3d_mixer_audio_unit_properties"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecOutputPrecedenceBitRate/title",
          "value": "kAudioCodecOutputPrecedenceBitRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecOutputPrecedenceBitRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecOutputPrecedenceBitRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecOutputPrecedenceSampleRate/title",
          "value": "kAudioCodecOutputPrecedenceSampleRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecOutputPrecedenceSampleRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecOutputPrecedenceSampleRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecOutputPrecedenceNone/title",
          "value": "kAudioCodecOutputPrecedenceNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecOutputPrecedenceNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecOutputPrecedenceNone"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1494070-deprecated-constants-used-with-k"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1494070-deprecated-constants-used-with-k"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
