{
  "abstract": [
    {
      "text": "These read-only properties disclose the capabilities of the codec and remain the same for all instances of the codec.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-codec"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494121-global-codec-properties"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Global Codec Properties"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These properties are used with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecGetProperty(_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The values of these properties are independent of the codec’s internal state and cannot be changed. They can be read at any time the codec is open.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494050-audio-codec-delay-modes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494050-audio-codec-delay-modes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Codec Delay Modes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1494050-audio-codec-delay-modes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494068-audio-codec-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494068-audio-codec-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Codec Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1494068-audio-codec-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494074-audio-codec-routine-selectors": {
      "abstract": [
        {
          "text": "Selectors used by the Component Manager to call routines implemented by the codec and exposed to developers through the Audio Codec Services API. These selectors are for use by codec developers; if you are calling Audio Codec Services functions, you don’t need to use these constants.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494074-audio-codec-routine-selectors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Codec Routine Selectors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1494074-audio-codec-routine-selectors"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494076-audio-codec-errors": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494076-audio-codec-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Codec Errors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1494076-audio-codec-errors"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494094-dynamic-range-control-modes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494094-dynamic-range-control-modes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dynamic Range Control Modes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1494094-dynamic-range-control-modes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494111-instance-codec-properties": {
      "abstract": [
        {
          "text": "Properties that can be set or read on an instance of the audio codec.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494111-instance-codec-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Instance Codec Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1494111-instance-codec-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494116-program-target-levels": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494116-program-target-levels",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Program Target Levels",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1494116-program-target-levels"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494122-output-status-constants": {
      "abstract": [
        {
          "text": "Status values returned from the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecProduceOutputPackets(_:_:_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494122-output-status-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Output Status Constants",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1494122-output-status-constants"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494127-audio-codec-delays": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494127-audio-codec-delays",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Codec Delays",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1494127-audio-codec-delays"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494130-audio-codec-quality-constants": {
      "abstract": [
        {
          "text": "Sound quality settings to be used with the property ",
          "type": "text"
        },
        {
          "code": "kAudioCodecPropertyQualitySetting",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494130-audio-codec-quality-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Codec Quality Constants",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1494130-audio-codec-quality-constants"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494144-bit-rate-control-mode-constants": {
      "abstract": [
        {
          "text": "Bit rate control modes to be used with ",
          "type": "text"
        },
        {
          "code": "kAudioCodecPropertyBitRateControlMode",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494144-bit-rate-control-mode-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Bit Rate Control Mode Constants",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1494144-bit-rate-control-mode-constants"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494154-audio-codec-priming-method-const": {
      "abstract": [
        {
          "text": "Values used with ",
          "type": "text"
        },
        {
          "code": "kAudioCodecPropertyPrimeMethod",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494154-audio-codec-priming-method-const",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Codec Priming Method Constants",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1494154-audio-codec-priming-method-const"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecGetProperty(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Retrieves the value of a codec property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioCodecGetProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodec",
          "text": "AudioCodec"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecGetProperty(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioCodecGetProperty"
        }
      ],
      "role": "symbol",
      "title": "AudioCodecGetProperty(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocodecgetproperty(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecProduceOutputPackets(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Retrieves output data from a codec.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioCodecProduceOutputPackets"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodec",
          "text": "AudioCodec"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioStreamPacketDescription",
          "text": "AudioStreamPacketDescription"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecProduceOutputPackets(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioCodecProduceOutputPackets"
        }
      ],
      "role": "symbol",
      "title": "AudioCodecProduceOutputPackets(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocodecproduceoutputpackets(_:_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-codec": {
      "abstract": [
        {
          "text": "Translate audio data from one format to another.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-codec",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Codec",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-codec"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyFormatCFString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyFormatCFString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyFormatCFString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyFormatCFString"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyFormatCFString",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyformatcfstring"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyManufacturerCFString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyManufacturerCFString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyManufacturerCFString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyManufacturerCFString"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyManufacturerCFString",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertymanufacturercfstring"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyNameCFString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyNameCFString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyNameCFString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyNameCFString"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyNameCFString",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertynamecfstring"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494122-output-status-constants",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494116-program-target-levels",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494094-dynamic-range-control-modes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494144-bit-rate-control-mode-constants",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494111-instance-codec-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494154-audio-codec-priming-method-const",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494130-audio-codec-quality-constants",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494074-audio-codec-routine-selectors",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494127-audio-codec-delays",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494050-audio-codec-delay-modes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494068-audio-codec-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494076-audio-codec-errors"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyFormatCFString",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyManufacturerCFString",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyNameCFString"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyFormatCFString",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyManufacturerCFString",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyNameCFString"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494122-output-status-constants",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494116-program-target-levels",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494094-dynamic-range-control-modes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494144-bit-rate-control-mode-constants",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494111-instance-codec-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494154-audio-codec-priming-method-const",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494130-audio-codec-quality-constants",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494074-audio-codec-routine-selectors",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494127-audio-codec-delays",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494050-audio-codec-delay-modes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494068-audio-codec-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494076-audio-codec-errors"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecGetProperty(_:_:_:_:)/title",
          "value": "AudioCodecGetProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecGetProperty(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecGetProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyManufacturerCFString/title",
          "value": "kAudioCodecPropertyManufacturerCFString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyManufacturerCFString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyManufacturerCFString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyNameCFString/title",
          "value": "kAudioCodecPropertyNameCFString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyNameCFString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyNameCFString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyFormatCFString/title",
          "value": "kAudioCodecPropertyFormatCFString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyFormatCFString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyFormatCFString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecProduceOutputPackets(_:_:_:_:_:_:)/title",
          "value": "AudioCodecProduceOutputPackets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecProduceOutputPackets(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecProduceOutputPackets"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1494121-global-codec-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1494121-global-codec-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
