{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-codec"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494068-audio-codec-properties"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio Codec Properties"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494050-audio-codec-delay-modes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494050-audio-codec-delay-modes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Codec Delay Modes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1494050-audio-codec-delay-modes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494074-audio-codec-routine-selectors": {
      "abstract": [
        {
          "text": "Selectors used by the Component Manager to call routines implemented by the codec and exposed to developers through the Audio Codec Services API. These selectors are for use by codec developers; if you are calling Audio Codec Services functions, you don’t need to use these constants.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494074-audio-codec-routine-selectors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Codec Routine Selectors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1494074-audio-codec-routine-selectors"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494076-audio-codec-errors": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494076-audio-codec-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Codec Errors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1494076-audio-codec-errors"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494094-dynamic-range-control-modes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494094-dynamic-range-control-modes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dynamic Range Control Modes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1494094-dynamic-range-control-modes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494111-instance-codec-properties": {
      "abstract": [
        {
          "text": "Properties that can be set or read on an instance of the audio codec.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494111-instance-codec-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Instance Codec Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1494111-instance-codec-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494116-program-target-levels": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494116-program-target-levels",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Program Target Levels",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1494116-program-target-levels"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494121-global-codec-properties": {
      "abstract": [
        {
          "text": "These read-only properties disclose the capabilities of the codec and remain the same for all instances of the codec.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494121-global-codec-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Global Codec Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1494121-global-codec-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494122-output-status-constants": {
      "abstract": [
        {
          "text": "Status values returned from the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecProduceOutputPackets(_:_:_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494122-output-status-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Output Status Constants",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1494122-output-status-constants"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494127-audio-codec-delays": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494127-audio-codec-delays",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Codec Delays",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1494127-audio-codec-delays"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494130-audio-codec-quality-constants": {
      "abstract": [
        {
          "text": "Sound quality settings to be used with the property ",
          "type": "text"
        },
        {
          "code": "kAudioCodecPropertyQualitySetting",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494130-audio-codec-quality-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Codec Quality Constants",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1494130-audio-codec-quality-constants"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494144-bit-rate-control-mode-constants": {
      "abstract": [
        {
          "text": "Bit rate control modes to be used with ",
          "type": "text"
        },
        {
          "code": "kAudioCodecPropertyBitRateControlMode",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494144-bit-rate-control-mode-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Bit Rate Control Mode Constants",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1494144-bit-rate-control-mode-constants"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494154-audio-codec-priming-method-const": {
      "abstract": [
        {
          "text": "Values used with ",
          "type": "text"
        },
        {
          "code": "kAudioCodecPropertyPrimeMethod",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494154-audio-codec-priming-method-const",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Codec Priming Method Constants",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1494154-audio-codec-priming-method-const"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecProduceOutputPackets(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Retrieves output data from a codec.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioCodecProduceOutputPackets"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodec",
          "text": "AudioCodec"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioStreamPacketDescription",
          "text": "AudioStreamPacketDescription"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecProduceOutputPackets(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioCodecProduceOutputPackets"
        }
      ],
      "role": "symbol",
      "title": "AudioCodecProduceOutputPackets(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocodecproduceoutputpackets(_:_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-codec": {
      "abstract": [
        {
          "text": "Translate audio data from one format to another.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-codec",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Codec",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-codec"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableBitRateRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableBitRateRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableBitRateRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableBitRateRange"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyAvailableBitRateRange",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyavailablebitraterange"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableInputChannelLayoutTags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableInputChannelLayoutTags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableInputChannelLayoutTags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableInputChannelLayoutTags"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyAvailableInputChannelLayoutTags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyavailableinputchannellayouttags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableInputSampleRates": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableInputSampleRates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableInputSampleRates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableInputSampleRates"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyAvailableInputSampleRates",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyavailableinputsamplerates"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableNumberChannels": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableNumberChannels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableNumberChannels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableNumberChannels"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyAvailableNumberChannels",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyavailablenumberchannels"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableOutputChannelLayoutTags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableOutputChannelLayoutTags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableOutputChannelLayoutTags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableOutputChannelLayoutTags"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyAvailableOutputChannelLayoutTags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyavailableoutputchannellayouttags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableOutputSampleRates": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableOutputSampleRates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableOutputSampleRates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableOutputSampleRates"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyAvailableOutputSampleRates",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyavailableoutputsamplerates"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyDoesSampleRateConversion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyDoesSampleRateConversion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyDoesSampleRateConversion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyDoesSampleRateConversion"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyDoesSampleRateConversion",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertydoessamplerateconversion"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyFormatInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyFormatInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyFormatInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyFormatInfo"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyFormatInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyformatinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyInputFormatsForOutputFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyInputFormatsForOutputFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyInputFormatsForOutputFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyInputFormatsForOutputFormat"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyInputFormatsForOutputFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyinputformatsforoutputformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyMinimumNumberInputPackets": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyMinimumNumberInputPackets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyMinimumNumberInputPackets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyMinimumNumberInputPackets"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyMinimumNumberInputPackets",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyminimumnumberinputpackets"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyMinimumNumberOutputPackets": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyMinimumNumberOutputPackets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyMinimumNumberOutputPackets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyMinimumNumberOutputPackets"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyMinimumNumberOutputPackets",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyminimumnumberoutputpackets"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyOutputFormatsForInputFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyOutputFormatsForInputFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyOutputFormatsForInputFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyOutputFormatsForInputFormat"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyOutputFormatsForInputFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyoutputformatsforinputformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertySupportedInputFormats": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertySupportedInputFormats"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertySupportedInputFormats",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertySupportedInputFormats"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertySupportedInputFormats",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertysupportedinputformats"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertySupportedOutputFormats": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertySupportedOutputFormats"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertySupportedOutputFormats",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertySupportedOutputFormats"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertySupportedOutputFormats",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertysupportedoutputformats"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494122-output-status-constants",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494116-program-target-levels",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494094-dynamic-range-control-modes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494144-bit-rate-control-mode-constants",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494121-global-codec-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494111-instance-codec-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494154-audio-codec-priming-method-const",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494130-audio-codec-quality-constants",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494074-audio-codec-routine-selectors",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494127-audio-codec-delays",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494050-audio-codec-delay-modes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494076-audio-codec-errors"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableBitRateRange",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableInputChannelLayoutTags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableInputSampleRates",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableNumberChannels",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableOutputChannelLayoutTags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableOutputSampleRates",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyDoesSampleRateConversion",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyFormatInfo",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyInputFormatsForOutputFormat",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyMinimumNumberInputPackets",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyMinimumNumberOutputPackets",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyOutputFormatsForInputFormat",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertySupportedInputFormats",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertySupportedOutputFormats"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableBitRateRange",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableInputChannelLayoutTags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableInputSampleRates",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableNumberChannels",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableOutputChannelLayoutTags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableOutputSampleRates",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyDoesSampleRateConversion",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyFormatInfo",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyInputFormatsForOutputFormat",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyMinimumNumberInputPackets",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyMinimumNumberOutputPackets",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyOutputFormatsForInputFormat",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertySupportedInputFormats",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertySupportedOutputFormats"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494122-output-status-constants",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494116-program-target-levels",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494094-dynamic-range-control-modes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494144-bit-rate-control-mode-constants",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494121-global-codec-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494111-instance-codec-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494154-audio-codec-priming-method-const",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494130-audio-codec-quality-constants",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494074-audio-codec-routine-selectors",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494127-audio-codec-delays",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494050-audio-codec-delay-modes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494076-audio-codec-errors"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableBitRateRange/title",
          "value": "kAudioCodecPropertyAvailableBitRateRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableBitRateRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyAvailableBitRateRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableInputSampleRates/title",
          "value": "kAudioCodecPropertyAvailableInputSampleRates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableInputSampleRates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyAvailableInputSampleRates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableOutputChannelLayoutTags/title",
          "value": "kAudioCodecPropertyAvailableOutputChannelLayoutTags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableOutputChannelLayoutTags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyAvailableOutputChannelLayoutTags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertySupportedInputFormats/title",
          "value": "kAudioCodecPropertySupportedInputFormats"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertySupportedInputFormats/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertySupportedInputFormats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecProduceOutputPackets(_:_:_:_:_:_:)/title",
          "value": "AudioCodecProduceOutputPackets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecProduceOutputPackets(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecProduceOutputPackets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertySupportedOutputFormats/title",
          "value": "kAudioCodecPropertySupportedOutputFormats"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertySupportedOutputFormats/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertySupportedOutputFormats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyInputFormatsForOutputFormat/title",
          "value": "kAudioCodecPropertyInputFormatsForOutputFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyInputFormatsForOutputFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyInputFormatsForOutputFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableNumberChannels/title",
          "value": "kAudioCodecPropertyAvailableNumberChannels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableNumberChannels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyAvailableNumberChannels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyDoesSampleRateConversion/title",
          "value": "kAudioCodecPropertyDoesSampleRateConversion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyDoesSampleRateConversion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyDoesSampleRateConversion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyMinimumNumberInputPackets/title",
          "value": "kAudioCodecPropertyMinimumNumberInputPackets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyMinimumNumberInputPackets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyMinimumNumberInputPackets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyMinimumNumberOutputPackets/title",
          "value": "kAudioCodecPropertyMinimumNumberOutputPackets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyMinimumNumberOutputPackets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyMinimumNumberOutputPackets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyFormatInfo/title",
          "value": "kAudioCodecPropertyFormatInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyFormatInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyFormatInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableInputChannelLayoutTags/title",
          "value": "kAudioCodecPropertyAvailableInputChannelLayoutTags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableInputChannelLayoutTags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyAvailableInputChannelLayoutTags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableOutputSampleRates/title",
          "value": "kAudioCodecPropertyAvailableOutputSampleRates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableOutputSampleRates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyAvailableOutputSampleRates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyOutputFormatsForInputFormat/title",
          "value": "kAudioCodecPropertyOutputFormatsForInputFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyOutputFormatsForInputFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyOutputFormatsForInputFormat"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1494068-audio-codec-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1494068-audio-codec-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
