{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/deprecated-symbols"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494107-deprecated-audio-codec-propertie"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Deprecated Audio Codec Properties"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533960-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533960-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1533960-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534019-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534019-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534019-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534063-3d_mixer_audio_unit_properties": {
      "abstract": [
        {
          "text": "Properties for the Apple 3D Mixer audio unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534063-3d_mixer_audio_unit_properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "3D Mixer Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534063-3d_mixer_audio_unit_properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534074-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534074-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534074-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534089-music-device-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534089-music-device-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Music Device Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534089-music-device-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534112-audio-unit-attenuation-propertie": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534112-audio-unit-attenuation-propertie",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Attenuation Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534112-audio-unit-attenuation-propertie"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534225-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534225-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534225-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1537630-audio-graph-errors": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1537630-audio-graph-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Graph Errors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1537630-audio-graph-errors"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584141-audio-unit-instrument-errors": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584141-audio-unit-instrument-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Instrument Errors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584141-audio-unit-instrument-errors"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618426-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618426-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1618426-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618742-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618742-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1618742-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619479-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619479-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1619479-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619504-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619504-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1619504-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621044-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621044-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1621044-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1624333-audio-converter-property-id": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1624333-audio-converter-property-id",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Converter Property ID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1624333-audio-converter-property-id"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/deprecated-symbols": {
      "abstract": [
        {
          "text": "Review unsupported symbols and their replacements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/audiotoolbox/deprecated-symbols"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecBitRateFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecBitRateFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecBitRateFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecBitRateFormat"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecBitRateFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecbitrateformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecDoesSampleRateConversion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecDoesSampleRateConversion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecDoesSampleRateConversion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecDoesSampleRateConversion"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecDoesSampleRateConversion",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecdoessamplerateconversion"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecExtendFrequencies": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecExtendFrequencies"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecExtendFrequencies",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecExtendFrequencies"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecExtendFrequencies",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecextendfrequencies"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecInputFormatsForOutputFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecInputFormatsForOutputFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecInputFormatsForOutputFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecInputFormatsForOutputFormat"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecInputFormatsForOutputFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecinputformatsforoutputformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecOutputFormatsForInputFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecOutputFormatsForInputFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecOutputFormatsForInputFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecOutputFormatsForInputFormat"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecOutputFormatsForInputFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecoutputformatsforinputformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecOutputPrecedence": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecOutputPrecedence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecOutputPrecedence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecOutputPrecedence"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecOutputPrecedence",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecoutputprecedence"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableBitRates": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableBitRates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableBitRates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableBitRates"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyAvailableBitRates",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyavailablebitrates"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableInputChannelLayouts": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableInputChannelLayouts"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableInputChannelLayouts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableInputChannelLayouts"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyAvailableInputChannelLayouts",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyavailableinputchannellayouts"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableOutputChannelLayouts": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableOutputChannelLayouts"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableOutputChannelLayouts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableOutputChannelLayouts"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyAvailableOutputChannelLayouts",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyavailableoutputchannellayouts"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyInputChannelLayout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyInputChannelLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyInputChannelLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyInputChannelLayout"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyInputChannelLayout",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyinputchannellayout"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyOutputChannelLayout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyOutputChannelLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyOutputChannelLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyOutputChannelLayout"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyOutputChannelLayout",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyoutputchannellayout"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyRequiresPacketDescription": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyRequiresPacketDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyRequiresPacketDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyRequiresPacketDescription"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyRequiresPacketDescription",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyrequirespacketdescription"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyZeroFramesPadded": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyZeroFramesPadded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyZeroFramesPadded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyZeroFramesPadded"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyZeroFramesPadded",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyzeroframespadded"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecUseRecommendedSampleRate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecUseRecommendedSampleRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecUseRecommendedSampleRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecUseRecommendedSampleRate"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecUseRecommendedSampleRate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecuserecommendedsamplerate"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534112-audio-unit-attenuation-propertie",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584141-audio-unit-instrument-errors",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534019-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534074-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1537630-audio-graph-errors",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1624333-audio-converter-property-id",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621044-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618426-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618742-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619479-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619504-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533960-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534225-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534089-music-device-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534063-3d_mixer_audio_unit_properties"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecBitRateFormat",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecDoesSampleRateConversion",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecExtendFrequencies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecInputFormatsForOutputFormat",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecOutputFormatsForInputFormat",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecOutputPrecedence",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableBitRates",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableInputChannelLayouts",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableOutputChannelLayouts",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyInputChannelLayout",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyOutputChannelLayout",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyRequiresPacketDescription",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyZeroFramesPadded",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecUseRecommendedSampleRate"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecBitRateFormat",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecDoesSampleRateConversion",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecExtendFrequencies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecInputFormatsForOutputFormat",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecOutputFormatsForInputFormat",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecOutputPrecedence",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableBitRates",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableInputChannelLayouts",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableOutputChannelLayouts",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyInputChannelLayout",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyOutputChannelLayout",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyRequiresPacketDescription",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyZeroFramesPadded",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecUseRecommendedSampleRate"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534112-audio-unit-attenuation-propertie",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584141-audio-unit-instrument-errors",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534019-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534074-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1537630-audio-graph-errors",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1624333-audio-converter-property-id",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621044-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618426-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618742-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619479-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619504-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533960-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534225-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534089-music-device-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534063-3d_mixer_audio_unit_properties"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecExtendFrequencies/title",
          "value": "kAudioCodecExtendFrequencies"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecExtendFrequencies/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecExtendFrequencies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableInputChannelLayouts/title",
          "value": "kAudioCodecPropertyAvailableInputChannelLayouts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableInputChannelLayouts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyAvailableInputChannelLayouts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyRequiresPacketDescription/title",
          "value": "kAudioCodecPropertyRequiresPacketDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyRequiresPacketDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyRequiresPacketDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecUseRecommendedSampleRate/title",
          "value": "kAudioCodecUseRecommendedSampleRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecUseRecommendedSampleRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecUseRecommendedSampleRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecOutputFormatsForInputFormat/title",
          "value": "kAudioCodecOutputFormatsForInputFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecOutputFormatsForInputFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecOutputFormatsForInputFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyInputChannelLayout/title",
          "value": "kAudioCodecPropertyInputChannelLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyInputChannelLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyInputChannelLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecDoesSampleRateConversion/title",
          "value": "kAudioCodecDoesSampleRateConversion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecDoesSampleRateConversion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecDoesSampleRateConversion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecInputFormatsForOutputFormat/title",
          "value": "kAudioCodecInputFormatsForOutputFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecInputFormatsForOutputFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecInputFormatsForOutputFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecOutputPrecedence/title",
          "value": "kAudioCodecOutputPrecedence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecOutputPrecedence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecOutputPrecedence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyZeroFramesPadded/title",
          "value": "kAudioCodecPropertyZeroFramesPadded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyZeroFramesPadded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyZeroFramesPadded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableBitRates/title",
          "value": "kAudioCodecPropertyAvailableBitRates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableBitRates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyAvailableBitRates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecBitRateFormat/title",
          "value": "kAudioCodecBitRateFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecBitRateFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecBitRateFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableOutputChannelLayouts/title",
          "value": "kAudioCodecPropertyAvailableOutputChannelLayouts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableOutputChannelLayouts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyAvailableOutputChannelLayouts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyOutputChannelLayout/title",
          "value": "kAudioCodecPropertyOutputChannelLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyOutputChannelLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyOutputChannelLayout"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1494107-deprecated-audio-codec-propertie"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1494107-deprecated-audio-codec-propertie"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
