{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/music-player"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1515479-music-event-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Music Event Types"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1473469-music-device-selectors": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1473469-music-device-selectors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Music Device Selectors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1473469-music-device-selectors"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1473494-music-note-events": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1473494-music-note-events",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Music Note Events",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1473494-music-note-events"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1515446-music-extended-control-event-typ": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1515446-music-extended-control-event-typ",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Music Extended Control Event Type",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1515446-music-extended-control-event-typ"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1515456-music-track-properties": {
      "abstract": [
        {
          "text": "Properties for music tracks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1515456-music-track-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Music Track Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1515456-music-track-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1515472-music-player-errors": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1515472-music-player-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Music Player Errors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1515472-music-player-errors"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533930-music-device-generic-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533930-music-device-generic-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Music Device Generic Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1533930-music-device-generic-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533931-music-device-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533931-music-device-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Music Device Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1533931-music-device-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533963-music-device-unit-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533963-music-device-unit-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Music Device Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1533963-music-device-unit-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533978-music-device-sample-frame-mask": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533978-music-device-sample-frame-mask",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Music Device Sample Frame Mask",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1533978-music-device-sample-frame-mask"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534202-instrument-types": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534202-instrument-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Instrument Types",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534202-instrument-types"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619498-music-instrument-audio-unit-subt": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619498-music-instrument-audio-unit-subt",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Music Instrument Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1619498-music-instrument-audio-unit-subt"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreate(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a MIDI file from the events in a music sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceFileCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceFileTypeID",
          "text": "MusicSequenceFileTypeID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceFileFlags",
          "text": "MusicSequenceFileFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreate(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceFileCreate"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceFileCreate(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencefilecreate(_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreateData(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a data object containing the events from a music sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceFileCreateData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceFileTypeID",
          "text": "MusicSequenceFileTypeID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceFileFlags",
          "text": "MusicSequenceFileFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": ">?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreateData(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceFileCreateData"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceFileCreateData(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencefilecreatedata(_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileFlags": {
      "abstract": [
        {
          "text": "Flags that configure the behavior of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreate(_:_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreateData(_:_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceFileFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceFileFlags"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceFileFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencefileflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileLoad(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Loads data into a music sequence from a URL reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceFileLoad"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceFileTypeID",
          "text": "MusicSequenceFileTypeID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceLoadFlags",
          "text": "MusicSequenceLoadFlags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileLoad(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceFileLoad"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceFileLoad(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencefileload(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileLoadData(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Load data into a music sequence from a data reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceFileLoadData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceFileTypeID",
          "text": "MusicSequenceFileTypeID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceLoadFlags",
          "text": "MusicSequenceLoadFlags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileLoadData(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceFileLoadData"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceFileLoadData(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencefileloaddata(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileTypeID": {
      "abstract": [
        {
          "text": "The various types of files that can be parsed by a music sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceFileTypeID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileTypeID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceFileTypeID"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceFileTypeID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencefiletypeid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceLoadFlags": {
      "abstract": [
        {
          "text": "Flags used to configure the behavior of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileLoad(_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileLoadData(_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceLoadFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceLoadFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceLoadFlags"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceLoadFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequenceloadflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceType": {
      "abstract": [
        {
          "text": "The various types of music sequences.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceType"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceType"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencetype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_AUPreset": {
      "abstract": [
        {
          "text": "An event containing an audio unit user preset dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMusicEventType_AUPreset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_AUPreset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMusicEventType_AUPreset"
        }
      ],
      "role": "symbol",
      "title": "kMusicEventType_AUPreset",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmusiceventtype_aupreset"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_ExtendedNote": {
      "abstract": [
        {
          "text": "A non-MIDI music event with variable number of parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMusicEventType_ExtendedNote"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_ExtendedNote",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMusicEventType_ExtendedNote"
        }
      ],
      "role": "symbol",
      "title": "kMusicEventType_ExtendedNote",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmusiceventtype_extendednote"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_ExtendedTempo": {
      "abstract": [
        {
          "text": "An event that signals a change in tempo, in beats-per-minute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMusicEventType_ExtendedTempo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_ExtendedTempo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMusicEventType_ExtendedTempo"
        }
      ],
      "role": "symbol",
      "title": "kMusicEventType_ExtendedTempo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmusiceventtype_extendedtempo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_MIDIChannelMessage": {
      "abstract": [
        {
          "text": "A MIDI channel message, other than note control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMusicEventType_MIDIChannelMessage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_MIDIChannelMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMusicEventType_MIDIChannelMessage"
        }
      ],
      "role": "symbol",
      "title": "kMusicEventType_MIDIChannelMessage",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmusiceventtype_midichannelmessage"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_MIDINoteMessage": {
      "abstract": [
        {
          "text": "A MIDI note-on message, including duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMusicEventType_MIDINoteMessage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_MIDINoteMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMusicEventType_MIDINoteMessage"
        }
      ],
      "role": "symbol",
      "title": "kMusicEventType_MIDINoteMessage",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmusiceventtype_midinotemessage"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_MIDIRawData": {
      "abstract": [
        {
          "text": "MIDI system-exclusive data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMusicEventType_MIDIRawData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_MIDIRawData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMusicEventType_MIDIRawData"
        }
      ],
      "role": "symbol",
      "title": "kMusicEventType_MIDIRawData",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmusiceventtype_midirawdata"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_Meta": {
      "abstract": [
        {
          "text": "A standard MIDI file metaevent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMusicEventType_Meta"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_Meta",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMusicEventType_Meta"
        }
      ],
      "role": "symbol",
      "title": "kMusicEventType_Meta",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmusiceventtype_meta"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_NULL": {
      "abstract": [
        {
          "text": "A null music event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMusicEventType_NULL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_NULL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMusicEventType_NULL"
        }
      ],
      "role": "symbol",
      "title": "kMusicEventType_NULL",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmusiceventtype_null"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_Parameter": {
      "abstract": [
        {
          "text": "An audio unit parameter event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMusicEventType_Parameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_Parameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMusicEventType_Parameter"
        }
      ],
      "role": "symbol",
      "title": "kMusicEventType_Parameter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmusiceventtype_parameter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_User": {
      "abstract": [
        {
          "text": "User-defined data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMusicEventType_User"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_User",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMusicEventType_User"
        }
      ],
      "role": "symbol",
      "title": "kMusicEventType_User",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmusiceventtype_user"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/music-player": {
      "abstract": [
        {
          "text": "Create and play a sequence of tracks, and manage aspects of playback in response to standard events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/music-player",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Music Player",
      "type": "topic",
      "url": "/documentation/audiotoolbox/music-player"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619498-music-instrument-audio-unit-subt",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1515456-music-track-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileTypeID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceLoadFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1515446-music-extended-control-event-typ",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1515472-music-player-errors",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1473494-music-note-events",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1473469-music-device-selectors",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533931-music-device-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533978-music-device-sample-frame-mask",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533963-music-device-unit-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534202-instrument-types",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533930-music-device-generic-properties"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_AUPreset",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_ExtendedNote",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_ExtendedTempo",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_MIDIChannelMessage",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_MIDINoteMessage",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_MIDIRawData",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_Meta",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_NULL",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_Parameter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_User"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_AUPreset",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_ExtendedNote",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_ExtendedTempo",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_MIDIChannelMessage",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_MIDINoteMessage",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_MIDIRawData",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_Meta",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_NULL",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_Parameter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_User"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619498-music-instrument-audio-unit-subt",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1515456-music-track-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileFlags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileTypeID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceLoadFlags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1515446-music-extended-control-event-typ",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1515472-music-player-errors",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1473494-music-note-events",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1473469-music-device-selectors",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533931-music-device-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533978-music-device-sample-frame-mask",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533963-music-device-unit-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534202-instrument-types",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533930-music-device-generic-properties"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_MIDIChannelMessage/title",
          "value": "kMusicEventType_MIDIChannelMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_MIDIChannelMessage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMusicEventType_MIDIChannelMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_ExtendedTempo/title",
          "value": "kMusicEventType_ExtendedTempo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_ExtendedTempo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMusicEventType_ExtendedTempo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileFlags/title",
          "value": "MusicSequenceFileFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceFileFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceFileFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_Meta/title",
          "value": "kMusicEventType_Meta"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_Meta/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMusicEventType_Meta"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileCreateData(_:_:_:_:_:)/title",
          "value": "MusicSequenceFileCreateData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileCreateData(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceFileCreateData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceType/title",
          "value": "MusicSequenceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_ExtendedNote/title",
          "value": "kMusicEventType_ExtendedNote"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_ExtendedNote/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMusicEventType_ExtendedNote"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileLoadData(_:_:_:_:)/title",
          "value": "MusicSequenceFileLoadData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileLoadData(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceFileLoadData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_MIDINoteMessage/title",
          "value": "kMusicEventType_MIDINoteMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_MIDINoteMessage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMusicEventType_MIDINoteMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileLoad(_:_:_:_:)/title",
          "value": "MusicSequenceFileLoad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileLoad(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceFileLoad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_NULL/title",
          "value": "kMusicEventType_NULL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_NULL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMusicEventType_NULL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceLoadFlags/title",
          "value": "MusicSequenceLoadFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceLoadFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceLoadFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceLoadFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceLoadFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileTypeID/title",
          "value": "MusicSequenceFileTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileTypeID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceFileTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileTypeID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceFileTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_MIDIRawData/title",
          "value": "kMusicEventType_MIDIRawData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_MIDIRawData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMusicEventType_MIDIRawData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_AUPreset/title",
          "value": "kMusicEventType_AUPreset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_AUPreset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMusicEventType_AUPreset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileCreate(_:_:_:_:_:)/title",
          "value": "MusicSequenceFileCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileCreate(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceFileCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_User/title",
          "value": "kMusicEventType_User"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_User/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMusicEventType_User"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_Parameter/title",
          "value": "kMusicEventType_Parameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_Parameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMusicEventType_Parameter"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1515479-music-event-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1515479-music-event-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
