{"identifier":{"url":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533941-music-effect-and-instrument-unit","interfaceLanguage":"swift"},"sections":[],"metadata":{"roleHeading":"API Collection","modules":[{"name":"Audio Toolbox"}],"role":"collectionGroup","title":"Music Effect and Instrument Unit Properties"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.audiotoolbox/documentation/AudioToolbox","doc://com.apple.audiotoolbox/documentation/AudioToolbox/music-player"]]},"topicSections":[{"title":"Constants","anchor":"Constants","identifiers":["doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_AddParameterMIDIMapping","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_AllParameterMIDIMappings","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_HotMapParameterMIDIMapping","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_RemoveParameterMIDIMapping"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/audiotoolbox/1533941-music-effect-and-instrument-unit"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/audiotoolbox/1533941-music-effect-and-instrument-unit"]}],"seeAlsoSections":[{"title":"Enumerations","anchor":"Enumerations","generated":true,"identifiers":["doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619498-music-instrument-audio-unit-subt","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1515456-music-track-properties","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileFlags","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileTypeID","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceLoadFlags","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceType","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1515446-music-extended-control-event-typ","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1515472-music-player-errors","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1515479-music-event-types","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1473494-music-note-events","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1473469-music-device-selectors","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533931-music-device-properties","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533978-music-device-sample-frame-mask","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533963-music-device-unit-properties","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534202-instrument-types"]}],"references":{"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534202-instrument-types":{"type":"topic","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534202-instrument-types","title":"Instrument Types","abstract":[],"role":"collectionGroup","kind":"article","url":"/documentation/audiotoolbox/1534202-instrument-types"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileTypeID":{"role":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileTypeID","kind":"symbol","abstract":[{"type":"text","text":"The various types of files that can be parsed by a music sequence."}],"navigatorTitle":[{"kind":"identifier","text":"MusicSequenceFileTypeID"}],"url":"/documentation/audiotoolbox/musicsequencefiletypeid","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MusicSequenceFileTypeID"}],"title":"MusicSequenceFileTypeID","type":"topic"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceType":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MusicSequenceType","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The various types of music sequences."}],"kind":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceType","url":"/documentation/audiotoolbox/musicsequencetype","title":"MusicSequenceType","navigatorTitle":[{"text":"MusicSequenceType","kind":"identifier"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1515446-music-extended-control-event-typ":{"type":"topic","url":"/documentation/audiotoolbox/1515446-music-extended-control-event-typ","kind":"article","title":"Music Extended Control Event Type","role":"collectionGroup","abstract":[],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1515446-music-extended-control-event-typ"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533931-music-device-properties":{"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533931-music-device-properties","url":"/documentation/audiotoolbox/1533931-music-device-properties","type":"topic","abstract":[],"role":"collectionGroup","title":"Music Device Properties","kind":"article"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1515472-music-player-errors":{"type":"topic","url":"/documentation/audiotoolbox/1515472-music-player-errors","kind":"article","title":"Music Player Errors","role":"collectionGroup","abstract":[],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1515472-music-player-errors"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_AddParameterMIDIMapping":{"navigatorTitle":[{"text":"kAudioUnitProperty_AddParameterMIDIMapping","kind":"identifier"}],"role":"symbol","url":"/documentation/audiotoolbox/kaudiounitproperty_addparametermidimapping","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioUnitProperty_AddParameterMIDIMapping","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@AudioUnitPropertyID","text":"AudioUnitPropertyID","kind":"typeIdentifier"}],"title":"kAudioUnitProperty_AddParameterMIDIMapping","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_AddParameterMIDIMapping","kind":"symbol","abstract":[],"type":"topic"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1515456-music-track-properties":{"type":"topic","url":"/documentation/audiotoolbox/1515456-music-track-properties","kind":"article","title":"Music Track Properties","role":"collectionGroup","abstract":[{"type":"text","text":"Properties for music tracks."}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1515456-music-track-properties"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1473469-music-device-selectors":{"type":"topic","url":"/documentation/audiotoolbox/1473469-music-device-selectors","kind":"article","title":"Music Device Selectors","role":"collectionGroup","abstract":[],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1473469-music-device-selectors"},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","type":"topic","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","role":"overview"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreate(_:_:_:_:_:)":{"title":"MusicSequenceFileCreate(_:_:_:_:_:)","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreate(_:_:_:_:_:)","abstract":[{"text":"Creates a MIDI file from the events in a music sequence.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MusicSequenceFileCreate"}],"url":"/documentation/audiotoolbox/musicsequencefilecreate(_:_:_:_:_:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MusicSequenceFileCreate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@MusicSequence","text":"MusicSequence"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CFURLRef","text":"CFURL"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MusicSequenceFileTypeID","text":"MusicSequenceFileTypeID"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MusicSequenceFileFlags","text":"MusicSequenceFileFlags"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int16V","text":"Int16"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus","text":"OSStatus"}],"type":"topic"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileFlags":{"navigatorTitle":[{"kind":"identifier","text":"MusicSequenceFileFlags"}],"type":"topic","url":"/documentation/audiotoolbox/musicsequencefileflags","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MusicSequenceFileFlags"}],"kind":"symbol","title":"MusicSequenceFileFlags","role":"symbol","abstract":[{"type":"text","text":"Flags that configure the behavior of the "},{"type":"reference","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreate(_:_:_:_:_:)","isActive":true},{"type":"text","text":" and "},{"type":"reference","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreateData(_:_:_:_:_:)","isActive":true},{"type":"text","text":" functions."}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileFlags"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1515479-music-event-types":{"type":"topic","url":"/documentation/audiotoolbox/1515479-music-event-types","kind":"article","title":"Music Event Types","role":"collectionGroup","abstract":[],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1515479-music-event-types"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox":{"type":"topic","kind":"symbol","title":"Audio Toolbox","role":"collection","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox","abstract":[{"text":"Record or play audio, convert formats, parse audio streams, and configure your audio session.","type":"text"}],"url":"/documentation/audiotoolbox"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533963-music-device-unit-properties":{"type":"topic","url":"/documentation/audiotoolbox/1533963-music-device-unit-properties","kind":"article","title":"Music Device Unit Properties","role":"collectionGroup","abstract":[],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533963-music-device-unit-properties"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_AllParameterMIDIMappings":{"url":"/documentation/audiotoolbox/kaudiounitproperty_allparametermidimappings","abstract":[],"role":"symbol","type":"topic","title":"kAudioUnitProperty_AllParameterMIDIMappings","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_AllParameterMIDIMappings","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioUnitProperty_AllParameterMIDIMappings","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioUnitPropertyID","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioUnitPropertyID"}],"navigatorTitle":[{"text":"kAudioUnitProperty_AllParameterMIDIMappings","kind":"identifier"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_RemoveParameterMIDIMapping":{"url":"/documentation/audiotoolbox/kaudiounitproperty_removeparametermidimapping","abstract":[],"role":"symbol","type":"topic","title":"kAudioUnitProperty_RemoveParameterMIDIMapping","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_RemoveParameterMIDIMapping","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioUnitProperty_RemoveParameterMIDIMapping","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioUnitPropertyID","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioUnitPropertyID"}],"navigatorTitle":[{"text":"kAudioUnitProperty_RemoveParameterMIDIMapping","kind":"identifier"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/music-player":{"type":"topic","url":"/documentation/audiotoolbox/music-player","kind":"article","title":"Music Player","role":"collectionGroup","abstract":[{"text":"Create and play a sequence of tracks, and manage aspects of playback in response to standard events.","type":"text"}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/music-player"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1473494-music-note-events":{"type":"topic","url":"/documentation/audiotoolbox/1473494-music-note-events","kind":"article","title":"Music Note Events","role":"collectionGroup","abstract":[],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1473494-music-note-events"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileLoad(_:_:_:_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MusicSequenceFileLoad","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MusicSequence","preciseIdentifier":"c:@T@MusicSequence","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"CFURL","preciseIdentifier":"c:@T@CFURLRef","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"MusicSequenceFileTypeID","preciseIdentifier":"c:@E@MusicSequenceFileTypeID","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"MusicSequenceLoadFlags","preciseIdentifier":"c:@E@MusicSequenceLoadFlags","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"OSStatus","preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier"}],"abstract":[{"text":"Loads data into a music sequence from a URL reference.","type":"text"}],"title":"MusicSequenceFileLoad(_:_:_:_:)","kind":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileLoad(_:_:_:_:)","url":"/documentation/audiotoolbox/musicsequencefileload(_:_:_:_:)","role":"symbol","type":"topic","navigatorTitle":[{"text":"MusicSequenceFileLoad","kind":"identifier"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceLoadFlags":{"role":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceLoadFlags","kind":"symbol","abstract":[{"type":"text","text":"Flags used to configure the behavior of the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileLoad(_:_:_:_:)"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileLoadData(_:_:_:_:)"},{"type":"text","text":" functions."}],"navigatorTitle":[{"kind":"identifier","text":"MusicSequenceLoadFlags"}],"url":"/documentation/audiotoolbox/musicsequenceloadflags","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MusicSequenceLoadFlags"}],"title":"MusicSequenceLoadFlags","type":"topic"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533978-music-device-sample-frame-mask":{"title":"Music Device Sample Frame Mask","abstract":[],"type":"topic","role":"collectionGroup","url":"/documentation/audiotoolbox/1533978-music-device-sample-frame-mask","kind":"article","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533978-music-device-sample-frame-mask"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreateData(_:_:_:_:_:)":{"url":"/documentation/audiotoolbox/musicsequencefilecreatedata(_:_:_:_:_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MusicSequenceFileCreateData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MusicSequence","kind":"typeIdentifier","preciseIdentifier":"c:@T@MusicSequence"},{"text":", ","kind":"text"},{"text":"MusicSequenceFileTypeID","kind":"typeIdentifier","preciseIdentifier":"c:@E@MusicSequenceFileTypeID"},{"text":", ","kind":"text"},{"text":"MusicSequenceFileFlags","kind":"typeIdentifier","preciseIdentifier":"c:@E@MusicSequenceFileFlags"},{"text":", ","kind":"text"},{"text":"Int16","kind":"typeIdentifier","preciseIdentifier":"s:s5Int16V"},{"text":", ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"Unmanaged","kind":"typeIdentifier","preciseIdentifier":"s:s9UnmanagedV"},{"text":"<","kind":"text"},{"text":"CFData","kind":"typeIdentifier","preciseIdentifier":"c:@T@CFDataRef"},{"text":">?>) -> ","kind":"text"},{"text":"OSStatus","kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus"}],"role":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreateData(_:_:_:_:_:)","title":"MusicSequenceFileCreateData(_:_:_:_:_:)","navigatorTitle":[{"text":"MusicSequenceFileCreateData","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Creates a data object containing the events from a music sequence.","type":"text"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_HotMapParameterMIDIMapping":{"url":"/documentation/audiotoolbox/kaudiounitproperty_hotmapparametermidimapping","abstract":[],"role":"symbol","type":"topic","title":"kAudioUnitProperty_HotMapParameterMIDIMapping","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_HotMapParameterMIDIMapping","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioUnitProperty_HotMapParameterMIDIMapping","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioUnitPropertyID","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioUnitPropertyID"}],"navigatorTitle":[{"text":"kAudioUnitProperty_HotMapParameterMIDIMapping","kind":"identifier"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619498-music-instrument-audio-unit-subt":{"type":"topic","url":"/documentation/audiotoolbox/1619498-music-instrument-audio-unit-subt","kind":"article","title":"Music Instrument Audio Unit Subtypes","role":"collectionGroup","abstract":[],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619498-music-instrument-audio-unit-subt"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileLoadData(_:_:_:_:)":{"navigatorTitle":[{"text":"MusicSequenceFileLoadData","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileLoadData(_:_:_:_:)","abstract":[{"text":"Load data into a music sequence from a data reference.","type":"text"}],"url":"/documentation/audiotoolbox/musicsequencefileloaddata(_:_:_:_:)","role":"symbol","title":"MusicSequenceFileLoadData(_:_:_:_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MusicSequenceFileLoadData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MusicSequence","kind":"typeIdentifier","preciseIdentifier":"c:@T@MusicSequence"},{"text":", ","kind":"text"},{"text":"CFData","kind":"typeIdentifier","preciseIdentifier":"c:@T@CFDataRef"},{"text":", ","kind":"text"},{"text":"MusicSequenceFileTypeID","kind":"typeIdentifier","preciseIdentifier":"c:@E@MusicSequenceFileTypeID"},{"text":", ","kind":"text"},{"text":"MusicSequenceLoadFlags","kind":"typeIdentifier","preciseIdentifier":"c:@E@MusicSequenceLoadFlags"},{"text":") -> ","kind":"text"},{"text":"OSStatus","kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/topicSections","op":"replace","value":[{"anchor":"Constants","identifiers":["doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_AddParameterMIDIMapping","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_AllParameterMIDIMappings","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_HotMapParameterMIDIMapping","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_RemoveParameterMIDIMapping"],"title":"Constants"}]},{"path":"/seeAlsoSections","op":"replace","value":[{"title":"Enumerations","anchor":"Enumerations","generated":true,"identifiers":["doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619498-music-instrument-audio-unit-subt","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1515456-music-track-properties","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileFlags","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileTypeID","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceLoadFlags","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceType","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1515446-music-extended-control-event-typ","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1515472-music-player-errors","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1515479-music-event-types","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1473494-music-note-events","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1473469-music-device-selectors","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533931-music-device-properties","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533978-music-device-sample-frame-mask","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533963-music-device-unit-properties","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534202-instrument-types"]}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileTypeID/title","op":"replace","value":"MusicSequenceFileTypeID"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileTypeID/fragments","op":"replace","value":[{"text":"MusicSequenceFileTypeID","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileTypeID/navigatorTitle","op":"replace","value":[{"text":"MusicSequenceFileTypeID","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceType/title","op":"replace","value":"MusicSequenceType"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceType/fragments","op":"replace","value":[{"kind":"identifier","text":"MusicSequenceType"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceType/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MusicSequenceType"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_AddParameterMIDIMapping/title","op":"replace","value":"kAudioUnitProperty_AddParameterMIDIMapping"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_AddParameterMIDIMapping/fragments","op":"replace","value":[{"kind":"identifier","text":"kAudioUnitProperty_AddParameterMIDIMapping"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileCreate(_:_:_:_:_:)/title","op":"replace","value":"MusicSequenceFileCreate"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileCreate(_:_:_:_:_:)/fragments","op":"replace","value":[{"kind":"identifier","text":"MusicSequenceFileCreate"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileFlags/title","op":"replace","value":"MusicSequenceFileFlags"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileFlags/fragments","op":"replace","value":[{"text":"MusicSequenceFileFlags","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileFlags/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MusicSequenceFileFlags"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_AllParameterMIDIMappings/title","value":"kAudioUnitProperty_AllParameterMIDIMappings","op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_AllParameterMIDIMappings/fragments","value":[{"text":"kAudioUnitProperty_AllParameterMIDIMappings","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_RemoveParameterMIDIMapping/title","value":"kAudioUnitProperty_RemoveParameterMIDIMapping","op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_RemoveParameterMIDIMapping/fragments","value":[{"kind":"identifier","text":"kAudioUnitProperty_RemoveParameterMIDIMapping"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileLoad(_:_:_:_:)/title","value":"MusicSequenceFileLoad","op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileLoad(_:_:_:_:)/fragments","value":[{"kind":"identifier","text":"MusicSequenceFileLoad"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceLoadFlags/title","value":"MusicSequenceLoadFlags","op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceLoadFlags/fragments","value":[{"kind":"identifier","text":"MusicSequenceLoadFlags"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceLoadFlags/navigatorTitle","value":[{"kind":"identifier","text":"MusicSequenceLoadFlags"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileCreateData(_:_:_:_:_:)/title","value":"MusicSequenceFileCreateData","op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileCreateData(_:_:_:_:_:)/fragments","value":[{"text":"MusicSequenceFileCreateData","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_HotMapParameterMIDIMapping/title","value":"kAudioUnitProperty_HotMapParameterMIDIMapping","op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_HotMapParameterMIDIMapping/fragments","value":[{"kind":"identifier","text":"kAudioUnitProperty_HotMapParameterMIDIMapping"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileLoadData(_:_:_:_:)/title","value":"MusicSequenceFileLoadData","op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileLoadData(_:_:_:_:)/fragments","value":[{"text":"MusicSequenceFileLoadData","kind":"identifier"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}