{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534082-other-plug-in-formats"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Other Plug-In Formats"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534177-renderquality": {
      "abstract": [
        {
          "text": "Render quality settings for audio units.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534177-renderquality",
      "kind": "article",
      "role": "collectionGroup",
      "title": "RenderQuality",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534177-renderquality"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo": {
      "abstract": [
        {
          "text": "The time- and transport-related callback functions for an audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HostCallbackInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HostCallbackInfo"
        }
      ],
      "role": "symbol",
      "title": "HostCallbackInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/hostcallbackinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties": {
      "abstract": [
        {
          "text": "Obtain information about the built-in mixers, equalizers, filters, effects, and other Audio Unit app extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/general-audio-unit-properties": {
      "abstract": [
        {
          "text": "Properties that apply to any audio unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/general-audio-unit-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "General Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/general-audio-unit-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kOtherPluginFormat_AU": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOtherPluginFormat_AU"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kOtherPluginFormat_AU",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOtherPluginFormat_AU"
        }
      ],
      "role": "symbol",
      "title": "kOtherPluginFormat_AU",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kotherpluginformat_au"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kOtherPluginFormat_Undefined": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOtherPluginFormat_Undefined"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kOtherPluginFormat_Undefined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOtherPluginFormat_Undefined"
        }
      ],
      "role": "symbol",
      "title": "kOtherPluginFormat_Undefined",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kotherpluginformat_undefined"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kOtherPluginFormat_kMAS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOtherPluginFormat_kMAS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kOtherPluginFormat_kMAS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOtherPluginFormat_kMAS"
        }
      ],
      "role": "symbol",
      "title": "kOtherPluginFormat_kMAS",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kotherpluginformat_kmas"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kOtherPluginFormat_kVST": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOtherPluginFormat_kVST"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kOtherPluginFormat_kVST",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOtherPluginFormat_kVST"
        }
      ],
      "role": "symbol",
      "title": "kOtherPluginFormat_kVST",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kotherpluginformat_kvst"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "General",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534177-renderquality",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/general-audio-unit-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo"
      ],
      "title": "General"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kOtherPluginFormat_AU",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kOtherPluginFormat_Undefined",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kOtherPluginFormat_kMAS",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kOtherPluginFormat_kVST"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kOtherPluginFormat_AU",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kOtherPluginFormat_Undefined",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kOtherPluginFormat_kMAS",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kOtherPluginFormat_kVST"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "General",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534177-renderquality",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/general-audio-unit-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo"
              ],
              "title": "General"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kOtherPluginFormat_kMAS/title",
          "value": "kOtherPluginFormat_kMAS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kOtherPluginFormat_kMAS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOtherPluginFormat_kMAS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kOtherPluginFormat_AU/title",
          "value": "kOtherPluginFormat_AU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kOtherPluginFormat_AU/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOtherPluginFormat_AU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kOtherPluginFormat_Undefined/title",
          "value": "kOtherPluginFormat_Undefined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kOtherPluginFormat_Undefined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOtherPluginFormat_Undefined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kOtherPluginFormat_kVST/title",
          "value": "kOtherPluginFormat_kVST"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kOtherPluginFormat_kVST/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOtherPluginFormat_kVST"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallbackInfo/title",
          "value": "HostCallbackInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallbackInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HostCallbackInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallbackInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HostCallbackInfo"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1534082-other-plug-in-formats"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1534082-other-plug-in-formats"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
