{"kind":"article","topicSections":[{"title":"Constants","identifiers":["doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_InputSize","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_OutputSize","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_PreflightName","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_PreflightRequirements","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_StartOffset"],"anchor":"Constants"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.audiotoolbox/documentation/AudioToolbox","doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"Offline Audio Unit Properties","modules":[{"name":"Audio Toolbox"}],"roleHeading":"API Collection","role":"collectionGroup"},"abstract":[{"type":"text","text":"Properties for audio units that perform offline processing—that is, processing in a nonplayback, nonrealtime mode."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/audiotoolbox/1534054-offline_audio_unit_properties"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/audiotoolbox/1534054-offline_audio_unit_properties"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534054-offline_audio_unit_properties"},"seeAlsoSections":[{"generated":true,"title":"Enumerations","identifiers":["doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584142-audio_unit_types","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584148-audio-unit-output-subtypes","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389613-midi_audio_unit_parameters","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType"],"anchor":"Enumerations"}],"references":{"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584148-audio-unit-output-subtypes":{"role":"collectionGroup","type":"topic","abstract":[],"kind":"article","url":"/documentation/audiotoolbox/1584148-audio-unit-output-subtypes","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584148-audio-unit-output-subtypes","title":"Audio Unit Output Subtypes"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox":{"type":"topic","kind":"symbol","title":"Audio Toolbox","role":"collection","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox","abstract":[{"text":"Record or play audio, convert formats, parse audio streams, and configure your audio session.","type":"text"}],"url":"/documentation/audiotoolbox"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes":{"title":"Converter Audio Unit Subtypes","type":"topic","role":"collectionGroup","abstract":[{"type":"text","text":"Audio data format converter audio unit subtypes for audio units provided by Apple."}],"kind":"article","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes","url":"/documentation/audiotoolbox/1584145-converter_audio_unit_subtypes"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes":{"kind":"article","url":"/documentation/audiotoolbox/1619485-i-o-audio-unit-subtypes","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes","title":"I/O Audio Unit Subtypes","abstract":[],"type":"topic","role":"collectionGroup"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_InputSize":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioUnitOfflineProperty_InputSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioUnitPropertyID","preciseIdentifier":"c:@T@AudioUnitPropertyID"}],"url":"/documentation/audiotoolbox/kaudiounitofflineproperty_inputsize","role":"symbol","type":"topic","title":"kAudioUnitOfflineProperty_InputSize","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_InputSize","navigatorTitle":[{"kind":"identifier","text":"kAudioUnitOfflineProperty_InputSize"}],"abstract":[],"kind":"symbol"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_OutputSize":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kAudioUnitOfflineProperty_OutputSize"}],"kind":"symbol","url":"/documentation/audiotoolbox/kaudiounitofflineproperty_outputsize","title":"kAudioUnitOfflineProperty_OutputSize","abstract":[],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_OutputSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioUnitOfflineProperty_OutputSize"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@AudioUnitPropertyID","kind":"typeIdentifier","text":"AudioUnitPropertyID"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes":{"role":"collectionGroup","type":"topic","abstract":[],"kind":"article","url":"/documentation/audiotoolbox/1584155-audio-unit-player-subtypes","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes","title":"Audio Unit Player Subtypes"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584142-audio_unit_types":{"title":"Audio Unit Types","type":"topic","role":"collectionGroup","abstract":[{"type":"text","text":"The defined types of audio processing plug-ins known as audio units."}],"kind":"article","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584142-audio_unit_types","url":"/documentation/audiotoolbox/1584142-audio_unit_types"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes":{"role":"collectionGroup","type":"topic","abstract":[],"kind":"article","url":"/documentation/audiotoolbox/1584152-audio-unit-pitch-subtypes","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes","title":"Audio Unit Pitch Subtypes"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api":{"role":"collectionGroup","type":"topic","abstract":[{"type":"text","text":"Configure an Audio Unit and prepare it to render audio."}],"kind":"article","url":"/documentation/audiotoolbox/audio-unit-v2-c-api","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api","title":"Audio Unit v2 (C) API"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_StartOffset":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kAudioUnitOfflineProperty_StartOffset"}],"kind":"symbol","url":"/documentation/audiotoolbox/kaudiounitofflineproperty_startoffset","title":"kAudioUnitOfflineProperty_StartOffset","abstract":[],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_StartOffset","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioUnitOfflineProperty_StartOffset"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@AudioUnitPropertyID","kind":"typeIdentifier","text":"AudioUnitPropertyID"}]},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","type":"topic","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","role":"overview"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes":{"abstract":[{"text":"Audio units that serve as sound sources.","type":"text"}],"kind":"article","title":"Generator Audio Unit Subtypes","role":"collectionGroup","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes","url":"/documentation/audiotoolbox/1619493-generator_audio_unit_subtypes","type":"topic"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi":{"role":"collectionGroup","type":"topic","abstract":[{"type":"text","text":"The Apple audio unit manufacturer code."}],"kind":"article","url":"/documentation/audiotoolbox/1584143-audio_unit_manufacturer_identifi","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi","title":"Audio Unit Manufacturer Identifier"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes":{"abstract":[],"kind":"article","title":"Audio Unit Panner Subtypes","role":"collectionGroup","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes","url":"/documentation/audiotoolbox/1584151-audio-unit-panner-subtypes","type":"topic"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele":{"title":"General Audio Unit Function Selectors","type":"topic","role":"collectionGroup","abstract":[{"type":"text","text":"General audio unit component selectors that correspond to functions in the audio unit API."}],"kind":"article","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele","url":"/documentation/audiotoolbox/1584140-general_audio_unit_function_sele"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_PreflightRequirements":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kAudioUnitOfflineProperty_PreflightRequirements"}],"kind":"symbol","url":"/documentation/audiotoolbox/kaudiounitofflineproperty_preflightrequirements","title":"kAudioUnitOfflineProperty_PreflightRequirements","abstract":[],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_PreflightRequirements","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioUnitOfflineProperty_PreflightRequirements"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@AudioUnitPropertyID","kind":"typeIdentifier","text":"AudioUnitPropertyID"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType":{"kind":"symbol","url":"/documentation/audiotoolbox/audiouniteventtype","role":"symbol","type":"topic","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioUnitEventType","kind":"identifier"}],"navigatorTitle":[{"text":"AudioUnitEventType","kind":"identifier"}],"title":"AudioUnitEventType","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi":{"type":"topic","url":"/documentation/audiotoolbox/1533986-reserved_audio_unit_clump_identi","title":"Reserved Audio Unit Clump Identifier","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi","kind":"article","role":"collectionGroup","abstract":[{"text":"Reserved for system use.","type":"text"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389613-midi_audio_unit_parameters":{"type":"topic","url":"/documentation/audiotoolbox/1389613-midi_audio_unit_parameters","title":"MIDI Audio Unit Parameters","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389613-midi_audio_unit_parameters","kind":"article","role":"collectionGroup","abstract":[{"text":"Parameters for instrument units.","type":"text"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types":{"kind":"article","url":"/documentation/audiotoolbox/1619501-inter-app-audio-unit-types","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types","title":"Inter-App Audio Unit Types","abstract":[],"type":"topic","role":"collectionGroup"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_PreflightName":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioUnitOfflineProperty_PreflightName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioUnitPropertyID","preciseIdentifier":"c:@T@AudioUnitPropertyID"}],"url":"/documentation/audiotoolbox/kaudiounitofflineproperty_preflightname","role":"symbol","type":"topic","title":"kAudioUnitOfflineProperty_PreflightName","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_PreflightName","navigatorTitle":[{"kind":"identifier","text":"kAudioUnitOfflineProperty_PreflightName"}],"abstract":[],"kind":"symbol"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes":{"type":"topic","url":"/documentation/audiotoolbox/1584139-input_output_audio_unit_subtypes","title":"Input/Output Audio Unit Subtypes","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes","kind":"article","role":"collectionGroup","abstract":[{"text":"Input/output audio unit subtypes for audio units provided by Apple.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"identifiers":["doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_InputSize","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_OutputSize","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_PreflightName","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_PreflightRequirements","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_StartOffset"],"title":"Constants","anchor":"Constants"}],"path":"/topicSections","op":"replace"},{"value":[{"anchor":"Enumerations","title":"Enumerations","identifiers":["doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584142-audio_unit_types","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584148-audio-unit-output-subtypes","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389613-midi_audio_unit_parameters","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType"],"generated":true}],"path":"/seeAlsoSections","op":"replace"},{"value":"kAudioUnitOfflineProperty_InputSize","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitOfflineProperty_InputSize/title","op":"replace"},{"value":[{"text":"kAudioUnitOfflineProperty_InputSize","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitOfflineProperty_InputSize/fragments","op":"replace"},{"value":"kAudioUnitOfflineProperty_OutputSize","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitOfflineProperty_OutputSize/title","op":"replace"},{"value":[{"text":"kAudioUnitOfflineProperty_OutputSize","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitOfflineProperty_OutputSize/fragments","op":"replace"},{"value":"kAudioUnitOfflineProperty_StartOffset","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitOfflineProperty_StartOffset/title","op":"replace"},{"value":[{"kind":"identifier","text":"kAudioUnitOfflineProperty_StartOffset"}],"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitOfflineProperty_StartOffset/fragments"},{"value":"kAudioUnitOfflineProperty_PreflightRequirements","op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitOfflineProperty_PreflightRequirements/title"},{"value":[{"text":"kAudioUnitOfflineProperty_PreflightRequirements","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitOfflineProperty_PreflightRequirements/fragments"},{"value":"AudioUnitEventType","op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEventType/title"},{"value":[{"kind":"identifier","text":"AudioUnitEventType"}],"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEventType/fragments"},{"value":[{"text":"AudioUnitEventType","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEventType/navigatorTitle"},{"value":"kAudioUnitOfflineProperty_PreflightName","op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitOfflineProperty_PreflightName/title"},{"value":[{"kind":"identifier","text":"kAudioUnitOfflineProperty_PreflightName"}],"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitOfflineProperty_PreflightName/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}