{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534150-spatial-mixer-property-ids"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Spatial Mixer Property IDs"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389739-aumultichannelmixer_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Multichannel Mixer unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389739-aumultichannelmixer_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUMultiChannelMixer Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389739-aumultichannelmixer_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389763-3d_mixer_unit_parameters": {
      "abstract": [
        {
          "text": "Parameters for the 3D Mixer unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389763-3d_mixer_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "3D Mixer Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389763-3d_mixer_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389928-stereo-mixer-unit-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389928-stereo-mixer-unit-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Stereo Mixer Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389928-stereo-mixer-unit-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389991-panner-audio-unit-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389991-panner-audio-unit-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Panner Audio Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389991-panner-audio-unit-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390003-aumatrixmixer-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390003-aumatrixmixer-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUMatrixMixer Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390003-aumatrixmixer-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390073-auspatialmixer-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390073-auspatialmixer-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUSpatialMixer Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390073-auspatialmixer-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534041-mixer_audio_unit_properties": {
      "abstract": [
        {
          "text": "Properties for Apple mixer audio units.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534041-mixer_audio_unit_properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mixer Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534041-mixer_audio_unit_properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584146-audio-unit-mixer-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584146-audio-unit-mixer-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Mixer Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584146-audio-unit-mixer-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584150-mixer_audio_unit_subtypes": {
      "abstract": [
        {
          "text": "Audio mixing audio unit subtypes for audio units provided by Apple.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584150-mixer_audio_unit_subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mixer Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584150-mixer_audio_unit_subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AU3DMixerAttenuationCurve"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AU3DMixerAttenuationCurve"
        }
      ],
      "role": "symbol",
      "title": "AU3DMixerAttenuationCurve",
      "type": "topic",
      "url": "/documentation/audiotoolbox/au3dmixerattenuationcurve"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerAttenuationCurve": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatialMixerAttenuationCurve"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerAttenuationCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatialMixerAttenuationCurve"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerAttenuationCurve",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixerattenuationcurve"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerOutputType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatialMixerOutputType"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerOutputType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatialMixerOutputType"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerOutputType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixeroutputtype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerPointSourceInHeadMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatialMixerPointSourceInHeadMode"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerPointSourceInHeadMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatialMixerPointSourceInHeadMode"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerPointSourceInHeadMode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixerpointsourceinheadmode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerRenderingFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatialMixerRenderingFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerRenderingFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatialMixerRenderingFlags"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerRenderingFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixerrenderingflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatialMixerSourceMode"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatialMixerSourceMode"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerSourceMode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixersourcemode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties": {
      "abstract": [
        {
          "text": "Obtain information about the built-in mixers, equalizers, filters, effects, and other Audio Unit app extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_ReverbRoomType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_ReverbRoomType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_ReverbRoomType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_ReverbRoomType"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_ReverbRoomType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_reverbroomtype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerAnyInputIsUsingPersonalizedHRTF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerAnyInputIsUsingPersonalizedHRTF"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerAnyInputIsUsingPersonalizedHRTF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerAnyInputIsUsingPersonalizedHRTF"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_SpatialMixerAnyInputIsUsingPersonalizedHRTF",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_spatialmixeranyinputisusingpersonalizedhrtf"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerAttenuationCurve": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerAttenuationCurve"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerAttenuationCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerAttenuationCurve"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_SpatialMixerAttenuationCurve",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_spatialmixerattenuationcurve"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerDistanceParams": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerDistanceParams"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerDistanceParams",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerDistanceParams"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_SpatialMixerDistanceParams",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_spatialmixerdistanceparams"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerEnableHeadTracking": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerEnableHeadTracking"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerEnableHeadTracking",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerEnableHeadTracking"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_SpatialMixerEnableHeadTracking",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_spatialmixerenableheadtracking"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerOutputType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerOutputType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerOutputType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerOutputType"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_SpatialMixerOutputType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_spatialmixeroutputtype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerPersonalizedHRTFMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerPersonalizedHRTFMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerPersonalizedHRTFMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerPersonalizedHRTFMode"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_SpatialMixerPersonalizedHRTFMode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_spatialmixerpersonalizedhrtfmode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerPointSourceInHeadMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerPointSourceInHeadMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerPointSourceInHeadMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerPointSourceInHeadMode"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_SpatialMixerPointSourceInHeadMode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_spatialmixerpointsourceinheadmode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerRenderingFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerRenderingFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerRenderingFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerRenderingFlags"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_SpatialMixerRenderingFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_spatialmixerrenderingflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerSourceMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerSourceMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerSourceMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerSourceMode"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_SpatialMixerSourceMode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_spatialmixersourcemode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatializationAlgorithm": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatializationAlgorithm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatializationAlgorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatializationAlgorithm"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_SpatializationAlgorithm",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_spatializationalgorithm"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_UsesInternalReverb": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_UsesInternalReverb"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_UsesInternalReverb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_UsesInternalReverb"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_UsesInternalReverb",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_usesinternalreverb"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Mixers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584146-audio-unit-mixer-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerAttenuationCurve",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerRenderingFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390073-auspatialmixer-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389991-panner-audio-unit-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390003-aumatrixmixer-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389739-aumultichannelmixer_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389928-stereo-mixer-unit-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534041-mixer_audio_unit_properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584150-mixer_audio_unit_subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerOutputType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerPointSourceInHeadMode",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389763-3d_mixer_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve"
      ],
      "title": "Mixers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_ReverbRoomType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerAttenuationCurve",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerDistanceParams",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerRenderingFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatializationAlgorithm",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_UsesInternalReverb",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerOutputType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerPointSourceInHeadMode",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerSourceMode",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerAnyInputIsUsingPersonalizedHRTF",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerEnableHeadTracking",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerPersonalizedHRTFMode"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_ReverbRoomType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerAttenuationCurve",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerDistanceParams",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerRenderingFlags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatializationAlgorithm",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_UsesInternalReverb",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerOutputType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerPointSourceInHeadMode",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerSourceMode",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerAnyInputIsUsingPersonalizedHRTF",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerEnableHeadTracking",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerPersonalizedHRTFMode"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Mixers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584146-audio-unit-mixer-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerAttenuationCurve",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerRenderingFlags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390073-auspatialmixer-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389991-panner-audio-unit-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390003-aumatrixmixer-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389739-aumultichannelmixer_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389928-stereo-mixer-unit-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534041-mixer_audio_unit_properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584150-mixer_audio_unit_subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerOutputType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerPointSourceInHeadMode",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389763-3d_mixer_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve"
              ],
              "title": "Mixers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerDistanceParams/title",
          "value": "kAudioUnitProperty_SpatialMixerDistanceParams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerDistanceParams/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_SpatialMixerDistanceParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerOutputType/title",
          "value": "kAudioUnitProperty_SpatialMixerOutputType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerOutputType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_SpatialMixerOutputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerAnyInputIsUsingPersonalizedHRTF/title",
          "value": "kAudioUnitProperty_SpatialMixerAnyInputIsUsingPersonalizedHRTF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerAnyInputIsUsingPersonalizedHRTF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_SpatialMixerAnyInputIsUsingPersonalizedHRTF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerPersonalizedHRTFMode/title",
          "value": "kAudioUnitProperty_SpatialMixerPersonalizedHRTFMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerPersonalizedHRTFMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_SpatialMixerPersonalizedHRTFMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerAttenuationCurve/title",
          "value": "AUSpatialMixerAttenuationCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerAttenuationCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerAttenuationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerAttenuationCurve/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerAttenuationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerSourceMode/title",
          "value": "kAudioUnitProperty_SpatialMixerSourceMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerSourceMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_SpatialMixerSourceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerOutputType/title",
          "value": "AUSpatialMixerOutputType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerOutputType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerOutputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerOutputType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerOutputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerSourceMode/title",
          "value": "AUSpatialMixerSourceMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerSourceMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerSourceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerSourceMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerSourceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerRenderingFlags/title",
          "value": "AUSpatialMixerRenderingFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerRenderingFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerRenderingFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerRenderingFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerRenderingFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_UsesInternalReverb/title",
          "value": "kAudioUnitProperty_UsesInternalReverb"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_UsesInternalReverb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_UsesInternalReverb"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatializationAlgorithm/title",
          "value": "kAudioUnitProperty_SpatializationAlgorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatializationAlgorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_SpatializationAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_ReverbRoomType/title",
          "value": "kAudioUnitProperty_ReverbRoomType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_ReverbRoomType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_ReverbRoomType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerPointSourceInHeadMode/title",
          "value": "AUSpatialMixerPointSourceInHeadMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerPointSourceInHeadMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerPointSourceInHeadMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerPointSourceInHeadMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerPointSourceInHeadMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerEnableHeadTracking/title",
          "value": "kAudioUnitProperty_SpatialMixerEnableHeadTracking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerEnableHeadTracking/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_SpatialMixerEnableHeadTracking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerRenderingFlags/title",
          "value": "kAudioUnitProperty_SpatialMixerRenderingFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerRenderingFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_SpatialMixerRenderingFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerAttenuationCurve/title",
          "value": "kAudioUnitProperty_SpatialMixerAttenuationCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerAttenuationCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_SpatialMixerAttenuationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerAttenuationCurve/title",
          "value": "AU3DMixerAttenuationCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerAttenuationCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AU3DMixerAttenuationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerAttenuationCurve/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AU3DMixerAttenuationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerPointSourceInHeadMode/title",
          "value": "kAudioUnitProperty_SpatialMixerPointSourceInHeadMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerPointSourceInHeadMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_SpatialMixerPointSourceInHeadMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1534150-spatial-mixer-property-ids"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1534150-spatial-mixer-property-ids"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
