{
  "abstract": [
    {
      "text": "Render quality settings for audio units.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534177-renderquality"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "RenderQuality"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534082-other-plug-in-formats": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534082-other-plug-in-formats",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Other Plug-In Formats",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534082-other-plug-in-formats"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo": {
      "abstract": [
        {
          "text": "The time- and transport-related callback functions for an audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HostCallbackInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HostCallbackInfo"
        }
      ],
      "role": "symbol",
      "title": "HostCallbackInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/hostcallbackinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties": {
      "abstract": [
        {
          "text": "Obtain information about the built-in mixers, equalizers, filters, effects, and other Audio Unit app extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/general-audio-unit-properties": {
      "abstract": [
        {
          "text": "Properties that apply to any audio unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/general-audio-unit-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "General Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/general-audio-unit-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRenderQuality_High": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRenderQuality_High"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRenderQuality_High",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRenderQuality_High"
        }
      ],
      "role": "symbol",
      "title": "kRenderQuality_High",
      "type": "topic",
      "url": "/documentation/audiotoolbox/krenderquality_high"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRenderQuality_Low": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRenderQuality_Low"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRenderQuality_Low",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRenderQuality_Low"
        }
      ],
      "role": "symbol",
      "title": "kRenderQuality_Low",
      "type": "topic",
      "url": "/documentation/audiotoolbox/krenderquality_low"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRenderQuality_Max": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRenderQuality_Max"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRenderQuality_Max",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRenderQuality_Max"
        }
      ],
      "role": "symbol",
      "title": "kRenderQuality_Max",
      "type": "topic",
      "url": "/documentation/audiotoolbox/krenderquality_max"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRenderQuality_Medium": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRenderQuality_Medium"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRenderQuality_Medium",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRenderQuality_Medium"
        }
      ],
      "role": "symbol",
      "title": "kRenderQuality_Medium",
      "type": "topic",
      "url": "/documentation/audiotoolbox/krenderquality_medium"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRenderQuality_Min": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRenderQuality_Min"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRenderQuality_Min",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRenderQuality_Min"
        }
      ],
      "role": "symbol",
      "title": "kRenderQuality_Min",
      "type": "topic",
      "url": "/documentation/audiotoolbox/krenderquality_min"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "General",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534082-other-plug-in-formats",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/general-audio-unit-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo"
      ],
      "title": "General"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRenderQuality_High",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRenderQuality_Low",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRenderQuality_Max",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRenderQuality_Medium",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRenderQuality_Min"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRenderQuality_High",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRenderQuality_Low",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRenderQuality_Max",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRenderQuality_Medium",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRenderQuality_Min"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "General",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534082-other-plug-in-formats",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/general-audio-unit-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo"
              ],
              "title": "General"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRenderQuality_Medium/title",
          "value": "kRenderQuality_Medium"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRenderQuality_Medium/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRenderQuality_Medium"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallbackInfo/title",
          "value": "HostCallbackInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallbackInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HostCallbackInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallbackInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HostCallbackInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRenderQuality_Low/title",
          "value": "kRenderQuality_Low"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRenderQuality_Low/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRenderQuality_Low"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRenderQuality_Max/title",
          "value": "kRenderQuality_Max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRenderQuality_Max/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRenderQuality_Max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRenderQuality_High/title",
          "value": "kRenderQuality_High"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRenderQuality_High/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRenderQuality_High"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRenderQuality_Min/title",
          "value": "kRenderQuality_Min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRenderQuality_Min/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRenderQuality_Min"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1534177-renderquality"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1534177-renderquality"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
