{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534086-ausampler-property-ids"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "AUSampler Property IDs"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389639-aurandom-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389639-aurandom-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AURandom Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389639-aurandom-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389727-aurogerbeep-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389727-aurogerbeep-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AURogerBeep Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389727-aurogerbeep-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389769-ausampler-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389769-ausampler-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUSampler Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389769-ausampler-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389808-auroundtripaacparam-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389808-auroundtripaacparam-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AURoundTripAACParam Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389808-auroundtripaacparam-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533959-ausampler-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533959-ausampler-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUSampler Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1533959-ausampler-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534190-aumidisynth-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534190-aumidisynth-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUMIDISynth Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534190-aumidisynth-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties": {
      "abstract": [
        {
          "text": "Obtain information about the built-in mixers, equalizers, filters, effects, and other Audio Unit app extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUSampler_DefaultBankLSB": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUSampler_DefaultBankLSB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUSampler_DefaultBankLSB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUSampler_DefaultBankLSB"
        }
      ],
      "role": "symbol",
      "title": "kAUSampler_DefaultBankLSB",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kausampler_defaultbanklsb"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUSampler_DefaultMelodicBankMSB": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUSampler_DefaultMelodicBankMSB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUSampler_DefaultMelodicBankMSB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUSampler_DefaultMelodicBankMSB"
        }
      ],
      "role": "symbol",
      "title": "kAUSampler_DefaultMelodicBankMSB",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kausampler_defaultmelodicbankmsb"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUSampler_DefaultPercussionBankMSB": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUSampler_DefaultPercussionBankMSB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUSampler_DefaultPercussionBankMSB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUSampler_DefaultPercussionBankMSB"
        }
      ],
      "role": "symbol",
      "title": "kAUSampler_DefaultPercussionBankMSB",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kausampler_defaultpercussionbankmsb"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Generators",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389639-aurandom-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389769-ausampler-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533959-ausampler-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389727-aurogerbeep-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534190-aumidisynth-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389808-auroundtripaacparam-parameters"
      ],
      "title": "Generators"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUSampler_DefaultBankLSB",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUSampler_DefaultMelodicBankMSB",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUSampler_DefaultPercussionBankMSB"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUSampler_DefaultBankLSB",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUSampler_DefaultMelodicBankMSB",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUSampler_DefaultPercussionBankMSB"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Generators",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389639-aurandom-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389769-ausampler-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533959-ausampler-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389727-aurogerbeep-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534190-aumidisynth-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389808-auroundtripaacparam-parameters"
              ],
              "title": "Generators"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUSampler_DefaultBankLSB/title",
          "value": "kAUSampler_DefaultBankLSB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUSampler_DefaultBankLSB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUSampler_DefaultBankLSB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUSampler_DefaultPercussionBankMSB/title",
          "value": "kAUSampler_DefaultPercussionBankMSB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUSampler_DefaultPercussionBankMSB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUSampler_DefaultPercussionBankMSB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUSampler_DefaultMelodicBankMSB/title",
          "value": "kAUSampler_DefaultMelodicBankMSB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUSampler_DefaultMelodicBankMSB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUSampler_DefaultMelodicBankMSB"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1534086-ausampler-property-ids"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1534086-ausampler-property-ids"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
