{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534212-aunetsendpresetformat-properties"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "AUNetSendPresetFormat Properties"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389633-aunetsend-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389633-aunetsend-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNetSend Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389633-aunetsend-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389891-net-status-audio-unit-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389891-net-status-audio-unit-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Net Status Audio Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389891-net-status-audio-unit-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389916-output_unit_parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389916-output_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Output Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389916-output_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389920-aunetreceive-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389920-aunetreceive-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNetReceive Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389920-aunetreceive-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534109-aunetreceive-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534109-aunetreceive-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNetReceive Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534109-aunetreceive-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534116-i_o_audio_unit_properties": {
      "abstract": [
        {
          "text": "Properties for Apple I/O audio units (sometimes called output units).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534116-i_o_audio_unit_properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "I/O Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534116-i_o_audio_unit_properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534207-aunetsend-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534207-aunetsend-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNetSend Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534207-aunetsend-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1585807-i_o_audio_unit_function_selector": {
      "abstract": [
        {
          "text": "Audio unit component selectors, specific to I/O audio units, that correspond to functions in the audio unit API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1585807-i_o_audio_unit_function_selector",
      "kind": "article",
      "role": "collectionGroup",
      "title": "I/O Audio Unit Function Selectors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1585807-i_o_audio_unit_function_selector"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621038-inter-app-audio-unit-property-ids": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621038-inter-app-audio-unit-property-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Inter-App Audio Unit Property IDs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1621038-inter-app-audio-unit-property-ids"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621039-inter-app-output-unit-property-ids": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621039-inter-app-output-unit-property-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Inter-App Output Unit Property IDs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1621039-inter-app-output-unit-property-ids"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitMIDICallbacks": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioOutputUnitMIDICallbacks"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitMIDICallbacks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioOutputUnitMIDICallbacks"
        }
      ],
      "role": "symbol",
      "title": "AudioOutputUnitMIDICallbacks",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiooutputunitmidicallbacks"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitStartAtTimeParams": {
      "abstract": [
        {
          "text": "A timestamp for scheduled starting of an I/O audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioOutputUnitStartAtTimeParams"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitStartAtTimeParams",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioOutputUnitStartAtTimeParams"
        }
      ],
      "role": "symbol",
      "title": "AudioOutputUnitStartAtTimeParams",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiooutputunitstartattimeparams"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties": {
      "abstract": [
        {
          "text": "Obtain information about the built-in mixers, equalizers, filters, effects, and other Audio Unit app extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendNumPresetFormats": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendNumPresetFormats"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendNumPresetFormats",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendNumPresetFormats"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendNumPresetFormats",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendnumpresetformats"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_128kbpspc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_128kbpspc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_128kbpspc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_128kbpspc"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_AAC_128kbpspc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_aac_128kbpspc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_32kbpspc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_32kbpspc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_32kbpspc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_32kbpspc"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_AAC_32kbpspc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_aac_32kbpspc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_40kbpspc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_40kbpspc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_40kbpspc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_40kbpspc"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_AAC_40kbpspc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_aac_40kbpspc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_48kbpspc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_48kbpspc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_48kbpspc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_48kbpspc"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_AAC_48kbpspc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_aac_48kbpspc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_64kbpspc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_64kbpspc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_64kbpspc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_64kbpspc"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_AAC_64kbpspc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_aac_64kbpspc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_80kbpspc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_80kbpspc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_80kbpspc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_80kbpspc"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_AAC_80kbpspc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_aac_80kbpspc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_96kbpspc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_96kbpspc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_96kbpspc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_96kbpspc"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_AAC_96kbpspc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_aac_96kbpspc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_32kbpspc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_LD_32kbpspc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_32kbpspc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_LD_32kbpspc"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_AAC_LD_32kbpspc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_aac_ld_32kbpspc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_40kbpspc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_LD_40kbpspc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_40kbpspc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_LD_40kbpspc"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_AAC_LD_40kbpspc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_aac_ld_40kbpspc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_48kbpspc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_LD_48kbpspc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_48kbpspc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_LD_48kbpspc"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_AAC_LD_48kbpspc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_aac_ld_48kbpspc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_64kbpspc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_LD_64kbpspc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_64kbpspc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_LD_64kbpspc"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_AAC_LD_64kbpspc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_aac_ld_64kbpspc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_IMA4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_IMA4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_IMA4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_IMA4"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_IMA4",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_ima4"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_Lossless16": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_Lossless16"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_Lossless16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_Lossless16"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_Lossless16",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_lossless16"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_Lossless24": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_Lossless24"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_Lossless24",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_Lossless24"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_Lossless24",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_lossless24"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_PCMFloat32": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_PCMFloat32"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_PCMFloat32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_PCMFloat32"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_PCMFloat32",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_pcmfloat32"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_PCMInt16": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_PCMInt16"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_PCMInt16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_PCMInt16"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_PCMInt16",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_pcmint16"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_PCMInt24": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_PCMInt24"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_PCMInt24",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_PCMInt24"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_PCMInt24",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_pcmint24"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_ULaw": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_ULaw"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_ULaw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_ULaw"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_ULaw",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_ulaw"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "InputOutput",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534116-i_o_audio_unit_properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621039-inter-app-output-unit-property-ids",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621038-inter-app-audio-unit-property-ids",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389916-output_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534109-aunetreceive-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534207-aunetsend-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389633-aunetsend-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389920-aunetreceive-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389891-net-status-audio-unit-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1585807-i_o_audio_unit_function_selector",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitMIDICallbacks",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitStartAtTimeParams"
      ],
      "title": "Input/Output"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendNumPresetFormats",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_128kbpspc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_32kbpspc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_40kbpspc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_48kbpspc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_64kbpspc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_80kbpspc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_96kbpspc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_32kbpspc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_40kbpspc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_48kbpspc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_64kbpspc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_IMA4",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_Lossless16",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_Lossless24",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_PCMFloat32",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_PCMInt16",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_PCMInt24",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_ULaw"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendNumPresetFormats",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_128kbpspc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_32kbpspc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_40kbpspc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_48kbpspc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_64kbpspc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_80kbpspc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_96kbpspc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_32kbpspc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_40kbpspc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_48kbpspc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_64kbpspc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_IMA4",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_Lossless16",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_Lossless24",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_PCMFloat32",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_PCMInt16",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_PCMInt24",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_ULaw"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "InputOutput",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534116-i_o_audio_unit_properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621039-inter-app-output-unit-property-ids",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621038-inter-app-audio-unit-property-ids",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389916-output_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534109-aunetreceive-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534207-aunetsend-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389633-aunetsend-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389920-aunetreceive-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389891-net-status-audio-unit-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1585807-i_o_audio_unit_function_selector",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitMIDICallbacks",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitStartAtTimeParams"
              ],
              "title": "Input/Output"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_96kbpspc/title",
          "value": "kAUNetSendPresetFormat_AAC_96kbpspc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_96kbpspc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_AAC_96kbpspc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_Lossless24/title",
          "value": "kAUNetSendPresetFormat_Lossless24"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_Lossless24/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_Lossless24"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_Lossless16/title",
          "value": "kAUNetSendPresetFormat_Lossless16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_Lossless16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_Lossless16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_40kbpspc/title",
          "value": "kAUNetSendPresetFormat_AAC_40kbpspc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_40kbpspc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_AAC_40kbpspc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendNumPresetFormats/title",
          "value": "kAUNetSendNumPresetFormats"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendNumPresetFormats/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendNumPresetFormats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_48kbpspc/title",
          "value": "kAUNetSendPresetFormat_AAC_48kbpspc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_48kbpspc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_AAC_48kbpspc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_LD_32kbpspc/title",
          "value": "kAUNetSendPresetFormat_AAC_LD_32kbpspc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_LD_32kbpspc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_AAC_LD_32kbpspc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_LD_48kbpspc/title",
          "value": "kAUNetSendPresetFormat_AAC_LD_48kbpspc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_LD_48kbpspc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_AAC_LD_48kbpspc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_IMA4/title",
          "value": "kAUNetSendPresetFormat_IMA4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_IMA4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_IMA4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_64kbpspc/title",
          "value": "kAUNetSendPresetFormat_AAC_64kbpspc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_64kbpspc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_AAC_64kbpspc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_80kbpspc/title",
          "value": "kAUNetSendPresetFormat_AAC_80kbpspc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_80kbpspc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_AAC_80kbpspc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_PCMInt24/title",
          "value": "kAUNetSendPresetFormat_PCMInt24"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_PCMInt24/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_PCMInt24"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitStartAtTimeParams/title",
          "value": "AudioOutputUnitStartAtTimeParams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitStartAtTimeParams/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioOutputUnitStartAtTimeParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitStartAtTimeParams/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioOutputUnitStartAtTimeParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_32kbpspc/title",
          "value": "kAUNetSendPresetFormat_AAC_32kbpspc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_32kbpspc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_AAC_32kbpspc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_PCMFloat32/title",
          "value": "kAUNetSendPresetFormat_PCMFloat32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_PCMFloat32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_PCMFloat32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_LD_64kbpspc/title",
          "value": "kAUNetSendPresetFormat_AAC_LD_64kbpspc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_LD_64kbpspc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_AAC_LD_64kbpspc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_128kbpspc/title",
          "value": "kAUNetSendPresetFormat_AAC_128kbpspc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_128kbpspc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_AAC_128kbpspc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_PCMInt16/title",
          "value": "kAUNetSendPresetFormat_PCMInt16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_PCMInt16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_PCMInt16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitMIDICallbacks/title",
          "value": "AudioOutputUnitMIDICallbacks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitMIDICallbacks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioOutputUnitMIDICallbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitMIDICallbacks/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioOutputUnitMIDICallbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_LD_40kbpspc/title",
          "value": "kAUNetSendPresetFormat_AAC_LD_40kbpspc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_LD_40kbpspc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_AAC_LD_40kbpspc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_ULaw/title",
          "value": "kAUNetSendPresetFormat_ULaw"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_ULaw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_ULaw"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1534212-aunetsendpresetformat-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1534212-aunetsendpresetformat-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
