{
  "abstract": [
    {
      "text": "The different types of node interactions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/deprecated-symbols",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-processing-graph-services"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1537633-kaunodeinteraction-connection"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "kAUNodeInteraction_Connection"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The term interaction is used as a general term to describe some interaction of a node. Currently, the interactions of a node that the graph manages are described below.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-processing-graph-services": {
      "abstract": [
        {
          "text": "Audio Unit Processing Graph Services provide interfaces for representing a set of audio units, connections between their inputs and outputs, and callbacks used to provide inputs. It also enables the embedding of sub (or child) processing graphs within parent graphs to allow for a logical organization of parts of an overall signal chain.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-processing-graph-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Processing Graph Services",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-processing-graph-services"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/deprecated-symbols": {
      "abstract": [
        {
          "text": "Review unsupported symbols and their replacements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/audiotoolbox/deprecated-symbols"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNodeInteraction_Connection": {
      "abstract": [
        {
          "text": "connections between 2 audio units,",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNodeInteraction_Connection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNodeInteraction_Connection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNodeInteraction_Connection"
        }
      ],
      "role": "symbol",
      "title": "kAUNodeInteraction_Connection",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunodeinteraction_connection"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNodeInteraction_InputCallback": {
      "abstract": [
        {
          "text": "input callbacks being registered to a single audio unit’s input bus.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNodeInteraction_InputCallback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNodeInteraction_InputCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNodeInteraction_InputCallback"
        }
      ],
      "role": "symbol",
      "title": "kAUNodeInteraction_InputCallback",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunodeinteraction_inputcallback"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNodeInteraction_Connection",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNodeInteraction_InputCallback"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNodeInteraction_Connection",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNodeInteraction_InputCallback"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNodeInteraction_Connection/title",
          "value": "kAUNodeInteraction_Connection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNodeInteraction_Connection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNodeInteraction_Connection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNodeInteraction_InputCallback/title",
          "value": "kAUNodeInteraction_InputCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNodeInteraction_InputCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNodeInteraction_InputCallback"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1537633-kaunodeinteraction-connection"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1537633-kaunodeinteraction-connection"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
