{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/deprecated-symbols"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1537630-audio-graph-errors"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio Graph Errors"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533960-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533960-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1533960-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534019-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534019-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534019-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534063-3d_mixer_audio_unit_properties": {
      "abstract": [
        {
          "text": "Properties for the Apple 3D Mixer audio unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534063-3d_mixer_audio_unit_properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "3D Mixer Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534063-3d_mixer_audio_unit_properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534074-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534074-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534074-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534089-music-device-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534089-music-device-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Music Device Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534089-music-device-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534112-audio-unit-attenuation-propertie": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534112-audio-unit-attenuation-propertie",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Attenuation Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534112-audio-unit-attenuation-propertie"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534225-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534225-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534225-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584141-audio-unit-instrument-errors": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584141-audio-unit-instrument-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Instrument Errors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584141-audio-unit-instrument-errors"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618426-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618426-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1618426-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618742-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618742-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1618742-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619479-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619479-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1619479-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619504-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619504-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1619504-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621044-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621044-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1621044-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1624333-audio-converter-property-id": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1624333-audio-converter-property-id",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Converter Property ID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1624333-audio-converter-property-id"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/deprecated-symbols": {
      "abstract": [
        {
          "text": "Review unsupported symbols and their replacements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/audiotoolbox/deprecated-symbols"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGraphErr_CannotDoInCurrentContext": {
      "abstract": [
        {
          "text": "To avoid spinning or waiting in the render thread (a bad idea!), many of the calls to AUGraph can return: ",
          "type": "text"
        },
        {
          "code": "kAUGraphErr_CannotDoInCurrentContext",
          "type": "codeVoice"
        },
        {
          "text": ". This result is only generated when you call an AUGraph API from its render callback. It means that the lock that it required was held at that time, by another thread. If you see this result code, you can generally attempt the action again - typically the NEXT render cycle (so in the mean time the lock can be cleared), or you can delegate that call to another thread in your app. You should not spin or put-to-sleep the render thread.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGraphErr_CannotDoInCurrentContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGraphErr_CannotDoInCurrentContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGraphErr_CannotDoInCurrentContext"
        }
      ],
      "role": "symbol",
      "title": "kAUGraphErr_CannotDoInCurrentContext",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugrapherr_cannotdoincurrentcontext"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGraphErr_InvalidAudioUnit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGraphErr_InvalidAudioUnit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGraphErr_InvalidAudioUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGraphErr_InvalidAudioUnit"
        }
      ],
      "role": "symbol",
      "title": "kAUGraphErr_InvalidAudioUnit",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugrapherr_invalidaudiounit"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGraphErr_InvalidConnection": {
      "abstract": [
        {
          "text": "The attempted connection between two nodes cannot be made.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGraphErr_InvalidConnection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGraphErr_InvalidConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGraphErr_InvalidConnection"
        }
      ],
      "role": "symbol",
      "title": "kAUGraphErr_InvalidConnection",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugrapherr_invalidconnection"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGraphErr_NodeNotFound": {
      "abstract": [
        {
          "text": "The specified node cannot be found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGraphErr_NodeNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGraphErr_NodeNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGraphErr_NodeNotFound"
        }
      ],
      "role": "symbol",
      "title": "kAUGraphErr_NodeNotFound",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugrapherr_nodenotfound"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGraphErr_OutputNodeErr": {
      "abstract": [
        {
          "text": "Audio processing graphs can only contain one output unit. This error is returned if trying to add a second output unit or if the graph’s output unit is removed while the graph is running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGraphErr_OutputNodeErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGraphErr_OutputNodeErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGraphErr_OutputNodeErr"
        }
      ],
      "role": "symbol",
      "title": "kAUGraphErr_OutputNodeErr",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugrapherr_outputnodeerr"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSession_AudioRouteChangeKey_OldRoute": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSession_AudioRouteChangeKey_OldRoute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSession_AudioRouteChangeKey_OldRoute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSession_AudioRouteChangeKey_OldRoute"
        }
      ],
      "role": "symbol",
      "title": "kAudioSession_AudioRouteChangeKey_OldRoute",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosession_audioroutechangekey_oldroute"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534112-audio-unit-attenuation-propertie",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584141-audio-unit-instrument-errors",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534019-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534074-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1624333-audio-converter-property-id",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621044-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618426-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618742-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619479-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619504-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533960-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534225-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534089-music-device-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534063-3d_mixer_audio_unit_properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSession_AudioRouteChangeKey_OldRoute"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGraphErr_CannotDoInCurrentContext",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGraphErr_InvalidAudioUnit",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGraphErr_InvalidConnection",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGraphErr_NodeNotFound",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGraphErr_OutputNodeErr"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGraphErr_CannotDoInCurrentContext",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGraphErr_InvalidAudioUnit",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGraphErr_InvalidConnection",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGraphErr_NodeNotFound",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGraphErr_OutputNodeErr"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534112-audio-unit-attenuation-propertie",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584141-audio-unit-instrument-errors",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534019-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534074-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1624333-audio-converter-property-id",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621044-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618426-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618742-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619479-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619504-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533960-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534225-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534089-music-device-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534063-3d_mixer_audio_unit_properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSession_AudioRouteChangeKey_OldRoute"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGraphErr_InvalidAudioUnit/title",
          "value": "kAUGraphErr_InvalidAudioUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGraphErr_InvalidAudioUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGraphErr_InvalidAudioUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGraphErr_InvalidConnection/title",
          "value": "kAUGraphErr_InvalidConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGraphErr_InvalidConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGraphErr_InvalidConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGraphErr_NodeNotFound/title",
          "value": "kAUGraphErr_NodeNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGraphErr_NodeNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGraphErr_NodeNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSession_AudioRouteChangeKey_OldRoute/title",
          "value": "kAudioSession_AudioRouteChangeKey_OldRoute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSession_AudioRouteChangeKey_OldRoute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSession_AudioRouteChangeKey_OldRoute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGraphErr_OutputNodeErr/title",
          "value": "kAUGraphErr_OutputNodeErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGraphErr_OutputNodeErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGraphErr_OutputNodeErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGraphErr_CannotDoInCurrentContext/title",
          "value": "kAUGraphErr_CannotDoInCurrentContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGraphErr_CannotDoInCurrentContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGraphErr_CannotDoInCurrentContext"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1537630-audio-graph-errors"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1537630-audio-graph-errors"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
