{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/core-audio-file-format"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547266-caf-file-chunk-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CAF File Chunk Types"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547255-caf-file-header": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547255-caf-file-header",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CAF File Header",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1547255-caf-file-header"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547262-caf-file-smpte-time-types": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547262-caf-file-smpte-time-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CAF File SMPTE Time Types",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1547262-caf-file-smpte-time-types"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547272-caf-file-marker-types": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547272-caf-file-marker-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CAF File Marker Types",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1547272-caf-file-marker-types"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFFormatFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAFFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFFormatFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAFFormatFlags"
        }
      ],
      "role": "symbol",
      "title": "CAFFormatFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/cafformatflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFRegionFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAFRegionFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFRegionFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAFRegionFlags"
        }
      ],
      "role": "symbol",
      "title": "CAFRegionFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/cafregionflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/core-audio-file-format": {
      "abstract": [
        {
          "text": "Parse the structure of Core Audio files.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/core-audio-file-format",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Audio File Format",
      "type": "topic",
      "url": "/documentation/audiotoolbox/core-audio-file-format"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_AudioDataChunkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_AudioDataChunkID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_AudioDataChunkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_AudioDataChunkID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_AudioDataChunkID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_audiodatachunkid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_ChannelLayoutChunkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_ChannelLayoutChunkID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_ChannelLayoutChunkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_ChannelLayoutChunkID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_ChannelLayoutChunkID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_channellayoutchunkid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_EditCommentsChunkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_EditCommentsChunkID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_EditCommentsChunkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_EditCommentsChunkID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_EditCommentsChunkID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_editcommentschunkid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_FillerChunkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_FillerChunkID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_FillerChunkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_FillerChunkID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_FillerChunkID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_fillerchunkid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_FormatListID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_FormatListID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_FormatListID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_FormatListID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_FormatListID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_formatlistid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_InfoStringsChunkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_InfoStringsChunkID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_InfoStringsChunkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_InfoStringsChunkID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_InfoStringsChunkID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_infostringschunkid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_InstrumentChunkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_InstrumentChunkID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_InstrumentChunkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_InstrumentChunkID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_InstrumentChunkID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_instrumentchunkid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_MIDIChunkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_MIDIChunkID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_MIDIChunkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_MIDIChunkID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_MIDIChunkID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_midichunkid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_MagicCookieID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_MagicCookieID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_MagicCookieID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_MagicCookieID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_MagicCookieID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_magiccookieid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_MarkerChunkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_MarkerChunkID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_MarkerChunkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_MarkerChunkID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_MarkerChunkID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_markerchunkid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_OverviewChunkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_OverviewChunkID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_OverviewChunkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_OverviewChunkID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_OverviewChunkID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_overviewchunkid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_PacketTableChunkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_PacketTableChunkID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_PacketTableChunkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_PacketTableChunkID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_PacketTableChunkID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_packettablechunkid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_PeakChunkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_PeakChunkID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_PeakChunkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_PeakChunkID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_PeakChunkID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_peakchunkid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_RegionChunkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_RegionChunkID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_RegionChunkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_RegionChunkID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_RegionChunkID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_regionchunkid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_StreamDescriptionChunkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_StreamDescriptionChunkID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_StreamDescriptionChunkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_StreamDescriptionChunkID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_StreamDescriptionChunkID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_streamdescriptionchunkid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_StringsChunkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_StringsChunkID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_StringsChunkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_StringsChunkID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_StringsChunkID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_stringschunkid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_UMIDChunkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_UMIDChunkID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_UMIDChunkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_UMIDChunkID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_UMIDChunkID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_umidchunkid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_UUIDChunkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_UUIDChunkID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_UUIDChunkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_UUIDChunkID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_UUIDChunkID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_uuidchunkid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_iXMLChunkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_iXMLChunkID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_iXMLChunkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_iXMLChunkID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_iXMLChunkID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_ixmlchunkid"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFFormatFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFRegionFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547272-caf-file-marker-types",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547262-caf-file-smpte-time-types",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547255-caf-file-header"
      ],
      "title": "Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_AudioDataChunkID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_ChannelLayoutChunkID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_EditCommentsChunkID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_FillerChunkID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_FormatListID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_InfoStringsChunkID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_InstrumentChunkID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_MIDIChunkID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_MagicCookieID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_MarkerChunkID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_OverviewChunkID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_PacketTableChunkID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_PeakChunkID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_RegionChunkID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_StreamDescriptionChunkID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_StringsChunkID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_UMIDChunkID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_UUIDChunkID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_iXMLChunkID"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_AudioDataChunkID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_ChannelLayoutChunkID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_EditCommentsChunkID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_FillerChunkID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_FormatListID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_InfoStringsChunkID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_InstrumentChunkID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_MIDIChunkID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_MagicCookieID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_MarkerChunkID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_OverviewChunkID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_PacketTableChunkID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_PeakChunkID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_RegionChunkID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_StreamDescriptionChunkID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_StringsChunkID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_UMIDChunkID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_UUIDChunkID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_iXMLChunkID"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFFormatFlags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFRegionFlags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547272-caf-file-marker-types",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547262-caf-file-smpte-time-types",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547255-caf-file-header"
              ],
              "title": "Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFRegionFlags/title",
          "value": "CAFRegionFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFRegionFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFRegionFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFRegionFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFRegionFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_FormatListID/title",
          "value": "kCAF_FormatListID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_FormatListID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_FormatListID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_OverviewChunkID/title",
          "value": "kCAF_OverviewChunkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_OverviewChunkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_OverviewChunkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_MIDIChunkID/title",
          "value": "kCAF_MIDIChunkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_MIDIChunkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_MIDIChunkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_iXMLChunkID/title",
          "value": "kCAF_iXMLChunkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_iXMLChunkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_iXMLChunkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_RegionChunkID/title",
          "value": "kCAF_RegionChunkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_RegionChunkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_RegionChunkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_MarkerChunkID/title",
          "value": "kCAF_MarkerChunkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_MarkerChunkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_MarkerChunkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_UMIDChunkID/title",
          "value": "kCAF_UMIDChunkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_UMIDChunkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_UMIDChunkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_StringsChunkID/title",
          "value": "kCAF_StringsChunkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_StringsChunkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_StringsChunkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_EditCommentsChunkID/title",
          "value": "kCAF_EditCommentsChunkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_EditCommentsChunkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_EditCommentsChunkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_InstrumentChunkID/title",
          "value": "kCAF_InstrumentChunkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_InstrumentChunkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_InstrumentChunkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_FillerChunkID/title",
          "value": "kCAF_FillerChunkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_FillerChunkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_FillerChunkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_ChannelLayoutChunkID/title",
          "value": "kCAF_ChannelLayoutChunkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_ChannelLayoutChunkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_ChannelLayoutChunkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_AudioDataChunkID/title",
          "value": "kCAF_AudioDataChunkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_AudioDataChunkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_AudioDataChunkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_PacketTableChunkID/title",
          "value": "kCAF_PacketTableChunkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_PacketTableChunkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_PacketTableChunkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_MagicCookieID/title",
          "value": "kCAF_MagicCookieID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_MagicCookieID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_MagicCookieID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_InfoStringsChunkID/title",
          "value": "kCAF_InfoStringsChunkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_InfoStringsChunkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_InfoStringsChunkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_PeakChunkID/title",
          "value": "kCAF_PeakChunkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_PeakChunkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_PeakChunkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_StreamDescriptionChunkID/title",
          "value": "kCAF_StreamDescriptionChunkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_StreamDescriptionChunkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_StreamDescriptionChunkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_UUIDChunkID/title",
          "value": "kCAF_UUIDChunkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_UUIDChunkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_UUIDChunkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFFormatFlags/title",
          "value": "CAFFormatFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFFormatFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFFormatFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFFormatFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFFormatFlags"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1547266-caf-file-chunk-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1547266-caf-file-chunk-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
