{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/core-audio-file-format"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547262-caf-file-smpte-time-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CAF File SMPTE Time Types"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547255-caf-file-header": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547255-caf-file-header",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CAF File Header",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1547255-caf-file-header"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547266-caf-file-chunk-types": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547266-caf-file-chunk-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CAF File Chunk Types",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1547266-caf-file-chunk-types"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547272-caf-file-marker-types": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547272-caf-file-marker-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CAF File Marker Types",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1547272-caf-file-marker-types"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFFormatFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAFFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFFormatFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAFFormatFlags"
        }
      ],
      "role": "symbol",
      "title": "CAFFormatFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/cafformatflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFRegionFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAFRegionFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFRegionFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAFRegionFlags"
        }
      ],
      "role": "symbol",
      "title": "CAFRegionFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/cafregionflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/core-audio-file-format": {
      "abstract": [
        {
          "text": "Parse the structure of Core Audio files.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/core-audio-file-format",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Audio File Format",
      "type": "topic",
      "url": "/documentation/audiotoolbox/core-audio-file-format"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType2398": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType2398"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType2398",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType2398"
        }
      ],
      "role": "symbol",
      "title": "kCAF_SMPTE_TimeType2398",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_smpte_timetype2398"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType24": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType24"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType24",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType24"
        }
      ],
      "role": "symbol",
      "title": "kCAF_SMPTE_TimeType24",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_smpte_timetype24"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType25": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType25"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType25",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType25"
        }
      ],
      "role": "symbol",
      "title": "kCAF_SMPTE_TimeType25",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_smpte_timetype25"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType2997": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType2997"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType2997",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType2997"
        }
      ],
      "role": "symbol",
      "title": "kCAF_SMPTE_TimeType2997",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_smpte_timetype2997"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType2997Drop": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType2997Drop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType2997Drop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType2997Drop"
        }
      ],
      "role": "symbol",
      "title": "kCAF_SMPTE_TimeType2997Drop",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_smpte_timetype2997drop"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType30": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType30"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType30",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType30"
        }
      ],
      "role": "symbol",
      "title": "kCAF_SMPTE_TimeType30",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_smpte_timetype30"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType30Drop": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType30Drop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType30Drop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType30Drop"
        }
      ],
      "role": "symbol",
      "title": "kCAF_SMPTE_TimeType30Drop",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_smpte_timetype30drop"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType50": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType50"
        }
      ],
      "role": "symbol",
      "title": "kCAF_SMPTE_TimeType50",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_smpte_timetype50"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType5994": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType5994"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType5994",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType5994"
        }
      ],
      "role": "symbol",
      "title": "kCAF_SMPTE_TimeType5994",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_smpte_timetype5994"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType5994Drop": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType5994Drop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType5994Drop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType5994Drop"
        }
      ],
      "role": "symbol",
      "title": "kCAF_SMPTE_TimeType5994Drop",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_smpte_timetype5994drop"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType60": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType60"
        }
      ],
      "role": "symbol",
      "title": "kCAF_SMPTE_TimeType60",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_smpte_timetype60"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType60Drop": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType60Drop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType60Drop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType60Drop"
        }
      ],
      "role": "symbol",
      "title": "kCAF_SMPTE_TimeType60Drop",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_smpte_timetype60drop"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeTypeNone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeTypeNone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeTypeNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeTypeNone"
        }
      ],
      "role": "symbol",
      "title": "kCAF_SMPTE_TimeTypeNone",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_smpte_timetypenone"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFFormatFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFRegionFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547266-caf-file-chunk-types",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547272-caf-file-marker-types",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547255-caf-file-header"
      ],
      "title": "Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType2398",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType24",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType25",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType2997",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType2997Drop",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType30",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType30Drop",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType50",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType5994",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType5994Drop",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType60",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType60Drop",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeTypeNone"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType2398",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType24",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType25",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType2997",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType2997Drop",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType30",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType30Drop",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType50",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType5994",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType5994Drop",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType60",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType60Drop",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeTypeNone"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFFormatFlags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFRegionFlags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547266-caf-file-chunk-types",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547272-caf-file-marker-types",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547255-caf-file-header"
              ],
              "title": "Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType30Drop/title",
          "value": "kCAF_SMPTE_TimeType30Drop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType30Drop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_SMPTE_TimeType30Drop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType5994Drop/title",
          "value": "kCAF_SMPTE_TimeType5994Drop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType5994Drop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_SMPTE_TimeType5994Drop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType2997Drop/title",
          "value": "kCAF_SMPTE_TimeType2997Drop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType2997Drop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_SMPTE_TimeType2997Drop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType30/title",
          "value": "kCAF_SMPTE_TimeType30"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType30/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_SMPTE_TimeType30"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType50/title",
          "value": "kCAF_SMPTE_TimeType50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_SMPTE_TimeType50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType2997/title",
          "value": "kCAF_SMPTE_TimeType2997"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType2997/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_SMPTE_TimeType2997"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFFormatFlags/title",
          "value": "CAFFormatFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFFormatFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFFormatFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFFormatFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFFormatFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeTypeNone/title",
          "value": "kCAF_SMPTE_TimeTypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeTypeNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_SMPTE_TimeTypeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType60/title",
          "value": "kCAF_SMPTE_TimeType60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_SMPTE_TimeType60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType60Drop/title",
          "value": "kCAF_SMPTE_TimeType60Drop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType60Drop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_SMPTE_TimeType60Drop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType5994/title",
          "value": "kCAF_SMPTE_TimeType5994"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType5994/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_SMPTE_TimeType5994"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType2398/title",
          "value": "kCAF_SMPTE_TimeType2398"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType2398/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_SMPTE_TimeType2398"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType25/title",
          "value": "kCAF_SMPTE_TimeType25"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType25/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_SMPTE_TimeType25"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType24/title",
          "value": "kCAF_SMPTE_TimeType24"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType24/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_SMPTE_TimeType24"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFRegionFlags/title",
          "value": "CAFRegionFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFRegionFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFRegionFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFRegionFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFRegionFlags"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1547262-caf-file-smpte-time-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1547262-caf-file-smpte-time-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
