{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/core-audio-file-format"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547255-caf-file-header"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CAF File Header"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547262-caf-file-smpte-time-types": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547262-caf-file-smpte-time-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CAF File SMPTE Time Types",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1547262-caf-file-smpte-time-types"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547266-caf-file-chunk-types": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547266-caf-file-chunk-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CAF File Chunk Types",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1547266-caf-file-chunk-types"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547272-caf-file-marker-types": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547272-caf-file-marker-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CAF File Marker Types",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1547272-caf-file-marker-types"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFFormatFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAFFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFFormatFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAFFormatFlags"
        }
      ],
      "role": "symbol",
      "title": "CAFFormatFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/cafformatflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFRegionFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAFRegionFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFRegionFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAFRegionFlags"
        }
      ],
      "role": "symbol",
      "title": "CAFRegionFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/cafregionflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/core-audio-file-format": {
      "abstract": [
        {
          "text": "Parse the structure of Core Audio files.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/core-audio-file-format",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Audio File Format",
      "type": "topic",
      "url": "/documentation/audiotoolbox/core-audio-file-format"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_FileType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_FileType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_FileType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_FileType"
        }
      ],
      "role": "symbol",
      "title": "kCAF_FileType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_filetype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_FileVersion_Initial": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_FileVersion_Initial"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_FileVersion_Initial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_FileVersion_Initial"
        }
      ],
      "role": "symbol",
      "title": "kCAF_FileVersion_Initial",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_fileversion_initial"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFFormatFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFRegionFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547266-caf-file-chunk-types",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547272-caf-file-marker-types",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547262-caf-file-smpte-time-types"
      ],
      "title": "Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_FileType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_FileVersion_Initial"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_FileType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_FileVersion_Initial"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFFormatFlags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFRegionFlags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547266-caf-file-chunk-types",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547272-caf-file-marker-types",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1547262-caf-file-smpte-time-types"
              ],
              "title": "Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_FileType/title",
          "value": "kCAF_FileType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_FileType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_FileType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFFormatFlags/title",
          "value": "CAFFormatFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFFormatFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFFormatFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFFormatFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFFormatFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFRegionFlags/title",
          "value": "CAFRegionFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFRegionFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFRegionFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFRegionFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFRegionFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_FileVersion_Initial/title",
          "value": "kCAF_FileVersion_Initial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_FileVersion_Initial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_FileVersion_Initial"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1547255-caf-file-header"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1547255-caf-file-header"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
