{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-queue-services"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1552630-audio-queue-time-pitch-algorithm"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio Queue Time Pitch Algorithms"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1552627-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1552627-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1552627-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1552629-audio-queue-property-ids": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1552629-audio-queue-property-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Queue Property IDs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1552629-audio-queue-property-ids"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618727-audio-queue-hardware-codec-polic": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618727-audio-queue-hardware-codec-polic",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Queue Hardware Codec Policy",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1618727-audio-queue-hardware-codec-polic"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618733-audio-queue-property-ids": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618733-audio-queue-property-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Queue Property IDs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1618733-audio-queue-property-ids"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueProcessingTapFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueProcessingTapFlags"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueProcessingTapFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueueprocessingtapflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-queue-services": {
      "abstract": [
        {
          "text": "Connect to audio hardware and manage the recording or playback process.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-queue-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Queue Services",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-queue-services"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueTimePitchAlgorithm_Spectral": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueTimePitchAlgorithm_Spectral"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueTimePitchAlgorithm_Spectral",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueTimePitchAlgorithm_Spectral"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueTimePitchAlgorithm_Spectral",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueuetimepitchalgorithm_spectral"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueTimePitchAlgorithm_TimeDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueTimePitchAlgorithm_TimeDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueTimePitchAlgorithm_TimeDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueTimePitchAlgorithm_TimeDomain"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueTimePitchAlgorithm_TimeDomain",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueuetimepitchalgorithm_timedomain"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueTimePitchAlgorithm_Varispeed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueTimePitchAlgorithm_Varispeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueTimePitchAlgorithm_Varispeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueTimePitchAlgorithm_Varispeed"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueTimePitchAlgorithm_Varispeed",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueuetimepitchalgorithm_varispeed"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1552627-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1552629-audio-queue-property-ids",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618733-audio-queue-property-ids",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618727-audio-queue-hardware-codec-polic"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueTimePitchAlgorithm_Spectral",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueTimePitchAlgorithm_TimeDomain",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueTimePitchAlgorithm_Varispeed"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueTimePitchAlgorithm_Spectral",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueTimePitchAlgorithm_TimeDomain",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueTimePitchAlgorithm_Varispeed"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapFlags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1552627-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1552629-audio-queue-property-ids",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618733-audio-queue-property-ids",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618727-audio-queue-hardware-codec-polic"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueTimePitchAlgorithm_Varispeed/title",
          "value": "kAudioQueueTimePitchAlgorithm_Varispeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueTimePitchAlgorithm_Varispeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueTimePitchAlgorithm_Varispeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueProcessingTapFlags/title",
          "value": "AudioQueueProcessingTapFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueProcessingTapFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueProcessingTapFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueProcessingTapFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueProcessingTapFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueTimePitchAlgorithm_TimeDomain/title",
          "value": "kAudioQueueTimePitchAlgorithm_TimeDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueTimePitchAlgorithm_TimeDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueTimePitchAlgorithm_TimeDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueTimePitchAlgorithm_Spectral/title",
          "value": "kAudioQueueTimePitchAlgorithm_Spectral"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueTimePitchAlgorithm_Spectral/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueTimePitchAlgorithm_Spectral"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1552630-audio-queue-time-pitch-algorithm"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1552630-audio-queue-time-pitch-algorithm"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
