{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-queue-services"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1552627-anonymous"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Anonymous"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1552629-audio-queue-property-ids": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1552629-audio-queue-property-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Queue Property IDs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1552629-audio-queue-property-ids"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1552630-audio-queue-time-pitch-algorithm": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1552630-audio-queue-time-pitch-algorithm",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Queue Time Pitch Algorithms",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1552630-audio-queue-time-pitch-algorithm"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618727-audio-queue-hardware-codec-polic": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618727-audio-queue-hardware-codec-polic",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Queue Hardware Codec Policy",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1618727-audio-queue-hardware-codec-polic"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618733-audio-queue-property-ids": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618733-audio-queue-property-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Queue Property IDs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1618733-audio-queue-property-ids"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueDispose(_:_:)": {
      "abstract": [
        {
          "text": "Disposes of an audio queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueDispose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueueRef",
          "text": "AudioQueueRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueDispose(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueDispose"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueDispose(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuedispose(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueuePrime(_:_:_:)": {
      "abstract": [
        {
          "text": "Decodes enqueued buffers in preparation for playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueuePrime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueueRef",
          "text": "AudioQueueRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueuePrime(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueuePrime"
        }
      ],
      "role": "symbol",
      "title": "AudioQueuePrime(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueueprime(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueProcessingTapFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueProcessingTapFlags"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueProcessingTapFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueueprocessingtapflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueReset(_:)": {
      "abstract": [
        {
          "text": "Resets an audio queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueReset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueueRef",
          "text": "AudioQueueRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueReset(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueReset"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueReset(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuereset(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueStop(_:_:)": {
      "abstract": [
        {
          "text": "Stops playing or recording audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueStop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueueRef",
          "text": "AudioQueueRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueStop(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueStop"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueStop(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuestop(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-queue-services": {
      "abstract": [
        {
          "text": "Connect to audio hardware and manage the recording or playback process.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-queue-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Queue Services",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-queue-services"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_BufferEmpty": {
      "abstract": [
        {
          "text": "The audio queue buffer is empty (that is, the ",
          "type": "text"
        },
        {
          "code": "mAudioDataByteSize",
          "type": "codeVoice"
        },
        {
          "text": " field = ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_BufferEmpty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_BufferEmpty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_BufferEmpty"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueErr_BufferEmpty",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueerr_bufferempty"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_BufferEnqueuedTwice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_BufferEnqueuedTwice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_BufferEnqueuedTwice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_BufferEnqueuedTwice"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueErr_BufferEnqueuedTwice",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueerr_bufferenqueuedtwice"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_BufferInQueue": {
      "abstract": [
        {
          "text": "The audio queue buffer cannot be disposed of when it is enqueued.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_BufferInQueue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_BufferInQueue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_BufferInQueue"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueErr_BufferInQueue",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueerr_bufferinqueue"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_CannotStart": {
      "abstract": [
        {
          "text": "The audio queue has encountered a problem and cannot start.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_CannotStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_CannotStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_CannotStart"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueErr_CannotStart",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueerr_cannotstart"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_CannotStartYet": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_CannotStartYet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_CannotStartYet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_CannotStartYet"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueErr_CannotStartYet",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueerr_cannotstartyet"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_CodecNotFound": {
      "abstract": [
        {
          "text": "The requested codec was not found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_CodecNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_CodecNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_CodecNotFound"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueErr_CodecNotFound",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueerr_codecnotfound"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_DisposalPending": {
      "abstract": [
        {
          "text": "The function cannot act on the audio queue because it is being asynchronously disposed of.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_DisposalPending"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_DisposalPending",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_DisposalPending"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueErr_DisposalPending",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueerr_disposalpending"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_EnqueueDuringReset": {
      "abstract": [
        {
          "text": "During a call to the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueReset(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueStop(_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", or ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueDispose(_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " functions, the system does not allow you to enqueue buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_EnqueueDuringReset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_EnqueueDuringReset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_EnqueueDuringReset"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueErr_EnqueueDuringReset",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueerr_enqueueduringreset"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidBuffer": {
      "abstract": [
        {
          "text": "The specified audio queue buffer does not belong to the specified audio queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_InvalidBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_InvalidBuffer"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueErr_InvalidBuffer",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueerr_invalidbuffer"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidCodecAccess": {
      "abstract": [
        {
          "text": "The codec could not be accessed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_InvalidCodecAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidCodecAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_InvalidCodecAccess"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueErr_InvalidCodecAccess",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueerr_invalidcodecaccess"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidDevice": {
      "abstract": [
        {
          "text": "The specified audio hardware device could not be located.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_InvalidDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_InvalidDevice"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueErr_InvalidDevice",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueerr_invaliddevice"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidOfflineMode": {
      "abstract": [
        {
          "text": "The operation requires the audio queue to be in offline mode but it isn’t, or vice versa.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_InvalidOfflineMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidOfflineMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_InvalidOfflineMode"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueErr_InvalidOfflineMode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueerr_invalidofflinemode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidParameter": {
      "abstract": [
        {
          "text": "The specified parameter ID is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_InvalidParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_InvalidParameter"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueErr_InvalidParameter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueerr_invalidparameter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidProperty": {
      "abstract": [
        {
          "text": "The specified property ID is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_InvalidProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_InvalidProperty"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueErr_InvalidProperty",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueerr_invalidproperty"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidPropertySize": {
      "abstract": [
        {
          "text": "The size of the specified property is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_InvalidPropertySize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidPropertySize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_InvalidPropertySize"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueErr_InvalidPropertySize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueerr_invalidpropertysize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidPropertyValue": {
      "abstract": [
        {
          "text": "The property value used is not valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_InvalidPropertyValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidPropertyValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_InvalidPropertyValue"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueErr_InvalidPropertyValue",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueerr_invalidpropertyvalue"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidQueueType": {
      "abstract": [
        {
          "text": "The queue is an input queue but the function can only operate on an output queue, or vice versa.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_InvalidQueueType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidQueueType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_InvalidQueueType"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueErr_InvalidQueueType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueerr_invalidqueuetype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidRunState": {
      "abstract": [
        {
          "text": "The queue is running but the function can only operate on the queue when it is stopped, or vice versa.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_InvalidRunState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidRunState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_InvalidRunState"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueErr_InvalidRunState",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueerr_invalidrunstate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidTapContext": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_InvalidTapContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidTapContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_InvalidTapContext"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueErr_InvalidTapContext",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueerr_invalidtapcontext"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidTapType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_InvalidTapType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidTapType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_InvalidTapType"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueErr_InvalidTapType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueerr_invalidtaptype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_Permissions": {
      "abstract": [
        {
          "text": "You do not have the required permissions to call the function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_Permissions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_Permissions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_Permissions"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueErr_Permissions",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueerr_permissions"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_PrimeTimedOut": {
      "abstract": [
        {
          "text": "During a call to the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueuePrime(_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function, the audio queue’s audio converter failed to convert the requested number of sample frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_PrimeTimedOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_PrimeTimedOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_PrimeTimedOut"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueErr_PrimeTimedOut",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueerr_primetimedout"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_QueueInvalidated": {
      "abstract": [
        {
          "text": "In iOS, the audio server has exited, causing the audio queue to become invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_QueueInvalidated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_QueueInvalidated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_QueueInvalidated"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueErr_QueueInvalidated",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueerr_queueinvalidated"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_RecordUnderrun": {
      "abstract": [
        {
          "text": "During recording, data was lost because there was no enqueued buffer to store it in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_RecordUnderrun"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_RecordUnderrun",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_RecordUnderrun"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueErr_RecordUnderrun",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueerr_recordunderrun"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_TooManyTaps": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_TooManyTaps"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_TooManyTaps",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueErr_TooManyTaps"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueErr_TooManyTaps",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueerr_toomanytaps"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1552630-audio-queue-time-pitch-algorithm",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1552629-audio-queue-property-ids",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618733-audio-queue-property-ids",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618727-audio-queue-hardware-codec-polic"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_BufferEmpty",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_BufferEnqueuedTwice",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_BufferInQueue",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_CannotStart",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_CodecNotFound",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_DisposalPending",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_EnqueueDuringReset",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidBuffer",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidCodecAccess",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidDevice",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidOfflineMode",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidParameter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidProperty",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidPropertySize",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidPropertyValue",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidQueueType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidRunState",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidTapContext",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidTapType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_Permissions",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_PrimeTimedOut",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_QueueInvalidated",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_RecordUnderrun",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_TooManyTaps",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_CannotStartYet"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_BufferEmpty",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_BufferEnqueuedTwice",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_BufferInQueue",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_CannotStart",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_CodecNotFound",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_DisposalPending",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_EnqueueDuringReset",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidBuffer",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidCodecAccess",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidDevice",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidOfflineMode",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidParameter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidProperty",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidPropertySize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidPropertyValue",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidQueueType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidRunState",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidTapContext",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_InvalidTapType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_Permissions",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_PrimeTimedOut",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_QueueInvalidated",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_RecordUnderrun",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_TooManyTaps",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueErr_CannotStartYet"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapFlags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1552630-audio-queue-time-pitch-algorithm",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1552629-audio-queue-property-ids",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618733-audio-queue-property-ids",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618727-audio-queue-hardware-codec-polic"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_InvalidBuffer/title",
          "value": "kAudioQueueErr_InvalidBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_InvalidBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueErr_InvalidBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_PrimeTimedOut/title",
          "value": "kAudioQueueErr_PrimeTimedOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_PrimeTimedOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueErr_PrimeTimedOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_InvalidRunState/title",
          "value": "kAudioQueueErr_InvalidRunState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_InvalidRunState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueErr_InvalidRunState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_RecordUnderrun/title",
          "value": "kAudioQueueErr_RecordUnderrun"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_RecordUnderrun/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueErr_RecordUnderrun"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_InvalidQueueType/title",
          "value": "kAudioQueueErr_InvalidQueueType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_InvalidQueueType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueErr_InvalidQueueType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_BufferEnqueuedTwice/title",
          "value": "kAudioQueueErr_BufferEnqueuedTwice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_BufferEnqueuedTwice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueErr_BufferEnqueuedTwice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_InvalidCodecAccess/title",
          "value": "kAudioQueueErr_InvalidCodecAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_InvalidCodecAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueErr_InvalidCodecAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_TooManyTaps/title",
          "value": "kAudioQueueErr_TooManyTaps"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_TooManyTaps/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueErr_TooManyTaps"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueReset(_:)/title",
          "value": "AudioQueueReset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueReset(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueReset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_InvalidTapType/title",
          "value": "kAudioQueueErr_InvalidTapType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_InvalidTapType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueErr_InvalidTapType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_DisposalPending/title",
          "value": "kAudioQueueErr_DisposalPending"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_DisposalPending/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueErr_DisposalPending"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_InvalidProperty/title",
          "value": "kAudioQueueErr_InvalidProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_InvalidProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueErr_InvalidProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_CodecNotFound/title",
          "value": "kAudioQueueErr_CodecNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_CodecNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueErr_CodecNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_InvalidTapContext/title",
          "value": "kAudioQueueErr_InvalidTapContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_InvalidTapContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueErr_InvalidTapContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueStop(_:_:)/title",
          "value": "AudioQueueStop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueStop(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueStop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_InvalidPropertyValue/title",
          "value": "kAudioQueueErr_InvalidPropertyValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_InvalidPropertyValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueErr_InvalidPropertyValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_InvalidDevice/title",
          "value": "kAudioQueueErr_InvalidDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_InvalidDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueErr_InvalidDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueDispose(_:_:)/title",
          "value": "AudioQueueDispose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueDispose(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueDispose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueProcessingTapFlags/title",
          "value": "AudioQueueProcessingTapFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueProcessingTapFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueProcessingTapFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueProcessingTapFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueProcessingTapFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueuePrime(_:_:_:)/title",
          "value": "AudioQueuePrime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueuePrime(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueuePrime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_BufferEmpty/title",
          "value": "kAudioQueueErr_BufferEmpty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_BufferEmpty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueErr_BufferEmpty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_CannotStartYet/title",
          "value": "kAudioQueueErr_CannotStartYet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_CannotStartYet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueErr_CannotStartYet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_Permissions/title",
          "value": "kAudioQueueErr_Permissions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_Permissions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueErr_Permissions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_BufferInQueue/title",
          "value": "kAudioQueueErr_BufferInQueue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_BufferInQueue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueErr_BufferInQueue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_EnqueueDuringReset/title",
          "value": "kAudioQueueErr_EnqueueDuringReset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_EnqueueDuringReset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueErr_EnqueueDuringReset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_CannotStart/title",
          "value": "kAudioQueueErr_CannotStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_CannotStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueErr_CannotStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_InvalidPropertySize/title",
          "value": "kAudioQueueErr_InvalidPropertySize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_InvalidPropertySize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueErr_InvalidPropertySize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_InvalidParameter/title",
          "value": "kAudioQueueErr_InvalidParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_InvalidParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueErr_InvalidParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_InvalidOfflineMode/title",
          "value": "kAudioQueueErr_InvalidOfflineMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_InvalidOfflineMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueErr_InvalidOfflineMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_QueueInvalidated/title",
          "value": "kAudioQueueErr_QueueInvalidated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueErr_QueueInvalidated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueErr_QueueInvalidated"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1552627-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1552627-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
