{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-converter-services"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559930-audio-converter-errors"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio Converter Errors"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533972-converter_audio_unit_properties": {
      "abstract": [
        {
          "text": "Properties for the Apple AUConverter audio unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533972-converter_audio_unit_properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Converter Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1533972-converter_audio_unit_properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559925-audio-converter-properties-macos": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559925-audio-converter-properties-macos",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Converter Properties (macOS)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1559925-audio-converter-properties-macos"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559931-audio-converter-dithering-algori": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559931-audio-converter-dithering-algori",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Converter Dithering Algorithms",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1559931-audio-converter-dithering-algori"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes": {
      "abstract": [
        {
          "text": "Audio data format converter audio unit subtypes for audio units provided by Apple.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Converter Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584145-converter_audio_unit_subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterFillComplexBuffer(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Converts audio data supplied by a callback function, supporting non-interleaved and packetized formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioConverterFillComplexBuffer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterRef",
          "text": "AudioConverterRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterComplexInputDataProc",
          "text": "AudioConverterComplexInputDataProc"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioBufferList",
          "text": "AudioBufferList"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioStreamPacketDescription",
          "text": "AudioStreamPacketDescription"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterFillComplexBuffer(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioConverterFillComplexBuffer"
        }
      ],
      "role": "symbol",
      "title": "AudioConverterFillComplexBuffer(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioconverterfillcomplexbuffer(_:_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterNew(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a new audio converter object based on specified audio formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioConverterNew"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioStreamBasicDescription",
          "text": "AudioStreamBasicDescription"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioStreamBasicDescription",
          "text": "AudioStreamBasicDescription"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterRef",
          "text": "AudioConverterRef"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterNew(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioConverterNew"
        }
      ],
      "role": "symbol",
      "title": "AudioConverterNew(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioconverternew(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-converter-services": {
      "abstract": [
        {
          "text": "Convert between linear PCM audio formats, and between linear PCM and compressed formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-converter-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Converter Services",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-converter-services"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_BadPropertySizeError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterErr_BadPropertySizeError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_BadPropertySizeError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterErr_BadPropertySizeError"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterErr_BadPropertySizeError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconvertererr_badpropertysizeerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_FormatNotSupported": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterErr_FormatNotSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_FormatNotSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterErr_FormatNotSupported"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterErr_FormatNotSupported",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconvertererr_formatnotsupported"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_HardwareInUse": {
      "abstract": [
        {
          "text": "Returned from the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterFillComplexBuffer(_:_:_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function if the underlying hardware codec has become unavailable, probably due to an audio interruption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterErr_HardwareInUse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_HardwareInUse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterErr_HardwareInUse"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterErr_HardwareInUse",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconvertererr_hardwareinuse"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_InputSampleRateOutOfRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterErr_InputSampleRateOutOfRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_InputSampleRateOutOfRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterErr_InputSampleRateOutOfRange"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterErr_InputSampleRateOutOfRange",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconvertererr_inputsamplerateoutofrange"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_InvalidInputSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterErr_InvalidInputSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_InvalidInputSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterErr_InvalidInputSize"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterErr_InvalidInputSize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconvertererr_invalidinputsize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_InvalidOutputSize": {
      "abstract": [
        {
          "text": "The byte size is not an integer multiple of the frame size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterErr_InvalidOutputSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_InvalidOutputSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterErr_InvalidOutputSize"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterErr_InvalidOutputSize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconvertererr_invalidoutputsize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_NoHardwarePermission": {
      "abstract": [
        {
          "text": "Returned from the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterNew(_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function if the new converter would use a hardware codec which the application does not have permission to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterErr_NoHardwarePermission"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_NoHardwarePermission",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterErr_NoHardwarePermission"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterErr_NoHardwarePermission",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconvertererr_nohardwarepermission"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_OperationNotSupported": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterErr_OperationNotSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_OperationNotSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterErr_OperationNotSupported"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterErr_OperationNotSupported",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconvertererr_operationnotsupported"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_OutputSampleRateOutOfRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterErr_OutputSampleRateOutOfRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_OutputSampleRateOutOfRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterErr_OutputSampleRateOutOfRange"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterErr_OutputSampleRateOutOfRange",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconvertererr_outputsamplerateoutofrange"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_PropertyNotSupported": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterErr_PropertyNotSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_PropertyNotSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterErr_PropertyNotSupported"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterErr_PropertyNotSupported",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconvertererr_propertynotsupported"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_RequiresPacketDescriptionsError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterErr_RequiresPacketDescriptionsError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_RequiresPacketDescriptionsError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterErr_RequiresPacketDescriptionsError"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterErr_RequiresPacketDescriptionsError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconvertererr_requirespacketdescriptionserror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_UnspecifiedError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterErr_UnspecifiedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_UnspecifiedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterErr_UnspecifiedError"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterErr_UnspecifiedError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconvertererr_unspecifiederror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533972-converter_audio_unit_properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559931-audio-converter-dithering-algori",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559925-audio-converter-properties-macos"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_BadPropertySizeError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_FormatNotSupported",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_HardwareInUse",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_InputSampleRateOutOfRange",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_InvalidInputSize",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_InvalidOutputSize",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_NoHardwarePermission",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_OperationNotSupported",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_OutputSampleRateOutOfRange",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_PropertyNotSupported",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_RequiresPacketDescriptionsError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_UnspecifiedError"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_BadPropertySizeError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_FormatNotSupported",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_HardwareInUse",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_InputSampleRateOutOfRange",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_InvalidInputSize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_InvalidOutputSize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_NoHardwarePermission",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_OperationNotSupported",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_OutputSampleRateOutOfRange",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_PropertyNotSupported",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_RequiresPacketDescriptionsError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterErr_UnspecifiedError"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533972-converter_audio_unit_properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559931-audio-converter-dithering-algori",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559925-audio-converter-properties-macos"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterFillComplexBuffer(_:_:_:_:_:_:)/title",
          "value": "AudioConverterFillComplexBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterFillComplexBuffer(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioConverterFillComplexBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterErr_OutputSampleRateOutOfRange/title",
          "value": "kAudioConverterErr_OutputSampleRateOutOfRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterErr_OutputSampleRateOutOfRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterErr_OutputSampleRateOutOfRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterErr_UnspecifiedError/title",
          "value": "kAudioConverterErr_UnspecifiedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterErr_UnspecifiedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterErr_UnspecifiedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterErr_InvalidInputSize/title",
          "value": "kAudioConverterErr_InvalidInputSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterErr_InvalidInputSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterErr_InvalidInputSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterErr_InvalidOutputSize/title",
          "value": "kAudioConverterErr_InvalidOutputSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterErr_InvalidOutputSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterErr_InvalidOutputSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterErr_NoHardwarePermission/title",
          "value": "kAudioConverterErr_NoHardwarePermission"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterErr_NoHardwarePermission/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterErr_NoHardwarePermission"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterNew(_:_:_:)/title",
          "value": "AudioConverterNew"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterNew(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioConverterNew"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterErr_PropertyNotSupported/title",
          "value": "kAudioConverterErr_PropertyNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterErr_PropertyNotSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterErr_PropertyNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterErr_BadPropertySizeError/title",
          "value": "kAudioConverterErr_BadPropertySizeError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterErr_BadPropertySizeError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterErr_BadPropertySizeError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterErr_HardwareInUse/title",
          "value": "kAudioConverterErr_HardwareInUse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterErr_HardwareInUse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterErr_HardwareInUse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterErr_OperationNotSupported/title",
          "value": "kAudioConverterErr_OperationNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterErr_OperationNotSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterErr_OperationNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterErr_InputSampleRateOutOfRange/title",
          "value": "kAudioConverterErr_InputSampleRateOutOfRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterErr_InputSampleRateOutOfRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterErr_InputSampleRateOutOfRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterErr_FormatNotSupported/title",
          "value": "kAudioConverterErr_FormatNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterErr_FormatNotSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterErr_FormatNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterErr_RequiresPacketDescriptionsError/title",
          "value": "kAudioConverterErr_RequiresPacketDescriptionsError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterErr_RequiresPacketDescriptionsError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterErr_RequiresPacketDescriptionsError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1559930-audio-converter-errors"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1559930-audio-converter-errors"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
