{
  "abstract": [
    {
      "text": "Audio converter properties, used with the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterGetPropertyInfo(_:_:_:_:)",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ", ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterGetProperty(_:_:_:_:)",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ", and ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterSetProperty(_:_:_:_:)",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " functions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-converter-services"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559928-audio-converter-properties"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio Converter Properties"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559923-sample-rate-conversion-complexit": {
      "abstract": [
        {
          "text": "Specifiers for the sample rate conversion algorithm, used for the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterComplexity",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559923-sample-rate-conversion-complexit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sample Rate Conversion Complexity Identifiers",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1559923-sample-rate-conversion-complexit"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559924-sample-rate-conversion-quality-i": {
      "abstract": [
        {
          "text": "Specifiers for sample rate conversion quality, used for the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterQuality",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559924-sample-rate-conversion-quality-i",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sample Rate Conversion Quality Identifiers",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1559924-sample-rate-conversion-quality-i"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559927-converter-priming-constants": {
      "abstract": [
        {
          "text": "Constants used with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPrimeMethod",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559927-converter-priming-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Converter Priming Constants",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1559927-converter-priming-constants"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterConvertBuffer(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Converts audio data from one linear PCM format to another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioConverterConvertBuffer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterRef",
          "text": "AudioConverterRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterConvertBuffer(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioConverterConvertBuffer"
        }
      ],
      "role": "symbol",
      "title": "AudioConverterConvertBuffer(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioconverterconvertbuffer(_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterGetProperty(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Gets an audio converter property value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioConverterGetProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterRef",
          "text": "AudioConverterRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterGetProperty(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioConverterGetProperty"
        }
      ],
      "role": "symbol",
      "title": "AudioConverterGetProperty(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioconvertergetproperty(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterGetPropertyInfo(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Gets information about an audio converter property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioConverterGetPropertyInfo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterRef",
          "text": "AudioConverterRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Darwin0A7BooleanV",
          "text": "DarwinBoolean"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterGetPropertyInfo(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioConverterGetPropertyInfo"
        }
      ],
      "role": "symbol",
      "title": "AudioConverterGetPropertyInfo(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioconvertergetpropertyinfo(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterPrimeInfo": {
      "abstract": [
        {
          "text": "Specifies priming information for an audio converter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioConverterPrimeInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterPrimeInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioConverterPrimeInfo"
        }
      ],
      "role": "symbol",
      "title": "AudioConverterPrimeInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioconverterprimeinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterSetProperty(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Sets the value of an audio converter object property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioConverterSetProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterRef",
          "text": "AudioConverterRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterSetProperty(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioConverterSetProperty"
        }
      ],
      "role": "symbol",
      "title": "AudioConverterSetProperty(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioconvertersetproperty(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-converter-services": {
      "abstract": [
        {
          "text": "Convert between linear PCM audio formats, and between linear PCM and compressed formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-converter-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Converter Services",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-converter-services"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterApplicableEncodeBitRates": {
      "abstract": [
        {
          "text": "An array of ",
          "type": "text"
        },
        {
          "code": "AudioValueRange",
          "type": "codeVoice"
        },
        {
          "text": " structures that describes applicable bit rates based on current settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterApplicableEncodeBitRates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterApplicableEncodeBitRates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterApplicableEncodeBitRates"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterApplicableEncodeBitRates",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterapplicableencodebitrates"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterApplicableEncodeSampleRates": {
      "abstract": [
        {
          "text": "An array of ",
          "type": "text"
        },
        {
          "code": "AudioValueRange",
          "type": "codeVoice"
        },
        {
          "text": " structures that describes applicable sample rates based on current settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterApplicableEncodeSampleRates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterApplicableEncodeSampleRates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterApplicableEncodeSampleRates"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterApplicableEncodeSampleRates",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterapplicableencodesamplerates"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterAvailableEncodeBitRates": {
      "abstract": [
        {
          "text": "An array of ",
          "type": "text"
        },
        {
          "code": "AudioValueRange",
          "type": "codeVoice"
        },
        {
          "text": " structures that describes the available bit rates based on the input format. You can determine the available bit rates using Audio Format Services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterAvailableEncodeBitRates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterAvailableEncodeBitRates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterAvailableEncodeBitRates"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterAvailableEncodeBitRates",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverteravailableencodebitrates"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterAvailableEncodeChannelLayoutTags": {
      "abstract": [
        {
          "text": "An array of ",
          "type": "text"
        },
        {
          "code": "AudioChannelLayoutTag",
          "type": "codeVoice"
        },
        {
          "text": " values for the format and number of channels specified in the encoder’s input format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterAvailableEncodeChannelLayoutTags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterAvailableEncodeChannelLayoutTags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterAvailableEncodeChannelLayoutTags"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterAvailableEncodeChannelLayoutTags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverteravailableencodechannellayouttags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterAvailableEncodeSampleRates": {
      "abstract": [
        {
          "text": "An array of ",
          "type": "text"
        },
        {
          "code": "AudioValueRange",
          "type": "codeVoice"
        },
        {
          "text": " structures that describes the available sample rates based on the input format. You can determine the available sample rates using Audio Format Services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterAvailableEncodeSampleRates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterAvailableEncodeSampleRates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterAvailableEncodeSampleRates"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterAvailableEncodeSampleRates",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverteravailableencodesamplerates"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterChannelMap": {
      "abstract": [
        {
          "text": "An array of ",
          "type": "text"
        },
        {
          "code": "SInt32",
          "type": "codeVoice"
        },
        {
          "text": " values that specify an input-to-output channel mapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterChannelMap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterChannelMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterChannelMap"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterChannelMap",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterchannelmap"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterCodecQuality": {
      "abstract": [
        {
          "text": "The rendering quality of a codec. A ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterCodecQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterCodecQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterCodecQuality"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterCodecQuality",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconvertercodecquality"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterCompressionMagicCookie": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "void*",
          "type": "codeVoice"
        },
        {
          "text": " value that points to memory set up by the caller. This property is returned by the converter so that your application may store it along with the output data. This property can then be passed back to the converter for decompression at a later time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterCompressionMagicCookie"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterCompressionMagicCookie",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterCompressionMagicCookie"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterCompressionMagicCookie",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconvertercompressionmagiccookie"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterCurrentInputStreamDescription": {
      "abstract": [
        {
          "text": "The current, completely specified input ",
          "type": "text"
        },
        {
          "code": "AudioStreamBasicDescription",
          "type": "codeVoice"
        },
        {
          "text": " structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterCurrentInputStreamDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterCurrentInputStreamDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterCurrentInputStreamDescription"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterCurrentInputStreamDescription",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconvertercurrentinputstreamdescription"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterCurrentOutputStreamDescription": {
      "abstract": [
        {
          "text": "The current, completely specified output ",
          "type": "text"
        },
        {
          "code": "AudioStreamBasicDescription",
          "type": "codeVoice"
        },
        {
          "text": " structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterCurrentOutputStreamDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterCurrentOutputStreamDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterCurrentOutputStreamDescription"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterCurrentOutputStreamDescription",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconvertercurrentoutputstreamdescription"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterDecompressionMagicCookie": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "void*",
          "type": "codeVoice"
        },
        {
          "text": " value that points to memory set up by the caller. This property is required by some audio data formats in order to decompress the input data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterDecompressionMagicCookie"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterDecompressionMagicCookie",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterDecompressionMagicCookie"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterDecompressionMagicCookie",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterdecompressionmagiccookie"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterEncodeAdjustableSampleRate": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "Float64",
          "type": "codeVoice"
        },
        {
          "text": " value that specifies an output sample rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterEncodeAdjustableSampleRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterEncodeAdjustableSampleRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterEncodeAdjustableSampleRate"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterEncodeAdjustableSampleRate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterencodeadjustablesamplerate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterEncodeBitRate": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value containing the number of bits per second to aim for when encoding data. Some decoders also allow you to query this property to discover the bit rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterEncodeBitRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterEncodeBitRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterEncodeBitRate"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterEncodeBitRate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterencodebitrate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterInputChannelLayout": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "AudioChannelLayout",
          "type": "codeVoice"
        },
        {
          "text": " structure that specifies an audio converter’s input channel layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterInputChannelLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterInputChannelLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterInputChannelLayout"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterInputChannelLayout",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterinputchannellayout"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterOutputChannelLayout": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "AudioChannelLayout",
          "type": "codeVoice"
        },
        {
          "text": " structure that specifies an audio converter’s output channel layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterOutputChannelLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterOutputChannelLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterOutputChannelLayout"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterOutputChannelLayout",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverteroutputchannellayout"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPrimeInfo": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterPrimeInfo",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterPrimeInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPrimeInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterPrimeInfo"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterPrimeInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterprimeinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPrimeMethod": {
      "abstract": [
        {
          "text": "The priming method, usually for sample-rate conversion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterPrimeMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPrimeMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterPrimeMethod"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterPrimeMethod",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterprimemethod"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyBitDepthHint": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value that designates the source bit depth to preserve.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyBitDepthHint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyBitDepthHint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyBitDepthHint"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterPropertyBitDepthHint",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterpropertybitdepthhint"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyCalculateInputBufferSize": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value that on input holds a size, in bytes, that is desired for the output data. On output, it holds the size, in bytes, of the input buffer required to generate that much output data. Note that some converters cannot do this calculation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyCalculateInputBufferSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyCalculateInputBufferSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyCalculateInputBufferSize"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterPropertyCalculateInputBufferSize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterpropertycalculateinputbuffersize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyCalculateOutputBufferSize": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value that on input holds a size, in bytes, that is desired for the input data. On output, it holds the size, in bytes, of the output buffer required to hold the output data to be generated. Some converters cannot do this calculation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyCalculateOutputBufferSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyCalculateOutputBufferSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyCalculateOutputBufferSize"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterPropertyCalculateOutputBufferSize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterpropertycalculateoutputbuffersize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyCanResumeFromInterruption": {
      "abstract": [
        {
          "text": "Indicates whether the underlying codec supports resumption of processing following an audio interruption. A read-only ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyCanResumeFromInterruption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyCanResumeFromInterruption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyCanResumeFromInterruption"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterPropertyCanResumeFromInterruption",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterpropertycanresumefrominterruption"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyFormatList": {
      "abstract": [
        {
          "text": "An array of ",
          "type": "text"
        },
        {
          "code": "AudioFormatListItem",
          "type": "codeVoice"
        },
        {
          "text": " structures that describes the set of data formats produced by the encoder end of an audio converter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyFormatList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyFormatList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyFormatList"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterPropertyFormatList",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterpropertyformatlist"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyInputCodecParameters": {
      "abstract": [
        {
          "text": "The value of this property varies from format to format and is considered private to the format. It is treated as a buffer of untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyInputCodecParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyInputCodecParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyInputCodecParameters"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterPropertyInputCodecParameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterpropertyinputcodecparameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMaximumInputBufferSize": {
      "abstract": [
        {
          "text": "Deprecated. The audio converter input callback may be passed any number of packets of data. If fewer are packets are returned than required, then the input proc is called again. If more packets are passed than required, they remain in the client’s buffer and are consumed as needed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyMaximumInputBufferSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMaximumInputBufferSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyMaximumInputBufferSize"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterPropertyMaximumInputBufferSize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterpropertymaximuminputbuffersize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMaximumInputPacketSize": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value that indicates the size, in bytes, of the largest single packet of data in the input format. This is mostly useful for variable bit rate compressed data (decoders).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyMaximumInputPacketSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMaximumInputPacketSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyMaximumInputPacketSize"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterPropertyMaximumInputPacketSize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterpropertymaximuminputpacketsize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMaximumOutputPacketSize": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value that indicates the size, in bytes, of the largest single packet of data in the output format. This is mostly useful for variable bit rate compressed data (encoders).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyMaximumOutputPacketSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMaximumOutputPacketSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyMaximumOutputPacketSize"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterPropertyMaximumOutputPacketSize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterpropertymaximumoutputpacketsize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMinimumInputBufferSize": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value that indicates the size, in bytes, of the smallest buffer of input data that can be supplied via the audio converter input callback or as the input to the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterConvertBuffer(_:_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyMinimumInputBufferSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMinimumInputBufferSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyMinimumInputBufferSize"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterPropertyMinimumInputBufferSize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterpropertyminimuminputbuffersize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMinimumOutputBufferSize": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value that indicates the size, in bytes, of the smallest buffer of output data that can be supplied to AudioConverterFillComplexBuffer or as the output to AudioConverterConvertBuffer",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyMinimumOutputBufferSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMinimumOutputBufferSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyMinimumOutputBufferSize"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterPropertyMinimumOutputBufferSize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterpropertyminimumoutputbuffersize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyOutputCodecParameters": {
      "abstract": [
        {
          "text": "The value of this property varies from format to format and is considered private to the format. It is treated as a buffer of untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyOutputCodecParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyOutputCodecParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyOutputCodecParameters"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterPropertyOutputCodecParameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterpropertyoutputcodecparameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertySettings": {
      "abstract": [
        {
          "text": "An array (of type ",
          "type": "text"
        },
        {
          "code": "CFArray",
          "type": "codeVoice"
        },
        {
          "text": ") of property settings for converters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertySettings"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertySettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertySettings"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterPropertySettings",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterpropertysettings"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterAlgorithm": {
      "abstract": [
        {
          "text": "A value that indicates the sample rate conversion algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterSampleRateConverterAlgorithm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterAlgorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterSampleRateConverterAlgorithm"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterSampleRateConverterAlgorithm",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconvertersamplerateconverteralgorithm"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterComplexity": {
      "abstract": [
        {
          "text": "The sample rate conversion algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterSampleRateConverterComplexity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterComplexity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterSampleRateConverterComplexity"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterSampleRateConverterComplexity",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconvertersamplerateconvertercomplexity"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterInitialPhase": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "Float64",
          "type": "codeVoice"
        },
        {
          "text": " value equal to ",
          "type": "text"
        },
        {
          "code": "0.0",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterSampleRateConverterInitialPhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterInitialPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterSampleRateConverterInitialPhase"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterSampleRateConverterInitialPhase",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconvertersamplerateconverterinitialphase"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterQuality": {
      "abstract": [
        {
          "text": "The rendering quality of the sample rate converter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterSampleRateConverterQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterSampleRateConverterQuality"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterSampleRateConverterQuality",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconvertersamplerateconverterquality"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559927-converter-priming-constants",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559924-sample-rate-conversion-quality-i",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559923-sample-rate-conversion-complexit"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMinimumInputBufferSize",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMinimumOutputBufferSize",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMaximumInputBufferSize",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMaximumInputPacketSize",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMaximumOutputPacketSize",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyCalculateInputBufferSize",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyCalculateOutputBufferSize",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyInputCodecParameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyOutputCodecParameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterAlgorithm",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterComplexity",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterQuality",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterInitialPhase",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterCodecQuality",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPrimeMethod",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPrimeInfo",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterChannelMap",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterDecompressionMagicCookie",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterCompressionMagicCookie",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterEncodeBitRate",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterEncodeAdjustableSampleRate",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterInputChannelLayout",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterOutputChannelLayout",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterApplicableEncodeBitRates",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterAvailableEncodeBitRates",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterApplicableEncodeSampleRates",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterAvailableEncodeSampleRates",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterAvailableEncodeChannelLayoutTags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterCurrentOutputStreamDescription",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterCurrentInputStreamDescription",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertySettings",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyBitDepthHint",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyFormatList",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyCanResumeFromInterruption"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMinimumInputBufferSize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMinimumOutputBufferSize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMaximumInputBufferSize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMaximumInputPacketSize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMaximumOutputPacketSize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyCalculateInputBufferSize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyCalculateOutputBufferSize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyInputCodecParameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyOutputCodecParameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterAlgorithm",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterComplexity",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterQuality",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterInitialPhase",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterCodecQuality",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPrimeMethod",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPrimeInfo",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterChannelMap",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterDecompressionMagicCookie",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterCompressionMagicCookie",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterEncodeBitRate",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterEncodeAdjustableSampleRate",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterInputChannelLayout",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterOutputChannelLayout",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterApplicableEncodeBitRates",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterAvailableEncodeBitRates",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterApplicableEncodeSampleRates",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterAvailableEncodeSampleRates",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterAvailableEncodeChannelLayoutTags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterCurrentOutputStreamDescription",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterCurrentInputStreamDescription",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertySettings",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyBitDepthHint",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyFormatList",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyCanResumeFromInterruption"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559927-converter-priming-constants",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559924-sample-rate-conversion-quality-i",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559923-sample-rate-conversion-complexit"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyBitDepthHint/title",
          "value": "kAudioConverterPropertyBitDepthHint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyBitDepthHint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterPropertyBitDepthHint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyMaximumOutputPacketSize/title",
          "value": "kAudioConverterPropertyMaximumOutputPacketSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyMaximumOutputPacketSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterPropertyMaximumOutputPacketSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyCalculateInputBufferSize/title",
          "value": "kAudioConverterPropertyCalculateInputBufferSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyCalculateInputBufferSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterPropertyCalculateInputBufferSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterAvailableEncodeSampleRates/title",
          "value": "kAudioConverterAvailableEncodeSampleRates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterAvailableEncodeSampleRates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterAvailableEncodeSampleRates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyFormatList/title",
          "value": "kAudioConverterPropertyFormatList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyFormatList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterPropertyFormatList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterDecompressionMagicCookie/title",
          "value": "kAudioConverterDecompressionMagicCookie"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterDecompressionMagicCookie/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterDecompressionMagicCookie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyMinimumInputBufferSize/title",
          "value": "kAudioConverterPropertyMinimumInputBufferSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyMinimumInputBufferSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterPropertyMinimumInputBufferSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterEncodeAdjustableSampleRate/title",
          "value": "kAudioConverterEncodeAdjustableSampleRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterEncodeAdjustableSampleRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterEncodeAdjustableSampleRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterApplicableEncodeSampleRates/title",
          "value": "kAudioConverterApplicableEncodeSampleRates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterApplicableEncodeSampleRates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterApplicableEncodeSampleRates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterAvailableEncodeBitRates/title",
          "value": "kAudioConverterAvailableEncodeBitRates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterAvailableEncodeBitRates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterAvailableEncodeBitRates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterCodecQuality/title",
          "value": "kAudioConverterCodecQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterCodecQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterCodecQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterChannelMap/title",
          "value": "kAudioConverterChannelMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterChannelMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterChannelMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyMaximumInputBufferSize/title",
          "value": "kAudioConverterPropertyMaximumInputBufferSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyMaximumInputBufferSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterPropertyMaximumInputBufferSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterGetProperty(_:_:_:_:)/title",
          "value": "AudioConverterGetProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterGetProperty(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioConverterGetProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPrimeMethod/title",
          "value": "kAudioConverterPrimeMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPrimeMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterPrimeMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertySettings/title",
          "value": "kAudioConverterPropertySettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertySettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterPropertySettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterPrimeInfo/title",
          "value": "AudioConverterPrimeInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterPrimeInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioConverterPrimeInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterPrimeInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioConverterPrimeInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterCurrentInputStreamDescription/title",
          "value": "kAudioConverterCurrentInputStreamDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterCurrentInputStreamDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterCurrentInputStreamDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyMaximumInputPacketSize/title",
          "value": "kAudioConverterPropertyMaximumInputPacketSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyMaximumInputPacketSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterPropertyMaximumInputPacketSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterApplicableEncodeBitRates/title",
          "value": "kAudioConverterApplicableEncodeBitRates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterApplicableEncodeBitRates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterApplicableEncodeBitRates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyCanResumeFromInterruption/title",
          "value": "kAudioConverterPropertyCanResumeFromInterruption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyCanResumeFromInterruption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterPropertyCanResumeFromInterruption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyOutputCodecParameters/title",
          "value": "kAudioConverterPropertyOutputCodecParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyOutputCodecParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterPropertyOutputCodecParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPrimeInfo/title",
          "value": "kAudioConverterPrimeInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPrimeInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterPrimeInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyInputCodecParameters/title",
          "value": "kAudioConverterPropertyInputCodecParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyInputCodecParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterPropertyInputCodecParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterAvailableEncodeChannelLayoutTags/title",
          "value": "kAudioConverterAvailableEncodeChannelLayoutTags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterAvailableEncodeChannelLayoutTags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterAvailableEncodeChannelLayoutTags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterCurrentOutputStreamDescription/title",
          "value": "kAudioConverterCurrentOutputStreamDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterCurrentOutputStreamDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterCurrentOutputStreamDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterEncodeBitRate/title",
          "value": "kAudioConverterEncodeBitRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterEncodeBitRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterEncodeBitRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyCalculateOutputBufferSize/title",
          "value": "kAudioConverterPropertyCalculateOutputBufferSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyCalculateOutputBufferSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterPropertyCalculateOutputBufferSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterSetProperty(_:_:_:_:)/title",
          "value": "AudioConverterSetProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterSetProperty(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioConverterSetProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterInputChannelLayout/title",
          "value": "kAudioConverterInputChannelLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterInputChannelLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterInputChannelLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyMinimumOutputBufferSize/title",
          "value": "kAudioConverterPropertyMinimumOutputBufferSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyMinimumOutputBufferSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterPropertyMinimumOutputBufferSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterOutputChannelLayout/title",
          "value": "kAudioConverterOutputChannelLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterOutputChannelLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterOutputChannelLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterSampleRateConverterInitialPhase/title",
          "value": "kAudioConverterSampleRateConverterInitialPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterSampleRateConverterInitialPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterSampleRateConverterInitialPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterSampleRateConverterQuality/title",
          "value": "kAudioConverterSampleRateConverterQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterSampleRateConverterQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterSampleRateConverterQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterCompressionMagicCookie/title",
          "value": "kAudioConverterCompressionMagicCookie"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterCompressionMagicCookie/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterCompressionMagicCookie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterGetPropertyInfo(_:_:_:_:)/title",
          "value": "AudioConverterGetPropertyInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterGetPropertyInfo(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioConverterGetPropertyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterConvertBuffer(_:_:_:_:_:)/title",
          "value": "AudioConverterConvertBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterConvertBuffer(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioConverterConvertBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterSampleRateConverterAlgorithm/title",
          "value": "kAudioConverterSampleRateConverterAlgorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterSampleRateConverterAlgorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterSampleRateConverterAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterSampleRateConverterComplexity/title",
          "value": "kAudioConverterSampleRateConverterComplexity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterSampleRateConverterComplexity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterSampleRateConverterComplexity"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1559928-audio-converter-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1559928-audio-converter-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
