{
  "abstract": [
    {
      "text": "Specifiers for sample rate conversion quality, used for the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterQuality",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " property.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-converter-services"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559924-sample-rate-conversion-quality-i"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Sample Rate Conversion Quality Identifiers"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Higher-quality sample-rate conversions entail higher processing cost.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559923-sample-rate-conversion-complexit": {
      "abstract": [
        {
          "text": "Specifiers for the sample rate conversion algorithm, used for the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterComplexity",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559923-sample-rate-conversion-complexit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sample Rate Conversion Complexity Identifiers",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1559923-sample-rate-conversion-complexit"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559927-converter-priming-constants": {
      "abstract": [
        {
          "text": "Constants used with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPrimeMethod",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559927-converter-priming-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Converter Priming Constants",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1559927-converter-priming-constants"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559928-audio-converter-properties": {
      "abstract": [
        {
          "text": "Audio converter properties, used with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterGetPropertyInfo(_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterGetProperty(_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterSetProperty(_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559928-audio-converter-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Converter Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1559928-audio-converter-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterGetProperty(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Gets an audio converter property value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioConverterGetProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterRef",
          "text": "AudioConverterRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterGetProperty(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioConverterGetProperty"
        }
      ],
      "role": "symbol",
      "title": "AudioConverterGetProperty(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioconvertergetproperty(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterGetPropertyInfo(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Gets information about an audio converter property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioConverterGetPropertyInfo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterRef",
          "text": "AudioConverterRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Darwin0A7BooleanV",
          "text": "DarwinBoolean"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterGetPropertyInfo(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioConverterGetPropertyInfo"
        }
      ],
      "role": "symbol",
      "title": "AudioConverterGetPropertyInfo(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioconvertergetpropertyinfo(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterSetProperty(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Sets the value of an audio converter object property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioConverterSetProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterRef",
          "text": "AudioConverterRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterSetProperty(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioConverterSetProperty"
        }
      ],
      "role": "symbol",
      "title": "AudioConverterSetProperty(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioconvertersetproperty(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-converter-services": {
      "abstract": [
        {
          "text": "Convert between linear PCM audio formats, and between linear PCM and compressed formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-converter-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Converter Services",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-converter-services"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPrimeMethod": {
      "abstract": [
        {
          "text": "The priming method, usually for sample-rate conversion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterPrimeMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPrimeMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterPrimeMethod"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterPrimeMethod",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterprimemethod"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterQuality_High": {
      "abstract": [
        {
          "text": "Specifies high sample rate conversion quality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterQuality_High"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterQuality_High",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterQuality_High"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterQuality_High",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterquality_high"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterQuality_Low": {
      "abstract": [
        {
          "text": "Specifies low sample rate conversion quality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterQuality_Low"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterQuality_Low",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterQuality_Low"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterQuality_Low",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterquality_low"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterQuality_Max": {
      "abstract": [
        {
          "text": "Specifies maximum sample-rate conversion quality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterQuality_Max"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterQuality_Max",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterQuality_Max"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterQuality_Max",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterquality_max"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterQuality_Medium": {
      "abstract": [
        {
          "text": "Specifies medium sample rate conversion quality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterQuality_Medium"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterQuality_Medium",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterQuality_Medium"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterQuality_Medium",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterquality_medium"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterQuality_Min": {
      "abstract": [
        {
          "text": "Specifies minimum sample rate conversion quality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterQuality_Min"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterQuality_Min",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterQuality_Min"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterQuality_Min",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterquality_min"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterComplexity": {
      "abstract": [
        {
          "text": "The sample rate conversion algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterSampleRateConverterComplexity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterComplexity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterSampleRateConverterComplexity"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterSampleRateConverterComplexity",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconvertersamplerateconvertercomplexity"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterQuality": {
      "abstract": [
        {
          "text": "The rendering quality of the sample rate converter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterSampleRateConverterQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterSampleRateConverterQuality"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterSampleRateConverterQuality",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconvertersamplerateconverterquality"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559928-audio-converter-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559927-converter-priming-constants",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559923-sample-rate-conversion-complexit"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterQuality_Max",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterQuality_High",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterQuality_Medium",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterQuality_Low",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterQuality_Min"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterQuality_Max",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterQuality_High",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterQuality_Medium",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterQuality_Low",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterQuality_Min"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559928-audio-converter-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559927-converter-priming-constants",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559923-sample-rate-conversion-complexit"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterQuality_Medium/title",
          "value": "kAudioConverterQuality_Medium"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterQuality_Medium/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterQuality_Medium"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPrimeMethod/title",
          "value": "kAudioConverterPrimeMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPrimeMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterPrimeMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterQuality_Low/title",
          "value": "kAudioConverterQuality_Low"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterQuality_Low/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterQuality_Low"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterSetProperty(_:_:_:_:)/title",
          "value": "AudioConverterSetProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterSetProperty(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioConverterSetProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterSampleRateConverterQuality/title",
          "value": "kAudioConverterSampleRateConverterQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterSampleRateConverterQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterSampleRateConverterQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterSampleRateConverterComplexity/title",
          "value": "kAudioConverterSampleRateConverterComplexity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterSampleRateConverterComplexity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterSampleRateConverterComplexity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterQuality_Min/title",
          "value": "kAudioConverterQuality_Min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterQuality_Min/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterQuality_Min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterGetPropertyInfo(_:_:_:_:)/title",
          "value": "AudioConverterGetPropertyInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterGetPropertyInfo(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioConverterGetPropertyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterQuality_High/title",
          "value": "kAudioConverterQuality_High"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterQuality_High/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterQuality_High"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterGetProperty(_:_:_:_:)/title",
          "value": "AudioConverterGetProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterGetProperty(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioConverterGetProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterQuality_Max/title",
          "value": "kAudioConverterQuality_Max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterQuality_Max/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterQuality_Max"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1559924-sample-rate-conversion-quality-i"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1559924-sample-rate-conversion-quality-i"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
