{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-stream-services"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576500-audio-file-errors"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio File Errors"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-stream-services": {
      "abstract": [
        {
          "text": "Parse streamed audio files as the data arrives on the user’s computer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-stream-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio File Stream Services",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-file-stream-services"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileBadPropertySizeError": {
      "abstract": [
        {
          "text": "The size of the property data was not correct.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileBadPropertySizeError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileBadPropertySizeError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileBadPropertySizeError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileBadPropertySizeError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilebadpropertysizeerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileDoesNotAllow64BitDataSizeError": {
      "abstract": [
        {
          "text": "The file offset was too large for the file type. The AIFF and WAVE file format types have 32-bit file size limits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileDoesNotAllow64BitDataSizeError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileDoesNotAllow64BitDataSizeError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileDoesNotAllow64BitDataSizeError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileDoesNotAllow64BitDataSizeError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofiledoesnotallow64bitdatasizeerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileEndOfFileError": {
      "abstract": [
        {
          "text": "End of file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileEndOfFileError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileEndOfFileError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileEndOfFileError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileEndOfFileError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileendoffileerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileFileNotFoundError": {
      "abstract": [
        {
          "text": "File not found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileFileNotFoundError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileFileNotFoundError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileFileNotFoundError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileFileNotFoundError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilefilenotfounderror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInvalidChunkError": {
      "abstract": [
        {
          "text": "Either the chunk does not exist in the file or it is not supported by the file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileInvalidChunkError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInvalidChunkError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileInvalidChunkError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileInvalidChunkError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileinvalidchunkerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInvalidFileError": {
      "abstract": [
        {
          "text": "The file is malformed, or otherwise not a valid instance of an audio file of its type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileInvalidFileError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInvalidFileError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileInvalidFileError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileInvalidFileError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileinvalidfileerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInvalidPacketDependencyError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileInvalidPacketDependencyError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInvalidPacketDependencyError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileInvalidPacketDependencyError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileInvalidPacketDependencyError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileinvalidpacketdependencyerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInvalidPacketOffsetError": {
      "abstract": [
        {
          "text": "A packet offset was past the end of the file, or not at the end of the file when a VBR format was written,  or a corrupt packet size was read when the packet table was built.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileInvalidPacketOffsetError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInvalidPacketOffsetError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileInvalidPacketOffsetError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileInvalidPacketOffsetError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileinvalidpacketoffseterror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileNotOpenError": {
      "abstract": [
        {
          "text": "The file is closed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileNotOpenError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileNotOpenError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileNotOpenError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileNotOpenError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilenotopenerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileNotOptimizedError": {
      "abstract": [
        {
          "text": "The chunks following the audio data chunk are preventing the extension of the audio data chunk. To write more data, you must optimize the file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileNotOptimizedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileNotOptimizedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileNotOptimizedError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileNotOptimizedError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilenotoptimizederror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileOperationNotSupportedError": {
      "abstract": [
        {
          "text": "The operation cannot be performed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileOperationNotSupportedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileOperationNotSupportedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileOperationNotSupportedError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileOperationNotSupportedError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileoperationnotsupportederror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePermissionsError": {
      "abstract": [
        {
          "text": "The operation violated the file permissions. For example, an attempt was made to write to a file opened with the ",
          "type": "text"
        },
        {
          "code": "kAudioFileReadPermission",
          "type": "codeVoice"
        },
        {
          "text": " constant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFilePermissionsError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePermissionsError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFilePermissionsError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFilePermissionsError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilepermissionserror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePositionError": {
      "abstract": [
        {
          "text": "Invalid file position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFilePositionError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePositionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFilePositionError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFilePositionError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilepositionerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_BadPropertySize": {
      "abstract": [
        {
          "text": "The size of the buffer you provided for property data was not correct.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_BadPropertySize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_BadPropertySize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_BadPropertySize"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamError_BadPropertySize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamerror_badpropertysize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_DataUnavailable": {
      "abstract": [
        {
          "text": "The amount of data provided to the parser was insufficient to produce any result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_DataUnavailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_DataUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_DataUnavailable"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamError_DataUnavailable",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamerror_dataunavailable"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_DiscontinuityCantRecover": {
      "abstract": [
        {
          "text": "A discontinuity has occurred in the audio data, and Audio File Stream Services cannot recover.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_DiscontinuityCantRecover"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_DiscontinuityCantRecover",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_DiscontinuityCantRecover"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamError_DiscontinuityCantRecover",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamerror_discontinuitycantrecover"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_IllegalOperation": {
      "abstract": [
        {
          "text": "An illegal operation was attempted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_IllegalOperation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_IllegalOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_IllegalOperation"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamError_IllegalOperation",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamerror_illegaloperation"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_InvalidFile": {
      "abstract": [
        {
          "text": "The file is malformed, not a valid instance of an audio file of its type, or not recognized as an audio file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_InvalidFile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_InvalidFile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_InvalidFile"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamError_InvalidFile",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamerror_invalidfile"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_InvalidPacketOffset": {
      "abstract": [
        {
          "text": "A packet offset was less than ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": ", or past the end of the file, or a corrupt packet size was read when building the packet table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_InvalidPacketOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_InvalidPacketOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_InvalidPacketOffset"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamError_InvalidPacketOffset",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamerror_invalidpacketoffset"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_NotOptimized": {
      "abstract": [
        {
          "text": "It is not possible to produce output packets because the streamed audio file’s packet table or other defining information is not present or appears after the audio data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_NotOptimized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_NotOptimized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_NotOptimized"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamError_NotOptimized",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamerror_notoptimized"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnspecifiedError": {
      "abstract": [
        {
          "text": "An unspecified error has occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_UnspecifiedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnspecifiedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_UnspecifiedError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamError_UnspecifiedError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamerror_unspecifiederror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnsupportedDataFormat": {
      "abstract": [
        {
          "text": "The data format is not supported by the specified file type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_UnsupportedDataFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnsupportedDataFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_UnsupportedDataFormat"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamError_UnsupportedDataFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamerror_unsupporteddataformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnsupportedFileType": {
      "abstract": [
        {
          "text": "The specified file type is not supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_UnsupportedFileType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnsupportedFileType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_UnsupportedFileType"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamError_UnsupportedFileType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamerror_unsupportedfiletype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnsupportedProperty": {
      "abstract": [
        {
          "text": "The property is not supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_UnsupportedProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnsupportedProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_UnsupportedProperty"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamError_UnsupportedProperty",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamerror_unsupportedproperty"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_ValueUnknown": {
      "abstract": [
        {
          "text": "The property value is not present in this file before the audio data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_ValueUnknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_ValueUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_ValueUnknown"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamError_ValueUnknown",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamerror_valueunknown"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnspecifiedError": {
      "abstract": [
        {
          "text": "An unspecified error has occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileUnspecifiedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnspecifiedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileUnspecifiedError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileUnspecifiedError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileunspecifiederror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnsupportedDataFormatError": {
      "abstract": [
        {
          "text": "The data format is not supported by this file type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileUnsupportedDataFormatError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnsupportedDataFormatError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileUnsupportedDataFormatError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileUnsupportedDataFormatError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileunsupporteddataformaterror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnsupportedFileTypeError": {
      "abstract": [
        {
          "text": "The file type is not supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileUnsupportedFileTypeError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnsupportedFileTypeError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileUnsupportedFileTypeError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileUnsupportedFileTypeError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileunsupportedfiletypeerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnsupportedPropertyError": {
      "abstract": [
        {
          "text": "The property is not supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileUnsupportedPropertyError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnsupportedPropertyError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileUnsupportedPropertyError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileUnsupportedPropertyError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileunsupportedpropertyerror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Result-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnsupportedFileType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnsupportedDataFormat",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnsupportedProperty",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_BadPropertySize",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_NotOptimized",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_InvalidPacketOffset",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_InvalidFile",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_ValueUnknown",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_DataUnavailable",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_IllegalOperation",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnspecifiedError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_DiscontinuityCantRecover"
      ],
      "title": "Result Codes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileBadPropertySizeError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileDoesNotAllow64BitDataSizeError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileEndOfFileError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileFileNotFoundError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInvalidChunkError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInvalidFileError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInvalidPacketOffsetError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileNotOpenError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileNotOptimizedError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileOperationNotSupportedError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePermissionsError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePositionError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnspecifiedError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnsupportedDataFormatError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnsupportedFileTypeError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnsupportedPropertyError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInvalidPacketDependencyError"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileBadPropertySizeError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileDoesNotAllow64BitDataSizeError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileEndOfFileError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileFileNotFoundError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInvalidChunkError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInvalidFileError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInvalidPacketOffsetError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileNotOpenError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileNotOptimizedError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileOperationNotSupportedError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePermissionsError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePositionError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnspecifiedError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnsupportedDataFormatError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnsupportedFileTypeError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnsupportedPropertyError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInvalidPacketDependencyError"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Result-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnsupportedFileType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnsupportedDataFormat",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnsupportedProperty",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_BadPropertySize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_NotOptimized",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_InvalidPacketOffset",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_InvalidFile",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_ValueUnknown",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_DataUnavailable",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_IllegalOperation",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnspecifiedError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_DiscontinuityCantRecover"
              ],
              "title": "Result Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_InvalidFile/title",
          "value": "kAudioFileStreamError_InvalidFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_InvalidFile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamError_InvalidFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileUnspecifiedError/title",
          "value": "kAudioFileUnspecifiedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileUnspecifiedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileUnspecifiedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_DataUnavailable/title",
          "value": "kAudioFileStreamError_DataUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_DataUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamError_DataUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileFileNotFoundError/title",
          "value": "kAudioFileFileNotFoundError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileFileNotFoundError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileFileNotFoundError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFilePermissionsError/title",
          "value": "kAudioFilePermissionsError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFilePermissionsError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFilePermissionsError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_BadPropertySize/title",
          "value": "kAudioFileStreamError_BadPropertySize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_BadPropertySize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamError_BadPropertySize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileBadPropertySizeError/title",
          "value": "kAudioFileBadPropertySizeError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileBadPropertySizeError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileBadPropertySizeError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_InvalidPacketOffset/title",
          "value": "kAudioFileStreamError_InvalidPacketOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_InvalidPacketOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamError_InvalidPacketOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileUnsupportedFileTypeError/title",
          "value": "kAudioFileUnsupportedFileTypeError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileUnsupportedFileTypeError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileUnsupportedFileTypeError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_UnsupportedProperty/title",
          "value": "kAudioFileStreamError_UnsupportedProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_UnsupportedProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamError_UnsupportedProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_UnsupportedDataFormat/title",
          "value": "kAudioFileStreamError_UnsupportedDataFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_UnsupportedDataFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamError_UnsupportedDataFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileUnsupportedDataFormatError/title",
          "value": "kAudioFileUnsupportedDataFormatError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileUnsupportedDataFormatError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileUnsupportedDataFormatError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_UnspecifiedError/title",
          "value": "kAudioFileStreamError_UnspecifiedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_UnspecifiedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamError_UnspecifiedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileNotOpenError/title",
          "value": "kAudioFileNotOpenError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileNotOpenError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileNotOpenError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileEndOfFileError/title",
          "value": "kAudioFileEndOfFileError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileEndOfFileError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileEndOfFileError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileInvalidChunkError/title",
          "value": "kAudioFileInvalidChunkError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileInvalidChunkError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileInvalidChunkError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_ValueUnknown/title",
          "value": "kAudioFileStreamError_ValueUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_ValueUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamError_ValueUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileInvalidFileError/title",
          "value": "kAudioFileInvalidFileError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileInvalidFileError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileInvalidFileError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileUnsupportedPropertyError/title",
          "value": "kAudioFileUnsupportedPropertyError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileUnsupportedPropertyError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileUnsupportedPropertyError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_IllegalOperation/title",
          "value": "kAudioFileStreamError_IllegalOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_IllegalOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamError_IllegalOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileOperationNotSupportedError/title",
          "value": "kAudioFileOperationNotSupportedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileOperationNotSupportedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileOperationNotSupportedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_NotOptimized/title",
          "value": "kAudioFileStreamError_NotOptimized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_NotOptimized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamError_NotOptimized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileInvalidPacketOffsetError/title",
          "value": "kAudioFileInvalidPacketOffsetError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileInvalidPacketOffsetError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileInvalidPacketOffsetError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_DiscontinuityCantRecover/title",
          "value": "kAudioFileStreamError_DiscontinuityCantRecover"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_DiscontinuityCantRecover/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamError_DiscontinuityCantRecover"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileNotOptimizedError/title",
          "value": "kAudioFileNotOptimizedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileNotOptimizedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileNotOptimizedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_UnsupportedFileType/title",
          "value": "kAudioFileStreamError_UnsupportedFileType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_UnsupportedFileType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamError_UnsupportedFileType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileInvalidPacketDependencyError/title",
          "value": "kAudioFileInvalidPacketDependencyError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileInvalidPacketDependencyError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileInvalidPacketDependencyError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFilePositionError/title",
          "value": "kAudioFilePositionError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFilePositionError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFilePositionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileDoesNotAllow64BitDataSizeError/title",
          "value": "kAudioFileDoesNotAllow64BitDataSizeError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileDoesNotAllow64BitDataSizeError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileDoesNotAllow64BitDataSizeError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1576500-audio-file-errors"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1576500-audio-file-errors"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
