{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1579372-audio_unit_carbon_view_selectors"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio Unit Carbon View Selectors"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1579363-audio_unit_carbon_view_component": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1579363-audio_unit_carbon_view_component",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Carbon View Component Types",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1579363-audio_unit_carbon_view_component"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1579365-audio_unit_carbon_view_events": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1579365-audio_unit_carbon_view_events",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Carbon View Events",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1579365-audio_unit_carbon_view_events"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUCocoaUIBase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AUCocoaUIBase"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUCocoaUIBase",
      "kind": "symbol",
      "role": "symbol",
      "title": "AUCocoaUIBase",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aucocoauibase"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCarbonView": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioUnitCarbonView"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCarbonView",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioUnitCarbonView",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitcarbonview"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCarbonViewEventID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioUnitCarbonViewEventID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCarbonViewEventID",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioUnitCarbonViewEventID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitcarbonvieweventid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCocoaViewInfo": {
      "abstract": [
        {
          "text": "The name and number of custom Cocoa views for an audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitCocoaViewInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCocoaViewInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitCocoaViewInfo"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitCocoaViewInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitcocoaviewinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/GetAudioUnitParameterDisplayType(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GetAudioUnitParameterDisplayType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/GetAudioUnitParameterDisplayType(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GetAudioUnitParameterDisplayType"
        }
      ],
      "role": "symbol",
      "title": "GetAudioUnitParameterDisplayType(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/getaudiounitparameterdisplaytype(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/SetAudioUnitParameterDisplayType(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAudioUnitParameterDisplayType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/SetAudioUnitParameterDisplayType(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SetAudioUnitParameterDisplayType"
        }
      ],
      "role": "symbol",
      "title": "SetAudioUnitParameterDisplayType(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/setaudiounitparameterdisplaytype(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api": {
      "abstract": [
        {
          "text": "Configure an Audio Unit and prepare it to render audio.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit v2 (C) API",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-v2-c-api"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitCarbonViewCreateSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kAudioUnitCarbonViewCreateSelect"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitCarbonViewCreateSelect",
      "kind": "symbol",
      "role": "symbol",
      "title": "kAudioUnitCarbonViewCreateSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitcarbonviewcreateselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitCarbonViewRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kAudioUnitCarbonViewRange"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitCarbonViewRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "kAudioUnitCarbonViewRange",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitcarbonviewrange"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitCarbonViewSetEventListenerSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kAudioUnitCarbonViewSetEventListenerSelect"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitCarbonViewSetEventListenerSelect",
      "kind": "symbol",
      "role": "symbol",
      "title": "kAudioUnitCarbonViewSetEventListenerSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitcarbonviewseteventlistenerselect"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitCarbonViewCreateSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitCarbonViewRange",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitCarbonViewSetEventListenerSelect"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-Audio-Unit-UI",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCocoaViewInfo",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUCocoaUIBase",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCarbonView",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCarbonViewEventID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1579365-audio_unit_carbon_view_events",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1579363-audio_unit_carbon_view_component",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/GetAudioUnitParameterDisplayType(_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/SetAudioUnitParameterDisplayType(_:_:)"
              ],
              "title": "Configuring the Audio Unit UI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1SetAudioUnitParameterDisplayType(_:_:)/title",
          "value": "SetAudioUnitParameterDisplayType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1SetAudioUnitParameterDisplayType(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SetAudioUnitParameterDisplayType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitCocoaViewInfo/title",
          "value": "AudioUnitCocoaViewInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitCocoaViewInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitCocoaViewInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitCocoaViewInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitCocoaViewInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1GetAudioUnitParameterDisplayType(_:)/title",
          "value": "GetAudioUnitParameterDisplayType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1GetAudioUnitParameterDisplayType(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GetAudioUnitParameterDisplayType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1579372-audio_unit_carbon_view_selectors"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1579372-audio_unit_carbon_view_selectors"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
