{
  "abstract": [
    {
      "text": "Audio data format converter audio unit subtypes for audio units provided by Apple.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-converter-services"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Converter Audio Unit Subtypes"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533972-converter_audio_unit_properties": {
      "abstract": [
        {
          "text": "Properties for the Apple AUConverter audio unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533972-converter_audio_unit_properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Converter Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1533972-converter_audio_unit_properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559925-audio-converter-properties-macos": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559925-audio-converter-properties-macos",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Converter Properties (macOS)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1559925-audio-converter-properties-macos"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559930-audio-converter-errors": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559930-audio-converter-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Converter Errors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1559930-audio-converter-errors"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559931-audio-converter-dithering-algori": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559931-audio-converter-dithering-algori",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Converter Dithering Algorithms",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1559931-audio-converter-dithering-algori"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-converter-services": {
      "abstract": [
        {
          "text": "Convert between linear PCM audio formats, and between linear PCM and compressed formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-converter-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Converter Services",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-converter-services"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api": {
      "abstract": [
        {
          "text": "Configure an Audio Unit and prepare it to render audio.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit v2 (C) API",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-v2-c-api"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_AUConverter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_AUConverter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_AUConverter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_AUConverter"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_AUConverter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_auconverter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_AUiPodTimeOther": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_AUiPodTimeOther"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_AUiPodTimeOther",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_AUiPodTimeOther"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_AUiPodTimeOther",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_auipodtimeother"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_DeferredRenderer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_DeferredRenderer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_DeferredRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_DeferredRenderer"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_DeferredRenderer",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_deferredrenderer"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Merger": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_Merger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Merger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_Merger"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_Merger",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_merger"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_MultiSplitter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_MultiSplitter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_MultiSplitter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_MultiSplitter"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_MultiSplitter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_multisplitter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_NewTimePitch": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_NewTimePitch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_NewTimePitch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_NewTimePitch"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_NewTimePitch",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_newtimepitch"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_RoundTripAAC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_RoundTripAAC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_RoundTripAAC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_RoundTripAAC"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_RoundTripAAC",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_roundtripaac"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Splitter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_Splitter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Splitter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_Splitter"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_Splitter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_splitter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Varispeed": {
      "abstract": [
        {
          "text": "An audio unit that can control playback rate. As the playback rate increases, so does pitch. This subtype provides a generic view, making it suitable for UI and programmatic context. macOS provides realtime and offline audio units of this subtype.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_Varispeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Varispeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_Varispeed"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_Varispeed",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_varispeed"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533972-converter_audio_unit_properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559931-audio-converter-dithering-algori",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559925-audio-converter-properties-macos",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559930-audio-converter-errors"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_AUConverter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_AUiPodTimeOther",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_DeferredRenderer",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Merger",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_MultiSplitter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_NewTimePitch",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_RoundTripAAC",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Splitter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Varispeed"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_AUConverter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_AUiPodTimeOther",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_DeferredRenderer",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Merger",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_MultiSplitter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_NewTimePitch",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_RoundTripAAC",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Splitter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Varispeed"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533972-converter_audio_unit_properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559931-audio-converter-dithering-algori",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559925-audio-converter-properties-macos",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559930-audio-converter-errors"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_AUConverter/title",
          "value": "kAudioUnitSubType_AUConverter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_AUConverter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_AUConverter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_Merger/title",
          "value": "kAudioUnitSubType_Merger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_Merger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_Merger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_Varispeed/title",
          "value": "kAudioUnitSubType_Varispeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_Varispeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_Varispeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_MultiSplitter/title",
          "value": "kAudioUnitSubType_MultiSplitter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_MultiSplitter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_MultiSplitter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_AUiPodTimeOther/title",
          "value": "kAudioUnitSubType_AUiPodTimeOther"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_AUiPodTimeOther/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_AUiPodTimeOther"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_NewTimePitch/title",
          "value": "kAudioUnitSubType_NewTimePitch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_NewTimePitch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_NewTimePitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_RoundTripAAC/title",
          "value": "kAudioUnitSubType_RoundTripAAC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_RoundTripAAC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_RoundTripAAC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_Splitter/title",
          "value": "kAudioUnitSubType_Splitter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_Splitter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_Splitter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_DeferredRenderer/title",
          "value": "kAudioUnitSubType_DeferredRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_DeferredRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_DeferredRenderer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1584145-converter_audio_unit_subtypes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1584145-converter_audio_unit_subtypes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
