{
  "abstract": [
    {
      "text": "Audio mixing audio unit subtypes for audio units provided by Apple.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584150-mixer_audio_unit_subtypes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Mixer Audio Unit Subtypes"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389739-aumultichannelmixer_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Multichannel Mixer unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389739-aumultichannelmixer_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUMultiChannelMixer Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389739-aumultichannelmixer_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389763-3d_mixer_unit_parameters": {
      "abstract": [
        {
          "text": "Parameters for the 3D Mixer unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389763-3d_mixer_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "3D Mixer Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389763-3d_mixer_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389928-stereo-mixer-unit-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389928-stereo-mixer-unit-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Stereo Mixer Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389928-stereo-mixer-unit-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389991-panner-audio-unit-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389991-panner-audio-unit-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Panner Audio Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389991-panner-audio-unit-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390003-aumatrixmixer-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390003-aumatrixmixer-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUMatrixMixer Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390003-aumatrixmixer-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390073-auspatialmixer-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390073-auspatialmixer-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUSpatialMixer Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390073-auspatialmixer-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534041-mixer_audio_unit_properties": {
      "abstract": [
        {
          "text": "Properties for Apple mixer audio units.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534041-mixer_audio_unit_properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mixer Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534041-mixer_audio_unit_properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534150-spatial-mixer-property-ids": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534150-spatial-mixer-property-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Spatial Mixer Property IDs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534150-spatial-mixer-property-ids"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584146-audio-unit-mixer-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584146-audio-unit-mixer-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Mixer Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584146-audio-unit-mixer-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AU3DMixerAttenuationCurve"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AU3DMixerAttenuationCurve"
        }
      ],
      "role": "symbol",
      "title": "AU3DMixerAttenuationCurve",
      "type": "topic",
      "url": "/documentation/audiotoolbox/au3dmixerattenuationcurve"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerAttenuationCurve": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatialMixerAttenuationCurve"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerAttenuationCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatialMixerAttenuationCurve"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerAttenuationCurve",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixerattenuationcurve"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerOutputType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatialMixerOutputType"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerOutputType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatialMixerOutputType"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerOutputType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixeroutputtype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerPointSourceInHeadMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatialMixerPointSourceInHeadMode"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerPointSourceInHeadMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatialMixerPointSourceInHeadMode"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerPointSourceInHeadMode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixerpointsourceinheadmode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerRenderingFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatialMixerRenderingFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerRenderingFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatialMixerRenderingFlags"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerRenderingFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixerrenderingflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatialMixerSourceMode"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatialMixerSourceMode"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerSourceMode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixersourcemode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties": {
      "abstract": [
        {
          "text": "Obtain information about the built-in mixers, equalizers, filters, effects, and other Audio Unit app extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_MatrixMixer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_MatrixMixer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_MatrixMixer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_MatrixMixer"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_MatrixMixer",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_matrixmixer"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_MultiChannelMixer": {
      "abstract": [
        {
          "text": "An audio unit that can have any number of input buses, with any number of channels on each input bus, and one output bus. In macOS, the output bus can have any number of channels. In iOS, the output bus always has two channels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_MultiChannelMixer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_MultiChannelMixer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_MultiChannelMixer"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_MultiChannelMixer",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_multichannelmixer"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_SpatialMixer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_SpatialMixer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_SpatialMixer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_SpatialMixer"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_SpatialMixer",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_spatialmixer"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Mixers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584146-audio-unit-mixer-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerAttenuationCurve",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerRenderingFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390073-auspatialmixer-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389991-panner-audio-unit-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390003-aumatrixmixer-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389739-aumultichannelmixer_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534150-spatial-mixer-property-ids",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389928-stereo-mixer-unit-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534041-mixer_audio_unit_properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerOutputType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerPointSourceInHeadMode",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389763-3d_mixer_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve"
      ],
      "title": "Mixers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_MatrixMixer",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_MultiChannelMixer",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_SpatialMixer"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_MatrixMixer",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_MultiChannelMixer",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_SpatialMixer"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Mixers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584146-audio-unit-mixer-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerAttenuationCurve",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerRenderingFlags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390073-auspatialmixer-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389991-panner-audio-unit-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390003-aumatrixmixer-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389739-aumultichannelmixer_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534150-spatial-mixer-property-ids",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389928-stereo-mixer-unit-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534041-mixer_audio_unit_properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerOutputType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerPointSourceInHeadMode",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389763-3d_mixer_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve"
              ],
              "title": "Mixers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerPointSourceInHeadMode/title",
          "value": "AUSpatialMixerPointSourceInHeadMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerPointSourceInHeadMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerPointSourceInHeadMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerPointSourceInHeadMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerPointSourceInHeadMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerAttenuationCurve/title",
          "value": "AUSpatialMixerAttenuationCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerAttenuationCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerAttenuationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerAttenuationCurve/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerAttenuationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerOutputType/title",
          "value": "AUSpatialMixerOutputType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerOutputType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerOutputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerOutputType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerOutputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_MultiChannelMixer/title",
          "value": "kAudioUnitSubType_MultiChannelMixer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_MultiChannelMixer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_MultiChannelMixer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerSourceMode/title",
          "value": "AUSpatialMixerSourceMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerSourceMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerSourceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerSourceMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerSourceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerAttenuationCurve/title",
          "value": "AU3DMixerAttenuationCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerAttenuationCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AU3DMixerAttenuationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerAttenuationCurve/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AU3DMixerAttenuationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_MatrixMixer/title",
          "value": "kAudioUnitSubType_MatrixMixer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_MatrixMixer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_MatrixMixer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_SpatialMixer/title",
          "value": "kAudioUnitSubType_SpatialMixer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_SpatialMixer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_SpatialMixer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerRenderingFlags/title",
          "value": "AUSpatialMixerRenderingFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerRenderingFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerRenderingFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerRenderingFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerRenderingFlags"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1584150-mixer_audio_unit_subtypes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1584150-mixer_audio_unit_subtypes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
