{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584138-audio-unit-errors"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio Unit Errors"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389613-midi_audio_unit_parameters": {
      "abstract": [
        {
          "text": "Parameters for instrument units.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389613-midi_audio_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Audio Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389613-midi_audio_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi": {
      "abstract": [
        {
          "text": "Reserved for system use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Reserved Audio Unit Clump Identifier",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1533986-reserved_audio_unit_clump_identi"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534054-offline_audio_unit_properties": {
      "abstract": [
        {
          "text": "Properties for audio units that perform offline processing—that is, processing in a nonplayback, nonrealtime mode.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534054-offline_audio_unit_properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Offline Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534054-offline_audio_unit_properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes": {
      "abstract": [
        {
          "text": "Input/output audio unit subtypes for audio units provided by Apple.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Input/Output Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584139-input_output_audio_unit_subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele": {
      "abstract": [
        {
          "text": "General audio unit component selectors that correspond to functions in the audio unit API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele",
      "kind": "article",
      "role": "collectionGroup",
      "title": "General Audio Unit Function Selectors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584140-general_audio_unit_function_sele"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584142-audio_unit_types": {
      "abstract": [
        {
          "text": "The defined types of audio processing plug-ins known as audio units.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584142-audio_unit_types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Types",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584142-audio_unit_types"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi": {
      "abstract": [
        {
          "text": "The Apple audio unit manufacturer code.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Manufacturer Identifier",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584143-audio_unit_manufacturer_identifi"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes": {
      "abstract": [
        {
          "text": "Audio data format converter audio unit subtypes for audio units provided by Apple.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Converter Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584145-converter_audio_unit_subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584148-audio-unit-output-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584148-audio-unit-output-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Output Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584148-audio-unit-output-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Panner Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584151-audio-unit-panner-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Pitch Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584152-audio-unit-pitch-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Player Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584155-audio-unit-player-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "I/O Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1619485-i-o-audio-unit-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes": {
      "abstract": [
        {
          "text": "Audio units that serve as sound sources.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Generator Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1619493-generator_audio_unit_subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Inter-App Audio Unit Types",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1619501-inter-app-audio-unit-types"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api": {
      "abstract": [
        {
          "text": "Configure an Audio Unit and prepare it to render audio.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit v2 (C) API",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-v2-c-api"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioComponentErr_InstanceInvalidated": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioComponentErr_InstanceInvalidated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioComponentErr_InstanceInvalidated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioComponentErr_InstanceInvalidated"
        }
      ],
      "role": "symbol",
      "title": "kAudioComponentErr_InstanceInvalidated",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocomponenterr_instanceinvalidated"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioComponentErr_InstanceTimedOut": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioComponentErr_InstanceTimedOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioComponentErr_InstanceTimedOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioComponentErr_InstanceTimedOut"
        }
      ],
      "role": "symbol",
      "title": "kAudioComponentErr_InstanceTimedOut",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocomponenterr_instancetimedout"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_CannotDoInCurrentContext": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_CannotDoInCurrentContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_CannotDoInCurrentContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_CannotDoInCurrentContext"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_CannotDoInCurrentContext",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_cannotdoincurrentcontext"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_ComponentManagerNotSupported": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_ComponentManagerNotSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_ComponentManagerNotSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_ComponentManagerNotSupported"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_ComponentManagerNotSupported",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_componentmanagernotsupported"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_ExtensionNotFound": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_ExtensionNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_ExtensionNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_ExtensionNotFound"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_ExtensionNotFound",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_extensionnotfound"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_FailedInitialization": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_FailedInitialization"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_FailedInitialization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_FailedInitialization"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_FailedInitialization",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_failedinitialization"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_FileNotSpecified": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_FileNotSpecified"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_FileNotSpecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_FileNotSpecified"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_FileNotSpecified",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_filenotspecified"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_FormatNotSupported": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_FormatNotSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_FormatNotSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_FormatNotSupported"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_FormatNotSupported",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_formatnotsupported"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_Initialized": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_Initialized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_Initialized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_Initialized"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_Initialized",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_initialized"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidElement": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidElement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidElement"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_InvalidElement",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_invalidelement"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidFile": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidFile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidFile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidFile"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_InvalidFile",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_invalidfile"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidFilePath": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidFilePath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidFilePath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidFilePath"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_InvalidFilePath",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_invalidfilepath"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidOfflineRender": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidOfflineRender"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidOfflineRender",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidOfflineRender"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_InvalidOfflineRender",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_invalidofflinerender"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidParameter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidParameter"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_InvalidParameter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_invalidparameter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidParameterValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidParameterValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidParameterValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidParameterValue"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_InvalidParameterValue",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_invalidparametervalue"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidProperty": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidProperty"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_InvalidProperty",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_invalidproperty"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidPropertyValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidPropertyValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidPropertyValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidPropertyValue"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_InvalidPropertyValue",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_invalidpropertyvalue"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidScope": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidScope"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidScope",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidScope"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_InvalidScope",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_invalidscope"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_MIDIOutputBufferFull": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_MIDIOutputBufferFull"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_MIDIOutputBufferFull",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_MIDIOutputBufferFull"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_MIDIOutputBufferFull",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_midioutputbufferfull"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_MissingKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_MissingKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_MissingKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_MissingKey"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_MissingKey",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_missingkey"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_NoConnection": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_NoConnection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_NoConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_NoConnection"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_NoConnection",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_noconnection"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_PropertyNotInUse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_PropertyNotInUse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_PropertyNotInUse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_PropertyNotInUse"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_PropertyNotInUse",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_propertynotinuse"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_PropertyNotWritable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_PropertyNotWritable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_PropertyNotWritable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_PropertyNotWritable"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_PropertyNotWritable",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_propertynotwritable"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_RenderTimeout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_RenderTimeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_RenderTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_RenderTimeout"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_RenderTimeout",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_rendertimeout"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_TooManyFramesToProcess": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_TooManyFramesToProcess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_TooManyFramesToProcess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_TooManyFramesToProcess"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_TooManyFramesToProcess",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_toomanyframestoprocess"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_Unauthorized": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_Unauthorized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_Unauthorized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_Unauthorized"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_Unauthorized",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_unauthorized"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_Uninitialized": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_Uninitialized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_Uninitialized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_Uninitialized"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_Uninitialized",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_uninitialized"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_UnknownFileType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_UnknownFileType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_UnknownFileType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_UnknownFileType"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_UnknownFileType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_unknownfiletype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584142-audio_unit_types",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584148-audio-unit-output-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534054-offline_audio_unit_properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389613-midi_audio_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioComponentErr_InstanceInvalidated",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_CannotDoInCurrentContext",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_FailedInitialization",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_FileNotSpecified",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_FormatNotSupported",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_Initialized",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidElement",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidFile",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidOfflineRender",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidParameter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidProperty",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidPropertyValue",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidScope",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_NoConnection",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_PropertyNotInUse",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_PropertyNotWritable",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_TooManyFramesToProcess",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_Unauthorized",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_Uninitialized",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_UnknownFileType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_RenderTimeout",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioComponentErr_InstanceTimedOut",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_ExtensionNotFound",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidFilePath",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidParameterValue",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_MIDIOutputBufferFull",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_MissingKey",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_ComponentManagerNotSupported"
      ],
      "title": "Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioComponentErr_InstanceInvalidated",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_CannotDoInCurrentContext",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_FailedInitialization",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_FileNotSpecified",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_FormatNotSupported",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_Initialized",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidElement",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidFile",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidOfflineRender",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidParameter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidProperty",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidPropertyValue",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidScope",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_NoConnection",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_PropertyNotInUse",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_PropertyNotWritable",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_TooManyFramesToProcess",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_Unauthorized",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_Uninitialized",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_UnknownFileType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_RenderTimeout",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioComponentErr_InstanceTimedOut",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_ExtensionNotFound",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidFilePath",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidParameterValue",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_MIDIOutputBufferFull",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_MissingKey",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_ComponentManagerNotSupported"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584142-audio_unit_types",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584148-audio-unit-output-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534054-offline_audio_unit_properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389613-midi_audio_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_RenderTimeout/title",
          "value": "kAudioUnitErr_RenderTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_RenderTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_RenderTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_PropertyNotInUse/title",
          "value": "kAudioUnitErr_PropertyNotInUse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_PropertyNotInUse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_PropertyNotInUse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidOfflineRender/title",
          "value": "kAudioUnitErr_InvalidOfflineRender"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidOfflineRender/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_InvalidOfflineRender"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioComponentErr_InstanceInvalidated/title",
          "value": "kAudioComponentErr_InstanceInvalidated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioComponentErr_InstanceInvalidated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioComponentErr_InstanceInvalidated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_NoConnection/title",
          "value": "kAudioUnitErr_NoConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_NoConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_NoConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_MIDIOutputBufferFull/title",
          "value": "kAudioUnitErr_MIDIOutputBufferFull"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_MIDIOutputBufferFull/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_MIDIOutputBufferFull"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_ExtensionNotFound/title",
          "value": "kAudioUnitErr_ExtensionNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_ExtensionNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_ExtensionNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_UnknownFileType/title",
          "value": "kAudioUnitErr_UnknownFileType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_UnknownFileType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_UnknownFileType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_Uninitialized/title",
          "value": "kAudioUnitErr_Uninitialized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_Uninitialized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_Uninitialized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_PropertyNotWritable/title",
          "value": "kAudioUnitErr_PropertyNotWritable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_PropertyNotWritable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_PropertyNotWritable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_FileNotSpecified/title",
          "value": "kAudioUnitErr_FileNotSpecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_FileNotSpecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_FileNotSpecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidPropertyValue/title",
          "value": "kAudioUnitErr_InvalidPropertyValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidPropertyValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_InvalidPropertyValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidScope/title",
          "value": "kAudioUnitErr_InvalidScope"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidScope/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_InvalidScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidParameterValue/title",
          "value": "kAudioUnitErr_InvalidParameterValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidParameterValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_InvalidParameterValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_Initialized/title",
          "value": "kAudioUnitErr_Initialized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_Initialized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_Initialized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_ComponentManagerNotSupported/title",
          "value": "kAudioUnitErr_ComponentManagerNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_ComponentManagerNotSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_ComponentManagerNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_CannotDoInCurrentContext/title",
          "value": "kAudioUnitErr_CannotDoInCurrentContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_CannotDoInCurrentContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_CannotDoInCurrentContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidFilePath/title",
          "value": "kAudioUnitErr_InvalidFilePath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidFilePath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_InvalidFilePath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidProperty/title",
          "value": "kAudioUnitErr_InvalidProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_InvalidProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_TooManyFramesToProcess/title",
          "value": "kAudioUnitErr_TooManyFramesToProcess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_TooManyFramesToProcess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_TooManyFramesToProcess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_Unauthorized/title",
          "value": "kAudioUnitErr_Unauthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_Unauthorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_Unauthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidFile/title",
          "value": "kAudioUnitErr_InvalidFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidFile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_InvalidFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_FormatNotSupported/title",
          "value": "kAudioUnitErr_FormatNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_FormatNotSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_FormatNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioComponentErr_InstanceTimedOut/title",
          "value": "kAudioComponentErr_InstanceTimedOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioComponentErr_InstanceTimedOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioComponentErr_InstanceTimedOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidParameter/title",
          "value": "kAudioUnitErr_InvalidParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_InvalidParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidElement/title",
          "value": "kAudioUnitErr_InvalidElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_InvalidElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_MissingKey/title",
          "value": "kAudioUnitErr_MissingKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_MissingKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_MissingKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_FailedInitialization/title",
          "value": "kAudioUnitErr_FailedInitialization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_FailedInitialization/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_FailedInitialization"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1584138-audio-unit-errors"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1584138-audio-unit-errors"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
