{"sections":[],"seeAlsoSections":[{"identifiers":["doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584142-audio_unit_types","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534054-offline_audio_unit_properties","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389613-midi_audio_unit_parameters","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType"],"generated":true,"title":"Enumerations","anchor":"Enumerations"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584148-audio-unit-output-subtypes"},"metadata":{"role":"collectionGroup","modules":[{"name":"Audio Toolbox"}],"roleHeading":"API Collection","title":"Audio Unit Output Subtypes"},"topicSections":[{"identifiers":["doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_DefaultOutput","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_HALOutput","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_SystemOutput"],"title":"Constants","anchor":"Constants"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.audiotoolbox/documentation/AudioToolbox","doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/audiotoolbox/1584148-audio-unit-output-subtypes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/audiotoolbox/1584148-audio-unit-output-subtypes"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"article","references":{"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi":{"role":"collectionGroup","type":"topic","abstract":[{"type":"text","text":"The Apple audio unit manufacturer code."}],"kind":"article","url":"/documentation/audiotoolbox/1584143-audio_unit_manufacturer_identifi","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi","title":"Audio Unit Manufacturer Identifier"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes":{"role":"collectionGroup","type":"topic","abstract":[],"kind":"article","url":"/documentation/audiotoolbox/1584152-audio-unit-pitch-subtypes","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes","title":"Audio Unit Pitch Subtypes"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_HALOutput":{"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_HALOutput","type":"topic","kind":"symbol","url":"/documentation/audiotoolbox/kaudiounitsubtype_haloutput","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioUnitSubType_HALOutput"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32"}],"navigatorTitle":[{"kind":"identifier","text":"kAudioUnitSubType_HALOutput"}],"title":"kAudioUnitSubType_HALOutput"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes":{"role":"collectionGroup","type":"topic","abstract":[],"kind":"article","url":"/documentation/audiotoolbox/1584155-audio-unit-player-subtypes","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes","title":"Audio Unit Player Subtypes"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes":{"abstract":[],"kind":"article","title":"Audio Unit Panner Subtypes","role":"collectionGroup","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes","url":"/documentation/audiotoolbox/1584151-audio-unit-panner-subtypes","type":"topic"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes":{"kind":"article","url":"/documentation/audiotoolbox/1619485-i-o-audio-unit-subtypes","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes","title":"I/O Audio Unit Subtypes","abstract":[],"type":"topic","role":"collectionGroup"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534054-offline_audio_unit_properties":{"url":"/documentation/audiotoolbox/1534054-offline_audio_unit_properties","abstract":[{"text":"Properties for audio units that perform offline processing—that is, processing in a nonplayback, nonrealtime mode.","type":"text"}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534054-offline_audio_unit_properties","role":"collectionGroup","kind":"article","title":"Offline Audio Unit Properties","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","type":"topic","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","role":"overview"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api":{"role":"collectionGroup","type":"topic","abstract":[{"type":"text","text":"Configure an Audio Unit and prepare it to render audio."}],"kind":"article","url":"/documentation/audiotoolbox/audio-unit-v2-c-api","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api","title":"Audio Unit v2 (C) API"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox":{"type":"topic","kind":"symbol","title":"Audio Toolbox","role":"collection","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox","abstract":[{"text":"Record or play audio, convert formats, parse audio streams, and configure your audio session.","type":"text"}],"url":"/documentation/audiotoolbox"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584142-audio_unit_types":{"title":"Audio Unit Types","type":"topic","role":"collectionGroup","abstract":[{"type":"text","text":"The defined types of audio processing plug-ins known as audio units."}],"kind":"article","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584142-audio_unit_types","url":"/documentation/audiotoolbox/1584142-audio_unit_types"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele":{"title":"General Audio Unit Function Selectors","type":"topic","role":"collectionGroup","abstract":[{"type":"text","text":"General audio unit component selectors that correspond to functions in the audio unit API."}],"kind":"article","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele","url":"/documentation/audiotoolbox/1584140-general_audio_unit_function_sele"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_SystemOutput":{"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_SystemOutput","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioUnitSubType_SystemOutput"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32"}],"navigatorTitle":[{"kind":"identifier","text":"kAudioUnitSubType_SystemOutput"}],"url":"/documentation/audiotoolbox/kaudiounitsubtype_systemoutput","type":"topic","title":"kAudioUnitSubType_SystemOutput"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types":{"kind":"article","url":"/documentation/audiotoolbox/1619501-inter-app-audio-unit-types","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types","title":"Inter-App Audio Unit Types","abstract":[],"type":"topic","role":"collectionGroup"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes":{"abstract":[{"text":"Audio units that serve as sound sources.","type":"text"}],"kind":"article","title":"Generator Audio Unit Subtypes","role":"collectionGroup","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes","url":"/documentation/audiotoolbox/1619493-generator_audio_unit_subtypes","type":"topic"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi":{"type":"topic","url":"/documentation/audiotoolbox/1533986-reserved_audio_unit_clump_identi","title":"Reserved Audio Unit Clump Identifier","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi","kind":"article","role":"collectionGroup","abstract":[{"text":"Reserved for system use.","type":"text"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389613-midi_audio_unit_parameters":{"type":"topic","url":"/documentation/audiotoolbox/1389613-midi_audio_unit_parameters","title":"MIDI Audio Unit Parameters","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389613-midi_audio_unit_parameters","kind":"article","role":"collectionGroup","abstract":[{"text":"Parameters for instrument units.","type":"text"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType":{"kind":"symbol","url":"/documentation/audiotoolbox/audiouniteventtype","role":"symbol","type":"topic","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioUnitEventType","kind":"identifier"}],"navigatorTitle":[{"text":"AudioUnitEventType","kind":"identifier"}],"title":"AudioUnitEventType","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_DefaultOutput":{"navigatorTitle":[{"kind":"identifier","text":"kAudioUnitSubType_DefaultOutput"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioUnitSubType_DefaultOutput","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32"}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_DefaultOutput","abstract":[],"type":"topic","url":"/documentation/audiotoolbox/kaudiounitsubtype_defaultoutput","kind":"symbol","title":"kAudioUnitSubType_DefaultOutput","role":"symbol"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes":{"title":"Converter Audio Unit Subtypes","type":"topic","role":"collectionGroup","abstract":[{"type":"text","text":"Audio data format converter audio unit subtypes for audio units provided by Apple."}],"kind":"article","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes","url":"/documentation/audiotoolbox/1584145-converter_audio_unit_subtypes"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes":{"type":"topic","url":"/documentation/audiotoolbox/1584139-input_output_audio_unit_subtypes","title":"Input/Output Audio Unit Subtypes","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes","kind":"article","role":"collectionGroup","abstract":[{"text":"Input/output audio unit subtypes for audio units provided by Apple.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/topicSections","value":[{"title":"Constants","anchor":"Constants","identifiers":["doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_DefaultOutput","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_HALOutput","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_SystemOutput"]}]},{"path":"/seeAlsoSections","op":"replace","value":[{"title":"Enumerations","anchor":"Enumerations","generated":true,"identifiers":["doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584142-audio_unit_types","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534054-offline_audio_unit_properties","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389613-midi_audio_unit_parameters","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes","doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType"]}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_HALOutput/title","op":"replace","value":"kAudioUnitSubType_HALOutput"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_HALOutput/fragments","op":"replace","value":[{"kind":"identifier","text":"kAudioUnitSubType_HALOutput"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_SystemOutput/title","op":"replace","value":"kAudioUnitSubType_SystemOutput"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_SystemOutput/fragments","op":"replace","value":[{"text":"kAudioUnitSubType_SystemOutput","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEventType/title","op":"replace","value":"AudioUnitEventType"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEventType/fragments","op":"replace","value":[{"kind":"identifier","text":"AudioUnitEventType"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEventType/navigatorTitle","op":"replace","value":[{"text":"AudioUnitEventType","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_DefaultOutput/title","op":"replace","value":"kAudioUnitSubType_DefaultOutput"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_DefaultOutput/fragments","op":"replace","value":[{"kind":"identifier","text":"kAudioUnitSubType_DefaultOutput"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}