{
  "abstract": [
    {
      "text": "Effect (digital signal processing) audio unit subtypes for audio units provided by Apple.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584154-effect_audio_unit_subtypes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Effect Audio Unit Subtypes"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389643-aunewtimepitch-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389643-aunewtimepitch-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNewTimePitch Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389643-aunewtimepitch-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389781-aumultibandcompressor-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389781-aumultibandcompressor-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUMultibandCompressor Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389781-aumultibandcompressor-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389801-aumatrixreverb-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389801-aumatrixreverb-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUMatrixReverb Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389801-aumatrixreverb-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389946-autimepitch_autimepitch_offline": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389946-autimepitch_autimepitch_offline",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUTimePitch, AUTimePitch (offline), and AUPitch Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389946-autimepitch_autimepitch_offline"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390010-audelay-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390010-audelay-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUDelay Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390010-audelay-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390014-varispeed_unit_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Varispeed unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390014-varispeed_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Varispeed Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390014-varispeed_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390086-audistortion-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390086-audistortion-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUDistortion Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390086-audistortion-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390119-reverb_parameters": {
      "abstract": [
        {
          "text": "Additional reverb parameters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390119-reverb_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Reverb Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390119-reverb_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534061-audeferredrenderer-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534061-audeferredrenderer-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUDeferredRenderer Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534061-audeferredrenderer-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1615024-reverb_unit_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Reverb unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1615024-reverb_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Reverb Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1615024-reverb_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3547050-ausampledelay-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3547050-ausampledelay-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUSampleDelay Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/3547050-ausampledelay-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUReverbRoomType"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUReverbRoomType"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties": {
      "abstract": [
        {
          "text": "Obtain information about the built-in mixers, equalizers, filters, effects, and other Audio Unit app extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_AUSoundIsolation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_AUSoundIsolation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_AUSoundIsolation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_AUSoundIsolation"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_AUSoundIsolation",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_ausoundisolation"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_AUiPodEQ": {
      "abstract": [
        {
          "text": "An audio unit that provides a graphic equalizer in iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_AUiPodEQ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_AUiPodEQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_AUiPodEQ"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_AUiPodEQ",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_auipodeq"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_BandPassFilter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_BandPassFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_BandPassFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_BandPassFilter"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_BandPassFilter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_bandpassfilter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Delay": {
      "abstract": [
        {
          "text": "An audio unit that introduces a time delay to a signal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_Delay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Delay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_Delay"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_Delay",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_delay"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Distortion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_Distortion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Distortion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_Distortion"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_Distortion",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_distortion"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_DynamicsProcessor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_DynamicsProcessor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_DynamicsProcessor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_DynamicsProcessor"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_DynamicsProcessor",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_dynamicsprocessor"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_HighPassFilter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_HighPassFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_HighPassFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_HighPassFilter"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_HighPassFilter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_highpassfilter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_HighShelfFilter": {
      "abstract": [
        {
          "text": "An audio unit suitable for implementing a treble control in an audio playback or recording system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_HighShelfFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_HighShelfFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_HighShelfFilter"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_HighShelfFilter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_highshelffilter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_LowPassFilter": {
      "abstract": [
        {
          "text": "An audio unit that passes frequencies below a specified cutoff frequency, and blocks frequencies above that cutoff frequency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_LowPassFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_LowPassFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_LowPassFilter"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_LowPassFilter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_lowpassfilter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_LowShelfFilter": {
      "abstract": [
        {
          "text": "An audio unit suitable for implementing a bass control in an audio playback or recording system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_LowShelfFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_LowShelfFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_LowShelfFilter"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_LowShelfFilter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_lowshelffilter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_NBandEQ": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_NBandEQ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_NBandEQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_NBandEQ"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_NBandEQ",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_nbandeq"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_ParametricEQ": {
      "abstract": [
        {
          "text": "An audio unit that provides a filter whose center frequency, boost/cut level, and Q can be adjusted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_ParametricEQ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_ParametricEQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_ParametricEQ"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_ParametricEQ",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_parametriceq"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_PeakLimiter": {
      "abstract": [
        {
          "text": "An audio unit that enforces an upper dynamic limit on an audio signal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_PeakLimiter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_PeakLimiter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_PeakLimiter"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_PeakLimiter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_peaklimiter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Reverb2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_Reverb2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Reverb2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_Reverb2"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_Reverb2",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_reverb2"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_SampleDelay": {
      "abstract": [
        {
          "text": "An audio unit that provides a time delay for a specified number of samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_SampleDelay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_SampleDelay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_SampleDelay"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_SampleDelay",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_sampledelay"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Effects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389801-aumatrixreverb-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390086-audistortion-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390119-reverb_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1615024-reverb_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390014-varispeed_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390010-audelay-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389781-aumultibandcompressor-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534061-audeferredrenderer-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3547050-ausampledelay-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389643-aunewtimepitch-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389946-autimepitch_autimepitch_offline"
      ],
      "title": "Effects"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_AUiPodEQ",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_BandPassFilter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Delay",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Distortion",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_DynamicsProcessor",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_HighPassFilter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_HighShelfFilter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_LowPassFilter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_LowShelfFilter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_NBandEQ",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_ParametricEQ",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_PeakLimiter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_SampleDelay",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_AUSoundIsolation",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Reverb2"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_AUiPodEQ",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_BandPassFilter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Delay",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Distortion",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_DynamicsProcessor",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_HighPassFilter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_HighShelfFilter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_LowPassFilter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_LowShelfFilter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_NBandEQ",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_ParametricEQ",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_PeakLimiter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_SampleDelay",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_AUSoundIsolation",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Reverb2"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Effects",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389801-aumatrixreverb-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390086-audistortion-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390119-reverb_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1615024-reverb_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390014-varispeed_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390010-audelay-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389781-aumultibandcompressor-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534061-audeferredrenderer-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3547050-ausampledelay-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389643-aunewtimepitch-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389946-autimepitch_autimepitch_offline"
              ],
              "title": "Effects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_Delay/title",
          "value": "kAudioUnitSubType_Delay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_Delay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_Delay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_AUiPodEQ/title",
          "value": "kAudioUnitSubType_AUiPodEQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_AUiPodEQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_AUiPodEQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType/title",
          "value": "AUReverbRoomType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUReverbRoomType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUReverbRoomType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_ParametricEQ/title",
          "value": "kAudioUnitSubType_ParametricEQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_ParametricEQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_ParametricEQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_Reverb2/title",
          "value": "kAudioUnitSubType_Reverb2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_Reverb2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_Reverb2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_BandPassFilter/title",
          "value": "kAudioUnitSubType_BandPassFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_BandPassFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_BandPassFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_NBandEQ/title",
          "value": "kAudioUnitSubType_NBandEQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_NBandEQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_NBandEQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_LowShelfFilter/title",
          "value": "kAudioUnitSubType_LowShelfFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_LowShelfFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_LowShelfFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_SampleDelay/title",
          "value": "kAudioUnitSubType_SampleDelay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_SampleDelay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_SampleDelay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_LowPassFilter/title",
          "value": "kAudioUnitSubType_LowPassFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_LowPassFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_LowPassFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_Distortion/title",
          "value": "kAudioUnitSubType_Distortion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_Distortion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_Distortion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_HighPassFilter/title",
          "value": "kAudioUnitSubType_HighPassFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_HighPassFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_HighPassFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_AUSoundIsolation/title",
          "value": "kAudioUnitSubType_AUSoundIsolation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_AUSoundIsolation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_AUSoundIsolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_DynamicsProcessor/title",
          "value": "kAudioUnitSubType_DynamicsProcessor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_DynamicsProcessor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_DynamicsProcessor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_PeakLimiter/title",
          "value": "kAudioUnitSubType_PeakLimiter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_PeakLimiter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_PeakLimiter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_HighShelfFilter/title",
          "value": "kAudioUnitSubType_HighShelfFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_HighShelfFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_HighShelfFilter"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1584154-effect_audio_unit_subtypes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1584154-effect_audio_unit_subtypes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
