{
  "abstract": [
    {
      "text": "The defined types of audio processing plug-ins known as audio units.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584142-audio_unit_types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio Unit Types"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389613-midi_audio_unit_parameters": {
      "abstract": [
        {
          "text": "Parameters for instrument units.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389613-midi_audio_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Audio Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389613-midi_audio_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi": {
      "abstract": [
        {
          "text": "Reserved for system use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Reserved Audio Unit Clump Identifier",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1533986-reserved_audio_unit_clump_identi"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534054-offline_audio_unit_properties": {
      "abstract": [
        {
          "text": "Properties for audio units that perform offline processing—that is, processing in a nonplayback, nonrealtime mode.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534054-offline_audio_unit_properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Offline Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534054-offline_audio_unit_properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes": {
      "abstract": [
        {
          "text": "Input/output audio unit subtypes for audio units provided by Apple.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Input/Output Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584139-input_output_audio_unit_subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele": {
      "abstract": [
        {
          "text": "General audio unit component selectors that correspond to functions in the audio unit API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele",
      "kind": "article",
      "role": "collectionGroup",
      "title": "General Audio Unit Function Selectors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584140-general_audio_unit_function_sele"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi": {
      "abstract": [
        {
          "text": "The Apple audio unit manufacturer code.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Manufacturer Identifier",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584143-audio_unit_manufacturer_identifi"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes": {
      "abstract": [
        {
          "text": "Audio data format converter audio unit subtypes for audio units provided by Apple.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Converter Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584145-converter_audio_unit_subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584148-audio-unit-output-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584148-audio-unit-output-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Output Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584148-audio-unit-output-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Panner Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584151-audio-unit-panner-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Pitch Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584152-audio-unit-pitch-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Player Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584155-audio-unit-player-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "I/O Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1619485-i-o-audio-unit-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes": {
      "abstract": [
        {
          "text": "Audio units that serve as sound sources.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Generator Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1619493-generator_audio_unit_subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Inter-App Audio Unit Types",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1619501-inter-app-audio-unit-types"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitEventType"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitEventType"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitEventType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiouniteventtype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api": {
      "abstract": [
        {
          "text": "Configure an Audio Unit and prepare it to render audio.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit v2 (C) API",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-v2-c-api"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Effect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitType_Effect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Effect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitType_Effect"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitType_Effect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounittype_effect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_FormatConverter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitType_FormatConverter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_FormatConverter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitType_FormatConverter"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitType_FormatConverter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounittype_formatconverter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Generator": {
      "abstract": [
        {
          "text": "A generator unit provides audio output but has no audio input. This audio unit type is appropriate for a tone generator. Unlike an instrument unit, a generator unit does not have a control input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitType_Generator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Generator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitType_Generator"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitType_Generator",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounittype_generator"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_MIDIProcessor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitType_MIDIProcessor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_MIDIProcessor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitType_MIDIProcessor"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitType_MIDIProcessor",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounittype_midiprocessor"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Mixer": {
      "abstract": [
        {
          "text": "A mixer unit takes a number of input channels and mixes them to provide one or more output channels. For example, the ",
          "type": "text"
        },
        {
          "code": "kAudioUnitSubType_StereoMixer",
          "type": "codeVoice"
        },
        {
          "text": " audio unit in macOS takes multiple mono or stereo inputs and produce a single stereo output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitType_Mixer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Mixer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitType_Mixer"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitType_Mixer",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounittype_mixer"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_MusicDevice": {
      "abstract": [
        {
          "text": "An instrument unit can be used as a software musical instrument, such as a sampler or synthesizer. It responds to MIDI (Musical Instrument Digital Interface) control signals and can create notes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitType_MusicDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_MusicDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitType_MusicDevice"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitType_MusicDevice",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounittype_musicdevice"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_MusicEffect": {
      "abstract": [
        {
          "text": "An effect unit that can respond to MIDI control messages, typically through a mapping of  MIDI messages to parameters of the audio unit’s DSP algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitType_MusicEffect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_MusicEffect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitType_MusicEffect"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitType_MusicEffect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounittype_musiceffect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_OfflineEffect": {
      "abstract": [
        {
          "text": "An offline effect unit provides digital signal processing of a sort that cannot proceed in realtime. For example, level normalization requires examination of an entire sound, beginning to end, before the normalization factor can be calculated. As such, offline effect units also have a notion of a priming stage that can be performed before the actual rendering/processing phase is executed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitType_OfflineEffect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_OfflineEffect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitType_OfflineEffect"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitType_OfflineEffect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounittype_offlineeffect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Output": {
      "abstract": [
        {
          "text": "An output unit provides input, output, or both input and output simultaneously. It can be used as the head of an audio unit processing graph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitType_Output"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Output",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitType_Output"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitType_Output",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounittype_output"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Panner": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitType_Panner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Panner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitType_Panner"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitType_Panner",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounittype_panner"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_SpeechSynthesizer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitType_SpeechSynthesizer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_SpeechSynthesizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitType_SpeechSynthesizer"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitType_SpeechSynthesizer",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounittype_speechsynthesizer"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584148-audio-unit-output-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534054-offline_audio_unit_properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389613-midi_audio_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Types",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Output",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_MusicDevice",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_MusicEffect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_FormatConverter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Effect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Mixer",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Panner",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_OfflineEffect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Generator",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_MIDIProcessor",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_SpeechSynthesizer"
      ],
      "title": "Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Types",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Output",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_MusicDevice",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_MusicEffect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_FormatConverter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Effect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Mixer",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Panner",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_OfflineEffect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Generator",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_MIDIProcessor",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_SpeechSynthesizer"
              ],
              "title": "Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584148-audio-unit-output-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534054-offline_audio_unit_properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389613-midi_audio_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_Effect/title",
          "value": "kAudioUnitType_Effect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_Effect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitType_Effect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_MusicEffect/title",
          "value": "kAudioUnitType_MusicEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_MusicEffect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitType_MusicEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_OfflineEffect/title",
          "value": "kAudioUnitType_OfflineEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_OfflineEffect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitType_OfflineEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_Output/title",
          "value": "kAudioUnitType_Output"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_Output/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitType_Output"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_Generator/title",
          "value": "kAudioUnitType_Generator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_Generator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitType_Generator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_Mixer/title",
          "value": "kAudioUnitType_Mixer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_Mixer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitType_Mixer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_FormatConverter/title",
          "value": "kAudioUnitType_FormatConverter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_FormatConverter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitType_FormatConverter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_SpeechSynthesizer/title",
          "value": "kAudioUnitType_SpeechSynthesizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_SpeechSynthesizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitType_SpeechSynthesizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_Panner/title",
          "value": "kAudioUnitType_Panner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_Panner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitType_Panner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_MusicDevice/title",
          "value": "kAudioUnitType_MusicDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_MusicDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitType_MusicDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEventType/title",
          "value": "AudioUnitEventType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEventType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEventType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_MIDIProcessor/title",
          "value": "kAudioUnitType_MIDIProcessor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_MIDIProcessor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitType_MIDIProcessor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1584142-audio_unit_types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1584142-audio_unit_types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
