{
  "abstract": [
    {
      "text": "Audio unit component selectors, specific to I/O audio units, that correspond to functions in the audio unit API.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1585807-i_o_audio_unit_function_selector"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "I/O Audio Unit Function Selectors"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389633-aunetsend-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389633-aunetsend-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNetSend Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389633-aunetsend-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389891-net-status-audio-unit-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389891-net-status-audio-unit-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Net Status Audio Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389891-net-status-audio-unit-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389916-output_unit_parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389916-output_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Output Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389916-output_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389920-aunetreceive-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389920-aunetreceive-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNetReceive Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389920-aunetreceive-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534109-aunetreceive-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534109-aunetreceive-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNetReceive Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534109-aunetreceive-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534116-i_o_audio_unit_properties": {
      "abstract": [
        {
          "text": "Properties for Apple I/O audio units (sometimes called output units).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534116-i_o_audio_unit_properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "I/O Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534116-i_o_audio_unit_properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534207-aunetsend-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534207-aunetsend-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNetSend Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534207-aunetsend-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534212-aunetsendpresetformat-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534212-aunetsendpresetformat-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNetSendPresetFormat Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534212-aunetsendpresetformat-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621038-inter-app-audio-unit-property-ids": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621038-inter-app-audio-unit-property-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Inter-App Audio Unit Property IDs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1621038-inter-app-audio-unit-property-ids"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621039-inter-app-output-unit-property-ids": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621039-inter-app-output-unit-property-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Inter-App Output Unit Property IDs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1621039-inter-app-output-unit-property-ids"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitMIDICallbacks": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioOutputUnitMIDICallbacks"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitMIDICallbacks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioOutputUnitMIDICallbacks"
        }
      ],
      "role": "symbol",
      "title": "AudioOutputUnitMIDICallbacks",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiooutputunitmidicallbacks"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitStart(_:)": {
      "abstract": [
        {
          "text": "Starts an I/O audio unit, which in turn starts the audio unit processing graph that it is connected to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioOutputUnitStart"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnit",
          "text": "AudioUnit"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitStart(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioOutputUnitStart"
        }
      ],
      "role": "symbol",
      "title": "AudioOutputUnitStart(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiooutputunitstart(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitStartAtTimeParams": {
      "abstract": [
        {
          "text": "A timestamp for scheduled starting of an I/O audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioOutputUnitStartAtTimeParams"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitStartAtTimeParams",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioOutputUnitStartAtTimeParams"
        }
      ],
      "role": "symbol",
      "title": "AudioOutputUnitStartAtTimeParams",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiooutputunitstartattimeparams"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitStop(_:)": {
      "abstract": [
        {
          "text": "Stops an I/O audio unit, which in turn stops the audio unit processing graph that it is connected to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioOutputUnitStop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnit",
          "text": "AudioUnit"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitStop(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioOutputUnitStop"
        }
      ],
      "role": "symbol",
      "title": "AudioOutputUnitStop(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiooutputunitstop(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties": {
      "abstract": [
        {
          "text": "Obtain information about the built-in mixers, equalizers, filters, effects, and other Audio Unit app extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitRange": {
      "abstract": [
        {
          "text": "The start of the numerical range for I/O audio unit function selectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioOutputUnitRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioOutputUnitRange"
        }
      ],
      "role": "symbol",
      "title": "kAudioOutputUnitRange",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiooutputunitrange"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitStartSelect": {
      "abstract": [
        {
          "text": "Used by the system to start an I/O audio unit when you call the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitStart(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioOutputUnitStartSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitStartSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioOutputUnitStartSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioOutputUnitStartSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiooutputunitstartselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitStopSelect": {
      "abstract": [
        {
          "text": "Used by the system to stop an I/O audio unit when you call the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitStop(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioOutputUnitStopSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitStopSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioOutputUnitStopSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioOutputUnitStopSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiooutputunitstopselect"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "InputOutput",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534116-i_o_audio_unit_properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621039-inter-app-output-unit-property-ids",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621038-inter-app-audio-unit-property-ids",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389916-output_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534109-aunetreceive-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534207-aunetsend-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389633-aunetsend-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389920-aunetreceive-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534212-aunetsendpresetformat-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389891-net-status-audio-unit-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitMIDICallbacks",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitStartAtTimeParams"
      ],
      "title": "Input/Output"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitRange",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitStartSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitStopSelect"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitRange",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitStartSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitStopSelect"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "InputOutput",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534116-i_o_audio_unit_properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621039-inter-app-output-unit-property-ids",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621038-inter-app-audio-unit-property-ids",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389916-output_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534109-aunetreceive-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534207-aunetsend-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389633-aunetsend-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389920-aunetreceive-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534212-aunetsendpresetformat-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389891-net-status-audio-unit-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitMIDICallbacks",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitStartAtTimeParams"
              ],
              "title": "Input/Output"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioOutputUnitStopSelect/title",
          "value": "kAudioOutputUnitStopSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioOutputUnitStopSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioOutputUnitStopSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitStart(_:)/title",
          "value": "AudioOutputUnitStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitStart(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioOutputUnitStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitStartAtTimeParams/title",
          "value": "AudioOutputUnitStartAtTimeParams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitStartAtTimeParams/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioOutputUnitStartAtTimeParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitStartAtTimeParams/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioOutputUnitStartAtTimeParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioOutputUnitStartSelect/title",
          "value": "kAudioOutputUnitStartSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioOutputUnitStartSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioOutputUnitStartSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitStop(_:)/title",
          "value": "AudioOutputUnitStop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitStop(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioOutputUnitStop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioOutputUnitRange/title",
          "value": "kAudioOutputUnitRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioOutputUnitRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioOutputUnitRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitMIDICallbacks/title",
          "value": "AudioOutputUnitMIDICallbacks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitMIDICallbacks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioOutputUnitMIDICallbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitMIDICallbacks/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioOutputUnitMIDICallbacks"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1585807-i_o_audio_unit_function_selector"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1585807-i_o_audio_unit_function_selector"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
