{
  "abstract": [
    {
      "text": "Property identifiers used with Audio Session Services in iOS.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-session-support"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618455-audio-session-property-identifie"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio Session Property Identifiers"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these property identifiers in concert with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionGetProperty(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionSetProperty(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionAddPropertyListener(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " functions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618357-audio-session-activation-flags": {
      "abstract": [
        {
          "text": "Flags that provide additional information about your app’s audio intentions upon session activation or deactivation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618357-audio-session-activation-flags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Session Activation Flags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1618357-audio-session-activation-flags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618372-audio-session-category-route-ove": {
      "abstract": [
        {
          "text": "Specifies whether the default audio route for the ",
          "type": "text"
        },
        {
          "code": "PlayAndRecord",
          "type": "codeVoice"
        },
        {
          "text": " category should be overridden.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618372-audio-session-category-route-ove",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Session Category Route Overrides",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1618372-audio-session-category-route-ove"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618405-audio-session-modes": {
      "abstract": [
        {
          "text": "Mode identifiers for audio sessions, used as values for the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_Mode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618405-audio-session-modes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Session Modes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1618405-audio-session-modes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618425-audio-session-interruption-state": {
      "abstract": [
        {
          "text": "Identifiers used with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionInterruptionListener",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " callback function in iOS to indicate that an audio interruption has started or stopped.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618425-audio-session-interruption-state",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Session Interruption States",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1618425-audio-session-interruption-state"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618427-audio-session-categories": {
      "abstract": [
        {
          "text": "Category identifiers for audio sessions, used as values for the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioCategory",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618427-audio-session-categories",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Session Categories",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1618427-audio-session-categories"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionAddPropertyListener(_:_:_:)": {
      "abstract": [
        {
          "text": "Adds a property listener callback function to your application’s audio session object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioSessionAddPropertyListener"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioSessionPropertyID",
          "text": "AudioSessionPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioSessionPropertyListener",
          "text": "AudioSessionPropertyListener"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionAddPropertyListener(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioSessionAddPropertyListener"
        }
      ],
      "role": "symbol",
      "title": "AudioSessionAddPropertyListener(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiosessionaddpropertylistener(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionGetProperty(_:_:_:)": {
      "abstract": [
        {
          "text": "Gets the value of a specified audio session property.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioSessionGetProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioSessionPropertyID",
          "text": "AudioSessionPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionGetProperty(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioSessionGetProperty"
        }
      ],
      "role": "symbol",
      "title": "AudioSessionGetProperty(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiosessiongetproperty(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionInterruptionListener": {
      "abstract": [
        {
          "text": "Invoked when an audio interruption in iOS begins or ends.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioSessionInterruptionListener"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionInterruptionListener",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioSessionInterruptionListener"
        }
      ],
      "role": "symbol",
      "title": "AudioSessionInterruptionListener",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiosessioninterruptionlistener"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionInterruptionType": {
      "abstract": [
        {
          "text": "Values that indicate the nature of the interruption that ended.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioSessionInterruptionType"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionInterruptionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioSessionInterruptionType"
        }
      ],
      "role": "symbol",
      "title": "AudioSessionInterruptionType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiosessioninterruptiontype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionSetProperty(_:_:_:)": {
      "abstract": [
        {
          "text": "Sets the value of a specified audio session property.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioSessionSetProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioSessionPropertyID",
          "text": "AudioSessionPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionSetProperty(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioSessionSetProperty"
        }
      ],
      "role": "symbol",
      "title": "AudioSessionSetProperty(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiosessionsetproperty(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-session-support": {
      "abstract": [
        {
          "text": "Describe the properties that you associate with audio sessions and audio routes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-session-support",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Session Support",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-session-support"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_MediaPlayback": {
      "abstract": [
        {
          "text": "For playing recorded music or other sounds that are central to the successful use of your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionCategory_MediaPlayback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_MediaPlayback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionCategory_MediaPlayback"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionCategory_MediaPlayback",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessioncategory_mediaplayback"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_PlayAndRecord": {
      "abstract": [
        {
          "text": "Allows recording (input) and playback (output) of audio, such as for a VOIP (voice over IP) app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionCategory_PlayAndRecord"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_PlayAndRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionCategory_PlayAndRecord"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionCategory_PlayAndRecord",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessioncategory_playandrecord"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioCategory": {
      "abstract": [
        {
          "text": "The category for the audio session. A read/write ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_AudioCategory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_AudioCategory"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_AudioCategory",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_audiocategory"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioInputAvailable": {
      "abstract": [
        {
          "text": "Indicates if audio input is available (a nonzero value) or not (a value of 0).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_AudioInputAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioInputAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_AudioInputAvailable"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_AudioInputAvailable",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_audioinputavailable"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioRouteChange": {
      "abstract": [
        {
          "text": "The reason the audio route changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_AudioRouteChange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioRouteChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_AudioRouteChange"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_AudioRouteChange",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_audioroutechange"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioRouteDescription": {
      "abstract": [
        {
          "text": "Information about an audio route.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_AudioRouteDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioRouteDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_AudioRouteDescription"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_AudioRouteDescription",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_audioroutedescription"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareIOBufferDuration": {
      "abstract": [
        {
          "text": "Indicates the current hardware IO buffer duration, in seconds, as a read-only ",
          "type": "text"
        },
        {
          "code": "Float32",
          "type": "codeVoice"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_CurrentHardwareIOBufferDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareIOBufferDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_CurrentHardwareIOBufferDuration"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_CurrentHardwareIOBufferDuration",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_currenthardwareiobufferduration"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareInputLatency": {
      "abstract": [
        {
          "text": "Indicates the current hardware input latency, in seconds, as a read-only ",
          "type": "text"
        },
        {
          "code": "Float32",
          "type": "codeVoice"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_CurrentHardwareInputLatency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareInputLatency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_CurrentHardwareInputLatency"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_CurrentHardwareInputLatency",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_currenthardwareinputlatency"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareInputNumberChannels": {
      "abstract": [
        {
          "text": "Indicates the current number of audio hardware input channels. A read-only ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_CurrentHardwareInputNumberChannels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareInputNumberChannels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_CurrentHardwareInputNumberChannels"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_CurrentHardwareInputNumberChannels",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_currenthardwareinputnumberchannels"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareOutputLatency": {
      "abstract": [
        {
          "text": "Indicates the current hardware output latency, in seconds, as a read-only ",
          "type": "text"
        },
        {
          "code": "Float32",
          "type": "codeVoice"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_CurrentHardwareOutputLatency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareOutputLatency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_CurrentHardwareOutputLatency"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_CurrentHardwareOutputLatency",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_currenthardwareoutputlatency"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareOutputNumberChannels": {
      "abstract": [
        {
          "text": "Indicates the current number of audio hardware output channels. A read-only ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_CurrentHardwareOutputNumberChannels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareOutputNumberChannels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_CurrentHardwareOutputNumberChannels"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_CurrentHardwareOutputNumberChannels",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_currenthardwareoutputnumberchannels"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareOutputVolume": {
      "abstract": [
        {
          "text": "Indicates the current audio output volume as ",
          "type": "text"
        },
        {
          "code": "Float32",
          "type": "codeVoice"
        },
        {
          "text": " value between 0.0 and 1.0. Read-only. This value is available to your app by way of a property listener callback function. See ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionAddPropertyListener(_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_CurrentHardwareOutputVolume"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareOutputVolume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_CurrentHardwareOutputVolume"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_CurrentHardwareOutputVolume",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_currenthardwareoutputvolume"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareSampleRate": {
      "abstract": [
        {
          "text": "Indicates the current hardware sample rate. A read-only ",
          "type": "text"
        },
        {
          "code": "Float64",
          "type": "codeVoice"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_CurrentHardwareSampleRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareSampleRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_CurrentHardwareSampleRate"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_CurrentHardwareSampleRate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_currenthardwaresamplerate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_InputGainAvailable": {
      "abstract": [
        {
          "text": "A read-only ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value that indicates whether or not audio input gain adjustment is available, where a nonzero value means adjustment is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_InputGainAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_InputGainAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_InputGainAvailable"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_InputGainAvailable",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_inputgainavailable"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_InputGainScalar": {
      "abstract": [
        {
          "text": "A read/write ",
          "type": "text"
        },
        {
          "code": "Float32",
          "type": "codeVoice"
        },
        {
          "text": " value that indicates the audio input gain setting for the active input source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_InputGainScalar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_InputGainScalar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_InputGainScalar"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_InputGainScalar",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_inputgainscalar"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_InputSource": {
      "abstract": [
        {
          "text": "The audio input source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_InputSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_InputSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_InputSource"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_InputSource",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_inputsource"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_InputSources": {
      "abstract": [
        {
          "text": "Details on the available audio input sources.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_InputSources"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_InputSources",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_InputSources"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_InputSources",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_inputsources"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_InterruptionType": {
      "abstract": [
        {
          "text": "Indicates the type of an end-interruption event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_InterruptionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_InterruptionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_InterruptionType"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_InterruptionType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_interruptiontype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_Mode": {
      "abstract": [
        {
          "text": "A read/write ",
          "type": "text"
        },
        {
          "code": "UIInt32",
          "type": "codeVoice"
        },
        {
          "text": " value that specifies the audio session mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_Mode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_Mode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_Mode"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_Mode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_mode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OtherAudioIsPlaying": {
      "abstract": [
        {
          "text": "Indicates whether or not another app (typically, the iPod app) is currently playing audio. Read-only. A non-zero ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value indicates that other audio is playing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_OtherAudioIsPlaying"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OtherAudioIsPlaying",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_OtherAudioIsPlaying"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_OtherAudioIsPlaying",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_otheraudioisplaying"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OtherMixableAudioShouldDuck": {
      "abstract": [
        {
          "text": "For audio session categories that allow audio mixing with other apps, specifies whether other audio should be reduced in level when your app produces sound. This property has a value of ",
          "type": "text"
        },
        {
          "code": "FALSE",
          "type": "codeVoice"
        },
        {
          "text": " (0) by default. Set it to a nonzero value to turn on ducking.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_OtherMixableAudioShouldDuck"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OtherMixableAudioShouldDuck",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_OtherMixableAudioShouldDuck"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_OtherMixableAudioShouldDuck",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_othermixableaudioshouldduck"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OutputDestination": {
      "abstract": [
        {
          "text": "The audio output destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_OutputDestination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OutputDestination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_OutputDestination"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_OutputDestination",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_outputdestination"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OutputDestinations": {
      "abstract": [
        {
          "text": "Details on the available audio output destinations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_OutputDestinations"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OutputDestinations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_OutputDestinations"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_OutputDestinations",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_outputdestinations"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OverrideAudioRoute": {
      "abstract": [
        {
          "text": "Specifies whether or not to override the audio session category’s typical audio route.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_OverrideAudioRoute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OverrideAudioRoute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_OverrideAudioRoute"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_OverrideAudioRoute",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_overrideaudioroute"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OverrideCategoryDefaultToSpeaker": {
      "abstract": [
        {
          "text": "Specifies whether or not to route audio to the speaker (instead of to the receiver) when no other audio route, such as a headset, is connected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_OverrideCategoryDefaultToSpeaker"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OverrideCategoryDefaultToSpeaker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_OverrideCategoryDefaultToSpeaker"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_OverrideCategoryDefaultToSpeaker",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_overridecategorydefaulttospeaker"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OverrideCategoryEnableBluetoothInput": {
      "abstract": [
        {
          "text": "Allows a paired Bluetooth device to appear as an available audio input route.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_OverrideCategoryEnableBluetoothInput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OverrideCategoryEnableBluetoothInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_OverrideCategoryEnableBluetoothInput"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_OverrideCategoryEnableBluetoothInput",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_overridecategoryenablebluetoothinput"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OverrideCategoryMixWithOthers": {
      "abstract": [
        {
          "text": "Changes the mixing behavior of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_MediaPlayback",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_PlayAndRecord",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " audio session categories.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_OverrideCategoryMixWithOthers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OverrideCategoryMixWithOthers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_OverrideCategoryMixWithOthers"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_OverrideCategoryMixWithOthers",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_overridecategorymixwithothers"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_PreferredHardwareIOBufferDuration": {
      "abstract": [
        {
          "text": "Your preferred hardware I/O buffer duration in seconds. Do not set this property unless you require lower I/O latency than is provided by default.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_PreferredHardwareIOBufferDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_PreferredHardwareIOBufferDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_PreferredHardwareIOBufferDuration"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_PreferredHardwareIOBufferDuration",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_preferredhardwareiobufferduration"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_PreferredHardwareSampleRate": {
      "abstract": [
        {
          "text": "Your preferred hardware sample rate for the audio session. A read/write ",
          "type": "text"
        },
        {
          "code": "Float64",
          "type": "codeVoice"
        },
        {
          "text": " value. The actual sample rate may be different and can be obtained using the ",
          "type": "text"
        },
        {
          "code": "kAudioSessionProperty_CurrentHardwareSampleRate",
          "type": "codeVoice"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_PreferredHardwareSampleRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_PreferredHardwareSampleRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_PreferredHardwareSampleRate"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_PreferredHardwareSampleRate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_preferredhardwaresamplerate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_ServerDied": {
      "abstract": [
        {
          "text": "Indicates if the audio server has died (indicated by a nonzero ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value) or is still running (a value of 0).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_ServerDied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_ServerDied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_ServerDied"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_ServerDied",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_serverdied"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Audio-Session-Support",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618427-audio-session-categories",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618405-audio-session-modes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618372-audio-session-category-route-ove",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618357-audio-session-activation-flags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618425-audio-session-interruption-state",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionInterruptionType"
      ],
      "title": "Audio Session Support"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_PreferredHardwareSampleRate",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_PreferredHardwareIOBufferDuration",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioCategory",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioRouteChange",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareSampleRate",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareInputNumberChannels",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareOutputNumberChannels",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareOutputVolume",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareInputLatency",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareOutputLatency",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareIOBufferDuration",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OtherAudioIsPlaying",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OverrideAudioRoute",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioInputAvailable",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_ServerDied",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OtherMixableAudioShouldDuck",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OverrideCategoryMixWithOthers",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OverrideCategoryDefaultToSpeaker",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OverrideCategoryEnableBluetoothInput",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_InterruptionType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_Mode",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_InputSources",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OutputDestinations",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_InputSource",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OutputDestination",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_InputGainAvailable",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_InputGainScalar",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioRouteDescription"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_PreferredHardwareSampleRate",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_PreferredHardwareIOBufferDuration",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioCategory",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioRouteChange",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareSampleRate",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareInputNumberChannels",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareOutputNumberChannels",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareOutputVolume",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareInputLatency",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareOutputLatency",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareIOBufferDuration",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OtherAudioIsPlaying",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OverrideAudioRoute",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioInputAvailable",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_ServerDied",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OtherMixableAudioShouldDuck",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OverrideCategoryMixWithOthers",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OverrideCategoryDefaultToSpeaker",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OverrideCategoryEnableBluetoothInput",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_InterruptionType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_Mode",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_InputSources",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OutputDestinations",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_InputSource",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OutputDestination",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_InputGainAvailable",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_InputGainScalar",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioRouteDescription"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Audio-Session-Support",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618427-audio-session-categories",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618405-audio-session-modes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618372-audio-session-category-route-ove",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618357-audio-session-activation-flags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618425-audio-session-interruption-state",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionInterruptionType"
              ],
              "title": "Audio Session Support"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_OverrideCategoryEnableBluetoothInput/title",
          "value": "kAudioSessionProperty_OverrideCategoryEnableBluetoothInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_OverrideCategoryEnableBluetoothInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_OverrideCategoryEnableBluetoothInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_AudioInputAvailable/title",
          "value": "kAudioSessionProperty_AudioInputAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_AudioInputAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_AudioInputAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_OutputDestination/title",
          "value": "kAudioSessionProperty_OutputDestination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_OutputDestination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_OutputDestination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_CurrentHardwareOutputVolume/title",
          "value": "kAudioSessionProperty_CurrentHardwareOutputVolume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_CurrentHardwareOutputVolume/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_CurrentHardwareOutputVolume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_PreferredHardwareIOBufferDuration/title",
          "value": "kAudioSessionProperty_PreferredHardwareIOBufferDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_PreferredHardwareIOBufferDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_PreferredHardwareIOBufferDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_InterruptionType/title",
          "value": "kAudioSessionProperty_InterruptionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_InterruptionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_InterruptionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_OverrideCategoryMixWithOthers/title",
          "value": "kAudioSessionProperty_OverrideCategoryMixWithOthers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_OverrideCategoryMixWithOthers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_OverrideCategoryMixWithOthers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_AudioRouteDescription/title",
          "value": "kAudioSessionProperty_AudioRouteDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_AudioRouteDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_AudioRouteDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_OutputDestinations/title",
          "value": "kAudioSessionProperty_OutputDestinations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_OutputDestinations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_OutputDestinations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_OverrideAudioRoute/title",
          "value": "kAudioSessionProperty_OverrideAudioRoute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_OverrideAudioRoute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_OverrideAudioRoute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_CurrentHardwareOutputNumberChannels/title",
          "value": "kAudioSessionProperty_CurrentHardwareOutputNumberChannels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_CurrentHardwareOutputNumberChannels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_CurrentHardwareOutputNumberChannels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_InputSources/title",
          "value": "kAudioSessionProperty_InputSources"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_InputSources/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_InputSources"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_InputGainAvailable/title",
          "value": "kAudioSessionProperty_InputGainAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_InputGainAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_InputGainAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_PreferredHardwareSampleRate/title",
          "value": "kAudioSessionProperty_PreferredHardwareSampleRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_PreferredHardwareSampleRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_PreferredHardwareSampleRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionCategory_PlayAndRecord/title",
          "value": "kAudioSessionCategory_PlayAndRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionCategory_PlayAndRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionCategory_PlayAndRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionInterruptionType/title",
          "value": "AudioSessionInterruptionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionInterruptionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioSessionInterruptionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionInterruptionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioSessionInterruptionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionCategory_MediaPlayback/title",
          "value": "kAudioSessionCategory_MediaPlayback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionCategory_MediaPlayback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionCategory_MediaPlayback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_CurrentHardwareInputLatency/title",
          "value": "kAudioSessionProperty_CurrentHardwareInputLatency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_CurrentHardwareInputLatency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_CurrentHardwareInputLatency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_OtherMixableAudioShouldDuck/title",
          "value": "kAudioSessionProperty_OtherMixableAudioShouldDuck"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_OtherMixableAudioShouldDuck/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_OtherMixableAudioShouldDuck"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionAddPropertyListener(_:_:_:)/title",
          "value": "AudioSessionAddPropertyListener"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionAddPropertyListener(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioSessionAddPropertyListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_OtherAudioIsPlaying/title",
          "value": "kAudioSessionProperty_OtherAudioIsPlaying"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_OtherAudioIsPlaying/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_OtherAudioIsPlaying"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_InputGainScalar/title",
          "value": "kAudioSessionProperty_InputGainScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_InputGainScalar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_InputGainScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_ServerDied/title",
          "value": "kAudioSessionProperty_ServerDied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_ServerDied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_ServerDied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_InputSource/title",
          "value": "kAudioSessionProperty_InputSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_InputSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_InputSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_CurrentHardwareSampleRate/title",
          "value": "kAudioSessionProperty_CurrentHardwareSampleRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_CurrentHardwareSampleRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_CurrentHardwareSampleRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionSetProperty(_:_:_:)/title",
          "value": "AudioSessionSetProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionSetProperty(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioSessionSetProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_CurrentHardwareOutputLatency/title",
          "value": "kAudioSessionProperty_CurrentHardwareOutputLatency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_CurrentHardwareOutputLatency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_CurrentHardwareOutputLatency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_CurrentHardwareIOBufferDuration/title",
          "value": "kAudioSessionProperty_CurrentHardwareIOBufferDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_CurrentHardwareIOBufferDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_CurrentHardwareIOBufferDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionGetProperty(_:_:_:)/title",
          "value": "AudioSessionGetProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionGetProperty(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioSessionGetProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_OverrideCategoryDefaultToSpeaker/title",
          "value": "kAudioSessionProperty_OverrideCategoryDefaultToSpeaker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_OverrideCategoryDefaultToSpeaker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_OverrideCategoryDefaultToSpeaker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_Mode/title",
          "value": "kAudioSessionProperty_Mode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_Mode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_Mode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_AudioCategory/title",
          "value": "kAudioSessionProperty_AudioCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_AudioCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_AudioCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_AudioRouteChange/title",
          "value": "kAudioSessionProperty_AudioRouteChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_AudioRouteChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_AudioRouteChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionInterruptionListener/title",
          "value": "AudioSessionInterruptionListener"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionInterruptionListener/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioSessionInterruptionListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionInterruptionListener/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioSessionInterruptionListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_CurrentHardwareInputNumberChannels/title",
          "value": "kAudioSessionProperty_CurrentHardwareInputNumberChannels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_CurrentHardwareInputNumberChannels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_CurrentHardwareInputNumberChannels"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1618455-audio-session-property-identifie"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1618455-audio-session-property-identifie"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
