{
  "abstract": [
    {
      "text": "Category identifiers for audio sessions, used as values for the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioCategory",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " property.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-session-support"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618427-audio-session-categories"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio Session Categories"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Each app running in iOS has a single audio session, which in turn has a single category. You can change your audio session’s category while your app is running.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can refine the configuration provided by the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_RecordAudio",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_PlayAndRecord",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " categories by using an audio session mode, as described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618405-audio-session-modes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_AmbientSound",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " category when you want your sounds to mix with other audio (such as from the iPod app). Use one of the other playback categories when you want audio from other apps to be silenced when your session is active. However, you can enable mixing for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_MediaPlayback",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_PlayAndRecord",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " categories by using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OverrideCategoryMixWithOthers",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property. For more information on audio session categories, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40007875",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618357-audio-session-activation-flags": {
      "abstract": [
        {
          "text": "Flags that provide additional information about your app’s audio intentions upon session activation or deactivation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618357-audio-session-activation-flags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Session Activation Flags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1618357-audio-session-activation-flags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618372-audio-session-category-route-ove": {
      "abstract": [
        {
          "text": "Specifies whether the default audio route for the ",
          "type": "text"
        },
        {
          "code": "PlayAndRecord",
          "type": "codeVoice"
        },
        {
          "text": " category should be overridden.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618372-audio-session-category-route-ove",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Session Category Route Overrides",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1618372-audio-session-category-route-ove"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618405-audio-session-modes": {
      "abstract": [
        {
          "text": "Mode identifiers for audio sessions, used as values for the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_Mode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618405-audio-session-modes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Session Modes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1618405-audio-session-modes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618425-audio-session-interruption-state": {
      "abstract": [
        {
          "text": "Identifiers used with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionInterruptionListener",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " callback function in iOS to indicate that an audio interruption has started or stopped.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618425-audio-session-interruption-state",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Session Interruption States",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1618425-audio-session-interruption-state"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618455-audio-session-property-identifie": {
      "abstract": [
        {
          "text": "Property identifiers used with Audio Session Services in iOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618455-audio-session-property-identifie",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Session Property Identifiers",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1618455-audio-session-property-identifie"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionInterruptionListener": {
      "abstract": [
        {
          "text": "Invoked when an audio interruption in iOS begins or ends.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioSessionInterruptionListener"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionInterruptionListener",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioSessionInterruptionListener"
        }
      ],
      "role": "symbol",
      "title": "AudioSessionInterruptionListener",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiosessioninterruptionlistener"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionInterruptionType": {
      "abstract": [
        {
          "text": "Values that indicate the nature of the interruption that ended.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioSessionInterruptionType"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionInterruptionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioSessionInterruptionType"
        }
      ],
      "role": "symbol",
      "title": "AudioSessionInterruptionType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiosessioninterruptiontype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionSetProperty(_:_:_:)": {
      "abstract": [
        {
          "text": "Sets the value of a specified audio session property.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioSessionSetProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioSessionPropertyID",
          "text": "AudioSessionPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionSetProperty(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioSessionSetProperty"
        }
      ],
      "role": "symbol",
      "title": "AudioSessionSetProperty(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiosessionsetproperty(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-session-support": {
      "abstract": [
        {
          "text": "Describe the properties that you associate with audio sessions and audio routes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-session-support",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Session Support",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-session-support"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_AmbientSound": {
      "abstract": [
        {
          "text": "For an app in which sound playback is nonprimary—that is, your app can be used successfully with the sound turned off.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionCategory_AmbientSound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_AmbientSound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionCategory_AmbientSound"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionCategory_AmbientSound",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessioncategory_ambientsound"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_AudioProcessing": {
      "abstract": [
        {
          "text": "For using an audio hardware codec or signal processor while not playing or recording audio. Use this category, for example, when performing offline audio format conversion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionCategory_AudioProcessing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_AudioProcessing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionCategory_AudioProcessing"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionCategory_AudioProcessing",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessioncategory_audioprocessing"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_MediaPlayback": {
      "abstract": [
        {
          "text": "For playing recorded music or other sounds that are central to the successful use of your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionCategory_MediaPlayback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_MediaPlayback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionCategory_MediaPlayback"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionCategory_MediaPlayback",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessioncategory_mediaplayback"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_PlayAndRecord": {
      "abstract": [
        {
          "text": "Allows recording (input) and playback (output) of audio, such as for a VOIP (voice over IP) app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionCategory_PlayAndRecord"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_PlayAndRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionCategory_PlayAndRecord"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionCategory_PlayAndRecord",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessioncategory_playandrecord"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_RecordAudio": {
      "abstract": [
        {
          "text": "For recording audio; this category silences playback audio. Recording continues with the screen locked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionCategory_RecordAudio"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_RecordAudio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionCategory_RecordAudio"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionCategory_RecordAudio",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessioncategory_recordaudio"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_SoloAmbientSound": {
      "abstract": [
        {
          "text": "The default category, used unless you set a category with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionSetProperty(_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionCategory_SoloAmbientSound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_SoloAmbientSound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionCategory_SoloAmbientSound"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionCategory_SoloAmbientSound",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessioncategory_soloambientsound"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioCategory": {
      "abstract": [
        {
          "text": "The category for the audio session. A read/write ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_AudioCategory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_AudioCategory"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_AudioCategory",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_audiocategory"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_Mode": {
      "abstract": [
        {
          "text": "A read/write ",
          "type": "text"
        },
        {
          "code": "UIInt32",
          "type": "codeVoice"
        },
        {
          "text": " value that specifies the audio session mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_Mode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_Mode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_Mode"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_Mode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_mode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OverrideCategoryMixWithOthers": {
      "abstract": [
        {
          "text": "Changes the mixing behavior of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_MediaPlayback",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_PlayAndRecord",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " audio session categories.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_OverrideCategoryMixWithOthers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OverrideCategoryMixWithOthers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_OverrideCategoryMixWithOthers"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_OverrideCategoryMixWithOthers",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_overridecategorymixwithothers"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/library/archive/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40007875": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40007875",
      "title": "Audio Session Programming Guide",
      "titleInlineContent": [
        {
          "text": "Audio Session Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40007875"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Audio-Session-Support",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618455-audio-session-property-identifie",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618405-audio-session-modes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618372-audio-session-category-route-ove",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618357-audio-session-activation-flags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618425-audio-session-interruption-state",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionInterruptionType"
      ],
      "title": "Audio Session Support"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_AmbientSound",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_SoloAmbientSound",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_MediaPlayback",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_RecordAudio",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_PlayAndRecord",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_AudioProcessing"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_AmbientSound",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_SoloAmbientSound",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_MediaPlayback",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_RecordAudio",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_PlayAndRecord",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionCategory_AudioProcessing"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Audio-Session-Support",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618455-audio-session-property-identifie",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618405-audio-session-modes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618372-audio-session-category-route-ove",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618357-audio-session-activation-flags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618425-audio-session-interruption-state",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionInterruptionType"
              ],
              "title": "Audio Session Support"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionCategory_PlayAndRecord/title",
          "value": "kAudioSessionCategory_PlayAndRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionCategory_PlayAndRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionCategory_PlayAndRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionCategory_RecordAudio/title",
          "value": "kAudioSessionCategory_RecordAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionCategory_RecordAudio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionCategory_RecordAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionInterruptionType/title",
          "value": "AudioSessionInterruptionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionInterruptionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioSessionInterruptionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionInterruptionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioSessionInterruptionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionInterruptionListener/title",
          "value": "AudioSessionInterruptionListener"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionInterruptionListener/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioSessionInterruptionListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionInterruptionListener/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioSessionInterruptionListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionCategory_AmbientSound/title",
          "value": "kAudioSessionCategory_AmbientSound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionCategory_AmbientSound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionCategory_AmbientSound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_OverrideCategoryMixWithOthers/title",
          "value": "kAudioSessionProperty_OverrideCategoryMixWithOthers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_OverrideCategoryMixWithOthers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_OverrideCategoryMixWithOthers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionCategory_SoloAmbientSound/title",
          "value": "kAudioSessionCategory_SoloAmbientSound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionCategory_SoloAmbientSound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionCategory_SoloAmbientSound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionCategory_MediaPlayback/title",
          "value": "kAudioSessionCategory_MediaPlayback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionCategory_MediaPlayback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionCategory_MediaPlayback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionSetProperty(_:_:_:)/title",
          "value": "AudioSessionSetProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionSetProperty(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioSessionSetProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_Mode/title",
          "value": "kAudioSessionProperty_Mode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_Mode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_Mode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionCategory_AudioProcessing/title",
          "value": "kAudioSessionCategory_AudioProcessing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionCategory_AudioProcessing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionCategory_AudioProcessing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_AudioCategory/title",
          "value": "kAudioSessionProperty_AudioCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_AudioCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_AudioCategory"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1618427-audio-session-categories"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1618427-audio-session-categories"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
