{
  "abstract": [
    {
      "text": "Flags that provide additional information about your app’s audio intentions upon session activation or deactivation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-session-support"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618357-audio-session-activation-flags"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio Session Activation Flags"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618372-audio-session-category-route-ove": {
      "abstract": [
        {
          "text": "Specifies whether the default audio route for the ",
          "type": "text"
        },
        {
          "code": "PlayAndRecord",
          "type": "codeVoice"
        },
        {
          "text": " category should be overridden.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618372-audio-session-category-route-ove",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Session Category Route Overrides",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1618372-audio-session-category-route-ove"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618405-audio-session-modes": {
      "abstract": [
        {
          "text": "Mode identifiers for audio sessions, used as values for the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_Mode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618405-audio-session-modes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Session Modes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1618405-audio-session-modes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618425-audio-session-interruption-state": {
      "abstract": [
        {
          "text": "Identifiers used with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionInterruptionListener",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " callback function in iOS to indicate that an audio interruption has started or stopped.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618425-audio-session-interruption-state",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Session Interruption States",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1618425-audio-session-interruption-state"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618427-audio-session-categories": {
      "abstract": [
        {
          "text": "Category identifiers for audio sessions, used as values for the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioCategory",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618427-audio-session-categories",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Session Categories",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1618427-audio-session-categories"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618455-audio-session-property-identifie": {
      "abstract": [
        {
          "text": "Property identifiers used with Audio Session Services in iOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618455-audio-session-property-identifie",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Session Property Identifiers",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1618455-audio-session-property-identifie"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionInterruptionListener": {
      "abstract": [
        {
          "text": "Invoked when an audio interruption in iOS begins or ends.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioSessionInterruptionListener"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionInterruptionListener",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioSessionInterruptionListener"
        }
      ],
      "role": "symbol",
      "title": "AudioSessionInterruptionListener",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiosessioninterruptionlistener"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionInterruptionType": {
      "abstract": [
        {
          "text": "Values that indicate the nature of the interruption that ended.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioSessionInterruptionType"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionInterruptionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioSessionInterruptionType"
        }
      ],
      "role": "symbol",
      "title": "AudioSessionInterruptionType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiosessioninterruptiontype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-session-support": {
      "abstract": [
        {
          "text": "Describe the properties that you associate with audio sessions and audio routes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-session-support",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Session Support",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-session-support"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioCategory": {
      "abstract": [
        {
          "text": "The category for the audio session. A read/write ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_AudioCategory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_AudioCategory"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_AudioCategory",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_audiocategory"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_Mode": {
      "abstract": [
        {
          "text": "A read/write ",
          "type": "text"
        },
        {
          "code": "UIInt32",
          "type": "codeVoice"
        },
        {
          "text": " value that specifies the audio session mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_Mode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_Mode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_Mode"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_Mode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_mode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionSetActiveFlag_NotifyOthersOnDeactivation": {
      "abstract": [
        {
          "text": "Indicates that when your audio session deactivates, other audio sessions that had been interrupted by your session can return to their active state.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionSetActiveFlag_NotifyOthersOnDeactivation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionSetActiveFlag_NotifyOthersOnDeactivation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionSetActiveFlag_NotifyOthersOnDeactivation"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionSetActiveFlag_NotifyOthersOnDeactivation",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionsetactiveflag_notifyothersondeactivation"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Audio-Session-Support",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618455-audio-session-property-identifie",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618427-audio-session-categories",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618405-audio-session-modes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618372-audio-session-category-route-ove",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618425-audio-session-interruption-state",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionInterruptionType"
      ],
      "title": "Audio Session Support"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionSetActiveFlag_NotifyOthersOnDeactivation"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionSetActiveFlag_NotifyOthersOnDeactivation"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Audio-Session-Support",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618455-audio-session-property-identifie",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618427-audio-session-categories",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618405-audio-session-modes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618372-audio-session-category-route-ove",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618425-audio-session-interruption-state",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionInterruptionType"
              ],
              "title": "Audio Session Support"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_Mode/title",
          "value": "kAudioSessionProperty_Mode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_Mode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_Mode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionSetActiveFlag_NotifyOthersOnDeactivation/title",
          "value": "kAudioSessionSetActiveFlag_NotifyOthersOnDeactivation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionSetActiveFlag_NotifyOthersOnDeactivation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionSetActiveFlag_NotifyOthersOnDeactivation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionInterruptionType/title",
          "value": "AudioSessionInterruptionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionInterruptionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioSessionInterruptionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionInterruptionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioSessionInterruptionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_AudioCategory/title",
          "value": "kAudioSessionProperty_AudioCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_AudioCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_AudioCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionInterruptionListener/title",
          "value": "AudioSessionInterruptionListener"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionInterruptionListener/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioSessionInterruptionListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionInterruptionListener/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioSessionInterruptionListener"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1618357-audio-session-activation-flags"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1618357-audio-session-activation-flags"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
