{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-queue-services"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618727-audio-queue-hardware-codec-polic"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio Queue Hardware Codec Policy"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1552627-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1552627-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1552627-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1552629-audio-queue-property-ids": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1552629-audio-queue-property-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Queue Property IDs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1552629-audio-queue-property-ids"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1552630-audio-queue-time-pitch-algorithm": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1552630-audio-queue-time-pitch-algorithm",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Queue Time Pitch Algorithms",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1552630-audio-queue-time-pitch-algorithm"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618733-audio-queue-property-ids": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618733-audio-queue-property-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Queue Property IDs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1618733-audio-queue-property-ids"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueProcessingTapFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueProcessingTapFlags"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueProcessingTapFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueueprocessingtapflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-queue-services": {
      "abstract": [
        {
          "text": "Connect to audio hardware and manage the recording or playback process.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-queue-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Queue Services",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-queue-services"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_Default": {
      "abstract": [
        {
          "text": "If the required codec is available in both hardware and software implementations, the audio queue will use a hardware codec if its audio session category permits; it will use a software codec otherwise. If the required codec is available in only one form, that codec implementation is used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueHardwareCodecPolicy_Default"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_Default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueHardwareCodecPolicy_Default"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueHardwareCodecPolicy_Default",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueuehardwarecodecpolicy_default"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_PreferHardware": {
      "abstract": [
        {
          "text": "The audio queue will use a hardware codec if one is available and if its use permitted by the audio session category that you have set; otherwise, it will use a software codec if one is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueHardwareCodecPolicy_PreferHardware"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_PreferHardware",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueHardwareCodecPolicy_PreferHardware"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueHardwareCodecPolicy_PreferHardware",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueuehardwarecodecpolicy_preferhardware"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_PreferSoftware": {
      "abstract": [
        {
          "text": "The audio queue will use a software codec if one is available; if not, it will use a hardware codec if one is available and if its use is permitted by the audio session category that you have set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueHardwareCodecPolicy_PreferSoftware"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_PreferSoftware",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueHardwareCodecPolicy_PreferSoftware"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueHardwareCodecPolicy_PreferSoftware",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueuehardwarecodecpolicy_prefersoftware"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_UseHardwareOnly": {
      "abstract": [
        {
          "text": "The audio queue will use a hardware codec if one is available and if its use is permitted by the audio session category that you have set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueHardwareCodecPolicy_UseHardwareOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_UseHardwareOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueHardwareCodecPolicy_UseHardwareOnly"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueHardwareCodecPolicy_UseHardwareOnly",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueuehardwarecodecpolicy_usehardwareonly"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_UseSoftwareOnly": {
      "abstract": [
        {
          "text": "The audio queue will use a software codec if one is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueHardwareCodecPolicy_UseSoftwareOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_UseSoftwareOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueHardwareCodecPolicy_UseSoftwareOnly"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueHardwareCodecPolicy_UseSoftwareOnly",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueuehardwarecodecpolicy_usesoftwareonly"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1552627-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1552630-audio-queue-time-pitch-algorithm",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1552629-audio-queue-property-ids",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618733-audio-queue-property-ids"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_Default",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_PreferHardware",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_PreferSoftware",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_UseHardwareOnly",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_UseSoftwareOnly"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_Default",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_PreferHardware",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_PreferSoftware",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_UseHardwareOnly",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_UseSoftwareOnly"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapFlags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1552627-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1552630-audio-queue-time-pitch-algorithm",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1552629-audio-queue-property-ids",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618733-audio-queue-property-ids"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueHardwareCodecPolicy_Default/title",
          "value": "kAudioQueueHardwareCodecPolicy_Default"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueHardwareCodecPolicy_Default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueHardwareCodecPolicy_Default"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueHardwareCodecPolicy_PreferHardware/title",
          "value": "kAudioQueueHardwareCodecPolicy_PreferHardware"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueHardwareCodecPolicy_PreferHardware/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueHardwareCodecPolicy_PreferHardware"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueHardwareCodecPolicy_PreferSoftware/title",
          "value": "kAudioQueueHardwareCodecPolicy_PreferSoftware"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueHardwareCodecPolicy_PreferSoftware/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueHardwareCodecPolicy_PreferSoftware"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueHardwareCodecPolicy_UseSoftwareOnly/title",
          "value": "kAudioQueueHardwareCodecPolicy_UseSoftwareOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueHardwareCodecPolicy_UseSoftwareOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueHardwareCodecPolicy_UseSoftwareOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueHardwareCodecPolicy_UseHardwareOnly/title",
          "value": "kAudioQueueHardwareCodecPolicy_UseHardwareOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueHardwareCodecPolicy_UseHardwareOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueHardwareCodecPolicy_UseHardwareOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueProcessingTapFlags/title",
          "value": "AudioQueueProcessingTapFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueProcessingTapFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueProcessingTapFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueProcessingTapFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueProcessingTapFlags"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1618727-audio-queue-hardware-codec-polic"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1618727-audio-queue-hardware-codec-polic"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
