{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621039-inter-app-output-unit-property-ids"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Inter-App Output Unit Property IDs"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389633-aunetsend-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389633-aunetsend-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNetSend Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389633-aunetsend-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389891-net-status-audio-unit-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389891-net-status-audio-unit-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Net Status Audio Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389891-net-status-audio-unit-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389916-output_unit_parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389916-output_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Output Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389916-output_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389920-aunetreceive-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389920-aunetreceive-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNetReceive Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389920-aunetreceive-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534109-aunetreceive-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534109-aunetreceive-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNetReceive Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534109-aunetreceive-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534116-i_o_audio_unit_properties": {
      "abstract": [
        {
          "text": "Properties for Apple I/O audio units (sometimes called output units).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534116-i_o_audio_unit_properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "I/O Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534116-i_o_audio_unit_properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534207-aunetsend-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534207-aunetsend-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNetSend Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534207-aunetsend-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534212-aunetsendpresetformat-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534212-aunetsendpresetformat-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNetSendPresetFormat Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534212-aunetsendpresetformat-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1585807-i_o_audio_unit_function_selector": {
      "abstract": [
        {
          "text": "Audio unit component selectors, specific to I/O audio units, that correspond to functions in the audio unit API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1585807-i_o_audio_unit_function_selector",
      "kind": "article",
      "role": "collectionGroup",
      "title": "I/O Audio Unit Function Selectors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1585807-i_o_audio_unit_function_selector"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621038-inter-app-audio-unit-property-ids": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621038-inter-app-audio-unit-property-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Inter-App Audio Unit Property IDs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1621038-inter-app-audio-unit-property-ids"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitMIDICallbacks": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioOutputUnitMIDICallbacks"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitMIDICallbacks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioOutputUnitMIDICallbacks"
        }
      ],
      "role": "symbol",
      "title": "AudioOutputUnitMIDICallbacks",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiooutputunitmidicallbacks"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitStartAtTimeParams": {
      "abstract": [
        {
          "text": "A timestamp for scheduled starting of an I/O audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioOutputUnitStartAtTimeParams"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitStartAtTimeParams",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioOutputUnitStartAtTimeParams"
        }
      ],
      "role": "symbol",
      "title": "AudioOutputUnitStartAtTimeParams",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiooutputunitstartattimeparams"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties": {
      "abstract": [
        {
          "text": "Obtain information about the built-in mixers, equalizers, filters, effects, and other Audio Unit app extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitProperty_HostReceivesRemoteControlEvents": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioOutputUnitProperty_HostReceivesRemoteControlEvents"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitProperty_HostReceivesRemoteControlEvents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioOutputUnitProperty_HostReceivesRemoteControlEvents"
        }
      ],
      "role": "symbol",
      "title": "kAudioOutputUnitProperty_HostReceivesRemoteControlEvents",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiooutputunitproperty_hostreceivesremotecontrolevents"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitProperty_HostTransportState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioOutputUnitProperty_HostTransportState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitProperty_HostTransportState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioOutputUnitProperty_HostTransportState"
        }
      ],
      "role": "symbol",
      "title": "kAudioOutputUnitProperty_HostTransportState",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiooutputunitproperty_hosttransportstate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitProperty_MIDICallbacks": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioOutputUnitProperty_MIDICallbacks"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitProperty_MIDICallbacks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioOutputUnitProperty_MIDICallbacks"
        }
      ],
      "role": "symbol",
      "title": "kAudioOutputUnitProperty_MIDICallbacks",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiooutputunitproperty_midicallbacks"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitProperty_NodeComponentDescription": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioOutputUnitProperty_NodeComponentDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitProperty_NodeComponentDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioOutputUnitProperty_NodeComponentDescription"
        }
      ],
      "role": "symbol",
      "title": "kAudioOutputUnitProperty_NodeComponentDescription",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiooutputunitproperty_nodecomponentdescription"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitProperty_RemoteControlToHost": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioOutputUnitProperty_RemoteControlToHost"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitProperty_RemoteControlToHost",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioOutputUnitProperty_RemoteControlToHost"
        }
      ],
      "role": "symbol",
      "title": "kAudioOutputUnitProperty_RemoteControlToHost",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiooutputunitproperty_remotecontroltohost"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "InputOutput",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534116-i_o_audio_unit_properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621038-inter-app-audio-unit-property-ids",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389916-output_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534109-aunetreceive-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534207-aunetsend-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389633-aunetsend-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389920-aunetreceive-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534212-aunetsendpresetformat-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389891-net-status-audio-unit-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1585807-i_o_audio_unit_function_selector",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitMIDICallbacks",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitStartAtTimeParams"
      ],
      "title": "Input/Output"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitProperty_MIDICallbacks",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitProperty_HostReceivesRemoteControlEvents",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitProperty_RemoteControlToHost",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitProperty_HostTransportState",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitProperty_NodeComponentDescription"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitProperty_MIDICallbacks",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitProperty_HostReceivesRemoteControlEvents",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitProperty_RemoteControlToHost",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitProperty_HostTransportState",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioOutputUnitProperty_NodeComponentDescription"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "InputOutput",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534116-i_o_audio_unit_properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621038-inter-app-audio-unit-property-ids",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389916-output_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534109-aunetreceive-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534207-aunetsend-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389633-aunetsend-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389920-aunetreceive-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534212-aunetsendpresetformat-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389891-net-status-audio-unit-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1585807-i_o_audio_unit_function_selector",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitMIDICallbacks",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitStartAtTimeParams"
              ],
              "title": "Input/Output"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioOutputUnitProperty_MIDICallbacks/title",
          "value": "kAudioOutputUnitProperty_MIDICallbacks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioOutputUnitProperty_MIDICallbacks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioOutputUnitProperty_MIDICallbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitStartAtTimeParams/title",
          "value": "AudioOutputUnitStartAtTimeParams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitStartAtTimeParams/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioOutputUnitStartAtTimeParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitStartAtTimeParams/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioOutputUnitStartAtTimeParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioOutputUnitProperty_HostReceivesRemoteControlEvents/title",
          "value": "kAudioOutputUnitProperty_HostReceivesRemoteControlEvents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioOutputUnitProperty_HostReceivesRemoteControlEvents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioOutputUnitProperty_HostReceivesRemoteControlEvents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioOutputUnitProperty_RemoteControlToHost/title",
          "value": "kAudioOutputUnitProperty_RemoteControlToHost"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioOutputUnitProperty_RemoteControlToHost/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioOutputUnitProperty_RemoteControlToHost"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioOutputUnitProperty_HostTransportState/title",
          "value": "kAudioOutputUnitProperty_HostTransportState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioOutputUnitProperty_HostTransportState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioOutputUnitProperty_HostTransportState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitMIDICallbacks/title",
          "value": "AudioOutputUnitMIDICallbacks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitMIDICallbacks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioOutputUnitMIDICallbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitMIDICallbacks/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioOutputUnitMIDICallbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioOutputUnitProperty_NodeComponentDescription/title",
          "value": "kAudioOutputUnitProperty_NodeComponentDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioOutputUnitProperty_NodeComponentDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioOutputUnitProperty_NodeComponentDescription"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1621039-inter-app-output-unit-property-ids"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1621039-inter-app-output-unit-property-ids"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
