{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/extended-audio-file-services"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1623673-codec-unavailable-errors"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Codec Unavailable Errors"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1486859-property-identifiers-for-extende": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1486859-property-identifiers-for-extende",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Property Identifiers for Extended Audio File Objects",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1486859-property-identifiers-for-extende"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1486883-extended-audio-file-errors": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1486883-extended-audio-file-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Extended Audio FIle Errors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1486883-extended-audio-file-errors"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3547074-extended-audio-file-packet-overr": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3547074-extended-audio-file-packet-overr",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Extended Audio File Packet Overrides",
      "type": "topic",
      "url": "/documentation/audiotoolbox/3547074-extended-audio-file-packet-overr"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileWrite(_:_:_:)": {
      "abstract": [
        {
          "text": "Performs a synchronous, sequential write operation on an audio file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExtAudioFileWrite"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFileRef",
          "text": "ExtAudioFileRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioBufferList",
          "text": "AudioBufferList"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileWrite(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ExtAudioFileWrite"
        }
      ],
      "role": "symbol",
      "title": "ExtAudioFileWrite(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/extaudiofilewrite(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/extended-audio-file-services": {
      "abstract": [
        {
          "text": "Read and write compressed files and linear PCM audio files using a simplified interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/extended-audio-file-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Extended Audio File Services",
      "type": "topic",
      "url": "/documentation/audiotoolbox/extended-audio-file-services"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_CodecUnavailableInputConsumed": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileWrite(_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function was interrupted and the last buffer that you provided was successfully written to disk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_CodecUnavailableInputConsumed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_CodecUnavailableInputConsumed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_CodecUnavailableInputConsumed"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileError_CodecUnavailableInputConsumed",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileerror_codecunavailableinputconsumed"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_CodecUnavailableInputNotConsumed": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileWrite(_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function was interrupted and the last buffer that you provided was ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "not",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " successfully written to disk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_CodecUnavailableInputNotConsumed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_CodecUnavailableInputNotConsumed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_CodecUnavailableInputNotConsumed"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileError_CodecUnavailableInputNotConsumed",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileerror_codecunavailableinputnotconsumed"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1486883-extended-audio-file-errors",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1486859-property-identifiers-for-extende",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3547074-extended-audio-file-packet-overr"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_CodecUnavailableInputConsumed",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_CodecUnavailableInputNotConsumed"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_CodecUnavailableInputConsumed",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_CodecUnavailableInputNotConsumed"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1486883-extended-audio-file-errors",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1486859-property-identifiers-for-extende",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3547074-extended-audio-file-packet-overr"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtAudioFileWrite(_:_:_:)/title",
          "value": "ExtAudioFileWrite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtAudioFileWrite(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ExtAudioFileWrite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_CodecUnavailableInputNotConsumed/title",
          "value": "kExtAudioFileError_CodecUnavailableInputNotConsumed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_CodecUnavailableInputNotConsumed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileError_CodecUnavailableInputNotConsumed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_CodecUnavailableInputConsumed/title",
          "value": "kExtAudioFileError_CodecUnavailableInputConsumed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_CodecUnavailableInputConsumed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileError_CodecUnavailableInputConsumed"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/1623673-codec-unavailable-errors"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/1623673-codec-unavailable-errors"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
