{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/extended-audio-file-services"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3547074-extended-audio-file-packet-overr"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Extended Audio File Packet Overrides"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1486859-property-identifiers-for-extende": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1486859-property-identifiers-for-extende",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Property Identifiers for Extended Audio File Objects",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1486859-property-identifiers-for-extende"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1486883-extended-audio-file-errors": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1486883-extended-audio-file-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Extended Audio FIle Errors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1486883-extended-audio-file-errors"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1623673-codec-unavailable-errors": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1623673-codec-unavailable-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Codec Unavailable Errors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1623673-codec-unavailable-errors"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/extended-audio-file-services": {
      "abstract": [
        {
          "text": "Read and write compressed files and linear PCM audio files using a simplified interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/extended-audio-file-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Extended Audio File Services",
      "type": "topic",
      "url": "/documentation/audiotoolbox/extended-audio-file-services"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFilePacketTableInfoOverride_UseFileValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFilePacketTableInfoOverride_UseFileValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFilePacketTableInfoOverride",
          "text": "ExtAudioFilePacketTableInfoOverride"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFilePacketTableInfoOverride_UseFileValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFilePacketTableInfoOverride_UseFileValue"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFilePacketTableInfoOverride_UseFileValue",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofilepackettableinfooverride_usefilevalue"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFilePacketTableInfoOverride_UseFileValueIfValid": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFilePacketTableInfoOverride_UseFileValueIfValid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFilePacketTableInfoOverride",
          "text": "ExtAudioFilePacketTableInfoOverride"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFilePacketTableInfoOverride_UseFileValueIfValid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFilePacketTableInfoOverride_UseFileValueIfValid"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFilePacketTableInfoOverride_UseFileValueIfValid",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofilepackettableinfooverride_usefilevalueifvalid"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1486883-extended-audio-file-errors",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1623673-codec-unavailable-errors",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1486859-property-identifiers-for-extende"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFilePacketTableInfoOverride_UseFileValue",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFilePacketTableInfoOverride_UseFileValueIfValid"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFilePacketTableInfoOverride_UseFileValue",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFilePacketTableInfoOverride_UseFileValueIfValid"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1486883-extended-audio-file-errors",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1623673-codec-unavailable-errors",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1486859-property-identifiers-for-extende"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFilePacketTableInfoOverride_UseFileValue/title",
          "value": "kExtAudioFilePacketTableInfoOverride_UseFileValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFilePacketTableInfoOverride_UseFileValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFilePacketTableInfoOverride_UseFileValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFilePacketTableInfoOverride_UseFileValueIfValid/title",
          "value": "kExtAudioFilePacketTableInfoOverride_UseFileValueIfValid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFilePacketTableInfoOverride_UseFileValueIfValid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFilePacketTableInfoOverride_UseFileValueIfValid"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/3547074-extended-audio-file-packet-overr"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/3547074-extended-audio-file-packet-overr"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
