{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/4304947-anonymous"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Anonymous"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534085-apple-voice-processing-audio-uni": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534085-apple-voice-processing-audio-uni",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Apple Voice Processing Audio Unit Errors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534085-apple-voice-processing-audio-uni"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3751765-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3751765-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/3751765-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3950917-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3950917-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/3950917-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/4103713-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/4103713-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/4103713-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/4354006-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/4354006-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/4354006-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerPersonalizedHRTFMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatialMixerPersonalizedHRTFMode"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerPersonalizedHRTFMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatialMixerPersonalizedHRTFMode"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerPersonalizedHRTFMode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixerpersonalizedhrtfmode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioConverterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioConverterOptions"
        }
      ],
      "role": "symbol",
      "title": "AudioConverterOptions",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioconverteroptions"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AudioToolbox Enumerations",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiotoolbox-enumerations"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicRangeCompressionProfile_GeneralCompression": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDynamicRangeCompressionProfile_GeneralCompression"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicRangeCompressionProfile_GeneralCompression",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDynamicRangeCompressionProfile_GeneralCompression"
        }
      ],
      "role": "symbol",
      "title": "kDynamicRangeCompressionProfile_GeneralCompression",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdynamicrangecompressionprofile_generalcompression"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicRangeCompressionProfile_LateNight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDynamicRangeCompressionProfile_LateNight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicRangeCompressionProfile_LateNight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDynamicRangeCompressionProfile_LateNight"
        }
      ],
      "role": "symbol",
      "title": "kDynamicRangeCompressionProfile_LateNight",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdynamicrangecompressionprofile_latenight"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicRangeCompressionProfile_LimitedPlaybackRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDynamicRangeCompressionProfile_LimitedPlaybackRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicRangeCompressionProfile_LimitedPlaybackRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDynamicRangeCompressionProfile_LimitedPlaybackRange"
        }
      ],
      "role": "symbol",
      "title": "kDynamicRangeCompressionProfile_LimitedPlaybackRange",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdynamicrangecompressionprofile_limitedplaybackrange"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicRangeCompressionProfile_NoisyEnvironment": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDynamicRangeCompressionProfile_NoisyEnvironment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicRangeCompressionProfile_NoisyEnvironment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDynamicRangeCompressionProfile_NoisyEnvironment"
        }
      ],
      "role": "symbol",
      "title": "kDynamicRangeCompressionProfile_NoisyEnvironment",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdynamicrangecompressionprofile_noisyenvironment"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicRangeCompressionProfile_None": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDynamicRangeCompressionProfile_None"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicRangeCompressionProfile_None",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDynamicRangeCompressionProfile_None"
        }
      ],
      "role": "symbol",
      "title": "kDynamicRangeCompressionProfile_None",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdynamicrangecompressionprofile_none"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534085-apple-voice-processing-audio-uni",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3751765-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3950917-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/4103713-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/4354006-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerPersonalizedHRTFMode",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterOptions"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicRangeCompressionProfile_GeneralCompression",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicRangeCompressionProfile_LateNight",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicRangeCompressionProfile_LimitedPlaybackRange",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicRangeCompressionProfile_NoisyEnvironment",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicRangeCompressionProfile_None"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicRangeCompressionProfile_GeneralCompression",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicRangeCompressionProfile_LateNight",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicRangeCompressionProfile_LimitedPlaybackRange",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicRangeCompressionProfile_NoisyEnvironment",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicRangeCompressionProfile_None"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534085-apple-voice-processing-audio-uni",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3751765-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3950917-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/4103713-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/4354006-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerPersonalizedHRTFMode",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterOptions"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicRangeCompressionProfile_LimitedPlaybackRange/title",
          "value": "kDynamicRangeCompressionProfile_LimitedPlaybackRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicRangeCompressionProfile_LimitedPlaybackRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDynamicRangeCompressionProfile_LimitedPlaybackRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerPersonalizedHRTFMode/title",
          "value": "AUSpatialMixerPersonalizedHRTFMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerPersonalizedHRTFMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerPersonalizedHRTFMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerPersonalizedHRTFMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerPersonalizedHRTFMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicRangeCompressionProfile_NoisyEnvironment/title",
          "value": "kDynamicRangeCompressionProfile_NoisyEnvironment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicRangeCompressionProfile_NoisyEnvironment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDynamicRangeCompressionProfile_NoisyEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicRangeCompressionProfile_LateNight/title",
          "value": "kDynamicRangeCompressionProfile_LateNight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicRangeCompressionProfile_LateNight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDynamicRangeCompressionProfile_LateNight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterOptions/title",
          "value": "AudioConverterOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioConverterOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioConverterOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicRangeCompressionProfile_GeneralCompression/title",
          "value": "kDynamicRangeCompressionProfile_GeneralCompression"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicRangeCompressionProfile_GeneralCompression/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDynamicRangeCompressionProfile_GeneralCompression"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicRangeCompressionProfile_None/title",
          "value": "kDynamicRangeCompressionProfile_None"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicRangeCompressionProfile_None/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDynamicRangeCompressionProfile_None"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/4304947-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/4304947-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
