{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU_SUPPORT_INTERAPP_AUDIO"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@AU_SUPPORT_INTERAPP_AUDIO",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AU_SUPPORT_INTERAPP_AUDIO"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AU_SUPPORT_INTERAPP_AUDIO"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "AU_SUPPORT_INTERAPP_AUDIO"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AU_SUPPORT_INTERAPP_AUDIO"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533960-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533960-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1533960-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534019-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534019-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534019-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534063-3d_mixer_audio_unit_properties": {
      "abstract": [
        {
          "text": "Properties for the Apple 3D Mixer audio unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534063-3d_mixer_audio_unit_properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "3D Mixer Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534063-3d_mixer_audio_unit_properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534074-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534074-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534074-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534089-music-device-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534089-music-device-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Music Device Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534089-music-device-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534112-audio-unit-attenuation-propertie": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534112-audio-unit-attenuation-propertie",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Attenuation Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534112-audio-unit-attenuation-propertie"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534225-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534225-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534225-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1537630-audio-graph-errors": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1537630-audio-graph-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Graph Errors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1537630-audio-graph-errors"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584141-audio-unit-instrument-errors": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584141-audio-unit-instrument-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Instrument Errors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584141-audio-unit-instrument-errors"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618426-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618426-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1618426-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618742-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618742-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1618742-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619479-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619479-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1619479-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619504-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619504-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1619504-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621044-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621044-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1621044-anonymous"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1624333-audio-converter-property-id": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1624333-audio-converter-property-id",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Converter Property ID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1624333-audio-converter-property-id"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU_SUPPORT_INTERAPP_AUDIO": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AU_SUPPORT_INTERAPP_AUDIO"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU_SUPPORT_INTERAPP_AUDIO",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AU_SUPPORT_INTERAPP_AUDIO"
        }
      ],
      "role": "symbol",
      "title": "AU_SUPPORT_INTERAPP_AUDIO",
      "type": "topic",
      "url": "/documentation/audiotoolbox/au_support_interapp_audio"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534112-audio-unit-attenuation-propertie",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584141-audio-unit-instrument-errors",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534019-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534074-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1537630-audio-graph-errors",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1624333-audio-converter-property-id",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621044-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618426-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618742-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619479-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619504-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533960-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534225-anonymous",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534089-music-device-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534063-3d_mixer_audio_unit_properties"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AU_SUPPORT_INTERAPP_AUDIO"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AU_SUPPORT_INTERAPP_AUDIO"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534112-audio-unit-attenuation-propertie",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584141-audio-unit-instrument-errors",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534019-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534074-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1537630-audio-graph-errors",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1624333-audio-converter-property-id",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621044-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618426-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618742-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619479-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619504-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533960-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534225-anonymous",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534089-music-device-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534063-3d_mixer_audio_unit_properties"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AU_SUPPORT_INTERAPP_AUDIO"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU_SUPPORT_INTERAPP_AUDIO/title",
          "value": "AU_SUPPORT_INTERAPP_AUDIO"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU_SUPPORT_INTERAPP_AUDIO/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AU_SUPPORT_INTERAPP_AUDIO"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/au_support_interapp_audio"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/au_support_interapp_audio"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
