{
  "abstract": [
    {
      "text": "An object that creates a version 3 audio unit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitFactory"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)AUAudioUnitFactory",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AUAudioUnitFactory"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AUAudioUnitFactory"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "AUAudioUnitFactory"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AUAudioUnitFactory"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSExtensionRequestHandling",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSExtensionRequestHandling",
              "text": "NSExtensionRequestHandling"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In most cases, if your audio unit specifies parameters to configure its behavior, it should provide a custom user interface to control those parameters. You create this user interface by subclassing the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreAudioKit/AUViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class and implementing this protocol on your subclass.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If your audio unit doesn’t provide a custom user interface, subclass the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class instead. In this case, the hosting app must create a generic user interface for your audio unit.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit": {
      "abstract": [
        {
          "text": "A class that defines a host’s interface to an audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioUnit"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUAudioUnit"
        }
      ],
      "role": "symbol",
      "title": "AUAudioUnit",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounit"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitBus": {
      "abstract": [
        {
          "text": "A class that defines an input or output connection point on an audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioUnitBus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitBus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUAudioUnitBus"
        }
      ],
      "role": "symbol",
      "title": "AUAudioUnitBus",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounitbus"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitBusArray": {
      "abstract": [
        {
          "text": "A class that defines a container for an audio unit’s input or output busses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioUnitBusArray"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitBusArray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUAudioUnitBusArray"
        }
      ],
      "role": "symbol",
      "title": "AUAudioUnitBusArray",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounitbusarray"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitFactory": {
      "abstract": [
        {
          "text": "An object that creates a version 3 audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioUnitFactory"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitFactory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUAudioUnitFactory"
        }
      ],
      "role": "symbol",
      "title": "AUAudioUnitFactory",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounitfactory"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitFactory/createAudioUnit(with:)": {
      "abstract": [
        {
          "text": "Creates an instance of an extension’s audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "createAudioUnit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioComponentDescription",
          "text": "AudioComponentDescription"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AUAudioUnit",
          "text": "AUAudioUnit"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitFactory/createAudioUnit(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "createAudioUnitWithComponentDescription:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "createAudioUnit(with:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounitfactory/createaudiounit(with:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitPreset": {
      "abstract": [
        {
          "text": "A class that describes an interface for custom parameter settings provided by the audio unit developer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioUnitPreset"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitPreset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUAudioUnitPreset"
        }
      ],
      "role": "symbol",
      "title": "AUAudioUnitPreset",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounitpreset"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitV2Bridge": {
      "abstract": [
        {
          "text": "A class that wraps a version 2 audio unit as version 3 audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioUnitV2Bridge"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitV2Bridge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUAudioUnitV2Bridge"
        }
      ],
      "role": "symbol",
      "title": "AUAudioUnitV2Bridge",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounitv2bridge"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitExtensionCopyComponentList(_:)": {
      "abstract": [
        {
          "text": "Returns the component registrations for a given audio unit extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitExtensionCopyComponentList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitExtensionCopyComponentList(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitExtensionCopyComponentList"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitExtensionCopyComponentList(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitextensioncopycomponentlist(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitExtensionSetComponentList(_:_:)": {
      "abstract": [
        {
          "text": "Allows the implementor of an audio unit extension to dynamically modify the list of component registrations for the extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitExtensionSetComponentList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitExtensionSetComponentList(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitExtensionSetComponentList"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitExtensionSetComponentList(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitextensionsetcomponentlist(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/debugging-out-of-process-audio-units-on-apple-silicon": {
      "abstract": [
        {
          "text": "Connect to out-of-process audio units using the Xcode debugger.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/debugging-out-of-process-audio-units-on-apple-silicon",
      "kind": "article",
      "role": "article",
      "title": "Debugging Out-of-Process Audio Units on Apple Silicon",
      "type": "topic",
      "url": "/documentation/audiotoolbox/debugging-out-of-process-audio-units-on-apple-silicon"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/incorporating-audio-effects-and-instruments": {
      "abstract": [
        {
          "text": "Add custom audio processing and MIDI instruments to your app by hosting Audio Unit (AU) plug-ins.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/incorporating-audio-effects-and-instruments",
      "kind": "article",
      "role": "sampleCode",
      "title": "Incorporating Audio Effects and Instruments",
      "type": "topic",
      "url": "/documentation/audiotoolbox/incorporating-audio-effects-and-instruments"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/creating-an-audio-unit-extension": {
      "abstract": [
        {
          "text": "Build an extension by using an Xcode template.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/creating-an-audio-unit-extension",
      "kind": "article",
      "role": "article",
      "title": "Creating an audio unit extension",
      "type": "topic",
      "url": "/documentation/AVFAudio/creating-an-audio-unit-extension"
    },
    "doc://com.apple.documentation/documentation/CoreAudioKit/AUViewController": {
      "abstract": [
        {
          "text": "The base class to extend when creating a custom user interface for an audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUViewController"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreAudioKit/AUViewController",
      "kind": "symbol",
      "role": "symbol",
      "title": "AUViewController",
      "type": "topic",
      "url": "/documentation/CoreAudioKit/AUViewController"
    },
    "doc://com.apple.documentation/documentation/avfoundation/creating_custom_audio_effects": {
      "abstract": [
        {
          "text": "Add custom audio-effect processing to apps like Logic Pro X and GarageBand by creating Audio Unit (AU) plug-ins.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/avfoundation/creating_custom_audio_effects",
      "kind": "article",
      "role": "sampleCode",
      "title": "Creating Custom Audio Effects",
      "type": "topic",
      "url": "/documentation/avfoundation/creating_custom_audio_effects"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSExtensionRequestHandling": {
      "abstract": [
        {
          "text": "The interface an app extension uses to respond to a request from a host app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSExtensionRequestHandling"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSExtensionRequestHandling",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSExtensionRequestHandling",
      "type": "topic",
      "url": "/documentation/foundation/nsextensionrequesthandling"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSExtensionRequestHandling",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Audio-Units",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/AVFAudio/creating-an-audio-unit-extension",
        "doc://com.apple.documentation/documentation/avfoundation/creating_custom_audio_effects",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/incorporating-audio-effects-and-instruments",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/debugging-out-of-process-audio-units-on-apple-silicon",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitBus",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitBusArray",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitPreset",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitV2Bridge",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitExtensionCopyComponentList(_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitExtensionSetComponentList(_:_:)"
      ],
      "title": "Audio Units"
    }
  ],
  "topicSections": [
    {
      "anchor": "Required-Methods",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitFactory/createAudioUnit(with:)"
      ],
      "title": "Required Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AUAudioUnitFactory"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitFactory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitFactory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Required-Methods",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitFactory/createAudioUnit(with:)"
              ],
              "title": "Required Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSExtensionRequestHandling"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Audio-Units",
              "generated": true,
              "identifiers": [
                "doc://com.apple.documentation/documentation/AVFAudio/creating-an-audio-unit-extension",
                "doc://com.apple.documentation/documentation/avfoundation/creating_custom_audio_effects",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/incorporating-audio-effects-and-instruments",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/debugging-out-of-process-audio-units-on-apple-silicon",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitBus",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitBusArray",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitPreset",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitV2Bridge",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitExtensionCopyComponentList(_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitExtensionSetComponentList(_:_:)"
              ],
              "title": "Audio Units"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AUAudioUnitFactory"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSExtensionRequestHandling",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSExtensionRequestHandling",
                    "text": "NSExtensionRequestHandling"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitFactory~1createAudioUnit(with:)/title",
          "value": "createAudioUnitWithComponentDescription:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitFactory~1createAudioUnit(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "createAudioUnitWithComponentDescription:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitV2Bridge/title",
          "value": "AUAudioUnitV2Bridge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitV2Bridge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitV2Bridge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitV2Bridge/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitV2Bridge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitFactory/title",
          "value": "AUAudioUnitFactory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitFactory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitFactory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitFactory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitFactory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitBusArray/title",
          "value": "AUAudioUnitBusArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitBusArray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitBusArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitBusArray/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitBusArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitPreset/title",
          "value": "AUAudioUnitPreset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitPreset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitPreset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitPreset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitPreset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit/title",
          "value": "AUAudioUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreAudioKit~1AUViewController/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AUViewController"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIViewController",
              "text": "UIViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitExtensionCopyComponentList(_:)/title",
          "value": "AudioUnitExtensionCopyComponentList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitExtensionCopyComponentList(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitExtensionCopyComponentList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitBus/title",
          "value": "AUAudioUnitBus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitBus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitBus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitBus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitBus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitExtensionSetComponentList(_:_:)/title",
          "value": "AudioUnitExtensionSetComponentList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitExtensionSetComponentList(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitExtensionSetComponentList"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/auaudiounitfactory"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/auaudiounitfactory"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
