{
  "abstract": [
    {
      "text": "Defines an audio queue buffer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@AudioQueueBuffer",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AudioQueueBuffer"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AudioQueueBuffer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AudioQueueBuffer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioQueueBuffer"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Each audio queue has an associated set of audio queue buffers.  To allocate a buffer, call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueAllocateBuffer(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function. To dispose of a buffer, call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueFreeBuffer(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If using a VBR compressed audio data format, you may want to instead use the ",
              "type": "text"
            },
            {
              "code": "AudioQueueAllocateBufferWithPacketDescriptions",
              "type": "codeVoice"
            },
            {
              "text": " function. This function allocates a buffer with additional space for packet descriptions. The ",
              "type": "text"
            },
            {
              "code": "mPacketDescriptionCapacity",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "mPacketDescriptions",
              "type": "codeVoice"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "code": "mPacketDescriptionCount",
              "type": "codeVoice"
            },
            {
              "text": " fields may only be used with buffers allocated with ",
              "type": "text"
            },
            {
              "code": "AudioQueueAllocateBufferWithPacketDescriptions",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueAllocateBuffer(_:_:_:)": {
      "abstract": [
        {
          "text": "Asks an audio queue object to allocate an audio queue buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueAllocateBuffer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueueRef",
          "text": "AudioQueueRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueueBufferRef",
          "text": "AudioQueueBufferRef"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueAllocateBuffer(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueAllocateBuffer"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueAllocateBuffer(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueueallocatebuffer(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer": {
      "abstract": [
        {
          "text": "Defines an audio queue buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueBuffer"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueBuffer"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueBuffer",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuebuffer"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer/init(mAudioDataBytesCapacity:mAudioData:mAudioDataByteSize:mUserData:mPacketDescriptionCapacity:mPacketDescriptions:mPacketDescriptionCount:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "mAudioDataBytesCapacity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mAudioData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mAudioDataByteSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mUserData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "mPacketDescriptionCapacity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mPacketDescriptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioStreamPacketDescription",
          "text": "AudioStreamPacketDescription"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "mPacketDescriptionCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer/init(mAudioDataBytesCapacity:mAudioData:mAudioDataByteSize:mUserData:mPacketDescriptionCapacity:mPacketDescriptions:mPacketDescriptionCount:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(mAudioDataBytesCapacity:mAudioData:mAudioDataByteSize:mUserData:mPacketDescriptionCapacity:mPacketDescriptions:mPacketDescriptionCount:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuebuffer/init(maudiodatabytescapacity:maudiodata:maudiodatabytesize:muserdata:mpacketdescriptioncapacity:mpacketdescriptions:mpacketdescriptioncount:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer/mAudioData": {
      "abstract": [
        {
          "text": "The audio data owned the audio queue buffer. The buffer address cannot be changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mAudioData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer/mAudioData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mAudioData"
        }
      ],
      "role": "symbol",
      "title": "mAudioData",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuebuffer/maudiodata"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer/mAudioDataByteSize": {
      "abstract": [
        {
          "text": "The number of bytes of valid audio data in the audio queue buffer’s ",
          "type": "text"
        },
        {
          "code": "mAudioData",
          "type": "codeVoice"
        },
        {
          "text": " field, initially set to ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": ". Your callback must set this value for a playback audio queue; for recording, the recording audio queue sets the value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mAudioDataByteSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer/mAudioDataByteSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mAudioDataByteSize"
        }
      ],
      "role": "symbol",
      "title": "mAudioDataByteSize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuebuffer/maudiodatabytesize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer/mAudioDataBytesCapacity": {
      "abstract": [
        {
          "text": "The size of the audio queue buffer, in bytes. This size is set when a buffer is allocated and cannot be changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mAudioDataBytesCapacity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer/mAudioDataBytesCapacity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mAudioDataBytesCapacity"
        }
      ],
      "role": "symbol",
      "title": "mAudioDataBytesCapacity",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuebuffer/maudiodatabytescapacity"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer/mPacketDescriptionCapacity": {
      "abstract": [
        {
          "text": "The maximum number of packet descriptions that can be stored in the ",
          "type": "text"
        },
        {
          "code": "mPacketDescriptions",
          "type": "codeVoice"
        },
        {
          "text": " field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mPacketDescriptionCapacity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer/mPacketDescriptionCapacity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mPacketDescriptionCapacity"
        }
      ],
      "role": "symbol",
      "title": "mPacketDescriptionCapacity",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuebuffer/mpacketdescriptioncapacity"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer/mPacketDescriptionCount": {
      "abstract": [
        {
          "text": "The number of valid packet descriptions in the buffer. You set this value when providing buffers for playback. The audio queue sets this value when returning buffers from a recording queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mPacketDescriptionCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer/mPacketDescriptionCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mPacketDescriptionCount"
        }
      ],
      "role": "symbol",
      "title": "mPacketDescriptionCount",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuebuffer/mpacketdescriptioncount"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer/mPacketDescriptions": {
      "abstract": [
        {
          "text": "An array of ",
          "type": "text"
        },
        {
          "code": "AudioStreamPacketDescription",
          "type": "codeVoice"
        },
        {
          "text": " structures for the buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mPacketDescriptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioStreamPacketDescription",
          "text": "AudioStreamPacketDescription"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer/mPacketDescriptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mPacketDescriptions"
        }
      ],
      "role": "symbol",
      "title": "mPacketDescriptions",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuebuffer/mpacketdescriptions"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer/mUserData": {
      "abstract": [
        {
          "text": "The custom data structure you specify, for use by your callback function, when creating a recording or playback audio queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mUserData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer/mUserData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mUserData"
        }
      ],
      "role": "symbol",
      "title": "mUserData",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuebuffer/muserdata"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBufferRef": {
      "abstract": [
        {
          "text": "A pointer to an audio queue buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueBufferRef"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBufferRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueBufferRef"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueBufferRef",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuebufferref"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueChannelAssignment": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueChannelAssignment"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueChannelAssignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueChannelAssignment"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueChannelAssignment",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuechannelassignment"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueFreeBuffer(_:_:)": {
      "abstract": [
        {
          "text": "Asks an audio queue to dispose of an audio queue buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueFreeBuffer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueueRef",
          "text": "AudioQueueRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueueBufferRef",
          "text": "AudioQueueBufferRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueFreeBuffer(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueFreeBuffer"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueFreeBuffer(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuefreebuffer(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueLevelMeterState": {
      "abstract": [
        {
          "text": "Specifies the current level metering information for one channel of an audio queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueLevelMeterState"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueLevelMeterState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueLevelMeterState"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueLevelMeterState",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuelevelmeterstate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueParameterEvent": {
      "abstract": [
        {
          "text": "Specifies an audio queue parameter and associated value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueParameterEvent"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueParameterEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueParameterEvent"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueParameterEvent",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueueparameterevent"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueParameterID": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value that uniquely identifies an audio queue parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueParameterID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueParameterID"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueParameterID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueueparameterid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueParameterValue": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "Float32",
          "type": "codeVoice"
        },
        {
          "text": " value for an audio queue parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueParameterValue"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueParameterValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueParameterValue"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueParameterValue",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueueparametervalue"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapCallback": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueProcessingTapCallback"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueProcessingTapCallback"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueProcessingTapCallback",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueueprocessingtapcallback"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueProcessingTapFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueProcessingTapFlags"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueProcessingTapFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueueprocessingtapflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapRef": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueProcessingTapRef"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueProcessingTapRef"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueProcessingTapRef",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueueprocessingtapref"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueChannelAssignment",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBufferRef",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueLevelMeterState",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueParameterEvent",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueParameterID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueParameterValue",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapCallback",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapRef"
      ],
      "title": "Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer/init(mAudioDataBytesCapacity:mAudioData:mAudioDataByteSize:mUserData:mPacketDescriptionCapacity:mPacketDescriptions:mPacketDescriptionCount:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer/mAudioData",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer/mAudioDataByteSize",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer/mAudioDataBytesCapacity",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer/mPacketDescriptionCapacity",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer/mPacketDescriptionCount",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer/mPacketDescriptions",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer/mUserData"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AudioQueueBuffer"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer/mAudioData",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer/mAudioDataByteSize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer/mAudioDataBytesCapacity",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer/mPacketDescriptionCapacity",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer/mPacketDescriptionCount",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer/mPacketDescriptions",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer/mUserData"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueChannelAssignment",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapFlags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBufferRef",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueLevelMeterState",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueParameterEvent",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueParameterID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueParameterValue",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapCallback",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapRef"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AudioQueueBuffer"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "AudioQueueBuffer"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueProcessingTapFlags/title",
          "value": "AudioQueueProcessingTapFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueProcessingTapFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueProcessingTapFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueProcessingTapFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueProcessingTapFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueAllocateBuffer(_:_:_:)/title",
          "value": "AudioQueueAllocateBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueAllocateBuffer(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueAllocateBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueBuffer~1mPacketDescriptionCapacity/title",
          "value": "mPacketDescriptionCapacity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueBuffer~1mPacketDescriptionCapacity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mPacketDescriptionCapacity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueBuffer~1mAudioDataBytesCapacity/title",
          "value": "mAudioDataBytesCapacity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueBuffer~1mAudioDataBytesCapacity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mAudioDataBytesCapacity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueProcessingTapCallback/title",
          "value": "AudioQueueProcessingTapCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueProcessingTapCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueProcessingTapCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueProcessingTapCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueProcessingTapCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueBuffer/title",
          "value": "AudioQueueBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueFreeBuffer(_:_:)/title",
          "value": "AudioQueueFreeBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueFreeBuffer(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueFreeBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueBuffer~1mPacketDescriptions/title",
          "value": "mPacketDescriptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueBuffer~1mPacketDescriptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mPacketDescriptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueBuffer~1mPacketDescriptionCount/title",
          "value": "mPacketDescriptionCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueBuffer~1mPacketDescriptionCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mPacketDescriptionCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueParameterID/title",
          "value": "AudioQueueParameterID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueParameterID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueParameterID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueBuffer~1mAudioData/title",
          "value": "mAudioData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueBuffer~1mAudioData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mAudioData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueChannelAssignment/title",
          "value": "AudioQueueChannelAssignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueChannelAssignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueChannelAssignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueChannelAssignment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueChannelAssignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueBuffer~1mUserData/title",
          "value": "mUserData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueBuffer~1mUserData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mUserData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueLevelMeterState/title",
          "value": "AudioQueueLevelMeterState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueLevelMeterState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueLevelMeterState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueLevelMeterState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueLevelMeterState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueProcessingTapRef/title",
          "value": "AudioQueueProcessingTapRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueProcessingTapRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueProcessingTapRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueProcessingTapRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueProcessingTapRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueParameterEvent/title",
          "value": "AudioQueueParameterEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueParameterEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueParameterEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueParameterEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueParameterEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueParameterValue/title",
          "value": "AudioQueueParameterValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueParameterValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueParameterValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueParameterValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueParameterValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueBuffer~1mAudioDataByteSize/title",
          "value": "mAudioDataByteSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueBuffer~1mAudioDataByteSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mAudioDataByteSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueBufferRef/title",
          "value": "AudioQueueBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueBufferRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueBufferRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueBufferRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/audioqueuebuffer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/audioqueuebuffer"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
