{
  "abstract": [
    {
      "text": "Access information about audio formats and codecs.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-format-services"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio Format Services"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This document describes Audio Format Services, a C interface for obtaining information about audio formats and codecs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494086-audio-codec-component-constants": {
      "abstract": [
        {
          "text": "Audio codec component types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494086-audio-codec-component-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Codec Component Constants",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1494086-audio-codec-component-constants"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1577851-audio-format-error-codes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1577851-audio-format-error-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Format Error Codes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1577851-audio-format-error-codes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1577853-audio-format-property-identifier": {
      "abstract": [
        {
          "text": "Constants for use with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatGetPropertyInfo(_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatGetProperty(_:_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1577853-audio-format-property-identifier",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Format Property Identifiers",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1577853-audio-format-property-identifier"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1620448-audio-codec-manufacturer-and-imp": {
      "abstract": [
        {
          "text": "Identifiers for audio codec manufacturers and implementation types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1620448-audio-codec-manufacturer-and-imp",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Codec Manufacturer and Implementation Types",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1620448-audio-codec-manufacturer-and-imp"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBalanceFade": {
      "abstract": [
        {
          "text": "Describes audio left/right balance and front/back fade values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioBalanceFade"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBalanceFade",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioBalanceFade"
        }
      ],
      "role": "symbol",
      "title": "AudioBalanceFade",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiobalancefade"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBalanceFadeType": {
      "abstract": [
        {
          "text": "Identifiers for audio balance fade types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioBalanceFadeType"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBalanceFadeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioBalanceFadeType"
        }
      ],
      "role": "symbol",
      "title": "AudioBalanceFadeType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiobalancefadetype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatGetProperty(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Gets the value of an audio format property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFormatGetProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatPropertyID",
          "text": "AudioFormatPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatGetProperty(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFormatGetProperty"
        }
      ],
      "role": "symbol",
      "title": "AudioFormatGetProperty(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioformatgetproperty(_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatGetPropertyInfo(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Gets information about an audio format property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFormatGetPropertyInfo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatPropertyID",
          "text": "AudioFormatPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatGetPropertyInfo(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFormatGetPropertyInfo"
        }
      ],
      "role": "symbol",
      "title": "AudioFormatGetPropertyInfo(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioformatgetpropertyinfo(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatInfo": {
      "abstract": [
        {
          "text": "A structure that specifies an audio format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFormatInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFormatInfo"
        }
      ],
      "role": "symbol",
      "title": "AudioFormatInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioformatinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatPropertyID": {
      "abstract": [
        {
          "text": "A type for four-char codes for audio format property identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFormatPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatPropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFormatPropertyID"
        }
      ],
      "role": "symbol",
      "title": "AudioFormatPropertyID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioformatpropertyid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo": {
      "abstract": [
        {
          "text": "Audio panning information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioPanningInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioPanningInfo"
        }
      ],
      "role": "symbol",
      "title": "AudioPanningInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiopanninginfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningMode": {
      "abstract": [
        {
          "text": "Identifiers for audio panning algorithms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioPanningMode"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioPanningMode"
        }
      ],
      "role": "symbol",
      "title": "AudioPanningMode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiopanningmode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo": {
      "abstract": [
        {
          "text": "A specifier for the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FormatList",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property, including the codec to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExtendedAudioFormatInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ExtendedAudioFormatInfo"
        }
      ],
      "role": "symbol",
      "title": "ExtendedAudioFormatInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/extendedaudioformatinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-components": {
      "abstract": [
        {
          "text": "Get information about audio file formats, and about files containing audio data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-components",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio File Components",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-file-components"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-services": {
      "abstract": [
        {
          "text": "Read or write a variety of audio data to or from disk or a memory buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio File Services",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-file-services"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-stream-services": {
      "abstract": [
        {
          "text": "Parse streamed audio files as the data arrives on the user’s computer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-stream-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio File Stream Services",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-file-stream-services"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/core-audio-file-format": {
      "abstract": [
        {
          "text": "Parse the structure of Core Audio files.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/core-audio-file-format",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Audio File Format",
      "type": "topic",
      "url": "/documentation/audiotoolbox/core-audio-file-format"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/extended-audio-file-services": {
      "abstract": [
        {
          "text": "Read and write compressed files and linear PCM audio files using a simplified interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/extended-audio-file-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Extended Audio File Services",
      "type": "topic",
      "url": "/documentation/audiotoolbox/extended-audio-file-services"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatBadPropertySizeError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatBadPropertySizeError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatBadPropertySizeError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatBadPropertySizeError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatBadPropertySizeError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioformatbadpropertysizeerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatBadSpecifierSizeError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatBadSpecifierSizeError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatBadSpecifierSizeError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatBadSpecifierSizeError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatBadSpecifierSizeError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioformatbadspecifiersizeerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FormatList": {
      "abstract": [
        {
          "text": "A list of structures describing the audio formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_FormatList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatPropertyID",
          "text": "AudioFormatPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FormatList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_FormatList"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatProperty_FormatList",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioformatproperty_formatlist"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatUnknownFormatError": {
      "abstract": [
        {
          "text": "The specified data format is not a known format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatUnknownFormatError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatUnknownFormatError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatUnknownFormatError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatUnknownFormatError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioformatunknownformaterror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatUnspecifiedError": {
      "abstract": [
        {
          "text": "An unspecified error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatUnspecifiedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatUnspecifiedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatUnspecifiedError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatUnspecifiedError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioformatunspecifiederror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatUnsupportedDataFormatError": {
      "abstract": [
        {
          "text": "The playback data format is unsupported (declared in ",
          "type": "text"
        },
        {
          "code": "AudioFormat.h",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatUnsupportedDataFormatError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatUnsupportedDataFormatError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatUnsupportedDataFormatError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatUnsupportedDataFormatError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioformatunsupporteddataformaterror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatUnsupportedPropertyError": {
      "abstract": [
        {
          "text": "The specified property is not supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatUnsupportedPropertyError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatUnsupportedPropertyError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatUnsupportedPropertyError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatUnsupportedPropertyError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioformatunsupportedpropertyerror"
    },
    "doc://com.apple.documentation/documentation/CoreAudioTypes/AudioFormatListItem": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFormatListItem"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreAudioTypes/AudioFormatListItem",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioFormatListItem",
      "type": "topic",
      "url": "/documentation/CoreAudioTypes/AudioFormatListItem"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Audio-Files-and-Formats",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-services",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/extended-audio-file-services",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-stream-services",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-components",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/core-audio-file-format"
      ],
      "title": "Audio Files and Formats"
    }
  ],
  "topicSections": [
    {
      "anchor": "Audio-Format-Services-Functions",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatGetProperty(_:_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatGetPropertyInfo(_:_:_:_:)"
      ],
      "title": "Audio Format Services Functions"
    },
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBalanceFade",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatInfo",
        "doc://com.apple.documentation/documentation/CoreAudioTypes/AudioFormatListItem",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatPropertyID"
      ],
      "title": "Data Types"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBalanceFadeType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1577853-audio-format-property-identifier",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494086-audio-codec-component-constants",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1620448-audio-codec-manufacturer-and-imp",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningMode"
      ],
      "title": "Constants"
    },
    {
      "abstract": [
        {
          "text": "This table lists the result codes defined for Audio Format Services.",
          "type": "text"
        }
      ],
      "anchor": "Result-Codes",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1577851-audio-format-error-codes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatUnspecifiedError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatUnsupportedPropertyError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatBadPropertySizeError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatBadSpecifierSizeError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatUnsupportedDataFormatError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatUnknownFormatError"
      ],
      "title": "Result Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Audio-Format-Services-Functions",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatGetProperty(_:_:_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatGetPropertyInfo(_:_:_:_:)"
              ],
              "title": "Audio Format Services Functions"
            },
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBalanceFade",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatInfo",
                "doc://com.apple.documentation/documentation/CoreAudioTypes/AudioFormatListItem",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatPropertyID"
              ],
              "title": "Data Types"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBalanceFadeType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1577853-audio-format-property-identifier",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1494086-audio-codec-component-constants",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1620448-audio-codec-manufacturer-and-imp",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningMode"
              ],
              "title": "Constants"
            },
            {
              "abstract": [
                {
                  "text": "This table lists the result codes defined for Audio Format Services.",
                  "type": "text"
                }
              ],
              "anchor": "Result-Codes",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1577851-audio-format-error-codes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatUnspecifiedError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatUnsupportedPropertyError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatBadPropertySizeError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatBadSpecifierSizeError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatUnsupportedDataFormatError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatUnknownFormatError"
              ],
              "title": "Result Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Audio-Files-and-Formats",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-services",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/extended-audio-file-services",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-stream-services",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-components",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/core-audio-file-format"
              ],
              "title": "Audio Files and Formats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatGetPropertyInfo(_:_:_:_:)/title",
          "value": "AudioFormatGetPropertyInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatGetPropertyInfo(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatGetPropertyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatBadSpecifierSizeError/title",
          "value": "kAudioFormatBadSpecifierSizeError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatBadSpecifierSizeError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatBadSpecifierSizeError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatUnspecifiedError/title",
          "value": "kAudioFormatUnspecifiedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatUnspecifiedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatUnspecifiedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatUnknownFormatError/title",
          "value": "kAudioFormatUnknownFormatError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatUnknownFormatError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatUnknownFormatError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtendedAudioFormatInfo/title",
          "value": "ExtendedAudioFormatInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtendedAudioFormatInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ExtendedAudioFormatInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtendedAudioFormatInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ExtendedAudioFormatInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_FormatList/title",
          "value": "kAudioFormatProperty_FormatList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_FormatList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatProperty_FormatList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningInfo/title",
          "value": "AudioPanningInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioPanningInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioPanningInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatPropertyID/title",
          "value": "AudioFormatPropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatPropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatPropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatBadPropertySizeError/title",
          "value": "kAudioFormatBadPropertySizeError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatBadPropertySizeError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatBadPropertySizeError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatInfo/title",
          "value": "AudioFormatInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatUnsupportedPropertyError/title",
          "value": "kAudioFormatUnsupportedPropertyError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatUnsupportedPropertyError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatUnsupportedPropertyError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioBalanceFadeType/title",
          "value": "AudioBalanceFadeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioBalanceFadeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioBalanceFadeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioBalanceFadeType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioBalanceFadeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatUnsupportedDataFormatError/title",
          "value": "kAudioFormatUnsupportedDataFormatError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatUnsupportedDataFormatError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatUnsupportedDataFormatError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioBalanceFade/title",
          "value": "AudioBalanceFade"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioBalanceFade/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioBalanceFade"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioBalanceFade/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioBalanceFade"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatGetProperty(_:_:_:_:_:)/title",
          "value": "AudioFormatGetProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatGetProperty(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatGetProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreAudioTypes~1AudioFormatListItem/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioFormatListItem"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningMode/title",
          "value": "AudioPanningMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioPanningMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioPanningMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/audio-format-services"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/audio-format-services"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
