{
  "abstract": [
    {
      "text": "Strings that identify the various audio input sources for a device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-session-support"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-input-routes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio Input Routes"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These strings are used as values for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSession_AudioRouteKey_Type",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key for the dictionary associated with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSession_AudioRouteKey_Inputs",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " array.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618380-audio-route-change-reasons": {
      "abstract": [
        {
          "text": "Identifiers for the various reasons that an audio route can change while your app is running.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618380-audio-route-change-reasons",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Route Change Reasons",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1618380-audio-route-change-reasons"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/alternative-audio-route-change-reason-dictionary-key": {
      "abstract": [
        {
          "text": "An alternate key for obtaining information about the reason for an audio route change.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/alternative-audio-route-change-reason-dictionary-key",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Alternative Audio Route Change Reason Dictionary Key",
      "type": "topic",
      "url": "/documentation/audiotoolbox/alternative-audio-route-change-reason-dictionary-key"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-output-routes": {
      "abstract": [
        {
          "text": "The various audio output destinations available for an iOS device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-output-routes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Output Routes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-output-routes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-route-change-dictionary-keys": {
      "abstract": [
        {
          "text": "Keys for obtaining information about an audio hardware route change.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-route-change-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Route Change Dictionary Keys",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-route-change-dictionary-keys"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-route-description-dictionary-keys": {
      "abstract": [
        {
          "text": "Keys for the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioRouteDescription",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-route-description-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Route Description Dictionary Keys",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-route-description-dictionary-keys"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-route-type-key": {
      "abstract": [
        {
          "text": "The one key for an audio route input or output dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-route-type-key",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Route Type Key",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-route-type-key"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-session-support": {
      "abstract": [
        {
          "text": "Describe the properties that you associate with audio sessions and audio routes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-session-support",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Session Support",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-session-support"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_BluetoothHFP": {
      "abstract": [
        {
          "text": "A microphone that is part of a Bluetooth Hands-Free Profile (HFP) device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionInputRoute_BluetoothHFP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_BluetoothHFP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionInputRoute_BluetoothHFP"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionInputRoute_BluetoothHFP",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessioninputroute_bluetoothhfp"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_BuiltInMic": {
      "abstract": [
        {
          "text": "A built-in microphone input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionInputRoute_BuiltInMic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_BuiltInMic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionInputRoute_BuiltInMic"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionInputRoute_BuiltInMic",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessioninputroute_builtinmic"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_HeadsetMic": {
      "abstract": [
        {
          "text": "A microphone that is part of a headset.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionInputRoute_HeadsetMic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_HeadsetMic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionInputRoute_HeadsetMic"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionInputRoute_HeadsetMic",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessioninputroute_headsetmic"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_LineIn": {
      "abstract": [
        {
          "text": "A line in input",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionInputRoute_LineIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_LineIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionInputRoute_LineIn"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionInputRoute_LineIn",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessioninputroute_linein"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_USBAudio": {
      "abstract": [
        {
          "text": "A Universal Serial Bus (USB) input, accessed through the device 30-pin connector.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionInputRoute_USBAudio"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_USBAudio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionInputRoute_USBAudio"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionInputRoute_USBAudio",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessioninputroute_usbaudio"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioRouteDescription": {
      "abstract": [
        {
          "text": "Information about an audio route.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_AudioRouteDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioRouteDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_AudioRouteDescription"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_AudioRouteDescription",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_audioroutedescription"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSession_AudioRouteKey_Inputs": {
      "abstract": [
        {
          "text": "An object containing details about audio input used in the current audio route.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSession_AudioRouteKey_Inputs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSession_AudioRouteKey_Inputs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSession_AudioRouteKey_Inputs"
        }
      ],
      "role": "symbol",
      "title": "kAudioSession_AudioRouteKey_Inputs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosession_audioroutekey_inputs"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSession_AudioRouteKey_Type": {
      "abstract": [
        {
          "text": "Audio routes input or output dictionary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSession_AudioRouteKey_Type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSession_AudioRouteKey_Type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSession_AudioRouteKey_Type"
        }
      ],
      "role": "symbol",
      "title": "kAudioSession_AudioRouteKey_Type",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosession_audioroutekey_type"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Audio-Routes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618380-audio-route-change-reasons",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-route-description-dictionary-keys",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-route-type-key",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-output-routes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-route-change-dictionary-keys",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/alternative-audio-route-change-reason-dictionary-key"
      ],
      "title": "Audio Routes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_LineIn",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_BuiltInMic",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_HeadsetMic",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_BluetoothHFP",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_USBAudio"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_LineIn",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_BuiltInMic",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_HeadsetMic",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_BluetoothHFP",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_USBAudio"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Audio-Routes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618380-audio-route-change-reasons",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-route-description-dictionary-keys",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-route-type-key",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-output-routes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-route-change-dictionary-keys",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/alternative-audio-route-change-reason-dictionary-key"
              ],
              "title": "Audio Routes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_AudioRouteDescription/title",
          "value": "kAudioSessionProperty_AudioRouteDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_AudioRouteDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_AudioRouteDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionInputRoute_LineIn/title",
          "value": "kAudioSessionInputRoute_LineIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionInputRoute_LineIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionInputRoute_LineIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionInputRoute_HeadsetMic/title",
          "value": "kAudioSessionInputRoute_HeadsetMic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionInputRoute_HeadsetMic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionInputRoute_HeadsetMic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSession_AudioRouteKey_Inputs/title",
          "value": "kAudioSession_AudioRouteKey_Inputs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSession_AudioRouteKey_Inputs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSession_AudioRouteKey_Inputs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionInputRoute_USBAudio/title",
          "value": "kAudioSessionInputRoute_USBAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionInputRoute_USBAudio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionInputRoute_USBAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionInputRoute_BuiltInMic/title",
          "value": "kAudioSessionInputRoute_BuiltInMic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionInputRoute_BuiltInMic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionInputRoute_BuiltInMic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSession_AudioRouteKey_Type/title",
          "value": "kAudioSession_AudioRouteKey_Type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSession_AudioRouteKey_Type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSession_AudioRouteKey_Type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionInputRoute_BluetoothHFP/title",
          "value": "kAudioSessionInputRoute_BluetoothHFP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionInputRoute_BluetoothHFP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionInputRoute_BluetoothHFP"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/audio-input-routes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/audio-input-routes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
