{
  "abstract": [
    {
      "text": "The unit-of-measure for an audio unit parameter.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AudioUnitParameterUnit",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AudioUnitParameterUnit"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AudioUnitParameterUnit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "AudioUnitParameterUnit"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioUnitParameterUnit"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The various units of measure for audio unit parameters are described in ",
              "type": "text"
            },
            {
              "code": "Audio Unit Parameter Units of Measure",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389613-midi_audio_unit_parameters": {
      "abstract": [
        {
          "text": "Parameters for instrument units.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389613-midi_audio_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Audio Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389613-midi_audio_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi": {
      "abstract": [
        {
          "text": "Reserved for system use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Reserved Audio Unit Clump Identifier",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1533986-reserved_audio_unit_clump_identi"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534054-offline_audio_unit_properties": {
      "abstract": [
        {
          "text": "Properties for audio units that perform offline processing—that is, processing in a nonplayback, nonrealtime mode.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534054-offline_audio_unit_properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Offline Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534054-offline_audio_unit_properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes": {
      "abstract": [
        {
          "text": "Input/output audio unit subtypes for audio units provided by Apple.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Input/Output Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584139-input_output_audio_unit_subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele": {
      "abstract": [
        {
          "text": "General audio unit component selectors that correspond to functions in the audio unit API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele",
      "kind": "article",
      "role": "collectionGroup",
      "title": "General Audio Unit Function Selectors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584140-general_audio_unit_function_sele"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584142-audio_unit_types": {
      "abstract": [
        {
          "text": "The defined types of audio processing plug-ins known as audio units.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584142-audio_unit_types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Types",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584142-audio_unit_types"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi": {
      "abstract": [
        {
          "text": "The Apple audio unit manufacturer code.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Manufacturer Identifier",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584143-audio_unit_manufacturer_identifi"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes": {
      "abstract": [
        {
          "text": "Audio data format converter audio unit subtypes for audio units provided by Apple.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Converter Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584145-converter_audio_unit_subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584148-audio-unit-output-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584148-audio-unit-output-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Output Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584148-audio-unit-output-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Panner Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584151-audio-unit-panner-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Pitch Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584152-audio-unit-pitch-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Player Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584155-audio-unit-player-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "I/O Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1619485-i-o-audio-unit-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes": {
      "abstract": [
        {
          "text": "Audio units that serve as sound sources.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Generator Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1619493-generator_audio_unit_subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Inter-App Audio Unit Types",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1619501-inter-app-audio-unit-types"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit": {
      "abstract": [
        {
          "text": "The unit-of-measure for an audio unit parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterUnit"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterUnit"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/BPM": {
      "abstract": [
        {
          "text": "A whole-number unit of measure for musical tempo, representing beats per minute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BPM"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/BPM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_BPM"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.BPM",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/bpm"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/absoluteCents": {
      "abstract": [
        {
          "text": "An absolute unit of measure for the musical pitch of a note.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "absoluteCents"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/absoluteCents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_AbsoluteCents"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.absoluteCents",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/absolutecents"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/beats": {
      "abstract": [
        {
          "text": "A time unit of measure in musical beats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beats"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/beats",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_Beats"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.beats",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/beats"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/boolean": {
      "abstract": [
        {
          "text": "A Boolean-like unit of measure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "boolean"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/boolean",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_Boolean"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.boolean",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/boolean"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/cents": {
      "abstract": [
        {
          "text": "A logarithmic unit of measure for a musical interval between two notes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cents"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/cents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_Cents"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.cents",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/cents"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/customUnit": {
      "abstract": [
        {
          "text": "A custom unit of measure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customUnit"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/customUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_CustomUnit"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.customUnit",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/customunit"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/decibels": {
      "abstract": [
        {
          "text": "A logarithmic unit of measure representing the ratio between two audio levels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decibels"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/decibels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_Decibels"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.decibels",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/decibels"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/degrees": {
      "abstract": [
        {
          "text": "An angular degree unit of measure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "degrees"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/degrees",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_Degrees"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.degrees",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/degrees"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/equalPowerCrossfade": {
      "abstract": [
        {
          "text": "An audio power unit of measure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "equalPowerCrossfade"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/equalPowerCrossfade",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_EqualPowerCrossfade"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.equalPowerCrossfade",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/equalpowercrossfade"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/generic": {
      "abstract": [
        {
          "text": "A generic unit of measure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "generic"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/generic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_Generic"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.generic",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/generic"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/hertz": {
      "abstract": [
        {
          "text": "A hertz unit of measure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hertz"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/hertz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_Hertz"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.hertz",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/hertz"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/indexed": {
      "abstract": [
        {
          "text": "An indexed unit of measure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indexed"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/indexed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_Indexed"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.indexed",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/indexed"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/init(rawvalue:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/linearGain": {
      "abstract": [
        {
          "text": "A linear unit of measure representing the difference between two audio levels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linearGain"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/linearGain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_LinearGain"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.linearGain",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/lineargain"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/meters": {
      "abstract": [
        {
          "text": "A distance unit of measure, corresponding to meters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "meters"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/meters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_Meters"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.meters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/meters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/midi2Controller": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "midi2Controller"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/midi2Controller",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_MIDI2Controller"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.midi2Controller",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/midi2controller"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/midiController": {
      "abstract": [
        {
          "text": "A whole-number unit of measure corresponding to standard MIDI control numbers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "midiController"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/midiController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_MIDIController"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.midiController",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/midicontroller"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/midiNoteNumber": {
      "abstract": [
        {
          "text": "A whole-number unit of measure corresponding to audio frequency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "midiNoteNumber"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/midiNoteNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_MIDINoteNumber"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.midiNoteNumber",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/midinotenumber"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/milliseconds": {
      "abstract": [
        {
          "text": "A time unit of measure representing milliseconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "milliseconds"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/milliseconds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_Milliseconds"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.milliseconds",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/milliseconds"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/mixerFaderCurve1": {
      "abstract": [
        {
          "text": "An audio power unit of measure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mixerFaderCurve1"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/mixerFaderCurve1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_MixerFaderCurve1"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.mixerFaderCurve1",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/mixerfadercurve1"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/octaves": {
      "abstract": [
        {
          "text": "A relative unit of measure for the musical interval between two notes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "octaves"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/octaves",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_Octaves"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.octaves",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/octaves"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/pan": {
      "abstract": [
        {
          "text": "An audio position unit of measure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pan"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/pan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_Pan"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.pan",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/pan"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/percent": {
      "abstract": [
        {
          "text": "A percentage unit of measure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "percent"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/percent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_Percent"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.percent",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/percent"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/phase": {
      "abstract": [
        {
          "text": "An angular degree unit of measure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "phase"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/phase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_Phase"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.phase",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/phase"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/rate": {
      "abstract": [
        {
          "text": "A multiplication factor unit of measure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rate"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/rate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_Rate"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.rate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/rate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/ratio": {
      "abstract": [
        {
          "text": "A unitless ratio unit of measure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ratio"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/ratio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_Ratio"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.ratio",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/ratio"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/relativeSemiTones": {
      "abstract": [
        {
          "text": "A relative unit of measure for a musical interval between two notes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "relativeSemiTones"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/relativeSemiTones",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_RelativeSemiTones"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.relativeSemiTones",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/relativesemitones"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/sampleFrames": {
      "abstract": [
        {
          "text": "A sample-frame-count unit of measure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sampleFrames"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/sampleFrames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_SampleFrames"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.sampleFrames",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/sampleframes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/seconds": {
      "abstract": [
        {
          "text": "A whole-seconds unit of measure, indicating either absolute or relative time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "seconds"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/seconds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_Seconds"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.seconds",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/seconds"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584142-audio_unit_types",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584148-audio-unit-output-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534054-offline_audio_unit_properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389613-midi_audio_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/absoluteCents",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/BPM",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/beats",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/boolean",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/cents",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/customUnit",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/decibels",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/degrees",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/equalPowerCrossfade",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/generic",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/hertz",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/indexed",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/linearGain",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/midiController",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/midiNoteNumber",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/meters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/milliseconds",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/mixerFaderCurve1",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/octaves",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/pan",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/percent",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/phase",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/rate",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/ratio",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/relativeSemiTones",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/sampleFrames",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/seconds",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/midi2Controller"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AudioUnitParameterUnit"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/absoluteCents",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/BPM",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/beats",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/boolean",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/cents",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/customUnit",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/decibels",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/degrees",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/equalPowerCrossfade",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/generic",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/hertz",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/indexed",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/linearGain",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/midiController",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/midiNoteNumber",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/meters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/milliseconds",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/mixerFaderCurve1",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/octaves",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/pan",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/percent",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/phase",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/rate",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/ratio",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/relativeSemiTones",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/sampleFrames",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/seconds",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/midi2Controller"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584142-audio_unit_types",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584148-audio-unit-output-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534054-offline_audio_unit_properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389613-midi_audio_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AudioUnitParameterUnit"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@UInt32",
                    "text": "UInt32"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1BPM/title",
          "value": "kAudioUnitParameterUnit_BPM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1BPM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_BPM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1equalPowerCrossfade/title",
          "value": "kAudioUnitParameterUnit_EqualPowerCrossfade"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1equalPowerCrossfade/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_EqualPowerCrossfade"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1milliseconds/title",
          "value": "kAudioUnitParameterUnit_Milliseconds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1milliseconds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_Milliseconds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1beats/title",
          "value": "kAudioUnitParameterUnit_Beats"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1beats/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_Beats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1pan/title",
          "value": "kAudioUnitParameterUnit_Pan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1pan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_Pan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1midiController/title",
          "value": "kAudioUnitParameterUnit_MIDIController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1midiController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_MIDIController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1phase/title",
          "value": "kAudioUnitParameterUnit_Phase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1phase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_Phase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1absoluteCents/title",
          "value": "kAudioUnitParameterUnit_AbsoluteCents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1absoluteCents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_AbsoluteCents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1generic/title",
          "value": "kAudioUnitParameterUnit_Generic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1generic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_Generic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1octaves/title",
          "value": "kAudioUnitParameterUnit_Octaves"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1octaves/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_Octaves"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1degrees/title",
          "value": "kAudioUnitParameterUnit_Degrees"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1degrees/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_Degrees"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1relativeSemiTones/title",
          "value": "kAudioUnitParameterUnit_RelativeSemiTones"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1relativeSemiTones/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_RelativeSemiTones"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1rate/title",
          "value": "kAudioUnitParameterUnit_Rate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1rate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_Rate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1customUnit/title",
          "value": "kAudioUnitParameterUnit_CustomUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1customUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_CustomUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1midi2Controller/title",
          "value": "kAudioUnitParameterUnit_MIDI2Controller"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1midi2Controller/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_MIDI2Controller"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1indexed/title",
          "value": "kAudioUnitParameterUnit_Indexed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1indexed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_Indexed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1ratio/title",
          "value": "kAudioUnitParameterUnit_Ratio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1ratio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_Ratio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1sampleFrames/title",
          "value": "kAudioUnitParameterUnit_SampleFrames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1sampleFrames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_SampleFrames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1cents/title",
          "value": "kAudioUnitParameterUnit_Cents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1cents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_Cents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1decibels/title",
          "value": "kAudioUnitParameterUnit_Decibels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1decibels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_Decibels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1boolean/title",
          "value": "kAudioUnitParameterUnit_Boolean"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1boolean/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_Boolean"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit/title",
          "value": "AudioUnitParameterUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1linearGain/title",
          "value": "kAudioUnitParameterUnit_LinearGain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1linearGain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_LinearGain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1seconds/title",
          "value": "kAudioUnitParameterUnit_Seconds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1seconds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_Seconds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1mixerFaderCurve1/title",
          "value": "kAudioUnitParameterUnit_MixerFaderCurve1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1mixerFaderCurve1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_MixerFaderCurve1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1percent/title",
          "value": "kAudioUnitParameterUnit_Percent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1percent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_Percent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1midiNoteNumber/title",
          "value": "kAudioUnitParameterUnit_MIDINoteNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1midiNoteNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_MIDINoteNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1hertz/title",
          "value": "kAudioUnitParameterUnit_Hertz"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1hertz/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_Hertz"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1meters/title",
          "value": "kAudioUnitParameterUnit_Meters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1meters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_Meters"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/audiounitparameterunit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/audiounitparameterunit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
