{
  "abstract": [
    {
      "text": "The name and number of custom Cocoa views for an audio unit.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCocoaViewInfo"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@AudioUnitCocoaViewInfo",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AudioUnitCocoaViewInfo"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AudioUnitCocoaViewInfo"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AudioUnitCocoaViewInfo"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioUnitCocoaViewInfo"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1579363-audio_unit_carbon_view_component": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1579363-audio_unit_carbon_view_component",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Carbon View Component Types",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1579363-audio_unit_carbon_view_component"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1579365-audio_unit_carbon_view_events": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1579365-audio_unit_carbon_view_events",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Carbon View Events",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1579365-audio_unit_carbon_view_events"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1579372-audio_unit_carbon_view_selectors": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1579372-audio_unit_carbon_view_selectors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Carbon View Selectors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1579372-audio_unit_carbon_view_selectors"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUCocoaUIBase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AUCocoaUIBase"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUCocoaUIBase",
      "kind": "symbol",
      "role": "symbol",
      "title": "AUCocoaUIBase",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aucocoauibase"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCarbonView": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioUnitCarbonView"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCarbonView",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioUnitCarbonView",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitcarbonview"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCarbonViewEventID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioUnitCarbonViewEventID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCarbonViewEventID",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioUnitCarbonViewEventID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitcarbonvieweventid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCocoaViewInfo": {
      "abstract": [
        {
          "text": "The name and number of custom Cocoa views for an audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitCocoaViewInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCocoaViewInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitCocoaViewInfo"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitCocoaViewInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitcocoaviewinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCocoaViewInfo/init(mCocoaAUViewBundleLocation:mCocoaAUViewClass:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "mCocoaAUViewBundleLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "mCocoaAUViewClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCocoaViewInfo/init(mCocoaAUViewBundleLocation:mCocoaAUViewClass:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(mCocoaAUViewBundleLocation:mCocoaAUViewClass:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitcocoaviewinfo/init(mcocoaauviewbundlelocation:mcocoaauviewclass:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCocoaViewInfo/mCocoaAUViewBundleLocation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mCocoaAUViewBundleLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCocoaViewInfo/mCocoaAUViewBundleLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mCocoaAUViewBundleLocation"
        }
      ],
      "role": "symbol",
      "title": "mCocoaAUViewBundleLocation",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitcocoaviewinfo/mcocoaauviewbundlelocation"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCocoaViewInfo/mCocoaAUViewClass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mCocoaAUViewClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCocoaViewInfo/mCocoaAUViewClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mCocoaAUViewClass"
        }
      ],
      "role": "symbol",
      "title": "mCocoaAUViewClass",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitcocoaviewinfo/mcocoaauviewclass"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/GetAudioUnitParameterDisplayType(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GetAudioUnitParameterDisplayType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/GetAudioUnitParameterDisplayType(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GetAudioUnitParameterDisplayType"
        }
      ],
      "role": "symbol",
      "title": "GetAudioUnitParameterDisplayType(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/getaudiounitparameterdisplaytype(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/SetAudioUnitParameterDisplayType(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAudioUnitParameterDisplayType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/SetAudioUnitParameterDisplayType(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SetAudioUnitParameterDisplayType"
        }
      ],
      "role": "symbol",
      "title": "SetAudioUnitParameterDisplayType(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/setaudiounitparameterdisplaytype(_:_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-Audio-Unit-UI",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/GetAudioUnitParameterDisplayType(_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/SetAudioUnitParameterDisplayType(_:_:)"
      ],
      "title": "Configuring the Audio Unit UI"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCocoaViewInfo/init(mCocoaAUViewBundleLocation:mCocoaAUViewClass:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCocoaViewInfo/mCocoaAUViewBundleLocation",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCocoaViewInfo/mCocoaAUViewClass"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AudioUnitCocoaViewInfo"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitCocoaViewInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitCocoaViewInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCocoaViewInfo/mCocoaAUViewBundleLocation",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCocoaViewInfo/mCocoaAUViewClass"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-Audio-Unit-UI",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUCocoaUIBase",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCarbonView",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCarbonViewEventID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1579365-audio_unit_carbon_view_events",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1579372-audio_unit_carbon_view_selectors",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1579363-audio_unit_carbon_view_component",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/GetAudioUnitParameterDisplayType(_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/SetAudioUnitParameterDisplayType(_:_:)"
              ],
              "title": "Configuring the Audio Unit UI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AudioUnitCocoaViewInfo"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitCocoaViewInfo/title",
          "value": "AudioUnitCocoaViewInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitCocoaViewInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitCocoaViewInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitCocoaViewInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitCocoaViewInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1GetAudioUnitParameterDisplayType(_:)/title",
          "value": "GetAudioUnitParameterDisplayType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1GetAudioUnitParameterDisplayType(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GetAudioUnitParameterDisplayType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitCocoaViewInfo~1mCocoaAUViewClass/title",
          "value": "mCocoaAUViewClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitCocoaViewInfo~1mCocoaAUViewClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mCocoaAUViewClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitCocoaViewInfo~1mCocoaAUViewBundleLocation/title",
          "value": "mCocoaAUViewBundleLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitCocoaViewInfo~1mCocoaAUViewBundleLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mCocoaAUViewBundleLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1SetAudioUnitParameterDisplayType(_:_:)/title",
          "value": "SetAudioUnitParameterDisplayType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1SetAudioUnitParameterDisplayType(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SetAudioUnitParameterDisplayType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/audiounitcocoaviewinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/audiounitcocoaviewinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
