{
  "abstract": [
    {
      "text": "The data type for an audio unit parameter value.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterValue"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@AudioUnitParameterValue",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AudioUnitParameterValue"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AudioUnitParameterValue"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "AudioUnitParameterValue"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioUnitParameterValue"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s7Float32a",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s7Float32a",
              "text": "Float32"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An audio unit parameter is an adjustable setting, such as gain. The parameters for Apple-supplied audio units are described in ",
              "type": "text"
            },
            {
              "code": "Audio Unit Parameters",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can change a parameter value directly by calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitSetParameter(_:_:_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function, or schedule a change by calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitScheduleParameters(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". See also ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioChannelCount": {
      "abstract": [
        {
          "text": "A number of audio channels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioChannelCount"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioChannelCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUAudioChannelCount"
        }
      ],
      "role": "symbol",
      "title": "AUAudioChannelCount",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiochannelcount"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioFrameCount": {
      "abstract": [
        {
          "text": "A number of audio sample frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioFrameCount"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioFrameCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUAudioFrameCount"
        }
      ],
      "role": "symbol",
      "title": "AUAudioFrameCount",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudioframecount"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioObjectID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioObjectID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioObjectID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUAudioObjectID"
        }
      ],
      "role": "symbol",
      "title": "AUAudioObjectID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudioobjectid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitStatus": {
      "abstract": [
        {
          "text": "A result code returned from an audio unit’s render function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioUnitStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUAudioUnitStatus"
        }
      ],
      "role": "symbol",
      "title": "AUAudioUnitStatus",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounitstatus"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUEventListenerProc"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUEventListenerProc"
        }
      ],
      "role": "symbol",
      "title": "AUEventListenerProc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aueventlistenerproc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerRef": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUEventListenerRef"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUEventListenerRef"
        }
      ],
      "role": "symbol",
      "title": "AUEventListenerRef",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aueventlistenerref"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventSampleTime": {
      "abstract": [
        {
          "text": "Expresses time as a sample count.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUEventSampleTime"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventSampleTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUEventSampleTime"
        }
      ],
      "role": "symbol",
      "title": "AUEventSampleTime",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aueventsampletime"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueObserver": {
      "abstract": [
        {
          "text": "A block called to notify the audio unit implementation of changes to a parameter value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUImplementorValueObserver"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueObserver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUImplementorValueObserver"
        }
      ],
      "role": "symbol",
      "title": "AUImplementorValueObserver",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auimplementorvalueobserver"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueProvider": {
      "abstract": [
        {
          "text": "A block called to fetch a parameter’s current value from the audio unit implementation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUImplementorValueProvider"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUImplementorValueProvider"
        }
      ],
      "role": "symbol",
      "title": "AUImplementorValueProvider",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auimplementorvalueprovider"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUMIDICIProfileChangedBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUMIDICIProfileChangedBlock"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUMIDICIProfileChangedBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUMIDICIProfileChangedBlock"
        }
      ],
      "role": "symbol",
      "title": "AUMIDICIProfileChangedBlock",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aumidiciprofilechangedblock"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameter": {
      "abstract": [
        {
          "text": "An adjustable audio unit attribute such as volume, pitch, or filter cutoff frequency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameter"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameter"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID": {
      "abstract": [
        {
          "text": "The data type for an audio unit parameter identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterID"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterValue": {
      "abstract": [
        {
          "text": "The data type for an audio unit parameter value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterValue"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterValue"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterValue",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparametervalue"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitScheduleParameters(_:_:_:)": {
      "abstract": [
        {
          "text": "Schedules changes to the value of an audio unit parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitScheduleParameters"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnit",
          "text": "AudioUnit"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioUnitParameterEvent",
          "text": "AudioUnitParameterEvent"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitScheduleParameters(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitScheduleParameters"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitScheduleParameters(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitscheduleparameters(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitSetParameter(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Sets the value of an audio unit parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitSetParameter"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnit",
          "text": "AudioUnit"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitScope",
          "text": "AudioUnitScope"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitElement",
          "text": "AudioUnitElement"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterValue",
          "text": "AudioUnitParameterValue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitSetParameter(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitSetParameter"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitSetParameter(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitsetparameter(_:_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MIDIChannelNumber": {
      "abstract": [
        {
          "text": "MIDI Channel, 0~15 (channels 1 through 16, respectively).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIChannelNumber"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MIDIChannelNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIChannelNumber"
        }
      ],
      "role": "symbol",
      "title": "MIDIChannelNumber",
      "type": "topic",
      "url": "/documentation/audiotoolbox/midichannelnumber"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ScheduledAudioFileRegion"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ScheduledAudioFileRegion"
        }
      ],
      "role": "symbol",
      "title": "ScheduledAudioFileRegion",
      "type": "topic",
      "url": "/documentation/audiotoolbox/scheduledaudiofileregion"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegionCompletionProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ScheduledAudioFileRegionCompletionProc"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegionCompletionProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ScheduledAudioFileRegionCompletionProc"
        }
      ],
      "role": "symbol",
      "title": "ScheduledAudioFileRegionCompletionProc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/scheduledaudiofileregioncompletionproc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSlice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ScheduledAudioSlice"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSlice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ScheduledAudioSlice"
        }
      ],
      "role": "symbol",
      "title": "ScheduledAudioSlice",
      "type": "topic",
      "url": "/documentation/audiotoolbox/scheduledaudioslice"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSliceCompletionProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ScheduledAudioSliceCompletionProc"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSliceCompletionProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ScheduledAudioSliceCompletionProc"
        }
      ],
      "role": "symbol",
      "title": "ScheduledAudioSliceCompletionProc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/scheduledaudioslicecompletionproc"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@Float32": {
      "abstract": [
        {
          "text": "Convenience type that represent a 32-bit floating point number",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@Float32",
      "kind": "symbol",
      "role": "symbol",
      "title": "Float32",
      "type": "topic",
      "url": "/documentation/kernel/float32"
    },
    "doc://com.externally.resolved.symbol/s:s7Float32a": {
      "abstract": [
        {
          "text": "A 32-bit floating point type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Float32"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7Float32a",
      "kind": "symbol",
      "role": "symbol",
      "title": "Float32",
      "type": "topic",
      "url": "/documentation/Swift/Float32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Audio-Unit-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSlice",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegionCompletionProc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSliceCompletionProc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MIDIChannelNumber",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioObjectID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUMIDICIProfileChangedBlock",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioChannelCount",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioFrameCount",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitStatus",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerProc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerRef",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventSampleTime",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueObserver",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueProvider"
      ],
      "title": "Audio Unit Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AudioUnitParameterValue"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Audio-Unit-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSlice",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegionCompletionProc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSliceCompletionProc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MIDIChannelNumber",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioObjectID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUMIDICIProfileChangedBlock",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioChannelCount",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioFrameCount",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitStatus",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerProc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerRef",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventSampleTime",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueObserver",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueProvider"
              ],
              "title": "Audio Unit Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@Float32",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@Float32",
                    "text": "Float32"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AudioUnitParameterValue"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MIDIChannelNumber/title",
          "value": "MIDIChannelNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MIDIChannelNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIChannelNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MIDIChannelNumber/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIChannelNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegion/title",
          "value": "ScheduledAudioFileRegion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ScheduledAudioFileRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ScheduledAudioFileRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUMIDICIProfileChangedBlock/title",
          "value": "AUMIDICIProfileChangedBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUMIDICIProfileChangedBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUMIDICIProfileChangedBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUMIDICIProfileChangedBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUMIDICIProfileChangedBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterValue/title",
          "value": "AudioUnitParameterValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/title",
          "value": "AudioUnitParameterID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioObjectID/title",
          "value": "AUAudioObjectID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioObjectID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioObjectID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioObjectID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioObjectID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioChannelCount/title",
          "value": "AUAudioChannelCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioChannelCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioChannelCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioChannelCount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioChannelCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioSlice/title",
          "value": "ScheduledAudioSlice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioSlice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ScheduledAudioSlice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioSlice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ScheduledAudioSlice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitStatus/title",
          "value": "AUAudioUnitStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueProvider/title",
          "value": "AUImplementorValueProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUImplementorValueProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUImplementorValueProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueObserver/title",
          "value": "AUImplementorValueObserver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueObserver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUImplementorValueObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueObserver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUImplementorValueObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerProc/title",
          "value": "AUEventListenerProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUEventListenerProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUEventListenerProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegionCompletionProc/title",
          "value": "ScheduledAudioFileRegionCompletionProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegionCompletionProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ScheduledAudioFileRegionCompletionProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegionCompletionProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ScheduledAudioFileRegionCompletionProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventSampleTime/title",
          "value": "AUEventSampleTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventSampleTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUEventSampleTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventSampleTime/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUEventSampleTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioSliceCompletionProc/title",
          "value": "ScheduledAudioSliceCompletionProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioSliceCompletionProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ScheduledAudioSliceCompletionProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioSliceCompletionProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ScheduledAudioSliceCompletionProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerRef/title",
          "value": "AUEventListenerRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUEventListenerRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUEventListenerRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioFrameCount/title",
          "value": "AUAudioFrameCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioFrameCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioFrameCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioFrameCount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioFrameCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitSetParameter(_:_:_:_:_:_:)/title",
          "value": "AudioUnitSetParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitSetParameter(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitSetParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitScheduleParameters(_:_:_:)/title",
          "value": "AudioUnitScheduleParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitScheduleParameters(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitScheduleParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameter/title",
          "value": "AudioUnitParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameter"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/audiounitparametervalue"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/audiounitparametervalue"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
