{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@AudioFileFDFTable",
    "fragments": [
      {
        "kind": "identifier",
        "text": "AudioFileFDFTable"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AudioFileFDFTable"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AudioFileFDFTable"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioFileFDFTable"
            },
            {
              "kind": "text",
              "text": " { ... } "
            },
            {
              "kind": "identifier",
              "text": "AudioFileFDFTable"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBytePacketTranslationFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioBytePacketTranslationFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBytePacketTranslationFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioBytePacketTranslationFlags"
        }
      ],
      "role": "symbol",
      "title": "AudioBytePacketTranslationFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiobytepackettranslationflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioFileFDFTable"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioFileFDFTable",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilefdftable"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mComponentStorage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mComponentStorage"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mComponentStorage",
      "kind": "symbol",
      "role": "symbol",
      "title": "mComponentStorage",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilefdftable/mcomponentstorage"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mCountUserDataFDF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mCountUserDataFDF"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mCountUserDataFDF",
      "kind": "symbol",
      "role": "symbol",
      "title": "mCountUserDataFDF",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilefdftable/mcountuserdatafdf"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mGetPropertyFDF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mGetPropertyFDF"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mGetPropertyFDF",
      "kind": "symbol",
      "role": "symbol",
      "title": "mGetPropertyFDF",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilefdftable/mgetpropertyfdf"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mGetPropertyInfoFDF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mGetPropertyInfoFDF"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mGetPropertyInfoFDF",
      "kind": "symbol",
      "role": "symbol",
      "title": "mGetPropertyInfoFDF",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilefdftable/mgetpropertyinfofdf"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mGetUserDataFDF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mGetUserDataFDF"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mGetUserDataFDF",
      "kind": "symbol",
      "role": "symbol",
      "title": "mGetUserDataFDF",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilefdftable/mgetuserdatafdf"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mGetUserDataSizeFDF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mGetUserDataSizeFDF"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mGetUserDataSizeFDF",
      "kind": "symbol",
      "role": "symbol",
      "title": "mGetUserDataSizeFDF",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilefdftable/mgetuserdatasizefdf"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mReadBytesFDF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mReadBytesFDF"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mReadBytesFDF",
      "kind": "symbol",
      "role": "symbol",
      "title": "mReadBytesFDF",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilefdftable/mreadbytesfdf"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mReadPacketsFDF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mReadPacketsFDF"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mReadPacketsFDF",
      "kind": "symbol",
      "role": "symbol",
      "title": "mReadPacketsFDF",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilefdftable/mreadpacketsfdf"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mSetPropertyFDF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mSetPropertyFDF"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mSetPropertyFDF",
      "kind": "symbol",
      "role": "symbol",
      "title": "mSetPropertyFDF",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilefdftable/msetpropertyfdf"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mSetUserDataFDF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mSetUserDataFDF"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mSetUserDataFDF",
      "kind": "symbol",
      "role": "symbol",
      "title": "mSetUserDataFDF",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilefdftable/msetuserdatafdf"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mWriteBytesFDF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mWriteBytesFDF"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mWriteBytesFDF",
      "kind": "symbol",
      "role": "symbol",
      "title": "mWriteBytesFDF",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilefdftable/mwritebytesfdf"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mWritePacketsFDF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mWritePacketsFDF"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mWritePacketsFDF",
      "kind": "symbol",
      "role": "symbol",
      "title": "mWritePacketsFDF",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilefdftable/mwritepacketsfdf"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTableExtended": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioFileFDFTableExtended"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTableExtended",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioFileFDFTableExtended",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilefdftableextended"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileFlags"
        }
      ],
      "role": "symbol",
      "title": "AudioFileFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofileflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileID": {
      "abstract": [
        {
          "text": "An opaque data type that represents an audio file object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileID"
        }
      ],
      "role": "symbol",
      "title": "AudioFileID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofileid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileMarker": {
      "abstract": [
        {
          "text": "Annotates a position in an audio file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileMarker"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileMarker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileMarker"
        }
      ],
      "role": "symbol",
      "title": "AudioFileMarker",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilemarker"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileMarkerList": {
      "abstract": [
        {
          "text": "A list of markers associated with an audio file, including their SMPTE time type, the number of markers, and the markers themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileMarkerList"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileMarkerList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileMarkerList"
        }
      ],
      "role": "symbol",
      "title": "AudioFileMarkerList",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilemarkerlist"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFilePropertyID": {
      "abstract": [
        {
          "text": "An audio file property identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFilePropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFilePropertyID"
        }
      ],
      "role": "symbol",
      "title": "AudioFilePropertyID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilepropertyid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileRegion": {
      "abstract": [
        {
          "text": "An audio file region specifies a segment of audio data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileRegion"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileRegion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileRegion"
        }
      ],
      "role": "symbol",
      "title": "AudioFileRegion",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofileregion"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileRegionFlags": {
      "abstract": [
        {
          "text": "Flags that specify a playback direction for an audio file region structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileRegionFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileRegionFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileRegionFlags"
        }
      ],
      "role": "symbol",
      "title": "AudioFileRegionFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofileregionflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileRegionList": {
      "abstract": [
        {
          "text": "A list of the audio file regions in a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileRegionList"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileRegionList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileRegionList"
        }
      ],
      "role": "symbol",
      "title": "AudioFileRegionList",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofileregionlist"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamParseFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileStreamParseFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamParseFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileStreamParseFlags"
        }
      ],
      "role": "symbol",
      "title": "AudioFileStreamParseFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilestreamparseflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamPropertyFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileStreamPropertyFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamPropertyFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileStreamPropertyFlags"
        }
      ],
      "role": "symbol",
      "title": "AudioFileStreamPropertyFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilestreampropertyflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamSeekFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileStreamSeekFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamSeekFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileStreamSeekFlags"
        }
      ],
      "role": "symbol",
      "title": "AudioFileStreamSeekFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilestreamseekflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFile_SMPTE_Time": {
      "abstract": [
        {
          "text": "A data structure for describing SMPTE (Society of Motion Picture and Television Engineers) time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFile_SMPTE_Time"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFile_SMPTE_Time",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFile_SMPTE_Time"
        }
      ],
      "role": "symbol",
      "title": "AudioFile_SMPTE_Time",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofile_smpte_time"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFramePacketTranslation": {
      "abstract": [
        {
          "text": "A structure that specifies frame and packet translations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFramePacketTranslation"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFramePacketTranslation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFramePacketTranslation"
        }
      ],
      "role": "symbol",
      "title": "AudioFramePacketTranslation",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioframepackettranslation"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBytePacketTranslationFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTableExtended",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileRegionFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamParseFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamPropertyFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamSeekFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFilePropertyID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFile_SMPTE_Time",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileMarker",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileMarkerList",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileRegion",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileRegionList",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFramePacketTranslation"
      ],
      "title": "Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mComponentStorage",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mCountUserDataFDF",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mGetPropertyFDF",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mGetPropertyInfoFDF",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mGetUserDataFDF",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mGetUserDataSizeFDF",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mReadBytesFDF",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mReadPacketsFDF",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mSetPropertyFDF",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mSetUserDataFDF",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mWriteBytesFDF",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mWritePacketsFDF"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileMarkerList/title",
          "value": "AudioFileMarkerList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileMarkerList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileMarkerList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileMarkerList/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileMarkerList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioBytePacketTranslationFlags/title",
          "value": "AudioBytePacketTranslationFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioBytePacketTranslationFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioBytePacketTranslationFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioBytePacketTranslationFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioBytePacketTranslationFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileStreamSeekFlags/title",
          "value": "AudioFileStreamSeekFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileStreamSeekFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileStreamSeekFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileStreamSeekFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileStreamSeekFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileStreamPropertyFlags/title",
          "value": "AudioFileStreamPropertyFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileStreamPropertyFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileStreamPropertyFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileStreamPropertyFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileStreamPropertyFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileRegionFlags/title",
          "value": "AudioFileRegionFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileRegionFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileRegionFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileRegionFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileRegionFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileMarker/title",
          "value": "AudioFileMarker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileMarker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileMarker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileMarker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileMarker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFilePropertyID/title",
          "value": "AudioFilePropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFilePropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFilePropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFilePropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFilePropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFile_SMPTE_Time/title",
          "value": "AudioFile_SMPTE_Time"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFile_SMPTE_Time/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFile_SMPTE_Time"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFile_SMPTE_Time/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFile_SMPTE_Time"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileStreamParseFlags/title",
          "value": "AudioFileStreamParseFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileStreamParseFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileStreamParseFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileStreamParseFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileStreamParseFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileRegionList/title",
          "value": "AudioFileRegionList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileRegionList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileRegionList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileRegionList/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileRegionList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileRegion/title",
          "value": "AudioFileRegion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileRegion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileRegion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFramePacketTranslation/title",
          "value": "AudioFramePacketTranslation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFramePacketTranslation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFramePacketTranslation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFramePacketTranslation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFramePacketTranslation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileID/title",
          "value": "AudioFileID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileFlags/title",
          "value": "AudioFileFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileFlags"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/audiofilefdftable"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
