{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AudioUnitEventType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AudioUnitEventType"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AudioUnitEventType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "AudioUnitEventType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioUnitEventType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389613-midi_audio_unit_parameters": {
      "abstract": [
        {
          "text": "Parameters for instrument units.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389613-midi_audio_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Audio Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389613-midi_audio_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi": {
      "abstract": [
        {
          "text": "Reserved for system use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Reserved Audio Unit Clump Identifier",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1533986-reserved_audio_unit_clump_identi"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534054-offline_audio_unit_properties": {
      "abstract": [
        {
          "text": "Properties for audio units that perform offline processing—that is, processing in a nonplayback, nonrealtime mode.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534054-offline_audio_unit_properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Offline Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534054-offline_audio_unit_properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes": {
      "abstract": [
        {
          "text": "Input/output audio unit subtypes for audio units provided by Apple.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Input/Output Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584139-input_output_audio_unit_subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele": {
      "abstract": [
        {
          "text": "General audio unit component selectors that correspond to functions in the audio unit API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele",
      "kind": "article",
      "role": "collectionGroup",
      "title": "General Audio Unit Function Selectors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584140-general_audio_unit_function_sele"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584142-audio_unit_types": {
      "abstract": [
        {
          "text": "The defined types of audio processing plug-ins known as audio units.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584142-audio_unit_types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Types",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584142-audio_unit_types"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi": {
      "abstract": [
        {
          "text": "The Apple audio unit manufacturer code.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Manufacturer Identifier",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584143-audio_unit_manufacturer_identifi"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes": {
      "abstract": [
        {
          "text": "Audio data format converter audio unit subtypes for audio units provided by Apple.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Converter Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584145-converter_audio_unit_subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584148-audio-unit-output-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584148-audio-unit-output-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Output Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584148-audio-unit-output-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Panner Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584151-audio-unit-panner-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Pitch Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584152-audio-unit-pitch-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Player Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584155-audio-unit-player-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "I/O Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1619485-i-o-audio-unit-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes": {
      "abstract": [
        {
          "text": "Audio units that serve as sound sources.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Generator Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1619493-generator_audio_unit_subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Inter-App Audio Unit Types",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1619501-inter-app-audio-unit-types"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitEventType"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitEventType"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitEventType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiouniteventtype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType/beginParameterChangeGesture": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginParameterChangeGesture"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType/beginParameterChangeGesture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitEvent_BeginParameterChangeGesture"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitEventType.beginParameterChangeGesture",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiouniteventtype/beginparameterchangegesture"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType/endParameterChangeGesture": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endParameterChangeGesture"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType/endParameterChangeGesture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitEvent_EndParameterChangeGesture"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitEventType.endParameterChangeGesture",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiouniteventtype/endparameterchangegesture"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiouniteventtype/init(rawvalue:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType/parameterValueChange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parameterValueChange"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType/parameterValueChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitEvent_ParameterValueChange"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitEventType.parameterValueChange",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiouniteventtype/parametervaluechange"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType/propertyChange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "propertyChange"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType/propertyChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitEvent_PropertyChange"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitEventType.propertyChange",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiouniteventtype/propertychange"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584142-audio_unit_types",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584148-audio-unit-output-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534054-offline_audio_unit_properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389613-midi_audio_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType/beginParameterChangeGesture",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType/endParameterChangeGesture",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType/parameterValueChange",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType/propertyChange"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AudioUnitEventType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType/beginParameterChangeGesture",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType/endParameterChangeGesture",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType/parameterValueChange",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEventType/propertyChange"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584142-audio_unit_types",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584148-audio-unit-output-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534054-offline_audio_unit_properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389613-midi_audio_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AudioUnitEventType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@UInt32",
                    "text": "UInt32"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEventType~1beginParameterChangeGesture/title",
          "value": "kAudioUnitEvent_BeginParameterChangeGesture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEventType~1beginParameterChangeGesture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitEvent_BeginParameterChangeGesture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEventType~1parameterValueChange/title",
          "value": "kAudioUnitEvent_ParameterValueChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEventType~1parameterValueChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitEvent_ParameterValueChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEventType~1propertyChange/title",
          "value": "kAudioUnitEvent_PropertyChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEventType~1propertyChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitEvent_PropertyChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEventType~1endParameterChangeGesture/title",
          "value": "kAudioUnitEvent_EndParameterChangeGesture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEventType~1endParameterChangeGesture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitEvent_EndParameterChangeGesture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEventType/title",
          "value": "AudioUnitEventType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEventType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEventType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitEventType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/audiouniteventtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/audiouniteventtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
