{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-structures"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "AudioToolbox Structures"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUMIDIEventList": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUMIDIEventList"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUMIDIEventList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUMIDIEventList"
        }
      ],
      "role": "symbol",
      "title": "AUMIDIEventList",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aumidieventlist"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioConverterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioConverterOptions"
        }
      ],
      "role": "symbol",
      "title": "AudioConverterOptions",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioconverteroptions"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AudioToolbox Constants",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiotoolbox-constants"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AudioToolbox Data Types",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiotoolbox-data-types"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AudioToolbox Enumerations",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiotoolbox-enumerations"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AudioToolbox Functions",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiotoolbox-functions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-enumerations",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-constants",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-functions",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Structures",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUMIDIEventList",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterOptions"
      ],
      "title": "Structures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Structures",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUMIDIEventList",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterOptions"
              ],
              "title": "Structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-enumerations",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-constants",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-functions",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterOptions/title",
          "value": "AudioConverterOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioConverterOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioConverterOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUMIDIEventList/title",
          "value": "AUMIDIEventList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUMIDIEventList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUMIDIEventList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUMIDIEventList/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUMIDIEventList"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/audiotoolbox-structures"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/audiotoolbox-structures"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
