{
  "abstract": [
    {
      "text": "Retrieves a reference to an audio component from an instance of that audio component.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentInstanceGetComponent(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@AudioComponentInstanceGetComponent",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AudioComponentInstanceGetComponent"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioComponentInstance",
        "text": "AudioComponentInstance"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioComponent",
        "text": "AudioComponent"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AudioComponentInstanceGetComponent"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "AudioComponentInstanceGetComponent(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioComponentInstanceGetComponent"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inInstance"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentInstance",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioComponentInstance",
              "text": "AudioComponentInstance"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioComponent",
              "text": "AudioComponent"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The component instance whose corresponding factory object you want to get. Must not be ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": ", and you must own the instance (specifically, you must not have previously called ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentInstanceDispose(_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " on the instance).",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inInstance"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A reference to the desired audio component. If the value provided in the ",
              "type": "text"
            },
            {
              "code": "inInstance",
              "type": "codeVoice"
            },
            {
              "text": " parameter is invalid, returns ",
              "type": "text"
            },
            {
              "code": "NULL",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this function to retrieve a reference to the audio component that was used to instantiate a given audio component instance. You can then query the component for its attributes by calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentGetDescription(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponent": {
      "abstract": [
        {
          "text": "An audio component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioComponent"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioComponent"
        }
      ],
      "role": "symbol",
      "title": "AudioComponent",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocomponent"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentCount(_:)": {
      "abstract": [
        {
          "text": "Returns the number of audio components that match a specified ",
          "type": "text"
        },
        {
          "code": "AudioComponentDescription",
          "type": "codeVoice"
        },
        {
          "text": " structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioComponentCount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioComponentDescription",
          "text": "AudioComponentDescription"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentCount(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioComponentCount"
        }
      ],
      "role": "symbol",
      "title": "AudioComponentCount(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocomponentcount(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentDescription": {
      "abstract": [
        {
          "text": "Identifying information for an audio component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioComponentDescription"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioComponentDescription"
        }
      ],
      "role": "symbol",
      "title": "AudioComponentDescription",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocomponentdescription"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentFactoryFunction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioComponentFactoryFunction"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentFactoryFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioComponentFactoryFunction"
        }
      ],
      "role": "symbol",
      "title": "AudioComponentFactoryFunction",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocomponentfactoryfunction"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentFindNext(_:_:)": {
      "abstract": [
        {
          "text": "Finds the next component that matches a specified ",
          "type": "text"
        },
        {
          "code": "AudioComponentDescription",
          "type": "codeVoice"
        },
        {
          "text": " structure after a specified audio component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioComponentFindNext"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioComponent",
          "text": "AudioComponent"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioComponentDescription",
          "text": "AudioComponentDescription"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioComponent",
          "text": "AudioComponent"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentFindNext(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioComponentFindNext"
        }
      ],
      "role": "symbol",
      "title": "AudioComponentFindNext(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocomponentfindnext(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioComponentFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioComponentFlags"
        }
      ],
      "role": "symbol",
      "title": "AudioComponentFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocomponentflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentGetDescription(_:_:)": {
      "abstract": [
        {
          "text": "Gets the class description, as an ",
          "type": "text"
        },
        {
          "code": "AudioComponentDescription",
          "type": "codeVoice"
        },
        {
          "text": " structure, of an audio component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioComponentGetDescription"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioComponent",
          "text": "AudioComponent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioComponentDescription",
          "text": "AudioComponentDescription"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentGetDescription(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioComponentGetDescription"
        }
      ],
      "role": "symbol",
      "title": "AudioComponentGetDescription(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocomponentgetdescription(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentInstance": {
      "abstract": [
        {
          "text": "A component instance, or object, is an audio unit or audio codec.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioComponentInstance"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentInstance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioComponentInstance"
        }
      ],
      "role": "symbol",
      "title": "AudioComponentInstance",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocomponentinstance"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentInstanceDispose(_:)": {
      "abstract": [
        {
          "text": "Disposes of an audio component instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioComponentInstanceDispose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioComponentInstance",
          "text": "AudioComponentInstance"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentInstanceDispose(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioComponentInstanceDispose"
        }
      ],
      "role": "symbol",
      "title": "AudioComponentInstanceDispose(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocomponentinstancedispose(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentInstanceGetComponent(_:)": {
      "abstract": [
        {
          "text": "Retrieves a reference to an audio component from an instance of that audio component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioComponentInstanceGetComponent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioComponentInstance",
          "text": "AudioComponentInstance"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioComponent",
          "text": "AudioComponent"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentInstanceGetComponent(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioComponentInstanceGetComponent"
        }
      ],
      "role": "symbol",
      "title": "AudioComponentInstanceGetComponent(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocomponentinstancegetcomponent(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentRegister(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioComponentRegister"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioComponentDescription",
          "text": "AudioComponentDescription"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioComponentFactoryFunction",
          "text": "AudioComponentFactoryFunction"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioComponent",
          "text": "AudioComponent"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentRegister(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioComponentRegister"
        }
      ],
      "role": "symbol",
      "title": "AudioComponentRegister(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocomponentregister(_:_:_:_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-an-Audio-Component-Dynamically",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentRegister(_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentCount(_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentFindNext(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentDescription",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentInstance",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentFactoryFunction"
      ],
      "title": "Creating an Audio Component Dynamically"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AudioComponentInstanceGetComponent"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioComponentInstanceGetComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-an-Audio-Component-Dynamically",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentRegister(_:_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentCount(_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentFindNext(_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentDescription",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentInstance",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentFlags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentFactoryFunction"
              ],
              "title": "Creating an Audio Component Dynamically"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AudioComponent",
                    "text": "AudioComponent"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AudioComponentInstanceGetComponent"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentInstance",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AudioComponentInstance",
                    "text": "AudioComponentInstance"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inInstance"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The component instance whose corresponding factory object you want to get. Must not be ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": ", and you must own the instance (specifically, you must not have previously called ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentInstanceDispose(_:)",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " on the instance).",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inInstance"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A reference to the desired audio component. If the value provided in the ",
                    "type": "text"
                  },
                  {
                    "code": "inInstance",
                    "type": "codeVoice"
                  },
                  {
                    "text": " parameter is invalid, returns ",
                    "type": "text"
                  },
                  {
                    "code": "NULL",
                    "type": "codeVoice"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentInstanceGetComponent(_:)/title",
          "value": "AudioComponentInstanceGetComponent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentInstanceGetComponent(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioComponentInstanceGetComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentDescription/title",
          "value": "AudioComponentDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioComponentDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioComponentDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentFlags/title",
          "value": "AudioComponentFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioComponentFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioComponentFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentFindNext(_:_:)/title",
          "value": "AudioComponentFindNext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentFindNext(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioComponentFindNext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponent/title",
          "value": "AudioComponent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentInstanceDispose(_:)/title",
          "value": "AudioComponentInstanceDispose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentInstanceDispose(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioComponentInstanceDispose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentRegister(_:_:_:_:)/title",
          "value": "AudioComponentRegister"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentRegister(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioComponentRegister"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentInstance/title",
          "value": "AudioComponentInstance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentInstance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioComponentInstance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentInstance/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioComponentInstance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentGetDescription(_:_:)/title",
          "value": "AudioComponentGetDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentGetDescription(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioComponentGetDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentCount(_:)/title",
          "value": "AudioComponentCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentCount(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioComponentCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentFactoryFunction/title",
          "value": "AudioComponentFactoryFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentFactoryFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioComponentFactoryFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentFactoryFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioComponentFactoryFunction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/audiocomponentinstancegetcomponent(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/audiocomponentinstancegetcomponent(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
