{
  "abstract": [
    {
      "text": "Configure system voice processing and respond to speech events.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-voice-i-o"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio Unit Voice I/O"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOMutedSpeechActivityEventListener": {
      "abstract": [
        {
          "text": "A block that the system calls to indicate speech activity while the user has the microphone muted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUVoiceIOMutedSpeechActivityEventListener"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOMutedSpeechActivityEventListener",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUVoiceIOMutedSpeechActivityEventListener"
        }
      ],
      "role": "symbol",
      "title": "AUVoiceIOMutedSpeechActivityEventListener",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auvoiceiomutedspeechactivityeventlistener"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOOtherAudioDuckingConfiguration": {
      "abstract": [
        {
          "text": "A structure that you use to configure ducking of other non-voice audio in a voice chat.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUVoiceIOOtherAudioDuckingConfiguration"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOOtherAudioDuckingConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUVoiceIOOtherAudioDuckingConfiguration"
        }
      ],
      "role": "symbol",
      "title": "AUVoiceIOOtherAudioDuckingConfiguration",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auvoiceiootheraudioduckingconfiguration"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOSpeechActivityEvent": {
      "abstract": [
        {
          "text": "Constants that indicate the state of muted speech.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUVoiceIOSpeechActivityEvent"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOSpeechActivityEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUVoiceIOSpeechActivityEvent"
        }
      ],
      "role": "symbol",
      "title": "AUVoiceIOSpeechActivityEvent",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auvoiceiospeechactivityevent"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-components": {
      "abstract": [
        {
          "text": "Find, load, and configure audio components, such as Audio Units and audio codecs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-components",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Components",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-components"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties": {
      "abstract": [
        {
          "text": "Obtain information about the built-in mixers, equalizers, filters, effects, and other Audio Unit app extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api": {
      "abstract": [
        {
          "text": "Configure an Audio Unit and prepare it to render audio.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit v2 (C) API",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-v2-c-api"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v3-plug-ins": {
      "abstract": [
        {
          "text": "Deliver custom audio effects, instruments, and other audio behaviors using an Audio Unit v3 app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v3-plug-ins",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit v3 Plug-Ins",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-v3-plug-ins"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/generating-spatial-audio-from-a-multichannel-audio-stream": {
      "abstract": [
        {
          "text": "Convert 8-channel audio to 2-channel spatial audio by using a spatial mixer audio unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/generating-spatial-audio-from-a-multichannel-audio-stream",
      "kind": "article",
      "role": "sampleCode",
      "title": "Generating spatial audio from a multichannel audio stream",
      "type": "topic",
      "url": "/documentation/audiotoolbox/generating-spatial-audio-from-a-multichannel-audio-stream"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUVoiceIOErr_UnexpectedNumberOfInputChannels": {
      "abstract": [
        {
          "text": "An error that indicates that the audio unit encountered an unexpected number of input channels during initialization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUVoiceIOErr_UnexpectedNumberOfInputChannels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUVoiceIOErr_UnexpectedNumberOfInputChannels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUVoiceIOErr_UnexpectedNumberOfInputChannels"
        }
      ],
      "role": "symbol",
      "title": "kAUVoiceIOErr_UnexpectedNumberOfInputChannels",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kauvoiceioerr_unexpectednumberofinputchannels"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUVoiceIOProperty_BypassVoiceProcessing": {
      "abstract": [
        {
          "text": "A property that bypasses all processing for microphone uplink done by the voice processing unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUVoiceIOProperty_BypassVoiceProcessing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUVoiceIOProperty_BypassVoiceProcessing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUVoiceIOProperty_BypassVoiceProcessing"
        }
      ],
      "role": "symbol",
      "title": "kAUVoiceIOProperty_BypassVoiceProcessing",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kauvoiceioproperty_bypassvoiceprocessing"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUVoiceIOProperty_MuteOutput": {
      "abstract": [
        {
          "text": "A property to mute the output of the processed microphone uplink.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUVoiceIOProperty_MuteOutput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUVoiceIOProperty_MuteOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUVoiceIOProperty_MuteOutput"
        }
      ],
      "role": "symbol",
      "title": "kAUVoiceIOProperty_MuteOutput",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kauvoiceioproperty_muteoutput"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUVoiceIOProperty_MutedSpeechActivityEventListener": {
      "abstract": [
        {
          "text": "A property to register a listener that the system calls when it detects speech while the user has the microphone muted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUVoiceIOProperty_MutedSpeechActivityEventListener"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUVoiceIOProperty_MutedSpeechActivityEventListener",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUVoiceIOProperty_MutedSpeechActivityEventListener"
        }
      ],
      "role": "symbol",
      "title": "kAUVoiceIOProperty_MutedSpeechActivityEventListener",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kauvoiceioproperty_mutedspeechactivityeventlistener"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUVoiceIOProperty_VoiceProcessingEnableAGC": {
      "abstract": [
        {
          "text": "A property to enable automatic gain control on the processed microphone uplink.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUVoiceIOProperty_VoiceProcessingEnableAGC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUVoiceIOProperty_VoiceProcessingEnableAGC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUVoiceIOProperty_VoiceProcessingEnableAGC"
        }
      ],
      "role": "symbol",
      "title": "kAUVoiceIOProperty_VoiceProcessingEnableAGC",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kauvoiceioproperty_voiceprocessingenableagc"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Audio-Units",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/generating-spatial-audio-from-a-multichannel-audio-stream",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v3-plug-ins",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-components",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties"
      ],
      "title": "Audio Units"
    }
  ],
  "topicSections": [
    {
      "anchor": "Observing-muted-speech",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUVoiceIOProperty_MutedSpeechActivityEventListener",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOMutedSpeechActivityEventListener",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOSpeechActivityEvent"
      ],
      "title": "Observing muted speech"
    },
    {
      "anchor": "Configuring-voice-processing",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUVoiceIOProperty_BypassVoiceProcessing",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUVoiceIOProperty_VoiceProcessingEnableAGC",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUVoiceIOProperty_MuteOutput"
      ],
      "title": "Configuring voice processing"
    },
    {
      "anchor": "Configuring-ducking-of-other-audio",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOOtherAudioDuckingConfiguration"
      ],
      "title": "Configuring ducking of other audio"
    },
    {
      "anchor": "Inspecting-errors",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUVoiceIOErr_UnexpectedNumberOfInputChannels"
      ],
      "title": "Inspecting errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Observing-muted-speech",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUVoiceIOProperty_MutedSpeechActivityEventListener",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOMutedSpeechActivityEventListener",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOSpeechActivityEvent"
              ],
              "title": "Observing muted speech"
            },
            {
              "anchor": "Configuring-voice-processing",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUVoiceIOProperty_BypassVoiceProcessing",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUVoiceIOProperty_VoiceProcessingEnableAGC",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUVoiceIOProperty_MuteOutput"
              ],
              "title": "Configuring voice processing"
            },
            {
              "anchor": "Configuring-ducking-of-other-audio",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOOtherAudioDuckingConfiguration"
              ],
              "title": "Configuring ducking of other audio"
            },
            {
              "anchor": "Inspecting-errors",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUVoiceIOErr_UnexpectedNumberOfInputChannels"
              ],
              "title": "Inspecting errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Audio-Units",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/generating-spatial-audio-from-a-multichannel-audio-stream",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v3-plug-ins",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-components",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties"
              ],
              "title": "Audio Units"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUVoiceIOProperty_MutedSpeechActivityEventListener/title",
          "value": "kAUVoiceIOProperty_MutedSpeechActivityEventListener"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUVoiceIOProperty_MutedSpeechActivityEventListener/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUVoiceIOProperty_MutedSpeechActivityEventListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUVoiceIOProperty_VoiceProcessingEnableAGC/title",
          "value": "kAUVoiceIOProperty_VoiceProcessingEnableAGC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUVoiceIOProperty_VoiceProcessingEnableAGC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUVoiceIOProperty_VoiceProcessingEnableAGC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUVoiceIOMutedSpeechActivityEventListener/title",
          "value": "AUVoiceIOMutedSpeechActivityEventListener"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUVoiceIOMutedSpeechActivityEventListener/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUVoiceIOMutedSpeechActivityEventListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUVoiceIOMutedSpeechActivityEventListener/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUVoiceIOMutedSpeechActivityEventListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUVoiceIOErr_UnexpectedNumberOfInputChannels/title",
          "value": "kAUVoiceIOErr_UnexpectedNumberOfInputChannels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUVoiceIOErr_UnexpectedNumberOfInputChannels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUVoiceIOErr_UnexpectedNumberOfInputChannels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUVoiceIOOtherAudioDuckingConfiguration/title",
          "value": "AUVoiceIOOtherAudioDuckingConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUVoiceIOOtherAudioDuckingConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUVoiceIOOtherAudioDuckingConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUVoiceIOOtherAudioDuckingConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUVoiceIOOtherAudioDuckingConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUVoiceIOSpeechActivityEvent/title",
          "value": "AUVoiceIOSpeechActivityEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUVoiceIOSpeechActivityEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUVoiceIOSpeechActivityEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUVoiceIOSpeechActivityEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUVoiceIOSpeechActivityEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUVoiceIOProperty_MuteOutput/title",
          "value": "kAUVoiceIOProperty_MuteOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUVoiceIOProperty_MuteOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUVoiceIOProperty_MuteOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUVoiceIOProperty_BypassVoiceProcessing/title",
          "value": "kAUVoiceIOProperty_BypassVoiceProcessing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUVoiceIOProperty_BypassVoiceProcessing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUVoiceIOProperty_BypassVoiceProcessing"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/audio-unit-voice-i-o"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/audio-unit-voice-i-o"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
