{
  "abstract": [
    {
      "text": "Obtain information about the built-in mixers, equalizers, filters, effects, and other Audio Unit app extensions.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio Unit Properties"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389597-peak_limiter_unit_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Peak Limiter unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389597-peak_limiter_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Peak Limiter Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389597-peak_limiter_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389633-aunetsend-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389633-aunetsend-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNetSend Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389633-aunetsend-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389639-aurandom-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389639-aurandom-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AURandom Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389639-aurandom-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389643-aunewtimepitch-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389643-aunewtimepitch-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNewTimePitch Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389643-aunewtimepitch-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389727-aurogerbeep-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389727-aurogerbeep-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AURogerBeep Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389727-aurogerbeep-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389739-aumultichannelmixer_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Multichannel Mixer unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389739-aumultichannelmixer_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUMultiChannelMixer Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389739-aumultichannelmixer_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389745-aunbandeq-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389745-aunbandeq-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNBandEQ Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389745-aunbandeq-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389763-3d_mixer_unit_parameters": {
      "abstract": [
        {
          "text": "Parameters for the 3D Mixer unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389763-3d_mixer_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "3D Mixer Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389763-3d_mixer_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389769-ausampler-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389769-ausampler-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUSampler Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389769-ausampler-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389781-aumultibandcompressor-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389781-aumultibandcompressor-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUMultibandCompressor Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389781-aumultibandcompressor-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389787-dynamics_processor_unit_paramete": {
      "abstract": [
        {
          "text": "Parameters for the Dynamics Processor unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389787-dynamics_processor_unit_paramete",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dynamics Processor Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389787-dynamics_processor_unit_paramete"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389801-aumatrixreverb-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389801-aumatrixreverb-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUMatrixReverb Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389801-aumatrixreverb-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389808-auroundtripaacparam-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389808-auroundtripaacparam-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AURoundTripAACParam Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389808-auroundtripaacparam-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389891-net-status-audio-unit-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389891-net-status-audio-unit-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Net Status Audio Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389891-net-status-audio-unit-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389916-output_unit_parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389916-output_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Output Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389916-output_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389920-aunetreceive-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389920-aunetreceive-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNetReceive Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389920-aunetreceive-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389928-stereo-mixer-unit-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389928-stereo-mixer-unit-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Stereo Mixer Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389928-stereo-mixer-unit-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389932-audio-unit-graphic-eq-parameter": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389932-audio-unit-graphic-eq-parameter",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Graphic EQ Parameter ID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389932-audio-unit-graphic-eq-parameter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389946-autimepitch_autimepitch_offline": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389946-autimepitch_autimepitch_offline",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUTimePitch, AUTimePitch (offline), and AUPitch Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389946-autimepitch_autimepitch_offline"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389948-auhipass_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Highpass unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389948-auhipass_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUHipass Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389948-auhipass_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389950-parametric_eq_unit_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Parametric EQ unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389950-parametric_eq_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Parametric EQ Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389950-parametric_eq_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389965-aunbandeq_filter_types": {
      "abstract": [
        {
          "text": "Values for the filter type parameter of the Multitype EQ (NBandEQ) unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389965-aunbandeq_filter_types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNBandEQ Filter Types",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389965-aunbandeq_filter_types"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389967-auhighshelffilter_parameters": {
      "abstract": [
        {
          "text": "Parameters for the High Shelf Filter unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389967-auhighshelffilter_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUHighShelfFilter Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389967-auhighshelffilter_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389991-panner-audio-unit-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389991-panner-audio-unit-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Panner Audio Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389991-panner-audio-unit-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389995-aulowshelf_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Low Shelf Filter unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389995-aulowshelf_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AULowShelf Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389995-aulowshelf_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389999-aulowpass_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Lowpass unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389999-aulowpass_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AULowpass Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389999-aulowpass_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390003-aumatrixmixer-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390003-aumatrixmixer-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUMatrixMixer Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390003-aumatrixmixer-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390010-audelay-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390010-audelay-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUDelay Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390010-audelay-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390014-varispeed_unit_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Varispeed unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390014-varispeed_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Varispeed Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390014-varispeed_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390073-auspatialmixer-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390073-auspatialmixer-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUSpatialMixer Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390073-auspatialmixer-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390086-audistortion-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390086-audistortion-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUDistortion Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390086-audistortion-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390119-reverb_parameters": {
      "abstract": [
        {
          "text": "Additional reverb parameters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390119-reverb_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Reverb Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390119-reverb_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390144-bandpass_unit_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Bandpass unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390144-bandpass_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Bandpass Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390144-bandpass_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533959-ausampler-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533959-ausampler-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUSampler Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1533959-ausampler-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534022-aunbandeq-property-ids": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534022-aunbandeq-property-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNBandEQ Property IDs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534022-aunbandeq-property-ids"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534041-mixer_audio_unit_properties": {
      "abstract": [
        {
          "text": "Properties for Apple mixer audio units.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534041-mixer_audio_unit_properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mixer Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534041-mixer_audio_unit_properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534061-audeferredrenderer-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534061-audeferredrenderer-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUDeferredRenderer Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534061-audeferredrenderer-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534082-other-plug-in-formats": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534082-other-plug-in-formats",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Other Plug-In Formats",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534082-other-plug-in-formats"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534086-ausampler-property-ids": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534086-ausampler-property-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUSampler Property IDs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534086-ausampler-property-ids"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534092-frequency_response_constants": {
      "abstract": [
        {
          "text": "The maximum number of frequency response bin structures for the ",
          "type": "text"
        },
        {
          "code": "AudioUnitProperty_FrequencyResponse",
          "type": "codeVoice"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534092-frequency_response_constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Frequency Response Constants",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534092-frequency_response_constants"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534109-aunetreceive-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534109-aunetreceive-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNetReceive Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534109-aunetreceive-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534116-i_o_audio_unit_properties": {
      "abstract": [
        {
          "text": "Properties for Apple I/O audio units (sometimes called output units).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534116-i_o_audio_unit_properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "I/O Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534116-i_o_audio_unit_properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534150-spatial-mixer-property-ids": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534150-spatial-mixer-property-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Spatial Mixer Property IDs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534150-spatial-mixer-property-ids"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534177-renderquality": {
      "abstract": [
        {
          "text": "Render quality settings for audio units.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534177-renderquality",
      "kind": "article",
      "role": "collectionGroup",
      "title": "RenderQuality",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534177-renderquality"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534190-aumidisynth-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534190-aumidisynth-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUMIDISynth Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534190-aumidisynth-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534207-aunetsend-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534207-aunetsend-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNetSend Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534207-aunetsend-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534212-aunetsendpresetformat-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534212-aunetsendpresetformat-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNetSendPresetFormat Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534212-aunetsendpresetformat-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584146-audio-unit-mixer-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584146-audio-unit-mixer-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Mixer Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584146-audio-unit-mixer-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584150-mixer_audio_unit_subtypes": {
      "abstract": [
        {
          "text": "Audio mixing audio unit subtypes for audio units provided by Apple.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584150-mixer_audio_unit_subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mixer Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584150-mixer_audio_unit_subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584153-audio-unit-filter-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584153-audio-unit-filter-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Filter Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584153-audio-unit-filter-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584154-effect_audio_unit_subtypes": {
      "abstract": [
        {
          "text": "Effect (digital signal processing) audio unit subtypes for audio units provided by Apple.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584154-effect_audio_unit_subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Effect Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584154-effect_audio_unit_subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1585807-i_o_audio_unit_function_selector": {
      "abstract": [
        {
          "text": "Audio unit component selectors, specific to I/O audio units, that correspond to functions in the audio unit API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1585807-i_o_audio_unit_function_selector",
      "kind": "article",
      "role": "collectionGroup",
      "title": "I/O Audio Unit Function Selectors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1585807-i_o_audio_unit_function_selector"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1615024-reverb_unit_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Reverb unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1615024-reverb_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Reverb Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1615024-reverb_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621038-inter-app-audio-unit-property-ids": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621038-inter-app-audio-unit-property-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Inter-App Audio Unit Property IDs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1621038-inter-app-audio-unit-property-ids"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621039-inter-app-output-unit-property-ids": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621039-inter-app-output-unit-property-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Inter-App Output Unit Property IDs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1621039-inter-app-output-unit-property-ids"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3547050-ausampledelay-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3547050-ausampledelay-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUSampleDelay Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/3547050-ausampledelay-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AU3DMixerAttenuationCurve"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AU3DMixerAttenuationCurve"
        }
      ],
      "role": "symbol",
      "title": "AU3DMixerAttenuationCurve",
      "type": "topic",
      "url": "/documentation/audiotoolbox/au3dmixerattenuationcurve"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AU3DMixerRenderingFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AU3DMixerRenderingFlags"
        }
      ],
      "role": "symbol",
      "title": "AU3DMixerRenderingFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/au3dmixerrenderingflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUReverbRoomType"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUReverbRoomType"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerAttenuationCurve": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatialMixerAttenuationCurve"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerAttenuationCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatialMixerAttenuationCurve"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerAttenuationCurve",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixerattenuationcurve"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerOutputType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatialMixerOutputType"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerOutputType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatialMixerOutputType"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerOutputType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixeroutputtype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerPointSourceInHeadMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatialMixerPointSourceInHeadMode"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerPointSourceInHeadMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatialMixerPointSourceInHeadMode"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerPointSourceInHeadMode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixerpointsourceinheadmode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerRenderingFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatialMixerRenderingFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerRenderingFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatialMixerRenderingFlags"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerRenderingFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixerrenderingflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatialMixerSourceMode"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatialMixerSourceMode"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerSourceMode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixersourcemode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatializationAlgorithm"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatializationAlgorithm"
        }
      ],
      "role": "symbol",
      "title": "AUSpatializationAlgorithm",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatializationalgorithm"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitMIDICallbacks": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioOutputUnitMIDICallbacks"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitMIDICallbacks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioOutputUnitMIDICallbacks"
        }
      ],
      "role": "symbol",
      "title": "AudioOutputUnitMIDICallbacks",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiooutputunitmidicallbacks"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitStartAtTimeParams": {
      "abstract": [
        {
          "text": "A timestamp for scheduled starting of an I/O audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioOutputUnitStartAtTimeParams"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitStartAtTimeParams",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioOutputUnitStartAtTimeParams"
        }
      ],
      "role": "symbol",
      "title": "AudioOutputUnitStartAtTimeParams",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiooutputunitstartattimeparams"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo": {
      "abstract": [
        {
          "text": "The time- and transport-related callback functions for an audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HostCallbackInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HostCallbackInfo"
        }
      ],
      "role": "symbol",
      "title": "HostCallbackInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/hostcallbackinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MixerDistanceParams": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MixerDistanceParams"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MixerDistanceParams",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MixerDistanceParams"
        }
      ],
      "role": "symbol",
      "title": "MixerDistanceParams",
      "type": "topic",
      "url": "/documentation/audiotoolbox/mixerdistanceparams"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-components": {
      "abstract": [
        {
          "text": "Find, load, and configure audio components, such as Audio Units and audio codecs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-components",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Components",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-components"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api": {
      "abstract": [
        {
          "text": "Configure an Audio Unit and prepare it to render audio.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit v2 (C) API",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-v2-c-api"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v3-plug-ins": {
      "abstract": [
        {
          "text": "Deliver custom audio effects, instruments, and other audio behaviors using an Audio Unit v3 app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v3-plug-ins",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit v3 Plug-Ins",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-v3-plug-ins"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-voice-i-o": {
      "abstract": [
        {
          "text": "Configure system voice processing and respond to speech events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-voice-i-o",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Voice I/O",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-voice-i-o"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/general-audio-unit-properties": {
      "abstract": [
        {
          "text": "Properties that apply to any audio unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/general-audio-unit-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "General Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/general-audio-unit-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/generating-spatial-audio-from-a-multichannel-audio-stream": {
      "abstract": [
        {
          "text": "Convert 8-channel audio to 2-channel spatial audio by using a spatial mixer audio unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/generating-spatial-audio-from-a-multichannel-audio-stream",
      "kind": "article",
      "role": "sampleCode",
      "title": "Generating spatial audio from a multichannel audio stream",
      "type": "topic",
      "url": "/documentation/audiotoolbox/generating-spatial-audio-from-a-multichannel-audio-stream"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Audio-Units",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/generating-spatial-audio-from-a-multichannel-audio-stream",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v3-plug-ins",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-components",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-voice-i-o"
      ],
      "title": "Audio Units"
    }
  ],
  "topicSections": [
    {
      "anchor": "General",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534082-other-plug-in-formats",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534177-renderquality",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/general-audio-unit-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo"
      ],
      "title": "General"
    },
    {
      "anchor": "Mixers",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584146-audio-unit-mixer-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerAttenuationCurve",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerRenderingFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390073-auspatialmixer-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389991-panner-audio-unit-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390003-aumatrixmixer-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389739-aumultichannelmixer_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534150-spatial-mixer-property-ids",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389928-stereo-mixer-unit-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534041-mixer_audio_unit_properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584150-mixer_audio_unit_subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerOutputType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerPointSourceInHeadMode",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389763-3d_mixer_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MixerDistanceParams"
      ],
      "title": "Mixers"
    },
    {
      "anchor": "Equalizers",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389950-parametric_eq_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389932-audio-unit-graphic-eq-parameter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389597-peak_limiter_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389787-dynamics_processor_unit_paramete",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534092-frequency_response_constants",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm"
      ],
      "title": "Equalizers"
    },
    {
      "anchor": "Filters",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584153-audio-unit-filter-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390144-bandpass_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389948-auhipass_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389999-aulowpass_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389995-aulowshelf_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389967-auhighshelffilter_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389965-aunbandeq_filter_types",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534022-aunbandeq-property-ids",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389745-aunbandeq-parameters"
      ],
      "title": "Filters"
    },
    {
      "anchor": "Effects",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584154-effect_audio_unit_subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389801-aumatrixreverb-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390086-audistortion-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390119-reverb_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1615024-reverb_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390014-varispeed_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390010-audelay-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389781-aumultibandcompressor-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534061-audeferredrenderer-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3547050-ausampledelay-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389643-aunewtimepitch-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389946-autimepitch_autimepitch_offline"
      ],
      "title": "Effects"
    },
    {
      "anchor": "InputOutput",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534116-i_o_audio_unit_properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621039-inter-app-output-unit-property-ids",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621038-inter-app-audio-unit-property-ids",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389916-output_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534109-aunetreceive-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534207-aunetsend-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389633-aunetsend-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389920-aunetreceive-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534212-aunetsendpresetformat-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389891-net-status-audio-unit-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1585807-i_o_audio_unit_function_selector",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitMIDICallbacks",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitStartAtTimeParams"
      ],
      "title": "Input/Output"
    },
    {
      "anchor": "Generators",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389639-aurandom-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389769-ausampler-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534086-ausampler-property-ids",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533959-ausampler-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389727-aurogerbeep-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534190-aumidisynth-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389808-auroundtripaacparam-parameters"
      ],
      "title": "Generators"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "General",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534082-other-plug-in-formats",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534177-renderquality",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/general-audio-unit-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo"
              ],
              "title": "General"
            },
            {
              "anchor": "Mixers",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584146-audio-unit-mixer-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerAttenuationCurve",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerRenderingFlags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390073-auspatialmixer-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389991-panner-audio-unit-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390003-aumatrixmixer-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389739-aumultichannelmixer_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534150-spatial-mixer-property-ids",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389928-stereo-mixer-unit-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534041-mixer_audio_unit_properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584150-mixer_audio_unit_subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerOutputType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerPointSourceInHeadMode",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389763-3d_mixer_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MixerDistanceParams"
              ],
              "title": "Mixers"
            },
            {
              "anchor": "Equalizers",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389950-parametric_eq_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389932-audio-unit-graphic-eq-parameter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389597-peak_limiter_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389787-dynamics_processor_unit_paramete",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534092-frequency_response_constants",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm"
              ],
              "title": "Equalizers"
            },
            {
              "anchor": "Filters",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584153-audio-unit-filter-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390144-bandpass_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389948-auhipass_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389999-aulowpass_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389995-aulowshelf_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389967-auhighshelffilter_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389965-aunbandeq_filter_types",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534022-aunbandeq-property-ids",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389745-aunbandeq-parameters"
              ],
              "title": "Filters"
            },
            {
              "anchor": "Effects",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584154-effect_audio_unit_subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389801-aumatrixreverb-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390086-audistortion-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390119-reverb_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1615024-reverb_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390014-varispeed_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390010-audelay-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389781-aumultibandcompressor-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534061-audeferredrenderer-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3547050-ausampledelay-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389643-aunewtimepitch-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389946-autimepitch_autimepitch_offline"
              ],
              "title": "Effects"
            },
            {
              "anchor": "InputOutput",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534116-i_o_audio_unit_properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621039-inter-app-output-unit-property-ids",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1621038-inter-app-audio-unit-property-ids",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389916-output_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534109-aunetreceive-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534207-aunetsend-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389633-aunetsend-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389920-aunetreceive-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534212-aunetsendpresetformat-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389891-net-status-audio-unit-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1585807-i_o_audio_unit_function_selector",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitMIDICallbacks",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitStartAtTimeParams"
              ],
              "title": "Input/Output"
            },
            {
              "anchor": "Generators",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389639-aurandom-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389769-ausampler-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534086-ausampler-property-ids",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533959-ausampler-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389727-aurogerbeep-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534190-aumidisynth-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389808-auroundtripaacparam-parameters"
              ],
              "title": "Generators"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Audio-Units",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/generating-spatial-audio-from-a-multichannel-audio-stream",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v3-plug-ins",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-components",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-voice-i-o"
              ],
              "title": "Audio Units"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerSourceMode/title",
          "value": "AUSpatialMixerSourceMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerSourceMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerSourceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerSourceMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerSourceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallbackInfo/title",
          "value": "HostCallbackInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallbackInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HostCallbackInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallbackInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HostCallbackInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitMIDICallbacks/title",
          "value": "AudioOutputUnitMIDICallbacks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitMIDICallbacks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioOutputUnitMIDICallbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitMIDICallbacks/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioOutputUnitMIDICallbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerAttenuationCurve/title",
          "value": "AU3DMixerAttenuationCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerAttenuationCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AU3DMixerAttenuationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerAttenuationCurve/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AU3DMixerAttenuationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType/title",
          "value": "AUReverbRoomType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUReverbRoomType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUReverbRoomType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerRenderingFlags/title",
          "value": "AU3DMixerRenderingFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerRenderingFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AU3DMixerRenderingFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerRenderingFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AU3DMixerRenderingFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MixerDistanceParams/title",
          "value": "MixerDistanceParams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MixerDistanceParams/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MixerDistanceParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MixerDistanceParams/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MixerDistanceParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerOutputType/title",
          "value": "AUSpatialMixerOutputType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerOutputType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerOutputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerOutputType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerOutputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerAttenuationCurve/title",
          "value": "AUSpatialMixerAttenuationCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerAttenuationCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerAttenuationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerAttenuationCurve/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerAttenuationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm/title",
          "value": "AUSpatializationAlgorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatializationAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatializationAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerPointSourceInHeadMode/title",
          "value": "AUSpatialMixerPointSourceInHeadMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerPointSourceInHeadMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerPointSourceInHeadMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerPointSourceInHeadMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerPointSourceInHeadMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerRenderingFlags/title",
          "value": "AUSpatialMixerRenderingFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerRenderingFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerRenderingFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerRenderingFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerRenderingFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitStartAtTimeParams/title",
          "value": "AudioOutputUnitStartAtTimeParams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitStartAtTimeParams/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioOutputUnitStartAtTimeParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitStartAtTimeParams/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioOutputUnitStartAtTimeParams"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/audio-unit-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/audio-unit-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
