{
  "abstract": [
    {
      "text": "Flags set by the property listener callback and the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamParseBytes(_:_:_:_:)",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " function.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-stream-services"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-stream-flags"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio File Stream Flags"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1391506-audio-file-stream-properties": {
      "abstract": [
        {
          "text": "Audio file stream properties contain information that you can use to help interpret the audio data in a stream.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1391506-audio-file-stream-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio File Stream Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1391506-audio-file-stream-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamParseBytes(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Passes audio file stream data to the parser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileStreamParseBytes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamID",
          "text": "AudioFileStreamID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioFileStreamParseFlags",
          "text": "AudioFileStreamParseFlags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamParseBytes(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileStreamParseBytes"
        }
      ],
      "role": "symbol",
      "title": "AudioFileStreamParseBytes(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilestreamparsebytes(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamParseFlags/discontinuity": {
      "abstract": [
        {
          "text": "Pass this flag to the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamParseBytes(_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function to signal a discontinuity in the audio data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "discontinuity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioFileStreamParseFlags",
          "text": "AudioFileStreamParseFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamParseFlags/discontinuity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamParseFlag_Discontinuity"
        }
      ],
      "role": "symbol",
      "title": "discontinuity",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilestreamparseflags/discontinuity"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamPropertyFlags/cacheProperty": {
      "abstract": [
        {
          "text": "A property listener sets this flag to instruct the parser to cache the property value so that it remains available after the callback returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cacheProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioFileStreamPropertyFlags",
          "text": "AudioFileStreamPropertyFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamPropertyFlags/cacheProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamPropertyFlag_CacheProperty"
        }
      ],
      "role": "symbol",
      "title": "cacheProperty",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilestreampropertyflags/cacheproperty"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamPropertyFlags/propertyIsCached": {
      "abstract": [
        {
          "text": "This flag is set when the callback ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStream_PropertyListenerProc",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is invoked in the case that the value of the property has been cached and can be obtained later.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "propertyIsCached"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioFileStreamPropertyFlags",
          "text": "AudioFileStreamPropertyFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamPropertyFlags/propertyIsCached",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamPropertyFlag_PropertyIsCached"
        }
      ],
      "role": "symbol",
      "title": "propertyIsCached",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilestreampropertyflags/propertyiscached"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamSeek(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Provides a byte offset for a specified packet in the data stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileStreamSeek"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamID",
          "text": "AudioFileStreamID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioFileStreamSeekFlags",
          "text": "AudioFileStreamSeekFlags"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamSeek(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileStreamSeek"
        }
      ],
      "role": "symbol",
      "title": "AudioFileStreamSeek(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilestreamseek(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamSeekFlags/offsetIsEstimated": {
      "abstract": [
        {
          "text": "This flag is returned by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamSeek(_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function if the byte offset is only an estimate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offsetIsEstimated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioFileStreamSeekFlags",
          "text": "AudioFileStreamSeekFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamSeekFlags/offsetIsEstimated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamSeekFlag_OffsetIsEstimated"
        }
      ],
      "role": "symbol",
      "title": "offsetIsEstimated",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilestreamseekflags/offsetisestimated"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStream_PropertyListenerProc": {
      "abstract": [
        {
          "text": "Invoked by an audio file stream parser when it finds a property value in the audio file stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileStream_PropertyListenerProc"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStream_PropertyListenerProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileStream_PropertyListenerProc"
        }
      ],
      "role": "symbol",
      "title": "AudioFileStream_PropertyListenerProc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilestream_propertylistenerproc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-stream-services": {
      "abstract": [
        {
          "text": "Parse streamed audio files as the data arrives on the user’s computer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-stream-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio File Stream Services",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-file-stream-services"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1391506-audio-file-stream-properties"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamPropertyFlags/propertyIsCached",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamPropertyFlags/cacheProperty",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamParseFlags/discontinuity",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamSeekFlags/offsetIsEstimated"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamPropertyFlags/propertyIsCached",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamPropertyFlags/cacheProperty",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamParseFlags/discontinuity",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamSeekFlags/offsetIsEstimated"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1391506-audio-file-stream-properties"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileStream_PropertyListenerProc/title",
          "value": "AudioFileStream_PropertyListenerProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileStream_PropertyListenerProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileStream_PropertyListenerProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileStream_PropertyListenerProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileStream_PropertyListenerProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileStreamPropertyFlags~1propertyIsCached/title",
          "value": "kAudioFileStreamPropertyFlag_PropertyIsCached"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileStreamPropertyFlags~1propertyIsCached/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamPropertyFlag_PropertyIsCached"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileStreamPropertyFlags~1cacheProperty/title",
          "value": "kAudioFileStreamPropertyFlag_CacheProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileStreamPropertyFlags~1cacheProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamPropertyFlag_CacheProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileStreamParseFlags~1discontinuity/title",
          "value": "kAudioFileStreamParseFlag_Discontinuity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileStreamParseFlags~1discontinuity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamParseFlag_Discontinuity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileStreamSeekFlags~1offsetIsEstimated/title",
          "value": "kAudioFileStreamSeekFlag_OffsetIsEstimated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileStreamSeekFlags~1offsetIsEstimated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamSeekFlag_OffsetIsEstimated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileStreamParseBytes(_:_:_:_:)/title",
          "value": "AudioFileStreamParseBytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileStreamParseBytes(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileStreamParseBytes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileStreamSeek(_:_:_:_:)/title",
          "value": "AudioFileStreamSeek"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileStreamSeek(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileStreamSeek"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/audio-file-stream-flags"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/audio-file-stream-flags"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
