{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioPanningInfo","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.audiotoolbox/documentation/AudioToolbox"]]},"topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo/init(mPanningMode:mCoordinateFlags:mCoordinates:mGainScale:mOutputChannelMap:)"],"anchor":"Initializers"},{"generated":true,"title":"Instance Properties","identifiers":["doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo/mCoordinateFlags","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo/mCoordinates","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo/mGainScale","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo/mOutputChannelMap","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo/mPanningMode"],"anchor":"Instance-Properties"}],"identifier":{"url":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"seeAlsoSections":[{"generated":true,"title":"Data Types","identifiers":["doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBalanceFade","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatInfo","doc://com.apple.documentation/documentation/CoreAudioTypes/AudioFormatListItem","doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatPropertyID"],"anchor":"Data-Types"}],"abstract":[{"type":"text","text":"Audio panning information."}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"],"kind":"relationships","type":"conformsTo"}],"metadata":{"role":"symbol","symbolKind":"struct","roleHeading":"Structure","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioPanningInfo","kind":"identifier"}],"navigatorTitle":[{"text":"AudioPanningInfo","kind":"identifier"}],"modules":[{"name":"Audio Toolbox"}],"externalID":"c:@S@AudioPanningInfo","title":"AudioPanningInfo","platforms":[{"deprecated":false,"beta":false,"unavailable":false,"name":"iOS"},{"deprecated":false,"beta":false,"unavailable":false,"name":"iPadOS"},{"deprecated":false,"beta":false,"unavailable":false,"name":"Mac Catalyst"},{"deprecated":false,"beta":false,"unavailable":false,"name":"macOS"},{"deprecated":false,"beta":false,"unavailable":false,"name":"tvOS"},{"deprecated":false,"beta":false,"unavailable":false,"name":"visionOS"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/audiotoolbox/audiopanninginfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/audiotoolbox/audiopanninginfo"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo/mGainScale":{"title":"mGainScale","abstract":[{"text":"A multiplier for audio panning values, typically representing a volume value in the range from 0 to 1. A value of 1 results in audio panning at unity gain. A value of 0 silences all channels.","type":"text"}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo/mGainScale","url":"/documentation/audiotoolbox/audiopanninginfo/mgainscale","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"mGainScale"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mGainScale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float32","preciseIdentifier":"s:s7Float32a"}]},"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP":{"abstract":[{"type":"text","text":""}],"url":"/documentation/Swift/BitwiseCopyable","kind":"symbol","title":"BitwiseCopyable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BitwiseCopyable"},{"kind":"text","text":" : ~Escapable"}],"identifier":"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","type":"topic","role":"symbol"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo":{"url":"/documentation/audiotoolbox/extendedaudioformatinfo","title":"ExtendedAudioFormatInfo","abstract":[{"text":"A specifier for the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FormatList","type":"reference"},{"text":" property, including the codec to use.","type":"text"}],"type":"topic","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ExtendedAudioFormatInfo"}],"navigatorTitle":[{"kind":"identifier","text":"ExtendedAudioFormatInfo"}],"role":"symbol"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox":{"type":"topic","kind":"symbol","title":"Audio Toolbox","role":"collection","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox","abstract":[{"text":"Record or play audio, convert formats, parse audio streams, and configure your audio session.","type":"text"}],"url":"/documentation/audiotoolbox"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo/init(mPanningMode:mCoordinateFlags:mCoordinates:mGainScale:mOutputChannelMap:)":{"abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"mPanningMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@AudioPanningMode","kind":"typeIdentifier","text":"AudioPanningMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mCoordinateFlags"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier","text":"UInt32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mCoordinates"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:s7Float32a","kind":"typeIdentifier","text":"Float32"},{"kind":"text","text":", "},{"text":"Float32","kind":"typeIdentifier","preciseIdentifier":"s:s7Float32a"},{"text":", ","kind":"text"},{"text":"Float32","kind":"typeIdentifier","preciseIdentifier":"s:s7Float32a"},{"text":"), ","kind":"text"},{"text":"mGainScale","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float32","kind":"typeIdentifier","preciseIdentifier":"s:s7Float32a"},{"text":", ","kind":"text"},{"text":"mOutputChannelMap","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"AudioChannelLayout","kind":"typeIdentifier","preciseIdentifier":"c:@S@AudioChannelLayout"},{"text":">)","kind":"text"}],"role":"symbol","title":"init(mPanningMode:mCoordinateFlags:mCoordinates:mGainScale:mOutputChannelMap:)","type":"topic","kind":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo/init(mPanningMode:mCoordinateFlags:mCoordinates:mGainScale:mOutputChannelMap:)","url":"/documentation/audiotoolbox/audiopanninginfo/init(mpanningmode:mcoordinateflags:mcoordinates:mgainscale:moutputchannelmap:)"},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","type":"topic","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","role":"overview"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatPropertyID":{"kind":"symbol","type":"topic","title":"AudioFormatPropertyID","url":"/documentation/audiotoolbox/audioformatpropertyid","abstract":[{"type":"text","text":"A type for four-char codes for audio format property identifiers."}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatPropertyID","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"AudioFormatPropertyID","kind":"identifier"}],"navigatorTitle":[{"text":"AudioFormatPropertyID","kind":"identifier"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FormatList":{"url":"/documentation/audiotoolbox/kaudioformatproperty_formatlist","title":"kAudioFormatProperty_FormatList","abstract":[{"type":"text","text":"A list of structures describing the audio formats."}],"type":"topic","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FormatList","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioFormatProperty_FormatList"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@AudioFormatPropertyID","kind":"typeIdentifier","text":"AudioFormatPropertyID"}],"navigatorTitle":[{"kind":"identifier","text":"kAudioFormatProperty_FormatList"}],"role":"symbol"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo/mCoordinateFlags":{"role":"symbol","type":"topic","url":"/documentation/audiotoolbox/audiopanninginfo/mcoordinateflags","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mCoordinateFlags"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo/mCoordinateFlags","kind":"symbol","abstract":[{"text":"For the available coordinate flags, see Channel Coordinate Flags.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"mCoordinateFlags"}],"title":"mCoordinateFlags"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBalanceFade":{"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBalanceFade","url":"/documentation/audiotoolbox/audiobalancefade","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioBalanceFade"}],"title":"AudioBalanceFade","type":"topic","kind":"symbol","abstract":[{"text":"Describes audio left/right balance and front/back fade values.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"AudioBalanceFade"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo/mCoordinates":{"role":"symbol","type":"topic","url":"/documentation/audiotoolbox/audiopanninginfo/mcoordinates","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mCoordinates"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Float32","preciseIdentifier":"s:s7Float32a"},{"kind":"text","text":", "},{"preciseIdentifier":"s:s7Float32a","text":"Float32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s7Float32a","text":"Float32","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo/mCoordinates","kind":"symbol","abstract":[{"text":"For the available coordinate index constants, see Channel Coordinate Index Constants.","type":"text"}],"navigatorTitle":[{"text":"mCoordinates","kind":"identifier"}],"title":"mCoordinates"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioPanningInfo"}],"navigatorTitle":[{"kind":"identifier","text":"AudioPanningInfo"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo","url":"/documentation/audiotoolbox/audiopanninginfo","abstract":[{"text":"Audio panning information.","type":"text"}],"title":"AudioPanningInfo"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo/mPanningMode":{"navigatorTitle":[{"text":"mPanningMode","kind":"identifier"}],"abstract":[{"type":"text","text":"The mode to use for panning."}],"role":"symbol","type":"topic","title":"mPanningMode","kind":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo/mPanningMode","url":"/documentation/audiotoolbox/audiopanninginfo/mpanningmode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mPanningMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioPanningMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@AudioPanningMode"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatInfo":{"title":"AudioFormatInfo","abstract":[{"text":"A structure that specifies an audio format.","type":"text"}],"navigatorTitle":[{"text":"AudioFormatInfo","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"AudioFormatInfo","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatInfo","kind":"symbol","role":"symbol","url":"/documentation/audiotoolbox/audioformatinfo"},"doc://com.apple.documentation/documentation/CoreAudioTypes/AudioFormatListItem":{"title":"AudioFormatListItem","abstract":[{"type":"text","text":""}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioFormatListItem"}],"type":"topic","identifier":"doc://com.apple.documentation/documentation/CoreAudioTypes/AudioFormatListItem","kind":"symbol","role":"symbol","url":"/documentation/CoreAudioTypes/AudioFormatListItem"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo/mOutputChannelMap":{"navigatorTitle":[{"text":"mOutputChannelMap","kind":"identifier"}],"abstract":[{"type":"text","text":"The channel map used to determine channel volumes for the audio panning."}],"role":"symbol","type":"topic","title":"mOutputChannelMap","kind":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo/mOutputChannelMap","url":"/documentation/audiotoolbox/audiopanninginfo/moutputchannelmap","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mOutputChannelMap"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"AudioChannelLayout","preciseIdentifier":"c:@S@AudioChannelLayout"},{"text":">","kind":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"beta":false,"unavailable":false,"name":"iOS"},{"deprecated":false,"beta":false,"unavailable":false,"name":"iPadOS"},{"beta":false,"name":"Mac Catalyst","unavailable":false,"deprecated":false},{"beta":false,"name":"macOS","unavailable":false,"deprecated":false},{"beta":false,"name":"tvOS","unavailable":false,"deprecated":false},{"beta":false,"name":"visionOS","unavailable":false,"deprecated":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Structure","path":"/metadata/roleHeading"},{"op":"replace","value":"AudioPanningInfo","path":"/metadata/title"},{"op":"replace","value":"struct","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"AudioPanningInfo"}],"path":"/metadata/fragments"},{"op":"replace","value":[{"text":"AudioPanningInfo","kind":"identifier"}],"path":"/metadata/navigatorTitle"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.audiotoolbox/documentation/AudioToolbox"]]},"op":"replace","path":"/hierarchy"},{"value":[{"identifiers":["doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo/mCoordinateFlags","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo/mCoordinates","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo/mGainScale","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo/mOutputChannelMap","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo/mPanningMode"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true}],"op":"replace","path":"/topicSections"},{"value":null,"op":"replace","path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBalanceFade","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatInfo","doc://com.apple.documentation/documentation/CoreAudioTypes/AudioFormatListItem","doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatPropertyID"],"generated":true,"title":"Data Types","anchor":"Data-Types"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioPanningInfo","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"/primaryContentSections/0"},{"value":"mGainScale","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningInfo~1mGainScale/title","op":"replace"},{"value":[{"kind":"identifier","text":"mGainScale"}],"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningInfo~1mGainScale/fragments","op":"replace"},{"value":"ExtendedAudioFormatInfo","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtendedAudioFormatInfo/title","op":"replace"},{"value":[{"kind":"identifier","text":"ExtendedAudioFormatInfo"}],"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtendedAudioFormatInfo/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ExtendedAudioFormatInfo"}],"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtendedAudioFormatInfo/navigatorTitle","op":"replace"},{"value":"AudioFormatPropertyID","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatPropertyID/title","op":"replace"},{"value":[{"kind":"identifier","text":"AudioFormatPropertyID"}],"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatPropertyID/fragments","op":"replace"},{"value":[{"text":"AudioFormatPropertyID","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatPropertyID/navigatorTitle","op":"replace"},{"value":"kAudioFormatProperty_FormatList","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_FormatList/title","op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_FormatList/fragments","op":"replace","value":[{"kind":"identifier","text":"kAudioFormatProperty_FormatList"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningInfo~1mCoordinateFlags/title","op":"replace","value":"mCoordinateFlags"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningInfo~1mCoordinateFlags/fragments","op":"replace","value":[{"text":"mCoordinateFlags","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioBalanceFade/title","op":"replace","value":"AudioBalanceFade"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioBalanceFade/fragments","op":"replace","value":[{"text":"AudioBalanceFade","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioBalanceFade/navigatorTitle","op":"replace","value":[{"text":"AudioBalanceFade","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningInfo~1mCoordinates/title","op":"replace","value":"mCoordinates"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningInfo~1mCoordinates/fragments","op":"replace","value":[{"text":"mCoordinates","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningInfo/title","op":"replace","value":"AudioPanningInfo"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningInfo/fragments","op":"replace","value":[{"text":"AudioPanningInfo","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningInfo/navigatorTitle","op":"replace","value":[{"text":"AudioPanningInfo","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningInfo~1mPanningMode/title","op":"replace","value":"mPanningMode"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningInfo~1mPanningMode/fragments","op":"replace","value":[{"text":"mPanningMode","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatInfo/title","op":"replace","value":"AudioFormatInfo"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatInfo/fragments","op":"replace","value":[{"text":"AudioFormatInfo","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatInfo/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AudioFormatInfo"}]},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1CoreAudioTypes~1AudioFormatListItem/fragments","op":"replace","value":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioFormatListItem"},{"kind":"text","text":";"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningInfo~1mOutputChannelMap/title","op":"replace","value":"mOutputChannelMap"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningInfo~1mOutputChannelMap/fragments","op":"replace","value":[{"text":"mOutputChannelMap","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}