{
  "abstract": [
    {
      "text": "Gets information about an audio format property.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatGetPropertyInfo(_:_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@AudioFormatGetPropertyInfo",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AudioFormatGetPropertyInfo"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioFormatPropertyID",
        "text": "AudioFormatPropertyID"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SV",
        "text": "UnsafeRawPointer"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      },
      {
        "kind": "text",
        "text": ">) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AudioFormatGetPropertyInfo"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "AudioFormatGetPropertyInfo(_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioFormatGetPropertyInfo"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inPropertyID"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatPropertyID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioFormatPropertyID",
              "text": "AudioFormatPropertyID"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inSpecifierSize"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inSpecifier"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SV",
              "text": "UnsafeRawPointer"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "outPropertyDataSize"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": ">) -> "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An ",
                  "type": "text"
                },
                {
                  "code": "AudioFormatPropertyID",
                  "type": "codeVoice"
                },
                {
                  "text": " constant.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inPropertyID"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The size of the specifier data.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inSpecifierSize"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A buffer of data used as an input argument for querying some of the properties.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inSpecifier"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The the size in bytes of the current value of the property. To get the property value, you need a buffer of this size.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "outPropertyDataSize"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code. Returns ",
              "type": "text"
            },
            {
              "code": "noErr",
              "type": "codeVoice"
            },
            {
              "text": " if successful.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatGetProperty(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Gets the value of an audio format property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFormatGetProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatPropertyID",
          "text": "AudioFormatPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatGetProperty(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFormatGetProperty"
        }
      ],
      "role": "symbol",
      "title": "AudioFormatGetProperty(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioformatgetproperty(_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatGetPropertyInfo(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Gets information about an audio format property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFormatGetPropertyInfo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatPropertyID",
          "text": "AudioFormatPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatGetPropertyInfo(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFormatGetPropertyInfo"
        }
      ],
      "role": "symbol",
      "title": "AudioFormatGetPropertyInfo(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioformatgetpropertyinfo(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatPropertyID": {
      "abstract": [
        {
          "text": "A type for four-char codes for audio format property identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFormatPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatPropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFormatPropertyID"
        }
      ],
      "role": "symbol",
      "title": "AudioFormatPropertyID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioformatpropertyid"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SV": {
      "abstract": [
        {
          "text": "A raw pointer for accessing untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeRawPointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SV",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeRawPointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeRawPointer"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Audio-Format-Services-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatGetProperty(_:_:_:_:_:)"
      ],
      "title": "Audio Format Services Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AudioFormatGetPropertyInfo"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatGetPropertyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Audio-Format-Services-Functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatGetProperty(_:_:_:_:_:)"
              ],
              "title": "Audio Format Services Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OSStatus",
                    "text": "OSStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AudioFormatGetPropertyInfo"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatPropertyID",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AudioFormatPropertyID",
                    "text": "AudioFormatPropertyID"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inPropertyID"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@UInt32",
                    "text": "UInt32"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inSpecifierSize"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inSpecifier"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@UInt32",
                    "text": "UInt32"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "outPropertyDataSize"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An ",
                        "type": "text"
                      },
                      {
                        "code": "AudioFormatPropertyID",
                        "type": "codeVoice"
                      },
                      {
                        "text": " constant.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inPropertyID"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The size of the specifier data.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inSpecifierSize"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A buffer of data used as an input argument for querying some of the properties.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inSpecifier"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The the size in bytes of the current value of the property. To get the property value, you need a buffer of this size.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "outPropertyDataSize"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A result code. Returns ",
                    "type": "text"
                  },
                  {
                    "code": "noErr",
                    "type": "codeVoice"
                  },
                  {
                    "text": " if successful.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatGetPropertyInfo(_:_:_:_:)/title",
          "value": "AudioFormatGetPropertyInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatGetPropertyInfo(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatGetPropertyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatGetProperty(_:_:_:_:_:)/title",
          "value": "AudioFormatGetProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatGetProperty(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatGetProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatPropertyID/title",
          "value": "AudioFormatPropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatPropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatPropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatPropertyID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/audioformatgetpropertyinfo(_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/audioformatgetpropertyinfo(_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
