{
  "abstract": [
    {
      "text": "Sets the value of a specified audio session property.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Deprecated in iOS 7.0.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionSetProperty(_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@AudioSessionSetProperty",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AudioSessionSetProperty"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioSessionPropertyID",
        "text": "AudioSessionPropertyID"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SV",
        "text": "UnsafeRawPointer"
      },
      {
        "kind": "text",
        "text": "!) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AudioSessionSetProperty"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "14.0",
        "message": "no longer supported",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "no longer supported",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "AudioSessionSetProperty(_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioSessionSetProperty"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inID"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionPropertyID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioSessionPropertyID",
              "text": "AudioSessionPropertyID"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inDataSize"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inData"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SV",
              "text": "UnsafeRawPointer"
            },
            {
              "kind": "text",
              "text": "!) -> "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The identifier for the audio session property that you want to set the value of.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inID"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The size, in bytes, of the value in the ",
                  "type": "text"
                },
                {
                  "code": "inData",
                  "type": "codeVoice"
                },
                {
                  "text": " parameter.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inDataSize"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The value that you are applying to the specified audio session property.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inData"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code. See Result Codes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Audio session properties are listed and described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618455-audio-session-property-identifie",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618455-audio-session-property-identifie": {
      "abstract": [
        {
          "text": "Property identifiers used with Audio Session Services in iOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618455-audio-session-property-identifie",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Session Property Identifiers",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1618455-audio-session-property-identifie"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentGetIcon(_:_:)": {
      "abstract": [
        {
          "text": "The UIImage of the audio component’s icon.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioComponentGetIcon"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioComponent",
          "text": "AudioComponent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentGetIcon(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioComponentGetIcon"
        }
      ],
      "role": "symbol",
      "title": "AudioComponentGetIcon(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocomponentgeticon(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentGetLastActiveTime(_:)": {
      "abstract": [
        {
          "text": "The time at which the application publishing the component was last active.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioComponentGetLastActiveTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioComponent",
          "text": "AudioComponent"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAbsoluteTime",
          "text": "CFAbsoluteTime"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentGetLastActiveTime(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioComponentGetLastActiveTime"
        }
      ],
      "role": "symbol",
      "title": "AudioComponentGetLastActiveTime(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocomponentgetlastactivetime(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentCreate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioFileComponentCreate"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentCreate",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioFileComponentCreate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilecomponentcreate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentDataIsThisFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioFileComponentDataIsThisFormat"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentDataIsThisFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioFileComponentDataIsThisFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilecomponentdataisthisformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentFileIsThisFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioFileComponentFileIsThisFormat"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentFileIsThisFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioFileComponentFileIsThisFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilecomponentfileisthisformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentInitialize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioFileComponentInitialize"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentInitialize",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioFileComponentInitialize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilecomponentinitialize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileCreate": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioFileCreate"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileCreate",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioFileCreate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilecreate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileInitialize": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioFileInitialize"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileInitialize",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioFileInitialize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofileinitialize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileOpen": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioFileOpen"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileOpen",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioFileOpen",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofileopen"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileReadPackets(_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Reads a fixed duration of audio data from an audio file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileReadPackets"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileID",
          "text": "AudioFileID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioStreamPacketDescription",
          "text": "AudioStreamPacketDescription"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileReadPackets(_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileReadPackets"
        }
      ],
      "role": "symbol",
      "title": "AudioFileReadPackets(_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilereadpackets(_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioHardwareServiceAddPropertyListener(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Registers a HAL audio object property listener callback function to be invoked when a specified property changes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwareServiceAddPropertyListener"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioObjectPropertyAddress",
          "text": "AudioObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertyListenerProc",
          "text": "AudioObjectPropertyListenerProc"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioHardwareServiceAddPropertyListener(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwareServiceAddPropertyListener"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwareServiceAddPropertyListener(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiohardwareserviceaddpropertylistener(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioHardwareServiceGetPropertyData(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Gets the value for a specified property.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwareServiceGetPropertyData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioObjectPropertyAddress",
          "text": "AudioObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioHardwareServiceGetPropertyData(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwareServiceGetPropertyData"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwareServiceGetPropertyData(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiohardwareservicegetpropertydata(_:_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioHardwareServiceGetPropertyDataSize(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Gets the payload size for a given property.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwareServiceGetPropertyDataSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioObjectPropertyAddress",
          "text": "AudioObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioHardwareServiceGetPropertyDataSize(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwareServiceGetPropertyDataSize"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwareServiceGetPropertyDataSize(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiohardwareservicegetpropertydatasize(_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioHardwareServiceHasProperty(_:_:)": {
      "abstract": [
        {
          "text": "Queries a HAL audio object about whether or not it has a specified property.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwareServiceHasProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioObjectPropertyAddress",
          "text": "AudioObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioHardwareServiceHasProperty(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwareServiceHasProperty"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwareServiceHasProperty(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiohardwareservicehasproperty(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioHardwareServiceIsPropertySettable(_:_:_:)": {
      "abstract": [
        {
          "text": "Queries a HAL audio object about whether a specified property is settable.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwareServiceIsPropertySettable"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioObjectPropertyAddress",
          "text": "AudioObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Darwin0A7BooleanV",
          "text": "DarwinBoolean"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioHardwareServiceIsPropertySettable(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwareServiceIsPropertySettable"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwareServiceIsPropertySettable(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiohardwareserviceispropertysettable(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioHardwareServiceRemovePropertyListener(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Unregisters a HAL audio object property listener callback function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwareServiceRemovePropertyListener"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioObjectPropertyAddress",
          "text": "AudioObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertyListenerProc",
          "text": "AudioObjectPropertyListenerProc"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioHardwareServiceRemovePropertyListener(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwareServiceRemovePropertyListener"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwareServiceRemovePropertyListener(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiohardwareserviceremovepropertylistener(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioHardwareServiceSetPropertyData(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Asks a HAL audio object to change the value of a specified property.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwareServiceSetPropertyData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioObjectPropertyAddress",
          "text": "AudioObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioHardwareServiceSetPropertyData(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwareServiceSetPropertyData"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwareServiceSetPropertyData(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiohardwareservicesetpropertydata(_:_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitGetHostIcon(_:_:)": {
      "abstract": [
        {
          "text": "The host app’s icon.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioOutputUnitGetHostIcon"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnit",
          "text": "AudioUnit"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitGetHostIcon(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioOutputUnitGetHostIcon"
        }
      ],
      "role": "symbol",
      "title": "AudioOutputUnitGetHostIcon(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiooutputunitgethosticon(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitPublish(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Registers an audio output unit for use by other applications.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioOutputUnitPublish"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioComponentDescription",
          "text": "AudioComponentDescription"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnit",
          "text": "AudioUnit"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitPublish(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioOutputUnitPublish"
        }
      ],
      "role": "symbol",
      "title": "AudioOutputUnitPublish(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiooutputunitpublish(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionAddPropertyListener(_:_:_:)": {
      "abstract": [
        {
          "text": "Adds a property listener callback function to your application’s audio session object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioSessionAddPropertyListener"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioSessionPropertyID",
          "text": "AudioSessionPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioSessionPropertyListener",
          "text": "AudioSessionPropertyListener"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionAddPropertyListener(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioSessionAddPropertyListener"
        }
      ],
      "role": "symbol",
      "title": "AudioSessionAddPropertyListener(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiosessionaddpropertylistener(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionGetProperty(_:_:_:)": {
      "abstract": [
        {
          "text": "Gets the value of a specified audio session property.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioSessionGetProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioSessionPropertyID",
          "text": "AudioSessionPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionGetProperty(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioSessionGetProperty"
        }
      ],
      "role": "symbol",
      "title": "AudioSessionGetProperty(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiosessiongetproperty(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionGetPropertySize(_:_:)": {
      "abstract": [
        {
          "text": "Gets the size of the value for a specified audio session property.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioSessionGetPropertySize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioSessionPropertyID",
          "text": "AudioSessionPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionGetPropertySize(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioSessionGetPropertySize"
        }
      ],
      "role": "symbol",
      "title": "AudioSessionGetPropertySize(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiosessiongetpropertysize(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionPropertyID": {
      "abstract": [
        {
          "text": "The data type for an audio session property identifier.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioSessionPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionPropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioSessionPropertyID"
        }
      ],
      "role": "symbol",
      "title": "AudioSessionPropertyID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiosessionpropertyid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionSetProperty(_:_:_:)": {
      "abstract": [
        {
          "text": "Sets the value of a specified audio session property.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioSessionSetProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioSessionPropertyID",
          "text": "AudioSessionPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionSetProperty(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioSessionSetProperty"
        }
      ],
      "role": "symbol",
      "title": "AudioSessionSetProperty(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiosessionsetproperty(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceLoadSMFDataWithFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MusicSequenceLoadSMFDataWithFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceLoadSMFDataWithFlags",
      "kind": "symbol",
      "role": "symbol",
      "title": "MusicSequenceLoadSMFDataWithFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequenceloadsmfdatawithflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceLoadSMFWithFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MusicSequenceLoadSMFWithFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceLoadSMFWithFlags",
      "kind": "symbol",
      "role": "symbol",
      "title": "MusicSequenceLoadSMFWithFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequenceloadsmfwithflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceSaveMIDIFile": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MusicSequenceSaveMIDIFile"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceSaveMIDIFile",
      "kind": "symbol",
      "role": "symbol",
      "title": "MusicSequenceSaveMIDIFile",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencesavemidifile"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceSaveSMFData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MusicSequenceSaveSMFData"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceSaveSMFData",
      "kind": "symbol",
      "role": "symbol",
      "title": "MusicSequenceSaveSMFData",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencesavesmfdata"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewExtendedControlEvent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MusicTrackNewExtendedControlEvent"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewExtendedControlEvent",
      "kind": "symbol",
      "role": "symbol",
      "title": "MusicTrackNewExtendedControlEvent",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musictracknewextendedcontrolevent"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SV": {
      "abstract": [
        {
          "text": "A raw pointer for accessing untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeRawPointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SV",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeRawPointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeRawPointer"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionGetProperty(_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionGetPropertySize(_:_:)"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileReadPackets(_:_:_:_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentGetIcon(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentGetLastActiveTime(_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioHardwareServiceAddPropertyListener(_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioHardwareServiceGetPropertyData(_:_:_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioHardwareServiceGetPropertyDataSize(_:_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioHardwareServiceHasProperty(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioHardwareServiceIsPropertySettable(_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioHardwareServiceRemovePropertyListener(_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioHardwareServiceSetPropertyData(_:_:_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitGetHostIcon(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioOutputUnitPublish(_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionAddPropertyListener(_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionGetProperty(_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionGetPropertySize(_:_:)"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "7.0",
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "7.0",
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AudioSessionSetProperty"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioSessionSetProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionGetProperty(_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionGetPropertySize(_:_:)"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileCreate",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileInitialize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileOpen",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileReadPackets(_:_:_:_:_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceLoadSMFDataWithFlags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceLoadSMFWithFlags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceSaveMIDIFile",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceSaveSMFData",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewExtendedControlEvent",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentGetIcon(_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentGetLastActiveTime(_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentCreate",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentDataIsThisFormat",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentFileIsThisFormat",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentInitialize"
              ],
              "title": "Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OSStatus",
                    "text": "OSStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AudioSessionSetProperty"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionPropertyID",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AudioSessionPropertyID",
                    "text": "AudioSessionPropertyID"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inID"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@UInt32",
                    "text": "UInt32"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inDataSize"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inData"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The identifier for the audio session property that you want to set the value of.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inID"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The size, in bytes, of the value in the ",
                        "type": "text"
                      },
                      {
                        "code": "inData",
                        "type": "codeVoice"
                      },
                      {
                        "text": " parameter.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inDataSize"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The value that you are applying to the specified audio session property.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inData"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A result code. See Result Codes.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Deprecated in iOS 7.0.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionPropertyID/title",
          "value": "AudioSessionPropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionPropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioSessionPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionPropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioSessionPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionGetProperty(_:_:_:)/title",
          "value": "AudioSessionGetProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionGetProperty(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioSessionGetProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioHardwareServiceSetPropertyData(_:_:_:_:_:_:)/title",
          "value": "AudioHardwareServiceSetPropertyData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioHardwareServiceSetPropertyData(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwareServiceSetPropertyData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitGetHostIcon(_:_:)/title",
          "value": "AudioOutputUnitGetHostIcon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitGetHostIcon(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioOutputUnitGetHostIcon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionAddPropertyListener(_:_:_:)/title",
          "value": "AudioSessionAddPropertyListener"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionAddPropertyListener(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioSessionAddPropertyListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioHardwareServiceAddPropertyListener(_:_:_:_:)/title",
          "value": "AudioHardwareServiceAddPropertyListener"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioHardwareServiceAddPropertyListener(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwareServiceAddPropertyListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioHardwareServiceGetPropertyDataSize(_:_:_:_:_:)/title",
          "value": "AudioHardwareServiceGetPropertyDataSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioHardwareServiceGetPropertyDataSize(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwareServiceGetPropertyDataSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioHardwareServiceRemovePropertyListener(_:_:_:_:)/title",
          "value": "AudioHardwareServiceRemovePropertyListener"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioHardwareServiceRemovePropertyListener(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwareServiceRemovePropertyListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionSetProperty(_:_:_:)/title",
          "value": "AudioSessionSetProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionSetProperty(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioSessionSetProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentGetLastActiveTime(_:)/title",
          "value": "AudioComponentGetLastActiveTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentGetLastActiveTime(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioComponentGetLastActiveTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionGetPropertySize(_:_:)/title",
          "value": "AudioSessionGetPropertySize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionGetPropertySize(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioSessionGetPropertySize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentGetIcon(_:_:)/title",
          "value": "AudioComponentGetIcon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentGetIcon(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioComponentGetIcon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioHardwareServiceGetPropertyData(_:_:_:_:_:_:)/title",
          "value": "AudioHardwareServiceGetPropertyData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioHardwareServiceGetPropertyData(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwareServiceGetPropertyData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitPublish(_:_:_:_:)/title",
          "value": "AudioOutputUnitPublish"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioOutputUnitPublish(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioOutputUnitPublish"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileReadPackets(_:_:_:_:_:_:_:)/title",
          "value": "AudioFileReadPackets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileReadPackets(_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileReadPackets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioHardwareServiceHasProperty(_:_:)/title",
          "value": "AudioHardwareServiceHasProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioHardwareServiceHasProperty(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwareServiceHasProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioHardwareServiceIsPropertySettable(_:_:_:)/title",
          "value": "AudioHardwareServiceIsPropertySettable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioHardwareServiceIsPropertySettable(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwareServiceIsPropertySettable"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/audiosessionsetproperty(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/audiosessionsetproperty(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
