{
  "abstract": [
    {
      "text": "Flags specified in a packet translation structure.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-services"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio_file_packet_translation_flags"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio File Packet Translation Flags"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Flag used with the ",
              "type": "text"
            },
            {
              "code": "mFlags",
              "type": "codeVoice"
            },
            {
              "text": " field of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBytePacketTranslation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " structure.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576492-audio-file-marker-types": {
      "abstract": [
        {
          "text": "A type of marker within a file used in the ",
          "type": "text"
        },
        {
          "code": "mType",
          "type": "codeVoice"
        },
        {
          "text": " field of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileMarker",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " structure.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576492-audio-file-marker-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio File Marker Types",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1576492-audio-file-marker-types"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576494-audio-file-loop-direction-consta": {
      "abstract": [
        {
          "text": "The playback direction of a looped segment of an audio file.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576494-audio-file-loop-direction-consta",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio File Loop Direction Constants",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1576494-audio-file-loop-direction-consta"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576495-audio-file-global-info-propertie": {
      "abstract": [
        {
          "text": "Access these properties using the functions described in Working with Global Information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576495-audio-file-global-info-propertie",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio File Global Info Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1576495-audio-file-global-info-propertie"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576499-audio-file-properties": {
      "abstract": [
        {
          "text": "Properties used by the functions described in getting and setting pieces of data in audio files. See Working with Global Information for details.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576499-audio-file-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio File Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1576499-audio-file-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBytePacketTranslation": {
      "abstract": [
        {
          "text": "A data structure used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePropertyByteToPacket",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePropertyPacketToByte",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioBytePacketTranslation"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBytePacketTranslation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioBytePacketTranslation"
        }
      ],
      "role": "symbol",
      "title": "AudioBytePacketTranslation",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiobytepackettranslation"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBytePacketTranslationFlags/bytePacketTranslationFlag_IsEstimate": {
      "abstract": [
        {
          "text": "If set, the result value is an estimate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bytePacketTranslationFlag_IsEstimate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioBytePacketTranslationFlags",
          "text": "AudioBytePacketTranslationFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBytePacketTranslationFlags/bytePacketTranslationFlag_IsEstimate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBytePacketTranslationFlag_IsEstimate"
        }
      ],
      "role": "symbol",
      "title": "bytePacketTranslationFlag_IsEstimate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiobytepackettranslationflags/bytepackettranslationflag_isestimate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileMarker": {
      "abstract": [
        {
          "text": "Annotates a position in an audio file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileMarker"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileMarker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileMarker"
        }
      ],
      "role": "symbol",
      "title": "AudioFileMarker",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilemarker"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFilePermissions": {
      "abstract": [
        {
          "text": "Flags for use when opening an audio file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFilePermissions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFilePermissions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFilePermissions"
        }
      ],
      "role": "symbol",
      "title": "AudioFilePermissions",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilepermissions"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileRegionFlags": {
      "abstract": [
        {
          "text": "Flags that specify a playback direction for an audio file region structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileRegionFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileRegionFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileRegionFlags"
        }
      ],
      "role": "symbol",
      "title": "AudioFileRegionFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofileregionflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileTypeID": {
      "abstract": [
        {
          "text": "Operating system constants that indicate the type of file to be written or a hint about what type of file to expect from data provided.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileTypeID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileTypeID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileTypeID"
        }
      ],
      "role": "symbol",
      "title": "AudioFileTypeID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofiletypeid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-services": {
      "abstract": [
        {
          "text": "Read or write a variety of audio data to or from disk or a memory buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio File Services",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-file-services"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio_file_creation_flags": {
      "abstract": [
        {
          "text": "Flags to set when creating an audio file.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio_file_creation_flags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio File Creation Flags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio_file_creation_flags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/info-string-keys": {
      "abstract": [
        {
          "text": "Key values of properties to get and set using Audio File Services functions and provide a common way to get the same information out of several different kinds of files.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/info-string-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Info String Keys",
      "type": "topic",
      "url": "/documentation/audiotoolbox/info-string-keys"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePropertyByteToPacket": {
      "abstract": [
        {
          "text": "Passes an audio byte packet translation structure with the ",
          "type": "text"
        },
        {
          "code": "mByte",
          "type": "codeVoice"
        },
        {
          "text": " field filled out and returns the ",
          "type": "text"
        },
        {
          "code": "mPacket",
          "type": "codeVoice"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "code": "mByteOffsetInPacket",
          "type": "codeVoice"
        },
        {
          "text": " fields. If the value in the ",
          "type": "text"
        },
        {
          "code": "mByte",
          "type": "codeVoice"
        },
        {
          "text": " field is an estimate then the ",
          "type": "text"
        },
        {
          "code": "kBytePacketTranslationFlag_IsEstimate",
          "type": "codeVoice"
        },
        {
          "text": " flag is set in the ",
          "type": "text"
        },
        {
          "code": "mFlags",
          "type": "codeVoice"
        },
        {
          "text": " field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFilePropertyByteToPacket"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePropertyByteToPacket",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFilePropertyByteToPacket"
        }
      ],
      "role": "symbol",
      "title": "kAudioFilePropertyByteToPacket",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilepropertybytetopacket"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePropertyPacketToByte": {
      "abstract": [
        {
          "text": "Passes an audio byte packet translation structure with the ",
          "type": "text"
        },
        {
          "code": "mPacket",
          "type": "codeVoice"
        },
        {
          "text": " field filled out and returns the ",
          "type": "text"
        },
        {
          "code": "mByte",
          "type": "codeVoice"
        },
        {
          "text": " field. The ",
          "type": "text"
        },
        {
          "code": "mByteOffsetInPacket",
          "type": "codeVoice"
        },
        {
          "text": " field is ignored. If the value in the ",
          "type": "text"
        },
        {
          "code": "mByte",
          "type": "codeVoice"
        },
        {
          "text": " field is an estimate then the ",
          "type": "text"
        },
        {
          "code": "kBytePacketTranslationFlag_IsEstimate",
          "type": "codeVoice"
        },
        {
          "text": " flag is set in the ",
          "type": "text"
        },
        {
          "code": "mFlags",
          "type": "codeVoice"
        },
        {
          "text": " field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFilePropertyPacketToByte"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePropertyPacketToByte",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFilePropertyPacketToByte"
        }
      ],
      "role": "symbol",
      "title": "kAudioFilePropertyPacketToByte",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilepropertypackettobyte"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileTypeID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio_file_creation_flags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFilePermissions",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576494-audio-file-loop-direction-consta",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576492-audio-file-marker-types",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileRegionFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/info-string-keys",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576499-audio-file-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576495-audio-file-global-info-propertie"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBytePacketTranslationFlags/bytePacketTranslationFlag_IsEstimate"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBytePacketTranslationFlags/bytePacketTranslationFlag_IsEstimate"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileTypeID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio_file_creation_flags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFilePermissions",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576494-audio-file-loop-direction-consta",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576492-audio-file-marker-types",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileRegionFlags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/info-string-keys",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576499-audio-file-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576495-audio-file-global-info-propertie"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioBytePacketTranslationFlags~1bytePacketTranslationFlag_IsEstimate/title",
          "value": "kBytePacketTranslationFlag_IsEstimate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioBytePacketTranslationFlags~1bytePacketTranslationFlag_IsEstimate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBytePacketTranslationFlag_IsEstimate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileTypeID/title",
          "value": "AudioFileTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileTypeID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileTypeID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFilePermissions/title",
          "value": "AudioFilePermissions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFilePermissions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFilePermissions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFilePermissions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFilePermissions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileMarker/title",
          "value": "AudioFileMarker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileMarker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileMarker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileMarker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileMarker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFilePropertyByteToPacket/title",
          "value": "kAudioFilePropertyByteToPacket"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFilePropertyByteToPacket/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFilePropertyByteToPacket"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileRegionFlags/title",
          "value": "AudioFileRegionFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileRegionFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileRegionFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileRegionFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileRegionFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFilePropertyPacketToByte/title",
          "value": "kAudioFilePropertyPacketToByte"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFilePropertyPacketToByte/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFilePropertyPacketToByte"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioBytePacketTranslation/title",
          "value": "AudioBytePacketTranslation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioBytePacketTranslation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioBytePacketTranslation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioBytePacketTranslation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioBytePacketTranslation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/audio_file_packet_translation_flags"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/audio_file_packet_translation_flags"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
