{
  "abstract": [
    {
      "text": "Plays a system sound object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesPlaySystemSound(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@AudioServicesPlaySystemSound",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AudioServicesPlaySystemSound"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SystemSoundID",
        "text": "SystemSoundID"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AudioServicesPlaySystemSound"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "AudioServicesPlaySystemSound(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioServicesPlaySystemSound"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inSystemSoundID"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/SystemSoundID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SystemSoundID",
              "text": "SystemSoundID"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The system sound to play. Before using this function, call the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesCreateSystemSoundID(_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " function to obtain a system sound.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inSystemSoundID"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function plays a short sound (30 seconds or less in duration). Because sound might play for several seconds, this function is executed asynchronously. To know when a sound has finished playing, call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesAddSystemSoundCompletion(_:_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function to register a callback function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "On some iOS devices, you can pass the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSystemSoundID_Vibrate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " constant to invoke vibration. On other iOS devices, calling this function with that constant does nothing.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Sound files that you play using this function must be:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "No longer than 30 seconds in duration",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In linear PCM or IMA4 (IMA/ADPCM) format",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Packaged in a ",
                      "type": "text"
                    },
                    {
                      "code": ".caf",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "code": ".aif",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", or ",
                      "type": "text"
                    },
                    {
                      "code": ".wav",
                      "type": "codeVoice"
                    },
                    {
                      "text": " file",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "In addition, when you use the ",
              "type": "text"
            },
            {
              "code": "AudioServicesPlaySystemSound",
              "type": "codeVoice"
            },
            {
              "text": " function:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Sounds play at the current system audio volume, with no programmatic volume control available",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Sounds play immediately",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Looping and stereo positioning are unavailable",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Simultaneous playback is unavailable: You can play only one sound at a time",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The sound is played locally on the device speakers; it does not use audio routing.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesAddSystemSoundCompletion(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Registers a callback function that is invoked when a specified system sound finishes playing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioServicesAddSystemSoundCompletion"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SystemSoundID",
          "text": "SystemSoundID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFRunLoopRef",
          "text": "CFRunLoop"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioServicesSystemSoundCompletionProc",
          "text": "AudioServicesSystemSoundCompletionProc"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesAddSystemSoundCompletion(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioServicesAddSystemSoundCompletion"
        }
      ],
      "role": "symbol",
      "title": "AudioServicesAddSystemSoundCompletion(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioservicesaddsystemsoundcompletion(_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesCreateSystemSoundID(_:_:)": {
      "abstract": [
        {
          "text": "Creates a system sound object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioServicesCreateSystemSoundID"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SystemSoundID",
          "text": "SystemSoundID"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesCreateSystemSoundID(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioServicesCreateSystemSoundID"
        }
      ],
      "role": "symbol",
      "title": "AudioServicesCreateSystemSoundID(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioservicescreatesystemsoundid(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesPlayAlertSound(_:)": {
      "abstract": [
        {
          "text": "Plays a system sound as an alert.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioServicesPlayAlertSound"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SystemSoundID",
          "text": "SystemSoundID"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesPlayAlertSound(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioServicesPlayAlertSound"
        }
      ],
      "role": "symbol",
      "title": "AudioServicesPlayAlertSound(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioservicesplayalertsound(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesPlayAlertSoundWithCompletion(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioServicesPlayAlertSoundWithCompletion"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SystemSoundID",
          "text": "SystemSoundID"
        },
        {
          "kind": "text",
          "text": ", (() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesPlayAlertSoundWithCompletion(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioServicesPlayAlertSoundWithCompletion"
        }
      ],
      "role": "symbol",
      "title": "AudioServicesPlayAlertSoundWithCompletion(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioservicesplayalertsoundwithcompletion(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesPlaySystemSound(_:)": {
      "abstract": [
        {
          "text": "Plays a system sound object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioServicesPlaySystemSound"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SystemSoundID",
          "text": "SystemSoundID"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesPlaySystemSound(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioServicesPlaySystemSound"
        }
      ],
      "role": "symbol",
      "title": "AudioServicesPlaySystemSound(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioservicesplaysystemsound(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesPlaySystemSoundWithCompletion(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioServicesPlaySystemSoundWithCompletion"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SystemSoundID",
          "text": "SystemSoundID"
        },
        {
          "kind": "text",
          "text": ", (() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesPlaySystemSoundWithCompletion(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioServicesPlaySystemSoundWithCompletion"
        }
      ],
      "role": "symbol",
      "title": "AudioServicesPlaySystemSoundWithCompletion(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioservicesplaysystemsoundwithcompletion(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/SystemSoundID": {
      "abstract": [
        {
          "text": "A system sound object, identified with a sound file you want to play.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SystemSoundID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/SystemSoundID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SystemSoundID"
        }
      ],
      "role": "symbol",
      "title": "SystemSoundID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/systemsoundid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSystemSoundID_Vibrate": {
      "abstract": [
        {
          "text": "On the iPhone, use this constant with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesPlayAlertSound(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function to invoke a brief vibration. On the iPod touch, does nothing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSystemSoundID_Vibrate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SystemSoundID",
          "text": "SystemSoundID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSystemSoundID_Vibrate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSystemSoundID_Vibrate"
        }
      ],
      "role": "symbol",
      "title": "kSystemSoundID_Vibrate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/ksystemsoundid_vibrate"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesAddSystemSoundCompletion(_:_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesCreateSystemSoundID(_:_:)"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Playing-Sounds",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesPlayAlertSoundWithCompletion(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesPlaySystemSoundWithCompletion(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesPlayAlertSound(_:)"
      ],
      "title": "Playing Sounds"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AudioServicesPlaySystemSound"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioServicesPlaySystemSound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesAddSystemSoundCompletion(_:_:_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesCreateSystemSoundID(_:_:)"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Playing-Sounds",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesPlayAlertSoundWithCompletion(_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesPlaySystemSoundWithCompletion(_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesPlayAlertSound(_:)"
              ],
              "title": "Playing Sounds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AudioServicesPlaySystemSound"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/SystemSoundID",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SystemSoundID",
                    "text": "SystemSoundID"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inSystemSoundID"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The system sound to play. Before using this function, call the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioServicesCreateSystemSoundID(_:_:)",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " function to obtain a system sound.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inSystemSoundID"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSystemSoundID_Vibrate/title",
          "value": "kSystemSoundID_Vibrate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSystemSoundID_Vibrate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSystemSoundID_Vibrate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioServicesPlayAlertSound(_:)/title",
          "value": "AudioServicesPlayAlertSound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioServicesPlayAlertSound(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioServicesPlayAlertSound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioServicesCreateSystemSoundID(_:_:)/title",
          "value": "AudioServicesCreateSystemSoundID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioServicesCreateSystemSoundID(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioServicesCreateSystemSoundID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioServicesAddSystemSoundCompletion(_:_:_:_:_:)/title",
          "value": "AudioServicesAddSystemSoundCompletion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioServicesAddSystemSoundCompletion(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioServicesAddSystemSoundCompletion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioServicesPlayAlertSoundWithCompletion(_:_:)/title",
          "value": "AudioServicesPlayAlertSoundWithCompletion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioServicesPlayAlertSoundWithCompletion(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioServicesPlayAlertSoundWithCompletion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1SystemSoundID/title",
          "value": "SystemSoundID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1SystemSoundID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SystemSoundID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1SystemSoundID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SystemSoundID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioServicesPlaySystemSound(_:)/title",
          "value": "AudioServicesPlaySystemSound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioServicesPlaySystemSound(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioServicesPlaySystemSound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioServicesPlaySystemSoundWithCompletion(_:_:)/title",
          "value": "AudioServicesPlaySystemSoundWithCompletion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioServicesPlaySystemSoundWithCompletion(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioServicesPlaySystemSoundWithCompletion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/audioservicesplaysystemsound(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/audioservicesplaysystemsound(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
