{
  "abstract": [
    {
      "text": "Value options for audio unit parameters.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AudioUnitParameterOptions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AudioUnitParameterOptions"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AudioUnitParameterOptions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AudioUnitParameterOptions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioUnitParameterOptions"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These constants are relevant only in macOS, and not in iOS.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Audio unit parameter flags, for use in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterInfo",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " data structure , serve as a dictionary-like set of information about an audio unit parameter. Parameter flag bit position 19 is reserved.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitConnection": {
      "abstract": [
        {
          "text": "An audio unit source-to-destination connection specification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitConnection"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitConnection"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitConnection",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitconnection"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEvent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitEvent"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitEvent"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitEvent",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitevent"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitExternalBuffer": {
      "abstract": [
        {
          "text": "Allows an audio unit host application to tell an audio unit to use a specified buffer for its input callback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitExternalBuffer"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitExternalBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitExternalBuffer"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitExternalBuffer",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitexternalbuffer"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitFrequencyResponseBin": {
      "abstract": [
        {
          "text": "An audio unit’s audio level at a particular frequency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitFrequencyResponseBin"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitFrequencyResponseBin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitFrequencyResponseBin"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitFrequencyResponseBin",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitfrequencyresponsebin"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitMIDIControlMapping": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitMIDIControlMapping"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitMIDIControlMapping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitMIDIControlMapping"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitMIDIControlMapping",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitmidicontrolmapping"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitMeterClipping": {
      "abstract": [
        {
          "text": "Audio clipping that has occurred in a mixer unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitMeterClipping"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitMeterClipping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitMeterClipping"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitMeterClipping",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitmeterclipping"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitOtherPluginDesc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitOtherPluginDesc"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitOtherPluginDesc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitOtherPluginDesc"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitOtherPluginDesc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitotherplugindesc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameter": {
      "abstract": [
        {
          "text": "An adjustable audio unit attribute such as volume, pitch, or filter cutoff frequency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameter"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameter"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterEvent": {
      "abstract": [
        {
          "text": "A scheduled change to an audio unit parameter’s value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterEvent"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterEvent"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterEvent",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterevent"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterHistoryInfo": {
      "abstract": [
        {
          "text": "The suggested update rate and history duration for parameters which have the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_PlotHistory",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " flag set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterHistoryInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterHistoryInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterHistoryInfo"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterHistoryInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterhistoryinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterIDName": {
      "abstract": [
        {
          "text": "A type definition for a data type that defines the short version of the name for an audio unit parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterIDName"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterIDName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterIDName"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterIDName",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteridname"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterInfo"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterNameInfo": {
      "abstract": [
        {
          "text": "A short version of the name for an audio unit parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterNameInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterNameInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterNameInfo"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterNameInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameternameinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions": {
      "abstract": [
        {
          "text": "Value options for audio unit parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterOptions",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteroptions"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_CFNameRelease": {
      "abstract": [
        {
          "text": "If an audio unit can generate parameter names dynamically, it should set this flag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flag_CFNameRelease"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_CFNameRelease",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterFlag_CFNameRelease"
        }
      ],
      "role": "symbol",
      "title": "flag_CFNameRelease",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteroptions/flag_cfnamerelease"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_CanRamp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flag_CanRamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_CanRamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterFlag_CanRamp"
        }
      ],
      "role": "symbol",
      "title": "flag_CanRamp",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteroptions/flag_canramp"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_DisplayCubeRoot": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flag_DisplayCubeRoot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_DisplayCubeRoot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterFlag_DisplayCubeRoot"
        }
      ],
      "role": "symbol",
      "title": "flag_DisplayCubeRoot",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteroptions/flag_displaycuberoot"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_DisplayCubed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flag_DisplayCubed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_DisplayCubed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterFlag_DisplayCubed"
        }
      ],
      "role": "symbol",
      "title": "flag_DisplayCubed",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteroptions/flag_displaycubed"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_DisplayExponential": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flag_DisplayExponential"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_DisplayExponential",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterFlag_DisplayExponential"
        }
      ],
      "role": "symbol",
      "title": "flag_DisplayExponential",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteroptions/flag_displayexponential"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_DisplayLogarithmic": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flag_DisplayLogarithmic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_DisplayLogarithmic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterFlag_DisplayLogarithmic"
        }
      ],
      "role": "symbol",
      "title": "flag_DisplayLogarithmic",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteroptions/flag_displaylogarithmic"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_DisplayMask": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flag_DisplayMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_DisplayMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterFlag_DisplayMask"
        }
      ],
      "role": "symbol",
      "title": "flag_DisplayMask",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteroptions/flag_displaymask"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_DisplaySquareRoot": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flag_DisplaySquareRoot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_DisplaySquareRoot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterFlag_DisplaySquareRoot"
        }
      ],
      "role": "symbol",
      "title": "flag_DisplaySquareRoot",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteroptions/flag_displaysquareroot"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_DisplaySquared": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flag_DisplaySquared"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_DisplaySquared",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterFlag_DisplaySquared"
        }
      ],
      "role": "symbol",
      "title": "flag_DisplaySquared",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteroptions/flag_displaysquared"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_ExpertMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flag_ExpertMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_ExpertMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterFlag_ExpertMode"
        }
      ],
      "role": "symbol",
      "title": "flag_ExpertMode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteroptions/flag_expertmode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_HasCFNameString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flag_HasCFNameString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_HasCFNameString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterFlag_HasCFNameString"
        }
      ],
      "role": "symbol",
      "title": "flag_HasCFNameString",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteroptions/flag_hascfnamestring"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_HasClump": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flag_HasClump"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_HasClump",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterFlag_HasClump"
        }
      ],
      "role": "symbol",
      "title": "flag_HasClump",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteroptions/flag_hasclump"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_IsElementMeta": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flag_IsElementMeta"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_IsElementMeta",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterFlag_IsElementMeta"
        }
      ],
      "role": "symbol",
      "title": "flag_IsElementMeta",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteroptions/flag_iselementmeta"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_IsGlobalMeta": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flag_IsGlobalMeta"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_IsGlobalMeta",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterFlag_IsGlobalMeta"
        }
      ],
      "role": "symbol",
      "title": "flag_IsGlobalMeta",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteroptions/flag_isglobalmeta"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_IsHighResolution": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flag_IsHighResolution"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_IsHighResolution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterFlag_IsHighResolution"
        }
      ],
      "role": "symbol",
      "title": "flag_IsHighResolution",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteroptions/flag_ishighresolution"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_IsReadable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flag_IsReadable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_IsReadable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterFlag_IsReadable"
        }
      ],
      "role": "symbol",
      "title": "flag_IsReadable",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteroptions/flag_isreadable"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_IsWritable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flag_IsWritable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_IsWritable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterFlag_IsWritable"
        }
      ],
      "role": "symbol",
      "title": "flag_IsWritable",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteroptions/flag_iswritable"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_MeterReadOnly": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flag_MeterReadOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_MeterReadOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterFlag_MeterReadOnly"
        }
      ],
      "role": "symbol",
      "title": "flag_MeterReadOnly",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteroptions/flag_meterreadonly"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_NonRealTime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flag_NonRealTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_NonRealTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterFlag_NonRealTime"
        }
      ],
      "role": "symbol",
      "title": "flag_NonRealTime",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteroptions/flag_nonrealtime"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_OmitFromPresets": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flag_OmitFromPresets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_OmitFromPresets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterFlag_OmitFromPresets"
        }
      ],
      "role": "symbol",
      "title": "flag_OmitFromPresets",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteroptions/flag_omitfrompresets"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_PlotHistory": {
      "abstract": [
        {
          "text": "If set, getting the ",
          "type": "text"
        },
        {
          "code": "kAudioUnitProperty_ParameterHistoryInfo",
          "type": "codeVoice"
        },
        {
          "text": " property fills out the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterHistoryInfo",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " struct containing the recommended update rate and history duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flag_PlotHistory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_PlotHistory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterFlag_PlotHistory"
        }
      ],
      "role": "symbol",
      "title": "flag_PlotHistory",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteroptions/flag_plothistory"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_ValuesHaveStrings": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flag_ValuesHaveStrings"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_ValuesHaveStrings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterFlag_ValuesHaveStrings"
        }
      ],
      "role": "symbol",
      "title": "flag_ValuesHaveStrings",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteroptions/flag_valueshavestrings"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteroptions/init(rawvalue:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterStringFromValue": {
      "abstract": [
        {
          "text": "A string representation of a parameter’s value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterStringFromValue"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterStringFromValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterStringFromValue"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterStringFromValue",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterstringfromvalue"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterValueFromString": {
      "abstract": [
        {
          "text": "A parameter’s value based on a string representation of the value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterValueFromString"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterValueFromString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterValueFromString"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterValueFromString",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparametervaluefromstring"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitConnection",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEvent",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitExternalBuffer",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitFrequencyResponseBin",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitMeterClipping",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitMIDIControlMapping",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitOtherPluginDesc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterEvent",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterHistoryInfo",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterNameInfo",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterIDName",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterInfo",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterStringFromValue",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterValueFromString"
      ],
      "title": "Structures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_CFNameRelease",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_CanRamp",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_DisplayCubeRoot",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_DisplayCubed",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_DisplayExponential",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_DisplayLogarithmic",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_DisplayMask",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_DisplaySquareRoot",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_DisplaySquared",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_ExpertMode",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_HasCFNameString",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_HasClump",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_IsElementMeta",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_IsGlobalMeta",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_IsHighResolution",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_IsReadable",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_IsWritable",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_MeterReadOnly",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_NonRealTime",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_OmitFromPresets",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_PlotHistory",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_ValuesHaveStrings"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AudioUnitParameterOptions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_CFNameRelease",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_CanRamp",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_DisplayCubeRoot",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_DisplayCubed",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_DisplayExponential",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_DisplayLogarithmic",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_DisplayMask",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_DisplaySquareRoot",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_DisplaySquared",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_ExpertMode",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_HasCFNameString",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_HasClump",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_IsElementMeta",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_IsGlobalMeta",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_IsHighResolution",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_IsReadable",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_IsWritable",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_MeterReadOnly",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_NonRealTime",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_OmitFromPresets",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_PlotHistory",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_ValuesHaveStrings"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Structures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitConnection",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEvent",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitExternalBuffer",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitFrequencyResponseBin",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitMeterClipping",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitMIDIControlMapping",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitOtherPluginDesc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterEvent",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterHistoryInfo",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterNameInfo",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterIDName",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterInfo",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterStringFromValue",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterValueFromString"
              ],
              "title": "Structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AudioUnitParameterOptions"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@UInt32",
                    "text": "UInt32"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitOtherPluginDesc/title",
          "value": "AudioUnitOtherPluginDesc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitOtherPluginDesc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitOtherPluginDesc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitOtherPluginDesc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitOtherPluginDesc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterEvent/title",
          "value": "AudioUnitParameterEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameter/title",
          "value": "AudioUnitParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitConnection/title",
          "value": "AudioUnitConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitConnection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_ExpertMode/title",
          "value": "kAudioUnitParameterFlag_ExpertMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_ExpertMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterFlag_ExpertMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_MeterReadOnly/title",
          "value": "kAudioUnitParameterFlag_MeterReadOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_MeterReadOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterFlag_MeterReadOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEvent/title",
          "value": "AudioUnitEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_DisplayCubed/title",
          "value": "kAudioUnitParameterFlag_DisplayCubed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_DisplayCubed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterFlag_DisplayCubed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_IsHighResolution/title",
          "value": "kAudioUnitParameterFlag_IsHighResolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_IsHighResolution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterFlag_IsHighResolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterInfo/title",
          "value": "AudioUnitParameterInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_HasCFNameString/title",
          "value": "kAudioUnitParameterFlag_HasCFNameString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_HasCFNameString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterFlag_HasCFNameString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_IsElementMeta/title",
          "value": "kAudioUnitParameterFlag_IsElementMeta"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_IsElementMeta/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterFlag_IsElementMeta"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_HasClump/title",
          "value": "kAudioUnitParameterFlag_HasClump"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_HasClump/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterFlag_HasClump"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_DisplaySquared/title",
          "value": "kAudioUnitParameterFlag_DisplaySquared"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_DisplaySquared/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterFlag_DisplaySquared"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterStringFromValue/title",
          "value": "AudioUnitParameterStringFromValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterStringFromValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterStringFromValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterStringFromValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterStringFromValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_IsReadable/title",
          "value": "kAudioUnitParameterFlag_IsReadable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_IsReadable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterFlag_IsReadable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_DisplaySquareRoot/title",
          "value": "kAudioUnitParameterFlag_DisplaySquareRoot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_DisplaySquareRoot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterFlag_DisplaySquareRoot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_DisplayExponential/title",
          "value": "kAudioUnitParameterFlag_DisplayExponential"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_DisplayExponential/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterFlag_DisplayExponential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterHistoryInfo/title",
          "value": "AudioUnitParameterHistoryInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterHistoryInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterHistoryInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterHistoryInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterHistoryInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_CanRamp/title",
          "value": "kAudioUnitParameterFlag_CanRamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_CanRamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterFlag_CanRamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitMIDIControlMapping/title",
          "value": "AudioUnitMIDIControlMapping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitMIDIControlMapping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitMIDIControlMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitMIDIControlMapping/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitMIDIControlMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterValueFromString/title",
          "value": "AudioUnitParameterValueFromString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterValueFromString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterValueFromString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterValueFromString/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterValueFromString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_PlotHistory/title",
          "value": "kAudioUnitParameterFlag_PlotHistory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_PlotHistory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterFlag_PlotHistory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_IsWritable/title",
          "value": "kAudioUnitParameterFlag_IsWritable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_IsWritable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterFlag_IsWritable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_DisplayLogarithmic/title",
          "value": "kAudioUnitParameterFlag_DisplayLogarithmic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_DisplayLogarithmic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterFlag_DisplayLogarithmic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_NonRealTime/title",
          "value": "kAudioUnitParameterFlag_NonRealTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_NonRealTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterFlag_NonRealTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_OmitFromPresets/title",
          "value": "kAudioUnitParameterFlag_OmitFromPresets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_OmitFromPresets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterFlag_OmitFromPresets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitExternalBuffer/title",
          "value": "AudioUnitExternalBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitExternalBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitExternalBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitExternalBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitExternalBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_CFNameRelease/title",
          "value": "kAudioUnitParameterFlag_CFNameRelease"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_CFNameRelease/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterFlag_CFNameRelease"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_IsGlobalMeta/title",
          "value": "kAudioUnitParameterFlag_IsGlobalMeta"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_IsGlobalMeta/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterFlag_IsGlobalMeta"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitMeterClipping/title",
          "value": "AudioUnitMeterClipping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitMeterClipping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitMeterClipping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitMeterClipping/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitMeterClipping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterNameInfo/title",
          "value": "AudioUnitParameterNameInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterNameInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterNameInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterNameInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterNameInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterIDName/title",
          "value": "AudioUnitParameterIDName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterIDName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterIDName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterIDName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterIDName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitFrequencyResponseBin/title",
          "value": "AudioUnitFrequencyResponseBin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitFrequencyResponseBin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitFrequencyResponseBin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitFrequencyResponseBin/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitFrequencyResponseBin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_DisplayCubeRoot/title",
          "value": "kAudioUnitParameterFlag_DisplayCubeRoot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_DisplayCubeRoot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterFlag_DisplayCubeRoot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_DisplayMask/title",
          "value": "kAudioUnitParameterFlag_DisplayMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_DisplayMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterFlag_DisplayMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions/title",
          "value": "AudioUnitParameterOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_ValuesHaveStrings/title",
          "value": "kAudioUnitParameterFlag_ValuesHaveStrings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_ValuesHaveStrings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterFlag_ValuesHaveStrings"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/audiounitparameteroptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/audiounitparameteroptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
