{
  "abstract": [
    {
      "text": "The various audio output destinations available for an iOS device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-session-support"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-output-routes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio Output Routes"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These strings are used as values for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSession_AudioRouteKey_Type",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key for the dictionary associated with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSession_AudioRouteKey_Outputs",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " array.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618380-audio-route-change-reasons": {
      "abstract": [
        {
          "text": "Identifiers for the various reasons that an audio route can change while your app is running.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618380-audio-route-change-reasons",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Route Change Reasons",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1618380-audio-route-change-reasons"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/alternative-audio-route-change-reason-dictionary-key": {
      "abstract": [
        {
          "text": "An alternate key for obtaining information about the reason for an audio route change.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/alternative-audio-route-change-reason-dictionary-key",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Alternative Audio Route Change Reason Dictionary Key",
      "type": "topic",
      "url": "/documentation/audiotoolbox/alternative-audio-route-change-reason-dictionary-key"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-input-routes": {
      "abstract": [
        {
          "text": "Strings that identify the various audio input sources for a device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-input-routes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Input Routes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-input-routes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-route-change-dictionary-keys": {
      "abstract": [
        {
          "text": "Keys for obtaining information about an audio hardware route change.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-route-change-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Route Change Dictionary Keys",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-route-change-dictionary-keys"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-route-description-dictionary-keys": {
      "abstract": [
        {
          "text": "Keys for the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioRouteDescription",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-route-description-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Route Description Dictionary Keys",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-route-description-dictionary-keys"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-route-type-key": {
      "abstract": [
        {
          "text": "The one key for an audio route input or output dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-route-type-key",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Route Type Key",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-route-type-key"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-session-support": {
      "abstract": [
        {
          "text": "Describe the properties that you associate with audio sessions and audio routes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-session-support",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Session Support",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-session-support"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_AirPlay": {
      "abstract": [
        {
          "text": "An output on an AirPlay device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_AirPlay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_AirPlay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_AirPlay"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionOutputRoute_AirPlay",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionoutputroute_airplay"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BluetoothA2DP": {
      "abstract": [
        {
          "text": "Speakers in a Bluetooth A2DP device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_BluetoothA2DP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BluetoothA2DP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_BluetoothA2DP"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionOutputRoute_BluetoothA2DP",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionoutputroute_bluetootha2dp"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BluetoothHFP": {
      "abstract": [
        {
          "text": "Speakers that are part of a Bluetooth Hands-Free Profile (HFP) accessory.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_BluetoothHFP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BluetoothHFP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_BluetoothHFP"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionOutputRoute_BluetoothHFP",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionoutputroute_bluetoothhfp"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BuiltInReceiver": {
      "abstract": [
        {
          "text": "The built-in speaker you hold to your ear when on a phone call.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_BuiltInReceiver"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BuiltInReceiver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_BuiltInReceiver"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionOutputRoute_BuiltInReceiver",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionoutputroute_builtinreceiver"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BuiltInSpeaker": {
      "abstract": [
        {
          "text": "The primary built-in speaker.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_BuiltInSpeaker"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BuiltInSpeaker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_BuiltInSpeaker"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionOutputRoute_BuiltInSpeaker",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionoutputroute_builtinspeaker"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_HDMI": {
      "abstract": [
        {
          "text": "An output available through the HDMI interface.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_HDMI"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_HDMI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_HDMI"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionOutputRoute_HDMI",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionoutputroute_hdmi"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_Headphones": {
      "abstract": [
        {
          "text": "Speakers in headphones or in a headset.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_Headphones"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_Headphones",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_Headphones"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionOutputRoute_Headphones",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionoutputroute_headphones"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_LineOut": {
      "abstract": [
        {
          "text": "Analog line-level output.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_LineOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_LineOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_LineOut"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionOutputRoute_LineOut",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionoutputroute_lineout"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_USBAudio": {
      "abstract": [
        {
          "text": "Speaker(s) in a Universal Serial Bus (USB) accessory, accessed through the device 30-pin connector.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_USBAudio"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_USBAudio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_USBAudio"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionOutputRoute_USBAudio",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionoutputroute_usbaudio"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioRouteDescription": {
      "abstract": [
        {
          "text": "Information about an audio route.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_AudioRouteDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioRouteDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_AudioRouteDescription"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_AudioRouteDescription",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_audioroutedescription"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSession_AudioRouteKey_Outputs": {
      "abstract": [
        {
          "text": "An object containing details about the audio output used in the current audio route.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSession_AudioRouteKey_Outputs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSession_AudioRouteKey_Outputs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSession_AudioRouteKey_Outputs"
        }
      ],
      "role": "symbol",
      "title": "kAudioSession_AudioRouteKey_Outputs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosession_audioroutekey_outputs"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSession_AudioRouteKey_Type": {
      "abstract": [
        {
          "text": "Audio routes input or output dictionary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSession_AudioRouteKey_Type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSession_AudioRouteKey_Type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSession_AudioRouteKey_Type"
        }
      ],
      "role": "symbol",
      "title": "kAudioSession_AudioRouteKey_Type",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosession_audioroutekey_type"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Audio-Routes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618380-audio-route-change-reasons",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-route-description-dictionary-keys",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-route-type-key",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-input-routes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-route-change-dictionary-keys",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/alternative-audio-route-change-reason-dictionary-key"
      ],
      "title": "Audio Routes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_LineOut",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_Headphones",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BluetoothHFP",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BluetoothA2DP",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BuiltInReceiver",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BuiltInSpeaker",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_USBAudio",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_HDMI",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_AirPlay"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_LineOut",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_Headphones",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BluetoothHFP",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BluetoothA2DP",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BuiltInReceiver",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BuiltInSpeaker",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_USBAudio",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_HDMI",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_AirPlay"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Audio-Routes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1618380-audio-route-change-reasons",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-route-description-dictionary-keys",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-route-type-key",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-input-routes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-route-change-dictionary-keys",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/alternative-audio-route-change-reason-dictionary-key"
              ],
              "title": "Audio Routes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_AudioRouteDescription/title",
          "value": "kAudioSessionProperty_AudioRouteDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_AudioRouteDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_AudioRouteDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_BluetoothHFP/title",
          "value": "kAudioSessionOutputRoute_BluetoothHFP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_BluetoothHFP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionOutputRoute_BluetoothHFP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_LineOut/title",
          "value": "kAudioSessionOutputRoute_LineOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_LineOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionOutputRoute_LineOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSession_AudioRouteKey_Type/title",
          "value": "kAudioSession_AudioRouteKey_Type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSession_AudioRouteKey_Type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSession_AudioRouteKey_Type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSession_AudioRouteKey_Outputs/title",
          "value": "kAudioSession_AudioRouteKey_Outputs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSession_AudioRouteKey_Outputs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSession_AudioRouteKey_Outputs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_BluetoothA2DP/title",
          "value": "kAudioSessionOutputRoute_BluetoothA2DP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_BluetoothA2DP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionOutputRoute_BluetoothA2DP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_AirPlay/title",
          "value": "kAudioSessionOutputRoute_AirPlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_AirPlay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionOutputRoute_AirPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_Headphones/title",
          "value": "kAudioSessionOutputRoute_Headphones"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_Headphones/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionOutputRoute_Headphones"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_USBAudio/title",
          "value": "kAudioSessionOutputRoute_USBAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_USBAudio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionOutputRoute_USBAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_HDMI/title",
          "value": "kAudioSessionOutputRoute_HDMI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_HDMI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionOutputRoute_HDMI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_BuiltInSpeaker/title",
          "value": "kAudioSessionOutputRoute_BuiltInSpeaker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_BuiltInSpeaker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionOutputRoute_BuiltInSpeaker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_BuiltInReceiver/title",
          "value": "kAudioSessionOutputRoute_BuiltInReceiver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_BuiltInReceiver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionOutputRoute_BuiltInReceiver"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/audio-output-routes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/audio-output-routes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
