{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "AudioToolbox Constants"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AudioToolbox Data Types",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiotoolbox-data-types"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AudioToolbox Enumerations",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiotoolbox-enumerations"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AudioToolbox Functions",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiotoolbox-functions"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AudioToolbox Structures",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiotoolbox-structures"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_AvailableArchitectures": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitConfigurationInfo_AvailableArchitectures"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_AvailableArchitectures",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitConfigurationInfo_AvailableArchitectures"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitConfigurationInfo_AvailableArchitectures",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitconfigurationinfo_availablearchitectures"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_MIDIProtocol": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitConfigurationInfo_MIDIProtocol"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_MIDIProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitConfigurationInfo_MIDIProtocol"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitConfigurationInfo_MIDIProtocol",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitconfigurationinfo_midiprotocol"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_MigrateFromPlugin": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitConfigurationInfo_MigrateFromPlugin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_MigrateFromPlugin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitConfigurationInfo_MigrateFromPlugin"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitConfigurationInfo_MigrateFromPlugin",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitconfigurationinfo_migratefromplugin"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-structures",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-enumerations",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-functions",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_AvailableArchitectures",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_MIDIProtocol",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_MigrateFromPlugin"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_AvailableArchitectures",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_MIDIProtocol",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_MigrateFromPlugin"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-structures",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-enumerations",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-functions",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitConfigurationInfo_AvailableArchitectures/title",
          "value": "kAudioUnitConfigurationInfo_AvailableArchitectures"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitConfigurationInfo_AvailableArchitectures/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitConfigurationInfo_AvailableArchitectures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitConfigurationInfo_MigrateFromPlugin/title",
          "value": "kAudioUnitConfigurationInfo_MigrateFromPlugin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitConfigurationInfo_MigrateFromPlugin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitConfigurationInfo_MigrateFromPlugin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitConfigurationInfo_MIDIProtocol/title",
          "value": "kAudioUnitConfigurationInfo_MIDIProtocol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitConfigurationInfo_MIDIProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitConfigurationInfo_MIDIProtocol"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/audiotoolbox-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/audiotoolbox-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
