{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-macros"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Macros"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ATTRIBUTE_PACKED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ATTRIBUTE_PACKED"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ATTRIBUTE_PACKED",
      "kind": "symbol",
      "role": "symbol",
      "title": "ATTRIBUTE_PACKED",
      "type": "topic",
      "url": "/documentation/audiotoolbox/attribute_packed"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUDIO_UNIT_VERSION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUDIO_UNIT_VERSION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUDIO_UNIT_VERSION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUDIO_UNIT_VERSION"
        }
      ],
      "role": "symbol",
      "title": "AUDIO_UNIT_VERSION",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio_unit_version"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGRAPH_DEPRECATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AUGRAPH_DEPRECATED"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGRAPH_DEPRECATED",
      "kind": "symbol",
      "role": "symbol",
      "title": "AUGRAPH_DEPRECATED",
      "type": "topic",
      "url": "/documentation/audiotoolbox/augraph_deprecated"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AUAudioUnitImplementation_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioToolbox_AUAudioUnitImplementation_h"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AUAudioUnitImplementation_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioToolbox_AUAudioUnitImplementation_h",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiotoolbox_auaudiounitimplementation_h"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AUCocoaUIView_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioToolbox_AUCocoaUIView_h"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AUCocoaUIView_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioToolbox_AUCocoaUIView_h",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiotoolbox_aucocoauiview_h"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AudioConverter_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioToolbox_AudioConverter_h"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AudioConverter_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioToolbox_AudioConverter_h",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiotoolbox_audioconverter_h"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AudioFileComponent_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioToolbox_AudioFileComponent_h"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AudioFileComponent_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioToolbox_AudioFileComponent_h",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiotoolbox_audiofilecomponent_h"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AudioFileStream_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioToolbox_AudioFileStream_h"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AudioFileStream_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioToolbox_AudioFileStream_h",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiotoolbox_audiofilestream_h"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AudioFile_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioToolbox_AudioFile_h"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AudioFile_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioToolbox_AudioFile_h",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiotoolbox_audiofile_h"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AudioFormat_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioToolbox_AudioFormat_h"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AudioFormat_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioToolbox_AudioFormat_h",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiotoolbox_audioformat_h"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AudioUnitUtilities_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioToolbox_AudioUnitUtilities_h"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AudioUnitUtilities_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioToolbox_AudioUnitUtilities_h",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiotoolbox_audiounitutilities_h"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AudioWorkInterval_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioToolbox_AudioWorkInterval_h"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AudioWorkInterval_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioToolbox_AudioWorkInterval_h",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiotoolbox_audioworkinterval_h"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_CAFFile_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioToolbox_CAFFile_h"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_CAFFile_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioToolbox_CAFFile_h",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiotoolbox_caffile_h"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_CAShow_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioToolbox_CAShow_h"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_CAShow_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioToolbox_CAShow_h",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiotoolbox_cashow_h"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_ExtendedAudioFile_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioToolbox_ExtendedAudioFile_h"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_ExtendedAudioFile_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioToolbox_ExtendedAudioFile_h",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiotoolbox_extendedaudiofile_h"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitDisplayTypeIsCubeRoot": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioUnitDisplayTypeIsCubeRoot"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitDisplayTypeIsCubeRoot",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioUnitDisplayTypeIsCubeRoot",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitdisplaytypeiscuberoot"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitDisplayTypeIsCubed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioUnitDisplayTypeIsCubed"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitDisplayTypeIsCubed",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioUnitDisplayTypeIsCubed",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitdisplaytypeiscubed"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitDisplayTypeIsExponential": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioUnitDisplayTypeIsExponential"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitDisplayTypeIsExponential",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioUnitDisplayTypeIsExponential",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitdisplaytypeisexponential"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitDisplayTypeIsLogarithmic": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioUnitDisplayTypeIsLogarithmic"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitDisplayTypeIsLogarithmic",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioUnitDisplayTypeIsLogarithmic",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitdisplaytypeislogarithmic"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitDisplayTypeIsSquareRoot": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioUnitDisplayTypeIsSquareRoot"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitDisplayTypeIsSquareRoot",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioUnitDisplayTypeIsSquareRoot",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitdisplaytypeissquareroot"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitDisplayTypeIsSquared": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioUnitDisplayTypeIsSquared"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitDisplayTypeIsSquared",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioUnitDisplayTypeIsSquared",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitdisplaytypeissquared"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnit_AudioOutputUnit_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioUnit_AudioOutputUnit_h"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnit_AudioOutputUnit_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioUnit_AudioOutputUnit_h",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounit_audiooutputunit_h"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnit_AudioUnitParameters_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioUnit_AudioUnitParameters_h"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnit_AudioUnitParameters_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioUnit_AudioUnitParameters_h",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounit_audiounitparameters_h"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnit_MusicDevice_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioUnit_MusicDevice_h"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnit_MusicDevice_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioUnit_MusicDevice_h",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounit_musicdevice_h"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/INTERAPP_AUDIO_DEPRECATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "INTERAPP_AUDIO_DEPRECATED"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/INTERAPP_AUDIO_DEPRECATED",
      "kind": "symbol",
      "role": "symbol",
      "title": "INTERAPP_AUDIO_DEPRECATED",
      "type": "topic",
      "url": "/documentation/audiotoolbox/interapp_audio_deprecated"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/NextCAFRegion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NextCAFRegion"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/NextCAFRegion",
      "kind": "symbol",
      "role": "symbol",
      "title": "NextCAFRegion",
      "type": "topic",
      "url": "/documentation/audiotoolbox/nextcafregion"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerChunkHdrSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCAFMarkerChunkHdrSize"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerChunkHdrSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCAFMarkerChunkHdrSize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcafmarkerchunkhdrsize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFRegionChunkHdrSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCAFRegionChunkHdrSize"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFRegionChunkHdrSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCAFRegionChunkHdrSize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcafregionchunkhdrsize"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Macros",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUDIO_UNIT_VERSION"
      ],
      "title": "Macros"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ATTRIBUTE_PACKED",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUDIO_UNIT_VERSION",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGRAPH_DEPRECATED",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AUAudioUnitImplementation_h",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AUCocoaUIView_h",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AudioConverter_h",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AudioFileComponent_h",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AudioFileStream_h",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AudioFile_h",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AudioFormat_h",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AudioUnitUtilities_h",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AudioWorkInterval_h",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_CAFFile_h",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_CAShow_h",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_ExtendedAudioFile_h",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitDisplayTypeIsCubeRoot",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitDisplayTypeIsCubed",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitDisplayTypeIsExponential",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitDisplayTypeIsLogarithmic",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitDisplayTypeIsSquareRoot",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitDisplayTypeIsSquared",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnit_AudioOutputUnit_h",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnit_AudioUnitParameters_h",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnit_MusicDevice_h",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/INTERAPP_AUDIO_DEPRECATED",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/NextCAFRegion",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerChunkHdrSize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFRegionChunkHdrSize"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUDIO_UNIT_VERSION/title",
          "value": "AUDIO_UNIT_VERSION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUDIO_UNIT_VERSION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUDIO_UNIT_VERSION"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/audiotoolbox-macros"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/audiotoolbox-macros"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
