{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapRef"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@AudioQueueProcessingTapRef",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AudioQueueProcessingTapRef"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AudioQueueProcessingTapRef"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "AudioQueueProcessingTapRef"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioQueueProcessingTapRef"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s13OpaquePointerV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s13OpaquePointerV",
              "text": "OpaquePointer"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer": {
      "abstract": [
        {
          "text": "Defines an audio queue buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueBuffer"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueBuffer"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueBuffer",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuebuffer"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBufferRef": {
      "abstract": [
        {
          "text": "A pointer to an audio queue buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueBufferRef"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBufferRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueBufferRef"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueBufferRef",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuebufferref"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueChannelAssignment": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueChannelAssignment"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueChannelAssignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueChannelAssignment"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueChannelAssignment",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuechannelassignment"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueLevelMeterState": {
      "abstract": [
        {
          "text": "Specifies the current level metering information for one channel of an audio queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueLevelMeterState"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueLevelMeterState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueLevelMeterState"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueLevelMeterState",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuelevelmeterstate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueParameterEvent": {
      "abstract": [
        {
          "text": "Specifies an audio queue parameter and associated value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueParameterEvent"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueParameterEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueParameterEvent"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueParameterEvent",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueueparameterevent"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueParameterID": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value that uniquely identifies an audio queue parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueParameterID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueParameterID"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueParameterID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueueparameterid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueParameterValue": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "Float32",
          "type": "codeVoice"
        },
        {
          "text": " value for an audio queue parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueParameterValue"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueParameterValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueParameterValue"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueParameterValue",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueueparametervalue"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapCallback": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueProcessingTapCallback"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueProcessingTapCallback"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueProcessingTapCallback",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueueprocessingtapcallback"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueProcessingTapFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueProcessingTapFlags"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueProcessingTapFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueueprocessingtapflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapRef": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueProcessingTapRef"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueProcessingTapRef"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueProcessingTapRef",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueueprocessingtapref"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s13OpaquePointerV": {
      "abstract": [
        {
          "text": "A wrapper around an opaque C pointer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OpaquePointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s13OpaquePointerV",
      "kind": "symbol",
      "role": "symbol",
      "title": "OpaquePointer",
      "type": "topic",
      "url": "/documentation/Swift/OpaquePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueChannelAssignment",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBufferRef",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueLevelMeterState",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueParameterEvent",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueParameterID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueParameterValue",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapCallback"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AudioQueueProcessingTapRef"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueProcessingTapRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueProcessingTapRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueChannelAssignment",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapFlags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBuffer",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueBufferRef",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueLevelMeterState",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueParameterEvent",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueParameterID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueParameterValue",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueProcessingTapCallback"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@OpaqueAudioQueueProcessingTap",
                    "text": "OpaqueAudioQueueProcessingTap"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "AudioQueueProcessingTapRef"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueProcessingTapRef/title",
          "value": "AudioQueueProcessingTapRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueProcessingTapRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueProcessingTapRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueProcessingTapRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueProcessingTapRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueBuffer/title",
          "value": "AudioQueueBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueLevelMeterState/title",
          "value": "AudioQueueLevelMeterState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueLevelMeterState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueLevelMeterState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueLevelMeterState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueLevelMeterState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueParameterValue/title",
          "value": "AudioQueueParameterValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueParameterValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueParameterValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueParameterValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueParameterValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueBufferRef/title",
          "value": "AudioQueueBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueBufferRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueBufferRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueChannelAssignment/title",
          "value": "AudioQueueChannelAssignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueChannelAssignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueChannelAssignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueChannelAssignment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueChannelAssignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueProcessingTapCallback/title",
          "value": "AudioQueueProcessingTapCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueProcessingTapCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueProcessingTapCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueProcessingTapCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueProcessingTapCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueParameterID/title",
          "value": "AudioQueueParameterID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueParameterID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueParameterID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueParameterEvent/title",
          "value": "AudioQueueParameterEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueParameterEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueParameterEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueParameterEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueParameterEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueProcessingTapFlags/title",
          "value": "AudioQueueProcessingTapFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueProcessingTapFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueProcessingTapFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueProcessingTapFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueProcessingTapFlags"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/audioqueueprocessingtapref"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/audioqueueprocessingtapref"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
