{
  "abstract": [
    {
      "text": "A structure holding magic cookie information needed by some codecs.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecMagicCookieInfo"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@AudioCodecMagicCookieInfo",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AudioCodecMagicCookieInfo"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AudioCodecMagicCookieInfo"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AudioCodecMagicCookieInfo"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioCodecMagicCookieInfo"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This structure is passed as input to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecGetProperty(_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function for the ",
              "type": "text"
            },
            {
              "code": "kAudioCodecPropertyFormatList",
              "type": "codeVoice"
            },
            {
              "text": " property. The first ",
              "type": "text"
            },
            {
              "code": "4 + sizeof(void *)",
              "type": "codeVoice"
            },
            {
              "text": " bytes of the buffer pointed to by the function’s ",
              "type": "text"
            },
            {
              "code": "outPropertyData",
              "type": "codeVoice"
            },
            {
              "text": " parameter contains this structure on input.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodec": {
      "abstract": [
        {
          "text": "An instance of a Component Manager component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioCodec"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodec",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioCodec"
        }
      ],
      "role": "symbol",
      "title": "AudioCodec",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocodec"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecAppendInputBufferListProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioCodecAppendInputBufferListProc"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecAppendInputBufferListProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioCodecAppendInputBufferListProc"
        }
      ],
      "role": "symbol",
      "title": "AudioCodecAppendInputBufferListProc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocodecappendinputbufferlistproc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecAppendInputDataProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioCodecAppendInputDataProc"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecAppendInputDataProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioCodecAppendInputDataProc"
        }
      ],
      "role": "symbol",
      "title": "AudioCodecAppendInputDataProc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocodecappendinputdataproc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecGetProperty(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Retrieves the value of a codec property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioCodecGetProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodec",
          "text": "AudioCodec"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecGetProperty(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioCodecGetProperty"
        }
      ],
      "role": "symbol",
      "title": "AudioCodecGetProperty(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocodecgetproperty(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecGetPropertyInfoProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioCodecGetPropertyInfoProc"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecGetPropertyInfoProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioCodecGetPropertyInfoProc"
        }
      ],
      "role": "symbol",
      "title": "AudioCodecGetPropertyInfoProc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocodecgetpropertyinfoproc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecGetPropertyProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioCodecGetPropertyProc"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecGetPropertyProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioCodecGetPropertyProc"
        }
      ],
      "role": "symbol",
      "title": "AudioCodecGetPropertyProc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocodecgetpropertyproc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecInitializeProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioCodecInitializeProc"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecInitializeProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioCodecInitializeProc"
        }
      ],
      "role": "symbol",
      "title": "AudioCodecInitializeProc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocodecinitializeproc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecMagicCookieInfo": {
      "abstract": [
        {
          "text": "A structure holding magic cookie information needed by some codecs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioCodecMagicCookieInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecMagicCookieInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioCodecMagicCookieInfo"
        }
      ],
      "role": "symbol",
      "title": "AudioCodecMagicCookieInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocodecmagiccookieinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecMagicCookieInfo/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecMagicCookieInfo/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocodecmagiccookieinfo/init()"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecMagicCookieInfo/init(mMagicCookieSize:mMagicCookie:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "mMagicCookieSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mMagicCookie"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecMagicCookieInfo/init(mMagicCookieSize:mMagicCookie:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(mMagicCookieSize:mMagicCookie:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocodecmagiccookieinfo/init(mmagiccookiesize:mmagiccookie:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecMagicCookieInfo/mMagicCookie": {
      "abstract": [
        {
          "text": "Generic constant pointer to the magic cookie.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mMagicCookie"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecMagicCookieInfo/mMagicCookie",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mMagicCookie"
        }
      ],
      "role": "symbol",
      "title": "mMagicCookie",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocodecmagiccookieinfo/mmagiccookie"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecMagicCookieInfo/mMagicCookieSize": {
      "abstract": [
        {
          "text": "The size of the magic cookie.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mMagicCookieSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecMagicCookieInfo/mMagicCookieSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mMagicCookieSize"
        }
      ],
      "role": "symbol",
      "title": "mMagicCookieSize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocodecmagiccookieinfo/mmagiccookiesize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecPrimeInfo": {
      "abstract": [
        {
          "text": "A structure specifying the number of leading and trailing empty frames to be inserted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioCodecPrimeInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecPrimeInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioCodecPrimeInfo"
        }
      ],
      "role": "symbol",
      "title": "AudioCodecPrimeInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocodecprimeinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecProduceOutputBufferListProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioCodecProduceOutputBufferListProc"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecProduceOutputBufferListProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioCodecProduceOutputBufferListProc"
        }
      ],
      "role": "symbol",
      "title": "AudioCodecProduceOutputBufferListProc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocodecproduceoutputbufferlistproc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecProduceOutputPacketsProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioCodecProduceOutputPacketsProc"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecProduceOutputPacketsProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioCodecProduceOutputPacketsProc"
        }
      ],
      "role": "symbol",
      "title": "AudioCodecProduceOutputPacketsProc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocodecproduceoutputpacketsproc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecPropertyID": {
      "abstract": [
        {
          "text": "An integer identifying an audio codec property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecPropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioCodecPropertyID"
        }
      ],
      "role": "symbol",
      "title": "AudioCodecPropertyID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocodecpropertyid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecResetProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioCodecResetProc"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecResetProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioCodecResetProc"
        }
      ],
      "role": "symbol",
      "title": "AudioCodecResetProc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocodecresetproc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecSetPropertyProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioCodecSetPropertyProc"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecSetPropertyProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioCodecSetPropertyProc"
        }
      ],
      "role": "symbol",
      "title": "AudioCodecSetPropertyProc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocodecsetpropertyproc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecUninitializeProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioCodecUninitializeProc"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecUninitializeProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioCodecUninitializeProc"
        }
      ],
      "role": "symbol",
      "title": "AudioCodecUninitializeProc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocodecuninitializeproc"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Codec-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecPrimeInfo",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodec",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecAppendInputBufferListProc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecAppendInputDataProc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecGetPropertyInfoProc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecGetPropertyProc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecInitializeProc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecProduceOutputBufferListProc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecProduceOutputPacketsProc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecPropertyID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecResetProc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecSetPropertyProc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecUninitializeProc"
      ],
      "title": "Codec Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecMagicCookieInfo/init()",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecMagicCookieInfo/init(mMagicCookieSize:mMagicCookie:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecMagicCookieInfo/mMagicCookie",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecMagicCookieInfo/mMagicCookieSize"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AudioCodecMagicCookieInfo"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecMagicCookieInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecMagicCookieInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecMagicCookieInfo/mMagicCookie",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecMagicCookieInfo/mMagicCookieSize"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Codec-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecPrimeInfo",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodec",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecAppendInputBufferListProc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecAppendInputDataProc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecGetPropertyInfoProc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecGetPropertyProc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecInitializeProc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecProduceOutputBufferListProc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecProduceOutputPacketsProc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecPropertyID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecResetProc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecSetPropertyProc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecUninitializeProc"
              ],
              "title": "Codec Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AudioCodecMagicCookieInfo"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodec/title",
          "value": "AudioCodec"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodec/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodec"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodec/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodec"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecSetPropertyProc/title",
          "value": "AudioCodecSetPropertyProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecSetPropertyProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecSetPropertyProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecSetPropertyProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecSetPropertyProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecMagicCookieInfo~1mMagicCookieSize/title",
          "value": "mMagicCookieSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecMagicCookieInfo~1mMagicCookieSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mMagicCookieSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecResetProc/title",
          "value": "AudioCodecResetProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecResetProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecResetProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecResetProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecResetProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecInitializeProc/title",
          "value": "AudioCodecInitializeProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecInitializeProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecInitializeProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecInitializeProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecInitializeProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecUninitializeProc/title",
          "value": "AudioCodecUninitializeProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecUninitializeProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecUninitializeProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecUninitializeProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecUninitializeProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecPrimeInfo/title",
          "value": "AudioCodecPrimeInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecPrimeInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecPrimeInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecPrimeInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecPrimeInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecGetPropertyProc/title",
          "value": "AudioCodecGetPropertyProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecGetPropertyProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecGetPropertyProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecGetPropertyProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecGetPropertyProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecGetPropertyInfoProc/title",
          "value": "AudioCodecGetPropertyInfoProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecGetPropertyInfoProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecGetPropertyInfoProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecGetPropertyInfoProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecGetPropertyInfoProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecProduceOutputPacketsProc/title",
          "value": "AudioCodecProduceOutputPacketsProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecProduceOutputPacketsProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecProduceOutputPacketsProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecProduceOutputPacketsProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecProduceOutputPacketsProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecPropertyID/title",
          "value": "AudioCodecPropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecPropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecPropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecGetProperty(_:_:_:_:)/title",
          "value": "AudioCodecGetProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecGetProperty(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecGetProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecProduceOutputBufferListProc/title",
          "value": "AudioCodecProduceOutputBufferListProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecProduceOutputBufferListProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecProduceOutputBufferListProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecProduceOutputBufferListProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecProduceOutputBufferListProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecMagicCookieInfo~1mMagicCookie/title",
          "value": "mMagicCookie"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecMagicCookieInfo~1mMagicCookie/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mMagicCookie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecMagicCookieInfo/title",
          "value": "AudioCodecMagicCookieInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecMagicCookieInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecMagicCookieInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecMagicCookieInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecMagicCookieInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecAppendInputBufferListProc/title",
          "value": "AudioCodecAppendInputBufferListProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecAppendInputBufferListProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecAppendInputBufferListProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecAppendInputBufferListProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecAppendInputBufferListProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecAppendInputDataProc/title",
          "value": "AudioCodecAppendInputDataProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecAppendInputDataProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecAppendInputDataProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecAppendInputDataProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecAppendInputDataProc"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/audiocodecmagiccookieinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/audiocodecmagiccookieinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
