{
  "abstract": [
    {
      "text": "Disposes of an audio queue’s timeline object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueDisposeTimeline(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@AudioQueueDisposeTimeline",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AudioQueueDisposeTimeline"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioQueueRef",
        "text": "AudioQueueRef"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioQueueTimelineRef",
        "text": "AudioQueueTimelineRef"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AudioQueueDisposeTimeline"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "AudioQueueDisposeTimeline(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioQueueDisposeTimeline"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inAQ"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioQueueRef",
              "text": "AudioQueueRef"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inTimeline"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueTimelineRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioQueueTimelineRef",
              "text": "AudioQueueTimelineRef"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The audio queue associated with the timeline object you want to dispose of.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inAQ"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The timeline object to dispose of.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inTimeline"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code. See Result Codes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Disposing of an audio queue automatically disposes of any associated resources, including a timeline object. Call this function only if you want to dispose of a timeline object and not the audio queue associated with it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueCreateTimeline(_:_:)": {
      "abstract": [
        {
          "text": "Creates a timeline object for an audio queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueCreateTimeline"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueueRef",
          "text": "AudioQueueRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueueTimelineRef",
          "text": "AudioQueueTimelineRef"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueCreateTimeline(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueCreateTimeline"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueCreateTimeline(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuecreatetimeline(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueDeviceGetCurrentTime(_:_:)": {
      "abstract": [
        {
          "text": "Gets the current time of the audio hardware device associated with an audio queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueDeviceGetCurrentTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueueRef",
          "text": "AudioQueueRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioTimeStamp",
          "text": "AudioTimeStamp"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueDeviceGetCurrentTime(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueDeviceGetCurrentTime"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueDeviceGetCurrentTime(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuedevicegetcurrenttime(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueDeviceGetNearestStartTime(_:_:_:)": {
      "abstract": [
        {
          "text": "Gets the start time, for an audio hardware device, that is closest to a requested start time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueDeviceGetNearestStartTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueueRef",
          "text": "AudioQueueRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioTimeStamp",
          "text": "AudioTimeStamp"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueDeviceGetNearestStartTime(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueDeviceGetNearestStartTime"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueDeviceGetNearestStartTime(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuedevicegetneareststarttime(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueDeviceTranslateTime(_:_:_:)": {
      "abstract": [
        {
          "text": "Converts the time for an audio queue’s associated audio hardware device from one time base representation to another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueDeviceTranslateTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueueRef",
          "text": "AudioQueueRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioTimeStamp",
          "text": "AudioTimeStamp"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioTimeStamp",
          "text": "AudioTimeStamp"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueDeviceTranslateTime(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueDeviceTranslateTime"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueDeviceTranslateTime(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuedevicetranslatetime(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueDispose(_:_:)": {
      "abstract": [
        {
          "text": "Disposes of an audio queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueDispose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueueRef",
          "text": "AudioQueueRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueDispose(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueDispose"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueDispose(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuedispose(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueDisposeTimeline(_:_:)": {
      "abstract": [
        {
          "text": "Disposes of an audio queue’s timeline object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueDisposeTimeline"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueueRef",
          "text": "AudioQueueRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueueTimelineRef",
          "text": "AudioQueueTimelineRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueDisposeTimeline(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueDisposeTimeline"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueDisposeTimeline(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuedisposetimeline(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueGetCurrentTime(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Gets the current audio queue time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueGetCurrentTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueueRef",
          "text": "AudioQueueRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueueTimelineRef",
          "text": "AudioQueueTimelineRef"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioTimeStamp",
          "text": "AudioTimeStamp"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Darwin0A7BooleanV",
          "text": "DarwinBoolean"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueGetCurrentTime(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueGetCurrentTime"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueGetCurrentTime(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuegetcurrenttime(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueRef": {
      "abstract": [
        {
          "text": "Defines an opaque data type that represents an audio queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueRef"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueRef"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueRef",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueueref"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueTimelineRef": {
      "abstract": [
        {
          "text": "Defines an opaque data type that represents an audio queue timeline object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueTimelineRef"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueTimelineRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueTimelineRef"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueTimelineRef",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuetimelineref"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueDispose(_:_:)"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Managing-the-Timeline",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueCreateTimeline(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueDeviceGetCurrentTime(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueDeviceGetNearestStartTime(_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueDeviceTranslateTime(_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueGetCurrentTime(_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueTimelineRef"
      ],
      "title": "Managing the Timeline"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AudioQueueDisposeTimeline"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueDisposeTimeline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueDispose(_:_:)"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Managing-the-Timeline",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueCreateTimeline(_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueDeviceGetCurrentTime(_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueDeviceGetNearestStartTime(_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueDeviceTranslateTime(_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueGetCurrentTime(_:_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueTimelineRef"
              ],
              "title": "Managing the Timeline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OSStatus",
                    "text": "OSStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AudioQueueDisposeTimeline"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AudioQueueRef",
                    "text": "AudioQueueRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inAQ"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueTimelineRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AudioQueueTimelineRef",
                    "text": "AudioQueueTimelineRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inTimeline"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The audio queue associated with the timeline object you want to dispose of.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inAQ"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The timeline object to dispose of.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inTimeline"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A result code. See Result Codes.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueDispose(_:_:)/title",
          "value": "AudioQueueDispose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueDispose(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueDispose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueRef/title",
          "value": "AudioQueueRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueCreateTimeline(_:_:)/title",
          "value": "AudioQueueCreateTimeline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueCreateTimeline(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueCreateTimeline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueDeviceGetCurrentTime(_:_:)/title",
          "value": "AudioQueueDeviceGetCurrentTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueDeviceGetCurrentTime(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueDeviceGetCurrentTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueDeviceGetNearestStartTime(_:_:_:)/title",
          "value": "AudioQueueDeviceGetNearestStartTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueDeviceGetNearestStartTime(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueDeviceGetNearestStartTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueTimelineRef/title",
          "value": "AudioQueueTimelineRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueTimelineRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueTimelineRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueTimelineRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueTimelineRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueDeviceTranslateTime(_:_:_:)/title",
          "value": "AudioQueueDeviceTranslateTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueDeviceTranslateTime(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueDeviceTranslateTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueGetCurrentTime(_:_:_:_:)/title",
          "value": "AudioQueueGetCurrentTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueGetCurrentTime(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueGetCurrentTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueDisposeTimeline(_:_:)/title",
          "value": "AudioQueueDisposeTimeline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueDisposeTimeline(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueDisposeTimeline"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/audioqueuedisposetimeline(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/audioqueuedisposetimeline(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
