{"seeAlsoSections":[{"identifiers":["doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion","doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSlice","doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegionCompletionProc","doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSliceCompletionProc","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MIDIChannelNumber","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioObjectID","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUMIDICIProfileChangedBlock","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioChannelCount","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioFrameCount","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitStatus","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerProc","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerRef","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventSampleTime","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueObserver","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueProvider"],"anchor":"Audio-Unit-Types","title":"Audio Unit Types","generated":true}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/audiotoolbox/audiounitpropertyid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/audiotoolbox/audiounitpropertyid"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioUnitPropertyID","kind":"identifier"},{"text":" = ","kind":"text"},{"text":"UInt32","identifier":"doc://com.externally.resolved.symbol/s:s6UInt32V","preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"Discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"An audio unit property is a key-value pair for a configuration setting, such as audio data stream format. The properties for Apple-supplied audio units are described in "},{"type":"codeVoice","code":"Audio Unit Properties"},{"type":"text","text":"."}]}]}],"abstract":[{"type":"text","text":"The data type for audio unit property keys."}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.audiotoolbox/documentation/AudioToolbox"]]},"metadata":{"platforms":[{"name":"iOS","beta":false,"unavailable":false,"deprecated":false},{"name":"iPadOS","beta":false,"unavailable":false,"deprecated":false},{"name":"Mac Catalyst","beta":false,"unavailable":false,"deprecated":false},{"name":"macOS","beta":false,"unavailable":false,"deprecated":false},{"name":"tvOS","beta":false,"unavailable":false,"deprecated":false},{"name":"visionOS","beta":false,"unavailable":false,"deprecated":false}],"roleHeading":"Type Alias","modules":[{"name":"Audio Toolbox"}],"title":"AudioUnitPropertyID","externalID":"c:@T@AudioUnitPropertyID","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioUnitPropertyID"}],"symbolKind":"typealias","navigatorTitle":[{"kind":"identifier","text":"AudioUnitPropertyID"}]},"identifier":{"url":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitPropertyID","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","type":"topic","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","role":"overview"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerRef":{"kind":"symbol","url":"/documentation/audiotoolbox/aueventlistenerref","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"AUEventListenerRef"}],"navigatorTitle":[{"kind":"identifier","text":"AUEventListenerRef"}],"title":"AUEventListenerRef","abstract":[],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerRef","type":"topic","role":"symbol"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitPropertyID":{"url":"/documentation/audiotoolbox/audiounitpropertyid","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioUnitPropertyID","kind":"identifier"}],"type":"topic","title":"AudioUnitPropertyID","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitPropertyID","abstract":[{"text":"The data type for audio unit property keys.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AudioUnitPropertyID","kind":"identifier"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitStatus":{"url":"/documentation/audiotoolbox/auaudiounitstatus","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AUAudioUnitStatus","kind":"identifier"}],"title":"AUAudioUnitStatus","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"AUAudioUnitStatus","kind":"identifier"}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitStatus","abstract":[{"type":"text","text":"A result code returned from an audio unit’s render function."}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueObserver":{"url":"/documentation/audiotoolbox/auimplementorvalueobserver","abstract":[{"type":"text","text":"A block called to notify the audio unit implementation of changes to a parameter value."}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"AUImplementorValueObserver"}],"role":"symbol","type":"topic","title":"AUImplementorValueObserver","kind":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueObserver","navigatorTitle":[{"kind":"identifier","text":"AUImplementorValueObserver"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioChannelCount":{"url":"/documentation/audiotoolbox/auaudiochannelcount","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"AUAudioChannelCount"}],"title":"AUAudioChannelCount","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AUAudioChannelCount"}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioChannelCount","abstract":[{"type":"text","text":"A number of audio channels."}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegionCompletionProc":{"abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ScheduledAudioFileRegionCompletionProc","kind":"identifier"}],"navigatorTitle":[{"text":"ScheduledAudioFileRegionCompletionProc","kind":"identifier"}],"url":"/documentation/audiotoolbox/scheduledaudiofileregioncompletionproc","type":"topic","role":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegionCompletionProc","title":"ScheduledAudioFileRegionCompletionProc","kind":"symbol"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MIDIChannelNumber":{"title":"MIDIChannelNumber","abstract":[{"text":"MIDI Channel, 0~15 (channels 1 through 16, respectively).","type":"text"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MIDIChannelNumber","kind":"identifier"}],"type":"topic","kind":"symbol","url":"/documentation/audiotoolbox/midichannelnumber","navigatorTitle":[{"text":"MIDIChannelNumber","kind":"identifier"}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MIDIChannelNumber","role":"symbol"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUMIDICIProfileChangedBlock":{"title":"AUMIDICIProfileChangedBlock","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AUMIDICIProfileChangedBlock","kind":"identifier"}],"type":"topic","kind":"symbol","url":"/documentation/audiotoolbox/aumidiciprofilechangedblock","navigatorTitle":[{"text":"AUMIDICIProfileChangedBlock","kind":"identifier"}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUMIDICIProfileChangedBlock","role":"symbol"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioObjectID":{"role":"symbol","navigatorTitle":[{"text":"AUAudioObjectID","kind":"identifier"}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioObjectID","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AUAudioObjectID","kind":"identifier"}],"url":"/documentation/audiotoolbox/auaudioobjectid","abstract":[],"kind":"symbol","title":"AUAudioObjectID"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerProc":{"role":"symbol","navigatorTitle":[{"text":"AUEventListenerProc","kind":"identifier"}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerProc","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AUEventListenerProc","kind":"identifier"}],"url":"/documentation/audiotoolbox/aueventlistenerproc","abstract":[],"kind":"symbol","title":"AUEventListenerProc"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSlice":{"url":"/documentation/audiotoolbox/scheduledaudioslice","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ScheduledAudioSlice","kind":"identifier"}],"role":"symbol","type":"topic","title":"ScheduledAudioSlice","kind":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSlice","navigatorTitle":[{"text":"ScheduledAudioSlice","kind":"identifier"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion":{"abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ScheduledAudioFileRegion","kind":"identifier"}],"navigatorTitle":[{"text":"ScheduledAudioFileRegion","kind":"identifier"}],"url":"/documentation/audiotoolbox/scheduledaudiofileregion","type":"topic","role":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion","title":"ScheduledAudioFileRegion","kind":"symbol"},"doc://com.externally.resolved.symbol/s:s6UInt32V":{"title":"UInt32","role":"symbol","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:s6UInt32V","abstract":[{"type":"text","text":"A 32-bit unsigned integer value type."}],"kind":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UInt32","kind":"identifier"}],"url":"/documentation/Swift/UInt32"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox":{"type":"topic","kind":"symbol","title":"Audio Toolbox","role":"collection","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox","abstract":[{"text":"Record or play audio, convert formats, parse audio streams, and configure your audio session.","type":"text"}],"url":"/documentation/audiotoolbox"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSliceCompletionProc":{"role":"symbol","navigatorTitle":[{"text":"ScheduledAudioSliceCompletionProc","kind":"identifier"}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSliceCompletionProc","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ScheduledAudioSliceCompletionProc","kind":"identifier"}],"url":"/documentation/audiotoolbox/scheduledaudioslicecompletionproc","abstract":[],"kind":"symbol","title":"ScheduledAudioSliceCompletionProc"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioFrameCount":{"url":"/documentation/audiotoolbox/auaudioframecount","type":"topic","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioFrameCount","title":"AUAudioFrameCount","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AUAudioFrameCount","kind":"identifier"}],"abstract":[{"text":"A number of audio sample frames.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AUAudioFrameCount","kind":"identifier"}],"kind":"symbol"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventSampleTime":{"role":"symbol","navigatorTitle":[{"text":"AUEventSampleTime","kind":"identifier"}],"title":"AUEventSampleTime","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventSampleTime","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Expresses time as a sample count."}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AUEventSampleTime","kind":"identifier"}],"url":"/documentation/audiotoolbox/aueventsampletime"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueProvider":{"navigatorTitle":[{"text":"AUImplementorValueProvider","kind":"identifier"}],"abstract":[{"text":"A block called to fetch a parameter’s current value from the audio unit implementation.","type":"text"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AUImplementorValueProvider","kind":"identifier"}],"url":"/documentation/audiotoolbox/auimplementorvalueprovider","type":"topic","role":"symbol","title":"AUImplementorValueProvider","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueProvider","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"deprecated":false,"name":"iOS","unavailable":false,"beta":false},{"deprecated":false,"name":"iPadOS","unavailable":false,"beta":false},{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false},{"deprecated":false,"name":"macOS","unavailable":false,"beta":false},{"deprecated":false,"name":"tvOS","unavailable":false,"beta":false},{"beta":false,"deprecated":false,"unavailable":false,"name":"visionOS"}],"op":"replace","path":"/metadata/platforms"},{"value":"Type Alias","op":"replace","path":"/metadata/roleHeading"},{"value":"AudioUnitPropertyID","op":"replace","path":"/metadata/title"},{"value":"typealias","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"AudioUnitPropertyID","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":[{"kind":"identifier","text":"AudioUnitPropertyID"}],"op":"replace","path":"/metadata/navigatorTitle"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.audiotoolbox/documentation/AudioToolbox"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"generated":true,"anchor":"Audio-Unit-Types","identifiers":["doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion","doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSlice","doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegionCompletionProc","doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSliceCompletionProc","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MIDIChannelNumber","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioObjectID","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUMIDICIProfileChangedBlock","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioChannelCount","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioFrameCount","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitStatus","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerProc","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerRef","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventSampleTime","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueObserver","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueProvider"],"title":"Audio Unit Types"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@T@UInt32","kind":"typeIdentifier","text":"UInt32"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioUnitPropertyID"},{"kind":"text","text":";"}]}]},"op":"replace","path":"/primaryContentSections/0"},{"value":"AUEventListenerRef","op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerRef/title"},{"value":[{"text":"AUEventListenerRef","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerRef/fragments"},{"value":[{"kind":"identifier","text":"AUEventListenerRef"}],"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerRef/navigatorTitle"},{"value":"AudioUnitPropertyID","op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitPropertyID/title"},{"value":[{"kind":"identifier","text":"AudioUnitPropertyID"}],"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitPropertyID/fragments"},{"value":[{"text":"AudioUnitPropertyID","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitPropertyID/navigatorTitle"},{"value":"AUAudioUnitStatus","op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitStatus/title"},{"value":[{"kind":"identifier","text":"AUAudioUnitStatus"}],"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitStatus/fragments"},{"value":[{"kind":"identifier","text":"AUAudioUnitStatus"}],"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitStatus/navigatorTitle"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueObserver/title","value":"AUImplementorValueObserver","op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueObserver/fragments","value":[{"text":"AUImplementorValueObserver","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueObserver/navigatorTitle","value":[{"kind":"identifier","text":"AUImplementorValueObserver"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioChannelCount/title","value":"AUAudioChannelCount","op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioChannelCount/fragments","value":[{"text":"AUAudioChannelCount","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioChannelCount/navigatorTitle","value":[{"text":"AUAudioChannelCount","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegionCompletionProc/title","value":"ScheduledAudioFileRegionCompletionProc","op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegionCompletionProc/fragments","value":[{"kind":"identifier","text":"ScheduledAudioFileRegionCompletionProc"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegionCompletionProc/navigatorTitle","value":[{"text":"ScheduledAudioFileRegionCompletionProc","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MIDIChannelNumber/title","value":"MIDIChannelNumber","op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MIDIChannelNumber/fragments","value":[{"kind":"identifier","text":"MIDIChannelNumber"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MIDIChannelNumber/navigatorTitle","value":[{"text":"MIDIChannelNumber","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUMIDICIProfileChangedBlock/title","value":"AUMIDICIProfileChangedBlock","op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUMIDICIProfileChangedBlock/fragments","value":[{"kind":"identifier","text":"AUMIDICIProfileChangedBlock"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUMIDICIProfileChangedBlock/navigatorTitle","value":[{"kind":"identifier","text":"AUMIDICIProfileChangedBlock"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioObjectID/title","value":"AUAudioObjectID","op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioObjectID/fragments","value":[{"text":"AUAudioObjectID","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioObjectID/navigatorTitle","value":[{"kind":"identifier","text":"AUAudioObjectID"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerProc/title","value":"AUEventListenerProc","op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerProc/fragments","value":[{"kind":"identifier","text":"AUEventListenerProc"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerProc/navigatorTitle","value":[{"text":"AUEventListenerProc","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioSlice/title","value":"ScheduledAudioSlice","op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioSlice/fragments","value":[{"kind":"identifier","text":"ScheduledAudioSlice"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioSlice/navigatorTitle","value":[{"kind":"identifier","text":"ScheduledAudioSlice"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegion/title","value":"ScheduledAudioFileRegion","op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegion/fragments","value":[{"kind":"identifier","text":"ScheduledAudioFileRegion"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegion/navigatorTitle","value":[{"kind":"identifier","text":"ScheduledAudioFileRegion"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioSliceCompletionProc/title","value":"ScheduledAudioSliceCompletionProc","op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioSliceCompletionProc/fragments","value":[{"text":"ScheduledAudioSliceCompletionProc","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioSliceCompletionProc/navigatorTitle","value":[{"kind":"identifier","text":"ScheduledAudioSliceCompletionProc"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioFrameCount/title","value":"AUAudioFrameCount","op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioFrameCount/fragments","value":[{"text":"AUAudioFrameCount","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioFrameCount/navigatorTitle","value":[{"text":"AUAudioFrameCount","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventSampleTime/title","value":"AUEventSampleTime","op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventSampleTime/fragments","value":[{"text":"AUEventSampleTime","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventSampleTime/navigatorTitle","value":[{"text":"AUEventSampleTime","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueProvider/title","value":"AUImplementorValueProvider","op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueProvider/fragments","value":[{"text":"AUImplementorValueProvider","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueProvider/navigatorTitle","value":[{"text":"AUImplementorValueProvider","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}