{
  "abstract": [
    {
      "text": "An audio unit’s audio level at a particular frequency.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitFrequencyResponseBin"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@AudioUnitFrequencyResponseBin",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AudioUnitFrequencyResponseBin"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AudioUnitFrequencyResponseBin"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AudioUnitFrequencyResponseBin"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioUnitFrequencyResponseBin"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An array of AudioUnitFrequencyResponseBin are passed in to kAudioUnitProperty_FrequencyResponse with the mFrequency field filled in. The array is returned with the mMagnitude fields filled in. If fewer than kNumberOfResponseFrequencies are needed, then the first unused bin should be marked with a negative frequency.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitConnection": {
      "abstract": [
        {
          "text": "An audio unit source-to-destination connection specification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitConnection"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitConnection"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitConnection",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitconnection"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEvent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitEvent"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitEvent"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitEvent",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitevent"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitExternalBuffer": {
      "abstract": [
        {
          "text": "Allows an audio unit host application to tell an audio unit to use a specified buffer for its input callback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitExternalBuffer"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitExternalBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitExternalBuffer"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitExternalBuffer",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitexternalbuffer"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitFrequencyResponseBin": {
      "abstract": [
        {
          "text": "An audio unit’s audio level at a particular frequency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitFrequencyResponseBin"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitFrequencyResponseBin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitFrequencyResponseBin"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitFrequencyResponseBin",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitfrequencyresponsebin"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitFrequencyResponseBin/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitFrequencyResponseBin/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitfrequencyresponsebin/init()"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitFrequencyResponseBin/init(mFrequency:mMagnitude:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "mFrequency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float64a",
          "text": "Float64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mMagnitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float64a",
          "text": "Float64"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitFrequencyResponseBin/init(mFrequency:mMagnitude:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(mFrequency:mMagnitude:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitfrequencyresponsebin/init(mfrequency:mmagnitude:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitFrequencyResponseBin/mFrequency": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mFrequency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float64a",
          "text": "Float64"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitFrequencyResponseBin/mFrequency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mFrequency"
        }
      ],
      "role": "symbol",
      "title": "mFrequency",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitfrequencyresponsebin/mfrequency"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitFrequencyResponseBin/mMagnitude": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mMagnitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float64a",
          "text": "Float64"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitFrequencyResponseBin/mMagnitude",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mMagnitude"
        }
      ],
      "role": "symbol",
      "title": "mMagnitude",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitfrequencyresponsebin/mmagnitude"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitMIDIControlMapping": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitMIDIControlMapping"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitMIDIControlMapping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitMIDIControlMapping"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitMIDIControlMapping",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitmidicontrolmapping"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitMeterClipping": {
      "abstract": [
        {
          "text": "Audio clipping that has occurred in a mixer unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitMeterClipping"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitMeterClipping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitMeterClipping"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitMeterClipping",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitmeterclipping"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitOtherPluginDesc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitOtherPluginDesc"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitOtherPluginDesc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitOtherPluginDesc"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitOtherPluginDesc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitotherplugindesc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameter": {
      "abstract": [
        {
          "text": "An adjustable audio unit attribute such as volume, pitch, or filter cutoff frequency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameter"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameter"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterEvent": {
      "abstract": [
        {
          "text": "A scheduled change to an audio unit parameter’s value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterEvent"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterEvent"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterEvent",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterevent"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterHistoryInfo": {
      "abstract": [
        {
          "text": "The suggested update rate and history duration for parameters which have the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_PlotHistory",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " flag set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterHistoryInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterHistoryInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterHistoryInfo"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterHistoryInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterhistoryinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterIDName": {
      "abstract": [
        {
          "text": "A type definition for a data type that defines the short version of the name for an audio unit parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterIDName"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterIDName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterIDName"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterIDName",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteridname"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterInfo"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterNameInfo": {
      "abstract": [
        {
          "text": "A short version of the name for an audio unit parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterNameInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterNameInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterNameInfo"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterNameInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameternameinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions": {
      "abstract": [
        {
          "text": "Value options for audio unit parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterOptions",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteroptions"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_PlotHistory": {
      "abstract": [
        {
          "text": "If set, getting the ",
          "type": "text"
        },
        {
          "code": "kAudioUnitProperty_ParameterHistoryInfo",
          "type": "codeVoice"
        },
        {
          "text": " property fills out the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterHistoryInfo",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " struct containing the recommended update rate and history duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flag_PlotHistory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_PlotHistory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterFlag_PlotHistory"
        }
      ],
      "role": "symbol",
      "title": "flag_PlotHistory",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteroptions/flag_plothistory"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterStringFromValue": {
      "abstract": [
        {
          "text": "A string representation of a parameter’s value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterStringFromValue"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterStringFromValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterStringFromValue"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterStringFromValue",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterstringfromvalue"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterValueFromString": {
      "abstract": [
        {
          "text": "A parameter’s value based on a string representation of the value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterValueFromString"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterValueFromString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterValueFromString"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterValueFromString",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparametervaluefromstring"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitConnection",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEvent",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitExternalBuffer",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitMeterClipping",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitMIDIControlMapping",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitOtherPluginDesc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterEvent",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterHistoryInfo",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterNameInfo",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterIDName",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterInfo",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterStringFromValue",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterValueFromString"
      ],
      "title": "Structures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitFrequencyResponseBin/init()",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitFrequencyResponseBin/init(mFrequency:mMagnitude:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitFrequencyResponseBin/mFrequency",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitFrequencyResponseBin/mMagnitude"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AudioUnitFrequencyResponseBin"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitFrequencyResponseBin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitFrequencyResponseBin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitFrequencyResponseBin/mFrequency",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitFrequencyResponseBin/mMagnitude"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Structures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitConnection",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEvent",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitExternalBuffer",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitMeterClipping",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitMIDIControlMapping",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitOtherPluginDesc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterEvent",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterHistoryInfo",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterNameInfo",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterIDName",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterInfo",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterStringFromValue",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterValueFromString"
              ],
              "title": "Structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AudioUnitFrequencyResponseBin"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitConnection/title",
          "value": "AudioUnitConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitConnection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitOtherPluginDesc/title",
          "value": "AudioUnitOtherPluginDesc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitOtherPluginDesc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitOtherPluginDesc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitOtherPluginDesc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitOtherPluginDesc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterNameInfo/title",
          "value": "AudioUnitParameterNameInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterNameInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterNameInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterNameInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterNameInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterValueFromString/title",
          "value": "AudioUnitParameterValueFromString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterValueFromString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterValueFromString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterValueFromString/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterValueFromString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_PlotHistory/title",
          "value": "kAudioUnitParameterFlag_PlotHistory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_PlotHistory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterFlag_PlotHistory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEvent/title",
          "value": "AudioUnitEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterHistoryInfo/title",
          "value": "AudioUnitParameterHistoryInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterHistoryInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterHistoryInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterHistoryInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterHistoryInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitFrequencyResponseBin/title",
          "value": "AudioUnitFrequencyResponseBin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitFrequencyResponseBin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitFrequencyResponseBin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitFrequencyResponseBin/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitFrequencyResponseBin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameter/title",
          "value": "AudioUnitParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions/title",
          "value": "AudioUnitParameterOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitFrequencyResponseBin~1mMagnitude/title",
          "value": "mMagnitude"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitFrequencyResponseBin~1mMagnitude/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mMagnitude"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitExternalBuffer/title",
          "value": "AudioUnitExternalBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitExternalBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitExternalBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitExternalBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitExternalBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitMIDIControlMapping/title",
          "value": "AudioUnitMIDIControlMapping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitMIDIControlMapping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitMIDIControlMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitMIDIControlMapping/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitMIDIControlMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterStringFromValue/title",
          "value": "AudioUnitParameterStringFromValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterStringFromValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterStringFromValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterStringFromValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterStringFromValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterIDName/title",
          "value": "AudioUnitParameterIDName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterIDName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterIDName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterIDName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterIDName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterEvent/title",
          "value": "AudioUnitParameterEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterInfo/title",
          "value": "AudioUnitParameterInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitFrequencyResponseBin~1mFrequency/title",
          "value": "mFrequency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitFrequencyResponseBin~1mFrequency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mFrequency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitMeterClipping/title",
          "value": "AudioUnitMeterClipping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitMeterClipping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitMeterClipping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitMeterClipping/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitMeterClipping"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/audiounitfrequencyresponsebin"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/audiounitfrequencyresponsebin"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
