{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerCreate(_:_:_:_:_:_:_:)"},"kind":"symbol","variants":[{"paths":["/documentation/audiotoolbox/aueventlistenercreate(_:_:_:_:_:_:_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/audiotoolbox/aueventlistenercreate(_:_:_:_:_:_:_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.audiotoolbox/documentation/AudioToolbox"]]},"metadata":{"role":"symbol","title":"AUEventListenerCreate(_:_:_:_:_:_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AUEventListenerCreate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AUEventListenerProc","preciseIdentifier":"c:@T@AUEventListenerProc","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"CFRunLoop","preciseIdentifier":"c:@T@CFRunLoopRef"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"CFString","preciseIdentifier":"c:@T@CFStringRef"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Float32","preciseIdentifier":"s:s7Float32a"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Float32","preciseIdentifier":"s:s7Float32a"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"AUEventListenerRef","preciseIdentifier":"c:@T@AUEventListenerRef"},{"kind":"text","text":"?>) -> "},{"kind":"typeIdentifier","text":"OSStatus","preciseIdentifier":"c:@T@OSStatus"}],"externalID":"c:@F@AUEventListenerCreate","symbolKind":"func","navigatorTitle":[{"kind":"identifier","text":"AUEventListenerCreate"}],"roleHeading":"Function","modules":[{"name":"Audio Toolbox"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"6.0"},{"beta":false,"unavailable":false,"name":"iPadOS","deprecated":false,"introducedAt":"6.0"},{"beta":false,"unavailable":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.1"},{"beta":false,"unavailable":false,"name":"macOS","deprecated":false,"introducedAt":"10.3"},{"beta":false,"unavailable":false,"name":"tvOS","deprecated":false,"introducedAt":"9.0"},{"beta":false,"unavailable":false,"name":"visionOS","deprecated":false,"introducedAt":"1.0"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"seeAlsoSections":[{"title":"Responding to Events","generated":true,"anchor":"Responding-to-Events","identifiers":["doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerCreateWithDispatchQueue(_:_:_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUListenerDispose(_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerNotify(_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerAddEventType(_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerRemoveEventType(_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUListenerAddParameter(_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUListenerRemoveParameter(_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerBlock"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AUEventListenerCreate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"inProc"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerProc","kind":"typeIdentifier","text":"AUEventListenerProc","preciseIdentifier":"c:@T@AUEventListenerProc"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"inUserData"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:Sv","kind":"typeIdentifier","text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"inRunLoop"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/c:@T@CFRunLoopRef","kind":"typeIdentifier","text":"CFRunLoop","preciseIdentifier":"c:@T@CFRunLoopRef"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"inRunLoopMode"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/c:@T@CFStringRef","kind":"typeIdentifier","text":"CFString","preciseIdentifier":"c:@T@CFStringRef"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"inNotificationInterval"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:s7Float32a","kind":"typeIdentifier","text":"Float32","preciseIdentifier":"s:s7Float32a"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"inValueChangeGranularity"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:s7Float32a","kind":"typeIdentifier","text":"Float32","preciseIdentifier":"s:s7Float32a"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"outListener"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerRef","kind":"typeIdentifier","text":"AUEventListenerRef","preciseIdentifier":"c:@T@AUEventListenerRef"},{"kind":"text","text":"?>) -> "},{"kind":"typeIdentifier","text":"OSStatus","preciseIdentifier":"c:@T@OSStatus"}],"languages":["swift"]}]}],"references":{"doc://com.externally.resolved.symbol/c:@T@CFRunLoopRef":{"abstract":[{"text":"A reference to a run loop object.","type":"text"}],"type":"topic","identifier":"doc://com.externally.resolved.symbol/c:@T@CFRunLoopRef","kind":"symbol","role":"symbol","url":"/documentation/corefoundation/cfrunloop","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"CFRunLoop"}],"title":"CFRunLoop"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerProc":{"role":"symbol","navigatorTitle":[{"text":"AUEventListenerProc","kind":"identifier"}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerProc","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AUEventListenerProc","kind":"identifier"}],"url":"/documentation/audiotoolbox/aueventlistenerproc","abstract":[],"kind":"symbol","title":"AUEventListenerProc"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUListenerRemoveParameter(_:_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"AUListenerRemoveParameter"}],"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AUListenerRemoveParameter"},{"kind":"text","text":"("},{"text":"AUParameterListenerRef","preciseIdentifier":"c:@T@AUParameterListenerRef","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:SP","text":"UnsafePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@S@AudioUnitParameter","text":"AudioUnitParameter","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","text":"OSStatus","preciseIdentifier":"c:@T@OSStatus"}],"kind":"symbol","role":"symbol","title":"AUListenerRemoveParameter(_:_:_:)","type":"topic","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUListenerRemoveParameter(_:_:_:)","url":"/documentation/audiotoolbox/aulistenerremoveparameter(_:_:_:)"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerRemoveEventType(_:_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"AUEventListenerRemoveEventType"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerRemoveEventType(_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AUEventListenerRemoveEventType"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AUEventListenerRef","text":"AUEventListenerRef"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv"},{"kind":"text","text":"?, "},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@S@AudioUnitEvent","kind":"typeIdentifier","text":"AudioUnitEvent"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"OSStatus","preciseIdentifier":"c:@T@OSStatus"}],"title":"AUEventListenerRemoveEventType(_:_:_:)","kind":"symbol","abstract":[],"url":"/documentation/audiotoolbox/aueventlistenerremoveeventtype(_:_:_:)"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerCreateWithDispatchQueue(_:_:_:_:_:)":{"navigatorTitle":[{"text":"AUEventListenerCreateWithDispatchQueue","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerCreateWithDispatchQueue(_:_:_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AUEventListenerCreateWithDispatchQueue"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@T@AUEventListenerRef","text":"AUEventListenerRef","kind":"typeIdentifier"},{"kind":"text","text":"?>, "},{"kind":"typeIdentifier","text":"Float32","preciseIdentifier":"s:s7Float32a"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Float32","preciseIdentifier":"s:s7Float32a"},{"text":", ","kind":"text"},{"text":"dispatch_queue_t","preciseIdentifier":"c:@T@dispatch_queue_t","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"AUEventListenerBlock","preciseIdentifier":"c:@T@AUEventListenerBlock","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"OSStatus","preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier"}],"title":"AUEventListenerCreateWithDispatchQueue(_:_:_:_:_:)","kind":"symbol","abstract":[],"url":"/documentation/audiotoolbox/aueventlistenercreatewithdispatchqueue(_:_:_:_:_:)"},"doc://com.externally.resolved.symbol/c:@T@Float32":{"title":"Float32","abstract":[{"text":"Convenience type that represent a 32-bit floating point number","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@T@Float32","url":"/documentation/kernel/float32","type":"topic"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUListenerAddParameter(_:_:_:)":{"url":"/documentation/audiotoolbox/aulisteneraddparameter(_:_:_:)","navigatorTitle":[{"text":"AUListenerAddParameter","kind":"identifier"}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUListenerAddParameter(_:_:_:)","title":"AUListenerAddParameter(_:_:_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AUListenerAddParameter","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AUParameterListenerRef","preciseIdentifier":"c:@T@AUParameterListenerRef"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:SP","text":"UnsafePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@S@AudioUnitParameter","text":"AudioUnitParameter","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"text":"OSStatus","kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus"}],"kind":"symbol","type":"topic","abstract":[]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUListenerDispose(_:)":{"url":"/documentation/audiotoolbox/aulistenerdispose(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AUListenerDispose"},{"kind":"text","text":"("},{"text":"AUParameterListenerRef","preciseIdentifier":"c:@T@AUParameterListenerRef","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"OSStatus","preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier"}],"title":"AUListenerDispose(_:)","navigatorTitle":[{"text":"AUListenerDispose","kind":"identifier"}],"role":"symbol","abstract":[],"kind":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUListenerDispose(_:)","type":"topic"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerBlock":{"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerBlock","kind":"symbol","url":"/documentation/audiotoolbox/aueventlistenerblock","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"AUEventListenerBlock"}],"navigatorTitle":[{"kind":"identifier","text":"AUEventListenerBlock"}],"title":"AUEventListenerBlock","abstract":[]},"doc://com.externally.resolved.symbol/s:Sv":{"role":"symbol","title":"UnsafeMutableRawPointer","identifier":"doc://com.externally.resolved.symbol/s:Sv","type":"topic","kind":"symbol","abstract":[{"text":"A raw pointer for accessing and manipulating untyped data.","type":"text"}],"fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UnsafeMutableRawPointer","kind":"identifier"}],"url":"/documentation/Swift/UnsafeMutableRawPointer"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerNotify(_:_:_:)":{"url":"/documentation/audiotoolbox/aueventlistenernotify(_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AUEventListenerNotify"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AUEventListenerRef","preciseIdentifier":"c:@T@AUEventListenerRef"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv"},{"kind":"text","text":"?, "},{"text":"UnsafePointer","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"AudioUnitEvent","preciseIdentifier":"c:@S@AudioUnitEvent","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"c:@T@OSStatus","text":"OSStatus","kind":"typeIdentifier"}],"title":"AUEventListenerNotify(_:_:_:)","navigatorTitle":[{"text":"AUEventListenerNotify","kind":"identifier"}],"role":"symbol","abstract":[],"kind":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerNotify(_:_:_:)","type":"topic"},"doc://com.externally.resolved.symbol/s:Sp":{"url":"/documentation/Swift/UnsafeMutablePointer","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Pointee","kind":"genericParameter"},{"text":"> ","kind":"text"},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Pointee","kind":"typeIdentifier"},{"text":" : ~Copyable","kind":"text"}],"type":"topic","title":"UnsafeMutablePointer","identifier":"doc://com.externally.resolved.symbol/s:Sp","abstract":[{"text":"A pointer for accessing and manipulating data of a specific type.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/s:s7Float32a":{"title":"Float32","abstract":[{"type":"text","text":"A 32-bit floating point type."}],"identifier":"doc://com.externally.resolved.symbol/s:s7Float32a","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"Float32"},{"kind":"text","text":" = "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"type":"topic","role":"symbol","kind":"symbol","url":"/documentation/Swift/Float32"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerCreate(_:_:_:_:_:_:_:)":{"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerCreate(_:_:_:_:_:_:_:)","type":"topic","url":"/documentation/audiotoolbox/aueventlistenercreate(_:_:_:_:_:_:_:)","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AUEventListenerCreate","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@AUEventListenerProc","text":"AUEventListenerProc","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"CFRunLoop","preciseIdentifier":"c:@T@CFRunLoopRef"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"CFString","preciseIdentifier":"c:@T@CFStringRef"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:s7Float32a","text":"Float32"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s7Float32a","text":"Float32"},{"kind":"text","text":", "},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"AUEventListenerRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@AUEventListenerRef"},{"text":"?>) -> ","kind":"text"},{"text":"OSStatus","kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus"}],"title":"AUEventListenerCreate(_:_:_:_:_:_:_:)","navigatorTitle":[{"text":"AUEventListenerCreate","kind":"identifier"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox":{"type":"topic","kind":"symbol","title":"Audio Toolbox","role":"collection","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox","abstract":[{"text":"Record or play audio, convert formats, parse audio streams, and configure your audio session.","type":"text"}],"url":"/documentation/audiotoolbox"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerAddEventType(_:_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"AUEventListenerAddEventType"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerAddEventType(_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AUEventListenerAddEventType"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AUEventListenerRef","preciseIdentifier":"c:@T@AUEventListenerRef"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"AudioUnitEvent","preciseIdentifier":"c:@S@AudioUnitEvent"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"OSStatus","preciseIdentifier":"c:@T@OSStatus"}],"title":"AUEventListenerAddEventType(_:_:_:)","kind":"symbol","abstract":[],"url":"/documentation/audiotoolbox/aueventlisteneraddeventtype(_:_:_:)"},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","type":"topic","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","role":"overview"},"doc://com.externally.resolved.symbol/c:@T@CFStringRef":{"url":"/documentation/corefoundation/cfstring","fragments":[{"text":"class ","kind":"text"},{"text":"CFString","kind":"identifier"}],"type":"topic","title":"CFString","identifier":"doc://com.externally.resolved.symbol/c:@T@CFStringRef","abstract":[{"text":"A reference to a CFString object.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerRef":{"kind":"symbol","url":"/documentation/audiotoolbox/aueventlistenerref","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"AUEventListenerRef"}],"navigatorTitle":[{"kind":"identifier","text":"AUEventListenerRef"}],"title":"AUEventListenerRef","abstract":[],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerRef","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"beta":false,"name":"iOS","deprecated":false,"introducedAt":"6.0","unavailable":false},{"beta":false,"name":"iPadOS","deprecated":false,"introducedAt":"6.0","unavailable":false},{"beta":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.1","unavailable":false},{"unavailable":false,"beta":false,"name":"macOS","introducedAt":"10.3","deprecated":false},{"unavailable":false,"beta":false,"name":"tvOS","introducedAt":"9.0","deprecated":false},{"unavailable":false,"beta":false,"name":"visionOS","introducedAt":"1.0","deprecated":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Function"},{"path":"/metadata/title","op":"replace","value":"AUEventListenerCreate"},{"path":"/metadata/symbolKind","op":"replace","value":"func"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"identifier","text":"AUEventListenerCreate"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.audiotoolbox/documentation/AudioToolbox"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"title":"Responding to Events","anchor":"Responding-to-Events","generated":true,"identifiers":["doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerCreateWithDispatchQueue(_:_:_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUListenerDispose(_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerNotify(_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerAddEventType(_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerRemoveEventType(_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUListenerAddParameter(_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUListenerRemoveParameter(_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerBlock"]}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus","text":"OSStatus"},{"kind":"text","text":" "},{"kind":"identifier","text":"AUEventListenerCreate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AUEventListenerProc","text":"AUEventListenerProc","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerProc"},{"kind":"text","text":" "},{"kind":"internalParam","text":"inProc"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"inUserData"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CFRunLoopRef","text":"CFRunLoopRef","identifier":"doc://com.externally.resolved.symbol/c:@T@CFRunLoopRef"},{"kind":"text","text":" "},{"kind":"internalParam","text":"inRunLoop"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CFStringRef","text":"CFStringRef","identifier":"doc://com.externally.resolved.symbol/c:@T@CFStringRef"},{"kind":"text","text":" "},{"kind":"internalParam","text":"inRunLoopMode"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@Float32","text":"Float32","identifier":"doc://com.externally.resolved.symbol/c:@T@Float32"},{"kind":"text","text":" "},{"kind":"internalParam","text":"inNotificationInterval"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@Float32","text":"Float32","identifier":"doc://com.externally.resolved.symbol/c:@T@Float32"},{"kind":"text","text":" "},{"kind":"internalParam","text":"inValueChangeGranularity"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AUEventListenerRef","text":"AUEventListenerRef","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerRef"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"outListener"},{"kind":"text","text":");"}]}]}},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFRunLoopRef/title","value":"CFRunLoopRef"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerProc/title","value":"AUEventListenerProc"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerProc/fragments","value":[{"text":"AUEventListenerProc","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerProc/navigatorTitle","value":[{"kind":"identifier","text":"AUEventListenerProc"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUListenerRemoveParameter(_:_:_:)/title","value":"AUListenerRemoveParameter"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUListenerRemoveParameter(_:_:_:)/fragments","value":[{"text":"AUListenerRemoveParameter","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerRemoveEventType(_:_:_:)/title","value":"AUEventListenerRemoveEventType"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerRemoveEventType(_:_:_:)/fragments","value":[{"kind":"identifier","text":"AUEventListenerRemoveEventType"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerCreateWithDispatchQueue(_:_:_:_:_:)/title","value":"AUEventListenerCreateWithDispatchQueue"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerCreateWithDispatchQueue(_:_:_:_:_:)/fragments","value":[{"text":"AUEventListenerCreateWithDispatchQueue","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUListenerAddParameter(_:_:_:)/title","value":"AUListenerAddParameter"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUListenerAddParameter(_:_:_:)/fragments","value":[{"text":"AUListenerAddParameter","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUListenerDispose(_:)/title","value":"AUListenerDispose"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUListenerDispose(_:)/fragments","value":[{"kind":"identifier","text":"AUListenerDispose"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerBlock/title","value":"AUEventListenerBlock"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerBlock/fragments","value":[{"text":"AUEventListenerBlock","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerBlock/navigatorTitle","value":[{"text":"AUEventListenerBlock","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerNotify(_:_:_:)/title","value":"AUEventListenerNotify"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerNotify(_:_:_:)/fragments","value":[{"text":"AUEventListenerNotify","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerCreate(_:_:_:_:_:_:_:)/title","value":"AUEventListenerCreate"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerCreate(_:_:_:_:_:_:_:)/fragments","value":[{"text":"AUEventListenerCreate","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerAddEventType(_:_:_:)/title","value":"AUEventListenerAddEventType"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerAddEventType(_:_:_:)/fragments","value":[{"kind":"identifier","text":"AUEventListenerAddEventType"}]},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title","value":"CFStringRef"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerRef/title","value":"AUEventListenerRef"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerRef/fragments","value":[{"text":"AUEventListenerRef","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerRef/navigatorTitle","value":[{"kind":"identifier","text":"AUEventListenerRef"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}