{
  "abstract": [
    {
      "text": "Deprecated in OS X v10.5. Instead, use ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphGetNodeInteractions(_:_:_:_:)",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphGetNodeConnections"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@AUGraphGetNodeConnections",
    "fragments": [
      {
        "kind": "identifier",
        "text": "AUGraphGetNodeConnections"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AUGraphGetNodeConnections"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.5",
        "introducedAt": "10.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "AUGraphGetNodeConnections"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AUGraphGetNodeConnections"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraph",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AUGraph",
              "text": "AUGraph"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inGraph"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUNode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AUNode",
              "text": "AUNode"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inNode"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitNodeConnection",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@AudioUnitNodeConnection",
              "text": "AudioUnitNodeConnection"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "outConnections"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@UInt32",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "ioNumConnections"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraph": {
      "abstract": [
        {
          "text": "An opaque type representing an audio processing graph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUGraph"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraph",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUGraph"
        }
      ],
      "role": "symbol",
      "title": "AUGraph",
      "type": "topic",
      "url": "/documentation/audiotoolbox/augraph"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphAddNode(_:_:_:)": {
      "abstract": [
        {
          "text": "Adds a node to an audio processing graph.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUGraphAddNode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUGraph",
          "text": "AUGraph"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioComponentDescription",
          "text": "AudioComponentDescription"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUNode",
          "text": "AUNode"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphAddNode(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUGraphAddNode"
        }
      ],
      "role": "symbol",
      "title": "AUGraphAddNode(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/augraphaddnode(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphAddRenderNotify(_:_:_:)": {
      "abstract": [
        {
          "text": "Adds a render notification callback to an audio processing graph.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUGraphAddRenderNotify"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUGraph",
          "text": "AUGraph"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AURenderCallback",
          "text": "AURenderCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphAddRenderNotify(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUGraphAddRenderNotify"
        }
      ],
      "role": "symbol",
      "title": "AUGraphAddRenderNotify(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/augraphaddrendernotify(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphClearConnections(_:)": {
      "abstract": [
        {
          "text": "Clears all of the interactions in an audio unit processing graph.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUGraphClearConnections"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUGraph",
          "text": "AUGraph"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphClearConnections(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUGraphClearConnections"
        }
      ],
      "role": "symbol",
      "title": "AUGraphClearConnections(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/augraphclearconnections(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphClose(_:)": {
      "abstract": [
        {
          "text": "Closes an audio unit processing graph.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUGraphClose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUGraph",
          "text": "AUGraph"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphClose(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUGraphClose"
        }
      ],
      "role": "symbol",
      "title": "AUGraphClose(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/augraphclose(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphConnectNodeInput(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Connects one node’s output to another node’s input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUGraphConnectNodeInput"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUGraph",
          "text": "AUGraph"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUNode",
          "text": "AUNode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUNode",
          "text": "AUNode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphConnectNodeInput(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUGraphConnectNodeInput"
        }
      ],
      "role": "symbol",
      "title": "AUGraphConnectNodeInput(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/augraphconnectnodeinput(_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphCountNodeConnections": {
      "abstract": [
        {
          "text": "Deprecated in OS X v10.5. Instead, use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphCountNodeInteractions(_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AUGraphCountNodeConnections"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphCountNodeConnections",
      "kind": "symbol",
      "role": "symbol",
      "title": "AUGraphCountNodeConnections",
      "type": "topic",
      "url": "/documentation/audiotoolbox/augraphcountnodeconnections"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphCountNodeInteractions(_:_:_:)": {
      "abstract": [
        {
          "text": "Retrieves the number of interactions of an audio processing graph’s node.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUGraphCountNodeInteractions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUGraph",
          "text": "AUGraph"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUNode",
          "text": "AUNode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphCountNodeInteractions(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUGraphCountNodeInteractions"
        }
      ],
      "role": "symbol",
      "title": "AUGraphCountNodeInteractions(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/augraphcountnodeinteractions(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphDisconnectNodeInput(_:_:_:)": {
      "abstract": [
        {
          "text": "Disconnects a node’s input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUGraphDisconnectNodeInput"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUGraph",
          "text": "AUGraph"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUNode",
          "text": "AUNode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphDisconnectNodeInput(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUGraphDisconnectNodeInput"
        }
      ],
      "role": "symbol",
      "title": "AUGraphDisconnectNodeInput(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/augraphdisconnectnodeinput(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphGetCPULoad(_:_:)": {
      "abstract": [
        {
          "text": "Obtains the short-term running average of the current CPU load of the audio processing graph.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUGraphGetCPULoad"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUGraph",
          "text": "AUGraph"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float32a",
          "text": "Float32"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphGetCPULoad(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUGraphGetCPULoad"
        }
      ],
      "role": "symbol",
      "title": "AUGraphGetCPULoad(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/augraphgetcpuload(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphGetConnectionInfo": {
      "abstract": [
        {
          "text": "Deprecated in OS X v10.5. Instead, use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphGetInteractionInfo(_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AUGraphGetConnectionInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphGetConnectionInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "AUGraphGetConnectionInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/augraphgetconnectioninfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphGetIndNode(_:_:_:)": {
      "abstract": [
        {
          "text": "Gets the audio processing graph node at a given index.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUGraphGetIndNode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUGraph",
          "text": "AUGraph"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUNode",
          "text": "AUNode"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphGetIndNode(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUGraphGetIndNode"
        }
      ],
      "role": "symbol",
      "title": "AUGraphGetIndNode(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/augraphgetindnode(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphGetInteractionInfo(_:_:_:)": {
      "abstract": [
        {
          "text": "Retrieves information about a particular interaction in an audio processing graph.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUGraphGetInteractionInfo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUGraph",
          "text": "AUGraph"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AUNodeInteraction",
          "text": "AUNodeInteraction"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphGetInteractionInfo(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUGraphGetInteractionInfo"
        }
      ],
      "role": "symbol",
      "title": "AUGraphGetInteractionInfo(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/augraphgetinteractioninfo(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphGetMaxCPULoad(_:_:)": {
      "abstract": [
        {
          "text": "Obtains the maximum CPU load of an audio processing graph since this call was last made or since the graph was last started.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUGraphGetMaxCPULoad"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUGraph",
          "text": "AUGraph"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float32a",
          "text": "Float32"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphGetMaxCPULoad(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUGraphGetMaxCPULoad"
        }
      ],
      "role": "symbol",
      "title": "AUGraphGetMaxCPULoad(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/augraphgetmaxcpuload(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphGetNodeConnections": {
      "abstract": [
        {
          "text": "Deprecated in OS X v10.5. Instead, use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphGetNodeInteractions(_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AUGraphGetNodeConnections"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphGetNodeConnections",
      "kind": "symbol",
      "role": "symbol",
      "title": "AUGraphGetNodeConnections",
      "type": "topic",
      "url": "/documentation/audiotoolbox/augraphgetnodeconnections"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphGetNodeCount(_:_:)": {
      "abstract": [
        {
          "text": "The number of nodes in an audio processing graph.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUGraphGetNodeCount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUGraph",
          "text": "AUGraph"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphGetNodeCount(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUGraphGetNodeCount"
        }
      ],
      "role": "symbol",
      "title": "AUGraphGetNodeCount(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/augraphgetnodecount(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphGetNodeInfo": {
      "abstract": [
        {
          "text": "Deprecated in OS X v10.5. Instead, use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphNodeInfo(_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AUGraphGetNodeInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphGetNodeInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "AUGraphGetNodeInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/augraphgetnodeinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphGetNodeInteractions(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Retrieves information about the interactions in an audio processing graph for a given node.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUGraphGetNodeInteractions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUGraph",
          "text": "AUGraph"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUNode",
          "text": "AUNode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AUNodeInteraction",
          "text": "AUNodeInteraction"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphGetNodeInteractions(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUGraphGetNodeInteractions"
        }
      ],
      "role": "symbol",
      "title": "AUGraphGetNodeInteractions(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/augraphgetnodeinteractions(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphNodeInfo(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns information about a node object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUGraphNodeInfo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUGraph",
          "text": "AUGraph"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUNode",
          "text": "AUNode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioComponentDescription",
          "text": "AudioComponentDescription"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnit",
          "text": "AudioUnit"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphNodeInfo(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUGraphNodeInfo"
        }
      ],
      "role": "symbol",
      "title": "AUGraphNodeInfo(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/augraphnodeinfo(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUNode": {
      "abstract": [
        {
          "text": "A member of an audio processing graph, associated with an audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUNode"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUNode"
        }
      ],
      "role": "symbol",
      "title": "AUNode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aunode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitNodeConnection": {
      "abstract": [
        {
          "text": "A connection between two node objects in an audio processing graph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitNodeConnection"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitNodeConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitNodeConnection"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitNodeConnection",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitnodeconnection"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Audio-Unit-Processing-Graph-Services-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphAddNode(_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphAddRenderNotify(_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphClearConnections(_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphClose(_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphConnectNodeInput(_:_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphCountNodeConnections",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphCountNodeInteractions(_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphDisconnectNodeInput(_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphGetConnectionInfo",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphGetCPULoad(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphGetIndNode(_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphGetInteractionInfo(_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphGetMaxCPULoad(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphGetNodeCount(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUGraphGetNodeInfo"
      ],
      "title": "Audio Unit Processing Graph Services Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUGraph/title",
          "value": "AUGraph"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUGraph/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUGraph/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUGraphGetInteractionInfo(_:_:_:)/title",
          "value": "AUGraphGetInteractionInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUGraphGetInteractionInfo(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGraphGetInteractionInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUGraphDisconnectNodeInput(_:_:_:)/title",
          "value": "AUGraphDisconnectNodeInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUGraphDisconnectNodeInput(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGraphDisconnectNodeInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUGraphGetCPULoad(_:_:)/title",
          "value": "AUGraphGetCPULoad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUGraphGetCPULoad(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGraphGetCPULoad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitNodeConnection/title",
          "value": "AudioUnitNodeConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitNodeConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitNodeConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitNodeConnection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitNodeConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUGraphCountNodeInteractions(_:_:_:)/title",
          "value": "AUGraphCountNodeInteractions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUGraphCountNodeInteractions(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGraphCountNodeInteractions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUNode/title",
          "value": "AUNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUGraphGetNodeInteractions(_:_:_:_:)/title",
          "value": "AUGraphGetNodeInteractions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUGraphGetNodeInteractions(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGraphGetNodeInteractions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUGraphConnectNodeInput(_:_:_:_:_:)/title",
          "value": "AUGraphConnectNodeInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUGraphConnectNodeInput(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGraphConnectNodeInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUGraphGetIndNode(_:_:_:)/title",
          "value": "AUGraphGetIndNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUGraphGetIndNode(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGraphGetIndNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUGraphNodeInfo(_:_:_:_:)/title",
          "value": "AUGraphNodeInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUGraphNodeInfo(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGraphNodeInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUGraphClose(_:)/title",
          "value": "AUGraphClose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUGraphClose(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGraphClose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUGraphGetMaxCPULoad(_:_:)/title",
          "value": "AUGraphGetMaxCPULoad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUGraphGetMaxCPULoad(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGraphGetMaxCPULoad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUGraphAddRenderNotify(_:_:_:)/title",
          "value": "AUGraphAddRenderNotify"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUGraphAddRenderNotify(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGraphAddRenderNotify"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUGraphGetNodeCount(_:_:)/title",
          "value": "AUGraphGetNodeCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUGraphGetNodeCount(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGraphGetNodeCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUGraphAddNode(_:_:_:)/title",
          "value": "AUGraphAddNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUGraphAddNode(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGraphAddNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUGraphClearConnections(_:)/title",
          "value": "AUGraphClearConnections"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUGraphClearConnections(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGraphClearConnections"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/augraphgetnodeconnections"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
