{
  "abstract": [
    {
      "text": "An object that represents a node in an audio unit’s parameter tree.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AUParameterNode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AUParameterNode"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AUParameterNode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AUParameterNode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AUParameterNode"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Nodes are instances of either an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterGroup",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorDisplayNameWithLengthCallback": {
      "abstract": [
        {
          "text": "A block called to obtain a parameter node’s display name, possibly truncated to a desired length.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUImplementorDisplayNameWithLengthCallback"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorDisplayNameWithLengthCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUImplementorDisplayNameWithLengthCallback"
        }
      ],
      "role": "symbol",
      "title": "AUImplementorDisplayNameWithLengthCallback",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auimplementordisplaynamewithlengthcallback"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorStringFromValueCallback": {
      "abstract": [
        {
          "text": "A block called to convert a parameter value to a string representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUImplementorStringFromValueCallback"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorStringFromValueCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUImplementorStringFromValueCallback"
        }
      ],
      "role": "symbol",
      "title": "AUImplementorStringFromValueCallback",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auimplementorstringfromvaluecallback"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueFromStringCallback": {
      "abstract": [
        {
          "text": "A block called to convert a string to a parameter value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUImplementorValueFromStringCallback"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueFromStringCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUImplementorValueFromStringCallback"
        }
      ],
      "role": "symbol",
      "title": "AUImplementorValueFromStringCallback",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auimplementorvaluefromstringcallback"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueObserver": {
      "abstract": [
        {
          "text": "A block called to notify the audio unit implementation of changes to a parameter value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUImplementorValueObserver"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueObserver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUImplementorValueObserver"
        }
      ],
      "role": "symbol",
      "title": "AUImplementorValueObserver",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auimplementorvalueobserver"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueProvider": {
      "abstract": [
        {
          "text": "A block called to fetch a parameter’s current value from the audio unit implementation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUImplementorValueProvider"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUImplementorValueProvider"
        }
      ],
      "role": "symbol",
      "title": "AUImplementorValueProvider",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auimplementorvalueprovider"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameter": {
      "abstract": [
        {
          "text": "An object that represents a single audio unit parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUParameter"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUParameter"
        }
      ],
      "role": "symbol",
      "title": "AUParameter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparameter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterGroup": {
      "abstract": [
        {
          "text": "A parameter group object represents a group of related audio unit parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUParameterGroup"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUParameterGroup"
        }
      ],
      "role": "symbol",
      "title": "AUParameterGroup",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparametergroup"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode": {
      "abstract": [
        {
          "text": "An object that represents a node in an audio unit’s parameter tree.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUParameterNode"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUParameterNode"
        }
      ],
      "role": "symbol",
      "title": "AUParameterNode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparameternode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/displayName": {
      "abstract": [
        {
          "text": "A localized display name for the parameter node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/displayName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayName"
        }
      ],
      "role": "symbol",
      "title": "displayName",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparameternode/displayname"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/displayName(withLength:)": {
      "abstract": [
        {
          "text": "Another version of the display name, possibly truncated to a desired length.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/displayName(withLength:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayNameWithLength:"
        }
      ],
      "role": "symbol",
      "title": "displayName(withLength:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparameternode/displayname(withlength:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/identifier": {
      "abstract": [
        {
          "text": "A non-localized, permanent name for the parameter node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparameternode/identifier"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/implementorDisplayNameWithLengthCallback": {
      "abstract": [
        {
          "text": "The callback for obtaining an abbreviated version of a parameter node display name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "implementorDisplayNameWithLengthCallback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUImplementorDisplayNameWithLengthCallback",
          "text": "AUImplementorDisplayNameWithLengthCallback"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/implementorDisplayNameWithLengthCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "implementorDisplayNameWithLengthCallback"
        }
      ],
      "role": "symbol",
      "title": "implementorDisplayNameWithLengthCallback",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparameternode/implementordisplaynamewithlengthcallback"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/implementorStringFromValueCallback": {
      "abstract": [
        {
          "text": "The callback for providing a string representation of a parameter value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "implementorStringFromValueCallback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUImplementorStringFromValueCallback",
          "text": "AUImplementorStringFromValueCallback"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/implementorStringFromValueCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "implementorStringFromValueCallback"
        }
      ],
      "role": "symbol",
      "title": "implementorStringFromValueCallback",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparameternode/implementorstringfromvaluecallback"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/implementorValueFromStringCallback": {
      "abstract": [
        {
          "text": "The callback for converting a string to a parameter value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "implementorValueFromStringCallback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUImplementorValueFromStringCallback",
          "text": "AUImplementorValueFromStringCallback"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/implementorValueFromStringCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "implementorValueFromStringCallback"
        }
      ],
      "role": "symbol",
      "title": "implementorValueFromStringCallback",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparameternode/implementorvaluefromstringcallback"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/implementorValueObserver": {
      "abstract": [
        {
          "text": "The callback for parameter value changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "implementorValueObserver"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUImplementorValueObserver",
          "text": "AUImplementorValueObserver"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/implementorValueObserver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "implementorValueObserver"
        }
      ],
      "role": "symbol",
      "title": "implementorValueObserver",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparameternode/implementorvalueobserver"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/implementorValueProvider": {
      "abstract": [
        {
          "text": "The callback for refreshing known stale values in a parameter tree.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "implementorValueProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUImplementorValueProvider",
          "text": "AUImplementorValueProvider"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/implementorValueProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "implementorValueProvider"
        }
      ],
      "role": "symbol",
      "title": "implementorValueProvider",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparameternode/implementorvalueprovider"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/keyPath": {
      "abstract": [
        {
          "text": "A key path generated by concatenating the identifiers of the parameter and its parents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyPath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/keyPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "keyPath"
        }
      ],
      "role": "symbol",
      "title": "keyPath",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparameternode/keypath"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/removeParameterObserver(_:)": {
      "abstract": [
        {
          "text": "Remove a specific parameter observer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeParameterObserver"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUParameterObserverToken",
          "text": "AUParameterObserverToken"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/removeParameterObserver(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeParameterObserver:"
        }
      ],
      "role": "symbol",
      "title": "removeParameterObserver(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparameternode/removeparameterobserver(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/token(byAddingParameterAutomationObserver:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "token"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "byAddingParameterAutomationObserver"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUParameterAutomationObserver",
          "text": "AUParameterAutomationObserver"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUParameterObserverToken",
          "text": "AUParameterObserverToken"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/token(byAddingParameterAutomationObserver:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tokenByAddingParameterAutomationObserver:"
        }
      ],
      "role": "symbol",
      "title": "token(byAddingParameterAutomationObserver:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparameternode/token(byaddingparameterautomationobserver:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/token(byAddingParameterObserver:)": {
      "abstract": [
        {
          "text": "Adds an observer for a single parameter or all parameters in a group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "token"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "byAddingParameterObserver"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUParameterObserver",
          "text": "AUParameterObserver"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUParameterObserverToken",
          "text": "AUParameterObserverToken"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/token(byAddingParameterObserver:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tokenByAddingParameterObserver:"
        }
      ],
      "role": "symbol",
      "title": "token(byAddingParameterObserver:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparameternode/token(byaddingparameterobserver:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/token(byAddingParameterRecordingObserver:)": {
      "abstract": [
        {
          "text": "Adds a recording observer for a single parameter or all parameters in a group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "token"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "byAddingParameterRecordingObserver"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUParameterRecordingObserver",
          "text": "AUParameterRecordingObserver"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUParameterObserverToken",
          "text": "AUParameterObserverToken"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/token(byAddingParameterRecordingObserver:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tokenByAddingParameterRecordingObserver:"
        }
      ],
      "role": "symbol",
      "title": "token(byAddingParameterRecordingObserver:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparameternode/token(byaddingparameterrecordingobserver:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterObserver": {
      "abstract": [
        {
          "text": "A block called after the value of a parameter changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUParameterObserver"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterObserver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUParameterObserver"
        }
      ],
      "role": "symbol",
      "title": "AUParameterObserver",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparameterobserver"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterRecordingObserver": {
      "abstract": [
        {
          "text": "A block called to record parameter changes as automation events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUParameterRecordingObserver"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterRecordingObserver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUParameterRecordingObserver"
        }
      ],
      "role": "symbol",
      "title": "AUParameterRecordingObserver",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparameterrecordingobserver"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterTree": {
      "abstract": [
        {
          "text": "An object that represents a top-level group node that contains all of an audio unit’s parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUParameterTree"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterTree",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUParameterTree"
        }
      ],
      "role": "symbol",
      "title": "AUParameterTree",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparametertree"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterGroup"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Parameters",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterGroup",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterTree"
      ],
      "title": "Parameters"
    }
  ],
  "topicSections": [
    {
      "anchor": "Identifiers",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/identifier",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/keyPath",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/displayName",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/displayName(withLength:)"
      ],
      "title": "Identifiers"
    },
    {
      "anchor": "Observers",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/token(byAddingParameterObserver:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/token(byAddingParameterRecordingObserver:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/token(byAddingParameterAutomationObserver:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/removeParameterObserver(_:)"
      ],
      "title": "Observers"
    },
    {
      "abstract": [
        {
          "text": "These properties are only of interest to audio unit subclasses.",
          "type": "text"
        }
      ],
      "anchor": "Audio-Unit-Implementations",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/implementorValueObserver",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/implementorValueProvider",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/implementorStringFromValueCallback",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/implementorValueFromStringCallback",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/implementorDisplayNameWithLengthCallback"
      ],
      "title": "Audio Unit Implementations"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterObserver",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterRecordingObserver",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueObserver",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueProvider",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorStringFromValueCallback",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueFromStringCallback",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorDisplayNameWithLengthCallback"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AUParameterNode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUParameterNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUParameterNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Identifiers",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/identifier",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/keyPath",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/displayName",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/displayName(withLength:)"
              ],
              "title": "Identifiers"
            },
            {
              "anchor": "Observers",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/token(byAddingParameterObserver:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/token(byAddingParameterRecordingObserver:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/token(byAddingParameterAutomationObserver:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/removeParameterObserver(_:)"
              ],
              "title": "Observers"
            },
            {
              "abstract": [
                {
                  "text": "These properties are only of interest to audio unit subclasses.",
                  "type": "text"
                }
              ],
              "anchor": "Audio-Unit-Implementations",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/implementorValueObserver",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/implementorValueProvider",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/implementorStringFromValueCallback",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/implementorValueFromStringCallback",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterNode/implementorDisplayNameWithLengthCallback"
              ],
              "title": "Audio Unit Implementations"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterObserver",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterRecordingObserver",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueObserver",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueProvider",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorStringFromValueCallback",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueFromStringCallback",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorDisplayNameWithLengthCallback"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterGroup"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Parameters",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterGroup",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterTree"
              ],
              "title": "Parameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AUParameterNode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterNode~1implementorValueProvider/title",
          "value": "implementorValueProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterNode~1implementorValueProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "implementorValueProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueObserver/title",
          "value": "AUImplementorValueObserver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueObserver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUImplementorValueObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueObserver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUImplementorValueObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterNode~1displayName/title",
          "value": "displayName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterNode~1displayName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displayName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameter/title",
          "value": "AUParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterNode~1keyPath/title",
          "value": "keyPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterNode~1keyPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "keyPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterNode/title",
          "value": "AUParameterNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUParameterNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUParameterNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterNode~1displayName(withLength:)/title",
          "value": "displayNameWithLength:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterNode~1displayName(withLength:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "displayNameWithLength:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterObserver/title",
          "value": "AUParameterObserver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterObserver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUParameterObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterObserver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUParameterObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterNode~1token(byAddingParameterAutomationObserver:)/title",
          "value": "tokenByAddingParameterAutomationObserver:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterNode~1token(byAddingParameterAutomationObserver:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tokenByAddingParameterAutomationObserver:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterNode~1implementorDisplayNameWithLengthCallback/title",
          "value": "implementorDisplayNameWithLengthCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterNode~1implementorDisplayNameWithLengthCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "implementorDisplayNameWithLengthCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterNode~1implementorValueFromStringCallback/title",
          "value": "implementorValueFromStringCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterNode~1implementorValueFromStringCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "implementorValueFromStringCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterGroup/title",
          "value": "AUParameterGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUParameterGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUParameterGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterNode~1removeParameterObserver(_:)/title",
          "value": "removeParameterObserver:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterNode~1removeParameterObserver(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeParameterObserver:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterNode~1token(byAddingParameterObserver:)/title",
          "value": "tokenByAddingParameterObserver:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterNode~1token(byAddingParameterObserver:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tokenByAddingParameterObserver:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterRecordingObserver/title",
          "value": "AUParameterRecordingObserver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterRecordingObserver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUParameterRecordingObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterRecordingObserver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUParameterRecordingObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterNode~1token(byAddingParameterRecordingObserver:)/title",
          "value": "tokenByAddingParameterRecordingObserver:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterNode~1token(byAddingParameterRecordingObserver:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tokenByAddingParameterRecordingObserver:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterNode~1implementorStringFromValueCallback/title",
          "value": "implementorStringFromValueCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterNode~1implementorStringFromValueCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "implementorStringFromValueCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueProvider/title",
          "value": "AUImplementorValueProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUImplementorValueProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUImplementorValueProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueFromStringCallback/title",
          "value": "AUImplementorValueFromStringCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueFromStringCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUImplementorValueFromStringCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueFromStringCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUImplementorValueFromStringCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterTree/title",
          "value": "AUParameterTree"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterTree/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUParameterTree"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterTree/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUParameterTree"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorDisplayNameWithLengthCallback/title",
          "value": "AUImplementorDisplayNameWithLengthCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorDisplayNameWithLengthCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUImplementorDisplayNameWithLengthCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorDisplayNameWithLengthCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUImplementorDisplayNameWithLengthCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorStringFromValueCallback/title",
          "value": "AUImplementorStringFromValueCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorStringFromValueCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUImplementorStringFromValueCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorStringFromValueCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUImplementorStringFromValueCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterNode~1identifier/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterNode~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterNode~1implementorValueObserver/title",
          "value": "implementorValueObserver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterNode~1implementorValueObserver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "implementorValueObserver"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/auparameternode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/auparameternode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
