{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@AUParameterMIDIMapping",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AUParameterMIDIMapping"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AUParameterMIDIMapping"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AUParameterMIDIMapping"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AUParameterMIDIMapping"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUParameterMIDIMapping"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUParameterMIDIMapping"
        }
      ],
      "role": "symbol",
      "title": "AUParameterMIDIMapping",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparametermidimapping"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparametermidimapping/init()"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/init(mScope:mElement:mParameterID:mFlags:mSubRangeMin:mSubRangeMax:mStatus:mData1:reserved1:reserved2:reserved3:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "mScope"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitScope",
          "text": "AudioUnitScope"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mElement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitElement",
          "text": "AudioUnitElement"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mParameterID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AUParameterMIDIMappingFlags",
          "text": "AUParameterMIDIMappingFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mSubRangeMin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterValue",
          "text": "AudioUnitParameterValue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mSubRangeMax"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterValue",
          "text": "AudioUnitParameterValue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mData1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "reserved1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "reserved2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "reserved3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/init(mScope:mElement:mParameterID:mFlags:mSubRangeMin:mSubRangeMax:mStatus:mData1:reserved1:reserved2:reserved3:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(mScope:mElement:mParameterID:mFlags:mSubRangeMin:mSubRangeMax:mStatus:mData1:reserved1:reserved2:reserved3:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparametermidimapping/init(mscope:melement:mparameterid:mflags:msubrangemin:msubrangemax:mstatus:mdata1:reserved1:reserved2:reserved3:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mData1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mData1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mData1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mData1"
        }
      ],
      "role": "symbol",
      "title": "mData1",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparametermidimapping/mdata1"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mElement": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mElement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitElement",
          "text": "AudioUnitElement"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mElement"
        }
      ],
      "role": "symbol",
      "title": "mElement",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparametermidimapping/melement"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AUParameterMIDIMappingFlags",
          "text": "AUParameterMIDIMappingFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mFlags"
        }
      ],
      "role": "symbol",
      "title": "mFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparametermidimapping/mflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mParameterID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mParameterID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mParameterID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mParameterID"
        }
      ],
      "role": "symbol",
      "title": "mParameterID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparametermidimapping/mparameterid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mScope": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mScope"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitScope",
          "text": "AudioUnitScope"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mScope",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mScope"
        }
      ],
      "role": "symbol",
      "title": "mScope",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparametermidimapping/mscope"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mStatus"
        }
      ],
      "role": "symbol",
      "title": "mStatus",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparametermidimapping/mstatus"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mSubRangeMax": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mSubRangeMax"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterValue",
          "text": "AudioUnitParameterValue"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mSubRangeMax",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mSubRangeMax"
        }
      ],
      "role": "symbol",
      "title": "mSubRangeMax",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparametermidimapping/msubrangemax"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mSubRangeMin": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mSubRangeMin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterValue",
          "text": "AudioUnitParameterValue"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mSubRangeMin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mSubRangeMin"
        }
      ],
      "role": "symbol",
      "title": "mSubRangeMin",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparametermidimapping/msubrangemin"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/reserved1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reserved1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/reserved1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reserved1"
        }
      ],
      "role": "symbol",
      "title": "reserved1",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparametermidimapping/reserved1"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/reserved2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reserved2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/reserved2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reserved2"
        }
      ],
      "role": "symbol",
      "title": "reserved2",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparametermidimapping/reserved2"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/reserved3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reserved3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/reserved3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reserved3"
        }
      ],
      "role": "symbol",
      "title": "reserved3",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparametermidimapping/reserved3"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitConnection": {
      "abstract": [
        {
          "text": "An audio unit source-to-destination connection specification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitConnection"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitConnection"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitConnection",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitconnection"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEvent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitEvent"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitEvent"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitEvent",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitevent"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitExternalBuffer": {
      "abstract": [
        {
          "text": "Allows an audio unit host application to tell an audio unit to use a specified buffer for its input callback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitExternalBuffer"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitExternalBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitExternalBuffer"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitExternalBuffer",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitexternalbuffer"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitFrequencyResponseBin": {
      "abstract": [
        {
          "text": "An audio unit’s audio level at a particular frequency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitFrequencyResponseBin"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitFrequencyResponseBin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitFrequencyResponseBin"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitFrequencyResponseBin",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitfrequencyresponsebin"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitMIDIControlMapping": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitMIDIControlMapping"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitMIDIControlMapping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitMIDIControlMapping"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitMIDIControlMapping",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitmidicontrolmapping"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitMeterClipping": {
      "abstract": [
        {
          "text": "Audio clipping that has occurred in a mixer unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitMeterClipping"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitMeterClipping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitMeterClipping"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitMeterClipping",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitmeterclipping"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitOtherPluginDesc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitOtherPluginDesc"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitOtherPluginDesc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitOtherPluginDesc"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitOtherPluginDesc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitotherplugindesc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameter": {
      "abstract": [
        {
          "text": "An adjustable audio unit attribute such as volume, pitch, or filter cutoff frequency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameter"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameter"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterEvent": {
      "abstract": [
        {
          "text": "A scheduled change to an audio unit parameter’s value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterEvent"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterEvent"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterEvent",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterevent"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterHistoryInfo": {
      "abstract": [
        {
          "text": "The suggested update rate and history duration for parameters which have the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_PlotHistory",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " flag set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterHistoryInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterHistoryInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterHistoryInfo"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterHistoryInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterhistoryinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterIDName": {
      "abstract": [
        {
          "text": "A type definition for a data type that defines the short version of the name for an audio unit parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterIDName"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterIDName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterIDName"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterIDName",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteridname"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterInfo"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterNameInfo": {
      "abstract": [
        {
          "text": "A short version of the name for an audio unit parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterNameInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterNameInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterNameInfo"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterNameInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameternameinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions": {
      "abstract": [
        {
          "text": "Value options for audio unit parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterOptions",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteroptions"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_PlotHistory": {
      "abstract": [
        {
          "text": "If set, getting the ",
          "type": "text"
        },
        {
          "code": "kAudioUnitProperty_ParameterHistoryInfo",
          "type": "codeVoice"
        },
        {
          "text": " property fills out the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterHistoryInfo",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " struct containing the recommended update rate and history duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flag_PlotHistory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions/flag_PlotHistory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterFlag_PlotHistory"
        }
      ],
      "role": "symbol",
      "title": "flag_PlotHistory",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteroptions/flag_plothistory"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterStringFromValue": {
      "abstract": [
        {
          "text": "A string representation of a parameter’s value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterStringFromValue"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterStringFromValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterStringFromValue"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterStringFromValue",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterstringfromvalue"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitConnection",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEvent",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitExternalBuffer",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitFrequencyResponseBin",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitMeterClipping",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitMIDIControlMapping",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitOtherPluginDesc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterEvent",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterHistoryInfo",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterNameInfo",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterIDName",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterInfo",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterStringFromValue"
      ],
      "title": "Structures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/init()",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/init(mScope:mElement:mParameterID:mFlags:mSubRangeMin:mSubRangeMax:mStatus:mData1:reserved1:reserved2:reserved3:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mData1",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mElement",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mParameterID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mScope",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mStatus",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mSubRangeMax",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mSubRangeMin",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/reserved1",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/reserved2",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/reserved3"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AUParameterMIDIMapping"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUParameterMIDIMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUParameterMIDIMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mData1",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mElement",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mFlags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mParameterID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mScope",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mStatus",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mSubRangeMax",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/mSubRangeMin",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/reserved1",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/reserved2",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/reserved3"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Structures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitConnection",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitEvent",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitExternalBuffer",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitFrequencyResponseBin",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitMeterClipping",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitMIDIControlMapping",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitOtherPluginDesc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterEvent",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterHistoryInfo",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterNameInfo",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterIDName",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterInfo",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterStringFromValue"
              ],
              "title": "Structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AUParameterMIDIMapping"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMapping/title",
          "value": "AUParameterMIDIMapping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMapping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUParameterMIDIMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMapping/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUParameterMIDIMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMapping~1reserved2/title",
          "value": "reserved2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMapping~1reserved2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reserved2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterIDName/title",
          "value": "AudioUnitParameterIDName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterIDName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterIDName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterIDName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterIDName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMapping~1mStatus/title",
          "value": "mStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMapping~1mStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMapping~1mSubRangeMin/title",
          "value": "mSubRangeMin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMapping~1mSubRangeMin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mSubRangeMin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEvent/title",
          "value": "AudioUnitEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterEvent/title",
          "value": "AudioUnitParameterEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterHistoryInfo/title",
          "value": "AudioUnitParameterHistoryInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterHistoryInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterHistoryInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterHistoryInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterHistoryInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMapping~1mElement/title",
          "value": "mElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMapping~1mElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMapping~1mFlags/title",
          "value": "mFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMapping~1mFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMapping~1mData1/title",
          "value": "mData1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMapping~1mData1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mData1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMapping~1mScope/title",
          "value": "mScope"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMapping~1mScope/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterStringFromValue/title",
          "value": "AudioUnitParameterStringFromValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterStringFromValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterStringFromValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterStringFromValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterStringFromValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMapping~1reserved1/title",
          "value": "reserved1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMapping~1reserved1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reserved1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterNameInfo/title",
          "value": "AudioUnitParameterNameInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterNameInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterNameInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterNameInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterNameInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions/title",
          "value": "AudioUnitParameterOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitMIDIControlMapping/title",
          "value": "AudioUnitMIDIControlMapping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitMIDIControlMapping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitMIDIControlMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitMIDIControlMapping/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitMIDIControlMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMapping~1mSubRangeMax/title",
          "value": "mSubRangeMax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMapping~1mSubRangeMax/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mSubRangeMax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitFrequencyResponseBin/title",
          "value": "AudioUnitFrequencyResponseBin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitFrequencyResponseBin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitFrequencyResponseBin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitFrequencyResponseBin/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitFrequencyResponseBin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameter/title",
          "value": "AudioUnitParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_PlotHistory/title",
          "value": "kAudioUnitParameterFlag_PlotHistory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions~1flag_PlotHistory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterFlag_PlotHistory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMapping~1reserved3/title",
          "value": "reserved3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMapping~1reserved3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reserved3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterInfo/title",
          "value": "AudioUnitParameterInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitExternalBuffer/title",
          "value": "AudioUnitExternalBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitExternalBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitExternalBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitExternalBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitExternalBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitMeterClipping/title",
          "value": "AudioUnitMeterClipping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitMeterClipping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitMeterClipping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitMeterClipping/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitMeterClipping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitConnection/title",
          "value": "AudioUnitConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitConnection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMapping~1mParameterID/title",
          "value": "mParameterID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMapping~1mParameterID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitOtherPluginDesc/title",
          "value": "AudioUnitOtherPluginDesc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitOtherPluginDesc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitOtherPluginDesc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitOtherPluginDesc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitOtherPluginDesc"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/auparametermidimapping"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/auparametermidimapping"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
