{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterAutomationEventType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AUParameterAutomationEventType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AUParameterAutomationEventType"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AUParameterAutomationEventType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "AUParameterAutomationEventType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AUParameterAutomationEventType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389613-midi_audio_unit_parameters": {
      "abstract": [
        {
          "text": "Parameters for instrument units.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389613-midi_audio_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Audio Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389613-midi_audio_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi": {
      "abstract": [
        {
          "text": "Reserved for system use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Reserved Audio Unit Clump Identifier",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1533986-reserved_audio_unit_clump_identi"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534054-offline_audio_unit_properties": {
      "abstract": [
        {
          "text": "Properties for audio units that perform offline processing—that is, processing in a nonplayback, nonrealtime mode.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534054-offline_audio_unit_properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Offline Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534054-offline_audio_unit_properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes": {
      "abstract": [
        {
          "text": "Input/output audio unit subtypes for audio units provided by Apple.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Input/Output Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584139-input_output_audio_unit_subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele": {
      "abstract": [
        {
          "text": "General audio unit component selectors that correspond to functions in the audio unit API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele",
      "kind": "article",
      "role": "collectionGroup",
      "title": "General Audio Unit Function Selectors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584140-general_audio_unit_function_sele"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584142-audio_unit_types": {
      "abstract": [
        {
          "text": "The defined types of audio processing plug-ins known as audio units.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584142-audio_unit_types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Types",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584142-audio_unit_types"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi": {
      "abstract": [
        {
          "text": "The Apple audio unit manufacturer code.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Manufacturer Identifier",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584143-audio_unit_manufacturer_identifi"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes": {
      "abstract": [
        {
          "text": "Audio data format converter audio unit subtypes for audio units provided by Apple.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Converter Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584145-converter_audio_unit_subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584148-audio-unit-output-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584148-audio-unit-output-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Output Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584148-audio-unit-output-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Panner Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584151-audio-unit-panner-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Pitch Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584152-audio-unit-pitch-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Player Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584155-audio-unit-player-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "I/O Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1619485-i-o-audio-unit-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes": {
      "abstract": [
        {
          "text": "Audio units that serve as sound sources.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Generator Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1619493-generator_audio_unit_subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Inter-App Audio Unit Types",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1619501-inter-app-audio-unit-types"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterAutomationEventType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUParameterAutomationEventType"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterAutomationEventType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUParameterAutomationEventType"
        }
      ],
      "role": "symbol",
      "title": "AUParameterAutomationEventType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparameterautomationeventtype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterAutomationEventType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterAutomationEventType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparameterautomationeventtype/init(rawvalue:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterAutomationEventType/release": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "release"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterAutomationEventType/release",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUParameterAutomationEventTypeRelease"
        }
      ],
      "role": "symbol",
      "title": "AUParameterAutomationEventType.release",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparameterautomationeventtype/release"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterAutomationEventType/touch": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touch"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterAutomationEventType/touch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUParameterAutomationEventTypeTouch"
        }
      ],
      "role": "symbol",
      "title": "AUParameterAutomationEventType.touch",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparameterautomationeventtype/touch"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterAutomationEventType/value": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "value"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterAutomationEventType/value",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUParameterAutomationEventTypeValue"
        }
      ],
      "role": "symbol",
      "title": "AUParameterAutomationEventType.value",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparameterautomationeventtype/value"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@uint32_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "uint32_t",
      "type": "topic",
      "url": "/documentation/kernel/uint32_t"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584142-audio_unit_types",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584148-audio-unit-output-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534054-offline_audio_unit_properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389613-midi_audio_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterAutomationEventType/release",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterAutomationEventType/touch",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterAutomationEventType/value"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterAutomationEventType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AUParameterAutomationEventType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUParameterAutomationEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUParameterAutomationEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterAutomationEventType/release",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterAutomationEventType/touch",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterAutomationEventType/value"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584142-audio_unit_types",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619501-inter-app-audio-unit-types",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584143-audio_unit_manufacturer_identifi",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584148-audio-unit-output-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619485-i-o-audio-unit-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584145-converter_audio_unit_subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1533986-reserved_audio_unit_clump_identi",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534054-offline_audio_unit_properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389613-midi_audio_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584140-general_audio_unit_function_sele",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1619493-generator_audio_unit_subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584139-input_output_audio_unit_subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584151-audio-unit-panner-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584155-audio-unit-player-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584152-audio-unit-pitch-subtypes"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AUParameterAutomationEventType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint32_t",
                    "text": "uint32_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterAutomationEventType~1release/title",
          "value": "AUParameterAutomationEventTypeRelease"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterAutomationEventType~1release/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUParameterAutomationEventTypeRelease"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterAutomationEventType/title",
          "value": "AUParameterAutomationEventType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterAutomationEventType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUParameterAutomationEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterAutomationEventType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUParameterAutomationEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterAutomationEventType~1value/title",
          "value": "AUParameterAutomationEventTypeValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterAutomationEventType~1value/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUParameterAutomationEventTypeValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterAutomationEventType~1touch/title",
          "value": "AUParameterAutomationEventTypeTouch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterAutomationEventType~1touch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUParameterAutomationEventTypeTouch"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/auparameterautomationeventtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/auparameterautomationeventtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
