{
  "abstract": [
    {
      "text": "A block to supply audio input to a render block.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AURenderPullInputBlock"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@AURenderPullInputBlock",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AURenderPullInputBlock"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AURenderPullInputBlock"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "AURenderPullInputBlock"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AURenderPullInputBlock"
            },
            {
              "kind": "text",
              "text": " = ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AudioUnitRenderActionFlags",
              "text": "AudioUnitRenderActionFlags"
            },
            {
              "kind": "text",
              "text": ">, "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@AudioTimeStamp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@AudioTimeStamp",
              "text": "AudioTimeStamp"
            },
            {
              "kind": "text",
              "text": ">, "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioFrameCount",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AUAudioFrameCount",
              "text": "AUAudioFrameCount"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@AudioBufferList",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@AudioBufferList",
              "text": "AudioBufferList"
            },
            {
              "kind": "text",
              "text": ">) -> "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitStatus",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AUAudioUnitStatus",
              "text": "AUAudioUnitStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The caller must supply valid buffers in the input data’s ",
              "type": "text"
            },
            {
              "code": "mBuffers'",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "code": "mData",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "mDataByteSize",
              "type": "codeVoice"
            },
            {
              "text": " fields (",
              "type": "text"
            },
            {
              "code": "mDataByteSize",
              "type": "codeVoice"
            },
            {
              "text": " must be consistent with ",
              "type": "text"
            },
            {
              "code": "frameCount",
              "type": "codeVoice"
            },
            {
              "text": "). This block may provide input in those specified buffers, or it may replace the ",
              "type": "text"
            },
            {
              "code": "mData",
              "type": "codeVoice"
            },
            {
              "text": " pointers with pointers to memory which it owns and guarantees will remain valid until the next render cycle.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The block returns an audio unit status result code. If instead an error is returned, the input data should be assumed to be invalid.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The block takes the following parameters:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The pointer to the action flags.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "actionFlags",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The HAL time at which the input data will be rendered. If there is a sample rate conversion or time compression/expansion downstream, the sample time will not be valid.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "timestamp",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The number of input sample frames requested.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "frameCount",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The index of the input bus being pulled.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "inputBusNumber",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The input audio data.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "inputData",
                    "type": "text"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioChannelCount": {
      "abstract": [
        {
          "text": "A number of audio channels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioChannelCount"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioChannelCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUAudioChannelCount"
        }
      ],
      "role": "symbol",
      "title": "AUAudioChannelCount",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiochannelcount"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioFrameCount": {
      "abstract": [
        {
          "text": "A number of audio sample frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioFrameCount"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioFrameCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUAudioFrameCount"
        }
      ],
      "role": "symbol",
      "title": "AUAudioFrameCount",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudioframecount"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioObjectID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioObjectID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioObjectID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUAudioObjectID"
        }
      ],
      "role": "symbol",
      "title": "AUAudioObjectID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudioobjectid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitStatus": {
      "abstract": [
        {
          "text": "A result code returned from an audio unit’s render function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioUnitStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUAudioUnitStatus"
        }
      ],
      "role": "symbol",
      "title": "AUAudioUnitStatus",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounitstatus"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUEventListenerProc"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUEventListenerProc"
        }
      ],
      "role": "symbol",
      "title": "AUEventListenerProc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aueventlistenerproc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerRef": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUEventListenerRef"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUEventListenerRef"
        }
      ],
      "role": "symbol",
      "title": "AUEventListenerRef",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aueventlistenerref"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventSampleTime": {
      "abstract": [
        {
          "text": "Expresses time as a sample count.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUEventSampleTime"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventSampleTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUEventSampleTime"
        }
      ],
      "role": "symbol",
      "title": "AUEventSampleTime",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aueventsampletime"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueObserver": {
      "abstract": [
        {
          "text": "A block called to notify the audio unit implementation of changes to a parameter value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUImplementorValueObserver"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueObserver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUImplementorValueObserver"
        }
      ],
      "role": "symbol",
      "title": "AUImplementorValueObserver",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auimplementorvalueobserver"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueProvider": {
      "abstract": [
        {
          "text": "A block called to fetch a parameter’s current value from the audio unit implementation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUImplementorValueProvider"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUImplementorValueProvider"
        }
      ],
      "role": "symbol",
      "title": "AUImplementorValueProvider",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auimplementorvalueprovider"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUMIDICIProfileChangedBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUMIDICIProfileChangedBlock"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUMIDICIProfileChangedBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUMIDICIProfileChangedBlock"
        }
      ],
      "role": "symbol",
      "title": "AUMIDICIProfileChangedBlock",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aumidiciprofilechangedblock"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AURenderPullInputBlock": {
      "abstract": [
        {
          "text": "A block to supply audio input to a render block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AURenderPullInputBlock"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AURenderPullInputBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AURenderPullInputBlock"
        }
      ],
      "role": "symbol",
      "title": "AURenderPullInputBlock",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aurenderpullinputblock"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags": {
      "abstract": [
        {
          "text": "Flags for configuring audio unit rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitRenderActionFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitRenderActionFlags"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitRenderActionFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitrenderactionflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MIDIChannelNumber": {
      "abstract": [
        {
          "text": "MIDI Channel, 0~15 (channels 1 through 16, respectively).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIChannelNumber"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MIDIChannelNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIChannelNumber"
        }
      ],
      "role": "symbol",
      "title": "MIDIChannelNumber",
      "type": "topic",
      "url": "/documentation/audiotoolbox/midichannelnumber"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ScheduledAudioFileRegion"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ScheduledAudioFileRegion"
        }
      ],
      "role": "symbol",
      "title": "ScheduledAudioFileRegion",
      "type": "topic",
      "url": "/documentation/audiotoolbox/scheduledaudiofileregion"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegionCompletionProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ScheduledAudioFileRegionCompletionProc"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegionCompletionProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ScheduledAudioFileRegionCompletionProc"
        }
      ],
      "role": "symbol",
      "title": "ScheduledAudioFileRegionCompletionProc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/scheduledaudiofileregioncompletionproc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSlice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ScheduledAudioSlice"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSlice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ScheduledAudioSlice"
        }
      ],
      "role": "symbol",
      "title": "ScheduledAudioSlice",
      "type": "topic",
      "url": "/documentation/audiotoolbox/scheduledaudioslice"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSliceCompletionProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ScheduledAudioSliceCompletionProc"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSliceCompletionProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ScheduledAudioSliceCompletionProc"
        }
      ],
      "role": "symbol",
      "title": "ScheduledAudioSliceCompletionProc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/scheduledaudioslicecompletionproc"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@S@AudioBufferList": {
      "abstract": [
        {
          "text": "A structure that stores a variable-length array of audio buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioBufferList"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@AudioBufferList",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioBufferList",
      "type": "topic",
      "url": "/documentation/CoreAudioTypes/AudioBufferList"
    },
    "doc://com.externally.resolved.symbol/c:@S@AudioTimeStamp": {
      "abstract": [
        {
          "text": "A structure that represents a timestamp value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioTimeStamp"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@AudioTimeStamp",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioTimeStamp",
      "type": "topic",
      "url": "/documentation/CoreAudioTypes/AudioTimeStamp"
    },
    "doc://com.externally.resolved.symbol/s:SP": {
      "abstract": [
        {
          "text": "A pointer for accessing data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SP",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafePointer"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Audio-Unit-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSlice",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegionCompletionProc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSliceCompletionProc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MIDIChannelNumber",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioObjectID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUMIDICIProfileChangedBlock",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioChannelCount",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioFrameCount",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitStatus",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerProc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerRef",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventSampleTime",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueObserver",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueProvider"
      ],
      "title": "Audio Unit Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AURenderPullInputBlock"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AURenderPullInputBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AURenderPullInputBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Audio-Unit-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSlice",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegionCompletionProc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSliceCompletionProc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MIDIChannelNumber",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioObjectID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUMIDICIProfileChangedBlock",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioChannelCount",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioFrameCount",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitStatus",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerProc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerRef",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventSampleTime",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueObserver",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueProvider"
              ],
              "title": "Audio Unit Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:BFI(#*$@E@AudioUnitRenderActionFlags#*1$@S@AudioTimeStamp#i#L#*$@S@AudioBufferList)",
                    "text": "int (^)(enum AudioUnitRenderActionFlags *, const struct AudioTimeStamp *, unsigned int, long, struct AudioBufferList *)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AURenderPullInputBlock"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegionCompletionProc/title",
          "value": "ScheduledAudioFileRegionCompletionProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegionCompletionProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ScheduledAudioFileRegionCompletionProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegionCompletionProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ScheduledAudioFileRegionCompletionProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@S@AudioBufferList/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioBufferList"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUMIDICIProfileChangedBlock/title",
          "value": "AUMIDICIProfileChangedBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUMIDICIProfileChangedBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUMIDICIProfileChangedBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUMIDICIProfileChangedBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUMIDICIProfileChangedBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueProvider/title",
          "value": "AUImplementorValueProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUImplementorValueProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUImplementorValueProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitRenderActionFlags/title",
          "value": "AudioUnitRenderActionFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitRenderActionFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitRenderActionFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitRenderActionFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitRenderActionFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventSampleTime/title",
          "value": "AUEventSampleTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventSampleTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUEventSampleTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventSampleTime/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUEventSampleTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioSlice/title",
          "value": "ScheduledAudioSlice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioSlice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ScheduledAudioSlice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioSlice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ScheduledAudioSlice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@S@AudioTimeStamp/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioTimeStamp"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AURenderPullInputBlock/title",
          "value": "AURenderPullInputBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AURenderPullInputBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AURenderPullInputBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AURenderPullInputBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AURenderPullInputBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueObserver/title",
          "value": "AUImplementorValueObserver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueObserver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUImplementorValueObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueObserver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUImplementorValueObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioFrameCount/title",
          "value": "AUAudioFrameCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioFrameCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioFrameCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioFrameCount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioFrameCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioChannelCount/title",
          "value": "AUAudioChannelCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioChannelCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioChannelCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioChannelCount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioChannelCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitStatus/title",
          "value": "AUAudioUnitStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerProc/title",
          "value": "AUEventListenerProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUEventListenerProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUEventListenerProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerRef/title",
          "value": "AUEventListenerRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUEventListenerRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUEventListenerRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegion/title",
          "value": "ScheduledAudioFileRegion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ScheduledAudioFileRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ScheduledAudioFileRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MIDIChannelNumber/title",
          "value": "MIDIChannelNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MIDIChannelNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIChannelNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MIDIChannelNumber/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIChannelNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioSliceCompletionProc/title",
          "value": "ScheduledAudioSliceCompletionProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioSliceCompletionProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ScheduledAudioSliceCompletionProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioSliceCompletionProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ScheduledAudioSliceCompletionProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioObjectID/title",
          "value": "AUAudioObjectID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioObjectID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioObjectID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioObjectID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioObjectID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/aurenderpullinputblock"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/aurenderpullinputblock"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
