{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AUReverbRoomType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AUReverbRoomType"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AUReverbRoomType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "AUReverbRoomType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AUReverbRoomType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389643-aunewtimepitch-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389643-aunewtimepitch-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUNewTimePitch Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389643-aunewtimepitch-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389781-aumultibandcompressor-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389781-aumultibandcompressor-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUMultibandCompressor Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389781-aumultibandcompressor-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389801-aumatrixreverb-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389801-aumatrixreverb-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUMatrixReverb Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389801-aumatrixreverb-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389946-autimepitch_autimepitch_offline": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389946-autimepitch_autimepitch_offline",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUTimePitch, AUTimePitch (offline), and AUPitch Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389946-autimepitch_autimepitch_offline"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390010-audelay-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390010-audelay-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUDelay Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390010-audelay-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390014-varispeed_unit_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Varispeed unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390014-varispeed_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Varispeed Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390014-varispeed_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390086-audistortion-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390086-audistortion-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUDistortion Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390086-audistortion-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390119-reverb_parameters": {
      "abstract": [
        {
          "text": "Additional reverb parameters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390119-reverb_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Reverb Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390119-reverb_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534061-audeferredrenderer-properties": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534061-audeferredrenderer-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUDeferredRenderer Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534061-audeferredrenderer-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584154-effect_audio_unit_subtypes": {
      "abstract": [
        {
          "text": "Effect (digital signal processing) audio unit subtypes for audio units provided by Apple.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584154-effect_audio_unit_subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Effect Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584154-effect_audio_unit_subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1615024-reverb_unit_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Reverb unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1615024-reverb_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Reverb Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1615024-reverb_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3547050-ausampledelay-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3547050-ausampledelay-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUSampleDelay Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/3547050-ausampledelay-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUReverbRoomType"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUReverbRoomType"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype/init(rawvalue:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_Cathedral": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reverbRoomType_Cathedral"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_Cathedral",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbRoomType_Cathedral"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType.reverbRoomType_Cathedral",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype/reverbroomtype_cathedral"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeChamber": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reverbRoomType_LargeChamber"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeChamber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbRoomType_LargeChamber"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType.reverbRoomType_LargeChamber",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype/reverbroomtype_largechamber"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeHall": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reverbRoomType_LargeHall"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeHall",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbRoomType_LargeHall"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType.reverbRoomType_LargeHall",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype/reverbroomtype_largehall"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeHall2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reverbRoomType_LargeHall2"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeHall2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbRoomType_LargeHall2"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType.reverbRoomType_LargeHall2",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype/reverbroomtype_largehall2"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeRoom": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reverbRoomType_LargeRoom"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeRoom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbRoomType_LargeRoom"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType.reverbRoomType_LargeRoom",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype/reverbroomtype_largeroom"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeRoom2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reverbRoomType_LargeRoom2"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeRoom2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbRoomType_LargeRoom2"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType.reverbRoomType_LargeRoom2",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype/reverbroomtype_largeroom2"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumChamber": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reverbRoomType_MediumChamber"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumChamber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbRoomType_MediumChamber"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType.reverbRoomType_MediumChamber",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype/reverbroomtype_mediumchamber"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumHall": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reverbRoomType_MediumHall"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumHall",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbRoomType_MediumHall"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType.reverbRoomType_MediumHall",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype/reverbroomtype_mediumhall"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumHall2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reverbRoomType_MediumHall2"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumHall2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbRoomType_MediumHall2"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType.reverbRoomType_MediumHall2",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype/reverbroomtype_mediumhall2"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumHall3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reverbRoomType_MediumHall3"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumHall3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbRoomType_MediumHall3"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType.reverbRoomType_MediumHall3",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype/reverbroomtype_mediumhall3"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumRoom": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reverbRoomType_MediumRoom"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumRoom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbRoomType_MediumRoom"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType.reverbRoomType_MediumRoom",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype/reverbroomtype_mediumroom"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_Plate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reverbRoomType_Plate"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_Plate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbRoomType_Plate"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType.reverbRoomType_Plate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype/reverbroomtype_plate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_SmallRoom": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reverbRoomType_SmallRoom"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_SmallRoom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbRoomType_SmallRoom"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType.reverbRoomType_SmallRoom",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype/reverbroomtype_smallroom"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Effects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584154-effect_audio_unit_subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389801-aumatrixreverb-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390086-audistortion-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390119-reverb_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1615024-reverb_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390014-varispeed_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390010-audelay-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389781-aumultibandcompressor-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534061-audeferredrenderer-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3547050-ausampledelay-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389643-aunewtimepitch-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389946-autimepitch_autimepitch_offline"
      ],
      "title": "Effects"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_Cathedral",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeChamber",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeHall",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeHall2",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeRoom",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeRoom2",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumChamber",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumHall",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumHall2",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumHall3",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumRoom",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_Plate",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_SmallRoom"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AUReverbRoomType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUReverbRoomType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUReverbRoomType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_Cathedral",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeChamber",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeHall",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeHall2",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeRoom",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeRoom2",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumChamber",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumHall",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumHall2",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumHall3",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumRoom",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_Plate",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_SmallRoom"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Effects",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584154-effect_audio_unit_subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389801-aumatrixreverb-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390086-audistortion-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390119-reverb_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1615024-reverb_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390014-varispeed_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390010-audelay-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389781-aumultibandcompressor-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534061-audeferredrenderer-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/3547050-ausampledelay-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389643-aunewtimepitch-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389946-autimepitch_autimepitch_offline"
              ],
              "title": "Effects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AUReverbRoomType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@UInt32",
                    "text": "UInt32"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_SmallRoom/title",
          "value": "kReverbRoomType_SmallRoom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_SmallRoom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbRoomType_SmallRoom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_MediumChamber/title",
          "value": "kReverbRoomType_MediumChamber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_MediumChamber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbRoomType_MediumChamber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_MediumHall3/title",
          "value": "kReverbRoomType_MediumHall3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_MediumHall3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbRoomType_MediumHall3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType/title",
          "value": "AUReverbRoomType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUReverbRoomType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUReverbRoomType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_MediumRoom/title",
          "value": "kReverbRoomType_MediumRoom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_MediumRoom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbRoomType_MediumRoom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_Cathedral/title",
          "value": "kReverbRoomType_Cathedral"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_Cathedral/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbRoomType_Cathedral"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_LargeHall/title",
          "value": "kReverbRoomType_LargeHall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_LargeHall/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbRoomType_LargeHall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_LargeHall2/title",
          "value": "kReverbRoomType_LargeHall2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_LargeHall2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbRoomType_LargeHall2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_MediumHall2/title",
          "value": "kReverbRoomType_MediumHall2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_MediumHall2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbRoomType_MediumHall2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_LargeRoom/title",
          "value": "kReverbRoomType_LargeRoom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_LargeRoom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbRoomType_LargeRoom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_LargeRoom2/title",
          "value": "kReverbRoomType_LargeRoom2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_LargeRoom2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbRoomType_LargeRoom2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_Plate/title",
          "value": "kReverbRoomType_Plate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_Plate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbRoomType_Plate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_MediumHall/title",
          "value": "kReverbRoomType_MediumHall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_MediumHall/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbRoomType_MediumHall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_LargeChamber/title",
          "value": "kReverbRoomType_LargeChamber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_LargeChamber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbRoomType_LargeChamber"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/aureverbroomtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/aureverbroomtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
