{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AUSpatialMixerSourceMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AUSpatialMixerSourceMode"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AUSpatialMixerSourceMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "AUSpatialMixerSourceMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AUSpatialMixerSourceMode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389739-aumultichannelmixer_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Multichannel Mixer unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389739-aumultichannelmixer_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUMultiChannelMixer Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389739-aumultichannelmixer_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389763-3d_mixer_unit_parameters": {
      "abstract": [
        {
          "text": "Parameters for the 3D Mixer unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389763-3d_mixer_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "3D Mixer Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389763-3d_mixer_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389928-stereo-mixer-unit-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389928-stereo-mixer-unit-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Stereo Mixer Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389928-stereo-mixer-unit-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389991-panner-audio-unit-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389991-panner-audio-unit-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Panner Audio Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389991-panner-audio-unit-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390003-aumatrixmixer-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390003-aumatrixmixer-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUMatrixMixer Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390003-aumatrixmixer-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390073-auspatialmixer-parameters": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390073-auspatialmixer-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AUSpatialMixer Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1390073-auspatialmixer-parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534041-mixer_audio_unit_properties": {
      "abstract": [
        {
          "text": "Properties for Apple mixer audio units.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534041-mixer_audio_unit_properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mixer Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534041-mixer_audio_unit_properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534150-spatial-mixer-property-ids": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534150-spatial-mixer-property-ids",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Spatial Mixer Property IDs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534150-spatial-mixer-property-ids"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584146-audio-unit-mixer-subtypes": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584146-audio-unit-mixer-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Mixer Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584146-audio-unit-mixer-subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584150-mixer_audio_unit_subtypes": {
      "abstract": [
        {
          "text": "Audio mixing audio unit subtypes for audio units provided by Apple.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584150-mixer_audio_unit_subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mixer Audio Unit Subtypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1584150-mixer_audio_unit_subtypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AU3DMixerAttenuationCurve"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AU3DMixerAttenuationCurve"
        }
      ],
      "role": "symbol",
      "title": "AU3DMixerAttenuationCurve",
      "type": "topic",
      "url": "/documentation/audiotoolbox/au3dmixerattenuationcurve"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerAttenuationCurve": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatialMixerAttenuationCurve"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerAttenuationCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatialMixerAttenuationCurve"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerAttenuationCurve",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixerattenuationcurve"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerOutputType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatialMixerOutputType"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerOutputType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatialMixerOutputType"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerOutputType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixeroutputtype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerPointSourceInHeadMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatialMixerPointSourceInHeadMode"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerPointSourceInHeadMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatialMixerPointSourceInHeadMode"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerPointSourceInHeadMode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixerpointsourceinheadmode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerRenderingFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatialMixerRenderingFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerRenderingFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatialMixerRenderingFlags"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerRenderingFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixerrenderingflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatialMixerSourceMode"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatialMixerSourceMode"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerSourceMode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixersourcemode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixersourcemode/init(rawvalue:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode/spatialMixerSourceMode_AmbienceBed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spatialMixerSourceMode_AmbienceBed"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode/spatialMixerSourceMode_AmbienceBed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatialMixerSourceMode_AmbienceBed"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerSourceMode.spatialMixerSourceMode_AmbienceBed",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixersourcemode/spatialmixersourcemode_ambiencebed"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode/spatialMixerSourceMode_Bypass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spatialMixerSourceMode_Bypass"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode/spatialMixerSourceMode_Bypass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatialMixerSourceMode_Bypass"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerSourceMode.spatialMixerSourceMode_Bypass",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixersourcemode/spatialmixersourcemode_bypass"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode/spatialMixerSourceMode_PointSource": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spatialMixerSourceMode_PointSource"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode/spatialMixerSourceMode_PointSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatialMixerSourceMode_PointSource"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerSourceMode.spatialMixerSourceMode_PointSource",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixersourcemode/spatialmixersourcemode_pointsource"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode/spatialMixerSourceMode_SpatializeIfMono": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spatialMixerSourceMode_SpatializeIfMono"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode/spatialMixerSourceMode_SpatializeIfMono",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatialMixerSourceMode_SpatializeIfMono"
        }
      ],
      "role": "symbol",
      "title": "AUSpatialMixerSourceMode.spatialMixerSourceMode_SpatializeIfMono",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatialmixersourcemode/spatialmixersourcemode_spatializeifmono"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Mixers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584146-audio-unit-mixer-subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerAttenuationCurve",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerRenderingFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390073-auspatialmixer-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389991-panner-audio-unit-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390003-aumatrixmixer-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389739-aumultichannelmixer_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534150-spatial-mixer-property-ids",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389928-stereo-mixer-unit-parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534041-mixer_audio_unit_properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584150-mixer_audio_unit_subtypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerOutputType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerPointSourceInHeadMode",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389763-3d_mixer_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve"
      ],
      "title": "Mixers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Modes",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode/spatialMixerSourceMode_AmbienceBed",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode/spatialMixerSourceMode_Bypass",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode/spatialMixerSourceMode_PointSource",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode/spatialMixerSourceMode_SpatializeIfMono"
      ],
      "title": "Modes"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AUSpatialMixerSourceMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerSourceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerSourceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Modes",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode/spatialMixerSourceMode_AmbienceBed",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode/spatialMixerSourceMode_Bypass",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode/spatialMixerSourceMode_PointSource",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerSourceMode/spatialMixerSourceMode_SpatializeIfMono"
              ],
              "title": "Modes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Mixers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584146-audio-unit-mixer-subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerAttenuationCurve",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerRenderingFlags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390073-auspatialmixer-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389991-panner-audio-unit-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1390003-aumatrixmixer-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389739-aumultichannelmixer_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534150-spatial-mixer-property-ids",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389928-stereo-mixer-unit-parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534041-mixer_audio_unit_properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1584150-mixer_audio_unit_subtypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerOutputType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatialMixerPointSourceInHeadMode",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389763-3d_mixer_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve"
              ],
              "title": "Mixers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AUSpatialMixerSourceMode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@UInt32",
                    "text": "UInt32"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerPointSourceInHeadMode/title",
          "value": "AUSpatialMixerPointSourceInHeadMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerPointSourceInHeadMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerPointSourceInHeadMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerPointSourceInHeadMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerPointSourceInHeadMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerOutputType/title",
          "value": "AUSpatialMixerOutputType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerOutputType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerOutputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerOutputType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerOutputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerSourceMode/title",
          "value": "AUSpatialMixerSourceMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerSourceMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerSourceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerSourceMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerSourceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerSourceMode~1spatialMixerSourceMode_SpatializeIfMono/title",
          "value": "kSpatialMixerSourceMode_SpatializeIfMono"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerSourceMode~1spatialMixerSourceMode_SpatializeIfMono/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatialMixerSourceMode_SpatializeIfMono"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerRenderingFlags/title",
          "value": "AUSpatialMixerRenderingFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerRenderingFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerRenderingFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerRenderingFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerRenderingFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerSourceMode~1spatialMixerSourceMode_Bypass/title",
          "value": "kSpatialMixerSourceMode_Bypass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerSourceMode~1spatialMixerSourceMode_Bypass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatialMixerSourceMode_Bypass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerAttenuationCurve/title",
          "value": "AU3DMixerAttenuationCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerAttenuationCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AU3DMixerAttenuationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerAttenuationCurve/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AU3DMixerAttenuationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerAttenuationCurve/title",
          "value": "AUSpatialMixerAttenuationCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerAttenuationCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerAttenuationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerAttenuationCurve/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatialMixerAttenuationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerSourceMode~1spatialMixerSourceMode_AmbienceBed/title",
          "value": "kSpatialMixerSourceMode_AmbienceBed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerSourceMode~1spatialMixerSourceMode_AmbienceBed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatialMixerSourceMode_AmbienceBed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerSourceMode~1spatialMixerSourceMode_PointSource/title",
          "value": "kSpatialMixerSourceMode_PointSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatialMixerSourceMode~1spatialMixerSourceMode_PointSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatialMixerSourceMode_PointSource"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/auspatialmixersourcemode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/auspatialmixersourcemode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
