{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AUSpatializationAlgorithm",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AUSpatializationAlgorithm"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AUSpatializationAlgorithm"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "AUSpatializationAlgorithm"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AUSpatializationAlgorithm"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389597-peak_limiter_unit_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Peak Limiter unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389597-peak_limiter_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Peak Limiter Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389597-peak_limiter_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389787-dynamics_processor_unit_paramete": {
      "abstract": [
        {
          "text": "Parameters for the Dynamics Processor unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389787-dynamics_processor_unit_paramete",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dynamics Processor Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389787-dynamics_processor_unit_paramete"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389932-audio-unit-graphic-eq-parameter": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389932-audio-unit-graphic-eq-parameter",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Graphic EQ Parameter ID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389932-audio-unit-graphic-eq-parameter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389950-parametric_eq_unit_parameters": {
      "abstract": [
        {
          "text": "Parameters for the Parametric EQ unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389950-parametric_eq_unit_parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Parametric EQ Unit Parameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1389950-parametric_eq_unit_parameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534092-frequency_response_constants": {
      "abstract": [
        {
          "text": "The maximum number of frequency response bin structures for the ",
          "type": "text"
        },
        {
          "code": "AudioUnitProperty_FrequencyResponse",
          "type": "codeVoice"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534092-frequency_response_constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Frequency Response Constants",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534092-frequency_response_constants"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatializationAlgorithm"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatializationAlgorithm"
        }
      ],
      "role": "symbol",
      "title": "AUSpatializationAlgorithm",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatializationalgorithm"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatializationalgorithm/init(rawvalue:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_EqualPowerPanning": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spatializationAlgorithm_EqualPowerPanning"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_EqualPowerPanning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatializationAlgorithm_EqualPowerPanning"
        }
      ],
      "role": "symbol",
      "title": "AUSpatializationAlgorithm.spatializationAlgorithm_EqualPowerPanning",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatializationalgorithm/spatializationalgorithm_equalpowerpanning"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_HRTF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spatializationAlgorithm_HRTF"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_HRTF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatializationAlgorithm_HRTF"
        }
      ],
      "role": "symbol",
      "title": "AUSpatializationAlgorithm.spatializationAlgorithm_HRTF",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatializationalgorithm/spatializationalgorithm_hrtf"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_HRTFHQ": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spatializationAlgorithm_HRTFHQ"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_HRTFHQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatializationAlgorithm_HRTFHQ"
        }
      ],
      "role": "symbol",
      "title": "AUSpatializationAlgorithm.spatializationAlgorithm_HRTFHQ",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatializationalgorithm/spatializationalgorithm_hrtfhq"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_SoundField": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spatializationAlgorithm_SoundField"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_SoundField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatializationAlgorithm_SoundField"
        }
      ],
      "role": "symbol",
      "title": "AUSpatializationAlgorithm.spatializationAlgorithm_SoundField",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatializationalgorithm/spatializationalgorithm_soundfield"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_SphericalHead": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spatializationAlgorithm_SphericalHead"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_SphericalHead",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatializationAlgorithm_SphericalHead"
        }
      ],
      "role": "symbol",
      "title": "AUSpatializationAlgorithm.spatializationAlgorithm_SphericalHead",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatializationalgorithm/spatializationalgorithm_sphericalhead"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_StereoPassThrough": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spatializationAlgorithm_StereoPassThrough"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_StereoPassThrough",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatializationAlgorithm_StereoPassThrough"
        }
      ],
      "role": "symbol",
      "title": "AUSpatializationAlgorithm.spatializationAlgorithm_StereoPassThrough",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatializationalgorithm/spatializationalgorithm_stereopassthrough"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_UseOutputType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spatializationAlgorithm_UseOutputType"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_UseOutputType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatializationAlgorithm_UseOutputType"
        }
      ],
      "role": "symbol",
      "title": "AUSpatializationAlgorithm.spatializationAlgorithm_UseOutputType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatializationalgorithm/spatializationalgorithm_useoutputtype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_VectorBasedPanning": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spatializationAlgorithm_VectorBasedPanning"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_VectorBasedPanning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatializationAlgorithm_VectorBasedPanning"
        }
      ],
      "role": "symbol",
      "title": "AUSpatializationAlgorithm.spatializationAlgorithm_VectorBasedPanning",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatializationalgorithm/spatializationalgorithm_vectorbasedpanning"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Equalizers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389950-parametric_eq_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389932-audio-unit-graphic-eq-parameter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389597-peak_limiter_unit_parameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389787-dynamics_processor_unit_paramete",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534092-frequency_response_constants"
      ],
      "title": "Equalizers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_EqualPowerPanning",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_HRTF",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_SoundField",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_SphericalHead",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_StereoPassThrough",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_VectorBasedPanning"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_HRTFHQ",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_UseOutputType"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AUSpatializationAlgorithm"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatializationAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatializationAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_EqualPowerPanning",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_HRTF",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_SoundField",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_SphericalHead",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_StereoPassThrough",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_VectorBasedPanning"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_HRTFHQ",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_UseOutputType"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Equalizers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389950-parametric_eq_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389932-audio-unit-graphic-eq-parameter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389597-peak_limiter_unit_parameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1389787-dynamics_processor_unit_paramete",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534092-frequency_response_constants"
              ],
              "title": "Equalizers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AUSpatializationAlgorithm"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@UInt32",
                    "text": "UInt32"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm~1spatializationAlgorithm_SoundField/title",
          "value": "kSpatializationAlgorithm_SoundField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm~1spatializationAlgorithm_SoundField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatializationAlgorithm_SoundField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm~1spatializationAlgorithm_EqualPowerPanning/title",
          "value": "kSpatializationAlgorithm_EqualPowerPanning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm~1spatializationAlgorithm_EqualPowerPanning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatializationAlgorithm_EqualPowerPanning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm~1spatializationAlgorithm_UseOutputType/title",
          "value": "kSpatializationAlgorithm_UseOutputType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm~1spatializationAlgorithm_UseOutputType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatializationAlgorithm_UseOutputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm/title",
          "value": "AUSpatializationAlgorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatializationAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatializationAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm~1spatializationAlgorithm_HRTF/title",
          "value": "kSpatializationAlgorithm_HRTF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm~1spatializationAlgorithm_HRTF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatializationAlgorithm_HRTF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm~1spatializationAlgorithm_VectorBasedPanning/title",
          "value": "kSpatializationAlgorithm_VectorBasedPanning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm~1spatializationAlgorithm_VectorBasedPanning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatializationAlgorithm_VectorBasedPanning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm~1spatializationAlgorithm_HRTFHQ/title",
          "value": "kSpatializationAlgorithm_HRTFHQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm~1spatializationAlgorithm_HRTFHQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatializationAlgorithm_HRTFHQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm~1spatializationAlgorithm_StereoPassThrough/title",
          "value": "kSpatializationAlgorithm_StereoPassThrough"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm~1spatializationAlgorithm_StereoPassThrough/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatializationAlgorithm_StereoPassThrough"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm~1spatializationAlgorithm_SphericalHead/title",
          "value": "kSpatializationAlgorithm_SphericalHead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm~1spatializationAlgorithm_SphericalHead/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatializationAlgorithm_SphericalHead"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/auspatializationalgorithm"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/auspatializationalgorithm"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
