{
  "abstract": [
    {
      "text": "A structure that you use to configure ducking of other non-voice audio in a voice chat.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOOtherAudioDuckingConfiguration"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@AUVoiceIOOtherAudioDuckingConfiguration",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AUVoiceIOOtherAudioDuckingConfiguration"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AUVoiceIOOtherAudioDuckingConfiguration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AUVoiceIOOtherAudioDuckingConfiguration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AUVoiceIOOtherAudioDuckingConfiguration"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this structure to specify whether to enable advanced ducking and set the ducking level of other non-voice audio in a voice chat. Advanced ducking ducks other non-voice audio based on the presence of voice activity from local and remote chat participants. Setting a higher level of ducking could increase the clarity of voice chat.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you don’t set this value, the default ducking configuration disables advanced ducking and sets the ducking level to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOOtherAudioDuckingLevel/default",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOOtherAudioDuckingConfiguration": {
      "abstract": [
        {
          "text": "A structure that you use to configure ducking of other non-voice audio in a voice chat.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUVoiceIOOtherAudioDuckingConfiguration"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOOtherAudioDuckingConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUVoiceIOOtherAudioDuckingConfiguration"
        }
      ],
      "role": "symbol",
      "title": "AUVoiceIOOtherAudioDuckingConfiguration",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auvoiceiootheraudioduckingconfiguration"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOOtherAudioDuckingConfiguration/init()": {
      "abstract": [
        {
          "text": "Creates a new ducking configuration for other non-voice audio with advanced ducking disabled and the default ducking level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOOtherAudioDuckingConfiguration/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auvoiceiootheraudioduckingconfiguration/init()"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOOtherAudioDuckingConfiguration/init(mEnableAdvancedDucking:mDuckingLevel:)": {
      "abstract": [
        {
          "text": "Creates a new ducking configuration in which you specify whether to enable advanced ducking and the ducking level of other non-voice audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "mEnableAdvancedDucking"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Darwin0A7BooleanV",
          "text": "DarwinBoolean"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mDuckingLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AUVoiceIOOtherAudioDuckingLevel",
          "text": "AUVoiceIOOtherAudioDuckingLevel"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOOtherAudioDuckingConfiguration/init(mEnableAdvancedDucking:mDuckingLevel:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(mEnableAdvancedDucking:mDuckingLevel:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auvoiceiootheraudioduckingconfiguration/init(menableadvancedducking:mduckinglevel:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOOtherAudioDuckingConfiguration/mDuckingLevel": {
      "abstract": [
        {
          "text": "The ducking level of other non-voice audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mDuckingLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AUVoiceIOOtherAudioDuckingLevel",
          "text": "AUVoiceIOOtherAudioDuckingLevel"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOOtherAudioDuckingConfiguration/mDuckingLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mDuckingLevel"
        }
      ],
      "role": "symbol",
      "title": "mDuckingLevel",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auvoiceiootheraudioduckingconfiguration/mduckinglevel"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOOtherAudioDuckingConfiguration/mEnableAdvancedDucking": {
      "abstract": [
        {
          "text": "A Boolean value that specifies whether to enable advanced ducking.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mEnableAdvancedDucking"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Darwin0A7BooleanV",
          "text": "DarwinBoolean"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOOtherAudioDuckingConfiguration/mEnableAdvancedDucking",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mEnableAdvancedDucking"
        }
      ],
      "role": "symbol",
      "title": "mEnableAdvancedDucking",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auvoiceiootheraudioduckingconfiguration/menableadvancedducking"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOOtherAudioDuckingLevel": {
      "abstract": [
        {
          "text": "The ducking level to apply to other non-voice audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUVoiceIOOtherAudioDuckingLevel"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOOtherAudioDuckingLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUVoiceIOOtherAudioDuckingLevel"
        }
      ],
      "role": "symbol",
      "title": "AUVoiceIOOtherAudioDuckingLevel",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auvoiceiootheraudioduckinglevel"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOOtherAudioDuckingLevel/default": {
      "abstract": [
        {
          "text": "The default ducking level of other non-voice audio in a typical voice chat.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOOtherAudioDuckingLevel/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUVoiceIOOtherAudioDuckingLevelDefault"
        }
      ],
      "role": "symbol",
      "title": "AUVoiceIOOtherAudioDuckingLevel.default",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auvoiceiootheraudioduckinglevel/default"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Creating-an-audio-ducking-configuration",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOOtherAudioDuckingLevel"
      ],
      "title": "Creating an audio ducking configuration"
    },
    {
      "anchor": "Inspecting-a-configuration",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOOtherAudioDuckingConfiguration/mEnableAdvancedDucking",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOOtherAudioDuckingConfiguration/mDuckingLevel"
      ],
      "title": "Inspecting a configuration"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOOtherAudioDuckingConfiguration/init()",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOOtherAudioDuckingConfiguration/init(mEnableAdvancedDucking:mDuckingLevel:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AUVoiceIOOtherAudioDuckingConfiguration"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUVoiceIOOtherAudioDuckingConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUVoiceIOOtherAudioDuckingConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-an-audio-ducking-configuration",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOOtherAudioDuckingLevel"
              ],
              "title": "Creating an audio ducking configuration"
            },
            {
              "anchor": "Inspecting-a-configuration",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOOtherAudioDuckingConfiguration/mEnableAdvancedDucking",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOOtherAudioDuckingConfiguration/mDuckingLevel"
              ],
              "title": "Inspecting a configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AUVoiceIOOtherAudioDuckingConfiguration"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUVoiceIOOtherAudioDuckingConfiguration/title",
          "value": "AUVoiceIOOtherAudioDuckingConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUVoiceIOOtherAudioDuckingConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUVoiceIOOtherAudioDuckingConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUVoiceIOOtherAudioDuckingConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUVoiceIOOtherAudioDuckingConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUVoiceIOOtherAudioDuckingLevel~1default/title",
          "value": "kAUVoiceIOOtherAudioDuckingLevelDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUVoiceIOOtherAudioDuckingLevel~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUVoiceIOOtherAudioDuckingLevelDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUVoiceIOOtherAudioDuckingLevel/title",
          "value": "AUVoiceIOOtherAudioDuckingLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUVoiceIOOtherAudioDuckingLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUVoiceIOOtherAudioDuckingLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUVoiceIOOtherAudioDuckingLevel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUVoiceIOOtherAudioDuckingLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUVoiceIOOtherAudioDuckingConfiguration~1mEnableAdvancedDucking/title",
          "value": "mEnableAdvancedDucking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUVoiceIOOtherAudioDuckingConfiguration~1mEnableAdvancedDucking/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mEnableAdvancedDucking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUVoiceIOOtherAudioDuckingConfiguration~1mDuckingLevel/title",
          "value": "mDuckingLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUVoiceIOOtherAudioDuckingConfiguration~1mDuckingLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mDuckingLevel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/auvoiceiootheraudioduckingconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/auvoiceiootheraudioduckingconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
