{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFDataChunk"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@CAFDataChunk",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CAFDataChunk"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CAFDataChunk"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CAFDataChunk"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CAFDataChunk"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFAudioDescription": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAFAudioDescription"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFAudioDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAFAudioDescription"
        }
      ],
      "role": "symbol",
      "title": "CAFAudioDescription",
      "type": "topic",
      "url": "/documentation/audiotoolbox/cafaudiodescription"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFAudioFormatListItem": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAFAudioFormatListItem"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFAudioFormatListItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAFAudioFormatListItem"
        }
      ],
      "role": "symbol",
      "title": "CAFAudioFormatListItem",
      "type": "topic",
      "url": "/documentation/audiotoolbox/cafaudioformatlistitem"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFChunkHeader": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAFChunkHeader"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFChunkHeader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAFChunkHeader"
        }
      ],
      "role": "symbol",
      "title": "CAFChunkHeader",
      "type": "topic",
      "url": "/documentation/audiotoolbox/cafchunkheader"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFDataChunk": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAFDataChunk"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFDataChunk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAFDataChunk"
        }
      ],
      "role": "symbol",
      "title": "CAFDataChunk",
      "type": "topic",
      "url": "/documentation/audiotoolbox/cafdatachunk"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFDataChunk/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFDataChunk/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/audiotoolbox/cafdatachunk/init()"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFDataChunk/init(mEditCount:mData:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "mEditCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFDataChunk/init(mEditCount:mData:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(mEditCount:mData:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/cafdatachunk/init(meditcount:mdata:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFDataChunk/mData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFDataChunk/mData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mData"
        }
      ],
      "role": "symbol",
      "title": "mData",
      "type": "topic",
      "url": "/documentation/audiotoolbox/cafdatachunk/mdata"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFDataChunk/mEditCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mEditCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFDataChunk/mEditCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mEditCount"
        }
      ],
      "role": "symbol",
      "title": "mEditCount",
      "type": "topic",
      "url": "/documentation/audiotoolbox/cafdatachunk/meditcount"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFFileHeader": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAFFileHeader"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFFileHeader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAFFileHeader"
        }
      ],
      "role": "symbol",
      "title": "CAFFileHeader",
      "type": "topic",
      "url": "/documentation/audiotoolbox/caffileheader"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFFormatFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAFFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFFormatFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAFFormatFlags"
        }
      ],
      "role": "symbol",
      "title": "CAFFormatFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/cafformatflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFInfoStrings": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAFInfoStrings"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFInfoStrings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAFInfoStrings"
        }
      ],
      "role": "symbol",
      "title": "CAFInfoStrings",
      "type": "topic",
      "url": "/documentation/audiotoolbox/cafinfostrings"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFInstrumentChunk": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAFInstrumentChunk"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFInstrumentChunk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAFInstrumentChunk"
        }
      ],
      "role": "symbol",
      "title": "CAFInstrumentChunk",
      "type": "topic",
      "url": "/documentation/audiotoolbox/cafinstrumentchunk"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFMarker": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAFMarker"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFMarker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAFMarker"
        }
      ],
      "role": "symbol",
      "title": "CAFMarker",
      "type": "topic",
      "url": "/documentation/audiotoolbox/cafmarker"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFMarkerChunk": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAFMarkerChunk"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFMarkerChunk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAFMarkerChunk"
        }
      ],
      "role": "symbol",
      "title": "CAFMarkerChunk",
      "type": "topic",
      "url": "/documentation/audiotoolbox/cafmarkerchunk"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFOverviewChunk": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAFOverviewChunk"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFOverviewChunk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAFOverviewChunk"
        }
      ],
      "role": "symbol",
      "title": "CAFOverviewChunk",
      "type": "topic",
      "url": "/documentation/audiotoolbox/cafoverviewchunk"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFOverviewSample": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAFOverviewSample"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFOverviewSample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAFOverviewSample"
        }
      ],
      "role": "symbol",
      "title": "CAFOverviewSample",
      "type": "topic",
      "url": "/documentation/audiotoolbox/cafoverviewsample"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFPacketTableHeader": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAFPacketTableHeader"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFPacketTableHeader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAFPacketTableHeader"
        }
      ],
      "role": "symbol",
      "title": "CAFPacketTableHeader",
      "type": "topic",
      "url": "/documentation/audiotoolbox/cafpackettableheader"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFPeakChunk": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAFPeakChunk"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFPeakChunk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAFPeakChunk"
        }
      ],
      "role": "symbol",
      "title": "CAFPeakChunk",
      "type": "topic",
      "url": "/documentation/audiotoolbox/cafpeakchunk"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFPositionPeak": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAFPositionPeak"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFPositionPeak",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAFPositionPeak"
        }
      ],
      "role": "symbol",
      "title": "CAFPositionPeak",
      "type": "topic",
      "url": "/documentation/audiotoolbox/cafpositionpeak"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFRegion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAFRegion"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFRegion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAFRegion"
        }
      ],
      "role": "symbol",
      "title": "CAFRegion",
      "type": "topic",
      "url": "/documentation/audiotoolbox/cafregion"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "File-Structure",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFAudioDescription",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFAudioFormatListItem",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFChunkHeader",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFFileHeader",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFFormatFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFInfoStrings",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFInstrumentChunk",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFMarker",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFMarkerChunk",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFOverviewChunk",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFOverviewSample",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFPacketTableHeader",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFPeakChunk",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFPositionPeak",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFRegion"
      ],
      "title": "File Structure"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFDataChunk/init()",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFDataChunk/init(mEditCount:mData:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFDataChunk/mData",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFDataChunk/mEditCount"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CAFDataChunk"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFDataChunk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFDataChunk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFDataChunk/mData",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFDataChunk/mEditCount"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "File-Structure",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFAudioDescription",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFAudioFormatListItem",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFChunkHeader",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFFileHeader",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFFormatFlags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFInfoStrings",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFInstrumentChunk",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFMarker",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFMarkerChunk",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFOverviewChunk",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFOverviewSample",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFPacketTableHeader",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFPeakChunk",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFPositionPeak",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAFRegion"
              ],
              "title": "File Structure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CAFDataChunk"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFMarker/title",
          "value": "CAFMarker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFMarker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFMarker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFMarker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFMarker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFInstrumentChunk/title",
          "value": "CAFInstrumentChunk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFInstrumentChunk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFInstrumentChunk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFInstrumentChunk/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFInstrumentChunk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFFileHeader/title",
          "value": "CAFFileHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFFileHeader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFFileHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFFileHeader/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFFileHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFOverviewChunk/title",
          "value": "CAFOverviewChunk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFOverviewChunk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFOverviewChunk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFOverviewChunk/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFOverviewChunk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFMarkerChunk/title",
          "value": "CAFMarkerChunk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFMarkerChunk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFMarkerChunk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFMarkerChunk/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFMarkerChunk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFDataChunk~1mEditCount/title",
          "value": "mEditCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFDataChunk~1mEditCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mEditCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFPositionPeak/title",
          "value": "CAFPositionPeak"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFPositionPeak/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFPositionPeak"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFPositionPeak/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFPositionPeak"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFAudioFormatListItem/title",
          "value": "CAFAudioFormatListItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFAudioFormatListItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFAudioFormatListItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFAudioFormatListItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFAudioFormatListItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFRegion/title",
          "value": "CAFRegion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFRegion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFRegion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFOverviewSample/title",
          "value": "CAFOverviewSample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFOverviewSample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFOverviewSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFOverviewSample/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFOverviewSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFDataChunk/title",
          "value": "CAFDataChunk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFDataChunk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFDataChunk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFDataChunk/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFDataChunk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFInfoStrings/title",
          "value": "CAFInfoStrings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFInfoStrings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFInfoStrings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFInfoStrings/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFInfoStrings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFPacketTableHeader/title",
          "value": "CAFPacketTableHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFPacketTableHeader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFPacketTableHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFPacketTableHeader/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFPacketTableHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFFormatFlags/title",
          "value": "CAFFormatFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFFormatFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFFormatFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFFormatFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFFormatFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFDataChunk~1mData/title",
          "value": "mData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFDataChunk~1mData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFAudioDescription/title",
          "value": "CAFAudioDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFAudioDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFAudioDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFAudioDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFAudioDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFPeakChunk/title",
          "value": "CAFPeakChunk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFPeakChunk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFPeakChunk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFPeakChunk/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFPeakChunk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFChunkHeader/title",
          "value": "CAFChunkHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFChunkHeader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFChunkHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAFChunkHeader/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFChunkHeader"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/cafdatachunk"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/cafdatachunk"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
