{
  "abstract": [
    {
      "text": "Deprecated. Use the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileCreateWithURL(_:_:_:_:_:_:)",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " function instead.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileCreateNew"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@ExtAudioFileCreateNew",
    "fragments": [
      {
        "kind": "identifier",
        "text": "ExtAudioFileCreateNew"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ExtAudioFileCreateNew"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.6",
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "ExtAudioFileCreateNew"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ExtAudioFileCreateNew"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@FSRef",
              "text": "FSRef"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "inParentDir"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFStringRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inFileName"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileTypeID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioFileTypeID",
              "text": "AudioFileTypeID"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inFileType"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@AudioStreamBasicDescription",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@AudioStreamBasicDescription",
              "text": "AudioStreamBasicDescription"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "inStreamDesc"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@AudioChannelLayout",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@AudioChannelLayout",
              "text": "AudioChannelLayout"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "inChannelLayout"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ExtAudioFileRef",
              "text": "ExtAudioFileRef"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "outExtAudioFile"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The directory in which to create the new file.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inParentDir"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The name of the new file.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inFileName"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The type of file to create. This is a constant from AudioToolbox/AudioFile.h, e.g. kAudioFileAIFFType. Note that this is not an HFSTypeCode.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inFileType"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The format of the audio data to be written to the file.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inStreamDesc"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The channel layout of the audio data. If non-null, this must be consistent with the number of channels specified by inStreamDesc.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inChannelLayout"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On output, a newly allocated extended audio file object.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "outExtAudioFile"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Creates a new audio file.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If the file to be created is in a compressed format, it is permissible for the sample rate in inStreamDesc to be 0, since in all cases, the file’s encoding AudioConverter may produce audio at a different sample rate than the source. The file will be created with the audio format actually produced by the encoder.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Special-Considerations",
          "level": 3,
          "text": "Special Considerations",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function is deprecated. Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileCreateWithURL(_:_:_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileTypeID": {
      "abstract": [
        {
          "text": "Operating system constants that indicate the type of file to be written or a hint about what type of file to expect from data provided.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileTypeID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileTypeID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileTypeID"
        }
      ],
      "role": "symbol",
      "title": "AudioFileTypeID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofiletypeid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileCreateNew": {
      "abstract": [
        {
          "text": "Deprecated. Use the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileCreateWithURL(_:_:_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function instead.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ExtAudioFileCreateNew"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileCreateNew",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExtAudioFileCreateNew",
      "type": "topic",
      "url": "/documentation/audiotoolbox/extaudiofilecreatenew"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileCreateWithURL(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a new audio file and associates it with a new extended audio file object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExtAudioFileCreateWithURL"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileTypeID",
          "text": "AudioFileTypeID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioStreamBasicDescription",
          "text": "AudioStreamBasicDescription"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioChannelLayout",
          "text": "AudioChannelLayout"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFileRef",
          "text": "ExtAudioFileRef"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileCreateWithURL(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ExtAudioFileCreateWithURL"
        }
      ],
      "role": "symbol",
      "title": "ExtAudioFileCreateWithURL(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/extaudiofilecreatewithurl(_:_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileOpen": {
      "abstract": [
        {
          "text": "Deprecated. Use the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileOpenURL(_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function instead.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ExtAudioFileOpen"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileOpen",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExtAudioFileOpen",
      "type": "topic",
      "url": "/documentation/audiotoolbox/extaudiofileopen"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileOpenURL(_:_:)": {
      "abstract": [
        {
          "text": "Opens an existing audio file for reading, and associates it with a new extended audio file object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExtAudioFileOpenURL"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFileRef",
          "text": "ExtAudioFileRef"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileOpenURL(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ExtAudioFileOpenURL"
        }
      ],
      "role": "symbol",
      "title": "ExtAudioFileOpenURL(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/extaudiofileopenurl(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileRef": {
      "abstract": [
        {
          "text": "An opaque structure representing an extended audio file object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExtAudioFileRef"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ExtAudioFileRef"
        }
      ],
      "role": "symbol",
      "title": "ExtAudioFileRef",
      "type": "topic",
      "url": "/documentation/audiotoolbox/extaudiofileref"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@S@AudioChannelLayout": {
      "abstract": [
        {
          "text": "A structure that specifies a channel layout in a file or in hardware.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioChannelLayout"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@AudioChannelLayout",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioChannelLayout",
      "type": "topic",
      "url": "/documentation/CoreAudioTypes/AudioChannelLayout"
    },
    "doc://com.externally.resolved.symbol/c:@S@AudioStreamBasicDescription": {
      "abstract": [
        {
          "text": "A format specification for an audio stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioStreamBasicDescription"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@AudioStreamBasicDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioStreamBasicDescription",
      "type": "topic",
      "url": "/documentation/CoreAudioTypes/AudioStreamBasicDescription"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileOpen"
      ],
      "title": "Deprecated Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtAudioFileRef/title",
          "value": "ExtAudioFileRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtAudioFileRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ExtAudioFileRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtAudioFileRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ExtAudioFileRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtAudioFileCreateWithURL(_:_:_:_:_:_:)/title",
          "value": "ExtAudioFileCreateWithURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtAudioFileCreateWithURL(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ExtAudioFileCreateWithURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@S@AudioChannelLayout/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioChannelLayout"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@S@AudioStreamBasicDescription/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioStreamBasicDescription"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtAudioFileOpenURL(_:_:)/title",
          "value": "ExtAudioFileOpenURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtAudioFileOpenURL(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ExtAudioFileOpenURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileTypeID/title",
          "value": "AudioFileTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileTypeID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileTypeID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileTypeID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/extaudiofilecreatenew"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
