{
  "abstract": [
    {
      "text": "A specifier for the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FormatList",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " property, including the codec to use.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@ExtendedAudioFormatInfo",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ExtendedAudioFormatInfo"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ExtendedAudioFormatInfo"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "ExtendedAudioFormatInfo"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ExtendedAudioFormatInfo"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBalanceFade": {
      "abstract": [
        {
          "text": "Describes audio left/right balance and front/back fade values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioBalanceFade"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBalanceFade",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioBalanceFade"
        }
      ],
      "role": "symbol",
      "title": "AudioBalanceFade",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiobalancefade"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatInfo": {
      "abstract": [
        {
          "text": "A structure that specifies an audio format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFormatInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFormatInfo"
        }
      ],
      "role": "symbol",
      "title": "AudioFormatInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioformatinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatPropertyID": {
      "abstract": [
        {
          "text": "A type for four-char codes for audio format property identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFormatPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatPropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFormatPropertyID"
        }
      ],
      "role": "symbol",
      "title": "AudioFormatPropertyID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioformatpropertyid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo": {
      "abstract": [
        {
          "text": "Audio panning information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioPanningInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioPanningInfo"
        }
      ],
      "role": "symbol",
      "title": "AudioPanningInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiopanninginfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo": {
      "abstract": [
        {
          "text": "A specifier for the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FormatList",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property, including the codec to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExtendedAudioFormatInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ExtendedAudioFormatInfo"
        }
      ],
      "role": "symbol",
      "title": "ExtendedAudioFormatInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/extendedaudioformatinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/audiotoolbox/extendedaudioformatinfo/init()"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo/init(mASBD:mMagicCookie:mMagicCookieSize:mClassDescription:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "mASBD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioStreamBasicDescription",
          "text": "AudioStreamBasicDescription"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mMagicCookie"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "mMagicCookieSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mClassDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioClassDescription",
          "text": "AudioClassDescription"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo/init(mASBD:mMagicCookie:mMagicCookieSize:mClassDescription:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(mASBD:mMagicCookie:mMagicCookieSize:mClassDescription:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/extendedaudioformatinfo/init(masbd:mmagiccookie:mmagiccookiesize:mclassdescription:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo/mASBD": {
      "abstract": [
        {
          "text": "A format specification for an audio stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mASBD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioStreamBasicDescription",
          "text": "AudioStreamBasicDescription"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo/mASBD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mASBD"
        }
      ],
      "role": "symbol",
      "title": "mASBD",
      "type": "topic",
      "url": "/documentation/audiotoolbox/extendedaudioformatinfo/masbd"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo/mClassDescription": {
      "abstract": [
        {
          "text": "A structure that describes an audio codec.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mClassDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioClassDescription",
          "text": "AudioClassDescription"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo/mClassDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mClassDescription"
        }
      ],
      "role": "symbol",
      "title": "mClassDescription",
      "type": "topic",
      "url": "/documentation/audiotoolbox/extendedaudioformatinfo/mclassdescription"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo/mMagicCookie": {
      "abstract": [
        {
          "text": "Decompression information for the audio data format specified in the ",
          "type": "text"
        },
        {
          "code": "mASBD",
          "type": "codeVoice"
        },
        {
          "text": " field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mMagicCookie"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo/mMagicCookie",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mMagicCookie"
        }
      ],
      "role": "symbol",
      "title": "mMagicCookie",
      "type": "topic",
      "url": "/documentation/audiotoolbox/extendedaudioformatinfo/mmagiccookie"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo/mMagicCookieSize": {
      "abstract": [
        {
          "text": "The size, in bytes, of the ",
          "type": "text"
        },
        {
          "code": "mMagicCookie",
          "type": "codeVoice"
        },
        {
          "text": " field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mMagicCookieSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo/mMagicCookieSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mMagicCookieSize"
        }
      ],
      "role": "symbol",
      "title": "mMagicCookieSize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/extendedaudioformatinfo/mmagiccookiesize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FormatList": {
      "abstract": [
        {
          "text": "A list of structures describing the audio formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_FormatList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatPropertyID",
          "text": "AudioFormatPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FormatList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_FormatList"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatProperty_FormatList",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioformatproperty_formatlist"
    },
    "doc://com.apple.documentation/documentation/CoreAudioTypes/AudioFormatListItem": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFormatListItem"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreAudioTypes/AudioFormatListItem",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioFormatListItem",
      "type": "topic",
      "url": "/documentation/CoreAudioTypes/AudioFormatListItem"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBalanceFade",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatInfo",
        "doc://com.apple.documentation/documentation/CoreAudioTypes/AudioFormatListItem",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatPropertyID"
      ],
      "title": "Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo/init()",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo/init(mASBD:mMagicCookie:mMagicCookieSize:mClassDescription:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo/mASBD",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo/mClassDescription",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo/mMagicCookie",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo/mMagicCookieSize"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ExtendedAudioFormatInfo"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ExtendedAudioFormatInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ExtendedAudioFormatInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo/mASBD",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo/mClassDescription",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo/mMagicCookie",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedAudioFormatInfo/mMagicCookieSize"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBalanceFade",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatInfo",
                "doc://com.apple.documentation/documentation/CoreAudioTypes/AudioFormatListItem",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatPropertyID"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ExtendedAudioFormatInfo"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatInfo/title",
          "value": "AudioFormatInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreAudioTypes~1AudioFormatListItem/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioFormatListItem"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtendedAudioFormatInfo~1mASBD/title",
          "value": "mASBD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtendedAudioFormatInfo~1mASBD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mASBD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioBalanceFade/title",
          "value": "AudioBalanceFade"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioBalanceFade/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioBalanceFade"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioBalanceFade/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioBalanceFade"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_FormatList/title",
          "value": "kAudioFormatProperty_FormatList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_FormatList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatProperty_FormatList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtendedAudioFormatInfo~1mClassDescription/title",
          "value": "mClassDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtendedAudioFormatInfo~1mClassDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mClassDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtendedAudioFormatInfo/title",
          "value": "ExtendedAudioFormatInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtendedAudioFormatInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ExtendedAudioFormatInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtendedAudioFormatInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ExtendedAudioFormatInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtendedAudioFormatInfo~1mMagicCookie/title",
          "value": "mMagicCookie"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtendedAudioFormatInfo~1mMagicCookie/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mMagicCookie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatPropertyID/title",
          "value": "AudioFormatPropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatPropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatPropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtendedAudioFormatInfo~1mMagicCookieSize/title",
          "value": "mMagicCookieSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtendedAudioFormatInfo~1mMagicCookieSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mMagicCookieSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningInfo/title",
          "value": "AudioPanningInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioPanningInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioPanningInfo"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/extendedaudioformatinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/extendedaudioformatinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
