{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/GetAudioUnitParameterDisplayType(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@GetAudioUnitParameterDisplayType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GetAudioUnitParameterDisplayType"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
        "text": "AudioUnitParameterOptions"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
        "text": "AudioUnitParameterOptions"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GetAudioUnitParameterDisplayType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "GetAudioUnitParameterDisplayType(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GetAudioUnitParameterDisplayType"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "flags"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
              "text": "AudioUnitParameterOptions"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
              "text": "AudioUnitParameterOptions"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1579363-audio_unit_carbon_view_component": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1579363-audio_unit_carbon_view_component",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Carbon View Component Types",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1579363-audio_unit_carbon_view_component"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1579365-audio_unit_carbon_view_events": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1579365-audio_unit_carbon_view_events",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Carbon View Events",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1579365-audio_unit_carbon_view_events"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1579372-audio_unit_carbon_view_selectors": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1579372-audio_unit_carbon_view_selectors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Carbon View Selectors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1579372-audio_unit_carbon_view_selectors"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUCocoaUIBase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AUCocoaUIBase"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUCocoaUIBase",
      "kind": "symbol",
      "role": "symbol",
      "title": "AUCocoaUIBase",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aucocoauibase"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCarbonView": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioUnitCarbonView"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCarbonView",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioUnitCarbonView",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitcarbonview"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCarbonViewEventID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioUnitCarbonViewEventID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCarbonViewEventID",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioUnitCarbonViewEventID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitcarbonvieweventid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCocoaViewInfo": {
      "abstract": [
        {
          "text": "The name and number of custom Cocoa views for an audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitCocoaViewInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCocoaViewInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitCocoaViewInfo"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitCocoaViewInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitcocoaviewinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions": {
      "abstract": [
        {
          "text": "Value options for audio unit parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterOptions",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameteroptions"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/GetAudioUnitParameterDisplayType(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GetAudioUnitParameterDisplayType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/GetAudioUnitParameterDisplayType(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GetAudioUnitParameterDisplayType"
        }
      ],
      "role": "symbol",
      "title": "GetAudioUnitParameterDisplayType(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/getaudiounitparameterdisplaytype(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/SetAudioUnitParameterDisplayType(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAudioUnitParameterDisplayType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
          "text": "AudioUnitParameterOptions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/SetAudioUnitParameterDisplayType(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SetAudioUnitParameterDisplayType"
        }
      ],
      "role": "symbol",
      "title": "SetAudioUnitParameterDisplayType(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/setaudiounitparameterdisplaytype(_:_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-Audio-Unit-UI",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCocoaViewInfo",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/SetAudioUnitParameterDisplayType(_:_:)"
      ],
      "title": "Configuring the Audio Unit UI"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GetAudioUnitParameterDisplayType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GetAudioUnitParameterDisplayType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-Audio-Unit-UI",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCocoaViewInfo",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUCocoaUIBase",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCarbonView",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitCarbonViewEventID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1579365-audio_unit_carbon_view_events",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1579372-audio_unit_carbon_view_selectors",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1579363-audio_unit_carbon_view_component",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/SetAudioUnitParameterDisplayType(_:_:)"
              ],
              "title": "Configuring the Audio Unit UI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
                    "text": "AudioUnitParameterOptions"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GetAudioUnitParameterDisplayType"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterOptions",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@AudioUnitParameterOptions",
                    "text": "AudioUnitParameterOptions"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "flags"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1SetAudioUnitParameterDisplayType(_:_:)/title",
          "value": "SetAudioUnitParameterDisplayType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1SetAudioUnitParameterDisplayType(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SetAudioUnitParameterDisplayType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitCocoaViewInfo/title",
          "value": "AudioUnitCocoaViewInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitCocoaViewInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitCocoaViewInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitCocoaViewInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitCocoaViewInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1GetAudioUnitParameterDisplayType(_:)/title",
          "value": "GetAudioUnitParameterDisplayType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1GetAudioUnitParameterDisplayType(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GetAudioUnitParameterDisplayType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions/title",
          "value": "AudioUnitParameterOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/getaudiounitparameterdisplaytype(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/getaudiounitparameterdisplaytype(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
