{
  "abstract": [
    {
      "text": "The time- and transport-related callback functions for an audio unit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@HostCallbackInfo",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HostCallbackInfo"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HostCallbackInfo"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "HostCallbackInfo"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HostCallbackInfo"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534082-other-plug-in-formats": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534082-other-plug-in-formats",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Other Plug-In Formats",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534082-other-plug-in-formats"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534177-renderquality": {
      "abstract": [
        {
          "text": "Render quality settings for audio units.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534177-renderquality",
      "kind": "article",
      "role": "collectionGroup",
      "title": "RenderQuality",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1534177-renderquality"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo": {
      "abstract": [
        {
          "text": "The time- and transport-related callback functions for an audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HostCallbackInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HostCallbackInfo"
        }
      ],
      "role": "symbol",
      "title": "HostCallbackInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/hostcallbackinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo/beatAndTempoProc": {
      "abstract": [
        {
          "text": "Your callback function that provides beat and tempo information to an audio unit. May be ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beatAndTempoProc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HostCallback_GetBeatAndTempo",
          "text": "HostCallback_GetBeatAndTempo"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo/beatAndTempoProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beatAndTempoProc"
        }
      ],
      "role": "symbol",
      "title": "beatAndTempoProc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/hostcallbackinfo/beatandtempoproc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo/hostUserData": {
      "abstract": [
        {
          "text": "Custom data specified by your application. May be ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hostUserData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo/hostUserData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hostUserData"
        }
      ],
      "role": "symbol",
      "title": "hostUserData",
      "type": "topic",
      "url": "/documentation/audiotoolbox/hostcallbackinfo/hostuserdata"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/audiotoolbox/hostcallbackinfo/init()"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo/init(hostUserData:beatAndTempoProc:musicalTimeLocationProc:transportStateProc:transportStateProc2:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "hostUserData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "beatAndTempoProc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HostCallback_GetBeatAndTempo",
          "text": "HostCallback_GetBeatAndTempo"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "musicalTimeLocationProc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HostCallback_GetMusicalTimeLocation",
          "text": "HostCallback_GetMusicalTimeLocation"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "transportStateProc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HostCallback_GetTransportState",
          "text": "HostCallback_GetTransportState"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "transportStateProc2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HostCallback_GetTransportState2",
          "text": "HostCallback_GetTransportState2"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo/init(hostUserData:beatAndTempoProc:musicalTimeLocationProc:transportStateProc:transportStateProc2:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(hostUserData:beatAndTempoProc:musicalTimeLocationProc:transportStateProc:transportStateProc2:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/hostcallbackinfo/init(hostuserdata:beatandtempoproc:musicaltimelocationproc:transportstateproc:transportstateproc2:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo/musicalTimeLocationProc": {
      "abstract": [
        {
          "text": "Your callback function that provides musical timeline information to an audio unit. May be ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "musicalTimeLocationProc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HostCallback_GetMusicalTimeLocation",
          "text": "HostCallback_GetMusicalTimeLocation"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo/musicalTimeLocationProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "musicalTimeLocationProc"
        }
      ],
      "role": "symbol",
      "title": "musicalTimeLocationProc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/hostcallbackinfo/musicaltimelocationproc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo/transportStateProc": {
      "abstract": [
        {
          "text": "Your callback function that provides audio transport state information (",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "play",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "rewind",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ", and so on) to an audio unit. May be ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transportStateProc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HostCallback_GetTransportState",
          "text": "HostCallback_GetTransportState"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo/transportStateProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "transportStateProc"
        }
      ],
      "role": "symbol",
      "title": "transportStateProc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/hostcallbackinfo/transportstateproc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo/transportStateProc2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transportStateProc2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HostCallback_GetTransportState2",
          "text": "HostCallback_GetTransportState2"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo/transportStateProc2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "transportStateProc2"
        }
      ],
      "role": "symbol",
      "title": "transportStateProc2",
      "type": "topic",
      "url": "/documentation/audiotoolbox/hostcallbackinfo/transportstateproc2"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/general-audio-unit-properties": {
      "abstract": [
        {
          "text": "Properties that apply to any audio unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/general-audio-unit-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "General Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/general-audio-unit-properties"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "General",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534082-other-plug-in-formats",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534177-renderquality",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/general-audio-unit-properties"
      ],
      "title": "General"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo/init()",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo/init(hostUserData:beatAndTempoProc:musicalTimeLocationProc:transportStateProc:transportStateProc2:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo/beatAndTempoProc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo/hostUserData",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo/musicalTimeLocationProc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo/transportStateProc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo/transportStateProc2"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HostCallbackInfo"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HostCallbackInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HostCallbackInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo/beatAndTempoProc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo/hostUserData",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo/musicalTimeLocationProc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo/transportStateProc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo/transportStateProc2"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "General",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534082-other-plug-in-formats",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1534177-renderquality",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/general-audio-unit-properties"
              ],
              "title": "General"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HostCallbackInfo"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallbackInfo~1musicalTimeLocationProc/title",
          "value": "musicalTimeLocationProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallbackInfo~1musicalTimeLocationProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "musicalTimeLocationProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallbackInfo~1beatAndTempoProc/title",
          "value": "beatAndTempoProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallbackInfo~1beatAndTempoProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "beatAndTempoProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallbackInfo/title",
          "value": "HostCallbackInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallbackInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HostCallbackInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallbackInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HostCallbackInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallbackInfo~1hostUserData/title",
          "value": "hostUserData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallbackInfo~1hostUserData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hostUserData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallbackInfo~1transportStateProc2/title",
          "value": "transportStateProc2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallbackInfo~1transportStateProc2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "transportStateProc2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallbackInfo~1transportStateProc/title",
          "value": "transportStateProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallbackInfo~1transportStateProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "transportStateProc"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/hostcallbackinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/hostcallbackinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
