{
  "abstract": [
    {
      "text": "When called by the system, provides musical timing information to an audio unit from a host application.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallback_GetMusicalTimeLocation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@HostCallback_GetMusicalTimeLocation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HostCallback_GetMusicalTimeLocation"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HostCallback_GetMusicalTimeLocation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "HostCallback_GetMusicalTimeLocation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HostCallback_GetMusicalTimeLocation"
            },
            {
              "kind": "text",
              "text": " = ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sv",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sv",
              "text": "UnsafeMutableRawPointer"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": ">?, "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s7Float32a",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s7Float32a",
              "text": "Float32"
            },
            {
              "kind": "text",
              "text": ">?, "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": ">?, "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s7Float64a",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s7Float64a",
              "text": "Float64"
            },
            {
              "kind": "text",
              "text": ">?) -> "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Custom data that you provided when registering your callback with the audio unit.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inHostUserData"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On output, the number of samples until the next beat.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "outDeltaSampleOffsetToNextBeat"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On output, the numerator for a musical time signature.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "outTimeSig_Numerator"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On output, the denominator for a musical time signature.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "outTimeSig_Denominator"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "outCurrentMeasureDownBeat"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you named your callback function ",
              "type": "text"
            },
            {
              "code": "MyHostCallback_GetMusicalTimeLocation",
              "type": "codeVoice"
            },
            {
              "text": ", you would declare it like this:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUInputSamplesInOutputCallback": {
      "abstract": [
        {
          "text": "Called by the system when an audio unit has provided a buffer of output samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUInputSamplesInOutputCallback"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUInputSamplesInOutputCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUInputSamplesInOutputCallback"
        }
      ],
      "role": "symbol",
      "title": "AUInputSamplesInOutputCallback",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auinputsamplesinoutputcallback"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUMIDIOutputCallback": {
      "abstract": [
        {
          "text": "When called by a host application, gets MIDI data from an audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUMIDIOutputCallback"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUMIDIOutputCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUMIDIOutputCallback"
        }
      ],
      "role": "symbol",
      "title": "AUMIDIOutputCallback",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aumidioutputcallback"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallback_GetBeatAndTempo": {
      "abstract": [
        {
          "text": "When called by the system, provides beat and tempo information to an audio unit from a host application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HostCallback_GetBeatAndTempo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallback_GetBeatAndTempo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HostCallback_GetBeatAndTempo"
        }
      ],
      "role": "symbol",
      "title": "HostCallback_GetBeatAndTempo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/hostcallback_getbeatandtempo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallback_GetMusicalTimeLocation": {
      "abstract": [
        {
          "text": "When called by the system, provides musical timing information to an audio unit from a host application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HostCallback_GetMusicalTimeLocation"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallback_GetMusicalTimeLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HostCallback_GetMusicalTimeLocation"
        }
      ],
      "role": "symbol",
      "title": "HostCallback_GetMusicalTimeLocation",
      "type": "topic",
      "url": "/documentation/audiotoolbox/hostcallback_getmusicaltimelocation"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallback_GetTransportState": {
      "abstract": [
        {
          "text": "When called by the system, provides audio transport state and timeline information to an audio unit from a host application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HostCallback_GetTransportState"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallback_GetTransportState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HostCallback_GetTransportState"
        }
      ],
      "role": "symbol",
      "title": "HostCallback_GetTransportState",
      "type": "topic",
      "url": "/documentation/audiotoolbox/hostcallback_gettransportstate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallback_GetTransportState2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HostCallback_GetTransportState2"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallback_GetTransportState2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HostCallback_GetTransportState2"
        }
      ],
      "role": "symbol",
      "title": "HostCallback_GetTransportState2",
      "type": "topic",
      "url": "/documentation/audiotoolbox/hostcallback_gettransportstate2"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    },
    "doc://com.externally.resolved.symbol/s:Sv": {
      "abstract": [
        {
          "text": "A raw pointer for accessing and manipulating untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sv",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutableRawPointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutableRawPointer"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    },
    "doc://com.externally.resolved.symbol/s:s7Float32a": {
      "abstract": [
        {
          "text": "A 32-bit floating point type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Float32"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7Float32a",
      "kind": "symbol",
      "role": "symbol",
      "title": "Float32",
      "type": "topic",
      "url": "/documentation/Swift/Float32"
    },
    "doc://com.externally.resolved.symbol/s:s7Float64a": {
      "abstract": [
        {
          "text": "A 64-bit floating point type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Float64"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7Float64a",
      "kind": "symbol",
      "role": "symbol",
      "title": "Float64",
      "type": "topic",
      "url": "/documentation/Swift/Float64"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Information-from-the-Host",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallback_GetBeatAndTempo",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallback_GetTransportState",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallback_GetTransportState2",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUInputSamplesInOutputCallback",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUMIDIOutputCallback"
      ],
      "title": "Getting Information from the Host"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HostCallback_GetMusicalTimeLocation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HostCallback_GetMusicalTimeLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HostCallback_GetMusicalTimeLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Information-from-the-Host",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallback_GetBeatAndTempo",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallback_GetTransportState",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallback_GetTransportState2",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUInputSamplesInOutputCallback",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUMIDIOutputCallback"
              ],
              "title": "Getting Information from the Host"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:*FI(#*v#*i#*f#S3_#*d)",
                    "text": "int (*)(void *, unsigned int *, float *, unsigned int *, double *)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HostCallback_GetMusicalTimeLocation"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUMIDIOutputCallback/title",
          "value": "AUMIDIOutputCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUMIDIOutputCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUMIDIOutputCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUMIDIOutputCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUMIDIOutputCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallback_GetTransportState/title",
          "value": "HostCallback_GetTransportState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallback_GetTransportState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HostCallback_GetTransportState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallback_GetTransportState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HostCallback_GetTransportState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallback_GetBeatAndTempo/title",
          "value": "HostCallback_GetBeatAndTempo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallback_GetBeatAndTempo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HostCallback_GetBeatAndTempo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallback_GetBeatAndTempo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HostCallback_GetBeatAndTempo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallback_GetTransportState2/title",
          "value": "HostCallback_GetTransportState2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallback_GetTransportState2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HostCallback_GetTransportState2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallback_GetTransportState2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HostCallback_GetTransportState2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUInputSamplesInOutputCallback/title",
          "value": "AUInputSamplesInOutputCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUInputSamplesInOutputCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUInputSamplesInOutputCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUInputSamplesInOutputCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUInputSamplesInOutputCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallback_GetMusicalTimeLocation/title",
          "value": "HostCallback_GetMusicalTimeLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallback_GetMusicalTimeLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HostCallback_GetMusicalTimeLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallback_GetMusicalTimeLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HostCallback_GetMusicalTimeLocation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/hostcallback_getmusicaltimelocation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/hostcallback_getmusicaltimelocation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
