{
  "abstract": [
    {
      "text": "Add custom audio processing and MIDI instruments to your app by hosting Audio Unit (AU) plug-ins.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v3-plug-ins"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/incorporating-audio-effects-and-instruments"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.15",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "16.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Incorporating Audio Effects and Instruments"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This sample app shows you how to use AU plug-ins in your iOS and macOS apps. You find and instantiate plug-ins, incorporate their user interfaces into your app’s interface, and work with their presets.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The sample app has targets for iOS and macOS. Both versions have three primary classes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "architecture",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "HostViewController",
                      "type": "codeVoice"
                    },
                    {
                      "text": " and its associated Storyboard provide the user interface.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "AudioUnitManager",
                      "type": "codeVoice"
                    },
                    {
                      "text": " manages the interactions with the effect and instrument plug-ins.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "SimplePlayEngine",
                      "type": "codeVoice"
                    },
                    {
                      "text": " uses ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioEngine",
                      "isActive": true,
                      "overridingTitle": "AVAudioEngine",
                      "overridingTitleInlineContent": [
                        {
                          "text": "AVAudioEngine",
                          "type": "text"
                        }
                      ],
                      "type": "reference"
                    },
                    {
                      "text": " to play back audio samples and MIDI data.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Find-Audio-Units",
          "level": 3,
          "text": "Find Audio Units",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You find Audio Units that are registered with the host system by creating an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentDescription",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " defining your search criteria. The sample app searches for component types, either audio effects (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Effect",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ") or MIDI instruments (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_MusicDevice",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "). You can also pass values for the other fields of ",
              "type": "text"
            },
            {
              "code": "AudioComponentDescription",
              "type": "codeVoice"
            },
            {
              "text": " or pass ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": " as a wildcard matching all values. Get the shared instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioUnitComponentManager",
              "isActive": true,
              "overridingTitle": "AVAudioUnitComponentManager",
              "overridingTitleInlineContent": [
                {
                  "text": "AVAudioUnitComponentManager",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": " and call its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioUnitComponentManager/components(matching:)-96l2c",
              "isActive": true,
              "overridingTitle": "components(matching:)",
              "overridingTitleInlineContent": [
                {
                  "text": "components(matching:)",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": " method to find the components matching your search criteria.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Make a component description matching any Audio Unit.",
            "let description = AudioComponentDescription(componentType: 0,",
            "                                            componentSubType: 0,",
            "                                            componentManufacturer: 0,",
            "                                            componentFlags: 0,",
            "                                            componentFlagsMask: 0)",
            "",
            "let components = AVAudioUnitComponentManager.shared().components(matching: description)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "This method returns an array of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioUnitComponent",
              "isActive": true,
              "overridingTitle": "AVAudioUnitComponent",
              "overridingTitleInlineContent": [
                {
                  "text": "AVAudioUnitComponent",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": " objects matching the component description, or an empty array if it found no matches. You can access a component’s properties to determine its capabilities and find identifying values, such as its name and manufacturer, for display in your user interface.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Instantiate-Audio-Units",
          "level": 3,
          "text": "Instantiate Audio Units",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When the user selects an Audio Unit in the user interface, your app needs to find the component and instantiate it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "iOS supports third-party plug-ins built using the latest Audio Unit standard (AUv3), which is based on the ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " model. Like all App Extensions in iOS, AUv3 plug-ins run ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "out-of-process",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ", which means they run in a dedicated process outside your app, and communication with the extension is done over interprocess communication (IPC).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You instantiate an AU by calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioUnit/instantiate(with:options:completionHandler:)",
              "isActive": true,
              "overridingTitle": "instantiate(with:options:completionHandler:)",
              "overridingTitleInlineContent": [
                {
                  "text": "instantiate(with:options:completionHandler:)",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": " method, passing it the component description. This method asynchronously returns the instantiated ",
              "type": "text"
            },
            {
              "code": "AVAudioUnit",
              "type": "codeVoice"
            },
            {
              "text": " or an ",
              "type": "text"
            },
            {
              "code": "Error",
              "type": "codeVoice"
            },
            {
              "text": " if the process failed. You must avoid blocking your application’s main thread when instantiating an Audio Unit.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Instantiate the Audio Unit",
            "AVAudioUnit.instantiate(with: description) { avAudioUnit, error in",
            "   // Use Audio Unit or handle error",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "In macOS, AUv3 plug-ins also default to running out-of-process. Running an Audio Unit this way is safer and more secure, because a misbehaving plug-in can’t corrupt or crash your app. However, the interprocess communication required of this model adds some small but potentially significant overhead. This can be problematic in professional audio environments where multiple Audio Units are used, especially when rendering at small audio I/O buffer sizes. To resolve this problem, AU authors can package their plug-ins to be run ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "in-process",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ". In macOS only, you can load an appropriately packaged plug-in in-process by passing that instantiation option to the ",
              "type": "text"
            },
            {
              "code": "instantiate",
              "type": "codeVoice"
            },
            {
              "text": " method, as shown below.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let options: AudioComponentInstantiationOptions = .loadInProcess",
            "",
            "// Instantiate the Audio Unit",
            "AVAudioUnit.instantiate(with: description, options: options) { avAudioUnit, error in",
            "   // Use Audio Unit or handle error",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "iOS and macOS support using existing AUv2 plug-ins. iOS supports only those provided by the operating system, but macOS supports third-party AUv2 plug-ins as well. In both platforms, these plug-ins are ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "always",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": " run as part of the host app’s process.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Present-an-Audio-Units-Custom-View",
          "level": 3,
          "text": "Present an Audio Unit’s Custom View",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A plug-in can provide a custom user interface to control its parameters. You get the custom view by asking the plug-in for its view controller, which returns an instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreAudioKit/AUViewController",
              "isActive": true,
              "overridingTitle": "AUViewController",
              "overridingTitleInlineContent": [
                {
                  "text": "AUViewController",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": ", or ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if it doesn’t provide a custom view. You add the view controller’s view to your user interface using the appropriate approach for your platform.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func loadAudioUnitViewController(completion: @escaping (ViewController?) -> Void) {",
            "    if let avAudioUnit = avAudioUnit {",
            "        // Call our AVAudioUnit extension to request the ViewController",
            "        // We will obtain a generic view if the plugin does not provide a custom view",
            "        avAudioUnit.requestViewController(completion: completion)",
            "    } else {",
            "        completion(nil)",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Select-Alternative-View-Configurations",
          "level": 3,
          "text": "Select Alternative View Configurations",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "All AU plug-ins can provide a custom user interface, but AUv3 plug-ins may also provide alternative views. A host app can support multiple view configurations. For example, an iOS app may provide compact and expanded views and switch between them depending on the device size or orientation. You define one or more supported view configurations using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreAudioKit/AUAudioUnitViewConfiguration",
              "isActive": true,
              "overridingTitle": "AUAudioUnitViewConfiguration",
              "overridingTitleInlineContent": [
                {
                  "text": "AUAudioUnitViewConfiguration",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": " class.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "private var currentViewConfigurationIndex = 1",
            "",
            "/// View configurations supported by the host app",
            "private var viewConfigurations: [AUAudioUnitViewConfiguration] = {",
            "    let compact = AUAudioUnitViewConfiguration(width: 400, height: 100, hostHasController: false)",
            "    let expanded = AUAudioUnitViewConfiguration(width: 800, height: 500, hostHasController: false)",
            "    return [compact, expanded]",
            "}()"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The view configuration object’s ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/CoreAudioKit/AUAudioUnitViewConfiguration/hostHasController",
                  "isActive": true,
                  "overridingTitle": "hostHasController",
                  "overridingTitleInlineContent": [
                    {
                      "text": "hostHasController",
                      "type": "text"
                    }
                  ],
                  "type": "reference"
                },
                {
                  "text": " property indicates whether the host app should show its control surface for the view configuration. The host app should respect this setting and update its user interface accordingly.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "The host can ask the plug-in which, if any, custom view configurations it supports.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let supportedConfigurations = audioUnit.supportedViewConfigurations(viewConfigurations)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "When the host switches between its supported configurations, it can ask the Audio Unit to do the same. The sample app defines two configurations and attempts to toggle between them.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "/// Toggles the current view mode (compact or expanded)",
            "func toggleViewMode() {",
            "    guard let audioUnit = audioUnit else { return }",
            "    currentViewConfigurationIndex = currentViewConfigurationIndex == 0 ? 1 : 0",
            "    audioUnit.select(viewConfigurations[currentViewConfigurationIndex])",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Load-Factory-Presets",
          "level": 3,
          "text": "Load Factory Presets",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A plug-in author can optionally provide one or more presets that define specific configurations of the plug-in’s parameter values. You access an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object’s presets through its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/factoryPresets",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property, which returns an array of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitPreset",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instances, or an empty array if it defines none.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "/// Gets the audio unit's factory presets.",
            "public var factoryPresets: [Preset] {",
            "    guard let presets = audioUnit?.factoryPresets else { return [] }",
            "    return presets.map { Preset(preset: $0) }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The sample app uses a simple wrapper type called ",
              "type": "text"
            },
            {
              "code": "Preset",
              "type": "codeVoice"
            },
            {
              "text": " to pass to the user interface tier. The view controller uses these objects to build the app’s preset selection interface.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Manage-User-Presets",
          "level": 3,
          "text": "Manage User Presets",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A plug-in may also support ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "user presets",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ", which are user-configured parameter settings. You query the Audio Unit’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/supportsUserPresets",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to determine if it supports saving user presets.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "var supportsUserPresets: Bool {",
            "    return audioUnit?.supportsUserPresets ?? false",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "If a plug-in supports user presets, you can get the currently saved presets by querying its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/userPresets",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "/// Gets the audio unit's user presets.",
            "public var userPresets: [Preset] {",
            "    guard let presets = audioUnit?.userPresets else { return [] }",
            "    return presets.map { Preset(preset: $0) }.reversed()",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "To be notified of changes to the Audio Unit’s user presets, you add a key-value observer to the ",
              "type": "text"
            },
            {
              "code": "userPresets",
              "type": "codeVoice"
            },
            {
              "text": " property. By observing changes to this property, you’ll get callbacks as presets are added or deleted.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Add key-value observer to the userPresets property.",
            "observation = audioUnit?.observe(\\.userPresets) { _, _ in",
            "    // User presets changed. Update the user interface.",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "To create a new user preset, first create an instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitPreset",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and give it a user-defined name and a negative ",
              "type": "text"
            },
            {
              "code": "number",
              "type": "codeVoice"
            },
            {
              "text": " value (user presets require a negative value for this property). Then call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/saveUserPreset(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, which persists the parameter state so the Audio Unit can recall it later.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let preset = AUAudioUnitPreset()",
            "preset.name = “A Custom Preset”",
            "preset.number = -1",
            "",
            "// Save the preset’s parameter state.",
            "do {",
            "    try audioUnit.saveUserPreset(preset)",
            "} catch {",
            "    // Handle the error.",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "If the user decides to delete this or another user preset, you call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/deleteUserPreset(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to remove it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Select-Factory-and-User-Presets",
          "level": 3,
          "text": "Select Factory and User Presets",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To select a factory or user preset, set it as the Audio Unit’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/currentPreset",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property. This restores the plug-in’s parameter state to the values stored with the specified preset.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "/// Get or set the audio unit's current preset.",
            "public var currentPreset: Preset? {",
            "    get {",
            "        guard let preset = audioUnit?.currentPreset else { return nil }",
            "        return Preset(preset: preset)",
            "    }",
            "    set {",
            "        audioUnit?.currentPreset = newValue?.audioUnitPreset",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "21130483bd32/IncorporatingAudioEffectsAndInstruments.zip": {
      "checksum": "21130483bd3215df8dc67e07f1595c2cd08d282ebcdaabc3ddac9d12ae03b59fecce0a179f11167f246d51b1e952698f8aef584e64dac89c8da57ab77bd25d45",
      "identifier": "21130483bd32/IncorporatingAudioEffectsAndInstruments.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/21130483bd32/IncorporatingAudioEffectsAndInstruments.zip"
    },
    "architecture": {
      "alt": "Sample App Architecture",
      "identifier": "architecture",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/6a43fb8e2ca660886a2d0941b0ae8ba7/architecture.png"
        }
      ]
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit": {
      "abstract": [
        {
          "text": "A class that defines a host’s interface to an audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioUnit"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUAudioUnit"
        }
      ],
      "role": "symbol",
      "title": "AUAudioUnit",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounit"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/currentPreset": {
      "abstract": [
        {
          "text": "The audio unit’s last-selected preset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentPreset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AUAudioUnitPreset",
          "text": "AUAudioUnitPreset"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/currentPreset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentPreset"
        }
      ],
      "role": "symbol",
      "title": "currentPreset",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounit/currentpreset"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/deleteUserPreset(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteUserPreset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AUAudioUnitPreset",
          "text": "AUAudioUnitPreset"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/deleteUserPreset(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deleteUserPreset:error:"
        }
      ],
      "role": "symbol",
      "title": "deleteUserPreset(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounit/deleteuserpreset(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/factoryPresets": {
      "abstract": [
        {
          "text": "A collection of presets provided by the audio unit’s developer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "factoryPresets"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AUAudioUnitPreset",
          "text": "AUAudioUnitPreset"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/factoryPresets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "factoryPresets"
        }
      ],
      "role": "symbol",
      "title": "factoryPresets",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounit/factorypresets"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/saveUserPreset(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "saveUserPreset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AUAudioUnitPreset",
          "text": "AUAudioUnitPreset"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/saveUserPreset(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "saveUserPreset:error:"
        }
      ],
      "role": "symbol",
      "title": "saveUserPreset(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounit/saveuserpreset(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/supportsUserPresets": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsUserPresets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/supportsUserPresets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsUserPresets"
        }
      ],
      "role": "symbol",
      "title": "supportsUserPresets",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounit/supportsuserpresets"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/userPresets": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userPresets"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AUAudioUnitPreset",
          "text": "AUAudioUnitPreset"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/userPresets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userPresets"
        }
      ],
      "role": "symbol",
      "title": "userPresets",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounit/userpresets"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitBus": {
      "abstract": [
        {
          "text": "A class that defines an input or output connection point on an audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioUnitBus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitBus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUAudioUnitBus"
        }
      ],
      "role": "symbol",
      "title": "AUAudioUnitBus",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounitbus"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitBusArray": {
      "abstract": [
        {
          "text": "A class that defines a container for an audio unit’s input or output busses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioUnitBusArray"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitBusArray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUAudioUnitBusArray"
        }
      ],
      "role": "symbol",
      "title": "AUAudioUnitBusArray",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounitbusarray"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitFactory": {
      "abstract": [
        {
          "text": "An object that creates a version 3 audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioUnitFactory"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitFactory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUAudioUnitFactory"
        }
      ],
      "role": "symbol",
      "title": "AUAudioUnitFactory",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounitfactory"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitPreset": {
      "abstract": [
        {
          "text": "A class that describes an interface for custom parameter settings provided by the audio unit developer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioUnitPreset"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitPreset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUAudioUnitPreset"
        }
      ],
      "role": "symbol",
      "title": "AUAudioUnitPreset",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounitpreset"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitV2Bridge": {
      "abstract": [
        {
          "text": "A class that wraps a version 2 audio unit as version 3 audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioUnitV2Bridge"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitV2Bridge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUAudioUnitV2Bridge"
        }
      ],
      "role": "symbol",
      "title": "AUAudioUnitV2Bridge",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounitv2bridge"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentDescription": {
      "abstract": [
        {
          "text": "Identifying information for an audio component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioComponentDescription"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioComponentDescription"
        }
      ],
      "role": "symbol",
      "title": "AudioComponentDescription",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocomponentdescription"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitExtensionCopyComponentList(_:)": {
      "abstract": [
        {
          "text": "Returns the component registrations for a given audio unit extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitExtensionCopyComponentList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitExtensionCopyComponentList(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitExtensionCopyComponentList"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitExtensionCopyComponentList(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitextensioncopycomponentlist(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitExtensionSetComponentList(_:_:)": {
      "abstract": [
        {
          "text": "Allows the implementor of an audio unit extension to dynamically modify the list of component registrations for the extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitExtensionSetComponentList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitExtensionSetComponentList(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitExtensionSetComponentList"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitExtensionSetComponentList(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitextensionsetcomponentlist(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v3-plug-ins": {
      "abstract": [
        {
          "text": "Deliver custom audio effects, instruments, and other audio behaviors using an Audio Unit v3 app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v3-plug-ins",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit v3 Plug-Ins",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-v3-plug-ins"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/debugging-out-of-process-audio-units-on-apple-silicon": {
      "abstract": [
        {
          "text": "Connect to out-of-process audio units using the Xcode debugger.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/debugging-out-of-process-audio-units-on-apple-silicon",
      "kind": "article",
      "role": "article",
      "title": "Debugging Out-of-Process Audio Units on Apple Silicon",
      "type": "topic",
      "url": "/documentation/audiotoolbox/debugging-out-of-process-audio-units-on-apple-silicon"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Effect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitType_Effect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Effect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitType_Effect"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitType_Effect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounittype_effect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_MusicDevice": {
      "abstract": [
        {
          "text": "An instrument unit can be used as a software musical instrument, such as a sampler or synthesizer. It responds to MIDI (Musical Instrument Digital Interface) control signals and can create notes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitType_MusicDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_MusicDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitType_MusicDevice"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitType_MusicDevice",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounittype_musicdevice"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVAudioEngine": {
      "abstract": [
        {
          "text": "An object that manages a graph of audio nodes, controls playback, and configures real-time rendering constraints.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioEngine"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioEngine",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioEngine",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioEngine"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVAudioUnit/instantiate(with:options:completionHandler:)": {
      "abstract": [
        {
          "text": "Creates an instance of an audio unit component asynchronously and wraps it in an audio unit class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instantiate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "audioComponentDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioComponentDescription",
          "text": "AudioComponentDescription"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioComponentInstantiationOptions",
          "text": "AudioComponentInstantiationOptions"
        },
        {
          "kind": "text",
          "text": " = [], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "@escaping"
        },
        {
          "kind": "text",
          "text": " ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioUnit",
          "text": "AVAudioUnit"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioUnit/instantiate(with:options:completionHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "instantiate(with:options:completionHandler:)",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioUnit/instantiate(with:options:completionHandler:)"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVAudioUnitComponent": {
      "abstract": [
        {
          "text": "An object that provides details about an audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitComponent"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioUnitComponent",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioUnitComponent",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioUnitComponent"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVAudioUnitComponentManager": {
      "abstract": [
        {
          "text": "An object that provides a way to search and query audio components that the system registers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitComponentManager"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioUnitComponentManager",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioUnitComponentManager",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioUnitComponentManager"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVAudioUnitComponentManager/components(matching:)-96l2c": {
      "abstract": [
        {
          "text": "Gets an array of audio component objects that match the search predicate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "components"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "matching"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "predicate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioUnitComponent",
          "text": "AVAudioUnitComponent"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioUnitComponentManager/components(matching:)-96l2c",
      "kind": "symbol",
      "role": "symbol",
      "title": "components(matching:)",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioUnitComponentManager/components(matching:)-96l2c"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/creating-an-audio-unit-extension": {
      "abstract": [
        {
          "text": "Build an extension by using an Xcode template.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/creating-an-audio-unit-extension",
      "kind": "article",
      "role": "article",
      "title": "Creating an audio unit extension",
      "type": "topic",
      "url": "/documentation/AVFAudio/creating-an-audio-unit-extension"
    },
    "doc://com.apple.documentation/documentation/CoreAudioKit/AUAudioUnitViewConfiguration": {
      "abstract": [
        {
          "text": "A configuration object that describes how to present the audio unit’s user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioUnitViewConfiguration"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreAudioKit/AUAudioUnitViewConfiguration",
      "kind": "symbol",
      "role": "symbol",
      "title": "AUAudioUnitViewConfiguration",
      "type": "topic",
      "url": "/documentation/CoreAudioKit/AUAudioUnitViewConfiguration"
    },
    "doc://com.apple.documentation/documentation/CoreAudioKit/AUAudioUnitViewConfiguration/hostHasController": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the host shows its own control surface in this view configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hostHasController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreAudioKit/AUAudioUnitViewConfiguration/hostHasController",
      "kind": "symbol",
      "role": "symbol",
      "title": "hostHasController",
      "type": "topic",
      "url": "/documentation/CoreAudioKit/AUAudioUnitViewConfiguration/hostHasController"
    },
    "doc://com.apple.documentation/documentation/CoreAudioKit/AUViewController": {
      "abstract": [
        {
          "text": "The base class to extend when creating a custom user interface for an audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUViewController"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreAudioKit/AUViewController",
      "kind": "symbol",
      "role": "symbol",
      "title": "AUViewController",
      "type": "topic",
      "url": "/documentation/CoreAudioKit/AUViewController"
    },
    "doc://com.apple.documentation/documentation/avfoundation/creating_custom_audio_effects": {
      "abstract": [
        {
          "text": "Add custom audio-effect processing to apps like Logic Pro X and GarageBand by creating Audio Unit (AU) plug-ins.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/avfoundation/creating_custom_audio_effects",
      "kind": "article",
      "role": "sampleCode",
      "title": "Creating Custom Audio Effects",
      "type": "topic",
      "url": "/documentation/avfoundation/creating_custom_audio_effects"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG": {
      "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG",
      "title": "App Extensions",
      "titleInlineContent": [
        {
          "text": "App Extensions",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "21130483bd32/IncorporatingAudioEffectsAndInstruments.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Audio-Units",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/AVFAudio/creating-an-audio-unit-extension",
        "doc://com.apple.documentation/documentation/avfoundation/creating_custom_audio_effects",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/debugging-out-of-process-audio-units-on-apple-silicon",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitBus",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitBusArray",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitPreset",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitV2Bridge",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitExtensionCopyComponentList(_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitExtensionSetComponentList(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitFactory"
      ],
      "title": "Audio Units"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Audio-Units",
              "generated": true,
              "identifiers": [
                "doc://com.apple.documentation/documentation/AVFAudio/creating-an-audio-unit-extension",
                "doc://com.apple.documentation/documentation/avfoundation/creating_custom_audio_effects",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/debugging-out-of-process-audio-units-on-apple-silicon",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitBus",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitBusArray",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitPreset",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitV2Bridge",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitExtensionCopyComponentList(_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitExtensionSetComponentList(_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitFactory"
              ],
              "title": "Audio Units"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreAudioKit~1AUViewController/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AUViewController"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIViewController",
              "text": "UIViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1currentPreset/title",
          "value": "currentPreset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1currentPreset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentPreset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitExtensionCopyComponentList(_:)/title",
          "value": "AudioUnitExtensionCopyComponentList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitExtensionCopyComponentList(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitExtensionCopyComponentList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitBus/title",
          "value": "AUAudioUnitBus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitBus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitBus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitBus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitBus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioEngine/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioEngine"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1deleteUserPreset(_:)/title",
          "value": "deleteUserPreset:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1deleteUserPreset(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deleteUserPreset:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioUnitComponentManager~1components(matching:)-96l2c/title",
          "value": "componentsMatchingPredicate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioUnitComponentManager~1components(matching:)-96l2c/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<AVAudioUnitComponent *>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "identifier",
              "text": "componentsMatchingPredicate:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSPredicate",
              "text": "NSPredicate"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "predicate"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitV2Bridge/title",
          "value": "AUAudioUnitV2Bridge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitV2Bridge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitV2Bridge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitV2Bridge/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitV2Bridge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitExtensionSetComponentList(_:_:)/title",
          "value": "AudioUnitExtensionSetComponentList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitExtensionSetComponentList(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitExtensionSetComponentList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioUnitComponent/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioUnitComponent"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1supportsUserPresets/title",
          "value": "supportsUserPresets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1supportsUserPresets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsUserPresets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit/title",
          "value": "AUAudioUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreAudioKit~1AUAudioUnitViewConfiguration~1hostHasController/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "atomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "hostHasController"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1factoryPresets/title",
          "value": "factoryPresets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1factoryPresets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "factoryPresets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioUnitComponentManager/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioUnitComponentManager"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1userPresets/title",
          "value": "userPresets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1userPresets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userPresets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1saveUserPreset(_:)/title",
          "value": "saveUserPreset:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1saveUserPreset(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "saveUserPreset:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_MusicDevice/title",
          "value": "kAudioUnitType_MusicDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_MusicDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitType_MusicDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitBusArray/title",
          "value": "AUAudioUnitBusArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitBusArray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitBusArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitBusArray/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitBusArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitFactory/title",
          "value": "AUAudioUnitFactory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitFactory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitFactory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitFactory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitFactory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitPreset/title",
          "value": "AUAudioUnitPreset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitPreset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitPreset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitPreset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitPreset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioUnit~1instantiate(with:options:completionHandler:)/title",
          "value": "instantiateWithComponentDescription:options:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioUnit~1instantiate(with:options:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "instantiateWithComponentDescription:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@AudioComponentDescription",
              "text": "AudioComponentDescription"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "audioComponentDescription"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "options:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AudioComponentInstantiationOptions",
              "text": "AudioComponentInstantiationOptions"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "completionHandler:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " (^)("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVAudioUnit",
              "text": "AVAudioUnit"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "audioUnit"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSError",
              "text": "NSError"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "error"
            },
            {
              "kind": "text",
              "text": ")) "
            },
            {
              "kind": "internalParam",
              "text": "completionHandler"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentDescription/title",
          "value": "AudioComponentDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioComponentDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioComponentDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_Effect/title",
          "value": "kAudioUnitType_Effect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_Effect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitType_Effect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreAudioKit~1AUAudioUnitViewConfiguration/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AUAudioUnitViewConfiguration"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/incorporating-audio-effects-and-instruments"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/incorporating-audio-effects-and-instruments"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
