{
  "abstract": [
    {
      "text": "Key values of properties to get and set using Audio File Services functions and provide a common way to get the same information out of several different kinds of files.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-services"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/info-string-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Info String Keys"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576492-audio-file-marker-types": {
      "abstract": [
        {
          "text": "A type of marker within a file used in the ",
          "type": "text"
        },
        {
          "code": "mType",
          "type": "codeVoice"
        },
        {
          "text": " field of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileMarker",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " structure.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576492-audio-file-marker-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio File Marker Types",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1576492-audio-file-marker-types"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576494-audio-file-loop-direction-consta": {
      "abstract": [
        {
          "text": "The playback direction of a looped segment of an audio file.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576494-audio-file-loop-direction-consta",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio File Loop Direction Constants",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1576494-audio-file-loop-direction-consta"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576495-audio-file-global-info-propertie": {
      "abstract": [
        {
          "text": "Access these properties using the functions described in Working with Global Information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576495-audio-file-global-info-propertie",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio File Global Info Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1576495-audio-file-global-info-propertie"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576499-audio-file-properties": {
      "abstract": [
        {
          "text": "Properties used by the functions described in getting and setting pieces of data in audio files. See Working with Global Information for details.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576499-audio-file-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio File Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1576499-audio-file-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileMarker": {
      "abstract": [
        {
          "text": "Annotates a position in an audio file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileMarker"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileMarker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileMarker"
        }
      ],
      "role": "symbol",
      "title": "AudioFileMarker",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilemarker"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFilePermissions": {
      "abstract": [
        {
          "text": "Flags for use when opening an audio file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFilePermissions"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFilePermissions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFilePermissions"
        }
      ],
      "role": "symbol",
      "title": "AudioFilePermissions",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilepermissions"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileRegionFlags": {
      "abstract": [
        {
          "text": "Flags that specify a playback direction for an audio file region structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileRegionFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileRegionFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileRegionFlags"
        }
      ],
      "role": "symbol",
      "title": "AudioFileRegionFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofileregionflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileTypeID": {
      "abstract": [
        {
          "text": "Operating system constants that indicate the type of file to be written or a hint about what type of file to expect from data provided.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileTypeID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileTypeID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileTypeID"
        }
      ],
      "role": "symbol",
      "title": "AudioFileTypeID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofiletypeid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-services": {
      "abstract": [
        {
          "text": "Read or write a variety of audio data to or from disk or a memory buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio File Services",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-file-services"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio_file_creation_flags": {
      "abstract": [
        {
          "text": "Flags to set when creating an audio file.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio_file_creation_flags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio File Creation Flags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio_file_creation_flags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio_file_packet_translation_flags": {
      "abstract": [
        {
          "text": "Flags specified in a packet translation structure.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio_file_packet_translation_flags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio File Packet Translation Flags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio_file_packet_translation_flags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Album": {
      "abstract": [
        {
          "text": "An album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Album"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Album",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Album"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_Album",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_album"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_ApproximateDurationInSeconds": {
      "abstract": [
        {
          "text": "An approximate duration in seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_ApproximateDurationInSeconds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_ApproximateDurationInSeconds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_ApproximateDurationInSeconds"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_ApproximateDurationInSeconds",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_approximatedurationinseconds"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Artist": {
      "abstract": [
        {
          "text": "An artist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Artist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Artist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Artist"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_Artist",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_artist"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_ChannelLayout": {
      "abstract": [
        {
          "text": "A channel layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_ChannelLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_ChannelLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_ChannelLayout"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_ChannelLayout",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_channellayout"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Comments": {
      "abstract": [
        {
          "text": "Comments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Comments"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Comments",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Comments"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_Comments",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_comments"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Composer": {
      "abstract": [
        {
          "text": "A composer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Composer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Composer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Composer"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_Composer",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_composer"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Copyright": {
      "abstract": [
        {
          "text": "Copyright.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Copyright"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Copyright",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Copyright"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_Copyright",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_copyright"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_EncodingApplication": {
      "abstract": [
        {
          "text": "An encoding application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_EncodingApplication"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_EncodingApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_EncodingApplication"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_EncodingApplication",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_encodingapplication"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Genre": {
      "abstract": [
        {
          "text": "A genre.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Genre"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Genre",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Genre"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_Genre",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_genre"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_ISRC": {
      "abstract": [
        {
          "text": "An International Standard Recording Code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_ISRC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_ISRC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_ISRC"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_ISRC",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_isrc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_KeySignature": {
      "abstract": [
        {
          "text": "A key signature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_KeySignature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_KeySignature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_KeySignature"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_KeySignature",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_keysignature"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Lyricist": {
      "abstract": [
        {
          "text": "A lyricist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Lyricist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Lyricist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Lyricist"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_Lyricist",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_lyricist"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_NominalBitRate": {
      "abstract": [
        {
          "text": "A nominal bit rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_NominalBitRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_NominalBitRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_NominalBitRate"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_NominalBitRate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_nominalbitrate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_RecordedDate": {
      "abstract": [
        {
          "text": "A recorded date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_RecordedDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_RecordedDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_RecordedDate"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_RecordedDate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_recordeddate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_SourceBitDepth": {
      "abstract": [
        {
          "text": "The bit depth of the source audio stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_SourceBitDepth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_SourceBitDepth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_SourceBitDepth"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_SourceBitDepth",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_sourcebitdepth"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_SourceEncoder": {
      "abstract": [
        {
          "text": "A source encoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_SourceEncoder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_SourceEncoder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_SourceEncoder"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_SourceEncoder",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_sourceencoder"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_SubTitle": {
      "abstract": [
        {
          "text": "A subtitle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_SubTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_SubTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_SubTitle"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_SubTitle",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_subtitle"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Tempo": {
      "abstract": [
        {
          "text": "A tempo.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Tempo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Tempo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Tempo"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_Tempo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_tempo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_TimeSignature": {
      "abstract": [
        {
          "text": "A time signature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_TimeSignature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_TimeSignature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_TimeSignature"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_TimeSignature",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_timesignature"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Title": {
      "abstract": [
        {
          "text": "A title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Title"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_Title",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_title"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_TrackNumber": {
      "abstract": [
        {
          "text": "A track number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_TrackNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_TrackNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_TrackNumber"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_TrackNumber",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_tracknumber"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Year": {
      "abstract": [
        {
          "text": "A year.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Year"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Year",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Year"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_Year",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_year"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileTypeID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio_file_creation_flags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFilePermissions",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576494-audio-file-loop-direction-consta",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576492-audio-file-marker-types",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileRegionFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio_file_packet_translation_flags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576499-audio-file-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576495-audio-file-global-info-propertie"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Artist",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Album",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Tempo",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_KeySignature",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_TimeSignature",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_TrackNumber",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Year",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Composer",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Lyricist",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Genre",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Title",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_RecordedDate",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Comments",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Copyright",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_SourceEncoder",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_EncodingApplication",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_NominalBitRate",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_ChannelLayout",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_ApproximateDurationInSeconds",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_SourceBitDepth",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_ISRC",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_SubTitle"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Artist",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Album",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Tempo",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_KeySignature",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_TimeSignature",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_TrackNumber",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Year",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Composer",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Lyricist",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Genre",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Title",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_RecordedDate",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Comments",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Copyright",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_SourceEncoder",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_EncodingApplication",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_NominalBitRate",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_ChannelLayout",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_ApproximateDurationInSeconds",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_SourceBitDepth",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_ISRC",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_SubTitle"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileTypeID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio_file_creation_flags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFilePermissions",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576494-audio-file-loop-direction-consta",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576492-audio-file-marker-types",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileRegionFlags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio_file_packet_translation_flags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576499-audio-file-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576495-audio-file-global-info-propertie"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_RecordedDate/title",
          "value": "kAFInfoDictionary_RecordedDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_RecordedDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_RecordedDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_TrackNumber/title",
          "value": "kAFInfoDictionary_TrackNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_TrackNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_TrackNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Album/title",
          "value": "kAFInfoDictionary_Album"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Album/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_Album"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_NominalBitRate/title",
          "value": "kAFInfoDictionary_NominalBitRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_NominalBitRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_NominalBitRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_SourceBitDepth/title",
          "value": "kAFInfoDictionary_SourceBitDepth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_SourceBitDepth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_SourceBitDepth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Composer/title",
          "value": "kAFInfoDictionary_Composer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Composer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_Composer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Genre/title",
          "value": "kAFInfoDictionary_Genre"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Genre/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_Genre"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_ApproximateDurationInSeconds/title",
          "value": "kAFInfoDictionary_ApproximateDurationInSeconds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_ApproximateDurationInSeconds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_ApproximateDurationInSeconds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_SubTitle/title",
          "value": "kAFInfoDictionary_SubTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_SubTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_SubTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Comments/title",
          "value": "kAFInfoDictionary_Comments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Comments/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_Comments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileTypeID/title",
          "value": "AudioFileTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileTypeID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileTypeID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_TimeSignature/title",
          "value": "kAFInfoDictionary_TimeSignature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_TimeSignature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_TimeSignature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Title/title",
          "value": "kAFInfoDictionary_Title"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_Title"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Artist/title",
          "value": "kAFInfoDictionary_Artist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Artist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_Artist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Copyright/title",
          "value": "kAFInfoDictionary_Copyright"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Copyright/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_Copyright"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_ISRC/title",
          "value": "kAFInfoDictionary_ISRC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_ISRC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_ISRC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Tempo/title",
          "value": "kAFInfoDictionary_Tempo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Tempo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_Tempo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Year/title",
          "value": "kAFInfoDictionary_Year"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Year/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_Year"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_ChannelLayout/title",
          "value": "kAFInfoDictionary_ChannelLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_ChannelLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_ChannelLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Lyricist/title",
          "value": "kAFInfoDictionary_Lyricist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Lyricist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_Lyricist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileRegionFlags/title",
          "value": "AudioFileRegionFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileRegionFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileRegionFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileRegionFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileRegionFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFilePermissions/title",
          "value": "AudioFilePermissions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFilePermissions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFilePermissions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFilePermissions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFilePermissions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_KeySignature/title",
          "value": "kAFInfoDictionary_KeySignature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_KeySignature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_KeySignature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_EncodingApplication/title",
          "value": "kAFInfoDictionary_EncodingApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_EncodingApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_EncodingApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_SourceEncoder/title",
          "value": "kAFInfoDictionary_SourceEncoder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_SourceEncoder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_SourceEncoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileMarker/title",
          "value": "AudioFileMarker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileMarker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileMarker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileMarker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileMarker"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/info-string-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/info-string-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
