{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_MaxGain"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@k3DMixerParam_Azimuth@k3DMixerParam_MaxGain",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "k3DMixerParam_MaxGain"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioUnitParameterID",
        "text": "AudioUnitParameterID"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "k3DMixerParam_MaxGain"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "2.0",
        "name": "iOS",
        "renamed": "k3DMixerParam_MaxGainInDecibels",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "2.0",
        "name": "iPadOS",
        "renamed": "k3DMixerParam_MaxGainInDecibels",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "10.0",
        "name": "macOS",
        "renamed": "k3DMixerParam_MaxGainInDecibels",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "renamed": "k3DMixerParam_MaxGainInDecibels",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "renamed": "k3DMixerParam_MaxGainInDecibels",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "k3DMixerParam_MaxGain"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "k3DMixerParam_MaxGain"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioUnitParameterID",
              "text": "AudioUnitParameterID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID": {
      "abstract": [
        {
          "text": "The data type for an audio unit parameter identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterID"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Azimuth": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_Azimuth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Azimuth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_Azimuth"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_Azimuth",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_azimuth"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Distance": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_Distance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Distance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_Distance"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_Distance",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_distance"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Elevation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_Elevation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Elevation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_Elevation"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_Elevation",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_elevation"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Enable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_Enable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Enable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_Enable"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_Enable",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_enable"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Gain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_Gain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Gain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_Gain"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_Gain",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_gain"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_GlobalReverbGain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_GlobalReverbGain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_GlobalReverbGain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_GlobalReverbGain"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_GlobalReverbGain",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_globalreverbgain"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_MaxGain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_MaxGain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_MaxGain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_MaxGain"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_MaxGain",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_maxgain"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_MinGain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_MinGain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_MinGain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_MinGain"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_MinGain",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_mingain"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_ObstructionAttenuation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_ObstructionAttenuation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_ObstructionAttenuation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_ObstructionAttenuation"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_ObstructionAttenuation",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_obstructionattenuation"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_OcclusionAttenuation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_OcclusionAttenuation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_OcclusionAttenuation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_OcclusionAttenuation"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_OcclusionAttenuation",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_occlusionattenuation"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PlaybackRate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_PlaybackRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PlaybackRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_PlaybackRate"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_PlaybackRate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_playbackrate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PostAveragePower": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_PostAveragePower"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PostAveragePower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_PostAveragePower"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_PostAveragePower",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_postaveragepower"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PostPeakHoldLevel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_PostPeakHoldLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PostPeakHoldLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_PostPeakHoldLevel"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_PostPeakHoldLevel",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_postpeakholdlevel"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PreAveragePower": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_PreAveragePower"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PreAveragePower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_PreAveragePower"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_PreAveragePower",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_preaveragepower"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PrePeakHoldLevel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_PrePeakHoldLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PrePeakHoldLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_PrePeakHoldLevel"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_PrePeakHoldLevel",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_prepeakholdlevel"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_ReverbBlend": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerParam_ReverbBlend"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_ReverbBlend",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerParam_ReverbBlend"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerParam_ReverbBlend",
      "type": "topic",
      "url": "/documentation/audiotoolbox/k3dmixerparam_reverbblend"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Azimuth",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Distance",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Elevation",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Enable",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Gain",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_GlobalReverbGain",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_MinGain",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_ObstructionAttenuation",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_OcclusionAttenuation",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PlaybackRate",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PostAveragePower",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PostPeakHoldLevel",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PreAveragePower",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PrePeakHoldLevel",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_ReverbBlend"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "k3DMixerParam_MaxGain"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_MaxGain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Azimuth",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Distance",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Elevation",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Enable",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_Gain",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_GlobalReverbGain",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_MinGain",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_ObstructionAttenuation",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_OcclusionAttenuation",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PlaybackRate",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PostAveragePower",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PostPeakHoldLevel",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PreAveragePower",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_PrePeakHoldLevel",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/k3DMixerParam_ReverbBlend"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "k3DMixerParam_MaxGain"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_PostPeakHoldLevel/title",
          "value": "k3DMixerParam_PostPeakHoldLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_PostPeakHoldLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_PostPeakHoldLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_PreAveragePower/title",
          "value": "k3DMixerParam_PreAveragePower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_PreAveragePower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_PreAveragePower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_OcclusionAttenuation/title",
          "value": "k3DMixerParam_OcclusionAttenuation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_OcclusionAttenuation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_OcclusionAttenuation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_Elevation/title",
          "value": "k3DMixerParam_Elevation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_Elevation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_Elevation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_MinGain/title",
          "value": "k3DMixerParam_MinGain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_MinGain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_MinGain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_GlobalReverbGain/title",
          "value": "k3DMixerParam_GlobalReverbGain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_GlobalReverbGain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_GlobalReverbGain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_PostAveragePower/title",
          "value": "k3DMixerParam_PostAveragePower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_PostAveragePower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_PostAveragePower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_ReverbBlend/title",
          "value": "k3DMixerParam_ReverbBlend"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_ReverbBlend/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_ReverbBlend"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_MaxGain/title",
          "value": "k3DMixerParam_MaxGain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_MaxGain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_MaxGain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_ObstructionAttenuation/title",
          "value": "k3DMixerParam_ObstructionAttenuation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_ObstructionAttenuation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_ObstructionAttenuation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_Gain/title",
          "value": "k3DMixerParam_Gain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_Gain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_Gain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_PrePeakHoldLevel/title",
          "value": "k3DMixerParam_PrePeakHoldLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_PrePeakHoldLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_PrePeakHoldLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_Distance/title",
          "value": "k3DMixerParam_Distance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_Distance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_Distance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_Enable/title",
          "value": "k3DMixerParam_Enable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_Enable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_Enable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/title",
          "value": "AudioUnitParameterID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_PlaybackRate/title",
          "value": "k3DMixerParam_PlaybackRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_PlaybackRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_PlaybackRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_Azimuth/title",
          "value": "k3DMixerParam_Azimuth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1k3DMixerParam_Azimuth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerParam_Azimuth"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/k3dmixerparam_maxgain"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/k3dmixerparam_maxgain"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
