{
  "abstract": [
    {
      "text": "A channel layout.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_ChannelLayout"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@kAFInfoDictionary_ChannelLayout",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAFInfoDictionary_ChannelLayout"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAFInfoDictionary_ChannelLayout"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAFInfoDictionary_ChannelLayout"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_ChannelLayout"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Album": {
      "abstract": [
        {
          "text": "An album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Album"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Album",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Album"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_Album",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_album"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Artist": {
      "abstract": [
        {
          "text": "An artist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Artist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Artist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Artist"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_Artist",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_artist"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_ChannelLayout": {
      "abstract": [
        {
          "text": "A channel layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_ChannelLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_ChannelLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_ChannelLayout"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_ChannelLayout",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_channellayout"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Comments": {
      "abstract": [
        {
          "text": "Comments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Comments"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Comments",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Comments"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_Comments",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_comments"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Composer": {
      "abstract": [
        {
          "text": "A composer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Composer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Composer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Composer"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_Composer",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_composer"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Copyright": {
      "abstract": [
        {
          "text": "Copyright.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Copyright"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Copyright",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Copyright"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_Copyright",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_copyright"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Genre": {
      "abstract": [
        {
          "text": "A genre.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Genre"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Genre",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Genre"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_Genre",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_genre"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_KeySignature": {
      "abstract": [
        {
          "text": "A key signature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_KeySignature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_KeySignature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_KeySignature"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_KeySignature",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_keysignature"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Lyricist": {
      "abstract": [
        {
          "text": "A lyricist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Lyricist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Lyricist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Lyricist"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_Lyricist",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_lyricist"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_RecordedDate": {
      "abstract": [
        {
          "text": "A recorded date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_RecordedDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_RecordedDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_RecordedDate"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_RecordedDate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_recordeddate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_SourceEncoder": {
      "abstract": [
        {
          "text": "A source encoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_SourceEncoder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_SourceEncoder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_SourceEncoder"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_SourceEncoder",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_sourceencoder"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Tempo": {
      "abstract": [
        {
          "text": "A tempo.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Tempo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Tempo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Tempo"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_Tempo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_tempo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_TimeSignature": {
      "abstract": [
        {
          "text": "A time signature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_TimeSignature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_TimeSignature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_TimeSignature"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_TimeSignature",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_timesignature"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Title": {
      "abstract": [
        {
          "text": "A title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Title"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_Title",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_title"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_TrackNumber": {
      "abstract": [
        {
          "text": "A track number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_TrackNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_TrackNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_TrackNumber"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_TrackNumber",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_tracknumber"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Year": {
      "abstract": [
        {
          "text": "A year.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Year"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Year",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAFInfoDictionary_Year"
        }
      ],
      "role": "symbol",
      "title": "kAFInfoDictionary_Year",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kafinfodictionary_year"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Artist",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Album",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Tempo",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_KeySignature",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_TimeSignature",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_TrackNumber",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Year",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Composer",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Lyricist",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Genre",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Title",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_RecordedDate",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Comments",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Copyright",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_SourceEncoder"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAFInfoDictionary_ChannelLayout"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_ChannelLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Artist",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Album",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Tempo",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_KeySignature",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_TimeSignature",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_TrackNumber",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Year",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Composer",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Lyricist",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Genre",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Title",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_RecordedDate",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Comments",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_Copyright",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAFInfoDictionary_SourceEncoder"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kAFInfoDictionary_ChannelLayout"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Year/title",
          "value": "kAFInfoDictionary_Year"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Year/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_Year"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Copyright/title",
          "value": "kAFInfoDictionary_Copyright"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Copyright/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_Copyright"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Composer/title",
          "value": "kAFInfoDictionary_Composer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Composer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_Composer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_TimeSignature/title",
          "value": "kAFInfoDictionary_TimeSignature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_TimeSignature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_TimeSignature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_SourceEncoder/title",
          "value": "kAFInfoDictionary_SourceEncoder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_SourceEncoder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_SourceEncoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Genre/title",
          "value": "kAFInfoDictionary_Genre"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Genre/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_Genre"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_ChannelLayout/title",
          "value": "kAFInfoDictionary_ChannelLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_ChannelLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_ChannelLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Tempo/title",
          "value": "kAFInfoDictionary_Tempo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Tempo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_Tempo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Album/title",
          "value": "kAFInfoDictionary_Album"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Album/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_Album"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_TrackNumber/title",
          "value": "kAFInfoDictionary_TrackNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_TrackNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_TrackNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Lyricist/title",
          "value": "kAFInfoDictionary_Lyricist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Lyricist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_Lyricist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_RecordedDate/title",
          "value": "kAFInfoDictionary_RecordedDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_RecordedDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_RecordedDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Artist/title",
          "value": "kAFInfoDictionary_Artist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Artist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_Artist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Comments/title",
          "value": "kAFInfoDictionary_Comments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Comments/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_Comments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Title/title",
          "value": "kAFInfoDictionary_Title"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_Title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_Title"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_KeySignature/title",
          "value": "kAFInfoDictionary_KeySignature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAFInfoDictionary_KeySignature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAFInfoDictionary_KeySignature"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kafinfodictionary_channellayout"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kafinfodictionary_channellayout"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
