{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerAttenuationCurve"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioUnitProperty_ReverbRoomType@kAudioUnitProperty_SpatialMixerAttenuationCurve",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioUnitProperty_SpatialMixerAttenuationCurve"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioUnitPropertyID",
        "text": "AudioUnitPropertyID"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioUnitProperty_SpatialMixerAttenuationCurve"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioUnitProperty_SpatialMixerAttenuationCurve"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_SpatialMixerAttenuationCurve"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitPropertyID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioUnitPropertyID",
              "text": "AudioUnitPropertyID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitPropertyID": {
      "abstract": [
        {
          "text": "The data type for audio unit property keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitPropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitPropertyID"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitPropertyID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitpropertyid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_ReverbRoomType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_ReverbRoomType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_ReverbRoomType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_ReverbRoomType"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_ReverbRoomType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_reverbroomtype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerAnyInputIsUsingPersonalizedHRTF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerAnyInputIsUsingPersonalizedHRTF"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerAnyInputIsUsingPersonalizedHRTF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerAnyInputIsUsingPersonalizedHRTF"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_SpatialMixerAnyInputIsUsingPersonalizedHRTF",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_spatialmixeranyinputisusingpersonalizedhrtf"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerAttenuationCurve": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerAttenuationCurve"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerAttenuationCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerAttenuationCurve"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_SpatialMixerAttenuationCurve",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_spatialmixerattenuationcurve"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerDistanceParams": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerDistanceParams"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerDistanceParams",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerDistanceParams"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_SpatialMixerDistanceParams",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_spatialmixerdistanceparams"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerEnableHeadTracking": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerEnableHeadTracking"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerEnableHeadTracking",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerEnableHeadTracking"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_SpatialMixerEnableHeadTracking",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_spatialmixerenableheadtracking"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerOutputType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerOutputType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerOutputType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerOutputType"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_SpatialMixerOutputType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_spatialmixeroutputtype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerPersonalizedHRTFMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerPersonalizedHRTFMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerPersonalizedHRTFMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerPersonalizedHRTFMode"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_SpatialMixerPersonalizedHRTFMode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_spatialmixerpersonalizedhrtfmode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerPointSourceInHeadMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerPointSourceInHeadMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerPointSourceInHeadMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerPointSourceInHeadMode"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_SpatialMixerPointSourceInHeadMode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_spatialmixerpointsourceinheadmode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerRenderingFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerRenderingFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerRenderingFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerRenderingFlags"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_SpatialMixerRenderingFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_spatialmixerrenderingflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerSourceMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerSourceMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerSourceMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatialMixerSourceMode"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_SpatialMixerSourceMode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_spatialmixersourcemode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatializationAlgorithm": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatializationAlgorithm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatializationAlgorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SpatializationAlgorithm"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_SpatializationAlgorithm",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_spatializationalgorithm"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_UsesInternalReverb": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_UsesInternalReverb"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_UsesInternalReverb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_UsesInternalReverb"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_UsesInternalReverb",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_usesinternalreverb"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_ReverbRoomType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerDistanceParams",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerRenderingFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatializationAlgorithm",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_UsesInternalReverb",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerOutputType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerPointSourceInHeadMode",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerSourceMode",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerAnyInputIsUsingPersonalizedHRTF",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerEnableHeadTracking",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerPersonalizedHRTFMode"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioUnitProperty_SpatialMixerAttenuationCurve"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_SpatialMixerAttenuationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_ReverbRoomType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerDistanceParams",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerRenderingFlags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatializationAlgorithm",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_UsesInternalReverb",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerOutputType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerPointSourceInHeadMode",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerSourceMode",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerAnyInputIsUsingPersonalizedHRTF",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerEnableHeadTracking",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SpatialMixerPersonalizedHRTFMode"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioUnitProperty_SpatialMixerAttenuationCurve"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerOutputType/title",
          "value": "kAudioUnitProperty_SpatialMixerOutputType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerOutputType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_SpatialMixerOutputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatializationAlgorithm/title",
          "value": "kAudioUnitProperty_SpatializationAlgorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatializationAlgorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_SpatializationAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitPropertyID/title",
          "value": "AudioUnitPropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitPropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitPropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerAnyInputIsUsingPersonalizedHRTF/title",
          "value": "kAudioUnitProperty_SpatialMixerAnyInputIsUsingPersonalizedHRTF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerAnyInputIsUsingPersonalizedHRTF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_SpatialMixerAnyInputIsUsingPersonalizedHRTF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_UsesInternalReverb/title",
          "value": "kAudioUnitProperty_UsesInternalReverb"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_UsesInternalReverb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_UsesInternalReverb"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerPointSourceInHeadMode/title",
          "value": "kAudioUnitProperty_SpatialMixerPointSourceInHeadMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerPointSourceInHeadMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_SpatialMixerPointSourceInHeadMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerEnableHeadTracking/title",
          "value": "kAudioUnitProperty_SpatialMixerEnableHeadTracking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerEnableHeadTracking/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_SpatialMixerEnableHeadTracking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerDistanceParams/title",
          "value": "kAudioUnitProperty_SpatialMixerDistanceParams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerDistanceParams/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_SpatialMixerDistanceParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_ReverbRoomType/title",
          "value": "kAudioUnitProperty_ReverbRoomType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_ReverbRoomType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_ReverbRoomType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerAttenuationCurve/title",
          "value": "kAudioUnitProperty_SpatialMixerAttenuationCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerAttenuationCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_SpatialMixerAttenuationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerRenderingFlags/title",
          "value": "kAudioUnitProperty_SpatialMixerRenderingFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerRenderingFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_SpatialMixerRenderingFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerPersonalizedHRTFMode/title",
          "value": "kAudioUnitProperty_SpatialMixerPersonalizedHRTFMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerPersonalizedHRTFMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_SpatialMixerPersonalizedHRTFMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerSourceMode/title",
          "value": "kAudioUnitProperty_SpatialMixerSourceMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SpatialMixerSourceMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_SpatialMixerSourceMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiounitproperty_spatialmixerattenuationcurve"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiounitproperty_spatialmixerattenuationcurve"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
