{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_UTIsForType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioFileComponent_CanRead@kAudioFileComponent_UTIsForType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioFileComponent_UTIsForType"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioFilePropertyID",
        "text": "AudioFilePropertyID"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioFileComponent_UTIsForType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioFileComponent_UTIsForType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioFileComponent_UTIsForType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFilePropertyID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioFilePropertyID",
              "text": "AudioFilePropertyID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFilePropertyID": {
      "abstract": [
        {
          "text": "An audio file property identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFilePropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFilePropertyID"
        }
      ],
      "role": "symbol",
      "title": "AudioFilePropertyID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilepropertyid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_AvailableFormatIDs": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_AvailableFormatIDs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_AvailableFormatIDs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_AvailableFormatIDs"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileComponent_AvailableFormatIDs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilecomponent_availableformatids"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_AvailableStreamDescriptionsForFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_AvailableStreamDescriptionsForFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_AvailableStreamDescriptionsForFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_AvailableStreamDescriptionsForFormat"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileComponent_AvailableStreamDescriptionsForFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilecomponent_availablestreamdescriptionsforformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_CanRead": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_CanRead"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_CanRead",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_CanRead"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileComponent_CanRead",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilecomponent_canread"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_CanWrite": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_CanWrite"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_CanWrite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_CanWrite"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileComponent_CanWrite",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilecomponent_canwrite"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_ExtensionsForType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_ExtensionsForType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_ExtensionsForType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_ExtensionsForType"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileComponent_ExtensionsForType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilecomponent_extensionsfortype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_FastDispatchTable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_FastDispatchTable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_FastDispatchTable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_FastDispatchTable"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileComponent_FastDispatchTable",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilecomponent_fastdispatchtable"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_FileTypeName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_FileTypeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_FileTypeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_FileTypeName"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileComponent_FileTypeName",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilecomponent_filetypename"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_HFSTypeCodesForType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_HFSTypeCodesForType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_HFSTypeCodesForType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_HFSTypeCodesForType"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileComponent_HFSTypeCodesForType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilecomponent_hfstypecodesfortype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_MIMETypesForType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_MIMETypesForType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_MIMETypesForType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_MIMETypesForType"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileComponent_MIMETypesForType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilecomponent_mimetypesfortype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_UTIsForType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_UTIsForType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_UTIsForType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileComponent_UTIsForType"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileComponent_UTIsForType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilecomponent_utisfortype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_AvailableFormatIDs",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_AvailableStreamDescriptionsForFormat",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_CanRead",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_CanWrite",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_ExtensionsForType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_FastDispatchTable",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_FileTypeName",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_HFSTypeCodesForType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_MIMETypesForType"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioFileComponent_UTIsForType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileComponent_UTIsForType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_AvailableFormatIDs",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_AvailableStreamDescriptionsForFormat",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_CanRead",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_CanWrite",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_ExtensionsForType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_FastDispatchTable",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_FileTypeName",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_HFSTypeCodesForType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileComponent_MIMETypesForType"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioFileComponent_UTIsForType"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_AvailableFormatIDs/title",
          "value": "kAudioFileComponent_AvailableFormatIDs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_AvailableFormatIDs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileComponent_AvailableFormatIDs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_MIMETypesForType/title",
          "value": "kAudioFileComponent_MIMETypesForType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_MIMETypesForType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileComponent_MIMETypesForType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFilePropertyID/title",
          "value": "AudioFilePropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFilePropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFilePropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFilePropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFilePropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_CanRead/title",
          "value": "kAudioFileComponent_CanRead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_CanRead/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileComponent_CanRead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_FastDispatchTable/title",
          "value": "kAudioFileComponent_FastDispatchTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_FastDispatchTable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileComponent_FastDispatchTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_AvailableStreamDescriptionsForFormat/title",
          "value": "kAudioFileComponent_AvailableStreamDescriptionsForFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_AvailableStreamDescriptionsForFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileComponent_AvailableStreamDescriptionsForFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_CanWrite/title",
          "value": "kAudioFileComponent_CanWrite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_CanWrite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileComponent_CanWrite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_UTIsForType/title",
          "value": "kAudioFileComponent_UTIsForType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_UTIsForType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileComponent_UTIsForType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_ExtensionsForType/title",
          "value": "kAudioFileComponent_ExtensionsForType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_ExtensionsForType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileComponent_ExtensionsForType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_FileTypeName/title",
          "value": "kAudioFileComponent_FileTypeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_FileTypeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileComponent_FileTypeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_HFSTypeCodesForType/title",
          "value": "kAudioFileComponent_HFSTypeCodesForType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileComponent_HFSTypeCodesForType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileComponent_HFSTypeCodesForType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiofilecomponent_utisfortype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiofilecomponent_utisfortype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
