{
  "abstract": [
    {
      "text": "Value is a read-only ",
      "type": "text"
    },
    {
      "code": "UInt32",
      "type": "codeVoice"
    },
    {
      "text": " value representing the number of channels in the audio hardware device associated with an audio queue.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueDeviceProperty_NumberChannels"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioQueueProperty_IsRunning@kAudioQueueDeviceProperty_NumberChannels",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioQueueDeviceProperty_NumberChannels"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioQueuePropertyID",
        "text": "AudioQueuePropertyID"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioQueueDeviceProperty_NumberChannels"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioQueueDeviceProperty_NumberChannels"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioQueueDeviceProperty_NumberChannels"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueuePropertyID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioQueuePropertyID",
              "text": "AudioQueuePropertyID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueLevelMeterState": {
      "abstract": [
        {
          "text": "Specifies the current level metering information for one channel of an audio queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueLevelMeterState"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueLevelMeterState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueLevelMeterState"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueLevelMeterState",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuelevelmeterstate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueuePropertyID": {
      "abstract": [
        {
          "text": "Identifiers for audio queue properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueuePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueuePropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueuePropertyID"
        }
      ],
      "role": "symbol",
      "title": "AudioQueuePropertyID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuepropertyid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueStart(_:_:)": {
      "abstract": [
        {
          "text": "Begins playing or recording audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueStart"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueueRef",
          "text": "AudioQueueRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioTimeStamp",
          "text": "AudioTimeStamp"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueStart(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueStart"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueStart(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuestart(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueStop(_:_:)": {
      "abstract": [
        {
          "text": "Stops playing or recording audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueueStop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueueRef",
          "text": "AudioQueueRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueStop(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueueStop"
        }
      ],
      "role": "symbol",
      "title": "AudioQueueStop(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuestop(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueDeviceProperty_NumberChannels": {
      "abstract": [
        {
          "text": "Value is a read-only ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value representing the number of channels in the audio hardware device associated with an audio queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueDeviceProperty_NumberChannels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueuePropertyID",
          "text": "AudioQueuePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueDeviceProperty_NumberChannels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueDeviceProperty_NumberChannels"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueDeviceProperty_NumberChannels",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueuedeviceproperty_numberchannels"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueDeviceProperty_SampleRate": {
      "abstract": [
        {
          "text": "Value is a read-only ",
          "type": "text"
        },
        {
          "code": "Float64",
          "type": "codeVoice"
        },
        {
          "text": " value representing the sampling rate of the audio hardware device associated with an audio queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueDeviceProperty_SampleRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueuePropertyID",
          "text": "AudioQueuePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueDeviceProperty_SampleRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueDeviceProperty_SampleRate"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueDeviceProperty_SampleRate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueuedeviceproperty_samplerate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_ChannelLayout": {
      "abstract": [
        {
          "text": "Describes an audio queue channel layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueProperty_ChannelLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueuePropertyID",
          "text": "AudioQueuePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_ChannelLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueProperty_ChannelLayout"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueProperty_ChannelLayout",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueproperty_channellayout"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_ConverterError": {
      "abstract": [
        {
          "text": "Value is a  read-only ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value that indicates the most recent error (if any) encountered by the audio queue’s internal encoding/decoding process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueProperty_ConverterError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueuePropertyID",
          "text": "AudioQueuePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_ConverterError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueProperty_ConverterError"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueProperty_ConverterError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueproperty_convertererror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_CurrentDevice": {
      "abstract": [
        {
          "text": "The unique identifier (UID) of the audio hardware device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueProperty_CurrentDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueuePropertyID",
          "text": "AudioQueuePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_CurrentDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueProperty_CurrentDevice"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueProperty_CurrentDevice",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueproperty_currentdevice"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_CurrentLevelMeter": {
      "abstract": [
        {
          "text": "A read-only array of level meter status structures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueProperty_CurrentLevelMeter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueuePropertyID",
          "text": "AudioQueuePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_CurrentLevelMeter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueProperty_CurrentLevelMeter"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueProperty_CurrentLevelMeter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueproperty_currentlevelmeter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_CurrentLevelMeterDB": {
      "abstract": [
        {
          "text": "Value is a read-only array of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueLevelMeterState",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " structures, one array element per audio channel. The member values in the structure are in decibels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueProperty_CurrentLevelMeterDB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueuePropertyID",
          "text": "AudioQueuePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_CurrentLevelMeterDB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueProperty_CurrentLevelMeterDB"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueProperty_CurrentLevelMeterDB",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueproperty_currentlevelmeterdb"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_DecodeBufferSizeFrames": {
      "abstract": [
        {
          "text": "Value is a read/write ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value that is the size of the buffer into which a playback (output) audio queue decodes buffers. A larger buffer provides more reliability and  better long-term performance at the expense of memory and decreased responsiveness in some situations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueProperty_DecodeBufferSizeFrames"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueuePropertyID",
          "text": "AudioQueuePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_DecodeBufferSizeFrames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueProperty_DecodeBufferSizeFrames"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueProperty_DecodeBufferSizeFrames",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueproperty_decodebuffersizeframes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_EnableLevelMetering": {
      "abstract": [
        {
          "text": "Value is a read/write ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value that indicates whether audio level metering is enabled for an audio queue. ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " = metering off, ",
          "type": "text"
        },
        {
          "code": "1",
          "type": "codeVoice"
        },
        {
          "text": " = metering on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueProperty_EnableLevelMetering"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueuePropertyID",
          "text": "AudioQueuePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_EnableLevelMetering",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueProperty_EnableLevelMetering"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueProperty_EnableLevelMetering",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueproperty_enablelevelmetering"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_EnableTimePitch": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueProperty_EnableTimePitch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueuePropertyID",
          "text": "AudioQueuePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_EnableTimePitch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueProperty_EnableTimePitch"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueProperty_EnableTimePitch",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueproperty_enabletimepitch"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_IsRunning": {
      "abstract": [
        {
          "text": "Value is a read-only ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value indicating whether or not the audio queue is running. A nonzero value means running; ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " means stopped. A notification is sent when the associated audio queue starts or stops, which may occur sometime after the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueStart(_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueueStop(_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function is called.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueProperty_IsRunning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueuePropertyID",
          "text": "AudioQueuePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_IsRunning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueProperty_IsRunning"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueProperty_IsRunning",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueproperty_isrunning"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_MagicCookie": {
      "abstract": [
        {
          "text": "Value is a read/write void pointer to a block of memory, which you set up, containing an audio format magic cookie. If the audio format you are playing or recording to requires a magic cookie, you must set a value for this property before enqueuing any buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueProperty_MagicCookie"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueuePropertyID",
          "text": "AudioQueuePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_MagicCookie",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueProperty_MagicCookie"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueProperty_MagicCookie",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueproperty_magiccookie"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_MaximumOutputPacketSize": {
      "abstract": [
        {
          "text": "Value is a read-only",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value that is the size, in bytes, of the largest single packet of data in the output format. Primarily useful when encoding VBR compressed data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueProperty_MaximumOutputPacketSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueuePropertyID",
          "text": "AudioQueuePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_MaximumOutputPacketSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueProperty_MaximumOutputPacketSize"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueProperty_MaximumOutputPacketSize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueproperty_maximumoutputpacketsize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_StreamDescription": {
      "abstract": [
        {
          "text": "An audio queue’s data format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueProperty_StreamDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueuePropertyID",
          "text": "AudioQueuePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_StreamDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueProperty_StreamDescription"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueProperty_StreamDescription",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueproperty_streamdescription"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_TimePitchAlgorithm": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueProperty_TimePitchAlgorithm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueuePropertyID",
          "text": "AudioQueuePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_TimePitchAlgorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueProperty_TimePitchAlgorithm"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueProperty_TimePitchAlgorithm",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueproperty_timepitchalgorithm"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_TimePitchBypass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueProperty_TimePitchBypass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueuePropertyID",
          "text": "AudioQueuePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_TimePitchBypass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueProperty_TimePitchBypass"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueProperty_TimePitchBypass",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueproperty_timepitchbypass"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueDeviceProperty_SampleRate",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_ChannelLayout",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_ConverterError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_CurrentDevice",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_CurrentLevelMeter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_CurrentLevelMeterDB",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_DecodeBufferSizeFrames",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_EnableLevelMetering",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_EnableTimePitch",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_IsRunning",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_MagicCookie",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_MaximumOutputPacketSize",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_StreamDescription",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_TimePitchAlgorithm",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_TimePitchBypass"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioQueueDeviceProperty_NumberChannels"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueDeviceProperty_NumberChannels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueDeviceProperty_SampleRate",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_ChannelLayout",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_ConverterError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_CurrentDevice",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_CurrentLevelMeter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_CurrentLevelMeterDB",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_DecodeBufferSizeFrames",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_EnableLevelMetering",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_EnableTimePitch",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_IsRunning",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_MagicCookie",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_MaximumOutputPacketSize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_StreamDescription",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_TimePitchAlgorithm",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_TimePitchBypass"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioQueueDeviceProperty_NumberChannels"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueStop(_:_:)/title",
          "value": "AudioQueueStop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueStop(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueStop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueProperty_MagicCookie/title",
          "value": "kAudioQueueProperty_MagicCookie"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueProperty_MagicCookie/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueProperty_MagicCookie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueProperty_TimePitchBypass/title",
          "value": "kAudioQueueProperty_TimePitchBypass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueProperty_TimePitchBypass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueProperty_TimePitchBypass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueuePropertyID/title",
          "value": "AudioQueuePropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueuePropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueuePropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueuePropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueuePropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueProperty_ChannelLayout/title",
          "value": "kAudioQueueProperty_ChannelLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueProperty_ChannelLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueProperty_ChannelLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueProperty_ConverterError/title",
          "value": "kAudioQueueProperty_ConverterError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueProperty_ConverterError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueProperty_ConverterError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueDeviceProperty_NumberChannels/title",
          "value": "kAudioQueueDeviceProperty_NumberChannels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueDeviceProperty_NumberChannels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueDeviceProperty_NumberChannels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueDeviceProperty_SampleRate/title",
          "value": "kAudioQueueDeviceProperty_SampleRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueDeviceProperty_SampleRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueDeviceProperty_SampleRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueProperty_MaximumOutputPacketSize/title",
          "value": "kAudioQueueProperty_MaximumOutputPacketSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueProperty_MaximumOutputPacketSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueProperty_MaximumOutputPacketSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueProperty_StreamDescription/title",
          "value": "kAudioQueueProperty_StreamDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueProperty_StreamDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueProperty_StreamDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueProperty_CurrentLevelMeterDB/title",
          "value": "kAudioQueueProperty_CurrentLevelMeterDB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueProperty_CurrentLevelMeterDB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueProperty_CurrentLevelMeterDB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueLevelMeterState/title",
          "value": "AudioQueueLevelMeterState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueLevelMeterState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueLevelMeterState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueLevelMeterState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueLevelMeterState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueStart(_:_:)/title",
          "value": "AudioQueueStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueueStart(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueueStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueProperty_EnableTimePitch/title",
          "value": "kAudioQueueProperty_EnableTimePitch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueProperty_EnableTimePitch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueProperty_EnableTimePitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueProperty_CurrentDevice/title",
          "value": "kAudioQueueProperty_CurrentDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueProperty_CurrentDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueProperty_CurrentDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueProperty_IsRunning/title",
          "value": "kAudioQueueProperty_IsRunning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueProperty_IsRunning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueProperty_IsRunning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueProperty_DecodeBufferSizeFrames/title",
          "value": "kAudioQueueProperty_DecodeBufferSizeFrames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueProperty_DecodeBufferSizeFrames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueProperty_DecodeBufferSizeFrames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueProperty_CurrentLevelMeter/title",
          "value": "kAudioQueueProperty_CurrentLevelMeter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueProperty_CurrentLevelMeter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueProperty_CurrentLevelMeter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueProperty_TimePitchAlgorithm/title",
          "value": "kAudioQueueProperty_TimePitchAlgorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueProperty_TimePitchAlgorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueProperty_TimePitchAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueProperty_EnableLevelMetering/title",
          "value": "kAudioQueueProperty_EnableLevelMetering"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueProperty_EnableLevelMetering/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueProperty_EnableLevelMetering"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaudioqueuedeviceproperty_numberchannels"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaudioqueuedeviceproperty_numberchannels"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
