{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetGlobalInfoSelect"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioFileCreateSelect@kAudioFileGetGlobalInfoSelect",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioFileGetGlobalInfoSelect"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioFileGetGlobalInfoSelect"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioFileGetGlobalInfoSelect"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioFileGetGlobalInfoSelect"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCloseSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileCloseSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCloseSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileCloseSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileCloseSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilecloseselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCountUserDataSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileCountUserDataSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCountUserDataSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileCountUserDataSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileCountUserDataSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilecountuserdataselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCreateSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileCreateSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCreateSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileCreateSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileCreateSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilecreateselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCreateURLSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileCreateURLSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCreateURLSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileCreateURLSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileCreateURLSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilecreateurlselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileDataIsThisFormatSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileDataIsThisFormatSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileDataIsThisFormatSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileDataIsThisFormatSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileDataIsThisFormatSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofiledataisthisformatselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileExtensionIsThisFormatSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileExtensionIsThisFormatSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileExtensionIsThisFormatSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileExtensionIsThisFormatSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileExtensionIsThisFormatSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileextensionisthisformatselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileFileDataIsThisFormatSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileFileDataIsThisFormatSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileFileDataIsThisFormatSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileFileDataIsThisFormatSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileFileDataIsThisFormatSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilefiledataisthisformatselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileFileIsThisFormatSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileFileIsThisFormatSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileFileIsThisFormatSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileFileIsThisFormatSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileFileIsThisFormatSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilefileisthisformatselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetGlobalInfoSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGetGlobalInfoSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetGlobalInfoSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGetGlobalInfoSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGetGlobalInfoSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilegetglobalinfoselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetGlobalInfoSizeSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGetGlobalInfoSizeSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetGlobalInfoSizeSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGetGlobalInfoSizeSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGetGlobalInfoSizeSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilegetglobalinfosizeselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetPropertyInfoSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGetPropertyInfoSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetPropertyInfoSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGetPropertyInfoSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGetPropertyInfoSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilegetpropertyinfoselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetPropertySelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGetPropertySelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetPropertySelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGetPropertySelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGetPropertySelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilegetpropertyselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataAtOffsetSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGetUserDataAtOffsetSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataAtOffsetSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGetUserDataAtOffsetSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGetUserDataAtOffsetSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilegetuserdataatoffsetselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGetUserDataSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGetUserDataSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGetUserDataSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilegetuserdataselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataSize64Select": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGetUserDataSize64Select"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataSize64Select",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGetUserDataSize64Select"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGetUserDataSize64Select",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilegetuserdatasize64select"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataSizeSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGetUserDataSizeSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataSizeSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGetUserDataSizeSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGetUserDataSizeSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilegetuserdatasizeselect"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Selectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCloseSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCountUserDataSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCreateSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCreateURLSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileDataIsThisFormatSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileExtensionIsThisFormatSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileFileDataIsThisFormatSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileFileIsThisFormatSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetGlobalInfoSizeSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetPropertyInfoSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataAtOffsetSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataSize64Select",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetPropertySelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataSizeSelect"
      ],
      "title": "Selectors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioFileGetGlobalInfoSelect"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGetGlobalInfoSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Selectors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCloseSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCountUserDataSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCreateSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCreateURLSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileDataIsThisFormatSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileExtensionIsThisFormatSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileFileDataIsThisFormatSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileFileIsThisFormatSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetGlobalInfoSizeSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetPropertyInfoSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataAtOffsetSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataSize64Select",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetPropertySelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGetUserDataSizeSelect"
              ],
              "title": "Selectors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioFileGetGlobalInfoSelect"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileCreateURLSelect/title",
          "value": "kAudioFileCreateURLSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileCreateURLSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileCreateURLSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetUserDataSizeSelect/title",
          "value": "kAudioFileGetUserDataSizeSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetUserDataSizeSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGetUserDataSizeSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileExtensionIsThisFormatSelect/title",
          "value": "kAudioFileExtensionIsThisFormatSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileExtensionIsThisFormatSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileExtensionIsThisFormatSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileCountUserDataSelect/title",
          "value": "kAudioFileCountUserDataSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileCountUserDataSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileCountUserDataSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetUserDataSize64Select/title",
          "value": "kAudioFileGetUserDataSize64Select"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetUserDataSize64Select/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGetUserDataSize64Select"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetPropertySelect/title",
          "value": "kAudioFileGetPropertySelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetPropertySelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGetPropertySelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileFileIsThisFormatSelect/title",
          "value": "kAudioFileFileIsThisFormatSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileFileIsThisFormatSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileFileIsThisFormatSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileCloseSelect/title",
          "value": "kAudioFileCloseSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileCloseSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileCloseSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileFileDataIsThisFormatSelect/title",
          "value": "kAudioFileFileDataIsThisFormatSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileFileDataIsThisFormatSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileFileDataIsThisFormatSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileCreateSelect/title",
          "value": "kAudioFileCreateSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileCreateSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileCreateSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetGlobalInfoSelect/title",
          "value": "kAudioFileGetGlobalInfoSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetGlobalInfoSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGetGlobalInfoSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetPropertyInfoSelect/title",
          "value": "kAudioFileGetPropertyInfoSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetPropertyInfoSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGetPropertyInfoSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetGlobalInfoSizeSelect/title",
          "value": "kAudioFileGetGlobalInfoSizeSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetGlobalInfoSizeSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGetGlobalInfoSizeSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetUserDataAtOffsetSelect/title",
          "value": "kAudioFileGetUserDataAtOffsetSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetUserDataAtOffsetSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGetUserDataAtOffsetSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetUserDataSelect/title",
          "value": "kAudioFileGetUserDataSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGetUserDataSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGetUserDataSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileDataIsThisFormatSelect/title",
          "value": "kAudioFileDataIsThisFormatSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileDataIsThisFormatSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileDataIsThisFormatSelect"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiofilegetglobalinfoselect"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiofilegetglobalinfoselect"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
