{
  "abstract": [
    {
      "text": "An effect unit that can respond to MIDI control messages, typically through a mapping of  MIDI messages to parameters of the audio unit’s DSP algorithm.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_MusicEffect"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioUnitType_Output@kAudioUnitType_MusicEffect",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioUnitType_MusicEffect"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioUnitType_MusicEffect"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioUnitType_MusicEffect"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioUnitType_MusicEffect"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Effect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitType_Effect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Effect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitType_Effect"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitType_Effect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounittype_effect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_FormatConverter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitType_FormatConverter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_FormatConverter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitType_FormatConverter"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitType_FormatConverter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounittype_formatconverter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Generator": {
      "abstract": [
        {
          "text": "A generator unit provides audio output but has no audio input. This audio unit type is appropriate for a tone generator. Unlike an instrument unit, a generator unit does not have a control input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitType_Generator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Generator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitType_Generator"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitType_Generator",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounittype_generator"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_MIDIProcessor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitType_MIDIProcessor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_MIDIProcessor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitType_MIDIProcessor"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitType_MIDIProcessor",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounittype_midiprocessor"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Mixer": {
      "abstract": [
        {
          "text": "A mixer unit takes a number of input channels and mixes them to provide one or more output channels. For example, the ",
          "type": "text"
        },
        {
          "code": "kAudioUnitSubType_StereoMixer",
          "type": "codeVoice"
        },
        {
          "text": " audio unit in macOS takes multiple mono or stereo inputs and produce a single stereo output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitType_Mixer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Mixer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitType_Mixer"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitType_Mixer",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounittype_mixer"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_MusicDevice": {
      "abstract": [
        {
          "text": "An instrument unit can be used as a software musical instrument, such as a sampler or synthesizer. It responds to MIDI (Musical Instrument Digital Interface) control signals and can create notes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitType_MusicDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_MusicDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitType_MusicDevice"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitType_MusicDevice",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounittype_musicdevice"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_MusicEffect": {
      "abstract": [
        {
          "text": "An effect unit that can respond to MIDI control messages, typically through a mapping of  MIDI messages to parameters of the audio unit’s DSP algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitType_MusicEffect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_MusicEffect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitType_MusicEffect"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitType_MusicEffect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounittype_musiceffect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_OfflineEffect": {
      "abstract": [
        {
          "text": "An offline effect unit provides digital signal processing of a sort that cannot proceed in realtime. For example, level normalization requires examination of an entire sound, beginning to end, before the normalization factor can be calculated. As such, offline effect units also have a notion of a priming stage that can be performed before the actual rendering/processing phase is executed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitType_OfflineEffect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_OfflineEffect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitType_OfflineEffect"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitType_OfflineEffect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounittype_offlineeffect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Output": {
      "abstract": [
        {
          "text": "An output unit provides input, output, or both input and output simultaneously. It can be used as the head of an audio unit processing graph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitType_Output"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Output",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitType_Output"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitType_Output",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounittype_output"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Panner": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitType_Panner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Panner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitType_Panner"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitType_Panner",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounittype_panner"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_SpeechSynthesizer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitType_SpeechSynthesizer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_SpeechSynthesizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitType_SpeechSynthesizer"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitType_SpeechSynthesizer",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounittype_speechsynthesizer"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Output",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_MusicDevice",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_FormatConverter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Effect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Mixer",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Panner",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_OfflineEffect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Generator",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_MIDIProcessor",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_SpeechSynthesizer"
      ],
      "title": "Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioUnitType_MusicEffect"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitType_MusicEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Output",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_MusicDevice",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_FormatConverter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Effect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Mixer",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Panner",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_OfflineEffect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_Generator",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_MIDIProcessor",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitType_SpeechSynthesizer"
              ],
              "title": "Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioUnitType_MusicEffect"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_Generator/title",
          "value": "kAudioUnitType_Generator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_Generator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitType_Generator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_MusicEffect/title",
          "value": "kAudioUnitType_MusicEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_MusicEffect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitType_MusicEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_MIDIProcessor/title",
          "value": "kAudioUnitType_MIDIProcessor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_MIDIProcessor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitType_MIDIProcessor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_Mixer/title",
          "value": "kAudioUnitType_Mixer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_Mixer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitType_Mixer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_SpeechSynthesizer/title",
          "value": "kAudioUnitType_SpeechSynthesizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_SpeechSynthesizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitType_SpeechSynthesizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_FormatConverter/title",
          "value": "kAudioUnitType_FormatConverter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_FormatConverter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitType_FormatConverter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_MusicDevice/title",
          "value": "kAudioUnitType_MusicDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_MusicDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitType_MusicDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_Panner/title",
          "value": "kAudioUnitType_Panner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_Panner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitType_Panner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_Output/title",
          "value": "kAudioUnitType_Output"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_Output/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitType_Output"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_Effect/title",
          "value": "kAudioUnitType_Effect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_Effect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitType_Effect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_OfflineEffect/title",
          "value": "kAudioUnitType_OfflineEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitType_OfflineEffect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitType_OfflineEffect"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiounittype_musiceffect"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiounittype_musiceffect"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
