{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_MIDIOutputEventListCallback"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioUnitProperty_ClassInfo@kAudioUnitProperty_MIDIOutputEventListCallback",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioUnitProperty_MIDIOutputEventListCallback"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioUnitPropertyID",
        "text": "AudioUnitPropertyID"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioUnitProperty_MIDIOutputEventListCallback"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioUnitProperty_MIDIOutputEventListCallback"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_MIDIOutputEventListCallback"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitPropertyID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioUnitPropertyID",
              "text": "AudioUnitPropertyID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitPropertyID": {
      "abstract": [
        {
          "text": "The data type for audio unit property keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitPropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitPropertyID"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitPropertyID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitpropertyid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_AUHostIdentifier": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_AUHostIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_AUHostIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_AUHostIdentifier"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_AUHostIdentifier",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_auhostidentifier"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_AudioChannelLayout": {
      "abstract": [
        {
          "text": "A read/write ",
          "type": "text"
        },
        {
          "code": "AudioChannelLayout",
          "type": "codeVoice"
        },
        {
          "text": " data structure valid on the audio unit input and output scopes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_AudioChannelLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_AudioChannelLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_AudioChannelLayout"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_AudioChannelLayout",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_audiochannellayout"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_AudioUnitMIDIProtocol": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_AudioUnitMIDIProtocol"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_AudioUnitMIDIProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_AudioUnitMIDIProtocol"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_AudioUnitMIDIProtocol",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_audiounitmidiprotocol"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_BypassEffect": {
      "abstract": [
        {
          "text": "A read/write ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value, representing a Boolean value, valid on the audio unit global scope.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_BypassEffect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_BypassEffect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_BypassEffect"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_BypassEffect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_bypasseffect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_CPULoad": {
      "abstract": [
        {
          "text": "A read-only ",
          "type": "text"
        },
        {
          "code": "Float64",
          "type": "codeVoice"
        },
        {
          "text": " value valid on the audio unit global scope.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_CPULoad"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_CPULoad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_CPULoad"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_CPULoad",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_cpuload"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_ClassInfo": {
      "abstract": [
        {
          "text": "Describes the state of an audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_ClassInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_ClassInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_ClassInfo"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_ClassInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_classinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_ClassInfoFromDocument": {
      "abstract": [
        {
          "text": "A read/write CFDictionary object, valid on the audio unit global scope.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_ClassInfoFromDocument"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_ClassInfoFromDocument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_ClassInfoFromDocument"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_ClassInfoFromDocument",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_classinfofromdocument"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_CocoaUI": {
      "abstract": [
        {
          "text": "A read-only ",
          "type": "text"
        },
        {
          "code": "AudioUnitCocoaViewInfo",
          "type": "codeVoice"
        },
        {
          "text": " data structure valid on the audio unit global scope.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_CocoaUI"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_CocoaUI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_CocoaUI"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_CocoaUI",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_cocoaui"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_ContextName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_ContextName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_ContextName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_ContextName"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_ContextName",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_contextname"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_DependentParameters": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_DependentParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_DependentParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_DependentParameters"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_DependentParameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_dependentparameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_ElementCount": {
      "abstract": [
        {
          "text": "A read/write ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value valid on any audio unit scope. The global audio unit scope always has an element count of 1.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_ElementCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_ElementCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_ElementCount"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_ElementCount",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_elementcount"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_ElementName": {
      "abstract": [
        {
          "text": "The name of the specified element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_ElementName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_ElementName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_ElementName"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_ElementName",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_elementname"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_FactoryPresets": {
      "abstract": [
        {
          "text": "So-called ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "factory presets",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " (as opposed to user-configured presets) are ones supplied with an audio unit by the manufacturer. You choose the active preset by setting the ",
          "type": "text"
        },
        {
          "code": "kAudioUnitProperty_PresentPreset",
          "type": "codeVoice"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_FactoryPresets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_FactoryPresets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_FactoryPresets"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_FactoryPresets",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_factorypresets"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_FastDispatch": {
      "abstract": [
        {
          "text": "A read-only ",
          "type": "text"
        },
        {
          "code": "void *",
          "type": "codeVoice"
        },
        {
          "text": " value valid on the audio unit global scope.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_FastDispatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_FastDispatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_FastDispatch"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_FastDispatch",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_fastdispatch"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_MIDIOutputEventListCallback": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_MIDIOutputEventListCallback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_MIDIOutputEventListCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_MIDIOutputEventListCallback"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_MIDIOutputEventListCallback",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_midioutputeventlistcallback"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SupportedNumChannels": {
      "abstract": [
        {
          "text": "A read-only array of channel information structures valid on the audio unit global scope.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SupportedNumChannels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SupportedNumChannels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_SupportedNumChannels"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_SupportedNumChannels",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_supportednumchannels"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_ElementCount",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SupportedNumChannels",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_AudioChannelLayout",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_AudioUnitMIDIProtocol",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_AUHostIdentifier",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_BypassEffect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_ClassInfo",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_ClassInfoFromDocument",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_CocoaUI",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_ContextName",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_CPULoad",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_DependentParameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_ElementName",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_FactoryPresets",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_FastDispatch"
      ],
      "title": "Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioUnitProperty_MIDIOutputEventListCallback"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_MIDIOutputEventListCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_ElementCount",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_SupportedNumChannels",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_AudioChannelLayout",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_AudioUnitMIDIProtocol",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_AUHostIdentifier",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_BypassEffect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_ClassInfo",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_ClassInfoFromDocument",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_CocoaUI",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_ContextName",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_CPULoad",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_DependentParameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_ElementName",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_FactoryPresets",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_FastDispatch"
              ],
              "title": "Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioUnitProperty_MIDIOutputEventListCallback"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_MIDIOutputEventListCallback/title",
          "value": "kAudioUnitProperty_MIDIOutputEventListCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_MIDIOutputEventListCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_MIDIOutputEventListCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_FastDispatch/title",
          "value": "kAudioUnitProperty_FastDispatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_FastDispatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_FastDispatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_CocoaUI/title",
          "value": "kAudioUnitProperty_CocoaUI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_CocoaUI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_CocoaUI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_ContextName/title",
          "value": "kAudioUnitProperty_ContextName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_ContextName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_ContextName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_AUHostIdentifier/title",
          "value": "kAudioUnitProperty_AUHostIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_AUHostIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_AUHostIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_DependentParameters/title",
          "value": "kAudioUnitProperty_DependentParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_DependentParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_DependentParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_AudioChannelLayout/title",
          "value": "kAudioUnitProperty_AudioChannelLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_AudioChannelLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_AudioChannelLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_ElementCount/title",
          "value": "kAudioUnitProperty_ElementCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_ElementCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_ElementCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SupportedNumChannels/title",
          "value": "kAudioUnitProperty_SupportedNumChannels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_SupportedNumChannels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_SupportedNumChannels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_FactoryPresets/title",
          "value": "kAudioUnitProperty_FactoryPresets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_FactoryPresets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_FactoryPresets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_ElementName/title",
          "value": "kAudioUnitProperty_ElementName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_ElementName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_ElementName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_AudioUnitMIDIProtocol/title",
          "value": "kAudioUnitProperty_AudioUnitMIDIProtocol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_AudioUnitMIDIProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_AudioUnitMIDIProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_ClassInfoFromDocument/title",
          "value": "kAudioUnitProperty_ClassInfoFromDocument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_ClassInfoFromDocument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_ClassInfoFromDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_CPULoad/title",
          "value": "kAudioUnitProperty_CPULoad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_CPULoad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_CPULoad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitPropertyID/title",
          "value": "AudioUnitPropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitPropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitPropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_ClassInfo/title",
          "value": "kAudioUnitProperty_ClassInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_ClassInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_ClassInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_BypassEffect/title",
          "value": "kAudioUnitProperty_BypassEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_BypassEffect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_BypassEffect"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiounitproperty_midioutputeventlistcallback"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiounitproperty_midioutputeventlistcallback"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
