{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyApplicableOutputSampleRates"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioCodecPropertyInputBufferSize@kAudioCodecPropertyApplicableOutputSampleRates",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioCodecPropertyApplicableOutputSampleRates"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioCodecPropertyID",
        "text": "AudioCodecPropertyID"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioCodecPropertyApplicableOutputSampleRates"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioCodecPropertyApplicableOutputSampleRates"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyApplicableOutputSampleRates"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecPropertyID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioCodecPropertyID",
              "text": "AudioCodecPropertyID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecPropertyID": {
      "abstract": [
        {
          "text": "An integer identifying an audio codec property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecPropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioCodecPropertyID"
        }
      ],
      "role": "symbol",
      "title": "AudioCodecPropertyID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocodecpropertyid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAdjustLocalQuality": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAdjustLocalQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAdjustLocalQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAdjustLocalQuality"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyAdjustLocalQuality",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyadjustlocalquality"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyApplicableBitRateRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyApplicableBitRateRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyApplicableBitRateRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyApplicableBitRateRange"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyApplicableBitRateRange",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyapplicablebitraterange"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyApplicableInputSampleRates": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyApplicableInputSampleRates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyApplicableInputSampleRates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyApplicableInputSampleRates"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyApplicableInputSampleRates",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyapplicableinputsamplerates"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyApplicableOutputSampleRates": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyApplicableOutputSampleRates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyApplicableOutputSampleRates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyApplicableOutputSampleRates"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyApplicableOutputSampleRates",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyapplicableoutputsamplerates"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyBitRateControlMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyBitRateControlMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyBitRateControlMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyBitRateControlMode"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyBitRateControlMode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertybitratecontrolmode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyCurrentInputChannelLayout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyCurrentInputChannelLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyCurrentInputChannelLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyCurrentInputChannelLayout"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyCurrentInputChannelLayout",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertycurrentinputchannellayout"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyCurrentInputFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyCurrentInputFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyCurrentInputFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyCurrentInputFormat"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyCurrentInputFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertycurrentinputformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyCurrentInputSampleRate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyCurrentInputSampleRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyCurrentInputSampleRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyCurrentInputSampleRate"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyCurrentInputSampleRate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertycurrentinputsamplerate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyCurrentOutputChannelLayout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyCurrentOutputChannelLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyCurrentOutputChannelLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyCurrentOutputChannelLayout"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyCurrentOutputChannelLayout",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertycurrentoutputchannellayout"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyCurrentOutputFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyCurrentOutputFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyCurrentOutputFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyCurrentOutputFormat"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyCurrentOutputFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertycurrentoutputformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyCurrentOutputSampleRate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyCurrentOutputSampleRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyCurrentOutputSampleRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyCurrentOutputSampleRate"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyCurrentOutputSampleRate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertycurrentoutputsamplerate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyCurrentTargetBitRate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyCurrentTargetBitRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyCurrentTargetBitRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyCurrentTargetBitRate"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyCurrentTargetBitRate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertycurrenttargetbitrate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyDelayMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyDelayMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyDelayMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyDelayMode"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyDelayMode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertydelaymode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyDynamicRangeControlMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyDynamicRangeControlMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyDynamicRangeControlMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyDynamicRangeControlMode"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyDynamicRangeControlMode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertydynamicrangecontrolmode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyFormatList": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyFormatList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyFormatList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyFormatList"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyFormatList",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyformatlist"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyHasVariablePacketByteSizes": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyHasVariablePacketByteSizes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyHasVariablePacketByteSizes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyHasVariablePacketByteSizes"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyHasVariablePacketByteSizes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyhasvariablepacketbytesizes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAdjustLocalQuality",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyApplicableBitRateRange",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyApplicableInputSampleRates",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyBitRateControlMode",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyCurrentInputChannelLayout",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyCurrentInputFormat",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyCurrentInputSampleRate",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyCurrentOutputChannelLayout",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyCurrentOutputFormat",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyCurrentOutputSampleRate",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyCurrentTargetBitRate",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyDelayMode",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyDynamicRangeControlMode",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyFormatList",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyHasVariablePacketByteSizes"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioCodecPropertyApplicableOutputSampleRates"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyApplicableOutputSampleRates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAdjustLocalQuality",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyApplicableBitRateRange",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyApplicableInputSampleRates",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyBitRateControlMode",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyCurrentInputChannelLayout",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyCurrentInputFormat",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyCurrentInputSampleRate",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyCurrentOutputChannelLayout",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyCurrentOutputFormat",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyCurrentOutputSampleRate",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyCurrentTargetBitRate",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyDelayMode",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyDynamicRangeControlMode",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyFormatList",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyHasVariablePacketByteSizes"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioCodecPropertyApplicableOutputSampleRates"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyDynamicRangeControlMode/title",
          "value": "kAudioCodecPropertyDynamicRangeControlMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyDynamicRangeControlMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyDynamicRangeControlMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyCurrentOutputSampleRate/title",
          "value": "kAudioCodecPropertyCurrentOutputSampleRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyCurrentOutputSampleRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyCurrentOutputSampleRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAdjustLocalQuality/title",
          "value": "kAudioCodecPropertyAdjustLocalQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAdjustLocalQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyAdjustLocalQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyDelayMode/title",
          "value": "kAudioCodecPropertyDelayMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyDelayMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyDelayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyHasVariablePacketByteSizes/title",
          "value": "kAudioCodecPropertyHasVariablePacketByteSizes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyHasVariablePacketByteSizes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyHasVariablePacketByteSizes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyCurrentOutputChannelLayout/title",
          "value": "kAudioCodecPropertyCurrentOutputChannelLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyCurrentOutputChannelLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyCurrentOutputChannelLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecPropertyID/title",
          "value": "AudioCodecPropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecPropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecPropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyCurrentOutputFormat/title",
          "value": "kAudioCodecPropertyCurrentOutputFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyCurrentOutputFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyCurrentOutputFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyApplicableOutputSampleRates/title",
          "value": "kAudioCodecPropertyApplicableOutputSampleRates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyApplicableOutputSampleRates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyApplicableOutputSampleRates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyCurrentTargetBitRate/title",
          "value": "kAudioCodecPropertyCurrentTargetBitRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyCurrentTargetBitRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyCurrentTargetBitRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyCurrentInputFormat/title",
          "value": "kAudioCodecPropertyCurrentInputFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyCurrentInputFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyCurrentInputFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyFormatList/title",
          "value": "kAudioCodecPropertyFormatList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyFormatList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyFormatList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyApplicableBitRateRange/title",
          "value": "kAudioCodecPropertyApplicableBitRateRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyApplicableBitRateRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyApplicableBitRateRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyCurrentInputSampleRate/title",
          "value": "kAudioCodecPropertyCurrentInputSampleRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyCurrentInputSampleRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyCurrentInputSampleRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyCurrentInputChannelLayout/title",
          "value": "kAudioCodecPropertyCurrentInputChannelLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyCurrentInputChannelLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyCurrentInputChannelLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyApplicableInputSampleRates/title",
          "value": "kAudioCodecPropertyApplicableInputSampleRates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyApplicableInputSampleRates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyApplicableInputSampleRates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyBitRateControlMode/title",
          "value": "kAudioCodecPropertyBitRateControlMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyBitRateControlMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyBitRateControlMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiocodecpropertyapplicableoutputsamplerates"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiocodecpropertyapplicableoutputsamplerates"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
