{
  "abstract": [
    {
      "text": "An ",
      "type": "text"
    },
    {
      "code": "SInt64",
      "type": "codeVoice"
    },
    {
      "text": " value indicating the byte offset in the streamed file at which the audio data starts.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_DataOffset"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioFileStreamProperty_ReadyToProducePackets@kAudioFileStreamProperty_DataOffset",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioFileStreamProperty_DataOffset"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
        "text": "AudioFileStreamPropertyID"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioFileStreamProperty_DataOffset"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioFileStreamProperty_DataOffset"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_DataOffset"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamPropertyID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
              "text": "AudioFileStreamPropertyID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamPropertyID": {
      "abstract": [
        {
          "text": "Uniquely identifies an audio file stream property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileStreamPropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "role": "symbol",
      "title": "AudioFileStreamPropertyID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilestreampropertyid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileWriteBytes(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Writes bytes of audio data to an audio file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileWriteBytes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileID",
          "text": "AudioFileID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileWriteBytes(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileWriteBytes"
        }
      ],
      "role": "symbol",
      "title": "AudioFileWriteBytes(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilewritebytes(_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileWritePackets(_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Writes packets of audio data to an audio data file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileWritePackets"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileID",
          "text": "AudioFileID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioStreamPacketDescription",
          "text": "AudioStreamPacketDescription"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileWritePackets(_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileWritePackets"
        }
      ],
      "role": "symbol",
      "title": "AudioFileWritePackets(_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilewritepackets(_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_AudioDataByteCount": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "UInt64",
          "type": "codeVoice"
        },
        {
          "text": " value indicating the number of bytes of audio data in the streamed file. This property is valid only if the number of bytes for the entire stream is known from the data parsed in the header. For some kinds of streams this property may have no value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_AudioDataByteCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_AudioDataByteCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_AudioDataByteCount"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_AudioDataByteCount",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_audiodatabytecount"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_AudioDataPacketCount": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "UInt64",
          "type": "codeVoice"
        },
        {
          "text": " value indicating the number of packets of audio data in the streamed file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_AudioDataPacketCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_AudioDataPacketCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_AudioDataPacketCount"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_AudioDataPacketCount",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_audiodatapacketcount"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_ByteToPacket": {
      "abstract": [
        {
          "text": "Obtains the packet number corresponding to a byte number. Pass an ",
          "type": "text"
        },
        {
          "code": "AudioBytePacketTranslation",
          "type": "codeVoice"
        },
        {
          "text": " structure with the ",
          "type": "text"
        },
        {
          "code": "mByte",
          "type": "codeVoice"
        },
        {
          "text": " field filled in, and values are returned in the ",
          "type": "text"
        },
        {
          "code": "mPacket",
          "type": "codeVoice"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "code": "mByteOffsetInPacket",
          "type": "codeVoice"
        },
        {
          "text": " fields. If the ",
          "type": "text"
        },
        {
          "code": "mPacket",
          "type": "codeVoice"
        },
        {
          "text": " value is an estimate, then the ",
          "type": "text"
        },
        {
          "code": "kBytePacketTranslationFlag_IsEstimate",
          "type": "codeVoice"
        },
        {
          "text": " value will be set in the ",
          "type": "text"
        },
        {
          "code": "mFlags",
          "type": "codeVoice"
        },
        {
          "text": " field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_ByteToPacket"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_ByteToPacket",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_ByteToPacket"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_ByteToPacket",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_bytetopacket"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_ChannelLayout": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "AudioChannelLayout",
          "type": "codeVoice"
        },
        {
          "text": " structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_ChannelLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_ChannelLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_ChannelLayout"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_ChannelLayout",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_channellayout"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_DataFormat": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "AudioStreamBasicDescription",
          "type": "codeVoice"
        },
        {
          "text": " structure describing the format of the audio data in the stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_DataFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_DataFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_DataFormat"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_DataFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_dataformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_DataOffset": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "SInt64",
          "type": "codeVoice"
        },
        {
          "text": " value indicating the byte offset in the streamed file at which the audio data starts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_DataOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_DataOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_DataOffset"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_DataOffset",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_dataoffset"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_FileFormat": {
      "abstract": [
        {
          "text": "A four-character code that identifies the audio data format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_FileFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_FileFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_FileFormat"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_FileFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_fileformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_FormatList": {
      "abstract": [
        {
          "text": "To support formats such as AAC with SBR where an encoded data stream can be decoded to multiple destination formats, this property returns an array of ",
          "type": "text"
        },
        {
          "code": "AudioFormatListItem",
          "type": "codeVoice"
        },
        {
          "text": " structures (declared in ",
          "type": "text"
        },
        {
          "code": "AudioFormat.h",
          "type": "codeVoice"
        },
        {
          "text": ")—one for each of the destination formats. The default behavior is to return an ",
          "type": "text"
        },
        {
          "code": "AudioFormatListItem",
          "type": "codeVoice"
        },
        {
          "text": " structure that has the same ",
          "type": "text"
        },
        {
          "code": "AudioStreamBasicDescription",
          "type": "codeVoice"
        },
        {
          "text": " structure as that returned by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_DataFormat",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_FormatList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_FormatList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_FormatList"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_FormatList",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_formatlist"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_FrameToPacket": {
      "abstract": [
        {
          "text": "Obtains the packet number corresponding to a frame number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_FrameToPacket"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_FrameToPacket",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_FrameToPacket"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_FrameToPacket",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_frametopacket"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_MagicCookieData": {
      "abstract": [
        {
          "text": "A pointer (",
          "type": "text"
        },
        {
          "code": "void *",
          "type": "codeVoice"
        },
        {
          "text": ") to a magic cookie. For audio file types that require a magic cookie before packets can be written to a file, you should get this property value before calling the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileWriteBytes(_:_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileWritePackets(_:_:_:_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_MagicCookieData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_MagicCookieData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_MagicCookieData"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_MagicCookieData",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_magiccookiedata"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_MaximumPacketSize": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value indicating the maximum packet size of the data in the streamed file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_MaximumPacketSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_MaximumPacketSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_MaximumPacketSize"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_MaximumPacketSize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_maximumpacketsize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketSizeUpperBound": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value indicating the theoretical maximum packet size in the streamed file. This value is useful for determining minimum buffer sizes, for example.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_PacketSizeUpperBound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketSizeUpperBound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_PacketSizeUpperBound"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_PacketSizeUpperBound",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_packetsizeupperbound"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketTableInfo": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "AudioFilePacketTableInfo",
          "type": "codeVoice"
        },
        {
          "text": " structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_PacketTableInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketTableInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_PacketTableInfo"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_PacketTableInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_packettableinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketToByte": {
      "abstract": [
        {
          "text": "Obtains the byte number corresponding to a packet number. Pass an ",
          "type": "text"
        },
        {
          "code": "AudioBytePacketTranslation",
          "type": "codeVoice"
        },
        {
          "text": " structure with the ",
          "type": "text"
        },
        {
          "code": "mPacket",
          "type": "codeVoice"
        },
        {
          "text": " field filled in, and a value is returned in the ",
          "type": "text"
        },
        {
          "code": "mByte",
          "type": "codeVoice"
        },
        {
          "text": " field. The ",
          "type": "text"
        },
        {
          "code": "mByteOffsetInPacket",
          "type": "codeVoice"
        },
        {
          "text": " field of the ",
          "type": "text"
        },
        {
          "code": "AudioBytePacketTranslation",
          "type": "codeVoice"
        },
        {
          "text": " structure is ignored. If the ",
          "type": "text"
        },
        {
          "code": "mByte",
          "type": "codeVoice"
        },
        {
          "text": " value is an estimate, then the ",
          "type": "text"
        },
        {
          "code": "kBytePacketTranslationFlag_IsEstimate",
          "type": "codeVoice"
        },
        {
          "text": " value will be set in the ",
          "type": "text"
        },
        {
          "code": "mFlags",
          "type": "codeVoice"
        },
        {
          "text": " field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_PacketToByte"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketToByte",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_PacketToByte"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_PacketToByte",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_packettobyte"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketToFrame": {
      "abstract": [
        {
          "text": "Obtains the frame number corresponding to a packet number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_PacketToFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketToFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_PacketToFrame"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_PacketToFrame",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_packettoframe"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_ReadyToProducePackets": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_ReadyToProducePackets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileStreamPropertyID",
          "text": "AudioFileStreamPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_ReadyToProducePackets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamProperty_ReadyToProducePackets"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamProperty_ReadyToProducePackets",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamproperty_readytoproducepackets"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_ReadyToProducePackets",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_FileFormat",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_DataFormat",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_FormatList",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_MagicCookieData",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_AudioDataByteCount",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_AudioDataPacketCount",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_MaximumPacketSize",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_ChannelLayout",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketToFrame",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_FrameToPacket",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketToByte",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_ByteToPacket",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketTableInfo",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketSizeUpperBound"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioFileStreamProperty_DataOffset"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_DataOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_ReadyToProducePackets",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_FileFormat",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_DataFormat",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_FormatList",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_MagicCookieData",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_AudioDataByteCount",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_AudioDataPacketCount",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_MaximumPacketSize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_ChannelLayout",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketToFrame",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_FrameToPacket",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketToByte",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_ByteToPacket",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketTableInfo",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamProperty_PacketSizeUpperBound"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioFileStreamProperty_DataOffset"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_PacketToFrame/title",
          "value": "kAudioFileStreamProperty_PacketToFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_PacketToFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_PacketToFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_FrameToPacket/title",
          "value": "kAudioFileStreamProperty_FrameToPacket"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_FrameToPacket/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_FrameToPacket"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_PacketTableInfo/title",
          "value": "kAudioFileStreamProperty_PacketTableInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_PacketTableInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_PacketTableInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_PacketToByte/title",
          "value": "kAudioFileStreamProperty_PacketToByte"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_PacketToByte/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_PacketToByte"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_AudioDataPacketCount/title",
          "value": "kAudioFileStreamProperty_AudioDataPacketCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_AudioDataPacketCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_AudioDataPacketCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_DataOffset/title",
          "value": "kAudioFileStreamProperty_DataOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_DataOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_DataOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_FileFormat/title",
          "value": "kAudioFileStreamProperty_FileFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_FileFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_FileFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_PacketSizeUpperBound/title",
          "value": "kAudioFileStreamProperty_PacketSizeUpperBound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_PacketSizeUpperBound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_PacketSizeUpperBound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_DataFormat/title",
          "value": "kAudioFileStreamProperty_DataFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_DataFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_DataFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileStreamPropertyID/title",
          "value": "AudioFileStreamPropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileStreamPropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileStreamPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileStreamPropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileStreamPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_ReadyToProducePackets/title",
          "value": "kAudioFileStreamProperty_ReadyToProducePackets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_ReadyToProducePackets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_ReadyToProducePackets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileWriteBytes(_:_:_:_:_:)/title",
          "value": "AudioFileWriteBytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileWriteBytes(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileWriteBytes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileWritePackets(_:_:_:_:_:_:_:)/title",
          "value": "AudioFileWritePackets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileWritePackets(_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileWritePackets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_MagicCookieData/title",
          "value": "kAudioFileStreamProperty_MagicCookieData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_MagicCookieData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_MagicCookieData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_ChannelLayout/title",
          "value": "kAudioFileStreamProperty_ChannelLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_ChannelLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_ChannelLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_ByteToPacket/title",
          "value": "kAudioFileStreamProperty_ByteToPacket"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_ByteToPacket/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_ByteToPacket"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_MaximumPacketSize/title",
          "value": "kAudioFileStreamProperty_MaximumPacketSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_MaximumPacketSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_MaximumPacketSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_FormatList/title",
          "value": "kAudioFileStreamProperty_FormatList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_FormatList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_FormatList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_AudioDataByteCount/title",
          "value": "kAudioFileStreamProperty_AudioDataByteCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamProperty_AudioDataByteCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamProperty_AudioDataByteCount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiofilestreamproperty_dataoffset"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiofilestreamproperty_dataoffset"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
