{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_AUSoundIsolation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioUnitSubType_PeakLimiter@kAudioUnitSubType_AUSoundIsolation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioUnitSubType_AUSoundIsolation"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioUnitSubType_AUSoundIsolation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioUnitSubType_AUSoundIsolation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_AUSoundIsolation"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_AUSoundIsolation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_AUSoundIsolation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_AUSoundIsolation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_AUSoundIsolation"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_AUSoundIsolation",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_ausoundisolation"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_AUiPodEQ": {
      "abstract": [
        {
          "text": "An audio unit that provides a graphic equalizer in iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_AUiPodEQ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_AUiPodEQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_AUiPodEQ"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_AUiPodEQ",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_auipodeq"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_BandPassFilter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_BandPassFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_BandPassFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_BandPassFilter"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_BandPassFilter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_bandpassfilter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Delay": {
      "abstract": [
        {
          "text": "An audio unit that introduces a time delay to a signal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_Delay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Delay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_Delay"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_Delay",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_delay"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Distortion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_Distortion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Distortion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_Distortion"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_Distortion",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_distortion"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_DynamicsProcessor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_DynamicsProcessor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_DynamicsProcessor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_DynamicsProcessor"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_DynamicsProcessor",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_dynamicsprocessor"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_HighPassFilter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_HighPassFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_HighPassFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_HighPassFilter"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_HighPassFilter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_highpassfilter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_HighShelfFilter": {
      "abstract": [
        {
          "text": "An audio unit suitable for implementing a treble control in an audio playback or recording system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_HighShelfFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_HighShelfFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_HighShelfFilter"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_HighShelfFilter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_highshelffilter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_LowPassFilter": {
      "abstract": [
        {
          "text": "An audio unit that passes frequencies below a specified cutoff frequency, and blocks frequencies above that cutoff frequency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_LowPassFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_LowPassFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_LowPassFilter"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_LowPassFilter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_lowpassfilter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_LowShelfFilter": {
      "abstract": [
        {
          "text": "An audio unit suitable for implementing a bass control in an audio playback or recording system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_LowShelfFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_LowShelfFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_LowShelfFilter"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_LowShelfFilter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_lowshelffilter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_NBandEQ": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_NBandEQ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_NBandEQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_NBandEQ"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_NBandEQ",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_nbandeq"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_ParametricEQ": {
      "abstract": [
        {
          "text": "An audio unit that provides a filter whose center frequency, boost/cut level, and Q can be adjusted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_ParametricEQ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_ParametricEQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_ParametricEQ"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_ParametricEQ",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_parametriceq"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_PeakLimiter": {
      "abstract": [
        {
          "text": "An audio unit that enforces an upper dynamic limit on an audio signal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_PeakLimiter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_PeakLimiter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_PeakLimiter"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_PeakLimiter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_peaklimiter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Reverb2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_Reverb2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Reverb2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_Reverb2"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_Reverb2",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_reverb2"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_SampleDelay": {
      "abstract": [
        {
          "text": "An audio unit that provides a time delay for a specified number of samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_SampleDelay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_SampleDelay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_SampleDelay"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_SampleDelay",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_sampledelay"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_AUiPodEQ",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_BandPassFilter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Delay",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Distortion",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_DynamicsProcessor",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_HighPassFilter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_HighShelfFilter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_LowPassFilter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_LowShelfFilter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_NBandEQ",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_ParametricEQ",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_PeakLimiter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_SampleDelay",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Reverb2"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioUnitSubType_AUSoundIsolation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_AUSoundIsolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_AUiPodEQ",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_BandPassFilter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Delay",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Distortion",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_DynamicsProcessor",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_HighPassFilter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_HighShelfFilter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_LowPassFilter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_LowShelfFilter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_NBandEQ",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_ParametricEQ",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_PeakLimiter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_SampleDelay",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Reverb2"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioUnitSubType_AUSoundIsolation"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_ParametricEQ/title",
          "value": "kAudioUnitSubType_ParametricEQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_ParametricEQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_ParametricEQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_Reverb2/title",
          "value": "kAudioUnitSubType_Reverb2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_Reverb2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_Reverb2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_HighPassFilter/title",
          "value": "kAudioUnitSubType_HighPassFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_HighPassFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_HighPassFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_LowShelfFilter/title",
          "value": "kAudioUnitSubType_LowShelfFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_LowShelfFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_LowShelfFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_LowPassFilter/title",
          "value": "kAudioUnitSubType_LowPassFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_LowPassFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_LowPassFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_SampleDelay/title",
          "value": "kAudioUnitSubType_SampleDelay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_SampleDelay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_SampleDelay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_NBandEQ/title",
          "value": "kAudioUnitSubType_NBandEQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_NBandEQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_NBandEQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_DynamicsProcessor/title",
          "value": "kAudioUnitSubType_DynamicsProcessor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_DynamicsProcessor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_DynamicsProcessor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_AUSoundIsolation/title",
          "value": "kAudioUnitSubType_AUSoundIsolation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_AUSoundIsolation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_AUSoundIsolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_Delay/title",
          "value": "kAudioUnitSubType_Delay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_Delay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_Delay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_PeakLimiter/title",
          "value": "kAudioUnitSubType_PeakLimiter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_PeakLimiter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_PeakLimiter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_HighShelfFilter/title",
          "value": "kAudioUnitSubType_HighShelfFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_HighShelfFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_HighShelfFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_AUiPodEQ/title",
          "value": "kAudioUnitSubType_AUiPodEQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_AUiPodEQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_AUiPodEQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_BandPassFilter/title",
          "value": "kAudioUnitSubType_BandPassFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_BandPassFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_BandPassFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_Distortion/title",
          "value": "kAudioUnitSubType_Distortion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_Distortion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_Distortion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiounitsubtype_ausoundisolation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiounitsubtype_ausoundisolation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
