{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/audiotoolbox/kaudiounitofflineproperty_inputsize"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/audiotoolbox/kaudiounitofflineproperty_inputsize"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.audiotoolbox/documentation/AudioToolbox"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Global Variable","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioUnitOfflineProperty_InputSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@AudioUnitPropertyID","text":"AudioUnitPropertyID","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"kAudioUnitOfflineProperty_InputSize","kind":"identifier"}],"symbolKind":"var","modules":[{"name":"Audio Toolbox"}],"title":"kAudioUnitOfflineProperty_InputSize","externalID":"c:@Ea@kAudioUnitOfflineProperty_InputSize@kAudioUnitOfflineProperty_InputSize","platforms":[{"name":"macOS","unavailable":false,"beta":false,"deprecated":false}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioUnitOfflineProperty_InputSize"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitPropertyID","kind":"typeIdentifier","text":"AudioUnitPropertyID","preciseIdentifier":"c:@T@AudioUnitPropertyID"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["macOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_InputSize"},"seeAlsoSections":[{"generated":true,"anchor":"Constants","title":"Constants","identifiers":["doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_OutputSize","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_PreflightName","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_PreflightRequirements","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_StartOffset"]}],"kind":"symbol","sections":[],"references":{"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_StartOffset":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kAudioUnitOfflineProperty_StartOffset"}],"kind":"symbol","url":"/documentation/audiotoolbox/kaudiounitofflineproperty_startoffset","title":"kAudioUnitOfflineProperty_StartOffset","abstract":[],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_StartOffset","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioUnitOfflineProperty_StartOffset"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@AudioUnitPropertyID","kind":"typeIdentifier","text":"AudioUnitPropertyID"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_PreflightName":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioUnitOfflineProperty_PreflightName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioUnitPropertyID","preciseIdentifier":"c:@T@AudioUnitPropertyID"}],"url":"/documentation/audiotoolbox/kaudiounitofflineproperty_preflightname","role":"symbol","type":"topic","title":"kAudioUnitOfflineProperty_PreflightName","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_PreflightName","navigatorTitle":[{"kind":"identifier","text":"kAudioUnitOfflineProperty_PreflightName"}],"abstract":[],"kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","type":"topic","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","role":"overview"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_PreflightRequirements":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kAudioUnitOfflineProperty_PreflightRequirements"}],"kind":"symbol","url":"/documentation/audiotoolbox/kaudiounitofflineproperty_preflightrequirements","title":"kAudioUnitOfflineProperty_PreflightRequirements","abstract":[],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_PreflightRequirements","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioUnitOfflineProperty_PreflightRequirements"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@AudioUnitPropertyID","kind":"typeIdentifier","text":"AudioUnitPropertyID"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_OutputSize":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kAudioUnitOfflineProperty_OutputSize"}],"kind":"symbol","url":"/documentation/audiotoolbox/kaudiounitofflineproperty_outputsize","title":"kAudioUnitOfflineProperty_OutputSize","abstract":[],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_OutputSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioUnitOfflineProperty_OutputSize"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@AudioUnitPropertyID","kind":"typeIdentifier","text":"AudioUnitPropertyID"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_InputSize":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioUnitOfflineProperty_InputSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioUnitPropertyID","preciseIdentifier":"c:@T@AudioUnitPropertyID"}],"url":"/documentation/audiotoolbox/kaudiounitofflineproperty_inputsize","role":"symbol","type":"topic","title":"kAudioUnitOfflineProperty_InputSize","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_InputSize","navigatorTitle":[{"kind":"identifier","text":"kAudioUnitOfflineProperty_InputSize"}],"abstract":[],"kind":"symbol"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox":{"type":"topic","kind":"symbol","title":"Audio Toolbox","role":"collection","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox","abstract":[{"text":"Record or play audio, convert formats, parse audio streams, and configure your audio session.","type":"text"}],"url":"/documentation/audiotoolbox"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitPropertyID":{"url":"/documentation/audiotoolbox/audiounitpropertyid","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioUnitPropertyID","kind":"identifier"}],"type":"topic","title":"AudioUnitPropertyID","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitPropertyID","abstract":[{"text":"The data type for audio unit property keys.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AudioUnitPropertyID","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"beta":false,"name":"macOS","deprecated":false}],"op":"replace"},{"value":"Enumeration Case","op":"replace","path":"/metadata/roleHeading"},{"value":"kAudioUnitOfflineProperty_InputSize","op":"replace","path":"/metadata/title"},{"value":"case","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"kAudioUnitOfflineProperty_InputSize"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.audiotoolbox/documentation/AudioToolbox"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"anchor":"Constants","generated":true,"identifiers":["doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_OutputSize","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_PreflightName","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_PreflightRequirements","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitOfflineProperty_StartOffset"],"title":"Constants"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"kind":"identifier","text":"kAudioUnitOfflineProperty_InputSize"}]}]},"path":"/primaryContentSections/0","op":"replace"},{"value":"kAudioUnitOfflineProperty_StartOffset","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitOfflineProperty_StartOffset/title","op":"replace"},{"value":[{"kind":"identifier","text":"kAudioUnitOfflineProperty_StartOffset"}],"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitOfflineProperty_StartOffset/fragments","op":"replace"},{"value":"kAudioUnitOfflineProperty_PreflightName","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitOfflineProperty_PreflightName/title","op":"replace"},{"value":[{"kind":"identifier","text":"kAudioUnitOfflineProperty_PreflightName"}],"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitOfflineProperty_PreflightName/fragments","op":"replace"},{"value":"kAudioUnitOfflineProperty_PreflightRequirements","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitOfflineProperty_PreflightRequirements/title","op":"replace"},{"value":[{"text":"kAudioUnitOfflineProperty_PreflightRequirements","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitOfflineProperty_PreflightRequirements/fragments","op":"replace"},{"value":"kAudioUnitOfflineProperty_OutputSize","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitOfflineProperty_OutputSize/title","op":"replace"},{"value":[{"kind":"identifier","text":"kAudioUnitOfflineProperty_OutputSize"}],"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitOfflineProperty_OutputSize/fragments","op":"replace"},{"value":"kAudioUnitOfflineProperty_InputSize","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitOfflineProperty_InputSize/title","op":"replace"},{"value":[{"kind":"identifier","text":"kAudioUnitOfflineProperty_InputSize"}],"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitOfflineProperty_InputSize/fragments","op":"replace"},{"value":"AudioUnitPropertyID","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitPropertyID/title","op":"replace"},{"value":[{"kind":"identifier","text":"AudioUnitPropertyID"}],"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitPropertyID/fragments","op":"replace"},{"value":[{"text":"AudioUnitPropertyID","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitPropertyID/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}