{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_InitialOutputs"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@kAudioUnitConfigurationInfo_InitialOutputs",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioUnitConfigurationInfo_InitialOutputs"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioUnitConfigurationInfo_InitialOutputs"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioUnitConfigurationInfo_InitialOutputs"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioUnitConfigurationInfo_InitialOutputs"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_BusCountWritable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitConfigurationInfo_BusCountWritable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_BusCountWritable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitConfigurationInfo_BusCountWritable"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitConfigurationInfo_BusCountWritable",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitconfigurationinfo_buscountwritable"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_ChannelConfigurations": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitConfigurationInfo_ChannelConfigurations"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_ChannelConfigurations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitConfigurationInfo_ChannelConfigurations"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitConfigurationInfo_ChannelConfigurations",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitconfigurationinfo_channelconfigurations"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_HasCustomView": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitConfigurationInfo_HasCustomView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_HasCustomView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitConfigurationInfo_HasCustomView"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitConfigurationInfo_HasCustomView",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitconfigurationinfo_hascustomview"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_IconURL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitConfigurationInfo_IconURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_IconURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitConfigurationInfo_IconURL"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitConfigurationInfo_IconURL",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitconfigurationinfo_iconurl"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_InitialInputs": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitConfigurationInfo_InitialInputs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_InitialInputs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitConfigurationInfo_InitialInputs"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitConfigurationInfo_InitialInputs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitconfigurationinfo_initialinputs"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_InitialOutputs": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitConfigurationInfo_InitialOutputs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_InitialOutputs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitConfigurationInfo_InitialOutputs"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitConfigurationInfo_InitialOutputs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitconfigurationinfo_initialoutputs"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_SupportedChannelLayoutTags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitConfigurationInfo_SupportedChannelLayoutTags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_SupportedChannelLayoutTags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitConfigurationInfo_SupportedChannelLayoutTags"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitConfigurationInfo_SupportedChannelLayoutTags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitconfigurationinfo_supportedchannellayouttags"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Configuration-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_BusCountWritable",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_ChannelConfigurations",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_HasCustomView",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_IconURL",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_InitialInputs",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_SupportedChannelLayoutTags"
      ],
      "title": "Getting the Configuration Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioUnitConfigurationInfo_InitialOutputs"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitConfigurationInfo_InitialOutputs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Configuration-Information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_BusCountWritable",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_ChannelConfigurations",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_HasCustomView",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_IconURL",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_InitialInputs",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitConfigurationInfo_SupportedChannelLayoutTags"
              ],
              "title": "Getting the Configuration Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kAudioUnitConfigurationInfo_InitialOutputs"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitConfigurationInfo_HasCustomView/title",
          "value": "kAudioUnitConfigurationInfo_HasCustomView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitConfigurationInfo_HasCustomView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitConfigurationInfo_HasCustomView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitConfigurationInfo_SupportedChannelLayoutTags/title",
          "value": "kAudioUnitConfigurationInfo_SupportedChannelLayoutTags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitConfigurationInfo_SupportedChannelLayoutTags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitConfigurationInfo_SupportedChannelLayoutTags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitConfigurationInfo_BusCountWritable/title",
          "value": "kAudioUnitConfigurationInfo_BusCountWritable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitConfigurationInfo_BusCountWritable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitConfigurationInfo_BusCountWritable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitConfigurationInfo_InitialOutputs/title",
          "value": "kAudioUnitConfigurationInfo_InitialOutputs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitConfigurationInfo_InitialOutputs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitConfigurationInfo_InitialOutputs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitConfigurationInfo_InitialInputs/title",
          "value": "kAudioUnitConfigurationInfo_InitialInputs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitConfigurationInfo_InitialInputs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitConfigurationInfo_InitialInputs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitConfigurationInfo_ChannelConfigurations/title",
          "value": "kAudioUnitConfigurationInfo_ChannelConfigurations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitConfigurationInfo_ChannelConfigurations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitConfigurationInfo_ChannelConfigurations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitConfigurationInfo_IconURL/title",
          "value": "kAudioUnitConfigurationInfo_IconURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitConfigurationInfo_IconURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitConfigurationInfo_IconURL"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiounitconfigurationinfo_initialoutputs"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiounitconfigurationinfo_initialoutputs"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
