{
  "abstract": [
    {
      "text": "An Audio Interchange File Format (AIFF) file.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileAIFFType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioFileAIFFType@kAudioFileAIFFType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioFileAIFFType"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioFileTypeID",
        "text": "AudioFileTypeID"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioFileAIFFType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioFileAIFFType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioFileAIFFType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileTypeID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioFileTypeID",
              "text": "AudioFileTypeID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileTypeID": {
      "abstract": [
        {
          "text": "Operating system constants that indicate the type of file to be written or a hint about what type of file to expect from data provided.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileTypeID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileTypeID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileTypeID"
        }
      ],
      "role": "symbol",
      "title": "AudioFileTypeID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofiletypeid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFile3GP2Type": {
      "abstract": [
        {
          "text": "A 3GPP2 file, suitable for video content on CDMA mobile phones.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFile3GP2Type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileTypeID",
          "text": "AudioFileTypeID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFile3GP2Type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFile3GP2Type"
        }
      ],
      "role": "symbol",
      "title": "kAudioFile3GP2Type",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofile3gp2type"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFile3GPType": {
      "abstract": [
        {
          "text": "A 3GPP file, suitable for video content on GSM mobile phones.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFile3GPType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileTypeID",
          "text": "AudioFileTypeID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFile3GPType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFile3GPType"
        }
      ],
      "role": "symbol",
      "title": "kAudioFile3GPType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofile3gptype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileAAC_ADTSType": {
      "abstract": [
        {
          "text": "An Advanced Audio Coding (AAC) Audio Data Transport Stream (ADTS) file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileAAC_ADTSType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileTypeID",
          "text": "AudioFileTypeID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileAAC_ADTSType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileAAC_ADTSType"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileAAC_ADTSType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileaac_adtstype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileAC3Type": {
      "abstract": [
        {
          "text": "An AC-3 file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileAC3Type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileTypeID",
          "text": "AudioFileTypeID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileAC3Type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileAC3Type"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileAC3Type",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileac3type"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileAIFCType": {
      "abstract": [
        {
          "text": "An Audio Interchange File Format Compressed (AIFF-C) file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileAIFCType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileTypeID",
          "text": "AudioFileTypeID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileAIFCType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileAIFCType"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileAIFCType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileaifctype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileAIFFType": {
      "abstract": [
        {
          "text": "An Audio Interchange File Format (AIFF) file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileAIFFType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileTypeID",
          "text": "AudioFileTypeID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileAIFFType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileAIFFType"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileAIFFType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileaifftype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileAMRType": {
      "abstract": [
        {
          "text": "An AMR (Adaptive Multi-Rate) file suitable for compressed speech.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileAMRType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileTypeID",
          "text": "AudioFileTypeID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileAMRType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileAMRType"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileAMRType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileamrtype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCAFType": {
      "abstract": [
        {
          "text": "A Core Audio File Format file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileCAFType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileTypeID",
          "text": "AudioFileTypeID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCAFType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileCAFType"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileCAFType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilecaftype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileM4AType": {
      "abstract": [
        {
          "text": "An M4A file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileM4AType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileTypeID",
          "text": "AudioFileTypeID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileM4AType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileM4AType"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileM4AType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilem4atype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileMP1Type": {
      "abstract": [
        {
          "text": "An MPEG Audio Layer 1 (",
          "type": "text"
        },
        {
          "code": ".mp1",
          "type": "codeVoice"
        },
        {
          "text": ") file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileMP1Type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileTypeID",
          "text": "AudioFileTypeID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileMP1Type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileMP1Type"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileMP1Type",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilemp1type"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileMP2Type": {
      "abstract": [
        {
          "text": "An MPEG Audio Layer 2 (",
          "type": "text"
        },
        {
          "code": ".mp2",
          "type": "codeVoice"
        },
        {
          "text": ") file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileMP2Type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileTypeID",
          "text": "AudioFileTypeID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileMP2Type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileMP2Type"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileMP2Type",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilemp2type"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileMP3Type": {
      "abstract": [
        {
          "text": "An MPEG Audio Layer 3 (",
          "type": "text"
        },
        {
          "code": ".mp3",
          "type": "codeVoice"
        },
        {
          "text": ") file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileMP3Type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileTypeID",
          "text": "AudioFileTypeID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileMP3Type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileMP3Type"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileMP3Type",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilemp3type"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileMPEG4Type": {
      "abstract": [
        {
          "text": "An MPEG 4 file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileMPEG4Type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileTypeID",
          "text": "AudioFileTypeID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileMPEG4Type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileMPEG4Type"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileMPEG4Type",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilempeg4type"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileNextType": {
      "abstract": [
        {
          "text": "A NeXT or Sun Microsystems file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileNextType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileTypeID",
          "text": "AudioFileTypeID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileNextType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileNextType"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileNextType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilenexttype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileSoundDesigner2Type": {
      "abstract": [
        {
          "text": "A Sound Designer II file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileSoundDesigner2Type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileTypeID",
          "text": "AudioFileTypeID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileSoundDesigner2Type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileSoundDesigner2Type"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileSoundDesigner2Type",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilesounddesigner2type"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileWAVEType": {
      "abstract": [
        {
          "text": "A Microsoft WAVE file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileWAVEType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileTypeID",
          "text": "AudioFileTypeID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileWAVEType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileWAVEType"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileWAVEType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilewavetype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileAIFCType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileWAVEType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileSoundDesigner2Type",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileNextType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileMP3Type",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileMP2Type",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileMP1Type",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileAC3Type",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileAAC_ADTSType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileMPEG4Type",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileM4AType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCAFType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFile3GPType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFile3GP2Type",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileAMRType"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioFileAIFFType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileAIFFType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileAIFCType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileWAVEType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileSoundDesigner2Type",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileNextType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileMP3Type",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileMP2Type",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileMP1Type",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileAC3Type",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileAAC_ADTSType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileMPEG4Type",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileM4AType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileCAFType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFile3GPType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFile3GP2Type",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileAMRType"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioFileAIFFType"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileAIFCType/title",
          "value": "kAudioFileAIFCType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileAIFCType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileAIFCType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileCAFType/title",
          "value": "kAudioFileCAFType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileCAFType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileCAFType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileAAC_ADTSType/title",
          "value": "kAudioFileAAC_ADTSType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileAAC_ADTSType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileAAC_ADTSType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileAIFFType/title",
          "value": "kAudioFileAIFFType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileAIFFType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileAIFFType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileNextType/title",
          "value": "kAudioFileNextType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileNextType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileNextType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileAC3Type/title",
          "value": "kAudioFileAC3Type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileAC3Type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileAC3Type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileAMRType/title",
          "value": "kAudioFileAMRType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileAMRType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileAMRType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileMP1Type/title",
          "value": "kAudioFileMP1Type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileMP1Type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileMP1Type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileMPEG4Type/title",
          "value": "kAudioFileMPEG4Type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileMPEG4Type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileMPEG4Type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileMP2Type/title",
          "value": "kAudioFileMP2Type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileMP2Type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileMP2Type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileM4AType/title",
          "value": "kAudioFileM4AType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileM4AType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileM4AType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFile3GP2Type/title",
          "value": "kAudioFile3GP2Type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFile3GP2Type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFile3GP2Type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileMP3Type/title",
          "value": "kAudioFileMP3Type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileMP3Type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileMP3Type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileTypeID/title",
          "value": "AudioFileTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileTypeID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileTypeID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileSoundDesigner2Type/title",
          "value": "kAudioFileSoundDesigner2Type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileSoundDesigner2Type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileSoundDesigner2Type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileWAVEType/title",
          "value": "kAudioFileWAVEType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileWAVEType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileWAVEType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFile3GPType/title",
          "value": "kAudioFile3GPType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFile3GPType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFile3GPType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiofileaifftype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiofileaifftype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
