{
  "abstract": [
    {
      "text": "Used by the system to schedule an audio unit parameter value change when you call the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitScheduleParameters(_:_:_:)",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " function.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitScheduleParametersSelect"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioUnitRange@kAudioUnitScheduleParametersSelect",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioUnitScheduleParametersSelect"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioUnitScheduleParametersSelect"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioUnitScheduleParametersSelect"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioUnitScheduleParametersSelect"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitAddPropertyListener(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Registers a callback to receive audio unit property change notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitAddPropertyListener"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnit",
          "text": "AudioUnit"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyListenerProc",
          "text": "AudioUnitPropertyListenerProc"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitAddPropertyListener(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitAddPropertyListener"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitAddPropertyListener(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitaddpropertylistener(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitGetParameter(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Gets the value of an audio unit parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitGetParameter"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnit",
          "text": "AudioUnit"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitScope",
          "text": "AudioUnitScope"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitElement",
          "text": "AudioUnitElement"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterValue",
          "text": "AudioUnitParameterValue"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitGetParameter(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitGetParameter"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitGetParameter(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitgetparameter(_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitGetPropertyInfo(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Gets information about an audio unit property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitGetPropertyInfo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnit",
          "text": "AudioUnit"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitScope",
          "text": "AudioUnitScope"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitElement",
          "text": "AudioUnitElement"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Darwin0A7BooleanV",
          "text": "DarwinBoolean"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitGetPropertyInfo(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitGetPropertyInfo"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitGetPropertyInfo(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitgetpropertyinfo(_:_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRender(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Initiates a rendering cycle for an audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitRender"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnit",
          "text": "AudioUnit"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitRenderActionFlags",
          "text": "AudioUnitRenderActionFlags"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioTimeStamp",
          "text": "AudioTimeStamp"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioBufferList",
          "text": "AudioBufferList"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRender(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitRender"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitRender(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitrender(_:_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitReset(_:_:_:)": {
      "abstract": [
        {
          "text": "Resets an audio unit’s render state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitReset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnit",
          "text": "AudioUnit"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitScope",
          "text": "AudioUnitScope"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitElement",
          "text": "AudioUnitElement"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitReset(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitReset"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitReset(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitreset(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitScheduleParameters(_:_:_:)": {
      "abstract": [
        {
          "text": "Schedules changes to the value of an audio unit parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitScheduleParameters"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnit",
          "text": "AudioUnit"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioUnitParameterEvent",
          "text": "AudioUnitParameterEvent"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitScheduleParameters(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitScheduleParameters"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitScheduleParameters(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitscheduleparameters(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitAddPropertyListenerSelect": {
      "abstract": [
        {
          "text": "Used by the system to register a property listener callback function for an audio unit when you call the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitAddPropertyListener(_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitAddPropertyListenerSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitAddPropertyListenerSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitAddPropertyListenerSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitAddPropertyListenerSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitaddpropertylistenerselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitAddRenderNotifySelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitAddRenderNotifySelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitAddRenderNotifySelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitAddRenderNotifySelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitAddRenderNotifySelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitaddrendernotifyselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitComplexRenderSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitComplexRenderSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitComplexRenderSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitComplexRenderSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitComplexRenderSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitcomplexrenderselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitGetParameterSelect": {
      "abstract": [
        {
          "text": "Used by the system to get the current value of an audio unit parameter when you call the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitGetParameter(_:_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitGetParameterSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitGetParameterSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitGetParameterSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitGetParameterSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitgetparameterselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitGetPropertyInfoSelect": {
      "abstract": [
        {
          "text": "Used by the system to get property information from an audio unit when you call the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitGetPropertyInfo(_:_:_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitGetPropertyInfoSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitGetPropertyInfoSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitGetPropertyInfoSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitGetPropertyInfoSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitgetpropertyinfoselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitGetPropertySelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitGetPropertySelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitGetPropertySelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitGetPropertySelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitGetPropertySelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitgetpropertyselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitInitializeSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitInitializeSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitInitializeSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitInitializeSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitInitializeSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitinitializeselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProcessMultipleSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProcessMultipleSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProcessMultipleSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProcessMultipleSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProcessMultipleSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitprocessmultipleselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProcessSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProcessSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProcessSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProcessSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProcessSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitprocessselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitRange"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitRange",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitrange"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitRemovePropertyListenerSelect": {
      "abstract": [
        {
          "text": "Used by the system to unregister a property listener callback function from an audio unit when you call the ",
          "type": "text"
        },
        {
          "code": "AudioUnitRemovePropertyListener",
          "type": "codeVoice"
        },
        {
          "text": " function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitRemovePropertyListenerSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitRemovePropertyListenerSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitRemovePropertyListenerSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitRemovePropertyListenerSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitremovepropertylistenerselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitRemovePropertyListenerWithUserDataSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitRemovePropertyListenerWithUserDataSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitRemovePropertyListenerWithUserDataSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitRemovePropertyListenerWithUserDataSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitRemovePropertyListenerWithUserDataSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitremovepropertylistenerwithuserdataselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitRemoveRenderNotifySelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitRemoveRenderNotifySelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitRemoveRenderNotifySelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitRemoveRenderNotifySelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitRemoveRenderNotifySelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitremoverendernotifyselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitRenderSelect": {
      "abstract": [
        {
          "text": "Used by the system to invoke audio rendering by an audio unit when you call the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRender(_:_:_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitRenderSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitRenderSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitRenderSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitRenderSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitrenderselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitResetSelect": {
      "abstract": [
        {
          "text": "Used by the system to reset an audio unit when you call the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitReset(_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitResetSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitResetSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitResetSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitResetSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitresetselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitScheduleParametersSelect": {
      "abstract": [
        {
          "text": "Used by the system to schedule an audio unit parameter value change when you call the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitScheduleParameters(_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitScheduleParametersSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitScheduleParametersSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitScheduleParametersSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitScheduleParametersSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitscheduleparametersselect"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitAddPropertyListenerSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitAddRenderNotifySelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitComplexRenderSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitGetParameterSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitGetPropertyInfoSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitGetPropertySelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitInitializeSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProcessMultipleSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProcessSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitRange",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitRemovePropertyListenerSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitRemovePropertyListenerWithUserDataSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitRemoveRenderNotifySelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitRenderSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitResetSelect"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioUnitScheduleParametersSelect"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitScheduleParametersSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitAddPropertyListenerSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitAddRenderNotifySelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitComplexRenderSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitGetParameterSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitGetPropertyInfoSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitGetPropertySelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitInitializeSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProcessMultipleSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProcessSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitRange",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitRemovePropertyListenerSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitRemovePropertyListenerWithUserDataSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitRemoveRenderNotifySelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitRenderSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitResetSelect"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioUnitScheduleParametersSelect"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitGetPropertySelect/title",
          "value": "kAudioUnitGetPropertySelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitGetPropertySelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitGetPropertySelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitInitializeSelect/title",
          "value": "kAudioUnitInitializeSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitInitializeSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitInitializeSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitRemoveRenderNotifySelect/title",
          "value": "kAudioUnitRemoveRenderNotifySelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitRemoveRenderNotifySelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitRemoveRenderNotifySelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProcessMultipleSelect/title",
          "value": "kAudioUnitProcessMultipleSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProcessMultipleSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProcessMultipleSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitAddRenderNotifySelect/title",
          "value": "kAudioUnitAddRenderNotifySelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitAddRenderNotifySelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitAddRenderNotifySelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitAddPropertyListener(_:_:_:_:)/title",
          "value": "AudioUnitAddPropertyListener"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitAddPropertyListener(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitAddPropertyListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitReset(_:_:_:)/title",
          "value": "AudioUnitReset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitReset(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitReset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitAddPropertyListenerSelect/title",
          "value": "kAudioUnitAddPropertyListenerSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitAddPropertyListenerSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitAddPropertyListenerSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitGetPropertyInfoSelect/title",
          "value": "kAudioUnitGetPropertyInfoSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitGetPropertyInfoSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitGetPropertyInfoSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitResetSelect/title",
          "value": "kAudioUnitResetSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitResetSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitResetSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitRenderSelect/title",
          "value": "kAudioUnitRenderSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitRenderSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitRenderSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitComplexRenderSelect/title",
          "value": "kAudioUnitComplexRenderSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitComplexRenderSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitComplexRenderSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitRange/title",
          "value": "kAudioUnitRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitRender(_:_:_:_:_:_:)/title",
          "value": "AudioUnitRender"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitRender(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitRender"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitGetPropertyInfo(_:_:_:_:_:_:)/title",
          "value": "AudioUnitGetPropertyInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitGetPropertyInfo(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitGetPropertyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitScheduleParameters(_:_:_:)/title",
          "value": "AudioUnitScheduleParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitScheduleParameters(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitScheduleParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitScheduleParametersSelect/title",
          "value": "kAudioUnitScheduleParametersSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitScheduleParametersSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitScheduleParametersSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitGetParameterSelect/title",
          "value": "kAudioUnitGetParameterSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitGetParameterSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitGetParameterSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitGetParameter(_:_:_:_:_:)/title",
          "value": "AudioUnitGetParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitGetParameter(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitGetParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitRemovePropertyListenerWithUserDataSelect/title",
          "value": "kAudioUnitRemovePropertyListenerWithUserDataSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitRemovePropertyListenerWithUserDataSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitRemovePropertyListenerWithUserDataSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProcessSelect/title",
          "value": "kAudioUnitProcessSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProcessSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProcessSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitRemovePropertyListenerSelect/title",
          "value": "kAudioUnitRemovePropertyListenerSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitRemovePropertyListenerSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitRemovePropertyListenerSelect"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiounitscheduleparametersselect"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiounitscheduleparametersselect"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
