{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_StartOfTrack"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioToolboxErr_InvalidSequenceType@kAudioToolboxErr_StartOfTrack",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioToolboxErr_StartOfTrack"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioToolboxErr_StartOfTrack"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioToolboxErr_StartOfTrack"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioToolboxErr_StartOfTrack"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_CannotDoInCurrentContext": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioToolboxErr_CannotDoInCurrentContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_CannotDoInCurrentContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioToolboxErr_CannotDoInCurrentContext"
        }
      ],
      "role": "symbol",
      "title": "kAudioToolboxErr_CannotDoInCurrentContext",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiotoolboxerr_cannotdoincurrentcontext"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_EndOfTrack": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioToolboxErr_EndOfTrack"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_EndOfTrack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioToolboxErr_EndOfTrack"
        }
      ],
      "role": "symbol",
      "title": "kAudioToolboxErr_EndOfTrack",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiotoolboxerr_endoftrack"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_IllegalTrackDestination": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioToolboxErr_IllegalTrackDestination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_IllegalTrackDestination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioToolboxErr_IllegalTrackDestination"
        }
      ],
      "role": "symbol",
      "title": "kAudioToolboxErr_IllegalTrackDestination",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiotoolboxerr_illegaltrackdestination"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_InvalidEventType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioToolboxErr_InvalidEventType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_InvalidEventType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioToolboxErr_InvalidEventType"
        }
      ],
      "role": "symbol",
      "title": "kAudioToolboxErr_InvalidEventType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiotoolboxerr_invalideventtype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_InvalidPlayerState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioToolboxErr_InvalidPlayerState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_InvalidPlayerState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioToolboxErr_InvalidPlayerState"
        }
      ],
      "role": "symbol",
      "title": "kAudioToolboxErr_InvalidPlayerState",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiotoolboxerr_invalidplayerstate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_InvalidSequenceType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioToolboxErr_InvalidSequenceType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_InvalidSequenceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioToolboxErr_InvalidSequenceType"
        }
      ],
      "role": "symbol",
      "title": "kAudioToolboxErr_InvalidSequenceType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiotoolboxerr_invalidsequencetype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_NoSequence": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioToolboxErr_NoSequence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_NoSequence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioToolboxErr_NoSequence"
        }
      ],
      "role": "symbol",
      "title": "kAudioToolboxErr_NoSequence",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiotoolboxerr_nosequence"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_StartOfTrack": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioToolboxErr_StartOfTrack"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_StartOfTrack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioToolboxErr_StartOfTrack"
        }
      ],
      "role": "symbol",
      "title": "kAudioToolboxErr_StartOfTrack",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiotoolboxerr_startoftrack"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_TrackIndexError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioToolboxErr_TrackIndexError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_TrackIndexError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioToolboxErr_TrackIndexError"
        }
      ],
      "role": "symbol",
      "title": "kAudioToolboxErr_TrackIndexError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiotoolboxerr_trackindexerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_TrackNotFound": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioToolboxErr_TrackNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_TrackNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioToolboxErr_TrackNotFound"
        }
      ],
      "role": "symbol",
      "title": "kAudioToolboxErr_TrackNotFound",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiotoolboxerr_tracknotfound"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxError_NoTrackDestination": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioToolboxError_NoTrackDestination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxError_NoTrackDestination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioToolboxError_NoTrackDestination"
        }
      ],
      "role": "symbol",
      "title": "kAudioToolboxError_NoTrackDestination",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiotoolboxerror_notrackdestination"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_CannotDoInCurrentContext",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_EndOfTrack",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_IllegalTrackDestination",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_InvalidEventType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_InvalidPlayerState",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_InvalidSequenceType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_NoSequence",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_TrackIndexError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_TrackNotFound",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxError_NoTrackDestination"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioToolboxErr_StartOfTrack"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioToolboxErr_StartOfTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_CannotDoInCurrentContext",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_EndOfTrack",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_IllegalTrackDestination",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_InvalidEventType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_InvalidPlayerState",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_InvalidSequenceType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_NoSequence",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_TrackIndexError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxErr_TrackNotFound",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioToolboxError_NoTrackDestination"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioToolboxErr_StartOfTrack"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioToolboxErr_NoSequence/title",
          "value": "kAudioToolboxErr_NoSequence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioToolboxErr_NoSequence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioToolboxErr_NoSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioToolboxErr_StartOfTrack/title",
          "value": "kAudioToolboxErr_StartOfTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioToolboxErr_StartOfTrack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioToolboxErr_StartOfTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioToolboxErr_TrackNotFound/title",
          "value": "kAudioToolboxErr_TrackNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioToolboxErr_TrackNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioToolboxErr_TrackNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioToolboxErr_InvalidEventType/title",
          "value": "kAudioToolboxErr_InvalidEventType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioToolboxErr_InvalidEventType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioToolboxErr_InvalidEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioToolboxErr_IllegalTrackDestination/title",
          "value": "kAudioToolboxErr_IllegalTrackDestination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioToolboxErr_IllegalTrackDestination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioToolboxErr_IllegalTrackDestination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioToolboxErr_CannotDoInCurrentContext/title",
          "value": "kAudioToolboxErr_CannotDoInCurrentContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioToolboxErr_CannotDoInCurrentContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioToolboxErr_CannotDoInCurrentContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioToolboxErr_TrackIndexError/title",
          "value": "kAudioToolboxErr_TrackIndexError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioToolboxErr_TrackIndexError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioToolboxErr_TrackIndexError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioToolboxErr_InvalidSequenceType/title",
          "value": "kAudioToolboxErr_InvalidSequenceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioToolboxErr_InvalidSequenceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioToolboxErr_InvalidSequenceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioToolboxErr_EndOfTrack/title",
          "value": "kAudioToolboxErr_EndOfTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioToolboxErr_EndOfTrack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioToolboxErr_EndOfTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioToolboxErr_InvalidPlayerState/title",
          "value": "kAudioToolboxErr_InvalidPlayerState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioToolboxErr_InvalidPlayerState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioToolboxErr_InvalidPlayerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioToolboxError_NoTrackDestination/title",
          "value": "kAudioToolboxError_NoTrackDestination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioToolboxError_NoTrackDestination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioToolboxError_NoTrackDestination"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiotoolboxerr_startoftrack"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiotoolboxerr_startoftrack"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
