{
  "abstract": [
    {
      "text": "The audio operation failed because your application’s audio session was not active.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionNotActiveError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioSessionNoError@kAudioSessionNotActiveError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioSessionNotActiveError"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioSessionNotActiveError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioSessionNotActiveError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioSessionNotActiveError"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesNoHardwareError": {
      "abstract": [
        {
          "text": "The audio operation failed because the device has no audio input available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioServicesNoHardwareError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesNoHardwareError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioServicesNoHardwareError"
        }
      ],
      "role": "symbol",
      "title": "kAudioServicesNoHardwareError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioservicesnohardwareerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionAlreadyInitialized": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "AudioSessionInitialize",
          "type": "codeVoice"
        },
        {
          "text": " function was called more than once during the lifetime of your application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionAlreadyInitialized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionAlreadyInitialized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionAlreadyInitialized"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionAlreadyInitialized",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionalreadyinitialized"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionBadPropertySizeError": {
      "abstract": [
        {
          "text": "The size of the audio session property data was not correct.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionBadPropertySizeError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionBadPropertySizeError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionBadPropertySizeError"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionBadPropertySizeError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionbadpropertysizeerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionIncompatibleCategory": {
      "abstract": [
        {
          "text": "The specified audio session category cannot be used for the attempted audio operation. For example, you attempted to play or record audio with the audio session category set to ",
          "type": "text"
        },
        {
          "code": "kAudioSessionCategory_AudioProcessing",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionIncompatibleCategory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionIncompatibleCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionIncompatibleCategory"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionIncompatibleCategory",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionincompatiblecategory"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInitializationError": {
      "abstract": [
        {
          "text": "There was an error during audio session initialization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionInitializationError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInitializationError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionInitializationError"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionInitializationError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessioninitializationerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionNoCategorySet": {
      "abstract": [
        {
          "text": "The audio operation failed because it requires the audio session to have an explicitly-set category, but none was set. To use a hardware codec you must explicitly initialize the audio session and explicitly set an audio session category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionNoCategorySet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionNoCategorySet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionNoCategorySet"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionNoCategorySet",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionnocategoryset"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionNoError": {
      "abstract": [
        {
          "text": "No error has occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionNoError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionNoError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionNoError"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionNoError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionnoerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionNotActiveError": {
      "abstract": [
        {
          "text": "The audio operation failed because your application’s audio session was not active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionNotActiveError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionNotActiveError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionNotActiveError"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionNotActiveError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionnotactiveerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionNotInitialized": {
      "abstract": [
        {
          "text": "An Audio Session function was called without first initializing the session. To avoid this error, call the ",
          "type": "text"
        },
        {
          "code": "AudioSessionInitialize",
          "type": "codeVoice"
        },
        {
          "text": " function before attempting to use the session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionNotInitialized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionNotInitialized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionNotInitialized"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionNotInitialized",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionnotinitialized"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionUnspecifiedError": {
      "abstract": [
        {
          "text": "An unspecified audio session error has occurred. This typically results from the audio system being in an inconsistent state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionUnspecifiedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionUnspecifiedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionUnspecifiedError"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionUnspecifiedError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionunspecifiederror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionUnsupportedPropertyError": {
      "abstract": [
        {
          "text": "The audio session property is not supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionUnsupportedPropertyError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionUnsupportedPropertyError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionUnsupportedPropertyError"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionUnsupportedPropertyError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionunsupportedpropertyerror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionNoError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionNotInitialized",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionAlreadyInitialized",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInitializationError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionUnsupportedPropertyError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionBadPropertySizeError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesNoHardwareError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionNoCategorySet",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionIncompatibleCategory",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionUnspecifiedError"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioSessionNotActiveError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionNotActiveError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionNoError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionNotInitialized",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionAlreadyInitialized",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInitializationError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionUnsupportedPropertyError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionBadPropertySizeError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioServicesNoHardwareError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionNoCategorySet",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionIncompatibleCategory",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionUnspecifiedError"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioSessionNotActiveError"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionUnsupportedPropertyError/title",
          "value": "kAudioSessionUnsupportedPropertyError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionUnsupportedPropertyError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionUnsupportedPropertyError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionNoError/title",
          "value": "kAudioSessionNoError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionNoError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionNoError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionBadPropertySizeError/title",
          "value": "kAudioSessionBadPropertySizeError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionBadPropertySizeError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionBadPropertySizeError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionAlreadyInitialized/title",
          "value": "kAudioSessionAlreadyInitialized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionAlreadyInitialized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionAlreadyInitialized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionNotInitialized/title",
          "value": "kAudioSessionNotInitialized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionNotInitialized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionNotInitialized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioServicesNoHardwareError/title",
          "value": "kAudioServicesNoHardwareError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioServicesNoHardwareError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioServicesNoHardwareError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionIncompatibleCategory/title",
          "value": "kAudioSessionIncompatibleCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionIncompatibleCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionIncompatibleCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionNoCategorySet/title",
          "value": "kAudioSessionNoCategorySet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionNoCategorySet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionNoCategorySet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionInitializationError/title",
          "value": "kAudioSessionInitializationError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionInitializationError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionInitializationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionUnspecifiedError/title",
          "value": "kAudioSessionUnspecifiedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionUnspecifiedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionUnspecifiedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionNotActiveError/title",
          "value": "kAudioSessionNotActiveError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionNotActiveError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionNotActiveError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiosessionnotactiveerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiosessionnotactiveerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
