{
  "abstract": [
    {
      "text": "A ",
      "type": "text"
    },
    {
      "code": "UInt32",
      "type": "codeVoice"
    },
    {
      "text": " value indicating the ID3 tag size. The ",
      "type": "text"
    },
    {
      "code": "inSpecifier",
      "type": "codeVoice"
    },
    {
      "text": " parameter must begin with the ID3 tag header and be at least 10 bytes in length.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_ID3TagSize"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioFormatProperty_FormatInfo@kAudioFormatProperty_ID3TagSize",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioFormatProperty_ID3TagSize"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioFormatPropertyID",
        "text": "AudioFormatPropertyID"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioFormatProperty_ID3TagSize"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioFormatProperty_ID3TagSize"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioFormatProperty_ID3TagSize"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatPropertyID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioFormatPropertyID",
              "text": "AudioFormatPropertyID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatPropertyID": {
      "abstract": [
        {
          "text": "A type for four-char codes for audio format property identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFormatPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFormatPropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFormatPropertyID"
        }
      ],
      "role": "symbol",
      "title": "AudioFormatPropertyID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioformatpropertyid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_ASBDFromESDS": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "AudioStreamBasicDescription",
          "type": "codeVoice"
        },
        {
          "text": " structure for a given elementary stream descriptor (ESDS). Set the ",
          "type": "text"
        },
        {
          "code": "inSpecifier",
          "type": "codeVoice"
        },
        {
          "text": " parameter to an ESDS. If multiple formats can be described by the ESDS, this property will return the base level format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_ASBDFromESDS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatPropertyID",
          "text": "AudioFormatPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_ASBDFromESDS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_ASBDFromESDS"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatProperty_ASBDFromESDS",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioformatproperty_asbdfromesds"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_AvailableEncodeBitRates": {
      "abstract": [
        {
          "text": "An array of ",
          "type": "text"
        },
        {
          "code": "AudioValueRange",
          "type": "codeVoice"
        },
        {
          "text": " structures describing all available bit rates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_AvailableEncodeBitRates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatPropertyID",
          "text": "AudioFormatPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_AvailableEncodeBitRates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_AvailableEncodeBitRates"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatProperty_AvailableEncodeBitRates",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioformatproperty_availableencodebitrates"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_AvailableEncodeSampleRates": {
      "abstract": [
        {
          "text": "An array of ",
          "type": "text"
        },
        {
          "code": "AudioValueRange",
          "type": "codeVoice"
        },
        {
          "text": " structures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_AvailableEncodeSampleRates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatPropertyID",
          "text": "AudioFormatPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_AvailableEncodeSampleRates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_AvailableEncodeSampleRates"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatProperty_AvailableEncodeSampleRates",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioformatproperty_availableencodesamplerates"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_ChannelLayoutFromESDS": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "AudioChannelLayout",
          "type": "codeVoice"
        },
        {
          "text": " structure for a given elementary stream descriptor (ESDS).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_ChannelLayoutFromESDS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatPropertyID",
          "text": "AudioFormatPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_ChannelLayoutFromESDS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_ChannelLayoutFromESDS"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatProperty_ChannelLayoutFromESDS",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioformatproperty_channellayoutfromesds"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_DecodeFormatIDs": {
      "abstract": [
        {
          "text": "An array of ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " values representing format identifiers for formats that are valid input formats for a converter. You must set the ",
          "type": "text"
        },
        {
          "code": "inSpecifier",
          "type": "codeVoice"
        },
        {
          "text": " parameter to ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_DecodeFormatIDs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatPropertyID",
          "text": "AudioFormatPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_DecodeFormatIDs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_DecodeFormatIDs"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatProperty_DecodeFormatIDs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioformatproperty_decodeformatids"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_Decoders": {
      "abstract": [
        {
          "text": "An array of ",
          "type": "text"
        },
        {
          "code": "AudioClassDescription",
          "type": "codeVoice"
        },
        {
          "text": " structures for all installed decoders for the specified audio format. Set the ",
          "type": "text"
        },
        {
          "code": "inSpecifier",
          "type": "codeVoice"
        },
        {
          "text": " parameter to the format that you are interested in, for instance, ",
          "type": "text"
        },
        {
          "code": "'aac'",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_Decoders"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatPropertyID",
          "text": "AudioFormatPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_Decoders",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_Decoders"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatProperty_Decoders",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioformatproperty_decoders"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_EncodeFormatIDs": {
      "abstract": [
        {
          "text": "An array of ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " values representing format identifiers for formats that are valid output formats for a converter. You must set the ",
          "type": "text"
        },
        {
          "code": "inSpecifier",
          "type": "codeVoice"
        },
        {
          "text": " parameter to ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_EncodeFormatIDs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatPropertyID",
          "text": "AudioFormatPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_EncodeFormatIDs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_EncodeFormatIDs"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatProperty_EncodeFormatIDs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioformatproperty_encodeformatids"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_Encoders": {
      "abstract": [
        {
          "text": "An array of ",
          "type": "text"
        },
        {
          "code": "AudioClassDescription",
          "type": "codeVoice"
        },
        {
          "text": " structures for all installed encoders for the specified audio format. Set the ",
          "type": "text"
        },
        {
          "code": "inSpecifier",
          "type": "codeVoice"
        },
        {
          "text": " parameter to the format that you are interested in, for instance, ",
          "type": "text"
        },
        {
          "code": "'aac'",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_Encoders"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatPropertyID",
          "text": "AudioFormatPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_Encoders",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_Encoders"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatProperty_Encoders",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioformatproperty_encoders"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FirstPlayableFormatFromList": {
      "abstract": [
        {
          "text": "The index of the first ",
          "type": "text"
        },
        {
          "code": "AudioFormatListItem",
          "type": "codeVoice"
        },
        {
          "text": " that represents an audio format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_FirstPlayableFormatFromList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatPropertyID",
          "text": "AudioFormatPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FirstPlayableFormatFromList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_FirstPlayableFormatFromList"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatProperty_FirstPlayableFormatFromList",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioformatproperty_firstplayableformatfromlist"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FormatInfo": {
      "abstract": [
        {
          "text": "General information about a format. Set the ",
          "type": "text"
        },
        {
          "code": "inSpecifier",
          "type": "codeVoice"
        },
        {
          "text": " parameter to a magic cookie, or ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": ". On input, the property value is an ",
          "type": "text"
        },
        {
          "code": "AudioStreamBasicDescription",
          "type": "codeVoice"
        },
        {
          "text": " structure which should have at least the ",
          "type": "text"
        },
        {
          "code": "mFormatID",
          "type": "codeVoice"
        },
        {
          "text": " field filled out. On output, the structure will be filled out as much as possible given the information known about the format and the contents of the magic cookie (if any is given). If multiple formats can be described by the ",
          "type": "text"
        },
        {
          "code": "AudioStreamBasicDescription",
          "type": "codeVoice"
        },
        {
          "text": " and the associated magic cookie, this property will return the base level format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_FormatInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatPropertyID",
          "text": "AudioFormatPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FormatInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_FormatInfo"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatProperty_FormatInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioformatproperty_formatinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FormatIsExternallyFramed": {
      "abstract": [
        {
          "text": "Indicates whether or not a format requires external framing information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_FormatIsExternallyFramed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatPropertyID",
          "text": "AudioFormatPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FormatIsExternallyFramed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_FormatIsExternallyFramed"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatProperty_FormatIsExternallyFramed",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioformatproperty_formatisexternallyframed"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FormatIsVBR": {
      "abstract": [
        {
          "text": "Indicates whether or not a format has a variable number of bytes-per-packet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_FormatIsVBR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatPropertyID",
          "text": "AudioFormatPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FormatIsVBR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_FormatIsVBR"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatProperty_FormatIsVBR",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioformatproperty_formatisvbr"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FormatList": {
      "abstract": [
        {
          "text": "A list of structures describing the audio formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_FormatList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatPropertyID",
          "text": "AudioFormatPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FormatList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_FormatList"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatProperty_FormatList",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioformatproperty_formatlist"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FormatName": {
      "abstract": [
        {
          "text": "A name for a given format. Set the ",
          "type": "text"
        },
        {
          "code": "inSpecifier",
          "type": "codeVoice"
        },
        {
          "text": " parameter to an ",
          "type": "text"
        },
        {
          "code": "AudioStreamBasicDescription",
          "type": "codeVoice"
        },
        {
          "text": " structure describing the format to ask about. The value is a ",
          "type": "text"
        },
        {
          "code": "CFStringRef",
          "type": "codeVoice"
        },
        {
          "text": " object. The caller is responsible for releasing the returned string. For some formats, such as linear PCM, you get back a descriptive string, for example, “16-bit, interleaved.”",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_FormatName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatPropertyID",
          "text": "AudioFormatPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FormatName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_FormatName"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatProperty_FormatName",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioformatproperty_formatname"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_ID3TagSize": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value indicating the ID3 tag size. The ",
          "type": "text"
        },
        {
          "code": "inSpecifier",
          "type": "codeVoice"
        },
        {
          "text": " parameter must begin with the ID3 tag header and be at least 10 bytes in length.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_ID3TagSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatPropertyID",
          "text": "AudioFormatPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_ID3TagSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_ID3TagSize"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatProperty_ID3TagSize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioformatproperty_id3tagsize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_OutputFormatList": {
      "abstract": [
        {
          "text": "A list of structures describing the audio formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_OutputFormatList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatPropertyID",
          "text": "AudioFormatPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_OutputFormatList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_OutputFormatList"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatProperty_OutputFormatList",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioformatproperty_outputformatlist"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FormatInfo",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FormatName",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_EncodeFormatIDs",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_DecodeFormatIDs",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FormatList",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_ASBDFromESDS",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_ChannelLayoutFromESDS",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_OutputFormatList",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FirstPlayableFormatFromList",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_Encoders",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_Decoders",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FormatIsVBR",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FormatIsExternallyFramed",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_AvailableEncodeBitRates",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_AvailableEncodeSampleRates"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioFormatProperty_ID3TagSize"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatProperty_ID3TagSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FormatInfo",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FormatName",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_EncodeFormatIDs",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_DecodeFormatIDs",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FormatList",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_ASBDFromESDS",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_ChannelLayoutFromESDS",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_OutputFormatList",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FirstPlayableFormatFromList",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_Encoders",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_Decoders",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FormatIsVBR",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_FormatIsExternallyFramed",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_AvailableEncodeBitRates",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFormatProperty_AvailableEncodeSampleRates"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioFormatProperty_ID3TagSize"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatPropertyID/title",
          "value": "AudioFormatPropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatPropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFormatPropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_FormatIsExternallyFramed/title",
          "value": "kAudioFormatProperty_FormatIsExternallyFramed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_FormatIsExternallyFramed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatProperty_FormatIsExternallyFramed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_FormatName/title",
          "value": "kAudioFormatProperty_FormatName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_FormatName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatProperty_FormatName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_ASBDFromESDS/title",
          "value": "kAudioFormatProperty_ASBDFromESDS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_ASBDFromESDS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatProperty_ASBDFromESDS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_AvailableEncodeSampleRates/title",
          "value": "kAudioFormatProperty_AvailableEncodeSampleRates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_AvailableEncodeSampleRates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatProperty_AvailableEncodeSampleRates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_ID3TagSize/title",
          "value": "kAudioFormatProperty_ID3TagSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_ID3TagSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatProperty_ID3TagSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_FirstPlayableFormatFromList/title",
          "value": "kAudioFormatProperty_FirstPlayableFormatFromList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_FirstPlayableFormatFromList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatProperty_FirstPlayableFormatFromList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_FormatInfo/title",
          "value": "kAudioFormatProperty_FormatInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_FormatInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatProperty_FormatInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_FormatList/title",
          "value": "kAudioFormatProperty_FormatList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_FormatList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatProperty_FormatList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_AvailableEncodeBitRates/title",
          "value": "kAudioFormatProperty_AvailableEncodeBitRates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_AvailableEncodeBitRates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatProperty_AvailableEncodeBitRates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_EncodeFormatIDs/title",
          "value": "kAudioFormatProperty_EncodeFormatIDs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_EncodeFormatIDs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatProperty_EncodeFormatIDs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_FormatIsVBR/title",
          "value": "kAudioFormatProperty_FormatIsVBR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_FormatIsVBR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatProperty_FormatIsVBR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_OutputFormatList/title",
          "value": "kAudioFormatProperty_OutputFormatList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_OutputFormatList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatProperty_OutputFormatList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_Decoders/title",
          "value": "kAudioFormatProperty_Decoders"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_Decoders/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatProperty_Decoders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_DecodeFormatIDs/title",
          "value": "kAudioFormatProperty_DecodeFormatIDs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_DecodeFormatIDs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatProperty_DecodeFormatIDs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_ChannelLayoutFromESDS/title",
          "value": "kAudioFormatProperty_ChannelLayoutFromESDS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_ChannelLayoutFromESDS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatProperty_ChannelLayoutFromESDS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_Encoders/title",
          "value": "kAudioFormatProperty_Encoders"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFormatProperty_Encoders/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatProperty_Encoders"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaudioformatproperty_id3tagsize"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaudioformatproperty_id3tagsize"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
