{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableOutputSampleRates"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioCodecPropertySupportedInputFormats@kAudioCodecPropertyAvailableOutputSampleRates",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioCodecPropertyAvailableOutputSampleRates"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioCodecPropertyID",
        "text": "AudioCodecPropertyID"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioCodecPropertyAvailableOutputSampleRates"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioCodecPropertyAvailableOutputSampleRates"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyAvailableOutputSampleRates"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecPropertyID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioCodecPropertyID",
              "text": "AudioCodecPropertyID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecPropertyID": {
      "abstract": [
        {
          "text": "An integer identifying an audio codec property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecPropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioCodecPropertyID"
        }
      ],
      "role": "symbol",
      "title": "AudioCodecPropertyID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocodecpropertyid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableBitRateRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableBitRateRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableBitRateRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableBitRateRange"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyAvailableBitRateRange",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyavailablebitraterange"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableInputChannelLayoutTags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableInputChannelLayoutTags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableInputChannelLayoutTags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableInputChannelLayoutTags"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyAvailableInputChannelLayoutTags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyavailableinputchannellayouttags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableInputSampleRates": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableInputSampleRates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableInputSampleRates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableInputSampleRates"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyAvailableInputSampleRates",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyavailableinputsamplerates"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableNumberChannels": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableNumberChannels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableNumberChannels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableNumberChannels"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyAvailableNumberChannels",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyavailablenumberchannels"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableOutputChannelLayoutTags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableOutputChannelLayoutTags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableOutputChannelLayoutTags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableOutputChannelLayoutTags"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyAvailableOutputChannelLayoutTags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyavailableoutputchannellayouttags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableOutputSampleRates": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableOutputSampleRates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableOutputSampleRates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableOutputSampleRates"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyAvailableOutputSampleRates",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyavailableoutputsamplerates"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyDoesSampleRateConversion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyDoesSampleRateConversion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyDoesSampleRateConversion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyDoesSampleRateConversion"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyDoesSampleRateConversion",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertydoessamplerateconversion"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyFormatInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyFormatInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyFormatInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyFormatInfo"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyFormatInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyformatinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyInputFormatsForOutputFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyInputFormatsForOutputFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyInputFormatsForOutputFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyInputFormatsForOutputFormat"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyInputFormatsForOutputFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyinputformatsforoutputformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyMinimumNumberInputPackets": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyMinimumNumberInputPackets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyMinimumNumberInputPackets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyMinimumNumberInputPackets"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyMinimumNumberInputPackets",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyminimumnumberinputpackets"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyMinimumNumberOutputPackets": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyMinimumNumberOutputPackets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyMinimumNumberOutputPackets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyMinimumNumberOutputPackets"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyMinimumNumberOutputPackets",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyminimumnumberoutputpackets"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyOutputFormatsForInputFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyOutputFormatsForInputFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyOutputFormatsForInputFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyOutputFormatsForInputFormat"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyOutputFormatsForInputFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyoutputformatsforinputformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertySupportedInputFormats": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertySupportedInputFormats"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertySupportedInputFormats",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertySupportedInputFormats"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertySupportedInputFormats",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertysupportedinputformats"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertySupportedOutputFormats": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertySupportedOutputFormats"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertySupportedOutputFormats",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertySupportedOutputFormats"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertySupportedOutputFormats",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertysupportedoutputformats"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableBitRateRange",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableInputChannelLayoutTags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableInputSampleRates",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableNumberChannels",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableOutputChannelLayoutTags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyDoesSampleRateConversion",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyFormatInfo",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyInputFormatsForOutputFormat",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyMinimumNumberInputPackets",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyMinimumNumberOutputPackets",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyOutputFormatsForInputFormat",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertySupportedInputFormats",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertySupportedOutputFormats"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioCodecPropertyAvailableOutputSampleRates"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyAvailableOutputSampleRates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableBitRateRange",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableInputChannelLayoutTags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableInputSampleRates",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableNumberChannels",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableOutputChannelLayoutTags",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyDoesSampleRateConversion",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyFormatInfo",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyInputFormatsForOutputFormat",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyMinimumNumberInputPackets",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyMinimumNumberOutputPackets",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyOutputFormatsForInputFormat",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertySupportedInputFormats",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertySupportedOutputFormats"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioCodecPropertyAvailableOutputSampleRates"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableInputChannelLayoutTags/title",
          "value": "kAudioCodecPropertyAvailableInputChannelLayoutTags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableInputChannelLayoutTags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyAvailableInputChannelLayoutTags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyFormatInfo/title",
          "value": "kAudioCodecPropertyFormatInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyFormatInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyFormatInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableNumberChannels/title",
          "value": "kAudioCodecPropertyAvailableNumberChannels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableNumberChannels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyAvailableNumberChannels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableOutputChannelLayoutTags/title",
          "value": "kAudioCodecPropertyAvailableOutputChannelLayoutTags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableOutputChannelLayoutTags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyAvailableOutputChannelLayoutTags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableBitRateRange/title",
          "value": "kAudioCodecPropertyAvailableBitRateRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableBitRateRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyAvailableBitRateRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertySupportedInputFormats/title",
          "value": "kAudioCodecPropertySupportedInputFormats"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertySupportedInputFormats/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertySupportedInputFormats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyInputFormatsForOutputFormat/title",
          "value": "kAudioCodecPropertyInputFormatsForOutputFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyInputFormatsForOutputFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyInputFormatsForOutputFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyOutputFormatsForInputFormat/title",
          "value": "kAudioCodecPropertyOutputFormatsForInputFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyOutputFormatsForInputFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyOutputFormatsForInputFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyMinimumNumberOutputPackets/title",
          "value": "kAudioCodecPropertyMinimumNumberOutputPackets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyMinimumNumberOutputPackets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyMinimumNumberOutputPackets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertySupportedOutputFormats/title",
          "value": "kAudioCodecPropertySupportedOutputFormats"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertySupportedOutputFormats/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertySupportedOutputFormats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyMinimumNumberInputPackets/title",
          "value": "kAudioCodecPropertyMinimumNumberInputPackets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyMinimumNumberInputPackets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyMinimumNumberInputPackets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecPropertyID/title",
          "value": "AudioCodecPropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecPropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecPropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableInputSampleRates/title",
          "value": "kAudioCodecPropertyAvailableInputSampleRates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableInputSampleRates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyAvailableInputSampleRates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableOutputSampleRates/title",
          "value": "kAudioCodecPropertyAvailableOutputSampleRates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableOutputSampleRates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyAvailableOutputSampleRates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyDoesSampleRateConversion/title",
          "value": "kAudioCodecPropertyDoesSampleRateConversion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyDoesSampleRateConversion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyDoesSampleRateConversion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiocodecpropertyavailableoutputsamplerates"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiocodecpropertyavailableoutputsamplerates"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
