{
  "abstract": [
    {
      "text": "A ",
      "type": "text"
    },
    {
      "code": "Float32",
      "type": "codeVoice"
    },
    {
      "text": " value that represents the value of the volume control.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMasterVolume"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioHardwareServiceProperty_ServiceRestarted@kAudioHardwareServiceDeviceProperty_VirtualMasterVolume",
    "fragments": [
      {
        "kind": "identifier",
        "text": "kAudioHardwareServiceDeviceProperty_VirtualMasterVolume"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioHardwareServiceDeviceProperty_VirtualMasterVolume"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.5",
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "kAudioHardwareServiceDeviceProperty_VirtualMasterVolume"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "kAudioHardwareServiceDeviceProperty_VirtualMasterVolume"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The range for this property’s value is ",
              "type": "text"
            },
            {
              "code": "0.0",
              "type": "codeVoice"
            },
            {
              "text": " (silence) through ",
              "type": "text"
            },
            {
              "code": "1.0",
              "type": "codeVoice"
            },
            {
              "text": " (full level). The effect of this property depends on the hardware device associated with the HAL audio object. If the device has a primary volume control, this property controls it. If the device has individual channel volume controls, this property applies to those identified by the device’s preferred multichannel layout, or the preferred stereo pair if the device is stereo only. This control maintains relative balance between the channels it affects.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMainBalance": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwareServiceDeviceProperty_VirtualMainBalance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMainBalance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwareServiceDeviceProperty_VirtualMainBalance"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwareServiceDeviceProperty_VirtualMainBalance",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiohardwareservicedeviceproperty_virtualmainbalance"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMainVolume": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwareServiceDeviceProperty_VirtualMainVolume"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMainVolume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwareServiceDeviceProperty_VirtualMainVolume"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwareServiceDeviceProperty_VirtualMainVolume",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiohardwareservicedeviceproperty_virtualmainvolume"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMasterBalance": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "Float32",
          "type": "codeVoice"
        },
        {
          "text": " value that represents the value of a hardware device’s stereo balance control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kAudioHardwareServiceDeviceProperty_VirtualMasterBalance"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMasterBalance",
      "kind": "symbol",
      "role": "symbol",
      "title": "kAudioHardwareServiceDeviceProperty_VirtualMasterBalance",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiohardwareservicedeviceproperty_virtualmasterbalance"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMasterVolume": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "Float32",
          "type": "codeVoice"
        },
        {
          "text": " value that represents the value of the volume control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kAudioHardwareServiceDeviceProperty_VirtualMasterVolume"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMasterVolume",
      "kind": "symbol",
      "role": "symbol",
      "title": "kAudioHardwareServiceDeviceProperty_VirtualMasterVolume",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiohardwareservicedeviceproperty_virtualmastervolume"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceProperty_ServiceRestarted": {
      "abstract": [
        {
          "text": "Used, with a HAL audio object property listener callback, as a flag that indicates a hardware service restart. The property’s ",
          "type": "text"
        },
        {
          "code": "Float32",
          "type": "codeVoice"
        },
        {
          "text": " value has no meaning. When the hardware service restarts, any associated application state, such as cached data or property listener callbacks, must be re-established.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwareServiceProperty_ServiceRestarted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceProperty_ServiceRestarted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwareServiceProperty_ServiceRestarted"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwareServiceProperty_ServiceRestarted",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiohardwareserviceproperty_servicerestarted"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceProperty_ServiceRestarted",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMasterBalance",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMainBalance",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMainVolume"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioHardwareServiceDeviceProperty_VirtualMainBalance/title",
          "value": "kAudioHardwareServiceDeviceProperty_VirtualMainBalance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioHardwareServiceDeviceProperty_VirtualMainBalance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwareServiceDeviceProperty_VirtualMainBalance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioHardwareServiceDeviceProperty_VirtualMainVolume/title",
          "value": "kAudioHardwareServiceDeviceProperty_VirtualMainVolume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioHardwareServiceDeviceProperty_VirtualMainVolume/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwareServiceDeviceProperty_VirtualMainVolume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioHardwareServiceProperty_ServiceRestarted/title",
          "value": "kAudioHardwareServiceProperty_ServiceRestarted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioHardwareServiceProperty_ServiceRestarted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwareServiceProperty_ServiceRestarted"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiohardwareservicedeviceproperty_virtualmastervolume"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
