{
  "abstract": [
    {
      "text": "An array of all audio file type IDs that support a specified ",
      "type": "text"
    },
    {
      "code": "HFSTypeCode",
      "type": "codeVoice"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_TypesForHFSTypeCode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioFileGlobalInfo_ReadableTypes@kAudioFileGlobalInfo_TypesForHFSTypeCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioFileGlobalInfo_TypesForHFSTypeCode"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioFilePropertyID",
        "text": "AudioFilePropertyID"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioFileGlobalInfo_TypesForHFSTypeCode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioFileGlobalInfo_TypesForHFSTypeCode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioFileGlobalInfo_TypesForHFSTypeCode"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFilePropertyID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioFilePropertyID",
              "text": "AudioFilePropertyID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When accessing this property, provide a pointer, in the ",
              "type": "text"
            },
            {
              "code": "inSpecifier",
              "type": "codeVoice"
            },
            {
              "text": " parameter, to an ",
              "type": "text"
            },
            {
              "code": "HFSTypeCode",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFilePropertyID": {
      "abstract": [
        {
          "text": "An audio file property identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFilePropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFilePropertyID"
        }
      ],
      "role": "symbol",
      "title": "AudioFilePropertyID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilepropertyid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_AllExtensions": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "CFArray",
          "type": "codeVoice"
        },
        {
          "text": " of ",
          "type": "text"
        },
        {
          "code": "CFStrings",
          "type": "codeVoice"
        },
        {
          "text": " containing all recognized file extensions. You can use this array when creating an ",
          "type": "text"
        },
        {
          "code": "NSOpenPanel",
          "type": "codeVoice"
        },
        {
          "text": " (declared in the AppKit’s ",
          "type": "text"
        },
        {
          "code": "NSOpenPanel.h",
          "type": "codeVoice"
        },
        {
          "text": " header file).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_AllExtensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_AllExtensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_AllExtensions"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGlobalInfo_AllExtensions",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileglobalinfo_allextensions"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_AllHFSTypeCodes": {
      "abstract": [
        {
          "text": "An array of HFS type codes containing all recognized HFS type codes. For more information on HFS type codes, see Audio Toolbox’s ",
          "type": "text"
        },
        {
          "code": "ExtendedAudioFile.h",
          "type": "codeVoice"
        },
        {
          "text": " header file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_AllHFSTypeCodes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_AllHFSTypeCodes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_AllHFSTypeCodes"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGlobalInfo_AllHFSTypeCodes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileglobalinfo_allhfstypecodes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_AllMIMETypes": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "CFArray",
          "type": "codeVoice"
        },
        {
          "text": " of CF strings of all MIME types are recognized by Audio File Services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_AllMIMETypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_AllMIMETypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_AllMIMETypes"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGlobalInfo_AllMIMETypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileglobalinfo_allmimetypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_AllUTIs": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "CFArray",
          "type": "codeVoice"
        },
        {
          "text": " of ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": " of all UTIs (Universal Type Identifiers) recognized by Audio File Services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_AllUTIs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_AllUTIs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_AllUTIs"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGlobalInfo_AllUTIs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileglobalinfo_allutis"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_AvailableFormatIDs": {
      "abstract": [
        {
          "text": "An array of format IDs for formats that can be read.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_AvailableFormatIDs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_AvailableFormatIDs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_AvailableFormatIDs"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGlobalInfo_AvailableFormatIDs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileglobalinfo_availableformatids"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_AvailableStreamDescriptionsForFormat": {
      "abstract": [
        {
          "text": "An array of audio stream basic description structures, which contain all the formats for a particular file type and format ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_AvailableStreamDescriptionsForFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_AvailableStreamDescriptionsForFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_AvailableStreamDescriptionsForFormat"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGlobalInfo_AvailableStreamDescriptionsForFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileglobalinfo_availablestreamdescriptionsforformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_ExtensionsForType": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "CFArray",
          "type": "codeVoice"
        },
        {
          "text": " of CF strings containing the recognized file extensions for a specified type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_ExtensionsForType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_ExtensionsForType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_ExtensionsForType"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGlobalInfo_ExtensionsForType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileglobalinfo_extensionsfortype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_FileTypeName": {
      "abstract": [
        {
          "text": "The name for the file type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_FileTypeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_FileTypeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_FileTypeName"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGlobalInfo_FileTypeName",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileglobalinfo_filetypename"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_HFSTypeCodesForType": {
      "abstract": [
        {
          "text": "An array of HFS type codes corresponding to a specified file type. The first type in the array is the preferred one to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_HFSTypeCodesForType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_HFSTypeCodesForType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_HFSTypeCodesForType"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGlobalInfo_HFSTypeCodesForType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileglobalinfo_hfstypecodesfortype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_MIMETypesForType": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "CFArray",
          "type": "codeVoice"
        },
        {
          "text": " of ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": " of all MIME types recognized by a specified file type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_MIMETypesForType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_MIMETypesForType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_MIMETypesForType"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGlobalInfo_MIMETypesForType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileglobalinfo_mimetypesfortype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_ReadableTypes": {
      "abstract": [
        {
          "text": "An array of ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " values containing the file types (such as AIFF, WAVE, and so forth) that can be opened for reading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_ReadableTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_ReadableTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_ReadableTypes"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGlobalInfo_ReadableTypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileglobalinfo_readabletypes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_TypesForExtension": {
      "abstract": [
        {
          "text": "An array of all audio file type IDs that support a specified filename extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_TypesForExtension"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_TypesForExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_TypesForExtension"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGlobalInfo_TypesForExtension",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileglobalinfo_typesforextension"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_TypesForHFSTypeCode": {
      "abstract": [
        {
          "text": "An array of all audio file type IDs that support a specified ",
          "type": "text"
        },
        {
          "code": "HFSTypeCode",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_TypesForHFSTypeCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_TypesForHFSTypeCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_TypesForHFSTypeCode"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGlobalInfo_TypesForHFSTypeCode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileglobalinfo_typesforhfstypecode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_TypesForUTI": {
      "abstract": [
        {
          "text": "An array of all audio file type IDs that support a specified UTI.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_TypesForUTI"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_TypesForUTI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_TypesForUTI"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGlobalInfo_TypesForUTI",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileglobalinfo_typesforuti"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_UTIsForType": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "CFArray",
          "type": "codeVoice"
        },
        {
          "text": " of ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": " of all Universal Type Identifiers recognized by a specified file type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_UTIsForType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_UTIsForType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_UTIsForType"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGlobalInfo_UTIsForType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileglobalinfo_utisfortype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_WritableTypes": {
      "abstract": [
        {
          "text": "An array of ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " values containing the file types (such as AIFF, WAVE, and so forth) that can be opened for writing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_WritableTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_WritableTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileGlobalInfo_WritableTypes"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileGlobalInfo_WritableTypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileglobalinfo_writabletypes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_ReadableTypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_WritableTypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_FileTypeName",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_AvailableFormatIDs",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_AvailableStreamDescriptionsForFormat",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_AllExtensions",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_AllHFSTypeCodes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_AllUTIs",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_AllMIMETypes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_ExtensionsForType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_HFSTypeCodesForType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_UTIsForType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_MIMETypesForType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_TypesForExtension",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_TypesForUTI"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioFileGlobalInfo_TypesForHFSTypeCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGlobalInfo_TypesForHFSTypeCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_ReadableTypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_WritableTypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_FileTypeName",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_AvailableFormatIDs",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_AvailableStreamDescriptionsForFormat",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_AllExtensions",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_AllHFSTypeCodes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_AllUTIs",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_AllMIMETypes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_ExtensionsForType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_HFSTypeCodesForType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_UTIsForType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_MIMETypesForType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_TypesForExtension",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileGlobalInfo_TypesForUTI"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioFileGlobalInfo_TypesForHFSTypeCode"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_AllExtensions/title",
          "value": "kAudioFileGlobalInfo_AllExtensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_AllExtensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGlobalInfo_AllExtensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_ExtensionsForType/title",
          "value": "kAudioFileGlobalInfo_ExtensionsForType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_ExtensionsForType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGlobalInfo_ExtensionsForType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_AvailableFormatIDs/title",
          "value": "kAudioFileGlobalInfo_AvailableFormatIDs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_AvailableFormatIDs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGlobalInfo_AvailableFormatIDs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_FileTypeName/title",
          "value": "kAudioFileGlobalInfo_FileTypeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_FileTypeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGlobalInfo_FileTypeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_MIMETypesForType/title",
          "value": "kAudioFileGlobalInfo_MIMETypesForType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_MIMETypesForType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGlobalInfo_MIMETypesForType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_TypesForExtension/title",
          "value": "kAudioFileGlobalInfo_TypesForExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_TypesForExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGlobalInfo_TypesForExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_AvailableStreamDescriptionsForFormat/title",
          "value": "kAudioFileGlobalInfo_AvailableStreamDescriptionsForFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_AvailableStreamDescriptionsForFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGlobalInfo_AvailableStreamDescriptionsForFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_ReadableTypes/title",
          "value": "kAudioFileGlobalInfo_ReadableTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_ReadableTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGlobalInfo_ReadableTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_HFSTypeCodesForType/title",
          "value": "kAudioFileGlobalInfo_HFSTypeCodesForType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_HFSTypeCodesForType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGlobalInfo_HFSTypeCodesForType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_AllUTIs/title",
          "value": "kAudioFileGlobalInfo_AllUTIs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_AllUTIs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGlobalInfo_AllUTIs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFilePropertyID/title",
          "value": "AudioFilePropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFilePropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFilePropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFilePropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFilePropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_AllMIMETypes/title",
          "value": "kAudioFileGlobalInfo_AllMIMETypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_AllMIMETypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGlobalInfo_AllMIMETypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_TypesForUTI/title",
          "value": "kAudioFileGlobalInfo_TypesForUTI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_TypesForUTI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGlobalInfo_TypesForUTI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_AllHFSTypeCodes/title",
          "value": "kAudioFileGlobalInfo_AllHFSTypeCodes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_AllHFSTypeCodes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGlobalInfo_AllHFSTypeCodes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_TypesForHFSTypeCode/title",
          "value": "kAudioFileGlobalInfo_TypesForHFSTypeCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_TypesForHFSTypeCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGlobalInfo_TypesForHFSTypeCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_WritableTypes/title",
          "value": "kAudioFileGlobalInfo_WritableTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_WritableTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGlobalInfo_WritableTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_UTIsForType/title",
          "value": "kAudioFileGlobalInfo_UTIsForType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileGlobalInfo_UTIsForType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileGlobalInfo_UTIsForType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiofileglobalinfo_typesforhfstypecode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiofileglobalinfo_typesforhfstypecode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
