{
  "abstract": [
    {
      "text": "The priming method, usually for sample-rate conversion.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPrimeMethod"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioConverterPropertyMinimumInputBufferSize@kAudioConverterPrimeMethod",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioConverterPrimeMethod"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioConverterPropertyID",
        "text": "AudioConverterPropertyID"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioConverterPrimeMethod"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioConverterPrimeMethod"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioConverterPrimeMethod"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterPropertyID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioConverterPropertyID",
              "text": "AudioConverterPropertyID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterPrimeInfo",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559927-converter-priming-constants",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559927-converter-priming-constants": {
      "abstract": [
        {
          "text": "Constants used with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPrimeMethod",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1559927-converter-priming-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Converter Priming Constants",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1559927-converter-priming-constants"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterConvertBuffer(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Converts audio data from one linear PCM format to another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioConverterConvertBuffer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterRef",
          "text": "AudioConverterRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterConvertBuffer(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioConverterConvertBuffer"
        }
      ],
      "role": "symbol",
      "title": "AudioConverterConvertBuffer(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioconverterconvertbuffer(_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterPrimeInfo": {
      "abstract": [
        {
          "text": "Specifies priming information for an audio converter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioConverterPrimeInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterPrimeInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioConverterPrimeInfo"
        }
      ],
      "role": "symbol",
      "title": "AudioConverterPrimeInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioconverterprimeinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterPropertyID": {
      "abstract": [
        {
          "text": "An audio converter property identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterPropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioConverterPropertyID"
        }
      ],
      "role": "symbol",
      "title": "AudioConverterPropertyID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioconverterpropertyid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterCodecQuality": {
      "abstract": [
        {
          "text": "The rendering quality of a codec. A ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterCodecQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterCodecQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterCodecQuality"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterCodecQuality",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconvertercodecquality"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPrimeInfo": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterPrimeInfo",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterPrimeInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPrimeInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterPrimeInfo"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterPrimeInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterprimeinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPrimeMethod": {
      "abstract": [
        {
          "text": "The priming method, usually for sample-rate conversion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterPrimeMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPrimeMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterPrimeMethod"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterPrimeMethod",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterprimemethod"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyCalculateInputBufferSize": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value that on input holds a size, in bytes, that is desired for the output data. On output, it holds the size, in bytes, of the input buffer required to generate that much output data. Note that some converters cannot do this calculation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyCalculateInputBufferSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyCalculateInputBufferSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyCalculateInputBufferSize"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterPropertyCalculateInputBufferSize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterpropertycalculateinputbuffersize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyCalculateOutputBufferSize": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value that on input holds a size, in bytes, that is desired for the input data. On output, it holds the size, in bytes, of the output buffer required to hold the output data to be generated. Some converters cannot do this calculation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyCalculateOutputBufferSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyCalculateOutputBufferSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyCalculateOutputBufferSize"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterPropertyCalculateOutputBufferSize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterpropertycalculateoutputbuffersize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyInputCodecParameters": {
      "abstract": [
        {
          "text": "The value of this property varies from format to format and is considered private to the format. It is treated as a buffer of untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyInputCodecParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyInputCodecParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyInputCodecParameters"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterPropertyInputCodecParameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterpropertyinputcodecparameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMaximumInputBufferSize": {
      "abstract": [
        {
          "text": "Deprecated. The audio converter input callback may be passed any number of packets of data. If fewer are packets are returned than required, then the input proc is called again. If more packets are passed than required, they remain in the client’s buffer and are consumed as needed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyMaximumInputBufferSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMaximumInputBufferSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyMaximumInputBufferSize"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterPropertyMaximumInputBufferSize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterpropertymaximuminputbuffersize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMaximumInputPacketSize": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value that indicates the size, in bytes, of the largest single packet of data in the input format. This is mostly useful for variable bit rate compressed data (decoders).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyMaximumInputPacketSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMaximumInputPacketSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyMaximumInputPacketSize"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterPropertyMaximumInputPacketSize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterpropertymaximuminputpacketsize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMaximumOutputPacketSize": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value that indicates the size, in bytes, of the largest single packet of data in the output format. This is mostly useful for variable bit rate compressed data (encoders).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyMaximumOutputPacketSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMaximumOutputPacketSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyMaximumOutputPacketSize"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterPropertyMaximumOutputPacketSize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterpropertymaximumoutputpacketsize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMinimumInputBufferSize": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value that indicates the size, in bytes, of the smallest buffer of input data that can be supplied via the audio converter input callback or as the input to the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioConverterConvertBuffer(_:_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyMinimumInputBufferSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMinimumInputBufferSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyMinimumInputBufferSize"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterPropertyMinimumInputBufferSize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterpropertyminimuminputbuffersize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMinimumOutputBufferSize": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value that indicates the size, in bytes, of the smallest buffer of output data that can be supplied to AudioConverterFillComplexBuffer or as the output to AudioConverterConvertBuffer",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyMinimumOutputBufferSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMinimumOutputBufferSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyMinimumOutputBufferSize"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterPropertyMinimumOutputBufferSize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterpropertyminimumoutputbuffersize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyOutputCodecParameters": {
      "abstract": [
        {
          "text": "The value of this property varies from format to format and is considered private to the format. It is treated as a buffer of untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyOutputCodecParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyOutputCodecParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterPropertyOutputCodecParameters"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterPropertyOutputCodecParameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconverterpropertyoutputcodecparameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterAlgorithm": {
      "abstract": [
        {
          "text": "A value that indicates the sample rate conversion algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterSampleRateConverterAlgorithm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterAlgorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterSampleRateConverterAlgorithm"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterSampleRateConverterAlgorithm",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconvertersamplerateconverteralgorithm"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterComplexity": {
      "abstract": [
        {
          "text": "The sample rate conversion algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterSampleRateConverterComplexity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterComplexity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterSampleRateConverterComplexity"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterSampleRateConverterComplexity",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconvertersamplerateconvertercomplexity"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterInitialPhase": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "Float64",
          "type": "codeVoice"
        },
        {
          "text": " value equal to ",
          "type": "text"
        },
        {
          "code": "0.0",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterSampleRateConverterInitialPhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterInitialPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterSampleRateConverterInitialPhase"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterSampleRateConverterInitialPhase",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconvertersamplerateconverterinitialphase"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterQuality": {
      "abstract": [
        {
          "text": "The rendering quality of the sample rate converter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioConverterSampleRateConverterQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioConverterPropertyID",
          "text": "AudioConverterPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioConverterSampleRateConverterQuality"
        }
      ],
      "role": "symbol",
      "title": "kAudioConverterSampleRateConverterQuality",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioconvertersamplerateconverterquality"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMinimumInputBufferSize",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMinimumOutputBufferSize",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMaximumInputBufferSize",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMaximumInputPacketSize",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMaximumOutputPacketSize",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyCalculateInputBufferSize",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyCalculateOutputBufferSize",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyInputCodecParameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyOutputCodecParameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterAlgorithm",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterComplexity",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterQuality",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterInitialPhase",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterCodecQuality",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPrimeInfo"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioConverterPrimeMethod"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterPrimeMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMinimumInputBufferSize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMinimumOutputBufferSize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMaximumInputBufferSize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMaximumInputPacketSize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyMaximumOutputPacketSize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyCalculateInputBufferSize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyCalculateOutputBufferSize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyInputCodecParameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPropertyOutputCodecParameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterAlgorithm",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterComplexity",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterQuality",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterSampleRateConverterInitialPhase",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterCodecQuality",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioConverterPrimeInfo"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioConverterPrimeMethod"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyInputCodecParameters/title",
          "value": "kAudioConverterPropertyInputCodecParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyInputCodecParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterPropertyInputCodecParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyCalculateOutputBufferSize/title",
          "value": "kAudioConverterPropertyCalculateOutputBufferSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyCalculateOutputBufferSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterPropertyCalculateOutputBufferSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyMinimumInputBufferSize/title",
          "value": "kAudioConverterPropertyMinimumInputBufferSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyMinimumInputBufferSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterPropertyMinimumInputBufferSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterPrimeInfo/title",
          "value": "AudioConverterPrimeInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterPrimeInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioConverterPrimeInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterPrimeInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioConverterPrimeInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterSampleRateConverterQuality/title",
          "value": "kAudioConverterSampleRateConverterQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterSampleRateConverterQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterSampleRateConverterQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyOutputCodecParameters/title",
          "value": "kAudioConverterPropertyOutputCodecParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyOutputCodecParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterPropertyOutputCodecParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyCalculateInputBufferSize/title",
          "value": "kAudioConverterPropertyCalculateInputBufferSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyCalculateInputBufferSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterPropertyCalculateInputBufferSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPrimeInfo/title",
          "value": "kAudioConverterPrimeInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPrimeInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterPrimeInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyMaximumInputPacketSize/title",
          "value": "kAudioConverterPropertyMaximumInputPacketSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyMaximumInputPacketSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterPropertyMaximumInputPacketSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPrimeMethod/title",
          "value": "kAudioConverterPrimeMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPrimeMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterPrimeMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyMaximumOutputPacketSize/title",
          "value": "kAudioConverterPropertyMaximumOutputPacketSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyMaximumOutputPacketSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterPropertyMaximumOutputPacketSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterSampleRateConverterComplexity/title",
          "value": "kAudioConverterSampleRateConverterComplexity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterSampleRateConverterComplexity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterSampleRateConverterComplexity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterSampleRateConverterInitialPhase/title",
          "value": "kAudioConverterSampleRateConverterInitialPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterSampleRateConverterInitialPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterSampleRateConverterInitialPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyMaximumInputBufferSize/title",
          "value": "kAudioConverterPropertyMaximumInputBufferSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyMaximumInputBufferSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterPropertyMaximumInputBufferSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterSampleRateConverterAlgorithm/title",
          "value": "kAudioConverterSampleRateConverterAlgorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterSampleRateConverterAlgorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterSampleRateConverterAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterCodecQuality/title",
          "value": "kAudioConverterCodecQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterCodecQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterCodecQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterConvertBuffer(_:_:_:_:_:)/title",
          "value": "AudioConverterConvertBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterConvertBuffer(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioConverterConvertBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterPropertyID/title",
          "value": "AudioConverterPropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterPropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioConverterPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioConverterPropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioConverterPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyMinimumOutputBufferSize/title",
          "value": "kAudioConverterPropertyMinimumOutputBufferSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioConverterPropertyMinimumOutputBufferSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioConverterPropertyMinimumOutputBufferSize"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaudioconverterprimemethod"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaudioconverterprimemethod"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
