{
  "abstract": [
    {
      "text": "Indicates the current hardware output latency, in seconds, as a read-only ",
      "type": "text"
    },
    {
      "code": "Float32",
      "type": "codeVoice"
    },
    {
      "text": " value.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareOutputLatency"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioSessionProperty_PreferredHardwareSampleRate@kAudioSessionProperty_CurrentHardwareOutputLatency",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioSessionProperty_CurrentHardwareOutputLatency"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioSessionProperty_CurrentHardwareOutputLatency"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioSessionProperty_CurrentHardwareOutputLatency"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_CurrentHardwareOutputLatency"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionAddPropertyListener(_:_:_:)": {
      "abstract": [
        {
          "text": "Adds a property listener callback function to your application’s audio session object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioSessionAddPropertyListener"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioSessionPropertyID",
          "text": "AudioSessionPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioSessionPropertyListener",
          "text": "AudioSessionPropertyListener"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionAddPropertyListener(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioSessionAddPropertyListener"
        }
      ],
      "role": "symbol",
      "title": "AudioSessionAddPropertyListener(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiosessionaddpropertylistener(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioCategory": {
      "abstract": [
        {
          "text": "The category for the audio session. A read/write ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_AudioCategory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_AudioCategory"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_AudioCategory",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_audiocategory"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioInputAvailable": {
      "abstract": [
        {
          "text": "Indicates if audio input is available (a nonzero value) or not (a value of 0).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_AudioInputAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioInputAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_AudioInputAvailable"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_AudioInputAvailable",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_audioinputavailable"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioRouteChange": {
      "abstract": [
        {
          "text": "The reason the audio route changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_AudioRouteChange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioRouteChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_AudioRouteChange"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_AudioRouteChange",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_audioroutechange"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareIOBufferDuration": {
      "abstract": [
        {
          "text": "Indicates the current hardware IO buffer duration, in seconds, as a read-only ",
          "type": "text"
        },
        {
          "code": "Float32",
          "type": "codeVoice"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_CurrentHardwareIOBufferDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareIOBufferDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_CurrentHardwareIOBufferDuration"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_CurrentHardwareIOBufferDuration",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_currenthardwareiobufferduration"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareInputLatency": {
      "abstract": [
        {
          "text": "Indicates the current hardware input latency, in seconds, as a read-only ",
          "type": "text"
        },
        {
          "code": "Float32",
          "type": "codeVoice"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_CurrentHardwareInputLatency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareInputLatency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_CurrentHardwareInputLatency"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_CurrentHardwareInputLatency",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_currenthardwareinputlatency"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareInputNumberChannels": {
      "abstract": [
        {
          "text": "Indicates the current number of audio hardware input channels. A read-only ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_CurrentHardwareInputNumberChannels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareInputNumberChannels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_CurrentHardwareInputNumberChannels"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_CurrentHardwareInputNumberChannels",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_currenthardwareinputnumberchannels"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareOutputLatency": {
      "abstract": [
        {
          "text": "Indicates the current hardware output latency, in seconds, as a read-only ",
          "type": "text"
        },
        {
          "code": "Float32",
          "type": "codeVoice"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_CurrentHardwareOutputLatency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareOutputLatency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_CurrentHardwareOutputLatency"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_CurrentHardwareOutputLatency",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_currenthardwareoutputlatency"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareOutputNumberChannels": {
      "abstract": [
        {
          "text": "Indicates the current number of audio hardware output channels. A read-only ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_CurrentHardwareOutputNumberChannels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareOutputNumberChannels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_CurrentHardwareOutputNumberChannels"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_CurrentHardwareOutputNumberChannels",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_currenthardwareoutputnumberchannels"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareOutputVolume": {
      "abstract": [
        {
          "text": "Indicates the current audio output volume as ",
          "type": "text"
        },
        {
          "code": "Float32",
          "type": "codeVoice"
        },
        {
          "text": " value between 0.0 and 1.0. Read-only. This value is available to your app by way of a property listener callback function. See ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionAddPropertyListener(_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_CurrentHardwareOutputVolume"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareOutputVolume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_CurrentHardwareOutputVolume"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_CurrentHardwareOutputVolume",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_currenthardwareoutputvolume"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareSampleRate": {
      "abstract": [
        {
          "text": "Indicates the current hardware sample rate. A read-only ",
          "type": "text"
        },
        {
          "code": "Float64",
          "type": "codeVoice"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_CurrentHardwareSampleRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareSampleRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_CurrentHardwareSampleRate"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_CurrentHardwareSampleRate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_currenthardwaresamplerate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OtherAudioIsPlaying": {
      "abstract": [
        {
          "text": "Indicates whether or not another app (typically, the iPod app) is currently playing audio. Read-only. A non-zero ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value indicates that other audio is playing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_OtherAudioIsPlaying"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OtherAudioIsPlaying",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_OtherAudioIsPlaying"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_OtherAudioIsPlaying",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_otheraudioisplaying"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OtherMixableAudioShouldDuck": {
      "abstract": [
        {
          "text": "For audio session categories that allow audio mixing with other apps, specifies whether other audio should be reduced in level when your app produces sound. This property has a value of ",
          "type": "text"
        },
        {
          "code": "FALSE",
          "type": "codeVoice"
        },
        {
          "text": " (0) by default. Set it to a nonzero value to turn on ducking.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_OtherMixableAudioShouldDuck"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OtherMixableAudioShouldDuck",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_OtherMixableAudioShouldDuck"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_OtherMixableAudioShouldDuck",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_othermixableaudioshouldduck"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OverrideAudioRoute": {
      "abstract": [
        {
          "text": "Specifies whether or not to override the audio session category’s typical audio route.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_OverrideAudioRoute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OverrideAudioRoute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_OverrideAudioRoute"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_OverrideAudioRoute",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_overrideaudioroute"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_PreferredHardwareIOBufferDuration": {
      "abstract": [
        {
          "text": "Your preferred hardware I/O buffer duration in seconds. Do not set this property unless you require lower I/O latency than is provided by default.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_PreferredHardwareIOBufferDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_PreferredHardwareIOBufferDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_PreferredHardwareIOBufferDuration"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_PreferredHardwareIOBufferDuration",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_preferredhardwareiobufferduration"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_PreferredHardwareSampleRate": {
      "abstract": [
        {
          "text": "Your preferred hardware sample rate for the audio session. A read/write ",
          "type": "text"
        },
        {
          "code": "Float64",
          "type": "codeVoice"
        },
        {
          "text": " value. The actual sample rate may be different and can be obtained using the ",
          "type": "text"
        },
        {
          "code": "kAudioSessionProperty_CurrentHardwareSampleRate",
          "type": "codeVoice"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_PreferredHardwareSampleRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_PreferredHardwareSampleRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_PreferredHardwareSampleRate"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_PreferredHardwareSampleRate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_preferredhardwaresamplerate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_ServerDied": {
      "abstract": [
        {
          "text": "Indicates if the audio server has died (indicated by a nonzero ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value) or is still running (a value of 0).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_ServerDied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_ServerDied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_ServerDied"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_ServerDied",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_serverdied"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_PreferredHardwareSampleRate",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_PreferredHardwareIOBufferDuration",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioCategory",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioRouteChange",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareSampleRate",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareInputNumberChannels",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareOutputNumberChannels",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareOutputVolume",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareInputLatency",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareIOBufferDuration",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OtherAudioIsPlaying",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OverrideAudioRoute",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioInputAvailable",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_ServerDied",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OtherMixableAudioShouldDuck"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioSessionProperty_CurrentHardwareOutputLatency"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_CurrentHardwareOutputLatency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_PreferredHardwareSampleRate",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_PreferredHardwareIOBufferDuration",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioCategory",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioRouteChange",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareSampleRate",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareInputNumberChannels",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareOutputNumberChannels",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareOutputVolume",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareInputLatency",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_CurrentHardwareIOBufferDuration",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OtherAudioIsPlaying",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OverrideAudioRoute",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_AudioInputAvailable",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_ServerDied",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OtherMixableAudioShouldDuck"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioSessionProperty_CurrentHardwareOutputLatency"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_AudioInputAvailable/title",
          "value": "kAudioSessionProperty_AudioInputAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_AudioInputAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_AudioInputAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_CurrentHardwareInputNumberChannels/title",
          "value": "kAudioSessionProperty_CurrentHardwareInputNumberChannels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_CurrentHardwareInputNumberChannels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_CurrentHardwareInputNumberChannels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_PreferredHardwareSampleRate/title",
          "value": "kAudioSessionProperty_PreferredHardwareSampleRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_PreferredHardwareSampleRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_PreferredHardwareSampleRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionAddPropertyListener(_:_:_:)/title",
          "value": "AudioSessionAddPropertyListener"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionAddPropertyListener(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioSessionAddPropertyListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_CurrentHardwareOutputVolume/title",
          "value": "kAudioSessionProperty_CurrentHardwareOutputVolume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_CurrentHardwareOutputVolume/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_CurrentHardwareOutputVolume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_OtherAudioIsPlaying/title",
          "value": "kAudioSessionProperty_OtherAudioIsPlaying"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_OtherAudioIsPlaying/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_OtherAudioIsPlaying"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_CurrentHardwareInputLatency/title",
          "value": "kAudioSessionProperty_CurrentHardwareInputLatency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_CurrentHardwareInputLatency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_CurrentHardwareInputLatency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_PreferredHardwareIOBufferDuration/title",
          "value": "kAudioSessionProperty_PreferredHardwareIOBufferDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_PreferredHardwareIOBufferDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_PreferredHardwareIOBufferDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_ServerDied/title",
          "value": "kAudioSessionProperty_ServerDied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_ServerDied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_ServerDied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_CurrentHardwareIOBufferDuration/title",
          "value": "kAudioSessionProperty_CurrentHardwareIOBufferDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_CurrentHardwareIOBufferDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_CurrentHardwareIOBufferDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_CurrentHardwareOutputNumberChannels/title",
          "value": "kAudioSessionProperty_CurrentHardwareOutputNumberChannels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_CurrentHardwareOutputNumberChannels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_CurrentHardwareOutputNumberChannels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_CurrentHardwareSampleRate/title",
          "value": "kAudioSessionProperty_CurrentHardwareSampleRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_CurrentHardwareSampleRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_CurrentHardwareSampleRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_AudioRouteChange/title",
          "value": "kAudioSessionProperty_AudioRouteChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_AudioRouteChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_AudioRouteChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_CurrentHardwareOutputLatency/title",
          "value": "kAudioSessionProperty_CurrentHardwareOutputLatency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_CurrentHardwareOutputLatency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_CurrentHardwareOutputLatency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_AudioCategory/title",
          "value": "kAudioSessionProperty_AudioCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_AudioCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_AudioCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_OverrideAudioRoute/title",
          "value": "kAudioSessionProperty_OverrideAudioRoute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_OverrideAudioRoute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_OverrideAudioRoute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_OtherMixableAudioShouldDuck/title",
          "value": "kAudioSessionProperty_OtherMixableAudioShouldDuck"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_OtherMixableAudioShouldDuck/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_OtherMixableAudioShouldDuck"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiosessionproperty_currenthardwareoutputlatency"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiosessionproperty_currenthardwareoutputlatency"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
