{
  "abstract": [
    {
      "text": "The operation cannot be performed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileOperationNotSupportedError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioFileUnspecifiedError@kAudioFileOperationNotSupportedError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioFileOperationNotSupportedError"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioFileOperationNotSupportedError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioFileOperationNotSupportedError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioFileOperationNotSupportedError"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For example, setting the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePropertyAudioDataByteCount",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " constant to increase the size of the audio data in a file is not a supported operation. Write the data instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileBadPropertySizeError": {
      "abstract": [
        {
          "text": "The size of the property data was not correct.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileBadPropertySizeError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileBadPropertySizeError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileBadPropertySizeError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileBadPropertySizeError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilebadpropertysizeerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileDoesNotAllow64BitDataSizeError": {
      "abstract": [
        {
          "text": "The file offset was too large for the file type. The AIFF and WAVE file format types have 32-bit file size limits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileDoesNotAllow64BitDataSizeError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileDoesNotAllow64BitDataSizeError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileDoesNotAllow64BitDataSizeError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileDoesNotAllow64BitDataSizeError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofiledoesnotallow64bitdatasizeerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileEndOfFileError": {
      "abstract": [
        {
          "text": "End of file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileEndOfFileError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileEndOfFileError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileEndOfFileError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileEndOfFileError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileendoffileerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileFileNotFoundError": {
      "abstract": [
        {
          "text": "File not found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileFileNotFoundError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileFileNotFoundError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileFileNotFoundError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileFileNotFoundError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilefilenotfounderror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInvalidChunkError": {
      "abstract": [
        {
          "text": "Either the chunk does not exist in the file or it is not supported by the file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileInvalidChunkError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInvalidChunkError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileInvalidChunkError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileInvalidChunkError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileinvalidchunkerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInvalidFileError": {
      "abstract": [
        {
          "text": "The file is malformed, or otherwise not a valid instance of an audio file of its type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileInvalidFileError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInvalidFileError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileInvalidFileError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileInvalidFileError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileinvalidfileerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInvalidPacketOffsetError": {
      "abstract": [
        {
          "text": "A packet offset was past the end of the file, or not at the end of the file when a VBR format was written,  or a corrupt packet size was read when the packet table was built.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileInvalidPacketOffsetError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInvalidPacketOffsetError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileInvalidPacketOffsetError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileInvalidPacketOffsetError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileinvalidpacketoffseterror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileNotOpenError": {
      "abstract": [
        {
          "text": "The file is closed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileNotOpenError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileNotOpenError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileNotOpenError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileNotOpenError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilenotopenerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileNotOptimizedError": {
      "abstract": [
        {
          "text": "The chunks following the audio data chunk are preventing the extension of the audio data chunk. To write more data, you must optimize the file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileNotOptimizedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileNotOptimizedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileNotOptimizedError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileNotOptimizedError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilenotoptimizederror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileOperationNotSupportedError": {
      "abstract": [
        {
          "text": "The operation cannot be performed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileOperationNotSupportedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileOperationNotSupportedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileOperationNotSupportedError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileOperationNotSupportedError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileoperationnotsupportederror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePermissionsError": {
      "abstract": [
        {
          "text": "The operation violated the file permissions. For example, an attempt was made to write to a file opened with the ",
          "type": "text"
        },
        {
          "code": "kAudioFileReadPermission",
          "type": "codeVoice"
        },
        {
          "text": " constant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFilePermissionsError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePermissionsError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFilePermissionsError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFilePermissionsError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilepermissionserror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePositionError": {
      "abstract": [
        {
          "text": "Invalid file position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFilePositionError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePositionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFilePositionError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFilePositionError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilepositionerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePropertyAudioDataByteCount": {
      "abstract": [
        {
          "text": "Indicates the number of bytes of audio data in the designated file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFilePropertyAudioDataByteCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePropertyAudioDataByteCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFilePropertyAudioDataByteCount"
        }
      ],
      "role": "symbol",
      "title": "kAudioFilePropertyAudioDataByteCount",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilepropertyaudiodatabytecount"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnspecifiedError": {
      "abstract": [
        {
          "text": "An unspecified error has occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileUnspecifiedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnspecifiedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileUnspecifiedError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileUnspecifiedError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileunspecifiederror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnsupportedDataFormatError": {
      "abstract": [
        {
          "text": "The data format is not supported by this file type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileUnsupportedDataFormatError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnsupportedDataFormatError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileUnsupportedDataFormatError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileUnsupportedDataFormatError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileunsupporteddataformaterror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnsupportedFileTypeError": {
      "abstract": [
        {
          "text": "The file type is not supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileUnsupportedFileTypeError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnsupportedFileTypeError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileUnsupportedFileTypeError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileUnsupportedFileTypeError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileunsupportedfiletypeerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnsupportedPropertyError": {
      "abstract": [
        {
          "text": "The property is not supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileUnsupportedPropertyError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnsupportedPropertyError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileUnsupportedPropertyError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileUnsupportedPropertyError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofileunsupportedpropertyerror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Result-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnspecifiedError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnsupportedFileTypeError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnsupportedDataFormatError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnsupportedPropertyError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileBadPropertySizeError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePermissionsError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileNotOptimizedError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInvalidChunkError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileDoesNotAllow64BitDataSizeError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInvalidPacketOffsetError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInvalidFileError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileNotOpenError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileEndOfFileError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePositionError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileFileNotFoundError"
      ],
      "title": "Result Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioFileOperationNotSupportedError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileOperationNotSupportedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Result-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnspecifiedError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnsupportedFileTypeError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnsupportedDataFormatError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileUnsupportedPropertyError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileBadPropertySizeError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePermissionsError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileNotOptimizedError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInvalidChunkError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileDoesNotAllow64BitDataSizeError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInvalidPacketOffsetError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileInvalidFileError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileNotOpenError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileEndOfFileError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePositionError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileFileNotFoundError"
              ],
              "title": "Result Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioFileOperationNotSupportedError"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileFileNotFoundError/title",
          "value": "kAudioFileFileNotFoundError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileFileNotFoundError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileFileNotFoundError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileInvalidFileError/title",
          "value": "kAudioFileInvalidFileError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileInvalidFileError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileInvalidFileError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileEndOfFileError/title",
          "value": "kAudioFileEndOfFileError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileEndOfFileError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileEndOfFileError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileOperationNotSupportedError/title",
          "value": "kAudioFileOperationNotSupportedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileOperationNotSupportedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileOperationNotSupportedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileUnsupportedFileTypeError/title",
          "value": "kAudioFileUnsupportedFileTypeError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileUnsupportedFileTypeError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileUnsupportedFileTypeError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileNotOptimizedError/title",
          "value": "kAudioFileNotOptimizedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileNotOptimizedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileNotOptimizedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileUnspecifiedError/title",
          "value": "kAudioFileUnspecifiedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileUnspecifiedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileUnspecifiedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileUnsupportedPropertyError/title",
          "value": "kAudioFileUnsupportedPropertyError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileUnsupportedPropertyError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileUnsupportedPropertyError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFilePropertyAudioDataByteCount/title",
          "value": "kAudioFilePropertyAudioDataByteCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFilePropertyAudioDataByteCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFilePropertyAudioDataByteCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileNotOpenError/title",
          "value": "kAudioFileNotOpenError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileNotOpenError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileNotOpenError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFilePermissionsError/title",
          "value": "kAudioFilePermissionsError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFilePermissionsError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFilePermissionsError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFilePositionError/title",
          "value": "kAudioFilePositionError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFilePositionError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFilePositionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileUnsupportedDataFormatError/title",
          "value": "kAudioFileUnsupportedDataFormatError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileUnsupportedDataFormatError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileUnsupportedDataFormatError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileDoesNotAllow64BitDataSizeError/title",
          "value": "kAudioFileDoesNotAllow64BitDataSizeError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileDoesNotAllow64BitDataSizeError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileDoesNotAllow64BitDataSizeError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileInvalidPacketOffsetError/title",
          "value": "kAudioFileInvalidPacketOffsetError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileInvalidPacketOffsetError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileInvalidPacketOffsetError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileInvalidChunkError/title",
          "value": "kAudioFileInvalidChunkError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileInvalidChunkError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileInvalidChunkError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileBadPropertySizeError/title",
          "value": "kAudioFileBadPropertySizeError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileBadPropertySizeError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileBadPropertySizeError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiofileoperationnotsupportederror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiofileoperationnotsupportederror"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
