{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecSetPropertySelect"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioCodecGetPropertyInfoSelect@kAudioCodecSetPropertySelect",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioCodecSetPropertySelect"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioCodecSetPropertySelect"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioCodecSetPropertySelect"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioCodecSetPropertySelect"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecAppendInputBufferListSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecAppendInputBufferListSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecAppendInputBufferListSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecAppendInputBufferListSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecAppendInputBufferListSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecappendinputbufferlistselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecAppendInputDataSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecAppendInputDataSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecAppendInputDataSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecAppendInputDataSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecAppendInputDataSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecappendinputdataselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecGetPropertyInfoSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecGetPropertyInfoSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecGetPropertyInfoSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecGetPropertyInfoSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecGetPropertyInfoSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecgetpropertyinfoselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecGetPropertySelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecGetPropertySelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecGetPropertySelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecGetPropertySelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecGetPropertySelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecgetpropertyselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecInitializeSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecInitializeSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecInitializeSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecInitializeSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecInitializeSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecinitializeselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecProduceOutputBufferListSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecProduceOutputBufferListSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecProduceOutputBufferListSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecProduceOutputBufferListSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecProduceOutputBufferListSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecproduceoutputbufferlistselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecProduceOutputDataSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecProduceOutputDataSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecProduceOutputDataSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecProduceOutputDataSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecProduceOutputDataSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecproduceoutputdataselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecResetSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecResetSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecResetSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecResetSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecResetSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecresetselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecSetPropertySelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecSetPropertySelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecSetPropertySelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecSetPropertySelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecSetPropertySelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecsetpropertyselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecUninitializeSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecUninitializeSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecUninitializeSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecUninitializeSelect"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecUninitializeSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecuninitializeselect"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecAppendInputBufferListSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecAppendInputDataSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecGetPropertyInfoSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecGetPropertySelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecInitializeSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecProduceOutputBufferListSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecProduceOutputDataSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecResetSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecUninitializeSelect"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioCodecSetPropertySelect"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecSetPropertySelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecAppendInputBufferListSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecAppendInputDataSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecGetPropertyInfoSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecGetPropertySelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecInitializeSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecProduceOutputBufferListSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecProduceOutputDataSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecResetSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecUninitializeSelect"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioCodecSetPropertySelect"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecSetPropertySelect/title",
          "value": "kAudioCodecSetPropertySelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecSetPropertySelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecSetPropertySelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecProduceOutputBufferListSelect/title",
          "value": "kAudioCodecProduceOutputBufferListSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecProduceOutputBufferListSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecProduceOutputBufferListSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecAppendInputDataSelect/title",
          "value": "kAudioCodecAppendInputDataSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecAppendInputDataSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecAppendInputDataSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecGetPropertySelect/title",
          "value": "kAudioCodecGetPropertySelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecGetPropertySelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecGetPropertySelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecGetPropertyInfoSelect/title",
          "value": "kAudioCodecGetPropertyInfoSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecGetPropertyInfoSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecGetPropertyInfoSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecAppendInputBufferListSelect/title",
          "value": "kAudioCodecAppendInputBufferListSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecAppendInputBufferListSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecAppendInputBufferListSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecUninitializeSelect/title",
          "value": "kAudioCodecUninitializeSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecUninitializeSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecUninitializeSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecInitializeSelect/title",
          "value": "kAudioCodecInitializeSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecInitializeSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecInitializeSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecProduceOutputDataSelect/title",
          "value": "kAudioCodecProduceOutputDataSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecProduceOutputDataSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecProduceOutputDataSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecResetSelect/title",
          "value": "kAudioCodecResetSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecResetSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecResetSelect"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiocodecsetpropertyselect"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiocodecsetpropertyselect"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
