{
  "abstract": [
    {
      "text": "The property value is not present in this file before the audio data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_ValueUnknown"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioFileStreamError_UnsupportedFileType@kAudioFileStreamError_ValueUnknown",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioFileStreamError_ValueUnknown"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioFileStreamError_ValueUnknown"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioFileStreamError_ValueUnknown"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioFileStreamError_ValueUnknown"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576500-audio-file-errors": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576500-audio-file-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio File Errors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/1576500-audio-file-errors"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_BadPropertySize": {
      "abstract": [
        {
          "text": "The size of the buffer you provided for property data was not correct.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_BadPropertySize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_BadPropertySize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_BadPropertySize"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamError_BadPropertySize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamerror_badpropertysize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_DataUnavailable": {
      "abstract": [
        {
          "text": "The amount of data provided to the parser was insufficient to produce any result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_DataUnavailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_DataUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_DataUnavailable"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamError_DataUnavailable",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamerror_dataunavailable"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_DiscontinuityCantRecover": {
      "abstract": [
        {
          "text": "A discontinuity has occurred in the audio data, and Audio File Stream Services cannot recover.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_DiscontinuityCantRecover"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_DiscontinuityCantRecover",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_DiscontinuityCantRecover"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamError_DiscontinuityCantRecover",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamerror_discontinuitycantrecover"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_IllegalOperation": {
      "abstract": [
        {
          "text": "An illegal operation was attempted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_IllegalOperation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_IllegalOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_IllegalOperation"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamError_IllegalOperation",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamerror_illegaloperation"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_InvalidFile": {
      "abstract": [
        {
          "text": "The file is malformed, not a valid instance of an audio file of its type, or not recognized as an audio file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_InvalidFile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_InvalidFile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_InvalidFile"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamError_InvalidFile",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamerror_invalidfile"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_InvalidPacketOffset": {
      "abstract": [
        {
          "text": "A packet offset was less than ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": ", or past the end of the file, or a corrupt packet size was read when building the packet table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_InvalidPacketOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_InvalidPacketOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_InvalidPacketOffset"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamError_InvalidPacketOffset",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamerror_invalidpacketoffset"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_NotOptimized": {
      "abstract": [
        {
          "text": "It is not possible to produce output packets because the streamed audio file’s packet table or other defining information is not present or appears after the audio data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_NotOptimized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_NotOptimized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_NotOptimized"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamError_NotOptimized",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamerror_notoptimized"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnspecifiedError": {
      "abstract": [
        {
          "text": "An unspecified error has occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_UnspecifiedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnspecifiedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_UnspecifiedError"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamError_UnspecifiedError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamerror_unspecifiederror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnsupportedDataFormat": {
      "abstract": [
        {
          "text": "The data format is not supported by the specified file type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_UnsupportedDataFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnsupportedDataFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_UnsupportedDataFormat"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamError_UnsupportedDataFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamerror_unsupporteddataformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnsupportedFileType": {
      "abstract": [
        {
          "text": "The specified file type is not supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_UnsupportedFileType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnsupportedFileType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_UnsupportedFileType"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamError_UnsupportedFileType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamerror_unsupportedfiletype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnsupportedProperty": {
      "abstract": [
        {
          "text": "The property is not supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_UnsupportedProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnsupportedProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_UnsupportedProperty"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamError_UnsupportedProperty",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamerror_unsupportedproperty"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_ValueUnknown": {
      "abstract": [
        {
          "text": "The property value is not present in this file before the audio data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_ValueUnknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_ValueUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFileStreamError_ValueUnknown"
        }
      ],
      "role": "symbol",
      "title": "kAudioFileStreamError_ValueUnknown",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilestreamerror_valueunknown"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Result-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576500-audio-file-errors",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnsupportedFileType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnsupportedDataFormat",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnsupportedProperty",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_BadPropertySize",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_NotOptimized",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_InvalidPacketOffset",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_InvalidFile",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_DataUnavailable",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_IllegalOperation",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnspecifiedError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_DiscontinuityCantRecover"
      ],
      "title": "Result Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioFileStreamError_ValueUnknown"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamError_ValueUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Result-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/1576500-audio-file-errors",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnsupportedFileType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnsupportedDataFormat",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnsupportedProperty",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_BadPropertySize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_NotOptimized",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_InvalidPacketOffset",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_InvalidFile",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_DataUnavailable",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_IllegalOperation",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_UnspecifiedError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFileStreamError_DiscontinuityCantRecover"
              ],
              "title": "Result Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioFileStreamError_ValueUnknown"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_IllegalOperation/title",
          "value": "kAudioFileStreamError_IllegalOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_IllegalOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamError_IllegalOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_DiscontinuityCantRecover/title",
          "value": "kAudioFileStreamError_DiscontinuityCantRecover"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_DiscontinuityCantRecover/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamError_DiscontinuityCantRecover"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_DataUnavailable/title",
          "value": "kAudioFileStreamError_DataUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_DataUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamError_DataUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_NotOptimized/title",
          "value": "kAudioFileStreamError_NotOptimized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_NotOptimized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamError_NotOptimized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_UnsupportedProperty/title",
          "value": "kAudioFileStreamError_UnsupportedProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_UnsupportedProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamError_UnsupportedProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_InvalidPacketOffset/title",
          "value": "kAudioFileStreamError_InvalidPacketOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_InvalidPacketOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamError_InvalidPacketOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_InvalidFile/title",
          "value": "kAudioFileStreamError_InvalidFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_InvalidFile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamError_InvalidFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_BadPropertySize/title",
          "value": "kAudioFileStreamError_BadPropertySize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_BadPropertySize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamError_BadPropertySize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_ValueUnknown/title",
          "value": "kAudioFileStreamError_ValueUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_ValueUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamError_ValueUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_UnsupportedFileType/title",
          "value": "kAudioFileStreamError_UnsupportedFileType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_UnsupportedFileType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamError_UnsupportedFileType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_UnsupportedDataFormat/title",
          "value": "kAudioFileStreamError_UnsupportedDataFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_UnsupportedDataFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamError_UnsupportedDataFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_UnspecifiedError/title",
          "value": "kAudioFileStreamError_UnspecifiedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFileStreamError_UnspecifiedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFileStreamError_UnspecifiedError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiofilestreamerror_valueunknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiofilestreamerror_valueunknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
