{
  "abstract": [
    {
      "text": "Used, with a HAL audio object property listener callback, as a flag that indicates a hardware service restart. The property’s ",
      "type": "text"
    },
    {
      "code": "Float32",
      "type": "codeVoice"
    },
    {
      "text": " value has no meaning. When the hardware service restarts, any associated application state, such as cached data or property listener callbacks, must be re-established.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceProperty_ServiceRestarted"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioHardwareServiceProperty_ServiceRestarted@kAudioHardwareServiceProperty_ServiceRestarted",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioHardwareServiceProperty_ServiceRestarted"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
        "text": "AudioObjectPropertySelector"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioHardwareServiceProperty_ServiceRestarted"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioHardwareServiceProperty_ServiceRestarted"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioHardwareServiceProperty_ServiceRestarted"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@AudioObjectPropertySelector",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
              "text": "AudioObjectPropertySelector"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMainBalance": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwareServiceDeviceProperty_VirtualMainBalance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMainBalance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwareServiceDeviceProperty_VirtualMainBalance"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwareServiceDeviceProperty_VirtualMainBalance",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiohardwareservicedeviceproperty_virtualmainbalance"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMainVolume": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwareServiceDeviceProperty_VirtualMainVolume"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMainVolume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwareServiceDeviceProperty_VirtualMainVolume"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwareServiceDeviceProperty_VirtualMainVolume",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiohardwareservicedeviceproperty_virtualmainvolume"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMasterBalance": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "Float32",
          "type": "codeVoice"
        },
        {
          "text": " value that represents the value of a hardware device’s stereo balance control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kAudioHardwareServiceDeviceProperty_VirtualMasterBalance"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMasterBalance",
      "kind": "symbol",
      "role": "symbol",
      "title": "kAudioHardwareServiceDeviceProperty_VirtualMasterBalance",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiohardwareservicedeviceproperty_virtualmasterbalance"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMasterVolume": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "Float32",
          "type": "codeVoice"
        },
        {
          "text": " value that represents the value of the volume control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kAudioHardwareServiceDeviceProperty_VirtualMasterVolume"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMasterVolume",
      "kind": "symbol",
      "role": "symbol",
      "title": "kAudioHardwareServiceDeviceProperty_VirtualMasterVolume",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiohardwareservicedeviceproperty_virtualmastervolume"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceProperty_ServiceRestarted": {
      "abstract": [
        {
          "text": "Used, with a HAL audio object property listener callback, as a flag that indicates a hardware service restart. The property’s ",
          "type": "text"
        },
        {
          "code": "Float32",
          "type": "codeVoice"
        },
        {
          "text": " value has no meaning. When the hardware service restarts, any associated application state, such as cached data or property listener callbacks, must be re-established.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwareServiceProperty_ServiceRestarted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceProperty_ServiceRestarted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwareServiceProperty_ServiceRestarted"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwareServiceProperty_ServiceRestarted",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiohardwareserviceproperty_servicerestarted"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@AudioObjectPropertySelector": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertySelector"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@AudioObjectPropertySelector",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioObjectPropertySelector",
      "type": "topic",
      "url": "/documentation/CoreAudio/AudioObjectPropertySelector"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMainBalance",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMainVolume"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioHardwareServiceProperty_ServiceRestarted"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwareServiceProperty_ServiceRestarted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMasterVolume",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMasterBalance",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMainBalance",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioHardwareServiceDeviceProperty_VirtualMainVolume"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioHardwareServiceProperty_ServiceRestarted"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioHardwareServiceDeviceProperty_VirtualMainVolume/title",
          "value": "kAudioHardwareServiceDeviceProperty_VirtualMainVolume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioHardwareServiceDeviceProperty_VirtualMainVolume/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwareServiceDeviceProperty_VirtualMainVolume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioHardwareServiceProperty_ServiceRestarted/title",
          "value": "kAudioHardwareServiceProperty_ServiceRestarted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioHardwareServiceProperty_ServiceRestarted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwareServiceProperty_ServiceRestarted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioHardwareServiceDeviceProperty_VirtualMainBalance/title",
          "value": "kAudioHardwareServiceDeviceProperty_VirtualMainBalance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioHardwareServiceDeviceProperty_VirtualMainBalance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwareServiceDeviceProperty_VirtualMainBalance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@AudioObjectPropertySelector/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@UInt32",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioObjectPropertySelector"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiohardwareserviceproperty_servicerestarted"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiohardwareserviceproperty_servicerestarted"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
