{
  "abstract": [
    {
      "text": "Audio routes input or output dictionary.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Deprecated in iOS 7.0.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSession_AudioRouteKey_Type"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kAudioSession_AudioRouteKey_Type",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioSession_AudioRouteKey_Type"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      },
      {
        "kind": "text",
        "text": "!"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioSession_AudioRouteKey_Type"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "14.0",
        "message": "no longer supported",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "no longer supported",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioSession_AudioRouteKey_Type"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioSession_AudioRouteKey_Type"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            },
            {
              "kind": "text",
              "text": "!"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfstring",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object that serves as the one key for an audio routes input or output dictionary, whose value specifies an input source or output destination.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_BluetoothHFP": {
      "abstract": [
        {
          "text": "A microphone that is part of a Bluetooth Hands-Free Profile (HFP) device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionInputRoute_BluetoothHFP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_BluetoothHFP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionInputRoute_BluetoothHFP"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionInputRoute_BluetoothHFP",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessioninputroute_bluetoothhfp"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_BuiltInMic": {
      "abstract": [
        {
          "text": "A built-in microphone input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionInputRoute_BuiltInMic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_BuiltInMic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionInputRoute_BuiltInMic"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionInputRoute_BuiltInMic",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessioninputroute_builtinmic"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_HeadsetMic": {
      "abstract": [
        {
          "text": "A microphone that is part of a headset.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionInputRoute_HeadsetMic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_HeadsetMic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionInputRoute_HeadsetMic"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionInputRoute_HeadsetMic",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessioninputroute_headsetmic"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_LineIn": {
      "abstract": [
        {
          "text": "A line in input",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionInputRoute_LineIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_LineIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionInputRoute_LineIn"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionInputRoute_LineIn",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessioninputroute_linein"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_USBAudio": {
      "abstract": [
        {
          "text": "A Universal Serial Bus (USB) input, accessed through the device 30-pin connector.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionInputRoute_USBAudio"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_USBAudio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionInputRoute_USBAudio"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionInputRoute_USBAudio",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessioninputroute_usbaudio"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_AirPlay": {
      "abstract": [
        {
          "text": "An output on an AirPlay device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_AirPlay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_AirPlay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_AirPlay"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionOutputRoute_AirPlay",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionoutputroute_airplay"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BluetoothA2DP": {
      "abstract": [
        {
          "text": "Speakers in a Bluetooth A2DP device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_BluetoothA2DP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BluetoothA2DP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_BluetoothA2DP"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionOutputRoute_BluetoothA2DP",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionoutputroute_bluetootha2dp"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BluetoothHFP": {
      "abstract": [
        {
          "text": "Speakers that are part of a Bluetooth Hands-Free Profile (HFP) accessory.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_BluetoothHFP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BluetoothHFP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_BluetoothHFP"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionOutputRoute_BluetoothHFP",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionoutputroute_bluetoothhfp"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BuiltInReceiver": {
      "abstract": [
        {
          "text": "The built-in speaker you hold to your ear when on a phone call.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_BuiltInReceiver"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BuiltInReceiver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_BuiltInReceiver"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionOutputRoute_BuiltInReceiver",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionoutputroute_builtinreceiver"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BuiltInSpeaker": {
      "abstract": [
        {
          "text": "The primary built-in speaker.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_BuiltInSpeaker"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BuiltInSpeaker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_BuiltInSpeaker"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionOutputRoute_BuiltInSpeaker",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionoutputroute_builtinspeaker"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_HDMI": {
      "abstract": [
        {
          "text": "An output available through the HDMI interface.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_HDMI"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_HDMI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_HDMI"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionOutputRoute_HDMI",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionoutputroute_hdmi"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_Headphones": {
      "abstract": [
        {
          "text": "Speakers in headphones or in a headset.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_Headphones"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_Headphones",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_Headphones"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionOutputRoute_Headphones",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionoutputroute_headphones"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_LineOut": {
      "abstract": [
        {
          "text": "Analog line-level output.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_LineOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_LineOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_LineOut"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionOutputRoute_LineOut",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionoutputroute_lineout"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_USBAudio": {
      "abstract": [
        {
          "text": "Speaker(s) in a Universal Serial Bus (USB) accessory, accessed through the device 30-pin connector.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_USBAudio"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_USBAudio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionOutputRoute_USBAudio"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionOutputRoute_USBAudio",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionoutputroute_usbaudio"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSession_AudioRouteChangeKey_CurrentRouteDescription": {
      "abstract": [
        {
          "text": "Describes the current audio route.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSession_AudioRouteChangeKey_CurrentRouteDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSession_AudioRouteChangeKey_CurrentRouteDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSession_AudioRouteChangeKey_CurrentRouteDescription"
        }
      ],
      "role": "symbol",
      "title": "kAudioSession_AudioRouteChangeKey_CurrentRouteDescription",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosession_audioroutechangekey_currentroutedescription"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSession_AudioRouteKey_Type": {
      "abstract": [
        {
          "text": "Audio routes input or output dictionary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSession_AudioRouteKey_Type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSession_AudioRouteKey_Type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSession_AudioRouteKey_Type"
        }
      ],
      "role": "symbol",
      "title": "kAudioSession_AudioRouteKey_Type",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosession_audioroutekey_type"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cfstring": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_BluetoothHFP",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_BuiltInMic",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_HeadsetMic",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_LineIn",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_USBAudio",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_AirPlay",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BluetoothA2DP",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BluetoothHFP",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BuiltInReceiver",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BuiltInSpeaker",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_HDMI",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_Headphones",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_LineOut",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_USBAudio",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSession_AudioRouteChangeKey_CurrentRouteDescription"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "7.0",
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "7.0",
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioSession_AudioRouteKey_Type"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSession_AudioRouteKey_Type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_BluetoothHFP",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_BuiltInMic",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_HeadsetMic",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_LineIn",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionInputRoute_USBAudio",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_AirPlay",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BluetoothA2DP",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BluetoothHFP",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BuiltInReceiver",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_BuiltInSpeaker",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_HDMI",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_Headphones",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_LineOut",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionOutputRoute_USBAudio",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSession_AudioRouteChangeKey_CurrentRouteDescription"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kAudioSession_AudioRouteKey_Type"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Deprecated in iOS 7.0.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~1cfstring/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_LineOut/title",
          "value": "kAudioSessionOutputRoute_LineOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_LineOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionOutputRoute_LineOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_BuiltInSpeaker/title",
          "value": "kAudioSessionOutputRoute_BuiltInSpeaker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_BuiltInSpeaker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionOutputRoute_BuiltInSpeaker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_USBAudio/title",
          "value": "kAudioSessionOutputRoute_USBAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_USBAudio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionOutputRoute_USBAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_Headphones/title",
          "value": "kAudioSessionOutputRoute_Headphones"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_Headphones/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionOutputRoute_Headphones"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_BluetoothA2DP/title",
          "value": "kAudioSessionOutputRoute_BluetoothA2DP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_BluetoothA2DP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionOutputRoute_BluetoothA2DP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_BuiltInReceiver/title",
          "value": "kAudioSessionOutputRoute_BuiltInReceiver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_BuiltInReceiver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionOutputRoute_BuiltInReceiver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_BluetoothHFP/title",
          "value": "kAudioSessionOutputRoute_BluetoothHFP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_BluetoothHFP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionOutputRoute_BluetoothHFP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSession_AudioRouteChangeKey_CurrentRouteDescription/title",
          "value": "kAudioSession_AudioRouteChangeKey_CurrentRouteDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSession_AudioRouteChangeKey_CurrentRouteDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSession_AudioRouteChangeKey_CurrentRouteDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_HDMI/title",
          "value": "kAudioSessionOutputRoute_HDMI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_HDMI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionOutputRoute_HDMI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionInputRoute_USBAudio/title",
          "value": "kAudioSessionInputRoute_USBAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionInputRoute_USBAudio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionInputRoute_USBAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionInputRoute_BuiltInMic/title",
          "value": "kAudioSessionInputRoute_BuiltInMic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionInputRoute_BuiltInMic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionInputRoute_BuiltInMic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionInputRoute_HeadsetMic/title",
          "value": "kAudioSessionInputRoute_HeadsetMic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionInputRoute_HeadsetMic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionInputRoute_HeadsetMic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_AirPlay/title",
          "value": "kAudioSessionOutputRoute_AirPlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionOutputRoute_AirPlay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionOutputRoute_AirPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionInputRoute_BluetoothHFP/title",
          "value": "kAudioSessionInputRoute_BluetoothHFP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionInputRoute_BluetoothHFP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionInputRoute_BluetoothHFP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSession_AudioRouteKey_Type/title",
          "value": "kAudioSession_AudioRouteKey_Type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSession_AudioRouteKey_Type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSession_AudioRouteKey_Type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionInputRoute_LineIn/title",
          "value": "kAudioSessionInputRoute_LineIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionInputRoute_LineIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionInputRoute_LineIn"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiosession_audioroutekey_type"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiosession_audioroutekey_type"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
