{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecUseRecommendedSampleRate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioCodecPropertyRequiresPacketDescription@kAudioCodecUseRecommendedSampleRate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioCodecUseRecommendedSampleRate"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioCodecPropertyID",
        "text": "AudioCodecPropertyID"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioCodecUseRecommendedSampleRate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioCodecUseRecommendedSampleRate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioCodecUseRecommendedSampleRate"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecPropertyID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioCodecPropertyID",
              "text": "AudioCodecPropertyID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecPropertyID": {
      "abstract": [
        {
          "text": "An integer identifying an audio codec property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioCodecPropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioCodecPropertyID"
        }
      ],
      "role": "symbol",
      "title": "AudioCodecPropertyID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocodecpropertyid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecBitRateFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecBitRateFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecBitRateFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecBitRateFormat"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecBitRateFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecbitrateformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecDoesSampleRateConversion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecDoesSampleRateConversion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecDoesSampleRateConversion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecDoesSampleRateConversion"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecDoesSampleRateConversion",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecdoessamplerateconversion"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecExtendFrequencies": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecExtendFrequencies"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecExtendFrequencies",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecExtendFrequencies"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecExtendFrequencies",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecextendfrequencies"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecInputFormatsForOutputFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecInputFormatsForOutputFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecInputFormatsForOutputFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecInputFormatsForOutputFormat"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecInputFormatsForOutputFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecinputformatsforoutputformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecOutputFormatsForInputFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecOutputFormatsForInputFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecOutputFormatsForInputFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecOutputFormatsForInputFormat"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecOutputFormatsForInputFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecoutputformatsforinputformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecOutputPrecedence": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecOutputPrecedence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecOutputPrecedence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecOutputPrecedence"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecOutputPrecedence",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecoutputprecedence"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableBitRates": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableBitRates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableBitRates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableBitRates"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyAvailableBitRates",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyavailablebitrates"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableInputChannelLayouts": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableInputChannelLayouts"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableInputChannelLayouts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableInputChannelLayouts"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyAvailableInputChannelLayouts",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyavailableinputchannellayouts"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableOutputChannelLayouts": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableOutputChannelLayouts"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableOutputChannelLayouts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyAvailableOutputChannelLayouts"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyAvailableOutputChannelLayouts",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyavailableoutputchannellayouts"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyInputChannelLayout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyInputChannelLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyInputChannelLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyInputChannelLayout"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyInputChannelLayout",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyinputchannellayout"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyOutputChannelLayout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyOutputChannelLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyOutputChannelLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyOutputChannelLayout"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyOutputChannelLayout",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyoutputchannellayout"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyRequiresPacketDescription": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyRequiresPacketDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyRequiresPacketDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyRequiresPacketDescription"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyRequiresPacketDescription",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyrequirespacketdescription"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyZeroFramesPadded": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyZeroFramesPadded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyZeroFramesPadded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecPropertyZeroFramesPadded"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecPropertyZeroFramesPadded",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecpropertyzeroframespadded"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecUseRecommendedSampleRate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioCodecUseRecommendedSampleRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioCodecPropertyID",
          "text": "AudioCodecPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecUseRecommendedSampleRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioCodecUseRecommendedSampleRate"
        }
      ],
      "role": "symbol",
      "title": "kAudioCodecUseRecommendedSampleRate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocodecuserecommendedsamplerate"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecBitRateFormat",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecDoesSampleRateConversion",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecExtendFrequencies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecInputFormatsForOutputFormat",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecOutputFormatsForInputFormat",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecOutputPrecedence",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableBitRates",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableInputChannelLayouts",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableOutputChannelLayouts",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyInputChannelLayout",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyOutputChannelLayout",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyRequiresPacketDescription",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyZeroFramesPadded"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioCodecUseRecommendedSampleRate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecUseRecommendedSampleRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecBitRateFormat",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecDoesSampleRateConversion",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecExtendFrequencies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecInputFormatsForOutputFormat",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecOutputFormatsForInputFormat",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecOutputPrecedence",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableBitRates",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableInputChannelLayouts",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyAvailableOutputChannelLayouts",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyInputChannelLayout",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyOutputChannelLayout",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyRequiresPacketDescription",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioCodecPropertyZeroFramesPadded"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioCodecUseRecommendedSampleRate"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecBitRateFormat/title",
          "value": "kAudioCodecBitRateFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecBitRateFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecBitRateFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyInputChannelLayout/title",
          "value": "kAudioCodecPropertyInputChannelLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyInputChannelLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyInputChannelLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecDoesSampleRateConversion/title",
          "value": "kAudioCodecDoesSampleRateConversion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecDoesSampleRateConversion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecDoesSampleRateConversion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableOutputChannelLayouts/title",
          "value": "kAudioCodecPropertyAvailableOutputChannelLayouts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableOutputChannelLayouts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyAvailableOutputChannelLayouts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyRequiresPacketDescription/title",
          "value": "kAudioCodecPropertyRequiresPacketDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyRequiresPacketDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyRequiresPacketDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecPropertyID/title",
          "value": "AudioCodecPropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecPropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioCodecPropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioCodecPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableBitRates/title",
          "value": "kAudioCodecPropertyAvailableBitRates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableBitRates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyAvailableBitRates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecOutputFormatsForInputFormat/title",
          "value": "kAudioCodecOutputFormatsForInputFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecOutputFormatsForInputFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecOutputFormatsForInputFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecUseRecommendedSampleRate/title",
          "value": "kAudioCodecUseRecommendedSampleRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecUseRecommendedSampleRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecUseRecommendedSampleRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableInputChannelLayouts/title",
          "value": "kAudioCodecPropertyAvailableInputChannelLayouts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyAvailableInputChannelLayouts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyAvailableInputChannelLayouts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyZeroFramesPadded/title",
          "value": "kAudioCodecPropertyZeroFramesPadded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyZeroFramesPadded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyZeroFramesPadded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecOutputPrecedence/title",
          "value": "kAudioCodecOutputPrecedence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecOutputPrecedence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecOutputPrecedence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecInputFormatsForOutputFormat/title",
          "value": "kAudioCodecInputFormatsForOutputFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecInputFormatsForOutputFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecInputFormatsForOutputFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyOutputChannelLayout/title",
          "value": "kAudioCodecPropertyOutputChannelLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecPropertyOutputChannelLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecPropertyOutputChannelLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecExtendFrequencies/title",
          "value": "kAudioCodecExtendFrequencies"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioCodecExtendFrequencies/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioCodecExtendFrequencies"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiocodecuserecommendedsamplerate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiocodecuserecommendedsamplerate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
