{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_MultiSplitter"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioUnitSubType_AUConverter@kAudioUnitSubType_MultiSplitter",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioUnitSubType_MultiSplitter"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioUnitSubType_MultiSplitter"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioUnitSubType_MultiSplitter"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_MultiSplitter"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_AUConverter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_AUConverter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_AUConverter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_AUConverter"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_AUConverter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_auconverter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_AUiPodTimeOther": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_AUiPodTimeOther"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_AUiPodTimeOther",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_AUiPodTimeOther"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_AUiPodTimeOther",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_auipodtimeother"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_DeferredRenderer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_DeferredRenderer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_DeferredRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_DeferredRenderer"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_DeferredRenderer",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_deferredrenderer"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Merger": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_Merger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Merger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_Merger"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_Merger",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_merger"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_MultiSplitter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_MultiSplitter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_MultiSplitter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_MultiSplitter"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_MultiSplitter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_multisplitter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_NewTimePitch": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_NewTimePitch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_NewTimePitch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_NewTimePitch"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_NewTimePitch",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_newtimepitch"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_RoundTripAAC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_RoundTripAAC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_RoundTripAAC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_RoundTripAAC"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_RoundTripAAC",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_roundtripaac"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Splitter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_Splitter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Splitter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_Splitter"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_Splitter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_splitter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Varispeed": {
      "abstract": [
        {
          "text": "An audio unit that can control playback rate. As the playback rate increases, so does pitch. This subtype provides a generic view, making it suitable for UI and programmatic context. macOS provides realtime and offline audio units of this subtype.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_Varispeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Varispeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitSubType_Varispeed"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitSubType_Varispeed",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitsubtype_varispeed"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_AUConverter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_AUiPodTimeOther",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_DeferredRenderer",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Merger",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_NewTimePitch",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_RoundTripAAC",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Splitter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Varispeed"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioUnitSubType_MultiSplitter"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_MultiSplitter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_AUConverter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_AUiPodTimeOther",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_DeferredRenderer",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Merger",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_NewTimePitch",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_RoundTripAAC",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Splitter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitSubType_Varispeed"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioUnitSubType_MultiSplitter"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_Varispeed/title",
          "value": "kAudioUnitSubType_Varispeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_Varispeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_Varispeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_Merger/title",
          "value": "kAudioUnitSubType_Merger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_Merger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_Merger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_RoundTripAAC/title",
          "value": "kAudioUnitSubType_RoundTripAAC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_RoundTripAAC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_RoundTripAAC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_DeferredRenderer/title",
          "value": "kAudioUnitSubType_DeferredRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_DeferredRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_DeferredRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_AUiPodTimeOther/title",
          "value": "kAudioUnitSubType_AUiPodTimeOther"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_AUiPodTimeOther/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_AUiPodTimeOther"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_MultiSplitter/title",
          "value": "kAudioUnitSubType_MultiSplitter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_MultiSplitter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_MultiSplitter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_Splitter/title",
          "value": "kAudioUnitSubType_Splitter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_Splitter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_Splitter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_NewTimePitch/title",
          "value": "kAudioUnitSubType_NewTimePitch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_NewTimePitch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_NewTimePitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_AUConverter/title",
          "value": "kAudioUnitSubType_AUConverter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitSubType_AUConverter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitSubType_AUConverter"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiounitsubtype_multisplitter"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiounitsubtype_multisplitter"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
