{
  "abstract": [
    {
      "text": "Indicates the total number of channels for input and output of a given matrix mixer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_MatrixDimensions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioUnitProperty_MeteringMode@kAudioUnitProperty_MatrixDimensions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioUnitProperty_MatrixDimensions"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioUnitPropertyID",
        "text": "AudioUnitPropertyID"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioUnitProperty_MatrixDimensions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioUnitProperty_MatrixDimensions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_MatrixDimensions"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitPropertyID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioUnitPropertyID",
              "text": "AudioUnitPropertyID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A read-only ",
              "type": "text"
            },
            {
              "code": "2 * UInt32",
              "type": "codeVoice"
            },
            {
              "text": " value valid on the audio unit global scope.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitPropertyID": {
      "abstract": [
        {
          "text": "The data type for audio unit property keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitPropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitPropertyID"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitPropertyID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitpropertyid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_InputAnchorTimeStamp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_InputAnchorTimeStamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_InputAnchorTimeStamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_InputAnchorTimeStamp"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_InputAnchorTimeStamp",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_inputanchortimestamp"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_MatrixDimensions": {
      "abstract": [
        {
          "text": "Indicates the total number of channels for input and output of a given matrix mixer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_MatrixDimensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_MatrixDimensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_MatrixDimensions"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_MatrixDimensions",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_matrixdimensions"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_MatrixLevels": {
      "abstract": [
        {
          "text": "Describes the internal state of a matrix mixer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_MatrixLevels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_MatrixLevels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_MatrixLevels"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_MatrixLevels",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_matrixlevels"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_MeterClipping": {
      "abstract": [
        {
          "text": "Indicates audio clipping that has occurred since this property was last accessed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_MeterClipping"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_MeterClipping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_MeterClipping"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_MeterClipping",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_meterclipping"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_MeteringMode": {
      "abstract": [
        {
          "text": "Specifies whether metering is enabled or disabled for a particular scope-element combination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_MeteringMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_MeteringMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitProperty_MeteringMode"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitProperty_MeteringMode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiounitproperty_meteringmode"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_InputAnchorTimeStamp",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_MatrixLevels",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_MeterClipping",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_MeteringMode"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioUnitProperty_MatrixDimensions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_MatrixDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_InputAnchorTimeStamp",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_MatrixLevels",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_MeterClipping",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitProperty_MeteringMode"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioUnitProperty_MatrixDimensions"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_MatrixDimensions/title",
          "value": "kAudioUnitProperty_MatrixDimensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_MatrixDimensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_MatrixDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_MeterClipping/title",
          "value": "kAudioUnitProperty_MeterClipping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_MeterClipping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_MeterClipping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_MatrixLevels/title",
          "value": "kAudioUnitProperty_MatrixLevels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_MatrixLevels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_MatrixLevels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_MeteringMode/title",
          "value": "kAudioUnitProperty_MeteringMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_MeteringMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_MeteringMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_InputAnchorTimeStamp/title",
          "value": "kAudioUnitProperty_InputAnchorTimeStamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitProperty_InputAnchorTimeStamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitProperty_InputAnchorTimeStamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitPropertyID/title",
          "value": "AudioUnitPropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitPropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitPropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitPropertyID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiounitproperty_matrixdimensions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiounitproperty_matrixdimensions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
