{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_Initialized"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioUnitErr_InvalidProperty@kAudioUnitErr_Initialized",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioUnitErr_Initialized"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioUnitErr_Initialized"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioUnitErr_Initialized"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_Initialized"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioComponentErr_InstanceInvalidated": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioComponentErr_InstanceInvalidated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioComponentErr_InstanceInvalidated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioComponentErr_InstanceInvalidated"
        }
      ],
      "role": "symbol",
      "title": "kAudioComponentErr_InstanceInvalidated",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiocomponenterr_instanceinvalidated"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_CannotDoInCurrentContext": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_CannotDoInCurrentContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_CannotDoInCurrentContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_CannotDoInCurrentContext"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_CannotDoInCurrentContext",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_cannotdoincurrentcontext"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_FailedInitialization": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_FailedInitialization"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_FailedInitialization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_FailedInitialization"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_FailedInitialization",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_failedinitialization"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_FileNotSpecified": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_FileNotSpecified"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_FileNotSpecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_FileNotSpecified"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_FileNotSpecified",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_filenotspecified"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_FormatNotSupported": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_FormatNotSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_FormatNotSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_FormatNotSupported"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_FormatNotSupported",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_formatnotsupported"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_Initialized": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_Initialized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_Initialized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_Initialized"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_Initialized",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_initialized"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidElement": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidElement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidElement"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_InvalidElement",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_invalidelement"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidFile": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidFile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidFile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidFile"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_InvalidFile",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_invalidfile"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidOfflineRender": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidOfflineRender"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidOfflineRender",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidOfflineRender"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_InvalidOfflineRender",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_invalidofflinerender"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidParameter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidParameter"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_InvalidParameter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_invalidparameter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidProperty": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidProperty"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_InvalidProperty",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_invalidproperty"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidPropertyValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidPropertyValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidPropertyValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidPropertyValue"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_InvalidPropertyValue",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_invalidpropertyvalue"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidScope": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidScope"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidScope",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_InvalidScope"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_InvalidScope",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_invalidscope"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_NoConnection": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_NoConnection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_NoConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_NoConnection"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_NoConnection",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_noconnection"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_PropertyNotInUse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_PropertyNotInUse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_PropertyNotInUse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_PropertyNotInUse"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_PropertyNotInUse",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_propertynotinuse"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_PropertyNotWritable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_PropertyNotWritable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_PropertyNotWritable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_PropertyNotWritable"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_PropertyNotWritable",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_propertynotwritable"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioComponentErr_InstanceInvalidated",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_CannotDoInCurrentContext",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_FailedInitialization",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_FileNotSpecified",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_FormatNotSupported",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidElement",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidFile",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidOfflineRender",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidParameter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidProperty",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidPropertyValue",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidScope",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_NoConnection",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_PropertyNotInUse",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_PropertyNotWritable"
      ],
      "title": "Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioUnitErr_Initialized"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_Initialized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioComponentErr_InstanceInvalidated",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_CannotDoInCurrentContext",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_FailedInitialization",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_FileNotSpecified",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_FormatNotSupported",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidElement",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidFile",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidOfflineRender",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidParameter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidProperty",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidPropertyValue",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_InvalidScope",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_NoConnection",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_PropertyNotInUse",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_PropertyNotWritable"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioUnitErr_Initialized"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidParameter/title",
          "value": "kAudioUnitErr_InvalidParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_InvalidParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_Initialized/title",
          "value": "kAudioUnitErr_Initialized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_Initialized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_Initialized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidScope/title",
          "value": "kAudioUnitErr_InvalidScope"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidScope/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_InvalidScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_PropertyNotInUse/title",
          "value": "kAudioUnitErr_PropertyNotInUse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_PropertyNotInUse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_PropertyNotInUse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_FailedInitialization/title",
          "value": "kAudioUnitErr_FailedInitialization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_FailedInitialization/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_FailedInitialization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidPropertyValue/title",
          "value": "kAudioUnitErr_InvalidPropertyValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidPropertyValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_InvalidPropertyValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidFile/title",
          "value": "kAudioUnitErr_InvalidFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidFile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_InvalidFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidOfflineRender/title",
          "value": "kAudioUnitErr_InvalidOfflineRender"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidOfflineRender/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_InvalidOfflineRender"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_FileNotSpecified/title",
          "value": "kAudioUnitErr_FileNotSpecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_FileNotSpecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_FileNotSpecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioComponentErr_InstanceInvalidated/title",
          "value": "kAudioComponentErr_InstanceInvalidated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioComponentErr_InstanceInvalidated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioComponentErr_InstanceInvalidated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidElement/title",
          "value": "kAudioUnitErr_InvalidElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_InvalidElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_NoConnection/title",
          "value": "kAudioUnitErr_NoConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_NoConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_NoConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_CannotDoInCurrentContext/title",
          "value": "kAudioUnitErr_CannotDoInCurrentContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_CannotDoInCurrentContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_CannotDoInCurrentContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_PropertyNotWritable/title",
          "value": "kAudioUnitErr_PropertyNotWritable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_PropertyNotWritable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_PropertyNotWritable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_FormatNotSupported/title",
          "value": "kAudioUnitErr_FormatNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_FormatNotSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_FormatNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidProperty/title",
          "value": "kAudioUnitErr_InvalidProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_InvalidProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_InvalidProperty"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiouniterr_initialized"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiouniterr_initialized"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
