{
  "abstract": [
    {
      "text": "The preferred codec implementation type—hardware or software—for an audio queue. Possible values for this constant are the remaining constants described in this section.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_HardwareCodecPolicy"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioQueueProperty_HardwareCodecPolicy@kAudioQueueProperty_HardwareCodecPolicy",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioQueueProperty_HardwareCodecPolicy"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioQueuePropertyID",
        "text": "AudioQueuePropertyID"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioQueueProperty_HardwareCodecPolicy"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioQueueProperty_HardwareCodecPolicy"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioQueueProperty_HardwareCodecPolicy"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueuePropertyID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioQueuePropertyID",
              "text": "AudioQueuePropertyID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueuePropertyID": {
      "abstract": [
        {
          "text": "Identifiers for audio queue properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioQueuePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioQueuePropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioQueuePropertyID"
        }
      ],
      "role": "symbol",
      "title": "AudioQueuePropertyID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audioqueuepropertyid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_Default": {
      "abstract": [
        {
          "text": "If the required codec is available in both hardware and software implementations, the audio queue will use a hardware codec if its audio session category permits; it will use a software codec otherwise. If the required codec is available in only one form, that codec implementation is used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueHardwareCodecPolicy_Default"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_Default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueHardwareCodecPolicy_Default"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueHardwareCodecPolicy_Default",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueuehardwarecodecpolicy_default"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_PreferHardware": {
      "abstract": [
        {
          "text": "The audio queue will use a hardware codec if one is available and if its use permitted by the audio session category that you have set; otherwise, it will use a software codec if one is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueHardwareCodecPolicy_PreferHardware"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_PreferHardware",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueHardwareCodecPolicy_PreferHardware"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueHardwareCodecPolicy_PreferHardware",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueuehardwarecodecpolicy_preferhardware"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_PreferSoftware": {
      "abstract": [
        {
          "text": "The audio queue will use a software codec if one is available; if not, it will use a hardware codec if one is available and if its use is permitted by the audio session category that you have set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueHardwareCodecPolicy_PreferSoftware"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_PreferSoftware",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueHardwareCodecPolicy_PreferSoftware"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueHardwareCodecPolicy_PreferSoftware",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueuehardwarecodecpolicy_prefersoftware"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_UseHardwareOnly": {
      "abstract": [
        {
          "text": "The audio queue will use a hardware codec if one is available and if its use is permitted by the audio session category that you have set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueHardwareCodecPolicy_UseHardwareOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_UseHardwareOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueHardwareCodecPolicy_UseHardwareOnly"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueHardwareCodecPolicy_UseHardwareOnly",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueuehardwarecodecpolicy_usehardwareonly"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_UseSoftwareOnly": {
      "abstract": [
        {
          "text": "The audio queue will use a software codec if one is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueHardwareCodecPolicy_UseSoftwareOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_UseSoftwareOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueHardwareCodecPolicy_UseSoftwareOnly"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueHardwareCodecPolicy_UseSoftwareOnly",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueuehardwarecodecpolicy_usesoftwareonly"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_HardwareCodecPolicy": {
      "abstract": [
        {
          "text": "The preferred codec implementation type—hardware or software—for an audio queue. Possible values for this constant are the remaining constants described in this section.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioQueueProperty_HardwareCodecPolicy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioQueuePropertyID",
          "text": "AudioQueuePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueProperty_HardwareCodecPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioQueueProperty_HardwareCodecPolicy"
        }
      ],
      "role": "symbol",
      "title": "kAudioQueueProperty_HardwareCodecPolicy",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudioqueueproperty_hardwarecodecpolicy"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_Default",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_UseSoftwareOnly",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_UseHardwareOnly",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_PreferSoftware",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_PreferHardware"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioQueueProperty_HardwareCodecPolicy"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueProperty_HardwareCodecPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_Default",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_UseSoftwareOnly",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_UseHardwareOnly",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_PreferSoftware",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioQueueHardwareCodecPolicy_PreferHardware"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioQueueProperty_HardwareCodecPolicy"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueuePropertyID/title",
          "value": "AudioQueuePropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueuePropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueuePropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioQueuePropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioQueuePropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueHardwareCodecPolicy_Default/title",
          "value": "kAudioQueueHardwareCodecPolicy_Default"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueHardwareCodecPolicy_Default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueHardwareCodecPolicy_Default"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueHardwareCodecPolicy_PreferSoftware/title",
          "value": "kAudioQueueHardwareCodecPolicy_PreferSoftware"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueHardwareCodecPolicy_PreferSoftware/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueHardwareCodecPolicy_PreferSoftware"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueHardwareCodecPolicy_PreferHardware/title",
          "value": "kAudioQueueHardwareCodecPolicy_PreferHardware"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueHardwareCodecPolicy_PreferHardware/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueHardwareCodecPolicy_PreferHardware"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueHardwareCodecPolicy_UseHardwareOnly/title",
          "value": "kAudioQueueHardwareCodecPolicy_UseHardwareOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueHardwareCodecPolicy_UseHardwareOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueHardwareCodecPolicy_UseHardwareOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueHardwareCodecPolicy_UseSoftwareOnly/title",
          "value": "kAudioQueueHardwareCodecPolicy_UseSoftwareOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueHardwareCodecPolicy_UseSoftwareOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueHardwareCodecPolicy_UseSoftwareOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueProperty_HardwareCodecPolicy/title",
          "value": "kAudioQueueProperty_HardwareCodecPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioQueueProperty_HardwareCodecPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioQueueProperty_HardwareCodecPolicy"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaudioqueueproperty_hardwarecodecpolicy"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaudioqueueproperty_hardwarecodecpolicy"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
