{
  "abstract": [
    {
      "text": "The audio session category has changed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionRouteChangeReason_CategoryChange"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioSessionRouteChangeReason_Unknown@kAudioSessionRouteChangeReason_CategoryChange",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioSessionRouteChangeReason_CategoryChange"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioSessionRouteChangeReason_CategoryChange"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioSessionRouteChangeReason_CategoryChange"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioSessionRouteChangeReason_CategoryChange"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionRouteChangeReason_CategoryChange": {
      "abstract": [
        {
          "text": "The audio session category has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionRouteChangeReason_CategoryChange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionRouteChangeReason_CategoryChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionRouteChangeReason_CategoryChange"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionRouteChangeReason_CategoryChange",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionroutechangereason_categorychange"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionRouteChangeReason_NewDeviceAvailable": {
      "abstract": [
        {
          "text": "A new audio hardware device became available; for example, a headset was plugged in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionRouteChangeReason_NewDeviceAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionRouteChangeReason_NewDeviceAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionRouteChangeReason_NewDeviceAvailable"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionRouteChangeReason_NewDeviceAvailable",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionroutechangereason_newdeviceavailable"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionRouteChangeReason_NoSuitableRouteForCategory": {
      "abstract": [
        {
          "text": "There is no audio hardware route for the audio session category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionRouteChangeReason_NoSuitableRouteForCategory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionRouteChangeReason_NoSuitableRouteForCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionRouteChangeReason_NoSuitableRouteForCategory"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionRouteChangeReason_NoSuitableRouteForCategory",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionroutechangereason_nosuitablerouteforcategory"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionRouteChangeReason_OldDeviceUnavailable": {
      "abstract": [
        {
          "text": "The previously-used audio hardware device is now unavailable; for example, a headset was unplugged.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionRouteChangeReason_OldDeviceUnavailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionRouteChangeReason_OldDeviceUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionRouteChangeReason_OldDeviceUnavailable"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionRouteChangeReason_OldDeviceUnavailable",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionroutechangereason_olddeviceunavailable"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionRouteChangeReason_Override": {
      "abstract": [
        {
          "text": "The audio route has been overridden.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionRouteChangeReason_Override"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionRouteChangeReason_Override",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionRouteChangeReason_Override"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionRouteChangeReason_Override",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionroutechangereason_override"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionRouteChangeReason_RouteConfigurationChange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionRouteChangeReason_RouteConfigurationChange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionRouteChangeReason_RouteConfigurationChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionRouteChangeReason_RouteConfigurationChange"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionRouteChangeReason_RouteConfigurationChange",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionroutechangereason_routeconfigurationchange"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionRouteChangeReason_Unknown": {
      "abstract": [
        {
          "text": "The audio route changed but the reason is not known.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionRouteChangeReason_Unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionRouteChangeReason_Unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionRouteChangeReason_Unknown"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionRouteChangeReason_Unknown",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionroutechangereason_unknown"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionRouteChangeReason_WakeFromSleep": {
      "abstract": [
        {
          "text": "The device woke from sleep.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionRouteChangeReason_WakeFromSleep"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionRouteChangeReason_WakeFromSleep",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionRouteChangeReason_WakeFromSleep"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionRouteChangeReason_WakeFromSleep",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionroutechangereason_wakefromsleep"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionRouteChangeReason_Unknown",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionRouteChangeReason_NewDeviceAvailable",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionRouteChangeReason_OldDeviceUnavailable",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionRouteChangeReason_Override",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionRouteChangeReason_WakeFromSleep",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionRouteChangeReason_NoSuitableRouteForCategory",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionRouteChangeReason_RouteConfigurationChange"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioSessionRouteChangeReason_CategoryChange"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionRouteChangeReason_CategoryChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionRouteChangeReason_Unknown",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionRouteChangeReason_NewDeviceAvailable",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionRouteChangeReason_OldDeviceUnavailable",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionRouteChangeReason_Override",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionRouteChangeReason_WakeFromSleep",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionRouteChangeReason_NoSuitableRouteForCategory",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionRouteChangeReason_RouteConfigurationChange"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioSessionRouteChangeReason_CategoryChange"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionRouteChangeReason_WakeFromSleep/title",
          "value": "kAudioSessionRouteChangeReason_WakeFromSleep"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionRouteChangeReason_WakeFromSleep/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionRouteChangeReason_WakeFromSleep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionRouteChangeReason_OldDeviceUnavailable/title",
          "value": "kAudioSessionRouteChangeReason_OldDeviceUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionRouteChangeReason_OldDeviceUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionRouteChangeReason_OldDeviceUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionRouteChangeReason_Unknown/title",
          "value": "kAudioSessionRouteChangeReason_Unknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionRouteChangeReason_Unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionRouteChangeReason_Unknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionRouteChangeReason_NoSuitableRouteForCategory/title",
          "value": "kAudioSessionRouteChangeReason_NoSuitableRouteForCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionRouteChangeReason_NoSuitableRouteForCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionRouteChangeReason_NoSuitableRouteForCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionRouteChangeReason_RouteConfigurationChange/title",
          "value": "kAudioSessionRouteChangeReason_RouteConfigurationChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionRouteChangeReason_RouteConfigurationChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionRouteChangeReason_RouteConfigurationChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionRouteChangeReason_Override/title",
          "value": "kAudioSessionRouteChangeReason_Override"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionRouteChangeReason_Override/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionRouteChangeReason_Override"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionRouteChangeReason_CategoryChange/title",
          "value": "kAudioSessionRouteChangeReason_CategoryChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionRouteChangeReason_CategoryChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionRouteChangeReason_CategoryChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionRouteChangeReason_NewDeviceAvailable/title",
          "value": "kAudioSessionRouteChangeReason_NewDeviceAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionRouteChangeReason_NewDeviceAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionRouteChangeReason_NewDeviceAvailable"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiosessionroutechangereason_categorychange"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaudiosessionroutechangereason_categorychange"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
