{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Sustain"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAUGroupParameterID_Volume@kAUGroupParameterID_Sustain",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAUGroupParameterID_Sustain"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioUnitParameterID",
        "text": "AudioUnitParameterID"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAUGroupParameterID_Sustain"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAUGroupParameterID_Sustain"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_Sustain"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioUnitParameterID",
              "text": "AudioUnitParameterID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID": {
      "abstract": [
        {
          "text": "The data type for an audio unit parameter identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterID"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllNotesOff": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_AllNotesOff"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllNotesOff",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_AllNotesOff"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_AllNotesOff",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_allnotesoff"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllSoundOff": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_AllSoundOff"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllSoundOff",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_AllSoundOff"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_AllSoundOff",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_allsoundoff"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ChannelPressure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_ChannelPressure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ChannelPressure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_ChannelPressure"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_ChannelPressure",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_channelpressure"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_DataEntry"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_DataEntry"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_DataEntry",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_dataentry"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry_LSB": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_DataEntry_LSB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry_LSB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_DataEntry_LSB"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_DataEntry_LSB",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_dataentry_lsb"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Expression"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Expression"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_Expression",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_expression"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression_LSB": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Expression_LSB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression_LSB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Expression_LSB"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_Expression_LSB",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_expression_lsb"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Foot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Foot"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_Foot",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_foot"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot_LSB": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Foot_LSB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot_LSB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Foot_LSB"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_Foot_LSB",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_foot_lsb"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_KeyPressure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_KeyPressure"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_KeyPressure",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_keypressure"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_FirstKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_KeyPressure_FirstKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_FirstKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_KeyPressure_FirstKey"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_KeyPressure_FirstKey",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_keypressure_firstkey"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_LastKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_KeyPressure_LastKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_LastKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_KeyPressure_LastKey"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_KeyPressure_LastKey",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_keypressure_lastkey"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_ModWheel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_ModWheel"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_ModWheel",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_modwheel"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel_LSB": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_ModWheel_LSB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel_LSB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_ModWheel_LSB"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_ModWheel_LSB",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_modwheel_lsb"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Pan": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Pan"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Pan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Pan"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_Pan",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_pan"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Sustain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Sustain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Sustain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUGroupParameterID_Sustain"
        }
      ],
      "role": "symbol",
      "title": "kAUGroupParameterID_Sustain",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaugroupparameterid_sustain"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllNotesOff",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllSoundOff",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ChannelPressure",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry_LSB",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression_LSB",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot_LSB",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_FirstKey",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_LastKey",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel_LSB",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Pan"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAUGroupParameterID_Sustain"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_Sustain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllNotesOff",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllSoundOff",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ChannelPressure",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry_LSB",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression_LSB",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot_LSB",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_FirstKey",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_LastKey",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel_LSB",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Pan"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAUGroupParameterID_Sustain"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_ModWheel_LSB/title",
          "value": "kAUGroupParameterID_ModWheel_LSB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_ModWheel_LSB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_ModWheel_LSB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_AllNotesOff/title",
          "value": "kAUGroupParameterID_AllNotesOff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_AllNotesOff/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_AllNotesOff"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_KeyPressure_FirstKey/title",
          "value": "kAUGroupParameterID_KeyPressure_FirstKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_KeyPressure_FirstKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_KeyPressure_FirstKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Foot/title",
          "value": "kAUGroupParameterID_Foot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Foot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_Foot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Expression/title",
          "value": "kAUGroupParameterID_Expression"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Expression/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_Expression"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_ModWheel/title",
          "value": "kAUGroupParameterID_ModWheel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_ModWheel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_ModWheel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Expression_LSB/title",
          "value": "kAUGroupParameterID_Expression_LSB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Expression_LSB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_Expression_LSB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_ChannelPressure/title",
          "value": "kAUGroupParameterID_ChannelPressure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_ChannelPressure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_ChannelPressure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_AllSoundOff/title",
          "value": "kAUGroupParameterID_AllSoundOff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_AllSoundOff/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_AllSoundOff"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Sustain/title",
          "value": "kAUGroupParameterID_Sustain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Sustain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_Sustain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/title",
          "value": "AudioUnitParameterID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_KeyPressure/title",
          "value": "kAUGroupParameterID_KeyPressure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_KeyPressure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_KeyPressure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_DataEntry_LSB/title",
          "value": "kAUGroupParameterID_DataEntry_LSB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_DataEntry_LSB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_DataEntry_LSB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_DataEntry/title",
          "value": "kAUGroupParameterID_DataEntry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_DataEntry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_DataEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Foot_LSB/title",
          "value": "kAUGroupParameterID_Foot_LSB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Foot_LSB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_Foot_LSB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_KeyPressure_LastKey/title",
          "value": "kAUGroupParameterID_KeyPressure_LastKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_KeyPressure_LastKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_KeyPressure_LastKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Pan/title",
          "value": "kAUGroupParameterID_Pan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Pan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUGroupParameterID_Pan"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaugroupparameterid_sustain"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaugroupparameterid_sustain"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
