{"metadata":{"navigatorTitle":[{"text":"kAUGroupParameterID_ChannelPressure","kind":"identifier"}],"roleHeading":"Global Variable","externalID":"c:@Ea@kAUGroupParameterID_Volume@kAUGroupParameterID_ChannelPressure","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAUGroupParameterID_ChannelPressure","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@AudioUnitParameterID","text":"AudioUnitParameterID","kind":"typeIdentifier"}],"modules":[{"name":"Audio Toolbox"}],"role":"symbol","platforms":[{"unavailable":false,"name":"iOS","beta":false,"deprecated":false},{"unavailable":false,"name":"iPadOS","beta":false,"deprecated":false},{"unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false},{"unavailable":false,"name":"macOS","beta":false,"deprecated":false},{"unavailable":false,"name":"tvOS","beta":false,"deprecated":false},{"unavailable":false,"name":"visionOS","beta":false,"deprecated":false}],"title":"kAUGroupParameterID_ChannelPressure","symbolKind":"var"},"variants":[{"paths":["/documentation/audiotoolbox/kaugroupparameterid_channelpressure"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/audiotoolbox/kaugroupparameterid_channelpressure"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAUGroupParameterID_ChannelPressure","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@AudioUnitParameterID","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID","text":"AudioUnitParameterID","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","identifier":{"url":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ChannelPressure","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.audiotoolbox/documentation/AudioToolbox"]]},"seeAlsoSections":[{"identifiers":["doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllNotesOff","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllSoundOff","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry_LSB","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression_LSB","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot_LSB","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_FirstKey","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_LastKey","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel_LSB","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Pan","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Pan_LSB"],"generated":true,"anchor":"Constants","title":"Constants"}],"references":{"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Pan_LSB":{"url":"/documentation/audiotoolbox/kaugroupparameterid_pan_lsb","navigatorTitle":[{"kind":"identifier","text":"kAUGroupParameterID_Pan_LSB"}],"title":"kAUGroupParameterID_Pan_LSB","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Pan_LSB","type":"topic","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAUGroupParameterID_Pan_LSB"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioUnitParameterID","text":"AudioUnitParameterID"}],"kind":"symbol"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression":{"url":"/documentation/audiotoolbox/kaugroupparameterid_expression","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAUGroupParameterID_Expression","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioUnitParameterID","preciseIdentifier":"c:@T@AudioUnitParameterID","kind":"typeIdentifier"}],"type":"topic","title":"kAUGroupParameterID_Expression","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"kAUGroupParameterID_Expression","kind":"identifier"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllNotesOff":{"title":"kAUGroupParameterID_AllNotesOff","role":"symbol","type":"topic","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllNotesOff","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAUGroupParameterID_AllNotesOff"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioUnitParameterID","preciseIdentifier":"c:@T@AudioUnitParameterID"}],"navigatorTitle":[{"kind":"identifier","text":"kAUGroupParameterID_AllNotesOff"}],"url":"/documentation/audiotoolbox/kaugroupparameterid_allnotesoff"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_FirstKey":{"url":"/documentation/audiotoolbox/kaugroupparameterid_keypressure_firstkey","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAUGroupParameterID_KeyPressure_FirstKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioUnitParameterID","preciseIdentifier":"c:@T@AudioUnitParameterID","kind":"typeIdentifier"}],"type":"topic","title":"kAUGroupParameterID_KeyPressure_FirstKey","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_FirstKey","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"kAUGroupParameterID_KeyPressure_FirstKey","kind":"identifier"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID":{"type":"topic","title":"AudioUnitParameterID","abstract":[{"type":"text","text":"The data type for an audio unit parameter identifier."}],"url":"/documentation/audiotoolbox/audiounitparameterid","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioUnitParameterID","kind":"identifier"}],"navigatorTitle":[{"text":"AudioUnitParameterID","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllSoundOff":{"url":"/documentation/audiotoolbox/kaugroupparameterid_allsoundoff","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAUGroupParameterID_AllSoundOff","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioUnitParameterID","preciseIdentifier":"c:@T@AudioUnitParameterID","kind":"typeIdentifier"}],"type":"topic","title":"kAUGroupParameterID_AllSoundOff","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllSoundOff","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"kAUGroupParameterID_AllSoundOff","kind":"identifier"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel_LSB":{"url":"/documentation/audiotoolbox/kaugroupparameterid_modwheel_lsb","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAUGroupParameterID_ModWheel_LSB"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioUnitParameterID","preciseIdentifier":"c:@T@AudioUnitParameterID"}],"type":"topic","title":"kAUGroupParameterID_ModWheel_LSB","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel_LSB","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kAUGroupParameterID_ModWheel_LSB"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure":{"title":"kAUGroupParameterID_KeyPressure","role":"symbol","type":"topic","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAUGroupParameterID_KeyPressure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioUnitParameterID","preciseIdentifier":"c:@T@AudioUnitParameterID"}],"navigatorTitle":[{"kind":"identifier","text":"kAUGroupParameterID_KeyPressure"}],"url":"/documentation/audiotoolbox/kaugroupparameterid_keypressure"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ChannelPressure":{"title":"kAUGroupParameterID_ChannelPressure","role":"symbol","type":"topic","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ChannelPressure","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAUGroupParameterID_ChannelPressure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioUnitParameterID","preciseIdentifier":"c:@T@AudioUnitParameterID"}],"navigatorTitle":[{"kind":"identifier","text":"kAUGroupParameterID_ChannelPressure"}],"url":"/documentation/audiotoolbox/kaugroupparameterid_channelpressure"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Pan":{"type":"topic","title":"kAUGroupParameterID_Pan","abstract":[],"url":"/documentation/audiotoolbox/kaugroupparameterid_pan","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAUGroupParameterID_Pan","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@AudioUnitParameterID","text":"AudioUnitParameterID","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"kAUGroupParameterID_Pan","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Pan"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry":{"title":"kAUGroupParameterID_DataEntry","role":"symbol","type":"topic","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAUGroupParameterID_DataEntry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioUnitParameterID","preciseIdentifier":"c:@T@AudioUnitParameterID"}],"navigatorTitle":[{"kind":"identifier","text":"kAUGroupParameterID_DataEntry"}],"url":"/documentation/audiotoolbox/kaugroupparameterid_dataentry"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_LastKey":{"type":"topic","title":"kAUGroupParameterID_KeyPressure_LastKey","abstract":[],"url":"/documentation/audiotoolbox/kaugroupparameterid_keypressure_lastkey","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAUGroupParameterID_KeyPressure_LastKey","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@AudioUnitParameterID","text":"AudioUnitParameterID","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"kAUGroupParameterID_KeyPressure_LastKey","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_LastKey"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox":{"type":"topic","kind":"symbol","title":"Audio Toolbox","role":"collection","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox","abstract":[{"text":"Record or play audio, convert formats, parse audio streams, and configure your audio session.","type":"text"}],"url":"/documentation/audiotoolbox"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot_LSB":{"url":"/documentation/audiotoolbox/kaugroupparameterid_foot_lsb","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAUGroupParameterID_Foot_LSB","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioUnitParameterID","preciseIdentifier":"c:@T@AudioUnitParameterID","kind":"typeIdentifier"}],"type":"topic","title":"kAUGroupParameterID_Foot_LSB","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot_LSB","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"kAUGroupParameterID_Foot_LSB","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","type":"topic","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","role":"overview"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel":{"url":"/documentation/audiotoolbox/kaugroupparameterid_modwheel","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAUGroupParameterID_ModWheel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioUnitParameterID","preciseIdentifier":"c:@T@AudioUnitParameterID","kind":"typeIdentifier"}],"type":"topic","title":"kAUGroupParameterID_ModWheel","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"kAUGroupParameterID_ModWheel","kind":"identifier"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry_LSB":{"title":"kAUGroupParameterID_DataEntry_LSB","role":"symbol","type":"topic","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry_LSB","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAUGroupParameterID_DataEntry_LSB"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioUnitParameterID","preciseIdentifier":"c:@T@AudioUnitParameterID"}],"navigatorTitle":[{"kind":"identifier","text":"kAUGroupParameterID_DataEntry_LSB"}],"url":"/documentation/audiotoolbox/kaugroupparameterid_dataentry_lsb"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression_LSB":{"title":"kAUGroupParameterID_Expression_LSB","role":"symbol","type":"topic","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression_LSB","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAUGroupParameterID_Expression_LSB"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioUnitParameterID","preciseIdentifier":"c:@T@AudioUnitParameterID"}],"navigatorTitle":[{"kind":"identifier","text":"kAUGroupParameterID_Expression_LSB"}],"url":"/documentation/audiotoolbox/kaugroupparameterid_expression_lsb"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot":{"type":"topic","title":"kAUGroupParameterID_Foot","abstract":[],"url":"/documentation/audiotoolbox/kaugroupparameterid_foot","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAUGroupParameterID_Foot","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioUnitParameterID","preciseIdentifier":"c:@T@AudioUnitParameterID","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"kAUGroupParameterID_Foot","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"name":"iOS","beta":false,"deprecated":false},{"unavailable":false,"name":"iPadOS","beta":false,"deprecated":false},{"beta":false,"unavailable":false,"name":"Mac Catalyst","deprecated":false},{"beta":false,"unavailable":false,"name":"macOS","deprecated":false},{"beta":false,"unavailable":false,"name":"tvOS","deprecated":false},{"beta":false,"unavailable":false,"name":"visionOS","deprecated":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Enumeration Case","path":"/metadata/roleHeading"},{"op":"replace","value":"kAUGroupParameterID_ChannelPressure","path":"/metadata/title"},{"value":"case","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"kAUGroupParameterID_ChannelPressure","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.audiotoolbox/documentation/AudioToolbox"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllNotesOff","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllSoundOff","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry_LSB","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression_LSB","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot_LSB","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_FirstKey","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_LastKey","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel_LSB","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Pan","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Pan_LSB"],"generated":true,"title":"Constants","anchor":"Constants"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"kind":"identifier","text":"kAUGroupParameterID_ChannelPressure"}]}]},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Pan_LSB/title","value":"kAUGroupParameterID_Pan_LSB"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Pan_LSB/fragments","value":[{"kind":"identifier","text":"kAUGroupParameterID_Pan_LSB"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Expression/title","value":"kAUGroupParameterID_Expression"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Expression/fragments","value":[{"kind":"identifier","text":"kAUGroupParameterID_Expression"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_AllNotesOff/title","value":"kAUGroupParameterID_AllNotesOff"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_AllNotesOff/fragments","value":[{"kind":"identifier","text":"kAUGroupParameterID_AllNotesOff"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_KeyPressure_FirstKey/title","value":"kAUGroupParameterID_KeyPressure_FirstKey"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_KeyPressure_FirstKey/fragments","value":[{"text":"kAUGroupParameterID_KeyPressure_FirstKey","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/title","value":"AudioUnitParameterID"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/fragments","value":[{"text":"AudioUnitParameterID","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/navigatorTitle","value":[{"kind":"identifier","text":"AudioUnitParameterID"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_AllSoundOff/title","value":"kAUGroupParameterID_AllSoundOff"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_AllSoundOff/fragments","value":[{"kind":"identifier","text":"kAUGroupParameterID_AllSoundOff"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_ModWheel_LSB/title","value":"kAUGroupParameterID_ModWheel_LSB"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_ModWheel_LSB/fragments","value":[{"kind":"identifier","text":"kAUGroupParameterID_ModWheel_LSB"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_KeyPressure/title","value":"kAUGroupParameterID_KeyPressure"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_KeyPressure/fragments","value":[{"kind":"identifier","text":"kAUGroupParameterID_KeyPressure"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_ChannelPressure/title","value":"kAUGroupParameterID_ChannelPressure"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_ChannelPressure/fragments","value":[{"kind":"identifier","text":"kAUGroupParameterID_ChannelPressure"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Pan/title","value":"kAUGroupParameterID_Pan"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Pan/fragments","value":[{"text":"kAUGroupParameterID_Pan","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_DataEntry/title","value":"kAUGroupParameterID_DataEntry"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_DataEntry/fragments","value":[{"kind":"identifier","text":"kAUGroupParameterID_DataEntry"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_KeyPressure_LastKey/title","value":"kAUGroupParameterID_KeyPressure_LastKey"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_KeyPressure_LastKey/fragments","value":[{"text":"kAUGroupParameterID_KeyPressure_LastKey","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Foot_LSB/title","value":"kAUGroupParameterID_Foot_LSB"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Foot_LSB/fragments","value":[{"text":"kAUGroupParameterID_Foot_LSB","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_ModWheel/title","value":"kAUGroupParameterID_ModWheel"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_ModWheel/fragments","value":[{"text":"kAUGroupParameterID_ModWheel","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_DataEntry_LSB/title","value":"kAUGroupParameterID_DataEntry_LSB"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_DataEntry_LSB/fragments","value":[{"kind":"identifier","text":"kAUGroupParameterID_DataEntry_LSB"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Expression_LSB/title","value":"kAUGroupParameterID_Expression_LSB"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Expression_LSB/fragments","value":[{"text":"kAUGroupParameterID_Expression_LSB","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Foot/title","value":"kAUGroupParameterID_Foot"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Foot/fragments","value":[{"kind":"identifier","text":"kAUGroupParameterID_Foot"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}