{"variants":[{"paths":["/documentation/audiotoolbox/kaugroupparameterid_volume_lsb"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/audiotoolbox/kaugroupparameterid_volume_lsb"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Volume_LSB","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.audiotoolbox/documentation/AudioToolbox"]]},"kind":"symbol","seeAlsoSections":[{"title":"Constants","generated":true,"identifiers":["doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllNotesOff","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllSoundOff","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ChannelPressure","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry_LSB","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression_LSB","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot_LSB","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_FirstKey","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_LastKey","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel_LSB","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Pan"],"anchor":"Constants"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAUGroupParameterID_Volume_LSB"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID","kind":"typeIdentifier","text":"AudioUnitParameterID","preciseIdentifier":"c:@T@AudioUnitParameterID"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"metadata":{"title":"kAUGroupParameterID_Volume_LSB","platforms":[{"name":"iOS","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","deprecated":false,"unavailable":false,"beta":false},{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false},{"name":"macOS","deprecated":false,"unavailable":false,"beta":false},{"name":"tvOS","deprecated":false,"unavailable":false,"beta":false},{"name":"visionOS","deprecated":false,"unavailable":false,"beta":false}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAUGroupParameterID_Volume_LSB","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioUnitParameterID","preciseIdentifier":"c:@T@AudioUnitParameterID","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"kAUGroupParameterID_Volume_LSB","kind":"identifier"}],"symbolKind":"var","roleHeading":"Global Variable","externalID":"c:@Ea@kAUGroupParameterID_Volume@kAUGroupParameterID_Volume_LSB","role":"symbol","modules":[{"name":"Audio Toolbox"}]},"references":{"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot":{"type":"topic","title":"kAUGroupParameterID_Foot","abstract":[],"url":"/documentation/audiotoolbox/kaugroupparameterid_foot","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAUGroupParameterID_Foot","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioUnitParameterID","preciseIdentifier":"c:@T@AudioUnitParameterID","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"kAUGroupParameterID_Foot","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot_LSB":{"url":"/documentation/audiotoolbox/kaugroupparameterid_foot_lsb","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAUGroupParameterID_Foot_LSB","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioUnitParameterID","preciseIdentifier":"c:@T@AudioUnitParameterID","kind":"typeIdentifier"}],"type":"topic","title":"kAUGroupParameterID_Foot_LSB","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot_LSB","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"kAUGroupParameterID_Foot_LSB","kind":"identifier"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure":{"title":"kAUGroupParameterID_KeyPressure","role":"symbol","type":"topic","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAUGroupParameterID_KeyPressure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioUnitParameterID","preciseIdentifier":"c:@T@AudioUnitParameterID"}],"navigatorTitle":[{"kind":"identifier","text":"kAUGroupParameterID_KeyPressure"}],"url":"/documentation/audiotoolbox/kaugroupparameterid_keypressure"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel_LSB":{"url":"/documentation/audiotoolbox/kaugroupparameterid_modwheel_lsb","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAUGroupParameterID_ModWheel_LSB"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioUnitParameterID","preciseIdentifier":"c:@T@AudioUnitParameterID"}],"type":"topic","title":"kAUGroupParameterID_ModWheel_LSB","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel_LSB","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kAUGroupParameterID_ModWheel_LSB"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllNotesOff":{"title":"kAUGroupParameterID_AllNotesOff","role":"symbol","type":"topic","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllNotesOff","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAUGroupParameterID_AllNotesOff"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioUnitParameterID","preciseIdentifier":"c:@T@AudioUnitParameterID"}],"navigatorTitle":[{"kind":"identifier","text":"kAUGroupParameterID_AllNotesOff"}],"url":"/documentation/audiotoolbox/kaugroupparameterid_allnotesoff"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Pan":{"type":"topic","title":"kAUGroupParameterID_Pan","abstract":[],"url":"/documentation/audiotoolbox/kaugroupparameterid_pan","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAUGroupParameterID_Pan","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@AudioUnitParameterID","text":"AudioUnitParameterID","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"kAUGroupParameterID_Pan","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Pan"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllSoundOff":{"url":"/documentation/audiotoolbox/kaugroupparameterid_allsoundoff","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAUGroupParameterID_AllSoundOff","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioUnitParameterID","preciseIdentifier":"c:@T@AudioUnitParameterID","kind":"typeIdentifier"}],"type":"topic","title":"kAUGroupParameterID_AllSoundOff","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllSoundOff","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"kAUGroupParameterID_AllSoundOff","kind":"identifier"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry_LSB":{"title":"kAUGroupParameterID_DataEntry_LSB","role":"symbol","type":"topic","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry_LSB","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAUGroupParameterID_DataEntry_LSB"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioUnitParameterID","preciseIdentifier":"c:@T@AudioUnitParameterID"}],"navigatorTitle":[{"kind":"identifier","text":"kAUGroupParameterID_DataEntry_LSB"}],"url":"/documentation/audiotoolbox/kaugroupparameterid_dataentry_lsb"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Volume_LSB":{"type":"topic","title":"kAUGroupParameterID_Volume_LSB","abstract":[],"url":"/documentation/audiotoolbox/kaugroupparameterid_volume_lsb","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAUGroupParameterID_Volume_LSB","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@AudioUnitParameterID","text":"AudioUnitParameterID","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"kAUGroupParameterID_Volume_LSB","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Volume_LSB"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox":{"type":"topic","kind":"symbol","title":"Audio Toolbox","role":"collection","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox","abstract":[{"text":"Record or play audio, convert formats, parse audio streams, and configure your audio session.","type":"text"}],"url":"/documentation/audiotoolbox"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel":{"url":"/documentation/audiotoolbox/kaugroupparameterid_modwheel","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAUGroupParameterID_ModWheel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioUnitParameterID","preciseIdentifier":"c:@T@AudioUnitParameterID","kind":"typeIdentifier"}],"type":"topic","title":"kAUGroupParameterID_ModWheel","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"kAUGroupParameterID_ModWheel","kind":"identifier"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ChannelPressure":{"title":"kAUGroupParameterID_ChannelPressure","role":"symbol","type":"topic","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ChannelPressure","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAUGroupParameterID_ChannelPressure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioUnitParameterID","preciseIdentifier":"c:@T@AudioUnitParameterID"}],"navigatorTitle":[{"kind":"identifier","text":"kAUGroupParameterID_ChannelPressure"}],"url":"/documentation/audiotoolbox/kaugroupparameterid_channelpressure"},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","type":"topic","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","role":"overview"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID":{"type":"topic","title":"AudioUnitParameterID","abstract":[{"type":"text","text":"The data type for an audio unit parameter identifier."}],"url":"/documentation/audiotoolbox/audiounitparameterid","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioUnitParameterID","kind":"identifier"}],"navigatorTitle":[{"text":"AudioUnitParameterID","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression":{"url":"/documentation/audiotoolbox/kaugroupparameterid_expression","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAUGroupParameterID_Expression","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioUnitParameterID","preciseIdentifier":"c:@T@AudioUnitParameterID","kind":"typeIdentifier"}],"type":"topic","title":"kAUGroupParameterID_Expression","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"kAUGroupParameterID_Expression","kind":"identifier"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry":{"title":"kAUGroupParameterID_DataEntry","role":"symbol","type":"topic","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAUGroupParameterID_DataEntry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioUnitParameterID","preciseIdentifier":"c:@T@AudioUnitParameterID"}],"navigatorTitle":[{"kind":"identifier","text":"kAUGroupParameterID_DataEntry"}],"url":"/documentation/audiotoolbox/kaugroupparameterid_dataentry"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_LastKey":{"type":"topic","title":"kAUGroupParameterID_KeyPressure_LastKey","abstract":[],"url":"/documentation/audiotoolbox/kaugroupparameterid_keypressure_lastkey","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAUGroupParameterID_KeyPressure_LastKey","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@AudioUnitParameterID","text":"AudioUnitParameterID","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"kAUGroupParameterID_KeyPressure_LastKey","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_LastKey"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_FirstKey":{"url":"/documentation/audiotoolbox/kaugroupparameterid_keypressure_firstkey","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAUGroupParameterID_KeyPressure_FirstKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioUnitParameterID","preciseIdentifier":"c:@T@AudioUnitParameterID","kind":"typeIdentifier"}],"type":"topic","title":"kAUGroupParameterID_KeyPressure_FirstKey","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_FirstKey","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"kAUGroupParameterID_KeyPressure_FirstKey","kind":"identifier"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression_LSB":{"title":"kAUGroupParameterID_Expression_LSB","role":"symbol","type":"topic","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression_LSB","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAUGroupParameterID_Expression_LSB"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioUnitParameterID","preciseIdentifier":"c:@T@AudioUnitParameterID"}],"navigatorTitle":[{"kind":"identifier","text":"kAUGroupParameterID_Expression_LSB"}],"url":"/documentation/audiotoolbox/kaugroupparameterid_expression_lsb"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"beta":false,"name":"iOS","deprecated":false,"unavailable":false},{"beta":false,"name":"iPadOS","deprecated":false,"unavailable":false},{"beta":false,"name":"Mac Catalyst","deprecated":false,"unavailable":false},{"beta":false,"name":"macOS","deprecated":false,"unavailable":false},{"beta":false,"name":"tvOS","deprecated":false,"unavailable":false},{"beta":false,"name":"visionOS","deprecated":false,"unavailable":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"/metadata/title","op":"replace","value":"kAUGroupParameterID_Volume_LSB"},{"path":"/metadata/symbolKind","op":"replace","value":"case"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"kAUGroupParameterID_Volume_LSB","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.audiotoolbox/documentation/AudioToolbox"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"title":"Constants","identifiers":["doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllNotesOff","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_AllSoundOff","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ChannelPressure","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_DataEntry_LSB","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Expression_LSB","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Foot_LSB","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_FirstKey","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_KeyPressure_LastKey","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_ModWheel_LSB","doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUGroupParameterID_Pan"],"anchor":"Constants"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"kind":"identifier","text":"kAUGroupParameterID_Volume_LSB"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Foot/title","op":"replace","value":"kAUGroupParameterID_Foot"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Foot/fragments","op":"replace","value":[{"text":"kAUGroupParameterID_Foot","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Foot_LSB/title","op":"replace","value":"kAUGroupParameterID_Foot_LSB"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Foot_LSB/fragments","op":"replace","value":[{"kind":"identifier","text":"kAUGroupParameterID_Foot_LSB"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_KeyPressure/title","op":"replace","value":"kAUGroupParameterID_KeyPressure"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_KeyPressure/fragments","op":"replace","value":[{"text":"kAUGroupParameterID_KeyPressure","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_ModWheel_LSB/title","op":"replace","value":"kAUGroupParameterID_ModWheel_LSB"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_ModWheel_LSB/fragments","op":"replace","value":[{"kind":"identifier","text":"kAUGroupParameterID_ModWheel_LSB"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_AllNotesOff/title","op":"replace","value":"kAUGroupParameterID_AllNotesOff"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_AllNotesOff/fragments","op":"replace","value":[{"text":"kAUGroupParameterID_AllNotesOff","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Pan/title","op":"replace","value":"kAUGroupParameterID_Pan"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Pan/fragments","op":"replace","value":[{"kind":"identifier","text":"kAUGroupParameterID_Pan"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_AllSoundOff/title","op":"replace","value":"kAUGroupParameterID_AllSoundOff"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_AllSoundOff/fragments","op":"replace","value":[{"kind":"identifier","text":"kAUGroupParameterID_AllSoundOff"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_DataEntry_LSB/title","op":"replace","value":"kAUGroupParameterID_DataEntry_LSB"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_DataEntry_LSB/fragments","op":"replace","value":[{"text":"kAUGroupParameterID_DataEntry_LSB","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Volume_LSB/title","op":"replace","value":"kAUGroupParameterID_Volume_LSB"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Volume_LSB/fragments","op":"replace","value":[{"text":"kAUGroupParameterID_Volume_LSB","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_ModWheel/title","op":"replace","value":"kAUGroupParameterID_ModWheel"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_ModWheel/fragments","op":"replace","value":[{"kind":"identifier","text":"kAUGroupParameterID_ModWheel"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_ChannelPressure/title","op":"replace","value":"kAUGroupParameterID_ChannelPressure"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_ChannelPressure/fragments","op":"replace","value":[{"kind":"identifier","text":"kAUGroupParameterID_ChannelPressure"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/title","op":"replace","value":"AudioUnitParameterID"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/fragments","op":"replace","value":[{"text":"AudioUnitParameterID","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AudioUnitParameterID"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Expression/title","op":"replace","value":"kAUGroupParameterID_Expression"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Expression/fragments","op":"replace","value":[{"kind":"identifier","text":"kAUGroupParameterID_Expression"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_DataEntry/title","op":"replace","value":"kAUGroupParameterID_DataEntry"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_DataEntry/fragments","op":"replace","value":[{"kind":"identifier","text":"kAUGroupParameterID_DataEntry"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_KeyPressure_LastKey/title","op":"replace","value":"kAUGroupParameterID_KeyPressure_LastKey"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_KeyPressure_LastKey/fragments","op":"replace","value":[{"kind":"identifier","text":"kAUGroupParameterID_KeyPressure_LastKey"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_KeyPressure_FirstKey/title","op":"replace","value":"kAUGroupParameterID_KeyPressure_FirstKey"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_KeyPressure_FirstKey/fragments","op":"replace","value":[{"kind":"identifier","text":"kAUGroupParameterID_KeyPressure_FirstKey"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Expression_LSB/title","op":"replace","value":"kAUGroupParameterID_Expression_LSB"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUGroupParameterID_Expression_LSB/fragments","op":"replace","value":[{"text":"kAUGroupParameterID_Expression_LSB","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}