{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_LowShelf"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAUNBandEQFilterType_Parametric@kAUNBandEQFilterType_LowShelf",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAUNBandEQFilterType_LowShelf"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAUNBandEQFilterType_LowShelf"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAUNBandEQFilterType_LowShelf"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAUNBandEQFilterType_LowShelf"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_2ndOrderButterworthHighPass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_2ndOrderButterworthHighPass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_2ndOrderButterworthHighPass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_2ndOrderButterworthHighPass"
        }
      ],
      "role": "symbol",
      "title": "kAUNBandEQFilterType_2ndOrderButterworthHighPass",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunbandeqfiltertype_2ndorderbutterworthhighpass"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_2ndOrderButterworthLowPass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_2ndOrderButterworthLowPass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_2ndOrderButterworthLowPass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_2ndOrderButterworthLowPass"
        }
      ],
      "role": "symbol",
      "title": "kAUNBandEQFilterType_2ndOrderButterworthLowPass",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunbandeqfiltertype_2ndorderbutterworthlowpass"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_BandPass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_BandPass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_BandPass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_BandPass"
        }
      ],
      "role": "symbol",
      "title": "kAUNBandEQFilterType_BandPass",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunbandeqfiltertype_bandpass"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_BandStop": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_BandStop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_BandStop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_BandStop"
        }
      ],
      "role": "symbol",
      "title": "kAUNBandEQFilterType_BandStop",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunbandeqfiltertype_bandstop"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_HighShelf": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_HighShelf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_HighShelf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_HighShelf"
        }
      ],
      "role": "symbol",
      "title": "kAUNBandEQFilterType_HighShelf",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunbandeqfiltertype_highshelf"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_LowShelf": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_LowShelf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_LowShelf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_LowShelf"
        }
      ],
      "role": "symbol",
      "title": "kAUNBandEQFilterType_LowShelf",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunbandeqfiltertype_lowshelf"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_Parametric": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_Parametric"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_Parametric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_Parametric"
        }
      ],
      "role": "symbol",
      "title": "kAUNBandEQFilterType_Parametric",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunbandeqfiltertype_parametric"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantHighPass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_ResonantHighPass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantHighPass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_ResonantHighPass"
        }
      ],
      "role": "symbol",
      "title": "kAUNBandEQFilterType_ResonantHighPass",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunbandeqfiltertype_resonanthighpass"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantHighShelf": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_ResonantHighShelf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantHighShelf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_ResonantHighShelf"
        }
      ],
      "role": "symbol",
      "title": "kAUNBandEQFilterType_ResonantHighShelf",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunbandeqfiltertype_resonanthighshelf"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantLowPass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_ResonantLowPass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantLowPass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_ResonantLowPass"
        }
      ],
      "role": "symbol",
      "title": "kAUNBandEQFilterType_ResonantLowPass",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunbandeqfiltertype_resonantlowpass"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantLowShelf": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_ResonantLowShelf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantLowShelf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNBandEQFilterType_ResonantLowShelf"
        }
      ],
      "role": "symbol",
      "title": "kAUNBandEQFilterType_ResonantLowShelf",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunbandeqfiltertype_resonantlowshelf"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNumAUNBandEQFilterTypes": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kNumAUNBandEQFilterTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNumAUNBandEQFilterTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kNumAUNBandEQFilterTypes"
        }
      ],
      "role": "symbol",
      "title": "kNumAUNBandEQFilterTypes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/knumaunbandeqfiltertypes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_2ndOrderButterworthHighPass",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_2ndOrderButterworthLowPass",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_BandPass",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_BandStop",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_HighShelf",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_Parametric",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantHighPass",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantHighShelf",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantLowPass",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantLowShelf",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNumAUNBandEQFilterTypes"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAUNBandEQFilterType_LowShelf"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNBandEQFilterType_LowShelf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_2ndOrderButterworthHighPass",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_2ndOrderButterworthLowPass",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_BandPass",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_BandStop",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_HighShelf",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_Parametric",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantHighPass",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantHighShelf",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantLowPass",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNBandEQFilterType_ResonantLowShelf",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kNumAUNBandEQFilterTypes"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAUNBandEQFilterType_LowShelf"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_ResonantLowPass/title",
          "value": "kAUNBandEQFilterType_ResonantLowPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_ResonantLowPass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNBandEQFilterType_ResonantLowPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_BandStop/title",
          "value": "kAUNBandEQFilterType_BandStop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_BandStop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNBandEQFilterType_BandStop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_2ndOrderButterworthLowPass/title",
          "value": "kAUNBandEQFilterType_2ndOrderButterworthLowPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_2ndOrderButterworthLowPass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNBandEQFilterType_2ndOrderButterworthLowPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_2ndOrderButterworthHighPass/title",
          "value": "kAUNBandEQFilterType_2ndOrderButterworthHighPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_2ndOrderButterworthHighPass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNBandEQFilterType_2ndOrderButterworthHighPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_HighShelf/title",
          "value": "kAUNBandEQFilterType_HighShelf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_HighShelf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNBandEQFilterType_HighShelf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_Parametric/title",
          "value": "kAUNBandEQFilterType_Parametric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_Parametric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNBandEQFilterType_Parametric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_BandPass/title",
          "value": "kAUNBandEQFilterType_BandPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_BandPass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNBandEQFilterType_BandPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_LowShelf/title",
          "value": "kAUNBandEQFilterType_LowShelf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_LowShelf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNBandEQFilterType_LowShelf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_ResonantHighPass/title",
          "value": "kAUNBandEQFilterType_ResonantHighPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_ResonantHighPass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNBandEQFilterType_ResonantHighPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kNumAUNBandEQFilterTypes/title",
          "value": "kNumAUNBandEQFilterTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kNumAUNBandEQFilterTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kNumAUNBandEQFilterTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_ResonantHighShelf/title",
          "value": "kAUNBandEQFilterType_ResonantHighShelf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_ResonantHighShelf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNBandEQFilterType_ResonantHighShelf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_ResonantLowShelf/title",
          "value": "kAUNBandEQFilterType_ResonantLowShelf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNBandEQFilterType_ResonantLowShelf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNBandEQFilterType_ResonantLowShelf"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaunbandeqfiltertype_lowshelf"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaunbandeqfiltertype_lowshelf"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
