{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_ULaw"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAUNetSendPresetFormat_PCMFloat32@kAUNetSendPresetFormat_ULaw",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAUNetSendPresetFormat_ULaw"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioUnitPropertyID",
        "text": "AudioUnitPropertyID"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAUNetSendPresetFormat_ULaw"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAUNetSendPresetFormat_ULaw"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_ULaw"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitPropertyID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioUnitPropertyID",
              "text": "AudioUnitPropertyID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitPropertyID": {
      "abstract": [
        {
          "text": "The data type for audio unit property keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitPropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitPropertyID"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitPropertyID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitpropertyid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendNumPresetFormats": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendNumPresetFormats"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendNumPresetFormats",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendNumPresetFormats"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendNumPresetFormats",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendnumpresetformats"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_128kbpspc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_128kbpspc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_128kbpspc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_128kbpspc"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_AAC_128kbpspc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_aac_128kbpspc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_32kbpspc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_32kbpspc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_32kbpspc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_32kbpspc"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_AAC_32kbpspc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_aac_32kbpspc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_40kbpspc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_40kbpspc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_40kbpspc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_40kbpspc"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_AAC_40kbpspc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_aac_40kbpspc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_48kbpspc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_48kbpspc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_48kbpspc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_48kbpspc"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_AAC_48kbpspc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_aac_48kbpspc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_64kbpspc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_64kbpspc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_64kbpspc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_64kbpspc"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_AAC_64kbpspc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_aac_64kbpspc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_80kbpspc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_80kbpspc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_80kbpspc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_80kbpspc"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_AAC_80kbpspc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_aac_80kbpspc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_96kbpspc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_96kbpspc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_96kbpspc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_96kbpspc"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_AAC_96kbpspc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_aac_96kbpspc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_32kbpspc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_LD_32kbpspc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_32kbpspc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_LD_32kbpspc"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_AAC_LD_32kbpspc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_aac_ld_32kbpspc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_40kbpspc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_LD_40kbpspc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_40kbpspc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_LD_40kbpspc"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_AAC_LD_40kbpspc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_aac_ld_40kbpspc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_48kbpspc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_LD_48kbpspc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_48kbpspc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_LD_48kbpspc"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_AAC_LD_48kbpspc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_aac_ld_48kbpspc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_64kbpspc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_LD_64kbpspc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_64kbpspc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_AAC_LD_64kbpspc"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_AAC_LD_64kbpspc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_aac_ld_64kbpspc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_IMA4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_IMA4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_IMA4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_IMA4"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_IMA4",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_ima4"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_Lossless16": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_Lossless16"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_Lossless16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_Lossless16"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_Lossless16",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_lossless16"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_Lossless24": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_Lossless24"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_Lossless24",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_Lossless24"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_Lossless24",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_lossless24"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_ULaw": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_ULaw"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitPropertyID",
          "text": "AudioUnitPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_ULaw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetSendPresetFormat_ULaw"
        }
      ],
      "role": "symbol",
      "title": "kAUNetSendPresetFormat_ULaw",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetsendpresetformat_ulaw"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendNumPresetFormats",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_128kbpspc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_32kbpspc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_40kbpspc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_48kbpspc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_64kbpspc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_80kbpspc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_96kbpspc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_32kbpspc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_40kbpspc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_48kbpspc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_64kbpspc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_IMA4",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_Lossless16",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_Lossless24"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAUNetSendPresetFormat_ULaw"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_ULaw"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendNumPresetFormats",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_128kbpspc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_32kbpspc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_40kbpspc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_48kbpspc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_64kbpspc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_80kbpspc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_96kbpspc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_32kbpspc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_40kbpspc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_48kbpspc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_AAC_LD_64kbpspc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_IMA4",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_Lossless16",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetSendPresetFormat_Lossless24"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAUNetSendPresetFormat_ULaw"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_48kbpspc/title",
          "value": "kAUNetSendPresetFormat_AAC_48kbpspc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_48kbpspc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_AAC_48kbpspc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendNumPresetFormats/title",
          "value": "kAUNetSendNumPresetFormats"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendNumPresetFormats/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendNumPresetFormats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_IMA4/title",
          "value": "kAUNetSendPresetFormat_IMA4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_IMA4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_IMA4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_96kbpspc/title",
          "value": "kAUNetSendPresetFormat_AAC_96kbpspc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_96kbpspc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_AAC_96kbpspc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_Lossless24/title",
          "value": "kAUNetSendPresetFormat_Lossless24"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_Lossless24/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_Lossless24"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitPropertyID/title",
          "value": "AudioUnitPropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitPropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitPropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_32kbpspc/title",
          "value": "kAUNetSendPresetFormat_AAC_32kbpspc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_32kbpspc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_AAC_32kbpspc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_LD_40kbpspc/title",
          "value": "kAUNetSendPresetFormat_AAC_LD_40kbpspc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_LD_40kbpspc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_AAC_LD_40kbpspc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_80kbpspc/title",
          "value": "kAUNetSendPresetFormat_AAC_80kbpspc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_80kbpspc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_AAC_80kbpspc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_40kbpspc/title",
          "value": "kAUNetSendPresetFormat_AAC_40kbpspc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_40kbpspc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_AAC_40kbpspc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_Lossless16/title",
          "value": "kAUNetSendPresetFormat_Lossless16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_Lossless16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_Lossless16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_LD_64kbpspc/title",
          "value": "kAUNetSendPresetFormat_AAC_LD_64kbpspc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_LD_64kbpspc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_AAC_LD_64kbpspc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_LD_48kbpspc/title",
          "value": "kAUNetSendPresetFormat_AAC_LD_48kbpspc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_LD_48kbpspc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_AAC_LD_48kbpspc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_128kbpspc/title",
          "value": "kAUNetSendPresetFormat_AAC_128kbpspc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_128kbpspc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_AAC_128kbpspc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_LD_32kbpspc/title",
          "value": "kAUNetSendPresetFormat_AAC_LD_32kbpspc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_LD_32kbpspc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_AAC_LD_32kbpspc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_ULaw/title",
          "value": "kAUNetSendPresetFormat_ULaw"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_ULaw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_ULaw"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_64kbpspc/title",
          "value": "kAUNetSendPresetFormat_AAC_64kbpspc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetSendPresetFormat_AAC_64kbpspc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetSendPresetFormat_AAC_64kbpspc"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaunetsendpresetformat_ulaw"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaunetsendpresetformat_ulaw"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
