{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetStatus_Overflow"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAUNetStatus_NotConnected@kAUNetStatus_Overflow",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAUNetStatus_Overflow"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAUNetStatus_Overflow"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAUNetStatus_Overflow"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAUNetStatus_Overflow"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetStatus_Connected": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetStatus_Connected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetStatus_Connected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetStatus_Connected"
        }
      ],
      "role": "symbol",
      "title": "kAUNetStatus_Connected",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetstatus_connected"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetStatus_Connecting": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetStatus_Connecting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetStatus_Connecting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetStatus_Connecting"
        }
      ],
      "role": "symbol",
      "title": "kAUNetStatus_Connecting",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetstatus_connecting"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetStatus_Listening": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetStatus_Listening"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetStatus_Listening",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetStatus_Listening"
        }
      ],
      "role": "symbol",
      "title": "kAUNetStatus_Listening",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetstatus_listening"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetStatus_NotConnected": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetStatus_NotConnected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetStatus_NotConnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetStatus_NotConnected"
        }
      ],
      "role": "symbol",
      "title": "kAUNetStatus_NotConnected",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetstatus_notconnected"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetStatus_Overflow": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetStatus_Overflow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetStatus_Overflow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetStatus_Overflow"
        }
      ],
      "role": "symbol",
      "title": "kAUNetStatus_Overflow",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetstatus_overflow"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetStatus_Underflow": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUNetStatus_Underflow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetStatus_Underflow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUNetStatus_Underflow"
        }
      ],
      "role": "symbol",
      "title": "kAUNetStatus_Underflow",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaunetstatus_underflow"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetStatus_Connected",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetStatus_Connecting",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetStatus_Listening",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetStatus_NotConnected",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetStatus_Underflow"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAUNetStatus_Overflow"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetStatus_Overflow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetStatus_Connected",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetStatus_Connecting",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetStatus_Listening",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetStatus_NotConnected",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUNetStatus_Underflow"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAUNetStatus_Overflow"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetStatus_Overflow/title",
          "value": "kAUNetStatus_Overflow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetStatus_Overflow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetStatus_Overflow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetStatus_Underflow/title",
          "value": "kAUNetStatus_Underflow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetStatus_Underflow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetStatus_Underflow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetStatus_Listening/title",
          "value": "kAUNetStatus_Listening"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetStatus_Listening/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetStatus_Listening"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetStatus_Connected/title",
          "value": "kAUNetStatus_Connected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetStatus_Connected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetStatus_Connected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetStatus_Connecting/title",
          "value": "kAUNetStatus_Connecting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetStatus_Connecting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetStatus_Connecting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetStatus_NotConnected/title",
          "value": "kAUNetStatus_NotConnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUNetStatus_NotConnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUNetStatus_NotConnected"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaunetstatus_overflow"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaunetstatus_overflow"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
