{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetManufacturerKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@kAUPresetManufacturerKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAUPresetManufacturerKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAUPresetManufacturerKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAUPresetManufacturerKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAUPresetManufacturerKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetCPULoadKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUPresetCPULoadKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetCPULoadKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUPresetCPULoadKey"
        }
      ],
      "role": "symbol",
      "title": "kAUPresetCPULoadKey",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaupresetcpuloadkey"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetDataKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUPresetDataKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetDataKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUPresetDataKey"
        }
      ],
      "role": "symbol",
      "title": "kAUPresetDataKey",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaupresetdatakey"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetElementNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUPresetElementNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetElementNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUPresetElementNameKey"
        }
      ],
      "role": "symbol",
      "title": "kAUPresetElementNameKey",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaupresetelementnamekey"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetExternalFileRefs": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUPresetExternalFileRefs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetExternalFileRefs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUPresetExternalFileRefs"
        }
      ],
      "role": "symbol",
      "title": "kAUPresetExternalFileRefs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaupresetexternalfilerefs"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetMASDataKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUPresetMASDataKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetMASDataKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUPresetMASDataKey"
        }
      ],
      "role": "symbol",
      "title": "kAUPresetMASDataKey",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaupresetmasdatakey"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetManufacturerKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUPresetManufacturerKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetManufacturerKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUPresetManufacturerKey"
        }
      ],
      "role": "symbol",
      "title": "kAUPresetManufacturerKey",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaupresetmanufacturerkey"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUPresetNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUPresetNameKey"
        }
      ],
      "role": "symbol",
      "title": "kAUPresetNameKey",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaupresetnamekey"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetNumberKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUPresetNumberKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetNumberKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUPresetNumberKey"
        }
      ],
      "role": "symbol",
      "title": "kAUPresetNumberKey",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaupresetnumberkey"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetPartKey": {
      "abstract": [
        {
          "text": "If present, distinguishes a global preset that is set on the global scope from a part-based preset that is set on the part scope. The value of this key is defined by the audio unit it applies to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUPresetPartKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetPartKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUPresetPartKey"
        }
      ],
      "role": "symbol",
      "title": "kAUPresetPartKey",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaupresetpartkey"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetRenderQualityKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUPresetRenderQualityKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetRenderQualityKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUPresetRenderQualityKey"
        }
      ],
      "role": "symbol",
      "title": "kAUPresetRenderQualityKey",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaupresetrenderqualitykey"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetSubtypeKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUPresetSubtypeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetSubtypeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUPresetSubtypeKey"
        }
      ],
      "role": "symbol",
      "title": "kAUPresetSubtypeKey",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaupresetsubtypekey"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetTypeKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUPresetTypeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetTypeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUPresetTypeKey"
        }
      ],
      "role": "symbol",
      "title": "kAUPresetTypeKey",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaupresettypekey"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetVSTDataKey": {
      "abstract": [
        {
          "text": "VST state from a VST “bank.”",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUPresetVSTDataKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetVSTDataKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUPresetVSTDataKey"
        }
      ],
      "role": "symbol",
      "title": "kAUPresetVSTDataKey",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaupresetvstdatakey"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetVSTPresetKey": {
      "abstract": [
        {
          "text": "VST state from a VST “preset.”",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUPresetVSTPresetKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetVSTPresetKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUPresetVSTPresetKey"
        }
      ],
      "role": "symbol",
      "title": "kAUPresetVSTPresetKey",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaupresetvstpresetkey"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetVersionKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAUPresetVersionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetVersionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUPresetVersionKey"
        }
      ],
      "role": "symbol",
      "title": "kAUPresetVersionKey",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaupresetversionkey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Audio-Unit-Presets",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetNumberKey",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetCPULoadKey",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetDataKey",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetElementNameKey",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetExternalFileRefs",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetMASDataKey",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetNameKey",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetPartKey",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetRenderQualityKey",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetSubtypeKey",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetTypeKey",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetVSTDataKey",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetVSTPresetKey",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetVersionKey"
      ],
      "title": "Getting the Audio Unit Presets"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAUPresetManufacturerKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUPresetManufacturerKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Audio-Unit-Presets",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetNumberKey",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetCPULoadKey",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetDataKey",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetElementNameKey",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetExternalFileRefs",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetMASDataKey",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetNameKey",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetPartKey",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetRenderQualityKey",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetSubtypeKey",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetTypeKey",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetVSTDataKey",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetVSTPresetKey",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAUPresetVersionKey"
              ],
              "title": "Getting the Audio Unit Presets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kAUPresetManufacturerKey"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUPresetRenderQualityKey/title",
          "value": "kAUPresetRenderQualityKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUPresetRenderQualityKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUPresetRenderQualityKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUPresetDataKey/title",
          "value": "kAUPresetDataKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUPresetDataKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUPresetDataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUPresetElementNameKey/title",
          "value": "kAUPresetElementNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUPresetElementNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUPresetElementNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUPresetPartKey/title",
          "value": "kAUPresetPartKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUPresetPartKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUPresetPartKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUPresetVSTDataKey/title",
          "value": "kAUPresetVSTDataKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUPresetVSTDataKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUPresetVSTDataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUPresetNameKey/title",
          "value": "kAUPresetNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUPresetNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUPresetNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUPresetMASDataKey/title",
          "value": "kAUPresetMASDataKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUPresetMASDataKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUPresetMASDataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUPresetNumberKey/title",
          "value": "kAUPresetNumberKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUPresetNumberKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUPresetNumberKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUPresetTypeKey/title",
          "value": "kAUPresetTypeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUPresetTypeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUPresetTypeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUPresetManufacturerKey/title",
          "value": "kAUPresetManufacturerKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUPresetManufacturerKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUPresetManufacturerKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUPresetVSTPresetKey/title",
          "value": "kAUPresetVSTPresetKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUPresetVSTPresetKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUPresetVSTPresetKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUPresetVersionKey/title",
          "value": "kAUPresetVersionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUPresetVersionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUPresetVersionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUPresetCPULoadKey/title",
          "value": "kAUPresetCPULoadKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUPresetCPULoadKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUPresetCPULoadKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUPresetSubtypeKey/title",
          "value": "kAUPresetSubtypeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUPresetSubtypeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUPresetSubtypeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUPresetExternalFileRefs/title",
          "value": "kAUPresetExternalFileRefs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAUPresetExternalFileRefs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUPresetExternalFileRefs"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kaupresetmanufacturerkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kaupresetmanufacturerkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
