{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_CannotSetTimeError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kCAClock_UnknownPropertyError@kCAClock_CannotSetTimeError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCAClock_CannotSetTimeError"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCAClock_CannotSetTimeError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCAClock_CannotSetTimeError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCAClock_CannotSetTimeError"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_CannotSetTimeError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAClock_CannotSetTimeError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_CannotSetTimeError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClock_CannotSetTimeError"
        }
      ],
      "role": "symbol",
      "title": "kCAClock_CannotSetTimeError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaclock_cannotsettimeerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidPlayRateError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAClock_InvalidPlayRateError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidPlayRateError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClock_InvalidPlayRateError"
        }
      ],
      "role": "symbol",
      "title": "kCAClock_InvalidPlayRateError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaclock_invalidplayrateerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidPropertySizeError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAClock_InvalidPropertySizeError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidPropertySizeError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClock_InvalidPropertySizeError"
        }
      ],
      "role": "symbol",
      "title": "kCAClock_InvalidPropertySizeError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaclock_invalidpropertysizeerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidSMPTEFormatError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAClock_InvalidSMPTEFormatError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidSMPTEFormatError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClock_InvalidSMPTEFormatError"
        }
      ],
      "role": "symbol",
      "title": "kCAClock_InvalidSMPTEFormatError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaclock_invalidsmpteformaterror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidSMPTEOffsetError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAClock_InvalidSMPTEOffsetError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidSMPTEOffsetError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClock_InvalidSMPTEOffsetError"
        }
      ],
      "role": "symbol",
      "title": "kCAClock_InvalidSMPTEOffsetError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaclock_invalidsmpteoffseterror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidSyncModeError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAClock_InvalidSyncModeError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidSyncModeError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClock_InvalidSyncModeError"
        }
      ],
      "role": "symbol",
      "title": "kCAClock_InvalidSyncModeError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaclock_invalidsyncmodeerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidSyncSourceError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAClock_InvalidSyncSourceError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidSyncSourceError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClock_InvalidSyncSourceError"
        }
      ],
      "role": "symbol",
      "title": "kCAClock_InvalidSyncSourceError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaclock_invalidsyncsourceerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidTimeFormatError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAClock_InvalidTimeFormatError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidTimeFormatError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClock_InvalidTimeFormatError"
        }
      ],
      "role": "symbol",
      "title": "kCAClock_InvalidTimeFormatError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaclock_invalidtimeformaterror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidTimebaseError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAClock_InvalidTimebaseError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidTimebaseError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClock_InvalidTimebaseError"
        }
      ],
      "role": "symbol",
      "title": "kCAClock_InvalidTimebaseError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaclock_invalidtimebaseerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidTimebaseSourceError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAClock_InvalidTimebaseSourceError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidTimebaseSourceError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClock_InvalidTimebaseSourceError"
        }
      ],
      "role": "symbol",
      "title": "kCAClock_InvalidTimebaseSourceError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaclock_invalidtimebasesourceerror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidUnitError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAClock_InvalidUnitError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidUnitError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClock_InvalidUnitError"
        }
      ],
      "role": "symbol",
      "title": "kCAClock_InvalidUnitError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaclock_invaliduniterror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_UnknownPropertyError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAClock_UnknownPropertyError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_UnknownPropertyError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClock_UnknownPropertyError"
        }
      ],
      "role": "symbol",
      "title": "kCAClock_UnknownPropertyError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaclock_unknownpropertyerror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidPlayRateError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidPropertySizeError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidSMPTEFormatError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidSMPTEOffsetError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidSyncModeError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidSyncSourceError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidTimeFormatError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidTimebaseError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidTimebaseSourceError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidUnitError",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_UnknownPropertyError"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCAClock_CannotSetTimeError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClock_CannotSetTimeError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidPlayRateError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidPropertySizeError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidSMPTEFormatError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidSMPTEOffsetError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidSyncModeError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidSyncSourceError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidTimeFormatError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidTimebaseError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidTimebaseSourceError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_InvalidUnitError",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAClock_UnknownPropertyError"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCAClock_CannotSetTimeError"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAClock_InvalidTimebaseError/title",
          "value": "kCAClock_InvalidTimebaseError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAClock_InvalidTimebaseError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClock_InvalidTimebaseError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAClock_UnknownPropertyError/title",
          "value": "kCAClock_UnknownPropertyError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAClock_UnknownPropertyError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClock_UnknownPropertyError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAClock_InvalidSMPTEOffsetError/title",
          "value": "kCAClock_InvalidSMPTEOffsetError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAClock_InvalidSMPTEOffsetError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClock_InvalidSMPTEOffsetError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAClock_InvalidSMPTEFormatError/title",
          "value": "kCAClock_InvalidSMPTEFormatError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAClock_InvalidSMPTEFormatError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClock_InvalidSMPTEFormatError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAClock_InvalidTimebaseSourceError/title",
          "value": "kCAClock_InvalidTimebaseSourceError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAClock_InvalidTimebaseSourceError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClock_InvalidTimebaseSourceError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAClock_InvalidUnitError/title",
          "value": "kCAClock_InvalidUnitError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAClock_InvalidUnitError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClock_InvalidUnitError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAClock_CannotSetTimeError/title",
          "value": "kCAClock_CannotSetTimeError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAClock_CannotSetTimeError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClock_CannotSetTimeError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAClock_InvalidSyncModeError/title",
          "value": "kCAClock_InvalidSyncModeError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAClock_InvalidSyncModeError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClock_InvalidSyncModeError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAClock_InvalidPropertySizeError/title",
          "value": "kCAClock_InvalidPropertySizeError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAClock_InvalidPropertySizeError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClock_InvalidPropertySizeError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAClock_InvalidSyncSourceError/title",
          "value": "kCAClock_InvalidSyncSourceError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAClock_InvalidSyncSourceError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClock_InvalidSyncSourceError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAClock_InvalidTimeFormatError/title",
          "value": "kCAClock_InvalidTimeFormatError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAClock_InvalidTimeFormatError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClock_InvalidTimeFormatError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAClock_InvalidPlayRateError/title",
          "value": "kCAClock_InvalidPlayRateError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAClock_InvalidPlayRateError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClock_InvalidPlayRateError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kcaclock_cannotsettimeerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kcaclock_cannotsettimeerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
