{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_Generic"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kCAFMarkerType_Generic@kCAFMarkerType_Generic",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCAFMarkerType_Generic"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCAFMarkerType_Generic"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCAFMarkerType_Generic"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCAFMarkerType_Generic"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_EditDestinationBegin": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_EditDestinationBegin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_EditDestinationBegin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_EditDestinationBegin"
        }
      ],
      "role": "symbol",
      "title": "kCAFMarkerType_EditDestinationBegin",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcafmarkertype_editdestinationbegin"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_EditDestinationEnd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_EditDestinationEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_EditDestinationEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_EditDestinationEnd"
        }
      ],
      "role": "symbol",
      "title": "kCAFMarkerType_EditDestinationEnd",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcafmarkertype_editdestinationend"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_EditSourceBegin": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_EditSourceBegin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_EditSourceBegin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_EditSourceBegin"
        }
      ],
      "role": "symbol",
      "title": "kCAFMarkerType_EditSourceBegin",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcafmarkertype_editsourcebegin"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_EditSourceEnd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_EditSourceEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_EditSourceEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_EditSourceEnd"
        }
      ],
      "role": "symbol",
      "title": "kCAFMarkerType_EditSourceEnd",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcafmarkertype_editsourceend"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_Generic": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_Generic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_Generic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_Generic"
        }
      ],
      "role": "symbol",
      "title": "kCAFMarkerType_Generic",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcafmarkertype_generic"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_Index": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_Index"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_Index",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_Index"
        }
      ],
      "role": "symbol",
      "title": "kCAFMarkerType_Index",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcafmarkertype_index"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_KeySignature": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_KeySignature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_KeySignature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_KeySignature"
        }
      ],
      "role": "symbol",
      "title": "kCAFMarkerType_KeySignature",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcafmarkertype_keysignature"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_ProgramEnd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_ProgramEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_ProgramEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_ProgramEnd"
        }
      ],
      "role": "symbol",
      "title": "kCAFMarkerType_ProgramEnd",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcafmarkertype_programend"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_ProgramStart": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_ProgramStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_ProgramStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_ProgramStart"
        }
      ],
      "role": "symbol",
      "title": "kCAFMarkerType_ProgramStart",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcafmarkertype_programstart"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_RegionEnd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_RegionEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_RegionEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_RegionEnd"
        }
      ],
      "role": "symbol",
      "title": "kCAFMarkerType_RegionEnd",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcafmarkertype_regionend"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_RegionStart": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_RegionStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_RegionStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_RegionStart"
        }
      ],
      "role": "symbol",
      "title": "kCAFMarkerType_RegionStart",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcafmarkertype_regionstart"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_RegionSyncPoint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_RegionSyncPoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_RegionSyncPoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_RegionSyncPoint"
        }
      ],
      "role": "symbol",
      "title": "kCAFMarkerType_RegionSyncPoint",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcafmarkertype_regionsyncpoint"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_ReleaseLoopEnd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_ReleaseLoopEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_ReleaseLoopEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_ReleaseLoopEnd"
        }
      ],
      "role": "symbol",
      "title": "kCAFMarkerType_ReleaseLoopEnd",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcafmarkertype_releaseloopend"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_ReleaseLoopStart": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_ReleaseLoopStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_ReleaseLoopStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_ReleaseLoopStart"
        }
      ],
      "role": "symbol",
      "title": "kCAFMarkerType_ReleaseLoopStart",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcafmarkertype_releaseloopstart"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_SavedPlayPosition": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_SavedPlayPosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_SavedPlayPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_SavedPlayPosition"
        }
      ],
      "role": "symbol",
      "title": "kCAFMarkerType_SavedPlayPosition",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcafmarkertype_savedplayposition"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_SelectionEnd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_SelectionEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_SelectionEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAFMarkerType_SelectionEnd"
        }
      ],
      "role": "symbol",
      "title": "kCAFMarkerType_SelectionEnd",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcafmarkertype_selectionend"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_EditDestinationBegin",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_EditDestinationEnd",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_EditSourceBegin",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_EditSourceEnd",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_Index",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_KeySignature",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_ProgramEnd",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_ProgramStart",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_RegionEnd",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_RegionStart",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_RegionSyncPoint",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_ReleaseLoopEnd",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_ReleaseLoopStart",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_SavedPlayPosition",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_SelectionEnd"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCAFMarkerType_Generic"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAFMarkerType_Generic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_EditDestinationBegin",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_EditDestinationEnd",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_EditSourceBegin",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_EditSourceEnd",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_Index",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_KeySignature",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_ProgramEnd",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_ProgramStart",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_RegionEnd",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_RegionStart",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_RegionSyncPoint",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_ReleaseLoopEnd",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_ReleaseLoopStart",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_SavedPlayPosition",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAFMarkerType_SelectionEnd"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCAFMarkerType_Generic"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_RegionEnd/title",
          "value": "kCAFMarkerType_RegionEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_RegionEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAFMarkerType_RegionEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_EditSourceEnd/title",
          "value": "kCAFMarkerType_EditSourceEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_EditSourceEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAFMarkerType_EditSourceEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_KeySignature/title",
          "value": "kCAFMarkerType_KeySignature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_KeySignature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAFMarkerType_KeySignature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_ProgramStart/title",
          "value": "kCAFMarkerType_ProgramStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_ProgramStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAFMarkerType_ProgramStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_SelectionEnd/title",
          "value": "kCAFMarkerType_SelectionEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_SelectionEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAFMarkerType_SelectionEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_EditSourceBegin/title",
          "value": "kCAFMarkerType_EditSourceBegin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_EditSourceBegin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAFMarkerType_EditSourceBegin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_RegionStart/title",
          "value": "kCAFMarkerType_RegionStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_RegionStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAFMarkerType_RegionStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_ReleaseLoopStart/title",
          "value": "kCAFMarkerType_ReleaseLoopStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_ReleaseLoopStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAFMarkerType_ReleaseLoopStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_RegionSyncPoint/title",
          "value": "kCAFMarkerType_RegionSyncPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_RegionSyncPoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAFMarkerType_RegionSyncPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_ProgramEnd/title",
          "value": "kCAFMarkerType_ProgramEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_ProgramEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAFMarkerType_ProgramEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_EditDestinationEnd/title",
          "value": "kCAFMarkerType_EditDestinationEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_EditDestinationEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAFMarkerType_EditDestinationEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_Generic/title",
          "value": "kCAFMarkerType_Generic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_Generic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAFMarkerType_Generic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_Index/title",
          "value": "kCAFMarkerType_Index"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_Index/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAFMarkerType_Index"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_SavedPlayPosition/title",
          "value": "kCAFMarkerType_SavedPlayPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_SavedPlayPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAFMarkerType_SavedPlayPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_ReleaseLoopEnd/title",
          "value": "kCAFMarkerType_ReleaseLoopEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_ReleaseLoopEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAFMarkerType_ReleaseLoopEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_EditDestinationBegin/title",
          "value": "kCAFMarkerType_EditDestinationBegin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAFMarkerType_EditDestinationBegin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAFMarkerType_EditDestinationBegin"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kcafmarkertype_generic"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kcafmarkertype_generic"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
