{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType30"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kCAF_SMPTE_TimeTypeNone@kCAF_SMPTE_TimeType30",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCAF_SMPTE_TimeType30"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCAF_SMPTE_TimeType30"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCAF_SMPTE_TimeType30"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCAF_SMPTE_TimeType30"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType2398": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType2398"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType2398",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType2398"
        }
      ],
      "role": "symbol",
      "title": "kCAF_SMPTE_TimeType2398",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_smpte_timetype2398"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType24": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType24"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType24",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType24"
        }
      ],
      "role": "symbol",
      "title": "kCAF_SMPTE_TimeType24",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_smpte_timetype24"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType25": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType25"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType25",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType25"
        }
      ],
      "role": "symbol",
      "title": "kCAF_SMPTE_TimeType25",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_smpte_timetype25"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType2997": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType2997"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType2997",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType2997"
        }
      ],
      "role": "symbol",
      "title": "kCAF_SMPTE_TimeType2997",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_smpte_timetype2997"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType2997Drop": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType2997Drop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType2997Drop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType2997Drop"
        }
      ],
      "role": "symbol",
      "title": "kCAF_SMPTE_TimeType2997Drop",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_smpte_timetype2997drop"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType30": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType30"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType30",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType30"
        }
      ],
      "role": "symbol",
      "title": "kCAF_SMPTE_TimeType30",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_smpte_timetype30"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType30Drop": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType30Drop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType30Drop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType30Drop"
        }
      ],
      "role": "symbol",
      "title": "kCAF_SMPTE_TimeType30Drop",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_smpte_timetype30drop"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType50": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType50"
        }
      ],
      "role": "symbol",
      "title": "kCAF_SMPTE_TimeType50",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_smpte_timetype50"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType5994": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType5994"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType5994",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType5994"
        }
      ],
      "role": "symbol",
      "title": "kCAF_SMPTE_TimeType5994",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_smpte_timetype5994"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType5994Drop": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType5994Drop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType5994Drop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType5994Drop"
        }
      ],
      "role": "symbol",
      "title": "kCAF_SMPTE_TimeType5994Drop",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_smpte_timetype5994drop"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType60": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType60"
        }
      ],
      "role": "symbol",
      "title": "kCAF_SMPTE_TimeType60",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_smpte_timetype60"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType60Drop": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType60Drop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType60Drop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeType60Drop"
        }
      ],
      "role": "symbol",
      "title": "kCAF_SMPTE_TimeType60Drop",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_smpte_timetype60drop"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeTypeNone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeTypeNone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeTypeNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_SMPTE_TimeTypeNone"
        }
      ],
      "role": "symbol",
      "title": "kCAF_SMPTE_TimeTypeNone",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_smpte_timetypenone"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType2398",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType24",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType25",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType2997",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType2997Drop",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType30Drop",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType50",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType5994",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType5994Drop",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType60",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType60Drop",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeTypeNone"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCAF_SMPTE_TimeType30"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_SMPTE_TimeType30"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType2398",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType24",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType25",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType2997",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType2997Drop",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType30Drop",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType50",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType5994",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType5994Drop",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType60",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeType60Drop",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_SMPTE_TimeTypeNone"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCAF_SMPTE_TimeType30"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType24/title",
          "value": "kCAF_SMPTE_TimeType24"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType24/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_SMPTE_TimeType24"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType2398/title",
          "value": "kCAF_SMPTE_TimeType2398"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType2398/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_SMPTE_TimeType2398"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType60/title",
          "value": "kCAF_SMPTE_TimeType60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_SMPTE_TimeType60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType30/title",
          "value": "kCAF_SMPTE_TimeType30"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType30/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_SMPTE_TimeType30"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType60Drop/title",
          "value": "kCAF_SMPTE_TimeType60Drop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType60Drop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_SMPTE_TimeType60Drop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType25/title",
          "value": "kCAF_SMPTE_TimeType25"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType25/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_SMPTE_TimeType25"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType5994/title",
          "value": "kCAF_SMPTE_TimeType5994"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType5994/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_SMPTE_TimeType5994"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType2997Drop/title",
          "value": "kCAF_SMPTE_TimeType2997Drop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType2997Drop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_SMPTE_TimeType2997Drop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeTypeNone/title",
          "value": "kCAF_SMPTE_TimeTypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeTypeNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_SMPTE_TimeTypeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType2997/title",
          "value": "kCAF_SMPTE_TimeType2997"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType2997/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_SMPTE_TimeType2997"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType30Drop/title",
          "value": "kCAF_SMPTE_TimeType30Drop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType30Drop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_SMPTE_TimeType30Drop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType5994Drop/title",
          "value": "kCAF_SMPTE_TimeType5994Drop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType5994Drop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_SMPTE_TimeType5994Drop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType50/title",
          "value": "kCAF_SMPTE_TimeType50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_SMPTE_TimeType50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_SMPTE_TimeType50"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kcaf_smpte_timetype30"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kcaf_smpte_timetype30"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
