{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_InfoStringsChunkID"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kCAF_StreamDescriptionChunkID@kCAF_InfoStringsChunkID",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCAF_InfoStringsChunkID"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCAF_InfoStringsChunkID"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCAF_InfoStringsChunkID"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCAF_InfoStringsChunkID"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_AudioDataChunkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_AudioDataChunkID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_AudioDataChunkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_AudioDataChunkID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_AudioDataChunkID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_audiodatachunkid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_ChannelLayoutChunkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_ChannelLayoutChunkID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_ChannelLayoutChunkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_ChannelLayoutChunkID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_ChannelLayoutChunkID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_channellayoutchunkid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_EditCommentsChunkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_EditCommentsChunkID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_EditCommentsChunkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_EditCommentsChunkID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_EditCommentsChunkID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_editcommentschunkid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_FillerChunkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_FillerChunkID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_FillerChunkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_FillerChunkID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_FillerChunkID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_fillerchunkid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_FormatListID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_FormatListID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_FormatListID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_FormatListID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_FormatListID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_formatlistid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_InfoStringsChunkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_InfoStringsChunkID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_InfoStringsChunkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_InfoStringsChunkID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_InfoStringsChunkID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_infostringschunkid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_InstrumentChunkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_InstrumentChunkID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_InstrumentChunkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_InstrumentChunkID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_InstrumentChunkID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_instrumentchunkid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_MIDIChunkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_MIDIChunkID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_MIDIChunkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_MIDIChunkID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_MIDIChunkID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_midichunkid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_MagicCookieID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_MagicCookieID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_MagicCookieID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_MagicCookieID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_MagicCookieID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_magiccookieid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_MarkerChunkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_MarkerChunkID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_MarkerChunkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_MarkerChunkID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_MarkerChunkID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_markerchunkid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_OverviewChunkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_OverviewChunkID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_OverviewChunkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_OverviewChunkID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_OverviewChunkID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_overviewchunkid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_PacketTableChunkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_PacketTableChunkID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_PacketTableChunkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_PacketTableChunkID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_PacketTableChunkID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_packettablechunkid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_PeakChunkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_PeakChunkID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_PeakChunkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_PeakChunkID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_PeakChunkID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_peakchunkid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_RegionChunkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_RegionChunkID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_RegionChunkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_RegionChunkID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_RegionChunkID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_regionchunkid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_StreamDescriptionChunkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_StreamDescriptionChunkID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_StreamDescriptionChunkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_StreamDescriptionChunkID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_StreamDescriptionChunkID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_streamdescriptionchunkid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_StringsChunkID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCAF_StringsChunkID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_StringsChunkID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAF_StringsChunkID"
        }
      ],
      "role": "symbol",
      "title": "kCAF_StringsChunkID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kcaf_stringschunkid"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_AudioDataChunkID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_ChannelLayoutChunkID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_EditCommentsChunkID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_FillerChunkID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_FormatListID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_InstrumentChunkID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_MIDIChunkID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_MagicCookieID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_MarkerChunkID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_OverviewChunkID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_PacketTableChunkID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_PeakChunkID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_RegionChunkID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_StreamDescriptionChunkID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_StringsChunkID"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCAF_InfoStringsChunkID"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_InfoStringsChunkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_AudioDataChunkID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_ChannelLayoutChunkID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_EditCommentsChunkID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_FillerChunkID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_FormatListID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_InstrumentChunkID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_MIDIChunkID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_MagicCookieID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_MarkerChunkID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_OverviewChunkID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_PacketTableChunkID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_PeakChunkID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_RegionChunkID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_StreamDescriptionChunkID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kCAF_StringsChunkID"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCAF_InfoStringsChunkID"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_FillerChunkID/title",
          "value": "kCAF_FillerChunkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_FillerChunkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_FillerChunkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_InstrumentChunkID/title",
          "value": "kCAF_InstrumentChunkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_InstrumentChunkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_InstrumentChunkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_InfoStringsChunkID/title",
          "value": "kCAF_InfoStringsChunkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_InfoStringsChunkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_InfoStringsChunkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_StreamDescriptionChunkID/title",
          "value": "kCAF_StreamDescriptionChunkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_StreamDescriptionChunkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_StreamDescriptionChunkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_MagicCookieID/title",
          "value": "kCAF_MagicCookieID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_MagicCookieID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_MagicCookieID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_PacketTableChunkID/title",
          "value": "kCAF_PacketTableChunkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_PacketTableChunkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_PacketTableChunkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_OverviewChunkID/title",
          "value": "kCAF_OverviewChunkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_OverviewChunkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_OverviewChunkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_AudioDataChunkID/title",
          "value": "kCAF_AudioDataChunkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_AudioDataChunkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_AudioDataChunkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_EditCommentsChunkID/title",
          "value": "kCAF_EditCommentsChunkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_EditCommentsChunkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_EditCommentsChunkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_MarkerChunkID/title",
          "value": "kCAF_MarkerChunkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_MarkerChunkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_MarkerChunkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_StringsChunkID/title",
          "value": "kCAF_StringsChunkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_StringsChunkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_StringsChunkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_RegionChunkID/title",
          "value": "kCAF_RegionChunkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_RegionChunkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_RegionChunkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_FormatListID/title",
          "value": "kCAF_FormatListID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_FormatListID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_FormatListID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_MIDIChunkID/title",
          "value": "kCAF_MIDIChunkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_MIDIChunkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_MIDIChunkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_ChannelLayoutChunkID/title",
          "value": "kCAF_ChannelLayoutChunkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_ChannelLayoutChunkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_ChannelLayoutChunkID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_PeakChunkID/title",
          "value": "kCAF_PeakChunkID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kCAF_PeakChunkID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAF_PeakChunkID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kcaf_infostringschunkid"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kcaf_infostringschunkid"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
